### ISSUE TITLE
[BOOM-2689] Combination generator in PS 1.7

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#10035]
This issue has been migrated from the Forge. Read the original ticket [here](http://forge.prestashop.com/browse/BOOM-2689).

**Describe the bug**
Hello.
In prestashop 1.7 the combinations have been simplified, but, when you need to generate a large number of combinations with different prices and price increases, how can you manage this without having to modify one by one? For example, a sofa with several measures in which it increases the price, textures, and several combinations that also carry their corresponding increase, how do I manage this? Prestashop 1.6 gave us the option to do it easily, and Ps1.7 did not? Attached 2 images. One of Ps1.6 and another of another product in ps1.7.
I know you have the option of mass actions, but once you have already generated all the combinations, therefore you have to go selecting the different combinations and calculating prices manually. Ps 1.6 performed this automatically. Attached images

![ejemplo-prestashop16](https://user-images.githubusercontent.com/13449658/63530838-8ea2fd00-c507-11e9-981d-80d7746a0d0f.jpeg)

![exampleps16](https://user-images.githubusercontent.com/13449658/63530844-919ded80-c507-11e9-985b-0945f19fdde4.jpg)

![Ejemplo-prestashop17](https://user-images.githubusercontent.com/13449658/63530853-94004780-c507-11e9-846a-118f1808e176.jpeg)

![exampleps17](https://user-images.githubusercontent.com/13449658/63530856-96fb3800-c507-11e9-9ba6-18ddda7ed417.jpg)

**Comment by holle75** [comment]
Hello Guys, mmh, installed 1.7.5, spent 2 month to get it going, fixed bugs, was wondering about missing features ....
Well, now i started to setup my products. Coming from 1.5/1.6 i spent a whole day trying to figure out how to NOT manually insert impact on price with eg 512 product combinations. Thought i´m probably to dumb to find the right way. But no, it´s not possible!

Presta 1.7.x without this possibility is not usable. So, this definitely is not a Feature as marked, its a necessity!
When will this "feature" been re-integrated from 1.6? I can´t use my Shop at all without being able to create my products. Or anyone have a hint for any workaround?

**Comment by marionf** [comment]
@holle75 

>  i spent a whole day trying to figure out how to NOT manually insert impact on price with eg 512 product combinations. Thought i´m probably to dumb to find the right way. But no, it´s not possible!

You can define impact on the price in bulk action, please look at the screenshot below:

![capture d ecran_966](https://user-images.githubusercontent.com/13449658/52202746-b5e9f380-286f-11e9-9249-c8c1e7746a65.png)

**Comment by holle75** [comment]
@marionf thank you for your quick reply. As i mentioned

"NOT manually"

How can you update impact on price (or weight) this way if you have 500+ combinations? It´s impossible.... or you spend 24 hours with just this one product.

Simple solution would be to have fields (impact on price/weight + other fields) aside attributes when CREATING combinations.

**Comment by marionf** [comment]
Ok, thank you for these details :+1:

**Comment by SharakPL** [comment]
@holle75 I'm with you on that. Managing combinations is somewhat easier and faster. I especially like how you can cycle through all combinations and bind images to each one with just 1 click. Although images are definitely too big for that which forces you to scroll down and slows whole proccess.
Unfortunately I must say that combinations were ruined since 1.6. Setting up impact of each attribute included in a combination **is a must**. Prestashop 1.7 only offers setting impact of whole combination. There still is `ps_attribute_impact` table in database but it seems it isn't used at all. In 1.6 I could have 10 attributes and to show my clients impact of each attribute on product price I could just retrieve it from the variable. Now in 1.7 I have to make 100 different attributes instead and put price impact in the name 😫 And that's just with 1 currency used! Not to mention cost of the multiple attributes combination has to be calculated manually + in most cases stripped from tax as this is the value price field requires.

Please, bring back proper attribute impact on the price 🙏 

Weight isn't something used very often on prestashop so I suppose this could stay related to combination only and not to each attribute.

**Comment by holle75** [comment]
Yes SharakPL you´re right. At least "impact on price" defined during creation of the combinations is an absolute necessity. Every additional field would be highly appreciated, but is, as marked, a feature ;)

**Comment by SharakPL** [comment]
Another BUG/required feature is that when some combinations are already generated then all used attributes with values should be always present in input `#form_step3_attributes-tokenfield`. Now it's empty so adding another attribute and clicking Generate makes not only useless combination just with this new attribute but also breaks the others and none of them is loaded on the product page!

You would think if I add again the same attributes and values I used before and just add another one then everything would be fine and you would update existing combinations. Wrong! You still get bunch of completely new combinations so if you had any impact prices already set then you're screwed and have to make those all over again. You simply can't update existing combinations with new attributes. You're forced to remove all of them and generate everything again.

It's really messed up at the moment. It shouldn't be marked as a Feature but as a Critical Bug :/

**Comment by marionf** [comment]
Related to: #11652

**Comment by SharakPL** [comment]
> 
> 
> @marionf thank you for your quick reply. As i mentioned
> 
>
> How can you update impact on price (or weight) this way if you have 500+ combinations? It´s impossible.... or you spend 24 hours with just this one product.
> 
Have you managed to update this kind of product? I've just got 512 combinations. Created with no problems but there's simply no way to edit anything then. I get an error with information that I need to increase `max_input_vars` in php.ini to **13.000!!!** 😲 Whole 1.6.x translation form required 3000. My server has a limit of 10.000 so once again I'm screwed :/ Probably using just 1 language on my store instead of 2 would drop this requirement a bit, but it's still unusable with more combinations. Not to mention I have to count 511 impact prices one by one and it's just 1 product :/

**Comment by holle75** [comment]
I found a module which is doing that. Still hesitating to pay ~40,- for such a core functionality. Simply put, Presta for more than lets say 100 combinations, without paying an extra module, is unusable. Or you love to spent your lifetime with saving updates to the price/weight manually. Every time i´m saving this product (it´s just a testproduct with 512 combinations cause i can´t use it without spending those 24 hours adjusting prices) i´m waiting around 1 minute.... sometimes i get a refusal to save. Be aware, the module is just using the core Combination-Generator from Presta. It kind of just gives you the interface Presta should give you. So it doesn´t help with your Server/Presta limitations. Module is called "Bulk combinations generator". Haven´t bought it yet. Thinking about switching to another shop. To many flaws in 1.7.5.... Translations (still trying to figure out who could come up with the idea to hide your translations in different categories so you spend hours to find the line you are searching for), Quality of emails, speed, you could go on ... a big mess .... wait for the moment you start to set up your shop for EU-Law (who the f#** created a EU-Law module which is able to attach millions of pages of legal text to emails but never had the idea to add a button to attach those pages as pdf? Well, probably this is a feature and not a necessity. I heard you can buy a module for that) or creating invoices (needed Taxnumbers and fields in different countries..., merchant from another EU or foreign country wants to order, VAT management) ... you gonna start screaming and wailing. Unfortunately already bought a Theme for Presta and invested around 9 weeks in setting up everything. This shop is not usable without paying a programmer and/or investing a hell lot of time. 

I freshly came back to presta. Last shop i set up was 1.5.6. Haven´t touched presta for a long time. Should have kept it this way. It seems that during those years (1.5 -> 1.7) it just became worse, not better (well, the BO seems much more fancy). AND I´M SORRY to put my frustration in written form. I know it´s free. I know programmers are under pressure. I know probably somebody else is deciding where you have to spend your time or with what .... but probably somebody else than this decision-maker now should be in charge of that. SORRY, SORRY, SORRY i know this is not constructive....

**Comment by MasterEmit** [comment]
Its sad to read, that this problem still exists. I planed to upgrade to 1.7 from 1.6. For 1.6 I bought Attribute Wizard Pro, which solved this issue for me (combinations can be 64 x 64 x 64 x 5. So you can guess, that just creating entries for each possible combination in the database is killing the system. I understand, that for products I buy and just sell its often fine enough - but for manufacturing products where customers are able to modify them the way is not working.
My bigest problem with Attribute Wizard Pro: I have to modify core files and I hate that. It makes it often unpossible to run updates.

**Comment by dtamajon** [comment]
Here is my proposal:

One solution would be to have an attribute filter on combinations, so we can select all the items filtered.  That would allow an ease mark on desired items to edit all them. I think it would be the easier solution on current version.

Also, I would like to have a default price + weight on each attribute, so it is aggregated automatically on generating combinations. In that case, we should be able to update all calculated combinations if default price is updated at any time. Of course, the update should be offered for all products (an explicit update button), or just go to the product and update only just combinations for that product.

And, just to add some additional feature, it should include volume also. In some cases, products are shipped by volume because weight is very low but with a high volume.

Additionally, we should think in a way to manage combinations as an array to avoid the explosion of input_vars... but this would require a harder work, but probably it worths.

**Comment by babyewok** [comment]
Is there still no solution offered by PS for this? It is a very basic requirement and I have no idea why they would strip this functionality from 1.7! It is a nightmare to have to calculate and then enter the combination prices. It was much easier when you could simply enter the attribute price impact and then the combination prices were calculated automatically.

I can't even find any suitable add-ons to add this functionality.

**Comment by SharakPL** [comment]
@babyewok Attribute Wizard Pro is the module you're looking for. Prestashop's default idea of managing combinations is pretty much useless and would be even if there was automatic price calculation. It needs to be redesigned to work like AWP...

**Comment by MatShir** [comment]
Done on the new product on PS 8.1 ;)
You can filter product combination by attributes and bulk edit them.
I suggest opening a new issue for new optimization on the new product page.
