### ISSUE TITLE
One click upgrade 1.7.3 to 1.7.4 error

### ISSUE THREAD

**Issue by cdpi404** [PrestaShop/PrestaShop#10176]
**Describe the bug**
I want to upgrade my prestashop to 1.7.4 from 1.7.3 with the module one click upgrade but when i want to proceed i've a prestashop error, when i click on "view more" it's says that the file "robot.txt" as been modified but i've never edited it.

**Screenshots**
https://imgur.com/a/fzTP3SJ

**Additionnal information**
PrestaShop version: 1.7.3
PHP version: 7.0.31

**Comment by khouloudbelguith** [comment]
Hi @cdpi404,

It seems that a description is missing, and that's why it could not be listed in the "following errors". 
Here's the PR about that issue in https://github.com/PrestaShop/PrestaShop/pull/9407.
If you're confident in modifying the core files manually, you can apply the changes to show the test in failure.

Best regards, Khouloud

**Comment by cdpi404** [comment]
Hello,

I've checked the thread but not found something usefull :/

**Comment by khouloudbelguith** [comment]
Hi @cdpi404,

You need to navigate to your PROJECT_FOLDER/public_html/themes/YourTheme
There you see a folder named "cache". Change file permissions of "cache" folder to 0711.
Thanks to check & feedback.

Best regards, Khouloud

**Comment by cdpi404** [comment]
Hi,

It's worked :D problem solved thank you

Best regards

**Comment by khouloudbelguith** [comment]
Hi @cdpi404,

Thanks for your feedback.
I close the ticket, feel free to open a new issue when needed.

Best regards, Khouloud
