### ISSUE TITLE
Can't access backoffice anymore 

### ISSUE THREAD

**Issue by Constances869** [PrestaShop/PrestaShop#10180]
I was working on a a website for weeks and while I was doing some changes, I just got log out of the back office. Since then, I can't login!! Every time I try this error appears: "**This employee account does not exist, or the password is wrong**". 
Prestashop is install on my local server (UWamp), and in Php MyAdmin, I still appear as the only employee.
In Prestashop documentation, they say we can change the password manually in _/config/settings.inc.php_ but this file is actually empty....

Please help me!

**Comment by khouloudbelguith** [comment]
hI @Constances869,

Have you tried to recover the password of this employee?
What is the exact version of Prestashop did you use?

Best regards, Khouloud

**Comment by Constances869** [comment]
@khouloudbelguith Yes I've tried but it won't work ("An error occurred while resetting the password.")

**Comment by khouloudbelguith** [comment]
Hi @Constances869,

What is the exact version of Prestashop did you use?

Best regards, Khouloud

**Comment by Constances869** [comment]
I'm using prestashop version1.7.4.2

**Comment by khouloudbelguith** [comment]
Hi @Constances869,

There are multiple ways to reset the admin password for PrestaShop. One particular method "How to Reset the PrestaShop Administrator Password for PS 1.6" is no longer feasible if you are running version 1.7. This is due to the fact that PrestaShop has deprecated the config/settings.inc.php file. This file was necessary to retrieve the COOKIE_KEY required for resetting the admin password. The file may still exist, however, this screenshot shows the deprecated version's content:
![image](https://user-images.githubusercontent.com/16067358/44780245-cd66d700-ab81-11e8-95f1-94cdd604ac83.png)
As you can see, the file no longer contains the data needed to follow the old method. However, the following steps can be taken to reset the admin password.
### Reset the Admin Password for PrestaShop 1.7

1. First, navigate to your PrestaShop's Front Officelogin page.
2. Click on the "Sign In" link, located in the upper right-hand corner.
3. Click on the "No account? Create one here" link.
4. After you will in the required fields (first name, last name, email, and password), click SAVE. Be sure to make note of the password you are using, you will end up using this password to login as the admin.
5. Open up phpMyAdmin and navigate to the database for your Prestashop installation.
6. Open the ps_customer table and look for the user you just created.
7. Copy the password field.
8. Open the ps_employee table and look for your admin user.
9. Paste the password you copied from the ps_customer table into the password field of the ps_employee for your admin user.
10. Click Go to save your changes.
11. Navigate to your PrestaShop admin login URL. Test your login to confirm the email address and password are combination work.

Thanks to check and feedback.

Best regards, Khouloud

**Comment by Constances869** [comment]
Yeah it works! Thank you
Have a nice day ;)

**Comment by khouloudbelguith** [comment]
Hi @Constances869,

You are welcome.
Thanks for your feedback.

Best regards, Khouloud
