### ISSUE TITLE
Integrate Webp support

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#10356]
I think it's a good idea to add support of webp images because having a better compression algorithm will help deceasing page load time.

---
Edited on November 16th, following https://github.com/PrestaShop/PrestaShop/issues/10356#issuecomment-728127438:

**Describe the solution you'd like:**

1. Add WebP as a supported image format.
2. Define its MIME type in ImageManager.
3. Allow the upload of WebP images.

**Specifications:**

https://github.com/PrestaShop/prestashop-specs/pull/179

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

Thanks for your report.
Yes, the webp is not supported by Prestashop.
![image](https://user-images.githubusercontent.com/16067358/45288632-6fc07c00-b4eb-11e8-8ec4-88f66508784b.png)
@eternoendless what do you think, can we integrate this image format?

Best regards, Khouloud

**Comment by rdy4ever** [comment]
Well, according to caniuse, webp has a very poor [browser support](https://caniuse.com/#feat=webp) right now. So using webp images would mean: 
- no images in any IE version
- no images in any Edge version
- no images in any Firefox version
- no images in any Safari version
- no images in any iOS Safari browser

So, if you ask me webp in not ready for production yet. 
It could be done but it would mean more than just allowing webp images: it would require a system to convert webp in jpg and serve the jpg's to the browsers that do not support webp. But I really can't see that in the near future of Prestashop, as other urgent issuses are yet to be solved,

**Comment by darkf3d3** [comment]
I know that webp it's supported by few browsers, but Chrome as nearly 60% of browser market share.
For sure this will require a lot of work to be implemented in the correct way, but i think that's a good idea to do this because since Google pay a lot of attenction to website performance, and this could help Prestashop websites to obtain improvements in SEO.

**Comment by mortenhartvig** [comment]
> I think it's a good idea to add support of webp images because having a better compression algorithm the will help deceasing page load time.

I have success using webp images (created with mod_pagespeed - apache module). Although i had issues with the existing Prestashop .htaccess files. - see my #11423

**Comment by mortenhartvig** [comment]
@rdy4ever - Thats why you would use something like mod_pagespeed for the next few years, that handles exactly that problem (by sending webp only when supported) :)

**Comment by khouloudbelguith** [comment]
Hi @mortenhartvig,

The mod_pagespeed is enabled.
In the product page, when I try to upload an image, I have an exception
I attached a video record.
https://drive.google.com/file/d/1IQsYO1jWOUynEJAfQVjV-Zshoi2RMEgc/view
Thanks!

**Comment by mortenhartvig** [comment]
@khouloudbelguith Thanks for the update.

Maybe the issue you showed has something to do with the "fileType" file being present in some folders (that has to be allowed too). 

We have looked at our mod_pagespeed integration with Prestashop 1.7.x in general. There are some weird behavior for images (even when i changed the .htaccess files), where image resources sometimes returns as a 404 (it looks like it happends when the internal cache between mod_pagespeed and apache invalidates. I think its about 10 or 15 minutes after the first cache hit, then it stops working), even though the files do exist in the filesystem (the local mod_pagespeed temp folder). 

If i disable the rewrite_images filter (still having mod_pagespeed on), and hit the URI of the missing image up directly (that previously returned a 404), the image shows just fine as the webp resource it was. 

Didn't look further into it, as we went for a quick fix up to Black friday. The temporary/permanent sollution, was to just use Cloudflare to cache/CDN all our assets. Although, this is not as fast, as having the images rewritten from mod_pagespeed. Would love to use both simultaneously in production, so at some point i will look further into this.

I believe the issue has something to do with the rewriterules in the root .htaccess file for images in general, but im not entirely sure (because i have it working for other small projects other than Prestashop). 

.htaccess is just hard to debug:/

**Comment by khouloudbelguith** [comment]
Hi @mortenhartvig,

Thanks for your feedback & your fix solution.

**Comment by colinegin** [comment]
What do you think of this idea @eternoendless @PrestaShop/prestashop-core-developers ?
Could it help improve load time and SEO ?

**Comment by PierreRambaud** [comment]
Agreed to add webp, even if it is not use or available everywhere, we must add the capability to support this type!

**Comment by jolelievre** [comment]
Then maybe we should add a warning when someone uploads a webp file, to inform the user that this format is not supported by every browsers.

**Comment by eternoendless** [comment]
Webp is supported by the GD library so adding support for it shouldn't be too complicated.

**Comment by colinegin** [comment]
But does it improve in any way SEO and / or load time ?

**Comment by eternoendless** [comment]
It could improve load time because it's more efficient in compressing images. As far as I know, this improvement would be most noticeable when compared to animated GIFs. 

While it's a nice to have, it's probable that impact would be marginal at best.

**Comment by colinegin** [comment]
Ok thanks for the clarification @eternoendless !

**Comment by darkf3d3** [comment]
Actually also Edge and Firefox added webp support that now it's supported 74.3% globally (source: caniuse.com).

**Comment by ghost** [comment]
Agree. WebP is needed in order to increase page speed and Google Speed Insights test. Its the future, and technology pushed by Google itself

**Comment by ghost** [comment]
Here is reason
https://teltonika.lt/products/rutx09/images/rutx09-1.png (79,1 KB) vs. https://teltonika.lt/products/rutx09/images/rutx09-1.webp (28,8 KB) in the same size

**Comment by ghost** [comment]
Bump

**Comment by mrsuchy** [comment]
What is the situation with WebP?

**Comment by PierreRambaud** [comment]
> What is the situation with WebP?

It's still in todo, feel free to create a pull request to support it :)

**Comment by LouiseBonnard** [comment]
@Progi1984 and I discussed this morning the possibility to add the WebP image format to PrestaShop. We decided to focus on all images upload available in the back office, except for the favicon and the mail/invoice logos in the Design > Theme & Logo page.

Why? First, because favicons are a specific case using precise image formats and then because email/invoice logos are meant to be sent by email/PDF documents and the email/PDF support for WebP images is way too limited for now.

<img width="1342" alt="Capture d’écran 2020-11-16 à 16 01 37" src="https://user-images.githubusercontent.com/32565890/99269392-9c3c5500-2826-11eb-84d1-b1cc0ec88f5e.png">

So here are the identified steps to offer WebP support in PrestaShop:

1. Add **WebP as a supported** image format.
2. **Define its MIME type** in ImageManager.
3. **Allow the upload** of WebP images.

**Comment by rblaurin** [comment]
I think it is a great improvement, but it would be mandatory to have an automatic fallback to jpg for unsupported browsers (Safari).

**Comment by LouiseBonnard** [comment]
@rblaurin, Safari 14 now supports WebP images. ;-)

https://developer.apple.com/documentation/safari-release-notes/safari-14-release-notes

**Comment by rblaurin** [comment]
> @rblaurin, Safari 14 now supports WebP images. ;-)

Great! this makes things easier. I think the fallback is not that mandatory then, but it would be useful for old devices...

**Comment by tswfi** [comment]
So does WIP label mean that someone is already working on this?

I think this also needs a change in the img folder .htaccess rule (at least my tests with pagespeed have not worked with the default rule and for some reason it is not even enough to add webp to the list but requires a larger change to the rule).

**Comment by Progi1984** [comment]
@tswfi Hi, the integration is currently in Work In Progress. It will be integrated in develop in a few weeks.

**Comment by tswfi** [comment]
@Progi1984 Thanks! Do you happend to know if the img folder .htaccess compatibility with mod_pagespeed is on the scope also?

**Comment by fdonnet** [comment]
hi, I implemented it on my side https://github.com/fdonnet/PrestaShop-Webp-QuickAnd ... it's not perfect but if it gives you some ideas, thats great.
- Create a new folder imgwebp in prestashop root
- Httaccess with webp support (in imgwebp folder)
- Each night run a script to convert all jpg to webp (can be run when you upolad an img too => imagemagik etc)
- Fallback from webp 404 to jpeg 
- Override Prestashop global httaccess generation method and include webp redirection (+ cache etc)... 
- Very transparent... works exactly as normal images but redirected to imgwebp folder... (same url structure)

It is easy and it works well... ex : for all product miniature images => picture tag + fall back to jpeg if 404 on webp.

Clearly it's a homemade solution but Google Page Speed test is happy.

For the moment, I didn't take care on side effects. => on product page the img tag is used in JS method so if you remplace it by a picture tag it will not work.

**Comment by Hlavtox** [comment]
This needs to be done carefully using `<picture>` with proper fallback sources for older browsers.

**Comment by lmeyer1** [comment]
@MatShir You removed this from the 1.7.8.0 milestone. Does this mean it will not be done before 1.7.9.0 and thus not before 2022?

**Comment by MatShir** [comment]
@lmeyer1 we didn't have enough resources and time to finish the PR unfortunately. We hope to integrate it in 1.7.9.0

**Comment by lmeyer1** [comment]
I understand, it is a highly complex problem, that affects everything from importing images, backoffice, .htaccess, templates, device screen resolution and more.
I implemented this all on my side, but unfortunately, it is a solution that might break backwards compatibility and cannot be easily generalized.

**Comment by lmeyer1** [comment]
More related features, that were not yet mentioned:

- For now all files are saved with an extension `.jpg`, either with the original file format (gif/ jpg/ png), everything in jpg or everything in png format, according to the setting *Image format* in *Design - Image Settings*. To optimize the space used, it would make sense to save all images in webp format. => Add an fourth option to *Image format*: *Use webp for all images*
- Instead of converting files from webp to png format on save time, convert them on demand using .htaccess and a conversion script.
- Make full use of the `<picture>` tag: 
    - fallback from webp to png or jpg for old browsers
    - using the `sizes` and `scrset` attributes, we can let the browser determine which size of the image is the best. This will eliminate the need of high resolution images for higher device pixel ratios.
  
   This would require changes to the template to be fully exploitable.
- Instead of having a set of arbitrary predefined sizes (or sizes adjusted to the template), have many sizes in equal steps => we get an independence from the templates here. I mean, instead of having `home_default`, `small_default` etc., have `@100px`, `@140px`, `@200px`etc.
- For large sizes, instead of adding a white border around the original picture, just symlink the original. This will further reduce the hard disk space needed.
- Not directly related to webp, but a huge disk space and bandwidth saver: optimize pngs using `pngquant` and `optipng`.

**Comment by lmeyer1** [comment]
To fully implement all these features, and keep backwards compatibility, we need to split this up in two parts:

## Part 1: Backoffice 
Add new options for image resizing, that lay a solid foundation for all the improvements mentioned above, while providing 100% BC with default values:
- allow webp as source image format 
- allow to save resized images as transparent png, webp or both
- allow for various optimizations, like browser side resize for images larger than original, crushing pngs and symlinking identical images 

## Part 2: Template 
Most of these features need to be supported by the template to be fully functional. On the other hand they also give more flexibility to template designers. 
- make full use of the `<picture>` tag
   - fallback between webp and png
   - let the browser choose the optimum size from all sizes available 
 - force the browser to enlarge the image when needed (`img` tag with `min-width` or `object-fit: cover` for instance)
 - provide sets of image sizes adapted to `<picture srcset>` (see previous comment) 
 
Flexibility added:
- simplify responsive design 
- no need to detect device pixel ratio, nor to have double resolution versions of images 
- possibility of css background color for transparent images 
- very important bandwidth saving 

I prepare a pull request for part 1.
Part 2 will be up to template designers, but I hope to be able to write a guide for it.

**Comment by nizar0x1f** [comment]
I guess we should wait for v8.0.0

**Comment by Hlavtox** [comment]
@lmeyer1 @Progi1984 Hi guys, if I enable webp using Progi's PR, how will it behave if the browser does not support webp? Is there any fallback? Or how to implement it? (I never worked with it.)

**Comment by tswfi** [comment]
@Hlavtox https://caniuse.com/webp someone should already let IE out of its misery :)

**Comment by Oksydan** [comment]
@tswfi it isn't about IE but safari THB. 
1. Implement suport with `.htaccess` by reading `Vary Accept` but it will not work for websites behind for example cloudflare. 
2. Use `picture` tag but it isn't perfect solution coz it will require template changes everywhere image is being used.

**Comment by tswfi** [comment]
@Oksydan oh right. only glimpsed the page, didn't notice the big sur requirement with safari...

**Comment by Hlavtox** [comment]
Yeah, let IE die, but Safari support is needed. And trust me you don't know what archaic versions of browsers do grandmas run 😄

**Comment by lmeyer1** [comment]
I think that switching to webp requires a change in templates using the `picture` tag. In my opinion this is what it is all about: allowing templates to use webp.

**Comment by Hlavtox** [comment]
Hmmm, but if you enable webp, the jpgs stop generating. PS cannot generate two formats of thumbnails. How to use them in the `picture` tags as a fallback then?

**Comment by lmeyer1** [comment]
Why ? the point is that PS generates always the two formats. Otherwise, we cannot switch to webp, because we need to support all browsers currently in use.

It is not *switching* to webp, but having Prestashop embracing newer and better image formats, while still serving all browsers.

**Comment by Hlavtox** [comment]
How it can generate two formats?
![Výstřižek](https://user-images.githubusercontent.com/6097524/140086921-cdb0b03d-457e-4675-af6b-700376c5a6de.JPG)

**Comment by lmeyer1** [comment]
Look at my PR #24159
It generates BOTH formats. That was the point of my PR and also of this issue IMHO.

**Comment by Hlavtox** [comment]
@lmeyer1 Man I didn't know about your PR, AWESOME THEN! And sorry for misunderstading! 🚀
