### ISSUE TITLE
Combination menu in right side not appears in back office while multi store enabled

### ISSUE THREAD

**Issue by Akashvastarpara** [PrestaShop/PrestaShop#10377]
Hello I'm facing one issue in Prestashop 1.7.4.2, but don't know how can i fix it,
In combination product right side block to choose attributes not appears in back office while I enables multi store. Can we avail this feature for multi-store also.

![combination](https://user-images.githubusercontent.com/40850132/45362393-56562780-b5f2-11e8-850c-794422213db5.png)

**Comment by dineshbadrukhiya** [comment]
Hi @Akashvastarpara 

Thanks for sharing your issue here.
I suggest you to replace below code in /src/PrestaShopBundle/Controller/Admin/ProductController.php file to get shop id instead of 1
$attributeGroups = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('PrestaShopBundle:Attribute')
            ->findByLangAndShop(1,1);

Replace with below code : 
$attributeGroups = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('PrestaShopBundle:Attribute')
            ->findByLangAndShop(1,(int)['shop_id']);

If you are using multi-language then you can also try as below :  
$attributeGroups = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('PrestaShopBundle:Attribute')
            ->findByLangAndShop((int)$languages[0]['id_lang'],(int)['shop_id']);

Thanks.

**Comment by Akashvastarpara** [comment]
Great! I tried it and my combination block is visible now.
Thank you. @dbadrukhiya

**Comment by MathiasReker** [comment]
@dbadrukhiya can you make a PR with your solution?

**Comment by dbadrukhiya** [comment]
Hello @Mreker 
Can you please tell me how to make PR for my solution?

**Comment by dbadrukhiya** [comment]
> 
> 
> @dbadrukhiya can you make a PR with your solution?

Hello @Mreker 
Can you give me advice what I need to improve in my pull request because this is my first pull request.

**Comment by khouloudbelguith** [comment]
Hi @Akashvastarpara,

With the fresh install of 1742, I did not manage to reproduce the issue.
I attached a video record
https://drive.google.com/file/d/1mm55OqNoXq8uTAPof0xyWiQVlgfQ3ICw/view
Thanks to check and feedback.

Best regards, Khouloud

**Comment by TeapotJames** [comment]
@khouloudbelguith The reason you're probably seeing no issue is because you still have the default language enabled. If you already have the demo content installed you should have some attributes and values with the default language (ID 1) in the database.

Try enabling another language (Assigned as ID 2 in the db), changing that one to the default language and then deleting the original language.

Then create some new attributes and values - you should still see the old attributes in the product edit page as they were created using language ID 1 and the $attributeGroups object is hardcoded to use language ID 1.

**Comment by khouloudbelguith** [comment]
Hi @TeapotJames,

Is it the same issue reported here: #9627?

Best regards, Khouloud

**Comment by TeapotJames** [comment]
Hi @khouloudbelguith yes I believe it looks like the same issue. I'm not sure why the language and shop id's have been hardcoded into the file as the ID's aren't always going to be these same.

**Comment by khouloudbelguith** [comment]
Hi @TeapotJames,

So after deleting the language which has id=1, in the Product page => in the list of the attribute, there are values which are missing, but not all the block.

Best regards, Khouloud

**Comment by marionf** [comment]
Duplicate of #9627

**Comment by keithg777** [comment]
thank you very much...save my time
