### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Marg88** [PrestaShop/PrestaShop#10378]
PrestaShop version: 1.7

When I'm on the auto-installer, I have a problem to install my database in Prestashop. I have a database on OVH but I don't know what are good informations to put on the right place on Prestashop. So I can't connect me to the server of my database. It say me that I need to check my connection identifiers. 
I join in attachment informations given by OVH and informations needed by Prestashop.

Can you help me, please ?

Best regards,

Marg

<img width="1625" alt="capture d ecran 2018-09-11 a 17 14 53" src="https://user-images.githubusercontent.com/42941368/45363225-ffe3eb80-b5e7-11e8-981e-21d5bcbced3f.png">
<img width="1188" alt="capture d ecran 2018-09-11 a 17 14 23" src="https://user-images.githubusercontent.com/42941368/45363235-083c2680-b5e8-11e8-9b48-55e098324874.png">

**Comment by MathiasReker** [comment]
Did you try with 'privatesql007' as database name?

**Comment by MathiasReker** [comment]
I don't understand France, but I guess you should not have 'elficstones' in both fields.

**Comment by phulstaert** [comment]
You are trying to connect to the SFTP port. Mysql runs at 35375 and not on your webserver, but on lm292794-001.privatesql. The correct connection string should be lm292794-001.privatesql:35375.
The username you should use should either be send by email when you created this instance or you can set it up under "Utilisateurs et droits". Ask OVH for more information if needed. They are helpful.

**Comment by khouloudbelguith** [comment]
Hi @Marg88,

The Database server address is not correct, in fact, it is the hostname of your MySQL server. It can be tied to your domain name (i.e. http://sql.example.com), tied to your web host (i.e. http://mysql2.alwaysdata.com), or simply be an IP address (i.e. 46.105.78.185).
Your issue is not a PrestaShop's core bug but most likely a server configuration.
If you need help, you can ask on the Forum (https://www.prestashop.com/forums/), Gitter (https://gitter.im/PrestaShop/General) or Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop).
Thanks for your understanding!

Best regards, Khouloud
