### ISSUE TITLE
Display subcategories in FO categories pages

### ISSUE THREAD

**Issue by allyx76** [PrestaShop/PrestaShop#10407]
After updating from 1.7.2.4 to 1.7.4.2 :   
Subcategories don't display at all (none their thumbnails).

**Comment by khouloudbelguith** [comment]
Hi @allyx76,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - screenshots
 -  Are those subcategories not displayed in the FO / BO?

Thanks!

Best regards, Khouloud

**Comment by allyx76** [comment]
Hi Khouloud,

Subcategories don't display in FO.   In 1.7.2.4  They've displayed (with their thumbnails).

For example photo :   buttons
![subcategory](https://user-images.githubusercontent.com/13217405/45437264-c75e1380-b6b4-11e8-8708-51cc869ad05f.jpg)

**Comment by khouloudbelguith** [comment]
Hi @allyx76,

Thanks for your report.
Yes, I manage to reproduce the issue with the last version 1.7.4 / 1.7.3
In the recent release 1.7.2, it seems like this
![image](https://user-images.githubusercontent.com/16067358/45441264-e497df80-b6be-11e8-91f3-7b669998cd92.png)
But in the PS 1.7.3 / 1.7.4, subcategories are not displayed in the ps_categorytree block
![image](https://user-images.githubusercontent.com/16067358/45441311-ff6a5400-b6be-11e8-865d-afff72f5e85e.png)
We will see how to fix it.

Best regards, Khouloud

**Comment by allyx76** [comment]
Great !  thanks a lot.
I am looking forward to the result !

**Comment by khouloudbelguith** [comment]
Hi @allyx76,

About the PS1.7.4, it is not a bug.
![image](https://user-images.githubusercontent.com/16067358/45476607-a262b280-b73f-11e8-84e8-8bf0b9076218.png)
In fact, there are no sub-categories under the men / women categories.
Thanks to check and feedback.

Best regards, Khouloud

**Comment by allyx76** [comment]
Sorry, it is not the problem.

The problem is  : 

- no subcategory under the category title (none thumbnails).
- on personal computer (not on a telephone)
- with 1.7.4.2 version

See my photo :   2 websites  :   
- Above :  old version, subcategories and their thumbnails appear,
- Below :  version 1.7.4.2, on PC computer : no subcategory under Category title


![subcategory](https://user-images.githubusercontent.com/13217405/45484627-13f92b80-b755-11e8-9185-5884caefa119.jpg)


I hope that it's clearer

**Comment by khouloudbelguith** [comment]
Hi @allyx76,

Comparing to the version 1.6, in the category page, there a Subcategories section.
![image](https://user-images.githubusercontent.com/16067358/45485247-2c6a4580-b757-11e8-9172-d55cd838bafa.png)
But in the PS 1.7, this section doesn't exist.
@marion what do you think of this issue?

Best regards, Khouloud

**Comment by allyx76** [comment]
Hello,

Is there a solution now ?

**Comment by khouloudbelguith** [comment]
Hi @allyx76 

Sorry not yet.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open source project, so it can be solved before if someone submits a pull request to solve it.

Best regards, Khouloud

**Comment by marionf** [comment]
@NeOMakinG 
Are you able to do it and if yes, do you need mockups ?

**Comment by NeOMakinG** [comment]
Should be fine without mockups

**Comment by colinegin** [comment]
What do you think of this @TristanLDD @prestascott ? Should we add subcategory blocks like in 1.6 ?

**Comment by prestascott** [comment]
Hi @colinegin,

Imo, we should continue without the subcategories because it adds another click for our users:
1. Click on the category -> only display the different subcategories (like 1.6)
2. Click on the subcategory -> display products of the subcategory
If we add subcategory, users will have to go back to the previous page to switch to another subcategory... 

If we simply add subcategories on top of all the products from the category, it will be too much because users can already filter products to show products from a specific subcategory. 
Also, users can simply click on the subcategory on the left sidebar to get there. 

Some examples: 
- Agatha (Bracelet page): https://www.agatha.fr/bracelets/
- HM (Jean page): https://www2.hm.com/fr_fr/homme/catalogue-par-produit/jeans.html

**Comment by dennispw** [comment]
@prestascott I think this decision should be in the hands of the shop owner and/or theme developers. By all means, disable and hide them by default if that's PrestaShop's stance on the matter but owners and/or theme developers should have the option of enabling it if they want or need to.

Something like `Display subcategories [Yes/No]` where `No` would be the default would suffice.

Just because HM or Agatha, in this case, are not showing them doesn't mean that it's a good practice for every single shop.

**Comment by NeOMakinG** [comment]
Anyway, I think I did it like 6 months ago, so it's up as it was a regression ^^

**Comment by prestascott** [comment]
@dennispw These shops are some of examples, i just explained why it's not the best way to optimize UX on these kind of websites. 

But yes, i agree with you. If we want to cover most of the cases, we should bring back this feature and let merchants have the control on displaying subcategories. 

An example featuring the subcategory:
- Fnac (laptop page): https://www.fnac.com/Ordinateurs-portables/shi48967/w-4#bl=ACInformatiqueARBO

Changed my mind, this feature will be interesting. :)

**Comment by colinegin** [comment]
@NeOMakinG this issue was waiting for UX, it should not have been added without UX approval.
Did you also integrate the feature to choose to display/hide subcategories ?

Thanks !

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/85291754-2b715680-b49b-11ea-82d9-4411f98233ca.png)

You added the waiting for UX and more, 11 days after It has been assigned to me and 4 days after it was already done

And no, I didn't add that feature, it require backend works for it, also it wasn't in place when subcategories where inside the project (as it is a regression)

Basically the only thing I did is porting the work that was before on the project on this version and adjust some style because that was pretty messy

**Comment by colinegin** [comment]
Sorry @NeOMakinG I did not mean to be agressive, I just meant there was a flaw in our product process ;)

Adding subcategories can be a nice feature for some merchants, but i'm not in favour of adding it for everyone. This is why @prestascott has created a new issue so that we can add the option to enable / disable it : #19895.

Thanks !

**Comment by NeOMakinG** [comment]
Np, me too !

Anyway, even if the product team is not in favor of adding it for everyone by default, it was like this before ^^
