### ISSUE TITLE
Some issues in the import page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#10430]
**Describe the bug**
In the import page, we have some issues.
During the installation:
- English language
- France country
![image](https://user-images.githubusercontent.com/16067358/45503199-69016580-b786-11e8-9685-056c188c1916.png)

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by Quetzacoalt91** [comment]
It seems the issues are going to be fixed by @rokaszygmantas with #10120. Unfortunately, this will be for 1.7.6.x.

**Comment by matks** [comment]
We can make it a mandatory requirement for 1.7.5 if necessary and speed up the review process of the related PR

**Comment by marionf** [comment]
Yes, it would be good to fix it as it's a regression :)

**Comment by matks** [comment]
@rokaszygmantas Do you believe it doable ? Do you think we can finish the Import page for 1.7.5 (so we would need to re-open the "Import page (2/2)" for branch `1.7.5.x`), so it would fix these bugs ?

**Comment by rokaszygmantas** [comment]
hi @matks, I'm not sure about the first issue - is it the incorrect language of file input translation? I think it's coming from the browser's language, isn't it?
The other two issues (prefilling of separator fields) are already fixed with https://github.com/PrestaShop/PrestaShop/pull/10120 so it's up to you if you want to merge it into `1.7.5.x` - I can open a PR for that. :slightly_smiling_face:

**Comment by matks** [comment]
@rokaszygmantas we need to to the 2nd PR for https://github.com/PrestaShop/PrestaShop/pull/10120 as there are feedbacks to handle
and then we have to pass QA validation that we skipped for PR 1 first 😉

**Comment by tomlev** [comment]
for the record:
the label on the input type=file button is translated by the browser
