### ISSUE TITLE
Can't translate new wording on override's modules in a template

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#10491]
**Describe the bug**
When I want to add some features belong to an override module in a theme, I need translate new wording on it. But those lines don't appear in the BO to translate them. 
However, when I add new wording on .tpl in the theme there is no problem. I used the same domain between .tpl theme and .tpl module.

**To Reproduce**
1. Add a sentence in an .tpl theme with the Theme domain ({l s='Test' d='Shop.Theme.Mytheme'})
2. Go to the BO in translation part. You see this sentence on the Shop/Theme/Mytheme domain) and you can translate it
3. Then add another sentence in an override module with the Theme domain ({l s='Test2' d='Shop.Theme.MyTheme'})
4. Go to the BO and you don't see it on this domain

**Additionnal information**
PrestaShop version: 1.7.4.X

**Comment by khouloudbelguith** [comment]
Hi @sLorenzini,

Thanks for your report.
It is the main issue with the ps_emailalerts module & wire payment module reported in this issue: #9697

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Hi @sLorenzini,

I manage to reproduce the issue.
Related to #9697 

Best regards, Khouloud

**Comment by mickaelandrieu** [comment]
Hi,

this should be fixed by https://github.com/PrestaShop/PrestaShop/pull/11321, but let's wait for the alpha release (with another one pull request about translation system I need to do) to check every translation issue again.

Long story short: we're aware that the support of translation of external modules is incomplete and we are working on it.

In 1.7.6, the support of legacy translations files will be supported in the translations manager.

The last feature missing: be able to save translations in the database for each theme, we need the help of someone from the community if we want this feature for 1.7.6 release...

**Comment by marionf** [comment]
@khouloudbelguith Could you try to reproduce it on 1.7.6.x branch ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

I did not manage to reproduce the issue with PS1.7.6.0beta1
1. I added this sentence `{l s='Test 1 more theme' d='Shop.Theme.MyTheme'}` in the file /themes/MyTheme/templates/catalog/product.tpl
2. I added this sentence `{l s='Test 2 more module' d='Shop.Theme.MyTheme'}` in the file /themes/MyTheme/modules/ps_customtext/ps_customtext.tpl

In the translation page, Shop/Theme/Mytheme domain they are displayed
![image](https://user-images.githubusercontent.com/16067358/58465921-903f6d80-8130-11e9-9282-a92cc250d0ed.png)

Thanks!
