### ISSUE TITLE
Bootstrap.php at line 140 eats up CPU

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#10527]
**Describe the bug**
Hi, after debugging a lot my case I ended up that the line 
    define('_PS_CREATION_DATE_', $config['parameters']['ps_creation_date']);
When is uncommented eats (literally) the CPU, even when the site is on maintenance mode.
When I comment it, of course the store stops working but stops eating the CPU

**To Reproduce**
1. Go to /config/bootstrap.php
2. Comment "define('_PS_CREATION_DATE_', $config['parameters']['ps_creation_date']);"
3. You will get an error "Error: "install" directory is missing", tried enabling debug mode, and same text and no additional info

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

Background:
I had my prestashop running as always and then I noticed a peak CPU usage from my hosting (no changes made in the files or database).
All I get from cPanel is this error:
lsphp:/websiteroot/index.php
Then I began debugging line per line. When index.php is full commented, front office stops to work, BO still works and CPU usage is normal.
After debugging config/config.inc.php commenting line 57 cpu stops being abused, this is the lane:

require_once $currentDir . DIRECTORY_SEPARATOR . 'bootstrap.php';

Then in bootstrap.php the only lane that affects the cpu is the above mentioned 

define('_PS_CREATION_DATE_', $config['parameters']['ps_creation_date']);

And I don't know how to continue the debugging since I'm not familiar with php nor what this lane exactly does, I'm a little bit desperate now.

After a lot of debugging I've tryied to update the prestashop version (from 1.7.2.1 to 1.7.4.2, but got no luck in CPU management, shop is now 1.7.4.2)

**UPDATE 20/9/18**
After checking backups from before the "accident" of CPU usage and now, the files are intact(no changes made) so i'm guessing that now it's a database problem related. I'm going to check it and reply when I have news.

**Comment by khouloudbelguith** [comment]
Hi @ChineseNorris,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.2.
When we comment ` "define('PS_CREATION_DATE', $config['parameters']['ps_creation_date']);"`
I get an error "Error: "install" directory is missing".
![image](https://user-images.githubusercontent.com/16067358/45806635-ddc22b80-bcc1-11e8-8c87-3b46c01c8958.png)
@eternoendless  what do you think about this issue.

Best regards, Khouloud

**Comment by rdy4ever** [comment]
How about insted of commenting out, do something like this:
` define('_PS_CREATION_DATE_', '1');`
The store should still work, but you could test the impact on the CPU. In my case I don't see any difference, but who knows...

**Comment by ChineseNorris** [comment]
@rdy4ever 

Thank you for you reply and assistance, I've made the modifications you mentioned but got no improvement in the CPU side.
I'll edit the full story to replicate step by step. Please check again main thread for more info.

**Comment by rdy4ever** [comment]
You could try to install a fresh prestashop instance on your hosting (it’s easy via Softaculous) and see if it behaves the same. Maybe the problem is not Prestashop but your host. Also, when you say that “it eats up CPU”, you mean on your server or on the client machine when you load the website? Could you share your url?
Also, I wouldn’t really point the problem to that line in bootstrap. Without the bootstraping process, any site would fail so it’s easy to see why it stops using CPU, because it fails to render the website.

**Comment by ChineseNorris** [comment]
Well, I've another prestashop sites in the same hosting and they are working properly without consuming that much CPU. When I mean "eating up CPU" is that when the line is commented the CPU is at 15-20% and when uncommented it goes to 90-100% within seconds.
What choice do I have to keep debugging and see where is the problem? I tried disabling overrides and modules, but with the same result.
The URL of the website is www.olidishop.com and It's working, slowly but working (even with cache enabled, because server is running slow). I got error 500 often because the CPU usage, so when I check the errors in cPanel I got a lot of errors and faults.

**Comment by eternoendless** [comment]
The problem is clearly not in the line itself, it's a simple constant declaration which has a complexity of O(1). There must be something else that uses that constant and according ot its value it triggers some behavior which is causing the performance issues you are experimenting. It could be a module or an override, it could be anything really.

I'd suggest looking for usages of `_PS_CREATION_DATE_` on your shop's code.
