### ISSUE TITLE
Too many calls to Addons API on install/update of a module

### ISSUE THREAD

**Issue by MonsieurRb** [PrestaShop/PrestaShop#10685]
Lo,

On an install or update of a module, a call to the Addons API is done every second on the check method for each installed module which can be very high.
/?version=1.7.3.0&iso_lang=en&iso_code=fr&shop_url=localhost&mail=xxxx&format=xml&method=check&module_name=xxxx&module_key=xxxx

**To Reproduce**
Installed a fresh 1.7.3.0 version
Installed 3 free modules
Updated "Faceted search" (I have the same problem with all modules)
39 calls on Addons API were done for each of the 3 modules with the check method

**Additionnal information**
PrestaShop version: 1.7.3.0
PHP version: 5.5.9

**Comment by khouloudbelguith** [comment]
Hi @MonsieurRb,

Thanks for your report.
Have you the same issue with the last version 1.7.4.2 & 1.7.5?

Best regards, Khouloud

**Comment by MonsieurRb** [comment]
Yes, I got this problem even on some 1.6 versions

**Comment by khouloudbelguith** [comment]
This issue seems that happens when the store cannot write on the cache the requests made on addons which produces that we re-queries each time.

**Comment by eternoendless** [comment]
We need to improve the API polling system so that it stops trying to retrieve data for a while (say, 1h or 2) if one request fails.

Currently, each request has a timeout of 5 seconds. But 5 + 5 + 5 makes a lot...

In the future, API requests should be done directly from the front-end. This would make the BO _way faster_ because it wouldn't have to wait for the API response before initial render. Of course, this would mean that the API should handle its own caching...

We could start emulating this by setting up an API bridge in the core (aka an endpoint that works as a proxy to the Addons API).

**Comment by marionf** [comment]
@eternoendless We can close this issue with the split ?

**Comment by eternoendless** [comment]
Yes we can. All calls to the Addons API are meant to be removed from the core.
