### ISSUE TITLE
Flash message alignment issue

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#10713]
There's a small alignment issue with flash messages as it does not fit with remaining content of the page, here's how it looks now:

![bad_alignment](https://user-images.githubusercontent.com/15143151/46064997-9e8c5280-c179-11e8-8de0-d80072410fce.png)

This is how it could look like:

![good_alignment](https://user-images.githubusercontent.com/15143151/46065018-a77d2400-c179-11e8-88c3-b0a1a05cd30e.png)

If you think that alignment should be fixed, I can do a pull request for that.

**Comment by sarjon** [comment]
@colinegin maybe you can give your input on this?

**Comment by colinegin** [comment]
Hello @sarjon ,

as seen with @matks this is not a critical bug so we can fix it for 1.7.6.
I've added the new milestone.

Thanks !

**Comment by colinegin** [comment]
@khouloudbelguith do you know if this issue has been fixed in 176 ?

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

Yes, it is fixed in the branch 1.7.6.x
![image](https://user-images.githubusercontent.com/16067358/60505105-e4eb8080-9cba-11e9-88f5-9b43e6c0ad25.png)
![image](https://user-images.githubusercontent.com/16067358/60505157-03ea1280-9cbb-11e9-94ff-5cac399a0938.png)

Since it is fixed, I close the issue.

Thanks!

**Comment by mirali-se** [comment]
I have new fresh PS 1.7.6.0, but still, I have this problem

**Comment by khouloudbelguith** [comment]
Hi @mirali-se, 

It is Ok in my case.
https://drive.google.com/file/d/1b8e1RwCxC2tf53ON95N5Q9zhFo-ZeKZ8/view
Thanks!
