### ISSUE TITLE
Deprecated: The each() function is deprecated version 1.6.1.20

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#10782]
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /tools/smarty/sysplugins/smarty_internal_compilebase.php on line 75

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

Could you please add steps to reproduce the issue in a new comment.

Thanks & best regards, Khouloud

**Comment by SebSept** [comment]
hello,

I guess, you are using php 7.2. @demeldoo .
This is a deprecation triggered by php - [php 7.2 deprecations](https://secure.php.net/manual/en/migration72.deprecated.php)
The each() call is made in [smarty](https://www.smarty.net/) code.
I don't know if this will be fixed in ps 1.6.

enable debug mode, use php 7.2, force template recompilation (maybe not needed) you'll reproduce the bug.

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

Prestashop 1.6 may have problems with PHP 7.2, we recommended using PHP 7.1.
You can follow this link: https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+label%3A1.6.1.x+PHP+7.2+is%3Aopen to see some fixes about php 7.2 compatibility.
Thanks to check & feedback.

Best regards, Khouloud

**Comment by demeldoo** [comment]
yes excatly as described

This is a deprecation triggered by php - php 7.2 deprecations
The each() call is made in smarty code.

enable debug mode, use php 7.2, force template recompilation (maybe not needed) you'll reproduce the bug.

**Comment by khouloudbelguith** [comment]
Hi @demeldoo,

As I said before, Prestashop 1.6 is not compatible with PHP 7.2, we recommended to use PHP 7.1.
In this link: https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+label%3A1.6.1.x+PHP+7.2+is%3Aopen you can follow the progress fixes about php 7.2 Prestashop's compatibility.
I close the issue, feel free to open a new one when needed.
