### ISSUE TITLE
Undefined "checkedForm" error on valid queries in SQL Manager

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10908]
**Describe the bug**
I have an error message "undefined checkedForm" when I try to export order sql query to sql manager. The SQL queries used to be considered valid in previous versions of PrestaShop.

**To Reproduce**
1. Go to Orders > Orders or Orders > Credit slip or Catalog > Products or Catalog > Categories
2. Click on Export to sql manager
3. Click on Save

The root cause is the same than in https://github.com/PrestaShop/PrestaShop/issues/10316

**Comment by marionf** [comment]
I can't reproduce it on develop branch

**Comment by Nittarab** [comment]
I have the same error in PS 1.7.4.4...  I try to execute the query directly in the DB and it work...

**Comment by kpodemski** [comment]
Same error for me on every 1.7 with migrated page. This page seems to be completely broken...

**Comment by marionf** [comment]
@kpodemski 

I can't reproduce with 1.7.6.0

![capture d'écran_1889](https://user-images.githubusercontent.com/13449658/63019706-6890b380-be9c-11e9-9965-2fda395978dd.png)

**Comment by kpodemski** [comment]
@marionf 

i'll try to do some debugging to see why error appears on some environments

**Comment by marionf** [comment]
Thank you very much @kpodemski

**Comment by noindie** [comment]
same error

**Comment by jonasburneika** [comment]
I have it on 1.7.5.1 my sql code: https://www.codepile.net/pile/K9GbMrvx

**Comment by ghost** [comment]
Is there any update? I have the same problem on 1.7.5.1 like @jonasburneika.
I can't join tables...

**Comment by matks** [comment]
It seems we cannot reproduce this issue 100% times so specific conditions are required to observe the buggy behavior 🤔

**Comment by ghost** [comment]
Everytime I want to join tables or make a query on mulitple tables I have this error.
So I did some basic SQL queries on PrestaShop and my processing by Excel and VBA.

**Comment by robrothkopf** [comment]
On the back end (e.g. phpMyAdmin), you know the query works because you've tested it, ya?  But that identical query gives this error when trying to save on PrestaShop's SQL Manager?

WORKAROUND:
Create a view via phpMyAdmin, and then in PrestaShop's SQL Manager, select the data from the view instead of the query.

e.g.
If your query was:  
`select * from MYTABLE`

create a view from that query as follows:
```
create view v_MyViewName as 
select * from MYTABLE
```

Now in PrestaShop's SQL Manager, your sql query will be:
`select * from v_MyViewName`

No more error and you get the same results!

Obviously, this was an overly-simplified sample query, but try it .. it did the trick for me!

**Comment by w3bissime** [comment]
Hello,
I have got this bug on Prestashop 1.6.1.24
Does anyone know how to correct it on this version?
Thank you

**Comment by bencheva-v** [comment]
Hi, guys, I found an answer of this bug in Prestashop 1.7.5.2  after many hours of debugging. Just change the function parsingSql in classes/RequestSql.php with prestashop 1.6 function parserSQL from classes/Tools of course with override and everything works.

Change:
` public function parsingSql($sql)
    {
        return Tools::parserSQL($sql);
    }`
    
    wiht:
    `public function parsingSql($sql)
    {
	   if (strlen($sql) > 0) {
            require_once(_PS_TOOL_DIR_.'parser_sql/PHPSQLParser.php');
            $parser = new PHPSQLParser($sql);
            return $parser->parsed;
        }
        return false;
		
       // return Tools::parserSQL($sql);
    }`

**Comment by pabluss** [comment]
it works, thank you

**Comment by Astalyos** [comment]
@bencheva-v Hey sorry to bother you ! 
I tried applying your fix via an override of RequestSql, but I’m getting a PHP fatal error related to a method signature mismatch.

I'm still running PrestaShop 1.7.5.1, and when checking [1.7.5.2 history](https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/tools/parser_sql/processors/SetProcessor.php) I didn't notice major differences around this area, so I didn't expect issues.

After applying the fix, I get:
`Compile Error: Declaration of DuplicateProcessor::process($tokens) must be compatible with SetProcessor::process($tokens, $isUpdate = false)` 

It seems the parser components shipped in my installation are inconsistent, causing the override to load incompatible processor classes.
Did you also update or replace the parser_sql processors directory when applying the fix, or did it work out of the box in your case?

Thanks in advance!

log : 
`[2026-02-02 20:02:58] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Declaration of DuplicateProcessor::process($tokens) must be compatible with SetProcessor::process($tokens, $isUpdate = false)" at /var/www/html/tools/parser_sql/processors/DuplicateProcessor.php line 42 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Declaration of DuplicateProcessor::process($tokens) must be compatible with SetProcessor::process($tokens, $isUpdate = false) at /var/www/html/tools/parser_sql/processors/DuplicateProcessor.php:42)"} []`

**Comment by bencheva-v** [comment]
Hi, @Astalyos !

This issue was far in time. I don't think that I changed the directory parser_sql. The fix was only in classes.

Your error says that function process in class DuplicateProcessor has only 1 parameter. It must have 2 parameters as in SetProcessor, add the second one and must be fixed.

I hope I helped!

**Comment by Astalyos** [comment]
Thanks you for answering @bencheva-v ! 
Indeed yes, time has passed ! 
I was wondering because since we're still in 1.7.5.1, tools is like part of the core of Prestashop, Prestashop tells how to override classes, controller and modules extends but i'm not sure how to override Tools if it is not modifying the core
I'll take a look closer tomorrow ! Thank you for your kind answer !
