### ISSUE TITLE
[SF Migration] Introduce a 'template' property for Columns to allow override ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10910]
https://gist.github.com/sarjon/50a2e79435e0902e6b1eb74a4d620538

Idea is to allow developers to override the template being used to render a Grid column for 1 grid only.
This could be done by adding a `template` property to columns, that would be used by Twig when not null.

Currently twig finds Twig template to render a column using `type`.

**Comment by sarjon** [comment]
As you can see here https://gist.github.com/sarjon/50a2e79435e0902e6b1eb74a4d620538 , there are a couple of reasons to add configurable templates for columns.

First, you can use `DataColumn` (or any other) column, but if you want your data to be centered. Do you have to create `CenterAlignedColumn`? Or if you want to make something like this:

![colorful_column](https://user-images.githubusercontent.com/15143151/46677648-b50bc280-cbeb-11e8-9fec-92b73690bbac.png)

In that case, it requires to create new column, like:
```php
/**
 * Class BadgeColumn displays column with badge.
 */
final class BadgeColumn extends AbstractColumn
{
    /**
     * {@inheritdoc}
     */
    public function getType()
    {
        return 'badge';
    }

    /**
     * {@inheritdoc}
     */
    protected function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setRequired([
                'field',
            ])
            ->setDefaults([
                'badge_type' => 'success',
            ])
            ->setAllowedTypes('field', 'string')
            ->setAllowedTypes('badge_type', ['success', 'info', 'danger', 'warning',])
        ;
    }
}
```

As you can see, this column is only needed as a replacement for template. :/

Second, this would allow reusing same column for different representations, as you can configure templates.

So the problem is that column itself and its options are good in most cases, but sometimes we need different representation of the same column. In additiona to that, this would also make templates explicit and easier to understand or configure, plus that way we wouldnt need to resolve templates on runtime, as it also costs on performance.

**Comment by sarjon** [comment]
one more thing, if we decide to introduce configurable templates, it would also be nice to do it for actions as well.

For example, see grid actions:
![icons](https://user-images.githubusercontent.com/15143151/46745816-7abb2780-ccb6-11e8-9553-f404739d566f.png)

Those icons are configured in the code, like `$action->setIcon('edit')`, i think it would be much better to allow template configuration, so its something like `$action->setTemplate('@path/to/template/export_to_sql_manager.html.twig')` or `$action->setTemplate('@path/to/template/show_sql_query.html.twig')`.

@matks wdyt?

**Comment by matks** [comment]
I like the idea. I am a bit concerned about the fact that this creates coupling between the form definition and Twig (or Smarty or any other template engines in the future) but I think this is a good trade-off which offers very good flexibility for PS developers and PS module developers.

@mickaelandrieu @eternoendless wdyt ?

**Comment by matks** [comment]
@eternoendless @mickaelandrieu I ping you again
If you dont deliver feedback, I'll consider it an approval 😄

**Comment by matks** [comment]
If we accept this feature, we'll be able to handle nicely [this issue](https://github.com/PrestaShop/PrestaShop/pull/10916#pullrequestreview-164751953).

**Comment by matks** [comment]
👍 OK this idea gets approval ! 🎉

**Comment by matks** [comment]
@sarjon @tomas862 you win 😃

**Comment by mickaelandrieu** [comment]
Hello, nope!

This is already possible using the templating system you have created @sarjon.

See the following screenshot:

![grid_templating_system](https://user-images.githubusercontent.com/1247388/50292436-65f6cf00-0471-11e9-9bde-94ca6fcdfd18.png)

Sorry ^^

**Comment by sarjon** [comment]
@mickaelandrieu yes, but it forces you to create a lot of different columns which does the same except template is different.

see https://github.com/PrestaShop/PrestaShop/issues/10910#issuecomment-428226708

in addition, it would make PS easier to understand for developers as it would be more explicit, dont you think?

**Comment by matks** [comment]
We need do document current available solution
