### ISSUE TITLE
Missing badge classes in the bootstrap css code

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#10977]
Hi
if you add this code in the classic theme nothing will be happen
<span class="badge badge-pill badge-primary">Primary</span>

this part is missing
https://getbootstrap.com/docs/4.1/components/badge/

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.0

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
@eternoendless @PrestaShop/prestashop-core-developers what do you think of his suggestion?
Thanks!

**Comment by NeOMakinG** [comment]
Unfortunately, it looks like the alpha version we're using on the classic theme doesn't include badges...

And we're unable to update it until next major :/

wdyt @PierreRambaud ?

**Comment by PierreRambaud** [comment]
@NeOMakinG I confirm.
Otherwise, we can update the bootstrap version, but we will break everything because people who create the first 1.7 version included Bootstrap 4 alpha :trollface: 
I'm closing this issue, we will update our dependencies as soon as possible, but we will not add `badge` classes manually.
