### ISSUE TITLE
Enable email notification 

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11026]
Enable "email notification" when stock return available also for default accept order when out of stock.
It's very useful to have email nofication always.
http://nimb.ws/jrxtHv

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Did you installed the mail alert module?
![image](https://user-images.githubusercontent.com/16067358/47013923-0d414800-d149-11e8-9a43-72028c8ca08f.png)
Thanks!

**Comment by centoasa** [comment]
Yes, it's working! but it show only if product have qty=0 and (Availability preferences)= Deny orders
Instead, also with a preference flag on setting, email alert box available also for qty=0, independently from Availability preferences into product.

**Comment by khouloudbelguith** [comment]
@centoasa, if the "Allow orders" option is selected, there is no indication for the user that it is out of stock.
If "email notification" is enabled, when stock return available also for default accept the order, when out of stock, it will be a contradiction for the users in the product page, because he is allowed to add the product to the cart, & he is out of stock.
I don't think, that will be a good idea to add it.

**Comment by centoasa** [comment]
but I can also have this scenario:
1: http://nimb.ws/AaxWkS
2: http://nimb.ws/dOP45r
3: https://www.100asa.it/it/ricambi-stampanti-e-fotocopiatori/35307-20g-grease-di-resina-for-fixing-film-universale.html
4:; customers can't add this product to cart, and can't receive notifications when back in stock

**Comment by khouloudbelguith** [comment]
@centoasa, yes for this case, we cannot add the product to cart ( Available for order is unchecked in the Options Tab).
But the "email notification" is not displayed ( because "allow orders" is selected.)
@marionf what do you think?
Thanks!

**Comment by marionf** [comment]
If you disable "available for order" in options tab, it's because you don't want your product to be purchased not because it is out of stock.
If the product is out of stock and you want it to be purchased, you allow orders when out of stock.
If the product is out of stock and you don't want it to be purchased, you disallow order when out of stock and your customer can be alerted when the product is back in stock.
That's why mailalert module works with disallow orders when out of stock and not with "available for order" option

**Comment by centoasa** [comment]
If I don't want my product will be purchased, in option I disable "available for order" (email alert is a little useful).
But, as in my case, my company produce labels and wax ribbon for label printer, maybe useful allow order (backorder) by customers or they have email alert when product back in stock, and they can complete order.
