### ISSUE TITLE
Configurable debug mode

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#11038]
**Is your feature request related to a problem? Please describe.**
Its a common need to debug issue in production shop. Since a lot of merchant dont have multiple environments (and if they do, sometimes you still have to debug on live shop), developers providing support (and not only) have to be really careful when debugging problems on live shop.

It would be a nice feature to be able to enable Debug mode for different IP addresses.

**Describe the solution you'd like**
Be able to configure IP addresses on which debug mode would be enabled from Back Office.

**Describe alternatives you've considered**
Hardcode IP check directly in defines.inc.php file to define `_PS_MODE_DEV_`.

**Additional context**
Its something similar as configuring Maintenance IP in Back Office.

**Comment by matks** [comment]
Makes sense 👍

**Comment by ghost** [comment]
Brilliant @sarjon ! So simple!

**Comment by sarjon** [comment]
@matks i would be willing to give it a shot, wdyt? however, i'd like to see some mockup how it should look like. :)

**Comment by sarjon** [comment]
@colinegin wdyt?

**Comment by colinegin** [comment]
Hello @sarjon , sorry I missed your comment !
Yes, it could be a great idea for developers ! 
I guess we could have the same feature as for maintenance mode, but let's wait for @TristanLDD 's mockups :)

**Comment by ghost** [comment]
Any news about this FR?

**Comment by sarjon** [comment]
hi @PrestaShark,

as you can see, it's waiting for UI mockups. :)

**Comment by sarjon** [comment]
@TristanLDD any news on this?

**Comment by Gipielle** [comment]
Upvote !

**Comment by Gipielle** [comment]
It is possible to use the same operation that uses the site under maintenance but on the contrary, you could integrate it very quickly. It would be a great thing!

Thank you

**Comment by Gipielle** [comment]
I have found this:
https://www.matthieu-jalbert.fr/activer-le-mode-debug-par-adresse-ip-sur-prestashop/

but make a flag in prestashop backoffice will be a lot better

**Comment by jf-viguier** [comment]
I've posted a pr to support ip V6 et ip subnet masks in maintenance ip. This feathure should also support it : https://github.com/PrestaShop/PrestaShop/pull/16876

**Comment by madsoliver** [comment]
I was just about to add a feature request for this myself but found this little gem ;-)
It would be great to have this.

One could also consider to have a list of checkboxes for employees you would like to  enable debug for (and then check cookie if they are logged in or not), so that we are not even required to add our (dynamic) ip for every time we need to debug a client site.

**Comment by ElodieOS** [comment]
Hello everyone! 

Thanks for spotting this issue, it seems to be very important for the user!

I think both ideas can be worked in terms of UX, it's not a problem. 

With @colinegin's proposal, we keep consistency with other features (like maintenance), but it's true that it might be annoying to search and put the IP address. 
![image](https://user-images.githubusercontent.com/113457393/199941836-f9e7f467-65f6-4423-a22c-2e7f21233da6.png)

With @madsoliver's proposal, it's faster but : 
- for the merchant: we need to configure other people in the team and 
- for the dev: we need to harmonize all the other features like this one (for example maintenance)
![image](https://user-images.githubusercontent.com/113457393/199941903-df2b9402-a7db-46f4-9d0c-119ce5007afd.png)

Maybe you know the most useful behavior to choose the best solution?

**Comment by madsoliver** [comment]
Hi @ElodieOS  and thanks for following up on this!

I think both proposals are a huge improvement. 

A third proposal to have both - but you might find it bulky 😉
So the logic is: `if(_PS_DEV_MODE_ OR in_array($request_ip, $allowed_ips_array) OR (adminIsLoggedIn() && in_array($id_profile, $allowed_profile_ids))`

This way you can let some module or theme developer see your front-office with all the missing indexes that was introduced with their module 😉 but still not allowing them access to your back-office - by adding their IP.
At the same time you as a merchant will be able to spot such errors without adding yourself to the ip-table beforehand. 
Since ips change, it would be very useful for merchants to be able to spot such warnings in the everyday use, just by being added to the right admin profile.

But if proposal 1 is implemented, one can always make a module to auto-add admin-ips to the dev-ip-array as well, so proposal 1 OR 3 is best IMO 🙂


Wording in Proposal 3:
Enable debug-mode for ALL visitors (not recommended if site is live)
Enable debug-mode for selected ips
Enable debug mode for selected logged in admins with profile

**Comment by kpodemski** [comment]
Very often, as someone who maintains a store, I have the same profile as the merchant. Maybe we should be more explicit and select accounts instead of profiles.

**Comment by madsoliver** [comment]
@kpodemski  Hmmm.. I think it's better to be explicit either via IP or adding a separate profile for the merchant.

I would typically allways enable debug for superadmins, then add the merchant in a "Store owner"-profile with every access they need. Then I would NOT add the "Store owner" profile to the debug profiles, unless they want to spend their days freaking out about some undefined variable, thinking that is the way the website looks for the end-users.

**Comment by ElodieOS** [comment]
@PrestaShop/product-team wdyt?

**Comment by eternoendless** [comment]
The discussion continues here: https://github.com/PrestaShop/PrestaShop/discussions/30840
