### ISSUE TITLE
theme.yml, dependencies & overrides

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#11119]
**Is your feature request related to a problem? Please describe.**
Having the option to require module dependencies in the `theme.yml` is great. It's quick and easy to setup and it works pretty good.

However, in some cases a custom theme may need a few slight module overrides in order to achieve whatever it is it's trying to achieve. A new hook, another field or whatever it may be. It's very easy to create a module override which you store in the `root\override\modules\xx_module` folder. It would be incredibly useful if we could also have a section for handling module overrides as dependencies. The same goes for controller overrides.

As an example, we recently had a case where we needed to modify: `controllers\front\CmsController.php`. A very specific change.

No big deal, we simply created an override and put it in `root\override\controllers\front\CmsController.php`. Works great.

Now here's the "issue". When we come back to this project later on, for whatever reason, a Prestashop upgrade, a new environment or similar it'll be very easy for that particular override to get lost since there really is no "record" of it.

It would be great if we could treat overrides the same as module dependencies so that they are always tied to the particular theme. Such as, we create a `override` folder with the correct structure in the theme folder:
`themename\dependencies\override\controllers\front\*.php`

And then in the `theme.yml`:
```
dependencies:
  modules:
    - xx_module
    - xx_anothermodule
    - ...
  override:
    - controllers/front/*.php
    - ...
```

Is something like this possible or perhaps even implemented but not documented right now?

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

Have you an issue similar to this ticket: #9941?
Thanks!

**Comment by dennispw** [comment]
@khouloudbelguith No. I'm not having an issue I'm just wondering if we can have the same possibilities with overrides as we do with module dependencies.

Thas is if we have an override för a controller or a module that we can specify that in the theme.yml and that those are applied with the installation/activation of the theme.

**Comment by khouloudbelguith** [comment]
Hi @dennispw, thanks for your feedback.
@eternoendless, @PrestaShop/prestashop-core-developers what do you think of his suggestion?
Thanks!

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers friendly reminder :)

**Comment by jolelievre** [comment]
Hello @dennispw,

I'm not sure this kind of feature will be proposed or encouraged in the coming versions as we want to deprecate the override system someday, not until a future major version (1.8 or more) but still enhancing the possibilities of the override system is not exactly in sync with what PrestaShop is supposed to look like in the future.

That said for present time your suggestion might be useful if you want to integrate all your override in your themes. But I'm wondering if it is really necessary to define in `theme.yml` the files. Maybe it would be simpler to simply respect the override folder structure inside the theme folder. Then the Dispatcher should be able to analyze the theme folder (not only the override one), so we wouldn't need to copy the files in the override folder.

Which seems safer because when you disable the theme you don't need to clean the copied files. But I'm not an expert in the override system so i'm not sure if this could work. From what I see in the Module class it seems that the way it works now is just by copying the files from the module folder.

**Comment by dennispw** [comment]
@jolelievre Yes, we can easily create an `override` folder in the theme and manually keep track of them, no big deal. Another option is of course to create a specific module containing the necessary overrides and have that particular module become a depency of the theme instead:
```
.../themes/my_theme/dependencies/modules/xx_overrides/override/...
```

Not ideal but it would definately work.

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers Can we close this issue if no changes are required ?

**Comment by PierreRambaud** [comment]
I don't think it's a good idea to add it since we are against the override system and will be removed in the future.

**Comment by eternoendless** [comment]
Thanks for your suggestion @dennispw but the override system is progressively going away, so we're not going to implement this feature as requested. IMO themes shouldn't override behavior, at best they could be bundled with a module that does the overriding itself (and by that I mean [service override](https://devdocs.prestashop.com/1.7/modules/concepts/services/)).
