### ISSUE TITLE
Composer install when installing

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11110]
**Describe the bug**
Install PrestaShop and it will ask you do a composer install during installation

**Screenshots**

![capture d ecran_492](https://user-images.githubusercontent.com/13449658/47303566-88609d80-d624-11e8-820a-88d2d89dc2de.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by matks** [comment]
After performing a code analysis, I can state that:
- this warning comes from Symfony `var/SymfonyRequirements`
- to check whether this warning should be displayed, `var/SymfonyRequirements` compares its own file content with the one from `vendor/sensio/distribution-bundle/Resources/skeleton/app/SymfonyRequirements.php`, if they differ the message is displayed
- this is consequently a failed warning as these files differ not because of an issue with `composer install` but rather because we adapted the initial file for php7.2

So this warning should appear for php5.6, php7.0 and php7.1 installs, not php7.2 . But it is still wrong, it's just that the process used to check whether `composer install` was successfull does not work in this usecase.

**Comment by matks** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/11209
