### ISSUE TITLE
[WIP] Module Manager : get Addons modules in the page even if not Installed (1.7.6)

### ISSUE THREAD

**Issue by LouToma** [PrestaShop/PrestaShop#11121]
**Describe the bug**
When connected to Addons account, my modules appear in Module Catalog. They must appear in Module Manager (sorted in Addons categories), even if they are not installed yet.
The default CTA will be "install" if module is not installed.

**To Reproduce**
Connect to Addons account that has modules in it (Kamel can give the access to his account)
Go to Module Manager
Paid modules of Addons account do not appear
(They only appear on Module Catalog page)

**Comment by marionf** [comment]
> When connected to Addons account, my modules appear in Module Selection

You mean Module Catalog ? Module Selection is the iframe page:

![capture d ecran_498](https://user-images.githubusercontent.com/13449658/47355569-01fa9900-d6c2-11e8-813a-c812b02450bb.png)

> They must appear in Module Catalog

You mean Module Manager ? They already appear in Module Catalog

**Comment by marionf** [comment]
What is the default button when the module isn't installed ? I supposed install ?

And what happens if I uninstall a module in module manager page ? Currently the module doesn't appear anymore in module manager page and appear in module catalog page, should we keep this behavior ?

Also, currently we can filter by status: enabled modules & disabled modules, maybe it should be good to add installed modules and uninstalled modules ?

**Comment by marionf** [comment]
With the split of the os project, I close this issue
