### ISSUE TITLE
Cart summary - total price not updated upon cart quantity change

### ISSUE THREAD

**Issue by jancinert** [PrestaShop/PrestaShop#11148]
**To Reproduce**
1. Install prestashop 1.6.1.20
2. Make following settings in Back Office:
- Administration -> Localization -> VAT -> Display tax in the shopping cart (YES)
- Administration -> Customers -> Groups -> Customer, Visitor or Guest atc -> Price display method -> Tax excluded
2. Go to frontend and add product demo_2 to cart
3. Go to cart summary page
4. Change quantity of the product to 2 and see that total price in last row named TOTAL is not updated

**Additional information**
PrestaShop version: 1.6.1.20
PHP version: 7.2

**Comment by jancinert** [comment]
It is because of duplicate id attribute in two div nodes in html
And cart-summary.js javascript using jQuery updates only a first one (row named "Total (VAT excl.)).

**Comment by khouloudbelguith** [comment]
Hi @jancinert,

I manage to reproduce the issue with PS 1.6.1.20.
https://drive.google.com/file/d/1h3YFgY0SNY3EBnbG6hFMwwLI8i0LUZFd/view
The issue doesn't exist in the 1.7.
Here's the fix for the 1.6: #11149
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
if your bug isn’t critical or a security issue, it can not be fixed.
@marionf, what do you think?
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 
What happens if you complete the order ? Do you pay the good price ?
Can you try with the last 1.6 ?

**Comment by khouloudbelguith** [comment]
@marionf, yes it is good.
In the first step, if you just refresh the page => the total will be correct.

**Comment by marionf** [comment]
Hello,

As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Your bug isn’t critical or a security issue, so it will not be fixed, that’s why I close it.

Regards
