### ISSUE TITLE
It impossible to Add the Gaeilge (Gaelic) language - Translations page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11220]
**Describe the bug**

In the BO => International => Translations page, when we try to add the `Gaeilge (Gaelic)` language, an exception is displayed.

**To Reproduce**
1. Go to the BO => International => Translations page
2. In the ADD / UPDATE A LANGUAGE part, select the `Gaeilge (Gaelic)` language & try to add this language
3. See error

PS1.7.4.3 => OK
I make test son the machine shuffle, nightly Prestashop & I manage to reproduce the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/47856150-c9a43a80-dde6-11e8-8320-712a44033bd7.png)

**Additionnal information**
PrestaShop version: 1.7.5.0 buildabeta2 / 1.7.5.x
PHP version: 7.1

**Comment by mickaelandrieu** [comment]
ping @eternoendless any chance this zip archive to be corrupted on the server? I don't see how a specific language pack can create bugs in the core...

**Comment by jolelievre** [comment]
So the problem comes from http://i18n.prestashop.com/translations/1.7.5.0/ga-IE/ga-IE.zip which does not exist.
What surprises me even more is that Gaelic is not managed in https://crowdin.com/project/prestashop-official
Which seems to be the source and platform we use to generate our translations.

Furthermore, @khouloudbelguith I tried to install this language in 1.7.4.x branch and I have an error as well (not the same one but stil it does not work). Which seems logical as http://i18n.prestashop.com/translations/1.7.4/ga-IE/ga-IE.zip does not exist as well.

When you look in the translations folder the downloaded zip it is actually a 404 response:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /translations/1.7.4/ga-IE/ga-IE.zip was not found on this server.</p>
</body></html>```

**Comment by LouiseBonnard** [comment]
Hello @khouloudbelguith, why the Gaelic? Is there not a confusion with the Galician being newly available in the installer?

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

I just tried with 1.7.4.4 & it is ok => https://drive.google.com/file/d/1XPzpGOh8BcnqlTvvynu6Vd6ucYvYipxr/view
But yes with the 1.7.5.0, there is an exception => https://drive.google.com/file/d/1GZ8WlwHQD_wvOH_cbrL5RHNH9jXDeRx4/view
@LouiseBonnard, I just tried to add the Gaelic language.
Thanks!

**Comment by marionf** [comment]
If it can help you, when I try to import irland pack in International > translations, Gaelic is well imported

**Comment by jolelievre** [comment]
@marionf on 1744 or 1750?
@khouloudbelguith whe I look at your video for 1744 I see that you update the language, not install it
I have the same behavior with the update part, but when I try to install from a fresh prestashop installation I have this error:

![capture d ecran 2018-11-22 a 10 48 06](https://user-images.githubusercontent.com/13801017/48895029-6b4a0500-ee44-11e8-8fe0-b2e85c14e869.png)

and once the first install failed, I can update without getting any errors just like in your video, even when I uninstall the language the error does not show again but I am almost sure some things are missing and the update should not work as well
If I select Gaelic as my language in my profile, the language is in english (I think as a fallback), and when I try to edit translations for gaelic I get an error because the language folder does not exist

Could you try from a fresh install to be sure we have the same behavior. Or even just try to use the Gaelic language or modify its translations please?

**Comment by marionf** [comment]
@jolelievre I tried on 1.7.5.x branch

**Comment by khouloudbelguith** [comment]
@jolelievre, when I tried to install 1744, I couldn't found the Gaelic language in the first step.
I tried to modify my profile to Gaelic, the BO is still in English.
When I tried to edit translations for Gaelic, I have an error
![image](https://user-images.githubusercontent.com/16067358/48896291-8bc78e80-ee47-11e8-8ec9-2e936759218d.png)
& this exception is displayed
![image](https://user-images.githubusercontent.com/16067358/48902930-5f693d80-ee5a-11e8-9afc-80792f6180cd.png)
Thanks!

**Comment by LouiseBonnard** [comment]
Dear all, Crowdin does not support the Irish Gaelic, only the Scottish Gaelic. So my advice is: add the Irish Gaelic in TranslationFiles (and do not care about Crowdin then) to prevent from any installation issue. If it needs to be listed in Crowdin, well I guess we will have to remove it from the allowed languages list.

**Comment by eternoendless** [comment]
Since Gaelic is not currently in Crowdin, I think the best would be removing it for now.

**Comment by eternoendless** [comment]
PR: https://github.com/PrestaShop/TranslationFiles/pull/4
