### ISSUE TITLE
Plus accès à l'admin

### ISSUE THREAD

**Issue by AxelMHA** [PrestaShop/PrestaShop#11243]
Bonjour,

**Describe the bug**

J'ai créé ma boutique en ligne ce midi. Mon hébergement est php.net
Je pouvais encore avoir accès au back office il y a quelques minutes avant le changement d'URL
Mon site est le suivant : http://my-hero-academia.fr
J'avais accès au back office via cette URL : http://tbk9716.phpnet.org/prestashop et le site n'était accessible que via cette adresse (http://tbk9716.phpnet.org)

J'ai donc appelé phpnet pour savoir comment faire et j'ai redirigé vers la racine /www/prestashop
Enfin je suis allé sur le back office de prestashop et j'ai modifié l'URL vers : my-hero-academia.fr

Sauf que depuis je n'ai plus accès à l'admin même en tapant my-hero-academia.fr/admin

Comment faire pour avoir accès au back office de ma boutique ?

**Screenshots**
ancienne URL
![image](https://user-images.githubusercontent.com/44704784/47921750-a98f7c80-deb5-11e8-98e6-acced91d2f4d.png)

nouvel accès avec nouvelle URL
![image](https://user-images.githubusercontent.com/44704784/47921779-ba3ff280-deb5-11e8-8c98-1fb299742df1.png)

Impossible d'accéder à l'admin
![image](https://user-images.githubusercontent.com/44704784/47921821-d04db300-deb5-11e8-8f04-7b5a171cb88b.png)

En faisant précédant je me retrouve avec un back office comme tel
![image](https://user-images.githubusercontent.com/44704784/47921847-dd6aa200-deb5-11e8-88e0-926aae6b64f9.png)

**Additionnal information**
PrestaShop version: 1.6

**Comment by khouloudbelguith** [comment]
Hi @AxelMHA,

The page doesn't exist `my-hero-academia.fr/admin` because the admin folder is renamed automatically for security reasons.
You need to check the new name of this folder
To access to the BO => You need to acces to this URL => my-hero-academia.fr/**admin-folder-after-renaming**
If it is ok, could you please try to naviagate to the BO => Preferences => SEO & URLs, disable the Friendly URL, click on save, then try to enable it again.
Thanks!

PS: As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.

**Comment by AxelMHA** [comment]
Hello,

Thank you for your reply.

Unfortunatly, I don't know what kind of folder do you mean ?

The only thing I changed was the URL in the BO settings

**Comment by AxelMHA** [comment]
I've found the acces to the admin

Thank you again for your time, last thing :
Where is the "Friendly URL" option ?

**Comment by khouloudbelguith** [comment]
@AxelMHA, in the BO => Preferences => SEO & URLs page.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @AxelMHA,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
