### ISSUE TITLE
Impossible to modify or delete an address in Japanese.

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#11251]
**Describe the bug**
Impossible to modify or delete an address in your profil in Japanese.

**To Reproduce**
1. Install Japanese Language Pack
2. Create account and go to the url http(s)://example.com/ja/住所 to modify or delete your address.
3. Even it's the option "Accented URL" is activate, you can't modify or delete the address.

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your report.
I manage to reproduce the issue with PS 1.7.4.3.
https://drive.google.com/file/d/1yDbYtWPcn0SgZbobwtHTAOezVOMBID9J/view
We will see how to fix it.
Thanks!

**Comment by BenTen** [comment]
Hello,
Is there some news about this bug?
Japanese can't use Prestashop 1.7, I think the priority need to be more than Standard, no?

Regards

**Comment by BenTen** [comment]
Hello,
I fount why we can't delete or modify address in Japanese.

in "Traffic & SEO" there is address and addresses.
The first is when we create an address, the second is to see addresses in "my-account".

But in Japanese there is not plural, so the Friendly url is 住所 for both.

If we change the Friendly url of one, the problem is solved.

**Comment by PierreRambaud** [comment]
Hi and thanks for the feedback.
Could be a solution to implement https://en.wikibooks.org/wiki/Japanese/Grammar/Nouns => Plurals?
@colinegin I think you must have a check on this issue and tell us if it's important to have plural in Friendly urls or not :)

**Comment by LouiseBonnard** [comment]
Hello! If there is a translation need, please go to the translation project [here](https://crowdin.com/project/prestashop-official/ja#) and turn the former false translation into the right new one. And if needed, ping me, I'll be glad to help. ;-)

**Comment by colinegin** [comment]
An easy fix would be to change the wording "Addresses" with "My Adresses" to prevent any issue with the URL. What do you think @LouiseBonnard ? @PierreRambaud ?

**Comment by PierreRambaud** [comment]
@colinegin I think it is a good idea to change wording.

**Comment by LouiseBonnard** [comment]
@BenTen, there are several mentions of the strings 'Address', 'Addresses' or 'My addresses' in the front office, you can find it [here](https://crowdin.com/project/prestashop-official/ja#/1.7.2/Shop) on Crowdin. Do you mind having a look at all the translations suggested and let me know what would be the best so that we can solve this issue? I'm afraid my skills in Japanese are not accurate enough. ;-)

https://crowdin.com/translate/prestashop-official/33530/en-ja#q=addr
https://crowdin.com/translate/prestashop-official/33527/en-ja#q=addr
https://crowdin.com/translate/prestashop-official/33516/en-ja#q=addr
https://crowdin.com/translate/prestashop-official/33526/en-ja#q=addr

**Comment by BenTen** [comment]
@LouiseBonnard I will dot that as soon as possible.

Thank you :)

**Comment by BenTen** [comment]
done

33530 (Addresses): from 住所情報の管理 to アドレス帳
33527 (Update your address): from 住所を更新します。to 住所を変更します。
33516 (Address): 住所
33526 (My address): from 住所 to 自分の住所

sorry for the delay m(_ _)m

**Comment by colinegin** [comment]
I close this issue, thank you @BenTen for your help !
