### ISSUE TITLE
Ps-wirepayment add icon PrestaShop : 1.7.3.0

### ISSUE THREAD

**Issue by KHATERSAID** [PrestaShop/PrestaShop#11296]
Hello
when I want to add a bank transfer icon
it multiplies on other payments
How to solve this problem
thank you 
![2](https://user-images.githubusercontent.com/39734318/48120715-3c903400-e273-11e8-8b3d-4b47ab4e69ce.jpg)
![3](https://user-images.githubusercontent.com/39734318/48120716-3c903400-e273-11e8-83c6-0ff98310ce03.jpg)
![1](https://user-images.githubusercontent.com/39734318/48120717-3c903400-e273-11e8-9aa3-a36f70c8f146.jpg)

**Comment by khouloudbelguith** [comment]
Hi @said4440,

Because you edited the payment.tpl of your current theme.
You need to edit your module, so you can add the logo.
Please be aware that the forge should be used to report issues ONLY. If you need help, you can ask on the Forum (https://www.prestashop.com/forums/), Gitter (https://gitter.im/PrestaShop/General) or Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop).
Thanks for your understanding!
