### ISSUE TITLE
Bad translation of 'Reorder'

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11298]
**Describe the bug**
Bad translation of 'Reorder'

In english it's the same word but not in other languages

![capture d ecran_570](https://user-images.githubusercontent.com/13449658/48121554-8c6ffa80-e275-11e8-9e87-55656aa7bfab.png)

![capture d ecran_571](https://user-images.githubusercontent.com/13449658/48121558-8f6aeb00-e275-11e8-8d81-6eff748fa8f8.png)

![capture d ecran_572](https://user-images.githubusercontent.com/13449658/48121566-91cd4500-e275-11e8-8dfa-bd1955cd57b2.png)

![capture d ecran_573](https://user-images.githubusercontent.com/13449658/48121574-94c83580-e275-11e8-8fd3-a00f67614a55.png)

**Comment by marionf** [comment]
@LouiseBonnard I think the string is the same in both places

**Comment by LouiseBonnard** [comment]
@marionf, thanks! In Crowdin, the string only exists in the _Admin.Actions_ file and it has been changed ten days ago so that it can mean "Réorganiser" instead of "Commander à nouveau" in both French and French (CA) translation projects. And I can confirm it has been taken into account in Crowdin. Also, to avoid misinterpretation, I have just added a comment for this string on all catalogs in order to help translators understand the right meaning.

**Comment by marionf** [comment]
It's all good in French in 1.7.4.3 :)
We will wait for translation in other languages :)

![capture d ecran_605](https://user-images.githubusercontent.com/13449658/48354095-25957b80-e691-11e8-8190-d231a81cfbf8.png)

![capture d ecran_606](https://user-images.githubusercontent.com/13449658/48354099-29c19900-e691-11e8-8845-eaa88800d862.png)

But I still have the problem in 1.7.5.0
@eternoendless is it because of catalog export ?

**Comment by marionf** [comment]
It's all good also in 1.7.5.0 so PR #11328 can be closed
