### ISSUE TITLE
`action<AdminControllerName>ListingFieldsModifier` no longer called on Symfony pages

### ISSUE THREAD

**Issue by firstred** [PrestaShop/PrestaShop#11304]
**Describe the bug**
`action<AdminControllerName>ListingFieldsModifier` is no longer being called on Symfony pages, which makes it impossible for modules to influence how lists are displayed. I know plenty of modules that use these hooks in order to prevent the usage of overrides. 
Is there an alternative? If there is, can it be documented, please? If not, what needs to be done to unbork these modules before 1.7.5 is released?

**To Reproduce**
N/A

**Screenshots**
N/A

**Additional information**
PrestaShop version: 1.7.0+
PHP version: all

**Comment by firstred** [comment]
Pinging the migration maestro @mickaelandrieu

**Comment by khouloudbelguith** [comment]
Hi @firstred,

Thanks for your report.
Could you please provide us a tuto module to test it.
Thanks!

**Comment by firstred** [comment]
Here's a quick module. It should dump the AdminLogs queries and crash out on the logs page when successful, but it doesn't do that on 1.7.5+.

[customlisting.zip](https://github.com/PrestaShop/PrestaShop/files/2557557/customlisting.zip)

**Comment by sarjon** [comment]
hey @firstred you can take a look at this module https://github.com/sarjon/demo-grid-module of how to modify new lists. :) It may be a bit outdated.

Also, you can check existing docs (some stuff may be outdated :/ ) https://devdocs.prestashop.com/1.7/development/components/grid/

Let me know if you have any more questions. :)

**Comment by firstred** [comment]
That is awesome! Thanks @sarjon 

Let's see if we can get a few real world examples integrated with the new grid component.
Closing this issue, because this looks like a really powerful alternative and there's a sufficient amount of documentation. Great job!

**Comment by kpodemski** [comment]
@sarjon @mickaelandrieu @khouloudbelguith 

there's "No change required" label but...

we can not use new Grid features on Products List, it's regression from 1.6

**Comment by stefanovita** [comment]
I am reopening this issue since this is a very big matter for module developers. If we need to change the listing in old controllers we have to use ListingFieldsModifier hook, we cannot use GridDefinitionModifier. Viceversa, we cannot use ListingFieldsModifier in modern controller. This means that we have to look for any new Prestashop version, and check if the controller is upgraded to modern, and remove the old ListingFieldsModifier hook and add the GridDefinitionModifier hook. This is a mess since we wold have to maintain different module versions for each Prestashop version! The other solution is to register always both the hooks but this is very hard to mantain, since the parameters are different. We saw that for product listing ther is a legacy adapter to the old ListingFieldsModifier hook, although with different signature (bad!), but this is an excpetion that has not been done for the other modern controllers. This leads to great confusion and hard maintenance work.

**Comment by matks** [comment]
Hi, indeed this isse is important.

> The other solution is to register always both the hooks but this is very hard to mantain, since the parameters are different.

This is exactly the right way to do it, which indeed avoids you to have to maintain 2 versions of the same module. If we had reused the same hook name, you would have been obliged to maintain 2 versions of your module.

The fact that parameters are different cannot be avoided as the parameters are related to the very architecture of the page behind, be it a legacy PrestaShop or a modern Symfony form.
It would be impossible to have identical parameters between the "old hook" an the "new hook" because of that. Moreover, modern pages use Twig while legacy pages use Smarty, so anyway you cannot and should not reuse the exact same code.

But your logic can stay the same 😉PrestaShop is a MVC framework, we are migrating the V and the C but your M should stay fine if you have separated correctly the M, the V and the C. This is just formatting, form configuration and rendering.

> This leads to great confusion and hard maintenance work.

No, actually this is the opposite 😉: you will have to, at some point, migrate your module from the legacy prestashop system (smarty + controller + form) to modern Symfony system (Twig + Symfony controller and form). If everything was migrated in PS 1.7.0 you would have needed to migrate all your modules at the same time at the launch !

The fact that BO pages are slowly being migrated, _version after version_, allows you to perform the migration module after module, following the rythm at which the pages get migrated. We release a new minor version every 6 months, so that means you are obliged to migrate modules only twice a year, for the pages that got migrated.

We are doing this incrementally **in order to make it progressive and easier** for you, instead of a big "hello, please modify everything now !" moment. Think about it : in PrestaShop 8, everything will be Symfony and Twig. You are given **years** to migrate from the legacy system to a new one, from PS 1.6 to PS 8.

I dont think a lot of opensource projects allow this much time for users to update their codebase 😄? Moreover we have 1-month long beta periods if you want to anticipate which pages will be migrated.

**Comment by stefanovita** [comment]
Thanks for the reply, but i was wondering how is it possibile to test the hooks for modern controllers when they are not yet available. Do we have to develop in the blind?

**Comment by matks** [comment]
> Thanks for the reply, but i was wondering how is it possibile to test the hooks for modern controllers when they are not yet available. Do we have to develop in the blind?

Well you cannot test something that has not been implemented 😄however, **before a new release you have a 2-months time window to check the modern controllers incoming**.

Indeed what we do is
Day 1: we feature freeze = software enters validation/stabilisation phase, only bugfixes are accepted (= no more migrating)
=> this is the beginning of beta test period
Day 31: we create a first Release Candidate, available for anybody
=> we still wait 1 more month to make sure this Release Candidate is fine
Day 61: we release the new version
=> if no regression have been reported in the past 30 days, the final version is the 1st release candidate

Also, once the new version is out, very few people upgrade their shop right away. So depending whether you sell modules or shops, you dont have to hurry as the number of customers "you cannot sell to" is limited. People upgrade slowly PrestaShop. You've got weeks, maybe months 😄 

However it's better to make a POC during beta period because at this moment if you encounter specific bugs related to your module we can make bugfix 😉. After the release, it's too late, you'll have to use workarounds or wait the next patch.
