### ISSUE TITLE
modifierWsLinkRewrite ... it can't work !

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#11343]
Hi,
Prestashop 1.7.4.4
In classes/Product.php

**$this->link_rewrite is a string** ... could you explain what will do this code ??? Very strange and couldn't have been tested. Is prestashop 1.7 for production or is it better to wait ? It's just a question ...

    public function modifierWsLinkRewrite()
    {
        foreach ($this->name as $id_lang => $name) {
            if (empty($this->link_rewrite[$id_lang])) {
                $this->link_rewrite[$id_lang] = Tools::link_rewrite($name);
            } elseif (!Validate::isLinkRewrite($this->link_rewrite[$id_lang])) {
                $this->link_rewrite[$id_lang] = Tools::link_rewrite($this->link_rewrite[$id_lang]);
            }
        }

        return true;
    }

thx

**Comment by khouloudbelguith** [comment]
@grabelle, did you have any issue due to this function?
Could you please add steps to reproduce it.
Thanks!

**Comment by grabelle** [comment]
Just imagine that you have 2 languages with id 1 and 2 ...
Product name "PIZZA"
Tools::link_rewrite($name) = "pizza"
$this->link_rewrite[1] = "i";
$this->link_rewrite[2] = "z";
>> what is that for ?
>> I'm sure you see the problem ?

**Comment by grabelle** [comment]
$this->link_rewrite must be an array ... not a string. But I guess it will impact other code

**Comment by khouloudbelguith** [comment]
ping @eternoendless @PrestaShop/prestashop-core-developers any ideas?
Thanks!

**Comment by eternoendless** [comment]
Hi @grabelle 

If you look closely at the field declaration [in this piece of code]( https://github.com/PrestaShop/PrestaShop/blob/1.7.4.4/classes/Product.php#L387-L397), you'll notice the `"lang" => true` setting. It indicates that this property is language-dependent.

When the ObjectModel is loaded, it will go fetch this property in the related `_lang` table (`ps_product_lang` in this case) for all languages, and store it as an array of strings indexed by `id_lang`.

For what is worth, this field and the provided function were added in PrestaShop 1.6.0.3 [more than four years ago](https://github.com/PrestaShop/PrestaShop/commit/78bad5ccce5ca204f43b4b18c4bfca0afaa9c29b) , and has remained largely unchanged since.

> Is prestashop 1.7 for production?

There are thousands of 1.7 shops currently in production, and people we spoke with are generally very happy with it.

**Comment by grabelle** [comment]
@eternoendless : Thanks a lot for your explanation and your work.
