### ISSUE TITLE
Allow themes to override jquery version

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#11352]
**Is your feature request related to a problem? Please describe.**
I really don't understand the need to force the jquery version regardless of the theme used. The jquery version should have a default but themes should be able to override jquery. This just doesn't make sense, especially when the currently used jquery version has known vulnerabilities.
**Describe the solution you'd like**
I would propose moving the default jquery in js/jquery/jquerydefault.min.js that can be overritten by customtheme/js/jquery/jqueryversion.min.js. The strange thing is there already is a jquery 1.1.10 there, probably to be used by the admin theme.
So, jquery should no longer be bundled in themes/core.js, but in js/jquery/jquery-default-version.min.js, making it easy to be overriden by theme developers.
**Alternative**
Remove jquery from core.js and bundle it via webpack in themes/classic/assets/js/theme.js. Of course, this would create problems with older themes that would need to be updated, so maybe it's better to stick to the js/jquery folder.

**Comment by MathiasReker** [comment]
👍 

Btw, why not update jquery to the latest version for 1.7.5.x if it has known vulnerabilities?

**Comment by kpodemski** [comment]
It's not good idea. Think about modules and backward compatibility.

**Comment by MathiasReker** [comment]
@kpodemski I am not sure what the vulnerabilities are about, but if they are critical I would say safety first.

**Comment by khouloudbelguith** [comment]
Hi @MathiasReker,

@eternoendless said, unfortunately, we cannot upgrade Bootstrap and jQuery on the classic theme until the next major version. Bootstrap changed their layout system since alpha 6, which is a backward compatibility break that would affect all of the classic's child themes.
If you are concerned about these vulnerabilities, take a look at [Classic-Rocket](https://github.com/PrestaShop/classic-rocket/), which is a community port of Classic to Bootstrap 4.1
@eternoendless, what do you think about the @rdy4ever suggestion?

**Comment by eternoendless** [comment]
As @kpodemski said, we cannot upgrade jQuery to the next major version right now because of the compatibility issues that would create with current themes and modules, which depend on its current behavior. We will upgrade it on the next major version of PrestaShop.

On your @rdy4ever's idea of making jQuery overridable:

While at first it may seem nice for flexibility, in the end it would be pretty pretty much the same as not including it at all and making it up to the theme developer to choose which library they want to use. If we let each theme use the libraries they want instead of making them share a common baseline, it would become extremely hard for module developers, because they won't be able to know which libraries they can rely on.

On the known vulnerabilities of jQuery 2.2:

There's only one vulnerability that I'm aware of, [CVE-2015-9251](https://nvd.nist.gov/vuln/detail/CVE-2015-9251), which is of "moderate" severity. It involves a possible XSS when fetching foreign content via ajax.

According to [this comment](https://github.com/jquery/jquery/issues/2432#issuecomment-403761229), it can be patched by inserting a small code snippet. We just need to find the right place to do it.

**Comment by rdy4ever** [comment]
Hi, @eternoendless
I was thinking that by separating jquery from core.js, two things would happen:
1. In most use cases, all themes and modules would still be able to rely on the default jquery 2.2.4 included in js/jquery folder by default. Nothing changes here.
2. If a theme developer makes his theme using a higher jquery version than the default, he just has to include it in it's theme_name/js/jquery folder to override default.
There, is, however, the problem with modules that may not work good with the higher jquery version. To overcome this, I think that the theme that uses a higher major jquery version than the default 2.2.4, should also include[ jquery-migrate](https://github.com/jquery/jquery-migrate). This should take care of the problem.

Another approach, could be module based, [like Drupal does](https://www.drupal.org/project/jquery_update). Include a default jquery version, but make a module called "jquery update", where the user will be able to choose a different jquery version (and jquery-migrate) to use in the FO. The module could have 3 options:
1. use jquery from [jsDelivr CDN](https://www.jsdelivr.com/)
2. use jquery from the module (and include some versions  in the module's js/jquery/version folder). Updating the module, would give newer jquery versions to choose from (while removing older, unsupported versions).
3. choose wether to use jquery-migrate and which version, simillar to jquery

**Comment by eternoendless** [comment]
Maybe jQuery migrate could be a way to upgrade while keeping backwards compatibility 🤔

**Comment by colinegin** [comment]
Duplicate of #13829
