### ISSUE TITLE
unable to add attachments to a product \ item section

### ISSUE THREAD

**Issue by rattala** [PrestaShop/PrestaShop#11351]
**Describe the bug**
Inside the backend is impossible to add any attachment to a product item. The ADD button is disabled.
Tried to pickup .pdf - .jpg - docx -> same behaviour. Try to remove spaces from attachment's name and to shorten name string or description's string -> same result.
found the same issue in previous versions (tagged as "resolved"), look at here:
http://forge.prestashop.com/browse/BOOM-1668
http://forge.prestashop.com/browse/BOOM-2593

**To Reproduce**

1. Go to your shop's backend - Product Catalog - Products
2. select a product \item and go to the Options tab
2. select a file to add as attachment (browse and confirm)
3. enter the attachment's description
4. Save the page just to be prudent
5. you can still see the ADD button greyed out \ disabled
6. no attachment can be added

**Screenshots**
![disabled_attachment](https://user-images.githubusercontent.com/44939891/48310829-dc143600-e595-11e8-95d5-dc099d9180a3.JPG)  ( Google Chrome 70.0.3538.77)

issue seems to be browser related, in fact using Internet Explorer 11 I can succesfully add an attachment
![disabled_attachment_ie11_ok](https://user-images.githubusercontent.com/44939891/48311084-4b8c2480-e59a-11e8-9f2b-4127b8867329.JPG)

 but there's the additional problem that I can see the attachment nr. zero that is not viewable in the front-end of the shop
![missed_attachment](https://user-images.githubusercontent.com/44939891/48311118-3237a800-e59b-11e8-999b-9e28d25eca42.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.2.10

**Comment by khouloudbelguith** [comment]
Hi @rattala,

I did not manage to reproduce the issue with the last version 1.7.4.4 / PHPv7.2.8.
I used a Google Chrome Version 69.0.3497.81 (Build officiel) (64 bits)
I attached a video record
https://drive.google.com/file/d/1SrxF4QplpjExa-ChPo_54FiYSOZ-yN76/view
![image](https://user-images.githubusercontent.com/16067358/48340498-0ab01080-e66b-11e8-9bde-30b4fd8f4ce8.png)
Thanks to check & feedback.

**Comment by rattala** [comment]
Hi :-) I checked again and ...now it partly works, maybe a magical update or mess with the browser with the code handling?
But however I can't save the page from which I have updated the attachment list and also it's poor that I can't remove attachments by the GUI interface,..
Please look at here: https://drive.google.com/file/d/1gVb5ZMYn10cDx9kGib48TDY2eCThV0EP/view?usp=sharing
and here:
https://drive.google.com/file/d/18SNatlD4X2ItpHezU2RJpdBEWtgTRwtY/view?usp=sharing
So now the question seems to be...why I can't save the page ?
Thanks for your support, have a nice day

**Comment by khouloudbelguith** [comment]
@rattala, I didn't manage to reproduce the issue, could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by matrixino** [comment]
This is happening to me too. The problem is that in the BO, where you assign the downloads to product (the file list), the list starts with id 0. While in the DB the attachment table starts with id 1. So there is a discrepancy of 1 in the IDs.

NVM: The problem is that there is no entry in attachment_lang for some attachment. Not sure how that happended.

**Comment by khouloudbelguith** [comment]
@matrixino, did you delete any language?
Are there any errors in your log file? any exception displayed?
Thanks!

**Comment by matrixino** [comment]
> @matrixino, did you delete any language?
> Are there any errors in your log file? any exception displayed?
> Thanks!

It is possible but I'm not sure (it's a customer site, we are a agency), but anyway the missing translations are for the only one available lang.
It's also possible that this was caused by deleting a multishop? I know for sure that this shop was a multishop before, one for each country/lang, which was later split in multiple PS installation with a single site on each.

**Comment by khouloudbelguith** [comment]
@matrixino, I tried to delete the language with id_language=1, but I did not manage to reproduce the issue either.
I tried also to delete the second shop when multishop is enabled, then I disabled the multishop context, but there's no problem.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

**Comment by matrixino** [comment]
> @matrixino, I tried to delete the language with id_language=1, but I did not manage to reproduce the issue either.
> I tried also to delete the second shop when multishop is enabled, then I disabled the multishop context, but there's no problem.
> We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.

Sorry I can't help, this was told to me way later than when it happened, I don't have any logs. We just solved it by adding a title for the default lang in the Catalog->Files section. Never happened again.

**Comment by khouloudbelguith** [comment]
Hi @rattala,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!

**Comment by rattala** [comment]
I noticed the same behavior mentioned by Matrix. Hope this helps



Inviato da Libero Mail per iOS


lunedì 19 novembre 2018, 18:06 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by rattala** [comment]
Hi, just for info I have no customizations and just configured virtual host the basic minimal way



Inviato da Libero Mail per iOS


mercoledì 21 novembre 2018, 14:45 +0100 da notifications@github.com  <notifications@github.com>:
