### ISSUE TITLE
Installation fail: "Cannot download language pack "en"

### ISSUE THREAD

**Issue by titamrtn** [PrestaShop/PrestaShop#11355]
**Describe the bug**
It is a fresh install of prestashop and i got this error at 23% "Cannot download language pack "en""

**To Reproduce**
Just install prestashop 1.7.4.3 with PHP 7.2 (i don't know if it's because of php version)

**Screenshots**
![screenshot from 2018-11-12 12 04 59](https://user-images.githubusercontent.com/5078563/48337167-46e76f00-e673-11e8-9084-f975c50af764.png)

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @titamrtn,

I did not manage to reproduce the issue with PS 1.7.4.3 & PHP v7.2.
The installation is ok.
![image](https://user-images.githubusercontent.com/16067358/48338263-7b542e80-e665-11e8-8d1a-6c2735994cdb.png)
But, it could be a problem of a network which is not available, as described in this issue: #10456 Thanks to check again & feedback.

**Comment by titamrtn** [comment]
Network work fine. But i tried the _"workaround"_ set `.... $is_addons_up = false;` but still have the same result.

**Comment by khouloudbelguith** [comment]
@titamrtn, if you try to enable the debug mode & re-install the shop, is there any exception?
You can enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`
… and change it to:
`define('_PS_MODE_DEV_', true);`
Thanks!

**Comment by titamrtn** [comment]
There is no exception, just a deprecated warning on step 3 :"System compatibility"
```
Deprecated: Function create_function() is deprecated in /var/www/html/ps/var/SymfonyRequirements.php on line 551

Deprecated: Function create_function() is deprecated in /var/www/html/ps/var/SymfonyRequirements.php on line 700

Deprecated: Function create_function() is deprecated in /var/www/html/ps/var/SymfonyRequirements.php on line 551

Deprecated: Function create_function() is deprecated in /var/www/html/ps/var/SymfonyRequirements.php on line 700
```

**Comment by titamrtn** [comment]
Also i tried download and install ps 1.7.4.4 and i have the same issue

**Comment by khouloudbelguith** [comment]
Hi @titamrtn, 

About the `Deprecated: Function create_function() is deprecated in /var/www/html/ps/var/SymfonyRequirements.php`, it is a different issue. Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9409 to solve the issue.
It is fixed in the next release 1.7.5.0.
What is the country/language did you chose during the install?
Thanks!

**Comment by titamrtn** [comment]
I tried both french and english. Got similar error Cannot download language pack "fr/en". There is no default language pack included in installation? I think it can be good to have default language(maybe english) which can be used when download failed.

**Comment by khouloudbelguith** [comment]
@titamrtn, is there any errors in your PHP file log?
Thanks!

**Comment by titamrtn** [comment]
Nothing in php and apache2 log

**Comment by khouloudbelguith** [comment]
@titamrtn, could you try to install Prestashop in another host, check & feedback.
Thanks!

**Comment by titamrtn** [comment]
I got  same result in another host. I also tried in another computer with same config. Still have the same error.

**Comment by titamrtn** [comment]
Hi @khouloudbelguith ,

Is there any way to download language pack manually and skip this part of installation?

**Comment by khouloudbelguith** [comment]
Hi @titamrtn,

Try to remove ./app/Resources/translations/en-US/en-US.zip and retry. Look like something goes wrong during download.
Thanks!

**Comment by titamrtn** [comment]
There is no ./app/Resources/translations/en-US/ directory. the only directory is /app/Resources/translations/default

**Comment by khouloudbelguith** [comment]
@titamrtn, are you trying to install the shop behind a proxy server?
It could be a problem & it will be stopped by the proxy filters.
Thanks!

**Comment by alouimohamedhabib** [comment]
Hello 
I actually faced same issue running Prestashop from docker container based on **docker-compose** file which it self cause issues at the beginning of containers setup
Ps version 1.7.4.4,  second refresh and program run correctly
Something is unstable!

**Comment by khouloudbelguith** [comment]
Hi @alouimohamedhabib,

Did you use this solution https://github.com/PrestaShop/PrestaShop#docker-compose to deploy PrestaShop?
Thanks!

**Comment by alouimohamedhabib** [comment]
In my case i used both the docker-compose file from downloaded zip und from github repo https://github.com/PrestaShop/docker

**Comment by stoycho** [comment]
I have the same problem with installing 1.7.4.4 on Fedora 29 with apache httpd. I think the problem is that the default configuration of SELinux and the new default way of running PHP with FastCGI (php-fpm) are inconsistent. Or I misconfigured the SELinux in some strange unknown to me way.
I did some debugging of the installation of PrestaShop and turns out all the "curl_exec" calls during the installation return "false", and when it fails to download the translations it throws exception and halts the installation. Unfortunately I have no idea (yet) how this SELinux thing works, so I cannot precisely configure it to allow my php-fpm service to access the internet, but when I shut it down with "setenforce 0", then the install of PrestaShop pass Ok. Another way out of this situation is, I guess, to switch the php to run in the old way with mod_php in httpd.

So I'll have to learn a bit SELinux to understand how to tune it to let my php-fpm to communicate with the world. Does anybody have some quick advice on the subject?

**Comment by PierreRambaud** [comment]
You can check what is needed to do on "httpd" you can use:
```bash
getsebool -a | grep httpd
```
 or directly:
```bash
setsebool -P httpd_enable_cgi on
setsebool -P httpd_unified on
setsebool -P httpd_builtin_scripting on
```

**Comment by stoycho** [comment]
Thank you very much for the guideline.
I checked those 3 options, and they were already enabled (I suppose by default), but it wasn't enough.
I saw in my /var/log/audit/audit.log that it adds the following lines during the PrestaShop installation:
denied  { name_connect } for  pid=xxxx comm="php-fpm" dest=80 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket permissive=0
So I searched a little further and found this article at Red Hat Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1528722
I tried the first suggestion and enabled the 'httpd_can_network_connect'.
After that the installation of PrestaShop 1.7.4.4 passed well.

I am not sure if that is the optimal thing to do from security point of view though...

Thanks again.

**Comment by neocarvajal** [comment]
I have the same problem on Ubuntu 18 with prestashop 1.7.4.4 and php 7.2

![error](https://i.ibb.co/X2GTNvk/Screenshot-from-2018-11-25-21-30-50.png)

**Comment by khouloudbelguith** [comment]
Hi @neocarvajal,

As I said before, it could be a problem of a network which is not available.
Thanks to check again & feedback.

**Comment by khouloudbelguith** [comment]
Hi,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!

**Comment by kalugauli** [comment]
Hello! Same problem. Prestashop 1.6.23   Cannot install language "Русский (Russian)"
![pic1](https://user-images.githubusercontent.com/46563199/51078520-28c7da80-16c7-11e9-9ae5-73c17711432b.jpg)

**Comment by khouloudbelguith** [comment]
HI @kalugauli,

This issue is currently closed, can you open a new one with more information about your configuration.
Thanks!

**Comment by agunk31** [comment]
you can read my tutorial in comment this
https://github.com/PrestaShop/PrestaShop/issues/10161#issuecomment-465403165

**Comment by Anthony-Kiiru** [comment]
This video has the fix (a hack!) https://www.youtube.com/watch?v=_rVxHGdzSeY
Just remember to remove the comments after successful installation :)

**Comment by EdgePhil** [comment]
Change the PHP version to 7.1 or 7.2 , restart all services. Drop your database and create a new one. Best you restart your system too. Then begin your prestashop installation again.
Hope this helps someone.

**Comment by Aadhavan** [comment]
Network is the issue

**Comment by Aadhavan** [comment]
Error because of Slow network

**Comment by 234146326** [comment]
![image](https://user-images.githubusercontent.com/17285770/80626204-a7918400-8a80-11ea-8f8a-df9431279ba4.png)
I successfully installed using the command line.

Summary: I installed it all day.Found that the language pack cannot be downloaded because of the network.

I ended up using SS proxy.finish installation.

Share as follows:

`php index_cli.php --db_server=127.0.0.1:8889 --db_name=prestashops --db_user=root --db_password=root --language=en —country=fr —firstname=Demo —lastname=Prestashop —email=demo@prestashop.com —password=prestashop_demo —db_create=1`

**Comment by eossa** [comment]
I solved with `setsebool -P httpd_can_network_connect on`

**Comment by theFra985** [comment]
For any future lurker the issue seems to be also related to old docker daemon versions being used to run the image relating to [this](https://stackoverflow.com/questions/59911649/fatal-unable-to-access-link-getaddrinfo-thread-failed-to-start).

**Comment by zer0yu** [comment]
> @titamrtn, if you try to enable the debug mode & re-install the shop, is there any exception? You can enable the Debug Move using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:
> 
> `define('_PS_MODE_DEV_', false);` … and change it to: `define('_PS_MODE_DEV_', true);` Thanks!

After enabling this option, if you see that the download file fails, you can directly modify the timeout time of the curl. The default value is 5 too short.

**Comment by call0fcode** [comment]
In my case there was a problem with my company's proxy. After disabling it (it's kind of a VPN) everything work having to do anything else.
