### ISSUE TITLE
Prestashop Module issue

### ISSUE THREAD

**Issue by rahuljj123** [PrestaShop/PrestaShop#11365]
**Describe the bug**
When i tried to install prestashop theme it is showing **Cannot install module smartblog. The module is invalid and cannot be loaded.**
I have purchased new theme from prestashop addons and they are not replying. 
Please help me out on this, as i have been lacking in this..

Theme link:    https://addons.prestashop.com/demo/FO32068.html

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/45000769/48408664-de29f080-e75f-11e8-9018-df7c7eab4a9c.png)

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @rahuljj123,

The error is NOT caused by PrestaShop. The theme tries to hook a module, it does not provide, not already installed on the shop and which is not available for free on the marketplace.
Our developer made the error messages a little bit clearer with https://github.com/PrestaShop/PrestaShop/pull/9089 and this is the best that he can do. 
As it's not the default theme, provided by Prestashop, we can't do anything with this. 
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by kpodemski** [comment]
Contact theme or module author. It's not issue related to PrestaShop.

**Comment by rahuljj123** [comment]
Yes i know but can u help me out.

**Comment by rahuljj123** [comment]
> Contact theme or module author. It's not issue related to PrestaShop.

I am new to prestsahop can u please let me know they are not replying...

**Comment by khouloudbelguith** [comment]
@rahuljj123, you need to find the module which causing this issue, in fact, which module the theme tries to hook it.
Thanks!

**Comment by rahuljj123** [comment]
I deleted that module, but after that another module started showing this error......

**Comment by khouloudbelguith** [comment]
@rahuljj123, you need to check all modules one by one.
Thanks!

**Comment by rahuljj123** [comment]
Ohk thanks..
