### ISSUE TITLE
[SF Migration] Improve form theme

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#11389]
Type: tech-issue

Todo:
- [x] Improve form theme https://github.com/PrestaShop/PrestaShop/pull/13875
- [ ] [SF Migration] Allows a module to add a field to a form, customize the rendering, choose where it appears, all of this easily #13876

As stated by @mickaelandrieu: for now, the developers are forced to override the view when they add a simple form field to configuration pages. With a consistent form theme, most of the time even us won't be forced to integrate pages we are migrating

**Comment by matks** [comment]
Scoped into 1.7.6 as discussed with @eternoendless

**Comment by colinegin** [comment]
@matks can I close this issue ? It seems like the related PR has been merged !

Thanks

**Comment by matks** [comment]
> @matks can I close this issue ? It seems like the related PR has been merged !
> 
> Thanks

No, the PR solves it partially only 😄

**Comment by colinegin** [comment]
Damn it ! 
Do you think you can update the description so that we know what's left and that there is another PR needed ?

**Comment by mickaelandrieu** [comment]
@colinegin what was merged have nothing to do with my issue: it's an improvement, not a bug fix.

Basically, we're now able to provide help messages with ease on forms.

The critical issue we have since 1.7.0 (*and which make the integration of forms for developers painful*) is that we have a terrible form theme.

The form theme is that we make us (and PrestaShop developers) able to render nice forms from PHP code. But.. currently, our back office is a mix of our form theme + markup added by every developer.

If you need to compare, you can take a look at our way to integrate forms [currently](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/performance.html.twig) (353 lines) and what should be [our way](https://gist.github.com/mickaelandrieu/ca53081e19032628a16ce18c3e6ec3a5) to integrate forms (93 lines).

As we migrate a lot of pages, the more we wait and the more pages we will have to update.

Sadly, this issue has been delayed from 1.7.3 to 1.7.4 and from 1.7.4 to 1.7.5, from 1.7.5 to 1.7.6 and now from 1.7.6 to 1.7.7.

I hope it will be fixed in 1.7.7, so the PrestaShop developers won't have to override templates when they add a new field to their forms (common need in `Configure` section of the back office, but also in `Entity` forms).

**Comment by eternoendless** [comment]
Related: #13876

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15130
