### ISSUE TITLE
rror: Access to undeclared static property:

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#11395]
**Describe the bug**
HTTP 500 Internal Server Error in BO

**To Reproduce**
1. enable Debug mode
2. create a DB backup
3. select any db backup using a checkbox on the left
3. using Bulk actions - click Delete selected
4. click OK
5. Error: Access to undeclared static property: PrestaShopBackup::$definition

**Screenshots**
![screenshot_2018-11-14 error access to undeclared static property prestashopbackup definition 500 internal server error](https://user-images.githubusercontent.com/31688689/48497554-a771da00-e834-11e8-8422-84b86afbd8d8.png)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.30

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.4.4.
But I did not manage to reproduce in the PS1.7.5.0.
So the issue will be fixed in the next release 1.7.5.0.
https://drive.google.com/file/d/1INoq8TEbxmIN1O4xC99HMQrp_CRTH8ww/view
I close the issue, feel free to open a new one when needed.
Thanks!
