### ISSUE TITLE
Secure Key Missmatch - deleted carts

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#11436]
Sometimes cart secure key is differ then customer secure key.

**To Reproduce**
1. Don't know how, but it started happen when i deleted all carts.
2. Maybe old cookies from users have something to it

**Additionnal information**
PrestaShop version: since 1.7.3, still happens on 1.7.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @slupostrupek,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by slupostrupek** [comment]
host ovh, dedicated server
debian + apache + mariadb + php7.1
prestashop 1.7.4.2

there is no log about it in php / apache. Only prestashop log is saying something and it is log level 1:

 `
23573 | -- | 1 | Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart | Cart | 8681 | 0x	0 | 2018-12-12 11:30:21
-- | -- | -- | -- | -- | -- | -- | --
23571 | -- | 1 | Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart | Cart | 5544 | 0x	0 | 2018-12-12 11:26:32
23572 | -- | 1 | Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart | Cart | 5544 | 0x	0 | 2018-12-12 11:26:32

`
so if my customer can't place order with his cart i am looking to database checking secure key in user table copy it and change it in table of 'cart' to correct it. But that was to much of work and it happend too often to a lot of users so i turned off checking this key in prestashop core files.

Every year in my shop i am also deleting orders (without carts). Maybe this will help to analyze problem.

**Comment by khouloudbelguith** [comment]
@slupostrupek, isn't the same issue with this ticket: #9866?
Thanks!

**Comment by slupostrupek** [comment]
I think it's seperate because they are able to create order. 

Same error occures in this issue but user can't place order which is much worser and user often resigns buying. Not all users reports issue.

**Comment by khouloudbelguith** [comment]
@slupostrupek, We need to retrieve the PHP error log in order to find out what's wrong.
Thanks!

**Comment by futurehousestore** [comment]
Hello guys,
I think both tickets are connected because in my shop both situations occur. For me, the problem started in ver 1.7.4.x but I don't really know when. I never had a problem to place an order and make a payment via any of the available payment methods in my shop, my friend who was testing it for me had no problem as well but I have noticed a lot of not ordered and abandoned carts. As I display a phone number and customers are able to make an order via phone, some of them phoned me up to let me know that there is an issue and they cannot complete the order and make a payment. In every situation (successful or nonsuccessful order) the same error is displayed in BO logs "Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart" I have tried many "fixes" from forums and all over the internet. I have also upgraded to version 1.7.5.0 (which apparently fixes the issue but in reality, it doesn't). This what slupostrupek says about clearing old carts kinda makes sense for me. I hope someone will find a solution ASAP as it is a very serious problem and many companies looses a lot of money and customers because of it.
Kind regards

**Comment by khouloudbelguith** [comment]
@futurehousestore, thanks for your feedback.
This issue is hard to reproduce.
In my case, I did not manage to reproduce the issue with PS1.7.5.0 / PS1.7.4.4
We really need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by futurehousestore** [comment]
Thank you for your reply @khouloudbelguith I never had that problem before and I'm using Prestashop since November 2017. For me, this problem has started around a month, maybe a month and a half ago. Please see the attached pictures and error log. Please note that the error log is one hour ahead (so if on a Prestashop screenshot you see 18:59 in a log the same issue is on 19:59) 
[CMD_SHOW_LOG.txt](https://github.com/PrestaShop/PrestaShop/files/2703980/CMD_SHOW_LOG.txt)
Error from not long ago
![presta1](https://user-images.githubusercontent.com/28427270/50359524-ef330200-0554-11e9-81fd-200d4ab96b32.jpg)
Please note that the error log is quite big as I'm also having some other issues so please scroll down to the bottom.
My payment options are
![presta3](https://user-images.githubusercontent.com/28427270/50359561-1ab5ec80-0555-11e9-882e-f4db83556cbf.jpg)
I'm using since beginning synchronisation modules with Dolibarr and eBay
![presta2](https://user-images.githubusercontent.com/28427270/50359597-37eabb00-0555-11e9-85f7-b4f4fd3d45a3.jpg)
![presta5](https://user-images.githubusercontent.com/28427270/50359612-45a04080-0555-11e9-991a-63c2d4c9dfa4.jpg)
![presta4](https://user-images.githubusercontent.com/28427270/50359613-489b3100-0555-11e9-8bcc-67764a9ab794.jpg)
since Prestashop 1.7.4.x (I don't really remember) I'm using PrestaSpeed module and there is an option to delete abandoned carts and I did it few times before, maybe it did delete the abandoned carts in Presta but not in DB or did it incorrectly (and that may be the real cause of our error at least in my case)
![presta6](https://user-images.githubusercontent.com/28427270/50359779-cbbc8700-0555-11e9-88c1-0e8cc902281d.jpg)
The last order in Presta is ID 4171 Ref: O18121971
![presta7](https://user-images.githubusercontent.com/28427270/50359997-88aee380-0556-11e9-9bdd-cd79fa99357c.jpg)
but in DB the last order looks completely different
![presta8](https://user-images.githubusercontent.com/28427270/50360045-a419ee80-0556-11e9-9915-b82258d00f0d.jpg)
![presta9](https://user-images.githubusercontent.com/28427270/50360054-a8460c00-0556-11e9-8fc7-7b2b88359240.jpg)
Sorry about the "bad screenshots"
I hope this will help.
Kind regards

I forgot to mention that I was for a long time on PHP 5 and now for a month or two I'm on PHP 7.0.33
Maybe PHP version has something to do with it as well. If you need anything else, please don't hesitate to let me know.
Kind regards

**Comment by khouloudbelguith** [comment]
Hi @futurehousestore,

Thanks for your feedback.
In your log file, you have errors in those modules:
1. gmerchantcenterpro module => `PHP Notice:  Undefined index: SCRIPT_URI`
2. stripejs => `PHP Notice:  Trying to get property of non-object`
3. cyberoffice=> `PHP Notice:  Undefined index: id_product_attribute`
4. fastbay1 => `PHP Notice:  Undefined index: epid`
5. mycyberoffice => `PHP Notice:  Undefined index: height`

All those modules are not provided by Prestashop.
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by futurehousestore** [comment]
Thank you very much @khouloudbelguith 
Merry Christmas!

**Comment by khouloudbelguith** [comment]
@futurehousestore, you are welcome!
Merry Christmas & Happy NewYear 2019!

**Comment by khouloudbelguith** [comment]
Hi @slupostrupek,

We need to retrieve the PHP error log in order to find out what's wrong.
Thanks!

**Comment by eandrei** [comment]
I have the same problem! 
Once in a while some customers call and give me this error. 
Today this pissed me off and I debugged and discovered that this happens because of different secure_key on cart.

Now, I checked the database and I had 200 instances with cart secure_key different than customer secure_key. So I had 200 lost orders? 

Any solution on this?

**Comment by khouloudbelguith** [comment]
Hi @eandrei,

Did you use the module MailChimp?
Thanks!

**Comment by eandrei** [comment]
> Hi @eandrei,
> 
> Did you use the module MailChimp?
> Thanks!

Yes I do!

**Comment by khouloudbelguith** [comment]
Hi,

The MailChimp Integration is causing this issue.
As described in the previous ticket: http://forge.prestashop.com/browse/BOOM-5486
I manage previously to reproduce the issue, the MailChimp Module added products to new customer's basket by default.
MailChimp isn't developed by PrestaShop.
You should contact the developer here: https://addons.prestashop.com/en/contact-us?id_product=26957
Thanks!
