### ISSUE TITLE
Full Price indexer crashes the server

### ISSUE THREAD

**Issue by andreic96** [PrestaShop/PrestaShop#11451]
**Describe the bug**
I have issues getting the right number of products of a specific manufacturer, so I am trying to run price indexer on almost 10k products, as I see it to resolve this problem. After I run the full indexer it crashes my server with a 503.

**To Reproduce**
1. Go to 'module page/run from console'
2. Click on 'Full price indexer'
3. Wait till it crashes the server
4. Have to restart the server to work again

**Additionnal information**
PrestaShop version: 1.6.0.8
PHP version: 5.4

**Comment by khouloudbelguith** [comment]
Hi @andreic96,

Did you use the `blocklayered` module to Rebuild entire price index?
![image](https://user-images.githubusercontent.com/16067358/48839097-9ec85900-ed8a-11e8-8eb7-7da96ca9ba31.png)
Thanks!

**Comment by andreic96** [comment]
Hello @khouloudbelguith ,

That's exactly, what I have used. Ran it from admin and also from server through ssh.

**Comment by khouloudbelguith** [comment]
Hi @andreic96,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

There are several different log data that you can add as a file to your ticket:

Server log:

- Apache: /var/log/apache/apache_error.log
- Nginx: /var/log/nginx/nginx_error.log
- IIS: %SystemDrive%\inetpub\logs\LogFiles

PHP error log:

1. Apache: /var/log/apache/php_error.log
2. Nginx: /var/log/php-fpm/default/error.log
3. IIS: %SystemDrive%\inetpub\logs\LogFiles

Console log:

- Firefox and Chrome: press Ctrl+Shit+J or Cmd+Shift+J.
- Internet Explorer and Edge: press F12 then go to the Console tab.

To enable the Debug Move using an FTP client (for instance the free Filezilla tool) try to edit the config/defines.inc.php file. Find the following line in the file:

`define('_PS_MODE_DEV_', false);`
… and change it to:
`define('_PS_MODE_DEV_', true);`

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @andreic96,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
