### ISSUE TITLE
Bug in BO Catalog

### ISSUE THREAD

**Issue by Gionny996** [PrestaShop/PrestaShop#11467]
Prestashop 1.7.7.4, when I open any product from the catalog and click on the "recycle bin" to delete a combination of that product, it is not deleted, I am not given any error in debug mode. I click on delete combination and nothing happens, neither an error message nor nothing

**Comment by khouloudbelguith** [comment]
Hi @Gionny996,

I did not manage to reproduce the issue with PS1.7.4.4.
I attached a video record.
https://drive.google.com/file/d/1mO5jTK9MAsJrIW5_07A_mH3xc7Xqyam7/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report /, unfortunately, doesn't exist
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by Gionny996** [comment]
if you leave me your email I can give you the data to access the BO of the test site and the FTP data

**Comment by khouloudbelguith** [comment]
@Gionny996,

My address mail: khouloud.belguith@prestashop.com

Thanks!

**Comment by khouloudbelguith** [comment]
@Gionny996, I just received the email.
I will check & feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
@Gionny996, in your console log, you have this error `Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR` => This is a network error on your side.
When you visit a webpage, your browser sends a request using SPDY protocol. An outdated browser will trigger an old version of SPDY. Since Google only supports the latest version, your request will result in an error.
Your browser will report an ERR_SPDY_PROTOCOL_ERROR.
Thanks to check & feedback.

**Comment by Gionny996** [comment]
what error do you mean? to that of slowness in payment methods and grafting
a form, or the fact that it does not eliminate the combinations?

Il giorno Gio 22 Nov 2018, 11:52 khouloudbelguith <notifications@github.com>
ha scritto:

**Comment by khouloudbelguith** [comment]
@Gionny996, when I try to delete a combination in the product page, I have this error `Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR`
Thanks!

**Comment by Gionny996** [comment]
how can I solve it?

**Comment by khouloudbelguith** [comment]
@Gionny996, what are the exact steps did you made before this issue occurs?
Did you installed any module?
Did deleted attributes?
Thanks!

**Comment by Gionny996** [comment]
I do not know when the error occurred

**Comment by Gionny996** [comment]
I try with a new installation of prestashop?

**Comment by khouloudbelguith** [comment]
@Gionny996, with fresh installation 1.7.4.4, this issue doesn't exist.
Thanks!

**Comment by Gionny996** [comment]
How can i do for to resolve this problem?

Il giorno Gio 22 Nov 2018, 13:21 khouloudbelguith <notifications@github.com>
ha scritto:

**Comment by khouloudbelguith** [comment]
Hi @Gionny996,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.
Thanks!
