### ISSUE TITLE
Update to the latest version of Font Awesome

### ISSUE THREAD

**Issue by By-oussef** [PrestaShop/PrestaShop#11501]
**Describe the solution you'd like**
Update to the latest version of Font Awesome because the latest version is 5.5.0 it was released in November 2018.

**Comment by eternoendless** [comment]
Hi @By-oussef 

As the Symfony migration moves forward, the Back Office is progressively moving to [Material Icons](https://material.io/tools/icons/?style=baseline). For future proofing, we suggest using Mateerial Icons instead of Font Awesome (which incidentally, is not available on Symfony pages).

Thanks for your understanding
