### ISSUE TITLE
Update to the latest version of symfony

### ISSUE THREAD

**Issue by By-oussef** [PrestaShop/PrestaShop#11500]
Currently Prestashop does not use the latest version of symfony and this poses a problem for our development team. Symfony 4 can significantly improve the performance of a website, it accelerates the web appication.
Is there a road map to update prestashop to the latest version of symfony?
https://symfony.com/4

Thank You for your answer.

**Comment by khouloudbelguith** [comment]
Hi @By-oussef,

 We decided it would make sense to target Symfony 3.4 instead of 2.8. And as Symfony 3.4 requires PHP 5.5.9+, PrestaShop 1.7.4 will require PHP 5.6+ to run.
You also wonder why we did not jump directly to Symfony 4.0? Here are our answers:

- v4 requires PHP 7.1, which is too big of a jump for many shops right now
- v3.4 has all the new features of v4, but it is an LTS version whereas v4 is not
For more details, you can follow this [link](http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/).

I close the issue, feel free to open a new one when needed.
Thanks!
