### ISSUE TITLE
[SF Migration] Apply defensive programming ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#11542]
This issue is a follow-up of code review discussion https://github.com/PrestaShop/PrestaShop/pull/11519#discussion_r236702704

The idea is : how far should we push a defensive programming approach to migrated code ?

Full defensive programming: php code should never trust input (so it needs to validate it). This means lot of checks (sometimes redundant) and exceptions throwing.

Half-defensive programming: trust items that come from trusted source. Applied to current usecase, it means if an object is fetched from database, we trust it has the correct properties because the database schema ensures them.

No defensive programming: trust user input to be correct. Not an acceptable approach 😛

**Comment by matks** [comment]
Please provide your insights 😃 @eternoendless @PierreRambaud @mickaelandrieu @Quetzacoalt91 @jolelievre @tomlev @sarjon

**Comment by PierreRambaud** [comment]
There are two situations when data must be checked.

- When you receive data from a user
- When you want to use the data

More when you manipulate object / array, you can't be sure an index or a property exists. Even if you today you have them, tomorrow, someone can remove them :)

**Comment by jolelievre** [comment]
On user input we must implement validation that's a given
However in the example you linked to with `$field['field_name']` I think it's overkill, if we can't even trust are own interfaces we're gonna put if and exceptions very 5 lines in the code which won't help the readability
Besides in this case if the index does not exist an error is gonna thrown itself no? `Undefined index`

**Comment by PierreRambaud** [comment]
In fact, you can always trust scalar values, but not dynamics elements. More because `stdClass` and `array` don't have interface, structure or anything else.

For example:
* Day 1
Woot what a feature, I need these fields today
```php
$arr = [
  'foo' => 'bar',
  'baz' => null
]:
```
* Day 29
Someone add the capability to don't save null values in database to prevent useless memory usage. And add a new key because he needs it.
```php
$arr = [
  'foo' => 'bar',
  'this' => 'is sparta',
]:
```

Now, you need to refactor each template to check if everything is ok because you thought values and key never change :/

If the index or property don't exists you will have:

```php                                                                                       
$a = new stdClass(); 
$a->foo = 'bar';
var_dump($a->foo);
var_dump($a->baz);

$b = [
    'foo' => 'bar',
];
var_dump($a['foo']);
var_dump($a['baz']);
```

```bash
[3.6.3] got@debian:~$ php test.php 
/home/got/test.php:5:
string(3) "bar"
PHP Notice:  Undefined property: stdClass::$baz in /home/got/test.php on line 6
PHP Stack trace:
PHP   1. {main}() /home/got/test.php:0
/home/got/test.php:6:
NULL
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /home/got/test.php:11
Stack trace:
#0 {main}
  thrown in /home/got/test.php on line 11
```

Which is not acceptable for a user :/

This is one reason why Doctrine use Collection / Object with accessors, (thing we don't have). We could plan to trust `array`and `stdclass` if we have proper ObjectModel.

**Comment by mickaelandrieu** [comment]
> thing we don't have

Are you sure? ;)

![collections](https://user-images.githubusercontent.com/1247388/49367311-fef4be80-f6eb-11e8-9ac1-a00b59d99933.png)

Collections are a structure I'm pushing into the PrestaShop code since 1.7.3.x: we have many reasons to use it:

* move the expected manipulations of a data into meaningful functions;
* store them into a dedicated object;
* "type-hintables";
* validables;
* unit testables;
* discoverables (thanks to IDE features);
* and so on...

> Full defensive programming: php code should never trust input (so it needs to validate it). This means lot of checks (sometimes redundant) and exceptions throwing.

Because we're stuck with PHP5, this is not like we have the choice: it's full or unsafe, sadly.
