### ISSUE TITLE
Prestashop 1.7.4.4, Putenv function

### ISSUE THREAD

**Issue by matesbu** [PrestaShop/PrestaShop#11552]
Hi,

after upgrading to version 1.7.4.4 I can't get to back office login page because of error 500. I turned on debug mode and it says the problem is with disabled function putenv. I googled it and there is one same case on forge.prestashop.com: http://forge.prestashop.com/browse/BOOM-6194 , but it was solved with provider. My provider isn't able to solve it because of security reasons, but they told me I can figure it out by editing .htaccess file or stoping the putenv script.

Any ideas how?

**Comment by khouloudbelguith** [comment]
Hi @matesbu,

Some server disables `putenv` because of security reason.
Your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
We can't do anything with this. 
You should contact your host provider, they are the only ones to help you with it.
Thanks!

**Comment by matesbu** [comment]
so there is no chance to solve it with htaccess or some other way? I don't unerstand, why new prestashop (1.7.4.4) needs this function while old version (1.7.2) didn't...
