### ISSUE TITLE
Impossible to create or edit CMS Page, missing databasefield after upgrade

### ISSUE THREAD

**Issue by netdrag** [PrestaShop/PrestaShop#11581]
The field head_seo_title is missing in the database table cms_lang after an upgrade from 1.7.4.3 to 1.7.5-beta1. 
So its impossible to create a CMS Page. The error message in the frontend doesn't say anything about it, just that there was an error updating the cms (with empty brackets where the database error should be).

PrestaShop version: 1.7.5-beta1

**Comment by khouloudbelguith** [comment]
Hi @netdrag,

It looks like something went wrong with your update and don't have some of the database columns that were added for 1.7.5.0
The solution is to add the missing columns to your database schema.
You can find the schema changes from 1.7.4.3 to 1.7.5.0 by looking at this file: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.x/install-dev/upgrade/sql/1.7.5.0.sql

You can find the full schema for 1.7.5.0beta1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0-beta.1/install-dev/data/db_structure.sql
Thanks to check & feedback.
Just for your information, the beta version is only for testing and currently, it is not possible to upgrade from 1.7.5.0beta1 to the stable version 1.7.5.0.
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @netdrag,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
