### ISSUE TITLE
multiple customer use the same id_cart, stealing each other

### ISSUE THREAD

**Issue by Bonobomagno** [PrestaShop/PrestaShop#11592]
**Describe the bug**
I checked on db, new user start with the same id_cart. 
So when you login for the first time, you are stealing the cart from an other customer, that now maybe create a new or steal it from an other customer.
We disabled override and non native modules, but the issue is still present

**To Reproduce**
We had an old 1.6 version, so we did the 1click upgrade to 1.7.x and after 
we migrated customer/product/order/cart etc data to this new prestashop1.7.4.4 istance

I've checked the db, and what happens is that the last cart record change the id_customer data, moving the last cart to a new user. Instead of just creating a new cart record.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.4.4
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @Bonobomagno,

Did you use the MailChimp module?
Thanks!

**Comment by Bonobomagno** [comment]
Yes, but i disabled every override and non native modules from the performance page

**Comment by khouloudbelguith** [comment]
@Bonobomagno, "Disable non PrestaShop modules" does not work, here's the issue: #9965.
Your issue occurs due to the mail chimp module.
This is a previous ticket: http://forge.prestashop.com/browse/BOOM-5486 about this issue.
MailChimp isn't developed by PrestaShop.
https://addons.prestashop.com/en/contact-us?id_product=26957
I close the issue, feel free to open a new one, when needed.
Thanks!

**Comment by Bonobomagno** [comment]
OMG, disabling mailchimp, worked.
Damn mailchimp.
