### ISSUE TITLE
Impossible to loggin or retrieve password

### ISSUE THREAD

**Issue by bijouxmexicains** [PrestaShop/PrestaShop#11727]
Last week I have changed my domain names from latapatia.fr to bijouxmexicains.fr ; I have moved my datas from my previous domain name to the new one and the same for my database. 
Thus i was accessing my back office using my previous domain login (alejandra@latapatia.fr). It worked fine for a couple of days. I changed it during my last session for thomas@bijouxmexicains.fr
This week end I tried to log in my backoffice but it was not working anymore. Tried to reinitiate my password using my old loggin : not working. Then using my new loggin thomas@bijouxmexicains.fr : email sent ; but actually i'm never receiving it.
 
I need your help please because i started to talk about my website and now i can't neither access my back office nor my linked mail adress

**Additionnal information**
PrestaShop version: 1.7.1.2

**Comment by luisjsolsona** [comment]
Hi,

This is not an official solution...but it works....  open your MySQL

Go to ps_employee

UPDATE `ps_employee` SET `passwd`= md5(‘<cookie_key><yourpass>’) where `email`='youremail@domain.com'

<cookie_key> you can find it in parameters.php (…/app/config/)

Regards

**Comment by bijouxmexicains** [comment]
Hi mistik
Can't find ps_employee in my MySQL, might it have another name ?
Tx

**Comment by bijouxmexicains** [comment]
ok did that changes
but still
i can't access my backoffice using this email and password. It keep saying account not existing or wrong password.
and then if i do reset password, i put the same mail adress in the reset password form -> never receiving the reset mail !

**Comment by khouloudbelguith** [comment]
Hi @bijouxmexicains,

Here's the solution to rest the password in your PrestaShop project manually.
So before doing any changes to your live database, I would highly recommend making a backup, or maybe even two!

First, you need to find out your COOKIE KEY which is in a new position since PrestaShop 1.7. Use your file manager to navigate to the app/config folder. Open the file parameters.php and find the row as seen in the picture:
![image](https://user-images.githubusercontent.com/16067358/49854876-d788aa80-fdeb-11e8-8df8-752cf0c11ad3.png)
Switch to phpMyAdmin and navigate to your PrestaShop database. Find the table PREFIX_employee and click BROWSE.
PS: PREFIX is the prefix of your tables, t could be for example ps.
![image](https://user-images.githubusercontent.com/16067358/49855029-436b1300-fdec-11e8-9a46-b45400d44daf.png)
Click on the edit button at the first row.

Scroll down to the field labeled passwd and clear the field from your old encrypted password. Now paste the COOKIE KEY followed by your new password, in this example newpassword. The cookie key and the new password have to be pasted behind each other without any blanks or other unwanted characters!

Click on the dropdown and select MD5 as our function. Scroll down to the bottom and select GO.
![image](https://user-images.githubusercontent.com/16067358/49855053-57167980-fdec-11e8-9abe-f5c3f6581e22.png)

Thanks to check & feedback.

**Comment by bijouxmexicains** [comment]
Hi Khouloud

I indeed followed this operation.

but still the access to my back office is not working using the mail loggin
and password I wrote in my database in the employee table.
Something is strange also : when I'm asking for password reset through your
website from , I'm never receiving the mail

How can I check this please ?

thx

Le mer. 12 déc. 2018 à 09:01, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
@bijouxmexicains, you are not receiving an email, it could be a configuration problem.
As described in our documentation, http://doc.prestashop.com/display/PS17/Email you can follow the steps to configure your shop.
In the PREFIX_employee table, you can check your mail login, the password, you can reset it as I described above.
Thanks!

**Comment by rdy4ever** [comment]
Hi @bijouxmexicains 
Could you check the table `ps_shop_url` in your database to see if `domain` and `domain_ssl` match the new domain name?
You might still have the old domain enteries there, if you haven't already changed them. The few days that your login still worked could be related to DNS propagation and there is a possibility that you were actually accessing the old hosting account.

**Comment by khouloudbelguith** [comment]
@bijouxmexicains, any news about your issue?
Thanks!

**Comment by bijouxmexicains** [comment]
ok, password is not changed, according your very detailed help guyz, thank you
i have this mail issue still but nothing to do with my back office access so THIS ISSUE IS FIXED
thanks a lot

**Comment by khouloudbelguith** [comment]
Hi @bijouxmexicains,

Thanks for your feedback.
Feel free to open a new one when needed.
Thanks!
