### ISSUE TITLE
module statsvisits error when download csv on 1.7.4.3

### ISSUE THREAD

**Issue by jcriadop** [PrestaShop/PrestaShop#11758]
Error when try to download csv file from stats visits on Prestashop 1.7.1.3.

Go to Statistics Tab and try to export to csv files. Prestashop show error 500.

Problem:

var $query must contain querys on array, but is not defined like an array.

Solved:

Edit modules/statsvisits.php and add array definition on public function setOption :

![issue1](https://user-images.githubusercontent.com/7642235/49927666-be9cf980-febe-11e8-9ae3-62c3ff5b674c.png)

Now you can download csv files with stats exported.

**Comment by khouloudbelguith** [comment]
Hi @jcriadop,

Thanks for your report.
Could you please provide me a screenshot from your BO before after the bug?
@jcriadop, what is the exact version of the module statsvisits did you use?
is it version 2.0.2?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jcriadop,

This issue is reproduced with PS 1.7.5.0rc1 / 1.7.4.0, only if the debug mode is enabled.
![image](https://user-images.githubusercontent.com/16067358/49932671-ecd40680-fec9-11e8-9470-220533110324.png)
![image](https://user-images.githubusercontent.com/16067358/49932633-d2019200-fec9-11e8-8f48-2c0df634d79c.png)
When Debug mode is disabled => OK.
![image](https://user-images.githubusercontent.com/16067358/49932724-0aa16b80-feca-11e8-9070-030d6923718e.png)
Thanks!

**Comment by matks** [comment]
Might be fixed by https://github.com/PrestaShop/statsvisits/pull/3

**Comment by jcriadop** [comment]
Fails even with debug disabled. Better change $query definition on top, not on method :)

**Comment by marionf** [comment]
@jcriadop PrestaShop/statsvisits#3 doesn't fix the issue for you ?

**Comment by jcriadop** [comment]
Yes, only said that on my Prestashop new install fails with and without debug mode active.

**Comment by marionf** [comment]
@jcriadop could you please open a new issue if it's not related to this one ?
