### ISSUE TITLE
Weak password policy

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/PrestaShop#11752]
Thanks Jhon Ken

Some websites prevents the users to use password constructed of character combinations that otherwise meet company policy, but should no longer be used because they have been deemed insecure for one or more reasons, such as being easily guessed, following a common pattern, or public disclosure from previous data breaches. 

Steps to reproduce: 
- Go to signup page
- Create an account by typing your email address and your password same as your email.
- Hit "Sign Up for " button.
- Your account will be created.

Some policies suggest or impose requirements on what type of password a user can choose, such as:

A key concern when using passwords for authentication is password strength. A "strong" password policy makes it difficult or even improbable for one to guess the password through either manual or automated means. The following characteristics define a strong password:

### Implement Proper Password Strength Controls

A key concern when using passwords for authentication is password strength. A "strong" password policy makes it difficult or even improbable for one to guess the password through either manual or automated means. The following characteristics define a strong password:

- Password Length
    - **Minimum** length of the passwords should be **enforced** by the application. Passwords **shorter than 8 characters** are considered to be weak ([NIST SP800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html)).
    - **Maximum** password length should not be set **too low**, as it will prevent users from creating passphrases. A common maximum length is 64 characters due to limitations in certain hashing algorithms, as discussed in the [Password Storage Cheat Sheet](Password_Storage_Cheat_Sheet.md#maximum-password-lengths). It is important to set a maximum password length to prevent [long password Denial of Service attacks](https://www.acunetix.com/vulnerabilities/web/long-password-denial-of-service/).
- Do not silently truncate passwords. The [Password Storage Cheat Sheet](Password_Storage_Cheat_Sheet.md#maximum-password-lengths) provides further guidance on how to handle passwords that are longer than the maximum length.
- Allow usage of **all** characters including unicode and whitespace. There should be no password composition rules limiting the type of characters permitted.
- Ensure credential rotation when a password leak, or at the time of compromise identification.
- Include password strength meter to help users create a more complex password and block common and previously breached passwords
    - [zxcvbn library](https://github.com/dropbox/zxcvbn) can be used for this purpose. (Note that this library is no longer maintained)
    - [Pwned Passwords](https://haveibeenpwned.com/Passwords) is a service where passwords can be checked against previously breached passwords. You can host it yourself or use [API](https://haveibeenpwned.com/API/v3#PwnedPasswords).
Refer to this link: https://en.wikipedia.org/wiki/Password_policy

Follow OWASP cheatsheets: https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#password-complexity

**Comment by eternoendless** [comment]
This needs to be prioritized

**Comment by eternoendless** [comment]
According to @PierreRambaud, this depends on the security page: #21120

**Comment by prestascott** [comment]
Hello everyone,

For the past days, I've worked on the design of this new component.

## Design

### Anatomy
<img width="613" alt="Anatomy (3)" src="https://user-images.githubusercontent.com/54888056/158846567-87358a08-9066-492b-976f-859d0399a939.png">

[Link to the Figma file](https://www.figma.com/file/1AcoQLzJG3K1eIKB6o0j4y/Password-strength?node-id=0%3A1)

**1. The tooltip**
Depending on what users write, the suggestions and warnings appear in this same tooltip.

**2. The show/hide icon**
It allows users to show or hide the password

**3. The password strength meter**
There will be 5 different levels of password strengths:
- Very weak `#D5343C`
- Weak `#D5343C`
- Average `#FFA000`
- Strong `#21834D`
- Very strong `#21834D`

It is highly recommended (but not mandatory) for users to create a "Strong" password based on suggestions from [zxcvbn tool](https://lowe.github.io/tryzxcvbn/).

**4. The mandatory requirement checked**
**5. The mandatory requirement not checked yet**


## Mockups

Overall, the icon button has been added to allow users to see or hide their password in the input.

### Installer
_Installer - Store information_
<img width="853" alt="Installer - Store information" src="https://user-images.githubusercontent.com/54888056/158183357-fe0eb435-5857-410c-b3fa-332382279dcc.png">


### Back office
_BO - Edit Employee > Password > Change password (Generate password)_
<img width="620" alt="BO - Generate a password - Hidden" src="https://user-images.githubusercontent.com/54888056/158182792-c9585acf-301b-4222-9576-acaa69941464.png">
<img width="620" alt="BO - Generate a password - Not hidden" src="https://user-images.githubusercontent.com/54888056/158182610-c002e3f5-d018-42b9-9827-d2c31139e8e7.png">
- The "Generate password" button has been removed because it is a native feature available on browsers

_BO - Add new employee > Password_
<img width="559" alt="BO - Add new employee - Password" src="https://user-images.githubusercontent.com/54888056/158182955-b15cc75a-77c5-425b-8305-690b3b6c563e.png">

_BO - Forgotten password_
WIP

### Front office
_FO - Account creation on Theme Classic_
<img width="544" alt="Classic theme" src="https://user-images.githubusercontent.com/54888056/158183740-083bfe17-0951-49ee-beb4-41b0279333d7.png">

_FO - Account creation on Theme Refacto_ 
<img width="464" alt="Theme refacto (1)" src="https://user-images.githubusercontent.com/54888056/158184032-5694ac29-f591-4131-8344-496fbadbd288.png">

Let me know what do you think ✌️
