### ISSUE TITLE
"An error occurred while processing your request", this issue is displayed on the Quick view for a product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#11771]
**Describe the bug**
In the Home page, after clicking "Continue shopping", we try to click on "quick view" on the same previous product added to the cart, an error is displayed on the modal product page.

**To Reproduce**
1. Go to FO
2. Click on "Quick view" on the product P1
3. Click on "Add to cart"
4. Click on "Continue shopping"
5. Click on "Quick view" on the previous product P1
6. see error

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/49950414-0f7d1400-fef8-11e8-963f-5ceb1e868916.png)

https://drive.google.com/file/d/1iS5vToIgiIbNI_s060fGNz2YUR6lfdGN/view

**Additionnal information**
PrestaShop version: 1.7.5.0rc1
PHP version: 7.1

**Comment by matks** [comment]
**Primary analysis**
Error message is displayed [here](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/product.js#L309) because of failed AJAX request triggered [here](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/product.js#L127)

AJAX request fails because
```
currentRequest = $.ajax({
      url: updateUrl + ((updateUrl.indexOf('?') === -1) ? '?' : '&') + formSerialized + preview,
      method: 'POST',
      data: {
        ajax: 1,
        action: 'refresh',
        quantity_wanted: $quantityWantedInput.val()
      },
```

`formSerialized` and `preview` are empty. This data comes from [here](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/product.js#L95) : `$('.product-actions')` . This CSS class does not exist when "continue shopping" button is pressed into modal.

All of this is triggered by emitted event "updateProduct" which is listened to [here](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/product.js#L301). Why is this event emitted when we click on "continue on shopping" button ? This needs to be found out 😄  I think it should not emitted.
