### ISSUE TITLE
php 7.3

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#11838]
Prestashop 1.7.4.4 or the latest 1.7.5 have compatibility with the latest php 7.3?
Thank you

**Comment by kpodemski** [comment]
No, it's just released.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Current situation of PrestaShop:
PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 / 1.7.5 is compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks!

**Comment by MindaugasVarkalys** [comment]
Your atitude about supporting new PHP versions is unacceptable. Compatibility issues should be solved while a new PHP version is in alpha/beta/rc phase but not when it's released. All changes in PHP are expected because they are deprecated in the previous version, so please, the next time you're solving compatibility issues, fix not only errors, but also deprecation warnings. Thanks!

**Comment by matks** [comment]
Hi @MindaugasVarkalys,

> Compatibility issues should be solved while a new PHP version is in alpha/beta/rc phase but not when it's released

This is a nice approach however you have to consider 3 points:
- PrestaShop codebase is quite large
- we are not many contributors to PrestaShop
- there is already a lot of in-progress work on the PrestaShop project (as I'm writing, we have 918 issues and 365 pull requests)

Because of that, I don't think your approach is doable for PrestaShop. But latest PrestaShop release (1.7.5) supports php7.2 and I think that most of PrestaShop users (devs or merchants) are using php5.6 to php7.2. They sometimes don't even have the choice: some hosting providers will not provide php7.3 for still a few months.

I understand you can feel frustrated. Do you want this to change ? If yes, you can do something: contribute ! 😄This is an opensource project and we welcome all contributions. We would be really happy if you are willing to help us making next PrestaShop release php7.3-compliant quickly. 😉

**Comment by PierreRambaud** [comment]
One more point:
Some dependencies are not compatible 5.6 and 7.3, 
If we take the 7.3 compatibility, we break 5.6, which is not acceptable in a minor version :/

**Comment by matks** [comment]
@centoasa @kpodemski It's decided: next PS version 1.7.7 will be compatible with php7.3 and will drop the php5.6 compatibility as a consequence
See http://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/
