### ISSUE TITLE
Complete the Translation system

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#11841]
Hello fellows,

since 1.7.0, we haven't fully implemented the new Translation system for modules:

* native modules use Back Office translations;
* current modules use `l()` implementation and so on can't use Symfony;
* Twig templates can't use old translations (the ones without domains)

At this moment, there are 2 options to fix the current issues:

* sounds like easy to do and to implement: backport the Smarty `l()` function to Twig and then translate modules the 1.6.x way;
* more complicated but better from a consistency point of view: add the complete support of new Translation system in modules;

> A WIP is started if we consider the 2nd option: https://github.com/PrestaShop/PrestaShop/pull/11321

My very own feeling on this is that we can and we should implement both to help 1.6.x developer to migrate modules to 1.7 and then deprecate the `l()` function in Twig, because, in the end of the day, we will only rely on the Symfony Translation component to manage all translations.

**Comment by eternoendless** [comment]
I think we should make modules use the new system when possible, while keeping compatibility with previous previous 1.7 releases. Here's how it would work:

1. Modules use the new system, each one having its own domain: `Modules.MyModule`
2. Modules can still use `$this->l()` which is going to behave as _deprecated alias_ of `$this->trans()`.
3. The translation system will work by registering a resource into the translator (`$translator->addResource()`). A loader will have to be written in order to be able to reuse the existing `.php` translation files which belong to the legacy system.

However, reusing the legacy-style `.php` files may prove a little challenging, because the old system uses obscure identifiers like `<{mymodule}prestashop>mymodule_2ddddc2a736e4128ce1cdfd22b041e7f` instead of simple key => value pairs.

An option would be to load keys from `.php` files as they are, and convert the token (eg. the parameter sent to `$this->trans()`) before handing it over to the translation system.

```php
// usage in module
$this->trans('Some wording', [], 'Modules.MyModule');

// contents of fr.php
$_MODULE['<{mymodule}prestashop>mymodule_89ea9052558795d183ae379c865c8cb6'] = 'Le wording';

// internal call in $this->trans()
$wording = 'Some wording';
$domain = 'Modules.MyModule';
$token = $someService->getTokenFor($wording, $domain); // returns '<{mymodule}prestashop>mymodule_89ea9052558795d183ae379c865c8cb6'
$translator->trans($token, [], $domain); // returns 'Le wording'
```

It's kind of hacky, but changing it would cascade into changing the way translation files are generated by in the translations controller...

**Comment by eternoendless** [comment]
Partially done in #11321, the rest will be done in #13039
