### ISSUE TITLE
On 1.7.5 is not possible to add icons to $helper->title of the

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#11886]
hi
now on the 1.7.5 is not possible to add icons or html code in the $helper->title of $helper->generateList
instead with $helper->generateForm is ok using the legend

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/50309129-e16e7580-049d-11e9-9f59-8d1d3739b24d.png)
![2](https://user-images.githubusercontent.com/653230/50309132-e501fc80-049d-11e9-9886-363f543f9eab.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
I manage to reproduce the issue with the last version 1.7.5.0.
In the PS1.7.5.0, I tried with this code `$helper->title = '<i class="icon-time"></i>'.$this->l('Cron tasks');`
=> NOK
![image](https://user-images.githubusercontent.com/16067358/50335041-64c5b080-050a-11e9-8373-0f60f27eeda0.png)
In the PS1.7.4.4, I tried with the same code `$helper->title = '<i class="icon-time"></i>'.$this->l('Cron tasks');` => OK
![image](https://user-images.githubusercontent.com/16067358/50335110-976fa900-050a-11e9-9e03-64e92c047692.png)
We will see how to fix it.
Thanks!

**Comment by matks** [comment]
Hi @maofree ,

We have improved the security of this template by escaping the title of a helper list (see https://github.com/PrestaShop/PrestaShop/commit/d7f4f87bed69fff4c3df2d96f3678545dcb585fe#diff-76d819935caecba2ee16f320a6aee630).

Although it can indeed be useful to insert html there, this was a security issue as it was vulnerable to XSS.

You can see in the template (see commit) that there already is a placeholder for `$icon`. Consequently there must be a way to display this icon in a secure manner 😉

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/11899 is one way to provide icon controlling capacities to HelperLists

**Comment by Maofree** [comment]
Hi @matks 
adding
$helper->icon = 'icon-cogs';

nothing happens

**Comment by matks** [comment]
@maofree With the current HelperList function, yes. It needs to be modified 😉 see https://github.com/PrestaShop/PrestaShop/pull/11899 for example

**Comment by Maofree** [comment]
however no html code can be used in the title like to add style attribute, so it is not possible to change a part of title

**Comment by Maofree** [comment]
why do you not use |escape:'javascript' instead of |escape:'html':'UTF-8' ?

**Comment by matks** [comment]
@maofree The escape argument is what is expected. This `title` is supposed to be an UTF-8 HTML string so we escape it to an HTML string.

I understand that this reduces your customization abilities for this HelperList. However the fact is that this customization ability was never intended to work in the 1st place ^^ it was a security mistake not to escape it.

Moreover, it is not a good practice to control your HTML markup from your php code. This mixes the data and how it's being rendered. Data should be computed by the php backend code, and it should be rendered in the smarty file using HTML, CSS and if required JS.  This is important because when you need to debug why your rendering has gone wrong, you want to know the scope of your search. It can be very frustrating to spend 1 or 2 hours debugging HTML/JS code only to find out the CSS class you are tracking was being added in the php backend 😅  . Your need is to control how you render this element so it should be performed in the smarty code, not on the backend code.

So here's some solutions I think would meet both your needs and security standards 😉 

- extend HelperList ability to add a `title_css_class` the same way I did for `title_icon` to be able to add a css class

However this will work only in a few usecases and is still a violation of the separation between view and data 😥 
- create your own HelperList class which has the desired behavior 😉 (when PrestaShop behavior is not the one needed, one can extend it)
- override the HelperList template being used to add the markup you need

What do you think ?

**Comment by Maofree** [comment]
Hi
I've looked about the override of list_header.tpl but there is not possible because it is not present a block solution

I'd like to use the span tag to put in evidence just a part of the title
however in the future we will use the ne UI, I hope you can add some nice solution to customize the title
thanks
byeeee
