### ISSUE TITLE
Make it possible to remove the attribute name from the title.

### ISSUE THREAD

**Issue by TemKaSD** [PrestaShop/PrestaShop#11927]
![screenshot_4](https://user-images.githubusercontent.com/6318282/50407696-212fb700-0828-11e9-900b-a12d10370f33.png)

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

Do you need to remove the attribute name from which title?
From this title?
![image](https://user-images.githubusercontent.com/16067358/50417332-14aa5f00-0826-11e9-81d0-896dd4d99d73.png)
Thanks!

**Comment by TemKaSD** [comment]
@khouloudbelguith yes

**Comment by khouloudbelguith** [comment]
Hi @TemKaSD,

You need to navigate to your BO => Product detail page => SEO tab & edit the meta title.
Thanks to check & feedback.

**Comment by TemKaSD** [comment]
@khouloudbelguith 

My title is 12345:
![screenshot_1](https://user-images.githubusercontent.com/6318282/50424625-d5761f80-08b2-11e9-87d7-211ba7454cf4.png)

Page title is 12345 Сорт 1:
![screenshot_2](https://user-images.githubusercontent.com/6318282/50424638-25ed7d00-08b3-11e9-9950-af86ac1583c4.png)

Сорт 1 - is attribute.
Me need remove attribute.

**Comment by TemKaSD** [comment]
@khouloudbelguith Need to add an option. Enable or disable the attribute name in the page title.

![screenshot_1](https://user-images.githubusercontent.com/6318282/50424677-f68b4000-08b3-11e9-9db5-8b2269bfcbab.png)

**Comment by khouloudbelguith** [comment]
@TemKaSD, in the file Project_Folder/controllers/front/ProductController.php, you can comment this line
`$page['meta']['title'] .= ' ' . $attribute['group_name'] . ' ' . $attribute['attribute_name'];`
So, the attribute_name & the group_name will be removed.
Thanks to check & feedback.

**Comment by TemKaSD** [comment]
@khouloudbelguith I already did it. Make the option to enable and disable the new version prestashop. I left a suggestion for improvement.

**Comment by khouloudbelguith** [comment]
@TemKaSD, thanks for your suggestion!
@colinegin, @marionf what do you think?
Thanks!

**Comment by pdkey** [comment]
its possible to make this the option in 1.7.5.1. We need full control of our SERP snippets. The attributes drastically extend the title length with ". . . " - Not pretty. Thank you.

**Comment by colinegin** [comment]
Hello,

Thanks for your feedback ! This is an improvement we have decided for the 1.7.5, it was highly recommended by SEO experts we worked with, as it improves the SEO of your page, preventing for instance duplicated content.

What are the reasons why you would like to remove it ? Is it "only" for aesthetics ?

Thank you !

**Comment by TemKaSD** [comment]
@colinegin In my case, this is superfluous.

**Comment by pdkey** [comment]
@colinegin What kind of Seo expert advised you to do that? We need full control over the snippets also in the title description and length. In our case - our title is 68 characters + the attributes are now over 116. It isn't recommended to use more than 70 characters. now everything is shortened in google with . . . This is for sure disadvantageous for users and for Google. In addition, the title of your solution does not even change when the variation changes, so the title no longer matches the selected product. 
So its SEO technically and aesthetically catastrophic.

**Comment by jolelievre** [comment]
Hello @pdkey and @TemKaSD 

I understand your problem, indeed this feature should be an option. Although I hesitate between two ways of managing this:
- either be able to enable/disable each attribute group (as you suggested @TemKaSD) which offers more precise control, but if you need to disable them all you need to do it one by one
- use a global option like "Show product attributes in title" which would hide all attributes when disabled

@colinegin what do you think?

By the way @pdkey I'm a bit surprised when you say the title doesn't adapt to selected variation
If you refer to the title when you click on an attribute to change its value then it's because the page is modified by AJAX, but the title doesn't change. However if you refresh the page you can see the title is correct so search engines will see the appropriate title.

**Comment by colinegin** [comment]
First, we had thought of putting an option in the SEO section of each product page.
But now that I think of it, I think a global option is a better option, as it is a simpler solution.
I'm just not exactly sure where this option should be located : product settings ? traffic & seo ?

**Comment by jolelievre** [comment]
I also think it's simpler, and I think people who don't want the feature will likely want to disable it everywhere. But I asked myself the same question as you:

- SEO & Urls would seem logical but there is no section with settings about the pages markups, content or display
- so product settings seems like a good alternative (maybe in the "Product page" section), but there is no settings about SEO in this page/form and it can become messy if each type of resources has its own SEO purpose rather than gather them all in one place

...

**Comment by TemKaSD** [comment]
In the settings of the product - the best option.
- If I need to disable it for one product, I can do it.
- If I need to disable for all products - I can disable all products.

It will not be possible to disable a certain parameter - this is bad.

**Comment by colinegin** [comment]
Hello @TemKaSD ,

Thanks for your feedback ! However, don't you think it is much simpler to do it globally ?
If you have to change this option for every product of your catalog, this will be time consuming.
What's your opinion ?

**Comment by pdkey** [comment]
@jolelievre Unfortunately, I can't confirm that. After changing the combination, the URL is correct, but even after refresh the page we see the default title with standard variation addition.

@colinegin position in "Traffic & SEO" is easy to find and understand.

Best option is the global one. for each product ist a crazy work and prone to mistakes.
Find the problem after seo lost positions in a catalog with about more the 1000 products,

in ths moment we notice lost some positions - we need this fix very fast.

**Comment by colinegin** [comment]
This fix is going to be done for the 1.7.5.1 version, which shouls be released in the next weeks. 

After discussion with @jolelievre, we agree with your recommendation, the option is to be added in the Traffic & SEO tab, in a dedicated section for SEO options.

What is your recommendation on wording @LouiseBonnard ?

**Comment by LouiseBonnard** [comment]
**NAME OF THE SECTION:** SEO options/parameters/settings/setup/configuration

**WORDING:** Display attributes in the product meta title (YES/NO)
