### ISSUE TITLE
Order History Crash if payment status not set

### ISSUE THREAD

**Issue by web-fu** [PrestaShop/PrestaShop#11946]
**Describe the bug**
If your order has not a valid status, the FO order history page crashes with error:
Undefined index: 
at file /classes/order/Order.php line 925

**To Reproduce**
This bug can reproduced if there is problem with payment module and the order status is not set.
In the BO the order is shown without a status, in the FO, there is the crash

**Screenshots**
https://imgur.com/AwyO4Ym

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @web-fu,

What is the exact payment method did you use?
Thanks!

**Comment by web-fu** [comment]
I used Payment via Credit Card (using this module : https://addons.prestashop.com/en/payment-card-wallet/7430-payment-with-credit-card-by-setefi-intesa-san-paol.html) but I think the problem is general

**Comment by khouloudbelguith** [comment]
@web-fu, this issue occurs only with a single customer or for all the customers created?
Thanks!

**Comment by web-fu** [comment]
The error occurs whenever, during the payment process, there's no correct callback to the shop.
It doesn't depend on the customer. The problem is difficult to reproduce but it is critical because the lack of an external data create an exeption.
If the payment fails for any reason, the shop shoudn't crash

**Comment by khouloudbelguith** [comment]
Hi @web-fu,

In my case, I did not manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
Have you the same issue when using a different payment method?
Have you tried to contact the module author https://addons.prestashop.com/en/contact-us?id_product=7430 via your account?
THanks!

**Comment by web-fu** [comment]
Hi @khouloudbelguith,
I've contacted the creator of the module, but it is not "their fault".
Let me explain: after payment the payment system call a "notify page". If the page takes too long to load, the payment system drop the connection. If this happens, the payment in the datatabase assume a null status that is managed by BO but not by FO.
The core problem is not the timeout, but the unmanaged status. 
This correction fix the issue:
https://github.com/PrestaShop/PrestaShop/pull/12050

**Comment by khouloudbelguith** [comment]
Hi @web-fu,

Thanks for this clarifications, but I did not manage to reproduce the issue following these steps:
In my case, I tried to change the status of any order to invalid status (id status =0)
![image](https://user-images.githubusercontent.com/16067358/50778288-ddb06080-129d-11e9-8247-8673db3f4045.png)
But in my order history, there is no error
![image](https://user-images.githubusercontent.com/16067358/50778452-45ff4200-129e-11e9-91f2-a1e730630105.png)
@marionf what do you think?
Thanks!

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

![capture d ecran_878](https://user-images.githubusercontent.com/13449658/50821010-61199280-132e-11e9-9e62-c84665e50659.png)

![capture d ecran_879](https://user-images.githubusercontent.com/13449658/50821018-6676dd00-132e-11e9-8a53-1d1411002c4b.png)

![capture d ecran_880](https://user-images.githubusercontent.com/13449658/50821025-6a0a6400-132e-11e9-8534-af4d4d166600.png)

![capture d ecran_881](https://user-images.githubusercontent.com/13449658/50821035-6ecf1800-132e-11e9-8a2d-5a677d9b0d5b.png)
