### ISSUE TITLE
error 500 while switching over templates and after clicking to Theme and Logo in BO

### ISSUE THREAD

**Issue by servidiomarco** [PrestaShop/PrestaShop#11993]
**Describe the bug**
error 500 while I was switching from other template to Classic template and now issue appear after clicking to Theme and Logo in BO
**To Reproduce**
1. Go to 'Design'
2. Click on '.Theme and logo'
3. See error

**Screenshots**
video:   https://vimeo.com/308908388

"debug on" screenshot: 
![screen shot 2018-12-31 at 16 56 15](https://user-images.githubusercontent.com/21959141/50564474-07590d00-0d1d-11e9-833d-6958a78cf7ab.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.0 also tried with 5.6

**Comment by khouloudbelguith** [comment]
Hi @servidiomarco 

Some server disables `putenv` because of security reason.
Your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem. 
You should contact your host provider, they are the only ones to help you with it.
We have updated the Symfony version, this new version use the Putenv function.
Thanks to check with your host and feedback.

**Comment by servidiomarco** [comment]
Checked with my host provider and fixed the issue!

Many thanks

**Comment by khouloudbelguith** [comment]
Hi @servidiomarco,

Thanks for your feedback.
Since it is fixed, I close the issue, feel free to open a new one when needed.
Thanks!
