### ISSUE TITLE
Webpack improve

### ISSUE THREAD

**Issue by Prestapro** [PrestaShop/PrestaShop#12019]
**Is your feature request related to a problem? Please describe.**
More readable code and improved performance

**Describe the solution you'd like**
Please, add, stylelint/critical path for webpack css/scss and update bootstrap 4 to stable version in classic theme.

**Describe alternatives you've considered**
The most important option is the critical path, which will definitely give a performance boost.

**Additional context**
It will also help developers make templates faster and better, as well as maintain a standard for writing CSS.

You can measure the performance of the demo, with virtually no modules and it looks sad:
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Ffo.demo.prestashop.com%2Fen%2F

I'm gaining 88 points, should be 99 or 100.
The result with modules and custom themes is even worse, about 40 points.

**Comment by khouloudbelguith** [comment]
Hi @Prestapro,

Unfortunately, we cannot upgrade Bootstrap and jQuery on the classic theme until the next major version. Bootstrap changed their layout system since alpha 6, which is a backward compatibility break that would affect all of the classic's child themes.
If you are concerned about these vulnerabilities, take a look at Classic-Rocket, which is a community port of Classic to Bootstrap 4.1
Also, you can follow this issue for more details: #11352
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Prestapro,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!
