### ISSUE TITLE
The bulk actions to uninstall modules does not work on 1.7.5.0

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#12011]
Hi
the bulk actions to unistall modules does not work on 1.7.5.0
if I do manually it is ok but one by one

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/50639739-d0743880-0f62-11e9-85b1-f6631e78fec5.png)

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
HI @maofree,

When I try to uninstall by bulk action, only one module will be uninstalled, for the other modules => NO, I tried to uninstall the other modules manually & they are uninstalled successfully.
I attached a video record.
https://drive.google.com/file/d/1NDQGozCn9jM3GOFoGNOm9TzvrOTzTqKa/view
We will see how to fix it.
Thanks!

**Comment by marionf** [comment]
I tried with banner and search block.
If you refresh the page, you are not able to find them on module manager page. And if you search them on Module Catalog page you can re-install them. So, they are well uninstalled. 
It's just you have only one success message instead of one for each module selected

https://drive.google.com/open?id=1O8VI8CtM3QyBhtWaXN9ITjv7xAavg4Wf

**Comment by Quetzacoalt91** [comment]
This issue is caused by concurrent calls to the module manager, which drops the whole cache after an action is done on the modules.

The other current calls loose the cache during their request, which makes an 500 error being thrown.

cc @jolelievre
