### ISSUE TITLE
Warning x Lekë paid instead of x  Lekë

### ISSUE THREAD

**Issue by gentianziu03** [PrestaShop/PrestaShop#12136]
Hello

I'am using 1.7.1.1 Prestashop with 20%tax.
COD Method for payment.
When the order is created go to **Proccesing in progress**

![capture](https://user-images.githubusercontent.com/46620232/51083140-5a679280-1715-11e9-9a31-3a73048d4009.JPG)

then when the order is done in preparation i put the order in **Payment accepted**

![capture](https://user-images.githubusercontent.com/46620232/51083153-88e56d80-1715-11e9-9ed5-24c3830b1662.JPG)

1) When i make a discount for example total is **1000 Leke** and discount is **100 Leke** = **Total 900 Leke**

2) The invoice shows correct **SUM** but in the **PAYMENT** shows me an warning.
**Warning 1000 Lekë paid instead of 900 Lekë**

![image](https://user-images.githubusercontent.com/46620232/51083018-b1b83380-1712-11e9-9bd0-bdf60dcd2603.png)

3) On total stats dashboard shows the SUM without discount
4) On Delivery Slip shows the sum without discount.

I want when i discount a value to show correct **sum on Delivery Slip** and **Total SUM On stats**
Can anybody help me?

**Comment by khouloudbelguith** [comment]
Hi @gentianziu03,

Thanks for your report.
About the warnings => it is a normal behavior => because you change the status of your order to payment accepted ( order just paid) => after that you added a discount => so, it is paid xx£ instead of yy£.
About the dashboard which shows the SUM without discount, here's the same issue reported in this ticket: #9983

About the sum on Delivery Slip, it is not updated after adding a discount.
In fact, we should have an option `Apply on the delivery slip`, like the invoice option, because, the total in the delivery Slip shows the sum without discount.
@marionf, @colinegin what do you think?

Thanks!

**Comment by gentianziu03** [comment]
Hi @khouloudbelguith  maybe i have found the solution for the Warning. The default stus that order go is Processing in progress You have to UNCHECK **Consider the associated order as validated.** and now when order is **Porcessing in progress** you can make a **discount**. And then you can go set any astatus and will not show the warning!

**Comment by colinegin** [comment]
Thanks for your feedback,

maybe we should just add a warning below Consider the associated order as validated, what do you think ?

**Comment by colinegin** [comment]
Hello @disarci,

Since we have had no news for a few months, I will close this issue.
Feel free to re-open it or write a new issue if needed !

Have a nice day,

Coline

**Comment by TomanDesign** [comment]
Hi, I have the same warning on selected orders. In addition, I have tax = 0 on the invoice summary.
