### ISSUE TITLE
BO: Translation missed

### ISSUE THREAD

**Issue by polo195pl** [PrestaShop/PrestaShop#12133]
**Describe the bug**
Missed translation in BO in 1.7.5.0 in Polish on Module tab also Contact form in PL it is Formularz kontaktpey " should be "Formularz kontaktowy"

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @polo195pl,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & the Polski language.
There are missed translation in BO in 1.7.5.0 in Polish on Module tab.
![image](https://user-images.githubusercontent.com/16067358/51170570-0ee8ec00-18af-11e9-9a40-ccdcdd201b1a.png)
With PS1.7.4.4, it is OK.
![image](https://user-images.githubusercontent.com/16067358/51170720-68511b00-18af-11e9-90f2-c9ceabca4e2e.png)
The "Contact form" in PL it is "Formularz kontaktpey", this issue exists in the PS1.7.5.0 & PS1.7.4.4.
@LouiseBonnard what do you think? it could be fixed in Crowdin
Thanks!

**Comment by LouiseBonnard** [comment]
Hi @khouloudbelguith, thanks for pinging me on this. I've just changed the translation into _Formularz kontaktowy_ (via Crowdin) as suggested by @polo195pl. It should be effective in a couple of days. ;-)

**Comment by marionf** [comment]
@khouloudbelguith Can you verify if it's solved and close this issue if it is ?

**Comment by khouloudbelguith** [comment]
@marionf, yes, it is OK.
![image](https://user-images.githubusercontent.com/16067358/52960554-59232880-3399-11e9-83d7-e59356e4099b.png)
Thanks!
