### ISSUE TITLE
php 7.2 combat issue, BO encryption Rijndael not selectable.

### ISSUE THREAD

**Issue by Casper-O** [PrestaShop/PrestaShop#12158]
**Describe the bug**
Running PHP 7.X without mcrypt [(deprecated)](http://php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt)
Part of the issue was solved in https://github.com/PrestaShop/PrestaShop/pull/9218 but there is still traces of only mcrypt_encrypt check in adminPerformanceController:
https://github.com/PrestaShop/PrestaShop/blob/1.6.1.x/controllers/admin/AdminPerformanceController.php#L843-L849

**To Reproduce**
Setup store without mcrypt_encrypt but with openssl_encrypt, go to performance in BO and see the encryption section.

**Screenshots**
Sorry it is in danish:
![image](https://user-images.githubusercontent.com/956154/51170566-0d1f2880-18af-11e9-8943-fbd0d58f4546.png)

**Additionnal information**
PrestaShop version: 1.6.1.20 and above
PHP version: 7.X

**Comment by khouloudbelguith** [comment]
Hi @Casper-O,

Thanks for your report.
What the exact version PHP did you use?
Could you please provide me the configuration Information of your shop, you can find it in the BO / Advanced Parameters / Configuration Information PAGE.
Thanks!

**Comment by Casper-O** [comment]
```
Serverinformation Linux #1 SMP Thu Jan 4 16:43:57 MSK 2018 i686
Server software version Apache
PHP version 7.2.10
Memory limit: 256M
Maks. executiontime: 240
```
I have downgraded now to 7.0 to be able to use mcrypt.

**Comment by khouloudbelguith** [comment]
@Casper-O, so the issue is solved after downgrading to PHP 7.0?
Thanks!

**Comment by Casper-O** [comment]
The mcrypt extension is available in 7.0, marked as Deprecated in 7.1 and finally removed in 7.2.
http://php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt

That is why it works in 7.0, gives a warning when running 7.1 with debug mode on and finally fails when running 7.2 since mcrypt is not there anymore.

**Comment by khouloudbelguith** [comment]
@Casper-O, PrestaShop 1.6 is not compatible with PHP 7.2.
PrestaShop is compatible with PHP 7.2 starting on 1.7.4.
As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Thanks!

**Comment by Casper-O** [comment]
could you then explain the following PR:
https://github.com/PrestaShop/PrestaShop/pull/9187
https://github.com/PrestaShop/PrestaShop/pull/8724

They are related to PHP 7.2 and making the code for 1.6 compatible with PHP 7.2

It's a problem introduced in Prestashop 1.6.1.20 that have multiple PR related to PHP combat issues. It was overseen in this PR https://github.com/PrestaShop/PrestaShop/pull/9218

**Comment by studiox3** [comment]
https://github.com/PrestaShop/PrestaShop/blob/70d12a5ffbd9f1123e76cded1be8d2f78d5f015c/classes/Rijndael.php#L71-L87
Calling the _generateHmac($encrypted)_ method on lines 71 and 84 causes ajax error in debug mode on PHP 7.x
`
Warning: Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' (this will throw an Error in a future version of PHP) in /PrestaShop/classes/Rijndael.php on line 124`

**Comment by khouloudbelguith** [comment]
Hi all,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
The end of 1.6 official support by the PrestaShop company. And the beginning of something new.
From the 1st of July 2019, the maintenance of PrestaShop 1.6.1.x is now being performed exclusively by volunteers. If a critical issue is discovered (we think mainly of security vulnerabilities), this team of volunteers will look for solutions from the community, work on it through a process of code review and extensive testing, in order to release a patch version to solve this critical issue.
Those patch versions will not be officially issued by PrestaShop nor available on prestashop.com, instead, they will be available on a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6
For more details, you can follow this link: http://build.prestashop.com/news/1.6.1.x-what-s-next/

I close the issue, feel free to open a new one when needed.

Thanks!
