### ISSUE TITLE
Can't do anything. Bad request. Size of request header field exceeds server limit

### ISSUE THREAD

**Issue by caotico25** [PrestaShop/PrestaShop#12185]
I am getting this type of error, produced at random, since it has happened to me both in the backoffice and in the front. I have also received complaints from clients and other employees, so I am not the only one affected by this problem.

The complete message is "Bad Request." Your browser sent a request that this server could not understand. Size of request header field exceeds server limit."

I don´t know exactly how to reproduce it. The last time I had a cart with many products. I started to delete them quickly, clicking on the trash can and reloading the page I missed this error

![captura de pantalla 2019-01-10 a las 9 25 17](https://user-images.githubusercontent.com/6215402/51272415-531cdf00-19ca-11e9-9f34-5f3ebcc5d851.png)

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @caotico25,

Could you please try to clear the cache from your browser and remove the cookies from websites that cause problems.
You can also clear cache manually by deleting all the folder into var/cache (prod & dev).
You should force refresh the browser (by pressing ctrl + shift + R on Windows / Linux, CMD + R on Mac OS).
Thanks to check and feedback.

**Comment by caotico25** [comment]
Hi @khouloudbelguith,

I know that doing this solve the problem, but it is temporal because it can happen again... I can do that and "see you later", the problem is when it happens to my customers.

The average profile of my clients is an adult person with little or no computer knowledge, so it would be unthinkable to explain to them that they have to do all this cleaning. Many of them are reticent and distrustful of online businesses (even if they use them). If now I tell them that they have to mess with the browser, I would definitely lose them as clients.

From what I have researched and what you are telling me about, the problem is that at some point the cookie takes on a larger size than it should or with the wrong information. This problem has been reproduced in both the front and the admin:
In the front, it has occurred mainly during the handling of the cart (modifying quantities or eliminating products).
In the admin has happened in different points, without anything remarkable: we were browsing and suddenly this error appeared. I also have to say that in the admin we are about 20-30 employees and only 4 have had this problem, two of them have admin permissions

**Comment by khouloudbelguith** [comment]
@caotico25, in the BO => Advanced Parameters => Administration => in the General section, you can change "Lifetime of front office cookies" & "Lifetime of back office cookies"
![image](https://user-images.githubusercontent.com/16067358/51309332-6c627180-1a44-11e9-99c8-21ee8c4d46f2.png)
I hope that this solves your issue.
Thanks!

**Comment by caotico25** [comment]
Hi @khouloudbelguith 

Of course, this solves the problem, temporarily. Before coming here to "bother" I have investigated all the possible solutions, which are the same ones that you are offering me (which I thank you very much, since you are investing your time in my problem).

But ... if I do this, I will be causing all my customers to lose their carts (I know that this in principle is inevitable and that they could really be recovered from admin if they are registered). But it's not a definitive solution, it's just a badly placed patch ...

I would like to know if you know the source of this problem and how I could fix it so that it does not reproduce anymore, since it is a huge annoyance that X number of users are unable to access my page due to this problem, or that an employee is left unable to do their job until that the cookies are deleted.

Thanks for your answers

**Comment by khouloudbelguith** [comment]
@caotico25, This issue can be caused by corrupted cookies.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @caotico25,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by bastienuh** [comment]
Old issue, for 1.7.5... and still there on 1.7.7... 😠 

I'm sorry but this answer and "solution" can't be accepted...
I understand the behavio but this is not a relevant behavior for final users.

Reduce the cookie lifetime is not acceptable, because if a user come on the website, put some articles in his cart, and come back after, I will have lost his cart...


Secondely, the customers are totally blocked with a bad request outside the website. The only solution seems to be to delete cookies, but :
- if you do that you loose you cart
- you are disconnected
- most of customers does not how to delete cookies

So : "No changed required" can't be OK... what **real** solutions can you propose?

**Comment by AdriCruz** [comment]
Hello, could you find the  solution?

Thanks

**Comment by bastienuh** [comment]
No, so we are losing customers !
The solution is to change our server, which cost money and time. But seems that it does not matter for Prestashop teams...

**Comment by udubniewski** [comment]
In my case there was a monster cookie causing the issue. the name was CurrentCartcurrentCartTemp.

I deleted the var/cache and var/cache111 directories content and that cookie disappeared and all seems to be working fine.

Prestashop 1.7.4.4

**Comment by LazyCircles** [comment]
Hello! I'm facing the same issue on my online store, it happens sometimes and usually on payment return. 

I've tried all the solutions above. 

I would like to know if there is any cookies/tables/files that I should delete to minimize the cookie size.

Thank you.

Prestashop 1.7.6.5

**Comment by jorunkel** [comment]
We were facing a similar problem, just that it was not the header but the returned cookie size which exceeded 4096 characters and thus was not accepted. After decoding the cookies content we've found that the module "blockviewed" adds the ID of every viewed product into the (clientside!) cookie. Viewing about 420 products were enough to blow the cookie. Our solution was to disable this module. Checking the source code of the newer "ps_viewedproduct" module it looks as if this behaviour is still present.

(To be clear: we didn't have the Bad Request behaviour. Instead our customers couldn't log-in anymore without any warning message, because the (updated) cookie after the authentication process was too large.)

**Comment by TechhDan** [comment]
I installed a new site for a client migrating from 1.6 to 1.7.8.8. My client is experiencing this issue and was unable to use the site for hours until receiving tech support. I downloaded a copy of a PrestaShop 1.7.8.8 docker container and I just got the same issue myself shortly after install. 

**Problem**
Receiving bad request error ```Size of a request header field exceeds server limit.```  

***Cause***
This is normally caused by having a very large Cookie, so a request header field exceeded the limit set for Web Server.

***Solution***
Increase the LimitRequestFieldSize in your apache2/httpd config files. The default is ```8190``` bytes. I set mine to ```16380``` bytes which solved my issue.
