### ISSUE TITLE
Changing combinations on product page on PS 1.7.5 - very slow compared to previous versions

### ISSUE THREAD

**Issue by grigorevlad** [PrestaShop/PrestaShop#12207]
Compared to PS 1.6 and first versions of PS 1.7, the new PS 1.7.5 loads combinations really slow (after fresh install and only default modules) 
PS 1.7.5 works really fast on every page, except this thing which is not actually a bug but needs a fix. 

Another thing:
I have 2 combinations: 'product size' and 'product colors'.  I recently installed a module from mypresta which adds product pictures to color combinations and after install those combinations (product colors) load almost instantly compared to 'product size' combinations. 
So after module install the color combinations load very fast compared to the size combinations which leads me to think that something can be done to load thinks quicker. 

1. Create at least two combinations
2. Add values to combinations
3. Go to product and assign the combinations, make sure you add several photos to each combination value. 
4. Go to frontend, product page, and play around with selecting combinations
5. You should notice that each combination selection loads pretty slow

Also, playing around with performance settings and cache doesn't seem to make a difference. 
I run a pretty capable server. 

![new project](https://user-images.githubusercontent.com/8983330/51377284-2f18e500-1b13-11e9-8386-a69fda73b20f.gif)

PrestaShop version: 1.7.5
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @grigorevlad,

Thanks for your report.
It's great to hear you have been using PrestaShop for long.
About your issue, we need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by grigorevlad** [comment]
Hi,

There is no error, just some process that takes longer that it used to. 
I find it wierd that a purchased module manages to change combinations and refresh the page a lot quicker than the combinations from default template. 

In the GIF uploaded as example you can see that clicking the image combinations from the purchased module refreshes the page almost instantly, while clicking the color combinations from default template takes longer. 
They are the same combinations actually. 

Hopefully I explained so everyone can understand. 

Best regards!

**Comment by khouloudbelguith** [comment]
Hi @grigorevlad,

Thanks for this clarifications.
I tried with a product which has two color combinations, such combination has 15 different images.
PS1.7.4.4 => When I switch between combinations => it takes 240ms <Time <260ms
PS1.7.5.0 => When I switch between combinations => it takes 359ms <Time <1.98 s
Ping @jocel1, @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by grigorevlad** [comment]
Hi @khouloudbelguith , I'm not a dev but when i install a market module that runs combinations better than default PS it's easy for me to guess that there must be a solution that works a lot faster. 

Keep up the good work, I'm here if you need any more feedback.

**Comment by mickaelandrieu** [comment]
Hi,

we need a Blackfire report to figure out what happens...

The module you're using, is it available on PrestaShop Addons?

Mickaël

**Comment by grigorevlad** [comment]
@mickaelandrieu it's not avaliable on Addons, i think it's developed by Vekia which is a valuable contributor for PS for a long time.
I can grant you FTP and Backend access while you gather what you need to test. 
It's ok this way? 

Vlad

**Comment by grigorevlad** [comment]
Hi,

I previously reported a bug which was confirmed (https://github.com/PrestaShop/PrestaShop/issues/12064). 
This bug doesn't happen when changing the combinations via the module described in this issue. 
Basically changing combinations using PS default combination container generates a thumbnail scrolling bug, and if i change the combinations using the module i purchased the bug isn't happening any more. 

Just wanted to let you know.

Vlad

**Comment by jolelievre** [comment]
Hello @grigorevlad,

I would need more info to figure out the issue. What is the name of the module you are using?

Are you sure it changes the combination or just the images? Which is not the same thing, when
you change combination with the PrestaShop elements (like size, color, ...) It requests various
information to the server (combination description, prices, title, discounts, minimum quantities, ...)

So if your module only changes images it sure will be faster.

But nonetheless @khouloudbelguith has made tests to compare 1744 and 1750, and the second is
slower, so we need to investigate on this matter, but having more info on the module could help us
as well.

We can't access your FTP or Backend, this is not a place for support but to improve the PrestaShop
project. Besides it is highly NOT RECOMMENDED to share your website's credentials to someone you don't know, even if they belong to a Project's team. Maybe you are already aware of this but I prefer to remind this for other users who will read this thread.

However I'd like to visit your website just to check my theory about your module refresh process. Could you please provide me your shop link to check it. This is a public space, you can provide me the link by email (jonathan.lelievre [at] prestashop.com), just the front url not the backend.
Let's be safe!

Thank you.

**Comment by grigorevlad** [comment]
Hi @jolelievre ,

The module is here: https://mypresta.eu/modules/front-office-features/product-pictures-on-product-listings.html 
Yes, the module changes the product combination, not just pictures. 

I'm sending you the URL of my store via email. 

Vlad

**Comment by joaoafpedro** [comment]
This is still an issue. As you can see from my video, it takes roughly 2-3 seconds for the page to update the price alone. The price/quantities are the only thing I'm setting differently for this product. It would be very appreciated if as solution for it was found asap and this is revealing to be a real problem.
![ca71398b3eef7e080a10942bd7492266](https://user-images.githubusercontent.com/47190155/52003345-28e41a80-24bc-11e9-9537-6826b90fe72e.gif)

**Comment by jolelievre** [comment]
Hi @joaoafpedro 
as you can see a PR is linked to this issue https://github.com/PrestaShop/PrestaShop/pull/12337 It "reverts" a modification in the js that was introduced in 175.

There is a delay between each action on a product and the request to fetch new datas This delay is here to avoid multiple unnecessary request when modifying quantity (for example) but it was too long (1.5 sec) so we adapt this delay depending on the action (quantity modified: 750ms, any other change: 200ms)
This should greatly reduce the update time.

As for the server/PHP part I was unable to reproduce slow request, I always get requests time around 300ms just like in 1744 (in dev mode). If anyone has a way to reproduce these slow requests or figured out why they are slower I'm interested.

**Comment by joaoafpedro** [comment]
Hi @jolelievre 
Thank you for your reply. Could you please guide me through fixing this issue then?
That'd be very much appreciated. I looked into the link you left there but didn't find any sort of guide on how to fix it.

Best regards

**Comment by grigorevlad** [comment]
@joaoafpedro , the fix is still open for testing. You can try to see if it works fine for you, just go here and reproduce on your server: https://github.com/PrestaShop/PrestaShop/pull/12337/files?utf8=%E2%9C%93&diff=split

**Comment by jolelievre** [comment]
Hi @joaoafpedro 

the link I provided is not a fix for you to apply. It is a pull request which purpose is to be merged/integrated in the PrestaShop core code. This PR targets the coming 1.7.5.1 version that will be released soon.

So I would advise you to wait for this release and update your shop, this way you will get this fix and other ones that are currently being tested and validated by our team.

**Comment by Vekia-** [comment]
> Hi @jolelievre ,
> 
> The module is here: https://mypresta.eu/modules/front-office-features/product-pictures-on-product-listings.html
> Yes, the module changes the product combination, not just pictures.
>

I confirm that module changes the combination, **but it uses only prestashop's features to switch it**. It does not create nor change the core. Just displays picture of combination and spawns the function to switch combination when someone will click on it.

So, the problem is somewhere in original core code / server side problem.

**Comment by kpodemski** [comment]
@Vekia- it has been fixed some time ago, there was not needed delay hardcoded in js

**Comment by joaoafpedro** [comment]
@jolelievre Is there any ETA on the 1.7.5.1 version with this fix?

**Comment by NoZTurn** [comment]
It is because of the symfony and the rendering way the prestashop 1.7 uses, I compared the 1.6 and the 1.7 combination selection page at product page, on 1.6 product page ,the html was generated with smarty at the server end and the javascript(jquery) only update combination data(at browser end)  when combination selection changes, but on 1.7,each time when selection change with combinations at product pages, the symfony (with its MVC twig template engine) will request changes with data updates(include the html strcuture) at server, and then renders the changes to the brower end, this is why when the network is worse, then the loading time is slower.

you can check Chrome console when selecting combinations and here is a screen

![image png 28ba049e914411d008f5a6cd3f7f6c49](https://user-images.githubusercontent.com/2842182/52702635-88abec80-2fb7-11e9-8e3d-41eab68b973d.png)

**Comment by kpodemski** [comment]
@NoZTurn you seem to have no idea what you're talking about

**Comment by jolelievre** [comment]
@NoZTurn PrestaShop 1.7 doesn't use symfony to render front pages (only in back-office), so your explication doesn't seem correct.

However one big difference with the 1.6 version is that not all the combinations data are included in the page, therefore an ajax call is performed when you switch (that's what you can see in your console). This ajax call include many informations, not only does it give you the images and descriptions, it also contains stock informations, prices discounts specific to the combination, ...

In a nutshell ALL the informations that could impact the product/combination which is why it is a bit slower than just switching images, as I suspect the module is doing (nothing wrong with that, only you can't compare the two behaviors).

Anyway a fix has been merged to accelerate this update which had a delay before the ajax request was made, the delay dropped from 1500 to 30ms for most operations so you should feel it's much faster (quantity operations are an exception and have a longer delay, 750ms, because of the UX controls - arrows and keyboard).

This modification will be available in the coming 1.7.5.1 version, and @joaoafpedro as you asked we just built the release today, we now need it to be validated by our QA team. So I'm hoping by then end of the week or beginning of the next one it should be released ^^

I hoped I could answer to all your questions and that you will be satisfied with the 1.7.5.1 improvements. As this ticket is closed if you encounter new problems I invite you to open a new issue once the new version will be released.

**Comment by egm14** [comment]
Can you indicate  the commit where is the solution? @jolelievre

**Comment by Klemart3D** [comment]
@egm14 : https://github.com/PrestaShop/PrestaShop/pull/12337/commits/f56d5d730c075ae2aa3c3500c6eb02dc29be20f7

**Comment by hostisoft** [comment]
In the latest versions we do not see that this has been solved, has anyone found a solution?
