### ISSUE TITLE
Update of the theme by default

### ISSUE THREAD

**Issue by By-oussef** [PrestaShop/PrestaShop#12202]
I was told that there was an update planned for the default theme but this is still not published.

Link : https://github.com/PrestaShop/classic-rocket/issues/24

**Comment by khouloudbelguith** [comment]
Hi @By-oussef,

About the default theme provided by PrestaShop "Classic".
Unfortunately, we cannot upgrade Bootstrap and jQuery on the classic theme until the next major version.
In fact, bootstrap changed their layout system since alpha 6, which is a backward compatibility break that would affect all of the classic's child themes.

If you are concerned about these vulnerabilities, take a look at Classic-Rocket, which is a community port of Classic, they are working on upgrading to Bootstrap 4.2 as they described in your issue.
You should contact them for more information.
Thanks!
