### ISSUE TITLE
Commandes -> Factures : Error 500

### ISSUE THREAD

**Issue by nicoladze** [PrestaShop/PrestaShop#12318]
I just updated from 1.7.2.4 to 1.7.5.0 and now when I click on Commandes -> Factures, I got this page :*

![image](https://user-images.githubusercontent.com/47031957/51779309-c4fdd280-2106-11e9-88ed-20bbaff86731.png)

**Comment by MathiasReker** [comment]
Enable debug mode and show us a new screenshot.

**Comment by khouloudbelguith** [comment]
Hi @nicoladze,

We need to retrieve the debug mode report in order to find out what's wrong.
Also, it could be the same issue reported [here](https://github.com/PrestaShop/PrestaShop/issues/11909), so could you please try to replace the **ps_configuration_lang** table and the **ps_configuration** table in the Database with the one from clean PS1.7.5.0 installation.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @nicoladze,

You can follow this comment: https://github.com/PrestaShop/PrestaShop/issues/12314#issuecomment-462410864 to fix your issue.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #11909
