### ISSUE TITLE
Filtering on messages in Logs does not return correct result

### ISSUE THREAD

**Issue by PrestaworksNiklas** [PrestaShop/PrestaShop#12338]
**Describe the bug**
On PS 1.7.5.0, filtering on messages under "Logs" does return the correct result, but keeps showing other pages within the result. These other pages do not contain the filtered messages. Selecting another number of results per page do not work either.

**To Reproduce**
1. Go To Advanced Parameters, Logs
2. Filter on Message. Click "Search".
3. The first page returns the correct result, but clicking on next page shows wrong results (not filtered results).

**Additionnal information**
PrestaShop version: 1.7.5.0

**Comment by khouloudbelguith** [comment]
Hi @PrestaworksNiklas,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0.
In the Logs page, the filter is resetting when we click on the next page.
It is not the same behavior as PS1.7.4.4., it is OK.
https://drive.google.com/file/d/1nEE5MFtlGJe15C5V8KVMhH6Wnmneqnno/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
