### ISSUE TITLE
[SF Migration] Grid row not clickable

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12348]
In legacy listings, when you click on any row, it does trigger the main action of the row. For most listings it means "edit", sometimes it can be "view".

On migrated listings, this feature is gone.

**Moreover**, in legacy listing since the row was not a link, you could not perform the "right click - open in a new tab" trick. If this can be done in migrated listings, this would be great.

**Comment by sarjon** [comment]
actually migrated lists (maybe not all of them) have this new clickable column, isnt it a replacement of legacy clickable rows? 

![screenshot](https://user-images.githubusercontent.com/15143151/51912847-e8ae6a80-23dd-11e9-81f7-480a58160076.png)

imo it's better since this way user actually knows that it can be clicked whereas in legacy its not obvious.

**Comment by matks** [comment]
In legacy, the hint is that the row gets colored in light blue when hovered 🤔

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16318
