### ISSUE TITLE
Wrong supplier combination collection management url on product administration. Prestashop 1.7.5.0

### ISSUE THREAD

**Issue by picolablv** [PrestaShop/PrestaShop#12366]
**Describe the bug**
There ir out-of-date combination url on
https://github.com/PrestaShop/PrestaShop/blob/78501e2813c2a88119a4ca0d883b65ab5fc50637/admin-dev/themes/default/js/bundle/product/form.js#L485-L488

After 1.7.5.0  this combination collection route url has changed to 
`refresh-combination-form `
therefore on product administration "Option" tab section " Supplier reference(s)" isn't working/updating when you choose suppliers associated with product. 

This bug is especially actual when you have more than one supplier...

**To Reproduce**
1. Go to Product administration page, Options tab
2. Click on multiple suppliers on 'Choose the suppliers associated with this product'
3. Scroll down to "Supplier reference(s)"
4. See error ( always loading only supplier reference with id is 1)
 
**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.10

**Comment by khouloudbelguith** [comment]
Hi @picolablv,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/51989917-47401b00-24a8-11e9-8f8b-844ad7095d93.png)

In the PS1.7.4.4 => ok.
![image](https://user-images.githubusercontent.com/16067358/51989975-5cb54500-24a8-11e9-9656-2a04d83e6df2.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
