### ISSUE TITLE
Module controller translation does not work

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#12373]
When we create a module with a front controller based on a layout, legacy translation does not work.

Following the rule to translate a module, as it's a non prestashop module, and we don 't have theme based tpl, we use the legacy translation system.

Our controller extends ModuleFrontController and display a specific template in initContent() using $this->setTemplate('module:purchase/views/templates/front/purchases.tpl');

In our tpl, we set the smarty variable to {l s='Home' mod='purchase'}. We translated the text using the back office and module section.

But nothing displays.

Doing some debugs and searching in the code, we finally found that in the fr.php translation file for that module the var was set with 
$_MODULE['<{deca_purchase}prestashop>**purchases**_db205f01b4fd580fb5daa9072d96849d'] = 'Total produits'; 

purchases is the name of our tpl. And it seems to be correct. But smarty modifier was searching for the layout template name, so it was looking for
$_MODULE['<{deca_purchase}prestashop>layout-both-columns_db205f01b4fd580fb5daa9072d96849d'] = 'Total produits'; 
We change manually purchases to layout-both-columns in fr.php and it worked.

So either the back office translation tools is not setting the right value, or smarty modifier is not looking for the right one, but it's not working for us on Prestashop 1.7.4.0.

**Comment by khouloudbelguith** [comment]
Hi @cedricfontaine,

In the last release PS1.7.5.0, we have made some fixes related to the translations.
You can follow this PRs:
https://github.com/PrestaShop/PrestaShop/pull/11345 fixes https://github.com/PrestaShop/PrestaShop/issues/9697
https://github.com/PrestaShop/PrestaShop/pull/9326 fixes [issue fixed in the PS1.7.4.2](http://forge.prestashop.com/browse/BOOM-5983)
https://github.com/PrestaShop/PrestaShop/pull/10735 fixes https://github.com/PrestaShop/PrestaShop/issues/9525

For more details about translations, you can follow this link: http://build.prestashop.com/news/new-translation-system-prestashop-17
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @cedricfontaine,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
