### ISSUE TITLE
Multiple Guest customers in Preastashop 

### ISSUE THREAD

**Issue by hekep** [PrestaShop/PrestaShop#12414]
Old issue: http://forge.prestashop.com/browse/PSCSX-9247

Prestashop creates multiple guest customers into database. 

PrestaShop version: 1.6.1.3
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @hekep,

We are aware of this issue, it is added to our debug roadmap.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
Your bug isn’t critical or a security issue, so it will not be fixed in the PS1.6, but it will be fixed in the PS1.7.
Your ticket is a duplicate of #10122
So, I close it.
Thanks !
