### ISSUE TITLE
The mime type of the file is invalid ("application/x-xz")

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#12427]
**Describe the bug**
 
Can't upload a module zipped with default compressor software of Ubuntu 18.04.

**To Reproduce**
1. Zip a module with default archive compressor of Ubuntu 18.04 into ".zip" format
2. Upload zipped file to PrestaShop 1.7.5.0
3. See complete message error:

> The mime type of the file is invalid ("application/x-xz"). Allowed mime types are "application/zip", "application/x-gzip", "application/gzip", "application/x-gtar", "application/x-tgz".

**Screenshots**

![capture d ecran de 2019-02-04 15-54-26](https://user-images.githubusercontent.com/7419525/52216121-db89f380-2895-11e9-8afe-a28467e453c8.png)

![capture d ecran de 2019-02-04 15-55-12](https://user-images.githubusercontent.com/7419525/52216143-e3e22e80-2895-11e9-85ca-f5415788a5be.png)

**Additionnal information**
OS: Ubuntu 18.04
PrestaShop version: 1.7.5.0
PHP version: 5.6

Does the [XZ format](https://tukaani.org/xz/xz-file-format.txt) (under free license) will be compatible with PrestaShop ?

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

after compressing the ps_clener folder to .zip file, I uploaded it & it is oK.
![52217580-032e8b00-2899-11e9-8d6d-55be804f6f3c](https://user-images.githubusercontent.com/16067358/52217951-d9299880-2899-11e9-86e6-3bc2672392f7.png)
I attached a video record.
https://drive.google.com/file/d/1FrwJrpREJNFexILW9wyaviHa2J2A0BBy/view
Thanks!

**Comment by Klemart3D** [comment]
Seems a cache issue. I retried with a new zip file and it's working. I tried with ".tar.xz" but the file is not uploadable ("You can't upload files of this type." message). And if if rename the ".tar.xz" extension to ".zip" (file attached) I get this error:

![capture d ecran de 2019-02-04 17-39-28](https://user-images.githubusercontent.com/7419525/52222531-02e7bd00-28a4-11e9-8442-328f15b13490.png)

[pscleaner.zip](https://github.com/PrestaShop/PrestaShop/files/2828949/pscleaner.zip)

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

I tried to upload your compressed file & it is OK, the module is installed.
But if I rename the ".tar.xz" extension to ".zip"
I have this error
![image](https://user-images.githubusercontent.com/16067358/52264409-d67a8200-2931-11e9-9e13-5138b8fc68a2.png)
It is normal behavior, the compressed file is not valid to be uploaded.
There's a difference between tar.gz & zip

**tar.gz**
Stores unix file attributes: uid, gid, permissions (most notably executable). The default may depend on your distribution, and can be toggled with options.
Consolidates all files to be archived in one file ("Tape ARchive").
Actual compression is done by GZIP, on the one .tar file

**zip**
Stores MSDOS attributes. (Archive, Readonly, Hidden, System)
Compresses each file individually, then consolidates the individually compressed files in one file
Includes a file table at the end of the file
Because zip compresses the files individually, a zip-archive will most-likely have a larger size (especially with many smaller files - think config files).

Thanks!

**Comment by Klemart3D** [comment]
Hi, I retried today with the renamed archive ".tar.xz" to ".zip" (yesterday attached file) and it works fine. But with .zip compression, I still have "The mime type of the file is invalid ("application/x-xz")" error, so I will attach you archive.
It seems to be a label inversion from ubuntu's file roller software so you can close the issue

[pscleaner.zip](https://github.com/PrestaShop/PrestaShop/files/2831786/pscleaner.zip)

**Comment by khouloudbelguith** [comment]
@Klemart3D,

I tried with your file uploaded, I have the same error
![image](https://user-images.githubusercontent.com/16067358/52264409-d67a8200-2931-11e9-9e13-5138b8fc68a2.png)
Since that, this issue is not a PrestaShop's core bug, I close it, feel free to open a new one when needed.
Thanks!
