### ISSUE TITLE
Major bug with Virtual Products command !

### ISSUE THREAD

**Issue by Peterits** [PrestaShop/PrestaShop#12442]
**Describe the bug**
Hi,
If we want to change the billing address for a virtual product order, 
an error is displayed, see below:

**To Reproduce**

1. Go to BO order
1. Click on command virtual product
1. change the billing address
1. See error

**Screenshots**
![adresse-virtual-product-bug](https://user-images.githubusercontent.com/44966543/52304679-8fbd7400-2993-11e9-9a59-ef543e3028c8.jpg)

2nd error
If you want to change only the billing address of the customer, big bug!
In addition, the address we wanted to edit is cloned by itself when we save or cancel the change!

![changement-adresse-vitual-p](https://user-images.githubusercontent.com/44966543/52304680-8fbd7400-2993-11e9-8d1d-0c9c728684a8.jpg)

See video:

![screencapture!UNITO-UNDERSCORE!05-02-2019!UNITO-UNDERSCORE!22!UNITO-UNDERSCORE!03!UNITO-UNDERSCORE!43](https://user-images.githubusercontent.com/44966543/52305534-9d73f900-2995-11e9-92f2-80350a349d67.gif)

I have the error on 1.7.3.3, 1.7.4.4 and 1.7.5.x

**Additionnal information**
PrestaShop version: 1.7.3.x - 1.7.4.x, 1.7.5.x
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @Peterits,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/52327660-2d915d00-29ed-11e9-9f4d-577a569c975a.png)
![image](https://user-images.githubusercontent.com/16067358/52327676-384bf200-29ed-11e9-93ee-5e29fb11c169.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related to: #12170

**Comment by colinegin** [comment]
Hello @khouloudbelguith do you reproduce this issue on the 177x branch ?

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

Not fixed, we have an expected error
![image](https://user-images.githubusercontent.com/16067358/74856171-fc5aa500-5341-11ea-9d78-dd7d9dd2a0c3.png)
https://drive.google.com/file/d/1igte2JACrtZKEiJGvO4NR2GGJPpwtPdG/view

Thanks!

**Comment by Progi1984** [comment]
Fixed by #17804
