### ISSUE TITLE
BO - Product page - combinations creation

### ISSUE THREAD

**Issue by rGaillard** [PrestaShop/PrestaShop#12440]
**Describe the bug**
When you want to generate combinations on the product page this is the public name of the attributes group which is autocomplete instead of the name. If you have multiple attribute groups with the same public name, you will not know which is the good one.

**To Reproduce**
- Create 2 attribute groups with Size as public name
- Create a new product
- Type Size in the search box

**Additionnal information**
PrestaShop version: 1.7.5

**Comment by khouloudbelguith** [comment]
Hi @rGaillard,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
I created a new Attribute with

- Name: test
- Public name: Size

![image](https://user-images.githubusercontent.com/16067358/52328703-cbd2f200-29f0-11e9-82a3-a6639a395845.png)

In the Product page, combination tab, when I type Size in the search box, the Public name of attributes will be displayed instead of their internal name.

![image](https://user-images.githubusercontent.com/16067358/52328723-e4430c80-29f0-11e9-8d90-ed1624826720.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
We should be able to search by private name

**Comment by MatShir** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/23865
