### ISSUE TITLE
Problem : Ranges are overlapping 1.7.5

### ISSUE THREAD

**Issue by morghy1992** [PrestaShop/PrestaShop#12502]
**Describe the bug** Hello, I am having trouble modifying the ranges for shipping. 
Continuously it comes out Ranges are overlapping  and it does't allow me to modify it.
How can I resolve the problem? What can I do for not having again this problem? 

<img width="1005" alt="schermata 2019-02-07 alle 21 05 01" src="https://user-images.githubusercontent.com/47249256/52439669-6da32d80-2b1c-11e9-8e1d-9fb0e9f91e20.png">

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

The issue occurs because you have invalid ranges saved in your database.
If you use a price range, you need to edit the ranges in the table `ps_range_price`
If you use a weight range, you need to edit the ranges in the table `ps_range_weight`
![image](https://user-images.githubusercontent.com/16067358/52467133-b8589000-2b84-11e9-9d09-d733ca7af8d4.png)

Thanks to check & feedback.

**Comment by morghy1992** [comment]
@khouloudbelguith Thanks for the answer, 
But I don't know where it Is, 
Where can I find this ps_range_weight ? 

Thank you for paying attention.

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

In your BO => Advanced Parameters => Information page, You can find your "Database information".
MySQL name => your database name
Tables prefix => the prefix of your table for example ps_
![image](https://user-images.githubusercontent.com/16067358/52559001-5e5e0180-2df4-11e9-9fca-259809f624ea.png)
You need to access to your database, search for the table prefix_range_weight.
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @morghy1992,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
