### ISSUE TITLE
Error total count in order edit PS 1.7.5

### ISSUE THREAD

**Issue by Goretsv** [PrestaShop/PrestaShop#12521]
I have store with USD default currency, but many orders are made by customers in UAH. If you try to edit the price / add / remove goods in the admin panel, you get absolutely incorrect sum total.

1. Create store with at least two currencies
2. Place your order in a non-default currency
3. Try admin panel to add product to order.

>Edit by Khouloud: https://github.com/PrestaShop/PrestaShop/issues/16937

If you change status of the order to "Payment accepted", consult the invoice: The sums in the invoice are wrong too (but currency sign is OK)

**Screenshots**
https://prnt.sc/minwqu

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 5.5

**Comment by Goretsv** [comment]
Also i can reproduce this bug on Prestashop demo store:
https://pastenow.ru/795a1676a3b9d22eef8a4696234e1b13

**Comment by khouloudbelguith** [comment]
Hi @Goretsv,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/52554796-3d8faf00-2de8-11e9-92ac-ce9bfff35821.png)
https://drive.google.com/file/d/115SZeeviZHn41N7Eo6FGuIrx4ydkPjK8/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Related to #9850
Thanks!

**Comment by Progi1984** [comment]
Fixed by #17927
