### ISSUE TITLE
Uninstall module ps_customeraccountlinks with CLI

### ISSUE THREAD

**Issue by sebastienhouzet** [PrestaShop/PrestaShop#12553]
**Describe the bug**
Error during Uninstall module ps_customeraccountlinks with CLI

**To Reproduce**
Open terminal, go on root folder prestashop.
php bin/console prestashop:module uninstall ps_customeraccountlinks

**Screenshots**
10:36:13 ERROR     [console] Error thrown while running command "prestashop:module uninstall ps_customeraccountlinks". Message: "Call to undefined method Ps_Customeraccountlinks::removeMyAccountBlockHook()" ["exception" => Error { …},"command" => "prestashop:module uninstall ps_customeraccountlinks","message" => "Call to undefined method Ps_Customeraccountlinks::removeMyAccountBlockHook()"] []

In ps_customeraccountlinks.php line 66:
                                                                                                              
  Attempted to call an undefined method named "removeMyAccountBlockHook" of class "Ps_Customeraccountlinks".  
                                                                                                              
**Additionnal information**
PrestaShop version: 1.7.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @sebastienhouzet,

I manage to reproduce the issue with PS1.7.5.0 & the `ps_customeraccountlinks` module v3.1.0.
![image](https://user-images.githubusercontent.com/16067358/52712600-62755500-2f95-11e9-9b4a-5841f8e3df72.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Related to #12552

**Comment by colinegin** [comment]
I close this issue as the PR has been merged. Thanks !
