### ISSUE TITLE
Uninstall module Welcome with CLI

### ISSUE THREAD

**Issue by sebastienhouzet** [PrestaShop/PrestaShop#12552]
**Describe the bug**
Uninstall module welcome with CLI

**To Reproduce**
Open terminal, go on root folder and exec
php bin/console prestashop:module uninstall welcome

**Screenshots**
root@4236fd5fec0c:/var/www/html# php bin/console prestashop:module uninstall welcome
11:03:13 ERROR     [console] Error thrown while running command "prestashop:module uninstall welcome". Message: "Notice: Use of undefined constant _PS_ADMIN_DIR_ - assumed '_PS_ADMIN_DIR_'" ["exception" => Symfony\Component\Debug\Exception\ContextErrorException { …},"command" => "prestashop:module uninstall welcome","message" => "Notice: Use of undefined constant _PS_ADMIN_DIR_ - assumed '_PS_ADMIN_DIR_'"] []

In Configuration.php line 289:
                                                                               
  Notice: Use of undefined constant _PS_ADMIN_DIR_ - assumed '_PS_ADMIN_DIR_'  
                                                                               

prestashop:module [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] <command> <action> <module name> [<file path>]

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @sebastienhouzet,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & the welcome module v5.1.0.
![image](https://user-images.githubusercontent.com/16067358/52708396-4ddf8f80-2f8a-11e9-8686-2e0dde3b5696.png)
I tried with the same command with PS1.7.4.4, also I have an error `Cannot uninstall module welcome. The module is invalid and cannot be loaded.`

I tried to uninstall the ps_legalcompilance & ps_brandlist with CLI => ok.

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

**Comment by matks** [comment]
Looks similar to https://github.com/PrestaShop/PrestaShop/issues/23370

**Comment by marionf** [comment]
Hello, 

The welcome module will be archived with the V8.0.0, so I close this issue.
