### ISSUE TITLE
Installation Error : the % symbol is doubled on the parameters.php file generation

### ISSUE THREAD

**Issue by Fabuloops** [PrestaShop/PrestaShop#12556]
**Describe the bug**
When you put a database password with the symbol "%" at installation, this character is doubled in the parameters.php file
It caused me a lot of trouble

**To Reproduce**
1. Start a new install of prestashop
2. In the database configuration step, put a password with a % symbol
3. Finish the installation and look at the /app/config/parameters.php
4. See error on the database password

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @Fabuloops,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0.
I checked the file /app/config/parameters.php, I found that 'database_password' => '%%test', but in our case the database password is %test.
In the FO, BO there are no problems.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Related to #12413 & #9564

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.4.4.
Thanks!

**Comment by matks** [comment]
This is a Symfony behavior: https://github.com/symfony/symfony-standard/issues/1084
