### ISSUE TITLE
The OnBoarding popup doesn't appear in the Theme & logo, payment and carriers pages

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#12560]
**Describe the bug**
On the develop branch, with the Welcome module v5.1.0 the OnBoarding popup doesn't appear in the Theme & Logo page.

**To Reproduce**
1. Fresh install Develop branch ( PS1.7.6.0)
2. When you navigate into the BO => Start with the welcome module
3. In the third step "Give your shop its own identity", the OnBoarding popup disappear ( in the Theme & Logo page)

**Screenshots**
https://drive.google.com/file/d/1JXRF4x5aJDR8U43Z6-Ha1tJ7pp05zuVa/view

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Same issue in the Payment methods page & the Carriers page
https://drive.google.com/file/d/1WFJP_JD6nxKw7R6VWC7cHYNCLZNrhnn0/view?usp=drivesdk
Thanks!

**Comment by colinegin** [comment]
@samuel-pires should we fix it or disable the module ?

**Comment by ghost** [comment]
@colinegin we should fix it.
Especially if we want to improve it later to add more information during the onboarding.

**Comment by colinegin** [comment]
Ok, i add it to the to do column then.

**Comment by SimonGrn** [comment]
The OnBoarding module seems to be broken from almost the beginning of the tutorial. On the first steps (when the module guides you to create a new product) every time you click on "Continue" the popup appears then instantaneously disappears.
You can't know what fields you have to fill to continue to the next step.

**UPDATE**: I installed my PrestaShop in French and added the English language after. With this configuration, it's impossible to use the tutorial.

**Comment by SimonGrn** [comment]
**Update**:
Here is how to reproduce this problem 100%: Install PrestaShop 1.7.6.x with any language, any country (example: country France and language English).

The OnBoarding module will then works **only** in the **language** that was selected during the installation. In the example above, the module would work in English but not in French (which was installed automatically because the country was set to France).
It will also not work with a new language pack if you install it through the localization BO page.

For example :
- language Spanish, country Italy: works in spanish, not in italian. Doesn't work with english when added later.
- language English, country France: works in english, not in french.

**Comment by marionf** [comment]
Here the regression for 1.7.6 is only on Theme & logo, payment and carriers pages
The issue with the language is an old one

**Comment by PierreRambaud** [comment]
Fixed here: https://github.com/PrestaShop/welcome/pull/56
