### ISSUE TITLE
Blank {followup} placeholder in the 'in-transit' template

### ISSUE THREAD

**Issue by febestore** [PrestaShop/PrestaShop#12592]
**Describe the bug**
Clients reported that they don't receive tracking information. I have reproduced the issue. Let me explain.
Our backoffice is synchronized by API web service with storehouse. Shipping number is generated outside of Prestashop backoffice and pasted in by web service. However that cause problem - when API service is changing order status automatic emails are not sending. 
That's why when the order is finished I'm changing order status to "Sent" manually. 
When I'm doing that {followup} placeholder doesn't work. 

Do You have any clue why it's not working?

Or is it any other way to edit the email template? What are available placeholders? Because {shipping_number} doesn't work as well. 
I could make a change that email will look like:
Shipping service: DB Schenker
Shipping number: {shipping_number}
Tracking link: - I could manually paste a general link to the carrier -
Any way to make that possible?

**Screenshots**
**[Screenshot 1]**  
I've made an carrier for testing. As You can see there is an DB Schenker tracking URL.
![1](https://user-images.githubusercontent.com/40421616/52863093-342f7b00-3137-11e9-9903-a23e76a367e0.JPG)
**[Screenshot 2]** 
There is an 'in-transit' email translation. Followup placeholder is as default.
![2](https://user-images.githubusercontent.com/40421616/52863094-342f7b00-3137-11e9-8331-3e53cee479af.JPG)
**[Screenshot 3]** 
As You can see shipping numer is generated correctly. When I click on it redirecting me to the DB Schenker website with the correct number. I've underlined URL
![3](https://user-images.githubusercontent.com/40421616/52863095-342f7b00-3137-11e9-9531-dd78594fc19e.JPG)
**[Screenshot 4]** 
Screenshot of email which I've received after the status change. Name and order id is downloaded. However [followup] placeholder doesn't 
![4](https://user-images.githubusercontent.com/40421616/52863098-342f7b00-3137-11e9-8c9c-40df8b076c9e.JPG)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.32

**Comment by khouloudbelguith** [comment]
Hi @febestore,

I did not manage to reproduce the issue with PS1.7.5.0.
![image](https://user-images.githubusercontent.com/16067358/52865139-2c260a00-313c-11e9-9b55-22c68e6dc65c.png)
Could you please provide some information about this only carrier, did you created it manually or it is a customized module that you installed?
Thanks!

**Comment by febestore** [comment]
It's manually created carrier. Without any modifications. When You manually write a shipping number {followup} works fine. But When You change order status with 'in_transit' template it doesn't work. 

Can I ask You to write me an email or private message? I will show You video with all the steps. 
It has few personal data I don't want to paste this in public.
Cheers

**Comment by khouloudbelguith** [comment]
Hi @febestore, 

This is a public space.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by khouloudbelguith** [comment]
@febestore, thanks a lot for these clarifications.
To reproduce this issue, we need to follow these steps:
1. Go to BO => Shop Parameters => Order Settings => Statuses Tab, edit the `Delivered` status where 
1.1 Send an email to the customer when his/her order status has changed. should be checked
1.2 Template => in_transit
![image](https://user-images.githubusercontent.com/16067358/52963842-27ae5b00-33a1-11e9-8258-d623beed4730.png)
2. Create a carrier with a Tracking URL: `http://example.com/track.php?num=@`
3. Create an order from FO/BO of this order to `Delivered`
4. In the BO => order details page: Edit the `Tracking number`
![image](https://user-images.githubusercontent.com/16067358/52963974-7b20a900-33a1-11e9-9931-08877d1fd901.png)
5. Update the status of this order to `Delivered`
6. You will receive an email with an empty link.
![image](https://user-images.githubusercontent.com/16067358/52964088-c3d86200-33a1-11e9-9c07-00cddfdfd374.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Issue reproduced on PS1.7.5.1 / PS1.7.5.0 / PS1.7.4.4
Thanks!

**Comment by jf-viguier** [comment]
Hi all, 
I've fixed this bug in this pull request: https://github.com/PrestaShop/PrestaShop/pull/12705
Hope this helps.

**Comment by febestore** [comment]
Hello,
You are the real MVP. Everything works after modifications!
Screenshot:
![1](https://user-images.githubusercontent.com/40421616/53397312-1ec41780-39a7-11e9-93e1-a534c03dc14f.JPG)

Thanks!
