### ISSUE TITLE
Module Manager (in Modules menu) is not translated

### ISSUE THREAD

**Issue by LouToma** [PrestaShop/PrestaShop#12590]
**Describe the bug**
When BO is set in French for example, Module Manager is still in English in the Modules menu.

**Comment by khouloudbelguith** [comment]
Hi,

Same issue with PS1.7.5.0 & PS1.7.5.1build1 & the develop branch.
Thanks!

**Comment by colinegin** [comment]
@LouiseBonnard do you think this is a translation issue ? IMO this is the translation we have set for french. What do you think ?

**Comment by LouiseBonnard** [comment]
@colinegin, not at all because it is correctly translated in Crowdin. I think there is a kind of bug on this entry because I have the string "Module manager" in the Crowdin catalog while I should have the string "Module Manager". And that might explain why it is not translated in the back office.

I remember having seen another remark about it but I can't find where... 🤔

**Comment by Progi1984** [comment]
Fixed by #17986
