### ISSUE TITLE
display_taxes_label not changable in backoffice

### ISSUE THREAD

**Issue by johanlantz** [PrestaShop/PrestaShop#12601]
On PS 1.7.5

Maybe I am missing something but I am not able to find the option in BO that will remove this line in product-prices.tpl

 {if $configuration.display_taxes_label}
        {$product.labels.tax_long}
      {/if}

**Comment by khouloudbelguith** [comment]
Hi @johanlantz,

To disable the `Display tax label` in the FO, you need to navigate to the BO => International => Locations => Countries Tab => Search for your country => Edit it, in the bottom of the page, you can find the `Display tax label` option, you can disable it.
![image](https://user-images.githubusercontent.com/16067358/52935864-d8453c00-335a-11e9-8c27-3d8b5be9fec3.png)
So, the tax label will not be displayed in the product page, in the other page, (shopping cat for example,...), we have already an issue added to our bug roadmap: #9808, so that it will be fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
