### ISSUE TITLE
Admin menu tab not selected for stock

### ISSUE THREAD

**Issue by sebastienhouzet** [PrestaShop/PrestaShop#12615]
**Describe the bug**
When you open stocks page on Admin, the menu Catalog is closed.

**To Reproduce**
Install version 1.7.4.0
Connect on Admin, click on Catalog and Stocks.

**Screenshots**
![capture d ecran 2019-02-18 a 20 08 09](https://user-images.githubusercontent.com/2550639/52971770-fd689780-33b8-11e9-92d2-71eec76f0711.png)

**Additionnal information**
PrestaShop version: 1.7.4.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @sebastienhouzet,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.5.0 & PS1.7.4.4.
When I open the Stocks page on Admin, the menu Catalog is closed, it is not the same behavior with all other pages.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by colinegin** [comment]
I don't manage to reproduce this issue with PS 1765.
@florine2623 can you confirm we can close this issue ?

**Comment by hibatallahAouadni** [comment]
Hello everyone,

I didn't manage to reproduce the issue with PS1.7.6.7 and PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1gQwwoJwfhY0GaFrtN37Zc5mhsJMNk8M3/view

I close this issue cause it's fixed.
Thanks!
