### ISSUE TITLE
Empty/blank orders in backoffice in PS 1.6.1.6

### ISSUE THREAD

**Issue by hellodracon** [PrestaShop/PrestaShop#12612]
Hello, I found a related issue on this but not really (and it's closed) so I'm trying a new post.
In one month, I received two blanks orders. The payment module had no change, and we didn't make any specific change on the Prestashop. Weird thing is that it happened two times, with only one payment option. We did get the payment (as we checked it in the bank logs) but nothing appears well in the order page. I'm trying to get some infos from people to know if anything weird happened while they were paying.

I know that you are supporting PS 1.6 for major issues, I guess that's one. Let me know !
Thank you.

**Screenshots**
![capture d ecran 2019-02-18 a 15 43 06](https://user-images.githubusercontent.com/5995162/52958619-be284f80-3394-11e9-95cb-b0cdf519415c.png)
![capture d ecran 2019-02-18 a 15 42 57](https://user-images.githubusercontent.com/5995162/52958620-bec0e600-3394-11e9-87f3-12e7aeff19e1.png)
![capture d ecran 2019-02-18 a 15 42 51](https://user-images.githubusercontent.com/5995162/52958621-bec0e600-3394-11e9-95fb-d4d1fb596809.png)
![capture d ecran 2019-02-18 a 15 42 42](https://user-images.githubusercontent.com/5995162/52958622-bec0e600-3394-11e9-98c3-ab0f1d28eaae.png)

**Additionnal information**
PrestaShop version: 1.6.1.6

**Comment by khouloudbelguith** [comment]
Hi @hellodracon,

I did not manage to reproduce the issue with PS1.6.1.23.
What is the exact payment module did you use?
The status of this order is determined?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by hellodracon** [comment]
Hi @khouloudbelguith , 

1- I'm using a non official module (Square Official Payment). But everything is quite good with it except these two payments. We got multiple orders everyday and they are all working fine.
2- no status on these orders. Just a "–" as you can see in the first screenshot.
3- How can I give you this informations ? There are other logs than the ones in the backoffice ?

**Comment by khouloudbelguith** [comment]
@hellodracon, have you tried to contact the module author about this issue?
Don't you know how to get this information? Please read the following article:
**Adding logs**
Sometimes you just don’t know what’s wrong: something’s not happening, that’s all.
That’s where log data can be helpful. They keep track of what is happening and allows to trace back to the moment when the issue happens.
There are several different log data that you can add as a file to your ticket:
 * Server log:
 ** Apache: /var/log/apache/apache_error.log
 ** Nginx: /var/log/nginx/nginx_error.log
 ** IIS: %SystemDrive%\inetpub\logs\LogFiles
 * PHP error log:
 ** Apache: /var/log/apache/php_error.log
 ** Nginx: /var/log/php-fpm/default/error.log
 ** IIS: %SystemDrive%\inetpub\logs\LogFiles
 * Console log:
 ** Firefox and Chrome: press Ctrl+Shit+J or Cmd+Shift+J.
 ** Internet Explorer and Edge: press F12 then go to the Console tab.

Copy the content relevant to your issue (or to the time the issue appeared), and paste it into the ticket 
**Enabling Debug Mode + cache**
PrestaShop has a debug mode, which can be used to see the non-obvious errors in your shop. For instance, in these situations:
 * The browser displays a blank page.
 * The browser displays a 500 Internal Server Error.
 * You cannot log into your dashboard, or access certain pages of the back office.

To turn on the Debug mode on PrestaShop, follow these steps using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

{{define('_PS_MODE_DEV_', false);}}

… and change it to:

{{define('_PS_MODE_DEV_', true);}}

Finally, emptying the cache of PrestaShop can also be useful, because it ensures that your browser only displays newly-generated files instead of old cached ones. 
Thanks!

**Comment by hellodracon** [comment]
Oh ok sorry, I misread the log things, I thought it was other logs in PS.
I got these errors : 

> [Sun Feb 17 13:54:26 2019] [error] [client 175.177.5.139] [host www.xxxx.com] (104)Connection reset by peer: AH10143: FastCGI: comm with server "/homez.138/ramdaneckg/xxxx/modules/squareup/validation.php" aborted: read failed, referer: https://www.xxxx.com/jp/module/squareup/payment
[Sun Feb 17 13:54:26 2019] [error] [client 175.177.5.139] [host www.xxxx.com] AH10149: FastCGI: incomplete headers (0 bytes) received from server "/homez.138/ramdaneckg/xxxx/modules/squareup/validation.php", referer: https://www.xxxx.com/jp/module/squareup/payment
[Sun Feb 17 13:54:26 2019] [error] [client 175.177.5.139] [host www.xxxx.com] AH10157: FastCGI: An error happend on Fastcgi processing, fallback to CGI, referer: https://www.xxxx.com/jp/module/squareup/payment
[Sun Feb 17 13:54:27 2019] [error] [client 175.177.5.139] [host www.xxxx.com] (104)Connection reset by peer: AH10143: FastCGI: comm with server "/homez.138/ramdaneckg/xxxx/index.php" aborted: read failed, referer: https://www.xxxx.com/jp/module/squareup/payment
[Sun Feb 17 13:54:27 2019] [error] [client 175.177.5.139] [host www.xxxx.com] AH10149: FastCGI: incomplete headers (0 bytes) received from server "/homez.138/ramdaneckg/xxxx/index.php", referer: https://www.xxxx.com/jp/module/squareup/payment
[Sun Feb 17 13:54:27 2019] [error] [client 175.177.5.139] [host www.xxxx.com] AH10157: FastCGI: An error happend on Fastcgi processing, fallback to CGI, referer: https://www.xxxx.com/jp/module/squareup/payment

I guess that's not because of PS then but more like the bank's server/module or our server ?

Thank you !

**Comment by khouloudbelguith** [comment]
@hellodracon, as described in your php log, it is a `squareup` module issue.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by hellodracon** [comment]
Thank you and sorry it wasn't PS related
