### ISSUE TITLE
"Bad request" error message when using bulk edit quantity with "0"

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#12672]
#### Describe the bug
"Bad request" error message when using bulk edit quantity with "0"

#### Steps to reproduce

1. BO>SELL>Catalog>Stock
2. Try to edit the quantity using the bulk edit with "0"
3. See error > "Bad request" error message is displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/153583973-f71f2955-f673-469f-8d1f-b1c29b29178b.png)

#### Addtional infos 

- PS version: 1.7.5.1 on debian 9.8
- PHP version: 7.2.15

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.4; PS1.7.5.1 & develop branch.
![image](https://user-images.githubusercontent.com/16067358/53246418-e4a9fb80-36b0-11e9-9ed1-a5c8014ad8f2.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by centoasa** [comment]
Is there a way to bring the quantities of the selected products to zero?
If I set 0 the mass update stock, quantities do not change

**Comment by florine2623** [comment]
This is fixed on PS 8.1.x, 9.0.x.


https://github.com/PrestaShop/PrestaShop/assets/16019289/d8bc2c22-8fc4-44e2-9d39-1ed85b082a4a

I'm closing this issue to avoid clogging the backlog.

If you need to put quantity to 0, you need to subtract the quantity.
