### ISSUE TITLE
It is possible to buy items out of stock 

### ISSUE THREAD

**Issue by axisepm** [PrestaShop/PrestaShop#12688]
Steps to reproduce: 

1) Create two user accounts 
2) With one account, add all the stock of one product to the basket, and then close the session
3) Start session with the other account and add all the stock of the same product to the basket. 
4) Proceed to checkout and finish the buy process until obtaining the order confirmation
5) Open the first account again and with the basket from step 2, also finish the operation

Expected result
The second user should not be able to complete the order and he should be informed about which item is out of stock. 

Actual result 

The second user can finish their orders and the stock is left negative

**Comment by khouloudbelguith** [comment]
Hi @axisepm,

Thanks for your report.
Did you use a PrestaShop version less than 1.7.3.2?
Because this issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/8752, it is fixed in the PS1.7.3.2.
Thanks to check & feedback.

**Comment by axisepm** [comment]
Hi, I'm stepping in 1.6.18, can this be fixed in 1.6 branch as well? It is causing a lot of trouble in our inventory management and we are receiving a lot of complaints from or customers.

**Comment by khouloudbelguith** [comment]
Hi @axisepm,

First of all, thank you for reporting your issue!
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be accepted in the `1.6.1.x` branch.
Thanks for your understanding!
