### ISSUE TITLE
Prestashop 1.7.5 new install - after order white page, no email to customer

### ISSUE THREAD

**Issue by caisik** [PrestaShop/PrestaShop#12685]
Hello,

i just install prestashop 1.7.5 few days ago.

I tested to order something. When i comfirm order, just white page show. No email come with order detail.

At order menu when i want to change status order show this error.
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
 
At log show this.
 
Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart

i can't to turn on debug mode because my webhosting have disabled putenv from security reason.
 
Thank you for any help. 

**Additionnal information**
PrestaShop version: 1.7.5.0
 PHP: 7.1.3
memory: 128M

**Comment by khouloudbelguith** [comment]
Hi @caisik,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
The error 500 cannot help us to understand the exact issue.
About `Putenv`, We have updated the Symfony version, this new version uses the `Putenv` function.
In fact, PrestaShop 1.7 was moved To Symfony 3.4 And PHP 5.6.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @caisik,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
