### ISSUE TITLE
after modify product quantity change to zero in PrestaShop 1.7.5.1

### ISSUE THREAD

**Issue by IranDec** [PrestaShop/PrestaShop#12777]
Hi I have some problem in my back office

1- after modifying a product the quantity of that product change to zero in PrestaShop 1.7.5.1 rtl (Persian language panel )
2- and in some page I can't modify the product and I get error can't saving

Both of problem related to Persian language panel , because last days I added English language to my back office and test the both of them with English dashboard and I don't get any errors and all things work it fine .

3- in front office when a customer want to add their address (in mobile and tablet ver ), get postal code and mobile phone type errors and both of them accurate when a customer use persian numeral keyboard in there phone and don't use default keyboard numeral.

**Comment by shikotakcom** [comment]
If I want to complete our friend report, I should say after modifying a product in Persian language, the quantity of products is shown in back office but in front office the product can not be order and  its quantity is zero.
And it seems this problem is just in Persian language.

**Comment by farhadheshmati** [comment]
Hi
I have some problem in 
my Persta panel

1- after modifying a product the quantity of that product change to zero in PrestaShop 1.7.5 rtl (Persian language panel)
2- and in some page I can't modify the product and I get error can't saving

3- in frontend when a customer want to add their address (in mobile and tablet version), get postal code and mobile phone type errors and both of them accurate when a customer use persian numeral keyboard in there phone and don't use default keyboard numeral.

Please help me to solve this problems

Thanks

**Comment by khouloudbelguith** [comment]
Hi @IranDec, @farhadheshmati, @shikotakcom,

About the first & the second issue, I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1yinYrgC8jmBjGJsAwq9tml1MKXBARVDB/view
About the last issue, do you need to add a code postal with Arab number like attached in the screenshot?
![image](https://user-images.githubusercontent.com/16067358/53724318-ea9a9c00-3e69-11e9-9a93-41ca407f7003.png)
Thanks!

**Comment by IranDec** [comment]
Hi @khouloudbelguith
I get one video for first & the second issue,
https://drive.google.com/open?id=1MjhRa1m-xhN57k5VjgkbRgaefNBLQiwa
yes add a postal code and any part needed to write numeral with Arab number in front office .

**Comment by khouloudbelguith** [comment]
Hi @IranDec,

Thanks for your feedback.
In your screen record.
The first product edit is successfully saved
![image](https://user-images.githubusercontent.com/16067358/53864566-172af100-3fed-11e9-822c-52283ed50160.png)
But the second Product no,
![image](https://user-images.githubusercontent.com/16067358/53864593-2ca01b00-3fed-11e9-9fe5-8ac6c892dd52.png)

What is the difference between these two products?
Friendly URL is enabled or not?
Accented URL is enabled or not? if no, thanks to enabling it, check & feedback.

About the second issue, could you please try to create a new issue because it is an improvement issue & different from the first one.
Thanks!

**Comment by ced--ced** [comment]
I have the same problem with the pack quantity resetting itself to 0.

Presta 1.7.5.1 ltr

**Comment by khouloudbelguith** [comment]
Hi @ced--ced,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/15Agupg_ZouXmhPFp-7OX3A5GL2RHZUpD/view
Did you installed your shop with which language/ country?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by ced--ced** [comment]
Hi @khouloudbelguith,

Here is a video of the problem I have: https://www.useloom.com/share/64d310f3537247d7a878fdd14a6ea127

I didn't install the site but I think it was installed with French / France.

I guess the PHP error log is to retrieve from the server, but where do I find the debug mode report?

Thanks

**Comment by IranDec** [comment]
Hi @khouloudbelguith
Thanks for your followup.
Friendly URL and Accented URL both of them are enabled, and there isn't any difference between both product.
for second problem I create new issue 
https://github.com/PrestaShop/PrestaShop/issues/12858

**Comment by khouloudbelguith** [comment]
Hi @ced--ced,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1Gw0Y3iYkdBCxcJJ5GBwlXNr6W1gRs6tE/view
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ced--ced** [comment]
Hi @khouloudbelguith,

I have made a new video with the debug mode on. The problem is still there: https://www.useloom.com/share/a67945dc1ea947f89a0d1354f6373a4e.

Host: DigitalOcean from Cloudways
Config: PHP7.1, MySQL5.5
Prestashop 1.7.5.1
Logs are attached

Thanks



[apache_prestashop-170674-493492.cloudwaysapps.com.access-log.txt](https://github.com/PrestaShop/PrestaShop/files/2987385/apache_prestashop-170674-493492.cloudwaysapps.com.access-log.txt)
[nginx_prestashop-170674-493492.cloudwaysapps.com.access-log.txt](https://github.com/PrestaShop/PrestaShop/files/2987386/nginx_prestashop-170674-493492.cloudwaysapps.com.access-log.txt)
[nginx_prestashop-170674-493492.cloudwaysapps.com.error-log.txt](https://github.com/PrestaShop/PrestaShop/files/2987387/nginx_prestashop-170674-493492.cloudwaysapps.com.error-log.txt)
[nginx-app.status-log.txt](https://github.com/PrestaShop/PrestaShop/files/2987388/nginx-app.status-log.txt)

**Comment by khouloudbelguith** [comment]
Hi @ced--ced,

When debug mode is enabled, there are no exceptions displayed.
About your logs, I cannot read them
![image](https://user-images.githubusercontent.com/16067358/54763968-32098200-4bf7-11e9-9190-860441172ca7.png)
Thanks to check & feedback.

**Comment by ced--ced** [comment]
Hi @khouloudbelguith,

Would you have any news regarding my problem?

Thanks

**Comment by khouloudbelguith** [comment]
@ced--ced, in my previous comment, I checked your files, but as you can see in my last screenshot, I can not read them.
thanks to provide me again those files.
Thanks!

**Comment by ced--ced** [comment]
@khouloudbelguith, I've changed their format. Is that better?

[nginx-app.status-log copy.txt](https://github.com/PrestaShop/PrestaShop/files/3007855/nginx-app.status-log.copy.txt)
[nginx_prestashop-170674-493492.cloudwaysapps.com.error-log copy.txt](https://github.com/PrestaShop/PrestaShop/files/3007856/nginx_prestashop-170674-493492.cloudwaysapps.com.error-log.copy.txt)
[nginx_prestashop-170674-493492.cloudwaysapps.com.access-log copy.txt](https://github.com/PrestaShop/PrestaShop/files/3007857/nginx_prestashop-170674-493492.cloudwaysapps.com.access-log.copy.txt)
[apache_prestashop-170674-493492.cloudwaysapps.com.access-log copy.txt](https://github.com/PrestaShop/PrestaShop/files/3007858/apache_prestashop-170674-493492.cloudwaysapps.com.access-log.copy.txt)

**Comment by khouloudbelguith** [comment]
@ced--ced, Yes now your files can be read, but there are no errors related to your issue.
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!

**Comment by IranDec** [comment]
Hi @khouloudbelguith 
my host disable putenv() and I can't access to debug place,  I send several messages to my host to enable that option but they don't accept to do it.
 is it any other solution to check the error log of the product page?

**Comment by khouloudbelguith** [comment]
Hi @IranDec,

To check the error log, it is necessary that the debug mode is enabled.

**Comment by samberrry** [comment]
please open the issue. There is still same problem on the latest version 1.7.7.4. This problem occur on RTL languages. There is also same issue on Arabic. This is a major issue on RTL languages.
I try to create a PR for it. 
Thanks

**Comment by samberrry** [comment]
It's worth to mention that this happens on products which have combinations.

**Comment by samberrry** [comment]
@hibatallahAouadni please check the issue, as I've explained. Thanks

**Comment by matks** [comment]
> please open the issue. There is still same problem on the latest version 1.7.7.4. This problem occur on RTL languages. There is also same issue on Arabic. This is a major issue on RTL languages.
> I try to create a PR for it.
> Thanks

Re-opening an issue that is 3 years old is only going to bring confusion 😄 

If you observe the same bug and you have an accurate list of steps we can use to reproduce the bug please open a new issue 😉  . A new issue will be better, with less noise, and easier to manage and track.

**Comment by samberrry** [comment]
@matks Ok great.
