### ISSUE TITLE
Nginx configuration update for multilang site

### ISSUE THREAD

**Issue by gorazdr** [PrestaShop/PrestaShop#12791]
Could you please update your nginx configuration (https://github.com/PrestaShop/PrestaShop/blob/develop/docs/server_config/nginx.conf.dist)
so that it works when multiple languages are enabled.

I added this to my configuration right after Symhony:
#multilang
rewrite ^/([a-z]{2})/(.*) /$1;

and it works now but I am not sure if that is optimal solution.

PS version 1.7.5.0 
problem urls:
- Product attachments
  http://siteurl/en/index.php?controller=attachment&id_attachment=2
- Quick view
  http://siteurl/en/index.php?controller=product

Thanks, Gorazd

**Comment by khouloudbelguith** [comment]
Hi @gorazdr,

Here's a pull request to inject multi lang & multishop configuration: https://github.com/PrestaShop/PrestaShop/pull/12082/files#diff-b115851dfa6156b9d45986fb7d75c601R103
Thanks to check & feedback.

**Comment by gorazdr** [comment]
As I can see in pull request rewrite is for one specific langage (fr), my rewrite is for any language.
Thanks

**Comment by khouloudbelguith** [comment]
@gorazdr, thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4
I attached a video record.
https://drive.google.com/file/d/1VyBqbKoNSuF_HlCP7V2AuwTXWG_56Q9E/view
I used `NGINX_VERSION | 1.14.0`
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request.
ping @PierreRambaud 
Thanks!

**Comment by PierreRambaud** [comment]
Hi,
You must write your own rules, like we do for Apache. You must not use a rewrite where you don't need it.
More because it's an example and you can customize this part by everything you want.

Kind regards,
