### ISSUE TITLE
Data mining for statistics - cpu resource

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#12813]
For the module "Data mining for statistics" please explain in detail the meaning of the 3 buttons and their relative consumption in terms of cpu and ram: https://nimb.ws/N71z0T

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Apply data mining help you to collect all the statistics you need to focus on your activity. Here, it allows to :
 

- Save page views for each customer, useful for the Visitors Online module
- Save global page views
- Detect plugins

You must be careful with some option because `storing page views` uses a lot of resources and database space. We advise you to enable it only if your server can handle it.
In fact, it takes very huge space in the database because it collects statistics from connections, from page views, ..., a lot & large number of data and it will be saved on your database.
Thanks!

**Comment by centoasa** [comment]
Thank you so much: in particular, what do you mean by "Detect plugins"? this plugin what is it for?

**Comment by khouloudbelguith** [comment]
@centoasa, some plugins as defined in this section: https://github.com/PrestaShop/statsdata/blob/31c4c8aa8a8dc243b9413b89a671bf075a73f784/statsdata.php#L85
Thanks!
