### ISSUE TITLE
Incorrect product price in backoffice "Catalog" product list with multistore feature.

### ISSUE THREAD

**Issue by PatrykMakowski** [PrestaShop/PrestaShop#12853]
**Describe the bug**
Product price in admin controller "sell/catalog/products" is incorrect for current shop context. 
At product list price is always from ps_product table (in multistore should be ps_product_shop i think)

**To Reproduce**
1. Enable multistore and create another shop. Eg. Shop A and Shop B.
2. Change product price only at Shop A.
3. Switch to Shop B and go to product list (Catalog) in backoffice
4. Product price in list will be from Shop A.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
https://i.imgur.com/NEDRpZQ.png

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @PatrykMakowski,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.1 & PS1.7.4.4.
![image](https://user-images.githubusercontent.com/16067358/54109465-06a8bb00-43df-11e9-8a12-7ddd9de702c6.png)
![image](https://user-images.githubusercontent.com/16067358/54109506-22ac5c80-43df-11e9-93a9-e0f9f144ae08.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by pabrigarcia** [comment]
Hi,

We managed to fix this issue changing the line 

From

212 - `'price' => array('table' => 'p', 'field' => 'price', 'filtering' => ' %s '),`

To 

212 - `'price' => array('table' => 'sa', 'field' => 'price', 'filtering' => ' %s '),`

In the /src/Adapter/Product/AdminProductDataProvider.php

This change makes the prestashop listing grab the prices from the ps_product_shop table instead of ps_product.

**Comment by khouloudbelguith** [comment]
Hi @pabrigarcia,

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop
Thank you!

**Comment by pabrigarcia** [comment]
@khouloudbelguith 

It looks like the line is changed in the current version. The bug only exists in the earlier versions.

**Comment by khouloudbelguith** [comment]
@pabrigarcia, yes great.
I cannot reproduce this issue on the branch 1.7.6.x
https://drive.google.com/file/d/1H9p3tiLTTnkz6F1u1n2WeBL7jdG6RmOk/view
Thanks a lot!
