### ISSUE TITLE
No shipping methods available

### ISSUE THREAD

**Issue by makritos** [PrestaShop/PrestaShop#12866]
Hi all,
I'm trying to find my issue.
I've set up different provinces associated to a zone; then I've configured new delivery associated to this zone.
When I reach delivery method on checkout process I've always have the message "Unfortunately there's no carrier available for your address"

I've read here for some fixes about related issues but did not work for me.

[e.g: #9932](https://github.com/PrestaShop/PrestaShop/issues/9932)

Here some details of my PS installation:

**Prestashop 1.7.5.1**
**Template: Warehouse 4.2.1**

An appointment about this issue; when I check free delivery for my carrier, It shows on frontend with, obviously, free shipping.

**Comment by khouloudbelguith** [comment]
Hi @makritos,

If PrestaShop Carriers Are Not Available At Checkout, you need to check:

1. Carrier Is Inactive: PrestaShop carrier status is the first thing you should consider
Incorrect Zone Assign or Country Disabled: Zone association is among the first things to check if a created carrier does not show for a specific shopper. When configuring PrestaShop carrier you are supposed to assign it to zones, this very carrier can deliver parcels within. If a carrier is not assigned to the zone, customer address belongs to, then it will not show as a delivery method at the checkout.
2. Carrier Is Not Allowed for Customer Group: This detail might easily be skipped, since you can have hundreds and thousands of customers, belonging to various customer groups. If some customer belongs to the group that is not served by the current shipper, it will not be offered as a delivery method for this customer
3. Weight or Price Ranges Are Not Specified: Creating PrestaShop carrier you usually define billing cost for each by one of the criteria: order price or weight. Having selected a suitable method, you need to create ranges and set prices for them. In case ranges are not created, “The product selection cannot be delivered by the available carrier(s). Please amend your cart” message will display at shipping step for a customer.
4. Package Dimensions Are Out of Range: If all above listed settings are configured properly but still PrestaShop carrier does not display at the checkout, you have to compare package dimensions with maximum dimensions PrestaShop carrier can handle. If the package goes beyond these limits, the carrier can’t ship it and, respectively will not display as a delivery method.

Thanks to check & feedback.

**Comment by makritos** [comment]
Thanks for reply @khouloudbelguith. I've checked all your tips.

1. Carrier is active, zone is active and all provinces (all active) are assigned to this zone.
2. Carrier is allowed to all customer groups.
3. Ranges are specified based on total amount so weight are not significant.
4. Based on point 3, I'm not using package dimensions.

If you need more info about my config, please ask for it =)

**Comment by khouloudbelguith** [comment]
@makritos, you don't need to follow these steps to reproduce your issue as described in this issue
https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-467397790, is it?
If no, do you have any cart rule applied in the FO?
Thanks!

**Comment by makritos** [comment]
Hi again @khouloudbelguith you're right, I don't need to follow this steps. I haven't got any cart rule applied.

The weird of all of this is that when I set free delivery on my carrier it shows correctly on front but if switch again to not free, disappears and get the red of the death message.

**Comment by khouloudbelguith** [comment]
@makritos, Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by makritos** [comment]
I'm gathering all info and post here soon.

**Comment by khouloudbelguith** [comment]
Hi @makritos,

Thanks!
Waiting for your feedback.

**Comment by makritos** [comment]
Here is all info I've gather at this moment.

- Server info: Linux #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 / Apache Server
- PHP Version 7.0.30
- Prestashop 1.7.5.1
- SQL: 10.1.37-MariaDB-0+deb9u1
- Host: http://www.elitepublicidad.com/ (you can do some tests if you want)

Then show you some screen captures about backend configs:

Active zones. Zone Península is the new one.
![Captura de pantalla 2019-03-12 a las 13 50 47](https://user-images.githubusercontent.com/39998608/54202067-7dbd7c80-44cf-11e9-9ac4-76fe2e4bd9ed.png)

España config:
![Captura de pantalla 2019-03-12 a las 13 55 13](https://user-images.githubusercontent.com/39998608/54204355-60d77800-44d4-11e9-8489-9ab169aaad5c.png)

Provinces set to Zona Península:
![Captura de pantalla 2019-03-12 a las 14 40 12](https://user-images.githubusercontent.com/39998608/54204583-c9bef000-44d4-11e9-92e4-c8b7ff3e5833.png)

And carrier to Peninsula Zone:
![Captura de pantalla 2019-03-12 a las 13 56 15](https://user-images.githubusercontent.com/39998608/54204440-89f80880-44d4-11e9-9505-85bb95d88c0a.png)

On checkout process, this is an address test:
![Captura de pantalla 2019-03-12 a las 14 41 43](https://user-images.githubusercontent.com/39998608/54204704-0db1f500-44d5-11e9-8230-84a5c6b273c1.png)

And then...
![Captura de pantalla 2019-03-12 a las 14 42 49](https://user-images.githubusercontent.com/39998608/54204733-21f5f200-44d5-11e9-9af8-2d8f991e15ba.png)

**Comment by khouloudbelguith** [comment]
Hi @makritos,

In your second screenshot, the zone of Espana is Europe.
![image](https://user-images.githubusercontent.com/16067358/54205213-2bcc2500-44d6-11e9-9c3d-c200f201667f.png)
But, in the carrier page, Europe is not selected.
![image](https://user-images.githubusercontent.com/16067358/54205264-51592e80-44d6-11e9-834e-3766be05059c.png)
In the FO, you have an address with the country Espana
![image](https://user-images.githubusercontent.com/16067358/54205347-79489200-44d6-11e9-88d1-5ab108785bf5.png)
So, it is normal behavior to have this alert.
Thanks to change the zone of the Espana country to "Zona Peninsula", check & feedback.

**Comment by makritos** [comment]
Thanks for the reply @khouloudbelguith but still not working. One appointment about this; if I switch on free delivery for my carrier, delivery options appear...

**Comment by khouloudbelguith** [comment]
@makritos, We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by makritos** [comment]
There's nothing on error on PHP log, promise. I'm afraid...

**Comment by khouloudbelguith** [comment]
@makritos, could you please provide the credentials of your shop to check it.
This is a public space.
You can provide me the access by email.
My address mail: khouloud.belguith@prestashop.com
Let's be safe!

**Comment by khouloudbelguith** [comment]
@makritos, I just received the mail.
I tried to navigate to FO,
I have this 
![image](https://user-images.githubusercontent.com/16067358/54271453-d2b9cb00-4581-11e9-9c6d-60b03cf2a813.png)
Can I allow it manually?
Thanks!

**Comment by makritos** [comment]
Mmmm, sorry I’m going to change it now.

**Comment by makritos** [comment]
Check again =)

**Comment by khouloudbelguith** [comment]
@makritos, I found this problem.
This issue occurs due to the genei module.
![image](https://user-images.githubusercontent.com/16067358/54274027-6641ca80-4587-11e9-9de8-1b70c84b5202.png)
As it's not the default module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by makritos** [comment]
Wow! I really appreciated your help.

**Comment by khouloudbelguith** [comment]
@makritos, you are welcome!
Thanks!
