### ISSUE TITLE
Cannot Edit Products

### ISSUE THREAD

**Issue by MubarakIssop** [PrestaShop/PrestaShop#12909]
****************************
DO NOT disclose security issues here, contact security@prestashop.com instead!
****************************
-->

**Describe the bug**
Hi, I have been using my Prestashop back office for a few years since it has been passed on to me by the developer. I have not had any problems so far until today. Yesterday i did a bulk import of products and now i cannot edit products. Once i go into the product, the "Save" and "Save and stay" buttons just keep spinning and does not allow me to save any changes. Can anyone help with this? Please see screenshot which will show the problem i am having

**Screenshots**
![image](https://user-images.githubusercontent.com/48523555/54289834-c47ba700-45a1-11e9-9ce4-d32c1afbdcc7.png)

**Additionnal information**
PrestaShop version: 1.6.1.17
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @MubarakIssop,

There is already an issue for 1.6: http://forge.prestashop.com/browse/PSCSX-9042
It wasn't necessary to create a new one.
So, this one can be closed
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and and security fixes will be accepted in the `1.6.1.x` branch.
Thanks!

**Comment by MubarakIssop** [comment]
Hi,

The thread that you have provided in the last email does not actually contain any answers if this issue was every fixed or not and how it was fixed. Was it ever fixed? I feel like I chose a developer for my store that chose Prestashop and just handed it over to me. Prestashop has so many glitches and bugs I feel like he has made the worse decision going with Prestashop and worse part is that they expect us to pay for the support when their own systems fail

Thanks

Mubarak Issop

**Comment by khouloudbelguith** [comment]
@MubarakIssop, in fact, this issue http://forge.prestashop.com/browse/PSCSX-9042 is not fixed yet.
But, as I said the maintenance support for PrestaShop 1.6 ended in October 2018, which is now in extended maintenance mode until June 30, 2019.
During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs will be fixed.
Thanks for your understanding!

**Comment by MubarakIssop** [comment]
Sir,

This IS a critical bug! How am I supposed to add new products or edit any existing products on our website. I have a team that lists products for us and they not cannot do their work. My website is at a standstill, how is this not a critical issue??? The thread you provided a link to has comments from April 2018. You are telling me it has nearly been a year and there is no solution? So shall I just close my website down now which I have been working on for almost 2 years now????

You keep saying the maintenance support ended in October 2018 but now is in extended maintenance mode. That means the maintenance mode is still on until 30th June. It does not make a difference that it is in extended maintenance mode, there must be a reason you extended the maintenance mode

This never happened before, only 2 days ago, I needed to add references to my listings so decided it would be easier and faster if I export my inventory, add the references and then import them again, and since I have imported the list this problem has started. Surely there must be a fix to this??

I just cannot believe how much money we have already spent on this website and the time and now we are potentially looking at closing the website before we have even started

Thanks

Mubarak

**Comment by ttoine** [comment]
Hello, the short term solution in your case is to restore a backup from before your bulk import.

But I don't really understand: your website is still not in production, after 2 years of development?

**Comment by MubarakIssop** [comment]
Hi,

Unfortunately I forgot to back up before doing the import. In this case, is there no solution?

I mean the website is Live and in production, but we still have a lot of products to add on to it. We are constantly changing our inventory and have around 2000 more lines to add on but with this issue my staff are completely stuck with their work and cannot do anything, I have had to send them home

Thanks

Mubarak
