### ISSUE TITLE
Bloc paiement

### ISSUE THREAD

**Issue by andreepi** [PrestaShop/PrestaShop#12978]
Le bloc paiement ne fonctionne pas. Inactif.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/48160466/54686011-8984f080-4b18-11e9-8523-18c595e7262c.png)

**Additionnal information**
PrestaShop version: 1.6.1.18
PHP version: N/A

**Comment by andreepi** [comment]
Bonjour,

J'ai vu votre réponse mais je n'ai pas compris.

Le #12978 est-il toujours en cours car je n'ai pas eu de réponse ?
Merci

**Comment by khouloudbelguith** [comment]
Hi @andreepi,

PrestaShop has a debug mode, which can be used to see the non-obvious errors in your shop. For instance.
To turn on the Debug mode on PrestaShop, follow these steps using an FTP client (for instance the free Filezilla tool) to edit the config/defines.inc.php file. Find the following line in the file:

`define('PS_MODE_DEV', false);`

… and change it to:

`define('PS_MODE_DEV', true);`

Finally, emptying the cache of PrestaShop can also be useful, because it ensures that your browser only displays newly-generated files instead of old cached ones.
Thanks to check & feedback.

**Comment by andreepi** [comment]
Bonjour,

J'ai vidé le cache, je le fais régulièrement mais cela n'a rien changé

Quant à la procédure du mode débogage, c'est trop compliqué pour moi et
j'aurais peur de faire des erreurs.

Cordialement

*Se Soigner NatureA. Pierdon*



Le jeu. 21 mars 2019 à 09:14, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
@andreepi, just you need to edit the config/defines.inc.php file. Find the following line in the file:

define('PS_MODE_DEV', false);

… and change it to:

define('PS_MODE_DEV', true);

In the FO => checkout page, you need to check if there are some exceptions displayed.

Thanks!

**Comment by andreepi** [comment]
RE-

N'étant pas une spécialiste du langage informatique, j'ai refait la
procédure de désinstallation, j'ai vidé le cache, réinstallé le module.
Il refonctionne.

Merci

*Se Soigner NatureA. Pierdon*



Le jeu. 21 mars 2019 à 09:51, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
Hi @andreepi,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.
PS: As you can see [here](https://www.prestashop.com/en/blog/Maintenance-extension-PrestaShop-1-6) : the maintenance of PrestaShop 1.6 is extended to June 2018 for security and critical bugs.
Thanks!
