### ISSUE TITLE
Option so specific prices and catalog price rules can be cumulative! 

### ISSUE THREAD

**Issue by sector7digital** [PrestaShop/PrestaShop#12993]
Seriously, who wouldnt' want that!! I really need the catalog price rules to be cumulative to my specific prices. but I guess with PS 1.6.1.23 it's too late already anyway, very very bad that this isn't already implemented and makes no sense to me either

**Comment by khouloudbelguith** [comment]
Hi @oliiix,

Thanks for your report.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be accepted in the next PS1.6.

About your suggestion, it could be added in our Project for the PS1.7 only.
So, if you need this feature for the PS1.7, thanks to describe your feature & the solution you'd like.
Thanks!

**Comment by sector7digital** [comment]
Thanks for coming back and I'm very sorry that I wrote this so harsh!! guess I was a little tired and couldn't set it up as I wanted, but still, I'm sorry for this! Still maybe you'd like to implement it in 1.7. We might change the version at some point in time but we programmed so much other tools relying on the 1.6 database structure so I'm not yet sure when this will be. THANK YOU!

**Comment by khouloudbelguith** [comment]
Hi @oliiix,

Thanks for your feedback.
You are welcome.
I close the issue, feel free to open a new one when needed.
Thanks!
