### ISSUE TITLE
Déclinaisons ne s’affichent pas sur site e-commerce

### ISSUE THREAD

**Issue by HECOSFAIR** [PrestaShop/PrestaShop#13037]
Bonjour,
Les déclinaisons des produits ne s’affichent qu’en partie sur le site e-commerce alorsqu’elles s’affichent correctement dans le backoffice. 
En effet, les attributs sont affichés mais les valeurs et le prix ne s’affichent pas. 
Les clients ne peuvent ni sélectionner ni acheter les déclinaisons de ces produits. Ils peuvent uniquement acheter la déclinaison par défaut.
Cependant, ces déclinaisons s’exportent sans problème sur les marketplaces comme Amazon. C’est uniquement sur le site e-commerce qu’elles ne s’affichent pas, comme le verrez dans le lien et la capture d’écran ci-dessous : 

https://hecosfair.com/accueil/136-164-pignon-de-cedre-bio-de-siberie-3770010599241.html#/159-mini-70g

![185BE60F-5104-4B32-B369-63D1FFC87FFE](https://user-images.githubusercontent.com/48907418/54910261-3e8a2500-4eec-11e9-8c11-0a451c0d086f.jpeg)

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

Bien cordialement

**Comment by khouloudbelguith** [comment]
Hi @HECOSFAIR,

Could you please provide me a screenshot from your BO => Product page => Combinations Tab.
It could be that combinations are not correctly generated.
Thanks!

**Comment by HECOSFAIR** [comment]
Hi 
Thank you for you quick answer!
I provide you many screenshots from my BO.
I hope it’s helpfull.

Best regards








         BLAISE Herlyne 
        CEO d'HECOSFAIR
       +33 7 69 14 43 65
        www.hecosfair.com




         BLAISE Herlyne 
        CEO d'HECOSFAIR
       +33 7 69 14 43 65
        www.hecosfair.com

**Comment by khouloudbelguith** [comment]
@HECOSFAIR, there are no screenshots uploaded.
You need to login on GitHub & upload those images here.
Thanks!

**Comment by HECOSFAIR** [comment]
Ok! Thank you so much!
Vous trouverez les images ci-dessous.

![0E14148D-C677-4AB1-BE62-EA5092E7C623](https://user-images.githubusercontent.com/48907418/54929865-832ab600-4f16-11e9-8348-8d9289a015d9.jpeg)
![7C58573C-6A10-4F74-A7CA-91B4B931D9F5](https://user-images.githubusercontent.com/48907418/54929866-83c34c80-4f16-11e9-9bce-86142c42afaa.jpeg)
![0AA5A44B-37E9-4C54-B2DB-C47EC36F041C](https://user-images.githubusercontent.com/48907418/54929867-83c34c80-4f16-11e9-80aa-4ddddf6e0b20.jpeg)

**Comment by khouloudbelguith** [comment]
@HECOSFAIR, thanks for your feedback.
Your combinations are not correctly generated.
Then, in the right column, you should select all your combinations (from your 1 group and click on "Generate" => for example in this product, you have some combination like `Mini: 20g`, `Mini: 100g`, `Mini: 150g`,...
I have to close this ticket because, in the combination list, every combination needs to have the same attributes than the others. I mean You can't have, in the same product, combinations with Mini and some others with Maxi.
All of them need to have Mini + Maxi or Mini or Maxi.

First, you should delete all your combinations & re-cretae them.
Second, the solutioncould be like this: `Mini: 20g`, `Mini: 100g`, `Mini: 150g`,... for product A / Moyen: 200g`, `Moyen: 300g`, `Moyen: 350g`,... for product B

I close the ticket, feel free to open a new one when needed.
Thanks!
