### ISSUE TITLE
Unable to access certain tab of the back office

### ISSUE THREAD

**Issue by lyion92** [PrestaShop/PrestaShop#13062]
**Describe the bug**

**To Reproduce**
1. Go to 'back office'
2. Click on 'shop parameters -> general'
3. See error

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

I have tried install different version of 1.7 but same issue.

![image](https://user-images.githubusercontent.com/23446063/55051374-c9efeb80-508f-11e9-9fe0-25ed697f50e9.png)

![image](https://user-images.githubusercontent.com/23446063/55051341-a036c480-508f-11e9-849e-302653e025d1.png)

**Comment by khouloudbelguith** [comment]
Hi @lyion92,

Is there any other script on your site/app that does any session manipulation outside of symfony's control?

Thanks!

**Comment by lyion92** [comment]
No. This is fresh install

**Comment by khouloudbelguith** [comment]
Hi @lyion92,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
