### ISSUE TITLE
The Employee does not exist, or the password provided is incorrect.

### ISSUE THREAD

**Issue by bbdebo** [PrestaShop/PrestaShop#13231]
I have been using the same email and password to log on my prestashop back office. Since yesterday, It can’t not access the back office, I have the following error message : The Employee does not exist, or the password provided is incorrect.

However I have not changed the password, or anything else.
Also I have clicked on Reset password, but I have not received any email. Seems my account is not working at all. 
Can someone help urgently please ?
many thanks !!

**Comment by khouloudbelguith** [comment]
Hi @bbdebo,

What is the exact version of PS did you used?

Thanks!

**Comment by bbdebo** [comment]
I don't know unfortunately.

**Comment by bbdebo** [comment]
Cant you still help me please ? I am desperate :(

**Comment by matks** [comment]
Hi @bbdebo,

If you have modified nothing on your shop (no configuration changed, no file changed, no server update ...) this should not happen. You should check with your hosting provider if anything was changed on your server, this is probably the reason behind it. If your hosting provider did some changes on the server, he should be able to fix/revert them.

Please note that this github repository goal is to be a bug / feature request tracker, in order to fix your issue the best place is probably the forum 😉 https://prestashop.com/forums so I suggest you check with your hosting provider and if it does not solve the issue, open a topic on the forum.

Thank you for understanding

**Comment by khouloudbelguith** [comment]
Hi @bbdebo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
