### ISSUE TITLE
Name of uploaded image not displayed in browse fields

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13260]
**Describe the bug**
The name of the uploaded image is not displayed in browse fields

**To Reproduce**
1. Go to for example category edit page
2. Click on Browse for category cover 
3. Select an image
4. The name of the uploaded image isn't displayed

**Screenshots**
![capture d'écran_1332](https://user-images.githubusercontent.com/13449658/55863652-42b87280-5b7b-11e9-8c42-e8375bd5f32b.png)

![capture d'écran_1333](https://user-images.githubusercontent.com/13449658/55863705-5d8ae700-5b7b-11e9-91a2-70e02a7ff2d7.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by tomas862** [comment]
Hi @marionf ,

Not sure I fully understand the problem but:

1. If comparing previous PrestaShop version 1.7.5 , for instance if you try to upload any image on categories form and after that you go to edit page again the input will remain empty.

as in 1.7.5 the same behavior is applied in this version as well and I think almost every form in PrestaShop does not store uploaded file name on any edit page

2. If the file does not appear instantly when you upload any file. That is weird because when I try it works like a charm . I'm on branch 1.7.6.x and I have rebuilt assets with command `npm run build` to make sure I have everything up to date

**Comment by marionf** [comment]
Hey @tomas862 

Yes, it was about 2. but you are right, it's working !
Thanks for looking :)
