### ISSUE TITLE
Multiple Duplicated Cart in Back Office

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#13414]
**Describe the bug**

There is multiple cart entry for the same cart (exact value and near time stamp)
![DUPLICATECART](https://user-images.githubusercontent.com/24798703/56186566-10e25880-6020-11e9-95ce-340ba3d9c4b4.png)

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.2
PHP version: 7.0-fpm

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

Did you use the template by default of Prestashop?

Thanks!

**Comment by matteolavaggi** [comment]
Yes, original classic theme

**Comment by khouloudbelguith** [comment]
@matteolavaggi, could you please try with this PR: #9076.
Thanks for check and feedback.

**Comment by matteolavaggi** [comment]
Applied the change and it seems to work. I wonder why there isn't a simple patch release system due to the huge amount of bugs on prestashop features present in every new release! Making a release upgrade to fix operating bugs is complicated, often impossible as well as making little sense!
Compared to other platforms where mainly security bug fixes are released, prestashop has an infinite number of open operating bugs, which in itself is strange and synonymous with incompleteness in the design and release of a new release, but makes it practically impossible to have a stable bug-free version! For each new release (assuming that it is possible to update, which is practically impossible on stores in production without starting from scratch with modules, products and configurations), new bugs emerge on the functioning of fundamental components, which are partially solved in the new relase, which presents new! The functioning of a release should be practically assured at 99.99% with the exception of security patches that follow any potential vulnerabilities, so it is a jungle to maintain a functioning ecommerce ...

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

This solution has been migrated since version 1.7.4.x.
PrestaShop is an open source, community project. If you find that any issue is important for you, it is important to have it fixed ASAP, then you can invest in having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try it on your own. The most important thing is to share that by submitting a Pull Request - that's what the open source is all about.
I close the ticket, feel free to open a new one when needed.

Thanks!

**Comment by matteolavaggi** [comment]
No, bug still here. Fix is a fetch work around not a save workaround, so not work :
![image](https://user-images.githubusercontent.com/24798703/56298182-fe584400-6131-11e9-9439-8a84935c96a7.png)

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

In my case, I did not manage to reproduce the issue with PS1.7.5.1.
But this issue exists in PS1.7.2.4 => PS1.7.3.4.
You should edit your file in the core like this fix https://github.com/PrestaShop/PrestaShop/pull/9076/files
These PR fixes duplicate carts in the back office.
After applying this patch, when you try to add some product to the cart, in the BO, this shopping cart is duplicated?
Thanks!

**Comment by matks** [comment]
> Compared to other platforms where mainly security bug fixes are released, prestashop has an infinite number of open operating bugs

Hi, do you mean in comparison with [magento](https://github.com/magento/magento2) and their 1085 issues ? Or [cinnamon](https://github.com/linuxmint/cinnamon) with their 857 issues ? Also issues can be feature requests or bug reports, be wary of that.

Basically, since magento, prestashop, cinnamon are widely used systems, yes there is a very large number of bugs reported. The more users you have, the more bug reports you get. And there is so many that we alone cannot fix them all.

Please remember that PrestaShop is an open source, community project. If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

Also in order not to introduce more bugs, we now have an extended full month-long public beta period for new minor versions. With 1.7.5.0, we used this extra time to gather feedback and bug reports from contributors and partner agencies. This is the longest beta period we ever did, and we are going to do the same for 1.7.6.0. We think this helped a lot to stabilize and consolidate this new version.

We also added a lot of unit tests, integration tests, end-to-end tests (and still add more !) and the Pull Request merge process is now a lot tougher thant it was years ago with CI being run, code review, QA review, PM review, UX review, all of this to ensure all modifications to the codebase are for the best and do not introduce bugs (but we all know there will always be bugs, alas!). By the way that also make PRs longer to merge but we think it's worth it.

So everything is done in order to strengthen PrestaShop and make it more robust, more reliable, more bug-free. But this is a long, hard work which requires time, energy and dedication. It will take time to fix it all. Will you participate ?

**Comment by matteolavaggi** [comment]
Hi dear, maybe start thinking that there is some problem in the actual relase plan, patch system and update procedure, is the first step for a future BETTER prestashop, dont think?

ITs an inifinite discussion but there is some problem:

1) its not accettable that some CORE function has bug in a 1.7.5 release of an ecommerce! Function like the core cache handle, or the cart handle, or the default template with bug, missing variable, THE SEARCH THAT DOES NOT WORK ON PS 1.7.3 (search is LIFE for an ecommerce ?!?!) ! These cant be issue! These are function that must WORK on prestashop 1.7.1 and must be fixed in prestashop 1.7.1 before release prestashop 1.7.X! 
2) There isn't a system to apply security patch to prestashop, there isnt a system to apply patch at all. Try the magento connect patch system.. work since 1.9 ... 
3) There isn't a system to upgrade PS version in save way, and if you release FUNCTION bug fix in new release, and this can't be installed in simple way ... this result in impossibility to fix the bug!
4) New release many times has some the same important functionality bug than the old one ! So why apply for a new release and take bug from oldest one ?


So when you reply that prestashop is an open source project, we EVERY day invest on it buying module and paing money for (many times) having basicall function striped out from prestashop that other ecommerce has . So we JUST contribute to prestashop with our money, with our time, with our bug segnalation ecc.

When you write to hire a programmer to fix prestashop bug, i need to ask how this can be suitable for an end user. So we apply for a developer to fix PS 1.7.2 bug, and next we upgrade to prestashop 1.7.3 to have finally a store with a new complete set of function bug ?! so another time we hire a developer to fix 1.7.3 bug , after 6 month we install a 1.7.4 with new bug? and so on?
Also 90% if the module you can buy on PS addons is not upgrade proof ^^ how we can maintain a stable release in this way? its IMPOSSIBLE!
The best an end user can do is to invest many and many dollar to fix their PS version, and NOT upgrade anymore, resulting in a unsafe diffusion of old ps intallation (found today many post of customer that not wont to upgrade from ps 1.6 to .17 due to bug problem ...).

i think there is lot of work to do on PS releasing / patching project and planning for the future.

In conclusion i'm partecipating dear, i dont know your time spent every day on PS, but i'll pay not less than 250$ every month in the last 2 years, + many our to fight against bug ^^ so i'm doing my parts , i'm the final user, not the developer team.

Invest more to create an upgrade proof / patch release system, and create some module compliance test / requirement to apply for upgrade program.

I give you 2K$ if you show me how to upgrade a 1.7.2 PS to a stable 17.5 version with 1 click upgrade .. or also by manual upgrade , there is no way. Maybe is possible with a fresh clean installed 1.7.1 ps, but there is no way in a production server with module installed and workaround bug fix ecc.

**Comment by matteolavaggi** [comment]
> Hi @matteolavaggi,
> 
> In my case, I did not manage to reproduce the issue with PS1.7.5.1.
> But this issue exists in PS1.7.2.4 => PS1.7.3.4.
> You should edit your file in the core like this fix https://github.com/PrestaShop/PrestaShop/pull/9076/files
> These PR fixes duplicate carts in the back office.
> After applying this patch, when you try to add some product to the cart, in the BO, this shopping cart is duplicated?
> Thanks!

I've apply for this fix, is a write fix or a read fix? it correct the way how BO access the data or the way how data is saved so i know if need to expect old cart duplicate disappear or take it in test for new cart.
Thanks

**Comment by khouloudbelguith** [comment]
@matteolavaggi, this fix will be applied on new carts.
Thanks!
