### ISSUE TITLE
Can't access to BO because of psaddonsconnect when addons.prestashop.com is down

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13438]
**Describe the bug**
Can't access to BO because of psaddonsconnect when addons.prestashop.com is down
Module version 1.0.1

**Screenshots**

1.7.6.0

![capture d'écran_1407](https://user-images.githubusercontent.com/13449658/56221521-b15d6a80-606a-11e9-95ed-5362b7546702.png)

1.7.5.1

![capture d'écran_1408](https://user-images.githubusercontent.com/13449658/56221560-bd492c80-606a-11e9-9846-4bb3ef2a8ded.png)

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

**Comment by marionf** [comment]
FYI @MatShir & @samuel-pires

**Comment by matks** [comment]
It's api-addons.prestashop.com that is the culprit here 😉

**Comment by matks** [comment]
We have this error message in DEV environment only because of one of my PRs: https://github.com/PrestaShop/PrestaShop/pull/12959/. Previous behavior (and this is what still happens in PROD environment) would just skip when one resouce could not be downloaded, no matter what would happen in the code later because of this failed download.

Now we get a beautiful error that crashes immediately 😁 so we are aware of the issue.

**Comment by Quetzacoalt91** [comment]
So, are we required to do anything?
Should the module display an error message instead?

**Comment by MatShir** [comment]
We are currently working on quick specs with the stakeholders of the module. Modules Team will implement the circuit breaker on it.

**Comment by Quetzacoalt91** [comment]
Circuit breaker has been implemented in the module. We may close this issue.
