### ISSUE TITLE
PrestaShopException when we add DNI option

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#13487]
**Describe the bug**
When the DNI option is activated there is an error in front office when you try to add an address. In 1.7.5.1 there is no error.

**To Reproduce**
1. Go to International -> Zone 
2. Create a country with DNI required 
3. Go to front add a product to the cart and start the order process 
4. When you add the adresse and validate see error

**Screenshots**
![Capture d’écran 2019-04-19 à 10 54 56](https://user-images.githubusercontent.com/3034677/56416625-b7816000-6291-11e9-851c-52e1d92f0442.png)

**Additionnal information**
PrestaShop version: 1.7.6.X
PHP version: N/A

**Comment by jolelievre** [comment]
Hello, this is probably linked to this fix https://github.com/PrestaShop/PrestaShop/pull/11726 and issue https://github.com/PrestaShop/PrestaShop/issues/9891
I'll look into it

**Comment by jolelievre** [comment]
Hello @sarahdib I can't reproduce this exception,
we probably didn't set the country address the same way

What I did is, in "International > Locations   Countries > Italia"
- add `dni` field in address format
- enable `Do you need a tax identification number?` for this country

The result is that a new field is added in the address form, when `tax identification number?` is enabled you can't submit the form because it is validated front side. When `tax identification number?` is disabled the for is correctly submitted.

**Comment by marionf** [comment]
@jolelievre 

It happens when you enable "Do you need a tax identification number?" without adding dni field in address format

**Comment by marionf** [comment]
Maybe we could automatically add dni field in address format when "Do you need a tax identification number?" is enabled to avoid this issue ?

**Comment by jolelievre** [comment]
@marionf yep that's what I thought as well, seems to be the safest way
Done in this PR https://github.com/PrestaShop/PrestaShop/pull/13578
