### ISSUE TITLE
It is possible to order product transformed from regular into product with combinations

### ISSUE THREAD

**Issue by tvorgul** [PrestaShop/PrestaShop#13497]
It is possible to order perviously created simple product after its transformation to a product with combinations. (so, the simple product should be unavailable for order)

Here is an exemple:

- create a simple product
- add it to cart
- modify product and switch to product with combinations mode, save
- go to your cart and buy the product.

This product is not available in the shop anymore but it is still available in **previously created shopping carts.** 
**The main problem** is not old shoppings cards but the **"order again" button** in user account. It is also possible to order simple product instead of the product with combination.

_Additional info_ : if I increase the quantity of the simple product (that should be normally unavailable) it will add the second line with product with default combination.

PrestaShop : 1.7.4.2

**Comment by khouloudbelguith** [comment]
Hi @tvorgul,

Thanks for your report.
I manage to reproduce the issue with PS1.7.4.4 & PS1.7.5.1.
I attached a video record.
https://drive.google.com/file/d/1sphRg2_rTI-QMc5XtnWsv6h9NiixRYh7/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Related to #11631
Thanks!

**Comment by tvorgul** [comment]
Hello,

Thank you for your quick response.
I'll been waiting for update!

Thank you !

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.beta1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14489
