### ISSUE TITLE
Upload a Module - Cannot Exit - Version 1.7.5.1

### ISSUE THREAD

**Issue by bestbuybargains** [PrestaShop/PrestaShop#13592]
The Upload a Module box will not close once opened.  You have to refresh the page to get it to close.

1. Go to Module > Module Catalog > Upload a Module
2. Click on the X to attempt to close the box
3. See error

![image](https://user-images.githubusercontent.com/50038176/56844541-61a34e00-6877-11e9-8b0a-3ce91f12743b.png)

PrestaShop version: 1.7.5.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @bestbuybargains,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record
https://drive.google.com/file/d/17gnil1cY-Ii930hUAr596W1bHRfw2bdx/view
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Thanks!

**Comment by khouloudbelguith** [comment]
@bestbuybargains, I checked your shop, it is fixed.
Feel free to open a new one when needed.
Thanks!
