### ISSUE TITLE
Syntax error in HTML Email (error with "3D")

### ISSUE THREAD

**Issue by 4itsoft** [PrestaShop/PrestaShop#13641]
**Describe the bug**
All transactional emails in HTML format contain the same syntax error. 
Instead of "=", "=3D" is displayed

![image](https://user-images.githubusercontent.com/50216024/57099481-31e7c080-6d25-11e9-9eec-2b16fd759d45.png)

**To Reproduce**
Send any transactional email and check the source code.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @4itsoft,

Thanks for your report.
I manage to reproduce the issue with PS1751 & PS1752.
![image](https://user-images.githubusercontent.com/16067358/57128494-ddc7f500-6d93-11e9-9298-1a9fcc0622ca.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
@4itsoft, did you closed the issue?
Thanks!
