### ISSUE TITLE
Discount cart rules invalid total_discount_tax_excl (the value is with tax included)

### ISSUE THREAD

**Issue by sanctusmob** [PrestaShop/PrestaShop#13689]
I create a cart rule "1 plus 1" in some brand apply a discount 100% to the cheapest product.
When the order is place the field in DB total_discount_tax_excl have the discount with tax.
ex.
total_discounts --> 39.990000
total_discount_tax_incl --> 39.990000
total_discount_tax_excl --> 39.990000

it should be like this (the product have 24% tax)
total_discounts --> 39.990000
total_discount_tax_incl --> 39.990000
total_discount_tax_excl --> 32.250000

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @sanctusmob,

Thanks for your report.
I manage to reproduce the issue with the last version PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/57304196-cd3ab600-70d6-11e9-83ec-1ac2920d5c5b.png)
In the database, ps_orders table the total_discount_tax_excl is incorrect
![image](https://user-images.githubusercontent.com/16067358/57304286-f3f8ec80-70d6-11e9-8ebf-0f05b16b86eb.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Prestaworks** [comment]
This issue is still present in 1.7.6.2
However, it has been fixed on the development version, I just noticed when I tried to do a pull request myself.

https://github.com/PrestaShop/PrestaShop/commit/c4167c566b92d0a7480810d40378b41136949452#diff-bfb3a7df5a16cd6e301d95412ace4715

It was fixed in may? how come we still have this issue in the "stable" release? come on, that the data is stored with bad values in the DB for orders are serious! it should have been merged long ago!

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Yes, you are right.
This issue is fixed in the develop branch.
![image](https://user-images.githubusercontent.com/16067358/71010103-a4a68000-20eb-11ea-9afd-c96087af5bdb.png)
It is fixed in the next release ps1.7.7.
I will close the issue.

Thanks!
