### ISSUE TITLE
Avoid overrides in Prestashop 1.7

### ISSUE THREAD

**Issue by CoralieNouletteAlbalogic** [PrestaShop/PrestaShop#13681]
Hi Prestashop Developers,

My issue is not really a bug a important question about overrides. I know the documentation advice us not to use them anymore. But I need to migrate a important module in PS 1.6 to 1.7 and I would like to get rid of overrides. When I have to install or upgrade the module, it takes a lot of time and generates errors.

My question is : is it possible to extends code classes and controllers to modify their methods without overrides ?

For example, I override Product classe to add 3 fields I want to be able and callable by the object. I override ProductController to display additionnal external informations. And so on.
Here is a short list of my overrides  : 
- Cart->getProducts (add custom field in the query)
- Cart->getTotalWeight (multiply weight by a custom field)
- PaymentModule->validateOrder (add additionnal price, a deposit, to product )
- AdminProductController->__construct (add custom field in form)
- ProductControler->initContente (additionnal product information)

Actually, I override 14 classes and 5 controllers. Why so much ? Because my module needs new fields, new controls, etc. We thought Symfony and namespaces bring us the opportinity to delete most of our overrides. We just want to be sure we can or not. 

In any way, thanks a lot for the time you will grant to this question. 

Have a good day.

**Comment by matks** [comment]
Hi @CoralieNouletteAlbalogic, thanks for reaching us with this very interesting question !

Indeed we want to deprecate the use overrides that are known to introduce several issues. I think you already encountered some of them: 2 modules overriding the same class, incompatible behaviors when upgrading the shop...

In the BO pages migrated to Symfony, we provide 2 replacement mechanisms to avoid overrides:
- More hooks, intended to handle fields and controls
This is already implement for incoming 1.7.6 version and the documentation is being written, with module examples provided.
- Symfony service definition override
When there is no hook you can use to modify the behavior of PrestaShop, we recommend using Symfony service definitions override or decoration (see https://symfony.com/doc/3.4/service_container/service_decoration.html)
You can see it as a better override mechanism because it does not replace the php definition but instead the usage PrestaShop makes of it. Again, documentation is being written so it's not yet available but here's a quick example:

Let's say you want to modify the behavior of migrated listing page "Customers" and the available hooks do not allow you to do so. For example you want to modify how the SQL filtering is being done on this page.

The standard SQL search for this page is being performed by class [CustomerQueryBuilder](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/Query/CustomerQueryBuilder.php). Instead of overriding the php class, you decorate its service definition [prestashop.core.grid.query_builder.customer](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml#L63) by creating your own definition `coralie.noulette.albalogic.query_builder.customer` and use this one instead.

Benefits:
- service `prestashop.core.grid.query_builder.customer` stays available if other services need it
- php class CustomerQueryBuilder stays available if other classes required/extend it
- you can choose, for any Symfony service using `prestashop.core.grid.query_builder.customer` whether it uses your decorated replacement or the original one
- you can even enable or disable the decorator at runtime ! something you cannot do with standard override

However this is only possible for migrated pages so far. For legacy pages, you still need to use overrides. Moreover in order to preserve as much as possible compatibility with existing modules, migrated pages still rely on ObjectModel. This means that you still need overrides to add SQL fields to a standard PrestaShop database object. 🤔 (I guess this is the easiest way, but better confirm @jolelievre @mickaelandrieu ?)

If you create a new database object, we recommend you use Doctrine to handle it (this is now possible for modules from 1.7.6). You will benefit from all features of Doctrine this way.

**Comment by Bonobomagno** [comment]
What about namespacing?
I think that the most important feature is to add module namespacing support before reading the overrided files.

**Comment by matks** [comment]
> What about namespacing?
> I think that the most important feature is to add module namespacing support before reading the overrided files.

Hi, indeed being able to use namespace inside Modules would be a nice feature however I'm not sure it's related to this conversation, is it ? 😅 

We discussed it before 😉 (see https://github.com/PrestaShop/PrestaShop/issues/11596#issuecomment-451965698) for 1.7, and because we cannot modify it without introducing breaking changes:
- the main module file (the one that extends `Module`) must be in the global namespace (so you cannot use it)
- any other php class used by the module can be namespaced using composer, it already works

For next major version, where we can break things, it would be nice to be able to namespace 100% of the module files, including the main one

We should create a dedicated issue for it if you want to discuss it further 😉

**Comment by Bonobomagno** [comment]
It already works on 1.7.6 
You cant use namespace on the module main file if you don't require the autoloader. 
For my custom use I extended context with the symfony kernel + module auto loader. This mean that I can use module namespaces from the overload files. 

Not totally related, but name space is first step. 
Unified servise container is next one

**Comment by jolelievre** [comment]
Hi @Bonobomagno,

as @matks said we can indeed use namespaces in modules for any class that is not the module class..
This was already possible for a while provided that you correctly included the module autoload.
However:
* since **1.7.4** autoload files are automatically loaded by the `AppKernel` so namespaces are automatically working in Symfony context (meaning migrated pages)
* since **1.7.6** autoload files are automatically loaded by `PrestaShop\PrestaShop\Adapter\ContainerBuilder` so now namespaces are usable in legacy contexts, both in admin **and** front which is a must have to use Doctrine entities even on front 😉

**WARNING** if you you include your own dependencies in a module they could conflict with the ones from the core, for that reason it is important that the modules dependencies are **not** prepended meaning they won't override the core ones you can define this behavior in your module's `composer.json` file:

```json
"config": {
    "prepend-autoloader": false
  },
```

Again sorry the doc is not ready yet for these new features (we are focusing on finishing the beta right now). But I will write the doc about the doctrine entities as well as the new features from the ContainerBuilder in legacy environments which now allow to define services accessible via this "light" container. This feature is already used in the core to access the CLDR service, and the coming module `productcomments` also uses it to access entity repositories in front controller.

(If you are curious feel free to read the code at https://github.com/PrestaShop/productcomments)

**Comment by Bonobomagno** [comment]
yes, for now i just load AppKernel singleton before loading frontcontroller

**Comment by jolelievre** [comment]
I wouldn't recommend it because it instanciates the whole Symfony stack (most of the time uselessly) which can be bad for performances

**Comment by matks** [comment]
It seems we have answered all questions here 😉if not, please open a new issue

**Comment by abdullacm** [comment]
> * More hooks, intended to handle fields and controls
>   This is already implement for incoming 1.7.6 version and the documentation is being written, with module examples provided.

@matks 
is this available in 1.7.8+ versions? I had added some custom fields to Product.php by overriding, but I would like to remove override and make it using any hooks or other ways if available. With override, sometimes the overrides are not working and have to remove/rename var/cache/<prod/dev>/class_index.php

what do you recommend?

thanks,
