### ISSUE TITLE
stock_available cleanup for non-existing products

### ISSUE THREAD

**Issue by LucaMozzo** [PrestaShop/PrestaShop#13682]
**Is your feature request related to a problem? Please describe.**
Yes. I was writing a program that was doing some mapping `product -> stock_available`, and I noticed that there were `stock_available` entries for non-existing products

**Describe the solution you'd like**
I believe it could make sense to have a `NOT NULL` constraint on the database field, and an update statement like `ON CASCADE DELETE`, unless it's not there for a reason

**Describe alternatives you've considered**
If there is a reason why it's not possible to do that, I'd like to have a confirmation around my own way of doing cleanup (so I can write a blog post about this and share with others).

The easy way of deleting what is not needed is:
```
DELETE FROM ps_stock_available WHERE id_product NOT IN (SELECT id_product FROM ps_product)
```
However I noticed that there are products *without combinations* that have two `stock_available` entries (they look the same except one has the `id_product_attribute` field set to `0`). Am I right saying that the entry with the aforementioned field set to 0 is redundant and can be deleted as well as part of my query above (from what I've seen it doesn't look like I am)?

Thanks

**Comment by khouloudbelguith** [comment]
ping @PrestaShop/prestashop-core-developers what do you think?
Thanks!

**Comment by colinegin** [comment]
Ping @PrestaShop/prestashop-core-developers what do you think ?

Thanks !

**Comment by matks** [comment]
Ping @zuk3975 and @jolelievre I think the current SQL structure of stock_available is not stable enough so we can alter it?

**Comment by zuk3975** [comment]
from a quick glance it might seem like something wrong happened and stock_available wasn't deleted? (so some kind of bug, or maybe product wasn't deleted using object model?).
Because as you can see here https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L1195
Product::delete() should take care of deleting every entry in stock_available with specified product id.

**Comment by matks** [comment]
Thank you @zuk3975 

@LucaMozzo it seems the `stock_available` entries for non-existing products are a mistake

> If there is a reason why it's not possible to do that

If I am correct, ON DELETE CASCADE  works only with tables with the storage engines that support foreign keys so that is InnoDB. Today we support both MyISAM and InnoDB although we are considering to drop MyISAM which would unlock this capability.

But for now, since we support both MyISAM and InnoDB we cannot rely, in the Core, on ON DELETE CASCADE. On your shop, if you use InnoDb, you can use it 😉
