### ISSUE TITLE
Can't delete dni from input Address format for country Spain

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#13691]
**Describe the bug**
Dni value is always present in input `Address format` for country Spain

**To Reproduce**
1. Go to 'International -> Locations ' SubMenu
2. Click on 'Countries' SubTab
3. Search for Spain
4. Click on 'Edit'
![Address fromat 1](https://user-images.githubusercontent.com/48441421/57282726-eaa75a00-70ad-11e9-809f-eb816576cc8a.png)
5. Edit Address format Value : let only 'phone' and delete 'dni'
![Address format 2](https://user-images.githubusercontent.com/48441421/57282797-13c7ea80-70ae-11e9-8f5b-e15a5641d6d6.png)
6. Click on 'Save'
7. Search for Spain
8. Click on 'Edit'
9. Address format Value = 'Phone dni' 
![Address format 3](https://user-images.githubusercontent.com/48441421/57282864-365a0380-70ae-11e9-9bb5-c3f2ee8e73d6.png)

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7.2

**Comment by mbadrani** [comment]
@khouloudbelguith wdyt?

**Comment by khouloudbelguith** [comment]
Hi @boubkerbribri, @mbadrani,

This is normal behavior, because `Do you need a tax identification number?` is enabled for Spain.
If you disable this option, you delete the dni from the address format & when you try to edit it, it will not be displayed.
![image](https://user-images.githubusercontent.com/16067358/57284765-baf65300-70a9-11e9-960b-e54c46f8b259.png)

PR for the fix: https://github.com/PrestaShop/PrestaShop/pull/11726

**Comment by boubkerbribri** [comment]
OK, thank you.
Test E2E updated #13686 commit [#25b4d75](https://github.com/PrestaShop/PrestaShop/pull/13686/commits/25b4d75893c8c92437a7e4f0283a109e1e074c0b).
