### ISSUE TITLE
ERROR 500 + NEED TO RESET COOKIE after shipping discount applied on cart

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#13715]
**Describe the bug**
Create a cart, apply a code discount for shipping, get error 500 and need to reset browser cookie (every page get error 500).

**To Reproduce**

May  8 16:25:23 vw03 ool www: PHP Fatal error:  Uncaught Error: Access to undeclared static property: CartCore::$_total_shipping in /mnt/datadisk/htdocs/prestashop/classes/Cart.php:3203#012Stack trace:#012#0 /mnt/datadisk/htdocs/prestashop/classes/CartRule.php(1010): CartCore->getCarrierCost(37, true, Object(Country))#012#1 /mnt/datadisk/htdocs/prestashop/classes/Cart.php(473): CartRuleCore->getContextualValue(true, Object(Context), 1)#012#2 /mnt/datadisk/htdocs/prestashop/classes/Cart.php(2054): CartCore->getCartRules(1)#012#3 /mnt/datadisk/htdocs/prestashop/classes/Cart.php(1937): CartCore->getTotalCalculationCartRules(3, true)#012#4 /mnt/datadisk/htdocs/prestashop/src/Adapter/Cart/CartPresenter.php(295): CartCore->getOrderTotal(false)#012#5 /mnt/datadisk/htdocs/prestashop/controllers/front/OrderController.php(204): PrestaShop\PrestaShop\Adapter\Cart\CartPresenter->present(Object(Cart))#012#6 /mnt/datadisk/htdocs/prestashop/classes/controller/Controller.php(205): OrderControllerCore->initContent()#012#7 /mnt/datadisk/htdocs/prestashop/override/classes/Dispatcher.php(387): Controll in /mnt/datadisk/htdocs/prestashop/classes/Cart.php on line 3203

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.2
PHP version: 7

**Comment by khouloudbelguith** [comment]
Hi @matteolavaggi,

You have an override of the Dispatcher.php class which is incompatible, you should check this override provided by which module?
Thanks!

**Comment by matteolavaggi** [comment]
Hi, thanks how we can check? can you help me to debug? thanks

**Comment by khouloudbelguith** [comment]
@matteolavaggi, in your log you have this

`PrestaShop\PrestaShop\Adapter\Cart\CartPresenter->present(Object(Cart))#12#6 /mnt/datadisk/htdocs/prestashop/classes/controller/Controller.php(205): OrderControllerCore->initContent()#12#7 /mnt/datadisk/htdocs/prestashop/override/classes/Dispatcher.php(387): Controll in /mnt/datadisk/htdocs/prestashop/classes/Cart.php on line 3203`

You have an error on line 387 on the override of the Dispatcher.php
Your issue is not a PrestaShop's core bug but a customization problem.
Thanks!
