### ISSUE TITLE
New design for searchbar in FO

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#13732]
UI/UX Improvement:
New design for the search bar in Front-Office.

Design: https://projects.invisionapp.com/d/main#/projects/prototypes/16658372

**Comment by ghost** [comment]
~~#13058~~
~~[#11](https://github.com/PrestaShop/ps_searchbar/pull/11)  in ps_searchbar~~
[#12](https://github.com/PrestaShop/ps_searchbar/pull/12)  in ps_searchbar

**Comment by jolelievre** [comment]
Hello @samuel-pires 

I looked at the PR for this issue, but I don't think this should be fixed in the core, rather in the module itself. This would allow to add additional classes to have a more proper CSS (which should be in the module as well).
Besides the new design includes product's thumbnails, this won't be manageable unless the module's javascript is updated.

What do you think?

**Comment by ghost** [comment]
Hi @jolelievre & @YeLnatSs,

I don't know what had been originally decided on this topic, but according to what you say @jolelievre, it totally makes sense to fix it in the module.

@YeLnatSs, can you fix it in the module instead?

**Comment by ghost** [comment]
PR has been created in the module repo : [#11](https://github.com/PrestaShop/ps_searchbar/pull/11)

**Comment by Progi1984** [comment]
Fixed in PrestaShop/ps_searchbar#12

**Comment by atomiix** [comment]
I'm thinking that we probably need to delete the `<prestashop>/themes/classic/modules/ps_searchbar` folder and its content.

Wdyt @jolelievre?
