### ISSUE TITLE
Can't display product.unity from cart.tpl (or included tpl)

### ISSUE THREAD

**Issue by vincent-dp** [PrestaShop/PrestaShop#13743]
If if put

`{$product.unity}`

in the cart-detailed-product-line.tpl for example, it displays nothing at all

Is this a bug or a normal behavior? How can I have access to this variable from these pages?

**Comment by khouloudbelguith** [comment]
Hi @vincent-dp,

What is the exact option in the product page from the BO, you want to display it in the cart page?
Thanks!

**Comment by vincent-dp** [comment]
There's an input right beside the "tax excluded" input in the "prices" tab
that one contain the condisioning unity of the product (for exemple, I have 2.5 Liter in a bottle of coka cola, this input contains 2.5 and can get display on product.tpl using {$product.unity})

**Comment by khouloudbelguith** [comment]
@vincent-dp, in fact, this variable `unity` is not defined in the `Project_PrestaShop/src/Adapter/Presenter/Cart/CartPresenter.php`
That's why in the cart-detailed-product-line.tpl, you cannot use {$product.unity}
In fact, this one is defined in the 
`Project_PrestaShop/src/Adapter/Presenter/Product/ProductLazyArray.php `
in the Product page, we can display it, you can check the block `product_unit_price` in the file `/Project_Folder/themes/your_theme/templates/catalog/_partials/product-prices.tpl`
Thanks!

**Comment by vincent-dp** [comment]
Ok, So I understand now it's normal and it's not a bug. But how can I override CartPresenter.php so it get unit defined?
Thank you for your help

**Comment by khouloudbelguith** [comment]
@vincent-dp,

Please be aware that this bug tracker should be used to report issues only. If you need help, you can ask on the Forum (https://www.prestashop.com/forums/), Gitter (https://gitter.im/PrestaShop/General) or Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop).
Thanks for your understanding!
