### ISSUE TITLE
Product features fields not updating for all languages

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#13751]
#### Describe the bug
With the 1.7.5.2 the only way I found this possible is to manually change the languages and imput all data again. This is very time consuming. 

#### Expected behavior
In 1.6 there was an option to update or delete ( by filling in nothing ) the text contant to ALL languages in the custom fields in the product features. Also when entering something in the custom field and saving the first time, this text was saved over all languages. 

#### Steps to Reproduce

1. BO > SELL > Catalog > Product 
2. Edit a product
3. add a feature in the product page with a customized value
4. this value is saved only in the language by default
5. FO > change the language
6. See error => the feature is displayed with empty value

**Screenshots**

### English selected
![image](https://user-images.githubusercontent.com/23308427/134773572-6d4ac625-cd6c-4b7d-9e31-de291c9efae2.png)

### Another language selected
![image](https://user-images.githubusercontent.com/23308427/134773591-3e5220af-3481-47af-89b8-d9bce724f93c.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @01park,

Yes, you are right, if I add a feature in the product page from the BO with a customized value => this value is saved only in the language by default
In the FO, if we change the language => the feature is displayed with empty value => incorrect
English selected
![image](https://user-images.githubusercontent.com/16067358/57536818-e47add00-733c-11e9-843a-6d8201b34d32.png)

Another language selected
![image](https://user-images.githubusercontent.com/16067358/57536850-fb213400-733c-11e9-9842-0e1abcc2b13b.png)

Same issue with PS1.7.5.1 & PS1.7.6.0beta1build1
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by 01park** [comment]
Hi,

Sorry, I won't be able to help you with a fix.

**Comment by MatShir** [comment]
It seems to be fixed on 8.1 new product page :)

**Comment by florine2623** [comment]
It is indeed fixed with the new product page :
<img width="495" alt="Screenshot 2023-07-05 at 14 08 34" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7d174e8d-4d36-4664-9b40-e82ceb7e4361">
<img width="499" alt="Screenshot 2023-07-05 at 14 08 41" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0b3d1dd7-b798-4259-b8d0-ea777adeee25">

I'm closing the issue.

**Comment by omidamini** [comment]
here is my solution for this problem that works perfectly fine :) . 

class AdminProductsController extends AdminProductsControllerCore
{
    public function processFeatures($id_product = null)
    {
        if (!Feature::isFeatureActive()) {
            return;
        }

        $id_product = (int) $id_product ? $id_product : (int) Tools::getValue('id_product');

        if (Validate::isLoadedObject($product = new Product($id_product))) {
            // delete all objects
            $product->deleteFeatures();

            // add new objects
            $languages = Language::getLanguages(false);
            $form = Tools::getValue('form', false);
            if (false !== $form) {
                $features = isset($form['step1']['features']) ? $form['step1']['features'] : [];
                if (is_array($features)) {
                    foreach ($features as $feature) {
                        if (!empty($feature['value'])) {
                            $product->addFeaturesToDB($feature['feature'], $feature['value']);
                        } 
                        else
                        {
                            $defaultValue = isset($feature['custom_value'][array_key_first($feature['custom_value'])])?$feature['custom_value'][array_key_first($feature['custom_value'])]:'';
                            $idValue = $product->addFeaturesToDB($feature['feature'], 0, 1);
                            foreach ($languages as $language) {
                                $valueToAdd = (isset($feature['custom_value'][$language['id_lang']]))
                                    ? $feature['custom_value'][$language['id_lang']]
                                    : $defaultValue;

                                $product->addFeaturesCustomToDB($idValue, (int) $language['id_lang'], $valueToAdd);
                            }
                            
                        }
                    }
                }
            }
        } else {
            $this->errors[] = $this->trans('A product must be created before adding features.', [], 'Admin.Catalog.Notification');
        }
    }
}
