### ISSUE TITLE
Smarty error when purchasing customizable products via Cash on Delivery module

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#13794]
Hi

The problem may be reproduced in Prestashop 1.7.5.1 and 1.7.5.2.  The steps to reproduce the issue have been outlined below.

1. Enable debug mode in Prestashop
2. Install and enable the Prestashop native module "Cash On Delivery"
3. On the store front, add a customizable product, such as the customizable mug to the basket
4.  Proceed through checkout and place an order using the Cash on Delivery payment method
5.  The attached error is produced.

Kind Regards
Musaffar
![screenshot](https://user-images.githubusercontent.com/44204668/57770751-ec55cb00-7708-11e9-9b0a-0ca1998d1809.jpg)

**Comment by khouloudbelguith** [comment]
Hi @musaffar-patel,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 / PS1.7.6.0beta1 & the ps_cashondelivery module v1.0.6.
![image](https://user-images.githubusercontent.com/16067358/57771499-c7faee00-770a-11e9-9f8d-780b7be67471.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

I didn't manage to reproduce the issue with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1uxVebmH8ylovl_Y-eWUDUeJu66XY1JRj/view

So, I close this issue cause it's fixed.

Thanks!
