### ISSUE TITLE
Bug in order confirmation - Error fatal in  line 1109

### ISSUE THREAD

**Issue by masztal18** [PrestaShop/PrestaShop#13909]
Hello,

Please help me. My old clients with Prestashop 1.6 (migration via module Migration Pro 1.6 > 1.7.5.1) have below error when click on "confirmation order". The same problem is in all peyment methods.

**Describe the bug**
[PrestaShopException]
Error critical
at line 1109 in file classes/Tools.php

1104.                 ->getTranslator()
1105.                 ->trans('Fatal error', [], 'Admin.Notifications.Error');
1106.         }
1107. 
1108.         if (_PS_MODE_DEV_) {
1109.             throw new PrestaShopException($errorMessage);
1110.         }
1111. 
1112.         return $errorMessage;
1113.     }
1114. 
ToolsCore::displayError - [line 254 - classes/PaymentModule.php]
PaymentModuleCore->validateOrder - [line 57 - modules/ps_cashondelivery/controllers/front/validation.php] - [9 Arguments]
Ps_CashondeliveryValidationModuleFrontController->postProcess - [line 270 - classes/controller/Controller.php]
ControllerCore->run - [line 511 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

**To Reproduce**
1. Add product to cart.
2. I choose peyment method and delivery.
3. I click on button "confirmation order".
4. I see error. 

**Screenshots**

![image](https://user-images.githubusercontent.com/19363321/58157586-eb78e800-7c78-11e9-86e2-b63c197083cf.png)

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @masztal18,

After the upgrade did you uninstalled the old module `cashondelivery` (module for PS1.6) & installed the new module for PS1.7 `ps_cashondelivery`?

Thanks!

**Comment by masztal18** [comment]
Yes, I reinstalled the caschondelivery module. It still does not work. If I choose a different payment method, I get an below error with bankwire module:

![image](https://user-images.githubusercontent.com/19363321/58158700-38f65480-7c7b-11e9-8ce7-da5121d6b9f9.png)

Thank you for help.

**Comment by masztal18** [comment]
It is fresh instalation Prestashop 1.7.5.1 with dedicated all modules for 1.7.5.1. All costumer and products was migartion via module Migartion Plus. 

I found the same problem in below topic with status "resolved" but author not response by 28 days.
https://github.com/PrestaShop/PrestaShop/issues/13121

**Comment by khouloudbelguith** [comment]
@masztal18, this issue is related to the database.
It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.5.1
Thanks to check if there are missing columns in your database schema.
You can find the full schema for 1.7.5.1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/install-dev/data/db_structure.sql

Thanks to check & feedback

**Comment by masztal18** [comment]
If i create new account client and i confirmation order, then all works correct. It seems to me that this is a bug in the database.

**Comment by khouloudbelguith** [comment]
@masztal18, this issue is related to the database.
It could be something went wrong with your update and don't have some of the database columns that were added for 1.7.5.1
Thanks to check if there are missing columns in your database schema.
You can find the full schema for 1.7.5.1 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.1/install-dev/data/db_structure.sql

Thanks to check & feedback

**Comment by khouloudbelguith** [comment]
Hi @masztal18,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
