### ISSUE TITLE
Assign "Generate high resolution images" to Smarty

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#13957]
Right now we have an option of generating higher resolution images: `Design > Image Settings > Generate high resolution images`. 

As far as I can tell though, there is no real way of actually using them. They are not assigned to any `image` object. As a test:

1. Open `classic\templates\catalog\_partials\miniatures\product.tpl`
2. Add `<pre>{print_r($product)}</pre>` to review available information
3. Notice there are **no** traces of any `2x` anywhere
4. We don't even have an option to check whether or not the `Generate high resolution images` option is active

**What we need**
We need to be able to:
1. Check if `Generate high resolution images` is active or not
2. Check if there actually is a "2x" image generated
3. Have it available on the `cover` and `images` objects/arrays.

**Additional information**
PrestaShop version: 1.7.x

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.2.

Similar issue reported on forge: http://forge.prestashop.com/browse/BOOM-2925
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by dennispw** [comment]
In order to keep up with the times I would greatly appreciate if this could be considered more than "minor". After all, with all the different devices, pixel densities etc. this is a big bonus to have at our disposal and will help all of us to create better ecommerce experiences.

**Comment by dennispw** [comment]
Any update on this? Even the original ticket on the forge is over **2 years** old.

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

Sorry not yet.
There are some major issues to solve before this one.
But PrestaShop is an open-source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by matks** [comment]
> Any update on this? Even the original ticket on the forge is over **2 years** old.

This ticket could be 2 years old, 5 years old, 10 years old, this will change nothing. The roadmap is not a [FIFO](https://en.wikipedia.org/wiki/FIFO) todo-list. The roadmap is actually a backlog in which we enter all items and sort them by priority.

For example if tomorrow you open a ticket about a major bug or feature, it will be done before this ticket although this ticket would be much older.

Does this mean we do not care about this ticket ? No. It doesn't mean that the issue is NOT important either 😉. It just means that other issues have been considered, for whatever reason, _more_ important, so they were (or are being) tackled first. There's an immense amount of work to be done (1265 issues right now, and growing!), and tasks take time.

Developer time is limited, so if the amount of tickets, bugs or features, opened in a certain timeframe exceeds the amount of issues that can be processed using the available developer time, tasks will simply **pile up**. This is common to ALL projects. Due to the number of pending issues, sometimes they may get lost in the pile and be forgotten about, so it's not a bad idea to ping us there from time to time to remind us about it 😉, like you just did, even if it's been a long while.

But here's the upside: PrestaShop is an open source, community project. If you find that any issue/feature is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

**Comment by khouloudbelguith** [comment]
PR: https://github.com/PrestaShop/PrestaShop/pull/16097

**Comment by matks** [comment]
Big thanks to @Prestaworks for handling this issue

@dennispw 😉merry christmas ?

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16097

**Comment by dennispw** [comment]
@matks Kind of, my coworkers. ;)
