### ISSUE TITLE
Error with hook displayAdminLogin

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#13962]
### BUG 1
**Describe the bug**
Hook `displayAdminLogin` is not in table `ps_hook`, so a module can not be hooked manually in this position unless you call `registerHook` function.

**To Reproduce**
1. Install module dummymodule_v1.zip
[dummymodule_v1.zip](https://github.com/PrestaShop/PrestaShop/files/3216911/dummymodule_v1.zip)
2. Go to "Design -> Positions -> Insert a module"
3. Can't be hooked to 'displayAdminLogin` because this position doesn't appear
4. Uninstall and remove module
5. Install module dummymodule_v2.zip
[dummymodule_v2.zip](https://github.com/PrestaShop/PrestaShop/files/3216910/dummymodule_v2.zip)
6. Go to "Design -> Positions"
7. Module is hooked to `displayAdminLogin`. You can unhook and hook module because now position is at `ps_hook` table.

**Hook `displayAdminLogin` should be inserted in `ps_hook` table in installation.**

**Additinnal information**
PrestaShop version: 1.7.6

### BUG 2
**Describe the bug**
Hook is linked with "multishop" and it shouldn't. It should be executed always, doesn't matter the shop context.

**To Reproduce**
1. Create a multishop with 2 stores
2. Go to "Modules -> Catalog manager"
3. Select the store with ID 2 in the store selector
4. Install module dummymodule_v2.zip
[dummymodule_v2.zip](https://github.com/PrestaShop/PrestaShop/files/3216910/dummymodule_v2.zip)
5. Open BO login page in an Incognito tab
6. Hook `displayAdminLogin` is not executed
8. Uninstall module
9. Select the store with ID 1 in the store selector
10. Install module dummymodule_v2.zip
11. Reload the previous BO login page opened
12. Hook `displayAdminLogin` is executed (appears a string `Dummy module` under the login box)

Hook is only executed if you install module in "All shops" context or in Multistore ID 1, while in BO login page there is not a shop context yet. Query that retrieves module hooks for hook `displayAdminLogin` should not take into consideration shop context.

**Additional information**
PrestaShop version: 1.7.6

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report.
First issue:
I manage to reproduce it with PS1.7.6.0beta1 & PS1.7.5.2
v1 of the module => NOK => displayAdminLogin doesn't exist
![image](https://user-images.githubusercontent.com/16067358/58332964-515d9f00-7e34-11e9-9a04-28df465d7d9f.png)
v2 of the module => OK => displayAdminLogin exist
![image](https://user-images.githubusercontent.com/16067358/58333000-676b5f80-7e34-11e9-8c33-712ed2bdb298.png)
Second issue:
I manage to reproduce it with PS1.7.6.0beta1 & PS1.7.5.2

if module installed when shop2 is selected => displayAdminLogin is not executed => NOK
![image](https://user-images.githubusercontent.com/16067358/58335417-786a9f80-7e39-11e9-971b-5f725605e5f7.png)
if module installed when shop1 is selected => displayAdminLogin is executed => OK

![image](https://user-images.githubusercontent.com/16067358/58335469-8ddfc980-7e39-11e9-82fc-735e5a859b19.png)

PS: if shop1 / shop2 are selected & we install the module => it will be installed in all shops

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by idnovate** [comment]
Where are the installation and upgrade SQL scripts?

**Comment by matks** [comment]
Here 😉 
https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/data installation data, including hooks for BDD
https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/upgrade upgrade script

**Comment by idnovate** [comment]
[Fix for Bug 2](https://github.com/PrestaShop/PrestaShop/pull/13980)
