### ISSUE TITLE
facetedsearch 3.0.1 - price slider not working on mobile

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#13965]
Hi,
Prestashop 1.7.5.2, facetedsearch 3.0.1

The price slider is ok on desktop but on a smartphone (mobile) you can slide the little bars.

Thanks

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

Could you please provide me a screenshot about your exact issue on mobile?

Thanks!

**Comment by grabelle** [comment]
![Screenshot_20190524-171938_Chrome](https://user-images.githubusercontent.com/5048627/58339234-6b55ac80-7e49-11e9-8b6e-09bccc621a1e.jpg)

You can't slide the red point on a mobile phone.

**Comment by khouloudbelguith** [comment]
Hi @grabelle,

Thanks for these clarifications.
I did not manage to reproduce the issue with PS1.7.5.2 & ps_factedsearch v3.0.2.
I attached a video record
https://drive.google.com/file/d/1tud8DLOocsu_fEs1hZbKqI4SJPlVdAp_/view
Thanks to check & feedback

**Comment by grabelle** [comment]
Hi, sorry but you click on the little bar, you don't slide your finger on the screen.

**Comment by kpodemski** [comment]
Yes, this issue exists, solution would be to use:
http://touchpunch.furf.com/

**Comment by khouloudbelguith** [comment]
Hi @grabelle, @kpodemski, thanks for these clarifications.
Yes, with ps_factedsearch v3.0.2, on a mobile phone touch screen, we can't slide the finger on the screen, but we can click
https://photos.app.goo.gl/Pv894CisEtccSeRW8

With ps_factedsearch v2.2.1 we have this
![image](https://user-images.githubusercontent.com/16067358/58459827-2de07000-8124-11e9-85ed-19ea31048509.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
ping @PierreRambaud

**Comment by PierreRambaud** [comment]
Should be ok with https://github.com/PrestaShop/ps_facetedsearch/pull/73 waiting for your feedback @kpodemski :+1:
