### ISSUE TITLE
Faceted search not displaying on custom hooks after upgrade to 3.0.2

### ISSUE THREAD

**Issue by gbr161** [PrestaShop/PrestaShop#13993]
**Describe the bug**
Module is shown only at left column.

**To Reproduce**
1. Try to transplant the module anywhere from displayLeftColumn hook.

I have custom hooks on my template and it was all working fine until this update. I know you were remaking this module but taking out possibility to hook it anywere than hooks hardcoded in module is nothing good for users/developers.

**Comment by khouloudbelguith** [comment]
Hi @gbr161,

Thanks for your report.
Your report makes our module better!
I manage to reproduce the issue with PS1.7.6.0beta1 & ps_factedsearch v3.0.2.
With ps_facetedseach v2.2.0 => OK
I attached a video record
https://drive.google.com/file/d/15BV_T72-ha8b-hpVOjIr26iQfhbgdTkd/view

Before the upgrade of the module
![image](https://user-images.githubusercontent.com/16067358/58458442-2a97b500-8121-11e9-970a-a8068b03052e.png)

After the upgrade

![image](https://user-images.githubusercontent.com/16067358/58458481-4307cf80-8121-11e9-8160-efba10915af3.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
ping @PierreRambaud

**Comment by PierreRambaud** [comment]
Should be ok here: https://github.com/PrestaShop/ps_facetedsearch/pull/74 Thanks for your feedback!

**Comment by gbr161** [comment]
@PierreRambaud I just tested your changes and it works as it should - faceted search displays where i place it, not only in displayLeftColum hook. Thank you very much.

**Comment by PierreRambaud** [comment]
@gbr161 Thanks, we are planning to release a new version this week, with fixes :wink:

**Comment by Peterits** [comment]
Hello team, with v3.0.2 faceted navigation, there are also a lot of problems with the display of the weight of items for delivery, add the search for the weight you will understand, depending on the version the kg for example becomes € ! Version v1.7.5.2, I personally came back to V2.2.1! See the video !

![v3 0 2 faceted navigation](https://user-images.githubusercontent.com/44966543/58548540-ca307280-8209-11e9-8e12-07ff152f3cda.gif)

**Comment by khouloudbelguith** [comment]
@Peterits, Yes, I manage to reproduce the issue with ps_factedsearch v3.0.2
![image](https://user-images.githubusercontent.com/16067358/58549082-a158af00-8202-11e9-8958-e22fa2a99bee.png)
I will create a new issue.
Thanks!

**Comment by khouloudbelguith** [comment]
@Peterits, this issue occurs only with PS1.7.5.2, but with PS1.7.6.0BETA1, it is OK
https://drive.google.com/file/d/1uJv7s4uW8KhV_q6UlHgDpb7DerWFagPm/view
![image](https://user-images.githubusercontent.com/16067358/58549553-b1bd5980-8203-11e9-8a1e-5799a54fd863.png)

So no need to create an issue, it is fixed.

Thanks!

**Comment by Peterits** [comment]
Ok, thanks for the info, but how do we do with 1.7.5.X ?? 😉

**Comment by khouloudbelguith** [comment]
@Peterits, we should ask our developer @PierreRambaud.
Thanks

**Comment by PierreRambaud** [comment]
I create a fix for you @Peterits https://github.com/PrestaShop/ps_facetedsearch/pull/75

**Comment by khouloudbelguith** [comment]
@PierreRambaud, it works for me!
Good work!

**Comment by espacious** [comment]
Thanks!
