### ISSUE TITLE
Wrong payments status after activation of stock management (prestashop 1.6)

### ISSUE THREAD

**Issue by LDMEDICAL** [PrestaShop/PrestaShop#14009]
Hi,
i just activated the stock magement function on my prestashop 1.6.1.4 and now, i have a problem with the order payment statuses.

For exemple 
Order test paid by check has automatically the status "paid by CB" instead of "waiting for check"
It's the same for all my payment method = wrong statuses.

If i disable the stock management it's ok.

I precise that my website has been updated since version 1.4

Regards

**Comment by khouloudbelguith** [comment]
Hi @LDMEDICAL,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.

Thanks for your understanding!

**Comment by LDMEDICAL** [comment]
ok super !!
