### ISSUE TITLE
Email Templates translation

### ISSUE THREAD

**Issue by jozefpinter** [PrestaShop/PrestaShop#14006]
Will be there an easier way (in the future) to edit email templates? like this.

1. translate prestashop email templates without editing all 30+ htmls? Some easier way. The way how it works now is very time consuming.

2. Editing email header and email footer in a single file? Because all 30+ emails shares the same header and footer.

**Comment by khouloudbelguith** [comment]
Hi @jozefpinter,

To translate email we need to go to the BO => International => Translations => 

- Select `Type of translation`: Email translations
- Select `email_content_type`: Body
- Select the language 

Now you can edit any mail type

In your case, these steps are very time-consuming?

Also, you want to edit the subject email & the core email on the same page?

PS: in the PS1.7.6.0: we have a new “modern” template design and wording for all transactional emails along with a new email template generation system and a new back office page dedicated to email management (in Design > Email theme)

Thanks to check & feedback

**Comment by jozefpinter** [comment]
Hello,

yes, it is time consuming. For example. Every email has a logo. If you want replace the logo you have to edit 30+ files for a single logo.

For example magento has a single header (and footer). It is enough to edit  a single file.

But for me localization is even bigger problem with this aproach.

BTW. I understand how to translate emails.

**Comment by nenes25** [comment]
Hi,

I've faced the same problem last week.
With a custom module and the existing hooks it is possible to manage easily header and footer 
see : https://www.h-hennes.fr/blog/2019/05/23/prestashop-simplification-de-la-mise-en-page-des-emails/  (french )
Otherwise you can try to use the not very know native prestashop module https://github.com/PrestaShop/ps_emailgenerator 

Regards,

**Comment by khouloudbelguith** [comment]
ping @marionf, @colinegin what do you think about the improvement of the email template translation?

Thanks!

**Comment by colinegin** [comment]
Indeed, we are planning on working on improving the current system. 
@jolelievre any idea on how to use the Email theme page to do this ?

**Comment by jolelievre** [comment]
Hi @colinegin,
I researched a little for this feature. It turns out to be a quick change. The main issue is that in translation page we can only edit keys for `EmailsSubject` domain, but by adding `EmailsBody` to this class https://github.com/PrestaShop/PrestaShop/blob/25a4e7660d5e8590ce5e6368505090da128ad308/src/PrestaShopBundle/Translation/Provider/MailsProvider.php#L39

Then we can translate the emails text from the back office, we should just change the form in translation page and replace in the selector "Subject" by "Subject and body texts" (or something similar)

This is the quick win modification, another possibility is to create another provider class `MailsBodyProvider` dedicated to body messages and add it in the selector.

Lastly we could integrate this form in the EmailTheme page to make it easier to access (without leaving it from the translation page to avoid confusing people used to this feature).

Either way this is not a heavy modification.

**Comment by colinegin** [comment]
This is great to hear ! Let's discuss it to see what's the better & quickest way to do it and try to implement it in 1.7.7.

**Comment by eternoendless** [comment]
I'm under the impression that this has been done in 1.7.7:

You can go to Design > Email Theme, then scroll down to Translate emails.

**Comment by eternoendless** [comment]
Duplicate of #15474
