### ISSUE TITLE
Provide reference usecase modules always up-to-date

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#14005]
We should provide some reference modules that people can use as an example/reference/skeleton to build their modules.

Usecases I can think of:
- carrier module
- payment module
- module that displays a block on FO
- module that displays a block on BO
- module that modifies login process (SSO ? )
- module that adds fields to a form in BO

These modules should provide:
- best practices about codestyle
- what a good module should do or should'nt do
- ideal folder structure
- security best practices
- explanations of what's going on under the hood (ex: uninstall process unregisters hooks automatically)
- use software quality tools such as phpstan (see https://github.com/PrestaShop/php-coding-standards)
- have a CI setup using Travis

We should update them for every minor version releases, in order to show new useful features for modules. So for 1.7.6 we should use Twig, Doctrine, new hooks, tests.

Doc tutorials about modules should refer to them

**Comment by matks** [comment]
Cc @Matt75 😉

**Comment by sarjon** [comment]
This is something that @tomas862 had already started. https://github.com/Invertus/prestashop-module-skeleton

**Comment by Matt75** [comment]
Great 🥳

We will have some feedback during [PSD Paris](http://build.prestashop.com/news/psd-2019-developer-space/) to define priority depends on top watchers.

For Payment Module, there are already https://github.com/PrestaShop/paymentexample who need some improvement to fit guideline defined here.

For Carrier Module, we have to explain how `FrontController::registerJavascript()` and first argument can help to not have multiple Google Maps included for example. Recurring problem since beginning of PrestaShop 😅
I think we should have something like `PrestaShop\PrestaShop\Core\Payment\PaymentOption` for Carrier, because some needs to select a pickup store etc... Currently this process is a real mess in order process due to missing guidelines...

**Comment by Quetzacoalt91** [comment]
Also, there is the validator which is able to generate modules: https://validator.prestashop.com/generator, and this old repository in which we can find another skeleton (from 2014): https://github.com/PrestaShop/module-generator

It looks like everybody had the same idea, but it is now time to merge everything in a single place instead of creating something else new. :)
Let me know if I can help.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/example-modules/
