### ISSUE TITLE
Prestashop 1.6.1.22 Free gift finder is doesn't work during new rule create

### ISSUE THREAD

**Issue by createcreative** [PrestaShop/PrestaShop#14019]
Hi!

I recently noticed that I can't add gift during new rule create because the free gift finder (in Action tab) doesn't work. I have the same issue in few shops. Is anyone can help me solve that problem?

**Comment by khouloudbelguith** [comment]
Hi @createcreative,

I did not manage to reproduce the issue with PS1.7.6.0beta1
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.

Thanks for your understanding!
