### ISSUE TITLE
Lack of practice registering combinations in PrestaShop

### ISSUE THREAD

**Issue by brunobenyyyyy** [PrestaShop/PrestaShop#14034]
I have to show several pairs of shoes and different colors and different numbers. For example: A shoe of 5 colors and the size of 32 to 42, I would have to create about 50 assignments, that's a lot of work. I have to go for example, inside the registered menu of the product: shoe, black, size 32 and relate the images to it.
shoe, black, size 33 and relate the images to it.
shoe, black, size 34 and relate the images to it.
shoe, black, size 35 and relate the images to it .................
I could select all the items I wanted to relate to the images, and save, so you would be more practical, but there are no boxes to mark and do that.

The related images, serve for the client to go on the site and for example click on: shoe, pink, size 35 and appear a pink shoe. if it did not have this tool it would appear any image of the advertisement

in the prestashop panel
Catalog - products - edit product - combinations -

![1111](https://user-images.githubusercontent.com/51216922/58672674-7fece580-831e-11e9-9ce4-e6f393c88944.png)

 1.6.1.13 version

**Comment by khouloudbelguith** [comment]
Hi @brunobenyyyyy,

Thanks for your report.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.

But this feature could be added in the PS1.7.
In the BO => Product detail page => combination tab => we can add the list of images in the Bulk actions
![image](https://user-images.githubusercontent.com/16067358/58693887-aac05380-8389-11e9-906e-774d13040bef.png)

@marionf, @colinegin what do you think?

Thanks!

**Comment by marionf** [comment]
Duplicate of #12773
