### ISSUE TITLE
[Ps_FacetedSearch] error on non multiple facet

### ISSUE THREAD

**Issue by netraagal** [PrestaShop/PrestaShop#14082]
**Describe the bug**
When a facet is non multiple and active on front, facets listed after it do no keep the information that it is active.

**To Reproduce**

1 - I have 2 facets
	- the first is not multiple allowed
	- the second is
2 - I am on a category page on the front and have the first facet activated.
3 - I use the second facet, the first is not kept.

**Code**
file src/Product/SearchProvider.php
class PrestaShop\Module\FacetedSearch\Product\SearchProvider
function addEncodedFacetsToFilters()

In the foreach($facets as $facet) block, the current facet is removed from active list if it is not multiple allowed.
And next the URL parameter block is generated.
Ok for the non multiple facet.

**BUT** the next facet use the same active list, where we removed the active filter of the previous non multiple allowed facet.

**Additionnal information**
PrestaShop version: 1.7
Ps_FacetedSearch version: 2.2.0 (the concerned function is the same is the newest version 3.0.2)
PHP version: 7.1.13

**Comment by PierreRambaud** [comment]
Hi and thanks for your feedback.
I create an pull request to fix this issue: https://github.com/PrestaShop/ps_facetedsearch/pull/86
But still working in progress, we need to add unit tests before to prevent regression in the future.

@khouloudbelguith @marionf Don't know if this one is a duplicate (can't search due to my internet connection).
