### ISSUE TITLE
Changements dans les produits non pris en compte

### ISSUE THREAD

**Issue by Akmicro55** [PrestaShop/PrestaShop#14110]
**Describe the bug**
Toutes les modifications sur l'un de nos produits ne sont pas prises en compte après l'enregistrement. que ce soir le changement de prix, changement de quantité ou de texte aussi...

**To Reproduce**
Effectuer un changement/modification dans un produit

**Additionnal information**
PrestaShop version: 1.6.1.10

**Comment by mariem-abid** [comment]
Hi @Akmicro55,

I did not manage to reproduce the issue with PS:1.7.5.2 and PS:1.7.6.0beta1
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in extended maintenance mode until June 30, 2019.

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.
Thanks for your understanding!
