### ISSUE TITLE
VAT (Japan)

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#14127]
Hello,

By default (fresh install PS 1.7.5.2) the VAT for Japan is 5%.
From 2014, the VAT is 8% and in October 1st 2019, it will be 10%.

Not so important because we can modify the value but it can be interesting to set the currently one by default.

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your report.
Yes, it is the same behavior with PS1.7.6.0.beta1
By default, after a fresh installation (Japan country / Japanese language), the VAT for Japan is 5%
![image](https://user-images.githubusercontent.com/16067358/59187747-077ff300-8b6e-11e9-99f0-af2ab34633f5.png)
![image](https://user-images.githubusercontent.com/16067358/59187751-0b137a00-8b6e-11e9-9c45-4fb3c28b86e6.png)

ping @marionf, @colinegin, what do you think? can we change it?

Thanks!

**Comment by LouiseBonnard** [comment]
Dear @BenTen, thanks for reporting this issue. Localization packs need to have their data updated, you're absolutely right. And this work is planned for the next minor version, 1.7.7, which is due for the end of the year. I close this issue since it has been added to our roadmap, but feel free to open it again if you need to bring another information to our attention. :-)
