### ISSUE TITLE
Changing order status bug - wrong logic - 1.7.5.2

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#14159]
**Describe the bug**
There is a wrong confirmation message when changing order status

**To Reproduce**
1. Go to 'orders and filter by status (status is not important)'
![step1](https://user-images.githubusercontent.com/31688689/59335005-febd2780-8cfb-11e9-8fbc-83c1a0c3744e.png)

2. Do NOT select any order and click on 'Bulk actions/Change Order Status'
3. You can now choose any new order status you like
![step2](https://user-images.githubusercontent.com/31688689/59335116-3c21b500-8cfc-11e9-9e33-d22302b66177.png)

4. Confirm "Update Order Status"

5. Successful update is displayed but no order status is changed.

6. If you already selected orders by filter, it should be possible to change the order status without further selecting individual orders. If it is not possible, there should be no successful message.

PrestaShop version: 1.7.5.2 
PHP version: 7.1.30

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2
https://drive.google.com/file/d/1G0BzdaA34U_LPnfVEynbHqvRZ2-R_dLH/view
@matks, this issue could be fixed in this ticket: https://github.com/PrestaShop/PrestaShop/issues/10582?

Thanks!

**Comment by matks** [comment]
@khouloudbelguith Yes it's an easy bug to fix, I add it to the issue 😄

**Comment by hibatallahAouadni** [comment]
Hello @mrabsinthe 

This issue has been fixed with PS1780, see the attached screen records below:

**Changing one order status:**

https://www.awesomescreenshot.com/video/6417487?key=90ac5bd63e3fc98f36ac072970fcdd98

**Changing the orders status with bulk actions:**

https://www.awesomescreenshot.com/video/6417523?key=5ddddde912b1d12fdbafaa50970f6587

Closing this issue :tada: 
Thanks!
