### ISSUE TITLE
Email translation of non-core theme 'save and stay' links to core theme 

### ISSUE THREAD

**Issue by nrcjea001** [PrestaShop/PrestaShop#14182]
**Describe the bug**
Whenever I change an email translation in a non-core theme (such as the classic or a newly purchased theme) and then click "save and stay", the link takes me to the core theme page instead.

**To Reproduce**
1. Go to email translation, choose body, classic theme, English
2. Click on core emails, order_changed and make a change to the email text.
3. Click 'save and stay'
4. Go back to order_changed and notice that nothing has changed (the link takes you to core theme instead of remaining in classic theme)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @nrcjea001,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2.
When I click "Save & Stay", I'm redirected to the core theme instead of remaining in a classic theme.
https://drive.google.com/file/d/1sF126ZFh-g6067S4yVlQUiQfQFlCLwny/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20070
