### ISSUE TITLE
Cannot use accented URL with arabic language

### ISSUE THREAD

**Issue by psX01** [PrestaShop/PrestaShop#14184]
**Describe the bug**
problem with language translation RTL in category (Arabic for example)

**Screenshots**
![no-valid0](https://user-images.githubusercontent.com/51779391/59416798-080ec880-8dbe-11e9-8dd0-21f646233bd4.jpg)
![no-valid](https://user-images.githubusercontent.com/51779391/59416812-0cd37c80-8dbe-11e9-8823-aca8d0d863e2.jpg)

**Additionnal information**
PrestaShop version: 1.7.6.0 Beta
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @psX01,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0beta1
When I create a category with `Friendly URL` = `إكسسوارات` in the Arabic language, I have an error
 
`"إكسسوارات" is invalid. - Language: اللغة العربية (Arabic)`

https://drive.google.com/file/d/1LctO1-ei3w3OpEhQ0BsFDHm12qqGcq2Q/view
![image](https://user-images.githubusercontent.com/16067358/59417598-786a1980-8dbf-11e9-8045-44c77388e970.png)

I tried to enable the `Accented URL` in the Traffic & SEO > SEO & URLs page, but the same issue.

In the PS1.7.5.2, it is OK.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Other informations:

1. In the PS1.7.5.2, if the `Accented URL` is enabled, we can create a category with Friendly URL = `إكسسوارات` in the Arabic language successfully.

2. With PS1.7.6.0beta1, in the Product page, we can create a product with Friendly URL = `إكسسوارات` in the Arabic language successfully.
![image](https://user-images.githubusercontent.com/16067358/59419595-21feda00-8dc3-11e9-8e97-ceeec0cf17cc.png)

3. With PS1.7.6.0beta1, On the Customer page, we can create a new customer with arabic name & last name.

4. In the Design > Pages, e can create a new page with Friendly URL = `إكسسوارات` in the Arabic language successfully.
![image](https://user-images.githubusercontent.com/16067358/59419878-c254fe80-8dc3-11e9-9be3-9514cc5fdfa9.png)

5. In the Design > Pages, e can create a new category page with Friendly URL = `إكسسوارات` in the Arabic language successfully.

Thanks!

**Comment by khouloudbelguith** [comment]
The same issue occurs in the category page when we have a meta keyword in the Arabic language.
![image](https://user-images.githubusercontent.com/16067358/59420240-7191d580-8dc4-11e9-9856-e953aac2a06a.png)

In the PS1.7.5.2, it is OK.
We can create a new page & new category page with meta keyword = `إكسسوارات` in the Arabic language successfully.

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14248

**Comment by abdessalem-woopa** [comment]
I think there is a regression on prestashop 1.7.7.0
I am experiencing the same issue
