### ISSUE TITLE
How to downgrade prestashop version 

### ISSUE THREAD

**Issue by renochost** [PrestaShop/PrestaShop#14209]
Please tell me Is the any way to downgrade prestashop version without uninstalling it and without loosing the data ?

**Comment by khouloudbelguith** [comment]
Hi @renochost,

You can use the 1-click upgrade to make rollback to previous database & files.
![image](https://user-images.githubusercontent.com/16067358/59501461-7a9da800-8e93-11e9-9a3e-8d3f5c1c0594.png)
In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the rollback on a separate machine from your production.

I close the issue, feel free to open a new one when needed.

Thanks!
