### ISSUE TITLE
not able to add to cart

### ISSUE THREAD

**Issue by anc91** [PrestaShop/PrestaShop#14228]
when i click add to cart i get this message
![Screenshot 2019-06-15 at 11 45 11 AM](https://user-images.githubusercontent.com/51860221/59554032-26fa8f80-8f63-11e9-8fe8-65341f05624f.png)

When i click on the cart though the item does show up in there. When i try to delete an item from the cart it says its unable to. 

I've disabled modules to try to identify the problem. But i haven't been able to fix it. I am using a chromebook to access my back office.

my website is https://www.covetlegs.com/shop/

PrestaShop version: 1.6.1.23

**Comment by ghost** [comment]
Hi. Its not fault of Prestashop 1.6.1.23 core.
It's fault of js mess in template 

![mess](https://user-images.githubusercontent.com/8243273/59588389-c3e63580-90e7-11e9-9658-c866b055d5a7.jpg)

**Comment by khouloudbelguith** [comment]
Hi @anc91,

Thanks for your report.
I did not manage to reproduce the issue with PS1.6.1.24.
I attached a video record
https://drive.google.com/file/d/1phk-VdZ61Sk_RlnFtzmTxmCBgedodo7A/view
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks for your understanding!
