### ISSUE TITLE
Faceted search - displaying wrong Availability count

### ISSUE THREAD

**Issue by gbr161** [PrestaShop/PrestaShop#14230]
**Describe the bug**
Counter has doubled value. If there are 10 products and one is not available counters shouild be: In stock (9) / Not available (1) but they are 8 / 2. If there are 2 products not available counters ar 6 / 4 and so on. 

**To Reproduce**
1. Add some products
2. Change random product quantity to 0 at product page in admin panel
3. Check faceted search counters

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.0.27

**Comment by khouloudbelguith** [comment]
Hi @gbr161,

Thanks for your report.
In the BO => Shop Parameters => Product Settings => the option "Allow ordering of out-of-stock products " is enabled or disbaled?
And what is the exact version of the ps_factedsearch did you use?

Thanks!

**Comment by gbr161** [comment]
Thanks for the reply.
"Allow ordering of out-of-stock products " is disabled.

ps_factedsearch version is v3.0.4

**Comment by khouloudbelguith** [comment]
@gbr161, thanks a lot for your feedback.
I manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2 & ps_facetedsearch v3.0.4.
https://drive.google.com/file/d/1WBio_A3j7YqO0LwpSCD74qQ490AkQ8ZZ/view
With ps_facetedsearch v2.2.0 => OK.

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
ping @PierreRambaud 
Thanks!

**Comment by PierreRambaud** [comment]
@khouloudbelguith @gbr161 Fixed in https://github.com/PrestaShop/ps_facetedsearch/pull/97 can you tell me if everything is ok? Thanks a lot for your feedback.

**Comment by gbr161** [comment]
@PierreRambaud All good. Thanks for fixing it very fast :)

**Comment by PierreRambaud** [comment]
Thanks to you for helping us to improve our native modules 👍
