### ISSUE TITLE
Error 404 con modulo MercadoPago en Prestashop 1.6

### ISSUE THREAD

**Issue by FabianaTorre** [PrestaShop/PrestaShop#14254]

**Comment by khouloudbelguith** [comment]
Hi @FabianaTorre,

Please, send your request in English.
English is the norm on this bug tracker. 
Thank you!

**Comment by khouloudbelguith** [comment]
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.
Thanks for your understanding!
