### ISSUE TITLE
Hook checkoutsession

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#14261]
For google analytics I want to be able to track each step during checkout.
There is no hook currently in OrderController, and it would be great to be able to have a hook with the steps list and the current step in order to send that data to google analytics after each new step.

**Comment by khouloudbelguith** [comment]
Hi @cedricfontaine,

This is the list of hooks displayed on the checkout page
displayPersonalInformationTop: Available since PS1.7.6 => Display actions or additional content in the personal details tab of the checkout funnel.

- displayBeforeCarrier: This hook is displayed before the carrier list on the Front Office
- displayAfterCarrier: This hook is displayed after the carrier list in Front Office
- actionCarrierUpdate: This hook is called when a carrier is updated
- displayPaymentTop: This hook is displayed at the top of the payment page
- termsAndConditions
- displayOrderConfirmation1

For more details, you can follow our documentation: https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/

THanks to check & feedback.

**Comment by Matt75** [comment]
You can also use PrestaShop javascript event for this :

https://github.com/PrestaShop/PrestaShop/blob/4c262cecde12a2a3e20deb979e23963a8edba964/themes/_core/js/checkout.js#L58

https://devdocs.prestashop.com/1.7/themes/reference/javascript-events/

**Comment by cedricfontaine** [comment]
Thanks, that's good suggestion. I'll work on this.

**Comment by khouloudbelguith** [comment]
@cedricfontaine, thanks for your feedback.

Can I close the issue?

Thanks!

**Comment by cedricfontaine** [comment]
Yes

**Comment by khouloudbelguith** [comment]
@cedricfontaine, thanks!
Feel free to open a new one when needed.

Thank you!
