### ISSUE TITLE
Manufacturers/Suppliers logo in list differs from logo in edit action when editing in different shop context

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#14299]
**Describe the bug**
This bug applies on both - manufacturers and suppliers. When changing logo in one shop context, the logo in other shop context differs between list and edit action. This happens because in list logo is taken considering the shop context, when in edit action shop context is not considered.

**To Reproduce**
Have two shops containing couple shared manufacturers (demo data suits fine)
1. Select first shop context
2. Go to `Sell > Catalog > Manufacturer > edit manufacturer
3. Change manufacturer logo image
4. Go to second shop context
5. Go `Sell > Catalog > Manufacturer`
6. See that manufacturer logo in list didn't change.
7. Click `Edit` on that manufacturer.
8. See that in edit action the logo has actually changed.

**Additionnal information**
PrestaShop version: 1.7.6.x (should also be reproduced in previous versions)
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I manage to reproduce the issue with PS1.7.5.2 & 1.7.6.x branch.
1.7.5.2: https://drive.google.com/file/d/1Wzj1mzk1L9NK-8YLN43F-2N6VsKUm64c/view
About The PS1.7.6.0: the first modification is OK, but the second modification is NOK as described in my screen record
1.7.6.0: https://drive.google.com/file/d/1MJLaKtms8o8CYJGFiqIgLGobxFOx8CCS/view
I’ll add this to the debug roadmap so that it’s fixed. 
Thanks!
