### ISSUE TITLE
Ignore non existing product while importing by reference

### ISSUE THREAD

**Issue by k-raw** [PrestaShop/PrestaShop#14306]
When you import products by reference in order to update just a few columns, Prestashop create a new product if the reference doesn't exist in database. Previously, the name of the product was a mandatory field which is no longer the case. Now I end up to get new products without name ...

Prestashop should ignore the rows where the reference isn't found in the database. At least, we should have an option to tell that in the first step once we choose to use reference.

**Comment by khouloudbelguith** [comment]
Hi @k-raw,

Thanks for your report.
I manage to reproduce the issue WITH ps1.7.5.2 & ps1.76.0BETA1.
I used this file 
[test.csv.txt](https://github.com/PrestaShop/PrestaShop/files/3311047/test.csv.txt)
In the import page, I enabled the option "Use product reference as key "
The import is done successfully but I have products with empty names

![image](https://user-images.githubusercontent.com/16067358/59860817-8ef01200-9377-11e9-9e91-645b60583067.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by k-raw** [comment]
I wonder which logic should be used.

I really want to be able to do import just for updating some fields (so I don't want any restriction about required ones).
I guess we could solve this with something like: if all mandatory fields are not there and the reference doesn't exist => ignore the row. In the case all is ok => add a new product.

But I think the user should have the choice between "Add a new product" or "Ignore the row" when the reference doesn't exist, even if the mandatory fields are not missing.

What do you think ?

**Comment by khouloudbelguith** [comment]
@k-raw, I think it could a red alert about the missing of the name will be the best solution.

Thanks!
