### ISSUE TITLE
Customer service - status not changed on reply 1.7.5.2

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#14313]
**Describe the bug**
Status of a message thread is not being changed to "Closed" when replying from order's page.

**To Reproduce**
1. Create an account, place an order, go to contact us page, select order ref number and send a message
2. In BO view the order and reply to the message:
![reply](https://user-images.githubusercontent.com/31688689/59903961-a1635d80-9402-11e9-8903-814514bdee8d.png)
3. Go to Customer Service - thread is still with green light - open status (should be status closed)
4. Despite the fact that the message is correctly visible in thread:
![thread](https://user-images.githubusercontent.com/31688689/59904113-fd2de680-9402-11e9-9488-6dd5ad523ccb.png)

The thread should be marked as handled / closed no matter if replied from order's page or from its thread.
 
**Screenshots**
https://drive.google.com/file/d/10ERrehIxwITxuc0GDK9rOAUO80akPU83/view

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.3.6

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0(branch 1.7.6.x).
In fact, when we replay to the customer from the order page, the thread is not closed, it is still open.
But if we replay to the customer from the customer service page, the thread will be closed.

https://drive.google.com/file/d/10ERrehIxwITxuc0GDK9rOAUO80akPU83/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by florine2623** [comment]
Fixed in 9.0.x :

https://github.com/user-attachments/assets/dba5f2d2-541c-43e3-953c-561ded006db3
