### ISSUE TITLE
During checkout, after login, redirects to home page instead of cart

### ISSUE THREAD

**Issue by TheChovix** [PrestaShop/PrestaShop#14315]
**Prestashop version**
1.6.1.9

**PHP version**
7.0.33

**My issue**
When using the 5 steps checkout process, I add some products to the cart and everytime I try to login (step 2), the website redirects me to the home page instead of the 3rd step of the order.

To be brief, I'm facing the same problem than this thread : [http://forge.prestashop.com/browse/PSCSX-8896](url)

I tried everything they mentionned but nothing worked, I tried to figure it out by myself but the cart still redirects me to the home page after the login.

**Comment by khouloudbelguith** [comment]
Hi @TheChovix,

I did not manage to reproduce the issue with PS1.6.1.2.4.
https://drive.google.com/file/d/1cN2cly4HOspx6LINCJwImbdBS3nTilYy/view
Try to use a Virtual host, it could a server issue.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks for your understanding!
