### ISSUE TITLE
Impossible d'envoyer des emails automatiques avec mes paramètres SMTP

### ISSUE THREAD

**Issue by jhocf** [PrestaShop/PrestaShop#14319]
Bonjour,

J'essaye de configurer les mails automatiques afin de pouvoir lancer une boutique cependant ça ne marche pas du tout j'ai une erreur : 

Error: Please check your configuration

Expected response code 250 but got code "501", with message "501 mail from address must be same as authorization user "

Je suis sous prestashop 1.7.5.0.
J'ai essayé beaucoup de combinaisons de chiffrement et de port mais rien n'y fais.

Auriez-vous des pistes pour une solution ?

**Comment by khouloudbelguith** [comment]
Hi @jhocf,

Thanks for your report.
English is the norm in this bug tracker.
About the technical configuration: to configure PrestaShop to send emails to your customers. We strongly advise you that you consult your web host to determine which settings to use for this feature.
 In my case, I use the SMTP server: `smtp.gmail.com` & it is well working with different issues.

Thanks to checking with your host & feedback.

**Comment by jhocf** [comment]
Sorry my bad. 
In my case the SMTP srever is : smtp.exmail.qq.com 
With an SSL encrypting so a 465 port

**Comment by khouloudbelguith** [comment]
@jhocf, issue solved?

Thanks!

**Comment by jhocf** [comment]
Euh no, I have all the information from my web host but it's doesn't work. He checked if the SMTP service was turned on and it is. I tried with a gmail account and it works but not with my host. Always the same error

**Comment by khouloudbelguith** [comment]
@jhocf, what is the exact PHP version did you use?

Thanks!

**Comment by jhocf** [comment]
I am using : PHP Version 5.6.31

**Comment by khouloudbelguith** [comment]
@jhocf, When trying to send a test message/newsletter using a custom SMTP method configured to use TLS/SSL encryption, you see an authorization error message.
In fact, PHP 5.6 or newer forces  [verification of the destination server's authenticity](http://php.net/manual/en/migration56.openssl.php). If for some reason, the server uses an invalid (or self-signed) certificate or your PHP has an invalid/missing certificate authority bundle, the secure connection will fail.
The solution, In the case of the invalid/missing certificate authority, please ensure that your host has a properly configured PHP installation that uses a valid [certificate authority bundle](https://curl.haxx.se/docs/caextract.html). 
If you are still unable to connect, it is possible that the destination server is using a self-signed certificate, which is disallowed by default. In this case, you can use a custom hook to configure the secure connection (i.e.,  [set SSL context options](http://php.net/manual/en/context.ssl.php)) and disable self-signed certificates and/or authenticity verification. 
I hope this helps you to solve your issue.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thanks for your understanding!
