### ISSUE TITLE
Link to a product from best sales not working 1.7.5.2

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#14328]
**Describe the bug**
BO, from Dashboard, Product & Sales, select "best sellers"
![best sales](https://user-images.githubusercontent.com/31688689/59928161-6aab3880-943e-11e9-8073-d56527490f77.png)

Click the link in Product column - you should be taken directly to the product, however you will land on Products page instead, which is wrong.

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & the PS1.7.6.0(branch 1.7.6.x) & the Dashboard Products module v2.0.4.
https://drive.google.com/file/d/1psJFCVRWKQXEq3lT8tYztbYDIGeEGf6E/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Progi1984** [comment]
Fixed by PrestaShop/dashproducts#20
