### ISSUE TITLE
Command EnableThemeHandler

### ISSUE THREAD

**Issue by studiokiwik** [PrestaShop/PrestaShop#14326]
**Describe the bug**

Using a string in the php reset function.

**To Reproduce**
1. Duplicate the classic theme to create a new theme
2. Arrange for the new theme to install normally.
3. Use the classic theme.
4. Remove in the new theme theme.css (in new_theme/assets/css/theme.css).
5. Define "_PS_MODE_DEV_" on true
6. Enable the new theme.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: 7.1
![bug_1](https://user-images.githubusercontent.com/4717939/59927570-12c00200-943d-11e9-9bf5-4aadc33f61f2.PNG)

Value of $errors :

![image](https://user-images.githubusercontent.com/4717939/59927624-32efc100-943d-11e9-995e-2b38d22bef31.png)

**Comment by studiokiwik** [comment]
Solution : 

Remove "reset" in the "CannotEnableThemeException"

**Comment by mickaelandrieu** [comment]
> Remove "reset" in the "CannotEnableThemeException"

:trollface: , we may check the existence for this file instead ?

Is this file required in order to enable a theme ? if not, we shouldn't expect it to be there.
If we do, we should forbid the activation of a theme when this file doesn't exists.

WDYT ?

Edit: Ok, I've understood the problem. I agree with your solution :+1:

**Comment by khouloudbelguith** [comment]
Hi @studiokiwik,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0(1.7.6.x) branch
![image](https://user-images.githubusercontent.com/16067358/59930002-d7700400-9439-11e9-9292-094e82874ced.png)

With PS1.7.5.2, we have a red alert
![image](https://user-images.githubusercontent.com/16067358/59930040-ed7dc480-9439-11e9-8b98-1fba3ddaef28.png)

It is a regression
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14331
