### ISSUE TITLE
view button does not work

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#14359]
"view" button does not work, but it works by clicking at text link.

![link](https://user-images.githubusercontent.com/26626066/60100094-4bbbe780-9759-11e9-8f67-6c17779df4e4.png)

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: 7.1.x
OS: Windows

**Comment by khouloudbelguith** [comment]
Hi @MathiasReker,

I manage to reproduce the issue with Branch 1.7.6.x & PS1.7.6.0beta1 & 1.7.6.x Branch.
When We click on "View" Orders.
When we click on "View" Carts => OK
https://drive.google.com/file/d/1N77W9QihUd6sTu3_k7GMTfeXez17HuPK/view?usp=sharing
with PS1.7.5.2 on windows => OK.
with PS1.7.6.0 on Debian => OK.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14364
