### ISSUE TITLE
Search returns extra results meaning Search exact end match is not working

### ISSUE THREAD

**Issue by hitinder** [PrestaShop/PrestaShop#14350]
When I search for a product in my website, it doesn't return the exact same result instead it returns everything.
For example, I search "Samsung Galaxy s8" and the result is 2242 products. It returned me all the products that have "Samsung" and "Galaxy" and "S8" in that. That means I have the whole "Samsung" catalog returned as a result.

Search result snapshot: **First result is A8 instead of S8**
![image](https://user-images.githubusercontent.com/9841229/60081942-86168c00-973b-11e9-8268-6ebad7ca838e.png)

In the BO I have following setting for search.

![image](https://user-images.githubusercontent.com/9841229/60082103-cbd35480-973b-11e9-897b-3a06ccbe9418.png)

PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @hitinder,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0rc1.
In the Shop Parameters => Search page => Search exact end match is enabled.
In the Product list page => I have those products
[product_2019-06-25_051336.csv.txt](https://github.com/PrestaShop/PrestaShop/files/3324486/product_2019-06-25_051336.csv.txt)

![image](https://user-images.githubusercontent.com/16067358/60085858-f7e9d800-9731-11e9-9566-78b8ec6410b5.png)

In the FO => when we try to search by "Samsung Galaxy s8" we have all products, ordered by position into a category.
![image](https://user-images.githubusercontent.com/16067358/60085991-37182900-9732-11e9-90cf-9d0c2caeea53.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/12407

**Comment by Tanguy-SALMON** [comment]
Hi @hitinder,

Does changing the setting of your search parameter like here could resolve your problem ?

Product name weight: 8
Reference weight: 2
Short description weight: 0
Description weight: 0
Category weight: 5
Brand weight: 10
Tags weight: 0
Attributes weight: 0
Features weight: 0

Regards,
Lathanao

**Comment by colinegin** [comment]
Closing this as it's integrated into #14428.

**Comment by hardikkal** [comment]
![img_20230715](https://github.com/PrestaShop/PrestaShop/assets/134080957/25011f01-848d-42f7-ad7d-7ffd6d8b4f3e)
