### ISSUE TITLE
Configuration::updateValue can return wrong type

### ISSUE THREAD

**Issue by zalexki** [PrestaShop/PrestaShop#14363]
**Describe the bug**
`Configuration::updateValue` return wrong type when you update the value.
Looks ok when the value to update is equal to the value in DB.
Wrong doc is here : https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/classes/Configuration.php#L423

**To Reproduce**
1. Create a configuration key named 'myawesomeconfig' set to 'false';
2. `Configuration::updateValue('myawesomeconfig', 'false');` will return true
3. `Configuration::updateValue('myawesomeconfig', 'true');` will return 1 (and not a bool as stated in the docs)

**Additionnal information**
PrestaShop version: 1.7.5.2
PHP version: 7.2.17

**Comment by khouloudbelguith** [comment]
Hi @zalexki,

In my case, I tried with PS1.7.5.2 & PS1.7.6.0beta1.
I just set the IMAP URL to false.
In the two cases, it returns 1.

`print_r("false => ".Configuration::updateValue('PS_SAV_IMAP_URL', 'false'));` => return 1
`print_r("true => ".Configuration::updateValue('PS_SAV_IMAP_URL', 'true'));` => return 1
Which is not a bool.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by zalexki** [comment]
well i guess we can just replace `return $result;` by `return (bool)$result;` [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/classes/Configuration.php#L542) but i don't like it much, i'd rather take more time investigating and see if there is a more elegant fix to apply somewhere else (i'm very new to prestashop ^^).
But that will not be so soon.

Also maybe this 1 properly means something and only the docs need a little update ¯\_(ツ)_/¯
