### ISSUE TITLE
Error SQL in class CMSCategoryCore in the method getRecurseCategory

### ISSUE THREAD

**Issue by carlead** [PrestaShop/PrestaShop#14366]
Hello,

I found a bug in CMSCategory class for the multisite mode Prestashop in last version 1.6.1.24.
You forgot an `id_shop` in SQL :
`$sql = 'SELECT c.id_cms, cl.meta_title, cl.link_rewrite
				FROM '._DB_PREFIX_.'cms c
				'.Shop::addSqlAssociation('cms', 'c').'
				JOIN '._DB_PREFIX_.'cms_lang cl ON c.id_cms = cl.id_cms
				WHERE id_cms_category = '.(int)$current.'
				AND cl.id_lang = '.(int)$id_lang.($active ? ' AND c.active = 1' : '').'
				GROUP BY c.id_cms
				ORDER BY c.position';`
Correction :  
`$sql = 'SELECT c.id_cms, cl.meta_title, cl.link_rewrite
				FROM '._DB_PREFIX_.'cms c
				'.Shop::addSqlAssociation('cms', 'c').'
				JOIN '._DB_PREFIX_.'cms_lang cl ON (c.id_cms = cl.id_cms AND cl.id_shop = '. (int) Context::getContext()->shop->id .' AND cl.id_lang = '.(int)$id_lang.')
				WHERE id_cms_category = '.(int)$current . ($active ? ' AND c.active = 1' : '').'
				GROUP BY c.id_cms
				ORDER BY c.position';`

Hoping to have been of assistance,

Have a nice day,

**Comment by khouloudbelguith** [comment]
Hi @carlead,

Thanks for your report.
It is the same issue with 1.7.6.x branch https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/CMSCategory.php#L194 
& PS1.7.5.2: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.2/classes/CMSCategory.php#L194

Would you be willing to make a pull request on GitHub with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop

PS: 
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.
Thank you!

**Comment by sarahdib** [comment]
Hello @carlead 

Thank you for your contribution.

In order to test we need the steps to reproduce the error.

Thank you

**Comment by matks** [comment]
@carlead your suggestion has been merged into the codebase through https://github.com/PrestaShop/PrestaShop/pull/15926 . Thank you !
