### ISSUE TITLE
Multiple failures from Travis on build PRESTASHOP_TEST_TYPE=e2e EXTRA_TESTS=functional

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#14384]
We have a insane number of CI builds failing because of a random occurrence of a test failure:

```
Guest Checkout
  1) "before all" hook
26 passing (27.50s)
1 failing
1) "before all" hook:
element (#blockcart-modal) still not visible after 2500ms
running chrome on Windows 7
Error: element (#blockcart-modal) still not visible after 2500ms
    at Object.<anonymous> (node_modules/webdriverio/lib/commands/waitForVisible.js:56:19)
    at Object.safeExecute (node_modules/webdriverio/lib/utils/safeExecute.js:19:24)
    at Object.resolve (node_modules/webdriverio/lib/webdriverio.js:87:29)
    at node_modules/webdriverio/lib/webdriverio.js:227:32
    at _rejected (node_modules/webdriverio/node_modules/q/q.js:830:24)
    at node_modules/webdriverio/node_modules/q/q.js:856:30
    at Promise.when (node_modules/webdriverio/node_modules/q/q.js:1108:31)
    at Promise.promise.promiseDispatch (node_modules/webdriverio/node_modules/q/q.js:774:41)
    at node_modules/webdriverio/node_modules/q/q.js:590:44
    at runSingle (node_modules/webdriverio/node_modules/q/q.js:123:13)
npm ERR! Test failed.  See above for more details.
```

@Quetzacoalt91 already checked in localhost, test pass. And re-running the build often fixes the issue.

We need to fix it.

**Comment by Quetzacoalt91** [comment]
Here are additional details:

We often see that the selenium tests fail for the same reason. The modal after clicking on "Add to cart" is never displayed. Here is the screenshot taken on Travis when the error occurs:

![image](https://user-images.githubusercontent.com/6768917/60189017-2d70ed00-9828-11e9-94e3-cc4e212ec7bc.png)

This is not caused by an exception as we may think, but a product with customizable data. It has been altered by the script `prepare-shop.php`: https://github.com/PrestaShop/PrestaShop/blob/430dd959e92c6adb0f77bdc65b846796b7789cfe/tests/Selenium/prepare-shop.php#L110-L133

However, it appears that during the test, we sometime don't select the proper product. Although tyhe selector is correct. Maybe the products are filtered during a few milliseconds which makes the click incorrect?

**Comment by matks** [comment]
Issue was fixed by disabling the bad test. Better solution will be implemented in https://github.com/PrestaShop/PrestaShop/issues/14497.
