### ISSUE TITLE
1.7.6 RC1 Issue with  prices display (dutch , euro currency)

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14392]
language dutch, currency EURO €. Product prices in frontend are all wrong. Wrong: €14,4 instead of €14,40 Also in order summary in back-end.
default settings 1.7.6
<img width="435" alt="afbeelding" src="https://user-images.githubusercontent.com/2944981/60263606-5e612880-98e1-11e9-95dc-c9647f7a6679.png">

**Comment by khouloudbelguith** [comment]
Hi @sdwebdesign,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0rc1 (Dutch language / Euro currency).
![image](https://user-images.githubusercontent.com/16067358/60264150-6b2e4e00-98da-11e9-915e-86e1198966c3.png)

With PS1.7.5.2 => OK
![image](https://user-images.githubusercontent.com/16067358/60264167-73868900-98da-11e9-835e-2df04466c905.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
PS: It's planned to remove the number of decimal parameters in Shop parameters > General.
You can follow this ticket: #12223
And it's also planned to add this feature in CLDR part 2: #11660
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14400
