### ISSUE TITLE
faceted search module price slider bug

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#14394]
Version 1.7.5.1 with module faceted search filter

<img width="386" alt="Schermafbeelding 2019-06-27 om 13 53 17" src="https://user-images.githubusercontent.com/2944981/60264251-06c3bc80-98e3-11e9-8754-5fe9192eb768.png">

**Comment by khouloudbelguith** [comment]
Hi @sdwebdesign,

What is the exact version of the ps_fecetedsearch module did you use?
Is it v3.0.5, if no, thanks to upgrade your module & feedback.
Thanks!

**Comment by ghost** [comment]
hi @khouloudbelguith module version v3.0.5

cleared cache , rebuild attributes and prices without result.

**Comment by ghost** [comment]
extra info: also no price slider at all in 1.7.6 RC1. maybe related to #14392

**Comment by khouloudbelguith** [comment]
@sdwebdesign, thanks for your feedback.
Yes, I manage to reproduce the issue with PS1.7.5.2 & ps_facetedsearch v3.0.5.
This issue is reproduced when Dutch Language/ Euro currency or Dollar currency.
With English language => OK
![image](https://user-images.githubusercontent.com/16067358/60265202-193af780-98dd-11e9-8e04-d5bf47a00fa9.png)

With PS1.7.6.0rc1 => It is OK.
![image](https://user-images.githubusercontent.com/16067358/60265258-396ab680-98dd-11e9-9416-ad2f83c30505.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
ping @PierreRambaud 
Thanks!

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/14392

**Comment by PierreRambaud** [comment]
Thanks a lot, a fixed is available here: https://github.com/PrestaShop/ps_facetedsearch/pull/104
