### ISSUE TITLE
Ps_facetedsearch problem with cache and widget system

### ISSUE THREAD

**Issue by iqit-commerce** [PrestaShop/PrestaShop#14423]
**Describe the bug**
When used as widget module is cached wrongly. It stores one cache for all categories. It was ok before 3.x version of module.

**To Reproduce**
1. Enable smarty cache in advanced parametrs
2. use ps_facatedsearch as widget in tpl file instead of hook. Ex {widget name="ps_facetedsearch"}
3. go to frontoffice and visit few categories, you will notice that it is cached same filtering for all, and once you click on some filter it change url to other category(for which facated search is cache)

**Screenshots**
https://snag.gy/xoDhTI.jpg
On screenshot you see that I'm in dresses category but it show filtering cached for it's parent "woman" category

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @iqit-commerce,

I did not manage to reproduce the issue with PS1.7.6.0rc1 and ps_facetedsearch v3.0.5.
I attached a screen record
https://drive.google.com/file/d/10lWIUoO2NW-uIyPdUIODVdR80ImsMBJd/view
Thanks to check and feedback.

**Comment by iqit-commerce** [comment]
@khouloudbelguith 
Category tpl should look like this
{extends file='catalog/listing/product-list.tpl'}

{block name='product_list_header'}
{widget name="ps_facetedsearch"}
    {include file='catalog/_partials/category-header.tpl' listing=$listing category=$category}
{/block}

you did not put widget code in block so it was acutally not visible on frontoffice, als remove facated search from left column hook then in desing > positions

**Comment by khouloudbelguith** [comment]
@iqit-commerce, thanks for your feedback.
Yes, I manage to reproduce the issue with PS1.7.6.0rc1 and PS1.7.5.2 and ps_facetedsearch v3.0.5.
![image](https://user-images.githubusercontent.com/16067358/60354274-cab45880-99c3-11e9-976a-39933119d67c.png)
With ps_facetedsearch v2, we have an exception when we add `{widget name="ps_facetedsearch"}` in a template reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/14423
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
ping @PierreRambaud 
Thanks!

**Comment by iqit-commerce** [comment]
@PierreRambaud and @khouloudbelguith 
I created PR which seems to fix the problem, but please review it
https://github.com/PrestaShop/ps_facetedsearch/pull/105
