### ISSUE TITLE
Faceted search: "regular" attribute displayed as a texture

### ISSUE THREAD

**Issue by glo-www** [PrestaShop/PrestaShop#14488]
I create a new attribute with some values. On the front, the module displays it as if it was a texture, trying to apply a background-image on the "checkbox", but obviously the image does not exist (it is not a texture).

**Additionnal information**

When I switch the front office to english, the problem is not visible anymore...
![Vêtements(2)](https://user-images.githubusercontent.com/406119/60677289-668d0b00-9e81-11e9-9fe4-8affdf5bf4be.png)
![Vêtements(1)](https://user-images.githubusercontent.com/406119/60677291-668d0b00-9e81-11e9-8933-da133e715609.png)

PrestaShop version: 1.7.6 beta
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @glo-www,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0rc1 & PS1.7.5.2 & the ps_facetedsearch v3.0.6.
The BO language is French / the employee language is French
I created an attribute "Attribute type" = Radio buttons.
In the FO => when Fr is selected,
![image](https://user-images.githubusercontent.com/16067358/60678462-73f3c680-9e7c-11e9-8970-a6de93dccb88.png)
When I select another language => There is no problem.

With PS1.7.5.2, I have the same issue with the English language
https://drive.google.com/file/d/1jQWFnTySGQc85Kc9RKXaP9weWm8LQDJj/view
ping @PierreRambaud 
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
With ps_facetedsearch v2.2.0 => OK
Thanks!

**Comment by PierreRambaud** [comment]
Thanks, fixed in https://github.com/PrestaShop/ps_facetedsearch/pull/110
