### ISSUE TITLE
Classic theme should promote code quality and best practices - upgrade and rework

### ISSUE THREAD

**Issue by tlhuillier** [PrestaShop/PrestaShop#14533]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open `.scss` files coming from the classic theme.
I see there is plenty of efforts that are being put on the backend side of Prestashop, but I'm not feeling like this is the same for the front end part.

Yes I know that there has been some pretty good changes like the venue of Webpack, ES6, on the tooling part.

But when I'm looking on files like [checkout.scss](https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/themes/classic/_dev/css/components/checkout.scss), I feel a bit like it's not a really enjoyable environment to work on. Don't take it like an offence, but I think this file for example is full of bad practices:
- `components/checkout.scss` should be something like `pages/checkout.scss` because its everything but a component.
- 39 ID selectors in one file, free CSS
- nesting is sometimes so deep that we can find a Balrog in there
```
...
      &.taxes {
        td {
          text-align: left;
          .value {
            padding-top: 0;
          }
        }
      }
    }
  }
```
- so many combined selectors like its the Guinness book of CSS specificity
```
body#checkout section.checkout-step.-reachable.-complete h1 .step-edit {
```
- empty blocks, because hey, the cart is empty
```
.cart-empty {
  .cart-summary {
  }
}
```
- styling attached to `.js-` classes and style that should really go inside the Atos module
```

.cart-empty {
  .cart-summary {
  }
}
.js-payment-binary {
  display: none;
  .accept-cgv {
    display: none;
  }
  &.disabled {
    opacity: 0.6;
    cursor: not-allowed;

    // A div overlay to prevent using clicking on stuff !
    // not even working on my Chrome 75.0.3770.100 (Official Build) (64-bit)
    &::before {
      content: "";
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      pointer-events: none;
    }
    .accept-cgv {
      display: block;
    }
  }
}
```
And I could continue for a day like this.

All this to tell you how I feel when seeing this .scss code, knowing this had been rewritten from scratch for 1.7.

**Describe the solution you'd like**
*I think like the classic theme should really promote good coding standards, best practices, and would really benefit from a complete cleanup.*
For now, I don't even think like Prestashop themes are a good environment for junior developers to learn html and CSS.

I was positively surprised when the starter theme came out, as it was in my sense a really good move toward code quality. But it's been discontinued.. too bad.

**Comment by ghost** [comment]
@tlhuillier please join to https://github.com/PrestaShop/classic-rocket project and participate in its development :)

**Comment by tlhuillier** [comment]
Hey @PrestaShark 
Your project seems like an interesting initiative, I'll give it a shot.

But still, the Classic theme (being shipped with Prestashop) should be the quality standard on top of which others could rely to take example.

**Comment by khouloudbelguith** [comment]
Hi @tlhuillier,

Thanks for your report.
ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by matks** [comment]
How could we disagree with such a statement 😄 obviously you're right @tlhuillier .

It's true that there is so much work on the backend side that we sometimes forget about the theme 💔 . Also since a lot of people use their own theme, they are more eager to report (and speak about) bugs about the backend logic than the theme.

There's just one thing that will be a blocker: retro-compatibility. Even if there are some useless CSS or IDs around, we cannot remove them because modules/themes rely on them. We'll have to wait for next major PS version (1.8.0.0) to be able to do such a breaking change.

**Comment by tlhuillier** [comment]
Glad to ear that.

1.7 themes not being retro compatible with 1.6, I think those things should have been removed totally since modules needed some updates to work on 1.7 and themes needed to be totally rewritten anyway.

One step toward dropping this compatibility code could be to move everything related to retro-compatibility inside a `shame.scss` [?](https://csswizardry.com/2013/04/shame-css/) or `retro-compatibility.scss` to be able to easily spot them. And the day Prestashop is ready to make another round of breaking changes, simply delete this file.

**Comment by SharakPL** [comment]
@tlhuillier The reason for bad quality of classic theme is simple and quite understandable: it's just bussiness. If classic were good enough less people would consider buying a theme from prestashop. That's fair considering it's free. The only thing I can't understand is why would anyone use **alpha** or even beta packages in production. It's been 1.5 years since stable Bootstrap 4 was released. It's 4.3.1 already and classic theme still uses 4.0.0-alpha.5. That's not even the newest of alphas! 😖

**Comment by tlhuillier** [comment]
@SharakPL 
Good points.

The classic theme being free doesn't mean it shouldn't be exemplary.
When a usual merchant buys a theme on Addons, it's not the code that he will look at, only the FO demo and screenshots anyway.
But for the sake of the community, if we wan't more quality themes (and thus happier merchants), we need to have a solid Classic theme.

**Comment by mickaelandrieu** [comment]
Hi,

> The only thing I can't understand is why would anyone use alpha or even beta packages in production. It's been 1.5 years since stable Bootstrap 4 was released. It's 4.3.1 already and classic theme still uses 4.0.0-alpha.5. That's not even the newest of alphas! confounded

Most of the themes on Addons are already based on the Classic theme, so updating bootstrap 4 to the latest (we all want to do that, believe me) will break **every theme** on the market place first, then will break every website once they will upgrade their shop.

Simply said: the core team can't do that before the next major release *but* you can rely on the community theme  *[classic-rocket](https://github.com/PrestaShop/classic-rocket)* which is mostly up to date regarding bootstrap :)

**Comment by eternoendless** [comment]
First of all, I fully agree with you @tlhuillier. The classic theme has not been receiving enough love -- in part due to the fact that we have had no fulltime front developers in the team for a while now. Please don't hesitate to send pull requests! Just try and make them small so that they can be merged quickly.

@SharakPL I wish it was like that, but it's not. This has been explained several times in Github discussions and is also one of the reasons PrestaShop/classic-rocket is a thing.

The development team in charge of the original 1.7 decided, back in the day, to develop new themes ("classic" for the FO and "new theme" for the BO) using the not-yet-released-at-the-time bootstrap 4. As they tell me, they thought that Bs4 would be final in time for final release of 1.7, and started working with the alphas... with turned out to be a _very bad call_.

Bs4 Alpha 6 was released in January 2017, _after_ initial release of PS 1.7.0 (Nov 2016). Worse, that alpha switched the grid model to flexbox, breaking everything. Since most themes are based on classic (as @mickaelandrieu explained), upgrading Bs4 in classic would break existing themes. So we are stuck.

In PrestaShop 8, we'll be able to switch to a new theme. In the meantime, there's classic-rocket which is basically an improved classic theme.

**Comment by tlhuillier** [comment]
@eternoendless 
Thanks for the clarifications, you made it very clear.

**Comment by SharakPL** [comment]
@eternoendless lack of flexbox is the most negative part of it 😢 I hope it will be proper way in 1.8 with Vue instead jquery for product, cart and order related components.

**Comment by colinegin** [comment]
What do you think of this issue @NeOMakinG ?

**Comment by matks** [comment]
@colinegin Full answer has already been given by @eternoendless and @mickaelandrieu . There is nothing we can do to address these issues on Classic Theme because doing so would break compatibility with all existing themes ... and anger the whole community doing themes for prestashop.

I think we should put this issue in PrestaShop 8 (prestashop next) kanban.

**Comment by colinegin** [comment]
Thanks @matks , i've put it in the dedicated kanban.

**Comment by khalidzuhd** [comment]
I have an idea ... 
You should stop working on classic v1 and move to classic v2 or another name  and build it from scratch with most newest tec....
And More thing ... Best mobile responsive..
Easy to edite... 
Easy css improvement...
Make it 💯% compatible with rtl ... And so on

**Comment by matks** [comment]
> I have an idea ...
> You should stop working on classic v1 and move to classic v2 or another name and build it from scratch with most newest tec....

This would benefit all people that would use v2 as a starting point, but it would leave behind all the people using v1. We cant do that. People trust us to update this v1 theme and we will not let them down 😉 . It's the trust between us, the maintainers, and the community ❤️ 

> Simply said: the core team can't do that before the next major release _but_ you can rely on the community theme _[classic-rocket](https://github.com/PrestaShop/classic-rocket)_ which is mostly up to date regarding bootstrap :)

https://github.com/PrestaShop/classic-rocket is somehow a v2 😉although developed by the community, not us

**Comment by rmelchner** [comment]
Maybe you guys should mention this stuff in the docs as it is very confusing for devs to get into it. Ive spend a couple of hours figuring out the contradictory docs and reasons classic theme is still on bootstrap alpha, fixing the build  process to run with latest Mac OS node versions etc. Maybe just a link and small text to classic-rocket would help the devs new to this topic. Sometimes this is crucial as a dev recommends to the employer wich software they should use and when he sees the deprecated stuff and the docs he wont consider prestashop..

**Comment by matks** [comment]
> Maybe you guys should mention this stuff in the docs as it is very confusing for devs to get into it. Ive spend a couple of hours figuring out the contradictory docs and reasons classic theme is still on bootstrap alpha, fixing the build process to run with latest Mac OS node versions etc. Maybe just a link and small text to classic-rocket would help the devs new to this topic. Sometimes this is crucial as a dev recommends to the employer wich software they should use and when he sees the deprecated stuff and the docs he wont consider prestashop..

Nice idea, I will do it 😄thanks !

**Comment by matks** [comment]
I think this discussion is complete so I close this issue.

**Comment by matks** [comment]
Actually I reopen 😅 this issue goes into the Kanban https://github.com/PrestaShop/PrestaShop/projects/6

**Comment by NeOMakinG** [comment]
@matks I don't know what to do with this issue, we can't rework it as everyone wants, because it would introduce so much BC breaks, this shouldn't go to the kanban tbh...

The only quick solution would be to develop a parallel theme, which is probably what we don't want, the next one is to wait the major version in order to refacto this theme.

wdyt @PrestaShop/prestashop-maintainers ?

**Comment by kpodemski** [comment]
I'm the one of few maintainers of community-theme for 1.6 (it's in PrestaShop organization), give me green light and I'll progress with similar project on 1.7

**Comment by matks** [comment]
> @matks I don't know what to do with this issue, we can't rework it as everyone wants, because it would introduce so much BC breaks

The right solution is to rework the Classic Theme for PS 8.0.0 . So it's a slow long-term solution.

As for a quick solution, we encourage people to create their own Theme base such as [Classic Rocket](https://github.com/prestarocket-agence/classic-rocket) but these must be community-only. 

There are many issues with starting a new Theme for PS 1.7
- it means we have 2 themes to maintain, every change in one Theme must be done in the 2nd (2x review, 2x QA, 2x time)
- we must document properly how to use both: 2x docs, tutos, examples
- if we are consistent, we must make sure native modules are compatible with both : 2x work for native FO modules

Then, when a developer that sells Themes and Modules on addons.prestashop.com he'll wonder what target he should hit. The modern new theme but maybe then the audience he can reach is very small ? Or the old bug-packed theme with hundred of stores already using it ? So we fragment the Theme market for PS 1.7 .

@kpodemski this is the reason why we never started, since Starter Theme, a new FO Theme project. It is actually very expensive for the maintainer team. If you think there is a need and you feel like addressing it, you can start a community-theme for 1.7 😉 you are free of course. But if it is not in the project main scope, no QA or developer time will be assigned to it 😞 .

The maintainance issues can be solved with more developer time but the Theme market fragmentation is bad for community of sellers on Addons 😞

**Comment by fdonnet** [comment]
classic-rocket project seems a little bit dead since end of 2020 and it's sad. 
Only here to say that it can be great to have a new version for 1.7.8, clean, simple, seo oriented etc. As a mini prestashop dev (3 shops online), I always prefer to start with the classic theme. 

A lot of market themes are even worse (maybe 2 or 3 big players with good themes to propose and good practices => exaggeration inside) but a lot of themes are only "make a package with a lot of unecessary modules that will not go up in vs" etc... such a headache... 
So yes +1000 to have a good FO theme to start with, with the next major vs.

**Comment by PierreRambaud** [comment]
I think a lot of frontend developers are waiting for a new theme that includes best practices and is able to be updated :roll_eyes:

**Comment by SharakPL** [comment]
@PierreRambaud Webpack config upgrade would be a good start. It should run on node 14, webpack 4/5 and newest sass. I've been working on my own config, but end up with multiple jquery instances in my files. It's already in `core.js`, right? I can't set it so I could use jquery code but without bundling jquery.

**Comment by NeOMakinG** [comment]
Didn't we update it to be compatible with node 12 (LTS) some months ago? I think yes

But this is a good thing to do as node 14 is now LTS too

**Comment by SharakPL** [comment]
> 
> 
> Didn't we update it to be compatible with node 12 (LTS) some months ago? I think yes
> 
> But this is a good thing to do as node 14 is now LTS too

Actually it does seem to work on Node 14, but...

1. `42 vulnerabilities (18 low, 8 moderate, 15 high, 1 critical)` hardly looks like a good config, especially that it still uses Webpack 2 (last stable is [5.24.x](https://github.com/webpack/webpack/releases))
2. Needs a fix #23560 to enable Windows development
3. Can't be updated because https://github.com/PrestaShop/eslint-config.git requires eslint ^5.4 while theme installs eslint ^6.8

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: prestashop-classic-dev-tools@1.0.0
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.8.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.4.0" from eslint-config-prestashop@0.1.0
npm ERR! node_modules/eslint-config-prestashop
npm ERR!   dev eslint-config-prestashop@"0.1.0" from the root project
```

**Comment by NeOMakinG** [comment]
Updating webpack seems to be a good thing to do yes 😆 

> 3. Can't be updated because https://github.com/PrestaShop/eslint-config.git requires eslint ^5.4 while theme installs eslint ^6.8

What can't be updated?

**Comment by SharakPL** [comment]
> 
> What can't be updated?

`npm update` in /themes/classic/_dev/ throws an error quoted above

**Comment by davidglezz** [comment]
Igor Stępień (@Oksydan) wrote in slack this good compilation of main issues with classic theme:

Hi,
I think it is worth to write it outside of replay to start discussion on my point on view.
1. Let’s start with frameworks - first mistake with classic was using bootstrap 4.0.0 alpha w/o providing updated in later prestashop releases.
With new theme/rework we should make sure that dependencies stay up to date. Bootstrap 5 is not ready yet, still in beta so when it comes to chose framework and bootstrap 5 will be your choice. You have to update it consistent on major releases.
2. Another mistake with bootstrap was overriding classes instead of using scss variables to modify it for our needs. Also classic theme isn’t using enough bootstrap components. Instead it is creating its own - custom radio/checkboxes, flags (could be badges), pagination, breadcrumb etc.
3. We have to provide better css file structure and methodology in theme to make it easier to maintain.
4. We should consider separating css/js files for specific pages ex. checkout, product, listing etc. What we get is reduced TBT and files sizes. Most of servers are using http 2 right now and it is better to provide more but smaller files to improve page load speed.
5. Core.js has its downside and upsides. I don’t like that we are not able to modify it. On the other hand developers can just forget about it and update shop w/o not that much to change in theme.
6. Whole prestashop js events idea is great but there is not enough of events. Model of data that events returns are not consistent, ex. productUpdate: to get reason why productUpdated was triggered we have to create flag with productUpdate event and then we can use it in productUpdated event.
7. It don’t like also that we are using jQueryUi. Library is really huge and we should consider using lighter one. Search bar could use simple jQuery library or our own autocomplete implementation, for filters slider we could us noUiSlider library.
8. For better developers experience we have to update webpack, use latest compilation tools like node-sass 5 and esbuild-loader for better compilation time. We should also provide configuration to work with webpack dev server and HMR to improve development experience while working on theme.
9. About smarty template, there is a lot of repetition. We should use components approach with use of block to extends file and overriding blocks for our needs.
If you are interested I can provide you my starter theme. Most of stuff mentioned above is used in it.

**Comment by SharakPL** [comment]
@davidglezz [node-sass](https://github.com/sass/node-sass) is depreciated so it's best to switch to recommended [sass package](https://github.com/sass/dart-sass)

**Comment by Oksydan** [comment]
@SharakPL you are right, changing to dart-sass is quite easy. Few lines of code in webpack config.

**Comment by matks** [comment]
https://build.prestashop.com/news/new-theme-announce/

**Comment by matks** [comment]
Following the Hummingbird rework I think we can close this issue. Classic theme will not promote code quality and best practices, its heir will !

https://github.com/PrestaShop/theme-refacto/
