### ISSUE TITLE
Wrong place of currency on second language

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#14555]
**Describe the bug**

**To Reproduce**
See screenshots. If I enable second language "kr." moved in front of the price.

**Screenshots**
![3](https://user-images.githubusercontent.com/26626066/60895042-30c29a80-a264-11e9-85fb-8ba618bc9961.png)
![1](https://user-images.githubusercontent.com/26626066/60895044-315b3100-a264-11e9-9979-0faecb6ef79a.png)
![2](https://user-images.githubusercontent.com/26626066/60895046-315b3100-a264-11e9-952b-5e786f61f7f1.png)

**Additionnal information**
PrestaShop version: 1.7.6 & develop
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @MathiasReker,

I tried o import the Denmark pack, In the FO, when English is selected & DKK kr is selected.
I have this:
![image](https://user-images.githubusercontent.com/16067358/60897650-5b125900-a260-11e9-85c6-4a417d64f5e6.png)

What is the exact Language/country did you used during the install?

Thanks!

**Comment by MathiasReker** [comment]
@khouloudbelguith Exacly! Thats the problem. The second language displayed wrong. Danish should be like this format: 1.000,00 kr.

If you install only 1 language then there are no problem. The problem exist from language 2+

**Comment by khouloudbelguith** [comment]
@MathiasReker, thanks for these clarifications.
We will check & feedback.

**Comment by PierreRambaud** [comment]
It's not a bug, when you're running in english, it takes the english currency format, not the danish one.
This mean if you have `$10.00` and you switch to danish currency, it takes the english CLDR currency, and use the danish currency symbol => `kr10.00`

**Comment by PierreRambaud** [comment]
Same if you're in french, you have `25,61 €` and if you switch to USD you have `28,72 $` because it's the French currency format :)

**Comment by MathiasReker** [comment]
@PierreRambaud The price is: `23,90 kr.` and my languege is danish. Then I want to translate my website to english and still show the price in `kr.`. Then it will look like this: `kr.23.90`

**Comment by PierreRambaud** [comment]
This is what I said, if you're in english, you must display currencies in english format :thinking:

**Comment by MathiasReker** [comment]
But what if I want to show everything in `kr.` (DKK)?

**Comment by jolelievre** [comment]
If you try to display with Euros with English language you will see that the € symbol is before the number:

![Capture d’écran 2019-07-09 à 17 25 39](https://user-images.githubusercontent.com/13801017/60901716-b64b4800-a26e-11e9-80ce-e9cb31b0cb82.png)

So this is the expected behavior of the CLDR, if you want more details you can check the english CLDR data in `localization/CLDR/core/common/main/en.xml` which comes from http://cldr.unicode.org/

**Comment by MathiasReker** [comment]
The currency format should be related to the currency and not to the language. Don't you agree? 🤔

**Comment by PierreRambaud** [comment]
No, consider what CLDR do, it's related to a language.

**Comment by jolelievre** [comment]
No it seems logical that it depends on the language If you speak arabic for example, no matter which currency you are paying with you still want the website to be displayed in LTR. Switching to $ doesn't mean you want to switch your website display.

It's the same principle here (at least it seems to be the CLDR unicode point of view), the important is what language and what country you are from. I insist on the country as well, because PrestaShop comes with the en-us language, but you have an override dedicated to Denmark, if you take a look at `localization/CLDR/core/common/main/en_DK.xml` config, you will see that the currency symbol is overriden with `kr.` (although the pattern doesn't change so it still will be on the left of the number).

So you would need the language en_DK to have the behavior you are expecting. Sadly when you look at the language installation select box it is limited (because having 700+ languages would be too complicated).

**Comment by MathiasReker** [comment]
Interesting, I did not know that. 😄 But it sounds legit.

**Comment by MathiasReker** [comment]
Thanks for the explanation ! :)
