### ISSUE TITLE
$allProductsLink links to a 404 page

### ISSUE THREAD

**Issue by ProBackup-nl** [PrestaShop/PrestaShop#14581]
**Describe the bug**
The "All products" link on the homepage return a 404 error message

**To Reproduce**
1. Have `0` 'Categories' and only `2` 'Products'
2. Have 'root' category renamed to a fancy name
3. Set root category 'Displayed=no'
4. The homepage "all products" hyperlink points to "/nl/2-fancy-name"
5. That returns a 404

**Screenshots**
![Categories • `t Zonnehuukske — Coöperatieve zonneweide (in aanbouw)](https://user-images.githubusercontent.com/515451/61005088-c430c400-a367-11e9-9e45-a8b5e12282ef.png)
---
![`t Zonnehuukske — Coöperatieve zonneweide (in aanbouw)](https://user-images.githubusercontent.com/515451/61005684-f262d380-a368-11e9-958f-76eaddb495b6.png)
---
![404 fout](https://user-images.githubusercontent.com/515451/61005769-1a523700-a369-11e9-8ca6-66afd059cff4.png)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2.18

**Comment by khouloudbelguith** [comment]
Hi @ProBackup-nl,

Thanks for your report.
I have the same issue when disabling the "Home" category with PS1.7.5.2 & PS1.7.6.0.
But this is normal behavior, because in this case, `"/nl/2-fancy-name"` the route of the Home category `{id}-{rewrite}`, this category is disabled & not active.
So, this page will not be displayed.
If you enable this category, it will be well displayed.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @ProBackup-nl,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by ProBackup-nl** [comment]
@khouloudbelguith I pitty that this is closed. A tiny webshop with 2 or 3 products doesn't need any categories. IMO: All product should be disabled without any categories. It is still not too well handling of edges cases here.
