### ISSUE TITLE
Problem with clearing cache in BO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14611]
I think cache clearing is not working as it should. When I click on "Clear cache" in BO > Performance, it gives me a white page.

After reloading a page, the page shows up saying, that cache has been cleared, but I think it's not cleared completely.

**Additional information**
PrestaShop version: 1.7.6 final
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Some server disables `putenv` because of security reasons.
Your issue is not a PrestaShop's core bug but most likely a server configuration problem.
We have updated the Symfony version, this new version uses the `Putenv` function
You should contact your host provider, they are the only ones to help you with it.

Thanks to check with your host and feedback.

**Comment by Hlavtox** [comment]
[12-Jul-2019 11:48:51 Europe/Prague] PHP Fatal error:  Uncaught Error: Class 'Tools' not found in /srv/www/eshop-teka.cz/public/new/classes/db/Db.php:794
Stack trace:
#0 /srv/www/eshop-teka.cz/public/new/config/alias.php(47): DbCore->escape('configuration', false)
#1 /srv/www/eshop-teka.cz/public/new/config/alias.php(52): pSQL('configuration')
#2 /srv/www/eshop-teka.cz/public/new/classes/Configuration.php(155): bqSQL('configuration')
#3 /srv/www/eshop-teka.cz/public/new/classes/Configuration.php(209): ConfigurationCore::loadConfiguration()
#4 /srv/www/eshop-teka.cz/public/new/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...')
#5 /srv/www/eshop-teka.cz/public/new/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex()
#6 [internal function]: PrestaShopAutoload->load('Tools')
#7 /srv/www/eshop-teka.cz/public/new/config/config.inc.php(85): spl_autoload_call('Tools')
#8 /srv/www/eshop-teka.cz/public/new/admin258ytdyrs/index.php(40): require('/srv/www/eshop-...')
#9 {main}
  thrown in /srv/www/eshop-teka.cz/public/new/classes/db/Db.php on line 794

**Comment by khouloudbelguith** [comment]
@Hlavtox, seems to be similar to this issue: #11105, is it?

Thanks!

**Comment by JustasBelevicius** [comment]
When is this going to be fixed? My site cannot function. Does enabling `putenv` fix the issue for now? However I might not be able to do that since I am using shared hosting provider. Also `putenv` is not secure, hence it is disabled by default on all php versions, I am aware it is the issue Symphony developers have to tackle.
Any help is highly appreciated

**Comment by JustasBelevicius** [comment]
Although in var/logs latest log file I am getting:
```
*ERROR* 	v1.7.6.0	2019/07/15 - 12:06:16: Link to database cannot be established: SQLSTATE[HY000] [1045] Access denied for user 'swrolt_tseu1'@'localhost' (using password: YES) at line 127 in file classes/db/DbPDO.php
```
I have checked my db information and passwords, and they're correct

**Comment by khouloudbelguith** [comment]
Hi @JustasBelevicius,

We have updated the Symfony version, this new version uses the Putenv function, so you need to enable this option on your server.
>*ERROR* 	v1.7.6.0	2019/07/15 - 12:06:16: Link to database cannot be established: SQLSTATE[HY000] [1045] Access denied for user 'swrolt_tseu1'@'localhost' (using password: YES) at line 127 in file classes/db/DbPDO.php

Your issue is not related to PrestaShop => it is an error on your server.

Try to connect to your MySQL server in command line if you can, `mysql -u MYSQL_USER -p DATABASE_NAME -h DATABASE_HOST` try to connect by replacing values.

Thanks to check & feedback.

**Comment by JustasBelevicius** [comment]
@khouloudbelguith what version of prestashop was it before the updated Symfony version was introduced? Using `putenv` is not secure, and since I cannot enable it due to the security of server and the restrictions of the provider I would better choose to use the older yet more secure and non-crashing version of prestashop.

Although this might not be the problem, I will try to recreate the issue and see if that's actually the case. Apparently after cache clearing some old database information is kept and used (logins mainly) which might be causing my problem.

**Comment by khouloudbelguith** [comment]
@JustasBelevicius, PrestaShop 1.7 was moved To Symfony 3.4 And PHP 5.6.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/

Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 
Did you managed to reproduce this issue ?

**Comment by khouloudbelguith** [comment]
hi @marionf,

No, in my case, it is OK.
https://drive.google.com/file/d/1s6kAaA1RNYw2BKvezG9H_out4Zwqgdl-/view
Thanks!

**Comment by Hlavtox** [comment]
@marionf It doesnt work!

It doesnt do it all the time, but the issue is there.

**Comment by marionf** [comment]
@Hlavtox 
@khouloudbelguith Can't reproduce the issue with the informations provided this why it's closed.
If you still have this issue, maybe you can provide more details to help us to reproduce it.

**Comment by Hlavtox** [comment]
```
[19-Aug-2019 11:33:17 Europe/Prague] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/srv/www/eshop-teka.cz/public/new/var/cache/prod/": rmdir(/srv/www/eshop-teka.cz/public/new/var/cache/prod/): Directory not empty. in /srv/www/eshop-teka.cz/public/new/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180
Stack trace:
#0 /srv/www/eshop-teka.cz/public/new/classes/Tools.php(3430): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /srv/www/eshop-teka.cz/public/new/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
```

```
[19-Aug-2019 11:33:57 Europe/Prague] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/srv/www/eshop-teka.cz/public/new/var/cache/prod/": rmdir(/srv/www/eshop-teka.cz/public/new/var/cache/prod/): Directory not empty. in /srv/www/eshop-teka.cz/public/new/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180
Stack trace:
#0 /srv/www/eshop-teka.cz/public/new/classes/Tools.php(3430): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /srv/www/eshop-teka.cz/public/new/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
```

```
[19-Aug-2019 14:47:50 Europe/Prague] PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/srv/www/eshop-teka.cz/public/new/var/cache/prod/": rmdir(/srv/www/eshop-teka.cz/public/new/var/cache/prod/): Directory not empty. in /srv/www/eshop-teka.cz/public/new/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180
Stack trace:
#0 /srv/www/eshop-teka.cz/public/new/classes/Tools.php(3430): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /srv/www/eshop-teka.cz/public/new/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
```

@marionf @khouloudbelguith Here you go girls.

Our stores are hosted on a server configured specifically for Prestashop, so believe me if I say the bug is there.

**Comment by eternoendless** [comment]
@Hlavtox it looks like it's a permission issue on `/var/cache/prod/`. But the error could be handled better in order to avoid the white page.
