### ISSUE TITLE
Convert Guest to Customer from BO not working

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14639]
**Describe the bug**
Conversion of guest to customer on backoffice -> order view page is not working.

**To Reproduce**
1. Make order as a guest.
2. Go to BO->Orders->Order
3. Click on "Convert guest to customer"
4. Guest is still a guest.

**Additional information**
PrestaShop version: 1.7.6

**Comment by mariem-abid** [comment]
Hi @Hlavtox,

I manage to reproduce the issue with PS:1.7.6.0
I attached a video record.
https://drive.google.com/file/d/1cjdjRzln25uB95buabFjZkbYmvtWia-a/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14673
