### ISSUE TITLE
Template \account.html.twig is not defined   (it's a bug ?)

### ISSUE THREAD

**Issue by fraria76** [PrestaShop/PrestaShop#14663]
Hi everyone,

I have this configuration:

WINDOWS SERVER 2019 with IIS 10
MySQL 8.0.16.0
PHP 7.2.16
PHPMYADMIN 4.9.0.1
Prestashop  1.7.6.0

I performed a new installation and at 23% appear a error message:

1: Template "C:\inetpub\wwwroot\XXXXXX\mails\themes\modern\core\account.html.twig" is not defined.

I specific than before I has Prestashop  v1.7.5.2 (with the same versions of MySQL, PHP, PHPMYADMIN) and the installation it's OK.

Thanks in advace for any help!﻿

![problema](https://user-images.githubusercontent.com/50572903/61229837-2f441700-a729-11e9-9c20-8d510bea10b5.jpg)

**Comment by khouloudbelguith** [comment]
Hi @fraria76,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.0 stable version.
What is the exact Language/country did you used during the install?

Thanks!

**Comment by fraria76** [comment]
Hi khouloudbelguith,

my installation language is ITALIAN.

I tried both to make a NEW installation Prestashop 1.7.6.0 and UPDATE from 1.7.5.2 but I have problems.

If I make a NEW installation Prestashop 1.7.6.0 at 23% appear a error message:    1: Template "C:\inetpub\wwwroot\XXXXXX\mails\themes\modern\core\account.html.twig" is not defined.

If I make a NEW installation Prestashop v1.7.5.2 the installation it's OK, but if I make a UPDATE to 1.7.6.0 appear a error message and If I refresh the page appear:   500 - Internal server error.

On PHPMYADMIN I use these character encoding for the database: utf8_general_ci

Kind regards﻿﻿

![error](https://user-images.githubusercontent.com/50572903/61293798-c619dd80-a7d4-11e9-840e-a59edf741841.jpg)

**Comment by fraria76** [comment]
Hi khouloudbelguith,

I did a complete new installation test of Prestahop 1.7.6.0 with ENGLISH language: the result is the same.

But now when appear the error at 23%
1: Template "C:\inetpub\wwwroot\XXXXXX\mails\themes\modern\core\account.html.twig" is not defined.

I go on directory C:\inetpub\wwwroot\XXXXX\mails\themes and I delete MODERN directory.

The installation completed successfully.

I also send you the print-screen step by step.

Deleting the MODERN directory what does it imply?

Kind regards

![Immagine](https://user-images.githubusercontent.com/50572903/61309509-9da0dc00-a7f2-11e9-96b6-ae15593d55f8.jpg)

**Comment by khouloudbelguith** [comment]
@fraria76, thanks for your feedback.
I did not manage to reproduce the issue with PS1.7.6.0 without removing the modern folder.
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by fraria76** [comment]
Hi khouloudbelguith,

I update you

I did a complete new installation test of Prestahop 1.7.6.0 with ITALIAN language and when appear the problem at 23% I remove the MODERN directory and procede with the installation.

At the end of installation I insert in the final path the MODERN directory and everything seems to work properly.

I have “only” these problem on the back office when I click on:

IMPROVE -> PAYMENT -> PAYMENT METHODS
IMPROVE -> INTERNATIONAL -> TAXES
CONFIGURE -> STORE PARAMETERS -> TRAFFIC & SEO

Appear the message: Server error - 500 - Internal server error -There is a problem that does not allow you to view the desired resource.

If I enabling the Debug Mode and these problems do not occur.

Kind regards

![errore](https://user-images.githubusercontent.com/50572903/61370110-e65ba200-a891-11e9-9cf1-fcc0afd24598.jpg)

**Comment by khouloudbelguith** [comment]
@fraria76, Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
Thanks to check and feedback.

**Comment by fraria76** [comment]
> @fraria76, thanks for your feedback.
> I did not manage to reproduce the issue with PS1.7.6.0 without removing the modern folder.
> We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!



> Could you please try to clear cache manually by deleting all the folder into var/cache (prod & dev).
> Thanks to check and feedback.

yes it worked!

**Comment by fraria76** [comment]
> @fraria76, thanks for your feedback.
> I did not manage to reproduce the issue with PS1.7.6.0 without removing the modern folder.
> We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
> Don't you know how to get this information? Please read the following article:
> http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
> 
> Thanks!

as soon as I can I send you the PHP error log

**Comment by khouloudbelguith** [comment]
@fraria76, so after clearing the cache, the issue is fixed?

Thanks!

**Comment by fraria76** [comment]
> @fraria76, so after clearing the cache, the issue is fixed?
> 
> Thanks!

Yes, it worked! Thanks!

**Comment by khouloudbelguith** [comment]
@fraria76, so can I close the issue?

Thanks!

**Comment by fraria76** [comment]
Hi,

this method (clear cache manually by deleting all the folder into var/cache (prod & dev)) solved the problem only the first time.... now the problem it's still there :-(

**Comment by khouloudbelguith** [comment]
@fraria76, when debug mode is enabled => are there any new exceptions displayed?

Thanks!

**Comment by fraria76** [comment]
Hi khouloudbelguith,

now in MODULE MANAGEMENT I have removed ps_mbo and now without using the DEBUG mode I can access to IMPROVE -> PAYMENT -> PAYMENT METHODS

But remain problems with
IMPROVE -> INTERNATIONAL -> TAXES
CONFIGURE -> STORE PARAMETERS -> TRAFFIC & SEO

Kind regard
![Immagine](https://user-images.githubusercontent.com/50572903/61389915-0c953800-a8ba-11e9-803d-0cf7e6998815.jpg)

**Comment by fraria76** [comment]
Hi khouloudbelguith,

I removed the ps_mbo module and can now log in without problem at:
IMPROVE -> PAYMENT -> PAYMENT METHODS

The problem remains with:
IMPROVE -> INTERNATIONAL -> TAXES
CONFIGURE -> STORE PARAMETERS -> TRAFFIC & SEO

Kind regards
![Immagine](https://user-images.githubusercontent.com/50572903/61390404-0784b880-a8bb-11e9-9470-f18e6a535e42.jpg)

**Comment by khouloudbelguith** [comment]
@fraria76, thanks for your feedback.
I did not manage to reproduce the issue when the mbo module is installed & debug mode is enabled.
I attached a screen record
https://drive.google.com/file/d/1rTT_GhQ9qMqHy0x1bEAUwtvLpJhSCJxS/view
Could you please try to run those command lines to remove the cache:
`rm -fR /Projet_PrestaShop/var/cache/*`

```
php -d memory_limit=-1 ./bin/console cache:clear
php -d memory_limit=-1 ./bin/console cache:clear --env=prod
```
Thanks!

**Comment by fraria76** [comment]
Hi khouloudbelguith,
do these commands work with Microsoft Windows or only with Linux?
If they work with Windows, where should I enter them?
Kind regards

**Comment by khouloudbelguith** [comment]
@fraria76, with windows, you can use the command prompt Cmd: https://en.wikipedia.org/wiki/Command-line_interface#Command_prompt

Thanks!

**Comment by fraria76** [comment]
Hi khouloudbelguith,
even giving the delete cache command the problem remains
Kind regards
![cache](https://user-images.githubusercontent.com/50572903/61465431-58a6b200-a978-11e9-8211-b72ac926f6e1.jpg)

**Comment by fraria76** [comment]
Hi khouloudbelguith,
even giving the delete cache command the problem remains
Kind regards
![cache](https://user-images.githubusercontent.com/50572903/61465661-c5ba4780-a978-11e9-8202-a81939cf7a45.jpg)

P.S.: in PHPMYADMIN I set for the database as Character Encoding "utf8_general_ci". It's correct?

**Comment by khouloudbelguith** [comment]
@fraria76, thanks for your feedback.
In my case, This issue doesn't occur.
Ping @sarahdib could you please try to reproduce the issue.

Thanks!

**Comment by fraria76** [comment]
Hi khouloudbelguith
Hi sarahdib

I redid a new Prestashop 1.7.6.0 installation (same Server, PHP, etc...) and I have equal problem:

IMPROVE -> INTERNATIONAL -> TAXES
CONFIGURE -> STORE PARAMETERS -> TRAFFIC & SEO

Appear the message: Server error - 500 - Internal server error -There is a problem that does not allow you to view the desired resource.

If I enabling the Debug Mode these problems do not occur.

Can I send you the file php.ini for a eventual control?

Kind regards

**Comment by khouloudbelguith** [comment]
@fraria76, Could you please follow this link: https://github.com/PrestaShop/php-ps-info 
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by fraria76** [comment]
Hi khouloudbelguith,

first thank you so much for all the help you are giving me!

Now I have made a VirtualBox virtual machine with my usual configuration:

WINDOWS SERVER 2019
IIS 10
MySQL 8.0.16.0
PHP 7.2.16
PHPMYADMIN 4.9.0.1
Prestashop 1.7.6.0

The result is always the same on the back office when I click on:

IMPROVE -> PAYMENT -> PAYMENT METHODS
IMPROVE -> INTERNATIONAL -> TAXES
CONFIGURE -> STORE PARAMETERS -> TRAFFIC & SEO

But this time does not appear the error "Server error - 500 - Internal server error" but appear a string.



IMPROVE -> PAYMENT -> PAYMENT METHODS

Appear:		PHP Warning:  Use of undefined constant ADMIN_LEGACY_CONTEXT - assumed 'ADMIN_LEGACY_CONTEXT' (this will throw an Error in a future version of PHP) in C:\inetpub\wwwroot\prestashop\modules\ps_mbo\ps_mbo.php on line 320

line 320 is:	if (ADMIN_LEGACY_CONTEXT === true) {



IMPROVE -> INTERNATIONAL -> TAXES
CONFIGURE -> STORE PARAMETERS -> TRAFFIC & SEO

Appear:		PHP Notice:  Undefined index: _route in C:\inetpub\wwwroot\prestashop\src\PrestaShopBundle\Controller\Admin\CommonController.php on line 121

line 121 is:	$routeName = $request->attributes->get('caller_route', $request->attributes->get('caller_parameters', ['_route' => false])['_route']);



I also ran PHP script and I enclose the result (pdf format)

Kind regards

[result PHP script.pdf](https://github.com/PrestaShop/PrestaShop/files/3407929/result.PHP.script.pdf)
![report](https://user-images.githubusercontent.com/50572903/61482419-d8457880-a99a-11e9-8582-fd14436f56d8.JPG)

**Comment by sarahdib** [comment]
Hello @fraria76 

I'm sorry I didn't reproduce.

It's maybe related to your configuration server.

Thank you

**Comment by khouloudbelguith** [comment]
Hi @fraria76,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thanks!

**Comment by fraria76** [comment]
Hi,
OK thanks immensely for all the help and when I find a solution I warn you.
Kind regards

p.s .: you performed the tests on server Linux or Microsoft ?

**Comment by khouloudbelguith** [comment]
@fraria76, in my case, usually I use Server Linux, but in some case, I test with the Microsoft also.

Thanks!

**Comment by fraria76** [comment]
OK thanks, have a nice day!

**Comment by Pirate911** [comment]
> I delete MODERN directory.
It works ..Thanks for the tip.

**Comment by fraria76** [comment]
Hi khouloudbelguith,

I inform you that I solved following the directions of "Alexandr Kamenev" from the prestashop.com forum 
https://www.prestashop.com/forums/topic/997625-back-office-problem-with-prestashop-1760/?tab=comments#comment-3153799

Change line 121 in '/src/PrestaShopBundle/Controller/Admin/CommonController.php' file to:

// $routeName = $request->attributes->get('caller_route', $request->attributes->get('caller_parameters', ['_route' => false])['_route']);
$routeN1 = $request->attributes->get('caller_parameters', ['_route' => false]);
if (!isset($routeN1['_route'])) {
    $routeN1['_route'] = false;
}
$routeName = $request->attributes->get('caller_route', $routeN1['_route']);


Now I don't see the mistake again.
Kind regards

**Comment by matks** [comment]
@fraria76 your suggestion has been merged into the codebase thanks to @Gamesh in https://github.com/PrestaShop/PrestaShop/pull/15906

**Comment by fabiorme** [comment]
hi, I found the same error, during a clean installation, from zero to prestashop
config:
PHP: 7.1.19
Prestashop 1.7.6.1

![presta_err](https://user-images.githubusercontent.com/18003540/67966851-df6c5b80-fc04-11e9-952d-0767e4bb55c9.jpg)

**Comment by khouloudbelguith** [comment]
Hi @fabiorme,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15906 to fix this issue.

Thanks!

**Comment by mvorisek** [comment]
This issue is not resolved with the PR https://github.com/PrestaShop/PrestaShop/pull/15906 . Please reopen.

Currently the installation fails on Windows. I tested latest .zip release, cloned source from git, from latest stable tag, from develop branch. All installation attempts fails no matter if installed from web or from cli.

The only solution was to delete the `mails\themes\modern` directory as advised here - then the installation completes. This issues needs to be confirmed and fixed asap as it affect all new users.

**Comment by Scippy** [comment]
Hi, I ran into the same problem during a clean installation, from zero.
Prestashop ver.1.7.6.5 on Windows IIS with PHP 7.2

**Comment by s427** [comment]
I can confirm that I had the same problem with a clean installation, just today.
Prestashop 1.7.6.5 on Windows 10, running Apache 2.4 and PHP 7.3.

My Apache error log only show those messages during that timeframe:

`[Thu Jun 18 14:28:06.422530 2020] [fcgid:warn] [pid 3832:tid 1252] [client 127.0.0.1:62319] mod_fcgid: stderr: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in W:\\htdocs\\myproject\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php on line 2636, referer: http://hds/myproject/install/index.php`  
`[Thu Jun 18 14:28:06.422530 2020] [fcgid:warn] [pid 3832:tid 1252] [client 127.0.0.1:62319] mod_fcgid: stderr: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in W:\\htdocs\\myproject\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php on line 2665, referer: http://hds/myproject/install/index.php`  
`[Thu Jun 18 14:28:10.821769 2020] [fcgid:warn] [pid 3832:tid 1252] [client 127.0.0.1:62319] mod_fcgid: stderr: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in W:\\htdocs\\myproject\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php on line 2636, referer: http://hds/myproject/install/index.php`  
`[Thu Jun 18 14:28:10.821769 2020] [fcgid:warn] [pid 3832:tid 1252] [client 127.0.0.1:62319] mod_fcgid: stderr: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in W:\\htdocs\\myproject\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php on line 2665, referer: http://hds/myproject/install/index.php`

Deleting the `mails\themes\modern` folder solves the problem. Since I'm not sure how this will impact PS's functionality, I restored it once the installation was finished. Hopefully it will not cause any more bugs...

**Comment by mvorisek** [comment]
@khouloudbelguith verify and reopen

**Comment by matks** [comment]
> I can confirm that I had the same problem with a clean installation, just today.
> Prestashop 1.7.6.5 on Windows 10, running Apache 2.4 and PHP 7.3.
> 
> My Apache error log only show those messages during that timeframe:
> 
> `[Thu Jun 18 14:28:06.422530 2020] [fcgid:warn] [pid 3832:tid 1252] [client 127.0.0.1:62319] mod_fcgid: stderr: PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in W:\\htdocs\\myproject\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php on line 2636, referer: http://hds/myproject/install/index.php`
> `[Thu Jun 18 14:28:06.422530 2020] [fcgid:warn] [pid 3832:tid 1252] [client 127.0.0.1:62319] mod_fcgid: stderr: PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in W:\\htdocs\\myproject\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php on line 2665, referer: http://hds/myproject/install/index.php`
> `[Thu Jun 18 14:28:10.821769 2020] [fcgid:warn] [pid 3832:tid 1252] [client 127.0.0.1:62319] mod_fcgid: stderr: PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in W:\\htdocs\\myproject\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php on line 2636, referer: http://hds/myproject/install/index.php`
> `[Thu Jun 18 14:28:10.821769 2020] [fcgid:warn] [pid 3832:tid 1252] [client 127.0.0.1:62319] mod_fcgid: stderr: PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in W:\\htdocs\\myproject\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\UnitOfWork.php on line 2665, referer: http://hds/myproject/install/index.php`
> 
> Deleting the `mails\themes\modern` folder solves the problem. But I'm not sure how this will impact PS's functionality.

This is not the same issue.

The error messages you have here come from the fact that PrestaShop 1.7.6 does not run with php7.3 . PS 1.7.7 (next version to be released) is compatible with php7.3 but for PS 1.7.6 you must use php7.1 or php7.2

**Comment by s427** [comment]
> This is not the same issue.
> 
> The error messages you have here come from the fact that PrestaShop 1.7.6 does not run with php7.3 . PS 1.7.7 (next version to be released) is compatible with php7.3 but for PS 1.7.6 you must use php7.1 or php7.2

Yes, it is the same issue. Let me clarify:

I only posted the messages visible in my Apache error log to show that _there is nothing else in it_ (for that timeframe). I was not aware that this was related to PHP 7.3 specifically.

__However__, even if I try a clean PS install with PHP 7.2 (same system), the problem remains:

1. the installation fails (`Template "W:\htdocs\myproject\mails\themes\modern\core\account.html.twig" is not defined.`)
2. deleting the `mails\themes\modern` folder allows the installation to continue.

**Comment by mvorisek** [comment]
I also think this bug need to be reopened.

If I remember correctly this bug is related with relative paths use in PrestaShop and with one of ZTS or NTS PHP for Windows (not rembeb which one).

This bug should be fully fixed once migrated to Symfony 4.0+ where relative paths for templates are not longer supported.

**Comment by DiegoStefanon** [comment]
Same error to me, ..."\mails\themes\modern\core\account.html.twig" is not defined."
 MODERN folder deletion seems to solve the problem...

A lot of users with this problem ... 
hehehe   it's a joke ? ;-) it seems to me

**Comment by despokd** [comment]
> 
> 
> Same error to me, ..."\mails\themes\modern\core\account.html.twig" is not defined."
> MODERN folder deletion seems to solve the problem...
> 
> A lot of users with this problem ...
> hehehe it's a joke ? ;-) it seems to me

Same here. Just deleted and recreated the folders "mails\themes\modern\core" and "mails\themes\modern\modules" after installation.

OS: Windows NT build 9600 (Windows Server 2012 R2 Standard Edition) AMD64 
Software: Microsoft-IIS/8.5 
PHP: 7.0.0
MySQL: 5.7.12-log 
PrestaShop: 1.7.6.8

**Comment by mvorisek** [comment]
I think it is https://github.com/PrestaShop/PrestaShop/issues/20709

@despokd and @DiegoStefanon , please describe here your enviroment (OS, PHP version (copy result of `php -v`) and PrestaShop version)

**Comment by keyamasabaya** [comment]
Same error for me. Tested on PHP 7.2.x, 7.3.x, 7.4.x. Nothing worked, but
PHP 7.1.1 works !

**Comment by matks** [comment]
Hi everybody,

If you have a reproductible issue (= a scenario that we can follow, with detailed settings, requirements, steps-by-steps instructions that can lead us to reproduce the error mentioned) please create a new issue, it will be a lot of easier to work on it. This issue has a long history and we tried many times to reproduce it without success. Reopening it would be a bad idea, because it would produce a long-term issue with multiple different inputs. It would be very ambiguous and hard to work on.

Please open a new issue if you have a reproductible item 😉 it will be a lot easier for all of us.

Also

> OS: Windows NT build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
> Software: Microsoft-IIS/8.5
> PHP: 7.0.0
> MySQL: 5.7.12-log
> PrestaShop: 1.7.6.8

PrestaShop latest version is not compatible, as far as I know, with Microsoft-IIS.

Some parts of it might be fine, but nothing has been implemented or tested for this platform so I'm quite sure there is no 100% compatibility with Microsoft-IIS.

**Comment by mvorisek** [comment]
@matks I think it is easy to reproduce, please retry with the following configuration:
- Windows 10 (but 7 or Server 2012-2020 should work the same)
- PHP 7.3 (but 7.2 - 7.4 should work the same)
- NTS build (TS build resolves paths a little bit differently - see https://bugs.php.net/bug.php?id=78939)

I am very sure it is related with https://github.com/PrestaShop/PrestaShop/issues/20709 which I backtraced to the NTS/TS issue. Please reproduce and look how template paths are passed. As far as I remember, PrestaShop was passing paths in format that is even not supported by never Twig or Symfony libs, I do not remember exactly... But it is an real issue as it prevents PrestaShop to install, can be reproduced and can/must be fixed in PrestaShop.

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

As commented here: https://github.com/PrestaShop/PrestaShop/issues/16736#issuecomment-564922095
it is ok in my case.
This issue is currently closed, can you open a new one with more information about your configuration.

Thanks!

**Comment by mvorisek** [comment]
@khouloudbelguith of course not, because I belive it is https://github.com/PrestaShop/PrestaShop/issues/20709 which is open and you was able to reproduce as well. It only needs to be assigned and fixed :)
