### ISSUE TITLE
Upgrade 1.7.6 Error

### ISSUE THREAD

**Issue by UMTR** [PrestaShop/PrestaShop#14667]
I tried to upgrade Prestashop 1.7.5.2
to Prestashop 1.7.6
PHP Version 7.0.33
Software Version Apache

After upgrade I could view home page and catalog pages but when I tried to view a product page, I would get the following shown in Debug mode:

"Fatal error: Access level to ProductController::$quantity_discounts must be protected (as in class ProductControllerCore) or weaker in /override/controllers/front/ProductController.php on line 262"

I went and viewed the file and line 262 is the last line in the file and only shows the symbol  } 

I disabled all third party modules and still wouldn't work. I had to do a rollback to get my site back up and running.

Any help would be appreciated.

Thank You

**Comment by khouloudbelguith** [comment]
Hi @UMTR,

Thanks for your report.
You have some issues with an override of your file `ProductController`.
>`/override/controllers/front/ProductController.php`

This override is not compatible with PS1.7.6.0, if it is added by a module, you need to check the module author about this issue.
For a quick fix, you need to rename this file and clear cache manually by deleting all the folder into var/cache (prod & dev).
Your issue is not a PrestaShop's core bug but a customization problem.

I close the issue, feel free to open a new one when needed.

Thanks!
