### ISSUE TITLE
Backoffice quick search - email / customer view redirect to customer page

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#14672]
I noticed that when using the BO search for a customers name or on email adres. After finding the result and clicking on the found customer. When clicking on view, it doesn't open the page with the customer, but redirects to the customer page with all customers where you have to look once again for the customer your searching for. This was not the case in previous versions

PrestaShop version:1.7.6
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @01park,

I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1vE4EEX2cdDq3aN-frkaSFQ4Bbnch59wt/view
Thanks to check & feedback.

**Comment by 01park** [comment]
Hi,

Sorry, I probably was not clear

<img width="1292" alt="Screenshot 2019-07-16 at 10 57 33" src="https://user-images.githubusercontent.com/46492443/61285332-a7a5e900-a7b8-11e9-9850-a41bdb78c1ee.png">


Im talking about this search option

**Comment by 01park** [comment]
<img width="1789" alt="Screenshot 2019-07-16 at 11 00 10" src="https://user-images.githubusercontent.com/46492443/61285772-74178e80-a7b9-11e9-85c0-479a22bac909.png">

<img width="1784" alt="Screenshot 2019-07-16 at 11 00 35" src="https://user-images.githubusercontent.com/46492443/61285844-8d203f80-a7b9-11e9-9b2b-6f58c44f5b29.png">

<img width="1752" alt="Screenshot 2019-07-16 at 11 01 25" src="https://user-images.githubusercontent.com/46492443/61285849-901b3000-a7b9-11e9-9020-cf71bfe43f55.png">

**Comment by khouloudbelguith** [comment]
@01park, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.0.
After searching in the BO => click on the "View" button we are redirected to Customer Page instead of the Customer details page.
https://drive.google.com/file/d/1ISksNunvQkZDfFqe2WdsBpXUL5DvyU4p/view
In the PS1.7.5.2 => OK
https://drive.google.com/file/d/1JrgQjayALhSAUngINMfcbsZvyyDMThCH/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
