### ISSUE TITLE
issue with texture property in ps_facetedsearch

### ISSUE THREAD

**Issue by monparaashvin** [PrestaShop/PrestaShop#14677]
If attribute is set with texture image, it is not display texture image in facet search.

**Comment by khouloudbelguith** [comment]
Hi @monparaashvin,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 & the ps_facetedsearch v3.1.0 & ps_facetedsearch v2.2.1.
![image](https://user-images.githubusercontent.com/16067358/61290179-243dc500-a7c3-11e9-885c-12508d814ffe.png)
https://drive.google.com/file/d/1zFVdATMBoasn4DOSU_AKvagvHvU80LB6/view
With PS1.7.5.1 ps_facetedsearch v2.2.1 / ps_facetedsearch v3.1.0 => OK
![image](https://user-images.githubusercontent.com/16067358/61290239-52bba000-a7c3-11e9-9f84-2b8ed2a2db7a.png)

https://drive.google.com/file/d/1kF94fhPc4H-cJrZG2bioLbxeJ_8cKNl0/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

Ping @PierreRambaud

**Comment by marionf** [comment]
@khouloudbelguith 
I can't reproduce with 1.7.6.0 and faceted search v.3.1.0

![capture d'écran_1764](https://user-images.githubusercontent.com/13449658/61354704-09c32480-a873-11e9-9b5b-5e7cc35e05f9.png)

**Comment by marionf** [comment]
@sarahdib Can you try to reproduce ?

**Comment by sarahdib** [comment]
@marionf @khouloudbelguith 

I didn't manage to reproduce 
![image](https://user-images.githubusercontent.com/3034677/61373448-26268780-a89a-11e9-81c1-aa80cfc985e8.png)
@monparaashvin can you try to rebuild all indexes, attribut and clear the module cache ?
![image](https://user-images.githubusercontent.com/3034677/61373682-ba90ea00-a89a-11e9-8578-560babd53876.png)

**Comment by PierreRambaud** [comment]
Fixed in https://github.com/PrestaShop/ps_facetedsearch/pull/114
