### ISSUE TITLE
Button erase all doesn't work for logs & email pages

### ISSUE THREAD

**Issue by Stephane1874** [PrestaShop/PrestaShop#14686]
**Describe the bug**

Hello the team,

Go to the advanced settings page> logs, tried to delete the logs, the button does not work.

**To Reproduce**
1. Go to advanced settings > logs
2. Click on Delete all
3. See error

**Screenshots**
![supprimer](https://user-images.githubusercontent.com/46202635/61301979-4cd6b680-a7e5-11e9-937c-df6853e94b9f.PNG)

**Additional information**
PrestaShop version: 1.7.6
PHP version: 7.1.3

**Comment by khouloudbelguith** [comment]
Hi @Stephane1874,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 fresh install & after upgrade from PS1.7.5.
https://drive.google.com/file/d/1kRxIzVAU3WIKNYQ5dxY-wz-sCtMn64yF/view
In the PS1.7.5.1 => OK
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
Same issue on email page, erase all button doesn't work
But if you select all and delete with bulk action it's working

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/14701

**Comment by arafatx** [comment]
This issue came back in 1.7.8.0. I will open a new issue.
