### ISSUE TITLE
Attempted to call an undefined method named "getLocale" of class "Language".

### ISSUE THREAD

**Issue by sas-adilis** [PrestaShop/PrestaShop#14697]
HI

This morning, 
Surprise my shop is not working with this issue, no reason why.

**Describe the bug**
Attempted to call an undefined method named "getLocale" of class "Language".
Did you mean to call "getLocaleByIso"?

(1/1) UndefinedMethodExceptionAttempted to call an undefined method named "getLocale" of class "Language".Did you mean to call "getLocaleByIso"?
--
in Controller.php line 188
at ControllerCore->init()in AdminController.php line 2789
at AdminControllerCore->init()in Controller.php line 272
at ControllerCore->run()in Dispatcher.php line 515
at DispatcherCore->dispatch()in index.php line 97

**Additional information**
PrestaShop version: 1.7.6
PHP version: 5.7.1

**Comment by jolelievre** [comment]
Hi @sas-adilis,
it's weird because this function does exist https://github.com/PrestaShop/PrestaShop/blob/bd01df4b896d04f33ea75a79704a3625eb6fd60f/classes/Language.php#L1488

Maybe you have an override (either from your `override` folder, or from a theme/module) that doesn't extend `LanguageCore` and does implement this method
