### ISSUE TITLE
BO | Products listing page empty after deleting products in bulk

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14713]
#### Describe the bug

When you remove all the products from the second or third page, a blank page will appear with an alert asking to add some products.

#### Expected behavior

To be redirected to the first page

#### Steps To Reproduce
1. Make at least 41 products.
2. Go to Admin > Catalog > Products
3. Set paging to 20.
4. Go to third page.
5. Select the product > Delete.
6. See empty page saying to add some products.
 
It should stay on the first page

**Screenshots**

https://drive.google.com/file/d/1MAUgxvjNUZ8AN_MkOqEwhPY-czJhGZ_B/view

#### Additional information

- PrestaShop version: 1.7.6.0 & 1.7.7.3
- PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
I have the same issue with PS1.7.5.2 & PS1.7.6.0.
https://drive.google.com/file/d/1MAUgxvjNUZ8AN_MkOqEwhPY-czJhGZ_B/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related: #9612

**Comment by Hlavtox** [comment]
@khouloudbelguith Fixed on v2 page maybe?

**Comment by florine2623** [comment]
Fixed on 8.1.x.

https://github.com/PrestaShop/PrestaShop/assets/16019289/c7ffea41-3791-41c7-bc17-7db3e0073437

I'm closing the issue.
