### ISSUE TITLE
1.6 | Cookie->Viewed gets long => unable to add anything to cart

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#14751]
_I don't know if you even fix anything for 1.6._

Finally found the source of a serious bug we have been facing for a year or longer.

When you browse a store long enough, 'viewed' value in cookie (a list of IDs of the product visited) get so long, that the browser refuses to set the cookie, because it's longer than 4096 characters.

**You can't add anything to cart.** You click add to cart, popup gets shown, you go to another page and page is empty.

It's get fixed by clearing the cookie and starting as a fresh customer.

I really don't want to even think about how many customers we have lost due to this. :-(

**Additional information**
PrestaShop version: 1.6.1.23
Viewed module is off.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be, that’s why I close it.

**Comment by khouloudbelguith** [comment]
Please follow this link: http://build.prestashop.com/news/1.6.1.x-what-s-next/

**Comment by Hlavtox** [comment]
@khouloudbelguith Do you consider unablity to use a shop as a not critical bug???

@marionf
