### ISSUE TITLE
Error after filtering date in error logs

### ISSUE THREAD

**Issue by ChineseNorris** [PrestaShop/PrestaShop#14785]
**Describe the bug**
After filtering the error log in the back office I get the following error (debug mode enabled)

An exception occurred while executing 'SELECT l.*, e.email, CONCAT(e.firstname, ' ', e.lastname) as employee FROM ps_log l LEFT JOIN ps_employee e ON l.id_employee = e.id_employee WHERE (object_type LIKE :object_type) AND (l.date_add BETWEEN :date_from AND :date_to) ORDER BY id_log desc LIMIT 20 OFFSET 0' with params ["2019-07-19", "2019-07-19"]:

Value for :object_type not found in params array. Params array key should be "object_type"

**To Reproduce**
1. Go to BO/Advanced parameters/error logs
2. Click on Date range and click filter
3. See error

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ChineseNorris,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 & PS1.7.5.2 when debug mode enabled.
I tried to make a filter by two fields => **Date** + another field => the exception will be displayed.

Filtering by only one field => OK
![image](https://user-images.githubusercontent.com/16067358/61616999-c517fe80-ac61-11e9-923b-c021bcbe8f67.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by ChineseNorris** [comment]
Hi @khouloudbelguith ,

thank you for reproducing the issue, I'm trying to clear at least the filter but without success, I've tried using another account to get the method for resetting the filter but I get error 405 "Method not allowed".

I need to reset the filter first and then I'll try to find a solution for the bug.

Regards

**Comment by matks** [comment]
We need to fix this bug _and_ add Behat tests to make sure it does not come back 😄

**Comment by 01park** [comment]
I applied the fixed files and the error is gone, but when I want to filter an employee on employee number or name, I get no results for a selected date.
