### ISSUE TITLE
Cannot enable Geolocation by IP address

### ISSUE THREAD

**Issue by fachies** [PrestaShop/PrestaShop#14829]
**Describe the bug**
I cannot enable Geolocation by IP address.

**To Reproduce**
When I go to Prefereces/Geolocation,
the page tells me download a file into my server:
![image](https://user-images.githubusercontent.com/496830/61716496-941df380-ad5f-11e9-9545-8edce071e71e.png)

When I click to the link to download the file, I see the link is broken:
![image](https://user-images.githubusercontent.com/496830/61716523-a304a600-ad5f-11e9-880f-d3b64424db2c.png)

**Screenshots**

**Additional information**
PrestaShop version: 1.6.1.5
PHP version: 5.5.38

**Comment by khouloudbelguith** [comment]
@fachies, I did not manage to reproduce the issue with PS1.7.6.0.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
