### ISSUE TITLE
Bug - strange symbols in the name of items (block viewed products)

### ISSUE THREAD

**Issue by q555** [PrestaShop/PrestaShop#14853]
strange symbols in the name of items http://prnt.sc/of5fkx
 
The issue comes directly from "block viewed products" module which is a default prestashop one.
 

**Additional information**
PrestaShop version: 1.6.1.12

**Comment by khouloudbelguith** [comment]
Hi @q555,

I did not manage to reproduce the issue with PS1.7.6.0 and ps_viewedproduct v1.2.1.
![viewed](https://user-images.githubusercontent.com/16067358/61937254-5353f380-af86-11e9-9b8c-1e79ff4d8cee.png)

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks
