### ISSUE TITLE
How to migrate from version 1.4.6.2 to recent version

### ISSUE THREAD

**Issue by Caro29** [PrestaShop/PrestaShop#14875]
Hello,
We have a old version of Prestashop 1.4.6.2 and we want to migrate to a recent version 1.6 for example.
First we have tried to import our project locally but we have some errors. We think it is a problem of compatibily of our Xampp which is recent.
After we have tried to import our database locally and to create a new prestashop project version 1.6.1.24 and to connect the old database with the new project. But we have several errors about the queries.
So we don't know how to solve our problem. We think it is dangerous to update Prestashop on our server directly but we didn't manage to import our project locally.
Do you have some advice for us please?

**Comment by khouloudbelguith** [comment]
Hi @Caro29,

You can use the 1-click upgrade module v1.6.1.8 to make an upgrade from 1.4 to 1.6 as described here: https://addons.prestashop.com/en/data-migration-backup/5496-.html
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

PS: 
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.

Thanks!

**Comment by Caro29** [comment]
Thank you for your response. But our problem is that we didn't manage to copy our files locally so we can't test the upgrade.

**Comment by khouloudbelguith** [comment]
@Caro29, for your safety!
You need to make a back up of your shop.

Thanks!
