### ISSUE TITLE
Remaining quantities on the product page take into account product already in cart

### ISSUE THREAD

**Issue by MockoB** [PrestaShop/PrestaShop#14880]
**Describe the bug**
I can't manage to display the quantities on the product page.

**To Reproduce**
1. Set in shop parameters/product settings/display remaining quantities when the quantity is lower than/

After setting the desired number there is just label telling customers there are **last items in stock** and no remaining quantities displayed.

Maybe there is setting I can't find yet ...

PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @MockoB,

You need to navigate to your BO => Shop Parameters => Product Settings => Enable the option "Display available quantities on the product page".
![image](https://user-images.githubusercontent.com/16067358/62010418-5acff400-b162-11e9-8fb7-4c086d5c65be.png)
Thanks to check & feedback.

**Comment by MockoB** [comment]
@khouloudbelguith that's exactly what I did and the only message I get is "last items in stock" and no remaining items as set in the settings.

Another thing I noticed. If product has combinations, when I choose a combination with low quantities there is no warning message telling there are last quantities. The message is shown just for the default combination and not the others. The only way to show it for the other product combinations is when changing the desired quantity, once the threshold is reached, the message "there are not enough products in stock" is showed.

**Comment by khouloudbelguith** [comment]
@MockoB, in the product page, Product details page => In stock field is not displayed?
![image](https://user-images.githubusercontent.com/16067358/62138854-4154b680-b2e0-11e9-9aef-de3a6db44ee1.png)

Thanks!

**Comment by MockoB** [comment]
@khouloudbelguith I would never suggest the available quantities will be hidden behind a closed tab! Never mind, there is still a bug. 
Look at the screenshot I set 3 items remaining for the default combination. 
When the default combination is chosen it shows the remaining quantities are: 1 piece.

https://imgur.com/jaV43MZ

https://imgur.com/stKrq53

**Comment by MockoB** [comment]
I just saw the remaining quantities are shown even when I set to be shown only if they are lower than 4.

**Comment by khouloudbelguith** [comment]
@MockoB, I did not manage to reproduce the issue with PS1.7.6.0.
I attached a screen record
https://drive.google.com/file/d/1S_7EoTJgt28Rh0RoHSeU-b5kRxkcESNj/view
Thanks to check & feedback.

**Comment by MockoB** [comment]
@khouloudbelguith the only issue I got was I can't view the items count, but more we continue to dig, more bugs I find. 
Look at the attached video, it's really strange that you can't reproduce the issue, but one thing I see in your video is: You set to display the remaining quantities when they are below 3, but you can also view the items count of combinations with more than 3 items available. In your video I think you  display the count of combination with 300 pieces available.

https://drive.google.com/file/d/1Zk2UQNpjjzkrVb-nyoQpkHEpDJxJqAR5/view?usp=sharing

**Comment by khouloudbelguith** [comment]
@MockoB, could you please try to empty your cart before, because I think, you have 2 products of the first combination in your cart.

Thanks!

**Comment by MockoB** [comment]
@khouloudbelguith you are right! But in no way, added to cart products shouldn't reflect product quantities.
And what about the product combinations with more than 3 items remaining? I don't think their quantities should be displayed, as set in the settings. 

Thanks!

**Comment by khouloudbelguith** [comment]
@MockoB,

>But in no way, added to cart products shouldn't reflect product quantities.

I'm a customer => I have 3 products in stock => I add two products to the cart => the stock is increasing from 3 to 1. If I delete my cart => quantity remains.

1. 

![image](https://user-images.githubusercontent.com/16067358/62221882-5433bd80-b3aa-11e9-8014-f81fe0d19fb4.png)
2. 

![image](https://user-images.githubusercontent.com/16067358/62221985-7a595d80-b3aa-11e9-9262-fa5beb838c04.png)
3. 

![image](https://user-images.githubusercontent.com/16067358/62222113-b2f93700-b3aa-11e9-89fd-0aa75b6d7645.png)

**Comment by MockoB** [comment]
@khouloudbelguith there is logic yes.
But what if, I add to cart 3 products and forget about it (like I did) and I see a message telling me that the main product I'm on that page for, is not available! I will definitely leave that shop and won't buy anything.
Even more, when I see a message telling me there are no products in stock I will decide that even those in my cart aren't available.
I think that 0 quantities should be displayed only if they are physically out of stock, and not in someones cart.

I think it is wrong to tell a customer that desired products are out of stock when he adds them to the cart.

Is it just for the current customer or every customer on the shop sees same message when someone adds product to the cart? Because I'm already worried if I have to fix my quantities when someone fills a cart and then leave the site without buying.

**Comment by khouloudbelguith** [comment]
@MockoB, to disable this option "Display remaining quantities when the quantity is lower than", you need just to set to "0" to disable this feature.
@MockoB, for example in stock we have 3 products.
Customer1 add two products to the cart => he can see in stock only 1.
Customer2 can see 3 products in the stock

the quantity from the back office is changed only if one of the customers bought those products & not only added them to the cart.

Thanks!

**Comment by MockoB** [comment]
Thanks @khouloudbelguith , but I believe customer should be able to add to the cart the last items indefinitely times, it is wrong to display a message telling customer that there are no products left. I never met such behaviour on any other site.

Speaking as a customer, it happened to me many times to enter a site today, fill a cart and leave it. When I'm back 2 weeks later, I usually browse same products and add them for second or third time to the cart, because I never think to check if I already added that product to the cart. If I see a message telling me there are no products left I will definitely leave! It's not just me, I'm pretty sure.

Giving you real life example. I am selling unique products, every product has 1 piece each, they are all look a like, just differ in sizes. It is not possible for the customer who comes back after 2 weeks to compare all the products in the cart with the rest in the site if he needs to add more. He will always see there are not available quantities and he will never know that those are in his cart and not sold during the 2 weeks period... I believe you get the point.

Please contact the UX team to talk the issue, or just ask some merchants or customers what they think.

**Comment by khouloudbelguith** [comment]
@MockoB, 
>but I believe customer should be able to add to the cart the last items indefinitely times, it is wrong to display a message telling customer that there are no products left. I never met such behaviour on any other site.

this is just an alert to indicate that these are the latest products in stock to encourage customers to buy it before they will not be available.
You can disable this feature as I said previously.

>Speaking as a customer, it happened to me many times to enter a site today, fill a cart and leave it. When I'm back 2 weeks later, I usually browse same products and add them for second or third time to the cart, because I never think to check if I already added that product to the cart. If I see a message telling me there are no products left I will definitely leave! It's not just me, I'm pretty sure.

In the BO => Shop Parameters => Customer Settings => "Re-display cart at login"' is enabled?


Thanks!

**Comment by MockoB** [comment]
> this is just an alert to indicate that these are the latest products in stock to encourage customers to buy it before they will not be available.
You can disable this feature as I said previously.

No it's not just an alert, it's show stopper! Even when I disable the available quantities display (which I need), there is still a message telling me there are no more items available and I am not able to add the product to the cart (assuming I'm not aware it is already in the cart).

> In the BO => Shop Parameters => Customer Settings => "Re-display cart at login"' is enabled?

No it is not, but it is useless in my case. 
Example:
Overall 98 products with same picture and with quantities = 1 each, in one category

1. Ring 12x13x5mm.
2. Ring 13x12x5mm.
3. Ring 5x13x12mm.
4. Ring 5x12x13mm.
5. Ring 13x5x12mm.
.
.
.

You already added 67 of those products to the cart, you get back 2 weeks later. Me as a merchant enabled that feature to re-display the shopping cart (which I did only because I know  prestashop's behaviour, not because I need it or like it), You as a customer look at the cart, remember all those 87 items with almost identical names and same picture. Then you decide to add another 20. Do you believe you will remember which exact product pages to enter, which will have quantity, because all other products will show you "no stock available" ... 
I don't think you will have a chance to remember all those products even if they were with different images and names...

Please give me one site example using such behaviour. I agree there has to be message informing customers there are last items left, but adding items to the cart shouldn't reflect the quantities.

**Comment by khouloudbelguith** [comment]
@MockoB, thanks for your feedback.
>but adding items to the cart shouldn't reflect the quantities.

I don't agree with you because this is will be confusing for the customer.
Ping @marionf, @colinegin what do you think?

Thanks!

**Comment by MockoB** [comment]
Thanks but I’m at the opposite opinion.

The customer will not be allowed to add to the cart more items than the real stock if it is made without reflecting the quantities. Telling customer there is no stock once the product is added to the cart is what’s confusing. I believe it’s not only me, but let’s see what others think. Please, really show me other platform or website where it is made that way.

All the best!

**Comment by marionf** [comment]
Hello @MockoB 

Remaining quantities on the product page takes into account what is already in your cart because you can't add to your cart more product than in stock.
So, you have 300 products in stock.
You add 100 products to your cart
It shows you only 200 products remaining because you can't add more than 200 in your cart.
It's the remaining quantity that you can add to your cart.

It will be not logical to display for example remaining quantity: 300 if you can add only 200 products in your cart because 100 are already in.

**Comment by MockoB** [comment]
Hi @marionf,
I will not be able to add to my cart more than 300 pieces, even if it doesn't change the remaining quantities. There will be appropriate message telling me there is not enough stock, or showing the available quantities on appropriate place on the product page, like it was in older PS versions, not in a tab. The current situation could lead only to confusion. 

It would be more logical the customer to know every moment what the available quantities are. Not checking his cart how many are already there and then go back to the product page check how many are left. And to check it in the additional tab, assuming the merchant enabled the remaining quantities feature. 

As a customer, when I see a message no more products in stock I will definitely find those on other place!

As a merchant I am selling unique products 1 piece each. Showing message to my customers, that the product is not available once they add it to the cart is more than frustrating.

As I asked couple of times already, please give me an example with other site or platform, where adding products to the cart is lowering quantities. I know you may believe it is PS feature and you put an efforts to make it this way, but it is not the right way. I believe few merchants are aware of this behaviour otherwise all would object it.

Regards, 
Moskov

**Comment by marionf** [comment]
> showing the available quantities on appropriate place on the product page, like it was in older PS versions, not in a tab

I am agree with you, it's not enough put forward, we can improve this.
I just created an issue for that: https://github.com/PrestaShop/PrestaShop/issues/15029

> As a customer, when I see a message no more products in stock I will definitely find those on other place!

As a customer when I see that there are already products in my cart, I check what it is.

Furthermore, you can use a module to [relaunch your customers by email when they have an abandoned cart ](https://addons.prestashop.com/en/remarketing-shopping-cart-abandonment/16535-abandoned-cart-reminder-pro.html). In the email sent to the customer, the products in the cart are displayed (so they know which they are) and the link redirect directly your customers to the cart (not to the product page).

You can also disable the option "Redisplay cart after customer login"

> As I asked couple of times already, please give me an example with other site or platform, where adding products to the cart is lowering quantities.

Please, take a look at the video below: 1 product in stock on the product page, I have already this product in my cart & when I try to add it again to the cart, it says product added to cart (but this is not true as I still have 1 product in my cart and not 2). 
https://drive.google.com/file/d/1OJKZahV_YfQw8BLcxJipQLEbuaOLtYgZ/view?usp=sharing
It's frustrating because even if I see that there is only one and I know that I have one in the basket, I am left with the hope that I can have more because I can click on add to the basket and furthermore it tells me that the item has been successfully added to the cart while it is not.

**Comment by MockoB** [comment]
Thanks for sharing your point of view @marionf
But when you enter a product page and you see there aren’t available quantities, the logic behaviour is not to check if the product is already in your cart. When it’s told there is no stock, it means just that. Especially when there is nothing informing you the last quantities are all in your cart as having availability field in the cart page telling the same.

You have to agree if there are 50 or even more similar products in your cart you can’t remember all, especially with all their quantities added. It could be applicable if you are selling washing machines or TVs, most probably I will add just one product in my cart and I will remember it.
Giving you an example: i am AliExpress customer, I regularly browse their site when I have nothing to do, but not finishing my orders right away, maybe once a month or two. Currently I got more than 80products in my cart, do you think that every time I’m using their app, I check all those products in the cart? Sure I don’t, I don’t have that much free time. I’m just browsing their catalog and it happens often to add same products more than once or twice.

Thanks for the video, but no one is adding one by one products to the cart. If I need 2 and I see remaining stock 2, I will add 2 pieces in my cart,  no matter I previously added 1 piece. And that’s the right logic, we don’t have to make the customer thinking or browsing additional pages and calculating it’s bad ux. If someone thinks like me (maybe wrongly cultivated behaviour from years online shopping), he could easily buy 3 pieces instead 2 and that could lead to troubles for the merchants. Please ask yourself a question, if that’s the right behaviour why no one else is using it? You (prestashop team) don’t have to reinvent the wheel, just follow the best practices others use. Or PLEASE give a chance to merchants to use what suits better for them, by adding an option to select appropriate behaviour in the back office.

Thanks for the patience reading everything and answering my questions.

All the best!
Moskov

**Comment by Alexandr-Vall** [comment]
U menya tochno tokaya-zhe problema.
U pochti vse tovary v kollichestve 1 shtuka
Pokupateli postoyanno sprashivayut - yest' etot tovar v nalichii ili net posle dobavleniya yego v korzinu, no eto postoyannyye pokupateli. A kto v pervyy raz zashel v moy magazin dobavil tovar v korzinu, a yemu srazu soobdeniye, chto dannogo tovara net v nalichii. Im ne otpravish' soobshcheniye - "ostalsya tovar v korzine", potomu-chto on yeshcho ne ostavil svoy ye-mayl. Eto ne obychnyy magazin, gde prodavets mozhet stoyat' ryadom s pokupatelem i yemu ob"yasnit' osobennosti raschota kollichestva tovara.
Pereshel na 1.7.5.2 s 1.5.6 tam takikh voprosov u pokupateley ne voznikalo, a seychas pochti kazhdyy den' obrashchayutsya s voprosom  o nalichii tovara.
Eto bol'shaya problema, osobenno v magazinakh tovarom v kollichestve 1 sht. Yesli v magazine tovarov 200-300 i boleye, to prodavtsu vso ravno kak schitayetsya ostatok tovara - on yest' v nalichii.
Ochen' bol'shaya problema.
Kak ispravit'?
Развернуть
911/5000
I definitely have the same problem.
Almost all products have 1 piece.
Buyers constantly ask whether this product is in stock or not after adding it to the basket, but these are regular customers. And whoever first went to my store added the product to the basket, and he immediately realized that the product was not in stock. You will not send them a message - "the goods remained in the basket", because he has not left his e-mail yet. This is not an ordinary store where the seller can stand next to the buyer and explain to him the features of calculating the amount of goods.
I switched to 1.7.5.2 from 1.5.6 where there were no such questions from buyers, and now almost every day they ask about the availability of goods.
This is a big problem, especially in stores with goods in the amount of 1 pc. If there are 200-300 or more in the store of goods, then the seller does not care how the rest of the goods is considered - he is in stock.
A very big problem.
How to fix?

**Comment by Alexandr-Vall** [comment]
I definitely have the same problem.
Almost all products have 1 piece.
Buyers constantly ask whether this product is in stock or not after adding it to the basket, but these are regular customers. And whoever first went to my store added the product to the basket, and he immediately realized that the product was not in stock. You will not send them a message - "the goods remained in the basket", because he has not left his e-mail yet. This is not an ordinary store where the seller can stand next to the buyer and explain to him the features of calculating the amount of goods.
I switched to 1.7.5.2 from 1.5.6 where there were no such questions from buyers, and now almost every day they ask about the availability of goods.
This is a big problem, especially in stores with goods in the amount of 1 pc. If there are 200-300 or more in the store of goods, then the seller does not care how the rest of the goods is considered - he is in stock.
A very big problem.
How to fix?

**Comment by marionf** [comment]
Hello guys,

Thank you for your feddbacks.
So, this is what we can do:
Display the real quantity in stock, no matter how many was added to the cart. 

Is it ok for you like this ?

**Comment by MockoB** [comment]
Hi @marionf,
If it means, when adding a product in the cart doesn't lower the available quantities (which forces warning message to appear, like it was in previous ps versions and is on all other platforms) it is perfectly fine for me :) You could still add it as a feature in the back office to choose between different behaviours.

Kind regards,
Moskov

**Comment by Alexandr-Vall** [comment]
Yes. This is what I need.
I need a real quantity in a warehouse, instead of a quantity in a warehouse minus a basket.
Thank.

**Comment by marionf** [comment]
@MockoB 

Let's say you have 1 product in stock and add this product in your cart.
You will still have the out of stock message and add to cart button disabled in the product page.
Because this product is always in your cart and you can't add it again.
Or we can change "Out of stock" by "Already in cart" ? What do you think about that ?

![capture d'écran_1887](https://user-images.githubusercontent.com/13449658/62959428-1054a580-bdf9-11e9-8f75-6542c2d22c63.png)

**Comment by Alexandr-Vall** [comment]
Change "Out of stock" by "Already in cart" 
If there is no way not to reduce the quantity of goods, then such a decision would suit.

**Comment by MockoB** [comment]
@marionf 
I still think that best way is to do it like all others did. And it is the way it was in previous PS versions, I believe you never got complains about it. 

But if you still want to be innovators, you may do it like that, yes. But I don't think that just "Already in cart" is enough. It should be more likely "The last item is already in your cart" and "The last 3 items are already in your cart" Of course the number should correspond to the number of items in your cart. But what IF, you added 3 and there is only one left, it will still show 1 item left and you will not be informed that the rest are in your cart ... I think you get the point :)

Please just do it like it was before, which is what all ecommerce customers are used to.

All the best,
Moskov

**Comment by marionf** [comment]
It was already like this in previous PS version, please see the screenrecord below of 1.6 version:
https://drive.google.com/file/d/1OJKZahV_YfQw8BLcxJipQLEbuaOLtYgZ/view?usp=sharing

On earlier 1.7 versions, what was already in cart wasn't taken into account and you were able to click on add to cart and get an empty success confirmation message and the product wasn't added to the cart: http://forge.prestashop.com/browse/BOOM-3308
We received a lot of complaints about this and fixed it by taking into account the products already in the cart, like it was on 1.6 version

**Comment by MockoB** [comment]
Hi @marionf ,
I believe the issue you are quoting is actually more related to the current issue. You see, the user got 3 items in his cart (with overall 5 available) and than adds additional 4 but they are not added to the cart and the cart quantities are still 3. The reason that happens is because the already added quantities are reflected and the remaining quantities are only 2, but that is not shown on the product page with appropriate message. If it was working as it should (as I propose), there had to be 4 items in the cart (not 3 or 7). Following the links, you could see that the issue is about adding more quantities than the ones available, without informing the customer with appropriate message.
PS, I just watched your video and it shows exactly what I mean above.

I have to say that my proposition about the previous PS’ versions behaviour was a little bit premature. That is why I’m still using 1.5.6.1 version like the user above. I never liked PS 1.6 and I never thought it deserves to replace my current shop. But with PS 1.7 and especially with prestarocket’s theme I definitely think it’s time for change.

So I still believe the best way to do it, is by adding a feature in the back office where merchants could choose desired behaviour. If not possible, than the preferred way is, adding a product to the cart doesn’t lower product quantities. They should be lowered only when the order is finalised, and not just for particular customer, but for everyone else also.

I don’t think there is sufficient solution where everyone is happy with the current behaviour :( You understand that merchants selling lower quantities will have troubles, if it stays like that. As for all with higher stock quantities, it really doesn’t matter. I believe, if it was like I propose in PS 1.6, there wouldn’t be any complains either.

**Comment by Alexandr-Vall** [comment]
The solution in 1.5 is correct in my opinion. And no one asked you questions about the quantity of goods. All questions for you began when there were corresponding changes in 1.6, and now they are relevant. I know many still work on 1.5 and when switching to 1.7 they will have the same questions.
The best, in my opinion, to do as it was in 1.5.
In extreme cases, instead of the message "out of stock" write "in basket 1 (2, 3, and so on) piece."

**Comment by marionf** [comment]
Guys, I just tried to see how it was working on PS 1.5 and it's like on PS 1.6 & 1.7:
https://drive.google.com/file/d/1aOds5Vs5cHazwtti7rizOyrg93hz-i5N/view?usp=sharing

10 products in stock
5 products in my cart
I try to add 10 products, I have an error "there isn't enough product in stock" and 0 product is added to the cart

If I understand well, you would like it to work like this:
10 products in stock
5 products in my cart
I try to add 10 products, 5 are added to the cart

Do you guys have an example of a website working like this ?

For the following case, we could do that:
10 products in stock
10 products in my cart
I arrive on the product page, add to cart button is disabled with a message like "X pieces already in cart, the stock is reached" or "X pieces already in cart, you can't add more"

**Comment by Alexandr-Vall** [comment]
In 1.5 it works correctly. After adding to the basket, the rest of the goods does not decrease. And most importantly there is no "out of stock" message.
It is the message "out of stock", after adding to the basket, scares the buyer.

**Comment by MockoB** [comment]
@marionf I am ashamed, but it really is working like that. May be the only reason we had no troubles so far, is because no one ever tried to add same product twice when he sees there is just one product left! But there is no warning message informing you when you add the last item to your cart to confuse the customer, like it is in 1.7. 

The way I think is correct is like aliexpress or ebay do it. 3 items in stock means there are 3 items in stock, and they will be 3 until I buy one. I think ecommerce leaders like them should know best.

The way you want it is like that: https://www.decathlon.com/collections/freeride-ski-boots/products/womens-ski-boots-wid-300?variantid=%24119.00&variant=351123800077
You could see live example of that you want to achieve, but that is made correctly. It is perfect example, because currently there are 2 sizes and one has 1 quantity left and the other one 2. Please check it. 

Both ways should do the job, but please still give a chance to merchants to decide.

**Comment by marionf** [comment]
> The way I think is correct is like aliexpress or ebay do it. 3 items in stock means there are 3 items in stock, and they will be 3 until I buy one. I think ecommerce leaders like them should know best.

Yes, as I told you, we can change that and display the real quantity in stock regardless what is already in the cart

Then, we can handle the following case:
Stock: 10
Products in cart: 10
Product page: Add to cart button disabled & display a message "All available products are in your cart" instead of the current "out of stock"

Guys, is it ok for you like this ?

**Comment by Alexandr-Vall** [comment]
"All available products are in your cart" instead of the current "out of stock"
Such a decision will suit me

**Comment by MockoB** [comment]
It's fine with me also, but what if there are 10 items in stock and I add 8 to the cart. What the message will be then? And what if I added previously 8 and come back few days later and try to add 3 pieces (assuming I forgot I already added 8). There will be message informing both, how many items are already in your cart and another line informing you about total stock ? 
You wish to take the best of both examples I gave above, but I don't think they are compatible. Or you propose to disable the button and show the message only if all products are added to the cart? And not informing anything about remaining quantities ... You should be more detailed because I think there will be conflicts with the proposed behaviour.
It would be nice to make a poll or something similar on the forums, with examples of the available options, so the community could decide what is best. And maybe someone could come up with better solution.

**Comment by MockoB** [comment]
I just checked it again on ebay. When you add a product in your cart, the button shows "in your basket" and you are not able to use the button any more, its only possible to change the quantities  within the cart. I'm not quite sure but it could be the better solution ... and solves the above problems.

**Comment by mariem-abid** [comment]
Hi @MockoB,

Does your problem is solved?

**Comment by MockoB** [comment]
@mariem-abid
The proposed solution is far better than the current situation. But it’s not clear what will happen in other situations like I asked above. Or once a product is added to the cart, the button will stay “already in your cart” and the only possible way to change the quantities will be from the cart itself? It would be nice to bring some clarifications. Thanks.

**Comment by marionf** [comment]
@MockoB 

> There will be message informing both, how many items are already in your cart and another line informing you about total stock ?

Yes, it's a good suggestion

We can handle the following case like this:
Stock: 10
Products in cart: 5
Product page: Try to put 6 in quantity field
The add to cart button is disabled & display a message "Already X products in your cart, you can add X only" instead of the current "There are not enough products in stock"

And also of course as I told before, display the real quantity in stock regardless what is already in the cart and put it more forward

**Comment by Alexandr-Vall** [comment]
For me, the most important thing is that there should be no "out of stock" message when the product is in stock but added to the basket.
What changes need to be made to the code to solve this problem.
It will suit me.

**Comment by MockoB** [comment]
@marionf It sounds perfect to me. I just don't know how you will handle both - the button is disabled and you try to add additional items in your cart with disabled button :) Otherwise looks great solution!

**Comment by marionf** [comment]
@MockoB 

The behavior of "add to cart" button stays the same as currently.
We just:
1) display the real quantity in stock regardless what is already in the cart and put it more forward

2) Display "All available products are in your cart" instead of "out of stock" in the following case:
Stock: 10
Products in cart: 10
In this case, the add add to cart button is disabled

3) Display "This product is already in your cart, you can add X more" instead of "There are not enough products in stock" in the following case:
Stock: 10
Products in cart: 5
Product page: Try to put 6 in quantity field
In this case, the add to cart button is disabled when you try to add to cart more products than there are in stock.

**Comment by MockoB** [comment]
@marionf something like that?: https://drive.google.com/file/d/1_OGyH48BmWldZPNU9YXEOHV6szMX6O8m/view?usp=sharing

**Comment by marionf** [comment]
@MockoB Yes, someting like that

**Comment by marionf** [comment]
Guys, thank you very much for your feedbacks !
I created a new issue more clear here: https://github.com/PrestaShop/PrestaShop/issues/15152
Please, follow this issue to stay informed

Regards

**Comment by mubz23** [comment]
guys, i also found this to be a bug in prestashop
totally agree with @MockoB & @Alexandr-Vall 

we need to display real quantities regardless of what's in the cart, i really hope that someone can find a fix for this soon, as this bug is the only thing that's holding me back from going live

**Comment by marionf** [comment]
@mubz23 

Please follow: https://github.com/PrestaShop/PrestaShop/issues/15152

**Comment by khouloudbelguith** [comment]
Duplicate of #15152
