### ISSUE TITLE
"Minimum quantity for sale" issue

### ISSUE THREAD

**Issue by ramwebkul** [PrestaShop/PrestaShop#14909]
This issue occurs in all PrestaShop versions (Checked in all versions above 1.7.4.x):

The user is able to order less quantity than "Minimum quantity for sale" setting.

To reproduce the issue:

1. Initially, the mimimum quantity is set 1

![image](https://user-images.githubusercontent.com/53465735/62108290-52dd9480-b2c7-11e9-849e-8d449facc183.png)

2. Added the product to cart with 1 quantity

![image](https://user-images.githubusercontent.com/53465735/62108336-70126300-b2c7-11e9-8223-6671ef388e99.png)

3. Change product minimum quantity for sale to 10 (opr any greater value than previous value.)

![image](https://user-images.githubusercontent.com/53465735/62108396-90dab880-b2c7-11e9-98a3-22652150c3d8.png)

4. Refresh cart page. The quantity will show updated but prices will not be updated anywhere

![image](https://user-images.githubusercontent.com/53465735/62108437-acde5a00-b2c7-11e9-9050-638686750490.png)

5. Make the order, it will be successful with old incorrect quantity.

![image](https://user-images.githubusercontent.com/53465735/62108543-eadb7e00-b2c7-11e9-9bb9-846f2dcbd4c6.png)

**Comment by khouloudbelguith** [comment]
Hi @ramwebkul,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0.
The new quantity is not applied
https://drive.google.com/file/d/1xLIMkJSSAVXnfuc7v5wLsO1ex7OKMzkj/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
