### ISSUE TITLE
Problème bloc promotions

### ISSUE THREAD

**Issue by charletmonaco** [PrestaShop/PrestaShop#14947]
Bonjour,

Nous rencontrons un problème avec notre bloc promotions (sur la page d'accueil).

Le bloc promotion a disparu, et nous souhaiterions le remettre. Nous n'avons pas remarqué de problème, car le module est bien activé mais le bloc n'est pas visible sur la page d'accueil. 
Serait il possible de regarder rapidement d'où vient le problème s'il vous plait ? 

Merci beaucoup, 
COrdialement, 
Lauriane THOORIS 
CHARLET MONACO

Sur notre HOME PAGE le bloc PROMOTIONS a disparu.

POSITIONS DES BLOCS :

1.	PROMOTIONS
2.	NOUVEAUTES
3.	BEST SELLERS

Le module est bien actif : PRODUITS MIS EN AVANT SUR LA PAGE D’ACCUEIL (voir capture ci-dessous)

 ![image](https://user-images.githubusercontent.com/53558833/62278785-0c17a800-b449-11e9-8a08-0000dc89e85a.png)

Il est bien mis en 1ère position (voir capture)

 
![image](https://user-images.githubusercontent.com/53558833/62278792-120d8900-b449-11e9-926d-ca408a719164.png)

Mais le bloc n'est pas visible sur la page d'accueil, et nous ne comprenons pas pourquoi.

**Comment by khouloudbelguith** [comment]
Hi @charletmonaco,

In my case, I did not manage to reproduce the issue with PS1.7.6.0 & the ps_specials module.
https://drive.google.com/file/d/1EhF79omtyXLN9yDcClID_ZNVTZQUSQHF/view
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
