### ISSUE TITLE
Duplicate Product in BO with different price for each shop (multishop)

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#14958]
**To Reproduce**

1. Set a multishop with 2 shops (or more). For instance:
2. Create a product in context all shop
3. On each shop set a different price for the product
4. Finally on products board, select the previous product and click on duplicate product on all shop context.

**Describe the bug**

A product duplicated from all shop context set the default shop's price for all shops. It should set the same price than the original product (the price corresponding to the shop).

**Additionnal information**
PrestaShop version: 1.7.x
PHP version: all

**Comment by khouloudbelguith** [comment]
Hi @202-ecommerce,

I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.0.
![image](https://user-images.githubusercontent.com/16067358/62307023-c4117900-b47a-11e9-8e67-7b5e2866ebb3.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
@202-ecommerce, thanks for the PR
