### ISSUE TITLE
Category tree on BO product page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14955]
When you create a new product, currently the category tree is fully depployed.
If there are many categories, the list is too long.
So, we should display only the first 2 levels of categories, like this:

![capture d'écran_1866](https://user-images.githubusercontent.com/13449658/62301032-1ac98380-b478-11e9-818f-84b6ce67f74f.png)

**Comment by tarasklymets** [comment]
The problem is that the site wants to display all 7000 categories, in 1.6 it worked somehow differently.

How do I make collapsed categories when entering editing? To make the page load faster. Or can I make a video of the difference in speed of 1.6 and 1.7?

PrestaShop 1.6 very fast https://skr.sh/v2STKMcje4L
PrestaShop 1.7 very slow https://skr.sh/v2SK5Qu6vQq

Most likely it is already difficult for the browser to display 7000 categories at once. The load on the server is minimal.

**Comment by tarasklymets** [comment]
Waiting for a decision?

**Comment by tarasklymets** [comment]
When to expect a change?

**Comment by NeOMakinG** [comment]
@PrestaShop/product-team should we fix it now, or do we wait for the product page migration?

**Comment by marionf** [comment]
I think we can do it now if it will not be necessary to redo it once the page will be migrated
