### ISSUE TITLE
Keeping things secure?

### ISSUE THREAD

**Issue by adu42** [PrestaShop/PrestaShop#14983]
"Adding an index.php file at the root of any module folder you create"?

Why not using module routing and set public assets and entry index.php for all routing?

We can see the modules route is confusion.

Do we need to refer to the PCI DSS specification?

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
@adu42 If we change the directory structure and put public assets and private directories containing codes and dependencies, we will have a bad time with an upgrade, it's not possible right now.
About the PCI DSS, it's not needed since the project doesn't store any credit card information, and about the ps_checkout account, everything is outside the PrestaShop module.

**Comment by PierreRambaud** [comment]
I'm closing it since PrestaShop has nothing to do here :)
