### ISSUE TITLE
Faceted search - issue with feature values order

### ISSUE THREAD

**Issue by grigorevlad** [PrestaShop/PrestaShop#14989]
Faceted search sorts feature values in numeric and alphabetic order, but latest 3.2.0 version fails to sort correctly in the following example.

To reproduce just add some numeric features to a product:
3
11 
13
35
56
110
130

On search block the module will display this order:
11
110
13
130
3
35
56

Screenshot:
![Untitledaa](https://user-images.githubusercontent.com/8983330/62464298-ebc35280-b794-11e9-87b7-91f0f5e35480.jpg)

PrestaShop version: 1.6.0
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @grigorevlad,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 & the ps_facetedsearch v3.2.0.
![image](https://user-images.githubusercontent.com/16067358/62472521-c9323900-b796-11e9-82c5-2e9e9d4520ba.png)
It was Ok with ps_facetedsearch v3.0.6.
![image](https://user-images.githubusercontent.com/16067358/62472541-d51dfb00-b796-11e9-84fd-c4026a64af87.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

Ping @PierreRambaud

**Comment by PierreRambaud** [comment]
This is because it's sort by string and not by numeric.. We will add a check for that. What behavior is desired? Numerci first or string first?

**Comment by marionf** [comment]
@PierreRambaud 
You mean if there are numeric and string, what should appear first ?

**Comment by grigorevlad** [comment]
I guess best would be to add a “Sort by” button for each filter in module config - backoffice. Alphabetical or Numeric.

Or else, if this approach would be difficult to implement: 
-If it starts with character, sort alphabetical;
-If filter value starts with number then sort numeric. (And ignore other characters after number, for situations like: 12mm, 110mm)

**Comment by PierreRambaud** [comment]
This is what I do for https://github.com/PrestaShop/ps_facetedsearch/pull/124
