### ISSUE TITLE
Two service containers coexist in back office - there should be only one

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#14995]
In back office, when requesting a page that has been migrated in symfony, when asking for a container from Context, we get an instance of **AdminContainer**, a service container generated by symfony, whose name is probably based on **config/services/admin**.

So it seems like we have the **SymfonyContainer** and the so called **AdminContainer** living in parallel when we are in a migrated page in back office.

**Comment by jolelievre** [comment]
So the name is not based on the config files, but rather on the way `ContainerBuilder` builds its dump container class in the cache:

https://github.com/PrestaShop/PrestaShop/blob/4e7901984b73ddffa5234680203f19cda0e395cf/src/Adapter/ContainerBuilder.php#L117

And in the `AdminController` class, the legacy (light) container is built this way:

https://github.com/PrestaShop/PrestaShop/blob/4e7901984b73ddffa5234680203f19cda0e395cf/classes/controller/AdminController.php#L4781

=> hence the `AdminContainer` class name

But indeed since now we should have the container accessible everywhere through the class `SymfonyContainer` (although it's ugly), and since the symfony kernel is always built in the back office anyway, we could drop this "AdminContainer" and use `SymfonyContainer::getInstance` instead in `AdminController::buildContainer()`

We need to be careful though that all the previous services present in `AdminContainer` will be available in the symfony container to avoid losing legacy services and creating a BC break. We must especially pay attention to service in `config/services/admin/*`

And if we are fearless, we could throw an exception in `ContainerBuilder` when it is called for a container 'admin' this could help us detect bad behavior more easily.

**Comment by colinegin** [comment]
Hello @matthieu-rolland, 

can we close this issue ?

**Comment by colinegin** [comment]
Are you still working on this issue @jolelievre or should we put in back in the to do column ?
