### ISSUE TITLE
Pricing Issue

### ISSUE THREAD

**Issue by pbpg** [PrestaShop/PrestaShop#15011]
I have an issue with the pricing of my products.
There are 2 different pricing, the correct one should be the one without discount.
These 2 website are entered from 2 different PC.
I realised that the link is different as well.

Any way to resolve this?
Someone kindly help! Urgent!

Thank you
![20190807_153731](https://user-images.githubusercontent.com/53854959/62605401-9c178f00-b92c-11e9-9a74-2bfcd30a4610.jpg)
![20190807_153928](https://user-images.githubusercontent.com/53854959/62605402-9c178f00-b92c-11e9-850b-eb98da252157.jpg)

**Comment by khouloudbelguith** [comment]
Hi @pbpg,

What the exact version PrestaShop did you use for your shops?
PS1.6.1.24?

Thanks!

**Comment by pbpg** [comment]
> Hi @pbpg,
> 
> What the exact version PrestaShop did you use for your shops?
> PS1.6.1.24?
> 
> Thanks!

Hi @khouloudbelguith,

I'm using PS1.6.1.17

**Comment by khouloudbelguith** [comment]
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks for your understanding!

**Comment by pbpg** [comment]
@khouloudbelguith 
so there is no solution to my problem?
