### ISSUE TITLE
AdminTabs controller can not be accessed - Menu BO Page

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#15048]
**Describe the bug**
`AdminTabs` admin controller doesn't appear in any menu. If you try to access directly by URL it returns an `Acces denied` error.

This functionality is not in any other controller.

**To Reproduce**
1. Open any AdminController
2. Change URL to `controller=AdminTabs`
3. Bypass token warning

**Additional information**
PrestaShop version: 1.7.6.0

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report.
I checked with PS1.6.1.24 => OK
![image](https://user-images.githubusercontent.com/16067358/62784544-9ea5f000-bab6-11e9-995c-ff9bdd6fe5b4.png)
I tried with PS1.7.5.1 & ps1.7.6.0 => Access denied
![image](https://user-images.githubusercontent.com/16067358/62784987-8f737200-bab7-11e9-95c1-a4a0d661e616.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by HamzaElghanoui** [comment]
Thanks @khouloudbelguith I make a pull request for this issue and waiting for merge https://github.com/PrestaShop/PrestaShop/pull/17501
