### ISSUE TITLE
Error: The file is not valid, when uploading child theme

### ISSUE THREAD

**Issue by vilzuh** [PrestaShop/PrestaShop#15053]
**Describe the bug**
When uploading a child theme of Prestashop's Classic theme, I receive error message stating "The file is not valid"
Other users have mentioned this happening with at least one other theme if not all. 

**To Reproduce**
1. Download child theme .zip from prestashop back office
2. Upload the same file modified or not, does not matter, as a child theme
3. Error is displayed

**Screenshots**
Another user posted video of the same problem here: https://www.prestashop.com/forums/topic/996729-child-theme-file-not-valid/
And https://www.prestashop.com/forums/topic/998080-child-theme-file-not-vaild-1760/

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0, 7.1, 7.2. 7.3

**Comment by khouloudbelguith** [comment]
Hi @vilzuh,

In fact, this issue occurs because the theme folder is in the zip file as reported here: https://github.com/PrestaShop/PrestaShop/issues/15004
If you try to upload a zip file with the theme folder => OK
[child_classic.zip](https://github.com/PrestaShop/PrestaShop/files/3486723/child_classic.zip)
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15004
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15004

**Comment by vilzuh** [comment]
Hi, 
I tried to upload that exact file you linked and it still resulted in an error. 
Here's a clip of it https://www.youtube.com/watch?v=c2uRQ0m8T6Y
I have no idea what is causing it, but the file apparently is not even uploaded to the remote server prestashop is running on, as the error message is instant upon dropping the file. 
Is there anything I can do to give more info on this?

**Comment by khouloudbelguith** [comment]
@vilzuh, I tried with the same file & it is OK
https://drive.google.com/file/d/1Nssw6AN1TLQDgjoAsLSqUTq3ayEqUb9q/view

**Comment by vilzuh** [comment]
It looks like this is not bug that many users at all experience. Are there any logs or such that I could send over for you to check out? If there's something obviously wrong or weird about my set up that could affect this.

**Comment by oplex** [comment]
@khouloudbelguith 
"If you try to upload a zip file with the theme folder => OK
child_classic.zip"

does not work
https://youtu.be/DA6weVrJc_4

**Comment by DotJoshJohnson** [comment]
Just in case this is still an issue for anyone, the problem is that Dropzone (the file upload control used by PrestaShop here) is being configured to only accept files with a type of "application/zip". Some environments, however, will use a different MIME type. Chrome 78 on Windows 10 (1909), for example, uses application/x-zip-compressed. Pasting the snippet below into the browser console just before uploading is what I'm using as a workaround:

```javascript
Dropzone.forElement(document.getElementById("importDropzone")).options.acceptedFiles = "application/x-zip-compressed";
```
