### ISSUE TITLE
problem with state and province

### ISSUE THREAD

**Issue by supvm** [PrestaShop/PrestaShop#15098]
Hi everyone, I have a problem, I have the 1.6.23 version of prestashop, I only sell in Italy, the problem is that when Import an ebay order with a form it confuses me with the provinces, instead of taking the Italian province from the list of the states, the province chooses me from the list united states, for example Milan becomes Michigan because they both have the initials MI, I have already disabled all the states by united states but it does the same, I think it's a bug, can someone help me to solve? thank you

**Comment by mariem-abid** [comment]
Hi @supvm,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in extended maintenance mode until June 30, 2019.

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.
