### ISSUE TITLE
Homepage image slider configuration different than current template

### ISSUE THREAD

**Issue by savoy6aus** [PrestaShop/PrestaShop#15113]
Hello,
The homepage image slider configuration is different than my current template. It's using the config for the last theme.

The logo and Favicon **does** update.

Help please!?
![Annotation 2019-08-14 095226](https://user-images.githubusercontent.com/53873584/63032367-4c304f00-be7b-11e9-8a60-d5c6c23aeb47.png)
![Annotation 2019-08-14 095642](https://user-images.githubusercontent.com/53873584/63032368-4cc8e580-be7b-11e9-99c9-d5aa344f41d0.png)
![Annotation 2019-08-14 095123](https://user-images.githubusercontent.com/53873584/63032369-4cc8e580-be7b-11e9-804c-dda8d3e80847.png)

![Annotation 2019-08-14 100916](https://user-images.githubusercontent.com/53873584/63032540-a03b3380-be7b-11e9-8879-eae548714a5a.png)

**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by mariem-abid** [comment]
Hi @savoy6aus, 

We could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a customization problem.
As it's not the default theme, provided by Prestashop, we can't do anything with this.
You should contact the theme author, they are the only ones to help you with it.
Thanks!
I close the ticket, feel free to open a new one when needed.
