### ISSUE TITLE
Faceted search | Filters suddenly disappear from the list

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#15138]
Watch the video, some filters suddenly disappear from the list on the left.

Keep an eye on **Rozměr - výška (mm)**. The bug happens when deselecting **Odstíny světlé** on 0:38 in the video.

https://drive.google.com/file/d/1AtOERy2BdpPPE_cKyURTRZj9yLkal0WD/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.6
Faceted search version: 3.2.0

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Could you please Enable the "Show the number of matching products" option.
I think this is normal behavior.
In fact, In my case for example:
For the attribute "Size" is used only in the "Clothes" category.
So, when we select a size, the filter category is not displayed anymore.
I attached a screen record
https://drive.google.com/file/d/1bczU0e8f6rOMBBFJYTvM_TqKffJKDc81/view
Thanks to check & feedback

**Comment by Hlavtox** [comment]
@khouloudbelguith I will record it with these numbers, but:

The filters get hidden when deselecting a option. If it was intended behavior, they would get hidden on selecting a option.

Rozměr - šířka (mm) - width
Rozměr - výška (mm) - height
Odstín dřezu - color
Tvar dřezu - shape

Look on the video, I deselect colour and several options from shape disappear and height disappears completely.

**Comment by khouloudbelguith** [comment]
@Hlavtox, thanks!
Waiting for the recording with numbers.

**Comment by Hlavtox** [comment]
@khouloudbelguith From some reason, these numbers do not appear on my classic-rocket theme, sorry.

They are useless anyway. They show how many numbers are having this feature from the original list, not the filtered one.

**Comment by khouloudbelguith** [comment]
@Hlavtox,

1. Create two products in the Test1 Category with combinations (color & Size)
2. Create two other products in the Test2 Category with combinations (Color only) with some brands Brand1.
3. Create two products in the Home Category with brand Brand2

In the FO
1. Try to select the Size filter => you will see that the Category filter disappear because we have only one category (Category1 with this filter)
2. If you click the filter "Color" => the Category will appear again

This behavior is related to this issue: https://github.com/PrestaShop/PrestaShop/issues/11207
If you change 

`$usefulFiltersCount > 1` to `$usefulFiltersCount >= 1` in the file `ps_facetedsearch/src/Product/SearchProvider.php file` you will see that the category Category1 will not be disepear if we select size.

Before change
![image](https://user-images.githubusercontent.com/16067358/63582849-bdfe4c00-c591-11e9-9701-a906458af378.png)

After change
![image](https://user-images.githubusercontent.com/16067358/63582721-81caeb80-c591-11e9-8994-79c30b53edb0.png)

Thanks to check & feedback

**Comment by Hlavtox** [comment]
@khouloudbelguith

Behavior in the ticket you mentioned is correct.

My case is different. When Rozměr - výška disappears, there are like 100 products with this parameter.

Watch the video again step by step. It disappears after DESELECTING a filter.

**Comment by Hlavtox** [comment]
Let's wait until you fix the module again, now it's completely unusable.

We will see what it does in version 3.2.1.

I don't understand what is so hard on opening 1.6 and 1.7 next to each other with same product catalog and making faceted search behave like it did, and shoud behave.

**Comment by khouloudbelguith** [comment]
Ping @colinegin @marionf is this the wanted behavior following these steps? https://github.com/PrestaShop/PrestaShop/issues/15138#issuecomment-524247702?
In fact, when we select the size filter => the `usefulFiltersCount` of the Category filter = 1 so it will not be displayed.
What do you think?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I just talked with @PierreRambaud about this issue.
This is normal behavior.
There's no point in displaying a filter if it's all by itself
In fact, you will have 20 filters that you do not have any utilities because there is just this product and others in it, and there are no other filters available.
As an available workaround in your case, you can change 
`$usefulFiltersCount > 1` to `$usefulFiltersCount >= 1` in the file `ps_facetedsearch/src/Product/SearchProvider.php file` 
I close the issue, feel free to open a new one when needed.
Thanks!
