### ISSUE TITLE
The discount total is zero when the cart rule offers a product

### ISSUE THREAD

**Issue by Kiweez859** [PrestaShop/PrestaShop#15160]
**Describe the bug**
When the cart rule offers a product, the value of this product is not reported in the fields total_discounts, total_discounts_tax_incl and total_discounts_tax_excl  in the table ps_orders .

**To Reproduce**
1. In BO, create a shopping cart rule with a product offered
2.In FO, create a cart and add the discount code
3. Validate the order
4. Check the fields total_discounts_tax_incl and total_discounts_tax_excl in the table ps_orders. The price of the product offered was not reported in these fields.

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7

**Comment by khouloudbelguith** [comment]
Hi @Kiweez859,

Thanks for your report.
I have the same issue with PS1.7.5.2.
But it is fixed with PS1.7.6.0.
![image](https://user-images.githubusercontent.com/16067358/63334624-b2ade500-c333-11e9-88b3-e0e7c6b632e7.png)
![image](https://user-images.githubusercontent.com/16067358/63334639-bd687a00-c333-11e9-86fd-f3334291d639.png)

Since it is fixed, I close the issue, feel free to open a new when needed.

Thanks!
