### ISSUE TITLE
Hello, I have created tax rules and and The products do not appear with VAT

### ISSUE THREAD

**Issue by JUANEF1986** [PrestaShop/PrestaShop#15211]
**Describe the bug**
I have created new tax rules for the VAT in Spain's provinces and this has caused that disappear the VAT have disappear in all articles. All tax rates are activate (like visitor, guest and customer. Also in tax options) and I don`t know  wich is the problem. 

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.6
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @JUANEF1986,

If you need to display Products with price tax excluded
=> in the BO => Customers => Groups page => "Edit" your Group & change the "Price display method" to "Tax excluded"
![image](https://user-images.githubusercontent.com/16067358/63499179-3c3dee00-c4bf-11e9-9e9b-36dbb8aa578d.png)

Also, in the BO => Localization => Taxes => You can enable tax & "Display tax in the shopping cart"
![image](https://user-images.githubusercontent.com/16067358/63499160-31835900-c4bf-11e9-8a8e-1c7f814b1c6c.png)
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.
Thanks!
