### ISSUE TITLE
Category view: sorting by price incorrect

### ISSUE THREAD

**Issue by Twabi2** [PrestaShop/PrestaShop#15223]
**Describe the bug**
When sorting products with a discount by price, the order is sometimes incorrect, despite rebuilding the price index and clearing cache in BO. 

**To Reproduce**
1. Go to FO, choose a category with products with a discount
2. Sort by price, low to high
3. Check sorting order

**Screenshots**
![image](https://user-images.githubusercontent.com/52446146/63527706-dfaff280-c501-11e9-880b-6415517c2591.png)

Current sorting order:
23.16
**23.98
23.98**
23.96
23.96
23.98
23.98
**25.48**
24.98

Should be:
23.16
23.96
23.96
23.98
23.98
23.98
23.98
24.98
25.48

**Additional information**
PrestaShop version: 1.7.6.0
ps_facetedsearch version: 3.2.0
PHP version: 7.2.17

**Comment by khouloudbelguith** [comment]
Hi @Twabi2,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0 & the ps_facetedsearch v3.2.0.
Stes to reproduce the issue:
1. Create a catalog Catalog Price Rules with
1.1. Reduction type = Percentage
1.2. Reduction = 50
1.3. Condition Group => Home
![image](https://user-images.githubusercontent.com/16067358/63532522-c65b7600-c502-11e9-86cd-286d87ffa4c4.png)

2. Go to the FO => Click on All products => Sort price 
3. Click on the second page
4. see error

![image](https://user-images.githubusercontent.com/16067358/63532629-fb67c880-c502-11e9-99bd-8203cf1c3b71.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
Ping @PierreRambaud

**Comment by PierreRambaud** [comment]
Hey @khouloudbelguith can you try again, I'm not able to reproduce:
![image](https://user-images.githubusercontent.com/1462701/64105365-62447780-cd76-11e9-8c05-41f9ff817dce.png)
![image](https://user-images.githubusercontent.com/1462701/64105396-712b2a00-cd76-11e9-9502-d2aa43462839.png)

**Comment by marionf** [comment]
@Twabi2 
Could you try to click on "Index all missing prices" and "Clear cache" in faceted search module ?

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

I tried with PS1.7.6.1 & ps_facetedsearch v3.2.1.
Cache is cleared & Price is indexed
https://drive.google.com/file/d/1wrURuqmTKH7BgSCZa6LnwMWaj_KsNRi3/view
In this second shop "Price High to Low" is incorrect.
- The product which is wrong: has a price 17.500000 Tax included
- In my second shop the Tax is disabled & Catalof rule with reduction 50% 

![image](https://user-images.githubusercontent.com/16067358/64110048-f31c5280-cd78-11e9-8cad-664f5ab6d399.png)

Thanks!

**Comment by PierreRambaud** [comment]
Can you tell me if with my new PR everything is ok for you? https://github.com/PrestaShop/ps_facetedsearch/pull/130

I also add a hook when Catalog Price Rules is set.

**Comment by khouloudbelguith** [comment]
@PierreRambaud, yes, I checked your PR & it is OK for me 
https://drive.google.com/file/d/1CTY3q4xQqxdc63mxd-UbHBJ86zauBx0J/view
Thanks!
