### ISSUE TITLE
[ORDER LIST] New KPI header design

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15230]
**USER STORY**

As a merchant, I want to quickly check the important KPI of my orders.

**WHY**

The KPI icon and display are redesigned. They were talking to much space and were too separated from each other, preventing a quick reading.

**DESIGN**

https://invis.io/YKTGGFZAMCB#/376656277_Order_List_-_Quick_View

![image](https://user-images.githubusercontent.com/43613217/63581475-69f66600-c597-11e9-814a-aafea3cf16f5.png)

**Comment by tomas862** [comment]
hey @matks  @MatShir 

I marked places with blue borders I want to discuss in the image below:

![Screenshot (22)](https://user-images.githubusercontent.com/17051250/66647548-de619300-ec31-11e9-9d85-bbe91d48e327.png)

to remove them and make it exactly like in the design sketch its a bit hard and here's why : 

there are three options how this can be achieved:

1. I would need to put kpis container in legacy tpl files. I would have to modify `\PrestaShopBundle\Twig\LayoutExtension`. @matks knows that this part is problematic and better to avoid legacy template modifications
2. I can do `position: absolute` - its hard to control where should we place exatly kpis since navigation menu has `position: fixed` and on tablet or mobile it starts to collapse. Moreover, notifications are being hidden if I do that so I have to add conditional padding for whole content.
3. Addind some negative margins - but this usually is not a good idea since the horizontal scrollbar appears on web page since your content goes out of bounds.

If everything would be rendered with twig then I would choose option 1 but it is how it is and its quite complex to implement it right now.

Is these gaps are really so important to do? Maybe at least for now I can ignore these gaps and do the remaining design changes for kpi's?

**Comment by matks** [comment]
> Is these gaps are really so important to do? Maybe at least for now I can ignore these gaps and do the remaining design changes for kpi's?

Yes we can ignore these gaps for now. In the current system, we cannot remove them without a very dirty hack in the code that is likely to bite us back later 😢.

@TristanLDD @MatShir I'm sorry, as stated by Tomas up there, we cannot 100% follow the mock-up. This obstacle spawns from https://github.com/PrestaShop/PrestaShop/issues/12925. When we get rid of this issue, we will be able to correct it.

**Comment by TristanLDD** [comment]
It's ok for me, let's avoid dirty hacks and remove the gaps later ;)
