### ISSUE TITLE
Zip code South Korea

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#15254]
The default Zip Code for South Korea seems not good on 1.7.5
_I didn't try on 1.7.6_

It's NNNNN and not NNN-NNN

Same here for the 1.6 in 2017
https://github.com/PrestaShop/PrestaShop/pull/8273

Source: My customer
Source 2: https://en.wikipedia.org/wiki/List_of_postal_codes_in_South_Korea

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

I have the same issue with PS1.7.6.0 & PS1.7.5.2.
![image](https://user-images.githubusercontent.com/16067358/63678963-38280e00-c7e8-11e9-8b50-0ba12ee93c04.png)

https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/xml/country.xml#L42
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15404 to fix the issue.
