### ISSUE TITLE
TinyMCE doesn't show on Safarii, js bug

### ISSUE THREAD

**Issue by toar86** [PrestaShop/PrestaShop#15272]
TinyMCE doesn't show on Safarii, js bug. On console we see error: 

[Error] Error: Syntax error, unrecognized expression: input[name^="cms_page[title](main.bundle.js:253:94328)

PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @toar86,

Thanks for your report.
Checked with browser => Safari & browser_version => 5.1

I manage to reproduce the issue with PS1.7.6.0 & PS1.7.6.1 & PS1.7.5.1.

![image](https://user-images.githubusercontent.com/16067358/63757548-2b6fec80-c8b2-11e9-8ea1-91fdbd0e985b.png)

![image](https://user-images.githubusercontent.com/16067358/63757580-3a569f00-c8b2-11e9-84a2-e755b05c381c.png)

![image](https://user-images.githubusercontent.com/16067358/63757628-58240400-c8b2-11e9-93dc-1983c648194c.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
