### ISSUE TITLE
Sales channel

### ISSUE THREAD

**Issue by SamirDieb** [PrestaShop/PrestaShop#15311]
Hi

Since I contacted their support regarding the integration error, I have received an answer where there is an error in line.

============================
3 count (): Parameters must be an array or an object that implements Countable (/home/xxxx/public_html/classes/webservice/WebserviceRequest.php, line 794)

============================

The version is: 1.6.1.24

I hope there is one of you who can help me find a solution to that.

**Comment by khouloudbelguith** [comment]
Hi @SamirDieb,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks for your understanding!
