### ISSUE TITLE
Product Comments module displays incorrect details for product with accessories

### ISSUE THREAD

**Issue by templatin** [PrestaShop/PrestaShop#15315]
**Describe the bug**
If you have product accessories added to a product, then add comment modal displays the details of that accessory instead of product you are adding comment.

**To Reproduce**
1. Add product accessory (or Related product) to any main product.
2. Go to main product page and click on 'Write your review'.
3. Add comment displays details of product accessory instead of main product.

**Additional information**
PrestaShop version: 1.7.6
Module version: 4.0.0

![bug](https://user-images.githubusercontent.com/3615808/63948081-b230ef00-ca95-11e9-8bb2-da835fdca566.jpg)

**Comment by templatin** [comment]
ping @jolelievre

**Comment by khouloudbelguith** [comment]
Hi @templatin,

Thanks for your report.
Yes, I manage to reproduce the issue with PS1.7.6.1 & the product comment module v4.0.0.
In fact, this issue occurs only for a product with related products.
![image](https://user-images.githubusercontent.com/16067358/63949738-c1eb0c00-ca72-11e9-894d-4b5bf0ce5d81.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Hlavtox** [comment]
Shows completely different product = minor :D :D

**Comment by marionf** [comment]
@Hlavtox 

Yes, please read the [bug severity classification article](http://build.prestashop.com/news/severity-classification/)

**Comment by matks** [comment]
PR https://github.com/PrestaShop/productcomments/pull/38 fixes the issue
