### ISSUE TITLE
Product comments module, translation JS error.

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaShop/PrestaShop#15329]
Hello, 
I've JavaScript translation error on productcomments module like this picture: 
![Capture d’écran 2019-08-30 à 12 48 17](https://user-images.githubusercontent.com/4788787/64015603-2d8db180-cb25-11e9-8eec-030d1a7db569.png)

It's need a backslashes on error message. 

PrestaShop 1.7.6.0
ProductComments v4.0.0 (no upgrade needed)

**Comment by khouloudbelguith** [comment]
Hi @PrestaSafe,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & the product comments module v4.0.0.
![image](https://user-images.githubusercontent.com/16067358/64016963-51022d80-cb20-11e9-9be7-d85562bf7f8d.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
In the BO => Translations page => you can edit the expression as you said
![image](https://user-images.githubusercontent.com/16067358/64017089-99b9e680-cb20-11e9-841b-053ae1cf04cd.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Ping @jolelievre

**Comment by PrestaSafe** [comment]
Great ! Thanks for your report ;)

**Comment by Klemart3D** [comment]
Hi,

I created this PR: https://github.com/PrestaShop/productcomments/pull/46

Not sure if it's a real fix or just a workaround but it also used like this in psgdpr module: 
https://github.com/PrestaShop/psgdpr/blob/master/views/templates/admin/menu.tpl#L81

For me, in french, like original issuer, js alert is fixed:
![Fix-JS-undefined-token-productcomments](https://user-images.githubusercontent.com/7419525/69437114-f05f4700-0d42-11ea-997b-39842160e81e.png)

**Comment by Klemart3D** [comment]
Rebased

**Comment by eternoendless** [comment]
Fixed here: https://github.com/PrestaShop/productcomments/pull/57
