### ISSUE TITLE
1.7.6.1 Moving parent category to sub category not possible. Not expanding - Safari browser

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15344]
Im trying to move a category to a sub category but sub categorys are not expanding. Not able to move.
>[Edited by Kholoud]
 We need to use Safari browser (Chrome => OK)

PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @01park,

I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/19JaOVcAjhs99AUHPpwfBrM9LNcre6QGB/view
Thanks to check & feedback.

**Comment by 01park** [comment]
@khouloudbelguith 

Thank you for testing.

I have retested the issue myself and discovered that its browser related. The expand works in Chrome, but not in Safari. I did not check other browsers.

I have test this on 3 different computers. All same result.

**Comment by khouloudbelguith** [comment]
@01park, thanks for these clarifications.
I tried with OS => Windows& os_version=10 &browser=Safari & browser_version=5.1
https://drive.google.com/file/d/1BRv46wbZrwJ9rhyo45xRqAb8IrQwfEI2/view
With PS1.7.6.1/ PS1.7.6.0 => NOK

![image](https://user-images.githubusercontent.com/16067358/64111908-b7d05280-cd7d-11e9-80ec-8658c45a8530.png)
With PS1.7.5.2 => OK
![image](https://user-images.githubusercontent.com/16067358/64111607-09c4a880-cd7d-11e9-899a-11032361df60.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Same issue with os=>OS+X & os_version=Mojave & browser=Safari & browser_version=12.1
https://drive.google.com/file/d/103DAg1ekgs9GyP_hLk31NeHi6dTzEOKx/view

Thanks!

**Comment by colinegin** [comment]
@jolelievre you have put this issue in review, but is there a PR related to it ?

**Comment by jolelievre** [comment]
@colinegin Nope, my bad Wrong manipulation, I moved the wrong card
I switch them back!

**Comment by jolelievre** [comment]
Hi @khouloudbelguith and @01park 
I tried to reproduce the bug but everything works fine for me on Safari 13 MacOS 10.14

About the first video it seems that the whole page is broken (the elements are not aligned and tinymce editors are not initialized), so it seems an error or some assets not found stopped lots of js scripts.

**Comment by 01park** [comment]
I can confirm that its now working for me with the latest version of Safari 13

**Comment by marionf** [comment]
@01park so this issue can be closed ?

**Comment by 01park** [comment]
Yes

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15665
