### ISSUE TITLE
[BUG] 1.6.1.11 File manager doesn't display my images on product descriptions

### ISSUE THREAD

**Issue by sanguine14** [PrestaShop/PrestaShop#15356]
Hi,
I'm having an issue with the 1.6.1.11 version of Prestashop on the website of my company.
To be clear, this is a huge issue because we can't add any picture on the "description" field on any product pages.
In fact, our pictures just don't show in the file manager, so we can't add it in the description.

https://gyazo.com/a5c28370fd164538263e838d447867de

As you can see on this gif ⬆, the file I uploaded isn't on the manager. 
In another hand, every pictures that were added before can't be displayed on this "file manager" screen which seems to load items (status bar from 0 to 100%) but doesn't.

We have this problem for a while now and were used to it : we were adding a full caps "A" at the start of the file name. 
For example : "image001" became "Aimage001", otherweise it wasn't displayed.
The image used for this example isn't named with this "A" rule, but it won't work anyway.

Do you know how to debug this issue ?

Thanks by advance ! 🙂

**Comment by khouloudbelguith** [comment]
Hi @sanguine14,

I did not manage to reproduce the issue with PS1.6.1.24 & PS1.7.6.0
https://drive.google.com/file/d/1ivvfak2KB9th1HCFbzW0X2qG7ulem2Wp/view
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks for your understanding!

**Comment by diogojesus95** [comment]
Having the same issue with version 1.7.6.1.

**Comment by khouloudbelguith** [comment]
Hi @diogojesus95,

It is OK with PS1.7.6.2.
https://drive.google.com/file/d/1bENlrCf6f1Out38xRJqpn_fZN9gf7gr5/view

Thanks!
