### ISSUE TITLE
Order page does not display navigation

### ISSUE THREAD

**Issue by slomoo** [PrestaShop/PrestaShop#15402]
![image](https://user-images.githubusercontent.com/49021553/64247822-3aa20a80-cf42-11e9-99b4-570506e8cf22.png)

Didn't my order page show navigation

In addition, where are the carriers allocated?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @slomoo,

What to Check If PrestaShop Carriers Are Not Available At Checkout?

1.  Carrier Is Inactive: PrestaShop carrier status is the first thing you should consider
2. Incorrect Zone Assign or Country Disabled: Zone association is among the first things to check if a created carrier does not show for a specific shopper. When configuring PrestaShop carrier you are supposed to assign it to zones, this very carrier can deliver parcels within. If a carrier is not assigned to the zone, customer address belongs to, then it will not show as a delivery method at the checkout.
3. Carrier Is Not Allowed for Customer Group: This detail might easily be skipped, since you can have hundreds and thousands of customers, belonging to various customer groups. If some customer belongs to the group that is not served by current shipper, it will not be offered as delivery method for this customer
4. Weight or Price Ranges Are Not Specified: Creating PrestaShop carrier you usually define billing cost for each by one of criteria: order price or weight. Having selected a suitable method, you need to create ranges and set prices for them. In case ranges are not created, “The product selection can not be delivered by the available carrier(s). Please amend your cart” message will display at shipping step for a customer.
5- Package Dimensions Are Out of Range: If all above listed settings are configured properly but still PrestaShop carrier does not display at the checkout, you have to compare package dimensions with maximum dimensions PrestaShop carrier can handle. If package goes beyond these limits, the carrier can’t ship it and, respectively will not display as a delivery method.

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @slomoo,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
