### ISSUE TITLE
The final product price for the combination sould be displayed also tax included

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#15416]
**Is your feature request related to a problem? Please describe.**
In the BO => Product details page => combination Tab => Edit a combination => Final price is displayed with Tax excluded

**Describe the solution you'd like**
It could be a good improvement to display it also tax included as in pricing tab

**Please note, both final prices should be updated when you modify the impact on price tax excl or tax incl.**

![capture d'écran_2123](https://user-images.githubusercontent.com/13449658/67937421-dd3ada80-fbcd-11e9-9e90-b153676ab5ed.png)

Display both as in Pricing tab
![capture d'écran_2122](https://user-images.githubusercontent.com/13449658/67937424-df9d3480-fbcd-11e9-9ba9-25978a446267.png)

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by marionf** [comment]
Yes, let's do that

**Comment by AldeaG** [comment]
Hi:
I´m using Prestashop 1.7.7
I´m importing combinations via csv. I get final selling (recommended) prices tax included from my provider. As the prices may differ from size to size or color to color I set the original price to 0 in products and set the price impact as final price in combinations. The problem is I get final prices prices included.

But if I import the price from Combinations csv, Impact in price appears but it does not indicate whether or not it includes the tax. And it does not.

I should be able to add an impact price with final price so "Tax included" is a must but I don´t have an option so I have to include a column in Excel and make an "inverse" Price without tax calculation formula before import the csv.

One would expect such a including / excluding tax option with all product related prices.

Another option would be a must is: if I import quantities via combination csv I should have an option of setting the new quantities as the actual quantities (inventory) or: ADD the new quantities to the already existing quantities (replenishment).

Thanks for your help in advance.

**Comment by khouloudbelguith** [comment]
Hi @marionf,

This improvement is fixed in the PS1776.
![image](https://user-images.githubusercontent.com/16067358/132498449-23635515-65fa-4ed9-91a8-1687759f2e4d.png)

Thanks!

**Comment by AldeaG** [comment]
> Hi @marionf,
> 
> This improvement is fixed in the PS1776.
> ![image](https://user-images.githubusercontent.com/16067358/132498449-23635515-65fa-4ed9-91a8-1687759f2e4d.png)
> 
> Thanks!

In fact I do have Prestashop 1.7.7.0 and I do have that option in the Combinations tab of the product. 
 
![Captura de pantalla 2021-09-12 a las 0 09 29](https://user-images.githubusercontent.com/61842395/132962991-4a7df969-12ee-4d2f-9aa9-0ca73af57f11.png)
It is another thing:
I mean that when I IMPORT a COMBINATIONS CSV I don´t find that option to set "Impact price tax included". Only the option "Tax excluded" is available. And "Tax included" should be available also when importing COMBINATIONS CSV

**Comment by khouloudbelguith** [comment]
Hi @AldeaG,

>It is another thing:
I mean that when I IMPORT a COMBINATIONS CSV I don´t find that option to set "Impact price tax included". Only the option "Tax excluded" is available. And "Tax included" should be available also when importing COMBINATIONS CSV

This is another issue.
You can follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/25746, it is similar to your problem.

Thanks!
