### ISSUE TITLE
Web Debug Toolbar missing on Addresses

### ISSUE THREAD

**Issue by milovanbgd** [PrestaShop/PrestaShop#15412]
**Describe the bug**
When I turn on debugging, Symfony Web Debug Toolbar appears on the most of the pages. However, it never shows on the Address list.

**To Reproduce**
1. Go to 'Customers'
2. Click on 'Addresses'
3. No Web Debug Toolbar on the bottom
4. Go to Customers for example, there is a Web Debug toolbar

**Screenshots**
![Screenshot_20190905_095420](https://user-images.githubusercontent.com/34404490/64322880-ae382c00-cfc3-11e9-8895-ee3931251292.png)
![Screenshot_20190905_095435](https://user-images.githubusercontent.com/34404490/64322881-ae382c00-cfc3-11e9-8431-e848cda6f741.png)

**Additional information**
PrestaShop version: 1.7.7.0, 1.7.6.0
PHP version: PHP 7.3.8

**Comment by khouloudbelguith** [comment]
Hi @milovanbgd,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
About the Addresses page, it is not migrated to Symfony that's why there is no Web Debug toolbar.

Thanks!
