### ISSUE TITLE
ps_emailsubscription 2.5 does not register e-mail in its database

### ISSUE THREAD

**Issue by pierreloicq** [PrestaShop/PrestaShop#15425]
With PS 1761, I upgraded the Newsletter subscription module from 2.3 to 2.5 as proposed in the Module manager/updates tab.
2.3 was working fine, but with 2.5, **e-mail is not saved in the db**, and there is no "well received" green message below the e-mail box. I am just sent to index.php#footer when I submit an e-mail. 

I also have an error popping up when I go on the module config page : 
```
Notice on line 74 in file C:\\Program Files (x86)\\Ampps\\www\\presta17\\src\\Adapter\\Routing\\LegacyHelperLinkBuilder.php
[8] Undefined index: id_merged
```

### To sum it up

- minor bug: "no 'well received' green message below the e-mail box"
- major bug: "e-mail is not saved in the db"

**Additional information**
PrestaShop version: 1761
PHP version: 7.1

Thank you

**Comment by khouloudbelguith** [comment]
Hi @pierreloicq,

About the red alert.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/15382 to fix the issue.
It is reported in this ticket:
https://github.com/PrestaShop/PrestaShop/issues/15318
About the seond issue, I manage to reproduce the issue with ps_emailsubscription v2.5.0 & PS1.7.6.1.
With ps_emailsubscription v2.3.0 => OK
With 1.7.6.0 & ps_emailsubscription v2.5.0 => NOK
With develop branch & ps_emailsubscription v2.5.0 => OK
https://drive.google.com/file/d/1CWadNE_yirc7ujoj58_jAQ9055a-OAOH/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith is it a regression of 1.7.6.0 or of ps_emailsubscription 2.5.0 ?
Do you have it with PS 1.7.5.2 & ps_emailsubscription 2.5.0 ?

**Comment by khouloudbelguith** [comment]
@marionf, it is a module regression.
Same issue with PS1.7.5.2 & ps_emailsubscription 2.5.0.

Thanks!

**Comment by marionf** [comment]
It was working also with ps_emailsubscription 2.4.0, so it's well a regression of 2.5.0
@Progi1984 FYI

**Comment by matks** [comment]
Found the issue, indeed it works on develop (= it works with PS > 1.7.7) thanks to PR https://github.com/PrestaShop/PrestaShop/pull/14937

**Comment by matks** [comment]
@pierreloicq a fix is on its way, see https://github.com/PrestaShop/ps_emailsubscription/pull/41/commits/f0c60d4d36348c5e663517a5b490fba020b85c76

**Comment by matks** [comment]
I did a full summary of all possible configurations in https://github.com/PrestaShop/PrestaShop/issues/15629

**Comment by matks** [comment]
Bug fixed on `dev` branch of https://github.com/PrestaShop/ps_emailsubscription/
Release in progress
