### ISSUE TITLE
Can't translate emails

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#15433]
**Describe the bug**
The new email theme system uses translations for the content of the emails, but there is no way to translate Emails.Body that the twig files refer to.

**To Reproduce**
Try to change the phrase "Hi" in the email theme and regenerate the templates.

**Screenshots**

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.x

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/14719 to fix the issue.
It is fixed in the PS1.7.6.1.
Thanks to check & feedback

**Comment by Prestaworks** [comment]
Hi Khouloud,

I can't find those transaltions in the admin on 1.7.6.1 either? can you tell me where they are located in the translations tab?

**Comment by khouloudbelguith** [comment]
@Prestaworks, you need to navigate to your BO => International => Translations =>
1. Type of translation => Email translations
2. Select the type of email content => Body
3. Select your theme => Classic
4. Select your language => English
5. Click on Modify

I attached a screen record
https://drive.google.com/file/d/1aj-ahHMsXXjazn6wkRcsnA66ZUykrzle/view

Original Email Translated
![image](https://user-images.githubusercontent.com/16067358/64417553-35070a80-d091-11e9-9150-ce496f77ab8b.png)

Email received
![image](https://user-images.githubusercontent.com/16067358/64417564-3c2e1880-d091-11e9-9901-5f8fa1ab5a56.png)

In fact, translations will directly edit static mail files
it must work, but it's saved in the files theme (like themes / classic / mails / en)
So it's not taken into account when you see the preview.

We can not edit the keys of trad that are in the body of the mails, we can only edit the subject.
This issue should be fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/14809 => it is still in progress.

Thanks!

**Comment by Prestaworks** [comment]
Hi Khouloud,

The problem is that when I go to design -> email themes and regenerate the template files, all changes to the html files are overwritten becuase the template generator uses transations for "Emails.Body" that can't be changed from admin, those values seems to be in the xlf files? but if the email template system should be possible to use, we need to be able to translate the templates also before regenerating the .html files.

**Comment by khouloudbelguith** [comment]
@Prestaworks,

>when I go to design -> email themes and regenerate the template files

What is the exact configuration did you make before regenerating emails?
- your email theme?
- the theme you want to overwrite?
- Overwrite templates is enabled

Thanks!

**Comment by Prestaworks** [comment]
the first two does not really matter. Overwrite templates should be set to yes.
All .html files will then be rewritten, so far so good. But inside the .twigg files for these templates, there are translation strings.
{{ 'Hi {firstname} {lastname},'|trans({}, 'Emails.Body', locale) }}

I want to change "Hi" to "Hejsan". These Emails.Body is not present in the translation tools in the BO.

**Comment by khouloudbelguith** [comment]
@Prestaworks, 

With this PR: #14809 we will Add translation provider to allow modifying body contents, add a form in Email Theme page to access this edition


Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by Bonobomagno** [comment]
So, the new "modern" email templating just don't work with translation.
1.7.6.1? The PR was merged 5 days ago.
Actually the only solution is using a custom translation domain (different from Email.Body)
Something like change Emails.Body to Modules.Custommodule.customsubdomain

you have to regenerate the emails on every translation change, but it will just work.
