### ISSUE TITLE
No breadcrumb on some important pages (like Stores, Sitemap, New Products, Best Sales, Suppliers, Cart...)

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#15440]
**Describe the bug**
On fresh install of PS 1.7.6, in front-office, breadcrumb is visible on every pages but no stores pages, why?

**Screenshots**
![no-breadcrumb-on-stores](https://user-images.githubusercontent.com/7419525/64417639-c7aba780-d099-11e9-8bcc-077fd4a33fdf.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

Thanks for your report.
Not only for the "Our stores" page, but there is also
1. Sitemap page
![image](https://user-images.githubusercontent.com/16067358/64418460-f83c1300-d092-11e9-82aa-da11f1de065b.png)
2. New products page
![image](https://user-images.githubusercontent.com/16067358/64418550-1efa4980-d093-11e9-8678-cf14d8e52f9c.png)
3. Best sales page
![image](https://user-images.githubusercontent.com/16067358/64418627-46511680-d093-11e9-9543-4f7a80d7dc28.png)
4. Suppliers page
![image](https://user-images.githubusercontent.com/16067358/64418671-5cf76d80-d093-11e9-96d3-2a9139f6f1ec.png)
5. My account page
![image](https://user-images.githubusercontent.com/16067358/64418688-67196c00-d093-11e9-9bfc-cca9351d1319.png)

Ping @PrestaShop/prestashop-product-team what do you think?
It will be a good improvement if all page are similar.

Thanks!

**Comment by Klemart3D** [comment]
6. And in the basket: 
![bc-basket](https://user-images.githubusercontent.com/7419525/66575551-63877200-eb76-11e9-846f-622315fa2e94.png)

**Comment by NeOMakinG** [comment]
Breadcrumb is backend defined

**Comment by sam-pires** [comment]
> 1. And in the basket:
>    ![bc-basket](https://user-images.githubusercontent.com/7419525/66575551-63877200-eb76-11e9-846f-622315fa2e94.png)

For the basket, I would recommend to **not** add breadcrumbs, the goal at this step is to bring the customer to the next step, it is a best practice to have as few navigation options as possible in the "purchase funnel"
What do you think?

**Comment by TristanLDD** [comment]
I agree with @sam-pires, breadcrumbs doesn't have to appear on every page especially cart page where we want the user to stay focus on the payment process. 

Exemple, Asos cart page doesn't have breadcrumb: 
(Pages like 'About us', 'Help', 'Delivery' doesn't have breadcrumbs neither)
![Capture d’écran 2020-01-03 à 13 59 08](https://user-images.githubusercontent.com/27484094/71724759-c618a300-2e31-11ea-942a-051b528014e9.png)

However, it's true that it's unclear what rule we follow on PrestaShop to display the breadcrumb or not. 

Usually, a good practice for breadcrumbs is simply to not display them when the page is only one level deep in the site's hierarchy: is this case they are just duplicating the main navigation indicator hence they are useless. 

That also is exactly what Asos seems to be doing on their website: you won't find a breadcrumb on 'Men' page (because it would be Home > Men) but it will appears on Home > Men > Accessories

**Comment by sam-pires** [comment]
related to #16836

**Comment by sam-pires** [comment]
Hello all, 
Considering the lack of rule for the Breadcrumbs implementation in the Front-office of PrestaShop I created an EPIC (#17131) to centralize the work on this topic.

We'll launch a study on our side to define the best rule/behavior to have, and then specify it.
We'll take into account several aspects, including:
- SEO
- User Experience best practices
- Technical feasibility/logic

Do not hesitate to share your experience and opinion about it in the EPIC comments, right here => https://github.com/PrestaShop/PrestaShop/issues/17131

Thanks

**Comment by sam-pires** [comment]
See #17131 for all the rework on breadcrumbs
