### ISSUE TITLE
Product ID Number

### ISSUE THREAD

**Issue by Allthejam** [PrestaShop/PrestaShop#15453]
I have a small issue with my catalog, it's in the product ID numbers, I have deleted a bulk of products I am no longer doing and was wondering if there's a way to reset the ID Numbers so the run in order because as of now I have large gaps in my catalog ID's 

It's not causing any issues with my site but it's going to cause issues in my management over time as I remove and replace items so please don't think of this as a serious issue more of a request for some ideas and advice.

Heres a screenshot of what I mean its just 1 section of many Id like to change if possible. 

![Product ID Numbers](https://user-images.githubusercontent.com/52738920/64448489-1ed36b80-d0de-11e9-80f8-8b6f9354ed56.jpg)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Allthejam,

I don't think that it is a good idea to reset the auto-increment primary key indexes in your table as it can cause many problems.

The database doesn't really care about sequential values.

Primary autoincrement keys in the database are used to uniquely identify a given row and shouldn't be given any business meaning. So leave the primary key as is. If you really need the sequencial data in every row then you can add another column called for example product_count. Then when you delete a record from the database you may want to send an additional UPDATE statement in order to decrement the product_count column of all rows that have product_count greater than the one you are currently deleting.

I suggest you don't reset the ids because tables are connected, if you don't it correctly, it will cause an error.
Here is one example. Assume you reset product id from 1, but you forget to clear ps_category_product table.

Thanks!

**Comment by Allthejam** [comment]
Ok thank you for your advice, I will leave it alone...

**Comment by khouloudbelguith** [comment]
@Allthejam, thanks!

Feel free to open a new one when needed.
