### ISSUE TITLE
Emails wrong text

### ISSUE THREAD

**Issue by sotirisa** [PrestaShop/PrestaShop#15469]
**Describe the bug**
Hi, after translation on emails I get emails that you can not read. I don't know what is the reason for this. Every email I get is this way. This happened right after translations.

**Steps to reproduce**

1. with Greek language / or we add some special characters in the test message
![image](https://user-images.githubusercontent.com/16067358/64534910-41e46200-d30e-11e9-9dde-68d36012089f.png)
2. ---
![image](https://user-images.githubusercontent.com/16067358/64534934-4f99e780-d30e-11e9-8f32-024777c0aa44.png)
3. With the Greek language
![image](https://user-images.githubusercontent.com/16067358/64534961-5e809a00-d30e-11e9-8e2c-1d6acf00970f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/54579601/64505024-12683200-d2db-11e9-9993-e1f4cd1119f3.png)

**Additional information**
PrestaShop version: 1.7.6.7
PHP version: 7.1.32

**Comment by khouloudbelguith** [comment]
Hi @sotirisa,

I did not manage to reproduce the issue with PS1.7.6.1.
It is OK & the email is well displayed after the translation.
![image](https://user-images.githubusercontent.com/16067358/64526749-050f6f80-d2fc-11e9-9d96-76c6c6cbca91.png)

Could you please provide the exact steps that you have done to reproduce the issue.
What is the exact type of this email?  order_conf, ..?

Thanks!

**Comment by sotirisa** [comment]
Hi,

After the translations in greek I try to make an account the mail that I received was like that.

This text that I send you is from test email. I go to Advanced parameter->Email->Test your email configuration. I put my email and I received this:

![image](https://user-images.githubusercontent.com/54579601/64531004-22056c00-d317-11e9-9371-c9870b7a358a.png)

All the emails that I test like new account, new order comes like this. I think is something with UTF but I don't know for sure.

**Comment by khouloudbelguith** [comment]
@sotirisa,
Thanks for your feedback.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 with Greek language / or we add some special characters in the test message
![image](https://user-images.githubusercontent.com/16067358/64534910-41e46200-d30e-11e9-9dde-68d36012089f.png)
 
![image](https://user-images.githubusercontent.com/16067358/64534934-4f99e780-d30e-11e9-8f32-024777c0aa44.png)

With the Greek language
![image](https://user-images.githubusercontent.com/16067358/64534961-5e809a00-d30e-11e9-8e2c-1d6acf00970f.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

Related to https://github.com/PrestaShop/PrestaShop/issues/9726

**Comment by sotirisa** [comment]
I couldn't fix it and I don't know if I can. If I'll make it I'll write back to you.

**Comment by sotirisa** [comment]
Hi, do we know when this is gonna fix?

**Comment by khouloudbelguith** [comment]
Hi @sotirisa,

Sorry not yet.
There are some major issues to solve before this one.
So, it will probably not solved right now. 
But PrestaShop is an open-source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by sotirisa** [comment]
Hi,

For this I found a soution that it works. You must go and translate the mails files from themes/YOURTHEME/mails. 

When I translate this everything is ok. I don't know if this is the right solution but from now it works.

**Comment by khouloudbelguith** [comment]
Same issue with frensh translation
![image](https://user-images.githubusercontent.com/16067358/90872029-462d5200-e39c-11ea-992e-c1344d0a43d5.png)
