### ISSUE TITLE
Discount badge is missing on products with attribute

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#15463]
**Describe the bug**
Discount label is missing on products with attributes.

**To Reproduce**
1. BO -> Add product with attributes. Add discounts for eg. 10 pcs.
2. FO -> Add 5 products per attribute.  Lets say you have 3 attributes, then you should have 15 products in cart. As the discount is for 10+ products you get discount on all 15 products. But the label with discount is missing.
3. The label only show if you add all product in same attribute.

This is a regression from Prestashop v. 1.6.1.x

**Screenshots**
Please see this video: https://reker.dk/badge.webm

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @MathiasReker,

Thanks for your report.
Yes, with PS1.6.1.24, if the quantity of products with different combinations is > = From (quantity) condition => the discount is applied correctly in the FO.
ps1.6 => BO
![image](https://user-images.githubusercontent.com/16067358/64520495-32552100-d2ee-11e9-8316-3b9e29b16b91.png)
PS1.6 => FO
![image](https://user-images.githubusercontent.com/16067358/64520542-4c8eff00-d2ee-11e9-8381-a339972eddb8.png)
PS: this condition is used if the "Quantity discounts based on Products" only.
With PS1.7 we don't have the same behavior.
The label discount is not displayed. => NOK.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by MathiasReker** [comment]
Thanks. The discount is already applied to the price so the discount label should be applied too. :)

**Comment by khouloudbelguith** [comment]
@MathiasReker, thanks!
I added this issue to our bug roadmap.

Thanks!

**Comment by colinegin** [comment]
@NeOMakinG is this something you would be able to do ?

**Comment by NeOMakinG** [comment]
I'll take a look, assigned to myself

**Comment by NeOMakinG** [comment]
After a lot of research

/Users/vSzczupak/Sites/prestashop/themes/_core/js/cart.js

Line 54 : `$('.cart-overview').replaceWith(resp.cart_detailed);`

resp.cart_detailed is not updated with new discounts when changing value, tried to see more in backend side but can't find how to do this, it's a backend issue...
