### ISSUE TITLE
Fixed a little html error in product.tpl

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15477]
Hi
if you open the file
/classic/templates/catalog/product.tpl
at line 213
the final p tag is not closed in the right mode, it is missing ">"
it should be

`<p>{$attachment.description}</p>`

not like now

`<p>{$attachment.description}</p`

bye

**Screenshots**
![11](https://user-images.githubusercontent.com/653230/64548666-6866c500-d32f-11e9-8ad3-87937bbc5dfc.png)

**Additional information**
PrestaShop version: N/A1.7.6.1
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your report.
Yes, I have same issue with develop branch https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/product.tpl#L206 & PS1.7.6.1 & PS1.7.6.0 & PS1.7.5.2.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by davidglezz** [comment]
Too easy to not to do it on the go =)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15512
