### ISSUE TITLE
Error message when we create a new category with invalid Friendly URL

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#15490]
**Describe the bug**
On fresh install of PS 1.7.6.1 when first, URL accentuated option is enabled in SEO tab (seems to be "on" by default) and when categories with accents are created, friendly URL of categories are auto-accentuated. In front and back : OK
Now, when I'm disabling URL accentuated option in SEO tab and save, in front on menu links and in back in category in friendly URL field, URL are staying accentuated.
And now if I want to save my category, by sample by removing accents of friendly URL, I have the following error :

> Une erreur inattendue s'est produite. [PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryException code 0]

**To Reproduce**
1. Go to SEO & URL tab and enable "accentuated URL" option if not
2. Create a new category named "Déjà"
3. Check if friendly URL is "déjà" and save
4. Check on front, category page with URL accentuated is available
5. Now disable "accentuated URL" option
6. Go back to "Déjà" category on BO and save. An error is it displayed?

May be related to #14790, but #15030 not fix it.

**Screenshots**
![bug-categories-url-accentued](https://user-images.githubusercontent.com/7419525/64623730-c5bf4c80-d3e9-11e9-87bf-50578bba5408.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

It is the same behavior as PS1.7.5.2 & PS1.7.6.
When the "accentuated URL" option is disabled the friendly URL is invalid, so you need to edit this filed
![image](https://user-images.githubusercontent.com/16067358/64627613-da024a00-d3e7-11e9-87dd-c2c229c297cf.png)

![image](https://user-images.githubusercontent.com/16067358/64627627-e1295800-d3e7-11e9-931a-1a7a98a5c49b.png)

Thanks!

**Comment by Klemart3D** [comment]
a - On PS 1.7.6.1 I don't have an explicit message like you to give me which field is wrong.
b - Even if I rename link rewrite field "déjà" to "deja", I still have the unexplicit error, not you?
c - I have hundreds links to rewrite, doesn't exists a way to auto rewrite all links without accent?

**Comment by khouloudbelguith** [comment]
@Klemart3D,

>On PS 1.7.6.1 I don't have an explicit message like you to give me which field is wrong.

![image](https://user-images.githubusercontent.com/16067358/64681458-abcc4b00-d477-11e9-926a-cd4743f1e7fe.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

>Even if I rename link rewrite field "déjà" to "deja"

You multilanguage in your case => you just edit it in the french language & not the other language.

>I have hundreds links to rewrite, doesn't exists a way to auto rewrite all links without accent

But default => you have only update categories via the import page or you can check that with a custom module, for example, SEO expert: https://addons.prestashop.com/en/seo-natural-search-engine-optimization/16939-seo-expert.html

Thanks!

**Comment by florine2623** [comment]
The issue is fixed in PS 9.0.0. Now, instead of an exception, I have a warning message telling me what's wrong with the field.

<img width="775" alt="Image" src="https://github.com/user-attachments/assets/0a974b68-f318-4681-bb84-dd3f6c933dc4" />

I will close this issue to avoid clogging the backlog.

**Comment by Klemart3D** [comment]
Thanks @florine2623 !
