### ISSUE TITLE
Bloated code in productcomments

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#15495]
I'm not sure how to phrase this, all in all it doesn't seem it's been thought through properly. As an example, look at the `product-list-reviews.tpl`. This means that for *every* product on the page, there's an added `<script>` tag added. Let's say you've got 24 products per page and perhaps 19 of them has reviews, that boils down to **19 ajax requests**. Why not make **1** request and dynamically add the reviews to the proper placeholders? Or better yet, why not add it to the `product` object? Perhaps something like `{$product.rating}`? 

Also, do you *really* need to load in the entire `jquery.rating.plugin.js` and run that *just* to have it displayed properly in product lists? Seems extremely overkill, even more so since when the rating in the product lists isn't interactive at all.

I guess the current way eliminates any caching issues so that it's always the most recent rating that's being displayed but wouldn't it make more sense to clear that cache when a rating or review has been submitted (or approved by the admin if that's the case)?

Another possible issue is with Google and their Pagespeed test. This adds to the amount of nodes in the DOM which they are counting and want to have as few as possible. Google is always Google so they might change that but still...

I'm not sure if this constitutes as a bug or feature report, I'm rather voicing my concerns with the current approach...

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

Thanks for your report.
Ping @jolelievre @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by jolelievre** [comment]
Hello @dennispw ,
indeed the script tag is added in each product thumbnail in order to get the rating via ajax and thus always get the most recent rating. But as you said it creates many ajax requests, and it is not computed by Google.

We already had a discussion about this problem in this thread https://github.com/PrestaShop/PrestaShop/issues/14878 As @kpodemski (and you) suggested, it would be better to integrate the rating in smarty and clear the cache when comments are validated.

This is an improvement that needs to be added to the module. I'm willing to make these improvements but I don't have the time right now as I'm working on the core or other modules. But if someone wants to change this behaviour I'll be happy to review his/her PR.

Since this was already discussed in another issue I think we can close this one?

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
