### ISSUE TITLE
Page does not scroll when customer clicks on "details" on an order in their history

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#15507]
**Describe the bug**
I haven't tried to reproduce this bug myself.

As reported by @ingenium13 in [this PR](https://github.com/PrestaShop/PrestaShop/pull/10644) and @MathiasReker in [this PR](https://github.com/PrestaShop/PrestaShop/pull/10645):

> When a customer clicks "Details" on an order in their history, it does not scroll to the bottom when Chrome is used. Chrome broke this around v61. Updating jquery.scrollTo.js to the current version (2.1.2) fixes this bug.

**To Reproduce**
Using Chrome, click "Details" from order history. It should scroll to the bottom of the page where order the order details are shown

**Additional information**
PrestaShop version: 1.6 and 1.7

**Comment by khouloudbelguith** [comment]
Hi @eternoendless,

I checked PS1.6. & PS1.7.
The behavior is not the same.
In fact, with PS1.6, in the `order history` page, when we click on the Details page => a new section is added to the same page => that's why we should scroll to the bottom of the page
order-history
![image](https://user-images.githubusercontent.com/16067358/64773457-51e88580-d54a-11e9-8ecf-dc3a8d92bc5a.png)

But with PS1.7 (trying with chrome & firefox), in the `order history` page, when we click on the Details page => we are redirected to a new page with all details => which is correct (no need to scroll).
![image](https://user-images.githubusercontent.com/16067358/64773608-996f1180-d54a-11e9-8961-2d37acdb66d0.png)

Since it is OK => I close this issue.

Thanks!
