### ISSUE TITLE
Bad calendar display on some screens for migrated listing pages

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15534]
**Describe the bug**

**To Reproduce**
On a Symfony page, if the filters contain one "from ... to ..." input, then if screen is too small it gets badly displayed (see screenshot below)

**Screenshots**
<img src="https://user-images.githubusercontent.com/3034677/64349686-a8f4d480-cff7-11e9-9b36-33fcb24e43da.png">

**Comment by prestascott** [comment]
Hi @matks,

Thank you for your reply. In order to avoid bad display in general, i was thinking of implementing display rules and some features:
- Each column has a minimum width and you can't go smaller so you don't break components inside
- An horizontal scrollbar appears on the bottom of the table when the page gets shrinked so the users can access to the rest of the table which is convenient for trackpad users
- Left/Right arrows buttons will appears next to the last column so the users with a mouse can quickly have access to the rest of the table
- Checkbox, ID columns and columns' categories must be sticky to allow users to easily identify which rows they are looking

![table-1](https://user-images.githubusercontent.com/54888056/75555071-d3ba6580-5a3b-11ea-8c80-ad748c6addfc.png)

- The users can quickly read the text when it's cropped (on hover)

![table-2](https://user-images.githubusercontent.com/54888056/75555375-63f8aa80-5a3c-11ea-86a3-d4d9b71d7a25.png)

Wdyt? @matks @NeOMakinG @colinegin 

PS: Please don't mind the navigation menu on the left.

**Comment by NeOMakinG** [comment]
I think that's cool and that should be doable !

**Comment by colinegin** [comment]
Great !

**Comment by sam-pires** [comment]
expected behaviors/modifications must be defined and specified

**Comment by LouiseBonnard** [comment]
Good news: this display issue has been fixed in the meantime, I close this ticket.
