### ISSUE TITLE
Main menu module: a new link is created when editing a previous link

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15559]
In the main menu module, when editing a previous link, after saving a new link is created and the old one has not changed. 

Work around; remove previous link and replace it with new details.

PS: 1.7.6.1
PHP 7.2
Module version: up to date.

**Comment by mariem-abid** [comment]
Hi @01park,

Could you please try to clear cache from your project and your navigator and feedback.

**Comment by 01park** [comment]
@mariem-abid 

This I already tried, but does not helped

Maybe its a multi-store issue.

**Comment by mariem-abid** [comment]
@01park , I manage to reproduce the issue with the last version PS:1.7.6.1:

**To Reproduce**
Steps to reproduce the behavior:
1. Add a new link.
2. Click on Edit button.
3. Edit the label.
=> The update button is not existing in the PS version 1.7.6.1 (PS:1.7.6.0 is OK)
I attached a video record.
https://drive.google.com/file/d/10RGsHOtebxjVkICoY2vCs2BLOe2seNp4/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by mariem-abid** [comment]
related to #15564
