### ISSUE TITLE
Product Back Office - Invalid keyword - no error message - no save

### ISSUE THREAD

**Issue by BrunoJunior** [PrestaShop/PrestaShop#15553]
**Describe the bug**
In the product admin page, Options tab, I add a keyword : 100% whool.
No error is displayed, worse PrestaShop tell me update are OK …
But when I reload the product page, modifications are gone …

**To Reproduce**
1. Go to Back Office > Catalog > Products > Choose one product
2. Make changes on the product
3. Go to Options tab
4. Add a keyword with the "%" carac
5. Save
4. No error
5. Reload the product page
6. All modifications are gone …

**Additional information**
PrestaShop version: 1.7.4.4
PHP version: 7.2.22

**Comment by mariem-abid** [comment]
Hi @BrunoJunior,

I did not manage to reproduce the issue with the last version PS:1.7.6.0
I attached a video record.
https://drive.google.com/file/d/19mFwIKH71QdGTfQghLZDn6c_dYZhW-QK/view

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in extended maintenance mode until June 30, 2019.

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.

Thanks for your understanding!

**Comment by BrunoJunior** [comment]
Sorry, I made a mistake … The version is 1.7.4.4

**Comment by BrunoJunior** [comment]
You did not follow my instructions …
You have to add a keyword in the Options tab.
And this keyword has to contains the % char …

**Comment by mariem-abid** [comment]
@BrunoJunior, in the field Tags?

**Comment by BrunoJunior** [comment]
Yes (I suppose, on the French version it's «mots clés»)

**Comment by mariem-abid** [comment]
Hi @BrunoJunior,

I manage to reproduce the issue with the last version PS:1.7.6.1.
I attached a video record.
https://drive.google.com/file/d/1cIMFgfFhmeNGcRwV-N4c9bH93MjfSi2d/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by BrunoJunior** [comment]
I think you forgot to push Enter after typing «test%test» …

**Comment by BrunoJunior** [comment]
I made the test in PS 1.7.4.4 and 1.7.6.1
1.7.4.4 : 
![ps1744](https://user-images.githubusercontent.com/4368255/64957809-fee63980-d88d-11e9-9f00-e0e4285788db.gif)

1.7.6.1 : 
![ps1761](https://user-images.githubusercontent.com/4368255/64957816-03125700-d88e-11e9-9ba4-bc8a1df1426a.gif)

**Comment by aniszr** [comment]
Hello,

I didn't succeed to reproduce this issue, i think it's solved.
see attached video.

https://github.com/PrestaShop/PrestaShop/assets/92626242/50190da8-5d3c-4449-b9f0-f62783c0eb16


Additional info:
PS version: 8.0.4
PHP version :7.2

Thanks!

**Comment by MatShir** [comment]
@aniszr 👍
