### ISSUE TITLE
Improve pop up information on Category deletion

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#15567]
The information displayed in the pop-up when removing a category is not clear, we should improve the content to make it more understandable. 
![image](https://user-images.githubusercontent.com/35263827/64972811-34991b80-d8aa-11e9-9a2e-2a87075491b1.png)

For instance, there is no information about what is happening for products which belong to 2 different categories when one of them is deleted.

**Comment by LouiseBonnard** [comment]
Hello @colinegin, here is a new suggestion of wording (to keep localized in Admin.Catalog.Notification), feel free to challenge it! I tend to synthesize it in order to get things clearer.

**What do you want to do with the products associated with this category?** 

- If they have no other category, I want to associate them with the parent category.

- If they have no other category, I want to associate them with the parent category and turn them offline. (recommended)

- If they have no other category, I want to delete them as well.

Note that if they have another category, your products will logically remain associated with it.

**Comment by colinegin** [comment]
Great thanks ! Maybe we should just leave the "Recommended" option, so that merchants easily know what they should do. What do you think ?
