### ISSUE TITLE
Subcategory not found with category id when searched for - redirection with the reset button also

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#15588]
In categories, when searching for a category based on category ID, name, description, position or displayed no results are found for subcategories.

**To Reproduce**
1. Go to BO => Catalog => Categories 
2. Click on "View button", Check that you have more than a category
3. Search for a subcategory by ID, name, description, position or displayed 
4. You are redirected to the Category list page

Prestashop 1.7.6
PHP 7.2

**Comment by khouloudbelguith** [comment]
Hi @01park,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.0 & PS1.7.5.2.
Same issue with the reset.
https://drive.google.com/file/d/1CxBBaK0rbktohMYdbJlp6sWM97mrIeHX/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Ping @matks this issue is not fixed
https://github.com/PrestaShop/PrestaShop/issues/10747
Thanks!

**Comment by Progi1984** [comment]
Fixed by #17399
