### ISSUE TITLE
Slow BO on listing products and in FO

### ISSUE THREAD

**Issue by Miestre** [PrestaShop/PrestaShop#15598]
By the way im a noob on programing, and this issue is geting me crazy!
The webpage is slow on FO and BO, but only when load products, on he BO when we select list of products take almost 4 min to load!!
I allready enabled smarty cash, all ccc, cache...but can´t fix this...pls Help 

This is the DEBUG when i try to see the products on BO.

![image](https://user-images.githubusercontent.com/55487556/65139748-0e3bc300-da05-11e9-8f41-c3f979ac2c06.png)

![image](https://user-images.githubusercontent.com/55487556/65139857-42af7f00-da05-11e9-9934-c4eb3c4df99c.png)

![image](https://user-images.githubusercontent.com/55487556/65139920-5ce95d00-da05-11e9-8d84-2e5274a07779.png)

PrestaShop version: 1.6.1.24
PHP version: 5.6.40

**Comment by khouloudbelguith** [comment]
Hi @Miestre,

You can follow these steps:

- `Never recompile template files`: this option is to be chosen for maximum performance.
- `Cache enabled (YES)`: makes pages fastest. 
- `Smart cache for CSS (YES)`: brings together in a single file, compresses and caches CSS files.
- `Smart cache for Javascript (YES)`: brings together in a single file, compresses and caches JS files.
- `Apache Optimization (YES)`: allows to further increase site performance.

In your BO => Modules Manager page => configure the `statsdata` module & check if `Save page views for each customer` is enabled, try to disable it because it uses a lot of CPU resources and database space.

You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
In fact, it takes a very huge space in the database because it collects statistics from connections.
you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019.
Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

Thanks for your understanding!

**Comment by Miestre** [comment]
Thanks for the answer, i followed ur tips, but no sucess, i have de same problem :(
