### ISSUE TITLE
Faceted Search and Pagination

### ISSUE THREAD

**Issue by pantagru** [PrestaShop/PrestaShop#15608]
**Describe the bug**
Problem with faceted search module in connection with pagination, using price filter.
If I use the pagination in a category, moving to last results page and I try to filter by price, the URL maintain de page reference (…page=3…), so the result is for example one product found, but not showed because is not at the page 3.
No problem using others filters in faceted search, the page reference from URL is deleted.

**To Reproduce**
- Go to FO, choose a category.
- Move to last results page (pagination active with 12 products per page).
- Filter by price (highest price).

**Screenshots**
![screenshot-en](https://user-images.githubusercontent.com/41157394/65226646-823e9f80-dac7-11e9-8eb0-86a76d6c9617.jpg)

**Additional information**
PrestaShop version: 1.7.2.4
Ps_facetedsearch version: 3.2.1

**Comment by khouloudbelguith** [comment]
Hi @pantagru,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & ps_facetedsearch v3.3.0.
https://drive.google.com/file/d/13G1wQXF-qBfgxOF2ukZu6Pzg6iiim1S4/view
Same issue with PS1.7.6.1 & ps_facetedsearch v3.0.6.
Same issue with PS1.7.5.2 & ps_facetedesarch v3.3.0.
It was OK with PS1.7.5.2 & ps_facetedsearch v2.2.0.
https://drive.google.com/file/d/1a3xPVQAjOGm_y6P9du3esWoHebsNQSos/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Ping @PierreRambaud

**Comment by PierreRambaud** [comment]
@marionf Can you confirm me that each time you use a facet filter, the pagination must be resetted?

**Comment by marionf** [comment]
@PierreRambaud 
Yes, I think it should be the same behavior for price and weight filters as other filters

**Comment by pantagru** [comment]
Looking at your video (https://drive.google.com/file/d/1a3xPVQAjOGm_y6P9du3esWoHebsNQSos/view)
The main difference that I see is that I can choose the style of the filter (check box or radio 
button) for region or brand filter, not for price filter.
![Screenshot_2019-09-19 Moduli Servizi • Ciboreat](https://user-images.githubusercontent.com/41157394/65262258-36f9b080-db0a-11e9-804f-bfdbcda5e874.png)
Using check box for region or brand filter I don’t have problem with pagination, because checking them the page reference in the URL disappeared.
I’ve also upgraded faceted search module to the last 3.3.0 version, but nothing changes.
