### ISSUE TITLE
Error with hookDisplayDashboardToolbarIcons

### ISSUE THREAD

**Issue by Numalama** [PrestaShop/PrestaShop#15628]
I was following the developper documentation of prestashop. ( link: https://devdocs.prestashop.com/1.7/modules/concepts/hooks/use-hooks-on-modern-pages/). But it seems like the hook displayDashboardToolbarIcons is never load/execute.

Like the example say, in a new module:
 1. I have register the hookdisplayDashboardToolbarIcons using `$this->registerHook('displayDashboardToolbarIcons')`

2.  I have create a non-static public methode, starting with the "hook" keyword for the execution of this hook : 
```
public function hookDisplayDashboardToolbarIcons($hookParams){
   $this->debug_to_console('Hello from hookDisplayDashboardToolbarIcons');
}
```

3. I have reinstall my new module for hook registration.

Note: In all of my modules, I use an function for displaying  data in console, :
```
     /**
      * Function for debug in console directly
      */
    public function debug_to_console( $data ) {
        $output = $data;
        if ( is_array( $output ) ){
            $output = implode( ',', $output);
        }
        echo "<script>console.log( '------------------------------------------------------' );</script>";
        echo "<script>console.log( '--------------[FROM mymodulename]------------------' );</script>";
        echo "<script>console.log( '------------------------------------------------------' );</script>";
        echo "<script>console.log( 'Debug Objects: " . $output . "' );</script>";
        echo "<script>console.log( '------------------------------------------------------' );</script>";
    }
```
In this cas this function help me to know if the hookDisplayDashboardToolbarIcons is load/execute correctly or not.

I have also active the debug mode, the hook is correctly called by my new module.

I have also try with hookDisplayDashboardToolbarTopMenu, with the same process. 
Result: The hook is load/execute correctly and I have an output in the console.

I don't know why but the hookDisplayDashboardToolbarIcons  is never load/execute.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @Numalama,

Since PrestaShop 1.7.3.0, we have introduced two hooks in the Product Catalog page in order to ease contributions on menus.
- `displayDashboardToolbarTopMenu` to add a new action to the top menu
- `displayDashboardToolbarIcons` to add new icons to the Dashboard block => will be available in every Dashboard modern pages.

For more details, you can follow this link: http://build.prestashop.com/news/make-back-office-modules-great-again/
So if you navigate to the BO => Product page => you can execute this hook
I checked with demo module & it is OK
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/3635291/mymodule.zip)

![image](https://user-images.githubusercontent.com/16067358/65317783-5dfcc480-db94-11e9-9c65-5a0ed8cfecbd.png)

I close the issue, feel free to open a new one when needed.
Thanks!

**Comment by pickarooney** [comment]
Has this hook been removed again in Prestashop 8.2? The mymodule example does not work when installed on this version.
