### ISSUE TITLE
Unable to create new supplier when VAT identification number is mandatory

### ISSUE THREAD

**Issue by JuanjoSCu** [PrestaShop/PrestaShop#15622]
If we have the VAT identification number required in countries, a new provider cannot be created.

**To Reproduce**
Go to International -> Locations -> Countries 
Edit Spain (España) 
Switch "Do you need a VAT identification number?" to yes.
Go to  Catalog -> Brands & Suppliers  -> Suppliers 
Add new supplier

![image](https://user-images.githubusercontent.com/40602985/65260182-4119b000-db06-11e9-8903-ee6b49f277ff.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.2

**Comment by khouloudbelguith** [comment]
Hi @JuanjoSCu,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & Ps1.7.6.0.
When we enable the "Do you need a tax identification number?" option a "dni" field added to the address form (not the same behavior at PS1.7.5.2)
In Catalog -> Brands & Suppliers -> Suppliers => Error 500 after creating new supplier
![image](https://user-images.githubusercontent.com/16067358/65260980-360f5180-daff-11e9-92c6-1f03b26940e3.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15685
