### ISSUE TITLE
Breadcrumb is not properly computed for home category

### ISSUE THREAD

**Issue by jocel1** [PrestaShop/PrestaShop#15641]
**Describe the bug**

**To Reproduce**
1. Go to a home category
2. Check the source code. 
3. You can see the breadcrumb contains two elements instead of one, and the second is null.

For example on https://demo-prestashop.prestarocket.com/2-accueil
"breadcrumb":{"links":[{"title":"Accueil","url":"https:\/\/demo-prestashop.prestarocket.com\/"},null],"count":2}

With themes trying to displaying breadcrumb for home it could be annoying, and it also "corrupt" google rich snippets

PrestaShop version: 1.7.6.1

**Comment by JBWModules** [comment]
Duplicate to https://github.com/PrestaShop/PrestaShop/issues/15302

**Comment by khouloudbelguith** [comment]
Hi @jocel1,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & the develop branch.
@JBWModules, your PR is merged in develop
![image](https://user-images.githubusercontent.com/16067358/65413567-9f39e200-dde9-11e9-93b6-50bbb3318d59.png)
But, You can see the breadcrumb contains two elements instead of one, and the second is null.
![image](https://user-images.githubusercontent.com/16067358/65413716-ef18a900-dde9-11e9-8741-ad2f9ebc0788.png)
I’ll add this to the debug roadmap.
Thanks!

**Comment by JBWModules** [comment]
True, it's still wrong in the JS code but with the PRs in development at least it's fixed in the visible part and meta tags relevant for SEO.

**Comment by jocel1** [comment]
@jbwmodules yes but only if you're using the 'standard' theme

**Comment by SNor42** [comment]
Hi!
I don't know what the solution would be, but I would prefer this one:
![exp1](https://user-images.githubusercontent.com/1334351/73102492-3b880880-3ef2-11ea-9046-550616b42a0c.jpg)
Also there is the quite same problem when we try to put the category_id 2 on the top menu. The main link goes to the home, and to the all products page:
![exp2](https://user-images.githubusercontent.com/1334351/73102696-b6e9ba00-3ef2-11ea-8146-0751ce794172.jpg)
Is it possible to fix this too? Thanks
