### ISSUE TITLE
Modern email theme translation and generation

### ISSUE THREAD

**Issue by Traineau** [PrestaShop/PrestaShop#15657]
**Describe the bug**
On PrestaShop 1.7.6. I'm discovering the email system, and I don't understand how the modern theme works. For classic theme everything seems good, i can translate it, generate the templates etc...

But for the modern theme, If I want to generate the templates it only propose me to "erase" classic or the core, I can't "erase" the modern theme because he is not showing. And I really don't get what "erasing" the core means ? 

<img width="1218" alt="Capture d’écran 2019-09-23 à 16 31 05" src="https://user-images.githubusercontent.com/20043825/65434860-d2976380-de1f-11e9-83d5-21a5591e205f.png">

Furthemore when I want to translate it, same thing it only propose me Core and classic, not modern theme. So I can translate the classic themes core, and the Core which is the same for every themes ? But not the modern theme ? I really don't get it.

<img width="1205" alt="Capture d’écran 2019-09-23 à 16 32 19" src="https://user-images.githubusercontent.com/20043825/65434897-e5119d00-de1f-11e9-9b57-7e761c7c8585.png">

**To Reproduce**
1. Install PrestaShop 1.7.6
2. Go to International->Traductions
3. Select Email translations
4. Selet message content
5. Try to select modern theme : It's not showing
6. Reproduce the same for email generation

I don't know if I missed something or if this is a normal behaviour but I can't figure it out. The files does exist in my folder.

PrestaShop version: 1.7.6
PHP version: 7.2

Thanks

**Comment by khouloudbelguith** [comment]
Hi @Traineau,

Here's a PR to Allow modifying email body contents.
Allow modifying email body contents
https://github.com/PrestaShop/PrestaShop/pull/14809
It will be added in the PS1.7.7.
Also, here's a tutorial for Mail Template in PrestaShop
https://github.com/jolelievre/tuto_mailtemplate

Thanks to check & feedback.

**Comment by Traineau** [comment]
Hello @khouloudbelguith hope you're doing well
Thanks for those informations, but I'm not sure that this PR will fix this. It seems that it will allows us to modify the body content of any theme without using the Core right ?

I'm just wondering if this is a normal behaviour that i'm not seeing "modern" template anywhere in my back-office, for now this forces me to work with the classic theme which is, well, pretty ugly...

**Comment by Traineau** [comment]
Oh and by the way I couldn't install the tutorial module you showed me :/ 

<img width="804" alt="Capture d’écran 2019-09-23 à 17 25 15" src="https://user-images.githubusercontent.com/20043825/65439235-20fc3080-de27-11e9-8c9c-cd0b6feac255.png">

**Comment by khouloudbelguith** [comment]
@Traineau, I attached a screen record.

https://drive.google.com/file/d/1lG4SirGlK2v0xPjQfvXnvz3IFgOnSSl7/view
here's a zip file of this module
[tuto_mailtemplate.zip](https://github.com/PrestaShop/PrestaShop/files/3642905/tuto_mailtemplate.zip)

Thanks!

**Comment by Traineau** [comment]
Thanks @khouloudbelguith but as I said, it woks for me as well with the classic theme but not the "modern" one, are you able to do the same with the "modern" theme ?

**Comment by khouloudbelguith** [comment]
@Traineau, but modern is not a theme, it is mail template.
So, in the BO, you can see the core & the theme added from the BO => Design => Theme & Logo.

Thanks!

**Comment by Traineau** [comment]
Ooooohh okey I was confused between classic theme and classic mail template. I understand now how the whole thing works, and the translation problem I had when changing theme seems to be resolved by https://github.com/PrestaShop/PrestaShop/pull/15139 .

Thanks @khouloudbelguith, closing this sorry for bothering you

**Comment by khouloudbelguith** [comment]
@Traineau, thanks!
Feel free to open a new one when needed.

**Comment by jolelievre** [comment]
Hi @Traineau,
indeed as @khouloudbelguith explained there is a difference between the shop theme and the email theme. It's even more confusing because each one has a "classic" theme by default. There's probably room for improvement in this section.

The issue you mentioned #15139 fixed some missing translation in our catalog, which made the new modern theme to have missing translations. However in 176 you can't edit these translation keys yet. When you go the the Translation back office page and try to edit Email content you get access to the old way of translating emails, which is by editing the html files directly.

In the coming 177 version we are going to add a feature to translate these keys which will then allow to generate the email themes with custom wordings (see this PR https://github.com/PrestaShop/PrestaShop/pull/14809)

Oh and by the way about the exemple module, the on you tried was a very simple tuto I used for a presentation, I recommend you use this module instead https://github.com/PrestaShop/example_module_mailtheme Which has more advanced feature (like color customization of the modern theme).

But remember you can't install it via an archive (Github archive doesn't have the format expected by PrestaShop), so you should follow the installation instruction in the Readme file to install it manually.
