### ISSUE TITLE
Faceted Search : display "name" instead of "public_name" for attributes filters

### ISSUE THREAD

**Issue by JulienNDKgroup** [PrestaShop/PrestaShop#15688]
Hi,

The faceted search module is using the column "name" instead of the column "public_name" when we use a attribute as a filter. Is it possible to change it or we have to rename the attribute ?

I declare the issue here because there is no answer on the forum for this [topic](https://www.prestashop.com/forums/topic/999188-faceted-search-display-filter-as-public-name-not-bo-name/) .

Thanks in advance.

**Comment by khouloudbelguith** [comment]
Hi @JulienNDKgroup,

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & ps_facetedsearch v3.3.0.
The public name is not displayed
![image](https://user-images.githubusercontent.com/16067358/65605440-03eb6d00-dfa1-11e9-905b-a7f69bea9207.png)
![image](https://user-images.githubusercontent.com/16067358/65605651-63497d00-dfa1-11e9-99a5-a65aca91786c.png)

I tried with ps_facetedesarch v2.2.1 => OK
![image](https://user-images.githubusercontent.com/16067358/65605636-57f65180-dfa1-11e9-83d6-56b99a9355b9.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Ping @PierreRambaud 
Thanks!

**Comment by JulienNDKgroup** [comment]
Thanks for your fast answer !

I tried to fix it, but it seems to be inside one of the core php file in the module ( Like ps_facetedsearch.php or another one). We don't want to override one of those file just for that because for futures upgrades.

Best Regards.
