### ISSUE TITLE
Migration 1.6 to 1.7

### ISSUE THREAD

**Issue by Miestre** [PrestaShop/PrestaShop#15719]
Hello

I have a theme that we worked on the past (html and css changes)(1.7)

And we have a website on version 1.6. that is online and working.

My question is..what is the best the best approach to migrate all the data(clients, orders, products, modules) from the 1.6 site to the theme 1.7?

Regards

**Comment by khouloudbelguith** [comment]
Hi @Miestre,

Please follow our documentation: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/, it describes several ways to complete an upgrade of PrestaShop.
In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
I close the issue, feel free to open a new one when needed.
Thanks for your understanding!
