### ISSUE TITLE
Wrong combinaison reference in customer account order history

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#15717]
**Bug description**
After purchasing a product (combinaison), go to the order history on your customer account, in the list of products you will find that the reference shows for the combinaison is that of the parent product.

**how to Reproduce**
1. Create a product with combinations (set product reference et combination reference)
2. Order the product combination in the front-office
3. In your **customer account > order details > produts list**  the reference shown is that of the parent product

**Screenshots**
https://drive.google.com/file/d/1pZ3v9K9Zo0XXIVDARbI1yXCfAaGAB5Bb/view

**Additional information**
PrestaShop version:  > 1.7.5.x
PHP version: 7.2
Server : Apache 2.0

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/65861455-31029b80-e364-11e9-8526-b89bd830ae10.png)
In the BO it iS oK
![image](https://user-images.githubusercontent.com/16067358/65861491-45df2f00-e364-11e9-9f35-fcfaece7d9c4.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by PululuK** [comment]
Hi @khouloudbelguith 

This has been fixed here:  https://github.com/PrestaShop/PrestaShop/pull/15706
