### ISSUE TITLE
The product selection cannot be delivered by the available carrier(s): it is too heavy. Please amend your cart to lower its weight.

### ISSUE THREAD

**Issue by Prem-lmx** [PrestaShop/PrestaShop#15722]
Hai..
im work on prestashop1.6.23
The order  issue some products only
ples support him..
screenshot:
![image](https://user-images.githubusercontent.com/52959027/65744779-0d96e100-e117-11e9-9b2d-2650ff7bbb9f.png)
waiting for the response....
Thanks..

**Comment by khouloudbelguith** [comment]
Hi @Prem-lmx,

I did not manage to reproduce the issue with PS1.7.6.1.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks for your understanding!

**Comment by jointsystems** [comment]
Check you **Localization** to see if you have the right default country and measurements.  Import the settings for your default country.
