### ISSUE TITLE
Error in blockreassurance version 4.1.0

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#15807]
Hi
in the product page I get this error if I enable the module blockreassurance on the product page.
I've unistalled and removed the previous folders and then installed the version 4.1.0 but the error continue to be present

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/66116866-c48dd380-e5d3-11e9-97f2-56523e70c15d.png)

**Additional information**
PrestaShop version: 1.7.5.2
PHP version: 7.2

**Comment by Maofree** [comment]
in my demo site with classic theme there are not errors
I can pass you the access of that site

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I did not manage to reproduce the issue wit PS1.7.6.1 &  `blockreassurance` module after upgrade from 3.0.1 to 4.1.0.
![image](https://user-images.githubusercontent.com/16067358/66119085-3c5dfd00-e5d8-11e9-988b-366e9153ec12.png)

But it occurs with PS1.7.5.2 & the `blockreassurance` v4.1.0
![image](https://user-images.githubusercontent.com/16067358/66118956-ec7f3600-e5d7-11e9-960d-d7602e48aaec.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
Fixed by https://github.com/PrestaShop/blockreassurance/pull/30
