### ISSUE TITLE
E-mail subscription <br><em> tags

### ISSUE THREAD

**Issue by N-Wouda** [PrestaShop/PrestaShop#15849]
**Describe the bug**
The e-mail subscription appears to escape its `<br>` and `<em>` tags, such that they end-up in the user text. See below for a screenshot.

**To Reproduce**
1. Install e-mail subscription module, e.g. 2.5.1
2. Fill in some string for the conditions field
3. Go to account -> personal information/identity in the FO

**Screenshots**
![email_subscription_issue](https://user-images.githubusercontent.com/16272507/66303781-0ed8c280-e8fc-11e9-95b5-977b49d5e6f0.png)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1.32

**Comment by khouloudbelguith** [comment]
Hi @N-Wouda,

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & the ps_emailsubscription v2.5.1 & v2.3.0.
Only in the Footer => NOK.
![image](https://user-images.githubusercontent.com/16067358/66305088-e4d4cf80-e8fe-11e9-974b-7e8c68a89569.png)

In the account -> personal information/identity => it is OK
![image](https://user-images.githubusercontent.com/16067358/66305171-09c94280-e8ff-11e9-8952-3ff8c4e5ed1a.png)

It is not a regression
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!


Thanks!
