### ISSUE TITLE
Bug add to cart without cookie session 

### ISSUE THREAD

**Issue by serumandco** [PrestaShop/PrestaShop#15878]
#### Describe the bug
When my cookie session is not generate, i can not add product to the cart at first time. 
The popin add to cart is empty. 

#### Steps to reproduce 
1- Go to http://demo.prestashop.com/#/en/front on a product page
2- flush your cookies
3- add the product to the cart 
You'll see the confirmation popin empty.

**Screenshots**

https://drive.google.com/file/d/1t8EbiJ3S5KvcSGotq9Lxr_gJbUKPBmCW/view

![cookie](https://user-images.githubusercontent.com/12627679/66469718-a703b280-ea88-11e9-832d-896c2e2fd543.PNG)
![cart](https://user-images.githubusercontent.com/12627679/66469719-a703b280-ea88-11e9-98bd-7f7c896ca364.PNG)

#### Additional infos:

- Prestashop version: 1.7.7.2
- PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SerumAndCo,

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.0 & PS1.7.5.2.
https://drive.google.com/file/d/1t8EbiJ3S5KvcSGotq9Lxr_gJbUKPBmCW/view
If we click the second time => OK.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by destrosvet** [comment]
Hi,
I think we are facing similar problem with PS 1.7.6.1. Without any cookie from website, it is impossible to add something to cart ("There are not enough products in stock" message popup) . You have to press multiple times "add cart" button. If you have cookie it is working fine. Reproducing is same as @SerumAndCo - only different message (could be theme related). I think shouldn't be tagged as trivial.

**Comment by NeOMakinG** [comment]
As with discussed with the team, it looks like it's not my job but maybe backend one

**Comment by danielgasser** [comment]
Does anyone have a fix for this? This is a really annoying bug! And I find it alarming that this bug is labeled as "Minor". I mean, not being able to add products to a cart is everything else than minor isn't it?

**Comment by msaustral** [comment]
Hi this happen to one of our customer after updating the Customer Reassurance module to v. 5.0.0, try to disable it

**Comment by danielgasser** [comment]
> Hi this happen to one of our customer after updating the Customer Reassurance module to v. 5.0.0, try to disable it

This installation does not have that module installed

**Comment by simulbeni** [comment]
I am facing same issue from 1 year.  Please get some information.

Cookie object with proper info

Cookie Object
(
    [_content:protected] => Array
        (
            [date_add] => 2020-08-07 11:05:14
            [id_lang] => 2
            [lgseoredirect_user_pagination_1] => 10
            [lgseoredirect_last_offset_1] => 1
            [id_currency] => 1
            [lgseoredirect_user_pagination_8] => 10
            [lgseoredirect_last_offset_8] => 1
            [last_visited_category] => 3
            [lgseoredirect_user_pagination_6] => 10
            [lgseoredirect_last_offset_6] => 1
            [lgseoredirect_user_pagination_3] => 10
            [lgseoredirect_last_offset_3] => 1
            [lgseoredirect_user_pagination_4] => 10
            [lgseoredirect_last_offset_4] => 1
            [ordertrackedmanually] => 0
            [check_cgv] => 
            [lgseoredirect_user_pagination_12] => 10
            [lgseoredirect_last_offset_12] => 1
            [id_guest] => 86
            [id_connections] => 458
            [id_cart] => 36817
            [checksum] => 827744006
        )

    [_name:protected] => PrestaShop-e76786d1afbbde310379311ade12e69e
    [_expire:protected] => 1601568803
    [_domain:protected] => .123bigbags.com.loc
    [_path:protected] => /
    [cipherTool:protected] => PhpEncryption Object
        (
        )

    [_modified:protected] => 
    [_allow_writing:protected] => 1
    [_salt:protected] => tNjxBH8B
    [_standalone:protected] => 
    [_secure:protected] => 1
)

Cookie object with wrong info

Cookie Object
(
    [_content:protected] => Array
        (
            [date_add] => 2020-09-11 19:14:28
            [id_lang] => 2
            [id_currency] => 1
            [last_visited_category] => 3
        )

    [_name:protected] => PrestaShop-4dbcb037b75ff1b97f260f16cf72998c
    [_expire:protected] => 1601572468
    [_domain:protected] => .bigbagland.com
    [_path:protected] => /
    [cipherTool:protected] => PhpEncryption Object
        (
        )

    [_modified:protected] => 1
    [_allow_writing:protected] => 1
    [_salt:protected] => B2LuNybd
    [_standalone:protected] => 
    [_secure:protected] => 
)

**Comment by hibatallahAouadni** [comment]
Related to #22711
Even when the issue mentioned above has been fixed on develop branch but I still manage to reproduce this issue on develop branch :sweat:

**Comment by davidcylke** [comment]
im having same issue on 1.7.7.6

**Comment by psyray** [comment]
Same issue with 1.7.6.9
@khouloudbelguith Is there a fix ?
It's really a high severity problem. Could you level up the resolution ?
It's tagged as minor, while it's not !!!

**Comment by msaustral** [comment]
Hi everybody can you send some more info?
screen of incognito window showing the cookies
did you modify the class Cookie.php? 
or do you have any override of that class?
what about your server?
it is a legacy server or container?
apache or nginx or other? 
regulas php or php-fpm?
what versión?

**Comment by psyray** [comment]
@msaustral 
Same workflow as @khouloudbelguith 
https://github.com/PrestaShop/PrestaShop/issues/15878#issuecomment-539940080

Here's the preview of an xdebug session of the problem
![image](https://user-images.githubusercontent.com/1230954/134377392-a668c37f-4a6d-4a4a-a9a3-f20370ba0e52.png)

The cookies of the call
![image](https://user-images.githubusercontent.com/1230954/134377654-8117d16a-e28a-4fd7-a4bf-c1a1f632587a.png)

The shop don't have any override
Class Cookie not modified

Technical informations
![image](https://user-images.githubusercontent.com/1230954/134378051-cd577dd1-1f96-4e80-a597-bf49048e8c8a.png)

Cookie content
![image](https://user-images.githubusercontent.com/1230954/134378419-20e93799-7013-4524-9511-b82a90a076d0.png)

Screen of the add to cart result
![image](https://user-images.githubusercontent.com/1230954/134381700-252d62d0-387b-410c-8b6e-771a0effcc28.png)

The modal is displayed because `_products` property in the `$this->context->cart` is empty

Tell me if you need some more informations, i'm always in debug mode

**Comment by psyray** [comment]
Screen of the add to cart result
![image](https://user-images.githubusercontent.com/1230954/134381700-252d62d0-387b-410c-8b6e-771a0effcc28.png)

The modal is displayed because `_products` property in the `$this->context->cart` is empty

**Comment by msaustral** [comment]
Hi @psyray your error is different, your cart is not empty, the PS does not allow you to buy because it say "there are not enough products in stock"

Did you migrate from 1.6 to 1.7?

**Comment by psyray** [comment]
My cart is empty
Forget about the message, it comes from the theme.
Problem is the same, 1st time add, with cookie flushed before (new incognito window), product is not added to cart.
2nd time it works.
The condition for the error message in the theme is this one
```
            {if $product}
            <div class="modal-header">
                <span class="modal-title"><i class="fa fa-check rtl-no-flip"
                                             aria-hidden="true"></i> {l s='Product successfully added to your shopping cart' d='Shop.Theme.Checkout'}</span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
...
        {else}
        <div class="modal-header">
            <span class="modal-title"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {l s='There are not enough products in stock' d='Shop.Theme.Checkout'}</span>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="cart-content">
                        <div class="cart-content-btn">
                            <button type="button" class="btn btn-secondary btn-block"
                                    data-dismiss="modal">{l s='Continue shopping' d='Shop.Theme.Actions'}</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {/if}
```

**Comment by msaustral** [comment]
Can you send me a dev environment on a temporary server?

**Comment by psyray** [comment]
Yes I will setup and send it to you.
How can I contact you in private ?

**Comment by psyray** [comment]
Dev server is set up, bug is also present.
Waiting for your feedback

**Comment by psyray** [comment]
I've sent url on your email address from your website

**Comment by msaustral** [comment]
Hi sorry i did not get you email, please send it to info@msaustral.com

**Comment by psyray** [comment]
I think I found the problem, it cames from 2 parts

### First run, refresh the product page, flush your cookie
![image](https://user-images.githubusercontent.com/1230954/134437989-2c3957f9-f901-48e7-8f11-18e8f73a1751.png)

![image](https://user-images.githubusercontent.com/1230954/134438004-93425bcf-8d09-45f0-8524-c351b2df6bf7.png)

And the JSON response

![image](https://user-images.githubusercontent.com/1230954/134438385-02a180db-59e0-457c-b499-fcc194ea3b21.png)

As the comment says in the [code](https://github.com/PrestaShop/PrestaShop/blob/2c059b93062ce25bbde22355982e651215544e81/controllers/front/CartController.php#L240) while checking cookie **BEFORE** adding the product to the cart context
```
// Update the cart ONLY if $this->cookies are available, in order to avoid ghost carts created by bots
```
But how can we make the difference between a browser with no cookie and a bot by basing only on the `$_COOKIE` var ?!?!?
It can't, so the adding process is bypassed, and potentially a customer, who's never visited the site, and access a product page directly from a search engine or a link, is facing the empty cart popin
Not good, and critical for me


### Second run, cookie was created by the precedent run
No problem, product is correctly added to the cart context because the cookie exists


### Conclusion

So, this bug is present on all version of Prestahop 1.7 (I've checked the code, this check was present in 2017, maybe before).

To exactly reproduce the bug check the @khouloudbelguith screen record
https://github.com/PrestaShop/PrestaShop/issues/15878#issuecomment-539940080

I've tested on the current demo of Prestashop, bug still there at this time

So you (we) need to fix this annoying problem.


### Fix (but has drawbacks)

Remove the check on the cookie, problem is gone, everything is working well, but every bot who visit the site could create ghost cart.
```php
    protected function updateCart()
    {
        // Update the cart ONLY if $this->cookies are available, in order to avoid ghost carts created by bots
        if (!$this->errors
            && !($this->context->customer->isLogged() && !$this->isTokenValid())
        ) {
            if (Tools::getIsset('add') || Tools::getIsset('update')) {
                $this->processChangeProductInCart();
            } elseif (Tools::getIsset('delete')) {
...
```
### To fix it on the long term

The method **exists()** of the **Cookke** class is exclusively used for this check, no other code use it.
It checks on the ``$_COOKIE`` PHP super global var, so we need to improve this too basic check to differentiate a real customer from  a bot

Any idea ?
It should have this kind of check elsewhere in Prestashop, right ?

EDIT
Found it
https://github.com/PrestaShop/PrestaShop/blob/2c059b93062ce25bbde22355982e651215544e81/classes/Connection.php#L141-L145

We could extract this check, make a method and use it for the cart.
I will do a PR

**Comment by msaustral** [comment]
Hi use cloudflare to avoid bots

**Comment by psyray** [comment]
> Hi use cloudflare to avoid bots El mié, 22 de sep. de 2021 a la(s) 21:40, Psyray ***@***.***) escribió:

Not the problem here, the problem is add to cart not working

**Comment by msaustral** [comment]
try to migrate the info to a fresh installation without installing additional modules, PS 1.7.x.x do not have this problem, we do have many installation working.

**Comment by psyray** [comment]
Go to the demo and make the @khouloudbelguith step and you'll see
https://drive.google.com/file/d/1t8EbiJ3S5KvcSGotq9Lxr_gJbUKPBmCW/view

I know Prestashop and I've saw this bug on a lot of customers so stop giving me bad advice, this issue is here for that and problem is confirmed

I know also [this problem](https://www.prestashop.com/forums/topic/626488-ps-17x-problem-with-cookies-sometime-not-working-addtocart/?_fromLogin=1#replyForm), due to migration (cart table not migrated and problem with identical id in order table `id_cart` column)
I've applied the **AUTOINCREMENT** modification too, but it did not solve the problem (maybe others later in the order process)

This bug is also present on 1.6 version.

I think this problem was not detected before GDPR, because until this, cookies was always set. Now, depending on the module, cookie could be blocked until you click accept.

**Comment by matks** [comment]
> It's tagged as minor, while it's not !!!

The label "minor" has a specific meaning, see https://devdocs.prestashop.com/1.7/contribute/contribution-process/how-issues-are-sorted/#issue-severity-criteria

Maybe it seems a major bug for you, but the label "minor" is simply an information. We could also say "bug level 1, 2 or 3' 😄 .

> So you (we) need to fix this annoying problem.

It's great 😄  as you can it's not just us, it's all of us together. It's great you explored the issue and submitted a PR. This is the open source spirit 😉  .

**Comment by psyray** [comment]
Look at my PR
https://github.com/PrestaShop/PrestaShop/pull/25972
Everything is explained
