### ISSUE TITLE
Bug in Customer CSV Export column email

### ISSUE THREAD

**Issue by elia-c** [PrestaShop/PrestaShop#15875]
Go to Customers > Customers
Click on Export

In the exported CSV, the column email is filled with the customer's firstname instead of email

Source:
src\PrestaShopBundle\Controller\Admin\Sell\Customer\CustomerController.php

line 690:
'email' => $record['firstname'],

**Comment by khouloudbelguith** [comment]
Hi @elia-c,

Thanks for your report.
I manage to reproduce the issue with ps1.7.6.0 & ps1.7.6.1.
![image](https://user-images.githubusercontent.com/16067358/66465582-6bb1b580-ea81-11e9-9701-35874ca8c97f.png)
Here's the file exported

[customer_2019-10-09_103451.csv.txt](https://github.com/PrestaShop/PrestaShop/files/3706414/customer_2019-10-09_103451.csv.txt)

It is Ok with PS1.7.5.2. It is a regression.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Hello!

The Lastname is incorrect also.
![image](https://user-images.githubusercontent.com/16067358/66471992-9e14e000-ea8c-11e9-9f4c-c22ede0125e6.png)

It is OK ps1.7.5.2
