### ISSUE TITLE
Admin url rewrite problems

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#15913]
Hi,
Im facing a fascinating bug in admin url rewriting.
Take a look at example.

This is how the links looks like.
I can enter in Carriers link but i can't open Preferences link because of invalid token (login screen occour)

Its related with variable:

var admin_modules_link = '{$link->getAdminLink("AdminModulesSf", true, ['route' => "admin_module_catalog_post"])|addslashes}';

But how to fix it?

```
<ul id="collapse-58" class="submenu panel-collapse">
	<li class="link-leveltwo " id="subtab-AdminCarriers" data-submenu="59">
		<a href="https://my-dom-ain.lol/admin/index.php?controller=AdminCarriers&amp;token=**a1f2758d0bf00829f756cfbe99dd1d99**" class="link">
			Carriers (LINK IS OKAY!)
		</a>
	</li>
	<li class="link-leveltwo " id="subtab-AdminShipping" data-submenu="60">
		<a href="/myhostingaccountname/my-dom-ain_catalog/admin/index.php/improve/shipping/preferences?_token=**iiffpe5G7IYX6vxzENy8g6kCQ_H7G-xQs10e_U7XuLU**" class="link">
			Preferences (LINK CAUSING SIGNOUT - CANT ENTER -> DIFFERENT TOKEN :O)
		</a>
	</li>
</ul>
```
PS 1.7.5.2
PHP 1.7.2
IdeaWebServer (Home.pl) "like" Apache

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

Your issue is related to cookies.
Here are some things you can try :

1/ Clear your browser cache and your cookies

2/ Check PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL in ps_configuration table

3/ Manually clear smarty cache: remove all files from /var/cache/

4/ Disable the IP check in classes/Cookie.php (this can cause many issues with dynamics IP)

5/ Into the path /PROJECT_FOLDER/classes/controller/AdminController.php, replace 900 to 3600 which increases the log-in period from 15 to 60 minutes.
replace this:
`if ($this->context->cookie->last_activity + 900 < time()) {`

By this:

`if ($this->context->cookie->last_activity + 3600 < time()) {`

Thanks to check & feedback.

**Comment by ghost** [comment]
Hi, 
Thanks for Your time @khouloudbelguith 

It's nasty and related with webhosting company settings... @home.pl...

Closed!

**Comment by khouloudbelguith** [comment]
@PrestaShark, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
