### ISSUE TITLE
blockreassurance: there is no way to delete a reassurance block

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#15935]
Oups, there is no delete button.

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks!
You are right.
Old version
![image](https://user-images.githubusercontent.com/16067358/66760389-4a4a3280-eea2-11e9-97a7-e5d07b2a53a5.png)

The new version doesn't exist
![image](https://user-images.githubusercontent.com/16067358/66760455-6ea60f00-eea2-11e9-83c7-34c5ceb8d58f.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
ping @Progi1984

**Comment by Progi1984** [comment]
Euh.... Yes : I contact the PO Team ;)

Poke @colinegin & @PrestaShop/prestashop-product-team

**Comment by colinegin** [comment]
Indeed, it seems this option was not in the mock ups and initial specs.
We need to add it in the available options for each "reassurance label".
The behaviour is the same as on migrated listings on back office : 

- remove the edit icon
- add 3 dots icon
- by clicking on this icon, edit and remove options need to be displayed.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/blockreassurance/pull/37
