### ISSUE TITLE
Update database error #1292 - Incorrect date value: '0000-00-00' for column

### ISSUE THREAD

**Issue by frevab** [PrestaShop/PrestaShop#15948]
After an update of MySQL to 5.7.27 one of my webshops is not working anymore. The front office does not shows any products. only if you know a direct link to a specific product you get to see it but nothing on the front office, only specific theme images or links to CMS etc work fine.
As this shop runs on old PS 1.5.4.1 I suppose  it does not work with MySQL 5.7.27 ?
To see if this is the case, I have started updating a copy of the database manually but got stuck with 1.6.0.11.sql and get error "#1292 - Incorrect date value: '0000-00-00' for column 'available_date' at row 1" when it has to change the decimals in Table PREFIX_product attribute.
Also when I want to change the decimals myself instead of running the SQL-query I get the same error and won't save this change.

I want to get the database upto PS 1.7 and use it wth a clean install of PS 1.7 to see if it work work with the default theme.

I read something online about the change of year from 2 to 4 and also something about Strict mode: 
_Strict mode affects whether the server permits '0000-00-00' as a valid date: If strict mode is not enabled, '0000-00-00' is permitted and inserts produce no warning. If strict mode is enabled, '0000-00-00' is not permitted and inserts produce an error, unless IGNORE is given as well. For INSERT IGNORE and UPDATE IGNORE, '0000-00-00' is permitted and inserts produce a warning._

What do I have to do to continue this manual database update.

**Comment by khouloudbelguith** [comment]
Hi @frevab,

PrestaShop previous versions < 1.6.1.4 uses 0-dates a lot which makes it incompatible with MySQL 5.7.
Changing your server configuration is the best way, however, if you can't modify it, you can apply this fix: https://github.com/PrestaShop/PrestaShop/pull/4507/files
About PrestaShop1.7, PrestaShop needs MySQL: 5.0 minimum, 5.6 or later recommended.
Thanks to follow this link: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

There are two ways to upgrade PrestaShop:

1. Automatic: for the 1.5: you can use the 1-click upgrade v1.6.8, for PS1.6 => 1.7, you can use 1-click upgrade v4.9.0
https://addons.prestashop.com/en/data-migration-backup/5496-.html
2. Manual: for PS1.5, you can follow this link: http://doc.prestashop.com/display/PS15/Manual+update
For PS1.6, you can follow this link: http://doc.prestashop.com/display/PS16/Manual+update
For PS1.7, you can follow this link: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#manual-upgrade-process-details

Thanks to check & feedback.

**Comment by frevab** [comment]
Hello @khouloudbelguith 

Thank you for your help.

Is it possible that shop with PS 1.5.4.1 gives problems after upgrade MySQL to 5.7.27 ?  I checked upgrade logs and all tables of database said status OK.

You write: for the 1.5: you can use the 1-click upgrade v1.6.8.  The link goes to v.4.9.0 in PS Module shop.  Where can I download v.1.6.8 ?

**Comment by khouloudbelguith** [comment]
@frevab, 
>Is it possible that shop with PS 1.5.4.1 gives problems after upgrade MySQL to 5.7.27 ?

Yes, as I said before: PrestaShop previous versions < 1.6.1.4 uses 0-dates a lot which makes it incompatible with MySQL 5.7.
Changing your server configuration is the best way, however, if you can't modify it, you can apply this fix: https://github.com/PrestaShop/PrestaShop/pull/4507/files => it is available in the PS1.6.1.4.

>Where can I download v.1.6.8?

From this link: https://addons.prestashop.com/en/data-migration-backup/5496-.html
![image](https://user-images.githubusercontent.com/16067358/66902308-ba6eca80-f000-11e9-8d3b-658bfea2e122.png)

PS: we don't support PS1.5 yet & as you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks for your understanding!
