### ISSUE TITLE
Unable to select product combination, because you need to go via a combination that is out of stock. Front 1.7.7.0

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#15960]
**Steps to reproduce the issue:**
1-Create a product with combinations. Put stock in some combination but not in all.
2- Disable the option "Allow to buy products out of stock."
3-Disable the option "Display unavailable product attributes on the product page" in the Product Settings page
4-In FO, combinations out of stock can not be selected
See screenshot for complete description of issue:

![Screenshot 2019-10-15 12 42 52](https://user-images.githubusercontent.com/30602638/66825269-4376fa80-ef4a-11e9-92d7-93407f66fb4d.png)

Try to select "Size - S, Color - White". Impossible, since you need to go via another combination that is out of stock.

Tested on develop branch at commit: b60f6ce.

**This does not fix it:**
https://github.com/PrestaShop/PrestaShop/pull/14452

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

Thanks, I manage to reproduce the issue with develop branch & PS1.7.6.1.
Steps to reproduce the issue:
1-Create a product with combinations. Put stock in some combination but not in all.
2- Disable the option "Allow to buy products out of stock."
3-Disable the option "Display unavailable product attributes on the product page" in the Product Settings page
4-In FO, combinations out of stock can not be selected

https://drive.google.com/file/d/1YoTsG5tSydgnhtQAYhWWXiMhbWOTXTd_/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Ping @Progi1984
Thanks!

**Comment by madsoliver** [comment]
Great!
I noticed that actually deleting the combinations that had qty = 0, made it work as expected. 
Even though, that is definitely not a solution, it might be useful to know when trying to fix the issue.

**Comment by marionf** [comment]
@khouloudbelguith It seems to be a duplicate of #9948

**Comment by khouloudbelguith** [comment]
Hi @marionf, yes, you are right.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

Your ticket is a duplicate of #9948
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9948
