### ISSUE TITLE
Prestashop 1.7.6.1 with PHP 7.1 and 7.2 gives blank page order confirmation

### ISSUE THREAD

**Issue by jajarom** [PrestaShop/PrestaShop#15990]
**Describe the bug**
Prestashop 1.7.6.1 with PHP 7.1 and 7.2 gives blank page order confirmation.
With php 7.0 all works well.
Warehouse compatible with PHP 7.1 and 7.2

Stack trace:
#0 /home/dual34/public_html/new/classes/Mail.php(323): MailCore::toPunycode('jajarom@yahoo.c...')
#1 /home/dual34/public_html/new/classes/order/OrderHistory.php(552): MailCore::send(12, 'bankwire', 'A\xC8\x99teaptare pla...', Array, 'jajarom@yahoo.c...', 'Test Test', 'contact@gpg.ro', 'GPG Mobile', NULL, NULL, '/home/dual34/pu...', false, 1)
#2 /home/dual34/public_html/new/classes/order/OrderHistory.php(468): OrderHistoryCore->sendEmail(Object(Order), Array)
#3 /home/dual34/public_html/new/classes/PaymentModule.php(549): OrderHistoryCore->addWithemail(true, Array)
#4 /home/dual34/public_html/new/modules/ps_wirepayment/controllers/front/validation.php(64): PaymentModuleCore->validateOrder(12742, '10', 275, 'Plata prin tran...', NULL, Array, 7, false, 'e1d03453f6b9d44...')
#5 /home/dual34/public_html/new/classes/controller/Controller.php(281): Ps_WirepaymentValidationModuleFrontController- in /home/dual34/public_html/new/classes/Mail.php on line 901

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1/7.2 not working

**Comment by khouloudbelguith** [comment]
Hi @jajarom,

This issue is occurred due to `php-intl` extension.
Could you please try to install it, it is required.
![image](https://user-images.githubusercontent.com/16067358/66989185-20705600-f0c4-11e9-99da-ef10e9105eb4.png)

Thanks to check and feedback.

**Comment by jajarom** [comment]
Thank you, working :)

**Comment by khouloudbelguith** [comment]
@jajarom, so, the issue is fixed?

Thanks!

**Comment by jajarom** [comment]
Yes,

But i have server error when i upload a picture, or i want to install another module

**Comment by khouloudbelguith** [comment]
@jajarom, your issue reported is

>Prestashop 1.7.6.1 with PHP 7.1 and 7.2 gives blank page order confirmation.

>But i have server error when i upload a picture, or i want to install another module

This is another issue? in which page => uploading the image doesn't work? what is the exact module?

Thanks!

**Comment by jajarom** [comment]
In Back Office when uploading imegae to store.
Module i try is v1.2.1-ps_emailsmanager.

**Comment by khouloudbelguith** [comment]
@jajarom, As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!

**Comment by jajarom** [comment]
![Prestazz](https://user-images.githubusercontent.com/5030991/67005005-3a249400-f0ea-11e9-8c7d-8c79d22a7835.jpg)

Module translate uploading image. This happens

**Comment by jajarom** [comment]
Module is from Prestashop

https://addons.prestashop.com/en/administrative-tools/25939-.html

**Comment by khouloudbelguith** [comment]
@jajarom, the screenshot is provided from the translation page?

Thanks!

**Comment by jajarom** [comment]
Yes.
Module error is beacauze zip disabled in php

**Comment by khouloudbelguith** [comment]
@jajarom, so after adding the zip extension, it is OK?

Thanks!

**Comment by jajarom** [comment]
The problem with module, yes.
The image uploading problem not fixed yet

**Comment by khouloudbelguith** [comment]
@jajarom, It is OK in my side
https://drive.google.com/file/d/1taTa1FYpyRVdXHVA9EDJnc4j4P6QtDA_/view
Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.
![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)

Thanks to check and feedback.

**Comment by jajarom** [comment]
![Screenshot_2019-10-17 PHP PrestaShop Info](https://user-images.githubusercontent.com/5030991/67027340-065d6480-f112-11e9-871e-472296c7dbd9.png)

**Comment by jajarom** [comment]
Must enable fileinfo to fix this

**Comment by khouloudbelguith** [comment]
Hi @jajarom,

Yes, in your case, you need to enable `allow_url_fopen`, it is required and you need to install `Fileinfo` extension.

I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by kitseller** [comment]
Hello Guys.

Need some help to solve this problem please:

It happens when selecting native payment (wire transfer)

![screenshot-kitseller pt-2020 03 (2)](https://user-images.githubusercontent.com/62908158/77956132-4895ef00-72c9-11ea-9c9b-62fa39ff47fc.png)

**Comment by khouloudbelguith** [comment]
Hi @kitseller,

This issue is fixed in the PrestaShop version 1.7.4.0.
Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/9080 to fix the issue.
Also, you need to check that the `php-intl `extension is installed on your server.
If you are using the `ps_emailalerts` module, In the "MERCHANT NOTIFICATIONS" part, if we have an E-mail address with Special chars for example "deméo@prestashop.com", when I create an order FO & I finish it, I have this error message as reported here: https://github.com/PrestaShop/PrestaShop/issues/9638

Thanks!

**Comment by kitseller** [comment]
php-intl extension installed and solved my problem.

 

Thanks a lot!!

 

 

 

De: khouloudbelguith [mailto:notifications@github.com] 
Enviada: 31 de março de 2020 09:27
Para: PrestaShop/PrestaShop
Cc: kitseller; Mention
Assunto: Re: [PrestaShop/PrestaShop] Prestashop 1.7.6.1 with PHP 7.1 and 7.2 gives blank page order confirmation (#15990)

 

Hi @kitseller <https://github.com/kitseller> ,

This issue is fixed in the PrestaShop version 1.7.4.0.
Here's the PR: #9080 <https://github.com/PrestaShop/PrestaShop/pull/9080>  to fix the issue.
Also, you need to check that the php-intl extension is installed on your server.
If you are using the ps_emailalerts module, In the "MERCHANT NOTIFICATIONS" part, if we have an E-mail address with Special chars for example "deméo@prestashop.com", when I create an order FO & I finish it, I have this error message as reported here: #9638 <https://github.com/PrestaShop/PrestaShop/issues/9638> 

Thanks!
