### ISSUE TITLE
Customer page on 1.7.6.1 can be improved

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#16006]
I just upgraded to 1.7.6.1 and I highly regret this. The customer page is not usable anymore.

1) an advert bloc for the documentation is taking half of the screen, and come back even if I remove it (screenshot attached)

<img width="1558" alt="Capture d’écran 2019-10-17 à 19 15 07" src="https://user-images.githubusercontent.com/32092528/67031813-9d2a2100-f112-11e9-94b5-9fba70177503.png">

2) no more possible to display a customer just by clicking on its line : you have to click on the 3points icon to the right, then select display : 2 clics instead of one before (why ? It's a loss of time, not an improvement !)

**Additional information**
PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @elmanu13,

Thanks for your report.

>an advert bloc for the documentation is taking half of the screen, and come back even if I remove it 

I did not manage to reproduce the issue with PS1.7.6.1.
https://drive.google.com/file/d/1eTKFOCFwyDvxh8yJXKwXd6AnSm4LR-Tz/view
It is fixed previously with this PR: https://github.com/PrestaShop/PrestaShop/pull/12111

>no more possible to display a customer just by clicking on its line

We are aware of this issue, it is fixed with PR: https://github.com/PrestaShop/PrestaShop/pull/15859, it is fixed in the next major patch PS1.7.6.2. reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/15831

Thanks to check & feedback.

**Comment by elmanu13** [comment]
Hi @khouloudbelguith ,

Do you use Chrome ? I had to connect with Chrome and close it to make it disapear, it was impossible with Firefox (last version)
Now it's ok even under FF.

Thanks !

**Comment by khouloudbelguith** [comment]
@elmanu13, I used Chrome & the firefox and it is OK.
Since it is fixed, I close the issue.

Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15831
