### ISSUE TITLE
1.7.6.1 and cache disabled

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#16034]
Prestashop 1.7.6.1 on php 7.2.23
if I disable smarty cache, my CPU consumption increases considerably and the site slows down a lot:
1: smarty cache enabled
2: smarty cache disabled
https://nimb.ws/KJF9Nq
Is this behavior normal?

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

You can follow these steps:

- `Never recompile template files`: this option is to be chosen for maximum performance.
- `Cache enabled (YES)`: makes pages fastest. 
- `Smart cache for CSS (YES)`: brings together in a single file, compresses and caches CSS files.
- `Smart cache for Javascript (YES)`: brings together in a single file, compresses and caches JS files.
- `Apache Optimization (YES)`: allows to further increase site performance.

In your BO => Modules Manager page => configure the `statsdata` module & check if `Save page views for each customer` is enabled, try to disable it because it uses a lot of CPU resources and database space.

You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
In fact, it takes a very huge space in the database because it collects statistics from connections.
you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.


Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
