### ISSUE TITLE
PS admin panel - Theme & Logo - does not display theme name properly

### ISSUE THREAD

**Issue by dreamtheme** [PrestaShop/PrestaShop#16054]
PS 1.7.4.0 - 1.7.6.1
In the config/theme.yml there is two options, theme name (folder) and display theme name
Example:
name: pcstore
display_name: PC Store
version: 1.0.0

In the PS admin panel - Theme & Logo - under themes options, should display the "Display name", instead is the "name" displayed.
Those are descried in the PS dev documentation - https://devdocs.prestashop.com/1.7/themes/getting-started/theme-yml/

Screenshot https://ibb.co/L1LqcLH

Additionally - Author URL is not displayed anywhere
  author:
    name: "John Doe"
    email: "pub@prestashop.com"
    url: "https://www.prestashop.com"

**Comment by khouloudbelguith** [comment]
Hi @dreamtheme,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
The name displayed is the first name & not the real display name.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
