### ISSUE TITLE
Faceted Search Module 3.4.0, unlimited filter depth, cannot filter deep subcategories in a category

### ISSUE THREAD

**Issue by globox91** [PrestaShop/PrestaShop#16067]
**Describe the bug**

If I set unlimited category filter depth (0), I cannot filter displayed subcategories on category page if these subcategories aren't direct children of a category I'm currently in.
When I click on an option, ajax request executes without changing anything.

The module searches for selected categories with current category as a parent.
But with unlimited depth I can have all possible children displayed (level 2, 3 and so on)

**To Reproduce**

1. Set "Category filter depth" on a module configuration page to 0
2. Go to some category with possible 2, 3 etc level subcategories
3. Select one of those
4. Wait for ajax request to finish
5. See that no changes are displayed

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 5.6
Module version: 3.4.0

**Comment by khouloudbelguith** [comment]
Hi @globox91,

I did not manage to reproduce the issue with PS1.7.6.1 & ps_facetedsearch v3.4.0.
When Category filter depth = 1.
I have Only the subcategories
![image](https://user-images.githubusercontent.com/16067358/67302422-282f6080-f4f1-11e9-9a44-62839fd32516.png)
Category filter depth = 0, I have unlimited categories
![image](https://user-images.githubusercontent.com/16067358/67302509-44cb9880-f4f1-11e9-8c50-822a350fbf1c.png)

Thanks to check & feedback.

**Comment by globox91** [comment]
I managed to reproduce this behaviour on fresh install (1.7.6.1 + 3.4.0)

1. You need to create the following category structure (create a child for a "men" category, in this case)

![изображение](https://user-images.githubusercontent.com/56883311/67377979-2e741a00-f58f-11e9-93f9-0a37bbc88883.png)


2. Go to "Clothes" category ("/3-clothes")

![изображение](https://user-images.githubusercontent.com/56883311/67377808-ea811500-f58e-11e9-8de5-fdf31d2d1d9c.png)

3. Click on the new child filter option ("manChild1")
4. Now you should see that wrong behaviour :)

**Comment by khouloudbelguith** [comment]
@globox91, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1 & the ps_facetedsearch v3.4.0.
https://drive.google.com/file/d/1T7uKzMd8J9fjjozQ65g8lvPJk_JpmjE1/view
It was ok with the ps_facetedsearch v2.2.0.
It is a regression.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Ping @PierreRambaud 
Thanks!

**Comment by JGomezSDI** [comment]
Good morning!!
We appreciate you solve this issue ASAP, please.
Thanks a lot

**Comment by dvitcompte** [comment]
Hello everyone.

The problem is still there, 
tested on PrestaShop 1.7.6.3 1.7.6.4 and 1.7.6.5, with ps_facetedsearch module in versions 3.4.1 and 3.5.0
Any update or information ?

PrestaShop version: 1.7.6.3 1.7.6.4 and 1.7.6.5
Faceted search version: 3.4.1 and 3.5.0
PHP version: 7.2.22 and 7.2.31

Regards,

**Comment by olih10200** [comment]
The bug still bug :( today refreshed ps_facetedsearch module
Server: Linux #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64
Software: Apache/2.4.38 (Debian)
PHP: 7.3.19-1~deb10u1
PS: 1.7.6.7

FacetedSearch: v3.6.0 

Best regards,
--
Olivér

**Comment by PierreRambaud** [comment]
> Good morning!!
> We appreciate you solve this issue ASAP, please.
> Thanks a lot

Don't forget this is an open source project, if this feature is mandatory for your business, feel free to create a pull request or hire a developer to do it for you. We have many other priorities and haven't planned to do it right now :/
