### ISSUE TITLE
Email Theme - Outlook Footer Alignment

### ISSUE THREAD

**Issue by devonto** [PrestaShop/PrestaShop#16073]
**Describe the bug**
Footer email content is not center-aligned in new email templates when viewing email in Outlook

**Screenshot**
![Annotation 2019-10-22 172634](https://user-images.githubusercontent.com/6807236/67307893-206fbc00-f4f1-11e9-8a6a-2820264ab735.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
Outlook version: Office 365 Subscription, version 1909

**Comment by khouloudbelguith** [comment]
Hi @devonto,

Thanks to navigate to your BO => Design => Email Theme => Email themes section => click on View action for the modern template & check the HTTP of any email.
https://drive.google.com/file/d/1g7pXiNKu-DGQ72pRNtDXa1ZAuXQknWWi/view

Thanks to check & feedback..

**Comment by devonto** [comment]
Thanks, yes - in all "modern" browsers and email clients it works correctly, however Outlook uses a very old rendering engine.

There are additional lines of code in the templates targeted specifically at Outlook.

Please send yourself a test message and view it within Outlook, only then will you see the misalignment.

**Comment by khouloudbelguith** [comment]
@devonto, I did not manage to reproduce the issue with PS1.7.6.1.
I attached a screen record
https://drive.google.com/file/d/1wpTWb4KX2HN_nyzLbNBF48wi4MqiBWaA/view
Thanks to check & feedback.

**Comment by devonto** [comment]
Sorrky @khouloudbelguith, the Outlook I am referring to is the desktop software package; not the web-based interface

**Comment by khouloudbelguith** [comment]
Hi @devonto,

I manage to reproduce the issue with PS1.7.6.1.
![1761](https://user-images.githubusercontent.com/16067358/67380631-eeab3380-f58a-11e9-8198-69d1e7ecc534.PNG)
It is reproduced only on the desktop, it is Ok on the web
![image](https://user-images.githubusercontent.com/16067358/67380752-18645a80-f58b-11e9-8b64-3e966e7139b2.png)

With PS1.7.5.2, by default, we have the same position
Outlook desktop:
![1752](https://user-images.githubusercontent.com/16067358/67380824-3205a200-f58b-11e9-9e2c-452ba538d1a3.png)
Outlook web:
![image](https://user-images.githubusercontent.com/16067358/67381089-a04a6480-f58b-11e9-86c4-b8a1598bd7e0.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Ping @jolelievre 
Ping @colinegin @marionf, we should fix it in the next patch or no?

Thanks!

**Comment by devonto** [comment]
@khouloudbelguith Thanks - I suppose the 1.7.5.2 version isn't as noticeable as the new design, so may have gone unnoticed.

Sorry, I do not have a fix for it; busy working on getting the upgraded site in question live.

**Comment by colinegin** [comment]
What do you guys think ? I think this is a very small issue, I don't think this is necessary to fix it for 1762.

**Comment by jolelievre** [comment]
The issue is small in the sens that it is only on a specific mail browser, the solution however might be really difficult to implement because email integration is really tricky as every mail browser has different way to interpret end render the html mails..
We already use MJML to generate the modern them which supposedly avoids such bugs (and it is their full time work..)

In a nutshell I don't think this can really be considered as a regression since the modern theme is new in 176, certainly a bug but I would suggest fixing it in a another version as it shouldn't block the release of 1762

**Comment by TristanLDD** [comment]
I agree with @jolelievre and @colinegin it is a very small issue that doesn't deteriorate user experience, it can be fixed after 1762.

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/88269515-74a00a80-ccd4-11ea-84d5-fd144311afac.png)

Can't reproduce on Outlook for Mac now, should be fine, feel free to open it again if you manage to reproduce it
