### ISSUE TITLE
Module excluding products from free shipping.

### ISSUE THREAD

**Issue by mike3334** [PrestaShop/PrestaShop#16096]
**Is your feature request related to a problem? Please describe.**
Free shipping is currently valid if the order exceeds the set value or price.

**Describe the solution you'd like**
I would like to exclude several products from free shipping.
For their delivery to be counted separately or to omit the option of free delivery from the weight and price and will charge the shipping cost according to the carrier's configuration.

The products tab had for example "Product not included in free shipping".

**Additional context**
If it is a paid module, it needs an invoice for my company.

Prestashop v1.6.1.16
PHP 5.6

**Comment by khouloudbelguith** [comment]
Hi @mike3334,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).
During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
