### ISSUE TITLE
Remove smarty from engine template for PrestaShop and use twig

### ISSUE THREAD

**Issue by heithemmoumni** [PrestaShop/PrestaShop#16128]
**Is your feature request related to a problem? Please describe.**
please remove smarty from engine template for Prestashop and use twig

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khouloudbelguith** [comment]
Hi @heithemmoumni,

Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Comment by matks** [comment]
This is already happening in the back-office 😉, we are migrating BO pages one by one from legacy prestashop framework to Symfony, and each new page uses Twig instead of Smarty.

However we cannot remove Smarty from front-office now as it would be a major BC break that would make all current FO themes totally useless. This would be a very harsh move for the community and a violation of SemVer :/ .

When we release next major version (= BC breaks allowed) we might drop smarty for twig, this has not been decided yet. Most of us would be happy to perform this move, however we need to consider the community and make sure this is in the best interest of both the software and its users.

**Comment by khouloudbelguith** [comment]
Hi @heithemmoumni,

So, can we close this ticket?

Thanks!

**Comment by PierreRambaud** [comment]
@khouloudbelguith If there is no other issue for Twig in Front office, we can't keep this one but the title needs to be changed.

**Comment by heithemmoumni** [comment]
@khouloudbelguith, @matks for you response.

**Comment by adriablancafort** [comment]
Will the migration to twig in the FO happen anytime soon? 
Has this been considered to be released in prestashop 9 or it will be left for prestashop 10 or a later version?

**Comment by kpodemski** [comment]
Hello @adriablancafort 

PrestaShop 9 is almost finished. There were no plans to replace Smarty with Twig in the front office, and it is not something to consider soon. I think the only approach is to allow Twig in front office (that is possible in v9 although not optimal), and come up with a hybrid solution as in the back office. Otherwise, it's a change that is too drastic for the ecosystem to adjust.
