### ISSUE TITLE
gray attributes out of stock on prestashop 1.7.6

### ISSUE THREAD

**Issue by Mamar25** [PrestaShop/PrestaShop#16140]
Hello,

Would it be possible to set up an additional option on prestashop 1.7.6: gray out the attributes where the stocks are at 0, so that customers can see that they have been in stock but can not order them.
Thank you

**Comment by sarahdib** [comment]
Hello @Mamar25 

Thanks for your report.
We are re-working on the product page
Ping @PrestaShop/prestashop-product-team what do you think of those improvements?
Can we add those improvements during the migration?


Thank you

**Comment by marionf** [comment]
> Can we add those improvements during the migration?

@sarahdib No, as it concerns the front-office

@Mamar25 

If you disallow the possibility to order of out of stock products, you will see that combinations out of stock can't be ordered

![capture d'écran_2117](https://user-images.githubusercontent.com/13449658/67668597-88e6ef00-f970-11e9-93df-dfcec3c27cd8.png)

![capture d'écran_2118](https://user-images.githubusercontent.com/13449658/67668601-8c7a7600-f970-11e9-87ff-578115af6436.png)

We can't disable them because some merchants use a module that allow customers to put their email address and to receive an alert when the product is back in stock. For this reason the combination must remain selectable

**Comment by chemocycling** [comment]
hi
i was consider the same think . when you set ''out of stock'' products to be visible , products with attributes  that are out of stock will be great if have different color in the drop down ,so they can check them and then customers cann put their email for alert when back in stock 

thanks
