### ISSUE TITLE
If a discount from one unit is created, discounts on subsequent quantities will always include a discount of the first one unit

### ISSUE THREAD

**Issue by levyn** [PrestaShop/PrestaShop#16163]
**Describe the bug**

**To Reproduce**
1. create multiple specific prices rules (percentage) 
2. one of them should be from a quantity equal to one product 
3. Product settings -> Display discounted price must be enabled 
4. As a result, we will get an incorrect calculation in the table (see the screenshot)

**Screenshots**
![6150528003](https://user-images.githubusercontent.com/1076017/67709880-eb230c80-f9cf-11e9-8b0b-c77b8a9ec7e5.jpg)

**Additional information**
PrestaShop version: 1.7.*
PHP version: 7.1

**fixed ticket**
#15100

**Comment by khouloudbelguith** [comment]
Hi @levyn,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2.
1. the product price tax excluded => 11.900000
2. the VAT for the product => 20%
3. The specific price is a percent
4. Prices are displayed tax excluded
5. Product settings -> Display discounted price must be enabled
![image](https://user-images.githubusercontent.com/16067358/67749402-67980880-fa2d-11e9-9ad6-370e3d760157.png)

The discounted Price is incorrect
![image](https://user-images.githubusercontent.com/16067358/67749493-8f876c00-fa2d-11e9-9450-a58de35bd629.png)
It is calculated like this 9.52-30% = 6.66 => it should be 11.90-30% = 8.33
![image](https://user-images.githubusercontent.com/16067358/67749605-c493be80-fa2d-11e9-8102-ef38bffaff72.png)
It is calculated 9.52-40%=5.71 => it should be 11.90-40% = 7.14

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Ping @marionf, this issue should be added to this epic: #15816
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith Fixes have been made on develop branch, could you try to reproduce it on develop ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes, the same issue with the develop branch
![image](https://user-images.githubusercontent.com/16067358/67760136-09752080-fa41-11e9-82a8-3d121ba0a972.png)

Thanks!

**Comment by Progi1984** [comment]
Fixed by #15100
