### ISSUE TITLE
Error when we add customer (with B2B enabled) if there is a specific character in field SIRET

### ISSUE THREAD

**Issue by felipesml** [PrestaShop/PrestaShop#16167]
Hi there all!
I have an issue that make me crazy. I need to know how prestashop 1.7.6 do validation of SIRET field into BackOffice (RUT in chilean).
In 1.7.5 version is Ok, but in the new version prestashop show me "content field is invalid", anyone knows where is the line to change the validation in 1.7.6 version?, I need complete this data with a "-" like "12345678-K"
<img width="468" alt="errorpng" src="https://user-images.githubusercontent.com/32575962/67730892-2b38be00-f9d5-11e9-9f69-82357119b2cd.png">

Cheers

**Comment by sarahdib** [comment]
Hello @felipesml 

Thank you for the bug report.

I reproduce the issue in 1.7.6.1 : https://drive.google.com/file/d/1dVodQURZFCOAA39F2j3jnhBRJl-IXvJR/view

In 1.7.5.2 it's OK : https://drive.google.com/file/d/1zSlDQyLxQY_Ckha2HcSpZ1INvQve4puI/view

Step to reproduce :
B2B mode need to be activated in Shop Parameters -> Customers Settings
1. Go to BO -> Customer
2. Click on "Add a customer"
3. Set up information and in the siret field set up : 12345678-K
4. See the error

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!
