### ISSUE TITLE
1 click module on Prestashop 1.4.6.2 not working

### ISSUE THREAD

**Issue by andidomingo** [PrestaShop/PrestaShop#16192]
We have our site running on Prestashop 1.4.6.2 and would like to migrate it to the latest version. We downloaded 1-click add on and added it to Modules but it seems that the whole module section is not working anymore, we need to revert the process so we can migrate it (as at the moment we cannot access 1-click addon).
![Screen Shot 2019-10-29 at 17 05 09](https://user-images.githubusercontent.com/57149132/67790583-4ad3f300-fa76-11e9-8b65-e2e373823af0.png)

**Comment by khouloudbelguith** [comment]
Hi @andidomingo,

You can use the 1-click upgrade module v1.6.1.8 to make an upgrade from 1.4 to 1.6 as described here: https://addons.prestashop.com/en/data-migration-backup/5496-.html
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
For your safety!
You need to make a back up of your shop.
For more details: The details of the changes to the MySQL database structure between 1.4 and 1.7 are available, version by version, in this folder https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/upgrade/sql
you should be able to modify your data in 1.4 formats in data format 1.7 by following the different instructions
beware: some of them run PHP scripts, it's not just SQL

Also, you can use this module https://addons.prestashop.com/fr/migration-donnees-sauvegarde/8934-outil-de-migration-prestashop.html?ab=1

PS: 
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.
