### ISSUE TITLE
Total tax amount is wrong in order confirmation email

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16227]
**To Reproduce**
0. Setup some VAT rule, 21% for example.
0. Setup a voucher which discounts the order by X percent.
1. Add something to cart.
2. Apply a voucher with discount.
3. Order it.
4. Total tax in email is wrong. It is calculated from the amount before discounts.

**Fix**
`'{total_tax_paid}' => Tools::displayPrice(($order->total_products_wt - $order->total_products) + ($order->total_shipping_tax_incl - $order->total_shipping_tax_excl), $this->context->currency, false)`
>>>>>
`'{total_tax_paid}' => Tools::displayPrice($order->total_paid_tax_incl - $order->total_paid_tax_excl, $this->context->currency, false)`

I found it suprising that something crucial as calculating VAT is still not fixed after years. This problem is there since 1.6.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1 & the develop branch.
In the email the Tax is incorrect.
![image](https://user-images.githubusercontent.com/16067358/67946024-a7532180-fbe0-11e9-82cc-56e2a3293c23.png)

In the FO it is OK
![image](https://user-images.githubusercontent.com/16067358/67945974-8a1e5300-fbe0-11e9-8cd9-ac962dc1be80.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

PS: about your fix, we stopped using Tools::displayPrice as it is deprecated, you can follow this PR: https://github.com/PrestaShop/PrestaShop/pull/15448
Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith PR opened #16571
