### ISSUE TITLE
1 Clic upgrade bug

### ISSUE THREAD

**Issue by sextoysunivers** [PrestaShop/PrestaShop#16247]
Hi,

After trying to upgrade with the 1 clic upgade module from 1.6.1.24 to 1.7.1.6 I get the follwong error : 

Fatal error: Uncaught Unknown column 'h.live_edit' in 'field list'<br /><br /><pre>SELECT h.`name` as hook, m.`id_module`, h.`id_hook`, m.`name` as module, h.`live_edit` FROM `px_module` m INNER JOIN px_module_shop module_shop ON (module_shop.id_module = m.id_module AND module_shop.id_shop = 1 AND module_shop.enable_device & 1) INNER JOIN `px_module_shop` `ms` ON ms.`id_module` = m.`id_module` INNER JOIN `px_hook_module` `hm` ON hm.`id_module` = m.`id_module` INNER JOIN `px_hook` `h` ON hm.`id_hook` = h.`id_hook` LEFT JOIN `px_module_group` `mg` ON mg.`id_module` = m.`id_module` WHERE (h.name != "displayPayment") AND (hm.id_shop = 1) AND (mg.id_shop = 1 AND mg.`id_group` IN (3)) GROUP BY hm.id_hook, hm.id_module ORDER BY hm.`position` </pre> thrown in /var/www/classes/db/Db.php on line 769

Thank you in advance for you help

Best regards,

JC

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.6.1.24
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @sextoysunivers,

First of all, thanks for your report.
Second, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
Also, PS1.6 is compatible with PHP5.2 to PHP7.1.
You can follow our documentation
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
You need to downgrade your PHP version.

Finally, you have an issue with the live edit, but with PS1.7, we decided to remove the Live Edit because it wasn't perfect and we're working on a new one, you can follow this PR: https://github.com/PrestaShop/PrestaShop/pull/8285

Thanks to downgrade your PHP version, check & feedback.

**Comment by sextoysunivers** [comment]
Dear khouloudbelguith,

Thank you very much for your kindly answer

When do you think the next Major release PS1.7.7 it's going to arrive ?

Best regards, 

JC

**Comment by sextoysunivers** [comment]
Dear khouloudbelguith,

I'm asking you this cause my server works with debian 10 buster which makes impossible to downgrade to php 7.2. To downgrade the php version wouldn't be an option

To do that I would have to  reinstall everything to an older debian 9 

Best regards,
JC

**Comment by khouloudbelguith** [comment]
Hi @sextoysunivers,

We are still working on the PS1.7.7.
You can follow our process here: https://github.com/PrestaShop/PrestaShop/projects/7

>To do that I would have to reinstall everything to an older debian 9

Thanks, waiting for your feedback.

**Comment by sextoysunivers** [comment]
Hi khouloudbelguith,

I can see a lot of hard work out there

I'll be monitoring 

Thank you 

Best regards,

JC

**Comment by khouloudbelguith** [comment]
@sextoysunivers, So you will work on it & I can close the issue?

Thanks!

**Comment by sextoysunivers** [comment]
I'll do it for you

Thank you again 👍 

JC

**Comment by khouloudbelguith** [comment]
@sextoysunivers, Thanks!
Feel free to open a new one when needed.
