### ISSUE TITLE
Localization exception in order creation page after clean ps install

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#16259]
**Describe the bug**
Cannot search for products in Sell > Order > add new Order.
Keep getting Localization exception associated with empty currency, thrown in Locale::getPriceSpecification() which is apparently called in admin controller when preparing context.

**To Reproduce**
1. Install prestashop development mode (using /install-dev)
2. Click on Sell > Orders > Create new
3. Search and choose a customer
4. Search for products
5. No products shows up. In console you can see ajax request error. (screenshot 1)

**Screenshots**
1. 
![Screenshot from 2019-11-04 13-05-27](https://user-images.githubusercontent.com/31609858/68116569-d54ba500-ff03-11e9-85d7-f22a38ddd478.png)

**Additional information**
PrestaShop version: develop
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I have the same issue with the develop Branch.
![image](https://user-images.githubusercontent.com/16067358/68117664-4425ff80-fefe-11e9-8f44-ecfbe988791b.png)
It is OK with PS1.7.6.2build1.
I’ll add this to the debug roadmap.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

The issue is not fixed yet.
Steps to reproduce the issue:
1. fresh install to develop or delete all shopping carts not ordered yet.
2. Try to add a new order from the BO
3. Choose a customer
4. see the error in the console
![image](https://user-images.githubusercontent.com/16067358/68291740-c9d6b600-008a-11ea-9694-80a91be53036.png)
 
Commented here: https://github.com/PrestaShop/PrestaShop/issues/16288#issuecomment-550254073

Thanks!
