### ISSUE TITLE
prestashop 1.6 chrome scroll down error

### ISSUE THREAD

**Issue by alaminmishu** [PrestaShop/PrestaShop#16264]
Whenever my site loads on the chrome browser it automatically scrolls down to footer area.
Not showing header content first. There is a slider in header area.

Tested in Iphone's Safari browser and opera browser this problem not occurs. 
plz have a look. 

site link: https://inglotbangladesh.com/

Prestashop version: 1.6.1.23

Appreciate, if anyone faces this problem and overcome. 
plz, let me know how you solved that?

**Comment by khouloudbelguith** [comment]
Hi @alaminmishu,

I did not manage to reproduce the issue with PS1.7.6.1.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
