### ISSUE TITLE
Tax Rules : Incorrect display value in Price Tab of admin product controller

### ISSUE THREAD

**Issue by WebXYAgency** [PrestaShop/PrestaShop#16308]
**Describe the bug**
When using an integer as tax rules name, the display value in tax rule field is incorrect. 

**To Reproduce**
1. Go to 'Internationnal' > 'Taxes' > 'Tax Rules' tab.
2. Add a new tax rule with an integer (ie: 20)  as name and save.
3. Go to any product page in 'Catalog' > 'Products'.
4. Go to 'Pricing' tab and open the select list of 'Tax rule' field.
5. The '20' tax rule name is displayed as '0'. 

**Screenshots**
![image](https://user-images.githubusercontent.com/57484794/68383031-2a322a00-0155-11ea-9d0d-a9cfd8020c3a.png)

![image](https://user-images.githubusercontent.com/57484794/68383014-1e466800-0155-11ea-8d84-23537e565c9c.png)

**Additional information**
PrestaShop version: 1.7.6.1 and earlier
PHP version: 7.1.16

**Comment by khouloudbelguith** [comment]
Hi @WebXYAgency,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.1 & PS1.7.6.2build1.
The display is incorrect.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith it's only in pricing tab or also in basic settings ?

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Yes, same problem in the basic settings.

Thanks!
