### ISSUE TITLE
Filter doesn't work when characteristic value starts with - (minus) character in ps_facetedsearch 3.4 

### ISSUE THREAD

**Issue by gaboto83** [PrestaShop/PrestaShop#16320]
When the character value begins with the character "-" (minus), the filter does not work when selecting that value.
For example, if I have the characteristic "Pressure range", and I have the value "-1 to 0 Bar", I see the option to select in the filters, but when I click on it, it does not work.
A workaround is to rename the value and add a blank space character before name, 
for example: " -1 to 0 Bar" instead of "-1 to 0 Bar".  But it is not a definitive solution to the problem.

I tried debugging it to find the problem. I see that the method "serializeListOfStrings" of the class URLFragmentSerializer serialize the characteristic and the value adding a "-" character between both. In the example above, it would be: "Pressure+range---1+to+0+Bar", (it uses "--" to escape "-"). But when unserializeListOfStrings method is executed, it returns a an array with "Pressure range-" and "1 to 0 Bar" instead of an array with "Pressure range" and "-1 to 0 Bar" .

**Additional information**
ps_facetedsearch 3.4 
PrestaShop version: 1.7.5.2

**Comment by khouloudbelguith** [comment]
Hi @gaboto83,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & ps_facetedsearch v3.4.0 & ps_facetedsearch v3.0.6.
I attached a screen record
https://drive.google.com/file/d/1tiPwub2c-G99szWFE0VU24Q2admMkmwP/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Ping @PierreRambaud

**Comment by tiagorodriguesnes** [comment]
The same exact same behavior happens when you add char '+' at the end of the attribute on version 1.7.6.
I believe it will happen having any special chars on attributes.
Example:
Energy classification of a fridge can have the value 'A+++', the query arrived to ps_facetedsearch has 'A&nbsp;&nbsp;&nbsp;'.
Hope this helps. 

-------

Turns out it was the theme decoding the query string before emitting

**Comment by PierreRambaud** [comment]
> The same exact same behavior happens when you add char '+' at the end of the attribute on version 1.7.6.
> I believe it will happen having any special chars on attributes.
> Example:
> Energy classification of a fridge can have the value 'A+++', the query arrived to ps_facetedsearch has 'A   '.
> Hope this helps.
> 
> Turns out it was the theme decoding the query string before emitting

I tried with my pull request and I have this when using + in URL:
![image](https://user-images.githubusercontent.com/1462701/101184243-c9736a80-3650-11eb-934e-b2965d11d04a.png)
It's working well for me :thinking:
