### ISSUE TITLE
ps_socialfollow wrong url adress

### ISSUE THREAD

**Issue by qwebdevel** [PrestaShop/PrestaShop#16325]
To Reproduce
1. Go to 'BO -> modules -> ps_socialfollow
2. Click on 'configure'
3. Add social media like 'facebook,twitter,etc'
4. See statement of url 'domain.com/facebook.com'
5. Need to be 'facebook.com'

PrestaShop version: N/A
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @qwebdevel,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.5.2 & ps_social follow v2.0.0.
When we add a link like `facebook.com` or `instagram.com` => there is an incorrect redirection `domain.com/facebook.com.`
We should add https:// before any link to be correct.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by cr998** [comment]
What would be the correct operation?

![image](https://user-images.githubusercontent.com/6900835/80289883-ebfbe780-8741-11ea-8757-49ca7badb533.png)
![image](https://user-images.githubusercontent.com/6900835/80289889-f8804000-8741-11ea-9ab2-f281917756a4.png)

In the first option the merchant need to write all URI otherwise in the second option th merchant only need to puts de end of the URI

**Comment by florine2623** [comment]
Hello ,

This issue is fixed. The error message forces the user to put the right URL.


https://github.com/PrestaShop/PrestaShop/assets/16019289/bdad8f55-0f9f-4fa5-8556-22870f6863a6



I'm closing this issue to avoid clogging the backlog.
Thanks!
