### ISSUE TITLE
Prestashop 1.7 manual upgrade error with SqlTranslationLoader.php

### ISSUE THREAD

**Issue by flavi1** [PrestaShop/PrestaShop#16342]
Hello
I'm trying to manually upgrade a Prestashop version from 1.6 to 1.7.6.1. However it doesn't work. I only got a blank page if I try to run the upgrade feature. You'll find the error message below.
`

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to PrestaShopBundle\Translation\Loader\SqlTranslationLoader::addTranslationsToCatalogue() must be of the type array, boolean given, called in /home/immoclic/public_html/sagapolynesie.com/new/src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php on line 84 in /home/immoclic/public_html/sagapolynesie.com/new/src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php:101 Stack trace: #0 /home/immoclic/public_html/sagapolynesie.com/new/src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php(84): PrestaShopBundle\Translation\Loader\SqlTranslationLoader->addTranslationsToCatalogue(false, Object(Symfony\Component\Translation\MessageCatalogue)) #1 /home/immoclic/public_html/sagapolynesie.com/new/vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php(381): PrestaShopBundle\Translation\Loader\SqlTranslationLoader->load('AdminActions.fr...', 'fr-FR', 'AdminActions') #2 /home/immoclic/p in /home/immoclic/public_html/sagapolynesie.com/new/src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php on line 101`

**Comment by khouloudbelguith** [comment]
Hi @flavi1,

This issue is fixed in the PS1.7.6.1 with this PR: https://github.com/PrestaShop/PrestaShop/pull/14620 as reported here: https://github.com/PrestaShop/PrestaShop/issues/14591
Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @flavi1,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

**Comment by evamariamontero** [comment]
Hi,

I'm having the same error and my prestashop version is 1.7.6.2
Any idea on what to do?

Thank you!

**Comment by mayoji** [comment]
> Hi @flavi1,
> 
> This issue is fixed in the PS1.7.6.1 with this PR: #14620 as reported here: #14591
> Thanks to check & feedback.

Hi @khouloudbelguith,
I've experienced the same issue today when trying to upgrade a store from 1.6.0.11 to 1.7.6.2, so if this is indeed the same issue as #14620 (the stack trace seems unrelated though), it looks like it is still there in 1.7.6.2. 
@evamariamontero also reported having the same issue with 1.7.6.2 a few weeks ago.
I also noticed that your replied to @flavi1 saying the issue was solved with 1.7.6.1, but that's the same version they reported having the issue with.
Thank you

**Comment by jakub-trzebiatowski** [comment]
I'm having the same issue on 1.7.6.3

**Comment by mayoji** [comment]
@cubuspl42 I found out when I had issue is that the database structure was corrupted, so I suspect the code that migrates the database schema between versions doesn't work for older versions. I ended up upgrading to 1.7.5.2 instead of 1.7.6.2 and that worked fine. 
Although I didn't try, you could then probably upgrade from 1.7.5.2 to 1.7.6.3.

**Comment by fsoabsix** [comment]
Hi,
I got this error with the 1.7.7.0 version.
I want upgrade from 1.6.1.24, not working, i tried manuel and automatic with one-click, the same errors.
