### ISSUE TITLE
How to add "recycled packaging" in order_conf and new_order mail and on order summary page and order confirmation page?

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#16348]
Hi, 
on order summary page (Please check your order before payment) before the customer click on "order with an obligation to pay" button the option "I would like to receive my order in recycled packaging" from checkout step 3 (shipping method) is not shown. And it is not shown on order confirmation page. 

And at least it is not shown in order_conf mail to the customer and not shown in new_order mail to the merchant. 

**Describe the solution you'd like:**

As specified in https://github.com/PrestaShop/PrestaShop/issues/16348#issuecomment-605923945 and https://github.com/PrestaShop/prestashop-specs/pull/175:

1. FRONT **final summary** (_displayed to the customer_)
Add 'Recycled packaging' (localized in _Shop.Theme.Checkout_) in the Shipping Method block.

2. FRONT **order confirmation** (_displayed to the customer_)
Add 'Recycled packaging' (localized in _Shop.Theme.Checkout_) in the Order Details section, just below the shipping method.

3. EMAIL **order_conf** (_displayed to the customer_)
Add 'Recycled packaging' (localized in _Emails.Body_) in italics characters in the Shipping block.

4. EMAIL **new_order** in module ps_emailalerts (_displayed to the merchant_)
Add 'Recycled packaging' (localized in _Emails.Body_) in italics characters in the Order Details block.

**Steps to reproduce the behavior:**

1. Go to backoffice: shop parameters -> order settings
2. enable "Enable final summary" and "Offer recycled packaging"
3. go to Frontoffice and make an order and choose in checkout step 3 Shipping Method: "I would like to receive my order in recycled packaging"
4. this option is not shown on order summary page before ordering
5. this option is not shown on order confirmation page after ordering 
6. get order_conf mail and you see not as customer that you have choosen this option
7. get new_order mail (from ps_emailalerts) and you see not that customer have choosen this option

**Screenshots**

![image](https://user-images.githubusercontent.com/44971218/68556337-2ee72e80-0432-11ea-8b14-6de5e8db3659.png)

![image](https://user-images.githubusercontent.com/44971218/68554564-4f5ebb00-0429-11ea-8069-da05358e3600.png)

![image](https://user-images.githubusercontent.com/44971218/68554597-82a14a00-0429-11ea-8b02-d8a83219606f.png)

![image](https://user-images.githubusercontent.com/44971218/68556454-9e5d1e00-0432-11ea-9fcf-c6d9388c9d00.png)

![image](https://user-images.githubusercontent.com/44971218/68556505-d82e2480-0432-11ea-8f7b-f8e1db7614ec.png)

**Additional information**
PrestaShop version: 1.7.x.x

**Comment by khouloudbelguith** [comment]
Hi @didi-2018,

Thanks for your report.
I have the same behavior as PS1.7.6.1.
The  Recycled packaging label is added only in the BO => Orders details page
![image](https://user-images.githubusercontent.com/16067358/68582349-cd977d80-047a-11ea-9cb5-01963ad65cd9.png)
It is **not displayed** in the:
1. Final summary
![image](https://user-images.githubusercontent.com/16067358/68582418-f1f35a00-047a-11ea-9e80-e29608363081.png)
2. Order Confirmation Page
![image](https://user-images.githubusercontent.com/16067358/68582472-164f3680-047b-11ea-8a66-8814e7a8ffaf.png)
3. Order confirmation Email
![image](https://user-images.githubusercontent.com/16067358/68582508-3252d800-047b-11ea-8225-e534831f04b4.png)
4. New Order mail
![image](https://user-images.githubusercontent.com/16067358/68582544-4b5b8900-047b-11ea-8e08-08ea569db6ce.png)

Ping @PrestaShop/prestashop-product-team what do you think to add this option in all these missing pages?

Thanks!

**Comment by didi-2018** [comment]
Hi @khouloudbelguith, do got any news?

**Comment by khouloudbelguith** [comment]
@didi-2018, sorry not yet.

Thanks for your understanding!

**Comment by Piszi** [comment]
Hello,
This is an old thread, but I run into the same problem just now. I needed to enable recycled packakging, but it wasn't showing up anywhere but the BO order details.
So I did some investigation and modded some core files and the ps_emailalerts module, to make this work.

First the mail alerts module:
**Step 1**: open **ps_emailalerts.php** and search for: **// Filling-in vars for email**
**Step 2**: just before that comment put something like this:
```
if($order->recyclable){
    $recyclable = 'I would like recycled packaging'; // or use bulilt in translations with $this->trans('No carrier', array(), 'Admin.Payment.Notification') for example
  }else{
    $recyclable = '';
   }
```
**Step 3**: create the new email variable, put something like this:
`'{recycled}' => $recyclable,`
at the end of the $template_vars array

Add Recycled packaging to order conf email:
**Step1**: open calsses/PaymentModule.php and find this: **// Send an e-mail to customer (one order = one email)**
**Step 2**: after the before mentioned comment find $data = array and before that put sometnig like this: 
```
if($order->recyclable){
    $recyclable = 'I would like recycled packaging'; // or use bulilt in translations with $this->trans('No carrier', array(), 'Admin.Payment.Notification') for example
  }else{
    $recyclable = '';
   }
```
**Step 3**:  create the new email variable, put something like this:
`'{recycled}' => $recyclable,`
at the end of the $data array
**Note this is a Core mod so you should do this as an override, because an update will undo it.**

Adding recycled to the order summary:
**Step 1**: open classes/checkout/CheckoutPaymentStep.php and find function render
**Step 2**: Add the folollowing to the start of the function:
`$isrecyclable = $this->getCheckoutSession()->isRecyclable();`
**Step 3**: assign the smarty var add the following to the end of the $assignedVars:
`'is_recyclable' => $isrecyclable,`
**Step 4**: in your order-final-summary.tpl use the before created var where you would like to show it. for example like this:
```
{if $is_recyclable}
  {l s='I would like recycled packaging' d="Shop.Theme.Checkout"}
{/if}
```

Adding recycled packaging to order conf page:
This is the easyest because the whole order var is passed to smarty.
**Step 1**: open order-confirmation.tpl and put something like this where you would like to display it:
```
{if $order.details.recyclable}
   {l s='I would like recycled packaging' d="Shop.Theme.Checkout"}
{/if}
```
And thats it.
Oh I left out you need to edit your email templates add the new email vars to them.

**Comment by LouiseBonnard** [comment]
I agree, thanks @didi-2018 and @khouloudbelguith! It would be a nice improvement to have this information displayed in the following pages:

1. FRONT **final summary** (_displayed to the customer_)

Add 'Recycled packaging' (localized in _Shop.Theme.Checkout_) in the Shipping Method block.

2. FRONT **order confirmation** (_displayed to the customer_)

Add 'Recycled packaging' (localized in _Shop.Theme.Checkout_) in the Order Details section, just below the shipping method.

3. EMAIL **order_conf** (_displayed to the customer_)

Add 'Recycled packaging' (localized in _Emails.Body_) in italics characters in the Shipping block.

4. EMAIL **new_order** in module ps_emailalerts (_displayed to the merchant_)

Add 'Recycled packaging' (localized in _Emails.Body_) in italics characters in the Order Details block.

---

Note that it is mentioned in the Order History section of the customer account:

![Capture d’écran 2020-03-30 à 12 27 09](https://user-images.githubusercontent.com/32565890/77903725-a0aa0280-7283-11ea-95d1-4c88f2e50160.png)
