### ISSUE TITLE
Two columns small left column with Recommended Product are not displaying corectly.

### ISSUE THREAD

**Issue by gbartosz83** [PrestaShop/PrestaShop#16352]
Hello, I have a little problem with displaying products on main page.
I wanted to have menu with all categories and products on main page, so I have changed grid for index to "Two columns small left column - Two columns with a small left column".
But now in the main page only two products in one row are displayed (instead of 3) 
How to change this to look the same as in category view where 3 products are displayed in a row.

this issue is in the popular products section, when I click "display all products" it display 3 products in a row.

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop 1.7.6.1
PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @gbartosz83,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.2build1 & PS1.7.5.2 & the Category tree links v2.0.0.
![image](https://user-images.githubusercontent.com/16067358/68591202-73091c00-0490-11ea-873e-03d428f261ed.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by gbartosz83** [comment]
Thanks! 
I don't have solution yet, but meanwhile I could have change it to something else.
How to set default category to be displayed in the main page instead of this broken popular product page?
I have added 
.product-miniature {
	margin: 8px !important;
}
it works somehow for now.

**Comment by gustavosimone** [comment]
you can add row class (bootstrap in the product container) or add custom css like this
.layout-left-column.page-index .products {
margin-right: -15px;
margin-left: -15px;
}
