### ISSUE TITLE
Display issue in the product page when a category has more than 30 chars

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16415]
**Describe the bug**
When a category has more than 30 chars (less on a small screen), you need to scrool horizontally in the product page to select the main category

**To Reproduce**
1. Go to Catalog > Category
2. Edit a category with a name with more than 30 chars
3. Go to Catalog > Products
4. Edit a product and see the Category part

**Screenshots**
![capture d'écran_2153](https://user-images.githubusercontent.com/13449658/68871523-dc8d6280-06fc-11ea-9186-493334c8694f.png)

![capture d'écran_2154](https://user-images.githubusercontent.com/13449658/68871536-e44d0700-06fc-11ea-8a78-f83eaa3fc9e9.png)

![capture d'écran_2155](https://user-images.githubusercontent.com/13449658/68871544-e6af6100-06fc-11ea-8510-bf98a911c49f.png)

**Additional information**
PrestaShop version: 1.7
PHP version: N/A

**Comment by marionf** [comment]
@TristanLDD

**Comment by prestascott** [comment]
Thank you @marionf ! 
Another display issue appears when there is more than 50 characters used for a category. It exceeds from the block.

**Screenshot**
![Bug display ](https://user-images.githubusercontent.com/54888056/69969619-117f1f00-151d-11ea-9623-0d41b874698d.png)

**I made a prototype in order to solve both issues:**
![Display issue categories 30chars](https://user-images.githubusercontent.com/54888056/69969735-455a4480-151d-11ea-8e4a-815740c44bf1.png)

What do you think? @marionf @TristanLDD

**Comment by marionf** [comment]
All good, thank you @prestascott

**Comment by NeOMakinG** [comment]
The problem won't be there in product v2 as the tree will be inside a modal
