### ISSUE TITLE
SMTP error 5.5.4 with Office 365 on Prestashop 1.7.5.1

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#16437]
**Describe the bug**
When we test email configuration of SMTP expert configuration on Start TLS with port 587, Prestashop can't send the test email and give this error.

554 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message.

I can't use PHP Mail() because my provider block outgoing email from the datacenter. The credentials and password, and smtp settings are verified and not in cause. I also try Start SSL with 465 with same results. 

On Office 365, All applications autorisations are activated.

Any help is appreciated.

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.20

**Comment by luisbo69** [comment]
Did you managed to resolve this issue?

**Comment by 8ternity** [comment]
> Did you managed to resolve this issue?

Yes. It was resolved by itself or fix. I don't remember. It's from last year.

**Comment by Support-Dolikom** [comment]
I have the same error, can you help the prestashop community ??

thanks ;)

**Comment by luisbo69** [comment]
Found that the problem is on the office365 ports settings, and there is no way to find a turn around, I have several prestashop implementations with gmail a points with no problems, the solution in this case was to change the office365 emails accounts bought in Godaddy, with another emails accounts offered and hosted by Godaddy, then there was no problems with prestashop ecommerce emails. Hope this helps.
