### ISSUE TITLE
Dashboard - customer link not working 1.7.6.1

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#16460]
**Describe the bug**
A link to a customer from dashboard will not open the Information about customer page.

**To Reproduce**
1. Go to dashboard - Last 10 orders
2. Click on any customer name
3. Instead of the selected customer details page, you'll only get general list of customers

I think the correct logic should be to show Information about customer page.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @mrabsinthe,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.2build1.
https://drive.google.com/file/d/1sQIxxAZvZsi1MeDaaw5wljNQDlEC7zg3/view
It is ok with PS1.7.5.2, it is a regression.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/14672

**Comment by khouloudbelguith** [comment]
Same issue with PS1.7.6.0
https://drive.google.com/file/d/1mfAYUPb0WOicZRaGd8J5ayzZk3V_f1cA/view

**Comment by Progi1984** [comment]
Merged in `dev` branch

**Comment by procent85** [comment]
Hello,
the problem still exists in version 1.7.6.3 @Progi1984 
Clickin on any customer name instead of the selected customer details page, you'll only get general list of customers

In changelog of 1.7.6.3 I found:
"Dashboard - customer link not working 1.7.6.1 "

**Comment by khouloudbelguith** [comment]
Hi @procent85,

This issue fixed in the module with this PR: https://github.com/PrestaShop/dashproducts/pull/19.
A new release of the `dashproducts` module not released yet.

Thanks!
