### ISSUE TITLE
Carrier - Ranges are overlapping

### ISSUE THREAD

**Issue by WellStraler** [PrestaShop/PrestaShop#16474]
Hi!

I can't access the 2nd page on the "Carrier" page to edit the cost of a shipment.
On top is the error: "Ranges are overlapping"

![image](https://user-images.githubusercontent.com/57994075/69241406-08966100-0b9f-11ea-886f-53d2904674d8.png)

PrestaShop version: 1.6.1.14

**Comment by khouloudbelguith** [comment]
Hi @WellStraler,

I did not manage to reproduce the issue with PS1.7.6.1.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs can be fixed.

Thanks for your understanding!
