### ISSUE TITLE
Duplicate payments in PS 1.6.1.24

### ISSUE THREAD

**Issue by frevab** [PrestaShop/PrestaShop#16483]
I have upgrade one of my shop to PS 1.6.1.24 from 1.5.4.1.

Now I get duplicated payments in orders. One payment with with payment transaction refno and one without. The one without has a time stamp which is later.
I cannot find any errors in the error-logs (both in root and in paypal map).
I use PayPal v3.13.1 and  Digiwallet for Prestashop v1.0.0 

What can cause this and how can this be fixed?

**Comment by khouloudbelguith** [comment]
Hi @frevab,

I did not manage to reproduce the issue with PS1.7.6.1 & the Paypal module v5.0.3.
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes, that's why I'm closing this issue.

Thanks!
