### ISSUE TITLE
Incorrect email subject and template variable {shop_name}

### ISSUE THREAD

**Issue by ziezo** [PrestaShop/PrestaShop#16499]
In PS 1.7.6.1 the email subject and template variable {shop_name} display the internal BO name from the "Multishop" settings. It should display the external name from "Contact" settings.

I patched /classes/Mail.php as follows:

```
//BEGIN PATCH
//            $subject = '[' . $shop->name . '] ' . $subject;
            $subject = '[' . Tools::safeOutput(Configuration::get('PS_SHOP_NAME', null, null, $id_shop)) . '] ' . $subject;
//END PATCH
```
and
```
//BEGIN PATCH
//            $templateVars['{shop_name}'] = Tools::safeOutput($shop->name);
            $templateVars['{shop_name}'] = Tools::safeOutput(Configuration::get('PS_SHOP_NAME', null, null, $id_shop));
//END PATCH
```

**Comment by khouloudbelguith** [comment]
Hi @ziezo,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.2build1.
The email subject & the `shop name` in the email body are incorrect.
It is not the `Shop name` defined in the BO => Shop Parameters => Contact => Stores page
![image](https://user-images.githubusercontent.com/16067358/69408388-0bac6100-0d07-11ea-9ad8-d352fa5be3d8.png)
It is in fact, the `Shop name` defiened in the multistore page
![image](https://user-images.githubusercontent.com/16067358/69408499-529a5680-0d07-11ea-955b-4021b98fff4f.png)

![image](https://user-images.githubusercontent.com/16067358/69408606-a86efe80-0d07-11ea-9ba6-0367c027a86b.png)
![image](https://user-images.githubusercontent.com/16067358/69408663-c3da0980-0d07-11ea-80d8-dc115115bb59.png)

![image](https://user-images.githubusercontent.com/16067358/69408667-c89ebd80-0d07-11ea-88a0-a6628cd315dc.png)
It is ok with PS1.7.5.2.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by PierreRambaud** [comment]
Ping @colinegin 
Can you confirm this is the desired behaviour? Could you tell us what we exactly want and create a spec for it :smile:
