### ISSUE TITLE
GDPR consent checkbox and text missing in product comments (reviews)

### ISSUE THREAD

**Issue by aledigit** [PrestaShop/PrestaShop#16505]
**Describe the bug**
- Official GDPR compliance 1.1.3 installed and set to show consent checkbox and text in product comments (reviews) form
- Official Product Comments 4.0.1 installed
- Consent checkbox and text are missing when filling product comments (reviews) form.

**To Reproduce**
-  Install Official GDPR compliance
-  Install Official Product Comments
-  Set Official GDPR compliance module do add consent checkbox and text with Product Comments module
-  Try to write a review in front end: checkbox and text are missing.

**Screenshots**.
Official GDPR compliance module setting
![immagine-1](https://user-images.githubusercontent.com/10708213/69423426-55f10a80-0d26-11ea-9a85-5f89c782bbbc.jpg)

Product Comments form without consent checkbox and text
![immagine-2](https://user-images.githubusercontent.com/10708213/69423652-f5160200-0d26-11ea-8598-1b2dc882700d.jpg)

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @aledigit,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.0 & PS1.7.6.2build1 GDPR v1.1.3 & Product Comments module v4.0.1.
![image](https://user-images.githubusercontent.com/16067358/69427731-22b37900-0d30-11ea-9989-d48940bfda9b.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by aledigit** [comment]
Ok!

**Comment by ghost** [comment]
Mine 5 cents...

There should be just:
`var customerName = comment.customer_name;`
To be GDPR compliant... Instead of customer full name by default.

**Comment by PeeyushAgrawal** [comment]
PR - https://github.com/PrestaShop/productcomments/pull/50

**Comment by HartLarsson** [comment]
Any news? GDPR is mandatory in Europe

**Comment by aledigit** [comment]
Any news?

**Comment by Progi1984** [comment]
Assigned to @okom3pom
