### ISSUE TITLE
how can i find why is slow

### ISSUE THREAD

**Issue by langziyang** [PrestaShop/PrestaShop#16537]
our mian page is very slow. this is our information
![Image of Yaktocat](https://www.518global.com/images/infor.png)

vps:
![Image of Yaktocat](https://www.518global.com/images/infor1.png)

mysql:
![Image of Yaktocat](https://www.518global.com/images/mysql.png)

profiling:
![Image of Yaktocat](https://www.518global.com/images/infor2.png)

so: how can i tracking why display is too slow?

**Comment by khouloudbelguith** [comment]
Hi @langziyang,

Thanks to follow these steps:

- `Never recompile template files`: this option is to be chosen for maximum performance.
- `Cache enabled (YES)`: makes pages fastest. 
- `Smart cache for CSS (YES)`: brings together in a single file, compresses and caches CSS files.
- `Smart cache for Javascript (YES)`: brings together in a single file, compresses and caches JS files.
- `Apache Optimization (YES)`: allows to further increase site performance.

In your BO => Modules Manager page => configure the `statsdata` module & check if `Save page views for each customer` is enabled, try to disable it because it uses a lot of CPU resources and database space.

You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
In fact, it takes a very huge space in the database because it collects statistics from connections.
you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.

Also, you can check the `ps_quest` table if it has a lot of data.

Thanks!

**Comment by langziyang** [comment]
> Hi @langziyang,
> 
> Thanks to follow these steps:
> 
> * `Never recompile template files`: this option is to be chosen for maximum performance.
> * `Cache enabled (YES)`: makes pages fastest.
> * `Smart cache for CSS (YES)`: brings together in a single file, compresses and caches CSS files.
> * `Smart cache for Javascript (YES)`: brings together in a single file, compresses and caches JS files.
> * `Apache Optimization (YES)`: allows to further increase site performance.
> 
> In your BO => Modules Manager page => configure the `statsdata` module & check if `Save page views for each customer` is enabled, try to disable it because it uses a lot of CPU resources and database space.
> 
> You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
> In fact, it takes a very huge space in the database because it collects statistics from connections.
> you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.
> 
> Also, you can check the `ps_quest` table if it has a lot of data.
> 
> Thanks!

i already did all list,i want know how to track the display time is 8442 ms, thanks

**Comment by khouloudbelguith** [comment]
@langziyang, you need to enable profiling mode & just did it.
When profiling mode is enabled, you should have information about the time needed to run queries.

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith profiling doesnt work

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Profiling for hooks is broken as reported here: https://github.com/PrestaShop/PrestaShop/issues/9659, here's the PR: https://github.com/PrestaShop/PrestaShop/pull/16231 to fix the issue.
But it can help us to get information about the time needed to run queries.

Thanks!

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @langziyang,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
