### ISSUE TITLE
voucher input box not showing but vouchers are active

### ISSUE THREAD

**Issue by alaminmishu** [PrestaShop/PrestaShop#16547]
I have followed the steps to create a voucher but somehow there is no box that displays an input for the voucher codes.

plz look at this website: https://inglotbangladesh.com/

If you inspect you will see discount price have rendered but price set as 0. plz someone give proper explanation.

**Comment by alaminmishu** [comment]
Prestashop version 1.6.1.23

**Comment by alaminmishu** [comment]
I've followed this post https://www.prestashop.com/forums/topic/248040-voucher-input-box-not-showing-but-vouchers-are-active/ but no luck.

**Comment by khouloudbelguith** [comment]
Hi @alaminmishu,

I did not manage to reproduce the issue with PS1.6.1.24.
![image](https://user-images.githubusercontent.com/16067358/69648743-2adf2180-106c-11ea-823c-24d846f728ef.png)

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
