### ISSUE TITLE
Question on Migrating Prestashop 1.7.5.1 to 17.6.1 ?

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#16557]
3-4 months ago i've seen that updating from 1.7.5.1 to 1.7.6.0 was not possible due to Kernel differences. Since i have problem with French Canada locales, i would like to know if the upgrade to version 1.7.6.1 is possible and will work well?

**Comment by khouloudbelguith** [comment]
Hi @8ternity,

As always, you can use the 1-click update to upgrade between minor versions without much trouble.
PS1.7.6.1 is fixing a lot of regressions of 1.7.6.0.
Also, in a few days, PS1.7.6.2 will be released.
5 days ago, we just released a new version 1-click upgrade: https://github.com/PrestaShop/autoupgrade/releases
You can download it from our addons Market place: https://addons.prestashop.com/en/data-migration-backup/5496-.html
In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks!
