### ISSUE TITLE
ps_mailalerts new order notification - logic for displaying customized products is broken

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16551]
**To Reproduce**
1. Make a customizable product. A text or file field (optional customization).
2. Go to FO. Open up the product.
3. Customize it, add it to cart. - Customization A
4. Customize it again, add it to cart. - Customization B
5. Do not customize it, add it to cart.
6. Your cart - 3 products - 1 default, 2 customized.
7. Order it.

**Resulting email table**
- Product - Customization A + Customization B
- Product - Customization A + Customization B
- Product - Customization A + Customization B

**Why is it wrong - ps_emailalerts.php (lines 300-320)**
```
foreach (product in order) {
	if (product ID found in customized datas) {
		foreach (customization for this product id) {
			// echo customization
		}              
	}
}
```

**Additional information**
PrestaShop version: 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.1 & ps1.7.5.2 & Mail alerts v2.1.1.
![image](https://user-images.githubusercontent.com/16067358/69647593-100bad80-106a-11ea-94e8-2ebb4034b2ec.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith @matks Hi guys, made a PR to fix this problem. Check it out.

https://github.com/PrestaShop/ps_emailalerts/pull/28

**Comment by khouloudbelguith** [comment]
Hi,

In the BO, it is OK
![image](https://user-images.githubusercontent.com/16067358/69708785-80fba580-10fc-11ea-8642-8915e2e79233.png)

Thanks!
