### ISSUE TITLE
Quickview and product flags bug 

### ISSUE THREAD

**Issue by dreamtheme** [PrestaShop/PrestaShop#16633]
When you are on the main page at the "popular products", and you have one of the products with "pack" label or with "on sale" label active, and you click the "quick view" button for the "pack" or "on sale" labeled product, then use the arrow buttons in quantity to change the quantity to 2, then the "on sale" or the "pack" label is applied to all products in "popular products" incorrectly.

See the screens.

**Screenshots**
![scr1](https://user-images.githubusercontent.com/17176009/69906205-7412d680-13c8-11ea-93b4-07803558b59c.jpg)

![scr2](https://user-images.githubusercontent.com/17176009/69906209-7ecd6b80-13c8-11ea-8e4e-2f2de8128ff5.jpg)

PrestaShop version: 1.7.6.1

**Comment by dreamtheme** [comment]
Tested additional versions
Also happens in 1.7.6.2
Does not happen in 1.7.5.2

**Comment by khouloudbelguith** [comment]
Hi @dreamtheme,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0, PS1.7.6.1 & PS1.7.6.2.
Same issue on the category page.
Same issue with **Pack** label & **New** flag & **Online Only** flag.
https://drive.google.com/file/d/1QIl9E6cE9KQGqG0OK2_8vB0DFpb7E9nZ/view
Before
![image](https://user-images.githubusercontent.com/16067358/69956758-2d74c780-1501-11ea-9bf6-6ab2975cddb8.png)
After
![image](https://user-images.githubusercontent.com/16067358/69956763-36659900-1501-11ea-9335-384d2373f4f2.png)
If we refresh the page => OK.
It is OK with PS1.7.5.2.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by dennispw** [comment]
This line simply needs a more specific selector to only target the currently viewed product: https://github.com/PrestaShop/PrestaShop/blob/33684a3828f66e3a0e91ed53a8239813dcef41dd/themes/_core/js/product.js#L186

**Comment by dreamtheme** [comment]
From what i see, its not only the ".product-flags" that needs specific selector for the currently viewed product, but the rest of the classes too.

**Comment by khouloudbelguith** [comment]
Related to: https://github.com/PrestaShop/PrestaShop/issues/9919

**Comment by marionf** [comment]
Fixed by #16852
