### ISSUE TITLE
Speed Improvment - OrderController is always called a second time at least

### ISSUE THREAD

**Issue by cedricfontaine** [PrestaShop/PrestaShop#16661]
I can't find the reason why the OrderController is always refreshed after a POST call to get the page using a GET.
It's really annoying cause it will double the time spent to load the page and will execute the same hook a second time, api calls...

The problem happens in OrderController initContent and it redirectwithnotification only if there is no error. Could you explain why ?

```php
        if (!$this->checkoutProcess->hasErrors()) {
            if ($_SERVER['REQUEST_METHOD'] !== 'GET' && !$this->ajax) {
                return $this->redirectWithNotifications(
                    $this->checkoutProcess->getCheckoutSession()->getCheckoutURL()
                );
            }
        }
```

**Comment by khouloudbelguith** [comment]
Hi @cedricfontaine,

Thanks for your report.
Ping @PrestaShop/prestashop-core-developers

Thanks!

**Comment by PierreRambaud** [comment]
Afaik, it's because some data need to be refreshed and unfortunately, we are not using an API or a front with reactive properties, so we have to rebuild it manually which is consuming time and can include risk. The best way to handle it is:

- GET the form
- Submit in POST
- Everything is OK, Redirect to Get the Form. 

By the way, the Order page has been migrated with the 1.7.7.0 (which is coming really really soon)
