### ISSUE TITLE
Product is added to cart with customization, when it should not

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16682]
**To Reproduce**
1. Set up an optional customization field on a product.
2. Go to this product in FO.
3. Customize it, save it, add it to cart.
4. Hit continue shopping.
5. Product page will refresh, saved customization will disappear visually.
6. Add the product to cart again. It should be added without customization, but it is added WITH the previous customization.

**The cause**
The input field is not updated on prestashop updatedProduct.
`<input type="hidden" name="id_customization" value="9" id="product_customization_id">`

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I manage to reproduce the issue with PS1.7.6.2 & PS1.7.5.2.
https://drive.google.com/file/d/15zJmLlV8TMc3OZLVZLIGhYBZ-Z4oFm-p/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Hlavtox** [comment]
Hi, @khouloudbelguith, can you add it to 1.7.7.1 milestone? 

It should not be hard to fix. When you add something to cart, change quantity or change combination, some parts of product page are updated by JS, but this line is not. We only need to update that one line or move it to some other part of TPL, so it gets updated.

**Comment by marionf** [comment]
Hello @Hlavtox 

This issue can't be part of the 1.7.7.1 as it's not a regression of the 1.7.7.0
You can read in our article about [patch release lifecycle](https://build.prestashop.com/news/ps17-patch-release-lifecycle/), we integrate in the patch versions only regressions from the last minor version or security fixes.

You seems to have an idea to fix this issue, you can submit a PR on develop branch to see this issue fixed in 1.7.8.0 if your PR is successfully reviewed and tested :)

**Comment by Hlavtox** [comment]
Hi @marionf, I made a PR, can you test it? :-) https://github.com/PrestaShop/PrestaShop/pull/22145

**Comment by marionf** [comment]
Good to see you contribute :+1: 
I am not from the QA team, but don't worry they will test your PR once it has been reviewed and approved by the maintainers :)
