### ISSUE TITLE
Stock manager will not show combinations with "-" in name

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#16706]
When I create an attribute group named like this: "Example-name", the stock manager combination GUI is broken, where only the portion behind the "-" is shown. See screenshot.

![Screenshot 2019-12-05 15 25 58](https://user-images.githubusercontent.com/30602638/70243903-d0cd1300-1773-11ea-9e4e-91f43e5b4ee5.png)
![Screenshot 2019-12-05 15 27 17](https://user-images.githubusercontent.com/30602638/70243907-d32f6d00-1773-11ea-809f-270972a40db3.png)

PS 1.7.6.1

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

I manage to reproduce the issue with PS1.7.6.2 & PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/70246926-c7927500-1778-11ea-9cf4-006ff35f1d2c.png)
![image](https://user-images.githubusercontent.com/16067358/70246961-d711be00-1778-11ea-8764-c8ad5ac81533.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
