### ISSUE TITLE
order validated but without products

### ISSUE THREAD

**Issue by Cyrilnel** [PrestaShop/PrestaShop#16711]
Hello,
I have a problem when creating orders.
A customer can place an order normally on my website and validate it when the order arrives on the BO we do not have the details of the products ordered.
I have looked in my cart, I have the details of the products ordered with the right order reference.
I can't find the source of the problem because there have been no changes on my website.

PrestaShop version: 1.6.0.5
PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @Cyrilnel,

I did not manage to reproduce the issue with PS1.7.6.2.
![image](https://user-images.githubusercontent.com/16067358/70247216-4e475200-1779-11ea-9a96-dc83867a3fbb.png)

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.
I will close the issue, thanks!
