### ISSUE TITLE
Viewed Products

### ISSUE THREAD

**Issue by corsik** [PrestaShop/PrestaShop#16739]
**Describe the bug**
The names of the viewed products in Russian, in the user’s card are displayed in the wrong encoding.

**Screenshots**
![image](https://user-images.githubusercontent.com/1533248/71972277-a22bd780-320c-11ea-9c8e-cd1b9ad5459f.png)

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1.21

**Comment by khouloudbelguith** [comment]
Hi @corsik,

I manage to reproduce the issue with PS1.7.6.0 & PS1.7.6.2.
Steps to reproduce the issue:
1. Add the Russian language
2. Edit the language employee to Russian
3. Add some product with a Russian name for example (СВИТЕР С КОЛИБРИ)
4. Go to the FO, sign in with Customer C & add this product to cart
5. Go to the BO => Customer => View this customer
6. Check the Viewed Products section
![image](https://user-images.githubusercontent.com/16067358/70429597-2b6ab580-1a79-11ea-875b-43681ad36125.png)

It is ok with PS1.7.5.2
![image](https://user-images.githubusercontent.com/16067358/70429750-843a4e00-1a79-11ea-9390-634070decceb.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by eternoendless** [comment]
Closed via #17065
