### ISSUE TITLE
second level pagination doesn't work in back office 

### ISSUE THREAD

**Issue by mamunhosen** [PrestaShop/PrestaShop#16732]
**Describe the bug**
There is a bug in all second level pagination in prestashop 1.7.4.2. For example in categories tab more than 100 categories I have and this level pagination works fine. If I click one of the category that has 50 subcategories and in this level pagination doesn't work. if I click on next button it redirects to parent page pagination.
**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop version: 1.7.4.2
PHP version: 7.0

**Comment by khouloudbelguith** [comment]
Hi @mamun-hosen,

The Category page in the PS1.7.6 was migrated to Symfony.
So, a lot of issues are fixed.
The second level pagination in the categories page is well working.
I attached a screen record
https://drive.google.com/file/d/1rRYkku8YJILoyrAifLklINMVY1-yXHEC/view
Thanks to check & feedback.

**Comment by mamunhosen** [comment]
Hi @khouloudbelguith 

Thanks for your response. 
So I need to upgrade the system from 1.7.4 to 1.7.6 to fix the issue?? right??

**Comment by khouloudbelguith** [comment]
@mamun-hosen, yes!
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
I close the issue, feel free to open a new one when needed.

Thanks!
