### ISSUE TITLE
ps_facedsearch enabled: Product in wrong category 

### ISSUE THREAD

**Issue by Emmanuel974** [PrestaShop/PrestaShop#16754]
Hi,
When faced search module is enabled with View sub categories products OK, the products and category are mix
You know this issue ?

Best regards,

Chrome
PS 1.7.5.2
PHP 7.0.33-0+deb9u3 (cli)
ps_facedsearch v3.4.0

**Comment by khouloudbelguith** [comment]
Hi @Emmanuel974,

The button "Show products from subcategories" is here to only display products that are in the "Main category" not the latest one.
Otherwise where it should be displayed if you have this:
![image](https://user-images.githubusercontent.com/1462701/58570390-2dd19480-8238-11e9-8d30-98d955a13485.png)
![image](https://user-images.githubusercontent.com/1462701/59031604-70145a80-8864-11e9-9255-bb486e3fbd50.png)
As you can see on the top right corner, it's written `Main category` not `Default category`.

You're talking about how you manage your categories, with only one level of category
In my situation, and if I take your definitions.
- `Clothes` is the main category for `Women` but not for `Men` and is not a subcategory of `Home`
- `Men` is the `Main category` for `Awesome subcategory` and not a subcategory for `Men`
- `Women` is a subcategory for `Clothes`

Thanks to check & feedback.

**Comment by Emmanuel974** [comment]
Hi,
Thank you.
Have you an older addon version with button price and not slider price please ?
Best regards,

**Comment by khouloudbelguith** [comment]
@Emmanuel974, an old version of ps_facetedsearch?
https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v2.2.1
[ps_facetedsearch.zip](https://github.com/PrestaShop/PrestaShop/files/3949582/ps_facetedsearch.zip)
Thanks to check & feedback.

**Comment by Emmanuel974** [comment]
Yes thank you very much.

See you,

**Comment by khouloudbelguith** [comment]
@Emmanuel974, you are welcome!
Feel free to open a new one when needed.

Thanks!
