### ISSUE TITLE
A partial refund does not reduce the sales for the day

### ISSUE THREAD

**Issue by thomashulin85** [PrestaShop/PrestaShop#16770]
Bonjour,

Un de mes clients se plaint car il effectue des remboursements partiels sur certaines commandes qui génèrent des avoirs, mais le CA ne baisse pas ni dans le dashboard ni dans les statistiques.

---
#### Describe the bug

One of my clients complains because he makes partial refunds on certain orders which generate credits, but the sales does not drop either in the dashboard or in the statistics.

#### Expected behavior

Refunds should be taken into account in both modules.

#### Steps to Reproduce

1. Create an Order
2. Make a partial refund
3. Go to Dashboard
4. See error > the refund is not taken into account

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/70626715-3a8e6680-1c25-11ea-9415-dbacec6218c1.png)
![image](https://user-images.githubusercontent.com/16067358/70626780-57c33500-1c25-11ea-8d47-e942adc3d2b5.png)
![image](https://user-images.githubusercontent.com/16067358/70626871-7c1f1180-1c25-11ea-89d0-0692ae4fabda.png)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @thomashulin85,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.2.
![image](https://user-images.githubusercontent.com/16067358/70626715-3a8e6680-1c25-11ea-9415-dbacec6218c1.png)
![image](https://user-images.githubusercontent.com/16067358/70626780-57c33500-1c25-11ea-8d47-e942adc3d2b5.png)
![image](https://user-images.githubusercontent.com/16067358/70626871-7c1f1180-1c25-11ea-89d0-0692ae4fabda.png)
The sum of revenue is not change doesn't remove the partial refund.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by leup** [comment]
Any news on this please ? Is the roadmap visible anywhere ?

**Comment by khouloudbelguith** [comment]
Hi @leup,

Sorry, not fixed yet.
But PrestaShop is an open-source project, so it can be solved before if someone submits a pull request to solve it.

Thanks!

**Comment by Robin-GH** [comment]
Hi guys! 
Any news on this issue yet? 

Thanks!

**Comment by Progi1984** [comment]
@PrestaShop/product-team Two questions for you :

* Does the module dashtrend have to consider refunds in their calculation ?
![image](https://user-images.githubusercontent.com/1533248/96846149-caaa5880-1451-11eb-8f0a-2894861db174.png)

* Does the module statssales have to consider refunds in their calculation ?
![image](https://user-images.githubusercontent.com/1533248/96846289-fe857e00-1451-11eb-84d3-54fd06edc79f.png)

**Comment by marionf** [comment]
@Progi1984 

Yes, refunds should be taken into account in both modules

**Comment by Progi1984** [comment]
@marionf : Fixed on
- statssales : PrestaShop/statssales#18
- dashtrends : PrestaShop/dashtrends#34

**Comment by Progi1984** [comment]
@marionf It's fixed in statssales & dashtrends.
