### ISSUE TITLE
Redirect 301 in multistore 

### ISSUE THREAD

**Issue by Majusek** [PrestaShop/PrestaShop#16794]
**Describe the bug**
I have three domains in shop:
domena2.fr
domena3.es
donena4.com

I need make a redirection from:
domena3.es to domena2.fr <- it's ok. In redirection checker I see 301.

But when I set redirection in htaccess for product which looks like that:
Redirect 301 https://www.domena3.es/category/1-product https://www.domena2.fr/category-new/1-product-new

In redirect checker I see:
301 https://www.domena3.es/category/1-product to https://www.domena2.fr/category/1-product
302 https://www.domena2.fr/category/1-product to https://www.domena2.fr/category-new/1-product-new

At first 301 change only domain name, at second 302 change all url.
I looking for a solution but don't know why is happens.

Any ideas?

Thanks for any suggestions.

**Additional information**
PrestaShop version: 1.6.1.4

**Comment by khouloudbelguith** [comment]
Hi @Majusek,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
