### ISSUE TITLE
bug: Cart cannot be loaded or an order has already been placed using this cart

### ISSUE THREAD

**Issue by flopez1977** [PrestaShop/PrestaShop#16814]
Hello, everybody.
In a PS 1.6.2.4 (good also happened in the 1.6.1.4 and that's why we tried to update the latter to see if it was solved but we remain the same)
In too many occasions when we are making a manual order, when putting a product (it is not any concrete this is random), we get the error that
"Cart cannot be loaded or an order has already been placed using this cart" we tried a thousand ways, we have updated, cleaned database all over the sides etc,
we manage to mitigate it out so much, but it keeps coming out. They are products with a lot of stock and it is rare that it is just because that product has been taken from the web.
Let's see if anyone has happened and tell me how he has solved it.

**Comment by khouloudbelguith** [comment]
Hi @flopez1977,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

PS: we have this issue: https://github.com/PrestaShop/PrestaShop/issues/9866, it is added to our bug roadmap, but it is just an error in logs.

Thanks!
