### ISSUE TITLE
Error in mails/it/order_customer_comment.html

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#16829]
Hi
I found an error in the file
mails/it/order_customer_comment.html
it is written firstrname instead of firstname
it is necessary to remove the "r" after first

the english version is ok
bye

**Screenshots**
![2](https://user-images.githubusercontent.com/653230/70905444-2ae79700-2004-11ea-80ef-b0ae1a673b2a.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by mariem-abid** [comment]
Hi @maofree,

Thank you for your report.
We'll first try to reproduce it and we'll come back to you if we need more information.

**Comment by khouloudbelguith** [comment]
Hi @maofree, thanks for your report.

I manage to reproduce the issue with PS1.7.6.1 & PS1.7.6.2.
In fact, this issue was fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/14945
It is merged, but this modification was removed again by this PR: https://github.com/PrestaShop/PrestaShop/pull/14719/files#diff-ad069b98e9b581f219f28732198910d1L253
So, it is a regression
![image](https://user-images.githubusercontent.com/16067358/70984722-4366b880-20bb-11ea-8c01-e36b005967b7.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Ping @jolelievre

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/16888
