### ISSUE TITLE
Breadcrumb missing on my account page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16836]
There is no breadcrumd in my account page on the front office.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Original description : 

If I make a PR fast, can we make it to 1.7.7?

**Missing breadcrumbs in these controllers**
bestsales
newproducts
pricesdrop
myaccount
password
Login page + registration

**Incomplete breadcrumbs in these controllers**
history - last key is missing
identity - last key is missing
discount - last key is missing
addresses - last key is missing
orderslip - last key is missing

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Is it the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/15440?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith It's different. I made a PR. Breadcrumbs on listing pages have been already added by someone else.

**Comment by khouloudbelguith** [comment]
@Hlavtox, thanks!

**Comment by colinegin** [comment]
Hello @Hlavtox, i've slightly modified your issue to take into account your PR.
You said that breadcrumbs on listings have already been added, do you know in which PR ?

Thanks !

**Comment by Hlavtox** [comment]
Hi @colinegin, it has been done by @SebBareyre 👍 

For example, new products page here: https://github.com/PrestaShop/PrestaShop/commit/c922f6e753ded0df942119b6489b00cefb260562

**Comment by colinegin** [comment]
Hello @Hlavtox and happy new year ! 

If I sum what has been done and will be available in 1.7.7: 
bestsales : OK
newproducts : OK 
pricesdrop : OK 
myaccount : OK 
password : OK
Login page + registration : OK
stores : NOK #15440 
sitemap : NOK
suppliers : NOK
basket : NOK

Incomplete breadcrumbs in these controllers 
history - last key is missing : OK
identity - last key is missing : OK
discount - last key is missing : OK
addresses - last key is missing : OK
orderslip - last key is missing : OK

**Comment by Hlavtox** [comment]
Hi @colinegin, I already made a PR #16837 for the my account pages, if you can merge it, there will be no missing breadcrumbs in 1.7.7.

Happy new year for you guys! 🎉 :-)

**Comment by colinegin** [comment]
Great, I thought it was only the general "my account" page ! I edit my comment then :)

**Comment by sam-pires** [comment]
Hello all,
Considering the lack of rule for the Breadcrumbs implementation in the Front-office of PrestaShop I created an EPIC (#17131) to centralize the work on this topic.

We'll launch a study on our side to define the best rule/behavior to have, and then specify it.
We'll take into account several aspects, including:
- SEO
- User Experience best practices
- Technical feasibility/logic

Do not hesitate to share your experience and opinion about it in the EPIC comments, right here => #17131 

@Hlavtox, your PR for this issue is already in our development process.  Considering the pages you modified, I don't think it will be impacted by this work.
Do not hesitate to follow the EPIC to be notified of further evolutions.

Thanks

**Comment by sam-pires** [comment]
Hello, 
As several issues have recently been opened about breadcrumbs in the Front-office, I started a study on breadcrumbs to standardize and specify the rule on breadcrumbs -> #17131  
I pause this issue until I finish the study.

**Comment by Progi1984** [comment]
Fixed by #18221
