### ISSUE TITLE
OrderDetail->product_quantity_in_stock is wrong

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#16840]
**Describe the bug**
This commit screwed up the logic of computing items-in-stock quantity.
https://github.com/PrestaShop/PrestaShop/commit/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9#diff-706c99b0aadf150c801cec8a83a90cc1

Wrong line (1.7.6.2):
`$product_quantity = (int)Product::getQuantity($this->product_id, $this->product_attribute_id, null, $cart);`

Correctly functioning (from 1.6.1.23):
`$product_quantity = (int)Product::getQuantity($this->product_id, $this->product_attribute_id);`

**To Reproduce**
1. Make a product, set quantity to 1.
2. Check ps_stock_available, search the id_product, should be like this: quantity: 1, physical_quantity: 1, reserved_quantity: 0.
3. Order 1 piece of the product.
4. Go to order detail in BO, you will see a warning that the product you ordered was not/is not in stock. You also won't see the blue circle under the products quantity in the product list.
5. Check ps_order_detail, search the id_product and id_order, you will find **product_quantity: 1, product_quantity_in_stock: 0**.  But it should be **product_quantity: 1, product_quantity_in_stock: 1**.
6. Now, try it in older Prestashop or try it with the mentioned line change in classes/order/OrderDetail.php. It will work fine.

I do not want to make a PR, I don't know why this change was introduced, but on my side, I reverted it and I don't see any abnormalities.

**Additional information**
PrestaShop version: 1.7.6.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
>Check ps_stock_available, search the id_product, should be like this: quantity: 1, physical_quantity: 1, reserved_quantity: 0.

In my case with PS1.7.6.2 & PS1.7.5.2
1. quantity =1
2. physical_quantity = 0
3. reserved_quantity = 0
![image](https://user-images.githubusercontent.com/16067358/71001417-8c2f6900-20dd-11ea-9c7e-c5426fc804b6.png)
>Check ps_order_detail
1. product_quantity =1
2. product_quantity_in_stock =0

Ping @PrestaShop/prestashop-core-developers what do you think, `product_quantity_in_stock` should be `1`?

Thanks!

**Comment by Hlavtox** [comment]
@PrestaShop/prestashop-core-developers  Any update? Or am I missing something?

**Comment by jolelievre** [comment]
Hi @Hlavtox,

I'm gonna give a little more context just to be sure we're on the same page.

First `Product::getQuantity` uses the cart as a parameter for a good reason (most of the time), it needs the cart so that it can substract its quantity to the actual stock quantity (we could call it the virtual stock). The reason is that as long as a cart has not been ordered its quantities are not substracted from the actual stock, this allows multiple users to create their cart in parallel without reducing the stock each time (especially important when visitor doesn't checkout its cart in the end.

Here's an example:

- Product A has 10 in stock
- Cart has 5 product A
- Cart wants to add 6 product
- If `Product::getQuantity` doesn't consider the quantity in cart it would return 10 allow the operation thus cart would have 11 products which is not allowed by the stock
- hence `Product::getQuantity` computes `10 - 5` = 5 which is the virtual remaining stock


So that's to explain the necessity of this cart parameter when you are checking the product quantity while creating your cart, now this is the most common use case but there are some others when you don't want that.
For example, when editing an order the product from the order's cart are actually out of the stock, so you don't want to substract the cart value and using `Product::getQuantity` without the cart parameter is valid.

Now your description of the is lack a little bit of precision because you refer to a commit with many modifications and it feels like you are saying this cart parameter should never be used (which is incorrect). But from the rest of your description I assume you are actually referring to this special line in OrderDetail:

http://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/classes/order/OrderDetail.php#L733-L735

In this case the purpose is to save how much of the ordered quantity is available in stock and save it in `OrderDetail::product_quantity_in_stock` so in that specific case indeed we are aiming for the **real stock** not the **virtual stock** I hope I understood your issue correctly?


That said I'm not sure to understand why this field is useful? because I couldn't find any place where it is actually used? Maybe you can help with that?

**Comment by Hlavtox** [comment]
@jolelievre Let's take it from a different end. I think we mean the same thing, but you are too technical for me... :-)

In all versions of Prestashop, **product_quantity** column contains the quantity of products ordered.

In PS 1.6 (and 1.7 after my mod), **product_quantity_in_stock** contained the quantity of products in stock **at the time of ordering**. This allows the merchant to know, if everything the customer ordered was in stock **at the time of ordering**. Many customers will argue to you about what was or was not in stock, that's why we need this information.

In default 1.7, this column contains _probably_ the amount after ordering, but even that does not make sense. Why isn't customizable mug -2?

![table](https://user-images.githubusercontent.com/6097524/100127159-1dc36100-2e7f-11eb-93af-33cf4c2a80b0.JPG)

**Comment by Hlavtox** [comment]
@jolelievre @hibatallahAouadni I am now re-reading this after some time, now I understand what you meant.

We need to save the real stock at the time of ordering, not the virtual stock. So, without subtracting the amount in cart. This is how it worked for years.

The aim of this PR was clearly to support pack items, not to change behavior of saving quantity data to database - https://github.com/PrestaShop/PrestaShop/commit/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9#diff-706c99b0aadf150c801cec8a83a90cc1

**Comment by jf-viguier** [comment]
product_quantity_in_stock is really weird:
You have 10 in stock
- You order 3 : product_quantity_in_stock is set to 3
- You order 4 : product_quantity_in_stock is set to 4
- You order 6 : product_quantity_in_stock is set to 4
- You order 13 : product_quantity_in_stock is set to -3

**Comment by Hlavtox** [comment]
@jf-viguier See my PR, it works perfectly.

**Result:**
You have 10 in stock
You order 3 : product_quantity_in_stock is set to 3
You order 4 : product_quantity_in_stock is set to 4
You order 6 : product_quantity_in_stock is set to 6
You order 13 : product_quantity_in_stock is set to 10

**Comment by hibatallahAouadni** [comment]
Thanks @Hlavtox for your PR :superhero:

**Comment by jf-viguier** [comment]
@hibatallahAouadni I've done a PR too

**Comment by hibatallahAouadni** [comment]
Thanks @jf-viguier for your PR :superhero:

**Comment by jf-viguier** [comment]
product_quantity_in_stock should manage ordered quantity in stock ou total quantity in stock ? @hibatallahAouadni ?
What's the behaviour in 1.6 ?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team @jolelievre could someone please answer @jf-viguier question 🙏 

For this issue we have two different solutions proposed by @jf-viguier and @Hlavtox which one is better?

Thanks in advance ☺️

**Comment by Hlavtox** [comment]
The solution I provided restores the correct functionality from 1.6 and 1.7.2. Feel free to confirm.

**Comment by Progi1984** [comment]
Fixed by @Hlavtox in #26075
