### ISSUE TITLE
Fresh install 1.7.6.2 unable to update settings on most products - client denied by server configuration

### ISSUE THREAD

**Issue by ElenaAlexi** [PrestaShop/PrestaShop#16911]
I've installed Preshashop 1.7.6.2 and imported my database from 1.6 using phpadmin.

As described in the title, when I try to update a product , I get the error "unable to update settings on most products".

After checking the server error log, here's the error message that is generated when the product can't be updated:
`[Mon Dec 23 22:10:43.603776 2019] [authz_core:error] [pid 11817:tid 47270288447232] [client xxx.xxx.xxx.xxx:31265] AH01630: client denied by server configuration: /home/alexispo/public_html/img/p/5/5/5/7`

This always links to an image folder that doesn't exist in my file directory.

Could you please help me sort this out?

The server I'm using has Apache 2.4.41.

**Comment by khouloudbelguith** [comment]
Hi @ElenaAlexi,

`AH01630: client denied by server configuration`
This error occurs in particular if you update your server to version 2.4 without having modified the configuration file beforehand.
Since version 2.4, access is managed by the new mod_authz_host module, which also manages all other authorization checks. The new directives to use are "Require any", "Require all" and "Require none". To allow access to everyone for a directory, only one line is necessary:
`Require all granted`

This issue is a server problem.
You need to check your host for more details.
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by ElenaAlexi** [comment]
Hi @khouloudbelguith ,

thanks for your response.
It's not possible to contact my host at the moment, so I was wondering if you can clarify something.
Do you mean that this line needs to be replaced in the htaccess file of the img directory?

Many thanks in advance,
Elena

**Comment by khouloudbelguith** [comment]
@ElenaAlexi, if you are using a virtual host, you can add it to your conf file.
In my case
```
<VirtualHost *:80>
      ServerAdmin test@test.com
      ServerName prestashop.local
      DocumentRoot /projet
      <Directory /projet/>
              Options FollowSymLinks Indexes MultiViews
              AllowOverride All
Allow from all
              Require all granted
      </Directory>
        ErrorLog /var/log/apache2/prestashop-error_log
#        CustomLog /var/log/apache2/prestashop-access_log common
</VirtualHost>
```
Thanks!
