### ISSUE TITLE
The alert success is not correct when deleting files with Bulk action

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#16921]
**Describe the bug**
In the BO => Catalog => files => when we delete files with bulk action, the alert-success is not correct.
It is displayed "Successful deletion."
![image](https://user-images.githubusercontent.com/16067358/71466841-1738ef00-27c1-11ea-8839-4372798202ea.png)

It should be "The selection has been successfully deleted."
![image](https://user-images.githubusercontent.com/16067358/71466946-74cd3b80-27c1-11ea-96ae-405614e02951.png)

**To Reproduce**
1. Go to the BO => Catalog => files 
2. You should have more than one file
3. Try to delete files with Bulk actions
4. See alert-success, it is incorrect

It was ok with PS1.7.6.2

**Additional information**
PrestaShop version: develop
PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Ping @nesrineabdmouleh

**Comment by khouloudbelguith** [comment]
Ping @matks

**Comment by arouiadib** [comment]
I don't know why I can't reproduce this behaviour in 1.7.6.2 !

**Comment by arouiadib** [comment]
Thank you @khouloudbelguith ,

I am really interested to know if the requirement is to change the alert success string for all bulk delete actions in BO. I see that in some controllers the string is "Successful deletion" but for others "The selection has been successfully deleted." . Is the objective is to normalize the situation in all BO for bulk deletion? 

The main question is : where can I read such requirements? where can I find such specifications without burdening the comments section here with questions.

I have created a [PR](https://github.com/PrestaShop/PrestaShop/pull/16946) for `Files` controller. If it is a correct approach, please to let me know so that I proceed to changing this string for the other delete bulk actions (ContactsController, CategoryController.... )


Again, thanks for your usual time and help.

**Comment by matks** [comment]
> The main question is : where can I read such requirements? where can I find such specifications without burdening the comments section here with questions.

For years, these requirements only existed into the brains of the Product Management team of PrestaShop and (sometimes) in folders/documents (mostly google docs) shared inside the company ; so there was nothing available for you.

We know it was a very bad habit for an opensource project thanks to @ttoine and this is why we created the github repository https://github.com/PrestaShop/prestashop-specs. This repository goal is to host **all specifications** for PrestaShop and this is where you'll find such requirements in the future.

We'll try, for all future features, to 1st publish in this repository the specs and then implement it, so you will be able to see next-to-be-done items and maybe volunteer to work on them if you like the topic 😄 

However the repository was started a few months ago only. There are hundred of missing items in it because we now have to recover all specs from the past and write them in it. The Product Management team of PrestaShop has started this very big task and will carry it probably for years.

**Comment by arouiadib** [comment]
@matks Thank you for the time and for the invaluable information. Having a dedicated repository for specs is a great idea. 

I hope to be part of this task.  PrestaShop is making life easier for us, so any contribution is a huge pleasure.
