### ISSUE TITLE
Custom Attribute values for URL and Meta title texts are not working after enabling "Display attributes in the product meta title" - Solved in the FO > Product listing page

### ISSUE THREAD

**Issue by k0lv** [PrestaShop/PrestaShop#16939]
**Describe the bug**
Follow-up on [issue#11927](https://github.com/PrestaShop/PrestaShop/issues/11927).
I have enabled attributes display in Meta-title, but it seems not taking the values from the attribute configuration, instead uses just Name and Public Name.

**1. Enabled parameter:**
![image](https://user-images.githubusercontent.com/59282576/71515176-bab1fe80-28aa-11ea-829e-b771fc4e32cf.png)

**2. Defined different values for different scenarios:**
![image](https://user-images.githubusercontent.com/59282576/71515257-095f9880-28ab-11ea-8bb6-9f1c2308ad6f.png)

**3. Clear Shop Cache; Clear Faceted search cache and Re-index.**

**Results:**
**A)** URL uses back-office attribute name (Expected: URL value from Attribute configuration):
![image](https://user-images.githubusercontent.com/59282576/71515433-d538a780-28ab-11ea-8044-3f24ff579a45.png)

**B)** Meta title uses back-office attribute name (Expected: Meta title value from Attribute configuration):
![image](https://user-images.githubusercontent.com/59282576/71515479-1d57ca00-28ac-11ea-9b56-c6e351ae1b67.png)

**C)** Faceted search uses Public Names for URL (Expected: URL value from Attribute configuration):
![image](https://user-images.githubusercontent.com/59282576/71515582-9fe08980-28ac-11ea-9592-b15642269079.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @k0lv,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.2 & ps_facetedsearch v3.0.4
I have the same issue with PS1.7.5.2 & ps_facetedsearch v2.2.1.

PS: in the BO => Shop Parameters => SEO & URLs page => Display attributes in the product meta title is enabled

In the FO => Product detail page
1. The URL uses back-office attribute name
2. Meta title uses back-office attribute name
![image](https://user-images.githubusercontent.com/16067358/71576948-934d7280-2af2-11ea-9849-698ca4e1c33c.png)

3. In the Category page, when filtering with ps_facetedsearch 
![image](https://user-images.githubusercontent.com/16067358/71577007-d14a9680-2af2-11ea-9ed8-6a7f23ffb6eb.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/15688

**Comment by k0lv** [comment]
Hello, @khouloudbelguith 
Thank you for the fast reply.
Unfortunately I am not (yet) enough skilled to solve this issue.
Sorry.

**Comment by ivangallegoc** [comment]
Hello @khouloudbelguith when is expected to have a fix for the issue of the url_name that as today is completely removed? We have the same problem as @k0lv and for us is a big problem touching the core to try to fix this issue because we want to stay as standard as possible to update the PS always.

**Comment by khouloudbelguith** [comment]
Hi @igallego-webimpacto,

Ping @PrestaShop/prestashop-product-team what do you think about the priority of this issue?

Thanks!

**Comment by ivangallegoc** [comment]
Hi @khouloudbelguith 

Do you have an estimated date to solve this issue?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @igallego-webimpacto,

Sorry, no.
Our product team is responsible for the priority of issues.
PrestaShop is an open source project, so it can be solved before if someone submits a pull
Thanks for your understanding!

**Comment by PierreRambaud** [comment]
> the BO => Shop Parameters => SEO & URLs page => Display attributes in the product meta title

FYI, the faceted search module doesn't aim to change the Product Page behavior, it's only for the search system. 
I really don't know how the Meta title should be used :thinking:

**Comment by khouloudbelguith** [comment]
Hi @PrestaShop/product-team,

This issue is partially fixed by this PR: https://github.com/PrestaShop/ps_facetedsearch/pull/301.
For more details, I added this comment: https://github.com/PrestaShop/ps_facetedsearch/pull/301#issuecomment-771469712
Previously reported by @PierreRambaud here: https://github.com/PrestaShop/PrestaShop/issues/16939#issuecomment-752125462

I will re-open the issue.

Thank you!

**Comment by marionf** [comment]
@khouloudbelguith I think we should rather close this one and create a new issue with what remains to do
And eventually create several issues if the remaining things to do will not be fixed in the same place (in the core or in the module)

**Comment by khouloudbelguith** [comment]
Hi @marionf,

Thank you!
I will close this issue.
The new issue is created here: https://github.com/PrestaShop/PrestaShop/issues/23096

Thanks!

**Comment by coluccini** [comment]
Sorry to write over here, but I haven't had any luck on the PS forums… This module should update the listing page meta title and main title (text on the H1 tag) based on the applied filters?

I think that, if you are allowing search engine to index the filtered pages, that each one should have a different title, but I can find a way to do it… The only way is by making code changes?

<img width="700" alt="Screenshot 2021-03-23 at 14 38 53" src="https://user-images.githubusercontent.com/20334179/112155435-97791a80-8be5-11eb-8677-e647709441a5.png">
