### ISSUE TITLE
The filter button to display the faceted search filters is not well placed on a mobile

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#16933]
**Describe the bug**
When you want to make a filter though faceted search on a mobile, you have to click on "Filter" button to display the filters
Unfortunately it is not intuitive because the button is right next to the dropdown to sort products and it looks like you have to click on it after selecting a new sort option in the dropdown

 
**To Reproduce**
1. Make sure faceted search is enabled
1. Go to a category in FO with a mobile
2. See the "Filter" button 

**Screenshots**

![capture d'écran_2209](https://user-images.githubusercontent.com/13449658/71510938-d8726a00-2890-11ea-86bf-d46fe84e4366.png)

**Additional information**
PrestaShop version: All
PHP version: N/A

**Comment by colinegin** [comment]
What is your recommendation @prestascott and @TristanLDD ? 
I've assigned @NeOMakinG to this issue, he'll be able to work on it once he's informed what he has to do !

**Comment by prestascott** [comment]
Thank you @marionf, 

Here is my redesign proposition (https://invis.io/AVVEP1YS64M):
- The 'Sort by' becomes a button and redirects to a full screen list where users can select different elements. There is no need to click on an 'Apply' button because it applies automatically (same amount of clicks than before).
- The 'Filter' button also redirects to a full screen list so users cannot be disturb by what is in the background (search bar, menu, etc...) and can focus on what is really important : filters. 
- When users have at least selected 1 filter it appears on the button and its background becomes blue with white text: 'Filters (1)'.

Wdyt @marionf @colinegin @TristanLDD ?

**Comment by marionf** [comment]
Perfect, thank you @prestascott :+1:

**Comment by NeOMakinG** [comment]
Changing this behavior will introduce some breaking changes, if a child theme did some css changes on these fields, it will break, for example the select item will not be a select anymore but an action button with popup, or a dropdown, which is different and child themes can probably break on that, isnt there another way of refactoring it or can we implement it without caring of breaking changes ? :/

@marionf @prestascott

**Comment by NeOMakinG** [comment]
Should be done on major version probably

**Comment by NeOMakinG** [comment]
Can be closed in favor of the new theme I think so, in order to avoid introducing BC
