### ISSUE TITLE
Generating sitemap in Backend with >25000 links fails

### ISSUE THREAD

**Issue by lichesser** [PrestaShop/PrestaShop#16991]
Hello,

PrestaShop: 1.7.6.1

if you have a shop with >25000 products, generating the sitemap in the backend (not via the Cron-URL) fails.

The first sitemap file is generated and contains ~25000 URLs.

The redirect (with `continue=1`) which is supposed to create the next sitemap file doesn't work. 

The redirect ends up in the "Module Catalog" in the backend.

Thus the missing sitemap files and the sitemap index files are not created.

**Comment by khouloudbelguith** [comment]
Hi @lichesser,

I manage to reproduce the issue with PS1.7.6.2 & `gsitemap` v4.1.0.
https://drive.google.com/file/d/19cSxMqTYP8nm0SVIbRfv7utYhkx70Xg6/view
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by colinegin** [comment]
This issue is fixed by the following PR : https://github.com/PrestaShop/gsitemap/pull/127

Thanks @DavidBoone !

**Comment by Progi1984** [comment]
Fixed in PrestaShop/gsitemap#127
