### ISSUE TITLE
Is it necessary to update all license headers for 2020 ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17007]
So far, each year we have updated all of our license headers to match the current year. As today is the 2nd of January, I expect another huge PR similar to https://github.com/PrestaShop/PrestaShop/pull/11997 to pop up.

Each year, we wonder whether or not this has to be done 🤔as in the OSS community different opinions arise.

This year I suggest we explore this issue and settle it once for all, and in order to make sure this question is 100% answered we should write an [ADR](https://github.com/PrestaShop/ADR) for that.

So, question is: Is it necessary to update all license headers for 2020 ?

ping @ttoine @toutantic @PrestaShop/prestashop-core-developers 

**EDIT**: answer has been provided, see below https://github.com/PrestaShop/PrestaShop/issues/17007

**Comment by davidglezz** [comment]
I would love to have the license date no longer updated.

Some projects use: 2007-Now PrestaShop SA and Contributors

In addition, reduce repeated information: "2007-2019 PrestaShop SA and Contributors" which is also in @copyright

**Comment by zalexki** [comment]
yeah just do like symfony and redirect licensing to a single LICENSE file at root of project

**Comment by ttoine** [comment]
It's like for a book: it must be somewhere, usually, you don't add it in the manuscrit/draft, but in the final version when you press the book to release it and distribute it in librairies. When you press again the book, you release it with the new release date. (This is an example to try to make it simple, let me know if it works)

I will not tell you that there are many ways to do that with software, you already knows at least those 3:
- change each year all files
- have one license file for all and change the date only here
- update the date only when a file has been modified, and then set a date in a general license file for the release only ((if a file didn't changed since 2017, why modify the date? the code is still covered by the OSL license and that don't expire)

Other possibilities are not listed, please add what you know on other project in a comment.

Note that the 3rd is my favorite but I am not the one who can take a decision. We must also check with Marine and Domitille that this is ok for them, as they are our lawyer and must validate such a decision regarding intellectual property management

**Comment by matks** [comment]
> * have one license file for all and change the date only here

Does this mean removing all license headers (= all this text on top of each file) from the project ? Or just remove the date from the license headers ?

**Comment by ttoine** [comment]
just remove the date. it's mandatory to provide copyright information per file, for compliance.

maybe we should take the opportunity to become follow REUSE principles:
https://reuse.software/tutorial/

**Comment by matks** [comment]
> have one license file for all and change the date only here

This is the solution I prefer.

> update the date only when a file has been modified, and then set a date in a general license file for the release only ((if a file didn't changed since 2017, why modify the date? the code is still covered by the OSL license and that don't expire)

I dislike this solution because it could make some people believe we are just messy 😅it would look strange to have different dates in the same application license headers

@eternoendless Are you OK with:

> have one license file for all and change the date only here

**Comment by matks** [comment]
OK, we want to follow `have one license file for all and change the date only here`
So we'll contact PrestaShop legal team

**Comment by matks** [comment]
Legal team of PrestaShop is on the topic, waiting for the answer

**Comment by Hlavtox** [comment]
I vote for license headers not being updated. 😄 Everytime I do upgrade, when new year came, I compare the files and billion of them seem to be changed, only to discover that only the date changed...

But I don't know the legal point of view - does it need to be there?

**Comment by matks** [comment]
Still waiting for Legal team POV 😅 I'm afraid without confirmation, we'll have to update all files again

**Comment by matks** [comment]
FYI Legal team answered 🎉 
- we can stop putting the "current" year in license header, "Since 2007" is enough
- we have an updated License header template

We will now need to update all license headers, but when it is done we wont need to it again 😊 

Thanks @PierreRambaud for doing it on the core https://github.com/PrestaShop/PrestaShop/pull/19752
