### ISSUE TITLE
Unit price set to 0 on product->save 

### ISSUE THREAD

**Issue by Daniel-Informax** [PrestaShop/PrestaShop#17010]
**Describe the bug**
If you get a product with a unit_price and you save/update this product from code (not the backend), the unit_price is set to 0.

**To Reproduce**
From backend: 
1- Create a product 
2- Add a unit_price_ratio and unity from backend
3- Save the product
4- Create an script with the following code

$idProduct = 1; //the product id of the created product
$product = new Product($idProduct);
try  {
$product->save();
}catch(Exception $ex) {
     echo $exc->getTraceAsString();
}
5- Reload backend and the unit_price_ratio will be set to 0

**Additional information**
PrestaShop version: 1.7.1.5 -> 1.7.6.2

It doesnt matter if you change the unit_price_ratio on the script, it will be save as 0 ALLWAYS

**Comment by khouloudbelguith** [comment]
Hi @Daniel-Informax,

Thanks for your report.
We have two issues related to the unit price.
First issue not fixed as reported here: https://github.com/PrestaShop/PrestaShop/issues/16353
Second issue fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16729 as reported here: https://github.com/PrestaShop/PrestaShop/issues/16353

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @Daniel-Informax,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
