### ISSUE TITLE
Add a message when symbol and format are reseted in currencies

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#17024]
In international -> localizations -> currencies 
Add a message when we reset symbol and format. It's not very obvious that the symbol and format is reseted.

**Comment by MatShir** [comment]
@sarahdib do you think it is needed on the currency's form and the language list?

**Comment by LouiseBonnard** [comment]
@sarahdib, @MatShir, here are some wording suggestions to explicit behaviors:

- I think the CTA wording should be 'Restore default settings' instead of 'Reset default settings' (which gives the impression that the default settings will be deleted permanently)

- When clicking both reset buttons (cf. screenshots below), a pop up must be displayed with the following wording: 'Are you sure you want to restore default settings?' + 'Restoring your currencies’ default settings will delete all the customizations you made before. Parameters will look just the same as when a currency is freshly imported.' + 'Cancel' + 'Restore'

<img width="207" alt="Capture d’écran 2020-01-06 à 15 41 54" src="https://user-images.githubusercontent.com/32565890/71829068-10a15600-30a4-11ea-8b48-865957d31f72.png">

<img width="121" alt="Capture d’écran 2020-01-06 à 15 42 14" src="https://user-images.githubusercontent.com/32565890/71829079-1434dd00-30a4-11ea-9dc3-6b88a96abb3e.png">

- Add a help text below the second part of the page, below the 'Format settings' title and instead of the lorem ipsum (cf. the mockup [here](https://projects.invisionapp.com/d/main?origin=v7#/console/11916080/386388367/preview?scrollOffset=1416)), with the following description: 'You might need to adapt the predefined format display of your currencies, or edit their symbol. Note that restoring default settings will erase symbol and format customizations'

**Comment by sarahdib** [comment]
@MatShir I think it's necessary because when the change is applied if the default setting is a , and you change it to . it's not very visible that the default setting was restore.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/17385/
