### ISSUE TITLE
Product Meta description not filled by default in the SEO preview

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#17078]
Hello,

I think i just found a small bug in the SEO tab in product pages.
When adding a title to the product, the SEO preview is automatically filled with the title in the meta title part.
But when adding a description of the product in the summary block, nothing is added to the meta description part, while it should. 

What do you think @khouloudbelguith @marionf ?

**Comment by marionf** [comment]
@colinegin 

The thing is that we recommend a meta descirption of 160 characters maximum while it's set at 800 by default for the summary
We could take the 160 first characters of the summary and put them in the meta title, but I am not sure it's a good idea.
Or change the max size of the summary for 160 instead of 800 by default.
Wdyt ?

**Comment by colinegin** [comment]
There's not limit on the title so I guess we should have the same behaviour for description and meta description ?

**Comment by marionf** [comment]
Yes, but I am wondering: it is a good practice to copy the summary in the meta_title if the summary is more than 160 characters as recommended ? 

There is no problem for name and meta_title because both are `varchar(128)` type
While description_short (= summary) is `text` type and meta_description is `varchar(512)` type
Which means if the summary have more than 512 chars, the save of the product will fail with an error message like below

![capture d'écran_2257](https://user-images.githubusercontent.com/13449658/72090505-7ee95100-330e-11ea-9d89-10052f54984c.png)


If we want to do this, we need to increase the limit of 512 for the meta_description

**Comment by colinegin** [comment]
When checking in the user doc, it is said :

> Summary and Description
> Describing your product well is essential, both for the customer (the more information, the better) and search engines (it will help your shop appear in more search requests).
> At the bottom of the screen, the two description fields each serve different purposes:
> The “Summary” field enables you to write a short description that will appear in search engines and in the description for your product. 
> This field is limited to 400 characters by default: if you exceed that limit, PrestaShop will warn you with a message in red below the field. You can change that limit in the “Products” preference page, where you will find the “Max size of product summary” option.
> The “Description” field enables you to write a full description of your product, which will appear directly on the product page. The text editor offers a wide range of options for creating visually attractive descriptions (font, size, text color, etc.).
> While this second field has no limits, there is such thing as too much content: strive to provide the essential information in a compelling way, and your product should be good to go.

So I guess summary should automatically fill the meta description field, but maybe we should reduce the number of letters recommended (to 512) to help merchants follow good practices. 

What do you think @marionf ?

ping @LouiseBonnard just to follow this issue and decide if we should edit the doc.

**Comment by marionf** [comment]
Yes, it seems good :+1:

**Comment by colinegin** [comment]
Ping @MatShir as it is related to product page.
