### ISSUE TITLE
Server error when quickview product quantity changed

### ISSUE THREAD

**Issue by Kharabet** [PrestaShop/PrestaShop#17104]
### Describe the bug 
Server error when quickview product quantity changed

### Expected behavior
No error message is displayed

### Steps to reproduce:
> Listed by @yanmakouf 

1. go to FO
2. click on any product to open the product page
3. scroll down open related product quick view modal
4. increase the product quantity
5. see "undefined" error message

---
1. Open any product page with additional parameters (ie. color):
![image](https://user-images.githubusercontent.com/14793248/62200879-f5147f80-b38e-11e9-83a9-d83df0988c13.png)
2. Open quickview product in the category products widget:
![image](https://user-images.githubusercontent.com/14793248/62200926-0e1d3080-b38f-11e9-90db-b353075ebde5.png)
![image](https://user-images.githubusercontent.com/14793248/62201048-46bd0a00-b38f-11e9-8596-8a63b2a7d437.png)
3. Close quickview. Now we see an error message under original product`s "add to cart" button.
![image](https://user-images.githubusercontent.com/14793248/62201136-6e13d700-b38f-11e9-850d-1a8317b625fd.png)
4. Error in the browser console:
![image](https://user-images.githubusercontent.com/14793248/62201184-913e8680-b38f-11e9-9507-46d14b48f5fb.png)

### Additional infos:

- PS version: 1.7.6.0
- PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @Kharabet,

I manage to reproduce the issue with PS1.7.6.2 & PS1.7.5.2 & the ps_categoryproducts module v1.0.4.
![image](https://user-images.githubusercontent.com/16067358/72541420-c9c11680-3882-11ea-85be-4c35010e338f.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Related to: https://github.com/PrestaShop/PrestaShop/issues/9919#issuecomment-490441708 
Thanks!

**Comment by matks** [comment]
@yanmakouf takes it

**Comment by yanmakouf** [comment]
I cannot seem to reproduce this bug on the develop branch. I see here a comment on related issue https://github.com/PrestaShop/PrestaShop/issues/9919#issuecomment-674761269. Maybe it is fixed ? Someone reproduces ?

**Comment by matks** [comment]
ping @PrestaShop/qa-team can someone try to reproduce ? 😄

**Comment by florine2623** [comment]
Hello @yanmakouf ,

I couldn't reproduce the exact same error, I have something a little different on develop branch:
<img width="1025" alt="Screenshot 2022-07-26 at 10 14 53" src="https://user-images.githubusercontent.com/16019289/180958004-63f2e5ca-423a-4c74-9e34-4cee0e511b5a.png">

https://user-images.githubusercontent.com/16019289/180958402-dd0d09e1-dfe9-4bda-b23e-02a5413c463a.mov

**Comment by hibatallahAouadni** [comment]
Ping @yanmakouf friendly reminder :wink:

**Comment by yanmakouf** [comment]
Hello, sorry for the late reply. I can reproduce the bug that @florine2623 mentioned. I will work on it starting today :)

**Comment by yanmakouf** [comment]
@florine2623 what is the expected behavior then ? just remove the "undefined" error ? Cause process seems to work fine to me, just this useless "undefined" warning to remove. right ?

So just to sum up the steps to reproduce : 

1) go to FO
2) click on any product to open the product page
3) scroll down open related product quick view modal
4) increase the product quantity / or modify any customization value (color, size...etc)
5) see "undefined" error message
