### ISSUE TITLE
Currency rate changes are not reflected in render

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#17121]
Assign currency rate to all templates, otherwise when rate changes, prices with old rates may be displayed if the page is in the cache.

see:
https://github.com/PrestaShop/PrestaShop/blob/cfe92813cc51397f21b0fb4a2108bd410c54a3b0/classes/controller/FrontController.php#L491
https://github.com/PrestaShop/PrestaShop/blob/cfe92813cc51397f21b0fb4a2108bd410c54a3b0/classes/controller/FrontController.php#L1563

It seems that also tax rates and other variables need to be added to prevent caching of not-up-too-date data.
>Edit by Khouloud

Prerequisites:
- enable cache
- at least one additional currency added/enabled

Steps to reproduce:
- open homepage and change currency to some non-main currency
- open the homepage and notice the prices (this cache the page)
- change the currency rate in BO
- refresh homepage and notice, that the prices are unchanged

**Comment by khouloudbelguith** [comment]
Hi @mvorisek,

Thanks for your report.
Could you please add steps to reproduce the issue in a new comment.

Thanks!

**Comment by mvorisek** [comment]
Prerequisites:
- enable cache
- at least one additional currency added/enabled

Steps to reproduce:
- open homepage and change currency to some non-main currency
- open homepage and notice the prices (this cache the page)
- change the currency rate in BO
- refresh homepage and notice, that the prices are unchanged

**Comment by khouloudbelguith** [comment]
@mvorisek, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.3
https://drive.google.com/file/d/1rEwZeH2BoALxfOVl_7caHjlKGzMA7uJi/view
This issue is reproduced only when Cache is enabled
![image](https://user-images.githubusercontent.com/16067358/73172874-4dd99080-4104-11ea-8785-05abe8b99b1f.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by mvorisek** [comment]
@khouloudbelguith Can this be prioritized? Displaying bad prices is major issues.

**Comment by mvorisek** [comment]
Please verify if this issue is still present, if yed, please fix urgently, displaying wrong price everywhere is a major and maybe even a legal issue.

**Comment by matks** [comment]
@mvorisek If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can invest into having it done. You can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request. This is how open source strives: different people rely on a common project, and each contribute to make it better as the sum of contributions benefit everyone.

This bug was labeled `Major` but it's not the only Major bug we have in the backlog. Developer time is limited, so if the amount of issues opened in a certain timeframe exceeds the amount of issues that can be processed using the available developer time, tasks will simply pile up. Due to the number of pending issues, sometimes they may get lost in the pile and be forgotten about, so it's not a bad idea to ping us there from time to time to remind us about it, even if it's been a long while, like you do here. 😊

**Comment by mvorisek** [comment]
I do - https://github.com/PrestaShop/PrestaShop/pulls/mvorisek - some changes there like https://github.com/PrestaShop/PrestaShop/pull/22823 is critical, many people reported it in the meantime, but no action is taken from your side. And @PierreRambaud is saying all possible things excl. testing it in action. I happily invite you too test it too.

**Comment by florine2623** [comment]
This issue is fixed wit 9.0.x :

https://github.com/user-attachments/assets/f62d0c52-795c-4426-9425-db0555bbf4c4

I will close this issue.
