### ISSUE TITLE
Module catalog "read more" popup not displayed

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#17124]
when I click on read more link on module catalog, popup is not shown.

Steps:
- git clone prestashop....
- docker-compose up
- go to module catalog
- click on read more link.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
![image](https://user-images.githubusercontent.com/194784/72219472-ceb25d00-3546-11ea-9fef-c79d89fa71e6.png)

**Additional information**
PrestaShop version: 1.7.7.0 dev
PHP version: 7.2.25

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

Thanks for your report.
I have the same issue with 1.7.7.x branch(PS1.7.7.0)
![image](https://user-images.githubusercontent.com/16067358/72426827-c3e80a00-378a-11ea-8d22-8e84ad0ae5cb.png)
It was ok with PS1.7.6.2.
![image](https://user-images.githubusercontent.com/16067358/72426865-d5c9ad00-378a-11ea-943d-5c416215f4ef.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Related to: #9722

**Comment by colinegin** [comment]
@matthieu-rolland it might be related to the module ps_mbo, wdyt ?

**Comment by colinegin** [comment]
ping @matthieu-rolland

**Comment by colinegin** [comment]
We need to test if this issue also occurs without MBO.

**Comment by khouloudbelguith** [comment]
Hi @colinegin,

In the branch 1.7.7.x
It is ok after uninstalling the ps_mbo module.
https://drive.google.com/file/d/1e8zHQGU991eu5s1EDubVXAegyI6xWKaG/view

Thanks!

**Comment by Matt75** [comment]
Fixed with ps_mbo v2.0.0

**Comment by marionf** [comment]
@PrestaShop/prestashop-qa Could you check if it's well fixed with ps_mbo v2.0.0 and close this issue if it is ?

**Comment by sarahdib** [comment]
Problem solved with ps_mbo 
<img width="1247" alt="Capture d’écran 2020-05-29 à 10 54 30" src="https://user-images.githubusercontent.com/3034677/83241538-43570280-a19b-11ea-882d-5ad5182f5a87.png">
