### ISSUE TITLE
Geolocalization archive link is broken

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#17174]
Cannot access to geolite.maxmind.com  , the link is broken or the server is down

![image](https://user-images.githubusercontent.com/52121301/72423479-a0ba5c00-3784-11ea-81d5-965373b75d05.png)
![a8a4b7c0-e314-11e6-92af-4bb66c12103c](https://user-images.githubusercontent.com/52121301/72423524-b760b300-3784-11ea-8fcd-b66223b09fec.png)

**Comment by khouloudbelguith** [comment]
Hi @ambarabaciccicocco,

Thanks for your report.
I have the same issue with PS1.7.6.2.
https://drive.google.com/file/d/1xtv5YbLz2vyToH8gXuHHsxQZOB4S5tv3/view
I’ll add this to the debug roadmap so that it’s fixed.
Thanks!

**Comment by matks** [comment]
It seems the server is not down but maxmind has changed its policy and now requires you to register an account before being able to download the data.

See https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by matks** [comment]
@LouiseBonnard We will need to update the content of this warning (see screenshot at the top).

I checked Maxmind new system. It requires you to:
1. create a user account, in the "create an account form" you must explain what you intend to use the maxmind geoip data for ; and you must agree to their terms of use which, in short, make sure you dont use maxmind geoip data to break privacy laws such as GDPR
2. you receive an email with a link, clicking on the link brings you to a page where you can create a password
3. with this password you can access your "my account" on maxmind where you have a dedicated page to download the data (so we cannot anymore provide a link for everybody: each account has a different link)

Please not this is going to impact **all PS versions which provide this text about Maxmind GeoIP database** (so maybe PS 1.5 and 1.6 too ?)

**Comment by matks** [comment]
One way to avoid this complex setup would be for prestashop to host the geoip database ourselves (so merchants would download the data from prestashop rather than from maxmind) however I'm not sure maxmind allows us to do so

If we want to do it, we need to check their terms of use and what it means for us. For example their terms of use state that if we store (and distribute) maxmind data, then
- we must ensure its safety and security
- we must make sure users comply with maxmind requirements and make users responsible for it if they break the rules

**Comment by LouiseBonnard** [comment]
Yep, the second solution is obviously better for users but it needs to be investigated because it looks quite constraining from a technical point of view. Let's change the warning notification at least for version 1.7.7 and check if this can come preconfigured in future versions!

My suggestion is to switch the current warning notification into _Since December 30, 2019, you need to register for a [1]MaxMind[/1] account to get a license key to be able to download the geolocation data. Once downloaded, extract the data using Winrar or Gzip into the /app/Resources/geoip/ directory._ ([1]MaxMind[/1] being the link this [GeoLite2 page](https://dev.maxmind.com/geoip/geoip2/geolite2) - if I'm correct) and localize it in _Admin.Notifications.Warning_, thanks!

**Comment by sam-pires** [comment]
Need to create another issue on 178 to improve the behavior

**Comment by LouiseBonnard** [comment]
> Need to create another issue on 178 to improve the behavior

@sam-pires, are you talking about this one, #17193?

**Comment by Progi1984** [comment]
Fixed in #17413 

@sam-pires Don't forget the new issue about use Maxmind API & License Key ;)

**Comment by sam-pires** [comment]
Thanks @Progi1984,

Louise already created it -> #17193 👍
