### ISSUE TITLE
Prestashop - Sale Prices not showing - Multi-Store

### ISSUE THREAD

**Issue by Terezabt** [PrestaShop/PrestaShop#17222]
Hi, 

I have a e-commerce store in prestashop 1.6.1.4 and groups for 2 clients with diferrent prices. 
The problem is that when i make a percentage sale for example to 30%  the plataform don't assume anything and nothing is showed on front page. 

Also have multi-store and in the other store everything works fine. 

Need help . 
P.s: Already change theme anda nothing appens. 
So i assume is the prestashop platform.

**Comment by khouloudbelguith** [comment]
Hi @Terezabt,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
