### ISSUE TITLE
Support link is not displayed properly in the order confirmation in Arabic

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17242]
**Describe the bug**
Support link is not displayed properly in the order confirmation in Arabic

**To Reproduce**
1. Make an order while logged in Arabic
2. On the confirmation page, check the support link, which is not displayed properly

**Screenshots**
![1763 support link broken](https://user-images.githubusercontent.com/55688534/72718927-28360f80-3b77-11ea-9f5c-811a69960940.png)

**Additional information**
PrestaShop version: 1.7.6.2 and 1.7.6.3 at least
https://drive.google.com/file/d/1vrdT1LBcbrSdnki9tbjPZ3FrVfjO1ylm/view
PHP version: N/A

**Comment by sarahdib** [comment]
related to #13358

**Comment by LouiseBonnard** [comment]
Hi there, this link is not displayed properly because the 1.7.6 Arabic translation catalog is not 100% completed. Currently, this string is translated but has not been approved yet ([here](https://crowdin.com/translate/prestashop-official/all/en-ar#q=If+you+have+questions%2C+comments+or+concerns%2C+please+contact+our+%5B1%5Dexp)). So it is perfectly normal. ;-)

One thing bothers me though, I can read this precise string in the 1.7.2, 1.7.5, and 1.7.6 catalogs but not in the 1.7.3 and 1.7.4 catalogs... if there is a bug, I think this is where we get it.

**Comment by Progi1984** [comment]
@Robin-Fischer-PS This bug is ever fixed in 1.7.7.0 with a PR from @PierreRambaud : #16586.

**Comment by Progi1984** [comment]
Fixed in #17433
