### ISSUE TITLE
in RTL Discount number in product not showing well (classic)

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17261]
in RTL Discount number in product not showing well (classic)
in v 1.7.6.2 rtl homepage product discount its in wrong place (orange color )
  
![image](https://user-images.githubusercontent.com/1392266/72757283-3d8f5600-3bd8-11ea-84a0-74dffd131459.png)
![image](https://user-images.githubusercontent.com/1392266/72757333-5992f780-3bd8-11ea-85de-72b8a92c6cda.png)

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

Thanks for your report.
I have the same issue with PS1.7.6.2 & PS1.7.6.1
![image](https://user-images.githubusercontent.com/16067358/72798787-179f9b00-3c44-11ea-890c-4fdf75e79003.png)
It is OK with 1.7.7.x branch (next version PS1.7.7.0)
![image](https://user-images.githubusercontent.com/16067358/72800117-e4aad680-3c46-11ea-9c32-aa0a99508ee2.png)
Since, it is fixed, I will close the issue.

Thanks!
