### ISSUE TITLE
Incorrect net-gross price display

### ISSUE THREAD

**Issue by mkplastimex** [PrestaShop/PrestaShop#17269]
Good morning,
I have a problem with the PRESTA 1.6 store.

Store address: www.mkplastimex.pl

After importing products into the store, the correct prices appear:

https://zapodaj.net/images/0757f5704b0f5.png

Other prices appear in the online store:

https://zapodaj.net/images/e654975f4a9d4.png

Regards

**Comment by khouloudbelguith** [comment]
Hi @mkplastimex,

It is OK with PS1.7.6.2
https://drive.google.com/file/d/1CNcaouY8cW-pnwtamjXCpZNwzLXI7c1G/view

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.
