### ISSUE TITLE
Combinations not saving sometimes in 1.6

### ISSUE THREAD

**Issue by AlexOtero32** [PrestaShop/PrestaShop#17283]
**Describe the bug**
When I am generating combinations, they create fine, but when I try to modify them to adjust the reference number and EAN13, sometimes it saves on the first try, other times it takes a few tries, other times doesn't work at all.
The error logs and debug mode don't throw any error messages.
We had an issue this week where some IDs in the database were offset (some products were trying to save with ID 70 when las ID was 81, but products with an ID higher than 70 did not appear). We solved this issue by deleting the rows of the non-existing products. Could this be related? If so, what table should I be looking for?

**Additional information**
PrestaShop version: 1.6.1.5
PHP version: 5.4

**Comment by khouloudbelguith** [comment]
Hi @AlexOtero32,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
