### ISSUE TITLE
Replace MediaServerConfiguration validateConfiguration() with native php7.3 validation

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17280]
Following this `@todo`:

```
@todo: when PHP minimum version will be 7.1, use "FILTER_VALIDATE_DOMAIN" constraint.
```

https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Media/MediaServerConfiguration.php#L90

Now is the time 😃

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by matthieu-rolland** [comment]
The current validation method has a comment stating:

> To be removed once the minimum version is PHP 7.1.

However I don't think this method should be removed, because the **FILTER_VALIDATE_DOMAIN** filter constraint alone is not sufficient, we still need the IP check that is done by the current **isValidDomain** method.

I think we should just add the **FILTER_VALIDATE_DOMAIN** constraint to the **isValidDomain** method.

**Comment by matks** [comment]
ping @PierreRambaud can we do it now ? 🤔

**Comment by PierreRambaud** [comment]
@matks Yes we can do it in right know, and should have been done in the 1.7.7.x.
Anyway, I agree with @matthieu-rolland we need both checks, FILTER_VALIDATE_DOMAIN and FILTER_VALIDATE_IP even if using an IP as media server isn't a good idea (can be for preproduction / integration environment).
