### ISSUE TITLE
Missing space between attributes in the product name string when using the dash separator

### ISSUE THREAD

**Issue by leup** [PrestaShop/PrestaShop#17309]
Hello !

A tiny bug, may be.

### Describe the bug

On the "My orders" page, we have the product name displayed with the attributes appended to it, a combination.

If you take a look at the screenshot you'll see the full name is 

**Caraco Georgia - Taille 1- Texture: Oro**

_Problem is,_ when using the dash ("-") as a separator and the combination has multiple attributes (here Size and Color) then there is a missing space before the dash.
We would like the combination label to be

**Caraco Georgia - Taille 1 - Texture: Oro**

with a space between the 1 and the dash.

I took a look at the code and it seems to be related to this:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cart.php#L1057

I am not sure at the moment if we are doing something wrong or if it is intended like this.

### To Reproduce

1. Choose the dash as the attribute separator in your shop settings
2. Order a product with a combination of at least two attributes
3. Watch product name on the order details page.

### Screenshots

![Sans titre](https://user-images.githubusercontent.com/431119/72919273-7568db80-3d47-11ea-99d1-c11fc950cca2.png)

### Additional information
PrestaShop version: 1.7.6

Thanks !

**Comment by khouloudbelguith** [comment]
Hi @leup,

I manage to reproduce the issue with PS1.7.5.2 & PS1.7.6.3 & branch 1.7.7.x.
There is no space between the 1 and the dash in:
1. the FO => order-confirmation page
![image](https://user-images.githubusercontent.com/16067358/72967800-712dd400-3dc2-11ea-9cb3-66c7b3106807.png)
2. The BO => Order details page
![image](https://user-images.githubusercontent.com/16067358/72967821-7d199600-3dc2-11ea-8084-82d5db225588.png)
3. The invoice
![image](https://user-images.githubusercontent.com/16067358/72967850-91f62980-3dc2-11ea-8d0a-5323663a21de.png)
4. the delivery
![image](https://user-images.githubusercontent.com/16067358/72967868-9ae6fb00-3dc2-11ea-84a2-d4d78d482a49.png)
5. All emails.
![image](https://user-images.githubusercontent.com/16067358/72967891-a4706300-3dc2-11ea-9a45-a052efeb8904.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by leup** [comment]
Thanks @khouloudbelguith you did a way better issue report than mine !

For the record, we have fixed the issue on our part by overriding the Cart class but by hardcoding the separator so... not a great way to do it.

I would gladly make a pull request to fix this, but I am not sure what would be the correct way to deal with this issue.

Check if the separator is a dash and add an extra space before it ? Simple and effective but may be not future-proof.
