### ISSUE TITLE
Webservice - Trying to get property of non-object - StockManager.php

### ISSUE THREAD

**Issue by F3D0RAM** [PrestaShop/PrestaShop#17335]
When I make a change in an order via webservice by means of a put request, the server offers error 500 with the following log:

[PHP Notice #8] Trying to get property of non-object (/..../classes/stock/StockManager.php, line 1107)\nPHP message: 
[PHP Notice #8] Trying to get property of non-object (/..../classes/stock/StockManager.php, line 1110)\nPHP message: 
[PHP Notice #8] Trying to get property of non-object (/..../classes/stock/StockManager.php, line 1113)\nPHP message: 
[PHP Notice #8] Trying to get property of non-object (/..../classes/stock/StockManager.php, line 1116)\nPHP message: 
[PHP Notice #8] Trying to get property of non-object (/..../classes/stock/StockManager.php, line 1119)\nPHP message: 
[PHP Notice #8] Trying to get property of non-object (/..../classes/stock/StockManager.php, line 1122)\n'

The change in the order makes a change of state and that change of state (sent or delivered) implies a movement of stock.

I think the problem is that in the put request it is not necessary to add the employee, but for the advanced stock change if necessary.

Thanks

**Additional information**
PrestaShop version: 1.6.1.24
PHP version: 5.6.40

**Comment by khouloudbelguith** [comment]
Hi @F3D0RAM,

I did not manage to reproduce the issue with PS1.7.6.3
https://drive.google.com/file/d/1e8QRA8WQoPkrDI9_KgdR0MrnrTqDaHX-/view
I used this script
```php
<html><head><title>pUT DATA</title></head><body>
<?php
/**
 * Created by PhpStorm.
 * User: khouloud.belguith
 * Date: 03/11/17
 * Time: 09:01
 */
define('DEBUG', true);
ini_set('display_errors','on');
define('PS_SHOP_PATH', 'shop.com');
define('PS_WS_AUTH_KEY', 'Key');
require_once('PSWebServiceLibrary.php');
$ws = new PrestaShopWebservice(
    'shp.com',
    'Key',
    false);
$id = 5; //ID order Here
$xml = $ws->get(array('resource' => 'orders', 'id' => $id));
echo "BEFORE\n";
echo $xml->asXML();
unset($xml->order->current_state);
$xml->order->current_state = 4;
$xml->order->shipping_number = 10;
$opt['putXml'] = $xml->asXML();
$opt['id'] = $id;
$opt['resource'] = 'orders';
$xml = $ws->edit($opt);
$xml = $ws->get(array('resource' => 'orders', 'id' => $id));
echo "AFTER\n";
echo $xml->asXML();
```

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
