### ISSUE TITLE
Upgrade should not enable disabled modules

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#17338]
1) Install Prestashop
2) Disable any FO module (ex. blockreassurance)
3) Make PS upgrade
4) Disabled module is enabled in FO...

Thanks!

**Comment by rdy4ever** [comment]
Hi @PrestaShark 
I remember I had this issue a while back, and it turned out it wasn't the upgrade itself doing this but the theme. After upgradade, the theme configuration file (theme.yml) is reapplied. If those modules are listed in `modules_to_hook` section, then they are reenabled. This is, of course, a bug - because only modules listed in `to_enable` should be enabled - but I remember I traced it to this configuration file so to fix it in my store I just removed the non needed modules from the theme's config file. Or maybe is more of an upgrade issue, because why would we reset the theme after upgrade?

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark, @rdy4ever,

I did not manage to reproduce the issue with PS1.7.6.3 after an upgrade from PS1.7.6.2 using the 1-click upgrade v4.10.1.
I attached a screen record
https://drive.google.com/file/d/1PIAV9l-FPLr3QN_kZxr5vG58J5H_IjRN/view
Thanks to check & feedback.

Related to: https://github.com/PrestaShop/PrestaShop/issues/11873

**Comment by ghost** [comment]
Close due to changed theme as @rdy4ever mention (and nee to test it one more time).
Thanks for Your time!

**Comment by khouloudbelguith** [comment]
@PrestaShark, thanks for your feedback.

Feel free to open a new one when needed.

Thanks!
