### ISSUE TITLE
birthday date to 'xx-xx-0000' erreur 500

### ISSUE THREAD

**Issue by julycmoi** [PrestaShop/PrestaShop#17341]
**Describe the bug**
if a customer create one account and change the birthday date to 'xx-xx-0000', th account is validate but when he want go to "account> informations " he have a error "500 Server Error" and he can't do an order (he can't go to url :/commande => "500 Server Error" )

if a customer change his birthday date in the account>information page with this value ('xx-xx-0000') he have the same probleme.

**Screenshots**
![Image 2](https://user-images.githubusercontent.com/18055268/73063417-043c3c00-3e9f-11ea-9486-a5bc4c9dda79.png)

**Additional information**
Version de PrestaShop : 1.7.6.3
Version de PHP : 7.2.26-1+ubuntu16.04.1+deb.sury.org+1

AND

Version de PrestaShop : 1.7.5.1
Version de PHP : 7.0.33-1~dotdeb+8.1

**Comment by khouloudbelguith** [comment]
Hi @julycmoi,
Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.5.2.
https://drive.google.com/file/d/1kdzb13_fQghM70B7C7RWG8UMZRPfrwNV/view
![image](https://user-images.githubusercontent.com/16067358/73064719-24b9c580-3ea2-11ea-8755-60dd5366a0ab.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

@01park reported also in this ticket: https://github.com/PrestaShop/PrestaShop/issues/17507, I would be nice if this was limited to the 19th century.

Thanks!
