### ISSUE TITLE
Use Guzzle 6.x for PrestaShop 1.7.7

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#17351]
Related with:
- https://github.com/PrestaShop/PrestaShop/issues/17300
- https://github.com/PrestaShop/circuit-breaker/issues/37

Very important to make PrestaShop working with modern libs like `microsoft/microsoft-graph`.

**Comment by mvorisek** [comment]
Here is an analysis of conflicting packages (packages that uses old Guzzle lib): https://github.com/mvorisek/PrestaShop/pull/1/commits/b3e6999ab6a6bbfe1fc649ddcbbd625201fe7eda

**Comment by mvorisek** [comment]
What needs to be done:
- make `prestashop/circuit-breaker` package compatible with Guzzle 6.x, i.e. revert https://github.com/PrestaShop/circuit-breaker/pull/29
- for `prestashop/circuit-breaker`, `prestashop/blockreassurance`, `prestashop/productcomments` packages and PrestaShop itself change `guzzlehttp/guzzle` dependency from `^5` to `^6.2.1` (first 6.x version without security holes as advised by Packagist)
- for `prestashop/blockreassurance`, `prestashop/productcomments` packages and PrestaShop itself replace `guzzlehttp/cache-subscriber` dependency with `kevinrob/guzzle-cache-middleware`
- in PrestaShop itself change `csa/guzzle-bundle` dependency from `1.3` to `^3.0`

This should be done at once, can this be done by someone from PrestaShop core team?

**Comment by matks** [comment]
I'm sorry this cannot be done 😢 since Guzzle 5 is shipped with PrestaShop, and there is huge BC breaks between guzzle 5 and guzzle 6 ; we have to follow SemVer here and stick with guzzle 5.

If we upgrade guzzle to version 6, we quite simply break all shops that use it in custom code and all modules that use it.

This is really sad and we even had to fork CsaGuzzleBundle to make it php7.3-compliant (see https://github.com/PrestaShop/CsaGuzzleBundle/tree/1.3), however this is how far we are willing to go to make as few as possible BC breaks for the community.

Guzzle will be one the very first dependencies we'll update when working on next major version of PS 😄because we all dream of it. But until PS 8.0.0 comes out ... we have to stick with guzzle 5, I'm sorry.

EDIT: the only situations where we would allow ourselves such as BC break would be:
- a security issue that needs guzzle update to be fixed
- PS 1.7.8 will be php7.4-compliant, and this means we'll have to update some dependencies (in order to use php7.4-compliant dependencies) ; if guzzle 5 **prevents** us from doing the update and consequently gets in the way of a php7.4-compliant version, **then** we might update guzzle (= php versions compatibility is a bigger requirement than "no BC break")

**Comment by mvorisek** [comment]
@matks I understand the reasoning, but Guzzle 5 is EOL. On one side staying with Guzzle 5 keeps full BC for existing 1.7 PS modules, but is it desired to prevent to use any modern libs that use Guzzle 6 in the next releases? Is it right to stop modern libs for about a year (until next major PS release)?

How big is the impact of both decisions? What is the real issue when:
- all PrestaShop managed modules will be modified to use the latest libs and properly tagged with incremented minor or major version
- PrestaShop 1.7.7 will require these modules and upgrade to 1.7.7 will be allowed only if all active modules are compatible or has compatible upgrade available
- there is already BC break in 1.7.7 as this version requires PHP 7.1 instead of PHP 5.6

This solution does not follow SemVer, but is it really worse than:
- keeping developers's hands tied as well as the PrestaShop development itself
- requiring EOL and not tested libs for targetted PHP version

Is the SemVer the real only issue? If so, is it really worth it to follow it?

The same for Symfony and Twig.

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
ping @eternoendless

**Comment by PierreRambaud** [comment]
@matks IMHO, since the Guzzle 5 is EOL, it should be updated because of security reason, otherwise if a new issue appeared, we shouldn't be able to properly update Guzzle quickly.

**Comment by matks** [comment]
Indeed Guzzle 5 being EOL is a strong incentive to update it. But
- we need @eternoendless opinion
- if we do it, we must warn prestashop developers now, and prepare the change for 1.7.8
- we must provide explanations for people about what this change means and how to update their code (maybe we could provide some adapters that have the same signatures that Guzzle5 methods but actually use Guzzle6, so people only need to change class names ?)

**Comment by mvorisek** [comment]
@eternoendless Can you please give the green light to deprecate the Guzzle 5 being EOL dependency in advance of the newer Guzzle 6 in 1.7.7?

**Comment by eternoendless** [comment]
Unfortunately I cannot accept updating Guzzle to v6, because it's a huge breaking change. If we update it, then module developers who use it will have to build and maintain different versions of their modules to support both newer and previous PS versions. This makes module development more expensive, which is bad for platform adoption. Upgrading shops may become harder as well.

Right now we're only "allowing" BC's for the following reasons:

- Symfony migration
- PHP compatibility (as explained in [this article](https://build.prestashop.com/news/announcing-end-of-support-for-obsolete-php-versions/))
- In rare cases, bug fixes (core) or security fixes in upstream libraries

So I'm against doing this unless there's a valid reason forcing us to do it, like a CVE.

Yes, I know developers' life will be less cool for a while. But that's the price we are forced to pay until the migration has been finished and we can go back to a shorter major release cycle.

**Comment by mvorisek** [comment]
@eternoendless I understand, thank you, but can you advise when will be the right point to upgrade the Guzzle library? The latest rel. was in 2008 and as @PierreRambaud mentioned, the Guzzle v5 is EOL, i.e. not even security fixes are released - see https://github.com/guzzle/guzzle#version-guidance

This library is used a lot in APIs libs, for example in `microsoft/microsoft-graph`, so the importance is very high, as not updating to Guzzle v6 can save a few developers from having to possibly update their modules, but prevent more and more developers to use Prestashop at all.

**Comment by PierreRambaud** [comment]
@mvorisek I'm agree with both of you. 
As @eternoendless said, it's a huge BC and it can break many modules but the Guzzlv5 is EOL and using the latest version (or a least a recent one) will allow developers to use library like `microsoft/microsoft-graph`

**Comment by eternoendless** [comment]
> can you advise when will be the right point to upgrade the Guzzle library?

Unless something happens that forces us to upgrade it, then that would be in the next major version. Probably about 1,5 years away at least :\

**Comment by PierreRambaud** [comment]
I'm closing this because we will not update this dependency.
Kind regards
