### ISSUE TITLE
[BO] Can't explore a category when all subcats are disabled

### ISSUE THREAD

**Issue by nozionbecome** [PrestaShop/PrestaShop#17379]
**Describe the bug**
When all subcategories from a parent are disabled then it's imposible to explore the parent again

**To Reproduce**
1. Go to Catalog / Categories
2. Create new category
3. Create a new subcategory with parent category equals the previous created category.
4. Edit the last new category and set it to disabled.
4. Go to main list, then it's imposible to enter the in the "view" of the parent category, list only allows to edit it but it is not possible to explore the disabled subcategory.

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @nozionbecome,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 & PS1.7.6.2 & PS1.7.6.1 & PS1.7.6.0.
https://drive.google.com/file/d/1GEX1rM0qciI_F19NUu1MgcjgEAm3wtGG/view
It was ok with PS1.7.5.2.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Progi1984** [comment]
Fixed in #17395
