### ISSUE TITLE
Use different strings for "New" translation

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#17455]
Is it possible to use different strings for _New_ translation?
This wording is used in 2 different cases:

- on new products (means _Nouveauté_ in french)
- on product condition (means _Neuf_ in french)

Currently, there is only one string and if I want to change translation for new products, it also changes wording for product condition (FO and BO).

In my opinion, we need to use two strings:

- `{l s='New product' d='Shop.Theme.Catalog'}` = _New_ in english = _Nouveauté_ in french
- `{l s='New' d='Shop.Theme.Catalog'}` = _New_ in english = _Neuf_ in french

@LouiseBonnard what do you think?

**Comment by LouiseBonnard** [comment]
It makes sense, and those two different strings already exist so it might be easy to switch. We just need to list all the files this change impacts. :-)

**Comment by micka-fdz** [comment]
Thx @LouiseBonnard, I'll make a PR.

**Comment by LouiseBonnard** [comment]
@micka-fdz, can you confirm you want to switch the two strings framed in the following image?

![Capture d’écran 2020-01-31 à 17 05 18](https://user-images.githubusercontent.com/32565890/73554816-b9956380-444c-11ea-98b6-5e537a1bd007.jpg)

It looks logical on a wording point of view (even more in French, I admit it) but if you look at the interface, I don't think we should have such a long wording in the flag that points out the new products. Especially with languages that contain long words such as German and Polish.

<img width="1087" alt="Capture d’écran 2020-01-31 à 17 18 58" src="https://user-images.githubusercontent.com/32565890/73555662-54427200-444e-11ea-8dc7-2fdbccd87fb9.png">

One thing we need to make sure though is not to confuse the two uses: 

- _new_ meaning _in perfect condition_
- _new_ meaning _most recent item_

And for that, one solution might be to use two different strings. I suggest keeping _New_ to designate recent items since it is largely used and create another string to designate the condition with _New condition_ (on both back and front offices). It is not ideal but there are not a lot of ways to differentiate the two... unless we keep the same wording _New_ but use a different domain to dissociate the two meanings and translate it right, what do you recommend @PrestaShop/prestashop-core-developers?

**Comment by micka-fdz** [comment]
In my opinion, we need to keep _New product_ for recent products.
On `ps_newproducts` module, section title is _New products_ so it makes sense.

As I said before, maybe we can just play with translations on `Shop.Theme.Catalog` (for product flags).

> {l s='New product' d='Shop.Theme.Catalog'} = _New_ in english = _Nouveauté_ in french

**Comment by Progi1984** [comment]
Fixed by #17461

**Comment by ttoine** [comment]
On a shop in 1.7.6.4, in French, it was translated as "Nouveau". And now it is translated as "Neuf" in 1.7.6.5. So there might be a need to fix that also in versions before 1.7.8, at least in 1.7.7 it would be great.

**Comment by Progi1984** [comment]
@ttoine Please open a new issue

**Comment by ttoine** [comment]
@Progi1984 I did already, and it's mentioned in this discussion just below your comment.
https://github.com/PrestaShop/PrestaShop/issues/19603
It has been closed already.

**Comment by btronquo** [comment]
any news?

**Comment by matks** [comment]
@btronquo this bug is fixed in next PS minor version 1.7.8.0

**Comment by btronquo** [comment]
> @btronquo this bug is fixed in next PS minor version 1.7.8.0

thanks
Do we have an ETA to the release of 1.7.8.0 ?

**Comment by matks** [comment]
> > @btronquo this bug is fixed in next PS minor version 1.7.8.0
> 
> thanks
> Do we have an ETA to the release of 1.7.8.0 ?

It's expected to be delivered in 1st half of 2021, like May/June. But as this date is far ahead, it can change.

**Comment by henri9813** [comment]
Hello :-)

When will this be released ?

**Comment by matks** [comment]
Hi

> It's expected to be delivered in 1st half of 2021, like May/June. But as this date is far ahead, it can change.

As expected, dates changed 😄  we had unexpected issues. 1.7.8.0 should be released in July or at the latest August. You can follow its progress on https://github.com/PrestaShop/PrestaShop/issues/23010
