### ISSUE TITLE
Combinations'  BO import not working - Impact on price not being saved  

### ISSUE THREAD

**Issue by diejorm** [PrestaShop/PrestaShop#17470]
We have been stuck with this for some weeks already and could not find any solution.

**The bug**
We are trying to update the Impact on Price (VAT Included) for each combination's variant via CSV/XCEL (about 800 rows), but after the process is finished without any apparent error, we check and no impact on price has been actually modified. Everything is still the same as it was before the import.  

**To Reproduce**
1. Go to 'Products' -> 'Import' -> 'Import'
2. Select 'combinations' & 'Use product reference as key'
3. Select the right fields 'ID', 'Reference', 'Impact on Price' & the two variables which are mandatory but are actually empty in our CSV
4. Then click Import
5. Everything seems to be fine but no changed has actually be arranged 

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.2.21

We appreciate your help guys!

**Comment by khouloudbelguith** [comment]
Hi @diejorm,

>which are mandatory but are actually empty in our CSV

They are empty, it shouldn't be empty.
If you ignore those columns, you should have those warnings.
![image](https://user-images.githubusercontent.com/16067358/73649232-a3231e00-467f-11ea-8904-1b27d47b601c.png)
![image](https://user-images.githubusercontent.com/16067358/73649284-be8e2900-467f-11ea-8b8c-9fd2924e90c8.png)
So, you can't import the file.
I tried with PS1.7.6.3
First, I imported this file
[first_combination.csv.txt](https://github.com/PrestaShop/PrestaShop/files/4147589/first_combination.csv.txt)
Second, I tried to update those combinations with this file
[second_comb.csv.txt](https://github.com/PrestaShop/PrestaShop/files/4147592/second_comb.csv.txt)
=> prices are well updated
Third, I updated using this file
[third_comb.csv.txt](https://github.com/PrestaShop/PrestaShop/files/4147595/third_comb.csv.txt)
=> prices are not updated because` Attribute (Name:Type:Position)*` & `Value (Value:Position)*` are empty.

Thanks to check & feedback!

**Comment by diejorm** [comment]
Hi @khouloudbelguith,

Thank you so much for your help! 
It worked like a charm 

It was driving us crazy for a few weeks and we could not find any related info.

Again, thank you so much for helping out  :)

**Comment by khouloudbelguith** [comment]
@diejorm, thanks for your feedback.

Thanks!
