### ISSUE TITLE
demo.prestashop.com is on 1.7.6.2, not 1.7.6.3

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17485]

**Comment by Quetzacoalt91** [comment]
This is caused by the Installer, which is unable to end successfully when installing all the languages when the Docker image `docker-internal-images` is built.

You may reproduce locally with https://github.com/PrestaShop/docker/blob/afd56be8c2668b532ffb297a50cab65344e32078/base/config_files/docker_run.sh#L94

Error log:
```
* Launching the installer script...
[91mPHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 106496 bytes) in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/XliffFileLoader.php on line 250
[0m
[91mPHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 69632 bytes) in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 165
[0m
Removing intermediate container fa7b8228d8c4
```

**Comment by Quetzacoalt91** [comment]
This will be fixed with https://github.com/PrestaShop/PrestaShop/pull/17307 on 1.7.7.0 & https://github.com/PrestaShop/PrestaShop/pull/17306 on 1.7.6.4

**Comment by khouloudbelguith** [comment]
Hi @matks,

Can we close this issue as it is not related to the PrestaShop core?

Thanks!

**Comment by matks** [comment]
> Hi @matks,
> 
> Can we close this issue as it is not related to the PrestaShop core?
> 
> Thanks!

Yes 😊
