### ISSUE TITLE
Disable cache, CPU 100%

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#17523]
Prestashop 1.7.6.3 on 10.1.43-MariaDB-0ubuntu0.18.04.1 - Apache
If I disable cache, my cpu goes at 100% and site crash. Error log is empty.
![2020-02-06 (2)](https://user-images.githubusercontent.com/5500935/73916151-2aa9a080-48bd-11ea-983d-2135db784ba8.png)

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

You can follow these steps:

- `Never recompile template files`: this option is to be chosen for maximum performance.
- `Cache enabled (YES)`: makes pages fastest. 
- `Smart cache for CSS (YES)`: brings together in a single file, compresses and caches CSS files.
- `Smart cache for Javascript (YES)`: brings together in a single file, compresses and caches JS files.
- `Apache Optimization (YES)`: allows to further increase site performance.

In your BO => Modules Manager page => configure the `statsdata` module & check if `Save page views for each customer` is enabled, try to disable it because it uses a lot of CPU resources and database space.

You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
In fact, it takes a very huge space in the database because it collects statistics from connections.
you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.


Thanks to check & feedback.

**Comment by centoasa** [comment]
Thanks @khouloudbelguith all done!
but if I disable only the cache, cpu goes at 100% and afterabout 1 min site goes down.

**Comment by khouloudbelguith** [comment]
@centoasa,

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @centoasa,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
