### ISSUE TITLE
On virtual product, the delivery time shouldn't display.

### ISSUE THREAD

**Issue by PeeyushAgrawal** [PrestaShop/PrestaShop#17542]
**Describe the bug**
When we set the "Delivery time of in-stock products", the delivery time get also display on the virtual product page. As we know that virtual product can't ship, so the delivery time shouldn't display on the virtual product page.

**To Reproduce**
1. Go to 'Products setting' in shop parameters tab on the BO and set "Delivery time of in-stock products".
2. Now go to the catalog page and create a new virtual product. 
3. Click on preview - here you will find that the delivery time is getting display. 

**Screenshots**
Virtual product page FO -
![virtual_product](https://user-images.githubusercontent.com/39614089/74014724-44c6aa00-49b5-11ea-8f69-f868419d881e.png)
 
Delivery time configuration - BO - 
![delivery_time_slot_config](https://user-images.githubusercontent.com/39614089/74014772-5dcf5b00-49b5-11ea-8464-315e5cf0b7b0.png)
 
**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @PeeyushAgrawalWebkul,

Thanks for your report.
I manage to reproduce the with PS1.7.5.2 & PS1.7.6.3 & the branch 1.7.7.x.
![image](https://user-images.githubusercontent.com/16067358/74018135-a4ad5880-4995-11ea-89d9-13e49ae37a49.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by PeeyushAgrawal** [comment]
@khouloudbelguith I have a solution for this and will create the PR soon.

**Comment by colinegin** [comment]
Thanks @PeeyushAgrawalWebkul ! I close this issue, now that you fixed it :)
