### ISSUE TITLE
Errors to upgrade from 1.7.6.2 to 1.7.6.3

### ISSUE THREAD

**Issue by ITProfeska** [PrestaShop/PrestaShop#17593]
Hi

today I've tried to upgrade from 1.7.6.2 to 1.7.6.3

using the 1-click upgrade module the updating is stopped when it tries to upgrade the database

"Error during database upgrade. You may need to restore your database.
Error updating translations"

site are multi-languages

**Comment by khouloudbelguith** [comment]
Hi @ITProfeska,

What is the exact version of the 1-click upgrade did you use?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

Thanks!

**Comment by ITProfeska** [comment]
[log.txt.zip](https://github.com/PrestaShop/PrestaShop/files/4188647/log.txt.zip)

**Comment by ITProfeska** [comment]
hi, 

I guess Ive got the latest version of the 1-click upgrade, how can I check is ?

Regards

**Comment by khouloudbelguith** [comment]
@ITProfeska,

>I guess Ive got the latest version of the 1-click upgrade, how can I check is

You can check the version in the [`Project_Folder/modules/autoupgrade/config.xml`](https://github.com/PrestaShop/autoupgrade/blob/master/config.xml#L5)

The upgrade of your Database is not done.

This is could be a permissions issue, related to some Apache rules or a size problem when moving old databases.
You must be careful with some options in the `statsdata` module because storing page views uses a lot of resources and database space. We advise you to enable page views only if your server can handle it.
In fact, it takes a very huge space in the database because it collects statistics from connections.
you can delete data from `ps_connections`, `ps_connections_page` & `ps_connections_source`.

Also, you can check the `ps_quest` table if it has a lot of data.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ITProfeska,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
