### ISSUE TITLE
1.7.6.3 admin dropdowns not working (clean install)

### ISSUE THREAD

**Issue by AxisNL** [PrestaShop/PrestaShop#17594]
I just installed prestashop for the first time, and I must say I am impressed! However, in the admin section, all dropdowns are broken. Everywhere I look (for example shop parameters > general, the dropdown lists for 'round mode' for example, does not allow me to select anything.

I've tried chrome/firefox/safari on mac, and chrome on windows, same behaviour everywhere. This kind of makes the control panel unusable.

Am I overlooking something simple here?

```
Server informationLinux #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64
Server software version:Apache/2
PHP version:7.4.2
Memory limit:128M
Max execution time:30
Upload Max File size:64M
```

**Comment by AxisNL** [comment]
Hmm.. I downgraded to php 7.2.27, and now everything seems to work find.

**Comment by khouloudbelguith** [comment]
Hi @AxisNL,

PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
That's why you need to downgrade your PHP version.

Thanks!

**Comment by AxisNL** [comment]
Thank you! The strange thing is that all check pages are green, and everything looks fine. I would expect the admin page to at least warn me somehow that I am running on an unsupported PHP version ;)

**Comment by consule** [comment]
> Hi @AxisNL,
> 
> PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
> For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
> Next Major release PS1.7.7 will be compatible with PHP7.3.
> That's why you need to downgrade your PHP version.
> 
> Thanks!

Works Fine!!!!
