### ISSUE TITLE
Issue after upgrading from 1.6.1.24 to 1.7.6.3

### ISSUE THREAD

**Issue by Precisionlasers** [PrestaShop/PrestaShop#17637]
We upgraded from 1.6.1.24 to 1.7.6.3. Once the upgrade was finished this message came up:
![image](https://user-images.githubusercontent.com/60999413/74404641-1427ba00-4e66-11ea-8ecd-72ce8ee847d0.png)

With a note that it was switching to the default theme. Aside from this everything was working fine. I loaded a new theme in around 20 minutes after the upgrade had finished. From there the dashboard started having problems, namely links not working (I cannot delete the theme I uploaded for example, and the module catalogue won't load), and text and links from our website itself is appearing in the background, I have to scroll down the page to access the actual dashboard pages.

I've cleared the cache, and found a list of missing files (through advanced parameters / information), which I copied back into the directory from the downloaded upgrade files, which cleared the list, however I am still having the same issues.

It says the following files have been updated, however from what I understand this wouldn't be an issue?

Backoffice/autoupgrade/index.php
Backoffice/autoupgrade/backup/index.php

I tried to rollback to the previous version through the 1-click module page, however the button doesn't load.

Our web guy has basically ghosted us so we are trying to work this out on our own so any help would be appreciated, thank you!

**Additional information**
PrestaShop version: 1.7.6.3
PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Precisionlasers,

What is the exact version of the 1-click upgrade did you use?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Precisionlasers,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
