### ISSUE TITLE
Indian numbers mixed with Arabic numbers in back office

### ISSUE THREAD

**Issue by khalidzuhd** [PrestaShop/PrestaShop#17684]
hello to you all 
 i use presa 1.7.6.3
i have trebles  with prestahop  i changed my default backoffice language to arabic 
i have many problems with numbers   changed   to indian number in many numbers feald 
![image](https://user-images.githubusercontent.com/1392266/74595624-9376e280-504c-11ea-8e09-3ae103a34afd.png)

![image](https://user-images.githubusercontent.com/1392266/74595634-a8ec0c80-504c-11ea-90d7-654bae03fe1b.png)

![image](https://user-images.githubusercontent.com/1392266/74595640-c1f4bd80-504c-11ea-864b-0409aeca5dea.png)

and in the date huge problem
![image](https://user-images.githubusercontent.com/1392266/74595655-f0729880-504c-11ea-8bda-99f34b569175.png)

**Comment by khouloudbelguith** [comment]
Hi @khalidzuhd,

About the Calendar
Please follow this ticket: https://github.com/PrestaShop/PrestaShop/issues/11571.

About the mix of Arabic number and non-Arabic number, I have the same behavior with PS1.7.5.2, PS1.7.6.3 & the 1.7.7.x branch
![image](https://user-images.githubusercontent.com/16067358/74640508-f3b27500-516f-11ea-89b2-2e8a59c89657.png)

Ping @LouiseBonnard what do you think?
We need to specify the exact format used? is it?

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @khalidzuhd, @khouloudbelguith, are there Indian numbers here? Anyway, Arabic and non-Arabic numbers should definitely not mix. @PrestaShop/prestashop-core-developers, how can we handle this issue? @MatShir, do you think it can be related to (and thus fixed by) the CLDR?

**Comment by khalidzuhd** [comment]
You must make options  what kind of number do indian or arabic.... 
And applay to all the site

**Comment by khalidzuhd** [comment]
In date problem ... Indian number not allowed ...
I wont it arabic number for all the site

**Comment by khalidzuhd** [comment]
What pm mean?

**Comment by LouiseBonnard** [comment]
@khalidzuhd, it stands for Product Manager. In other words, when your issue is labeled 'PM approved', it means that the Product team has approved it. :-)

**Comment by khalidzuhd** [comment]
Great... I have alot of things that i sow it should reported but my English is weak do you have any one speaks arabic ?

**Comment by matks** [comment]
> do you have any one speaks arabic ?

No, we dont have someone who speaks arabic unfortunately 😭 

>  @PrestaShop/prestashop-core-developers how can we handle this issue

As far as I know, CLDR will not solve this issue.

I think that currently _PrestaShop does not support non-arabic numbers_. It's a limitation of the current software. We can start a project to allow the use of non-arabic numbers in the software but _that would be a gigantic project_ because we need to modify
- every input where you can submit numbers
- verify every location in the software where we display these numbers (to validate they display correctly)
- verify every location in the software where we use these numbers, for example computing prices (additions, multiplications, applying tax rates...) to validate they are correct

I'm afraid such a gigantic project, very expensive, is not likely to happen soon :(

I put back `Waiting for PM` to validate but I would unfortunately think we will close this issue. This does not mean we dont care or we dont think this is interesting, it's rather that we have so much topics to handle, this one cannot reach the top of our pile of things to do _today_.

**Comment by MatShir** [comment]
As @matks said, unless we get big contributions from an Indian or Arab contributor, we won't be able to solve this problem any time soon.

**Comment by hibatallahAouadni** [comment]
Closing the issue because there has been no reaction for two years
