### ISSUE TITLE
Exception in the FO after a new install

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#17725]
**Describe the bug**
After a new install of the branch develop, we have a new exception in the FO, this exception is displayed only when debug mode is enabled.

**To Reproduce**
1. `git clone https://github.com/PrestaShop/PrestaShop.git`
2. `Composer install`
3. `make install`
4. Install the develop branch (debug mode is enabled)
5. Go to the FO => an exception is displayed in the FO
![image](https://user-images.githubusercontent.com/16067358/74815901-60597b00-52fa-11ea-8fac-23cecaccbadf.png)

If you disable the debug mode => FO is well working!

**Additional information**
PrestaShop version: develop
PHP version: 7.2.22

**Comment by itsvahid** [comment]
I had the same issue. looks like there are no data in ps_image_type after fresh installation and in ImageRetriever.php file line 271 it tries to access $urls[$keys[0]]. but $keys is empty because there are no image types in ps_image_type table.
I solved this by adding a row in the table manually then error was solved.

**Comment by matks** [comment]
> I had the same issue. looks like there are no data in ps_image_type after fresh installation and in ImageRetriever.php file line 271 it tries to access $urls[$keys[0]]. but $keys is empty because there are no image types in ps_image_type table.
> I solved this by adding a row in the table manually then error was solved.

Thanks for the tip

**Comment by alexmixaylov** [comment]
I have same error after instalation. No any types in ps_image_type.

**Comment by khalidumarr** [comment]
running below sql fixed the issue for me:

```
INSERT INTO `{PREFIX}_image_type` (`id_image_type`, `name`, `width`, `height`, `products`, `categories`, `manufacturers`, `suppliers`, `stores`)
VALUES
	(10, 'large_banner', 960, 400, 0, 1, 0, 0, 0),
	(9, 'product_listing', 220, 220, 1, 1, 1, 1, 0),
	(8, 'category_default', 960, 350, 0, 1, 0, 0, 0),
	(7, 'home_default', 250, 250, 1, 0, 0, 0, 0),
	(6, 'large_default', 500, 500, 1, 0, 0, 0, 0),
	(5, 'medium_default', 300, 300, 1, 1, 1, 1, 0),
	(4, 'small_default', 125, 125, 1, 1, 1, 1, 0),
	(3, 'cart_default', 80, 80, 1, 0, 0, 0, 0);
```

**Comment by matks** [comment]
Reproduced today by @zuk3975 (still struggling with it)
I tried too. 1st install I so the bug (both empty SQL table and broken FO). Then did a reinstall and it worked (so 2nd attempt => OK).

Strange 🤔

**Comment by gadnis** [comment]
I get the same error too.. 
I use steps described in devdocs: "How to become a Core Contributor using Docker". 

Everytime:
- I clean the docker 
`docker-compose down -v` 
`docker system prune -a`

- reseting my fork to the latest upstream from Prestashop/Prestashop 
`git fetch ps`
`git reset --hard ps/develop`
`git push origin develop`

- I remove PrestaShop directory from Mac OS 10.12 system (node version: v11.14.0)
- I download my fork
`git clone https://github.com/preston/PrestaShop.git`
- and run using docker
`cd PrestaShop`
`docker-compose up`

P.S. Also everytime I have to use `make assets` cause there is no styling, is this like it should be?

**Comment by dali-rajab** [comment]
May be we should add another script to https://github.com/PrestaShop/PrestaShop/blob/develop/Makefile in order to add this missing `{PREFIX}_image_type` entries.

**Comment by matks** [comment]
> https://github.com/PrestaShop/PrestaShop/blob/develop/Makefile

Maybe a good idea, wdyt @PierreRambaud ?

**Comment by matks** [comment]
> P.S. Also everytime I have to use `make assets` cause there is no styling, is this like it should be?

Yes we think it's better not to commit assets, see https://build.prestashop.com/news/open-question-not-commiting-assets-anymore/

**Comment by matks** [comment]
New occurence of the bug, I reinstall, bug is gone. Like it has been said before, my SQL table `ps_image_type` was empty

**Comment by matks** [comment]
Would it be worth it to at least provide a well-described error for developer ?
```
public function getNoPictureImage(Language $language)
    {
        $urls = [];
        $type = 'products';
        $image_types = ImageType::getImagesTypes($type, true);

        if (empty($image_types)) {
            throw new SomeLoveException('Hey there my friend ! It seems there is no image_type available for products and that looks like bug https://github.com/PrestaShop/PrestaShop/issues/17725, so maybe you want to reinstall your shop or manually fill the ps_image_type SQL table ?';
        }
```

wdyt @PrestaShop/prestashop-core-developers

**Comment by milapparikh** [comment]
After execute query of, this link solution working fine for me.
https://github.com/PrestaShop/PrestaShop/issues/17725#issuecomment-616215788

**Comment by PierreRambaud** [comment]
It's maybe due to a wrong dependency in the XML files during the installation?

**Comment by atomiix** [comment]
Hi! I've been able to reproduce this error and it looks like it happens when you run the installer before (or while) building the assets (with `make assets`). The reason is that if the assets of the FO theme are not built, [2 required files](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Addon/Theme/ThemeValidator.php#L130-L131) are missing and the theme is considered invalid. As the table `image_type` is filled from [the theme configuration file](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/config/theme.yml#L101), the table cannot be populated.

@gadnis I think your docker is using some cache from the previous script [`docker_run_git.sh`](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/.docker/docker_run_git.sh) because the version in the `develop` branch [compile the assets automatically](https://github.com/PrestaShop/PrestaShop/blob/develop/.docker/docker_run_git.sh#L7) **before** running the installer.

**Comment by SharakPL** [comment]
> 
> 
> Hi! I've been able to reproduce this error and it looks like it happens when you run the installer before (or while) building the assets (with `make assets`). The reason is that if the assets of the FO theme are not built, [2 required files](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Addon/Theme/ThemeValidator.php#L130-L131) are missing and the theme is considered invalid. As the table `image_type` is filled from [the theme configuration file](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/config/theme.yml#L101), the table cannot be populated.
> 
> @gadnis I think your docker is using some cache from the previous script [`docker_run_git.sh`](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/.docker/docker_run_git.sh) because the version in the `develop` branch [compile the assets automatically](https://github.com/PrestaShop/PrestaShop/blob/develop/.docker/docker_run_git.sh#L7) **before** running the installer.

Then I guess docker setup needs fixing because this bug is still there. I have fresh fork of develop branch on Ubuntu (WSL 2) and every time I do `docker-compose up` it throws the same error. Clearly theme installation doesn't work as intended. Admin panel is accessible (with couple notices right after login). Looks like default theme is set:

![obraz](https://user-images.githubusercontent.com/5007456/113181022-a39e5100-9251-11eb-9db9-b867f45db3d7.png)

but there's none of required image types:

![obraz](https://user-images.githubusercontent.com/5007456/113181201-cd577800-9251-11eb-8de3-0056ecb3d9b2.png)

**Comment by topfuel75** [comment]
If you for some reason missing the file 'fileType' in the product image folder (ie: img/p/1/2/3/4/5), then you will receive this error message.

The content in 'fileType' is the extension of your product image. Usually it only contain 'jpg'.

I'm not sure why I had a lot of folders missing the file 'fileType', I cant recall that I have deleted them. It might be due to some product import module or some kind of secure module.

There should really be a fallback for this in PS. 
After a quick look in the code there seems to be some kind of fall back. If the file 'fileType' is empty there is a fallback.
But if the file 'fileType' is missing there is no fallback, and you will receive heaps of error messages.

**Comment by SharakPL** [comment]
@topfuel75 does it still happen to you? I haven't had this issue since my previous comment here so ~2 years.

**Comment by topfuel75** [comment]
> @topfuel75 does it still happen to you? I haven't had this issue since my previous comment here so ~2 years.

I noticed these errors a week ago. I'm pretty sure it was due to some security scanning script that deleted the file  'fileType'. Some img/p folders had the file 'fileType', but in most of the folders it was missing.
I made a small script that created the file 'fileType' in the folders were it was missing. And then these error messages disappeared.
