### ISSUE TITLE
Mail with prices with taxes/no taxes mixed

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#17764]
**Describe the bug**
'order_conf' mail template displays the order summary, and prices tax are mixed.

**To Reproduce**
1. Configure a customer group with "No taxes"
![image](https://user-images.githubusercontent.com/15104724/74950548-92083a00-53ff-11ea-81d2-0903c12ae058.png)

2. Create a coupon code with 1€ "No taxes"
![image](https://user-images.githubusercontent.com/15104724/74950564-9896b180-53ff-11ea-9622-3e96688662e9.png)

3. All prices in checkout are displayed with "No taxes"
![image](https://user-images.githubusercontent.com/15104724/74950759-e27f9780-53ff-11ea-8684-70c228212e7d.png)
![image](https://user-images.githubusercontent.com/15104724/74952108-646fc080-5400-11ea-85d7-eb756843ba06.png)

4. Finish order and check email. There are prices with "No taxes" and prices "With taxes".
![image](https://user-images.githubusercontent.com/15104724/74952393-78b3bd80-5400-11ea-8b21-598036eb5d61.png)

**Additional information**
PrestaShop version: 1.7.6.3

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.3 and PS1.7.5.2 and 1.7.7.x branch.
![image](https://user-images.githubusercontent.com/16067358/75027780-6d639f00-549f-11ea-9ed5-1195f402145d.png)
In the BO => Orders details page and in the FO => OK
BO: ![image](https://user-images.githubusercontent.com/16067358/75028008-c6cbce00-549f-11ea-9e9f-f3214b5a56bb.png)

FO: ![image](https://user-images.githubusercontent.com/16067358/75028038-d8ad7100-549f-11ea-8ffb-148f6ed3dbfe.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Seb33300** [comment]
PR to fix this issue: https://github.com/PrestaShop/PrestaShop/pull/28231

**Comment by hibatallahAouadni** [comment]
@Seb33300 thanks for your PR :rocket:
