### ISSUE TITLE
Problems changing the store name (my Shop) prestashop 1.7.6 [Not Solved]

### ISSUE THREAD

**Issue by FaustoBoscaro** [PrestaShop/PrestaShop#17783]
Hello, after updating prestashop 1.7.5 to 1.7.6, the name of the store was changed to "My Shop"
I tried to change the name in the back office and it didn't change, I went to the database (pr_configuration - PS_SHOP_NAME) to change it from there and it didn't work. I have prestashop 1.7.6 (before with 1.7.5 and if it worked) The name "My Shop" is in the mail and in other sections.
I use the warehouse template

Additional Information
PrestaShop version: 1.7.6
PHP Version: 7.3
MariaDB 10.1

The solution with Multistore is dangerous and can cause the virtual deletion of subcategories!

**Comment by khouloudbelguith** [comment]
Hi @FaustoBoscaro,

First, PrestaShop is not compatible with PHP 7.3, in fact, PrestaShop 1.7.0 to 1.7.3 is compatible with PHP 7.1 and PrestaShop 1.7.4 & 1.7.5 & PS1.7.6 are compatible with PHP 7.2.
For more details, you can follow this link: http://build.prestashop.com/news/prestashop-1-7-is-moving-to-symfony-3-4-and-php-5-6/
Next Major release PS1.7.7 will be compatible with PHP7.3.
You need to downgrade your PHP version.

Second, the incorrect email subject and template variable `{shop_name}` was fixed in the PS1.7.6.2 with this PR: https://github.com/PrestaShop/PrestaShop/pull/16500
And If the shop name contains special chars => the email subject will be incorrect. => this issue is fixed in the next patch 1.7.6.4 with this PR: https://github.com/PrestaShop/PrestaShop/pull/17608

Thanks to check & feedback.

**Comment by khouloudbelguith** [comment]
Hi @FaustoBoscaro,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
