### ISSUE TITLE
Checkout: Payment Step: Missing error message when terms not accepted

### ISSUE THREAD

**Issue by patrickmyh** [PrestaShop/PrestaShop#17812]
Using a sligtly modified classic theme. 

**To Reproduce**
Put some article in the cart.
Proceed to checkout, finish all steps (persoanl info, adress, shipping) however you want.
Choose a payment method.
Click "Order" Button which is disabled since the "I agree to the terms..:" Checkbox wasn't clicked.

-> There should be a tooltip / error message, informing that the "terms and services" checkbox should be ticked in order to proceed.

**Screenshots**
![image](https://user-images.githubusercontent.com/8437284/75188440-6d3bfb80-574c-11ea-83c4-c9d2d34fa918.png)

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2

**Comment by arouiadib** [comment]
This is a good idea and will offer a better user experience, especially for customers who are new to internet shopping. But IMHO, for Prestashop team, it is a feature creep. Such features are better kept for merchants/theme developers to make their themes perfect as they like.

Let's say Prestashop adds this feature to classic theme, and you are using a slightly modified version of classic theme, what ensures that the lines added by Prestashop co-exist well with your theme?

**Comment by micka-fdz** [comment]
I think it's a good idea too. This UX improvement can help to increase the transformation rate of order page, which is essential for merchants.

**Comment by jf-viguier** [comment]
Good idea @patrickmyh have you planned to make a pull request ?

**Comment by khouloudbelguith** [comment]
Hi @patrickmyh,

Thanks for your report.
I think it will be a good improvement.
In fact, we have two cases:
1. Payment method is selected but the the "I agree to the terms..:" Checkbox wasn't clicked
![image](https://user-images.githubusercontent.com/16067358/75229920-29301180-57b3-11ea-91c9-67a3a45fe75d.png)
2. The "I agree to the terms..:" Checkbox is clicked but the payment method is not selected
![image](https://user-images.githubusercontent.com/16067358/75229981-49f86700-57b3-11ea-9299-9f5600159ffe.png)
=> this case could fixed by this ticket: https://github.com/PrestaShop/PrestaShop/issues/11435

Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by LouiseBonnard** [comment]
@prestascott, @TristanLDD, do you think it is relevant to add the same notification as in the 'Personal Information' step when the 'I agree to the terms and conditions and the privacy policy' checkbox is not ticked?

<img width="713" alt="Capture d’écran 2020-02-25 à 13 01 56" src="https://user-images.githubusercontent.com/32565890/75245915-06135b00-57cf-11ea-994c-3f4940570171.png">

**Comment by patrickmyh** [comment]
I might work on a pr if wished. Guess this killed one and another conversion.

**Comment by LouiseBonnard** [comment]
But what do you think about this idea, @patrickmyh? At least it will harmonize all steps of the checkout while showing precisely the missing element to complete the purchase.

**Comment by micka-fdz** [comment]
@LouiseBonnard I agree with your proposal, form validation should be similar on every forms.

**Comment by patrickmyh** [comment]
@LouiseBonnard +1 for similairty of form validation.

**Comment by SD1982** [comment]
LGTM the tooltip is correctly added Thanks @patrickmyh
