### ISSUE TITLE
Problem with save prestashop button 1.6.1.20

### ISSUE THREAD

**Issue by Webgaict** [PrestaShop/PrestaShop#17865]
Good morning everyone when i try to save a new product or any changes i get from this error (screen attached) If i activate the devug mode it signals these errors to me.
what can I do?
![Immagine](https://user-images.githubusercontent.com/56969939/75444356-92ef1d80-5963-11ea-8756-f0575ec7423d.png)
![Immagine2](https://user-images.githubusercontent.com/56969939/75444358-9387b400-5963-11ea-8c87-59abc4130a8a.png)

**Comment by khouloudbelguith** [comment]
Hi @Webgaict,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

PS: PrestaShop 1.6 is not compatible with PHP 7.2, in fact, PrestaShop 1.6 is compatible with PHP5.6 => PHP 7.1  
For more details, you can follow this link: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!
