### ISSUE TITLE
The list of modules to update only display 6 modules max

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/PrestaShop#17871]
**Describe the bug**
In Modules > Module Manager > Updates tab, the list only displays 6 modules maximum. 

In the example below you can see there are 10 modules to updates, but only 6 displayed

See screenshot:
![Capture d’écran 2020-02-27 à 14 25 56](https://user-images.githubusercontent.com/25405887/75450468-2bd76600-596f-11ea-9d74-f19a333915f8.png)

When the page is loading you can briefly see all the modules in the list before it disappears and only displays 6 of them.

**To Reproduce**
1. Make sure you have more than 6 modules to update
2. Go to 'Modules > Module Manager > Updates tab'

**Additional information**
PrestaShop version: 1.7.6.2

---
**Expected behavior**

All modules to upgrade should be displayed in the list.
No more limitation to 6 display. Just a simple list as it it today.

**Comment by sam-pires** [comment]
Hello @TristanLDD & @prestascott,
Do you validate the expected behavior?

I guess when you have 100 modules to upgrade it can become messy without search, but as you can search and update modules from the first "Modules" tab, the users won't be stuck.

**Comment by prestascott** [comment]
Hi @sam-pires, 

Thank you for your report. I agree with you, this page should show the exact amount of modules that need to be updated. 

Search bar will only be nice to use when either the users already know the module to update or simply search if a specific module requires one. As you said, it will be really helpful for the users if they are overloaded by a long modules list to update. If they have less than 30 modules to update, i think it is useless.

I validate the expected behavior. :)

Wdyt? @TristanLDD

**Comment by TristanLDD** [comment]
Hi, I agree with @prestascott, I'm not sure the list of modules to upgrade would justify its own search bar, or at least it's not a priority in my opinion.

**Comment by sam-pires** [comment]
Perfect!
We're good to go then.

Thanks

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-qa : Will this issue (and PR) have impact on your automatized test ?

**Comment by boubkerbribri** [comment]
@Progi1984 No impact on automated UI tests.

Thanks for asking.
