### ISSUE TITLE
Free shipping vouchers in FO and BO should not be cumulative

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#17875]
**Describe the bug**
When adding two (or more) cart rules in FO and BO which include Free Shipping, they are both added, only on should be added.

**To Reproduce on FO**
1. Go to BO => Catalog => Discounts, create two cart rules with free shipping
2. Go to FO, create an order with paid shipping
3. Add the two cart rules
4. Shipping price is deducted twice

**Screenshots**
![two shipping vouchers](https://user-images.githubusercontent.com/55688534/75459019-0a7e7600-597f-11ea-9dae-f38ed7e3eee4.png)

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

**Comment by arouiadib** [comment]
Thank you @Robin-Fischer-PS for this important subject. 

If cart rules named `Ship 1` and `Ship 2` have conditions ( like restriction on product selection and/or restriction on carrier selection). 
And there are different carriers active. 
And, the cart contains many products (with or without specific carriers available)...
And, cart rules named `Ship 1` and `Ship 2` have other actions (like percentage  :rofl: and/or :rofl: free gift)...
Then the current behaviour is a normal behaviour. Because it takes the final amount, after all calculations, of  `Ship 1`  and add it to the final amount of `Ship 2`.

Here is my humbly point of view, please to correct me if I am wrong:
Current system is build with an idea in mind:  merchants will never create multiple cart rules with that same special configuration : **free shipping and only free shipping + no conditions**. That special configuration, let's call it the SUPERHERO-SHIPPING, is like telling customers: I will ship you for free all your cart, no matter is the number of products no matter what are specific carriers for each product, no matter what is the quantity...etc...etc, which no merchant will do (maybe). If this special case should be handled (Multiple SUPERHERO-SHIPPINGs ) then two modifications are needed:
![image](https://user-images.githubusercontent.com/23559010/75501292-ea2ad780-59cf-11ea-8704-84d17d1adafe.png)
The second is fixed by #17502. 
Maybe we should prevent merchant in BO to not create multiple Superheros.
AFAIK, there will be discussion about specs of cart rules during migration of `Catalog/Discounts/Add new cart rule`.  It will tell us what does free shipping really means? Do we need to implement [the proposal of Hlavtox](https://github.com/PrestaShop/PrestaShop/issues/16642)? team what do you think?

Thank you for reading.

**Comment by matthieu-rolland** [comment]
Looks like this issue is fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/17611

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/18321
