### ISSUE TITLE
Fix Serbian locale in PrestaShop

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#17890]
> message from Zoran, Serbian translator on Crowdin

#### Describe the bug

In PrestaShop 1.7.6, some code is changed and now is not possible to translate to Serbian language from BO. I found that the have added some code that says locale should be a combination of country code and language code. In Serbian case, it would be Sr-RS. That is why old Sr-CS is not working anymore. It works actually everywhere but not on BO when you want to translate anything. 

Fortunately I have fond solution for the problem and it works for me. But every time I have to install new PrestaShop I have to go to some modifications in order that everything works.

#### Expected behavior

Locale SR-CS is wrong, it should be called SR-RS (Combination of country code and language code according to some lines in PrestaShop cod). This new map on Crowdin for presta  1.7.7 is already there and it is named Sr-CS 

1.	Map should be renamed  from Sr-CS to Sr-RS 

2.	In all files in that map, on many places Sr-CS should be renamed to Sr-RS (please save all these files because I have translated everything myself and it took me so much time) 

3.	In this folder : \localization\CLDR\core\common\main there are two files:  sr_RS.xml file and another file sr.xml. In both files Sr-CS shoud be changed in Sr-RS

4.	In this folder \install\langs\sr language.xml is also one place with Sr-CS. It should be changed to Sr-RS. During the installation this will and up in database.

This is all. After these 4 steps PrestaShop could be used in Serbia without any problem.

#### One more thing

I reported long ago that even file: \js\jquery\plugins\validate\localization\ messages_sr.js is wrong. Language used in this file is Serbian Cyrillic and it should be Latinic. This is not changed yet. I have provided correct file but nothing has been done. I can provide correct file again if someone is willing to do these changes. 

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: N/A

**Comment by LouiseBonnard** [comment]
@PrestaShop/prestashop-core-developers, are you aware of this issue?

**Comment by matks** [comment]
Related to https://github.com/jquery-validation/jquery-validation/issues/2244

**Comment by LouiseBonnard** [comment]
> answer from the core team

So this issue comes from jQuery plugin for translation which does not handle properly Serbian language. If you really want this issue to be fixed you have to consider other solutions:

1. Stop using jQuery Validation in PrestaShop (drop this piece of software) and use a replacement that handles Serbia language correctly.

2. Modify how PrestaShop maps languages Serbia ISO code: according to the jQuery Validation maintainer, the right translation is put in another file called messages_sr_lat.js so it would require a dedicated behavior for Serbia where we ignore message_sr.js and use message_sr_lat.js instead.

3. Modify ourselves the code of jQuery Validation which is something that should never been done, excluding security vulnerabilities because the moment we do that it means we cannot upgrade anymore to new versions of jQuery Validation, we have to maintain our own version (previous core team did that for TinyMCE, it created bugs that lasted for years)

As you can see there is no easy solution here, each possible way requires a huge amount of energy so I'm afraid it won't be fixed on our end. I close this bug report, feel free to re-open it if need be.

**Comment by LouiseBonnard** [comment]
@matks, it looks like something has changed in 1.7.6 and there is now a real bug on this page, cf. screenshots below:

**International > Translations in 1.7.5**
![capture d'écran_2438](https://user-images.githubusercontent.com/32565890/75902659-aa854500-5e40-11ea-8995-0fadfefea2cd.png)

**International > Translations in 1.7.6**
<img width="328" alt="Capture d’écran 2020-03-04 à 17 46 09" src="https://user-images.githubusercontent.com/32565890/75902804-e6b8a580-5e40-11ea-9fc1-10d1f5c067ab.png">

**International > Translations in 1.7.7**
<img width="401" alt="Capture d’écran 2020-03-04 à 17 43 50" src="https://user-images.githubusercontent.com/32565890/75902863-02bc4700-5e41-11ea-82f4-a2b01979d468.png">

jQuery has not changed between versions 1.7.5 and 1.7.6, did he? :-)

**Comment by Zoran23** [comment]
Yes something is changed in PrestaShop 1.7.6 and now is not possible to translate Serbian language from BO. When I compared 1.75 and 1.7.6. I found new piece of code that says Locale should be made of country ISO code and language ISO code, Like sr-RS or sr-CS. 
CS was language code for now not existing country “Serbia and Montenegro”. 
Now existing country Serbia has language code RS and locale should be sr-RS. That is why we have error “Provided locale sr-CS is invalid” 
You can see language code for Serbia here: https://www.iso.org/obp/ui/#iso:code:3166:RS
Either new code that decides how locale should look like has to be changed , or 
Change the place where prestashop is checking Serbian language code, or 
Change locale for Serbian language in all 4 places that I have described above.
I have changed it for my shop and everything works as it should. 

Regards
Zoran

these 4 steps again:
1. Map should be renamed from Sr-CS to Sr-RS

2. In all files in that map, on many places Sr-CS should be renamed to Sr-RS (please save all these files because I have translated everything myself and it took me so much time)

3. In this folder : \localization\CLDR\core\common\main there are two files: sr_RS.xml file and another file sr.xml. In both files Sr-CS shoud be changed in Sr-RS

4. In this folder \install\langs\sr language.xml is also one place with Sr-CS. It should be changed to Sr-RS. During the installation this will and up in database.

**Comment by eternoendless** [comment]
Looks like we've been using `sr-CS` since [early 1.7.0.0](https://github.com/PrestaShop/PrestaShop/commit/f4b122dcb2359b154a650ae6ff666e613952d0ad), everywhere. 

No idea where that "CS" came from, as it's not a valid country code. Maybe it's short for "Cyrillic Script"? It sure looks like it was intentional because Serbian is written with cyrillic characters [in this file](https://github.com/PrestaShop/PrestaShop/commit/0cf1f2495cd29d13618697aa08f1d0921c2c48f3#diff-43d08b783f65830a5043bbdc65d0becaR480). Either way, the correct locale should be either `sr-Cyrl-RS` or `sr-Latn-RS`, but I don't think PrestaShop will support that kind of format without further modifications.

Anyway, I found the reason why Serbian cannot be translated in 1.7.6. It's due to [this verification](https://github.com/PrestaShop/PrestaShop/pull/11321/files#diff-f0c2048d6122a903ce9515acfd72098dR74-R77). It fails specifically for `sr-CS` because it's not a standard locale. I'll fix that so that we verify against installed languages instead.

**Comment by Zoran23** [comment]
Thank you, it woud be great.

**Comment by Zoran23** [comment]
CS was code for ex conty "Serbia and Montenegro". In serriban **C**rnagora **S**rbija

**Comment by eternoendless** [comment]
> CS was code for ex conty "Serbia and Montenegro". In serriban **C**rnagora **S**rbija

Thanks for the info! The More You Know...

**Comment by eternoendless** [comment]
I opened [another issue](https://github.com/PrestaShop/PrestaShop/issues/18062) to track the regression mentioned in [this comment](https://github.com/PrestaShop/PrestaShop/issues/17890#issuecomment-594657943) which I fixed.

**Comment by LouiseBonnard** [comment]
Now I close this issue since #18062 handles it. Many thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #18062
