### ISSUE TITLE
/modules/ps_advertising/img/advertising-s1.jpg net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#17929]
Get error: /modules/ps_advertising/img/advertising-s1.jpg net::ERR_BLOCKED_BY_CLIENT

and image of block advertising not shown with firefox

I think the image name is the problem but not sure

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Betafer,

I did not manage to reproduce the issue with PS1.7.6.3 and the ps_advertising module v1.0.2 using Firefox v45.6.0.
I attached a screen record
https://drive.google.com/file/d/1sO61zzW7j-XJiWwPq_X3Cyx3gvbvOAfy/view
What is the exact version of Firefox did you use?

Thanks!

**Comment by Betafer** [comment]
Hello, i have firefox 73

**Comment by khouloudbelguith** [comment]
@Betafer, it is ok using Firefox v73
https://drive.google.com/file/d/1f9niCKzCpPka25P0B9TGFl0Lmzo3N5wl/view
The cause could be in the network transport layer, a proxy server or a router between you and the server. It might also be something in the browser.

Thanks to check with your host and feedback.

**Comment by Betafer** [comment]
I Think Adblock plus, but i also have the problem without it

**Comment by khouloudbelguith** [comment]
@Betafer,

**How to solve net::err_blocked_by_client?**
There are some essential ways following which you can solve the net::err_blocked_by_client problem and use the browser at its full potential once again.

1. Disable the extension – one of the easiest ways to prevent this error from happening is by disabling the extension from Chrome. Just disable the Adblocker or the browser safety extension and prevent the error from popping up.
2. Whitelist the domain. You can also use a Whitelist domain to prevent this error. Therefore when you access trusted websites, you will not have to use Adblockers or safety extensions and thus preventing the users from getting the net::err_blocked_by_client error.
3. Debug the issue – another brilliant way to solve the problem is to debug the issue to the developer. If the net:: err_blocked_by_client message is showing even when you are not using an Adblocker or safety extension, then debug the issue. This will help them to check what is the exact reason you are facing this problem and show you the right solution in case it needs to be done from your side.

The above solutions that we have mentioned are proved to be helpful for many of the Chrome Browser extension. The net::err_blocked_by_client in Chrome can be irritating, and the ways it can be solved are not that difficult at the same time. Hence you can solve the problem by yourself and be back to using the browser again.

If you are not bothered about Advertisements, then disable the ad blocker in the first place, and your problem will be solved immediately. However, if ads are that irritating for you then make sure to debug the problem and wait for the development team to help you out or try other ways.

As it is not a PrestaShop core issue, I will close the ticket, feel free to open a new one when needed.

Thanks!

**Comment by Betafer** [comment]
Hello, the problem is not for me (shop owner) but for clients.
The customer must be able to see the block, even if he uses an adblocker, I think it is enough to be able to change the name of the image or perhaps the module

**Comment by Betafer** [comment]
Problem solved by re-installing the module
