### ISSUE TITLE
Not able  to upgrade from Prestashop 1.5.6.2 to 1.7.6.3 using 1-Click Upgrade

### ISSUE THREAD

**Issue by ashish76** [PrestaShop/PrestaShop#17932]
Hi,
I am trying to upgrade my shop from Prestashop 1.5.6.2 to the latest version 1.7.6.3 using 1-Click upgrade module developed by Prestashop. 

My database size almost 6.5 GB. and its taking hell lots of time to upgrade. After taking backup of the database it gives an error that Prestashop directory does not exist in the path /adminpanel/autoupgrade/download.

I have checked the path and found that there is no Prestashop directory but there is a file called Prestashop.zip

I tried 3 times but no success.

Now it becomes very critical so could you please help me with this?

Thanks

**Comment by khouloudbelguith** [comment]
Hi @ashish76,

You can use the 1-click upgrade module v1.6.1.8 to make an upgrade from 1.5 to 1.6 as described here: https://addons.prestashop.com/en/data-migration-backup/5496-.html
You can use the 1-click upgrade module v4.10.1 to make an upgrade from 1.6 to 1.7 as described here: https://addons.prestashop.com/en/data-migration-backup/5496-.html
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.
For your safety!
You need to make a back up of your shop.
For more details: The details of the changes to the MySQL database structure between 1.5 and 1.7 are available, version by version, in this folder https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/upgrade/sql


Also, you can use this module https://addons.prestashop.com/fr/migration-donnees-sauvegarde/8934-outil-de-migration-prestashop.html?ab=1

Thanks to check & feedback.

**Comment by ashish76** [comment]
Hi 
I am using the 1-click upgrade module v1.6.1.8. That is correct

Is it a 2-way process? Means first I have to upgrade the shop into 1.6 and then 1.7

Do you have any tutorials or videos for the same? 

But why I am getting this error? 

Please advise

**Comment by khouloudbelguith** [comment]
@ashish76,

There are two ways to upgrade PrestaShop:

1. Automatic: for the 1.5: you can use the 1-click upgrade v1.6.8(you can follow this [link](http://doc.prestashop.com/display/PS15/Automatic+update)), for PS1.6 => 1.7, you can use 1-click upgrade v4.10.1
https://addons.prestashop.com/en/data-migration-backup/5496-.html
2. Manual: for PS1.5, you can follow this link: http://doc.prestashop.com/display/PS15/Manual+update
For PS1.6, you can follow this link: http://doc.prestashop.com/display/PS16/Manual+update
For PS1.7, you can follow this link: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#manual-upgrade-process-details

Please be aware that PrestaShop previous versions < 1.6.1.4 uses 0-dates a lot which makes it incompatible with MySQL 5.7.
Changing your server configuration is the best way, however, if you can't modify it, you can apply this fix: https://github.com/PrestaShop/PrestaShop/pull/4507/files
About PrestaShop1.7, PrestaShop needs MySQL: 5.6 minimum or later recommended.
Thanks to follow this link: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @ashish76,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
