### ISSUE TITLE
Declinaison reference is not displayed on pack composition

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#17957]
#### Describe the bug

On backoffice product page for a pack, the declinaison reference is not displayed, product reference is displayed instead

#### Steps to Reproduce
1. Go to a declinaison detail 'T-shirt imprimé colibri Taille - S, Couleur - Blanc
2. Add a reference : demo_1_S_BLANC
3. Create a pack product
4. Add the declinaison to the pack : the declinaison reference is displayed. i.e. demo_1_S_BLANC
5. Save and reload page : the product reference demo_1 is displayed instead of declinaison reference

**Screenshots**
![download](https://user-images.githubusercontent.com/16720275/75795460-a4289780-5d72-11ea-887b-d9b0653aca93.png)

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2 and PS1.7.6.3.
A new pack product
![image](https://user-images.githubusercontent.com/16067358/75859622-9f0f2b00-5dfa-11ea-8c89-fc1ed2b3a108.png)
After reloading the page
![image](https://user-images.githubusercontent.com/16067358/75859665-b3532800-5dfa-11ea-85bc-99fc79783ef0.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Progi1984** [comment]
Fixed by #17972
