### ISSUE TITLE
Override dosen´t work in Multistore

### ISSUE THREAD

**Issue by Jose-Gp** [PrestaShop/PrestaShop#17964]
Hi, I have a problem that is driving me crazy. I have a multistore installed in Prestashop 1.6.1.24 and in one of those stores (id1) when activating the Override mode it only returns to its original state, when I give it to save the button it returns to blue, that is, if I select all The tie allows the override and everything works, I choose any store and it works except if I choose the store 1. I have renamed the override folder, I have copied the original files of the clean installation (classes, controllers, override, tools and some more) and NOTHING . I don't know if it is possible to activate this option from the BD or from any file. It is the first time that happens to me and in no other installation has it happened to me. I beg you for help since it is driving me crazy and I need the override so that modules that I need in the store work well.
Please i need Help!
Prestashop 1.6.1.24
PHP: 7.1
Multistore
![error-override](https://user-images.githubusercontent.com/61780653/75866428-4e50ff80-5e05-11ea-8e72-b3cfab0c398f.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Jose-Gp,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed.

But this issue occurs also with PS1.7.
This issue will be fixed in this ticket: https://github.com/PrestaShop/PrestaShop/issues/14804
Your ticket is a duplicate of #14804
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #14804

**Comment by Jose-Gp** [comment]
Thanks for your answer. I´m new here. I am not able to find the answer you tell me. Can you please tell me how I get to the solution of this problem. Again thank you very much for your help.

**Comment by khouloudbelguith** [comment]
@Jose-Gp, sorry, this issue not fixed yet.

Thanks!
