### ISSUE TITLE
Symfony module autowiring

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#17988]
Hello, I'm trying to integrate this Symfony code into a PrestaShop module : https://github.com/printoclock/business-api-demo-client

Standalone code is working perfectly but once integrated into a PrestaShop module "Autowire" don't seems to work and I get this error : 

<img width="1059" alt="Capture d'écran 2020-03-04 23 26 01" src="https://user-images.githubusercontent.com/167037/75928991-e552a180-5e6f-11ea-8fa8-da0c6d6b7d8e.png">

Here is my service.yml content and the project structure : 

<img width="1218" alt="Capture d'écran 2020-03-04 23 32 25" src="https://user-images.githubusercontent.com/167037/75929246-73c72300-5e70-11ea-8c38-a62d0038b9f7.png">

(I really just copied the files into a PrestaShop module)

Can you help?

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

Regards,

David.

**Comment by khouloudbelguith** [comment]
Hi @Daaaaad,

Please be aware that this bug tracker should be used to report issues ONLY. If you need help, you can ask on the Forum (https://www.prestashop.com/forums/), Gitter (https://gitter.im/PrestaShop/General) or Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop).
Thanks for your understanding!

**Comment by Daaaaad** [comment]
Hi @khouloudbelguith, "Symfony autowiring is no working" => I think it's a bug 😉

If not, Symfony integration is not ready for module integration...

**Comment by khouloudbelguith** [comment]
Ping @mickaelandrieu what do you think?

Thanks!

**Comment by matks** [comment]
> Hi @khouloudbelguith, "Symfony autowiring is no working" => I think it's a bug 😉
> 
> If not, Symfony integration is not ready for module integration...

I'm sorry to disagree, Symfony autowiring is a possible mode for Symfony to manage services. It's not mandatory to use it.

We actually did not check whether it works on try to make it work on purpose because we dont consider a good thing for PrestaShop right now.

A bit of context: a lot of PrestaShop developers are learning Symfony on-the-go with PS 1.7 and Dependency Injection is already something very new to them.

Autowiring adds a layer of magic which can prove very useful but can also confuse newcomers to Symfony. Even if it worked, we would neither promote its usage nor recommand using it as we prefer configuration that is clear and explicit, thus making it easier to learn and master.

So I'm not against looking at the issue and fixing it if it's not a big one, indeed it's nice to allow module developers to use Symfony autowiring if they want to, but I would not say "If Symfony autowiring is no working, Symfony integration is not ready for module integration"

**Comment by MageParts** [comment]
Lots of love
