### ISSUE TITLE
Newsletter_voucher email is sent in sign up without checking the newsletter subscription

### ISSUE THREAD

**Issue by kyripapa** [PrestaShop/PrestaShop#17990]
Hello,
n version 1.7.6.2 I have an issue with the newsletter.
During registration I have not checked "Subscribe to newsletter". However an email is sent to me
with the voucher code for the subscription to newsletter (Newsletter_voucher). In the backoffice the user is not registered to newsletter, but the coupon is sent anyway.

**Comment by khouloudbelguith** [comment]
Hi @kyripapa,

I did not manage to reproduce the issue with PS1.7.6.3 and the ps_emailsubscription module v2.3.0.
But, I have a similar issue with PS1.7.6.3 & PS1.7.5.2 and the `ps_emailsubscription` module v2.5.1.
https://drive.google.com/file/d/1uuupLlhE9-BnOqFSx1369DFc0P33D_bx/view
It is a regression
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks! in the module.

**Comment by matthieu-rolland** [comment]
Fixed in this PR:  https://github.com/PrestaShop/ps_emailsubscription/pull/51

(the bug comes from the module)

**Comment by Progi1984** [comment]
Fixed by PrestaShop/ps_emailsubscription#51
