### ISSUE TITLE
Problem while using the Click Upgrade module

### ISSUE THREAD

**Issue by tegeeks** [PrestaShop/PrestaShop#18048]
#### Describe the bug

I have recently purchased the click upgrade module, I have been able to install it but when I click to configure it is thinking and at the end of the error. How can I solve it?

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @tegeeks,

Thanks to provide us a clear description of your issue.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @tegeeks,

Thanks for your report.
What is the exact version of the 1-click upgrade did you install it.
Did you install this module from the BO => Modules => Module Catalog page?
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by tegeeks** [comment]
v4.10.1 - de PrestaShop
Nothing appears in the PHP error log, it just keeps thinking and hangs the page does not allow or configure the module.
this is what appears
admin_17.js:19 Uncaught ReferenceError: $ is not defined
    at admin_17.js:19

**Comment by tegeeks** [comment]
[DOM] Input elements should have **manage?_token=HMeHBluaysNzchF_F-k1BVawUexEWToU5zp3oGWSwe0** 
autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) 

Failed to load resource: the server responded with a status of 504 ()

**Comment by khouloudbelguith** [comment]
@tegeeks, thanks to turn on the Debug mode on PrestaShop 1.7, follow these steps:

- Got to Advanced Parameters > Performance
- In the Debug Mode section, set “Debug Mode” to “Yes”.
- Click the “Save” button.

Now, go back to the configuration page and check if there is an exception displayed.

Did you install this module from the BO => Modules => Module Catalog page?
https://addons.prestashop.com/fr/migration-donnees-sauvegarde/5496-1-click-upgrade.html

Thanks to try to re-install the module, clear cache, check and feedback.

**Comment by tegeeks** [comment]
I've done all the steps and it still doesn't work

**Comment by didi-2018** [comment]
@khouloudbelguith I had the same problem today. I think it was the time when Presta offered the Upgrade to the module. By trying to access the module I always got an timeout. After a while it was working again without porblems.

**Comment by tegeeks** [comment]
In my case I hope, the page hangs and this error appears:
504 Gateway Time-out

**Comment by khouloudbelguith** [comment]
@tegeeks, Most of the time, a 504 Gateway Timeout error means that whatever other server is taking so long that it's "timing out," is probably down or not working properly.
Misconfigurations at the client side can result in “504 gateway time-out error in Prestashop”, It can be due to various reasons like:

- Improper browser settings or browser cache.
- Temporary problems with the network devices such as modems, routers, etc.
- Incorrect proxy settings in the browser or application.
- Network issues.

Please contact your host about this error & feedback.

**Comment by tegeeks** [comment]
There is no configuration, the rest of the modules work correctly for me. In addition, this module does not even let me configure it, it remains hung whenever I make any gesture with the module. Therefore, it is a problem with the module that has never worked since I installed it.

**Comment by khouloudbelguith** [comment]
@tegeeks 

Could you please follow this link: https://github.com/PrestaShop/php-ps-info
phppsinfo file provides an equivalent to the phpinfo() function that reports PrestaShop Requirements information about the PHP/MySQL/Apache environment and offers suggestions for improvement.
[phppsinfo.php.zip](https://github.com/PrestaShop/PrestaShop/files/4311387/phppsinfo.php.zip)

1. Upload the file to the server. You should upload your file to the exact directory you want to test. Typically, this will be your httpdocs (/var/www/vhosts/example.com/httpdocs/) directory, although you can upload it to any subdirectory on your server as well. Use FTP to upload the file.
2. Visit the page in your browser. If you uploaded it to your html directory, you should now visit http://www.example.com/phppsinfo.php, replacing example.com with your own domain name.
3. Now you can view all of the information about PHP for your server for that particular directory.

![image](https://user-images.githubusercontent.com/16067358/44723217-a8199080-aacf-11e8-8c33-171ecbf3b5db.png)
Thanks to check and feedback.

**Comment by didi-2018** [comment]
@khouloudbelguith today the same at me. It loads and loads and loads until timeout error 😔. If I try a few times to load then it loads. And I get this message in module:

![image](https://user-images.githubusercontent.com/44971218/76338690-53c4b300-62f9-11ea-963c-a2ef2d177588.png)

maybe that helps?

**Comment by khouloudbelguith** [comment]
@tegeeks, I need to get these informations provided in this [comment](https://github.com/PrestaShop/PrestaShop/issues/18048#issuecomment-596984562).

Thanks!

**Comment by marionf** [comment]
Hello,
Since we had no news from you for more than 25 days, I close this issue. Feel free to open another one if you can provide more details.
Thank you!

**Comment by fhemery** [comment]
Hello,
In case it could help anyone reaching this thread because he encounters the error, I faced the issue and solved it through a workaround.

The module explores your full website to check what kind of backup he'll have to do as soon as it starts. As a consequence, if you have many products, thus many images (i have more than 500k on my site), it hangs forever. 

Solution : move the `img/p` folder outside of your website before clicking on the 1-Click upgrade module (and take profit to back them up somewhere 😋).

Hope it helps :)
