### ISSUE TITLE
Capitalized mail addresses still not fixed in 1.7.6.4

### ISSUE THREAD

**Issue by sharkooon** [PrestaShop/PrestaShop#18053]
Why is pull request #16550 still not fixed in 1.7.6.4?
It fixes sending variables in mailtemplates when CAPITALIZED mail addresses is used..

https://github.com/PrestaShop/PrestaShop/issues/16436
https://github.com/PrestaShop/PrestaShop/pull/16550

**Comment by khouloudbelguith** [comment]
Hi @sharkooon,

Thanks for your report.
PS1.7.6.4 is a patch version, not a major version.
As you can see in [our official documentation](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#target-branch).
A patch version (in our case, it is PS1.7.6.4) is released to fix critical bug issues and regressions only.
The "Capitalized mail addresses" is fixed in the next Major version PS1.7.7.0 because:
- It is not a regression
- It is not a critical security issue

Thanks for your understanding!

**Comment by sharkooon** [comment]
Well this is really a critical bug which should be fixed.

using mail@Gmail.com will cause problems right now!

**Comment by khouloudbelguith** [comment]
Hi @sharkooon,

Thanks to check this [link](https://build.prestashop.com/news/severity-classification/) to check the bug severity classification.

Thanks!

**Comment by sharkooon** [comment]
Alright, but based on that link, it is classified as critical: Difficulty to globally place and manage orders

**Comment by ttoine** [comment]
Hello, you can have a look at the version in which a pull request has been merged in the right column, see under "milestone"

![Selection_666](https://user-images.githubusercontent.com/4619685/76227821-28ba6080-6220-11ea-991c-fa50119055ae.png)

This particular fix has been merged in the 1.7.7 branch. The good news is that the beta of this release is on the way, and hopefully, it should be released soon.

Regarding the way issues are sorted (severity, and priority), please respect the work of the team doing it. In this case, this is, for sure, not critical and it does not deserve a dedicated patch release.
