### ISSUE TITLE
Exclude discounted products: YES & Apply a discount to Selected product(s) Don't work correctly

### ISSUE THREAD

**Issue by webstartconsulting** [PrestaShop/PrestaShop#18065]
#### Describe the bug

The coupon settings below do not work. The discount rate is incorrect because it also counts a discount on a promotional product. The product has a unique price (screen3).

#### Expected behavior

The coupon should give you a 790 HUF discount. 100% of the price of the non-promotional product. Or 50% if the coupon is set up this way.

-------------------------
>Edited by Khouloud

Steps to reproduce the issue:
1. Create a product `Product1` with a price = 36€ Tax included
2. Create a specific price on this product with 20€ Tax included
3. Create a second product Product2 with a price =120€ Tax included
4. Create a cart rule
4.1 With a code/ or not
4.2 Conditions => Product Selection ( add those product created Product1 & Product2 to the selection)
![image](https://user-images.githubusercontent.com/16067358/76239358-b8b4d600-6231-11ea-8b76-28bba1a55400.png)
4.3 Actions: Apply a discount 100% to Selected products + Exclude discounted products enabled
![image](https://user-images.githubusercontent.com/16067358/76239449-e13cd000-6231-11ea-88e2-c19ca0e58e0f.png)
5. Save
6. Go to the FO => add those products Product1 & Product2 to the cart
7. see error => Cart total should be calculated with cart rule applying only on the not-discounted product
![image](https://user-images.githubusercontent.com/16067358/76239623-2eb93d00-6232-11ea-937f-c4e7e08519ea.png)

This issue: https://github.com/PrestaShop/PrestaShop/issues/10300 is not fixed when we have the product selection in the cart rule.

------------------------------

#### Steps to Reproduce

**1. In the administration interface, add the coupon with the settings shown in the image.**
![Screenshot_1](https://user-images.githubusercontent.com/41392532/76232610-39220980-6227-11ea-9daf-898de2ac401f.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/41392532/76232619-3e7f5400-6227-11ea-9572-65d76a769539.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/41392532/76232627-40e1ae00-6227-11ea-8e14-8390cb6ed474.jpg)

**2.  Add a specific price to a product**
![Screenshot_4](https://user-images.githubusercontent.com/41392532/76232660-4fc86080-6227-11ea-9b90-4675c481fafe.jpg)

**3. Put the products in to your cart:**
![Screenshot_3](https://user-images.githubusercontent.com/41392532/76232728-666eb780-6227-11ea-9ee3-ef741d16bdd2.jpg)

**Correctly, the coupon discount should only count on non-promotional products.**

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.2

The following reports and fixes not resolve this bug: #10454, #15876, #14407, #14442

**Comment by khouloudbelguith** [comment]
Hi @webstartconsulting,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.4, and the branch 1.7.7.x
Steps to reproduce the issue:
1. Create a product `Product1` with a price = 36€ Tax included
2. Create a specific price on this product with 20€ Tax included
3. Create a second product Product2 with a price =120€ Tax included
4. Create a cart rule
4.1 With a code/ or not
4.2 Conditions => Product Selection ( add those product created Product1 & Product2 to the selection)
![image](https://user-images.githubusercontent.com/16067358/76239358-b8b4d600-6231-11ea-8b76-28bba1a55400.png)
4.3 Actions: Apply a discount 100% to Selected products + Exclude discounted products enabled
![image](https://user-images.githubusercontent.com/16067358/76239449-e13cd000-6231-11ea-88e2-c19ca0e58e0f.png)
5. Save
6. Go to the FO => add those products Product1 & Product2 to the cart
7. see error => Cart total should be calculated with cart rule applying only on the not-discounted product
![image](https://user-images.githubusercontent.com/16067358/76239623-2eb93d00-6232-11ea-937f-c4e7e08519ea.png)

This issue: https://github.com/PrestaShop/PrestaShop/issues/10300 is not fixed when we have the `product selection` in the cart rule.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/prestashop-product-team what do you think?
This issue should be fixed in the PS1.7.7.0?

Thanks!

**Comment by colinegin** [comment]
If I understand correctly, we did not manage to fix all issues in #10300, which was fixed for 1.7.7.
So, yes, I recommend to fix it for 1.7.7. I put it in the kanban.

**Comment by Progi1984** [comment]
Fixed by #18144

**Comment by Whip** [comment]
Hi. There is still a minor discrepancy in the discounts displayed. If you take a look at the screenshot, one of the products has discount and should be excluded from promo discount calculation which is working fine. Its a 10% off coupon so you get 39.9 off on the 399 product. The total amount being calculated is correct too but below that, the promo code says -91.8 discounted. This message is conflicting with the -39.9 displayed above and is confusing the customers.

![2021-01-02](https://user-images.githubusercontent.com/11595460/103451044-eb5e1c80-4ce4-11eb-88c5-18e05b601628.jpg)

**Comment by MatShir** [comment]
Hi @hibatallahAouadni or @khouloudbelguith, could you reproduce @VeeK727's issue, please 😄

**Comment by hibatallahAouadni** [comment]
Hello @VeeK727 

We are aware of that issue #19090, it is already in our debug backlog.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!
