### ISSUE TITLE
Menu entries wrongly displayed in 1.7.7

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#18067]
#### Describe the bug

While testing the 1.7.7 via my VM, I noticed two incorrect menu entries, 'Order Settings' instead of '**Orders**' and 'Customer Settings' instead of '**Customers**'. See screenshots below.

<img width="483" alt="Capture d’écran 2020-03-06 à 17 08 26" src="https://user-images.githubusercontent.com/32565890/76240090-ecdcc680-6232-11ea-8034-e372d7e4d0b3.png">

<img width="547" alt="Capture d’écran 2020-03-06 à 17 08 47" src="https://user-images.githubusercontent.com/32565890/76240095-eea68a00-6232-11ea-89f5-0daaeb6a37c5.png">

#### Expected behavior

'Order Settings' should be '**Orders**'
'Customer Settings' should be '**Customers**'

#### Steps to reproduce the behavior

1. Go to PrestaShop 1.7.7's back office
2. See errors

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by LouiseBonnard** [comment]
Hi @khouloudbelguith, could you tell me if you reproduce this issue? It is all fine on @MatShir side so I'm not sure if it is a real bug or not. :-)

**Comment by khouloudbelguith** [comment]
Hi @LouiseBonnard,

Yes, I manage to reproduce the issue with PS1.7.6.4.
Steps to reproduce the issue:
1. Install PS with French language and France country
2. Go to the BO => International => import united states pack
3. Change the employee language to English
4. See error

![image](https://user-images.githubusercontent.com/16067358/76294209-bba3db00-62b2-11ea-985e-ac225925c25d.png)

This issue is duplicated of https://github.com/PrestaShop/PrestaShop/issues/9762
Related to this: https://github.com/PrestaShop/PrestaShop/issues/9816

Thanks!

**Comment by LouiseBonnard** [comment]
I close this issue since it is a duplicate, thank you again @khouloudbelguith!

**Comment by khouloudbelguith** [comment]
Duplicate of #9762
