### ISSUE TITLE
Duplicate address in checkout Address step on address edition  

### ISSUE THREAD

**Issue by DelecroixQuentin** [PrestaShop/PrestaShop#18072]
#### Describe the bug

With the security fix apply (tested on 1.7.2.3, 1.7.4.3, 1.7.5.1, 1.7.6.2, 1.7.6.4), when editing an address from the "Address" step of the checkout, a new address will be created instead of editing the current one.

From the "Address" page of the customer account, this works well.

The problem is that the `Tools::getValue('id_address')` (introduced in this [commit](https://github.com/PrestaShop/PrestaShop/commit/470af81cafd3b0c24f039e2559f2e744292054c5)) can't read an address id in the $_GET or $_POST (see screenshot) 

![Capture d’écran 2020-03-10 à 10 22 56](https://user-images.githubusercontent.com/8830801/76298059-28ba6f00-62b9-11ea-8d68-767c092a9e8f.png)

#### Expected behavior

Edit the address instead of creating a new one when the customer wants to edit his address

#### Steps to Reproduce

1.  Login, if you don't have an address, create it
2. Add product in cart
3. Process checkout
4. On the "Address" step, edit your address and save
5. Back to the "Address" step
6. See error

Before:
![Capture d’écran 2020-03-10 à 10 30 00](https://user-images.githubusercontent.com/8830801/76298751-3c1a0a00-62ba-11ea-8bc4-e112e0a088a8.png)

After:
![Capture d’écran 2020-03-10 à 10 30 21](https://user-images.githubusercontent.com/8830801/76298765-420feb00-62ba-11ea-9794-fb3f1b5cb2e6.png)

#### Additional information

* PrestaShop version: tested on 1.7.2.3, 1.7.4.3, 1.7.5.1, 1.7.6.2, 1.7.6.4
* PHP version: 7.2.21

**Comment by nand2** [comment]
**Edit: I am not running a clean 1.7.6.4 installation, so the bug I am describing may not happen in a clean installation.**

This pull request does not seem (not tested your patch, assumed) to fix the case where you edit your address in your profile (not in the checkout process).
How to reproduce : Go to your profile, edit an address. Put numbers in the firstname field in order to trigger a validation error. Then remove the number, and save. It will create a duplicate address. Reason: The url for the POST is set to /adresse?id_address=0

I would even say that part of the [fix for CVE-2020-5250](https://github.com/PrestaShop/PrestaShop/commit/470af81cafd3b0c24f039e2559f2e744292054c5) in classes/form/CustomerAddressFormatter.php  : 
```patch
        $format = [
-            'id_address' => (new FormField())
-                ->setName('id_address')
-                ->setType('hidden'),
```
for the purpose of preventing editing other's addresses was unnecessary because the id_address was already validated (cf CustomerAddressPersister.php)
```php
private function authorizeChange(Address $address, $token)
{
    if ($address->id_customer && (int)$address->id_customer !== (int)$this->customer->id) {
        // Can't touch anybody else's address
        return false;
    }
    [...]
}
```
and I was not able to reproduce the problem where one could overwrite the address of someone else.

That being said, on submission, the id_address should only be given once, and it was given twice here (as a GET and a POST parameter). So it is good it was removed as a POST parameter, but then it should be always be there as a GET paramater, which is not the case after a validation error.

And I am reaching here the limits of my Prestashop knowledge :-) I can't see why it is not filled again after a validation error without going deep into the code... Anyone can see why? Thanks!

**Comment by DelecroixQuentin** [comment]
Nice catch ! 
A possible fix (tested only for this case), in classes/form/CustomerAddressForm class, function getTemplateVariables(), change this
```php
return array(
            'id_address' => (isset($this->address->id)) ? $this->address->id : 0,
            'action' => $this->action,
            'errors' => $this->getErrors(),
            'formFields' => $formFields,
        );
```
to this
```php
return array(
            'id_address' => (isset($this->address->id)) ? $this->address->id : Tools::getValue('id_address', 0),
            'action' => $this->action,
            'errors' => $this->getErrors(),
            'formFields' => $formFields,
        );
```

**Comment by nand2** [comment]
Thanks, I confirm this fix the bug I described.

**Comment by Progi1984** [comment]
Fixed by #18073

**Comment by DelecroixQuentin** [comment]
Hey @Progi1984, 
Did you notice this [comment](https://github.com/PrestaShop/PrestaShop/issues/18072#issuecomment-597524637) ?
There are another duplication address issue but this one is on customer address page.
Should we create another issue for this bug?

Thanks !

**Comment by khouloudbelguith** [comment]
Hi @DelecroixQuentin, @nand2,

Issue created here: https://github.com/PrestaShop/PrestaShop/issues/18100

Thanks!

**Comment by Progi1984** [comment]
Sorry ! Not seen the comment. Thanks @khouloudbelguith

**Comment by colinegin** [comment]
I reopen this issue as we have to fix it for 1765.

**Comment by colinegin** [comment]
Fixed by: #18103

**Comment by khouloudbelguith** [comment]
Hi!

This issue is still reproduced with PS1773build1 & PS1769.
Steps to reproduce the issue:
0. Enable France & United states countries in the BO > International > Location > Countries page
1. Go to FO  > Sign in with John Doe
2. Add a product to the cart
3. Click on Proceed to checkout 
4. In the Address step: Edit the **country** from France to "United States"
5. Click "Save"
6. Click on the "Address step" => Duplicated Address

https://drive.google.com/file/d/1YwU4rUQaNV3B6qel0Z43SWDS_5Z00uT9/view?usp=sharing

Ping @PrestaShop/product-team what do you think? it should be fixed in which version?

Thank you!

**Comment by marionf** [comment]
@khouloudbelguith Could you please create a new issue ?
