### ISSUE TITLE
[Order page] All links in order page should open a new tab

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#18105]
Currently when clicking on a link, the new page replaces the old one. This should not be the behaviour, the new page should be opened in a new tab, to allow the user to see both pages.

All following links should follow this rule : 
- customer in the order listing
- view full details in the customer block
- configure predefined messages in the message block
- the product page in the product block

**Comment by matks** [comment]
@colinegin Are you sure about that ?

I'm asking because, if you ask people "do you prefer than clicking on links open a new tab or replaces current page" you will get 50% "Yes I want it !" and 50% "No I dont want that" 😄and some people will tell us we are crazy for even considering doing it (or not doing it).

So if we implement this feature, we can expect people to complain 😄for sure (and if we dont do it, we'll have other people complaining too ! you need to choose which side you want to header).

The only argument I have in favor of one of the 2 sides is that if we choose "open links in current page", people can always open links in a new tab using right click. If we choose "open links in new tabs" I'm not people can workaround it 🤔

**Comment by NeOMakinG** [comment]
The rule should be : If the link is aiming an external page, then open a new tab, otherwise if it's aiming the product and will change informations on the current page afterwhile, then replace the current page, that's a common web rule to be honest

**Comment by colinegin** [comment]
Again ping @MatShir @TristanLDD , i'm not the one who decides here, i just wrote the issue after we talked about it when testing the page.

**Comment by TristanLDD** [comment]
For more consistency I say we replace the current page on every link of the order details page (and leave the choice to the user to use the right click) 
But for the customer link in the order listing, I'd like to open it in a new tab so the merchant doesn't loose the pagination / position of the line he clicked on.

**Comment by Progi1984** [comment]
Fixed by #18266
