### ISSUE TITLE
File uploads on each page refresh, also Error on refresh page after deleting the customization on Product in fron office.

### ISSUE THREAD

**Issue by ramwebkul** [PrestaShop/PrestaShop#18118]
**Describe the bug:**
After the customization value is deleted in product page, following issues occur:
- Error on refreshing product page after deleting the customization value.

**Expected Behaviour:**
- Should not show error on refresh the page.

**Steps to reproduce:**
- Go to BO => Products
- Create a new product
- In the options Tab => add a Customization (all type and could be required or not)
- Go to the FO => Product details page => add the customization to the product:-
![image](https://user-images.githubusercontent.com/53465735/76523579-a84d6700-648e-11ea-9cbf-59eada299686.png)
- ***FIRST ISSUE*** - Refresh the page now, it will ask for resubmitting the data and on confirmation, it again uploads the image.
![image](https://user-images.githubusercontent.com/53465735/76524889-d92e9b80-6490-11ea-8a2a-e8151015f71b.png)

- Now delete this value/file:
![image](https://user-images.githubusercontent.com/53465735/76523645-c1561800-648e-11ea-9a42-909fc37f6525.png)

- ***SECOND ISSUE*** - Now refresh the page, you will see error message.
![image](https://user-images.githubusercontent.com/53465735/76523703-d8950580-648e-11ea-87f6-ff85f5251051.png)

This is because the URL contains "?deletePicture=idCustomization" which is not removed on successfully deleting the picture hence on refresh, it again tries to delete the customization which is already deleted.

If the image/text was successfully deleted, the URL should not show "deletePicture" argument anytime.

Additional information
PrestaShop version: 1.7.6.1 (checked in this version but exists in all versions I tried)
PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @ramwebkul,

Thanks for your report.
I have the same issue with PS1.7.5.2 and PS1.7.6.4.
But it is fixed in the next release PS1.7.7.0.
I attached a screen record
https://drive.google.com/file/d/1BjwjodjT7TGK3GUNZbvguHzBrjOtD-yx/view
Those [issues](https://github.com/PrestaShop/PrestaShop/issues?q=label%3ACustomized+label%3AFO+label%3AFixed+is%3Aclosed) are fixed in the PS1.7.7.0 related to the customized product.

Since, it is fixed, I will close the issue.
Thanks!
