### ISSUE TITLE
Cart rule with free product

### ISSUE THREAD

**Issue by ebaubau** [PrestaShop/PrestaShop#18129]
When the customer adds the cart rule code the free product is added to the cart but the custmer should not have the possibility to change the quantity of the free product.

**Comment by arouiadib** [comment]
Hello @ebaubau 

> .... but the customer should not have the possibility to change the quantity of the free product.

It depends on the merchant. What if he wants to allow the purchase of additional items from the free product.
<del>What if the cart rule has an end date after which the merchant wants normal purchase? or maybe other conditions? </del>

I agree with you that some merchants would want to have a product X to serve only as a gift, but here we should disable the add-to-cart button for product X as well, and it is not the only part to change. Maybe an option in the back office like "Allow purchase of gift product"  and all the processing behind, database, calculations, display.... It needs a study and a specification.

IMO the current behaviour is enough. Customer is able to add product X to cart and the default quantity is 2. if you decrease to 1 then the product is removed from cart. 

Let's first ask @PrestaShop/prestashop-product-team is this feature belongs to current specs? or is planned in the future? out of scope?

Thank you very much.

**Comment by ebaubau** [comment]
I agree with this sentence
"IMO the current behaviour is enough. Customer is able to add product X to
cart and the default quantity is 2. if you decrease to 1 then the product
is removed from cart."

But the customer can change the quantity of the FREE PRODUCT. He can get
999 free products.






Il Sab 14 Mar 2020, 17:41 Adib Aroui <notifications@github.com> ha scritto:

**Comment by arouiadib** [comment]
Hi @ebaubau,

I totally agree with you about the `999` matter. Great catch from you :).  I suggest you look at a similar scenario [in a another situation here](https://github.com/PrestaShop/PrestaShop/issues/17665#issuecomment-586744326).

I think your observation needs to be studied and specified first, because it has connection with other conditions. I heard that cart rules will be discussed in depth before migrating the cart rules page in BO for 1.7.8.0. That will be a good opportunity to suggest scenarios because it is really not an issue of quick fix (it concerns many parts of the codebase, php, javascript, templates, integration tests... and hence needs to be deeply discussed).

There is a [newly created repo for specs.](https://github.com/PrestaShop/prestashop-specs). It is really a good place for scenarios ( Kudos for the smart  guys who created the repo). If we can help Prestashop 7 developpers in 2050 when they will be migrating code from an architecture to another :D. We can also help ourselves by answering exactly such questions. That will be amazing :) no?. It is like creating the "minimum viable Prestashop" for all times,  to which we can go back to answer exactly such questions.

If you are interested in giving it more thought or sharing them with the community, please to write them as a ticket or PR there.

Thank you very much for this important subject and for your time :)

**Comment by khouloudbelguith** [comment]
Hi @ebaubau,

Thanks for your report.
>but the custmer should not have the possibility to change the quantity of the free product.

As @arouiadib said, It depends on the merchant.

The Gift product, it is in fact a simple product active with X quantity, if you search this product in your shop, you can see it and add it to cart independent of the cart rule created.
https://drive.google.com/file/d/13A6L618uy22rGxX37y8RuP0w1HGKux3t/view?usp=sharing

>But the customer can change the quantity of the FREE PRODUCT. He can get
999 free products.


The customer can get X quantity available for the gift product, but he can get only one free product.
 1. Cart rule Action
![image](https://user-images.githubusercontent.com/16067358/76846554-f40e6080-6840-11ea-8f33-337695549463.png)

2. Fo => Shopping cart page
![image](https://user-images.githubusercontent.com/16067358/76846748-494a7200-6841-11ea-84c6-96a9b57fc726.png)


Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @ebaubau,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
