### ISSUE TITLE
Can't show module on the Left Column

### ISSUE THREAD

**Issue by ErikDeMartiis** [PrestaShop/PrestaShop#18137]
#### Describe the bug

I can Transplant the module in the leftcolumn and leftColumnProduct position, but the module is not showing

#### Expected behavior

See products related/inside the same Category of the product that I'm browsing in the left column

#### Steps to Reproduce

1. Go to 'Modules'
2. Click on 'Trasplant Modules'
3. Scroll down to 'Product in the same category', Trasplant to displayColumnLeft or/and displayColumnProduct
4. Browse a product or a category page (both with layout with 2 or 3 columns) and you can't see  any product of the same category in the left column, but only in product page in displayFooterProduct 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

<img width="908" alt="Schermata 2020-03-13 alle 11 34 40" src="https://user-images.githubusercontent.com/10062040/76613570-b054e780-651e-11ea-8f32-b8b3f6ab981d.png">

<img width="599" alt="Schermata 2020-03-13 alle 11 32 54" src="https://user-images.githubusercontent.com/10062040/76613619-c793d500-651e-11ea-9c59-861068ef150a.png">

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @ErikDeMartiis,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.4, and the branch 1.7.7.x
![image](https://user-images.githubusercontent.com/16067358/76755656-843aa000-6784-11ea-933f-11ba5d30043b.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
