### ISSUE TITLE
Tabs of product page have different widths in back end with view only permission.

### ISSUE THREAD

**Issue by JoshaMunnik** [PrestaShop/PrestaShop#18173]
#### Describe the bug

When changing the permission of a profile for products to View only (Add, Edit and Delete are all unchecked) the tabs of the product page have different widths and are shown differently compared to an employee that does have a profile that allows for editing of a product.

#### Expected behavior

The layout/styling should be the same; just with buttons disabled.

#### Steps to Reproduce

1. Via Create an employee with profile salesman.
2. Alter the permissions for salesman for Products so that only the View is checked.
3. Logout / Login as newly created employee.
4. Select a product from the Products list

First tab:
![Prestashop View Only 1](https://user-images.githubusercontent.com/1231100/76828084-d7fec500-6828-11ea-8201-f97456b28257.png)

Options tab:
![Prestashop View Only 2](https://user-images.githubusercontent.com/1231100/76828094-de8d3c80-6828-11ea-8c9a-15189a5c9bdc.png)

#### Cause

This is probably caused because `product.html.twig` surrounds the form with a `<fieldset disabled id="field-disabled">` when the product is not editable.

#### Additional information

* PrestaShop version: 1.7.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @JoshaMunnik,

Thanks for your report.
I manage to reproduce the issue with 1.7.7.x branch, PS1.7.6.4, and PS1.7.4.4.
In the BO => Catalog => Product details page, the tabs of the product page have different widths and are shown differently.

1. Basic Settings Tab
2. Shipping Tab
3. Pricing Tab
=> 
![image](https://user-images.githubusercontent.com/16067358/76833940-8d7f4780-682c-11ea-9345-9d9c403635e6.png)

1. Quantities Tab
![image](https://user-images.githubusercontent.com/16067358/76833991-aab41600-682c-11ea-92c7-08af583fa9f3.png)

1. SEO Tab
2. Options Tab
=>
![image](https://user-images.githubusercontent.com/16067358/76834037-bef81300-682c-11ea-8cb8-5945e83778fa.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by colinegin** [comment]
ping @MatShir @TristanLDD I think this could be fixed during the product page migration.
What do you think ?

**Comment by colinegin** [comment]
ping @MatShir @TristanLDD I think this could be fixed during the product page migration.
What do you think ?
