### ISSUE TITLE
PrestaShop 1.7.6.2 - PHP 7.2 - Payment module not displayed on Front office

### ISSUE THREAD

**Issue by OBSEVILLA** [PrestaShop/PrestaShop#18252]
#### Describe the bug
Payment module not displayed in the checkout page. PrestaShop 1.7.6.2
They are actived in the bacck office, but impossible to display on the Fo
Migration from 1.6 to 1.7.6.2 without 1-Click upgrade
Everything work fine except this
In the back office, it's impossible to change the Carrier restrictions

#### Expected behavior
It's better with payment module :)

#### Steps to Reproduce
1 - Add procduct to cart
2 - Proceed to checkout...
3 - Step 4 : "Unfortunately, there are no payment method available."

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5737509/77223720-6479f200-6b5f-11ea-94c7-8467c448970b.JPG)
![Capture2](https://user-images.githubusercontent.com/5737509/77223721-65128880-6b5f-11ea-8fe0-f632ccec25d5.JPG)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @OBSEVILLA,

Thanks for your report.
As you can see in your screenshot
![image](https://user-images.githubusercontent.com/16067358/77301656-5a3b2d80-6cf0-11ea-9029-f9ab4bbe573f.png)
All your payment modules are not selected.
So, this is the whole issue.

>In the back office, it's impossible to change the Carrier restrictions

We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by OBSEVILLA** [comment]
Hi,
thanks for contact me

I succeed in repair the error

- I fix the next problem: updating the carrier restriction, it was a
problem with the php input_var_max value
- next I have reinitialized the modules, it was good because the shipment
restriction were goods, and I had the module in the 2 hooks

but it was strange

Best Regards

Olivier Bertoncello
0034 955 180 438
0034 699 557 553
obdc@data-consulting.org
www.data-consulting.org
www.tapas-shop.com


Le lun. 23 mars 2020 à 10:27, khouloudbelguith <notifications@github.com> a
écrit :

**Comment by khouloudbelguith** [comment]
@OBSEVILLA, thanks for your feedback.
Since it is fixed, I will close the issue.
Feel free to open a new one when needed.

Thanks!
