### ISSUE TITLE
The server returned a "500 Internal Server Error"... in v 1.7.6.4...

### ISSUE THREAD

**Issue by ventybug** [PrestaShop/PrestaShop#18260]
Hi,

when in the back office in v 1.7.6.4 I choose     CONFIGURE / settings Shop Parameters / General ... ,  I get the following:

"Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

Occasionally with other menu items in the back office...

PHP - 7.2.9

Pls, help...

Thanks in advance!

BR

Venty

**Comment by JBWModules** [comment]
Please see my answer in the forum, you have an override active causing the issue
https://www.prestashop.com/forums/topic/1017892-the-server-returned-a-500-internal-server-error-in-v-1764/?tab=comments#comment-3210935

**Comment by khouloudbelguith** [comment]
Hi @ventybug,

When debug mode is enabled, you have this exception as explained in the [forum](https://www.prestashop.com/forums/topic/1017892-the-server-returned-a-500-internal-server-error-in-v-1764/?tab=comments#comment-3210935).
![image](https://user-images.githubusercontent.com/16067358/77295408-3377f980-6ce6-11ea-916b-9c91bac6dc09.png)
Your issue is not a PrestaShop's core bug but most likely a customization problem.

Thanks!
