### ISSUE TITLE
Add support for Addons API stability channels

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#18273]
### Description 

The Addons API now has a `channel` parameter which allows you to choose amongst the three stability channels: `alpha`, `beta` and `stable`.

There should be a master setting, managed via environment variable and install parameter to let you switch from `stable` (default) to the other API channels. Of course, changing channel means invalidating local cache for API requests.

Further documentation can be found in [this document](https://docs.google.com/document/d/1Pu4hQqX37JrKq2hnMsby2Q7k6yd8jjvoXmjQ6KK7lbs/edit?usp=sharing) (French, PS employees only).

---
Must be available in a development environment only!

**Specs available here:** https://github.com/PrestaShop/prestashop-specs/pull/169/files
**Platform Issue:** https://forge.prestashop.com/browse/PLFS-1327

**Comment by colinegin** [comment]
ping @LouiseBonnard is this issue ready to go to backlog ? 
There are 2 options :
- only tech improvement
- tech improvement + option in Advanced settings for the user

**Comment by LouiseBonnard** [comment]
It is ready now, thanks! In order to install the alpha or beta versions of Addons modules, a tech feature but still useful for the users who would like to test modules in advance, we should do **both the tech improvement** in the code **and the option in the Advanced Parameters > Administration section of the back office** - by a dropdown selector, for instance.

**Comment by Progi1984** [comment]
@Julievrz What is the wording for the option ?

**Comment by Progi1984** [comment]
@Julievrz What is the wording / domain for channels : 'alpha', 'beta', 'stable' ?

**Comment by Julievrz** [comment]
"Addons API stability channel" in Admin.Advparameters.Feature 

"Stable" in Admin.Advparameters.Feature
"Alpha" in Admin.Advparameters.Feature
"Beta" in Admin.Advparameters.Feature

A tooltip: "Choose a stability level for the modules downloaded from Addons Marketplace. All zips pushed on Addons are in stable state unless stated otherwise." located in Admin.Advparameters.Help

@Progi1984

**Comment by eternoendless** [comment]
> Choose a stability level for the modules on the Addons API

How about "Choose a stability level for the modules downloaded from Addons Marketplace"?

**Comment by Julievrz** [comment]
> > Choose a stability level for the modules on the Addons API
> 
> How about "Choose a stability level for the modules downloaded from Addons Marketplace"?

Following your explanation, it sounds good to me! 😊

**Comment by Progi1984** [comment]
Great @Julievrz. I applied this in my PR.

**Comment by Progi1984** [comment]
@PrestaShop/product-team The stability channel is not available for regular sellers on Addons Marketplace, only for PrestaShop modules. Should we put the option only in the development environment ?
