### ISSUE TITLE
TravisCI results are not reported

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#18287]
When I open `https://travis-ci.org/github/PrestaShop/PrestaShop` the following is shows:
![image](https://user-images.githubusercontent.com/2228672/77418110-bb353500-6dc6-11ea-99f2-e916c3cee08e.png)

Is this the reason why TravisCI results are not reported?

![image](https://user-images.githubusercontent.com/2228672/77418562-57f7d280-6dc7-11ea-8021-d39c3d5e25d5.png)

If yes, please change TravisCI settings/hooks here accordingly.

And if possible, increase (= pay more :) ) the max. count of parallel builds so developers have not to wait so long for the results.

**Comment by khouloudbelguith** [comment]
Ping @matks @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
We migrated from Travis.org (https://travis-ci.org/github/PrestaShop/PrestaShop) to Travis.com (https://travis-ci.com/github/PrestaShop/PrestaShop) recently, I dont remember exactly why 🤔maybe to benefit from new features and new plans

We had issues between the .org and the .com both trying to validate PRs for a while but it seems it only affected PRs created before the switch. New PRs are only being processed by the .com ... at least it seems like this. I noticed one or two issues, and indeed it can block the PR.

Please ping me on those PRs as it seems with some turn-it-off-turn-it-on moves we can reset the situation of the PR and make Travis correctly acknowledge the PR status.

**Comment by matks** [comment]
Also
- not sure about it, but it seems to me we are usually the free plan of Travis (as this is an open source project) so we cannot raise the max number of builds allowed, and we cannot move from "free open source plan" to "paying plan" because it's a public repository
- we already checked whether the number of builds we have is relevant (we compared with other open source projects) and found we are correct (neither the top nor the worse), the "feedback time" for Travis (... when it works 😛) is "average" for this kind of open source project

**Comment by mvorisek** [comment]
@matks After an hour the TravisCI statuses updated. Closing now.
