### ISSUE TITLE
Big problem about products with combinations, in all type of product list always are shown default combinations

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#18368]
Hi
there is a problem with product with combinations
all my customers that have products with combinations need to be present, in the product list, the possibility to show the combinations selected from some selection or from the search

example
https://www.lampadaribartalini.it/luce-illuminazione-vendita-online/124-lampade-a-batteria-per-esterni?q=Colore-Nero

here I select only product with color equal to black, there are only one product but if I add it to the cart, will be added the default combination, in this case the white one

the same if I search a product combination by its reference the shown data will be about the default combinazion

the prices, images, urls, references, will be blocked to the default combination
but if the advanced search (so using ps_facetedsearch module) or from the regular search, should show only what I want, because the visitors cannot understand this thing and can make errors to do cart and understand from product list the real images and prices

now you need to consider these situations and understand the real problems of shopkeepers and customers who browse an ecommerce site.

I search the product x with color black and large y, why do you show me products with images and prices of different combinations? I cannot go inside of each product to look these things for 100 products

I know that you will not fix this problem on 1.7, but for important features useful for each eshop should be taken into consideration quickly.

thanks

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/77914650-862d5480-7296-11ea-8cc1-422efd9e57fb.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello @maofree 

Thanks for the report.

The default template don't allow to add a product from the listing. We can't reproduce this bug.

Also there is an epic for improve faceted search : https://github.com/PrestaShop/PrestaShop/issues/15166
the last 3 in this epic is related to your bug.

**Comment by Maofree** [comment]
Hi
yes the add to cart button are no present in the classic theme (they should be present because it is a feature request from all eshop) but the problem is not restrict only to ps_facetedsearch module also for the search results

however those tickets are made 10 months ago
why as yet no corrections have been made to this problem?

**Comment by sarahdib** [comment]
@maofree,
>yes the add to cart button are no present in the classic theme (they should be present because it is a feature request from all eshop)

Thanks to create a new issue about this improvement, I will ping our Product Team.

>but the problem is not restrict only to ps_facetedsearch module also for the search results

We have the same behavior as ps_facetedsearch, the default template doesn't allow to add a product from the listing **search**, so we can't reproduce the issue.

Thanks!

**Comment by Maofree** [comment]
do you know why the tickets of #15166 are not fixed after 10 months from their creation?

**Comment by Jonatan949** [comment]
The problem of combinations product when someone add to cart continue?? I have the problem and i do not know how to solvent it

**Comment by Ycyconsulting** [comment]
I can now reproduce the search-result part of this report on a current PrestaShop 9 installation with a fully synthetic catalogue.

Environment:

- official `prestashop/prestashop:9.1.4-8.2` image (`prestashop/prestashop@sha256:14c74ff23340f335b30b02e58ed2cd1873154b5cbe45eb25dffe2c61d11ad596`)
- PrestaShop 9.1.4, PHP 8.2.29, MariaDB 10.11, Hummingbird
- the third-party search provider was disabled and the production cache was cleared before the native-search requests

Synthetic product 24 has these references:

- attribute 40: `NPBENCH-TEE-S`, Small/Blue, default combination
- attribute 41: `NPBENCH-TEE-S-RED`
- attribute 42: `NPBENCH-TEE-L-BLUE`
- attribute 43: `NPBENCH-TEE-L`, Large/Red, not the default

Steps and observation:

1. Search the exact combination reference with `/search?controller=search&s=NPBENCH-TEE-L`.
2. The expected product is returned, so combination references are present in the native index.
3. The result link is nevertheless the default Small/Blue combination: `/24-40-benchmark-combination-tee.html#/26-benchmark_size-small/28-benchmark_color-blue`.
4. The expected link for the queried reference is attribute 43, Large/Red: `/24-43-benchmark-combination-tee.html#/27-benchmark_size-large/29-benchmark_color-red`.

Disclosure: I maintain a commercial PrestaShop search module. The result above was captured with that module disabled; I am adding only the native PrestaShop reproduction because the original issue was closed as unable to reproduce. Could this current-version data be reconsidered here, or is there a more specific existing issue where it should be attached?
