### ISSUE TITLE
The tooltip of Delete/Edit product from cart ( order view page migrated) -  wrong behaviour

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/PrestaShop#18387]
#### Steps to reproduce

- Go to order view page (migrated ) for order with id=4 (`sell/orders/orders/4/view`).
- Add a product to existing cart. Now you have two products but there is  a problem of the tooltip when hovering on "delete icon" and "Edit" icon, it doesn't work for the newly added products.
![image](https://user-images.githubusercontent.com/23559010/77971279-2d85a800-72e6-11ea-9e79-8004fea45269.png)
 - Delete the newly added product, now you see a weird behaviour of the tooltip:

![image](https://user-images.githubusercontent.com/23559010/77971460-a84ec300-72e6-11ea-86ff-fd11c3c200d6.png)
 - play with page scroll, you will see the tooltip go to the top left of the screen:

![image](https://user-images.githubusercontent.com/23559010/77971536-d207ea00-72e6-11ea-87eb-f833e9a68c2c.png)

#### Expected behavior

The tooltip must appear for every product on cart when hovering on icon, in other words, for both producst (those who are loaded on first page load and those who are loaded via ajax).
When the delete icon is clicked, all tooltips must disapear till we hover on one of them.

 - Mozilla Firefox 74.0
- New installation of 1.7.7.0

**Comment by khouloudbelguith** [comment]
Hi @arouiadib,

Thanks for your report.
I manage to reproduce the issue with 1.7.7.x branch, the tooltip for "Delete" and "Edit" buttons are not displayed when we add a new product, it is OK when we refresh the page.
![image](https://user-images.githubusercontent.com/16067358/78033059-31590f00-7366-11ea-8e11-390e5fff344d.png)
![image](https://user-images.githubusercontent.com/16067358/78033129-4170ee80-7366-11ea-801e-01f22c6cbaed.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by NeOMakinG** [comment]
Fixed it, also there was another bug, when you was adding a product, tooltips was not added to this product until the reload of the page.

**Comment by arouiadib** [comment]
Yes you are right, @NeOMakinG , thank you very much for the PR.

**Comment by Progi1984** [comment]
Fixed by #18445
