### ISSUE TITLE
robots.txt blocks product pages because of prefix

### ISSUE THREAD

**Issue by rAthusFr** [PrestaShop/PrestaShop#18398]
The automatically generated _robots.txt_ file disallows files ending with keywords from pretty URLs. 

Eg my order page URL is `example.com/commande` so the _robots.txt_ file will have `Disallow: /*commande`, I have a product wich URL is `example.com/dolphon-m500-avec-telecommande.html`, this product is ignored by robots and metas are removed from Google because it ends with "commande". 

Why are the _robot.txt_ instructions so vague? There should be a way to secure sensible URLs without having this kind of conflict. 

Same occures one 1.6 and 1.7

**Comment by khouloudbelguith** [comment]
Hi @rAthusFr,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?
Checked with PS1.7.5.2, PS1.7.6.4 and the branch 1.7.7.x
We have in the `Robots.txt` file:

```
# Private pages
Disallow: /*?order=
Disallow: /*&order=
```

Thanks!

**Comment by rAthusFr** [comment]
It seems like it's actually an issue only on 1.6, as 1.7 seem to add the language, eg `Disallow: /*fr/commande`

**Comment by khouloudbelguith** [comment]
@rAthusFr, so it is ok in the 1.7?

Thanks!

**Comment by rAthusFr** [comment]
@khouloudbelguith yes it's ok on 1.7 as they forced the language into the _robot.txt_ conditions so there's no way an URL will end with `fr/commande.html` for example :) 

Issue only occures on 1.6.

**Comment by khouloudbelguith** [comment]
@rAthusFr,

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
