### ISSUE TITLE
Unable to save product information

### ISSUE THREAD

**Issue by raysiah** [PrestaShop/PrestaShop#18403]
#### Describe the bug

After filling up all product information such as Title, short description, descriptions, tag, and clicked on either save and stay button or save button. However the page either refreshes by itself but all the data entered are gone or it goes to the catalog/products page but the newly entered product cannot be found. 

#### Expected behavior

I expect all product information entered is save after clicking either save and stay or save button.

#### Steps to Reproduce

1. Go to 'Catalog/products'
2. Click on 'Add new product'
3. Fill in 'Name', 'short description', 'description'
4. Scroll down and click 'save and stay' or 'save' button
5. See error

**Screenshots**

All information entered are gone.

#### Additional information

* PrestaShop version: 1.6.0.14
* PHP version: 5.6.30

**Comment by khouloudbelguith** [comment]
Hi @raysiah,

I did not manage to reproduce the issue with PS1.7.6.4 and PS1.6.1.24.
https://drive.google.com/file/d/13iqSq12V1_5rCwK32aT3AYmXWpTqF8BJ/view?usp=sharing
https://drive.google.com/file/d/11Y83cwkJVKxWF5FJJDK3upc-hXwiy7m7/view?usp=sharing

As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!

**Comment by raysiah** [comment]
Thank you for your help, I would like to upgrade PS1.7.6.4, will it override the information from previous version PS1.6.0.14 store?
