### ISSUE TITLE
BO - Wrong total in order detail page when adding a product with modified price

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#18433]
#### Describe the bug

When adding a product with modified price to an order in BO, the "Total" price is wrong : It's the catalog price which is applied, instead of the modified price.

The "Products" total is OK.

#### Expected behavior

The Total should be with the modified price.

#### Steps to Reproduce

1. Go to FO, create an order.
2. Go to BO, to the created order, click on "Add a product" button
3. Select a product and change it's price
4. Add the product : The "Total" is wrong, when "Products" is right.

**Screenshots**

https://drive.google.com/file/d/1gH9Y2xsDCphQXkUmpKOIXBWYjjPIC0x4/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Robin-Fischer-PS,

It is OK with PS1.7.6.4.

Thanks!

**Comment by sowbiba** [comment]
> Hi @Robin-Fischer-PS,
> 
> It is OK with PS1.7.6.4.
> 
> Thanks!

Hello @khouloudbelguith 

It's not OK on PS1.7.6.4 on myside :thinking: 

https://drive.google.com/file/d/1dfHVxFFq9Uxq-Ce622_r_SmwW4RzU_Oy/view

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

Following steps provided by @Robin-Fischer-PS, it is ok in my side with PS1.7.6.4
I attached a screen record
https://drive.google.com/file/d/1B3-r5fhcq8WQ8fkLd_nG5fyImy9viZa9/view?usp=sharing

But I think, your screen record,
 is related to another issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/16937 and here: https://github.com/PrestaShop/PrestaShop/issues/12521 fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/17927.

Thanks!

**Comment by sowbiba** [comment]
Ok, I think I got it.

When the currency is the default one, when you edit prices, it's OK

When you use another currency, editing the prices (TTC or HT) makes the total wrong ;)

Thanks

**Comment by eternoendless** [comment]
Lowered severity according to discussion with @colinegin

**Comment by Progi1984** [comment]
Fixed by #18456
