### ISSUE TITLE
As a merchant when I navigate between combinations in product page, I want data to be automatically saved

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#18462]
#### Is your feature request related to a problem?

On legacy product page, when you navigate between combinations and then save, this could be a problem if there are error messages because we can't display them all.

#### Describe the solution you'd like

When we detect a click on "previous combination" or "next combination" button, we trigger the save. If it works, we display the next or previous combination and display a success message "**Settings successfully saved**" in _Admin.Notifications.Success_

If it fails, we display a warning message to user: "**Settings cannot be saved**" in _Admin.Notifications.Error_

**Please, use this type of notifications:**

![67474896-7eb5af80-f655-11e9-9df5-8e15bdcf73d0](https://user-images.githubusercontent.com/13449658/78377700-3b7e4600-75d0-11ea-9450-64a232174ff0.png)

![67475395-66926000-f656-11e9-8f55-d59e7a63b9a6](https://user-images.githubusercontent.com/13449658/78377722-433dea80-75d0-11ea-9335-7980f63f239c.png)

**Comment by marionf** [comment]
ping @LouiseBonnard for the wording

**Comment by LouiseBonnard** [comment]
I don't know it the word 'update' is relevant, you do not really update when you fill a field for the first time. So I'd rather write:

**1. for the success notification**

_Settings successfully saved_
in _Admin.Notifications.Success_

**2. for the error notification**

_Settings cannot be saved, update invalid fields to continue_
in _Admin.Notifications.Error_

or we can keep it short with _Settings cannot be saved_ in _Admin.Notifications.Error_ since invalid fields are highlighted just below.

**Comment by marionf** [comment]
Thank you @LouiseBonnard :)

**Comment by marionf** [comment]
We need to find another solution, better than an autosave @MatShir
