### ISSUE TITLE
Error loading Modules page

### ISSUE THREAD

**Issue by ninab20** [PrestaShop/PrestaShop#18471]
#### Describe the bug

Hello, I am getting the following error when trying to access my Modules page in the back office: 
Fatal error in module Module.php(1224) : eval()'d 
Redefinition of parameter $id_shop

I believe my hosting provider may have recently updated php to 7.0

#### Additional information

* PrestaShop version: 1.6.0.9
* PHP version: 7.0.33

**Comment by khouloudbelguith** [comment]
Hi @ninab20,

I did not manage to reproduce the issue with PS1.7.6.4 and PS1.6.1.24.
I attached a screen record
https://drive.google.com/file/d/1VgDkTHInEGBR_MAJ0GzTUYPhM46FPitD/view?usp=sharing
As you may already know, normal maintenance support for PrestaShop 1.6 ended in October 2018, which is now in [extended maintenance mode until June 30, 2019](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6).

During this period, and in order to ensure the stability of current 1.6 shops, only critical bugs and security fixes will be fixed, that’s why I close it.

Thanks!
