### ISSUE TITLE
Product page not updated after changing attributes - BC break

### ISSUE THREAD

**Issue by glo-www** [PrestaShop/PrestaShop#18509]
#### Describe the bug

Some parts of the product page must be updated in ajax after changing an attribute, since 1.7.6.3, a too specific selector was introduced in core.js file that break some themes.
This is not a bug per say, as the classic theme still works, but minor updates are not supposed to break third party themes.

#### Expected behavior

Attributes should updates depending on existing combinations.
ex, two combinations:

1. size: S, color black
2. size M, color white

selecting "S" should only display white color and selecting "M" should only display "black" color. This is not the case anymore with some themes who where working well before. 

#### Steps to Reproduce

Can be reproduced with "01 Oslo" theme for exemple.

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

**Comment by marionf** [comment]
Hello @glo-www 

> This is not a bug per say, as the classic theme still works, but minor updates are not supposed to break third party themes.

**1.7.6.3 is a patch version** and you are right, patches versions shouldn't break third party themes.

Thank you for your PR, I add this issue in the 1.7.6 project to fix it

**Comment by colinegin** [comment]
ping @SD1982 is it the problem you were talking about yesterday ?

**Comment by SD1982** [comment]
Hello @colinegin It seems that it is not the same problem because here it is a question of a behavior which is manifested only with certain third party theme. But I will try again with the theme indicated by @glo-www  to be sure because I had tested with the theme "01 bold" and it seems that this theme is not concerned by the problem.

**Comment by sarahdib** [comment]
@colinegin what should we do with this issue ?

**Comment by colinegin** [comment]
@NeOMakinG is taking care of it, I've just discussed with him

**Comment by NeOMakinG** [comment]
Fixed by #19800

I still added a selector so you'r not forced anymore to use the `.row` class

It doesn't totally resolve this issue but we don't want to restore the big bug we resolved on this patch, people using the "Classic" layout will be fine, others will need to add the new `.product-container` class !

**Comment by Progi1984** [comment]
Fixed by #19800
