### ISSUE TITLE
[gsitemap] - Check the presence of the image files on the server

### ISSUE THREAD

**Issue by cryptolikely** [PrestaShop/PrestaShop#18508]
When I use this option and trying to generate sitemap including links for images I get Error 500.

**Comment by marionf** [comment]
Hello,

I tried to reproduce the issue with gsitemap v4.1.0 & PrestaShop v1.7.6.4 but I could not reproduce your issue with the provided information as you can see in [this screenrecord](https://drive.google.com/file/d/12jQevRhwmA6ePu43x3ay4HKbvmp99wDm/view?usp=sharing).

Please give us more informations:
- Version of the module gsitemap
- Version of PrestaShop
- Version of PHP
- Debug mode report

You don't know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by cryptolikely** [comment]
@marionf marionf
Google Sitemap: v4.1.0 
Prestashop version 1.7.6.4
Version of PHP: 7.1.33
Information about store: https://www.dropbox.com/s/7gqd6yjtk8v83qp/Screenshot%202020-04-08%2012.28.56.png?dl=0
Video of error: https://www.dropbox.com/s/9d56dpu7kwl8nim/Screen%20Recording%202020-04-08%20at%2012.13.50%20PM.mov?dl=0
But u need to forward the video because it taking a while
Please check and tell me what info u need.
Thanks

**Comment by marionf** [comment]
Hello,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration as the issue is a timeout.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Best regards.
