### ISSUE TITLE
Can't change cms pages position

### ISSUE THREAD

**Issue by mcube27** [PrestaShop/PrestaShop#18512]
#### Describe the bug

On the BO->Design->Pages there is no way to change pages positions.

I expected to have the arrows or to be able to drag and drop, but nothing.

![image](https://user-images.githubusercontent.com/10844608/78747237-353df000-7969-11ea-815f-82cb23df53bb.png)

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.1.33

**Comment by marionf** [comment]
Hello @mcube27 

You have the possibility to change pages positions, please look [this screenrecord](https://drive.google.com/file/d/1PAEwJoqszRGAAqB4V1GOdCWGy0VNEeks/view?usp=sharing) & screenshot below.
Please note, to be able to change positions, you need to order by position ascending. Otherwise you are not able to change the position.

![capture d'écran_2503](https://user-images.githubusercontent.com/13449658/78765912-ed2ec580-7988-11ea-8c32-bff754cc3116.png)
