### ISSUE TITLE
Impossible to install the module vatnumber in Prestashop 1.7.6.4

### ISSUE THREAD

**Issue by uruk-hai-21** [PrestaShop/PrestaShop#18574]
#### Describe the bug

Impossibile install the module vatnumber in Prestashop 1.7.6.4

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.29

**Comment by florine2623** [comment]
Hi @ajejebrazorf01 ,
Which module is it exactly ? Is it from PrestaShop ?

Thanks

**Comment by uruk-hai-21** [comment]
Hi @florine2623 ,
yes it was possible to search the module in backend but now strangely not.

The module is this:
https://github.com/PrestaShop/vatnumber

**Comment by khouloudbelguith** [comment]
Hi @ajejebrazorf01,

The VATNumber native module in 1.7 is not released because it doesn't work.
It is https://github.com/PrestaShop/vatnumber
[vatnumber.zip](https://github.com/PrestaShop/PrestaShop/files/4462685/vatnumber.zip)
We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #9884
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #9884
