### ISSUE TITLE
I can' add my IP address maintenance

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#18594]
Hello
#### Describe the bug

I can't add my IP address to the maintenance page

![2020-04-11_20-07-13](https://user-images.githubusercontent.com/11594433/79057878-33707700-7c5e-11ea-8662-27eeb9fced20.gif)

20-04-12 01:28:40 | Access | 41.249.59.51 | 302 | POST /admin003hg/index.php/configure/advanced/performance/?_token=-n8g2zdBpE5Ad12aCM3V9BRvFCg1ZKcawfXlMJGrR74 HTTP/1.0 |   |   | 1.21 K | Apache SSL/TLS access
-- | -- | -- | -- | -- | -- | -- | -- | --
2020-04-12 01:30:26 | Access | 41.249.59.51 | 302 | POST /admin003hg/index.php/configure/shop/maintenance/?_token=-n8g2zdBpE5Ad12aCM3V9BRvFCg1ZKcawfXlMJGrR74 HTTP/1.0 |   |   | 1.19 K | Apache SSL/TLS access
2020-04-12 01:30:34 | Access | 41.249.59.51 | 302 | POST /admin003g/index.php/configure/shop/maintenance/?_token=-n8g2zdBpE5Ad12aCM3V9BRvFCg1ZKcawfXlMJGrR74 HTTP/1.0

* PrestaShop version: : 1.7.6.4
*Version du logiciel serveur : Apache
Version de PHP : 7.2.29
Limite de mémoire : 5128M
Temps maximal d'exécution : 9000
Taille max. pour envoi de fichiers : 200M

Regards

**Comment by khouloudbelguith** [comment]
Hi @go-sudo,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.4.
![image](https://user-images.githubusercontent.com/16067358/79432087-a023a280-7fcb-11ea-8c33-15dcfca98dc6.png)
I attached a screen record
https://drive.google.com/file/d/1LJLB3LeHF1XWvyGAyhF_xqaruuktAXZc/view?usp=sharing
We need to retrieve the PHP error log and the debug mode report in order to find out what's wrong.
Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by go-sudo** [comment]
Hi @khouloudbelguith 

it works now, thank you
