### ISSUE TITLE
Nav accessibility in theme default admin

### ISSUE THREAD

**Issue by ytilotti** [PrestaShop/PrestaShop#18604]
#### Describe the bug

The menu in the admin default theme is not accessible between 1023px and 1009px.

#### Expected behavior

Change the breakpoint on .js-mobile-menu icon

#### Steps to Reproduce

1. Go to the admin and log in
2. Change the size of your browser

**Comment by Klemart3D** [comment]
You're right but only if zoom is 70% or less (cf screenshot)
PS 1.7.6.4
Browser : Firefox 75.0

![screen](https://user-images.githubusercontent.com/7419525/79204656-307fad00-7e3d-11ea-9237-0accef2224a3.png)

**Comment by ytilotti** [comment]
I have the same problem in 100% @Klemart3D. Don't test in view adaptative.
PS 1.7.6.4
Browser : Firefox 75.0

![image](https://user-images.githubusercontent.com/5848945/79206780-2317f200-7e40-11ea-8a5a-d5e7ea907b97.png)

**Comment by matks** [comment]
Thank you for being accurate 😄

In order to help QA reproduce this, can you please share your total screen size ?

**Comment by Klemart3D** [comment]
Same with Chrome 80.0. Screen sizes are 1019 x 659px with zoom 100% (see my JS console) :

![chrom](https://user-images.githubusercontent.com/7419525/79208227-15fc0280-7e42-11ea-8464-b4556bee60c9.png)

**Comment by ytilotti** [comment]
The bug is present between 1023px and 1007px exaclty.

**Comment by florine2623** [comment]
Hi @yneet ,
I could not reproduce your issue. Here are the screenshots : 
1020 * 740 px - Firefox 75 :
![Capture d’écran 2020-04-16 à 15 17 14](https://user-images.githubusercontent.com/16019289/79461060-f1e12280-7ff5-11ea-98ea-ad18541f8adc.png)
@Klemart3D 
1019 * 659 px -  Chrome 80.0 : 
![Capture d’écran 2020-04-16 à 15 23 32](https://user-images.githubusercontent.com/16019289/79461428-7338b500-7ff6-11ea-906b-afda845886b2.png)

**Comment by Klemart3D** [comment]
@florine2623 : please do not use the responsive view of your browser (customers are not using it and render is not same as direct view, e.g. you don't have scrollbar), just resize browser with a window width **between 1023px and 1007px**, you should reproduce it.

By sample with your own demo website by reducing progressively your browser's window you should get this:

![no-menu-icon-on-demo](https://user-images.githubusercontent.com/7419525/79466401-d594b400-7ffc-11ea-827d-780c672eef46.png)

It's really problematic because some cash register screens are with a low resolution of 1020px and some sellers can't access to their orders in BO! This issue must be reconsidered as major.
