### ISSUE TITLE
Translations Backoffice 

### ISSUE THREAD

**Issue by andreact95** [PrestaShop/PrestaShop#18609]
#### Describe the bug

When i change some translation of the backoffice, apparently it saves, but the modify is not showed/saved/updated. Also when i search some words, it shows me the number of expressions but not where are there or where change it.

#### Steps to Reproduce

1. Go to  International > Translations 
2. Click on Backoffice and Italian
3. Search a word to translate
4. Change it, and modifies doesn't affect it
5. Clean the cache

**Screenshots**

![Cattura1](https://user-images.githubusercontent.com/63620984/79172672-a5c78f80-7df5-11ea-9d4e-1fc6a998da02.PNG)
![Cattura2](https://user-images.githubusercontent.com/63620984/79172674-a6602600-7df5-11ea-89d9-1126e8b48210.PNG)
![Cattura3](https://user-images.githubusercontent.com/63620984/79172675-a6f8bc80-7df5-11ea-8611-784d38f806aa.PNG)
![Result](https://user-images.githubusercontent.com/63620984/79172676-a6f8bc80-7df5-11ea-8653-7a077fa8d37f.PNG)

#### Additional information
Default Theme
* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @andreact95,

Thanks for your report.
>Also when i search some words, it shows me the number of expressions but not where are there or where change it.

In the next version 1.7.7.0, we have added an improvement, when item is not enabled hide it a little with opacity.
![image](https://user-images.githubusercontent.com/16067358/79433561-8f742c00-7fcd-11ea-914f-7f5ec34547a0.png)
Fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/12997 which reported here: https://github.com/PrestaShop/PrestaShop/issues/12888.

>When i change some translation of the backoffice, apparently it saves, but the modify is not showed/saved/updated

About the BO menu, we are aware of this issue, here is the PR: https://github.com/PrestaShop/PrestaShop/pull/18082 to fix the issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/9762, it is still in progress.


Thanks to check and feedback.
