### ISSUE TITLE
PNG thumbnails are not regenerated automatically, if missing

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#18769]
#### Bug description
If some thumbnails of product images are missing, Prestashop automatically generates them on the fly for JPG images, but not for PNG images. This can happen if regeneration goes wrong, during custom external imports from suppliers etc.

#### How to reproduce this bug

1. Go to your Prestashop image settings and set image format to "Use PNG if original file is PNG".
2. A) Make a product, name it "JPG Product", upload few images in JPG format.
2. B) Make a product, name it "PNG Product," upload few images in PNG format.
3. A) Find id_image of one JPG image, go to /img/p/X/X/X/X/X/ and delete all thumbnails. Do not delete XXXXX.jpg, filetype and index.php.
3. B) Find id_image of one PNG image, go to /img/p/X/X/X/X/X/ and delete all thumbnails. Do not delete XXXXX.jpg, filetype and index.php.
4. A) Open JPG Product, see all images correctly. Check /img/p/X/X/X/X/X/ folder and see all thumbnails go back.
4. B) Open PNG Product, images are gone and not regenerated.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @Hlavtox ,
I manage to reproduce the issue with PrestaShop version 1.7.6.5 exactly how you described it.
JPG images are regenerated -> OK
PNG images are not regenerated -> NOK

However on PS 1.7.5.2,  both PNG and JPG are not regenerated : 
JPG images are not regenerated -> NOK
PNG images are not regenerated -> NOK

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by lmeyer1** [comment]
This problem happens, because all images regardless of their type are saved with a `jpg` file extension, but in `ImageRetriever::getImage()`, the code responsible to regenerate the images, a file with an extension corresponding to it's type is searched for.
i.e. If the image is of type png, then it is saved as `123.jpg`, and the file `fileType` exists, `ImageRetriever::getImage()` is attempting to resize the inexistent file `123.png`
