### ISSUE TITLE
Error 404: Design>Positions

### ISSUE THREAD

**Issue by rodrideveloper** [PrestaShop/PrestaShop#18819]
Hello 
Error 404: Design>Positions

1. Go to 'Design>Positions'
2. Click on 'Positions'
3. See error

![image](https://user-images.githubusercontent.com/2502778/80280801-7443a380-86d4-11ea-9817-7a611c8c885c.png)

![image](https://user-images.githubusercontent.com/2502778/80280833-bff64d00-86d4-11ea-8774-f8b0357c7b17.png)
![image](https://user-images.githubusercontent.com/2502778/80280869-11064100-86d5-11ea-8b8f-6a50aa932a4c.png)

Server information Linux #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
Server software version: Apache
PHP version: 7.3.16
Memory limit: 128M
Max execution time: 30
Upload Max File size: 32M

**Comment by PierreRambaud** [comment]
Hi @iLChopper 

Unfortunately, we are not able to reproduce the issue.

We check your website, it looks like you have a conflicts with your woocommerce installation.
![image](https://user-images.githubusercontent.com/1462701/80360525-c4129e00-887f-11ea-8b63-ac7976654349.png)

It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.

Thank you!
