### ISSUE TITLE
Error id_product_attribute [ Product Attribute ]

### ISSUE THREAD

**Issue by hasanshaker** [PrestaShop/PrestaShop#18855]
#### Describe the bug

*ERROR* 	v1.7.5.0	2020/04/27 - 11:37:57: Can not retrieve the id_product_attribute at line 6310 in file classes/Product.php

#### Expected behavior

An error occurred while processing your request

#### Steps to Reproduce

1. Go to page product
2. Click on 'product attributs' EX: S, M, L, XL, XXL
3. See error

**Screenshots**

![Capture](https://user-images.githubusercontent.com/25296917/80407769-6e151900-88c6-11ea-9fad-971b1cd883d5.PNG)

#### Additional information

* PrestaShop version: 1.7.5.0
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello @hasanshaker 

This bug appear since the beginning or after install a new modules, template or upgrade ?

Thank you

**Comment by florine2623** [comment]
Hi @hasanshaker 
Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.
Thanks!

**Comment by pardebits** [comment]
Same error here:
Can not retrieve the id_product_attribute
at line 7532 in file classes/Product.php

I just create two combinations, I added to a product, and when I go to product page and select, show "undefined" alert, and error 500 in console.

Prestashop 1.7.8.5

EDIT: I found the error and was because a custom code in products.tpl in minuatures. Sorry! Thanks
