### ISSUE TITLE
error with full screen youtube video iframe

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#18872]
#### Describe the bug

when I attach a video to a product, if I have this option "Use HTMLPurifier library" activated, the html is corrected and the full screen does not work

the html of the video should be this, 
<iframe width = "560" height = "315" src = "https://www.youtube.com/video" frameborder = "0" allow = "accelerometer; autoplay; encrypted-media ; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe>

-
But HTMLPurifier library makes html like this, 
<iframe width = "560" height = "315" src = "https://www.youtube.com/video" frameborder = "0" allow = "accelerometer; autoplay; encrypted -media; gyroscope; picture-in-picture"></iframe>
this is missing allowfullscreen = "allowfullscreen"

#### Expected behavior

this should appear allowfullscreen = "allowfullscreen"

#### Steps to Reproduce

1. Go to insert a video in the description of an article
2. Click on FO, and go to see the video, try to activate fullscreen (HTMLPurifier library must be activate) (clean caché)
3. See error

**Screenshots**

https://prnt.sc/s7dkju
https://prnt.sc/s7djxg
https://imgur.com/a/o64kUtX

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.29

**Comment by florine2623** [comment]
Hi @alfonsolr09 ,
When you deactivate the HTML purifier Option it works correctly.
Thanks!

**Comment by alfonsolr09** [comment]
I know but, is it good to desactivate html purifier?

**Comment by florine2623** [comment]
Hi again @alfonsolr09 ,

I think that if HTMLPurifier blocks the use of a YouTube option, it's because HTML Purifier considers this option to be unsafe and disables it.
Indeed embedding external content is very often considered unsecure. You allow an external source to do whatever it wants on your page (including injecting viruses into your customer's page !).

Here are your options :
- you can choose 100% security and not use Youtube (or find another Youtube option that is safe to use)
- you can choose to consider this Youtube option "safe" and disable HTMLPurifier for it

Thanks @matks for the details !

**Comment by alfonsolr09** [comment]
How can I disable html purifier just for youtbe?

**Comment by florine2623** [comment]
It is not possible !

**Comment by alfonsolr09** [comment]
ok, i think its a bug but ok...

**Comment by florine2623** [comment]
Hi @alfonsolr09 ,
A request has been made to avoid your issue.
You can follow this issue https://github.com/PrestaShop/PrestaShop/issues/18917.
In the following versions of PS, you might be able to add iframes and disable htlmPurifier.
Thanks!
