### ISSUE TITLE
BO - Missing reset button in Theme & Logo

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#18893]
#### Describe the bug

The reset button is missing in theme & logo

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to Back office -> appearance -> theme & logo
2. Scroll down to the bottom 
3. See the missing button 

**Screenshots**
1.7.7.0
<img width="1276" alt="Capture d’écran 2020-04-29 à 14 31 48" src="https://user-images.githubusercontent.com/3034677/80596544-d5e27580-8a26-11ea-83b7-3562f5b8d6a6.png">

1.7.6.5
<img width="1211" alt="Capture d’écran 2020-04-29 à 14 31 58" src="https://user-images.githubusercontent.com/3034677/80596547-d975fc80-8a26-11ea-8168-26474d84c82d.png">

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.1

**Comment by Progi1984** [comment]
Fixed by #19032

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

This issue is reproduced in only one shop in my case 1770beta2build1 and ps_themecusto v1.2.0
![image](https://user-images.githubusercontent.com/16067358/91326070-32328780-e7c4-11ea-8bb1-5859aa3a7ae0.png)
Also reproduced by @sarahdib and @SD1982 
Here's my configuration
![image](https://user-images.githubusercontent.com/16067358/91326287-732a9c00-e7c4-11ea-9bf2-4ba121a92ed5.png)

I will re-open the issue.

Thanks!

**Comment by atomiix** [comment]
@khouloudbelguith I think it's the normal behavior when not in debugMode, you can see the specification of this page in [this file](https://docs.google.com/document/d/1krTRDT40MOpAxePGNap89hpAXFTdR2dIe2t3CQ0e1Uc/).

**Comment by khouloudbelguith** [comment]
Thanks a lot, @atomiix :wink:
