### ISSUE TITLE
Basket with products no longer existing

### ISSUE THREAD

**Issue by jerome77oak** [PrestaShop/PrestaShop#18995]
Hello,

I expose you the concern which I meet.

A customer adds products to her basket but does not finalize her order. His basket and therefore keep as is by the site.

The trader removes (puts offline) one of the products in this said basket because she no longer manufactures it.

The customer returns to her basket a few days later, finalizes her order ... the product removed and still ordered !!

(Precision, the trader does not use the stock system because she manufactures her products as she goes along)

How to ensure that the passage from the basket to the order, there is a control of the existence of the product? (parameter ?, module?)

Thank you in advance for your help.

I am told that this bug did not exist before version 1.7?

Jerome

#### Additional information

* PrestaShop version: 1.7.1.2
* PHP version: 7.2

**Comment by TristanLDD** [comment]
Hi @jerome77oak, thanks for your report. 

Unfortunately we could not reproduce your bug, on both 1.6 and 1.7 versions the passage from the basket to the order shows an error message when one or several products are set offline in between, and the "Proceed to checkout" button is disabled. 

Here on 1.7: 
<img width="1180" alt="Capture d’écran 2020-05-06 à 10 54 32" src="https://user-images.githubusercontent.com/27484094/81158174-032fa600-8f88-11ea-8aed-c9850d39917a.png">

 And 1.6:
<img width="1229" alt="Capture d’écran 2020-05-06 à 10 45 09" src="https://user-images.githubusercontent.com/27484094/81158260-16427600-8f88-11ea-9ad0-d9835c587e42.png">


It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
Thank you!
