### ISSUE TITLE
Cart synchronization

### ISSUE THREAD

**Issue by baldemir** [PrestaShop/PrestaShop#19035]
#### Describe the bug

When user signs in different devices, cart contents are not synchronized between each other. It causes problems in payment modules.

#### Expected behavior

When user signs in and adds products to cart in one browser, if they go sign in another browser they should see the existing products in cart.

#### Steps to Reproduce

1. Sign in to your account
2. Add items to basket
3. Open another browser
4. Sign in to same account
5. See empty basket

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by atomiix** [comment]
Hi @baldemir,

Thanks for your contribution.

@PrestaShop/prestashop-product-team what do you think?

**Comment by LouiseBonnard** [comment]
I can reproduce this issue, thanks @baldemir! I agree with you, it'd be great that at least signed in customers could keep their cart when switching devices.

**Comment by marionf** [comment]
Guys, there is already an option to do that

![capture d'écran_2596](https://user-images.githubusercontent.com/13449658/81548601-d1e71980-937d-11ea-9648-250890cbf4d9.png)

**Comment by baldemir** [comment]
@marionf thank you for taking time to check it. But what i mean by synchronization is not synchronizing the carts on login. Assume you have two sessions with same account on your mobile and on your desktop. When you add item to cart on mobile, I'm expecting to see it on desktop too. It is what happens on popular e-commerce websites. But I don't see this behaviour on PrestaShop.

You are right about reproducing error flow though. I didn't explain the already logged in flow.

**Comment by marionf** [comment]
@baldemir It works if you enable the option to redisplay cart at login

1. Enable the option redisplay cart at login
2. Login to your account in a browser
3. Login to your account in another browser or in private navigation
4. Add a product to your cart in browser 1
5. Refresh the page on browser 2
6. The product added to the cart in browser 1 is also in your cart in browser 2

See the screenrecord below: https://drive.google.com/file/d/1MFHo97yYGN67favO4C_c5augP1ZgO9gw/view?usp=sharing

**Comment by baldemir** [comment]
When I try with a new user everything worked as expected. I think in my first try it didn't work because of existing carts before changing settings. Thank you very much @marionf for your time!

**Comment by ghost** [comment]
However, there is a problem that I just can't solve, even though "display cart on login" is set. Let's assume the case in which the customer is logged in on two different devices.
An order is placed from a device. At this point the cart returns to zero on both devices.
If I now add a product to Google Chrome, and update the Mozilla page (for example), I won't see the Google Chrome cart on Mozilla. I would only see it if I logged out and then logged in again, which is extremely inconvenient.
If I even add a product on Mozilla, two different carts are created for the customer.
How can this be remedied and there is only one cart? Without having to log out and then log in?
Thank you very much!

**Comment by MatShir** [comment]
A browser refresh or customer action (product navigation for example) doesn't update the cart?

**Comment by ghost** [comment]
Unfortunately not.
Prestashop's "Display cart on login" function means that when you log in, the last available cart is loaded.
But if you finish an order, you remain logged into your browser but you have no active carts.
So if you were already logged in on multiple devices and you start adding products both in one browser and in another, you create 2 different shopping carts.
What I would like is for the carts to be synchronized, as happens in the main online ecommerce.

**Comment by MatShir** [comment]
The idea is to resync the cart after placing an order on device 1 and having other items on device 2, so that the product from device 2 is also included in device 1. Am I right?

**Comment by ghost** [comment]
I don't know, I can't understand well. I'll try to summarize in points:
1. I log in from device 1. Just logging in creates a €0 cart.
2. I add products for €20 on device 1. I therefore have a cart of €20.
3. I log in from device 2 and correctly see the €20 cart. This is because the "Display cart on login" option is enabled correctly.
4. I complete the order (from device 1 or 2, it doesn't matter).
5. Upon completing the order, the cart no longer exists correctly and therefore I cannot see it either from device 1 or 2.
6. Now I am already logged in from both devices.
7. I add a product to device 1
8. In device 2 if I refresh the page I have an empty cart and I don't see what I added from device 1.
9. I add products from device 2.
10. Now I have two separate carts, one on device 1 and one on device 2; I can also see the two distinct carts from the Prestashop dashboard.

What I would like is that the cart is not only loaded upon login, but that it is always synchronized between one device and another.
In practice, each user should be able to have only one cart at a time.
This is because users normally remain logged in on multiple devices, they do not log out after each purchase.
I hope I explained myself correctly.

**Comment by MatShir** [comment]
I see now. I'm sorry to ask so much of you, but I think it's worth making a new issue. This one's closed, so it's not worth digging up.

**Comment by jaroslavstreit** [comment]
Do you have new issue number?

**Comment by MatShir** [comment]
https://github.com/PrestaShop/PrestaShop/discussions/33918 no need @jaroslavstreit
