### ISSUE TITLE
Core/Module js files are directly accessing theme classes

### ISSUE THREAD

**Issue by mrusmanali** [PrestaShop/PrestaShop#19031]
#### Html classes being accessed by core and module .js files

I have recently started working on Prestashop to develop a solution for my client and I have realized that core/module .js files are referencing HTML classes and modifying the DOM. What if someone doesn't want to use those classes, also this clearly breaks the abstraction rules, and the developer has to look into core code to figure out how things are working.

#### Core js as lib with customizations

It would be nice to have the core .js to be included as lib having options, methods, events init and destroy features, this will give theme developers flexibility to init core-js and use it as per their needs

**Comment by florine2623** [comment]
Hi @mrusmanali ,
Thanks for the recommandation!
Please stay tuned, I will ping our developer team.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

What do you thing about @mrusmanali 's idea ?

Thanks!

**Comment by PierreRambaud** [comment]
Good idea, I approve but need more feedback from the team

**Comment by NeOMakinG** [comment]
Are you talking about BO or FO or both ? (since FO has a core bundle)

This looks a good idea to be honest, for selectors it would be an array of selectors not bundled in the core lib, but passed as an argument to the core init function, so you can override these selectors easily. I also seen that a lot of things were not really respecting good practices regarding DOM changes events, there are a lot of events missing in order to stick to the actual behavior as an external user/dev, what I do in order to not modify the core is that I use a MutationObserver, but this is so tricky.

By the way, this method will introduce a lot of breaking changes and a lot of refacto, I think it's not doable inside a minor version, that should be spoken for a major one.

Waiting for team advices!

**Comment by mrusmanali** [comment]
@NeOMakinG I didn't get a chance to look at BO javascript code, but the same practices should be followed. I guess there are many technical challenges to achieve such functionality since people can install 3rd party modules that can bring their own styles and scripts.

Anyways since Prestashop provides theme designers to override template files, so it should do the same with javascript and styles

**Comment by NeOMakinG** [comment]
@mrusmanali 

Do you mind writing a complete ADR about this ? I think a customer is absolutely aimed by this practice and maybe that would be way more complete if a customer is at the base, that would be so lovely!

https://github.com/PrestaShop/ADR

I can still work with you on it without any problems!

**Comment by hibatallahAouadni** [comment]
Hello @mrusmanali ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
