### ISSUE TITLE
Modules & Services

### ISSUE THREAD

**Issue by JayWilliams74** [PrestaShop/PrestaShop#19171]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

When I click on the menu option for Modules & Services within my Admin menu I would expect that it gives me a list of all the Modules and Services that I have to customise my store.

This is what it did up to me trying to install a number of free modules that I downloaded from the Prestashop Marketplace last week.
Now it is not working and issuing an error message.

#### Steps to Reproduce

1. Go to Menu Option
2. Click on Modules & Services
3. Scroll down to Modules & Services and Select
4. See error message.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.6.24
* PHP version: 7.2

![https___euphoric-nights uk_store_store_admin_index php_controller=AdminModules token=a2999e9a49396f87004237b62aac6daa - Google Chrome 16_05_2020 22_04_46](https://user-images.githubusercontent.com/65467851/82130218-53e1a300-97c1-11ea-9a9a-cf6fc81a782d.png)

I have also been in contact with customer services and they told me to report the issue to the Module developer, this I have done as I think that the module that is the issue was Net Reviews V7.9.0 however I have not had any response and I am unable to customise any of the site that I am working on.

**Comment by Matt75** [comment]
You have a module on your server not compatible with your PrestaShop version.

With PrestaShop 1.6, module can’t use namespace in main `Module` class due to an [eval](https://github.com/PrestaShop/PrestaShop-1.6/blob/21284d2ff48245cdcb343f41e545d8b629cec4bb/classes/module/Module.php), `eval` cannot read php file who use a `use` instruction.

In class `Module` we have to use Fully qualified namespaces instead.

So you have to search on your FTP, a module with a `use` inside his main PHP file and remove it to restore your Modules & Services page.

**Comment by JayWilliams74** [comment]
Hi Matt

I did what you suggested and looked through each of the modules and found that It was potentially Netreview & Mailchimp that were at fault. As soon as I deleted both folders I have access to Modules again.

Many Thanks!

**Comment by karensenna** [comment]
k

**Comment by JayWilliams74** [comment]
Thank you for the resolve..
Issue Closed
