### ISSUE TITLE
Swahili language is not available in the back office

### ISSUE THREAD

**Issue by nenowasaleh** [PrestaShop/PrestaShop#19193]
#### Describe the bug

Hi,
I've translated into Swahili language the strings of PrestaShop and I've uploaded it
Unfortunately when I try to add it to my installed PrestaShop I receive the following message:
"Sorry this language is not available".

#### Expected behavior

I expect to be able to download the just translated language.

#### Steps to Reproduce

* PrestaShop version: 1.7.6
* PHP version: 7

**Comment by LouiseBonnard** [comment]
Hi @nenowasaleh, thanks for your issue (and Swahili translation)! I can reproduce this bug, the Swahili language is part of both Kenya and Tanzania localization packs but I cannot succeed in adding it via the International > Translations section of the back office.

When I import the Kenya localization pack, I get a success message but I cannot find the Swahili in the Languages listing. When I import the Tanzania localization pack, I get the following error message.

![Capture d’écran 2020-05-20 à 09 27 01](https://user-images.githubusercontent.com/32565890/82417889-82d76d80-9a7c-11ea-8880-3519f1a7e067.png)

I guess the bug comes from the fact that the Swahili is in [the legacy-to-standard-locales file](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/legacy-to-standard-locales.json) as well as in [the available_languages file](https://github.com/PrestaShop/TranslationFiles/blob/master/1.7/translations/1.7.7/available_languages.json) but not in the [all_languages.json file](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/all_languages.json).

**Comment by nenowasaleh** [comment]
Hi, LouiseBonnard,
thank for you reply.
So what can I do?
I'm translating PrestaShop but I'm not able to see this translation in my installed PrestaShop 1.7.6
Greetings

**Comment by LouiseBonnard** [comment]
Dear @nenowasaleh, thanks for your quick reply! You might need to add the language to the last file mentioned. But let's wait for a dev to answer before, just to make sure it is the only step missing to be able to retrieve this language in PrestaShop.

@PrestaShop/prestashop-core-developers, can you confirm that the Swahili language needs to be added to _all_languages.json_ file?

**Comment by Progi1984** [comment]
@LouiseBonnard A documentation page exist : [https://devdocs.prestashop.com/1.7/development/internationalization/activate-a-language-in-prestashop/#update-required-json-configuration-files-in-the-prestashop-project](https://devdocs.prestashop.com/1.7/development/internationalization/activate-a-language-in-prestashop/). And yes, you need ;)

**Comment by nenowasaleh** [comment]
Hi, @Progi1984 and @LouiseBonnard 
thank you very much.
I 've modified the json configuration.
But I didn't understand what to do about i18n.prestashop.com ;((

I appreciate your help

**Comment by Progi1984** [comment]
Relative PR on core & LocalizationFiles : https://github.com/PrestaShop/LocalizationFiles/pull/2 :heavy_check_mark:
