### ISSUE TITLE
"Root Categorie": SEO Preview in EDIT Menu not working, BO Categorie Page misses content after saving "Root Categorie"

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#19198]
#### Describe the bug

Go for your BO - Menu - Sell - Catalog - Catogries and click EDIT for the "root Categorie" (displayed above the Categorie List).
The SEO Preview is not working.

Also, when you save the settings, you get redirected to the Categorie List again, but he does not load the "root categorie" above the list. Also, it seems quite laggy if smth is changed there, as the sites is build really slow afterwards.

If you enter the EDIT Feature for the root categorie again, you still see no proper SEO Preview of the data that you saved before.

#### Expected behavior

SEO Preview should work as expected.

#### Steps to Reproduce

- Go for your BO - Menu - Sell - Catalog - Catogries and click EDIT for the "root Categorie" (displayed above the Categorie List).
- Change whatever you like, no live preview.
- Save, and see the Categorie Page is building up slow, and misses the "Root Categorie" of before.

* PrestaShop version: 1.7.6.5 minimum
* PHP version: 7.1.3 and 7.2.3 and higher

**Comment by sarahdib** [comment]
Hello @6xthFNGR 

This is the issue  ?
<img width="1221" alt="Capture d’écran 2020-05-19 à 12 37 27" src="https://user-images.githubusercontent.com/3034677/82316760-937cda80-99cd-11ea-9bc8-0a666b3a7506.png">


Thank you :)

**Comment by pitkz** [comment]
Seems like you could reproduce it...

**Comment by pitkz** [comment]
![Screenshot from 2020-05-19 12-38-00](https://user-images.githubusercontent.com/64662500/82317127-1aca4e00-99ce-11ea-9e37-1c5648760ec3.png)

After Saving, the Categorie is missing

![Screenshot from 2020-05-19 12-37-55](https://user-images.githubusercontent.com/64662500/82317122-19008a80-99ce-11ea-9cba-70c2b1dd1ccc.png)

I just noticed now: He goes for "root" after saving, so he is displaying it properly, it is just confusing because you can only go for this root directory by the "Edit and Save" way I discribed. If you select Categories in the Menu, you are not in Root but already within the first categorie.
That confusion is no bug, but maybe could be displayed better.

**Comment by sarahdib** [comment]
@PrestaShop/prestashop-product-team could you check this ? A better way to display that we are in Root category ?

**Comment by colinegin** [comment]
It seems that there are 2 bugs here :
- SEO preview is not working for the home category
- display issue when saving the home category - there are several options IMO when we save the root category : 
1/ remove the banner with the breadcrumb 
or
2/ show the same breadcrumb as when the user is on the category level 1 listing 
or
3/ show the category level 1 listing (same as when you click on Categories in the BO menu)

What do you think @TristanLDD @prestascott ?

**Comment by prestascott** [comment]
Hi everyone, 

Currently the breadcrumb seems separated from its category because of 2 different blocks. 
IMO, we shouldn’t remove the banner with the breadcrumb but go for @colinegin  second proposition. Breadcrumb should appear above the list so the user knows where he is. First thing to do is to put the breadcrumb and the list together in the same block to have a better reading. 

Wdyt?

**Comment by khouloudbelguith** [comment]
Hi @prestascott,

About 
>SEO preview is not working for the home category

It is reported here:
https://github.com/PrestaShop/PrestaShop/issues/15420

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @6xthFNGR 

About the first issue SEO preview, as @khouloudbelguith mentioned above is a duplicate of #15420 
About the second issue breadcrumb missing after saving categories, I didn't manage to reproduce with PS1.7.7.1.

Could you please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @6xthFNGR 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15420. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #15420
