### ISSUE TITLE
Return tab on order BO page has no "tracking number" + wrong wording

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#19200]
#### Describe the bug

On the "merchandise return" tab on an order, the label of tracking number is just the "return ID"

It should be : 
* Column label: Return number
* Value: #RE000001 (if prefix is set to RE)

An improvement: have a link to edit the "return" (there is a link from a return to an order but not in the other way)

**Screenshots**

![image](https://user-images.githubusercontent.com/52157233/82303667-8f47c180-99bb-11ea-8e2c-fe09542572eb.png)

#### Describe how it should work

**Specifications**

https://github.com/PrestaShop/prestashop-specs/pull/196/files

#### Additional information

* PrestaShop version: 1.7.6.5 1.7.7.0
* PHP version: N/A

+ "Carrier" in the table is not the good wording. It should be replaced by "Status" (see screenshot below)

BEFORE
![image](https://user-images.githubusercontent.com/70583503/112277913-89c5a280-8c82-11eb-88ec-addf3e182360.png)
AFTER
![image](https://user-images.githubusercontent.com/70583503/112277261-dc528f00-8c81-11eb-987f-871c00230a8b.png)

**Comment by LouiseBonnard** [comment]
Hi again @clotaire202, thanks for opening this issue, I managed to reproduce it. I'll let the product team know about it so that it can be specified and rewrote if need be.

@MatShir, do you think it could be part of the #17598 EPIC?

**Comment by Junebyun** [comment]
For this issue, there are 2 possible scenarios:

1) Keep the value 1 (which corresponds to the ID):

- Column label: ID

- Value: 1
![InkedScenario 1_LI](https://user-images.githubusercontent.com/64894223/83534171-d02df300-a4f0-11ea-942f-1bc1351d168a.jpg)

2) Keep the reference number: 

- Column label: return number

- Value: #RE000001
![InkedScenario 2_LI](https://user-images.githubusercontent.com/64894223/83534224-dcb24b80-a4f0-11ea-86b7-2760c76272a4.jpg)

Personally, I prefer the second scenario. I think it will be easier for the merchant to have the return reference number instead of the ID!

Wdyt @MatShir?

**Comment by clotairer** [comment]
@Junebyun more over in the front office, the customer has #RE000001. If the merchand want to contact the customer about a return, it's easier to use the same number.

**Comment by MatShir** [comment]
Thanks, @clotaire202 for the request. Indeed, it seems more logical to have the return number. It will prioritize with the other issue.

**Comment by Junebyun** [comment]
Slight modification: 
- Column label: Number

- Value: #RE000001 (return reference number)

I changed the label of the column to _Number_ because it is in harmony with the _Documents_ tab in the BO.
![image](https://user-images.githubusercontent.com/64894223/83625170-cdd0a500-a593-11ea-982a-e8ba3235e670.png)

**Comment by Junebyun** [comment]
Slight modification: 
- Column label: Number

- Value: #RE000001 (return reference number)

I changed the label of the column to _Number_ because it is in harmony with the _Documents_ tab in the BO.
![image](https://user-images.githubusercontent.com/64894223/83625170-cdd0a500-a593-11ea-982a-e8ba3235e670.png)

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team I can see that this improvement is approved from **`PM`** and **`Wording`**, so shall we change its status to **`To Do`** ?

**Comment by khouloudbelguith** [comment]
Hi @PrestaShop/product-team, @Julievrz,

The wording of the "Order return status" is NOK also.
![image](https://user-images.githubusercontent.com/16067358/112174982-23477280-8bf7-11eb-87b5-32fdd1e6bd5d.png)

Thank you!

**Comment by Julievrz** [comment]
Oh wow, you're right @khouloudbelguith thanks! Should I open a dedicated issue?

**Comment by khouloudbelguith** [comment]
Hi @Julievrz,

Yes, we can create a new issue or edit this issue (first comment + title) to fix two problems in the same page & the same block.

Thank you!

**Comment by Julievrz** [comment]
@khouloudbelguith @hibatallahAouadni I modified the first comment and the title. Thank you :)
