### ISSUE TITLE
ps_emailsubscription integration with mailchimp module

### ISSUE THREAD

**Issue by Gazi96** [PrestaShop/PrestaShop#19240]
Hello,

I would like to suggest, that ps_emailsubscription should be integrated with mailchimp. It will be great feature, because now emails from prestashop goes to mailchimp audience, but from this module not. 
I know, that I can export and import emails with this module, but I have emails automation with 
a discount code and these emails should be send to client immediately.

Kind regards
RG

**Comment by matks** [comment]
> Hello,
> 
> I would like to suggest, that ps_emailsubscription should be integrated with mailchimp. It will be great feature, because now emails from prestashop goes to mailchimp audience, but from this module not.
> I know, that I can export and import emails with this module, but I have emails automation with
> a discount code and these emails should be send to client immediately.
> 
> Kind regards
> RG

There is already multiple Mailchimp modules available on Addons marketplace 😉 
https://addons.prestashop.com/en/search?id_category=0&search_query=mailchimp

We cannot release a free module connected to Mailchimp because it would not be fair for the people selling the modules now on marketplace (between a free module and a module you need to buy, people would immediately use the free) and they are partners 😊

**Comment by LouiseBonnard** [comment]
Hi @Gazi96, thanks a lot for your improvement idea! Since no change is required here, I close this issue. Feel free to reopen it if need be. :-)

**Comment by Gazi96** [comment]
I know, that there are a lot of mailchimp modules, I use one of these, but
I would like to suggest, that ps_emailsubscription should be integrated
with mailchimp modules, because now only emails from prestashop goes to
mailchimp audience.

śr., 20 maj 2020 o 18:30 LouiseBonnard <notifications@github.com>
napisał(a):

**Comment by theodiablo** [comment]
I totally agree with Gazi96, this is the kind of features which makes people's life easier (and cheaper)

To have a platform which can handle natively those simple tasks (without having to be charged 50€ for every single little extra feature) makes it way more attractive. Especially because many people are using Mailchimp!

**Comment by theodiablo** [comment]
@Gazi96 what did you do in the end to fix this?
