### ISSUE TITLE
Product page - tech task - Warehouse management in Product page ? Explore

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#19266]
Related to https://github.com/PrestaShop/PrestaShop/issues/19259

I found in current Product page some code related to warehouse management, which is a feature removed from PrestaShop during 1.6 -> 1.7 rework.

We must analyze this code to confirm that it is dead code and can be removed.

**Comment by zuk3975** [comment]
this is what I've got:
1. There is WarehouseDataProvider in ProductController which gets the warehouses if `PS_ADVANCED_STOCK_MANAGEMENT` is truthy. (which by default is FALSE)
___
2. There is a twig template with a warehouse combination form `form_warehouse_combination.html.twig` which is rendered inside `form_shipping.html.twig` on following conditions
```php
{% if warehouses|length > 0 %}
...
//asm_globally_activated is the PS_ADVANCED_STOCK_MANAGEMENT config.
//isNotVirtual checks if product is virtual (you dont need warehouse for virtual product)
//isChecked is basically advancedStockManagement for current product, which is taken from quantity form
    {% if asm_globally_activated and isNotVirtual and isChecked %}
      {{ include('@PrestaShop/Admin:Product/ProductPage/Forms/form_warehouse_combination.html.twig', { 'warehouses': warehouses, 'form': form }) }}
    {% endif %}
```
___
So to see the warehouse combinations form for product with combinations in shipping block you would need to manually create database records for warehouses, change `PS_ADVANCED_STOCK_MANAGEMENT` settings and might even need to change the syntax in the template (because current syntax throws rendering error at least for me) see bellow:

from this
 ```
  {{ include('@PrestaShop/Admin:Product/ProductPage/Forms/form_warehouse_combination.html.twig', { 'warehouses': warehouses, 'form': form }) }}
```
to this 
```
{{ include('@PrestaShop/Admin/Product/ProductPage/Forms/form_warehouse_combination.html.twig', { 'warehouses': warehouses, 'form': form }) }}
```
___
3. There is no way to create warehouses or change `PS_ADVANCED_STOCK_MANAGEMENT` (ASM) configuration settings via UI. (as you said it was removed in 1.7)

4. In `Quantity` tab there is a checkbox for "advanced stock management" (appears only if globall ASM is on). It seems to be related with warehouses and the initial purpose might have been to enable/disable the ASM for current product, BUT it doesn't seem to work (if you check that option an ajax request fails with error and nothing happens), so I wonder if it suppose to work, or its forgotten too? :man_shrugging: 
![Screenshot from 2020-05-23 14-53-01](https://user-images.githubusercontent.com/31609858/82730027-669a3180-9d05-11ea-9fc7-08d2c403a2ba.png)
@MatShir maybe you know anything about it? 

5. Finally, there doesn't seem to be any specific hooks associated with warehouses that would be called in product form.

**Overall, it seems, that it is safe to forget this feature when migrating the product page**, tho Im not sure about nr. 4

**Comment by matks** [comment]
## Status update

We must check PrestaShop Advanced Stock Management modules to check whether they rely on this dead code and the SQL structure below to work. If they dont, well, it seems we can remove this.

Warning: warehouses and advanced stock management are related but not the same thing.

**Comment by matks** [comment]
Code related to adv stock management is being removed in PS 8.0.0 in PR https://github.com/PrestaShop/PrestaShop/pull/25621
