### ISSUE TITLE
reset Password issue when email address have capital letters

### ISSUE THREAD

**Issue by simulbeni** [PrestaShop/PrestaShop#19294]
I came across a very strange issue that customers receving empty emails like this screenshot.

Email Id was : Tre*******@P****P***B*****C****.com
![Annotation 2020-05-25 132408](https://user-images.githubusercontent.com/437314/82791328-295fac00-9e8b-11ea-8edf-0ac6261109b5.jpg)

We need to save all emails in small caps.

**Comment by sarahdib** [comment]
Hello @beniwal 

Thank for reporting this issue.

Could you indicate which prestashop version you found this in order to try to reproduce ? 

Thank you

**Comment by simulbeni** [comment]
my version is 1.7.6.2, 1.7.6.4

Its saving emails with captial letters but then sending empty emails without replacing template variables.

Really serious issue as at least 5% of customers having this type of email letters and all of them get these garbage emails.

**Comment by florine2623** [comment]
Hi @beniwal ,
I managed to reproduce your issue with PS 1.7.6.5. On PS 1.7.7 beta this issue is solved.
So I would advise you to wait for the release of PS 1.7.7 stable and upgrade.
Here's the release article of PS 1.7.7 Beta :
https://build.prestashop.com/news/prestashop-1-7-7-0-beta-release/

_On 1.7.6.5, with capital letters on email address :_
![Capture d’écran 2020-05-28 à 16 05 36](https://user-images.githubusercontent.com/16019289/83151664-266bf200-a0fd-11ea-8a01-41a575dbcd79.png)
_On 1.7.6.5, with lowercase letters on email address :_
![Capture d’écran 2020-05-28 à 16 05 42](https://user-images.githubusercontent.com/16019289/83151766-48fe0b00-a0fd-11ea-9683-5c9c2d4c7fc4.png)

_On PS 1.7.7 beta with/without capital letters :_
![Capture d’écran 2020-05-28 à 16 07 43](https://user-images.githubusercontent.com/16019289/83151855-63d07f80-a0fd-11ea-90f3-74069f1ae732.png)

**Comment by Azeus1980** [comment]
hi @florine2623 
Thanks for your reply.
I can't make any update on my prestashop 1.7.6.1, do you have the patch for this issue only ?
It's a real problem for my customer because he has all his customer's email in caps...
Thank you
