### ISSUE TITLE
Linklist - Add multistore shop association block

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19296]
As a merchant, I want to be able to select one or many stores when I create or edit a block, so that I can display it on the store(s) of my choice

When a new block is added, the merchant can choose to which shop(s) the block will be associated thanks to the “shop association block” component.
The specifications of this block are described in the [multistore general specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#shop-association-block)

Specs for the module: https://github.com/PrestaShop/prestashop-specs/blob/master/modules/ps_linklist.md

**Comment by Nachopresta** [comment]
Hi, I'm new in github and I don't really  know yet how github works, sorry for my daring... I'm suffering a problem with my prestashop 1.7 multistore which I have identified here, the linklist module doesn't work in multistore environment. After working for more than 2 months updating my prestashop 1.6 to 1.7, when I was about to finish after many many problems I have suffered this new problem which is really serious for me because my shops are now in maintenance mode, I can't open them with the same cms blocks showing in the frontoffice of both shops since one is a B2B shop and the other one is a B2C shop. This is why I kindly ask you:
-Is there a fast solution already available?
Please kindly let me know, thanks in advance and best regards.

**Comment by kpodemski** [comment]
Pull Request PrestaShop/ps_linklist#114 has been merged. The fix for this issue is expected to be delivered with v5.0.0 of Linklist module.
