### ISSUE TITLE
product indexing decrease every time I make changes

### ISSUE THREAD

**Issue by lamaji** [PrestaShop/PrestaShop#19301]
#### Describe the bug

The auto indexing does not working.

#### Expected behavior

When I add/edit some products, the number of indexing products decrease by 2, 10 or more..

**Screenshots**
![image](https://user-images.githubusercontent.com/17889279/82802178-60779280-9e76-11ea-9d5f-5d252d050a61.png)

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: 7.3.14

**Comment by sarahdib** [comment]
Hello @arradijamal 

PrestaShop 1.7.6 isn't compatible with php 7.3 
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Please try to downgrade to php 7.2 and check again.

I close this issue, feel free to open a new issue if the problem is still there after downgrading your php version.

Thank you

**Comment by lamaji** [comment]
Hello,

I downgrade my php to 7.2 but the problem still there.
I can't even make cron job to index products.
