### ISSUE TITLE
Table of the Confirmation Order Email is not displayed correctly

### ISSUE THREAD

**Issue by emflomed17** [PrestaShop/PrestaShop#19344]
#### Describe the bug

The order confirmation email is not displayed correctly.

#### Expected behavior

The table with the summary of the order should be displayed correctly

#### Steps to Reproduce

1. Create a new order.
2. Open the confirmation order email
3. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

![image](https://user-images.githubusercontent.com/25670760/82854582-77e26a00-9ece-11ea-9eb2-fb4f23991d9f.png)

#### Additional information

* PrestaShop version: **1.7.6.4**
* PHP version: 7.1

**Comment by sarahdib** [comment]
Hello @emflomed17 

I didn't reproduce the issue 
<img width="566" alt="Capture d’écran 2020-05-26 à 15 20 34" src="https://user-images.githubusercontent.com/3034677/82905733-83807000-9f64-11ea-9fdc-d09fcd240827.png">
This is the email sent using a PrestaShop 1.7.6.4 & Php 7.1

Did you change the template ?

**Comment by emflomed17** [comment]
> Hello @emflomed17
> 
> I didn't reproduce the issue
> <img alt="Capture d’écran 2020-05-26 à 15 20 34" width="566" src="https://user-images.githubusercontent.com/3034677/82905733-83807000-9f64-11ea-9fdc-d09fcd240827.png">
> This is the email sent using a PrestaShop 1.7.6.4 & Php 7.1
> 
> Did you change the template ?

Hi @sarahdib thanks for replying!

No, I did not update the template but there other people working in the website.

Could you share me the template of your order confirmation email? O would like to replace mine.

**Comment by florine2623** [comment]
Hi @emflomed17 ,
Your issue seems to be the same as : https://github.com/PrestaShop/PrestaShop/issues/18790#issuecomment-618902253
Please follow the steps there !

**Comment by emflomed17** [comment]
I could solve it. 

Apparently my file was corrupted during the installation. I overwrite the file with a new one.

**Comment by madsoliver** [comment]
This is still an issue! 

The order_conf.html table gets broken with using HTML-editor of AdminTranslations. I guess the products-loop gets moved outside of the table (because of syntax cleanup?). The result is that `{products} {discounts}` gets moved above the order summary table, rendering the email just like the screenshot by @emflomed17 


Please reopen

**Comment by emflomed17** [comment]
> This is still an issue!
> 
> The order_conf.html table gets broken with using HTML-editor of AdminTranslations. I guess the products-loop gets moved outside of the table (because of syntax cleanup?). The result is that `{products} {discounts}` gets moved above the order summary table, rendering the email just like the screenshot by @emflomed17
> 
> Please reopen

Hi @onklmaps use this order_conf file: 

[order_conf.zip](https://github.com/PrestaShop/PrestaShop/files/4731100/order_conf.zip)

**Comment by Yuraken** [comment]
Hi everyone!

The issue isn't resolved yet! The problem is still here in our website. Whenever we attempt to translate our order_conf mail template via the HTML-editor of AdminTranslations, our html template is broken and our tables are all messed up for no reasons.

Is there a known problem about products tables in the twig template on presta 1.7.6.3, because I can't find any solution about this problem right now.

Could you reopen this issue ? 

Thank you for your time.

**Comment by khouloudbelguith** [comment]
Hi @Yuraken,

This issue is currently closed, can you open a new one with more information about your configuration.

Thank you!

**Comment by totti240282** [comment]
Same problem.
