### ISSUE TITLE
Payment module order status email template generation

### ISSUE THREAD

**Issue by tomazpu** [PrestaShop/PrestaShop#19388]
#### Is your feature request related to a problem? 

Yes, we are creating a custom order status. The order status needs a custom email template. But we found no "module" way of generating an email template that we are able to use for the order status email.

We see that the functionality is in PrestaShop -> https://devdocs.prestashop.com/1.7/modules/concepts/mail-templates/add-a-layout-from-module

but the templates created that way don't show up in the order status view.
![Screenshot 2020-05-26 at 15 37 40 (3)](https://user-images.githubusercontent.com/32056440/82907628-2508c100-9f67-11ea-868f-36c283756608.png)

#### Describe the solution you'd like

A hook where you can generate / "register" the email templates that you can use for order status.

#### Alternatives you've considered

No preference.

#### Additional context

It is kind of very important to be able to add email templates for order statuses, for a payment module.

**Comment by marionf** [comment]
Hello @tomazpu 

You can create a new template directly in the folder /mails/_language_
And after you can select this template in the order status

Regards

**Comment by tomazpu** [comment]
Hi @marionf,

Is this the module way of creating an email template? So if I understand correctly:

my_module_name/mails/en/my_email_order_state_template.txt
my_module_name/mails/en/my_email_order_state_template.html

When I go then to PrestaShop Order state try to select an email template, my template is not on the list.
I need a way of doing this with a module, not directly in the shop.

Best Regards

**Comment by marionf** [comment]
Sorry, I can't help you to create a module. You should ask this kind of questions on [the forum](https://www.prestashop.com/forums/)

**Comment by tomazpu** [comment]
Hi @marionf, 

sorry but, I think you need to know as PrestaShop if the shop framework for the modules allows adding templates for order states. According to my research and looking at the PrestaShop code it's not, as the Order Status view only looks for templates in the root PrestaShop mail folder. This is a big issue for us as we ship are module we have no access to write something into the root Prestashop mail folder(prestashop_installation/mail/en/).

This an issue for every module that wants to introduce an email template for an order state.
I think I found an issue in PrestaShop and that's why I'm reporting it here and not on the forum.

Best Regards

**Comment by Matt75** [comment]
Hi,

Yes you can send mail with your module, sorry about lack of documentation, we work to improve it.
So create your template : 
my_module_name/mails/en/my_email_order_state_template.txt
my_module_name/mails/en/my_email_order_state_template.html

Then on your module install/upgrade add or update your custom OrderState : https://github.com/PrestaShop/paymentexample/blob/5304fec4e4c5e888ae4bc9d68e6b0dcf97b04c9c/paymentexample.php#L576 (Example of OrderState factory)
With parameters template « my_email_order_state_template » and isSendEmail to 1

I work on it since few day to improve payment example module on devdocs
Pull Request is here : https://github.com/PrestaShop/paymentexample/pull/14

**Comment by tomazpu** [comment]
Hi @Matt75, 

thank you very much!

Best Regards
