### ISSUE TITLE
Multistore - Order > Order - Disable add new button in all shops or in a group context and add message on hover

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19396]
Currently, the button  “Add new order” is enabled in all shops or in a group context and a message is diplayed when you click on it "You have to select a shop before creating new orders."

To avoid frustration, we should inform the merchants earlier

As specified in the [multistore specials cases specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-1-add-new-actions-only-enabled-in-a-specific-shop-context), the “Add new order” action is not possible in all shops or in a group context, so the button should be disabled in these contexts and we should display a message when the user hovers the "add new" button: "You can use this feature in a single shop context only. Switch context to enable it."

**Comment by matks** [comment]
@marionf Please see what I have done for this feature

![Capture d’écran 2021-03-31 à 17 41 15](https://user-images.githubusercontent.com/3830050/113172262-8ca73100-9248-11eb-96d5-640439b81259.png)

### What is implemented

The "Add new order" is disabled: it cannot be clicked, it is gray.

When you put your mouse over it you see a little "forbidden!" sign 🚫 
⬆️ you cannot see this on the screenshot because when I capture the screen, the mouse disappears 😛 

Also when you hover it, after 1 second a message appears "You can use this feature in a single shop context only. Switch context to enable it."

_The above behavior was achieved using Bootstrap [disabled](https://www.w3schools.com/tags/att_button_disabled.asp) behavior and [tooltip](https://www.w3schools.com/bootstrap/bootstrap_tooltip.asp) behavior._

⚠️ **Is this OK? Can I move forward and submit a PR?** ⚠️ 

Also please note that standard Bootstrap buttons or link-that-act-as-buttons cannot have a hover message when they are disabled but I can workaround this.

**Comment by marionf** [comment]
Thank you @matks yes, you can submit a PR as it seems really great and perfectly matches what was expected :+1:

**Comment by matks** [comment]
@marionf PR submitted https://user-images.githubusercontent.com/3830050/113743377-e6ee3900-9703-11eb-9e18-23c5b095a3cc.png

It looks like the UI Kit was updated recently so the message now looks better

<img src="https://user-images.githubusercontent.com/3830050/113743377-e6ee3900-9703-11eb-9e18-23c5b095a3cc.png">
