### ISSUE TITLE
PrestaShop Cleaner (pscleaner) - "Delete catalog" is not working.

### ISSUE THREAD

**Issue by k0lv** [PrestaShop/PrestaShop#19444]
1. Open "PrestaShop Cleaner" module
2. "I understand that all the catalog data will be removed without possible rollback: products, features, categories, tags, images, prices, attachments, scenes, stocks, attribute groups and values, manufacturers, suppliers..." - select YES.
3. Click button "Delete catalog".
4. Message "Please read the disclaimer and click "Yes" above". Click "OK".
5. Nothing happens.

**Expected:** Catalog is deleted.

![image](https://user-images.githubusercontent.com/59282576/83161540-3f7e9e00-a111-11ea-8289-e2f43cfe50cf.png)

#### Additional information
* PrestaShop version: 1.7.7.0
* PHP version: 7.2.31

**Comment by florine2623** [comment]
Hi @k0lv ,
I managed to reproduce this issue in 1.7.7.0, with ps_cleaner 2.0.0.

This is a regression, in PS 1.7.6.5, when choosing to delete the catalog, it works correctly.

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Progi1984** [comment]
PR : PrestaShop/pscleaner#45

**Comment by Progi1984** [comment]
Fixed by PrestaShop/pscleaner#45
