### ISSUE TITLE
Prestashop debug mode

### ISSUE THREAD

**Issue by srn87** [PrestaShop/PrestaShop#19465]
I am using a translator since my English is very basic if something is not understood they tell me, I am experiencing problems with prestashop, in which I activated the debug mode in the backoffice because I want to reproduce another error that the system is producing but I will look at it In another post and it turns out that I get the screen that I attach, it does not allow me to access the backoffice now in debug mode.

![mododebug2](https://user-images.githubusercontent.com/66142800/83306032-bdb66f80-a1f9-11ea-8ff1-aaf34f93e8b2.png)

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.3.1

**Comment by Matt75** [comment]
Hi @srn87

We released a new version of ps_mbo module this morning to fix this issue, you can download it here : https://github.com/PrestaShopCorp/ps_mbo/releases/latest

This issue https://github.com/PrestaShopCorp/ps_mbo/pull/96 is due to cache not well cleared, after applying the new version of ps_mbo module please clear your cache by delete folders `dev` and `prod` in `var/cache`

Sorry for this issue, we tested this version very long time before release but cache issue occur only when cache is really big or if additional server cache is not well invalidated.

**Comment by srn87** [comment]
Hi @Matt75 i clear the folder that i you said, then i need to install this ps_mob like a normal module in backoffice of prestashop?

**Comment by srn87** [comment]
i Attached what appeared to me after installing what you told me
![mododebug3](https://user-images.githubusercontent.com/66142800/83312570-a8960c80-a20a-11ea-9e50-53b214a60736.png)

**Comment by Matt75** [comment]
This is due to template cache not updated.

If you are in production it can be useful to enable maintenance mode to avoid concomitant access to cache when cleaning or warmup.

You can do that with this SQL Query on MySQL (use phpmyadmin for example)
`UPDATE ps_configuration SET value = 0 WHERE name = "PS_SHOP_ENABLE"` (If you use a custom table prefix, change table name accordingly)

You should unzip new module version of ps_mbo then upload it with ftp software in `modules` folder of your PrestaShop Instance.

After that go to `var/cache` folder then rename `dev` to `dev.old` and `prod` to `prod.old` ; finally delete `dev.old` and `prod.old`

If issue still occur please rename `ps_mbo` folder to `ps_mbo.bak` in your modules folder.

**Comment by srn87** [comment]
Thank you very much!! It Worked @Matt75
