### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by ksaandev** [PrestaShop/PrestaShop#19481]
#### Is your feature request related to a problem?

It would be great to be able to use postgresql

pgsql have many useful features like logical replication, huge performance compared to mysql

#### Describe the solution you'd like

Be able to plug prestashop on a postgresql database instead of mysql, select database type "postgresql" and it works

**Comment by florine2623** [comment]
Hi @ksaandev ,
Thanks for the recommandation.
I will ping our dev team, please stay tuned !

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,
Is this something that can be done ?
Thanks!

**Comment by PierreRambaud** [comment]
Hi @ksaandev 
Unfortunately, it's currently not possible, we use too many MySQL specific things (yes it's bad), but I totally agree that PgSQL is really awesome.
Maybe one day, but for now we are already too busy and have a lot of major projects in progress, and the work needed to make this happen is huge.

I'm closing it since it's not planned.

**Comment by PierreRambaud** [comment]
Duplicate of #13512

**Comment by ksaandev** [comment]
Thank you for answering
