### ISSUE TITLE
Address form should be opened in modal

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19499]
By the way, the Address form should be opened in modal, not a new page. (same behavior as in order create page), isn't it? (because now it seems to be forgotten. It opens up in a new page)

_Originally posted by @zuk3975 in https://github.com/PrestaShop/PrestaShop/issues/19341#issuecomment-634475159_

**Comment by MatShir** [comment]
As discussed with @TristanLDD, It's better to be able to homogenize behavior between pages.

**Comment by jolelievre** [comment]
Just a thing to be careful about When an address assigned to an order is edited it is actually soft delete and duplicated So the ID is supposed to change, I wonder if the order page should be updated then (or at least the address field)

**Comment by MatShir** [comment]
@matks have you find if the modal address was done and lost in the conflict?

**Comment by matks** [comment]
Nope, nothing done yet

**Comment by matks** [comment]
Started working on it ; I think it was never done. I thought we were talking about the "create an order" page, not the "view an order".

No big deal, I can re-apply what I did in "create an order" page.

Working on it now, I have a funny bug. I dont know (yet) why but when I edit the address, it creates a new one instead of modifying the one selected. I have to find if this is a setting I can modify or it is a rule I cannot modify.

If it's a rule, then I will have to
- open "edit an address" page
- do the modifications
- on save, modify the order "related address ID" for the new ID

**Comment by Progi1984** [comment]
Fixed by #19730
