### ISSUE TITLE
FO Account creation - Browser-side validation problem on the number of characters in a password

### ISSUE THREAD

**Issue by florian-202** [PrestaShop/PrestaShop#19505]
#### Describe the bug

There is only a HTML validation of the password when creating an account. This is problematic if a theme does not add this check because it is impossible for the user to connect later.

#### Expected behavior

In case there is no HTML validation in the theme, perform a validation from the server before registration.

#### Steps to Reproduce

1. Delete the validation from the template `form-fields.tpl`
![form-fields](https://user-images.githubusercontent.com/60136267/83425050-947e2500-a42d-11ea-94c1-47e48bcb429f.png)

2. Go on the registration form
3. Create an account with a password under 5 characters long
![form](https://user-images.githubusercontent.com/60136267/83424870-53861080-a42d-11ea-8609-6a95a43c513a.png)

5. Log out and try to log in
![loginform](https://user-images.githubusercontent.com/60136267/83424914-613b9600-a42d-11ea-8f12-cd10ec7ef3e1.png)
![erorr](https://user-images.githubusercontent.com/60136267/83424931-66004a00-a42d-11ea-8321-574b952180a2.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

**Comment by jolelievre** [comment]
Hi @florian-202 

I managed to reproduce the bug on 1.7.7 and 1.7.6.

I will add this bug to the develop roadmap. The `Validate::isPasswd` needs to be udpated to manage this min length. This indeed MUST be checked on the server side.

Although I don't understand why during the login the min length error is applied. Since it's not validated by the `Validate` class maybe there's an additional check in `AuthController`. This needs to be checked thoroughly because it means the creation form and the login form don't use the same logic to validate inputs and therefore can be inconsistent. We need to modify the workflow so that the same rules are applied in both cases.

Thank you for your feedback.
