### ISSUE TITLE
Longstanding bug still there [PSCSX-9685]

### ISSUE THREAD

**Issue by ukbazz** [PrestaShop/PrestaShop#19532]
It seems an issue first reported on the old Forge repository is still 'live' I can no longer access Forge bug repository and it is not mentioned here,
But the issue occurs while creating new account on OPC with a separarate delivery and invoice addresses.

Missing out any fields in the 2n'd 'Invoice Address the registration takes place on the delivery address and the Invoice address will not be made.

Is there a fix for this?
Using Prestashop v 1.6.1.24

**Comment by florine2623** [comment]
Hi @ukbazz ,
PrestaShop 1.6 [isn't maintained anymore](http://build.prestashop.com/news/1.6.1.x-what-s-next/). The maintenance for this version is now being performed exclusively by volunteers to fix critical issues.
You can open an issue on the [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues). Please keep in mind that only critical issues will be acknowledged.
If you need support from our team, you can buy support here : https://addons.prestashop.com/en/388-support
Thanks!

**Comment by matks** [comment]
@ukbazz your issue on the 1.6 repo was closed because it's not a critical issue and only critical issues are fixed on 1.6

However if your issue still happens on recent PS versions 😄 like PS 1.7.6 it's another story

**Comment by ukbazz** [comment]
@matks  Am wondering how a bug that actually _prevents people from making an order_ is deemed not critical! I did post on the dedicated 1.6 repository earlier - that post was removed also and I was directed here. Since this is an acknowledged bug in a version that many people still use it might have been helpful to keep the old forge up so that users might be able to address this

**Comment by matks** [comment]
> @matks Am wondering how a bug that actually _prevents people from making an order_ is deemed not critical! I did post on the dedicated 1.6 repository earlier - that post was removed also and I was directed here

If you're curious, here's how issues are labeled: https://build.prestashop.com/news/severity-classification/

Basically a "critical" bug makes the software unusable. It looks you are using PS 1.6 as do hundred of other people everyday, even though the bug is not fixed ; so the software cannot be described as unusable, right ? 😄 

Anyway, PS 1.6 is now dead software (= EOL) so it will only benefit, from some volunteers, of maintainance for critical issues (mostly security issues) see https://build.prestashop.com/news/1.6.1.x-what-s-next/ for details
So it's likely your bug will not be fixed.

May I suggest to migrate to a more recent version of PS 1.7 ? Because this version is maintained and active, so bugfixes are delivered frequently. Moreover since PS 1.6 is now the past, still using it will keep you into a situation more and more narrow: less and less people willing to work with it (and skilled), less and less modules and themes, more and more outdated with recent advances in software and technology ... you probably don't want to stay stuck in the past for too long.

**Comment by ukbazz** [comment]
@matks as you say - I like hundreds of others - though I suspect the number is in the very high thousands are indeed continuing to use v1.6 for as long as possible. Mostly because, those of us who have been using it for over 10 years find it a much better platform currently than v1.7!

I am more than happy to look at this bug myself and get it fixed, but it would help if someone at Prestashop could confirm if this was ever working as it should, and if so in what version -  it plainly doesn't work in the last versions on 1.6.

**Comment by matks** [comment]
> @matks as you say - I like hundreds of others - though I suspect the number is in the very high thousands are indeed continuing to use v1.6 for as long as possible. Mostly because, those of us who have been using it for over 10 years find it a much better platform currently than v1.7!

Well it's good to know you like one of PrestaShop projects 😊 

> I am more than happy to look at this bug myself and get it fixed, but it would help if someone at Prestashop could confirm if this was ever working as it should, and if so in what version - it plainly doesn't work in the last versions on 1.6.

I'm sorry this we cannot do it, because it's not in our scope (we are PS employees so we are paid for a mission, and the mission is "work on PS 1.7" 😉 ) and also because we do not have the skills anymore as it's old software now and we have not worked / leveled up on it. Our feedback would not be relevant on a bugfix for PS 1.6.

May I suggest you reach out to PS 1.6 maintainers on https://github.com/PrestaShop/PrestaShop-1.6 ?
They will not fix it as an official issue however they might be able to give you some feedback on your bugfix 😉 and these people have been working for years with PS 1.6

I think one of the easiest way to reach out to them is to look for the https://friendsofpresta.org/ PS user group because at least 2 of them are part of this group. They have a nice Slack channel with people using PS 1.6 and people using PS 1.7

On our side we'll not be able to help you. However if you are successfull in your mission, feel free to give us updates 😉 as this GitHub repository is "the new Forge", people looking for a bugfix for this might arrive here.

Have a nice day !
