### ISSUE TITLE
GeneratableTextType and ReductionType show help two times

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#19547]
#### Describe the bug

If you want to use GeneratableTextType or ReductionType from PrestaShopBundle with configure help. Help is displayed Two time

![image](https://user-images.githubusercontent.com/4932192/83653272-dccb4d80-a5bb-11ea-8548-25ccb9cd775e.png)

![image](https://user-images.githubusercontent.com/4932192/83937188-f098ce80-a7ca-11ea-9885-68080b06c2ec.png)

#### Expected behavior

Display only once.

#### Steps to Reproduce

1. Install PS 1.7.7 and [sample module](https://github.com/202ecommerce/checkboform)

2. See error o  "check bo form" admin tab

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by MatShir** [comment]
@PrestaShop/prestashop-core-developers Wdyt ?

**Comment by PierreRambaud** [comment]
@MatShir What is the question? AFAIK, regarding the image it's a bug :thinking: 
And a pull request is already opened #19453

**Comment by MatShir** [comment]
Nice, It was not very clear but I could not reproduce the bug (I couldn't download the module) so I was asking your opinion on the issue. All the information seems to be here. Thanks everyone

**Comment by clotairer** [comment]
@PierreRambaud The PR don't fix this issue. It's not the same twig block

**Comment by clotairer** [comment]
@MatShir I've committed vendor directory. No need composer, just download the zip from github.
branch label should be develop and not 1.7.7.0. It's not a regression.

**Comment by 202-ecommerce** [comment]
Edit > Add ReductionType in the same issue

**Comment by florine2623** [comment]
Hello all,

I can reproduce the issue on PS 1.7.8.x and develop, so I can confirm that this behavior is indeed a bug. :
<img width="754" alt="Screenshot 2022-02-15 at 13 06 28" src="https://user-images.githubusercontent.com/16019289/154059027-c6059738-459b-4243-81e0-3f5979e8aa7f.png">

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment]
@202-ecommerce Have you got always the bug with the `develop` branch ?

@PrestaShop/qa-functional Could you check again ?

**Comment by clotairer** [comment]
hi @Progi1984 I'll try my module but it's not compatible... I need to upgrade it...

**Comment by Progi1984** [comment]
@clotairer Thanks. I will work on it as soon your module is available.

**Comment by Progi1984** [comment]
@clotairer Friendly Reminder ;)

**Comment by clotairer** [comment]
We work on it this week and will send a PR.

**Comment by Progi1984** [comment]
@clotairer You are a boss. Thanks :pray:

**Comment by clotairer** [comment]
Hola !

Here the checkform working on PrestaShop 8.
[checkboform.zip](https://github.com/PrestaShop/PrestaShop/files/8427375/checkboform.zip)

I'm also ready to send you a PR.
