### ISSUE TITLE
Incorrect discount value

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#19551]
Hello,
I use in product settings the parameter "Display discounted price"  =  "Yes" (In the volume discounts board, display the new price with the applied discount instead of showing the discount (ie. "-5%")).
But there is still displayed the discount with %, I expect there should be displayed discount amount with the currency (in my example there is "-10%" and "Save 10%", there should be "€-13,50" and "Save €-13,50")

Product in the list
![image](https://user-images.githubusercontent.com/33311857/83720549-87ce1c80-a639-11ea-8700-4d29bb132491.png)

Product detail
![image](https://user-images.githubusercontent.com/33311857/83720917-530e9500-a63a-11ea-85a6-b248e7b957a9.png)

Configuration
![image](https://user-images.githubusercontent.com/33311857/83721055-a08b0200-a63a-11ea-84f6-e01c5c65d7ba.png)

**Comment by florine2623** [comment]
Hi @juraj1000 ,
The option you chose is for the volume discount board. For example :
![Capture d’écran 2020-06-04 à 11 22 54](https://user-images.githubusercontent.com/16019289/83739359-c1148580-a655-11ea-909a-5ec8cb366bf3.png)
If you want the discount to show in amount, you need to put the discount amount instead of the percentage directly in the product sheet.
In product sheet > Price > Specific Price :
![Capture d’écran 2020-06-04 à 11 24 59](https://user-images.githubusercontent.com/16019289/83739610-1d77a500-a656-11ea-8aa9-54c3ef473209.png)
It will show in amount like so :
![Capture d’écran 2020-06-04 à 11 26 40](https://user-images.githubusercontent.com/16019289/83739733-4730cc00-a656-11ea-9f7d-15da9ca61407.png)
Thanks!
