### ISSUE TITLE
Very slow massive products delete

### ISSUE THREAD

**Issue by linuxatico** [PrestaShop/PrestaShop#19605]
#### Describe the bug
Deleting 4000+ products each with an average of 4-5 combinations without any image takes very long, ~ 15 s / product and 100% cpu usage till the end.

#### Expected behavior
To delete products with time consumption of lower order of magnitude: It's not the same, but for give an idea, doing the TRUNCATE commands via MySql for all the related tables is far more more more efficient, there has to be something to improve.
This may be related with https://github.com/PrestaShop/PrestaShop/issues/15380

Invoking the following method N times:
```
    public function manage()
    {
        //Take array of product references to delete
        foreach ($productsToDeleteEffectively as $reference => $values) {
            $this->deleteProductByReference($values);
        }
     }



    protected function deleteProductByReference(string $reference): void
    {
        $start = microtime(true);
        $methodName = "deleteProductByReference";
        $productIDs = $this->getProductIDsByReference($reference);
        $PSProduct = new Product($productIDs[0]);
        $PSProduct->delete();
        $duration = microtime(true) - $start;
        self::log(self::LOG_INFO, $methodName, "Deleted product|reference|$reference|productIDs[0]|" . var_export($productIDs[0], TRUE)."|duration|".$duration);
    }
  
 public function getProductIDsByReference($reference): array
    {
        $results2 = array();
        /** @noinspection SqlResolve */
        $sql = 'SELECT id_product FROM ' . _DB_PREFIX_ . "product WHERE reference = '" . $reference . "'";
        if ($results = Db::getInstance()->ExecuteS($sql)) {
            foreach ($results as $row) {
                $results2[] = $row['id_product'];
            }
        }
        return $results2;
    }

    private static function log(string $logLevel, string $methodName, string $stringToLog): void
    {
        $logger = new FileLogger(0);
        $logger->setFilename(PS_PRODUCTS_ERROR_LOG_FILE);
        $fullStringToLog = "$methodName|$stringToLog";
        if($logLevel == self::LOG_ERROR){
            $logger->logError($fullStringToLog);
        } else if($logLevel == self::LOG_WARN){
            $logger->logWarning($fullStringToLog);
        } else if($logLevel == self::LOG_INFO){
            $logger->logInfo($fullStringToLog);
        } else if($logLevel == self::LOG_DEBUG){
            $logger->logDebug($fullStringToLog);
        }
    }
```

#### Steps to Reproduce

1. Create 4000+ products
2. Create a module implementing ```WebserviceSpecificManagementProductsImporter implements WebserviceSpecificManagementInterface```
3. Query for all the product references in the DB and foreach of them call ```deleteProductByReference``` in the ```manage()``` method
4. See logs and note the long time spent for deleting every single product, see also the CPU usage consumption almost always at 100% and the low RAM usage.

E.g. 

```
*INFO* 	v1.7.6.5	2020/06/05 - 15:50:58: deleteProductByReference|Deleted product|reference|a|productIDs[0]|'3528'|duration|10.653426885605
*INFO* 	v1.7.6.5	2020/06/05 - 15:51:08: deleteProductByReference|Deleted product|reference|b|productIDs[0]|'3529'|duration|9.792445898056
*INFO* 	v1.7.6.5	2020/06/05 - 15:51:45: deleteProductByReference|Deleted product|reference|c|productIDs[0]|'3530'|duration|36.687208890915
*INFO* 	v1.7.6.5	2020/06/05 - 15:52:44: deleteProductByReference|Deleted product|reference|d|productIDs[0]|'3531'|duration|59.316357135773
*INFO* 	v1.7.6.5	2020/06/05 - 15:53:48: deleteProductByReference|Deleted product|reference|e|productIDs[0]|'3532'|duration|64.010340929031
*INFO* 	v1.7.6.5	2020/06/05 - 15:54:49: deleteProductByReference|Deleted product|reference|f|productIDs[0]|'3533'|duration|61.316828966141
*INFO* 	v1.7.6.5	2020/06/05 - 15:55:43: deleteProductByReference|Deleted product|reference|g|productIDs[0]|'3534'|duration|53.773839950562
*INFO* 	v1.7.6.5	2020/06/05 - 15:56:36: deleteProductByReference|Deleted product|reference|h|productIDs[0]|'3535'|duration|53.408065080643
*INFO* 	v1.7.6.5	2020/06/05 - 15:57:25: deleteProductByReference|Deleted product|reference|i|productIDs[0]|'3536'|duration|48.723160982132
*INFO* 	v1.7.6.5	2020/06/05 - 15:58:14: deleteProductByReference|Deleted product|reference|j|productIDs[0]|'3537'|duration|49.325378894806
*INFO* 	v1.7.6.5	2020/06/05 - 15:58:56: deleteProductByReference|Deleted product|reference|k|productIDs[0]|'3538'|duration|41.96346616745
*INFO* 	v1.7.6.5	2020/06/05 - 15:59:56: deleteProductByReference|Deleted product|reference|l|productIDs[0]|'3539'|duration|59.596213102341
*INFO* 	v1.7.6.5	2020/06/05 - 16:00:38: deleteProductByReference|Deleted product|reference|m|productIDs[0]|'3540'|duration|41.721590042114
*INFO* 	v1.7.6.5	2020/06/05 - 16:00:48: deleteProductByReference|Deleted product|reference|n|productIDs[0]|'3541'|duration|10.430980920792
*INFO* 	v1.7.6.5	2020/06/05 - 16:00:59: deleteProductByReference|Deleted product|reference|o|productIDs[0]|'3542'|duration|10.412371873856
*INFO* 	v1.7.6.5	2020/06/05 - 16:01:08: deleteProductByReference|Deleted product|reference|p|productIDs[0]|'3543'|duration|9.5320839881897
*INFO* 	v1.7.6.5	2020/06/05 - 16:01:17: deleteProductByReference|Deleted product|reference|q|productIDs[0]|'3544'|duration|8.6736090183258
*INFO* 	v1.7.6.5	2020/06/05 - 16:01:25: deleteProductByReference|Deleted product|reference|r|productIDs[0]|'3545'|duration|8.3608248233795

```

#### Additional information
* Server with 4G RAM
* CPU:
```
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel Core Processor (Haswell, no TSX)
stepping	: 1
microcode	: 0x1
cpu MHz		: 2095.058
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4190.11
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```
* PrestaShop version: 1.7.6.5
![prestashop_info](https://user-images.githubusercontent.com/1684502/83884950-f3051500-a745-11ea-9fc4-814fce45d453.png)

**Comment by florine2623** [comment]
Hi @linuxatico ,
Do you have a test module available so that I can test it on my end ?
Thanks!

**Comment by linuxatico** [comment]
Hi @florine2623 ,
I'm sorry but I have a whole ad hoc project for inserting and deleting products and it will take lot of effort creating a test module: I know that it's not ideal, but I posted some crucial points of code, I hope you can find a way of testing this without problems, don't you have some test cases for inserting and deleting products?

**Comment by jolelievre** [comment]
Hi @linuxatico 

I agree that using truncate on the table directly is more efficient, however I'm not sure we can do it that easily, because using `Product::delete` (or any delete on an Object model) manages more that just removing the table row There are hooks that are called (so that module can removed related data if needed) it also needs to remove and the relation with categories, suppliers, ... The stock must be updated as well

Some other entities also have checks to prevent deleting (do not delete default currency), or use soft delete: a deleted boolean in the DB so that it is not displayed/used any more but is still accessible because it is related to another object like an order or an invoice.

**Comment by NeOMakinG** [comment]
I’ll add this to the debug roadmap so that the team will work on optimize it

Thanks!

**Comment by linuxatico** [comment]
Hi @jolelievre , 
thanks for your time, I surely understand it may not be easily improvable but I think that there has to be a way of improving this behavior: doing the same things with a very low amount of products it's far very efficient (~ 0.3/s or less per product).
Here an improved list of info(s) that may be useful to you to understand the problem:

1. The site is not public yet, it's still under development (no real customers at all, no traffic coming from HTTP except mine)
2. 98 ps_attributes
3. 2392 ps_products
4. 9806 ps_product_attribute_combination and 9806 ps_product_attribute
5. 15 parent categories
6. 8547 ps_specific_price
7. 72 child categories
8. 1 single language (IT)
9. 1 single currency (€)
10. 5 test orders with 1-2 products at max
11. 12129 ps_stock_available

This numbers, with my use case, will grow in future and the products will change almost often during the month: I fear that updating the catalog will be too slow and too much expensive, during the deletion the front office becomes very unresponsive. I will opt for night operations, but it's only a workaround that only avoid the obstacle.

At last, I can try with a bigger server, but I find this a loss

**Comment by marionf** [comment]
@NeOMakinG Could you add the bug label ?

**Comment by sam-pires** [comment]
Some other related issues about the webservice perf, might be worth having a look as well. 
#15380 & #14903

**Comment by davidglezz** [comment]
probably related to https://github.com/PrestaShop/PrestaShop/issues/12907

**Comment by kviwilavi** [comment]
It's and old thread and I hope it's solved by now, but I'm having the same problem with newest PrestaShop 1.7.7.6. Testing enviroment with around 10 to 20k products, I need to insert and delete them very often a very quickly. It seems that the problem is mainly in categories, perhaps PrestaShop is trying to re-order ALL products after one delete (?).

If you are **testing** and just need very **quick bulk-delete**, 
`TRUNCATE TABLE `ps_category_product``
speeds up the process (from 2 products/minute to 3000 products in few seconds!!)

However, this is probably very bad idea for some already running shop. You could do the following

delete products from all categories (have some config file to remember the needed ones)
delete all products you want
assign categories

Hope it will get solved soon.

**Comment by jolelievre** [comment]
Hi @kviwilavi,

as I explained in an earlier comment (https://github.com/PrestaShop/PrestaShop/issues/19605#issuecomment-640624605) the solution is not as simple as truncating the DB directly, at least not for everyone...

PrestaShop acts as a CMS that provides hooks for external modules and solutions, when a product is deleted a hook is called so that modules can clear their own data related to the deleted product. If we were sure that only the PrestaShop model is used and assigned to the product we could very well implement an optimized bulk delete relying only on our core tables and performing bulk delete SQL queries. However, we must think in a more generic way, so I guess (I didn't check the code yet) that we are forced to perform a loop of all the deleted products and calling the `Product::delete` method.

That said, **maybe** (and I insist on the "maybe") it is possible to optimize this feature, by relying on a dedicated service that simulates the loop of hooks on each product and performs the removal relying on SQL queries in the background. The main thing I'm worried about here is that the hook expects the Product object to be instantiated, so even if the removal query can be done via a bulk SQL query, we would still have to fetch each product independently beforehand thus the optimization would not be that huge..

For a full optimization, we would need to change the hook contract (by only providing the product ID for example), but this will represent a breaking change.

**Comment by kviwilavi** [comment]
@jolelievre

I have read this (and many more) discussion and I understand it's not that simple as performing one SQL query. I have written my comment here because I've been searching for a solution for quite a long time with an headache, blaming my own computer. Deleting just a few thousand products  for hours is really annoying and **at least for testing purposes** , deleting the categories x products table really helps - and then performing the official Presta's built-in delete.

At least for me, it seems like a huge problem, that is "being solved" since 2016. I'm building a shop and even now, in a testing phase, I know I will need to speed up this deleting/updating feature. I've searched the internet and it really seems like  a problem that annoys a lot of people, not just me. Purchasing better webservice won't help, it's really not the server's fault, as the bulk operations don't really use much processing power, just take a long time.

I just wanted to know if any "official" solution is available (or at least description of the real problem). If not, I will  have to dig into the PrestaShop's code and find something suitable for me, but I'm not PrestaShop developer and of course don't really understand all core features, so mistake can be made very easily. I wanted to avoid that.

Thank you for your time and comment.

**Comment by Multipage** [comment]
Currently we are having difficulty mass deletion of products programmatically in 1.7.8.2, 6 products in 1 minute. This is WAY to slow since it has to delete 44.000 products. 
The problem is in the  product->delete() function. Here it uses product->deleteCategories(true) and that triggers the function Product::cleanPositions which is VERY slow.
Currently we use a workaround by manually deleting the product from categorie_product stable. 
Now mass deletion is around 200 products a minute(still way to slow imho). Later we will loop through all categories to recalculate the positions.

We don't use the webservice.

**Comment by Multipage** [comment]
Seems to me the 'Module::setBatchMode(true)' could be integrated so we can avoid this behaviour like it's doing with tags/tagcount

**Comment by ghost** [comment]
Yes, This is just insane to delete thousands of products at once! 
6000 products and about 60 seconds to delete one its 4 days of non stop deleting?!!!!!!!!!!!!!!!!

**Comment by jolelievre** [comment]
OK, I see the problem that you explained, if I get it right the main problem here is that categories' positions are recomputed for each product which is deleted Which of course is a huge loss of performance since it should only be done once all the products have been removed

But Product::delete doesn't propose any parameter to prevent this we can't optimize this currently, seeing the code I don't have a clean solution, it's full of static code so it's hard to optimize this with nice code we have to play by the rules and use static code as well in such situations.

But my idea would be to activate a special mode when performing bulk deletion, like:

```php
Product::beginBulkDeletionMode();

public static function beginBulkDeletionMode(): void
{
    if (static::$bulkDeletionMode) {
        return;
    }
    static::$bulkDeletionMode = true;
    static::$categoriesToClean = [];
}
```

Then when this mode is enabled in `Product::cleanPositions`

```php
public static function cleanPositions($id_category, $position = 0)
{
    if (static::$bulkDeletionMode) {
        if (!in_array($id_category, static::categhoriesToClean[]) {
            static::categoriesToClean[] = $id_category;
        }

        return true;
    }

    // Rest of the code is untouched
}
```

This way the heavy update for positions is ignored while all products are being deleted, but we save which categories will need to be cleaned, so that finally after the bulk deletion we can do:

```php
Product::endBulkDeletionMode();

public static function beginBulkDeletionMode(): void
{
    if (!static::$bulkDeletionMode) {
        return;
    }
    static::$bulkDeletionMode = false;
    foreach (static::$categoriesToClean as $categoryId) {
        static::cleanPositions(categoryId);
    }
    static::$categoriesToClean = [];
}
```

What do you guys think? If it seems like a solution or at least the beginning of one feel free to open a PR in that way. It's just a rough first write which I'm sure can be improved.

**Comment by vegmaster** [comment]
Is any news about that?
I tried the idea proposed by @jolelievre but it doesn't improve anything.
I have more than 3500 products to delete. 2 days after it is continuing to delete them...And it can only be done in CLI mode because of timeouts.
I am OK that there is hooks but it is completely crazy that it takes so much time. Maybe there is multiple mysql joins during the process? the joins can be very time-consuming.

**Comment by JoseNOM** [comment]
+1

**Comment by blawdi** [comment]
no issue?

**Comment by jamiloo** [comment]
Hi all. Are you bored with this uncomfortable problem with bulk products delete? I have been dealing with it several years. I have dived into code and found that bottleneck finally ;) .  In Product->delete() function, there is row "!$this->deleteCategories(false) ||" .  There was true, I changed to false and problem is gone.  This param means clean positions and makes it slowwwwwww and slower and slowest if there are many products.

Here you can see my override function. NOTE: I overrided function directly in original class file classes/Product.php not in override/classes/Product.php. I made it due fact I was not able to override this function in override foilder it did not work. If anybody will solve it, it would be greeeeat ;)


```php

  
public function delete()
    {
        /*
         * @since 1.5.0
         * It is NOT possible to delete a product if there are currently:
         * - physical stock for this product
         * - supply order(s) for this product
         */
        if (Configuration::get('PS_ADVANCED_STOCK_MANAGEMENT') && $this->advanced_stock_management) {
            $stock_manager = StockManagerFactory::getManager();
            $physical_quantity = $stock_manager->getProductPhysicalQuantities($this->id, 0);
            $real_quantity = $stock_manager->getProductRealQuantities($this->id, 0);
            if ($physical_quantity > 0) {
                return false;
            }
            if ($real_quantity > $physical_quantity) {
                return false;
            }

            $warehouse_product_locations = ServiceLocator::get('\\PrestaShop\\PrestaShop\\Core\\Foundation\\Database\\EntityManager')->getRepository('WarehouseProductLocation')->findByIdProduct($this->id);
            foreach ($warehouse_product_locations as $warehouse_product_location) {
                $warehouse_product_location->delete();
            }

            $stocks = ServiceLocator::get('\\PrestaShop\\PrestaShop\\Core\\Foundation\\Database\\EntityManager')->getRepository('Stock')->findByIdProduct($this->id);
            foreach ($stocks as $stock) {
                $stock->delete();
            }
        }
        $result = parent::delete();

        // Removes the product from StockAvailable, for the current shop
        StockAvailable::removeProductFromStockAvailable($this->id);
        $result &= ($this->deleteProductAttributes() && $this->deleteImages());
        // If there are still entries in product_shop, don't remove completely the product
        if ($this->hasMultishopEntries()) {
            return true;
        }

        Hook::exec('actionProductDelete', array('id_product' => (int)$this->id, 'product' => $this));
        if (!$result ||
            !GroupReduction::deleteProductReduction($this->id) ||
            !$this->deleteCategories(false) || // there was true, I changed to false, this param means clean positions and makes it slowwwwwww
            !$this->deleteProductFeatures() ||
            !$this->deleteTags() ||
            !$this->deleteCartProducts() ||
            !$this->deleteAttributesImpacts() ||
            !$this->deleteAttachments(false) ||
            !$this->deleteCustomization() ||
            !SpecificPrice::deleteByProductId((int)$this->id) ||
            !$this->deletePack() ||
            !$this->deleteProductSale() ||
            !$this->deleteSearchIndexes() ||
            !$this->deleteAccessories() ||
            !$this->deleteFromAccessories() ||
            !$this->deleteFromSupplier() ||
            !$this->deleteDownload() ||
            !$this->deleteFromCartRules()) {
            return false;
        }

        return true;
    }

```

**Comment by jolelievre** [comment]
Hi @jamiloo 

it's not that we are bored, far from it, we are just focused on other things but we always welcome contributions from anyone. But as we already discussed in this thread we can't purely ignore the category position recomputing because it would mess with the category page and simply toggling the parameter, as you did, will have side effects that other users won't be happy about (which is understandable).

We already identified in this discussion that the bulk deletion slowness comes from the category positions recomputing, which is why I suggested an alternative in a previous comment https://github.com/PrestaShop/PrestaShop/issues/19605#issuecomment-1021089334 The idea is to disable TEMPORARILY the automatic computing and instead store all categories related to deleted products, and when they have been deleted we manually recompute the affected categories. But no PR was proposed the suggested solution so far.

The product page is currently being refactored/remigrated it should be fully released in v8.1 so this optimization could be integrated into the https://github.com/PrestaShop/PrestaShop/blob/f8e8dee18ac01bdf23f347e6c63280e7b451232c/src/Adapter/Product/CommandHandler/BulkDeleteProductHandler.php#L60

By the way the bulk delete has been remade in the product V2 list so it might (I insist on `might`) be a bit more efficient than in V1, I didn't test with thousands of products so I don't know but I invite you to test the V8 and enable the product V2 page to test it out.

@MatShir do you think this optimization idea could be integrated in the v8.1 scope officially?

**Comment by ozselgin** [comment]
Keeping positions in category_product table is design  failure. It should be removed at all.

**Comment by davidglezz** [comment]
<img width="199" alt="image" src="https://user-images.githubusercontent.com/194784/206578836-2fe404ef-7ac0-4e3e-9170-2d9696210797.png">
After delete product 20:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/194784/206578916-7cd36629-d691-45ba-b2d5-43ee93f36b77.png">

Why is it so important that the position be consecutive numbers? to maintain order it is not necessary.

Searching for position, its only used in `ORDER BY` part of sql queries.

I have created a PR so that when deleting a product it does not update the positions of all the others, leaving gaps.

https://github.com/PrestaShop/PrestaShop/pull/30541

But yes, the current ordering system is unnecessarily overcomplicated.
