### ISSUE TITLE
Overriding/extending ProductLazyArray

### ISSUE THREAD

**Issue by stijnvergote** [PrestaShop/PrestaShop#19640]
Hello,

I have a question regarding the ProductLazyArray class (namespace PrestaShop\PrestaShop\Adapter\Presenter\Product).

I would like to change the rounding for the $presAbsoluteReduction from 2 decimals to 0 in the 'addPriceInformation' method. This is a very small change but I do not want to add this adjustment in the core files. So I'm looking for a way to override or extend this functionality.

What is the best way to do this?
Thanks in advance.

**Comment by matks** [comment]
We've recently added a hook into ProductPresenter, I think it will do the job ?
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Product/ProductPresenter.php#L95

**Comment by matks** [comment]
(see https://devdocs.prestashop.com/1.7/modules/concepts/hooks/ if you are not familiar with hooks)

**Comment by stijnvergote** [comment]
Hi @matks, 

Thank you for your reply.
I'm using the last stable version in production (1.7.6.5) so the hook isn't present yet. 
But nice to see that this will be possible in the future!

Is there a solution for 1.7.6.5 or do I wait until 1.7.7 is stable?

Thanks

**Comment by stijnvergote** [comment]
@matks will you also add a hook into ProductListingPresenter?
That would do the job 👍

**Comment by idnovate** [comment]
> We've recently added a hook into ProductPresenter, I think it will do the job ?
> https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Product/ProductPresenter.php#L95

This has not been merged yet  :man_shrugging:

@matks any idea when it will be included? Thanks.

EDIT: OK it's in PS 1.7.8 :)

**Comment by musaffar-patel** [comment]
Can you please provide an example of how to utilise the actionPresentProductListing hook to modify products in the product list?

**Comment by pelleringa** [comment]
Hi,
I tried to use that hook to modify some product properties (my goal is to override the getFlags function from the ProductLazyArray to set a percentage discount on the products with a low discount amount, but since it seems it can not be overriden or decorated, I tried this hook to set the changes in the product attributes so the flags will get the behaviour I want), but since the product property from the class is protected, it can not be modified or set. Is there any way to do this with any other hook?
Finally I could do this by adding some more code to the hook hookActionProductFlagsModifier removing and adding flags but I'm not sure how can I use the ProductPresenter hook correctly to modify the lazy product, it would be better than the current solution
