### ISSUE TITLE
Product Properties Caching causes errors

### ISSUE THREAD

**Issue by Shoprunners** [PrestaShop/PrestaShop#19654]
#### Describe the bug

When re-calculating frontend prices due to quantity change in the presence of quantity discounts, prices will not be correctly recalculated due to Product::getProductProperties caching the results with improper cache keys.

Either the cache key must reflect more / all of the function parameters (as would make sense!) or the caching needs to be dropped entirely. But caching something and ignoring any change is very buggy.

#### Expected behavior

The price on the frontend should change according to quantity discounts.

#### Steps to Reproduce

When Product::getProductProperties gets invoked before ProductController::getTemplateVarProduct()

(which might be template dependant) the function caches the properties and in subsequent calls with different quantities will not correctly calculate the prices but return the cached results.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @Shoprunners 

Sorry for the late response :confounded:  
Could you please provide a clear steps to reproduce the issue and to better understand how it affects the FO.

Thanks in advance.

**Comment by Shoprunners** [comment]
Hi,
well, the exact example I cannot remember after 7 months, but if you look at the current code, it is obvious:
file classes/Product.php function "getProductProperties"

there is a cache built with a cachekey.
Cachekey is built like this:
 $cache_key = $row['id_product'] . '-' . $id_product_attribute . '-' . $id_lang . '-' . (int) $usetax;

so no use of context i.e.

and if this cachekey can be found, this value will be returned
  if (isset(self::$productPropertiesCache[$cache_key])) {
            return array_merge($row, self::$productPropertiesCache[$cache_key]);
        }

if the cachekey wasn't found, the entry will be created. During creation process, the context, which is a function argument, will be taken into account for price calculation (i.e. one group can have other prices than others, quantity discount for current cart....)

So building cache entry uses context, retrieving from cache not. The outcome can be right, but will be false for sure, if you are working with groups, specific prices, quantity discounts....

**Comment by hibatallahAouadni** [comment]
Hello @Shoprunners 

I know it has been more than 7 months :sweat: 
But I really need some clear steps to reprpduce the issue in FO. That we help our developers to fix the problem as soon as possible.

Thanks for your feedback :pray:

**Comment by Shoprunners** [comment]
Hi, please show it to a developer and he will see at once what the problem is. I can't reproduce the certain misbehaviour right now, but it is a really potential risk to leave the code as it is. Just can give you the hint to this.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could you please take a look on this issue :pray: it seems there's problem with **`cachekey`** in this function **`getProductProperties`**, could you please check it?

**Comment by matks** [comment]
Hi everybody, sorry for late answer

> it is a really potential risk to leave the code as it is

Yes this is likely to create bug issues

> I can't reproduce the certain misbehaviour right now

Same for me, it's hard to build a _reproductible scenario_ without spending a few (maybe more) hours on this topic

> Either the cache key must reflect more / all of the function parameters (as would make sense!) or the caching needs to be dropped entirely. But caching something and ignoring any change is very buggy.

I guess the right solution would be to `the cache key must reflect more / all of the function parameters`

That being said, as the issue is hard to reproduce and scope, it will be hard
- to build a _reproductible scenario_ to observe buggy behavior
- to fix the issue as we dont have an accurate list of all possible contexts needed to acknowledge in the cache strategy
- to validate the fix (if we could deliver it) as we dont have an accurate list of all possible usecases where such prices are computed

So I'm afraid this issue is likely to stay like this for months, maybe years 😓  . It needs to be narrowed down to something more accurate so we can work on it. We cant just go explore in the dark, hoping to find something 😢 .

So I close this issue. This does not mean we dont care or we dont think this is interesting, it's rather that we have so much topics to handle, this one will never reach the top of our pile of things to do in its current state. But if you are interested in the topic feel free to invest yourself in it 😉  .

**Comment by cristiancaceres1** [comment]
I found a reproducible scenario where quantity discounts stop working due to productProperties caching.

Steps to reproduce:

1. Create a product with combinations and quantity discounts (SpecificPrice with from_quantity).
2. Configure the same product as its own accessory (ps_accessory id_product_1 = id_product_2).
3. Open the product page and change quantity above the discount threshold.

Observed behavior:

ProductController::getAccessories() calls Product::getProductProperties() before the main product price calculation.

Because getProductProperties() caching does not include quantity in the cache key, 
it stores the result calculated with minimal_quantity (1).

Later calls from getTemplateVarProduct() hit the cache and specific prices are not applied.

Result:
- specific_prices = false
- quantity discounts not applied
- wrong price displayed.

Removing the self-accessory fixes the issue.

Suggestion:
Prevent a product from being assigned as an accessory of itself or include quantity in the cache key.

Use this query to locate all products that list themselves as an accessory:

SELECT 
    a.id_product_1 AS id_product,
    pl.name,
    p.reference,
    p.active
FROM ps_accessory a
JOIN ps_product p 
    ON p.id_product = a.id_product_1
JOIN ps_product_lang pl 
    ON pl.id_product = p.id_product
    AND pl.id_lang = 1
WHERE a.id_product_1 = a.id_product_2
ORDER BY a.id_product_1;
