### ISSUE TITLE
Broken theme after 1.7.6.3 update

### ISSUE THREAD

**Issue by rflorent** [PrestaShop/PrestaShop#19661]
#### Describe the bug

Prestashop updated from 1.7.5 to 1.7.6.
The themes/core.js example changes : 
1.7.5 => (0,r.default)(".product-prices").replaceWith(e.product_prices)
1.7.6 => (0,r.default)(".quickview .product-prices, .page-product:not(.modal-open) .row .product-prices").replaceWith(e.product_prices)

This changes broke the theme's templates bought on addons market place.
Why using a specific class like ".row" ? This change force to edit the template !

#### Expected behavior

Expect that a minor update don't break themes !

#### Steps to Reproduce

Don't tell me I can't reproduce...

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by eternoendless** [comment]
I found the offending change: https://github.com/PrestaShop/PrestaShop/pull/16852 (merged in 1.7.6.3).

@NeOMakinG do you think we could have done it without the `.row` part in the selector?

**Comment by rflorent** [comment]
Thanks for help, I end up removing the .row, the theme works again.
I alert the seller (templatetrip) that the theme is not working with the 1.7.6.3.
As the core.js is not a part of their theme, they don't care...  but the theme rely on this file for working !

**Comment by NeOMakinG** [comment]
The only way to handle that without the .row class is to add a new class because there are not any other selector to rely on for this fix. Unfortunately, this will lead to the exact same thing as you are living with your theme, theme developers will have to edit their theme in order to add this new class...

The fact that we introduced this .row is to fix big bugs when you change quantity/product_attribute, it was changing every prices/flags of the product on the page when you've related product or when you'r on quickview on a listing page..

**Comment by NeOMakinG** [comment]
Hey @rflorent 

We decided to add a new selector in order to avoid to force theme developers to use the .row class, btw the theme developer will have to update their theme after the release of this selector, because this fix some big bugs on product page and product listing. We decided to not revert that change because it's a bug fix..

Hope you understand and you agree with our choice

See this PR : https://github.com/PrestaShop/PrestaShop/pull/19800

Thanks for your report.

**Comment by rflorent** [comment]
Hello @NeOMakinG 

Thanks for this. I understand, agree and I think the theme developer doesn't do his job.
