### ISSUE TITLE
if a Tax is deactivated all the Tax Rules referring it are DELETED

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#19715]
#### Describe the bug

When you create a Tax and connect also to that tax some Taxrules if you deactrivate the Taxe the taxrules connected are DELETED not deactivated.

#### Expected behavior

Normally a deactivation of a value must follow a deactivation to a derivate/connected rule not a delete.
If a tax is deactivated the Country with tax applied must be deactivated not deleted inside the Tax Rule record.

if for some test you deactivate a Tax you will loose all the configurations in tax rules.

#### Steps to Reproduce

1) Create a tax
2) Create a Tax Rule
3) fill the Tax Rule with some country and with the Tax % created
4) Deactivate the tax created
5) Check the tax rule that is Active but all the country inside are DELETED.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

**Comment by florine2623** [comment]
Hi @HartLarsson ,

Thanks for the report.
I did manage to reproduce the issue in both PS 1.7.6.5 and PS 1.7.7.0.
Here's my screen record :
https://drive.google.com/file/d/1RXQ9tPrPrwv-S9Ilw3uaKXCwY_3OZtQ-/view

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by psantalla** [comment]
Hi, so I had this problem.
The only way you I could barely solve it, it's by deleting every tax rule you have the trouble with and then importing taxes for that country from locations.

**Comment by Progi1984** [comment]
Fixed in #33124 by @mflasquin (Version 8.0.5)
