### ISSUE TITLE
Bug in stock quantity update - the quantity is added several times when clicking the Apply button several times

### ISSUE THREAD

**Issue by rricci34** [PrestaShop/PrestaShop#19789]
I noticed a bug with the quantity updates in the stock management.

Indeed, some times on the 1st click we have the impression that nothing is happening, so we are tempted to click a second or a third time. 
Watch what is happening, I am attaching a video that will be more telling.

[gestion-stock-bug.zip](https://github.com/PrestaShop/PrestaShop/files/4786428/gestion-stock-bug.zip)

**Comment by colinegin** [comment]
Hello @rricci34 ,

I manage to reproduce your bug on 1.7.6.5 : [https://drive.google.com/file/d/1IA2GccG0HIqh0Rph0qdeDyoyejk51_XT/view](https://drive.google.com/file/d/1IA2GccG0HIqh0Rph0qdeDyoyejk51_XT/view)
I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you!
