### ISSUE TITLE
Wrong behavior when changing customer's group

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19815]
#### Describe the bug

0. Put {$customer.id_default_group} anywhere in the template to view current customer's group.
0. Create user group with id 4.
1. Go to FO, register a new customer. Log in to this customer.
2. Customer group should be 3.
3. Go to BO, edit this customer and change his default group to 4.
4. Go to FO, you will be logged out, but the customer group in context will still be 4.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by colinegin** [comment]
Hello @Hlavtox ,

Thanks for your feedback.
I reproduced all your steps on 1.7.6.5 (thanks for the clear explanation by the way), and yes in the end :
- the customer is logged out
- but conditions of the group are still applied and displayed (try for instance with a 50% discount)

I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you!

**Comment by Hlavtox** [comment]
Hi @colinegin, the same behavior goes when deleting a customer.

1. Make a customer.
2. To make this issue clearer, put some catalog rule discount for customer group 3.
3. Log in as this customer in FO.
4. Delete this customer in BO.
5. Refresh page in FO, you should be logged out, but still get the discounts for customer group 3.

**Comment by Hlavtox** [comment]
Just testing this on develop and the issue has been fixed by someone, sometimes, by accident. 😄 Cloooosing.
