### ISSUE TITLE
Allow override of checkoutProcess construction

### ISSUE THREAD

**Issue by ksaandev** [PrestaShop/PrestaShop#19848]
#### Is your feature request related to a problem?

I would like to modify the content of `controllers/front/OrderController.php` property `$checkoutProcess` when it is is constructed in `bootstrap()` function but I cannot do it through an override, it's not available.

#### Describe the solution you'd like

Put the logic of construction of `$checkoutProcess` inside a protected function to allow developers to override it

#### Alternatives you've considered

Use a hook

**Comment by ksaandev** [comment]
I have made a PR https://github.com/PrestaShop/PrestaShop/pull/19830/

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-core-developers ,

@ksaandev wants to override `OrderController.php`, he has a PR available. Could you please take a look and test it out ?
Thanks!

**Comment by ksaandev** [comment]
Hi ! Any news ! Something blocks the topic ?

**Comment by matks** [comment]
Hi @ksaandev, though overrides are powerful to extend PrestaShop, we try to avoid them as much as possible because they can have significant side-effects and make a shop very hard to upgrade in the future. It would be better to allow extension of `checkoutProcess` by using a hook - although indeed moving the construction logic into a function `buildCheckoutProcess()` is not a bad idea either.

You can read more about "why overrides are dangerous" here https://github.com/PrestaShop/PrestaShop/issues/13681

**Comment by ksaandev** [comment]
> Hi @ksaandev, though overrides are powerful to extend PrestaShop, we try to avoid them as much as possible because they can have significant side-effects and make a shop very hard to upgrade in the future. It would be better to allow extension of `checkoutProcess` by using a hook - although indeed moving the construction logic into a function `buildCheckoutProcess()` is not a bad idea either.
> 
> You can read more about "why overrides are dangerous" here #13681

Hi !

OK I will modify PR to use hook

**Comment by ksaandev** [comment]
@matks I have updated PR https://github.com/PrestaShop/PrestaShop/pull/19830 see actionCheckoutRender
