### ISSUE TITLE
Bug classification question

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#19861]
Why did you create a bug classification, when nobody follows it?

https://build.prestashop.com/news/severity-classification/

Are filters on employee page not working really that critical that it needs to be fixed asap? 🙄
  https://github.com/PrestaShop/PrestaShop/issues/19812

There are huge bugs regarding display of prices, gifts, even browsing products has issues that are not fixed for more than 2 years. 

Can you give some insight into this? I really don't understand it and I think I can speak for the majority of merchants and web agencies.

There are really not THAT much bugs in FO. If it was fixed, every merchant could have a peace of mind and just do business. The BO could be fixed in next century and nobody would care and be mad. We can always fix something manually in database or program a custom tool or script to do some actions that are not working.

**Comment by PululuK** [comment]
Thank you very much, it comforts me, I thought I was the only one.
Prestashop are very inconsistent in what they say and what they do.

Example
https://build.prestashop.com/news/open-question-not-commiting-assets-anymore/

I am discouraged 🤔

But I can understand, it is very difficult to stay focused when you are surrounded by : https://drive.google.com/file/d/1SCQs7x0h__N0yYjZxZ8DGzR4cwr-T6oB/view

**Comment by matks** [comment]
Actually we are 100% following our own criteria.
Bug https://github.com/PrestaShop/PrestaShop/issues/19812 is labeled critical because `It can lead to data loss, introduce a security vulnerability or break the automatic end to end tests`

The 3rd part applies here. Our automatic end-to-end tests have reported this issue and we have applied the right label.
This is why the label `Detected by TE` is applied too.

**Comment by matks** [comment]
We also follow 100% https://build.prestashop.com/news/open-question-not-commiting-assets-anymore/ on `develop` branch.

Next time you see something strange, before saying "Prestashop are very inconsistent in what they say and what they do." maybe you can simply ask (on our Slack channel https://github.com/PrestaShop/open-source/tree/master/slack for example) about it and we'll provide a valid explanation 😉

**Comment by matks** [comment]
No answer from author since 2 days, I believe my answer was complete enough 😊 so I close this issue. Feel free to tell me if I'm wrong (or open another issue or come discuss on the Slack !)

**Comment by PululuK** [comment]
> No answer from author since 2 days, I believe my answer was complete enough  so I close this issue. Feel free to tell me if I'm wrong (or open another issue or come discuss on the Slack !)

So two days without any response you close the issue 🤔 ?

**Comment by matks** [comment]
> > No answer from author since 2 days, I believe my answer was complete enough  so I close this issue. Feel free to tell me if I'm wrong (or open another issue or come discuss on the Slack !)
> 
> So two days without any response you close the issue 🤔 ?

In theory we do not answer questions on GitHub as it is a bug tracker / feature tracker for us. I did an exception here 😄 

When people open bug reports or feature requests, if there is a missing information in it we ask for it and apply the "NMI" (Need More Information) label. If we get no answer in 30 days we close the issue as it seems it wont go anywhere and it's needed to keep our backlog clean to stay efficient.

Here it's the same for me. I provided an answer, looks like no other items need to be answered, so I close the issue.

It **does not mean I close the discussion**. The discussion can keep going on in this issue, in another issue or in another channel (Slack ? twitter ? mail ?). And closing an issue is not the end of all. An issue can be reopened ! But if the item seems like it does not _need_ to stay opened I close it. Because we have a backlog here. A backlog must be managed so we are efficient. We try to have only "todo" issues opened. A "todo" issue is something that needs an action to be solved, be it a feature request or a bug report.

Here in this issue it seems there is no such action needed 😉 so I close the issue in order to help keeping the backlog clean and efficient

**Comment by PululuK** [comment]
> > > No answer from author since 2 days, I believe my answer was complete enough  so I close this issue. Feel free to tell me if I'm wrong (or open another issue or come discuss on the Slack !)
> > 
> > 
> > So two days without any response you close the issue thinking ?
> 
> In theory we do not answer questions on GitHub as it is a bug tracker / feature tracker for us. I did an exception here 
> 
> When people open bug reports or feature requests, if there is a missing information in it we ask for it and apply the "NMI" (Need More Information) label. If we get no answer in 30 days we close the issue as it seems it wont go anywhere and it's needed to keep our backlog clean to stay efficient.
> 
> Here it's the same for me. I provided an answer, looks like no other items need to be answered, so I close the issue.
> 
> It **does not mean I close the discussion**. The discussion can keep going on in this issue, in another issue or in another channel (Slack ? twitter ? mail ?). And closing an issue is not the end of all. An issue can be reopened ! But if the item seems like it does not _need_ to stay opened I close it. Because we have a backlog here. A backlog must be managed so we are efficient. We try to have only "todo" issues opened. A "todo" issue is something that needs an action to be solved, be it a feature request or a bug report.
> 
> Here in this issue it seems there is no such action needed  so I close the issue in order to help keeping the backlog clean and efficient

Ok @matks  !
