### ISSUE TITLE
Total discount wrong with multiple same gift from cart rules

### ISSUE THREAD

**Issue by CT-Web** [PrestaShop/PrestaShop#19862]
#### Describe the bug

When I add multiple cart rules to add the same product gift repeatedly, the discount is not ok : 
- RULE 1 : 1 gift for each order > 0€ => total discount is OK if the only rule applied is this one
- RULE 2 : same gift as RULE 1 for each order >= 50€ :  total discount is NOK if this rule is applied. The customer has to pay 50% of one of the gift.
- RULE 3 : same gift again for each order >= 50€ : total NOT. The client has to pay 33% of one of the 2nd gift and a mysterious part of the 3rd... 

#### Expected behavior

Each gift must be free ^^

#### Steps to Reproduce

Create 3 rules that offer the same gift. And try to have the 3 gift for free.

**Screenshots**
Exemple with only one  rule, every thing is ok 
![image](https://user-images.githubusercontent.com/17764379/85069881-24092f00-b1b5-11ea-85b0-90021b5ba3f6.png)

Exemple with 2 rules applied,  there is an extra of 0.25€ 
![image](https://user-images.githubusercontent.com/17764379/85069594-afce8b80-b1b4-11ea-98b6-cdc46d0eea77.png)

Exemple with the 3 rules applied,  there is an extra of 0.44€ 
![image](https://user-images.githubusercontent.com/17764379/85069323-36369d80-b1b4-11ea-9282-695862fadf8c.png)

#### Additional information
I found a solution to correct this issue. I edit the src/Core/Cart/CartRuleCalculator.php

Just before the application of the free gift in applyCartRule(), i force the cart_quantity to 1 

```
$data = $cartRow->getRowData();
$data['cart_quantity'] = 1;
$cartRow->setRowData($data);

$cartRuleData->addDiscountApplied($cartRow->getFinalUnitPrice());
$cartRow->applyFlatDiscount($cartRow->getFinalUnitPrice());
```
It's not very elegant, but it works. 

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.31

**Comment by florine2623** [comment]
Hi @CT-Web ,
Indeed, I manage to reproduce your issue in PS 1.7.6.5. However this bug has been fixed in PS 1.7.7.0. I would advise you to wait for the release candidate to upgrade your shop.

In PS 1.7.6.5 :
![Capture d’écran 2020-06-19 à 10 24 25](https://user-images.githubusercontent.com/16019289/85113181-2b612480-b217-11ea-98b3-ece0538518fb.png)

In PS 1.7.7.0 :
![Capture d’écran 2020-06-19 à 10 24 32](https://user-images.githubusercontent.com/16019289/85113169-27cd9d80-b217-11ea-92db-802fa44ba7a5.png)

Thanks!
