### ISSUE TITLE
Payment modules are not compatible with PrestaShop

### ISSUE THREAD

**Issue by margud** [PrestaShop/PrestaShop#19874]
#### Is your feature request related to a problem?

Most payment modules use third party pages to finish payment. If customer decides to return to checkout and select different payment the cart is already gone because PrestaShop creates order when payment is selected and because of that merchants are not happy because it effects their sales. If we try to create order after payment is made in some cases customer might pay for product that is already out of stock.

For example when you use Mollie module and select one of their payment you get redirected to Mollie page where you need to finish your payment but if customer selects wrong payment and wants to return to checkout too choose new payment method the cart is gone because the order is already created.
#### Describe the solution you'd like

We tried to create order after payment but we had issues when people pay for product that is already out of stock because some one else bought it.

#### Alternatives you've considered

I still don't know any alternatives.

**Comment by florine2623** [comment]
Hi @margud ,
It seems like your issue is not with payment modules, but more with the availability of your products.
You can go to each product page and make sure that you allow or not the orders when you don't have any stock available :
![Capture d’écran 2020-06-19 à 17 17 54](https://user-images.githubusercontent.com/16019289/85148921-fe316800-b250-11ea-9573-78125696abce.png)
You can also check in BO > Shop Parameters > Products > Product Settings :
![Capture d’écran 2020-06-19 à 17 20 45](https://user-images.githubusercontent.com/16019289/85149132-3b95f580-b251-11ea-95d6-e08733522e39.png)

If you have an improvement to suggest to Mollie, please contact them directly.
On GitHub PrestaShop, we only take care of PrestaShop Core, not external modules.
Thanks!
