### ISSUE TITLE
emails for voucher 

### ISSUE THREAD

**Issue by alexwweiss** [PrestaShop/PrestaShop#19915]
Hello everyone, I have a problem at hand and I need your help.
How can I configure prestashop so that when the customer registers on the site, he automatically receives a discount voucher ??
Another doubt is: when I create a voucher manually and select the customer, the email is not triggered in any way, how can I correct this?

Prestashop: 1.7.6.1

**Comment by prestascott** [comment]
Hi @alexwweiss, thank you for your report!

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- debug mode report
- PHP version
- PHP error logs
- apache error log
- Javascript console log
- screenshots

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you!

**Comment by sarahdib** [comment]
Hello, 

Please be aware that this bug tracker should be used to report issues only. 
If you need help, you can ask on the :
- Forum (https://www.prestashop.com/forums/)
- Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop)

You can also join slack in order to discuss with developer : https://github.com/PrestaShop/open-source/blob/master/slack/readme.md

Thanks for your understanding!
