### ISSUE TITLE
prices visible in the product pack even if in catalog mode it is set to not display prices

### ISSUE THREAD

**Issue by ballashop** [PrestaShop/PrestaShop#19952]
In catalog mode and with hidden prices, a pack product still shows the prices of the individual items that compose it.
is it a bug or is there a setting that I missed?

#### Describe the bug

I able the catalogue mode and disable product price
I created the new pack product
When I show the product page I see the single product price.
<img width="1362" alt="Schermata 2020-06-26 alle 12 49 41" src="https://user-images.githubusercontent.com/28685316/85849604-8a8cdf00-b7ab-11ea-946d-fdfadcda8266.png">

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.1.32

Thanks for any reply.
Balla

**Comment by florine2623** [comment]
Hi @ballashop ,
Thanks for the report.
This has been fixed in PS 1.7.7 :
![Capture d’écran 2020-06-26 à 14 25 39](https://user-images.githubusercontent.com/16019289/85856799-ee69d480-b7b8-11ea-9844-4af332f43e9b.png)
I would advise you to wait for the release candidate to be approved, and then you will be able to update your shop !
I close your issue as it is fixed.
Thanks!

**Comment by ballashop** [comment]
Hi @florine2623,
thanks for replying so quickly.
Ok, we are waiting.
Thanks.
Balla
