### ISSUE TITLE
Module update not available on official repo - statslive and ps_contactinfo

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#20005]
The back office shows me that there is an update available, but it is not available in the repository. I would like to see the changes.
Is it possible that you forgot to publish the release?

I have found these 2

Name           | Update          | Lastest release | Repository                                   |
---------------|-----------------|-----------------|----------------------------------------------|
statslive      | v2.0.2 → v2.1.0 | v2.0.2          | https://github.com/PrestaShop/statslive      |
ps_contactinfo | v3.2.0 → v3.3.0 | v3.2.0          | https://github.com/PrestaShop/ps_contactinfo |

**Comment by matks** [comment]
> The back office shows me that there is an update available, but it is not available in the repository. I would like to see the changes.
> Is it possible that you forgot to publish the release?
Yes we forgot 😞 

We merged `dev` into `master in these PRs https://github.com/PrestaShop/statslive/pull/8 and https://github.com/PrestaShop/ps_contactinfo/pull/26 but we forgot to create the GitHub releases. This does not impact how the module is being distributed by PrestaShop Addons API, which is why it appears in the BO.

Thank you for telling us this feedback 😉 

We are still doing too much work manually when releasing a module which means sometimes we forget something. We need to automatize more and more and more 😄

**Comment by matks** [comment]
I will do the releases tomorrow morning. It's not a good idea to release stuff at 11pm 😅

**Comment by matks** [comment]
Releases have been created
https://github.com/PrestaShop/ps_contactinfo/releases/tag/v3.3.0
https://github.com/PrestaShop/statslive/releases/tag/v2.1.0

Thank you @davidglezz
