### ISSUE TITLE
Le serveur a renvoyé une "500 erreur de serveur interne".

### ISSUE THREAD

**Issue by sylva31** [PrestaShop/PrestaShop#20008]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by LouiseBonnard** [comment]
Hi @sylva31, this issue is void so I close it. Feel free to open a new one if need be, with a full description of the problem encountered (in English).

Need help? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/), thank you very much!
