### ISSUE TITLE
Bug lors de la mise à jour vers Prestashop 1.7.6.5

### ISSUE THREAD

**Issue by malodeco** [PrestaShop/PrestaShop#20015]
J'ai un message d'erreur qui apparaît lorsque je fais la mise à jour du module "Module 1-Click Upgrade" vers Prestashop 1.7.6.5

1. J'ai téléchargé le Module 1-Click Upgrade
2. Je cherche le module dans mon catalogue et je clique sur "Upgrade Prestashop Now! " 
3. Le téléchargement commence
4. Puis j'ai un message qui apparaît dans mon journal d'activité : "Sauvegarde des fichiers en cours. Encore 30908 fichiers.
[Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:" " jqXHR: "
500 Server Error
Oops, something went wrong.

Try to refresh this page or feel free to contact us if the problem persists." 

Je précise que je ne m'y connais pas du tout en programmation etc... donc si vous pouvez m'expliquer avec des mots simples je vous en serais très reconnaissante. 

Merci d'avance ! 

![Capture 10](https://user-images.githubusercontent.com/67692415/86247757-3a4bbd80-bbad-11ea-81f9-81ca4cd72b53.JPG)

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: N/A

![Capture 11](https://user-images.githubusercontent.com/67692415/86247876-65cea800-bbad-11ea-9d0e-d85b65f7f40a.JPG)

**Comment by LouiseBonnard** [comment]
Hello @malodeco, thanks for the report. Could you please send your request in English? English is the norm on GitHub since it allows anyone to work on your issue, thank you very much in advance.

Also, can you give more details regarding this issue? It will help us understand if this is a bug or if you should reach the [support](https://www.prestashop.com/support) team. Alternatively, you can also ask for help in the community forums, click [here](https://www.prestashop.com/forums/forum/18-forum-francophone) to access the French-speaking forum.

**Comment by sarahdib** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
