### ISSUE TITLE
SEO not updating when filling product, meta description disappearing after page refresh

### ISSUE THREAD

**Issue by dorianelucas** [PrestaShop/PrestaShop#20030]
#### Describe the bug

Hello,
I'm updating product and SEO description title + meta description. I filled them in FR and GB, save it but when I go back to the page later on, all infos disappeared ! I tried on Chrome and Firefox (sometimes that helps), but infos don't stay. What can I do?

#### Expected behavior

I 'd the infos I just filled and saved to stay on the SEO description page.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![86361312-ef48ad80-bc73-11ea-83f3-64af7708134e](https://user-images.githubusercontent.com/3034677/86785611-30b9ce00-c063-11ea-8522-9313ff9b1c36.png)

#### Additional information

* PrestaShop version: 1.7.2.4
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @dorianelucas ,
Please change your admin folder name. This is a public space, let's be safe.
I can't reproduce your issue on PS 1.7.2.4.
Please open the console and check for errors. Right click > Inspect > Console
Or check your log file if there are any fatal errors.
Thanks!

**Comment by dorianelucas** [comment]
Hi,
Thank you for your reply. I checked the Console and this is what appears :
![86368669-b7defe80-bc7d-11ea-9b1a-2dcba5870124](https://user-images.githubusercontent.com/3034677/86785809-79718700-c063-11ea-976e-9af18593c74b.png)

**Comment by florine2623** [comment]
Enable debug mode and re-do the steps and see if errors appear

**Comment by dorianelucas** [comment]
Ok, where do I enable "debug mode"? on Google Chrome or Prestashop?

**Comment by florine2623** [comment]
On PrestaShop, Advanced Parameters > Performances

**Comment by dorianelucas** [comment]
Ok I did, but it still doesn't stay when I refresh
![86379680-6e95ab80-bc8b-11ea-9374-2a4fbf75e5fc](https://user-images.githubusercontent.com/3034677/86785976-ab82e900-c063-11ea-9d47-e43e2f512591.png)


Can I  do something else?

**Comment by florine2623** [comment]
Check your log file in /var/log to check for fatal errors
Do not forget to change your admin folder.

**Comment by sarahdib** [comment]
Hello @dorianelucas 

Please be carful when you submitting screenshots, your BO link is visible. 
I edit all of them. 
Like @florine2623 said don't forget to change your admin folder for **security reason**.

Despite our efforts, we were not able to reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans: https://www.prestashop.com/support

Alternatively, you can also ask for help in the community forums: https://www.prestashop.com/forums/

Thank you!
