### ISSUE TITLE
1.7.7.0 Beta - Unexpected error after disabling "Debug mode".

### ISSUE THREAD

**Issue by k0lv** [PrestaShop/PrestaShop#20064]
I have disabled Debug mode in Performance tab, and not able to open Back-office. Getting error:

"You have requested a non-existent service "mbo.tab.collection.provider".
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException 0]"

![image](https://user-images.githubusercontent.com/59282576/86533438-f53fc800-bed9-11ea-8a5d-56d74078d6d9.png)

**Solution: Push the button "Enable debug mode"**

**Comment by k0lv** [comment]
Sorry, duplicate to #19741

**Comment by tayfun476** [comment]
Hello Community!
I'd like to share my experience with debugging a session service error in my PrestaShop module.

Error Description:

I was encountering the following error message in my PrestaShop module due to an unavailable session service:

ServiceNotFoundException
Solution:

I identified the issue as being related to the session service's definition or invocation. Upon examining the getSession method, I discovered that the session service was either missing or incorrectly defined. I updated the method as follows:

PHP
public function getSession()
{
  $container = $this->getCoreServiceContainer();
  if ($container) {
    if ($container->has('session')) {
      $session = $container->get('session');
      return $session;
    } else {
      $this->getLogger()->warning('Session service not found, using fallback session.');
      return new \PrestaShop\Module\PsAccounts\Session\FallbackSession(
        $this->getService(\PrestaShop\Module\PsAccounts\Adapter\Configuration::class)
      );
    }
  } else {
    $this->getLogger()->warning('Core service container not found, using fallback session.');
      return new \PrestaShop\Module\PsAccounts\Session\FallbackSession(
      $this->getService(\PrestaShop\Module\PsAccounts\Adapter\Configuration::class)
    );
  }
}
Kodu [dikkatli](https://github.com/faq#coding) kullanın.
content_copy
This modification resolved the error by creating and utilizing a fallback session when the session service was unavailable. Additionally, I corrected a typo in the getLogger method:

PHP
public function getLogger()
{
  return $this->getService('ps_accounts.logger');
}
Kodu [dikkatli](https://github.com/faq#coding) kullanın.
content_copy
Conclusion:

I hope this solution proves helpful to others encountering a similar issue.

Additional Notes:


Feel free to reach out if you have any questions or comments.
Happy coding!

[ps_accounts.zip](https://github.com/user-attachments/files/15544024/ps_accounts.zip)
