### ISSUE TITLE
[BO] - Category root displayed after filter 

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#20067]
#### Describe the bug

When you filter categories by `name=root` or `displayed=Yes`, category root is displayed (unwanted behavior after the fix in #17399 )

#### Expected behavior

Category root not displayed

#### Steps to Reproduce

1. Go to 'BO -> categories page'
2. Filter by displayed = Yes
3. See result
![image](https://user-images.githubusercontent.com/48441421/86572523-5b2c5e00-bf73-11ea-9d06-2291087f790f.png)

#### Additional information

* PrestaShop version: branch 1.7.7.x
* PHP version: 7.2

**Comment by matks** [comment]
Note: this actually makes sense 😁 : you ask "show me all active categories" and "Root" IS an active category.

It also works if you search "Root" ("Racine" in French) as category name, you'll find the "Root" category as a search result because, well, you searched for it.

But I get the idea 😄 I will remove "Root" category from search results.

**Comment by matks** [comment]
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/20433

**Comment by Progi1984** [comment]
Fixed by #20433
