### ISSUE TITLE
Regenerating core.js

### ISSUE THREAD

**Issue by gyan111** [PrestaShop/PrestaShop#20061]
If we want to change some core code like cart.js etc, we have to modify the js file and recompile to get a new core.js file. (I may be wrong but this is what I have found so far).

Is there anyway to regenerate without command line?
As on shared server there is no access to the command line.

**Comment by kpodemski** [comment]
The thing is, that you should never ever touch core.js :) 

Maybe tell us what are you trying to do :)

**Comment by gyan111** [comment]
I am trying to send additional data when add to cart button is clicked.

**Comment by kpodemski** [comment]
Ok!

Take a look here:
https://devdocs.prestashop.com/1.7/themes/reference/javascript-events/

and here:
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/cart.js#L85

as you can see after clicking add-to-cart button form is sent to target URL

**Comment by sarahdib** [comment]
Hello, 

Please be aware that this bug tracker should be used to report issues only. 
If you need help, you can ask on the :
- Forum (https://www.prestashop.com/forums/)
- Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop)

You can also join slack in order to discuss with developer : https://github.com/PrestaShop/open-source/blob/master/slack/readme.md

Thank you @kpodemski :) 

Thanks for your understanding!
