### ISSUE TITLE
es-AR translations errors

### ISSUE THREAD

**Issue by mescalitog** [PrestaShop/PrestaShop#20088]
#### Describe the bug

There are some translations mistakes in es-AR

in  ShopThemeCheckout.es-AR.xlf
```
      <trans-unit id="96b0141273eabab320119c467cdcaf17" approved="yes">
        <source>Total</source>
        <target state="final">Total con IVA</target>
        <note>Line: 395</note>
      </trans-unit>
```
should be 

```
      <trans-unit id="96b0141273eabab320119c467cdcaf17" approved="yes">
        <source>Total</source>
        <target state="final">Total</target>
        <note>Line: 395</note>
      </trans-unit>
```

With the original file, in the checkout when the prices are displayed without taxes the legend incorrectly say

**Total con IVA (sin IVA)**

#### Expected behavior

In the checkout view Total (with or without taxes) 

#### Steps to Reproduce

It´s happen all the time 

**Screenshots**

![image](https://user-images.githubusercontent.com/10231443/86801049-03acf180-c04a-11ea-8abe-7abe114bc72a.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1.33

**Comment by marionf** [comment]
Hello, 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

- Language and country chosen during shop installation
- In International > Taxes, taxes are enabled or disabled ?
- How is configured the customer's group in Shop parameters > Customers settings > Groups: Display tax price incl or excl ?

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you!

**Comment by mescalitog** [comment]
Hi, thanks for the answer.

* Not sure about "Language and country chosen during shop installation", could be spanish.
* In International > Taxes (with taxes disabled in customer´s groups) 
** if taxes are enabled the label is "Total con IVA (IVA incl.)" (something like Total with taxes (Tax Included).
![image](https://user-images.githubusercontent.com/10231443/86916795-81c8d100-c0fa-11ea-8690-c14dd7d451ef.png)
** if taxes are disabled the label is "Total con IVA" (Total with Taxes)
![image](https://user-images.githubusercontent.com/10231443/86916826-8db49300-c0fa-11ea-96ba-9fcda1cf9346.png)
* In customer's group in Shop parameters > Customers settings > Groups (with taxes enabled international > taxes)
** if taxes are enabled the label is "Total con IVA (IVA incl.)"
![image](https://user-images.githubusercontent.com/10231443/86916985-c81e3000-c0fa-11ea-8798-806e420634bb.png)
** if taxes are disabled the label is "Total con IVA (sin IVA)"
![image](https://user-images.githubusercontent.com/10231443/86917193-0fa4bc00-c0fb-11ea-9b71-ef065c00884b.png)

**Comment by prestascott** [comment]
Hi @mescalitog, thank you for you report!

@Junebyun Can you take a look at this issue please?

**Comment by LouiseBonnard** [comment]
Hi @mescalitog, thanks a lot for bringing this issue! For global translation errors, please go to the Spanish (Argentina) project on [Crowdin](https://crowdin.com/project/prestashop-official/es-AR) and subscribe to suggest a more accurate translation. @Junebyun here will be there to onboard you and help you find the original Spanish (AR) translation of the wording mentioned here. ;-)

If you need a more customized translation, know that you can edit it in the International > Translations section of your back office. @mescalitog, @Junebyun, I let you guys close this issue when it is fixed on Crowdin!

**Comment by Junebyun** [comment]
Hi @mescalitog ! I tried to reproduce the bug but I got different results:

- In International > Taxes: **Enabled** + in Shop parameters > Customers settings > Groups > Price display method : **Tax Incl.** 
![image](https://user-images.githubusercontent.com/64894223/87767857-96ece080-c81b-11ea-872c-d55649412b20.png)

- In International > Taxes: **Enabled** + in Shop parameters > Customers settings > Groups > Price display method : **Tax Excl.** 
**ES - AR**
![image](https://user-images.githubusercontent.com/64894223/87768263-27c3bc00-c81c-11ea-9ded-5d6a4dc5a259.png)
**ENG**
![image](https://user-images.githubusercontent.com/64894223/87769225-9ce3c100-c81d-11ea-9381-9b40eb8edc8e.png)


- In International > Taxes: **Disabled** + in Shop parameters > Customers settings > Groups > Price display method : **Tax Incl.** 
![image](https://user-images.githubusercontent.com/64894223/87768553-99036f00-c81c-11ea-878b-379ecb87e271.png)


- In International > Taxes: **Disabled** + in Shop parameters > Customers settings > Groups > Price display method : **Tax Excl.** 
![image](https://user-images.githubusercontent.com/64894223/87768447-6b1e2a80-c81c-11ea-8965-ab150dda6c99.png)

The problem here is when you are in the scenario: 
International > Taxes: **Enabled** + in Shop parameters > Customers settings > Groups > Price display method : **Tax Excl.** 

To fix this, you can suggest a more accurate translation in the ES AR PrestaShop project on Crowdin in Shop > Theme > Checkout file or change in your shop's BO in International > Translations > select Themes translations and then Shop > Theme > Checkout. 
I think changing the ES-AR translation of _Total con IVA_ to simply _Total_ for the English string "_Total_" will do the trick. 

This was the result I had after changing the translation:
![image](https://user-images.githubusercontent.com/64894223/87771296-74a99180-c820-11ea-9b77-a27572210298.png)

I hope this solves your problem, let me know once you have made translation suggestions on Crowdin so that I can close this issue! ;)

**Comment by mescalitog** [comment]
Thanks @Junebyun 
Your description describe exactly my issue
I manage to fix my issue modifying "Total con Iva" by "Total" in this files:
* app/Resources/translations/es-AR/ShopThemeCheckout.es-AR.xlf
* app/Resources/translations/es-AR/ShopPdf.es-AR.xlf
* app/Resources/translations/es-AR/AdminGlobal.es-AR.xlf
because couldn't find all ocurrences of "Total con Iva" in BO translations.
I would make the suggestion on Crowdin

**Comment by Junebyun** [comment]
Hi @mescalitog I have approved your translation suggestion on Crowdin! Thank you :)
