### ISSUE TITLE
Product default supplier reference is not updated

### ISSUE THREAD

**Issue by simondaigre** [PrestaShop/PrestaShop#20094]
#### Describe the bug

When updating a product, supplier_reference attribute should be updated with the reference from default supplier.

This was fixed by https://github.com/PrestaShop/PrestaShop/pull/11175 last year, but broken by https://github.com/PrestaShop/PrestaShop/commit/29bda43a552316fb4a29c60f44ff287230bce62f#diff-7d7493bae4eba5d548b7f7f88d16d7ea

This field is used by some ERP connectors.

@PierreRambaud what do you think ?

#### Expected behavior

Product supplier reference should be updated

#### Steps to Reproduce

Create a product, add a product supplier with reference, edit supplier reference.

**Comment by marionf** [comment]
Hello @simondaigre 

I can't reproduce the issue with the provided informations, here are the steps I followed:

1. Go to the BO > Catalog > Brands & Suppliers > Supplier > Create a new supplier & enable it
2. Go to Products > Add a product, enter the product name
3. Click on Options tab, select the supplier created before
4. Enter the supplier reference & save
5. Edit the product, click on options tab, edit the supplier reference & save
6. Refresh the page, the supplier reference is well updated

Could you please provide us the exact steps to reproduce the issue ? And the PrestaShop version ?

Thank you!

**Comment by simondaigre** [comment]
Hi @marionf 

The attribute `supplier_reference` is not updated in database, it should be filled with default supplier reference.

Tested with PS 1.7.6.5.

**Comment by florine2623** [comment]
Hi @simondaigre ,
When modifying the supplier reference in the product page, it is updated in the table `ps_product_supplier` in attribute `product_supplier_reference`.

**Comment by simondaigre** [comment]
@florine2623 yes, and `supplier_reference` in `ps_product` table should also be updated with default supplier reference.
This was confirmed by QA in https://github.com/PrestaShop/PrestaShop/pull/11175.

**Comment by florine2623** [comment]
Ok thanks for the clarification.
Indeed the issue is present.
I manage to reproduce the issue in PS 1.7.7.0 and PS 1.7.6.5.

1. Go to the BO > Catalog > Brands & Suppliers > Supplier > Create a new supplier & enable it
2. Go to Products > Add a product, enter the product name
3. Click on Options tab, select the supplier created before
4. Enter the supplier reference & save
5. Edit the product, click on options tab, edit the supplier reference & save
6. Refresh the page, the supplier reference is well updated
7. Go to database, table `ps_product` in `supplier_reference`
8. No data is saved

Your issue will be added to our debug roadmap, if you have a PR, please link it here !
Thanks!

**Comment by rajat315315** [comment]
I cannot see any supplier reference field in options tab while creating a new product. I am in branch 1.7.7.x

**Comment by PierreRambaud** [comment]
After investigation, I think the `supplier_reference` is a deprecated attribute in the database. 
Everything is managed by the `ProductSupplier` Object Model since the 1.5.0, I also see deprecated annotation about the supplier_reference https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Product.php#L1626  :thinking: 
Since the data is already stored in the `ProductSupplier` table, it seems illogical to duplicate the value in another table.

**Comment by PierreRambaud** [comment]
After more investigation, what should be the value of `supplier_reference` in the product if you have this:
![image](https://user-images.githubusercontent.com/1462701/87325684-0f108900-c532-11ea-9e05-cb493aa24424.png)


I really think this field is deprecated and must be removed :/

**Comment by marionf** [comment]
To do: Mark supplier_reference as deprecated

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20198

**Comment by karacsonattila** [comment]
Hi guys,

I have a problem, when i check or uncheck a supplier the earlier datas will remove from input.
Can you tell me in which file can i edit the supplier ajax in option tab.

This one: /sell/catalog/products/suppliers/refresh-product-supplier-combination-form/

Thank

**Comment by Flo340** [comment]
> 

Did you find a solution?

**Comment by Flo340** [comment]
> Hi guys,
> 
> I have a problem, when i check or uncheck a supplier the earlier datas will remove from input. Can you tell me in which file can i edit the supplier ajax in option tab.
> 
> This one: /sell/catalog/products/suppliers/refresh-product-supplier-combination-form/
> 
> Thank

Did you find a solution?

**Comment by arLevi** [comment]
> Hi guys,
> 
> I have a problem, when i check or uncheck a supplier the earlier datas will remove from input. Can you tell me in which file can i edit the supplier ajax in option tab.
> 
> This one: /sell/catalog/products/suppliers/refresh-product-supplier-combination-form/
> 
> Thank

Did you find a solution for the combination options ?
I'm able to see "supplier reference" only in "simple product"
