### ISSUE TITLE
Link list module in left/right column

### ISSUE THREAD

**Issue by TVBZ** [PrestaShop/PrestaShop#20100]
#### Is your feature request related to a problem?

When transplanting the link widget to left or right column (for example on cms page), the blocks are created as columns inside the left/right column.

![image](https://user-images.githubusercontent.com/43469713/86911001-d8de9e00-c11a-11ea-91df-d9914a2052c2.png)

#### Describe the solution you'd like

In left/right column, the different link blocks should just be above eacht other, in a single column.
Maybe a different template file depending on the hook the module is in?

#### Additional context

Working in PS 1.7.6.5

**Comment by marionf** [comment]
Hello, 

I was able to reproduce the issue with PrestaShop 1.7.7.0

![capture d'écran_2709](https://user-images.githubusercontent.com/13449658/86924461-cb7fde80-c12f-11ea-85d1-4ddad6b35c43.png)

I’ll add this to the debug backlog so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please send us a pull request!

Thank you!

**Comment by TVBZ** [comment]
@marionf I worked around the issue with only a few lines of css:

```
#left-column .links {
    float: none;
    width: 100%;
}

#left-column .links .wrapper {
    width: 100%;
    padding: 0;
    margin-bottom: 2rem;
}
```

But it would probably be better to have seperate .tpl for the left/right column.
It would allow some other improvements like heading format.

Cheers
