### ISSUE TITLE
after initial install - no shop on OSX

### ISSUE THREAD

**Issue by matt-matt1** [PrestaShop/PrestaShop#20154]
My computer:
I have successfully installed and can fully use PS 1.7.6 on Ubuntu.  On the same computer, ie. same hardware, I also have an installation of OSX and cannot get the shop to launch after installation.

What I've tried:
Since I have successfully installed; and launched; then made configuration changes (eg. cache, HTTPS), and relaunched; and continued interactions with Ubuntu, I will no longer mention this platform.
I tried with several versions of PS 1.7, including the developers version.
My OSX is installed with brew (something like apt or yum and systemctl for mac).  This keeps Apache, PHP, etc. the latest version.  Many other AMP software such as Wordpress, Joomla, PhpMyAdmin and several others work completely.

I realize that most (probably all) production web servers are built with Linux or Windows.  So this issue is not a major issue, but prevents absolute deployment of all computers.

Actually happens:
When I attempt to open the shop, in a browser, in wants to download the index.php file.  (Someone had a similar issue, but guess it was a Linux machine.  His solution with to switch from using PHP 5.6 to PHP 7.0).  It seems the server won't execute PHP...
Also dynamic links - like where the URL ends with a language code (eg. .../en/) results in 403 Forbidden.
Just to be certain I create DB + user (with PhpMyAdmin); download and extract the zip; install (pink/blue shop animation); then the assistant install launches with steps like language, database name, actual install with progress bar are all successful.  Problems arise after all that, when trying to get to any page in either front end or back end of the store.

**Comment by matks** [comment]
> I realize that most (probably all) production web servers are built with Linux or Windows. So this issue is not a major 
> When I attempt to open the shop, in a browser, in wants to download the index.php file. (Someone had a similar issue, but guess it was a Linux machine. His solution with to switch from using PHP 5.6 to PHP 7.0). It seems the server won't execute PHP...

When you request an index.php file and your browser starts downloading it, it means the webserver did not understand this is an executable file. So it might indicate an issue in Apache configuration. Just like you I use homebrew to run PrestaShop and everything runs very fine.

I suggest having a look on Google with searches like "[apache downloads php instead of executing](https://www.google.com/search?q=apache+downloads+php+instead+of+executing&oq=apache+downloads+php&aqs=chrome.0.0j69i57j0l3.3817j0j7&sourceid=chrome&ie=UTF-8)", but I am quite certain this issue does not come from PrestaShop. PrestaShop does nothing exotic on server side, this is a very standard PHP setup with Apache and PHP coming together.

You might want to look at our Docker images for setup examples => https://github.com/PrestaShop/docker

**Comment by matks** [comment]
I close this issue as I think I provided a complete answer. Feel free to open another issue if you have a tangible (= we can reproduce) issue.

**Comment by matt-matt1** [comment]
@Mathieu Ferment: Where’s the answer?

**Comment by matks** [comment]
Open your eyes 😄   I wrote only 2 messages here https://github.com/PrestaShop/PrestaShop/issues/20154

**Comment by matt-matt1** [comment]
OK got it!  Thanks.  Repaired it
