### ISSUE TITLE
Problem enabling Payment Method for carriers Prestashop 1.7.6.7

### ISSUE THREAD

**Issue by Mariooti** [PrestaShop/PrestaShop#20173]
I have had endless problems with a Prestashop installation.  Every day there is a new problem.

I am unable to enable/select and save the payment methods in carrier restrictions.  I select all payment options for all carriers (paypal, Stripe, Credit Card Gateway etc) and when I save it only picks a few on the first line and nothing else. 

![pay4ship](https://user-images.githubusercontent.com/68290569/87445882-47cb6380-c601-11ea-9a3f-d4d6cc893afe.png)

I select all except for bank transfer and pay by check as I do not use these and the first two shipping carriers are actually disabled but no matter what I do it refreshes after saving to this.  

If I select all carrier and leave out the first two carrier, it does the same with the selected item being only the first in my selection list.  Stripe is always disabled on save.

I have checked all payment gateways and they are configured correctly - everything was working fine in terms of payment but a develop messed up my shipping module in trying to fix his module so I had to do a fresh install of everything today.

Any help would be greatly appreciated.

 
* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by matks** [comment]
Looks a bit like https://github.com/PrestaShop/PrestaShop/issues/20130

**Comment by prestascott** [comment]
Hi @Mariooti,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20130. To be informed when it's fixed, please subscribe to the issue mentioned above.

I close the ticket.

Thank you!

**Comment by prestascott** [comment]
Duplicate of #20130

**Comment by Mariooti** [comment]
it is not the same issue as the other one, as the carriers do not have the same name.

**Comment by Mariooti** [comment]
> Hi @Mariooti,
> 
> We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20130. To be informed when it's fixed, please subscribe to the issue mentioned above.
> 
> I close the ticket.
> 
> Thank you!

It is a serious issue as it renders the store unusable as people cannot pay and check out.  I hope this issue gets resolved quickly.

My store has over 25000 products so doing a fresh install is not that easy, is there another workaround?

**Comment by prestascott** [comment]
I understand. Is your issue related to this one https://github.com/PrestaShop/PrestaShop/issues/18936?

**Comment by Mariooti** [comment]
I think I solved the problem.  My store has a carrier module linked to all my carriers (DHL, TNT etc) I uninstalled the module and reinstalled it and now all my carriers have payment options enabled.

I hope this solution works for others.

**Comment by prestascott** [comment]
Okay, i'm glad that you solved the problem. Since you've found a solution, i can close this issue.

Thank you :)

**Comment by passio777x** [comment]
I paid a developper who told me he found a bug in the prestashop core after 5-6 hours. He tolds me it was a country related issue... It's possible because I actiavated multishop, added country and I got error when I did this...

**Comment by matks** [comment]
Please consider sharing that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about 😉

**Comment by Mariooti** [comment]
> Please consider sharing that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about 😉

hi matks,

I'm very new to Github, so if you could tell me how to do that I will gladly do it. :)

**Comment by matks** [comment]
You can submit it a Pull Request following these guidelines https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/ 😉 

It's a great opportunity to learn !

**Comment by thmavrosavva** [comment]
Hey @matks , 

I'm colluegues with @Mariooti  and he isn't a web developer or php programmer  :), he said that he just removed (uninstalled) all carriers module and reinstalled the module in prestashop backend.

**Comment by passio777x** [comment]
OH MY GOD I FIND THE ISSUE AFTER 1 WEEK OH MY GOD !!!!

Just add : **max_input_vars = 3000** 
for your server... In my case there was more than 1000 checkboxes on the page and that's why the last checkboxes were not checked... AwWWWWwhhhhhhhhh !!! 1 WEEK FOR THAT

**Comment by matks** [comment]
@passio777x Looks like the developer you paid did not find that 😅

**Comment by matks** [comment]
@passio777x 1000 checkboxes in that page ? How many payment methods and carriers do you have ?! 😮

**Comment by passio777x** [comment]
It was really hard to find... The developper I paid has 5 stars review, 11 years experience and 550 5* reviews (99%)..... But I find myself the problem thanks to him when I realized unchek all checkbox make possible to check the last of them....

How many should i pay him compared to its original bids ? because I find the solution myself, but... thanks to him.

I have 244 countries and 6 carrier in this page... Enough to be >1000.

**Comment by passio777x** [comment]
I have to say 3 developpers surrended, (one after 2 days) and 5 people didntt answered... This issue was the worst nightmare in 7 years of prestashop for me. Including it happened after I activated multishop but also a paiement method... then It made me confuse about problem's origin.

**Comment by passio777x** [comment]
Prestashop should really warn people about this issue in the payment->preferences page because it's a real nightmare.

**Comment by thmavrosavva** [comment]
This is awesome!!!

**Comment by matks** [comment]
> Prestashop should really warn people about this issue in the payment->preferences page because it's a real nightmare.

I am thinking about that, but this situation is very unusual 😄  . And it is complex because issue is in server configuration, not in prestashop. We dont control that.

One idea could be "when one page* has more than 500 form inputs, we display a warning flash message". The Flash message would explain that the form, in order to work properly, require a relevant value of `max_input_vars` on server side. But it's very hard to know which number exactly because modules are free to inject HTML into pages.

What would you think of that ?

Another idea would be to write into developer documentation http://devdocs.prestashop.com/ this trick, but where exactly ? 😄

**Comment by Mariooti** [comment]
I am not a developer or a programmer but I have been using Prestashop for more than 4 years now.  I like to enrich my store with as many options for the clients as possible (sometimes this is good and sometimes not).  But if I can add my 5c worth from the perspective of a user and not a developer.

I assume that most developers, when making a module, make it to work on a stand alone version of Prestashop, as can clearly be seen when you see the demo shops for their modules.  However I don't think there is a shop out there with only 1 module or only modules from 1 developer.  So it is important that developers see how their module will impact other modules as well.  Perhaps Prestaship should have one installation with every single module installed to see how each affect each other.

I have spent a small fortune paying "experts" to fix little problems that are a direct result of one or another module. And if there is ever an update I tremble to see if this update will undo all my little fixes.  As a store owner, we want to stay current with our software, but most importantly, we want to be online and working 24/7.

I am the type of person who reads the user guide from start to finish, and in most cases I ask the developer questions before I buy a module.  Yet to date only one module developer (of the modules I have purchased) has given me a list of server settings and requirements in detail.

We need to respect that Prestashop is open source, thus free and yet also respect that we spent money, sometimes a lot, on extra modules and developers to make our sites work just they way we want them to.

There needs to be a balance of understanding, one to allow users to have an easier experience, and secondly to allow them to gain the trust in the modules available not to destroy or make their sites not function as needed.

I hope this made sense.   

I also want to thank the people on Github, and other forums, who often offer more help about problems than module developers do.  A big thank you to all of you for taking your time to help us.

**Comment by matks** [comment]
Hi @Mariooti 

First of all, thank you for this very valuable feedback. Not everybody takes the time to write about their issues in such a polite and constructive manner 😄 

> I assume that most developers, when making a module, make it to work on a stand alone version of Prestashop, as can clearly be seen when you see the demo shops for their modules. However I don't think there is a shop out there with only 1 module or only modules from 1 developer. So it is important that developers see how their module will impact other modules as well. Perhaps Prestaship should have one installation with every single module installed to see how each affect each other.
> 
> I have spent a small fortune paying "experts" to fix little problems that are a direct result of one or another module. And if there is ever an update I tremble to see if this update will undo all my little fixes. As a store owner, we want to stay current with our software, but most importantly, we want to be online and working 24/7.

You are 100% right and you are refering to an broad issue that has been here since day 1 : compatibility between modules. This is a very complex topic as you can guess but we know it is a big problem.

We have plans for next versions of PrestaShop to improve this topic but these plans will not please everybody.
- to improve server / shop / module compatibility we plan to, in the long term, rely on [Composer](https://github.com/PrestaShop/PrestaShop/issues/12586) as it already has all the necessary features but this will change tremendously how Module Developers work so we expect part of them to dislike this change
- to improve modules compatibility we will probably start "sandboxing" modules, limit how they can interact with the Core to make sure in order to better preserve the shop behavior (you can read about this future [here](https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/)) but this will also reduce the degree of freedom the modules have and, once again, be disliked by some

The "sandbox idea" is not new: this is what Android or iOS do to ensure applications installed on your smartphone do not fight each other.

So it's a dangerous move to do 😄  increase the software stability but upset some module developers, which are key to our business model. We need to do it slowly and help people adopt better ways to avoid a big slashback. We will try to preserve as much as possible the customization capabilities of modules and themes while sandboxing them to preserve the shop best interest. Obviously we will need the help and the feedback of the community - all sides of them : merchants, module developers, theme developers, shop administrators, agencies.

As you have nicely said, this is all about balance:

> There needs to be a balance of understanding, one to allow users to have an easier experience, and secondly to allow them to gain the trust in the modules available not to destroy or make their sites not function as needed.

> I also want to thank the people on Github, and other forums, who often offer more help about problems than module developers do. A big thank you to all of you for taking your time to help us.

It's great to hear ❤️

**Comment by passio777x** [comment]
What is terrible with is issue is that you do not see bottom of country list, and you don't realize this issue also concern bottom of countries checkboxes, because you have to scrolldown to see it...  

This issue is 100% counterintuitive and you don't get any warning or error message.

If you remove a paiement method, or make some test, you can think you fixed the problem but it is only because you reduced the amount of checkboxes in the page. 

**A warning is definitely a good idea.**

**Comment by mrazekrad** [comment]
> OH MY GOD I FIND THE ISSUE AFTER 1 WEEK OH MY GOD !!!!
> 
> Just add : **max_input_vars = 3000** for your server... In my case there was more than 1000 checkboxes on the page and that's why the last checkboxes were not checked... AwWWWWwhhhhhhhhh !!! 1 WEEK FOR THAT

Thank you for sharing... Today, the same problem!!!

**Comment by ChineseNorris** [comment]
> What is terrible with is issue is that you do not see bottom of country list, and you don't realize this issue also concern bottom of countries checkboxes, because you have to scrolldown to see it...
> 
> This issue is 100% counterintuitive and you don't get any warning or error message.
> 
> If you remove a paiement method, or make some test, you can think you fixed the problem but it is only because you reduced the amount of checkboxes in the page.
> 
> **A warning is definitely a good idea.**

Completely agree, in 1.6 at least gives you a blank page which gives you some hints, but just no warnings...

Thank you for sharing the solution

**Comment by Sameye** [comment]
I had same issue and it was indeed related to the max_input_vars limit. Thanks for sharing because I could have search all day.
