### ISSUE TITLE
Guest Order Tracking redirects to shop Homepage when Friendly URLs are disabled

### ISSUE THREAD

**Issue by SuichiM** [PrestaShop/PrestaShop#20194]
#### Describe the bug

I'm using prestashop 1.7.6.5 with the classic theme and  when I want to follow an order as a guest user _(with valids order_id and email)_, the form redirect to the main page. 

#### Expected behavior

Show the order history.

#### Steps to Reproduce

1. Go to 'index.php?controller=guest-tracking'
2. Complete the fields with a valid order_id and e-mail
3. Submit

**Possible solution**
if I add the follow hidden input to the form, the bug is fixed, but I don't know if is the best solution.

file `themes/classic/templates/customer/guest-login.tpl`

`
<input type="hidden" name="controller" value="guest-tracking" >
`

If this is a good solution I could make the PR.

awaiting for feedback...

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 5.6

**Comment by khouloudbelguith** [comment]
Hi @SuichiM,

Thanks for your report.
I think your issue is simar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/15605 fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16872
Thanks to check it and feedback.

**Comment by SuichiM** [comment]
I don't believe that is the same bug. In my case I just try with a never-used email (never registered as user). And have the same bug.

my problem, seems to be a malformed url when submit the form (lost the controller param)
... 
`index.php?order_reference=FJMGFENOB&email=testingmail%40ageokfc.com`

instead of:
`index.php?controller=guest-tracking&order_reference=FJMGFENOB&email=testingmail%40ageokfc.com`

**Comment by florine2623** [comment]
Hi @SuichiM ,

Thanks for your report. I did manage to reproduce the issue in PS 1.6.7.5 and PS 1.7.7.0.
- Disable friendly URL
- Go to 'index.php?controller=guest-tracking'
- Complete the fields with a valid order_id and e-mail
- Submit
- Redirect to shop home page instead of Guest Tracking page :

![Capture d’écran 2020-07-24 à 15 03 01](https://user-images.githubusercontent.com/16019289/88393926-ce7cff00-cdbe-11ea-9347-3cec1a8f691c.png)


If you have a PR you can submit it !
Thanks.

FYI : When Friendly URL are enabled, the bug does not occur.
