### ISSUE TITLE
"Use this address for invoice too" doesn't work

### ISSUE THREAD

**Issue by uruk-hai-21** [PrestaShop/PrestaShop#20209]
#### Describe the bug

Invoice address is always replaced with new address.

On checkout page in Addresses step:
1) I click "add new address"
2) I fill all fields
3) I uncheck "Use this address for invoice too" and I click to Continue button
4) The system go to "Shipping Method" step and set Delivery Address and Invoice address the new address

#### Expected behavior

If I uncheck "Use this address for invoice too" I expect that shipping address is the new address and the invoice address doesn't change.

#### Steps to Reproduce

On checkout page in Addresses step:
1) I click "add new address"
2) I fill all fields
3) I uncheck "Use this address for invoice too" and I click to Continue button
4) The system go to "Shipping Method" step and set Delivery Address and Invoice address the new address

**Screenshots**

https://www.youtube.com/watch?v=uiWekKdOn_w

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @ajejebrazorf01 ,
Thank you for your report.
But this is actually how the system works. For example if you have 3 different addresses saved, the system cannot guess which address you want to put in the invoice address and shipping address. That's why you have to choose manually which address you want in the invoice and the shipping
Also please downgrade your PHP version to 7.2 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Comment by uruk-hai-21** [comment]
> if you have 3 different addresses saved, the system cannot guess which address you want to put in the invoice address and shipping address.

ok I agree with you but if I check or uncheck the input "Use this address for invoice too" the system behaves the same way.
If I uncheck the input I would like to stay in "Addresses" step where I can choose the Invoce/shipping address, instead the system (independently of my choose) bring me to "Shipping Method" step forcing me to go back to the previous step to change the settings.

Please watch the video:
https://www.youtube.com/watch?v=uiWekKdOn_w

**Comment by uruk-hai-21** [comment]
News? There is a workaround for this problem?

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team  ,

@ajejebrazorf01 has an improvement to suggest.
When adding a new address an unchecking this option :
![Capture d’écran 2020-07-23 à 12 43 38](https://user-images.githubusercontent.com/16019289/88278144-36114c80-cce2-11ea-8c91-8345085d78c9.png)
The customer goes directly to the next step : **3. Shipping Method**, when it should stay on step **2. Addresses**; so the customer can choose both shipping and billing addresses.

What do you think about that ?

**Comment by uruk-hai-21** [comment]
Hi, @sowbiba sorry for disturbing.
What do you think abotu this?

**Comment by LouiseBonnard** [comment]
I agree with @ajejebrazorf01: **if the user unchecks the box 'Use this address for invoice too', the checkout process must stay at step two** to allow the user to choose his/her invoice address. Also, there is already an issue raising this problem, cf. #11595. So I close this one so that we can all focus on one same issue. :-)

**Comment by khouloudbelguith** [comment]
Duplicate of #11595
