### ISSUE TITLE
issue whit customer mensajes

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#20226]
#### Describe the bug

the mensajes of customers in 1.7.6.7 dont see properly, the ` and ñ get truncate and dont see

#### Expected behavior

the bd is in utf8_general_ci
#### Steps to Reproduce

1. Go to 'customer mensajes'
2. Click on 'mensaje'

**Screenshots**
![image](https://user-images.githubusercontent.com/9163980/87858728-47e49f80-c930-11ea-9fc4-d2d1e82263d3.png)
![image](https://user-images.githubusercontent.com/9163980/87858765-9d20b100-c930-11ea-9c3e-e174d30ed638.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information.
<img width="387" alt="Capture d’écran 2020-07-21 à 10 23 02" src="https://user-images.githubusercontent.com/3034677/88030955-307a0200-cb3c-11ea-9d31-41fc46f21715.png">
<img width="255" alt="Capture d’écran 2020-07-21 à 10 27 51" src="https://user-images.githubusercontent.com/3034677/88031511-fc531100-cb3c-11ea-9267-ccd0889f37fa.png">

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Thank you!
