### ISSUE TITLE
Issue with import csv and ps 1.7.5.2

### ISSUE THREAD

**Issue by Dario9494** [PrestaShop/PrestaShop#20247]
#### Describe the bug

The csv import feature stopped working after updating Chrome version 84.0.4147.89.
I've tried to reproduce it in Firefox and it worked but I've noticed that after clicking the "Next Step" button the form re submission alert appeared and I had to conferm the re submittion.
It seems like that the redirect break the import process.

#### Expected behavior

The mapping page is shown

#### Steps to Reproduce

1. Go to 'BackOffice'
2. Click on 'Advanced->Import'
3. Upload a valid File csv
4. Click on "Next Step"

**Screenshots**

Chrome issue: https://gyazo.com/3d02755ff29fdb410d77e7d3c3c2e228
Firefox Working: https://gyazo.com/ec5f401c5dc05a1e155050dc753c5dbd

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2

**Comment by sarahdib** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Could you try with the last PrestaShop version and if the problem still appear re-open a new issue.

Thank you!
