### ISSUE TITLE
Bug ps_emailalerts 2.2.0

### ISSUE THREAD

**Issue by grafeco** [PrestaShop/PrestaShop#20252]
#### Describe the bug

Hello! I’m Darío, Prestashop Developer.
 
I found a bug in ps_emailalerts 2.2.0: https://github.com/PrestaShop/ps_emailalerts
 
If you have more than 2 products with “Product::CUSTOMIZE_TEXTFIELD” in the same order, this is print duplicate in the email. Example:
 
(Mail)
 
<img src="https://i.imgur.com/6dJgkzm.png">
 
(Order in Ps 1.7 Backoffice)
 
<img src="https://i.imgur.com/D4N1Hkw.png">
 
 
This order is a test, for this reason you can not find the price, but with the normal orders we have the same issue.
 
This process start in line 299 in ps_emailalerts.php.
 
And in the database’s table PS doesn’t have “$text['name']” neither.
 
 
I hope this can help.

#### Expected behavior

One customezed text per product line in mails.

#### Steps to Reproduce

Make a new Order with more than two products with CUSTOMIZE_TEXTFIELD.

**Edit** @sowbiba :
In BO, add a product with text customization field
In FO, add the product with customization text in the cart
Add the same product a second time with customization text
Check the email received after order confirmation

#### Additional information

* PrestaShop version: 1.7.6.4
* Module version: v2.2.0
* PHP version: 7.2.29

**Comment by grafeco** [comment]
I hope this can help.
 
Thank you very much to develop all these lines.
I’ll follow the news about this module and PS!

**Comment by uruk-hai-21** [comment]
Could be depending from mail template?

**Comment by sowbiba** [comment]
Thanks @grafeco for the report

**Comment by uruk-hai-21** [comment]
@grafeco @sowbiba @marionf 
In my opinion the problem could be in "/mails/en/order_conf_product_list.tpl"
I don't have installed the module "ps_emailalerts" and I have the same issue with customized products.

**Comment by marionf** [comment]
@sowbiba Did you reproduced this issue ?

**Comment by uruk-hai-21** [comment]
Hello everyone, news?

**Comment by uruk-hai-21** [comment]
😴💤

**Comment by matks** [comment]
@ajejebrazorf01 Hi, this github repository has a Code of Conduct https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md which mentions
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members

Please understand this last message was not what I would call "welcoming" and "respectful".

Developer time is limited, so if the amount of issues opened in a certain timeframe exceeds the amount of issues that can be processed using the available developer time, tasks will simply pile up. This is common to ALL projects. Due to the number of pending issues, sometimes they may get lost in the pile and be forgotten about, so it's not a bad idea to ping us there from time to time to remind us about it, even if it's been a long while.

This is a Open Source Project, you might not receive answers or late answers. It is all right to kindly ask for an update in this situation.

But here's the upside: PrestaShop is an open source, community project. If you find that any issue is critical for you, and it's important to have it fixed _ASAP_, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

**Comment by uruk-hai-21** [comment]
Unfortunately I don't know how to fix it.

**Comment by uruk-hai-21** [comment]
Nothing?

**Comment by hibatallahAouadni** [comment]
Hello @grafeco 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #16551. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #16551
