### ISSUE TITLE
Display DNI field in address BO, even if it's not required

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20321]
#### Describe the bug

DNI (company ID) field is a regular part of address. 
In Prestashop, it only shows up in BO address edit, if you enable "DNI REQUIRED" checkbox in country settings.
In front office, it shows up normally.

#### Expected behavior

If dni field is set up in address format, it should be visible in BO regardless if its required or not. This nonsense is present ever since I am using prestashop... :-)

#### Steps to Reproduce

1. Set your country's address format to this:
_firstname lastname
company
dni
vat_number
address1
postcode city
Country:name
phone_
2. Go to FO, register a new account and see address form - DNI is there.
**3. Go to BO, edit the address you made and DNI is missing.**

#### The cause and fix
- After you open the address edit in BO or change the address country, js/admin.js makes an ajax call to AdminAddressesController asking, if DNI is required for this country. 
- If AdminAddressesController replies 1, js/admin.js hides the field. 
- It should instead add/remove required class from the input label and add/remove required="required" parameter from the input.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

ping @matks Is it possible to merge a fix this to next minor version, or it needs to wait for a major and possibly a page migration? Shouldn't bring any BC breaks.

**Comment by florine2623** [comment]
Hi @Hlavtox ,
Thanks for your report !

I did manage to reproduce the issue in PS 1.7.6.7 and PS .1.7.7.0.
I’ll add this to the debug backlog so that it’s fixed.
Thank you for your PR.

**Comment by matks** [comment]
Oh ? the "DNI madness" comes 😄 

The reason why I say this is madness is because we spent a huge time trying to deal with this when working on Symfony page migration for "Adresses" page ... and we found no solution, just a bigger problem.

The idea behind this is that **there are multiple ways to make DNI a required field or not**
- you can define it as a required field from "Adresses pages" below the listing
- you can define it as a required field for _some countries_
- modules have access to a hook in FO that allow them to define what fields are required

In all of this mix, it's very hard to know what should be done on BO side. For example a simple conflict is
- in "Adresses pages" below the listing, I select DNI to be a required field
- I define it as required for France, not for USA
What should be
- displayed on the form ?
- what happens when you change the country on the form ?
- what happens when you submit the data ?

So for now what we have done is "let full freedom to merchants". We think inside their BO merchants should be able to input whatever data they want, including not valid data if they want to. PrestaShop should not "stand in the way" of merchants wanting to sell!

A better response might be left to find (@MatShir "loves" this topic and is in charge) but for now it's "full freedom"

**Comment by ballashop** [comment]
Hi @matks 
the many posts about this topic means that many users find this important and perhaps unclear, or incomplete, aspect in PrestaShop.
For example, it is strange that the dni field is only optional in the Personal Information section, while in address information it is possible to make it optional, mandatory and also hidden.
It would be fantastic to allow the merchant to have complete control of the registration form on the site.
Thanks a lot for your support.
Balla

**Comment by Hlavtox** [comment]
@matks Fixed in 1.7.7 🚀
