### ISSUE TITLE
Why orders navigation is confusing?

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [PrestaShop/PrestaShop#20326]
We have orders in one column, where the last order is placed at the top of list. So we navigate UP and DOWN along the list.
https://prnt.sc/tnukhz

But in order editing window we have navigation buttons showing us LEFT and RIGHT
https://prnt.sc/tnum3a
Does it make sense? 

Buttons should be UP and DOWN as we navigate along the list in the same manner.

**Comment by florine2623** [comment]
Hi @PrestaShop/prestashop-product-team ,

@Laimonas-Mituzas finds it confusing that the button in the order details page are "Left and Right"
What do you think about that ? Is it relevant ?

Thanks!

**Comment by marionf** [comment]
ping @MatShir

**Comment by TristanLDD** [comment]
Hi @Laimonas-Mituzas, thanks for your report. 

I understand your remark, but the choice to have left and right navigation buttons in the order details page was deliberated.

We did it that way because left and right buttons are a universal way to explicit the notions of "previous" and "next", the order list might be vertical, but the results can change depending on the filters you apply to the list, as these filters aren't applied to these buttons (which always show previous and next order in a chronological order) we though left and right was the best option.  

Also, note that this behavior is already used on famous platforms such as Youtube: 
<img width="1047" alt="Capture d’écran 2020-07-27 à 17 47 15" src="https://user-images.githubusercontent.com/27484094/89196190-26c7b400-d5aa-11ea-9ed0-8b0b5933fb04.png">
Thank you.
