### ISSUE TITLE
class HelperTreeCategoriesCore is not translated

### ISSUE THREAD

**Issue by cortierdev** [PrestaShop/PrestaShop#20348]
Some text in this class is hardcoded, like "Expand All", "Collapse All", etc.

These strings should be translatable.

>Edited by Khouloud

Steps to reproduce the issue
1. Go to BO => Shop Parameters => General page 
2. Enable multishop context
3. Go to BO => Advanced Parameters => Multistore
4. Edit a shop
5. Change the language of the employee to any other language
`Collapse All`, `Expand All`, `Check All`, `Uncheck All` expressions are always displayed in English

**Comment by khouloudbelguith** [comment]
Hi @cortier,

I manage to reproduce the issue with PS1.7.5.1, PS1.7.6.7, and 1.7.7.x branch.
![image](https://user-images.githubusercontent.com/16067358/88527037-040f2b80-cffd-11ea-9c6a-8b174b709f7e.png)

Steps to reproduce the issue
1. Go to BO => Shop Parameters => General page 
2. Enable multishop context
3. Go to BO => Advanced Parameters => Multistore
4. Edit a shop
5. Change the language of the employee to any other language
`Collapse All`, `Expand All`, `Check All`, `Uncheck All` expressions are always displayed in English

In the BO => International => Translations page, it is well translated
![image](https://user-images.githubusercontent.com/16067358/88527643-d5de1b80-cffd-11ea-9238-7748fec95490.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by cortierdev** [comment]
I haven't fixed it. Please add it to the debug roadmap. Thanks.

**Comment by rehanrida** [comment]
SQL query:


CREATE TEMPORARY TABLE `INNODB_SYS_SEMAPHORE_WAITS` (
  `THREAD_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `OBJECT_NAME` varchar(4000) DEFAULT NULL,
  `FILE` varchar(4000) DEFAULT NULL,
  `LINE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `WAIT_TIME` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `WAIT_OBJECT` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `WAIT_TYPE` varchar(16) DEFAULT NULL,
  `HOLDER_THREAD_ID` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `HOLDER_FILE` varchar(4000) DEFAULT NULL,
  `HOLDER_LINE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `CREATED_FILE` varchar(4000) DEFAULT NULL,
  `CREATED_LINE` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `WRITER_THREAD` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `RESERVATION_MODE` varchar(16) DEFAULT NULL,
  `READERS` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `WAITERS_FLAG` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `LOCK_WORD` bigint(21) UNSIGNED NOT NULL DEFAULT 0,
  `LAST_READER_FILE` varchar(4000) DEFAULT NULL,
  `LAST_READER_LINE` int(11) UNSIGNED NOT NU[...]
MySQL said: Documentation

#1118 - Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
hi i downloading presta version 1.7.6.7 and following error  fix this error
