### ISSUE TITLE
[1.7.6.7] Different order of languages

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#20341]
Hello,
I have just added a few new languages to my Prestashop and I noticed that order of languages displayed is different is a few places. In some places languages are displayed according to their ID, but in some places the order is totally random. Here's an example:

This is the order of the languages in New feature section. This is the ocrrect order according to the ID of the language presented on the International -> Localization -> Languages. 

![feature](https://user-images.githubusercontent.com/48493952/88433234-f8094b00-cdfd-11ea-9ad5-7c9c1c80352d.jpg)

And this is the order of languages when I am adding a new category - it's ordered randomly.

![category](https://user-images.githubusercontent.com/48493952/88433296-140cec80-cdfe-11ea-92bd-850c36a6604b.jpg)

I prefer the display according to the ID everywhere because it is easier to add new things or modify something because I know the position of all languages on the list with jsut a quick look. With random order I have stop for a moment to find the langauge I want to work with. Can you help?

**Comment by khouloudbelguith** [comment]
Hi @banan44,

Thanks for your report.
I manage to reproduce the issue.
![image](https://user-images.githubusercontent.com/16067358/88540266-eb117500-d012-11ea-8f71-14210229dc19.png)

In fact, all pages migrated to Symfony, the languages are randomly ordered
![image](https://user-images.githubusercontent.com/16067358/88540190-ccab7980-d012-11ea-8930-95211bfbd124.png)

In the legacy page, they are ordered by ID.
![image](https://user-images.githubusercontent.com/16067358/88540209-d339f100-d012-11ea-9f17-f06363d14a38.png)

To reproduce the issue:
1. You have more than 3 languages
2. Change the employee language (id_language <>1)
3. Change the default language ( id_language<>1 & default language<> employee's language)

4. Go to a migrated page and compare it to a legacy page

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Ping @PrestaShop/prestashop-product-team, this a migration regression.
Thanks!

**Comment by LouiseBonnard** [comment]
Hi @khouloudbelguith & @banan44, thanks for the issue and explanation! I agree, it would be more relevant to have the languages organized according to their ID. :-)

I'll list all pages containing a language selector so that it can be fixed and harmonized for the 1.7.8 version.

**Comment by LouiseBonnard** [comment]
As stated yesterday, here is the list of all the pages (migrated and not-migrated-yet-but-soon-to-be) impacted:

- Orders > Orders
- Orders > Invoices
- Orders > Credit Slips
- Orders > Delivery Slips
- Catalog > Products
- Catalog > Categories
- Catalog > Attributes & Features
- Catalog > Brands & Suppliers
- Catalog > Files
- Catalog > Discounts
- Customer Service > Customer Service
- Customer Service > Order Messages
- Customer Service > Merchandise Returns
- Design > Email Theme
- Design > Pages
- Design > Link Widget
- Shipping  > Carriers
- International > Localization > Localization
- International > Localization > Currencies
- International > Locations  > Countries
- International > Taxes
- International > Translations
- Shop Parameters > General > Maintenance
- Shop Parameters > Order Settings  > Statuses
- Shop Parameters > Product Settings
- Shop Parameters > Customer Settings  > Titles
- Shop Parameters > Contact > Contacts
- Shop Parameters > Contact > Stores
- Shop Parameters > Traffic & SEO > SEO & URLs
- Shop Parameters > Search
- Shop Parameters > Search > Tags
- Advanced Parameters > Import
- Advanced Parameters > Team > Employees
- Advanced Parameters > Team > Profiles

... and the language selector in the front office in case it also needs to be reworked!
