### ISSUE TITLE
Lines in User review for product are not separated with CR/LF

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#20343]
#### Describe the bug
I created more lines comment in User review for product but after sending it is displayed in one line. 

#### Expected behavior
The User review should be displayed by the same way as it was created.

_User review - Create_ 
![image](https://user-images.githubusercontent.com/33311857/88435292-2e48c980-ce02-11ea-9021-114b927a582d.png)

_User review - Display_ 
![image](https://user-images.githubusercontent.com/33311857/88435334-40c30300-ce02-11ea-913a-3357068090cc.png)

#### Additional information
* PrestaShop version: 1.7.6.7
* PHP version: 7..2

**Comment by khouloudbelguith** [comment]
Hi @juraj1000,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.7 and the `productcomments` module v4.0.1.
![image](https://user-images.githubusercontent.com/16067358/88534033-8ac90600-d007-11ea-9172-e028e94108ed.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Ping @marionf can we add this issue to this [epic](https://github.com/PrestaShop/PrestaShop/issues/19933)?
Thanks!

**Comment by Progi1984** [comment]
Fixed by PrestaShop/productcomments#65
