### ISSUE TITLE
Some order status label colors are wrong

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#20355]
#### Describe the bug

Some difference for 2 of the colors mentionned in #15228, it can be seen on "order statuses listing page":

> In dark blue HEX #34219E for waiting on client action
> In green HEX #2ECC71 , if no action is required anymore

For the "dartk blue" i have #34209E instead of #34219E
and for the "greene i have #01B887 instead of #2ECC71

The PR which modified the colors is #16104. There might have been an issue in it.

#### Expected behavior

Order status colors should be exact.

* PrestaShop version: develop

**Comment by matks** [comment]
Issue reported in https://github.com/PrestaShop/PrestaShop/pull/17215#issuecomment-661745374 by @SD1982

**Comment by khouloudbelguith** [comment]
Hi @matks, @SD1982,

I have the same issue with 1.7.7.x branch
1. For the "dark blue" I have #34209E instead of #34219E
![image](https://user-images.githubusercontent.com/16067358/88531091-9bc34880-d002-11ea-8ebf-72f13dd126ab.png)
2. For the "green I have #01B887 instead of #2ECC71
![image](https://user-images.githubusercontent.com/16067358/88531158-b2699f80-d002-11ea-80c5-3977cb08a192.png)

I’ll add this to the debug roadmap.

Thanks!

**Comment by khouloudbelguith** [comment]
@matks @PrestaShop/prestashop-product-team this issue should be fixed in the PS1.7.7.0?

Thanks!

**Comment by LouiseBonnard** [comment]
It's a regression and it looks very easy to fix so I'd say yes, @khouloudbelguith. :-)

**Comment by Progi1984** [comment]
It's not a regression. It has been modified by @atomiix in #17568. It has been validated by @TristanLDD (Slack chat).

**Comment by SimonGrn** [comment]
See [here](https://github.com/PrestaShop/PrestaShop/issues/15228#issue-484389768).
