### ISSUE TITLE
ATTENTION TO YOUR SITE: www.prestashop.com

### ISSUE THREAD

**Issue by tdvcprov** [PrestaShop/PrestaShop#20414]
Hello. I'm from Brazil and I don't speak English. Well, sorry for the mistakes. I saw that you launched a Bug Bounty program. Is your website, www.prestashop.com, included in the reward program?

**Comment by PierreRambaud** [comment]
Hi,

Unfortunately, the Bug Bounty Program only concerns the open-source project. But feel free to send us an email to security@prestashop.com we will do our best to evaluate the security issue if there is one. 

I'm closing this issue since this conversation has nothing to do here :sweat_smile: 

Kind regards
