### ISSUE TITLE
In backend, unhook Welcome 6.0.0 module from displayAdminNavBarBeforeEnd crashes backend

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20429]
#### Describe the bug

From backend, Design->Positions, when unhooking Welcome module v6.0.0 from displayAdminNavBarBeforeEnd crashes completely the backend.

#### Expected behavior

Unhook the module

#### Steps to Reproduce

1. Go to backend in demo shop (http://demo.prestashop.com/#/en/back)
2. Click on 'Design -> Positions'
3. Unhook Welcome v6.0.0 from displayAdminNavBarBeforeEnd

**Screenshots**

![unhook](https://user-images.githubusercontent.com/54415801/89170745-5feb2e80-d580-11ea-93ce-baf9e7157792.gif)

![error](https://user-images.githubusercontent.com/54415801/89170951-b7899a00-d580-11ea-8586-bf5a8b320a91.gif)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: ??

**Comment by ghost** [comment]
After that, nothing can be done....

**Comment by khouloudbelguith** [comment]
Hi @pista7,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.7 downloaded PrestaShop.
https://drive.google.com/file/d/10v5JUnae9UZU15Gb7KKxAg8ldTeRj3I8/view?usp=sharing
I will close the issue as it is not a core issue.

This issue exists only in the demo shop.
Ping @Quetzacoalt91

Thanks!

**Comment by ghost** [comment]
Hi! @khouloudbelguith  @Quetzacoalt91 

It did happen in my local environment, that's why I found out in the first place. Just downloaded and created the shop, nothing else.

Windows 8.1, MySQL 5.7.24, PHP 7.2.19 (Laragon 4.0.16)

Then I tried on my test server Debian 9.... the same. Then I tried in the demo shop. The same. It could be not a core issue, but it crashes everything. After that there's a 500 error and nothing can be done. I cannot believe that it is only happening to me.....

X.

**Comment by khouloudbelguith** [comment]
@pista7,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by ghost** [comment]
Hi!

I know 500 errors are frustating, but they need to be dealt with, anyway...

I'm running a Windows 8.1 patched regularly, i7-5500U, 16GB RAM, so enough to run prestashop. Everything else is stopped. Firefox 79.0 (64-bit)

I downloaded bitnami package so the environment is fixed (https://bitnami.com/download/files/stacks/prestashop/1.7.6.7-0/bitnami-prestashop-1.7.6.7-0-windows-x64-installer.exe?with_popup_skip_signin=1). I installed it locally, not in the cloud. Same error:

1. Install prestashop
2. Connect to 127.0.0.1/prestashop/administration (backend) with user/pwd.
3. Close modal Welcome to your shop!
4. Go to Design -> Positions (http://192.168.43.180/prestashop/administration/index.php/improve/design/modules/positions/?_token=YVOLqAWf2GoWJSLB8u3kmyiqPUTRxQgzFx7WiSCIPLg)
5. Unhook Welcome  - v6.0.0 from displayAdminNavBarBeforeEnd using the dropdown option in the edit button (as in the picture provided initially)

The access.log (in the apache/logs folder inside bitnami installation folder) only says:

192.168.43.180 - - [03/Aug/2020:19:21:53 +0200] "GET /prestashop/administration/index.php/improve/design/modules/positions/unhook?moduleId=54&hookId=445&_token=YVOLqAWf2GoWJSLB8u3kmyiqPUTRxQgzFx7WiSCIPLg HTTP/1.1" 302 728
192.168.43.180 - - [03/Aug/2020:19:21:53 +0200] "GET /prestashop/administration/index.php/improve/design/modules/positions/?_token=YVOLqAWf2GoWJSLB8u3kmyiqPUTRxQgzFx7WiSCIPLg HTTP/1.1" 500 495

No more details about the error. What else can I provide to help with this?
Regards,
X.

**Comment by ghost** [comment]
Same procedure with `define('_PS_MODE_DEV_', true);` works fine. No 500 error.

![imagen](https://user-images.githubusercontent.com/54415801/89211017-6c43ab80-d5c1-11ea-9391-2af5adf542f4.png)

Any information I could provide?
X.

**Comment by ghost** [comment]
Same happens on a Mac OS Catalina 10.15.2 (19C57) using bitnami package downloaded just now.

<img width="757" alt="Captura de pantalla 2020-08-03 a las 21 55 17" src="https://user-images.githubusercontent.com/54415801/89221859-496ec280-d5d4-11ea-9eaa-fd9bc861f533.png">

**Comment by khouloudbelguith** [comment]
@pista7,

>Same procedure with define('_PS_MODE_DEV_', true); works fine. No 500 error.


So, when debug mode is enabled => the issue doesn't exist anymore.

Thanks for these clarifications.
I manage to reproduce the issue with PS1.7.5.1, PS1.7.6.7, and PS1.7.7.0beta1
This issue occurs only when debug mode is disabled.

But, I checked with 1.7.7.x branch, it is fixed.
I attached a screen record
https://drive.google.com/file/d/1t5oEkt7pfwQGQ4GCtPt-Dwur1qF4a8yy/view?usp=sharing

This issue will be fixed in the next release 1.7.7.0.
I close the issue, feel free to open a new one when needed.

Thanks!
