### ISSUE TITLE
productoutofstock email doesn't have the product name nor employee firstname & lastname

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#20445]
#### Describe the bug
When getting the productoutofstock for a product below the stock level, the email doesn't say which product is (see screenshot attached).

#### Expected behavior
Display the product name

#### Steps to Reproduce

1. Set a stock alert below the current stock on the product page in the admin
2. Order the product
3. Open the email alert productoutofstock

**Screenshots**
![Capture d’écran 2020-08-04 à 12 27 56](https://user-images.githubusercontent.com/1193727/89283747-f2a5cf00-d64d-11ea-9e56-afe4f2dc7cd4.jpg)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @arirangz,

I manage to reproduce the issue with PS1.7.6.0, PS1.7.6.7, and 1.7.7.x branch.
![image](https://user-images.githubusercontent.com/16067358/89288180-7f07c000-d655-11ea-8262-c4db0c1dbf32.png)
With PS1.7.5.1, we have this
![image](https://user-images.githubusercontent.com/16067358/89288337-c3935b80-d655-11ea-91b9-cb0a5e326cf3.png)

This regression reported [previously](https://github.com/PrestaShop/PrestaShop/issues/13424) but not fixed.
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by arirangz** [comment]
Great thanks for adding it to the roadmap.

By the way, is this feature not duplicated with Mail Alert module?

I mean, if you have this alert enabled and PS Mail Alert enabled, you will get two emails.
