### ISSUE TITLE
Hook ActionObjectCombinationAddAfter is not triggered

### ISSUE THREAD

**Issue by c3do** [PrestaShop/PrestaShop#20489]
1. Go to BackOffice
2. Select a product
3. Add a combination

**Comment by SimonGrn** [comment]
Dear @c3do 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by c3do** [comment]
Bad hook name, it is actionAttributeCombinationSave that is not triggered

**Comment by SimonGrn** [comment]
Hello @c3do 
As stated in my previous message, this issue is no longer active. If you think you can give us more information, please feel free to open another issue, but keep in mind that you need to keep the template and fill all the informations.
We cannot work on 3 lines of steps.

Thank you for your understanding.
