### ISSUE TITLE
contactform mail xss

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20503]
Edited by @PierreRambaud for security reasons.
Thank @tonius85 for the report.

**Comment by khouloudbelguith** [comment]
Hi @tonius85,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by PierreRambaud** [comment]
Hi and thanks for your report.

The problem exists, but we need to determine if it's the desired behavior or not.

About magic quote gpc, since PrestaShop does not support PHP 5.3, we will not take into consideration this part. 
https://www.php.net/manual/en/info.configuration.php#ini.magic-quotes-gpc

Kind regards

**Comment by ghost** [comment]
Hi thanks for your response,

Indeed the way 2 is obsolete with magic quote and corrected in an 1.7.6.X 

For example
Version 1.7.6.4
`'{message}' => Tools::nl2br(stripslashes($message)),`

And version 1.7.6.7 
`'{message}' => Tools::nl2br(Tools::stripslashes($message)),`

Good job and thanks 👍

**Comment by PierreRambaud** [comment]
@tonius85 Thanks a lot

**Comment by PierreRambaud** [comment]
I'm closing this issue, we are currently using GitHub Advisory to manage this issue.
Thanks again @tonius85
