### ISSUE TITLE
Error from psgdpr module when installing in russian language and Ukraine country

### ISSUE THREAD

**Issue by Djonivan** [PrestaShop/PrestaShop#20519]
#### Describe the bug

psgdpr1: Unable to install module "psgdpr", Tab-> name property is 70 characters long. Must be between 0 and 64 char.

#### Expected behavior

successful installation as in English.

#### Steps to Reproduce

Installing Prestashop using the installation assistant.
Russian language;
Country Ukraine.

**Screenshots**

http://prntscr.com/tx47ti
http://prntscr.com/tx485s
http://prntscr.com/tx48ff
http://prntscr.com/tx48mi
http://prntscr.com/tx48st

#### Additional information

* PrestaShop version: PrestaShop 1.7.7.0 Beta AND PrestaShop 1.7.6.7 Stable
* PHP version: PHP 7.0 AND PHP 7.3

Currently, I and other users solve this problem as follows: run the installation wizard in English, and after a successful installation, change the language in the admin panel to Russian or Ukrainian.

![Screenshot_1](https://user-images.githubusercontent.com/69455063/89780204-a52bd500-db19-11ea-88db-f7487f3b55a9.png)
![Screenshot_2](https://user-images.githubusercontent.com/69455063/89780211-a65d0200-db19-11ea-8969-341fcc532ed6.png)
![Screenshot_3](https://user-images.githubusercontent.com/69455063/89780212-a65d0200-db19-11ea-80b5-af5448be488e.png)
![Screenshot_4](https://user-images.githubusercontent.com/69455063/89780214-a6f59880-db19-11ea-9721-1f0d74023fda.png)
![Screenshot_6](https://user-images.githubusercontent.com/69455063/89780215-a6f59880-db19-11ea-8e8b-820a18daf30f.png)
![Screenshot_12](https://user-images.githubusercontent.com/69455063/89780216-a78e2f00-db19-11ea-9037-0ce8877cf289.png)

**Comment by khouloudbelguith** [comment]
HI @Djonivan,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.7 and 1.7.7.x branch.
![image](https://user-images.githubusercontent.com/16067358/89791822-15d7ef00-db24-11ea-97ff-0e4ec90a5f48.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Djonivan** [comment]
> HI @Djonivan,
> 
> Thanks for your report.
> I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.7 and 1.7.7.x branch.
> ![image](https://user-images.githubusercontent.com/16067358/89791822-15d7ef00-db24-11ea-97ff-0e4ec90a5f48.png)
> I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
> Thanks!

Unfortunately I'm not a developer, I'm a marketer and an HTML-CSS layout designer. I also almost don't know English :)

**Comment by cyberax88** [comment]
Hi,

I've got the same error when trying to install, it got stacked at 67% with the error below:

![Capture](https://user-images.githubusercontent.com/69478671/89815232-19cc3700-db4d-11ea-8be3-ee18d9017a77.JPG)

**Comment by SimonGrn** [comment]
> Hi,
> 
> I've got the same error when trying to install, it got stacked at 67% with the error below:
> 

Hello, this is not the same problem. Your MySQL server seems to have gone away, which means it couldn't keep up. Are you testing this in a local environment ? You don't have enough computing resources.
Please open your own issue if you think this is a real issue from PrestaShop and not a problem lying in your own environment.

**Comment by cyberax88** [comment]
Hi,

I'm not testing in my own environment, I tried to instal it into online
hosting platform. With the previous Prestashop version, everything works
well.

Regards

**Comment by evgenij-sobolev** [comment]
> 
> #### Describe the bug
> 
> psgdpr1: Unable to install module "psgdpr", Tab-> name property is 70 characters long. Must be between 0 and 64 char.
> #### Expected behavior
> 
> successful installation as in English.
> #### Steps to Reproduce
> 
> Installing Prestashop using the installation assistant.
> Russian language;
> Country Ukraine.
> 
> **Screenshots**
> 
> http://prntscr.com/tx47ti
> http://prntscr.com/tx485s
> http://prntscr.com/tx48ff
> http://prntscr.com/tx48mi
> http://prntscr.com/tx48st
> #### Additional information
> 
>     * PrestaShop version: PrestaShop 1.7.7.0 Beta AND PrestaShop 1.7.6.7 Stable
> 
>     * PHP version: PHP 7.0 AND PHP 7.3
> 
> 
> Currently, I and other users solve this problem as follows: run the installation wizard in English, and after a successful installation, change the language in the admin panel to Russian or Ukrainian.
> 
> 

I have the same issue when choosing Russian or Ukrainian language during installation.
psgdpr module is included in standard prestashop installation package.
So, It is impossible to install prestashop if you choose Ukrainian or Russian language during installation.

This bug is also described on the official forum:
https://www.prestashop.com/forums/topic/1028184-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-psgdpr1/

Tested on prestashop 1.7.6.7, 1.7.6.8, 1.7.7

This bug can be fixed in this way:
Before installation, change 2 files in the installation package:

1. install\upgrade\sql\1.6.0.3.sql

`ALTER TABLE `PREFIX_tab_lang` CHANGE `name` `name` VARCHAR(64) DEFAULT NULL;`
change 64 to 512
​
2. \classes\Tab.php

`'name' => array('type' => self::TYPE_STRING, 'lang' => true, 'required' => true, 'validate' => 'isTabName', 'size' => 64),`
change 64 to 512

**Comment by TemKaSD** [comment]
@khouloudbelguith Problem 6 years ? https://github.com/PrestaShop/PrestaShop/blob/1.6.0.3/install-dev/upgrade/sql/1.6.0.3.sql#L8 FIX PLS!!!!!!!!!!!!!!!!!!!!

Need FIX https://github.com/PrestaShopCorp/psgdpr/blob/master/translations/ru.php#L22

**Comment by SimonGrn** [comment]
> 
> 
> @khouloudbelguith Problem 6 years ? https://github.com/PrestaShop/PrestaShop/blob/1.6.0.3/install-dev/upgrade/sql/1.6.0.3.sql#L8 FIX PLS!!!!!!!!!!!!!!!!!!!!
> 
> Need FIX https://github.com/PrestaShopCorp/psgdpr/blob/master/translations/ru.php#L22

Please follow our Code of Conduct. This is not acceptable.

**Comment by TemKaSD** [comment]
> > @khouloudbelguith Problem 6 years ? https://github.com/PrestaShop/PrestaShop/blob/1.6.0.3/install-dev/upgrade/sql/1.6.0.3.sql#L8 FIX PLS!!!!!!!!!!!!!!!!!!!!
> > Need FIX https://github.com/PrestaShopCorp/psgdpr/blob/master/translations/ru.php#L22
> 
> Please follow our Code of Conduct. This is not acceptable.

SOrry

**Comment by matks** [comment]
> @khouloudbelguith Problem 6 years ? https://github.com/PrestaShop/PrestaShop/blob/1.6.0.3/install-dev/upgrade/sql/1.6.0.3.sql#L8 FIX PLS!!!!!!!!!!!!!!!!!!!!
> 
> Need FIX https://github.com/PrestaShopCorp/psgdpr/blob/master/translations/ru.php#L22

Hi there,

Not having an issue fixed immediately (or in a fixed timeframe) does not mean that it won't be fixed, or that we don't care. It doesn't mean that the issue is NOT important either. It just means that other issues have been considered, for whatever reason, _more_ important, so they were (or are being) tackled first. There's an immense amount of work to be done (1900 issues right now, and growing!), and tasks take time.

Developer time is limited, so if the amount of issues opened in a certain timeframe exceeds the amount of issues that can be processed using the available developer time, tasks will simply pile up. This is common to ALL projects. Due to the number of pending issues, sometimes they may get lost in the pile and be forgotten about, so it's not a bad idea to ping us there from time to time to remind us about it, even if it's been a long while.

But here's the upside: PrestaShop is an open source, community project. If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

If this bug has not been fixed after 6 years it's simply that we have other topics we must work on. So the best option for you to get it fixed is to _invest_ into having it done: either find a developer to fix it or fix it yourself. The code is open, you can work on it just like anybody else. The PrestaShop company cannot handle all the topics of the PrestaShop open source project, a part of the work must be done by the community too.

**Comment by evgenij-sobolev** [comment]
Latest version 1.7.7.3
This bug is still not resolved ...

**Comment by marionf** [comment]
Hello @evgenij-sobolev 

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). 
Remember that the more people contribute, the better PrestaShop becomes for everyone ;)

**Comment by Progi1984** [comment]
Fixed by @TemKaSD in PrestaShop/psgdpr#115

**Comment by stufently** [comment]
For asap fix 

1. install\upgrade\sql\1.6.0.3.sql

7 lines:

ALTER TABLE PREFIX_tab_lang CHANGE name name VARCHAR(64) DEFAULT NULL;
change 64 to 512

2. \classes\Tab.php

73 lines:

‘name’ => array(‘type’ => self::TYPE_STRING, ‘lang’ => true, ‘required’ => true, ‘validate’ => ‘isTabName’, ‘size’ => 64),
change 64 to 512

**Comment by xpcrts** [comment]
Not working for Prestashop 1.7.8.9

> For asap fix
> 
> 1. install\upgrade\sql\1.6.0.3.sql
> 
> 7 lines:
> 
> ALTER TABLE PREFIX_tab_lang CHANGE name name VARCHAR(64) DEFAULT NULL; change 64 to 512
> 
> 2. \classes\Tab.php
> 
> 73 lines:
> 
> ‘name’ => array(‘type’ => self::TYPE_STRING, ‘lang’ => true, ‘required’ => true, ‘validate’ => ‘isTabName’, ‘size’ => 64), change 64 to 512

**Comment by xpcrts** [comment]
⭐⭐⭐⭐⭐
✅✅✅✅✅
I am using Prestashop 1.7.8.9 but I think it might apply to other part as well.

If you are hosting your Prestashop on Linux server (or Ubuntu server) you can follow this first

**Step 1:**

For asap fix

ROOT directory of Prestashop > install\upgrade\sql\1.6.0.3.sql
7 lines:

ALTER TABLE PREFIX_tab_lang CHANGE name name VARCHAR(64) DEFAULT NULL;
change 64 to 512

ROOT directory of Prestashop >  \classes\Tab.php
73 lines: (maybe different line than this one)

‘name’ => array(‘type’ => self::TYPE_STRING, ‘lang’ => true, ‘required’ => true, ‘validate’ => ‘isTabName’, ‘size’ => 64),
change 64 to 512

**Step 2:**
ROOT directory of Prestashop >  /modules/psgdpr/translations/ and then choose your language.php for example:
ROOT directory of Prestashop >  /modules/psgdpr/translations/ru.php
or
ROOT directory of Prestashop >  /modules/psgdpr/translations/fr.php

cd into that directory then type chmod 444 fr.php (if you use French, if you choose Russia or other language change .php type based on that.


then close your installation tap of Prestashop completely and retry it all over again
