### ISSUE TITLE
BO - Orders page - Wrong rounding price displayed in the Editing product interface

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20573]
#### Describe the bug

In the BO => Order page => a wrong rounding price displayed in the Editing product interface

#### Steps to Reproduce

1. Create a `ProductA` with 10 euro tax included
2. Create an order with the last product created and generate an invoice `invoice1`
3. In the BO => Order details page => Edit the `ProductA`'s price = 100 euro tax included
4. I add product A in a second invoice `invoice2` with price =100 tax included
5. Edit the `ProductA`'s price
![image](https://user-images.githubusercontent.com/16067358/90129839-aa7f5e80-dd69-11ea-950d-5359d32b9bc4.png)

https://drive.google.com/file/d/1GWR8s9WBBVXgW32D783QFG3z-ULvoLQF/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by matks** [comment]
This will be hard to fix.

The data is being badly stored when we submit it. So when merchant enters 100.00, what is being stored in database is 99.996000 in order detail SQL column `unit_price_tax_incl`.

So issue happens at this step

> I add product A in a second invoice invoice2 with price =100 tax included

This issue is unseen until you try editing the product because this is rounded for display. So 99.996 is stored, but in every place where we display it we round it. But when we edit, there, we use the raw price.

**Comment by matks** [comment]
Next step is to find why 99.996000 was put inside database instead of 100.000000 when merchant submitted the product A new price.

**Comment by matks** [comment]
This issue must wait for https://github.com/PrestaShop/PrestaShop/pull/20145 to be merged because this PR modifies this behavior.

The issue might be solved after the merge of the PR.

**Comment by jolelievre** [comment]
I just checked with PR #20145 the bug is still present, however indeed since the PR modifies a lot of things regarding the order edition it's safer to wait for it to be merged And I prefer not to fix the issue in the same PR as it would delay its merge even longer

**Comment by jolelievre** [comment]
Regarding the bug it's indeed a precision problem, I didn't look into detail but it kind of makes sense The submitted/saved price (tax excluded) is 83.33 with 20% tax added it results 99.996...
So the problem might come from the front input which has a too little precision

**Comment by matthieu-rolland** [comment]
@matks After spending time toying with the frontend precision in the BO Order Detail page, I think there's not much we can do about this issue, at least in 1.7.7

You're right @jolelievre, in the `UpdateProductInOrderHandler` the value is rounded before being stored... but the thing is, its rounded to its computing precision, which is the right thing to do, the issue is that now our computing precision is always the same as our display precision...  this issue should fix itself when we restore the correct computing precision in 1.7.8.

But maybe there's another way I'm missing ?

**EDIT**:  I just tested in 1.7.6 and the bug doesn't exist, and yet the precision was still the same too...  It means this bug should be fixable 🤔   I'll keep looking

**Comment by elrosi** [comment]
Hi, 
I found a problem with incorrect rounding Price (tax incl.) at values of 32.30, 33.30, 33.24, 33.22
These values change the price of the product to many decimal places, such as 32.229999, 33.229999
This looks like a problem in JavaScript.
PrestaShop v. 1.7.6.8, 1.7.7.0 beta 1
https://share.vidyard.com/watch/sCA81ZYLSxne6VbgHVp9Sj?

**Comment by marionf** [comment]
Hello @elrosi 
Your issue is not related to this issue on the order page but rather to this one: https://github.com/PrestaShop/PrestaShop/issues/9972, you should follow this issue

**Comment by Progi1984** [comment]
Fixed by #20882
