### ISSUE TITLE
Unable to switch template for a single store in a multistore setup

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#20579]
#### Describe the bug

In a multistore installation, I go to *Appearance - Themes*, click on *Use this theme*, and I get a Error 500.
Nevertheless, the theme is switched for the current store, but on the FO, it displays incorrectly due to incoherent CSS.

The log has these details:
```
[Thu Aug 13 14:14:39.423113 2020] [***] AH01071: Got error '
PHP message: PHP Fatal error:  Uncaught Error: Class 'Tools' not found in /home/www-data/ps1767.sbgmb.net/classes/db/Db.php:794
Stack trace:
#0 /home/www-data/ps1767.sbgmb.net/config/alias.php(47): DbCore->escape('configuration', false)
#1 /home/www-data/ps1767.sbgmb.net/config/alias.php(52): pSQL('configuration')
#2 /home/www-data/ps1767.sbgmb.net/classes/Configuration.php(155): bqSQL('configuration')
#3 /home/www-data/ps1767.sbgmb.net/classes/Configuration.php(209): ConfigurationCore::loadConfiguration()
#4 /home/www-data/ps1767.sbgmb.net/classes/PrestaShopAutoload.php(171): ConfigurationCore::get('PS_DISABLE_OVER...')
#5 /home/www-data/ps1767.sbgmb.net/classes/PrestaShopAutoload.php(130): PrestaShopAutoload->generateIndex()
#6 [internal function]: PrestaShopAutoload->load('Tools')
#7 /home/www-data/ps1767.sbgmb.net/config/config.inc.php(85): spl_autoload_call('Tools')
#8 /home/www-data/ps1767.sbgmb.net/admin491uyu33e/index.php(40): require('/home/www-data/...')
#9 {main}
  thrown in /home/www-d...', referer: https://ps1767.sbgmb.net/admin491uyu33e/index.php/improve/design/themes/?_token=***
```

#### Steps to Reproduce

1. Enable multistore, configure 2 stores.
2. Install a second theme alongside `classic` (`classic-rocket` in my case)
3. Got to *Appearance - Themes*
4. Click on *Use this theme*
5. Error 500 displays
6. Reload page: Theme is applied
7. Go to FO of the two stores and notice the mangled display

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7520695/90140529-2c778380-dd7a-11ea-8de0-f4a83ede73db.PNG)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33-1+ubuntu18.04.1+deb.sury.org+1

**Comment by khouloudbelguith** [comment]
Hi @lmeyer1,

Thanks for your report.
I did not manage to reproduce the issue with PS1.7.6.7.
I used this theme: https://github.com/prestarocket-agence/classic-rocket
I attached a screen record
https://drive.google.com/file/d/1MJ46mIplzlczXxrjztuez1jujY0y0n7N/view?usp=sharing
The FO is well displayed
![image](https://user-images.githubusercontent.com/16067358/90229616-7e6ee680-de18-11ea-8bba-5db3a420b594.png)

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.

Try to turn on the Debug mode on PrestaShop 1.7, follow these steps:

1. Got to Advanced Parameters > Performance
2. In the Debug Mode section, set “Debug Mode” to “Yes”.
3. Click the “Save” button.

then check if you have any exception displayed.

Thanks!

**Comment by lmeyer1** [comment]
Thank you for your answer.
Actually there are two bugs interleaving.
- The display of `classic-rocket` in a multistore environment. I filed a separate bug [here](https://github.com/prestarocket-agence/classic-rocket/issues/181)
- The Error 500

As of the error 500 related to Prestashop Core, I reproduced it yesterday several time, but today I'm not able to reproduce.

**Comment by khouloudbelguith** [comment]
@lmeyer1, thanks for your feedback.
Feel free to open a new one when needed.

Thanks!
