### ISSUE TITLE
Incorrect amount with wire payment (always at 0)

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#20580]
#### Describe the bug

Since I've updated the module, the amount to pay is always at 0.

The problem seems to come from this commit: https://github.com/PrestaShop/ps_wirepayment/pull/21/files

This line is strange because it subtracts the total by itself.

![image](https://user-images.githubusercontent.com/22885898/90140085-875cab00-dd79-11ea-8492-168f32cd447b.png)

#### Expected behavior

Get the right amount, just like before.

#### Steps to Reproduce

1. Make an order
2. Pay with wire payment
3. View the amount

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version: 7.2

**Comment by sarahdib** [comment]
@yannicka 
The problem is fixed with the last version of the module and prestashop.
<img width="1048" alt="Capture d’écran 2020-08-13 à 17 27 24" src="https://user-images.githubusercontent.com/3034677/90154322-4620c700-dd8a-11ea-8ca6-395fa3892a95.png">

I close this issue feel free to open a new one if you reproduce this issue with the last version.

Thank you :) !

**Comment by javierVP** [comment]
I have the latest version of module 2.1.0 and PrestaShop 1.7.7.4 I have the same error.

**Comment by jonathanromain** [comment]
i have a same error with module 2.1.0. the amount to pay is always at 0. 

someone has a solution ? 
Thanks

**Comment by Shaggy84675** [comment]
Happened to me too, after we upgraded PrestaShop from 1.6 to 1.7.

I found the problem is in row: https://github.com/PrestaShop/ps_wirepayment/blob/e06c7bf331ad0f900afe93ca814de52ecd01e5af/ps_wirepayment.php#L236

Both values of the `$params['order']->getOrdersTotalPaid()` and `$params['order']->getTotalPaid()` are the total prices and that's the reason why the result of the subtraction is 0. Could I ask what's the difference between "getOrdersTotalPaid" and "getTotalPaid"?

**Comment by PicenoC** [comment]
I have the same problem even without an update, in fact it does the same calculation if you download the ps version 

I solved it by commenting - $ params ['order'] -> getTotalPaid ();

**Comment by bfontaine** [comment]
I have the same problem with PrestaShop 1.7.8.6. There must be an issue somewhere if we are so many with the same problem.

**Comment by bfontaine** [comment]
I believe I made some progress in investigating the issue.

On my instance the order state id 12 is "remote payment accepted". The id 12 is also used for the [`PS_OS_OUTOFSTOCK_UNPAID` config key](https://github.com/PrestaShop/PrestaShop/blob/cfeda5a14feb360235d01729bdda755378b66f7d/install-dev/data/xml/configuration.xml#L383-L384). When an order is validated with a product that’s out of stock, [the order is set to this state](https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/PaymentModule.php#L578-L584). However my instance is configured to allow buying out-of-stock items. When one buys such item, PrestaShop sets the order status to `PS_OS_OUTOFSTOCK_UNPAID` aka id=12 aka "remote payment accepted", which in turn marks the order as paid and so there’s 0€ left to pay by wire.

For me the fix was to change this `PS_OS_OUTOFSTOCK_UNPAID` in the database to another state: `update ps_configuration set value = '13' where name = 'PS_OS_OUTOFSTOCK_UNPAID' and value = '12';` (the exact value can be different on your instance).

**Comment by arLevi** [comment]
I experienced this issue when I wrote my own payment method following `ps_wirepayments`
and I put by accident a constant order status that is a "blue color" meaning = "already paid" so the amount was 0 as there's nothing left to pay ...
```
# shop -> order settings
| PS_OS_WS_PAYMENT        | 11 |
```
I used this constant variable here
```
# file: controllers/front/validation.php
...
$this->module->validateOrder($cart->id, (int) Configuration::get('PS_OS_WS_PAYMENT'), $total, $this->module->displayName, null, $mailVars, (int) $currency->id, false, $customer->secure_key);
                                                                       ^^^
```

So instead I created my own status ( or you can use existing "purple color" one such that requires processing) and placed its integer ID that was created by PS instead like so:
```
# file: controllers/front/validation.php
$this->module->validateOrder($cart->id, 14, $total, $ ...);
```

I wouldn't recommend to remove/uncomment this variable, as it's calculating gift cards etc ...
```
# mymodulename.php
public function hookDisplayPaymentReturn($params) {
           .... 
           # Don't change this
           $totalToPaid = $params['order']->getOrdersTotalPaid() - $params['order']->getTotalPaid();

           # to this
           $totalToPaid = $params['order']->getOrdersTotalPaid();
}
```
