### ISSUE TITLE
eMail Preview - wrong value in {total_products}

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#20625]
#### Describe the bug

When using the email preview or send test email function from Design->Email themes->modern->order_conf the variable {total_products} is filled with the number of products in the order instead of the total product amount (when real order is placed it's working fine)

#### Expected behavior
Show the total product amount as in real order confirmation

#### Steps to Reproduce

1. Go to Design->Email themes->modern->order_conf 
2. Click on HTTP Preview
3. Scroll down to 'Products'

**Screenshots**

![grafik](https://user-images.githubusercontent.com/47666330/90508099-5a344200-e157-11ea-8b78-a936fcc7a782.png)
#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @JBWModules,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.7 and 1.7.7.x branch.
![image](https://user-images.githubusercontent.com/16067358/90509105-19d5c380-e159-11ea-8d51-28607327a51a.png)

In the received email => OK
![image](https://user-images.githubusercontent.com/16067358/90509200-3a9e1900-e159-11ea-98ec-4ccb79a76772.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @PrestaShop/prestashop-product-team, What do you think? it should be fixed in which version.
Thanks!

**Comment by marionf** [comment]
@khouloudbelguith Is it a regression of the 1.7.6 ?

**Comment by khouloudbelguith** [comment]
@marionf, in fact, the theme email is a new feature for PS1.7.6.
With PS1.7.5, it doesn't exist.

Thanks!
