### ISSUE TITLE
Product availability date is displayed even if it's in the past

### ISSUE THREAD

**Issue by awitkutarahil** [PrestaShop/PrestaShop#20659]
#### Describe the bug

Product availability date is useful to tell customers when a given product will be available. But it's displayed even if it's in the past.

#### Expected behavior

If product availability date is in the past, hide it. I will submit a Pull Request.

#### Steps to Reproduce

1. Go to a product page in BO
2. Add a product availability date, select past date
3. Look on FO at product page, click on "details" you see the date, it should be hidden

#### Additional information

* PrestaShop version: develop
* PHP version: php7.2

**Comment by SimonGrn** [comment]
Hello, thank you for your issue.
I reproduce it with PrestaShop 1.7.8 (`develop`) and PHP 7.2 : 
![image](https://user-images.githubusercontent.com/49909275/90783978-0a917a00-e301-11ea-8bc0-027fe3ea48a5.png)


@PrestaShop/prestashop-product-team what do you think ? Is it working as intended ?

**Comment by marionf** [comment]
Hello @awitkutarahil 
This seems like a good idea and can avoid merchants from removing each availability date when it is reached

**Comment by awitkutarahil** [comment]
> Hello @awitkutarahil
> This seems like a good idea and can avoid merchants from removing each availability date when it is reached

Thanks ! That is the idea indeed.

I have submitted a Pull Request to implement that https://github.com/PrestaShop/PrestaShop/pull/20660

**Comment by AldeaG** [comment]
Hi all. 
I have this question but not sure if it is completely related.
I am preparing my store for the next season and I have already placed orders with suppliers that will arrive at the beginning of the year. To get ahead of my work, I want to prepare the CSVs and upload them to Prestashop, but I don't want them to be available or visible for order until then. How do I prepare the CSV so that the availability date is exactly as planned? On other occasions I have done the same, but even setting a later availability date, the products were seen and could be ordered, thus losing their effectiveness.

In the section to import Products and/or Import Combinations there is the option of availability date. Can you put different availability dates to different combinations (colors) since each color arrives on a different date?
