### ISSUE TITLE
Allow merchants to easily configure, what data do they want to see in BO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#20669]
#### Is your feature request related to a problem?

One of the first things I do for every client is customizing order list and product list. They do not care about some information and they want some extra information.

Example - orders: removing new client, removing country, adding carrier
Example - products: adding manufacturer. adding mpn

#### Describe the solution you'd like

- User could click a **"settings"** button, then select **"choose and reorganize columns"**.
- A modal would pop up. In the modal, there would be a table with position, column name and checkbox to hide or show the column.
- He would select fields he wants to display by checkboxes and reorder them. (using the same mechanism as reordering categories for example)

#### Quick sketch
![1](https://user-images.githubusercontent.com/6097524/90895016-c0bc9880-e3c1-11ea-98a1-2ca79dc85de6.png)

![2](https://user-images.githubusercontent.com/6097524/90895022-c2865c00-e3c1-11ea-90ae-05832aad74d2.png)

**Comment by matks** [comment]
ping @prestascott I think you mentioned that 👍

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your report.
Ping @PrestaShop/prestashop-product-team what do you think?

Thanks!

**Comment by Hlavtox** [comment]
@matks @khouloudbelguith @prestascott Added a quick sketch

**Comment by PululuK** [comment]
@Hlavtox  man you're in the future  😅
Very good idea !!

**Comment by prestascott** [comment]
Hi everyone,

Thank you @Hlavtox for your report, it's very interesting!
Your sketches are almost identical as mine that is why I thought they were mine haha

In fact, we did some interviews by the end of the year of 2019 about tables in the BO and one of the insight were that our users wanted to manage their columns by hiding some, and sometimes adding others. This improvement will definitely be a good thing for PrestaShop. 

I added an 'edit button' in the last column to show and manage columns, but it can also be placed in the 'settings' button like you did so the table has more space by removing the last column. 
I also added the drag & drop feature so it will be easier for users to reorder columns as they want.

These were my design propositions, please don't mind the wording on the second one because it's an export so keep in mind that it's for column management. The difference is that the first doesn't need to refresh the page because it instantly changes the layout of the columns according to which columns are checked. 
Second one is a modal with a save button in order to confirm changes and it needs to refresh the page.

FIRST DESIGN PROPOSITION:
![Manage columns](https://user-images.githubusercontent.com/54888056/90900953-78ee3f00-e3ca-11ea-84e2-bfaebc6424a7.png)

SECOND DESIGN PROPOSITION: 
![Export](https://user-images.githubusercontent.com/54888056/90901700-9e2f7d00-e3cb-11ea-899b-d201f2dff453.png)

**Comment by alfonsolr09** [comment]
will work on this improvement?
