### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by BrunoGonc-lab** [PrestaShop/PrestaShop#20696]
When I try to open the **Modules**>**Modules and Services** or **Payment**>**Payment Methods**, I get a _500 Internal Server Error_.

Last night I updated Paypal but everything was working well. I don't know if it's the reason for this error.

![image](https://user-images.githubusercontent.com/61451077/91142619-610c0900-e6b1-11ea-9119-618351c5a16a.png)

* PrestaShop version: **v1.7.1.2**
* PHP version: **7.0.33**

**Comment by khouloudbelguith** [comment]
Hi @BrunoGonc-lab,

The 500 Internal Server Error can be very frustrating because it is such a vague error. In addition to the error message text itself being vague, there are actually several different issues that can cause the 500 error message to appear.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by BrunoGonc-lab** [comment]
Hi @khouloudbelguith,

I enabled Debug Mode and at the **Module and Services** I get this:

> Attempted to load class "SymfonyContainer" from namespace "PrestaShop\PrestaShop\Adapter".
> Did you forget a "use" statement for another namespace?
> 500 Internal Server Error - ClassNotFoundException

Here's the page with the error.
[Error Log.zip](https://github.com/PrestaShop/PrestaShop/files/5123639/Error.Log.zip)

The javascript console doesn't show more than the 500 Internal Server Error.

Thank you so much

**Comment by khouloudbelguith** [comment]
@BrunoGonc-lab,

You have an issue with the `paygreen` module.
As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
