### ISSUE TITLE
Upgrade the latest Symfony LTS version

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#20739]
#### Is your feature request related to a problem?

PrestaShop is currently based on Symfony 3.4 LTS which will become EoL late 2021, that's a little more than a year from now.

![Screenshot 2020-08-26 at 18 06 05](https://user-images.githubusercontent.com/1009343/91328420-3d3ae700-e7c7-11ea-8b54-eb603df0b8c1.png)

_Source: [Symfony releases](https://symfony.com/releases)_

Since 1.7.8 is due for release early 2021 and probably 1.7.9 won't be out before late 2021, if we don't upgrade Symfony we might end up releasing software based on an unsupported or yet-to-be unsupported framework version.

Therefore, we must consider upgrading to the latests LTS, 4.4.

#### Describe the solution you'd like

Update to Symfony 4.4

#### Alternatives you've considered

- Updating to 5.x instead of 4.4 would provide a better path for upgrading to 5.4 when it's out. However, 5.4 is  due for release in November 2021, which right now appears as too late for 1.7.9. Choosing a non LTS version from the 5.x branch (say, 5.2) would provide a shorter support lifespan for that PrestaShop release compared to 4.4.

### Current status:

- Guzzle will be updated from version 5 to version 7.3
- [Circuit breaker](https://github.com/PrestaShop/circuit-breaker/pull/42) update
- [Header-stamp v2.0](https://github.com/PrestaShopCorp/header-stamp/releases/tag/v2.0) has been released
- [Php dev tools v4.0 ](https://github.com/PrestaShop/php-dev-tools/releases/tag/v4.0) has been released
- The PHP minimum version will be 7.2.5 because of Guzzle 7.3 (`php: ^7.2.5 || ^8.0`)

**Comment by eternoendless** [comment]
The first step is analyzing what needs to be done in order to be able to run on Sf 4.4

If the task seems too complex, we can postpone this for 1.7.9

**Comment by PierreRambaud** [comment]
FYI, we will have to update GuzzleHttp, TranslationsToolsBundle, Circuit-breaker, and many other packages that are not compatible with Symfony 4.

**Comment by eternoendless** [comment]
Symfony 4 uses guzzle? O_o

**Comment by PierreRambaud** [comment]
No, but csa guzzle bundle uses 
```
        "symfony/framework-bundle": "^3.4",
        "symfony/dependency-injection": "^3.4",
        "symfony/http-kernel": "^3.4",
        "twig/twig": "^1.34|^2.4",
        "symfony/expression-language": "^3.4"
```
It's time to update our dependencies instead of continuing forking the world :(

**Comment by eternoendless** [comment]
You know that updating Guzzle will break a lot of modules

**Comment by matks** [comment]
@eternoendless we will face this issue over and over in the incoming years. Even if we manage to release 1 major version per year, it will only mean "yeah this is a major update so we cant break whatever we want".

What if the root cause is different?

Hexagonal architecture teaches us not to rely on implementations but on interfaces to allow easy replacement of component. Maybe our mistake was to tell people our Composer dependencies are part of PrestaShop public API.

My question/suggestion is:
- should we continue to say all our Composer dependencies are part of PrestaShop public API? maybe we should define what belongs to it and what does not
- should we start creating interface (exemple: PHPCurlClientInterface) that are being implemented by a Guzzle Adapter, allowing us to modify Guzzle version behind the adapter at will while interface remains backward compatible

**Comment by PierreRambaud** [comment]
I know, but we can't continue to update forks, it's ugly and against all good practices :/

**Comment by eternoendless** [comment]
Yes but modules are using Guzzle now. What do we do with that?

**Comment by matks** [comment]
> Yes but modules are using Guzzle now. What do we do with that?

What about
1. we warn everybody that we cannot keep our SemVer promise for Guzzle (and other libs, to be identified) for PS 1.7.9 (= build article)
2. in 1.7.8 we introduce new interfaces and classes to wrap the future implementation and add deprecation messages for existing code
3. in 1.7.9 we perform the upgrade and we write a detailed article about what has been changed and how to update their code

By the way maybe we could look at the upgrade diff right for (step 3). Maybe actually there's not so many differences. Or it could be polyfilled.

**Comment by PierreRambaud** [comment]
We will have to be compatible with PHP8.0, Symfony 4.4 for the 1.7.8.0 and not only for security reasons. Using old, outdated and unmaintained packages is dangerous :/

**Comment by kpodemski** [comment]
From my point of view, the faster we warn everybody the less problems we'll have.

IMO communication is the key, let developers know as early as possible and they'll handle it, we know that it's impossible to keep everything backward compatible, I think it's time to stop wasting energy in a fight that cannot be won?

**Comment by eternoendless** [comment]
The problem is that module developers will be forced to maintain two separate packages for <1.7.8 and >1.7.8, and some developers might take a long time to do that, which may hold back adoption of 1.7.8.

**Comment by PierreRambaud** [comment]
One day or another, they will have to do it. 
We use packages that are not maintained anymore, if they receive security issues, we will not be able to fix it without forking.
I think the solution from @matks is the best one. If we provide interface/helpers to use requests, it will do the job whatever the version of PS you used.

**Comment by rblaurin** [comment]
So... can we expect classes to wrap Guzzle in 1.7.8?

**Comment by eternoendless** [comment]
That's a complicated business. By the looks of it, 1.7.9 is shaping up to be a "semi major" version (php 8 compatibility, symfony update, guzzle update, and much more)

**Comment by amoutiers** [comment]
I'm not a Prestashop developer, but a PHP one, mainly Drupal. I came across this repo to help a friend with his online store.

If you have API changes, you must bump your next release to 1.8.0

I agree with updating to SF 5.3 (release in May) and provide Interface Wrapper will be your best scenario.

**Comment by matks** [comment]
> I agree with updating to SF 5.3 (release in May) and provide Interface Wrapper will be your best scenario.

We are rather targeting SF 4 instead of SF 5. We think jumping from SF 3 to SF 4 will introduce less BC breaks than SF 3 to SF 5 🤔  but I did not verify this.

> If you have API changes, you must bump your next release to 1.8.0

I see why you say that 😄  but it's not that simple.

Also [in theory SemVer says that bumping Symfony version is not a BC break](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api) but I disagree with this statement 😛

**Comment by amoutiers** [comment]
Bumping to SF >= 5.2 and you get PHP8. And that's less work to get into 5.4 LTS after.

**Comment by PierreRambaud** [comment]
Status update:

- Guzzle will be updated from version 5 to version 7.3
- [Circuit breaker](https://github.com/PrestaShop/circuit-breaker/pull/42) update
- [Header-stamp v2.0](https://github.com/PrestaShopCorp/header-stamp/releases/tag/v2.0) has been released
- [Php dev tools v4.0 ](https://github.com/PrestaShop/php-dev-tools/releases/tag/v4.0) has been released

**Comment by PierreRambaud** [comment]
The PHP minimum version will be 7.2.5 because of Guzzle 7.3 (`php: ^7.2.5 || ^8.0`)

**Comment by mickaelandrieu** [comment]
Hello.

> Also in theory SemVer says that bumping Symfony version is not a BC break but I disagree with this statement.

PrestaShop code rely directly on some Symfony/Doctrine interfaces and classes and some of them won't exists in v4 or v5.
If you plan to migrate before the next major of PrestaShop itself, I think it's a rely good time to use your own interfaces as @matks suggested.

Also :

> Guzzle will be updated from version 5 to version 7.3

Good news : better late than never 👍

> Circuit breaker update

How about https://github.com/loveOSS/resiliency instead ? 
* No direct/hard dependencies on Guzzle nor Symfony : provide your own PrestaShop Client and "Voilà".
* Only (big!) issue : min version >= PHP 7.4. 
Anyway, I advice you _strongly_ to rely on the Symfony Http Client instead of Guzzle as the interfaces are the same on Symfony 4 and 5 (thanks to symfony/contracts package).

> The problem is that module developers will be forced to maintain two separate packages for <1.7.8 and >1.7.8, and some developers might take a long time to do that, which may hold back adoption of 1.7.8.

How many people have used Guzzle directly in their modules : 1%, 0.1%, 0.01% ?
But let's say we want to fix this issue, no matter how many people are impacted !
As you know I've been involved in solving this issue before as the former contributor of the Guzzle client in PrestaShop and the former contributor of the Circuit Breaker library. 
I've ended up with 2 options :

#### Option 1 : quick & dirty
You provide the code to help the module developers guess which version of Guzzle is used, and they all introduce a "if/else" block in their modules.

* Pros : (Almost) no work for the module developers
* Cons : Dirty code shipped in the modules, and one more to do in the next major of PrestaShop

#### Option 2 : clean & time consuming
Introduce a new micro package PHP that the Core team could maintain until the release of the next major, which provide PHP client that works with the same API on PrestaShop 1.7.0+. Module developers require this package and rely on it : this package will stay the same until the end of PrestaShop 1.7.

Something like :

```php
// before in a PS module
$response = $guzzleClient->get('some_url', ...);

// after, with a new package (works in 1.7.0+, must not depends on Guzzle)
use PrestaShop\Legacy\HttpClient; // whatever
$client = new HttpClient(...);
$response = $client->get('some_url', ...);
```

* Pros : Clean by design, could be given up once PS 1.8 is released and no more Guzzle issue !
* Cons : Create and maintain a new package, lot of work

So ... yeah, people will have to update there module and include this new package. And you will have to maintain this client.
But, you will fix once and for all the issue about Guzzle which is a pain in the ass since a bad developer introduced it (guess who 
 ? 😏).

Good luck : dunno how I ended up answering this thread, maybe because this was the kind of challenges I've enjoyed in my previous career xD

**Comment by pablomartin89** [comment]
Symfony 4.4 has : 

End of bug fixes:
November 2022

![image](https://user-images.githubusercontent.com/16488733/140477576-290b5ebb-7952-4ed1-9ba5-77ae162e2d63.png)

Maybe it have sense to migrate to 5.4 after launch v8 :)

**Comment by eternoendless** [comment]
We will likely do that in 9.0
