### ISSUE TITLE
Accessing Symfony services through webservice call

### ISSUE THREAD

**Issue by Slews** [PrestaShop/PrestaShop#20740]
Hello,

I am working on a module which declare its own services.

The module needs to call a service on actionObjectOrderCarrierUpdateAfter hook call.

So, according to the Prestashop documentation (https://devdocs.prestashop.com/1.7/modules/concepts/services/#accessing-your-services), we use:

`$yourService = $this->context->controller->getContainer()->get('your_company.your_module.front.your_service');`

But it triggers the following PHP error:

`PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getContainer()`

I guess the reason is that there is no controller initiate while processing to a webservice action. Am I right ?

We also tried to use:

`SymfonyContainer::getInstance()->get('your_company.your_module.front.your_service');`

But with the same result (prestashop seems to not be able to return a SymfonyContainer instance):

`PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get() on null`

Is there a way to get Symfony services while a webservice call or do we have to completely avoid the use of Symfony services in that case ?

**Comment by sarahdib** [comment]
Hello, 

Please be aware that this bug tracker should be used to report issues only. 
If you need help, you can ask on the :
- Forum (https://www.prestashop.com/forums/)
- Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop)

You can also join slack in order to discuss with developer : https://github.com/PrestaShop/open-source/blob/master/slack/readme.md

Thanks for your understanding!
