### ISSUE TITLE
 hook action order grid not work

### ISSUE THREAD

**Issue by JulianoSGomes** [PrestaShop/PrestaShop#20745]
Hi, on my custom module i followed [this documentation steps](https://devdocs.prestashop.com/1.7/modules/sample-modules/grid-and-identifiable-object-form-hooks-usage/) for add columns on customer grid, it works, so i tried to replicate for the order grid but nothing happens. 
Prestashop version: 1.7.6.7

```php
    public function install()
    {
        return parent::install() &&
            ...
            $this->registerHook('actionOrderGridDefinitionModifier') &&   \\ this not works
            $this->registerHook('actionCustomerGridDefinitionModifier') && \\ this works
           ...
    }



    public function hookActionCustomerGridDefinitionModifier(array $params)
    {
        ...
    }

    public function hookActionOrderGridDefinitionModifier(array $params)
    {
        ...
    }

```

**Comment by sarahdib** [comment]
Hello, 

Please be aware that this bug tracker should be used to report issues only. 
If you need help, you can ask on the :
- Forum (https://www.prestashop.com/forums/)
- Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop)

You can also join slack in order to discuss with developer : https://github.com/PrestaShop/open-source/blob/master/slack/readme.md

Thanks for your understanding!
