### ISSUE TITLE
Problem not solved - Deleting product combinations

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#20786]
Hi @SebastienLi,

Thanks for your feedback.
I close the issue, feel free to open a new one when needed.

Best regards, Khouloud

_Originally posted by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/issues/10198#issuecomment-417227503_

**Comment by loetje88** [comment]
Still same problem on 1.7.5.

No error or anything, combinations simply will not disappear when deleting them.

Force compilation is on, cache is off, cleared cache manually many times, edit the code to .htacces file - nothing works.

Save buttons becomes grey as well while processing until i do a refresh of the page (does not finish processing as well) but eventually wont delete any combinations.

Very annoying that this still happends after releasing many previous versions, and even the new ones, but old problems cannot be solved.

I have several domains at same hoster, with exact same configuration, this problems only happends with presta 1.7 installations.

**Comment by SimonGrn** [comment]
This is a new issue you created when answering an old issue.
Please use the correct template.

I close this one.

PS: if your issue is not reproduced on newer versions of PrestaShop, we will not be able to do anything for you except encouraging you to update your installation. Remember that you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**Comment by loetje88** [comment]
> This is a new issue you created when answering an old issue.
> Please use the correct template.
> 
> I close this one.
> 
> PS: if your issue is not reproduced on newer versions of PrestaShop, we will not be able to do anything for you except encouraging you to update your installation. Remember that you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).


And what template should that be?

Instead of closing actual tickets due to customer not using any "templates" , the team maybe should just focus on solving the problems?
This is a long excisting problem that is not solved.

**Comment by SimonGrn** [comment]
> And what template should that be?

The "new issue" one. 

> Instead of closing actual tickets due to customer not using any "templates" , the team maybe should just focus on solving the problems?

Pleas remember you're talking to actual people and not robots dedicated to answer 24/7. I understand you're encountering an issue but this is not a valid reason to be rude. 
When we ask people to follow the template it's not to be annoying, it's because it helps us work faster on your problems. We're a small team. You can learn more about why we're enforcing our own rules [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

> This is a long excisting problem that is not solved.

As you can read on the original issue, the main culprit was the server not allowing PUT and DELETE methods. I see you tried to edit your .htaccess but to no avail. I can also see that I'm not able to reproduce your issue on the latest version (1.7.6.7). I then strongly advise you to upgrade your version of PrestaShop as no more patch versions will be issued for the 1.7.5 branch (the last version for this branch, 1.7.5.2, was released in May 2019).

**Comment by SimonGrn** [comment]
> And what template should that be?

The "new issue" one. 

> Instead of closing actual tickets due to customer not using any "templates" , the team maybe should just focus on solving the problems?

Please remember you're talking to actual people and not robots dedicated to answer 24/7. I understand you're encountering an issue but this is not a valid reason to be rude. 
When we ask people to follow the template it's not to be annoying, it's because it helps us work faster on your problems. We're a small team. You can learn more about why we're enforcing our own rules [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

> This is a long excisting problem that is not solved.

As you can read on the original issue, the main culprit was the server not allowing PUT and DELETE methods. I see you tried to edit your .htaccess but to no avail. I can also see that I'm not able to reproduce your issue on the latest version (1.7.6.7). I then strongly advise you to upgrade your version of PrestaShop as no more patch versions will be issued for the 1.7.5 branch (the last version for this branch, 1.7.5.2, was released in May 2019).

Thank you for your understanding.
