### ISSUE TITLE
FO - Create a customer account - Property Customer->optin is empty.

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#20801]
#### Describe the bug

In the FO > Create an account page > an exception is displayed
`Property Customer->optin is empty.` if BO admin has created a impossible configuration

#### Expected behavior

Please see the messages below this post. We should add a warning message in the back-office to inform Back-office admins to NOT modify settings into a impossible configuration.

Nice-to-have: Additionally, even if the shop has been given an impossible configuration we should NOT display an exception page on FO. Instead of a exception page, the FO should prompt an error page / error message.

#### Steps to Reproduce

1. Go Back-office (BO) > Shop parameters > customer settings then do: _disable "partner offers"_
2. Go to BO > Customers page > use "Define required fiels" button at the bottom and set "Partner offers" as required
3. Go to Front-office (FO) > go on login page, click on "create a new account", fill the form, submit and see exception bug

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/91836613-53bfc300-ec4b-11ea-805a-d24741f804f3.png)

#### Additional information

* PrestaShop version: 1767, 177X, develop
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi,

To fix this issue, just go BO > Shop parameters > customer settings > enable "partner offers".
![image](https://user-images.githubusercontent.com/16067358/91836833-9c777c00-ec4b-11ea-9283-05260d2846cc.png)

**Comment by LouiseBonnard** [comment]
Hi @khouloudbelguith, thanks for this issue. Do you need a better exception wording here?

**Comment by khouloudbelguith** [comment]
Hi @LouiseBonnard,

Yes :+1: 
For example an alert
![image](https://user-images.githubusercontent.com/16067358/92583796-2601fc00-f293-11ea-94b3-e862865933d2.png)

Thanks!

**Comment by Julievrz** [comment]
@LouiseBonnard @khouloudbelguith I don't understand where the alert message will appear and what it should contains? Is "Your information is incomplete, please update it" just a random example?

**Comment by khouloudbelguith** [comment]
Hi @Julievrz,

For example, when we have an incomplete `Address`, we have this alert.
![image](https://user-images.githubusercontent.com/16067358/94259626-13442400-ff2f-11ea-8668-781a6d0a6ce2.png)

We can add a similar alert in the "Personal Information" step.
@LouiseBonnard what do you think?

Thanks!

**Comment by Julievrz** [comment]
Hi @khouloudbelguith 
I think the alert message should appear in the BO when the merchand requires partner offers on the Customer page.
![image](https://user-images.githubusercontent.com/70583503/94289304-d12fd800-ff58-11ea-9d51-cf6e37b2a3ab.png)


Maybe something like : 

"Before requiring partner offers, please be sure to enable them in the [1] Shop Parameters > Customer Settings[/1] section of the back office. Otherwise, new customers won't be able to create an account and process to check out." 

We could also imagine to add another alert message in the  Customer Settings page when the merchand disables partner offers 
![image](https://user-images.githubusercontent.com/70583503/94289479-0e946580-ff59-11ea-8814-b5e3f5e3f847.png)


saying " "Before desabling partner offers, please be sure they are not a required field in the [1]  Customer [/1] section of the back office. Otherwise, new customers won't be able to create an account and process to check out." 

@LouiseBonnard What do you think of the wording?

**Comment by Julievrz** [comment]
Following Louise's advice, here is an updated wording : "Before requiring partner offers, please **make** sure you enabled them in the [1]Shop Parameters > Customer Settings[/1] section of the back office. Otherwise, new customers won't be able to create an account and **proceed** to checkout."

"Before desabling partner offers, please **make** sure they are not set as required in the [1]Customers[/1] section of the back office. Otherwise, new customers won't be able to create an account and proceed to checkout."

**Comment by Progi1984** [comment]
@Julievrz It's fixed.
