### ISSUE TITLE
Upgrade Bootstrap in admin template

### ISSUE THREAD

**Issue by elburgl69** [PrestaShop/PrestaShop#20808]
#### Current bootstrap version in admin template is 4.0.0. Most recent version is 4.5.x

The admin template uses a rather old version of Bootstrap. This is frustrating since documentation examples from bootstrap can not always be applied to f.e. prestatshop modules. Only to discover, after long trial and error that the feature was not supported in 4.0.0.

When using third-party js scripts (f.e. vue components) it really get messy. Is the problem in the component or bootstrap? 

#### Please upgrade to 4.5.x stable

Please upgrade bootstrap in the admin-dev/new-theme to version 4.5.x.
(npm update bootstrap)

#### Alternatives you've considered

In a custom CSS file for my modules I can copy over the Bootstrap CSS code. However I have to apply the !important tag, which could have side effects.

#### Additional context

N/A

**Comment by sarahdib** [comment]
@NeOMakinG Could you check this ?

**Comment by JoryHogeveen** [comment]
+1

**Comment by matks** [comment]
Hi, unfortunately we cannot do that because it would introduce a very massive Breaking Change 😞 .

You will find all details about this sad topic here:
- https://github.com/PrestaShop/PrestaShop/issues/14533#issuecomment-511464778
- https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/

We wish we could but ... it cannot be done now. We must wait next major release.

But rest assured that this will probably _the very first thing we change (and break !)_ when we work on next PrestaShop major version !
