### ISSUE TITLE
No Email Theme page in PrestaShop v1.7.6.5

### ISSUE THREAD

**Issue by jonpontet** [PrestaShop/PrestaShop#20897]
#### Describe the bug

Despite being launched for v1.7.6 (http://doc.prestashop.com/display/PS17/Email+Theme), I do not find the Email Theme page (under Design in the backoffice) in v1.7.6.5. Did it regress?

#### Expected behavior

I can see that it is working again in v1.7.6.7, but I need it in v1.7.6.5

**Can anyone help me have this working in v1.7.6.5?**

#### Steps to Reproduce

1. You will not find Email Theme menu item under Design in backoffice

**Screenshots**

![Annotation 2020-09-08 154441](https://user-images.githubusercontent.com/20968408/92485081-ca7c3380-f1ea-11ea-9164-fec026f0205a.png)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @jonpontet,

I did not manage to reproduce the issue with PS1.7.6.5.
The Email Theme is well displayed
I attached a screen record
https://drive.google.com/file/d/1TUv1IlZRdxM1FJJvMrm1o0fuuMhR3Y08/view?usp=sharing
Did you use a superadmin employee?

Thanks!

**Comment by jonpontet** [comment]
@khouloudbelguith thank you - I can see it is clearly there. 

Indeed I am superadmin. 

Here is a screenshot of our dashboard where you can clearly see there is no Email Theme link under Appearance
![Annotation 2020-09-09 164051](https://user-images.githubusercontent.com/20968408/92613490-5362a000-f2bb-11ea-86a3-db37a585c21b.png)

**How could a link be removed ? Could it be our theme ?**

**Comment by khouloudbelguith** [comment]
@jonpontet, thanks to navigate to your BO > Advanced Parameters > Databse > create an SQL Query 
`select * from ps_tab ps_tab where  class_name ='AdminParentMailTheme'`
and check if `active = 1`
![image](https://user-images.githubusercontent.com/16067358/92615417-61192500-f2bd-11ea-9c48-45a5eaac8409.png)
If no, your Email theme menu is disabled, you should enable it.

Thanks!

**Comment by jonpontet** [comment]
@khouloudbelguith thanks for the query. I receive no results.

Should I add it?

**Comment by florine2623** [comment]
Hi @jonpontet ,
Yes you can add this line from your database if no result comes up.
Thanks!

**Comment by jonpontet** [comment]
@florine2623 @khouloudbelguith I have added this row but still there is a problem- can you help ?

![image](https://user-images.githubusercontent.com/20968408/92886481-f4646e80-f413-11ea-8704-25010801f475.png)

![image](https://user-images.githubusercontent.com/20968408/92886766-3db4be00-f414-11ea-8d68-0fd8ffd79ac5.png)

**Comment by florine2623** [comment]
Can you search for id_tab = 55 and screenshot what you have ?

**Comment by jonpontet** [comment]
@florine2623 sorry for the delay. Here is the result of id_tab = 55 in ps_tab

![image](https://user-images.githubusercontent.com/20968408/93053686-7d73e380-f668-11ea-83b8-322241c47bd1.png)

Is that good or bad ?

**Comment by khouloudbelguith** [comment]
Hi @jonpontet,

Are you using PS1.7.6.5 fresh install or it is an upgrade from a previous version?

Thanks!

**Comment by jonpontet** [comment]
@khouloudbelguith it is an upgrade from v1.7.4.4

**Comment by khouloudbelguith** [comment]
@jonpontet, have you any errors during the upgrade?
Could you please provide us the log file into the path `/Prestashop_folder/admin-dev/autoupgrade/tmp/`.

Thanks!

**Comment by jonpontet** [comment]
@khouloudbelguith it has been some months since so I do not remember anything specific.

I used the 1 Click Upgrade. Initially be referencing our Dev site as the resource, but when that didnt work I referenced a fresh version of v1.7.6.5.

I can share our log file with you privately - can you provide a way to do so?

**Comment by khouloudbelguith** [comment]
@jonpontet, I did not manage to reproduce the issue with 1765 after an upgrade from PS1744 using the 1-click upgrade v4.10.1.
PS: I used the local archive because now we can upgrade only to 1767.
I attached a screen record
https://drive.google.com/file/d/1cIAciCiwJb8RwErvtmBmvyAfgqassebY/view?usp=sharing
it could be something went wrong with your update and don't have some of the database columns that were added for 1.7.6.5
The solution is to check if there are missing columns in your database schema.
You can find the full schema for 1.7.6.5 here: https://github.com/PrestaShop/PrestaShop/blob/1.7.6.5/install-dev/data/db_structure.sql

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
