### ISSUE TITLE
glyph.png is missing

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#20894]
#### Describe the bug

Active debug mode on prestashop 1.7.7.0-beta2 open console and see error 

We found the directory and the png in prestashop 1.7.6.x  release

But i don't find where the directory **scss** is ignore for the release.

I can  move the file in /admin-dev/themes/new-theme/img/glyph.png

and edit /src/PrestaShopBundle/Resources/views/Admin/WebProfiler/config.html.twig with the good path ?

**Screenshots**

![Capture d’écran de 2020-09-08 14-12-34](https://user-images.githubusercontent.com/5064590/92475251-60a95d00-f1dd-11ea-8843-122a1be2a161.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

I manage to reproduce the issue with PS1770beta2
![image](https://user-images.githubusercontent.com/16067358/92478746-e8de3100-f1e2-11ea-90bc-791bbfc4bdf3.png)
It is ok with PS1.7.6.7
![image](https://user-images.githubusercontent.com/16067358/92478788-fbf10100-f1e2-11ea-8981-a9afeebc0aef.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

The issue fixed with 1.7.7.x branch.
![image](https://user-images.githubusercontent.com/16067358/92481689-00b7b400-f1e7-11ea-9eb4-5061ca01bcc7.png)
I close this issue since it is fixed.

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith 

I download the Nightly releases of PrestaShop 

https://console.cloud.google.com/storage/browser/_details/prestashop-core-nightly/2020-09-07-1.7.7.x-prestashop_1.7.7.0.zip

The scss folder is not present i think is  When a version is made the scss folder are ignored now ?

**Comment by khouloudbelguith** [comment]
@okom3pom, I tried to install this version, but I don't have an error in the console about `glyph.png`.
https://drive.google.com/file/d/1S0Od04asv2xD6AAKmO8-NQTrgBBYcsGO/view?usp=sharing

Thanks!

**Comment by ghost** [comment]
Active débug :)

**Comment by khouloudbelguith** [comment]
@okom3pom, you are right.
Thanks for the clarification.
![image](https://user-images.githubusercontent.com/16067358/92495732-8f343180-f1f7-11ea-859c-6539dfd65078.png)
Ping @PrestaShop/prestashop-core-developers what do you think?
This issue is reproduced with releases 1770beta2, Nightly release.
With 177x branch => ok
PS: with PS1767 => ok

@okom3pom, I will re-open the issue.

Thanks!

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/blob/develop/tools/build/Library/ReleaseCreator.php#L128

**Comment by matks** [comment]
Hi @okom3pom thanks for trying the beta 2 and the nightly !

Indeed SCSS files should be removed from ZIP archives built for shops.

Ah, I see we're talking about the SF debug bar.

**Comment by Progi1984** [comment]
Fixed by #20911
