### ISSUE TITLE
Classic theme uses alpha version of Bootstrap

### ISSUE THREAD

**Issue by JoryHogeveen** [PrestaShop/PrestaShop#20901]
Currently the classic Prestashop theme uses Bootstrap v4.0.0-alpha.5
Even though I don't get why an alpha release was distributed in the first place, I believe it's best to update this to the latest version a.s.a.p.

Related issue (admin): #20808

* PrestaShop version: latest
* PHP version: N/A

**Comment by matks** [comment]
Hi, unfortunately we cannot do that because it would introduce a very massive Breaking Change 😞 .

You will find all details about this sad topic here:
- https://github.com/PrestaShop/PrestaShop/issues/14533#issuecomment-511464778
- https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-3-the-future-architecture/

We wish we could but ... it cannot be done now. We must wait next major release.

**Comment by Koubae** [comment]
End of 2022, almost 2022, and the theme is still using **4.0.0-alpha.5**
[classic-theme](https://github.com/PrestaShop/classic-theme/blob/develop/_dev/package.json)

From https://github.com/PrestaShop/PrestaShop/issues/14533#issuecomment-511464778:

> **_In PrestaShop 8, we'll be able to switch to a new theme. In the meantime, there's classic-rocket which is basically an improved classic theme._**

Well, this didn't age well I guess.

**Comment by justeen35** [comment]
You want to change this? Then go and help the hummingbird project https://github.com/PrestaShop/hummingbird it's the next theme

It will be much more efficient than complaining here while other people do the work instead of you

**Comment by JoryHogeveen** [comment]
@justeen35 
I understand your comment and totally agree with you regarding contributing to open source projects.
As a contributor to several open source projects I can relate to feeling annoyed when your free work is criticized.

However, this tone will not make other dev's wanting to contribute at all.
If anything, it'll make then look for alternatives instead.

I didn't know about the Hummingbird project at the time (did it exist in 2020?). Hence the reason I didn't follow up on this topic anymore after it was closed and simply created my own theme.

Anyhow, since the PS team announced that it would switch to a new modern theme at PS-8 you can't be surprised if users comment on this when it didn't happen.. Don't announce things you cannot guarantee.

I'd say that with the whole funding and marketplace revenue etc. that PS should have plenty of resources to make these type of improvements happen according to plan:
https://getlatka.com/companies/prestashop
https://growjo.com/company/PrestaShop

**Comment by ShapesGraphicStudio** [comment]
Hello,
Almost end of 2023 and now on the new major version PrestaShop classic theme is still using Bootstrap v4.0.0-alpha.5. It's really a pity for such a CMS.

**Comment by matks** [comment]
@ShapesGraphicStudio Are you willing to contribute to this open source project to make it better?

**Comment by ShapesGraphicStudio** [comment]
Whithin my time and skills limitation yes I would! What would it ask from me?

Regarding the theme, I know it's a lot of work and I think I would not complain about using Bootstrap 4.4 or 4.6 but 4.0 alpha is really outdated and the alpha is not really reassuring.

As of the project being open source I'm sorry but I do not totally agree as there is a lot of marketing around PS. And there should be some revenue too from the marketplace and the partners and experts programs.

**Comment by matks** [comment]
Regarding the theme: the new theme that will replace Classic Theme and make us all forget about Bootstrap 4.0 alpha is almost ready. It's Hummingbird https://github.com/PrestaShop/hummingbird/

Hummingbird is almost ready to be released as a 1.0.0 . We plan to add it inside PrestaShop 9 next to Classic theme: people who download PS9 would have the 2 themes available in the ZIP.

However we're not planning to make Hummingbird the default theme of PS9 because it's a huge step forward and we want the theme to be battle-trained before it's being used by hundred of merchants. That's why the plan is
- test it now, ask people to use it and give us feedback
- put it as 2nd theme inside PrestaShop 9
- in PrestaShop 10 remove Classic theme definitely and Hummingbird becomes the default theme

**What can you do to help us achieve this**

1. You can try Hummingbird! Please install it on PrestaShop 8.1 and test it! The more tests we do the more we are confident in releasing a 1.0
2. If you find bugs in Hummingbird, submit a Pull Request to fix them 😉 and help us make one more step towards the release of Hummingbird 1.0 ... and the death of Classic theme

**Disclaimer** 😛 

The above is a plan: I can't promise it will happen just like this. If we discover a massive flaw inside Hummingbird, maybe we'll have to postpone it. If we get multiple bad feedbacks, same. Also maybe there will not be enough people to finish it before PS9 is released. I can only tell you what we plan and hope to achieve, I can't guarantee the outcome

**Comment by ShapesGraphicStudio** [comment]
OK, I will test Hummingbird on a test site to see how it looks and works.

I strongly agree to not rush to make it default theme as lots of shops must be running with a classic theme child theme.

I'm currently struggling with 2 important shops because I was using PrestaRocket classic rocket theme as parent theme which now seems abandonned as I can see no support for PrestaShop 8.x and I think the need to switch to 8 is urgent to be able to switch PHP to 8.

So I'm rewriting my child theme to be prestashop classic theme children.
And downgrading Bootstrap was not something I thought I would have to do.

Helping the project would really be something I would like to do, I tried to take a look at the expert program but it was quite expensive.

**Comment by Oksydan** [comment]
Hi @ShapesGraphicStudio 

If you need something up to date, build be prestashop community. There is Falcon theme project https://github.com/Oksydan/falcon. It's bootstrap 4.6 based. We are working on version 4 right now with bootstrap 5.3. I will be first core.js less, jquery less prestashop theme. If you can't wait for hummingbird theme hop on the Falcon train and maybe you will stay for a while.
