### ISSUE TITLE
Mobiledetect missing some devices

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#20937]
#### Describe the bug

Missing some devices Example : [`Android SM-T510`](https://www.samsung.com/be_fr/tablets/galaxy-tab-a-10-1-t510/SM-T510NZKDLUX/) .

#### Expected behavior

The following code must display `2` in [`Android SM-T510`](https://www.samsung.com/be_fr/tablets/galaxy-tab-a-10-1-t510/SM-T510NZKDLUX/) devices  [See](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Context.php#L123)

```php

<?php

require_once __DIR__.'/config/config.inc.php';
echo Context::getContext()->getDevice(); 
```

#### Steps to Reproduce

- Create a php script in your root folder  (`my_script.php`): 
```php

<?php

require_once __DIR__.'/config/config.inc.php';
echo Context::getContext()->getDevice(); 
```
- Try to call `www.your_site_url.fr/my_script.php` In [`Android SM-T510`](https://www.samsung.com/be_fr/tablets/galaxy-tab-a-10-1-t510/SM-T510NZKDLUX/)
-   This code will display 4 (mobile type) [See](https://www.samsung.com/be_fr/tablets/galaxy-tab-a-10-1-t510/SM-T510NZKDLUX/) 
- This should return 2 (tablet type) [See](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Context.php#L123)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @PululuK,


I tried with Samsung Galaxy Tab 4
![image](https://user-images.githubusercontent.com/16067358/92756506-2da5cb80-f38d-11ea-9ed9-87ba9b3ba26c.png)
I tried with Samsung Galaxy Tab S6
![image](https://user-images.githubusercontent.com/16067358/92756782-69409580-f38d-11ea-8328-e07c131be0b8.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
