### ISSUE TITLE
Where are the statistics of the products in the promo?

### ISSUE THREAD

**Issue by kenlog** [PrestaShop/PrestaShop#20955]
Hi guys, do you know a way to get the data of the promotional products sold?

Thanks for the lighting :bulb:

**Comment by florine2623** [comment]
Hi @kenlog ,
In PS 1.7.6.7, there's no **specific** information about **On sale** items.
You will have to see for yourself by creating SQL queries.
For example :
`SELECT * from ps_product WHERE on_sale = 1;`
You will be able to see all "On sale" product and from that, you can create other queries in order to get the data you need.

You can also check on [Addons](https://addons.prestashop.com/) if they are modules that suit your needs.

Thanks!
