### ISSUE TITLE
Upgrade to new version fails at 'ALTER IGNORE TABLE...' Queries with MySql server >= 5.7

### ISSUE THREAD

**Issue by Markus-Gurkcity** [PrestaShop/PrestaShop#21014]
#### Describe the bug

If you upgrade your PrestaShop version < 1.6.1.0 to a newer version (manual or with Autoupgrade module) it fails with MySql server version >= 5.7

In some sql upgrade files there are 'ALTER IGNORE TABLE ...' queries. 
For example in file /install-dev/upgrade/sql/1.6.1.0.sql on line 139:
ALTER IGNORE TABLE `PREFIX_image` ADD UNIQUE KEY `id_product_cover` (`id_product`,`cover`);

But 'ALTER IGNORE TABLE' is deprecated and removed in MySql Version 5.7 and higher:
https://dev.mysql.com/worklog/task/?id=7395

#### Expected behavior

Turn all 
'ALTER IGNORE TABLE ...'
to
'ALTER TABLE ...'

#### Steps to Reproduce

Install a PrestaShop version below 1.6.0.4
Use the autoupgrade module to upgrade the shop tho the latest version.
The autoupgrade module will throw a error at some sql upgrade files.

**Comment by florine2623** [comment]
Hello @Markus-Gurkcity ,
PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you

**Comment by jf-viguier** [comment]
Hello,

This issue should be reopened because 1.6 upgrade tu 1.7 is still supported and is in the code i.e. : 
https://github.com/PrestaShop/PrestaShop/blob/83d0a653faac3a88b6d9840092a507eac37ad892/install-dev/upgrade/php/update_modules_sql.php#L31

Prestashop should support mysql 5.7+, there is no maximum version there https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

MySQL 5.7 Compatibility is from Prestashop 1.6.1.4 : 
https://github.com/PrestaShop/PrestaShop/pull/4507

**Comment by matks** [comment]
@jf-viguier thanks for the notice, indeed this issue seems important

ping @atomiix @PierreRambaud

**Comment by atomiix** [comment]
@jf-viguier Are you sure about this? It seems that `PrestaShop/install-dev/upgrade/php/update_modules_sql.php` is only called when migrating from a version of PrestaShop < 1.4.0.5

**Comment by jf-viguier** [comment]
@atomiix it's just an example, there are others ALTER IGNORE in upgrade folder.

**Comment by ioniks** [comment]
Hi,

You can check the upgrade SQL file for 1.6.1.0.
https://github.com/PrestaShop/PrestaShop/blob/1.7.0.x/install-dev/upgrade/sql/1.6.1.0.sql

Many `ALTER IGNORE TABLE .... ADD KEY ....`

All the `ALTER IGNORE TABLE .... ADD KEY ....` fails because Mysql >= 5.7 don't support `IGNORE` in `ALTER` queries

https://dev.mysql.com/worklog/task/?id=7395

I have done recently a 1.6.0.11 Update to 1.6.1.24 and i have all this error on Mysql 5.7

**Comment by jf-viguier** [comment]
"No change required" label is still there.
Thanks @ioniks

**Comment by hibatallahAouadni** [comment]
Hello @Markus-Gurkcity 

Did you try to upgrade your shop from 1.6.0.1 to 1.6.1.24 and then to 1.7.7.2?
Please check and feedback.

Thanks!

**Comment by ioniks** [comment]
> Hello @Markus-Gurkcity 
> 
> Did you try to upgrade your shop from 1.6.0.1 to 1.6.1.24 and then to 1.7.7.2?
> Please check and feedback.
> 
> Thanks!

In MySQL 5.7 alter ignore is not compatible, the only solution is to use MySQL 5.6.

**Comment by Markus-Gurkcity** [comment]
Hi, I tried to uprgade from version 1.6.1.24 to 1.7.7.0

**Comment by florine2623** [comment]
Hello @Markus-Gurkcity ,
You should be using MySQL 5.6.
Can you check this article : https://dev.mysql.com/worklog/task/?id=7395 

Thanks

**Comment by florine2623** [comment]
Hello,
since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.
Thanks!

**Comment by jf-viguier** [comment]
@florine2623
>You should be using MySQL 5.6.

It's not a good advice, the devdoc recommand a recent version.
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
"MySQL: 5.6 minimum, a recent version is recommended."

Please reopen the issue, it's a real one.
