### ISSUE TITLE
Block "instead of" in DisplayPackPrice is missing

### ISSUE THREAD

**Issue by hiro-software** [PrestaShop/PrestaShop#21034]
#### Describe the bug

The displayPackPack in controllers/front/ProductController.php is not assigned well. Let's see the line code:

$this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < $this->product->getNoPackPrice()) ? true : false);

In that line, $productPrice is float, but $this->product->getNoPackPrice() is formattted price, so in that comparation, it can be false even the noPackPrice is greater than pack price

#### Expected behavior

The block "Instead of" should be displayed allways a pack price is lower than no price pack. 

#### Steps to Reproduce

1. Create a product with a price of 7.99€, tax included
2. Create a pack that includes the previous product, with a pack price of 23€, tax included
3. Go to pack product page. The block "Instead of" is missing

**Screenshots**
![pack-ok](https://user-images.githubusercontent.com/53755049/93459056-73a8e500-f8e1-11ea-9634-997fc6056121.png)

![pack-error](https://user-images.githubusercontent.com/53755049/93459079-799ec600-f8e1-11ea-9a32-bdf8c4fdcfa3.png)

#### Additional information

* PrestaShop version: 1.7.6.1 (failure still happens)
* PHP version: 7.1

**Comment by florine2623** [comment]
Hi @hiro-software ,

I have reproduce the same issue in PS 1.7.6.5 and PS 1.7.7.0.

When the difference between the pack price and the total of the product is < 1, the displayPackPrice does not show.
![Capture d’écran 2020-09-17 à 14 39 12](https://user-images.githubusercontent.com/16019289/93471433-a360e880-f8f3-11ea-831f-2293c6c25234.png)
![Capture d’écran 2020-09-17 à 14 39 23](https://user-images.githubusercontent.com/16019289/93471445-a5c34280-f8f3-11ea-9544-aaed97edaeef.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by Prestaworks** [comment]
This should be solved in ProductController.

change
$this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < $this->product->getNoPackPrice()) ? true : false);
to
$this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < Pack::noPackPrice((int) $this->product->id)) ? true : false);
on line 327

**Comment by Fukitsune** [comment]
Hello,

Is it possible to display NoPAckPrice in backend / admin ? In the detailed product sheet ?

Sincerely
