### ISSUE TITLE
Product price with ecotax is false in webservice

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#21051]
#### Describe the bug
Order a product with ecotax. Check product price excluding tax with webservice order_details method.
This ex. tax price includes ecotax **with** tax.

#### Expected behavior
A price excluding tax should include ecotax without tax too OR shouldn't include ecotax.
I think you should mix ex.tax with inc.tax.
price ex.tax + tax should be equals to price inc.tax. It's not true now.

#### Steps to Reproduce

1. Add ecotax onto a product
2. Order it, VAT must be applied
3. Check amount with a browser or Postman in order_details webservice method

**Screenshots**

![2020-09-18 07_52_14-Mozilla Firefox](https://user-images.githubusercontent.com/6622400/93561277-2e89bf00-f984-11ea-9911-a115411f14a3.png)

1 => product price is in fact 169.00 ex.tax
2=> in order to find 174.00, you should add ecotax inc.tax (5.00)
3 => VAT is 20%. 174.00 * 1.2 != 207.80

#### Additional information

* PrestaShop version: 1.7.6.5 (found onto a customer shop, i don't tested it onto other version, but i don't see something about it onto release notes).

Thanks :)

**Comment by florine2623** [comment]
Hi @Max84 ,

I did reproduce your issue in PS 1.7.6.5, but it has been fixed in PS 1.7.7.0.
Here are the results :
In PS 1.7.6.5 : 
![Capture d’écran 2020-09-18 à 09 21 28](https://user-images.githubusercontent.com/16019289/93571954-7238f480-f995-11ea-83b5-26a25e3d3712.png)
In PS 1.7.7.0 :
![Capture d’écran 2020-09-18 à 10 03 01](https://user-images.githubusercontent.com/16019289/93572539-45d1a800-f996-11ea-8861-9a3da3b7c6a3.png)

As it is fixed, I'll close your issue.
Thanks!
