### ISSUE TITLE
[BO][ADVANCED PARAM][MENU] Bulk delete "default" creates an error and crashes the shop

### ISSUE THREAD

**Issue by ngodefroy** [PrestaShop/PrestaShop#21063]
#### Describe the bug

In BO, I go into menu, Bulk actions > delete DEFAULT > I get an error "invalid security token" then I get a 500. Can't reload the page or go back to my shop, I need to reinstall it. 

#### Expected behavior

Lock the possibility to bulk delete the part that is creating the error or fixing the error. 

#### Steps to Reproduce

1. Go to BO>Menu>more
2. Click on Bulk edit, Delete the "Default" 

**Screenshots**

https://drive.google.com/file/d/1J3lqVsp0EsEBFlKQN7LXHCab9d8vKM11/view

#### Additional information

* PrestaShop version: 7.2
* PHP version: 1.7.8

**Comment by marionf** [comment]
In 1.7.7.x this  "menus" page wasn't displayed and if I try to enter directly the controller name in the URL (controller=AdminTabs) I have an error message "Access denied"

![capture d'écran_2790](https://user-images.githubusercontent.com/13449658/93754430-fee7ea80-fc01-11ea-9e1a-adc36437e8fd.png)

Maye I missed something, @LouiseBonnard @MatShir do you know if it's wanted to display this page in 1.7.8 ?

**Comment by LouiseBonnard** [comment]
🤔

It's super weird, I've just browsed the 1.7.8 kanban and I cannot see any merged ticket related to this. Or I've been missing something too. @ngodefroy, it is the first time you run into this page?

**Comment by ngodefroy** [comment]
> 🤔
> 
> It's super weird, I've just browsed the 1.7.8 kanban and I cannot see any merged ticket related to this. Or I've been missing something too. @ngodefroy, it is the first time you run into this page?

Yes, since I arrived, its the first time im testing this page on develop. 
Never saw this on the 177x version.

**Comment by matks** [comment]
It seems that, from this page, you can edit/delete things that are actually quite critical for PrestaShop correct behavior 🤔 

I think deleting the "Default" row from "Menus" listing will create big issues for the shop, and the 1st issue appears in this bug report.

**I suggest that we rather PREVENT people from deleting such important configuration items from Menus**.

**Comment by marionf** [comment]
Hi everyone,

For the history, this page was present in 1.6 and allowed to add, edit, delete, activate / deactivate menus and reorganize them thanks to the position column.
This page was deleted in 1.7.0 because merchants were removing menus and then didn't know how to re-add them because don't know how to find th the controller name.
This page reappeared in 1.7.8 following [the issue](https://github.com/PrestaShop/PrestaShop/issues/15048) opened by @idnovate 
The issue was identified as a bug (instead this was the wanted behavior) and the PR associated has been merged without being validated by PrestaShop's product team.


For the reasons mentioned above and as we only received one request to redisplay this page since the start of 1.7.0, the PrestaShop product team has decided not to restore this page in 1.7.8 (see issue #21107)

The behavior in 1.7.8 will be:
No "menu" tab in the BO menu
An "access denied" message when trying to access directly to the URL controller=AdminTabs
+ We will add message in the code to indicate to the developers how to access to this page if they want to

**Comment by idnovate** [comment]
> * We will add message in the code to indicate to the developers how to access to this page if they want to

How we will be able to access this page? The controller will be restored but not a link from the left menu?
