### ISSUE TITLE
Minus symbol missing if subtotal is discount type

### ISSUE THREAD

**Issue by oscc-es** [PrestaShop/PrestaShop#21067]
https://github.com/PrestaShop/PrestaShop/blob/42833c4097071b46f37b76f6c347fb579447e3e1/themes/classic/templates/checkout/_partials/cart-summary-subtotals.tpl#L37

**Comment by sarahdib** [comment]
Hello @oscc-es ,

since the provided information isn't sufficient to reproduce the issue, we are closing it. Feel free to open a new one with all the requested information. 

Thank you!

**Comment by oscc-es** [comment]
![Screenshot_2020-09-22 Be](https://user-images.githubusercontent.com/57987628/93893817-5c596580-fcee-11ea-85d8-8843ed623ce6.png)

Sorry, I gave the details in the [PR](https://github.com/PrestaShop/PrestaShop/pull/21065) without any issue and when I was required to open one I didn't realize that a description was also required here.

The thing is that in the Classic theme a minus symbol is missing at the checkout's cart summary when subtotal is discount type. I mean the top right summary in the screenshot.

**Comment by khouloudbelguith** [comment]
Hi @oscc-es,

This issue is currently closed, can you open a new one with more information about your configuration.
In fact, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!

**Comment by oscc-es** [comment]
Hi,

Sorry, I skip the issue template by opening the issue from the code line. I have opened a proper [issue](https://github.com/PrestaShop/PrestaShop/issues/21161#issue-708872387) (I hope).

Thanks for your help.

**Comment by SimonGrn** [comment]
> Hi,
> 
> Sorry, I skip the issue template by opening the issue from the code line. I have opened a proper [issue](https://github.com/PrestaShop/PrestaShop/issues/21161#issue-708872387) (I hope).
> 
> Thanks for your help.

Thank you, this is perfect :)
