### ISSUE TITLE
HTML (smarty) id attribute duplication

### ISSUE THREAD

**Issue by dali-rajab** [PrestaShop/PrestaShop#21069]
https://github.com/PrestaShop/PrestaShop/blob/4a38749755e5fe48122cfe81aa18e6b3723649a2/themes/classic/templates/checkout/_partials/steps/payment.tpl#L74

This `id="payment-form"` would be duplicated (since it's inside a foreach loop), let's just change it to `id="payment-{$option.id}-form"`

**Comment by sarahdib** [comment]
Hello @dali-rajab ,

since the provided information isn't sufficient to reproduce the issue, we are closing it. Feel free to open a new one with all the requested information. 

Thank you!

**Comment by dali-rajab** [comment]
@sarahdib please re-open the issue, that doesn't need more informations, it's HTML basics, a HTML page can not have identical IDs !! every one here knows what i am talking about.

The id global attribute defines an identifier (ID) which must be unique in the whole document. Its purpose is to identify the element when linking (using a fragment identifier), scripting, or styling (with CSS). 
source : https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by NeOMakinG** [comment]
@dali-rajab

Hello,

I agree with you, this is a problem and a disrespect of HTML best practices.

Btw, could you please provide some informations in order to reproduce it ? It looks like it's on payment step.

Just follow the issue template and I'll open it again, and probably fix it in next days, except if you want to provide the PR :)

Here is the template : 

```
<!--
****************************
DO NOT disclose security issues here, contact security@prestashop.com instead!
****************************
-->

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A
```

I think @sarahdib closed it because it's not respecting this template at all, and that's it, and I agree with that choice, dealing with ton of issues force us to take some decisions about a certain workflow in order to avoid being in a chaotic area 

Thanks for you'r report anyway 😃
