### ISSUE TITLE
ps_sharebuttons module - Undefined index: product

### ISSUE THREAD

**Issue by web-plus** [PrestaShop/PrestaShop#21170]
>EDit by Khouloud
Steps to reproduce the issue:
1. Install the `productcomments` module
2. Go to BO > Design > Positions page
3. Click on the Transplant button
4. select the ps_sharebuttons module
5. select the displayAfterProductThumbs hook
![image](https://user-images.githubusercontent.com/16067358/94407953-6f4bba00-0174-11eb-9623-4ab33ee59d13.png)
6. Save
7. Go to FO > Product page
8. see error
-------------------------------------------------------------------------
Go to theme.yml and try to hook ps_sharebuttons module into displayAfterProductThumbs

      displayAfterProductThumbs:
        - ps_sharebuttons

You will get this notice error:
Notice: Undefined index: product
https://www.dropbox.com/s/955qmn3onuh820o/Screenshot%202020-09-26%2005.15.57.png?dl=0

I'm developing theme and I need to split product comments from share buttons. Both modules are using the same hook. At the moment, it's not possible, because if I place ps_sharebuttons to displayAfterProductThumbs, user gets this error. Also I can't use widget feature for productcomments module because it doesn't support it. 

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @web-plus,

Thanks for your report.
I manage to reproduce the issue using the PS1768 & 177x branch with `ps_sharebuttons` module v2.1.0 and the `productcomments` module v4.1.0
This exception is displayed only when the `productcomments` module is installed.
![image](https://user-images.githubusercontent.com/16067358/94407551-de74de80-0173-11eb-8296-78ac41af5d60.png)

Steps to reproduce the issue:
1. Install the `productcomments` module
2. Go to BO > Design > Positions page
3. Click on the Transplant button
4. select the ps_sharebuttons module
5. select the displayAfterProductThumbs hook
![image](https://user-images.githubusercontent.com/16067358/94407953-6f4bba00-0174-11eb-9623-4ab33ee59d13.png)
6. Save
7. Go to FO > Product page
8. see error

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by PrestaEdit** [comment]
Hi,

I'm not able to reproduce this, it's still valid ?

**Comment by leemyongpakvn** [comment]
@PrestaEdit & @hibatallahAouadni This issue has gone since [ps_sharebutton release v2.1.1 PR#49](https://github.com/PrestaShop/ps_sharebuttons/pull/49/files#diff-5a7b8a1940b3fcc1e8883c947a4238988ada197b72e1368d88d88d879dc0c6bfL136-L160)
`function renderWidget` stopped getting product from `$params` that caused error on **old line 138** as @web-plus reported,
and got product from `$this->context` on **new line 179** instead.
