### ISSUE TITLE
Customer Edit => Error 500

### ISSUE THREAD

**Issue by ProstageSL** [PrestaShop/PrestaShop#21176]
#### Describe the bug

When I like to open the customer edit page, error 500 is shown in case the customer has already placed an order. If no order has been placed so far, the customer edit page opens correctly.

#### Expected behavior

I expected that the edit page opens also for customers who have placed orders.

#### Steps to Reproduce

Click in the customers list onto a customer.

There are discussions in the forum about this since more than one year(!), but no solution:
https://www.prestashop.com/forums/topic/998570-error-500-edit-customer/?tab=comments#comment-3266400
https://www.prestashop.com/forums/topic/1006028-edit-customer-error-500/

Please note: the issue has nothing to do with imported data. It happens with customer accounts and orders created in prestashop. All I could find out so far is that it has to do something with following line of code:

file: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php  function editAction(), line 203:  (version 1.7.6.7)
            $customerInformation = $this->getQueryBus()->handle(new GetCustomerForViewing((int) $customerId)); 

Will this terrible issue be fixed someday?
#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by matks** [comment]
Hi @ProstageSL until proven otherwise, this error has nothing to do with PrestaShop. The "Edit a Customer" Back-Office page works quite well in standard conditions. You can see by yourself on demo.prestashop.com (which is a regular prestashop instance): go in Back-Office, open customer "John DOE" page (it's a fake customer who has placed orders). You can also install a fresh new 1.7.6.7 shop, you'll see it works quite well out-of-the-box.

I had a look at https://www.prestashop.com/forums/topic/998570-error-500-edit-customer/?tab=comments#comment-3266400 discussions. Multiple people who are talking in the thread mention that they recently upgraded/migrated their shops or have installed a module. So maybe the issue arise from these items, from these settings.

So what I am saying here that: the issue you report seem to happen only in specific circumstances. If you can isolate and identify these circumstances, and we can reproduce the error when following your directions, we could find a solution. But without these circumstances it's like driving in a thick fog: you have no idea where the road is.

I promise the Customer Page in Back Office works quite well 😁 indeed if it was not working it would be a critical and "terrible" issue as you say, but it works. It does not work for you, in your specific situation, with your specific settings (server configuration, installed modules, installed theme...) but it works for most people.

**Comment by khouloudbelguith** [comment]
Hi @ProstageSL,

I did not manage to reproduce the issue with PS1.7.6.8.
I attached a screen record
https://drive.google.com/file/d/1avjoeWI4z73Ht0IKD4xJjlKjTwUMyj1Q/view?usp=sharing
Did you use any specific module to create an order? 

Thanks!

**Comment by ProstageSL** [comment]
Hello,
      
First of all, thanx for your fast reaction. 
As I already wrote, the issue has nothing to do with imported records; it happens with customer accounts and orders created under PS.
Also, I'm using the default theme for the backend (custom theme only for frontend)
Thus, it might have to do something with modules.
I'm using Packlink module for shipping, but I have the issue also if customer only buys a virtual product where no shipping applies.
I'm using PayPal and Creditcard module, but issue is the same whether the client did pay by PayPal or Credit.
I'm using a couple of 3rd party modules, but they should affect only frontend (e.g. Mega Menu) or at least not Orders (e.g. I have installed TinyMCEpro and Product Comments from mypresta.eu).
Further I have installed SuperSpeed by ETS soft, but this one is disabled as it makes the page slower, not faster (!).
      
If I like to check one-by-one which module could cause the issue, can I just disable a module, or do I need to uninstall it?
      
PS: I can edit addresses, but not customers.
      
Thanx
Lukas

**Comment by ProstageSL** [comment]
Hello,

It looks like there is still no solution...? Today I noticed that the error also ocures sometimes when I try to set the Staus to "Payment accepted". I have two orders from the same customer, for the same product, using the same payment method, no carrier (virtual product). One has been set automatically to "Payment accepted" after payment made, the other not. I can set the Status of this second order manually e.g. to "Payment Error", but if I like to set it to "Payment accepted", I end up with error 500.

Sorry, but this Prestashop is a terrible nightmare!! And it does definitely not help if you tell me how good your product works - it's not true.
      
Regards
Lukas

**Comment by hibatallahAouadni** [comment]
Hello @ProstageSL 

I didn't manage to reproduce your issue with PS1.7.6.7, even when **the customer only buys a virtual product where no shipping applies** (like you mentioned above), see the attached screen record below:

https://drive.google.com/file/d/191Jt0DNm2Nn3gR7kmlpU-wLq7SpRpCiA/view

As you can see, I can edit the customer page and see all infos about the client, also, the last order with the virtual product is already with **"Payment accepted"** status, see the screenshot below: 

![image](https://user-images.githubusercontent.com/23308427/100218191-b5bf5a00-2f14-11eb-873a-79047b7a147a.png)

Please check and feedback.

Thanks!

**Comment by ProstageSL** [comment]
Hello
      
Please see this video:
      
https://www.prostage.eu/PS_Error_500.mov
      
as you can see, the only non-prestashop modules I have installed and which affects orders or customers are:
      
      - PayPal
      - Packlink Pro Shipping
      - DHL Live Shipping module (issue did all ready exist before installing this module)
      - Paycomet (Credit Card payment)
      - Easy Mailchimp Integration
      
Even if I disable all these modules, the problem is still there!

=> If someone orders a virtual product, status is not set to "payment accepted" thus the client cannot download his purchase.
It is also not possible to set the status to "payment accepted" manualy (Error 500). Thus I have to send the virtual product to each customer by email and I do set the status to "delivered" in order that I know I did.
      
=> Once a customer did buy something, it is not possible to edit the customer anymore (it is still possible to edit the address, but not the customer)
      
Please check and feedback.
      
Prostage SL

**Comment by hibatallahAouadni** [comment]
Hello @ProstageSL 

I saw your screen record, it's really odd! Well, I couldn't help you anymore cause I couldn't reproduce it.
So, I close the issue cause it seems your problem is with third-party modules.

If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
