### ISSUE TITLE
Product comments grade disappear after clicking add to cart

### ISSUE THREAD

**Issue by web-plus** [PrestaShop/PrestaShop#21171]
Install product comments module latest version 4.1.0. Make sure you see rating in hook displayProductAdditionalInfo.
Click on Add to cart -> Grade in displayProductAdditionalInfo hook will disappear.

Video:
https://www.dropbox.com/s/qjh7g89nexy9fhs/men%20-%20google%20chrome%202020-09-26%2013-26-09.mp4?dl=0

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @web-plus,

I manage to reproduce the issue with PS1.7.6.8 and 1.7.7.x branch using the `productcomments` module v4.1.0.
![image](https://user-images.githubusercontent.com/16067358/94411537-fc910d80-0178-11eb-8bc6-775353e4b6bb.png)
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by khouloudbelguith** [comment]
Ping @PrestaShop/product-team can we add this issue to this [Epic](https://github.com/PrestaShop/PrestaShop/issues/19933)?

THanks!
