### ISSUE TITLE
Standard Refund PrestaShop Back Office: Quantity and Amount refunded doesnot get updated in the UI.

### ISSUE THREAD

**Issue by confusedatma9** [PrestaShop/PrestaShop#21177]
**Describe the bug**
When we trigger **Standard refund** in the Back Office which uses **actionProductCancel** hook, it doesn't reflect the refunded quantity and refunded amount in the UI under the Refunded column.
<img width="1238" alt="ScreenShot" src="https://user-images.githubusercontent.com/71811239/94366434-dbd3a400-00f5-11eb-993d-3d0a05c1246c.png">

**Expected behavior**
Should have updated as "10 ($90.00 refund)" under the Refunded column for the item **Brown bear - Vector graphicsReference number: demo_19**

**Steps to Reproduce**
1. Got to an order in the Back Office.
2. Click **Standard refund** and it will scroll to the section where we can enter the quantity to refund.
3. Select the checkbox for the item that you want to refund.
4. Click Standard **Refund products**.

**Additional Information**
PrestaShop version: 1.7.6.7
PHP version: 7.1.33

**Comment by khouloudbelguith** [comment]
Hi @confusedatma9,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.8.
https://drive.google.com/file/d/1_mB8P2_nFOHAj5Grgh_bg5NHYHe_yawq/view?usp=sharing
But, it is fixed in th next major release 1.7.7.0.
I attached  the record of the fix:
https://drive.google.com/file/d/1izkLqwCswrcRi6p5TF2i4KkJWm9iQHjd/view?usp=sharing

Thanks to check and feedback.

**Comment by confusedatma9** [comment]
@khouloudbelguith,

 Thanks for the clarifying with the right data.
