### ISSUE TITLE
BO - Categories page - Multistore - an error is displayed where trying to create a root category

### ISSUE THREAD

**Issue by b44x** [PrestaShop/PrestaShop#21180]
#### Describe the bug

A new root category cannot be created if the association is empty.

#### Expected behavior

There should be some validation or show some error.

#### Steps to Reproduce
>Edit by Khouloud

Steps to reproduce the issue:
1. Enable the multistore context
2. Create a new shop
3. Go to BO > Catalog > Categories 
4. All shops selected
5. Create a new Root category
6. Unselect All shop association

![94541972-84921880-0248-11eb-94b5-2cfc14c04701](https://user-images.githubusercontent.com/13449658/94545062-53b3e280-024c-11eb-9c3d-80569cdca748.png)

* PrestaShop version: 1.7.7.0
* PHP version: 7.3.19-1~deb10u1

**Comment by khouloudbelguith** [comment]
Hi @b44x,

I did not manage to reproduce the issue with PS1.7.6.8 and 1.7.7.x branch.
I attached a screen record
https://drive.google.com/file/d/1lxvHIWPcFPcoRoRHJTvhjwyJCrMfDnPd/view?usp=sharing
Thanks to check and feedback.

**Comment by b44x** [comment]
@khouloudbelguith - You need to turn on multistore.

https://drive.google.com/file/d/1dk1mhZIagqd_qs8N3SWXkhQr4DNkdStE/view?usp=sharing

**Comment by khouloudbelguith** [comment]
@b44x, thanks for these clarifications.
I manage to reproduce the issue with PS1.7.6.8 & PS1.7.7.x.
![image](https://user-images.githubusercontent.com/16067358/94541972-84921880-0248-11eb-94b5-2cfc14c04701.png)
Steps to reproduce the issue:
1. Enable the multistore context
2. Create a new shop
3. Go to BO > Catalog > Categories 
4. All shops selected
5. Create a new Root category
6. Unselect All shop association

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by florine2623** [comment]
This is fixed in PS 9.0.0

https://github.com/user-attachments/assets/c76e966e-0f8b-45b0-a7b0-4efc31a92508

I will close this issue to avoid clogging the blacklog
