### ISSUE TITLE
CI: Skip Travis CI check in some cases

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#21212]
#### Is your feature request related to a problem?

In some cases it is unnecessary to run the Travis CI checks. For example if you just modify the Contributors file, there is no need to run the Travis CI.

Examples : 

- https://github.com/PrestaShop/PrestaShop/pull/21211
- https://github.com/PrestaShop/PrestaShop/pull/21208
- etc

#### Describe the solution you'd like

Do not perform travis when the PR modifies only the following files :  

- `.gitignore`
- `.md`
- `.png`
- `.jpg`
- `.gif`

#### Alternatives you've considered

Use @prestonBot  to edit the title of PR when it only contains files with the some extentions (`.png`, `.jpg`, `.gif`, `.md`, `.gitignore`)

See [Travis CI how to skip a build](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build)

**Comment by eternoendless** [comment]
Hm... some files like `.md` could be skipped, but the other ones can absolutely have a functional impact:

Eg. modifying a `.twig` file may very well break a functional scenario.

**Comment by eternoendless** [comment]
Also, `.twig` files are checked for syntax.

**Comment by PululuK** [comment]
> Also, `.twig` files are checked for syntax.

I totally agree with you. I updated my PR and ISSUE.

**Comment by PierreRambaud** [comment]
It's the same for images files if the image is malformed, it can break the BO, if the image is used with gd, it can break another thing.
The gitignore file can also introduce problems. If you ignore a file you already have on your computer, how do you know a fresh install will create this file/directory, I already saw this kind of errors in other projects.
Finally, only md files can be ignored :thinking:

**Comment by PululuK** [comment]
>  The gitignore file can also introduce problems. If you ignore a file you already have on your computer, how do you know a fresh install will create this file/directory, I already saw this kind of errors in other projects.

I'm not sure we're talking about the same thing ... 😃
Travis CI will not be able to detect this ... this is a remark that should be made by a maintainer

**Comment by PierreRambaud** [comment]
The CI is executing our tests. In our tests we have the installation process that can be tested with a fresh install everything is working well.
If an image is malformed and the test is executed by a human, something can be missed.
If a directory is missing because of a wrong gitignore, something will be broken too.

Having CI here that takes only a few minutes to be executed is not a problem, in the meanwhile, you have got a poor chance of having your pull request reviewed fast just after creating a pull request.

Regarding how other open source projects are working, we (PrestaShop open source project) has a really fast CI and PR are reviewed fast too :sweat_smile:

**Comment by PululuK** [comment]
@PierreRambaud  If you have to pay for each build, I think you wouldn't have the same option 😅
Do not forget that behind all this there are electrical resources ... so for the good of the planet let's avoid unnecessary waste! 🙂

**Comment by PierreRambaud** [comment]
> @PierreRambaud If you have to pay for each build, I think you wouldn't have the same option 


Even if I had to pay for it, I think the whole Core team can agree with the fact that I'm really annoying to be sure it's fully executed whatever the time it can take :sweat_smile: 

> Do not forget that behind all this there are electrical resources ... so for the good of the planet let's avoid unnecessary waste!

As I said, it's not unnecessary because it can find errors that a human can miss. Because if there is an error during the installation process and we skip the CI, we will all try to find the problem, checkout and pull the branch, try to install prestashop, communicate through GitHub / slack, many notifications mails will be sent. It will cost more in electricity than using poor docker images during a few minutes.

**Comment by PululuK** [comment]
> Even if I had to pay for it, I think the whole Core team can agree with the fact that I'm really annoying to be sure it's fully executed whatever the time it can take 

Yes I know. Don't worry, I had the opportunity to discuss with you on a little more controversial subjects, and I know very well that you all share the same options.

> As I said, it's not unnecessary because it can find errors that a human can miss. Because if there is an error during the installation process and we skip the CI, we will all try to find the problem, checkout and pull the branch, try to install prestashop, communicate through GitHub / slack, many notifications mails will be sent. It will cost more in electricity than using poor docker images during a few minutes.


If I provide a PR with a single malformed `.png` file and neither the maintainers nor the QA team can detect it, I think the problem is much more serious.

**Comment by PierreRambaud** [comment]
> If I provide a PR with a single malformed `.png` file and neither the maintainers nor the QA team can detect it, I think the problem is much more serious.

If your PR change a lot of images, it's the same thing :wink:

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

Friendly reminder :wink: what's the status of this feature?
