### ISSUE TITLE
You cannot specify different payment module options on carriers with the same name

### ISSUE THREAD

**Issue by Xaconi** [PrestaShop/PrestaShop#21259]
#### Describe the bug

When you have two (or more) carriers with the same name on your store, you cannot assign them different payment modules options on the Payment Preferences page.

#### Expected behavior

I expected to assign different payment module options on the Payment Preferences page.

#### Steps to Reproduce

1. Fresh install
2. Go to BackOffice
3. Create two carriers, with the same name
4. Go to Payment > Preferences
5. You'll see the error. You'll se only one carrier instead of the two you created before.

**Screenshots**

Two carriers:

![image](https://user-images.githubusercontent.com/1944438/94846788-012c1f00-0422-11eb-912f-84a7fe12cac8.png)

Only one to manage payment modules preferences:

![image](https://user-images.githubusercontent.com/1944438/94846879-2456ce80-0422-11eb-97dc-11f28da21ab4.png)

**Comment by Xaconi** [comment]
I have workaround-code but I need approval from the Prestashop Core team. The result would be like the next pic:

![image](https://user-images.githubusercontent.com/1944438/94847274-aa731500-0422-11eb-9150-70d685424ae8.png)

I must pass the ID (or something specific from the carrier) to make the array on CarrierByReferenceChoiceProvider.php:75 a valid one. If I pass only the name, the array is incorrect.

**Comment by SimonGrn** [comment]
Hello,

please specify the PrestaShop version you're referring to.

**Comment by Xaconi** [comment]
> Hello,
> 
> please specify the PrestaShop version you're referring to.

Hi!

The version is 1.7.6.7 but I think it's happening in 1.7.x.

**Comment by SimonGrn** [comment]
Hello,
please think about using the template, this helps us avoiding asking additional questions.

I reproduce with 1.7.6.7 :
![image](https://user-images.githubusercontent.com/49909275/94894714-39ffde80-048a-11eb-8b05-947ea2bab476.png)

I however don't reproduce with PrestaShop 1.7.7.0 RC1 (even with a carrier with the same delivery time, check the last 2 rows):
![image](https://user-images.githubusercontent.com/49909275/94895223-4afd1f80-048b-11eb-9ebf-af7385610679.png)

This issue has been fixed in the next version of PrestaShop, so I close it.
You'll be able to upgrade when PrestaShop 1.7.7.0 drops, in a few weeks from now if everything goes as planned ;)

Thank you.
