### ISSUE TITLE
Product combination duplicates number of '\' in Reference upon saving

### ISSUE THREAD

**Issue by Mysklep** [PrestaShop/PrestaShop#21271]
#### Describe the bug

While modifying product combination, if 'Reference' field contains at least one '\\' backslash, when saving it gets replaced with double the number of backslashes. So 1 -> 2,  2 -> 4 and so on. This might be a problem for people that use management software (like SymSync) which might require backslashes for combinations.

#### Example

Index 'demo_14\\m' upon saving changes gets replaced with 'demo_14\\\\m'

#### Expected behavior

If a backslash is present in Index field, upon saving changes, contents of Reference field should remain unchanged.

#### Steps to Reproduce

1. Go to BO Catalog -> Products
2. Click 'edit a product' on with combinations
3. Go to Combinations tab
4. Choose one combination
5. In 'Index' field input a string with '\\'
6. Save changes
7. Reload page
8. Revisit this combination
9. There will be x2 the amount of '\\'

Works for vanilla 1.7.6.5 and 1.7.6.8

**Screenshots**

https://imgur.com/a/Jix74by

#### Additional information

* Server information Linux x86_64
* Server software version: nginx/1.18.0
* PHP version: 7.2.33
* Memory limit: 512M
* Max execution time: 200
* Upload Max File size: 20M
* PrestaShop version: 1.7.6.5 
* Current theme in use: classic

**Comment by florine2623** [comment]
Hi @Mysklep ,
I have managed to reproduce the issue in PS 1.7.6.8 ans PS 1.7.7.0.
![Capture d’écran 2020-10-02 à 14 17 04](https://user-images.githubusercontent.com/16019289/94922155-fae98180-04b9-11eb-8f2a-d397d8cda538.png)
![Capture d’écran 2020-10-02 à 14 16 19](https://user-images.githubusercontent.com/16019289/94922188-0b99f780-04ba-11eb-8b4e-344dc006add5.png)


I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by matks** [comment]
@lartist starts it

**Comment by lartist** [comment]
This bug is fixed in the product page v2.

**Comment by rkryvasheyeu** [comment]
> This bug is fixed in the product page v2.

@lartist, could you please point where it has been fixed in the code? If you still remember ofc 😅
I can't upgrade the system to higher version, so looking for the way to fix it for the current (1.7.6.9).
And I couldn't find any related commit or something that refers to this issue so far.
