### ISSUE TITLE
Email : Lots of translations don't work

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#21291]
#### Describe the bug

Lots of translations don't work, the Translation file ( EmailsBody.fr-FR.xlf ) don't match with twig file. 
 
#### Steps to Reproduce

1. Install a shop with French language 
2. Make an order
3. Check the mails

For exemple If i change in **EmailsBody.fr-FR.xlf**

`<source><![CDATA[Review this credit slip and download your invoice on our shop, go to the <a href="{history_url}" target="_blank">Credit slips</a> section of your customer account.]]></source>`

By 

`<source><![CDATA[Review this credit slip and download your invoice on our shop, go to the <a href="{history_url}" target="_blank">%credit_slips_label%</a> section of your customer account.]]></source>`

**%credit_slips_label% != Credit slips**

And i generate email template, translation work

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0 2020-10-5
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Thanks for your report.
I manage to reproduce the issue with PS1.7.7.0rc1.
![image](https://user-images.githubusercontent.com/16067358/95058857-66209700-06f8-11eb-9ea4-efdba1096a82.png)
I tried to translate this expression from BO > International > Translation page => NOK
![image](https://user-images.githubusercontent.com/16067358/95058995-95370880-06f8-11eb-9245-64d0521c8512.png)
I tried to translate this expression from BO > Design > Email theme page => NOK
![image](https://user-images.githubusercontent.com/16067358/95059089-b8fa4e80-06f8-11eb-94a5-1e28db3530bb.png)

With PS1.7.6.8 => ok
![image](https://user-images.githubusercontent.com/16067358/95059230-e47d3900-06f8-11eb-8f5e-e4ec29d2b5c8.png)
It is a regression.
I’ll add this to the debug roadmap.
Thanks!

**Comment by atomiix** [comment]
@okom3pom @khouloudbelguith It looks like this bug will be fixed as soon as the translation catalogue is pushed on crowdin.

**Comment by ghost** [comment]
@atomiix 

I asked for an access on crowdin i wait :)

Here it's https://github.com/PrestaShop/TranslationFiles/tree/master/1.7/translations/1.7.7/fr-FR not a reflect of crowdin ?

**Comment by ghost** [comment]
And before pushed it's possible to see : https://github.com/PrestaShop/PrestaShop/pull/21273 ?

**Comment by jolelievre** [comment]
Your PR is a nice improvement, however it won't be integrated in 177 because it doesn't just change the email template and is a new feature. So nothing to worry regarding the 177 catalog update which should be performed tomorrow

**Comment by marionf** [comment]
Verify if it work after the catalog update tomorrow

**Comment by ghost** [comment]
I made a test today it's the same.

**Comment by SimonGrn** [comment]
@okom3pom the catalog wasn't pushed. Don't worry, we're on it :)

**Comment by jolelievre** [comment]
Hi @okom3pom,

I just pushed the new translation towards Crowdin our Translation platform. So the translation archives for
PrestaShop should be updated tomorrow. The workflow updates them once a day I believe around 7AM.

I'll check tomorrow that everything updated correctly.

**Comment by ghost** [comment]
Yes i received an email

**Comment by jolelievre** [comment]
Hi @okom3pom,

I tested a few things so it turns out the catalog for french is not completely up to date yet, the new wordings
still need to be translated in Crowdin and only then will they be integrated into the TranslationFiles repo which
is used to generate the languages archives.

However I tested the Translation of Emails text again in the BackOffice and I think it works now, I can see some
wordings that are not translated yet including the one you are referring to:

`Review this credit slip and download your invoice on our shop, go to the <a href="{history_url}" target="_blank">%credit_slips_label%</a> section of your customer account.`

So it is now accessible because the default catalog has been updated with the missing wording recently
in this PR https://github.com/PrestaShop/PrestaShop/pull/21179 and they are now accessible in the
Translation interface. I can only guess that you tried a version of the 177 branch before this PR was merged.

I believe I made the same test as @khouloudbelguith but it worked fine for me, I edited the translations by
accessing it via `Design > Email theme` And then I selected french in the `Translate emails` before clicking
on the button. This redirects me to the translation manager to edit workspace `EmailsBody`

![Capture d’écran 2020-10-08 à 01 48 35](https://user-images.githubusercontent.com/13801017/95399408-6c855d80-0908-11eb-8ef6-7da838a6543a.png)

Once it's saved I checked the result using the preview system for Email theme:

![Capture d’écran 2020-10-08 à 01 50 48](https://user-images.githubusercontent.com/13801017/95399559-b66e4380-0908-11eb-92a3-71e613e3e642.png)

I just modified the locale manually `/improve/design/mail_theme/preview/fr-FR/modern/credit_slip.html` because
it uses the default language (`en` in my case, but if you selected `fr` as your profile language it will display it
automatically).

And finally, to be sure, I regenerated the emails without selecting a theme (Core option) and forcing Overwrite which
updates the static mail template stored in `mails/fr/credit_slip.html`
If you have a shop theme installed you should regenerate the emails selecting it in the option so that static templates
are generated in the appropriate theme folder (if present) like `theme/your_theme/mails` for example.

Can you please retry with the latest 1.7.7.x branch and confirm it works ok?

**Comment by ghost** [comment]
Hello,

I always use  the last nightly.

It's ok for me now.

**Comment by jolelievre** [comment]
Hi @okom3pom I just tested to modify this wording in the BO and it works fine (the wording itself is not translated yet, but I'm sure the crowdin community is working on it 🙂), so I'm gonna close this issue.

Thanks for your report
