### ISSUE TITLE
Address selectors reversed after edition in FO's checkout process

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#21437]
#### Describe the bug

In **FO > Checkout > Address selection**, if you have more than one address, for example 2 addresses, editing one address will change the order of the address selector.

#### Expected behavior

Address selectors should not be reversed.

#### Steps to Reproduce

1. Make sure you have 2 addresses or more for your customer account.
2. Add a product to your cart, and proceed to checkout
3. At the address selection step, edit the first address, push the form, you'll see that the addresses selectors are reversed.

#### Screenshots

Before editing address "Home"
<img width="737" alt="Capture d’écran 2020-10-14 à 11 16 47" src="https://user-images.githubusercontent.com/1784781/95969886-96121d80-0e0f-11eb-8eda-70d899004fc7.png">
After editing address "Home"
<img width="690" alt="Capture d’écran 2020-10-14 à 11 22 07" src="https://user-images.githubusercontent.com/1784781/95969905-99a5a480-0e0f-11eb-8ff4-ebf53c2d7d1a.png">

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7, 1.7.8

**Comment by matthieu-rolland** [comment]
This bug is due to the way address are edited: it performs a soft delete and adds a new address in the table `ps_address`, then the addresses are fetched in creation descending order.

**Comment by kpodemski** [comment]
Provided description of the issue is not precise enough.

Address will get a new ID only if you previously used it for any order, then you edit previously used address and this address becomes `deleted`.

Instead of sorting by `id` we can sort by `alias` field, it's hard to sort by `id` because if we have 1, 2, 3 and we edit `2` we have now id `4`, no chance to put it in the middle, to do this we would need to make sorting using some `id_address_reference` field like shipping methods, is it worth it?

@sarahdib @matthieu-rolland
