### ISSUE TITLE
Forum  validation email

### ISSUE THREAD

**Issue by logobg** [PrestaShop/PrestaShop#21440]
after registration on the forum website, no validation email is send to me since 1 day (2 different emails)

**Comment by sarahdib** [comment]
Hello, 

Please be aware that this bug tracker should be used to report issues only. 
If you need help, you can ask on the :
- Forum (https://www.prestashop.com/forums/)
- Stack Overflow (https://stackoverflow.com/questions/tagged/prestashop)

You can also join slack in order to discuss with developer : https://github.com/PrestaShop/open-source/blob/master/slack/readme.md

Thanks for your understanding!

**Comment by matks** [comment]
@logobg You can send a mail to forum@prestashop.com for help 😉  this is the account in charge of the forum

I also reported your issue to the team
