### ISSUE TITLE
BO - Order page - Ajax issue - The gift Product is not removed when removing a product ordered

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21500]
#### Describe the bug

Related to this [PR](https://github.com/PrestaShop/PrestaShop/pull/21447)
In the FO, when we add product A to the cart then checkout, the Order must contain Product A and Product B
In the BO > Order detail page => when we remove the Product A from the order, the cart rule is removed and Product B is not removed, we need to reload the page

#### Expected behavior

The ProductB should be removed

**SPECS**:

When a product is successfully added to the order, a notification of success is displayed: "The item was successfully added." in Admin.Notifications.Success.
Then the product list is reloaded behind the loading spinner to check if any new products could be added through automatics carts rules. The user is redirected to the first page of the product list.

When a product is removed from the order, a notification is displayed: "The item was successfully removed." in Admin.Notifications.Error.
Then the product list is refreshed behind the loading spinner to check if any gift product has to be removed as well. The user is redirected to the page where the user removed the product. If the removed product was on the last page, the user is redirected to the second-last page.

FYI: specs are updated

#### Steps to Reproduce

1. Go to BO > Catalog > Discounts page
2. Create a cart rule "free gift "demo_6 60*90"
3. Go to FO > Add any other product to cart
4. Apply the discount
5. Continue checkout
6. in the BO > Order detail page > remove the product Ordered
7. See the error "The gift Product is not removed"
8. if you reload the page => OK

**Screenshots**

https://drive.google.com/file/d/1N06UU3WrfwgVwgeiTDnB26R_3PEOtc3v/view?usp=sharing

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

**Comment by MatShir** [comment]
Currently, the product list displays the product by the order in which the products are added to the cart. So the first page of the product list into the order page is the first one to be added and the last page on the product list displays the latest products added. 

A product added through the BO's order page was displayed on the page where the product was added and then displayed at the end after a refresh.

Now, with the new refresh system of the product list, the user won't know if the product is successfully added since the product will be added directly on the last page. 
So, to bring more awareness to the user, when a product is added, the page will display a success alert. The product list will now display the product by the order anti chronological, the latest product added to the cart are the first one to be displayed.

**Comment by MatShir** [comment]
@Julievrz I'll let you confirm which is the most appropriate wording.
Waiting for @TristanLDD designs

**Comment by Julievrz** [comment]
"The item was successfully added." in Admin.Notifications.Success
"The item was successfully removed." in Admin.Notifications.Error

**Comment by sowbiba** [comment]
Here is a record of what is done yet
https://drive.google.com/file/d/1KmyGktgV26l2PKqqJgNREXHp6857k4wp/view
with the loading spinner, the list of products ordered : the last product added is on top. The pagination is handled well

Waiting for @TristanLDD review.

And my question is : Do we still need an alert (The item was successfully added or removed)?

**Comment by Progi1984** [comment]
Fixes #21692
