### ISSUE TITLE
Search by & show EAN  and other reference fields in Catalog / Stock Window

### ISSUE THREAD

**Issue by equipposbarcelona** [PrestaShop/PrestaShop#21503]
#### Is your feature request related to a problem?
In many cases, EAN13 is representing a unique combination (color, size...) Searching by EAN we can get the exact combination we're looking for. Additionally, we can export this window to perform inventories based on barcodes.

![ean13](https://user-images.githubusercontent.com/73116704/96454563-533fb380-121c-11eb-8ba3-bfbd5540bf0a.png)

It would be useful to search by EAN and show EAN column in Stock Window

This will also help to export a list of all products and its combinations, including products that has no combinations, all in a single sheet with corresponding EAN codes. Filtering by brand would be useful also. It's something really needed for stores working with thousand of combinations, manufacturers & providers.

**US**
As a merchant, I would like to search my stock depending of any references 

**Specs**
The search takes into account Reference, MPN, UPC barcode, EAN-13 or JAN barcode and ISBN 

**Acceptance test**
Edit mug product add  EAN-13 
When I search  EAN-13, only the mug is displayed

**Comment by khouloudbelguith** [comment]
Hi @equipposbarcelona,

Thanks for your report.
Ping @PrestaShop/product-team what do you think?

Thanks!

**Comment by MatShir** [comment]
Hi @equipposbarcelona, 
Great idea to add the search for EAN13 on the stock page! 
But to display all the information plus EAN13, it can be a lot for the table. We might need advice from our Designers. 
What do you think @TristanLDD @prestascott? 
Maybe if merchants is searching/sorting by EAN13, they might not need to see the reference as well.

**Comment by ajpresta** [comment]
Hello,  


does someone have a solution for it? ean search?

**Comment by prestascott** [comment]
Hi everyone, 

Thanks @equipposbarcelona for your request!

I agree with @MatShir that adding an ean13 column will be too much for the table since it has 11 columns already. It will be difficult to read through it.
According to the previous interviews, some of our merchants use the reference to find the right product they are looking for, so this column cannot be replaced by the ean13 by default and must be optional. 

It will be really nice if our table could support custom display, like choosing which columns to add/remove/replace depending on the merchants' usage. I will add this issue to the related epic so we can work on this and think of the best solution.

**Comment by prestascott** [comment]
Hi everyone, 

Thanks @equipposbarcelona for your request!

According to the previous interviews, some of our merchants use the reference to find the right product they are looking for, so this column cannot be replaced by the ean13 by default and must be at least optional. So imo, this isn't the best solution.

I agree with @MatShir that adding an EAN13 column can be a lot for this 'Stock table' since it has 10 columns already.
Some of the tables in the BO have 13 columns like 'Manage your Customers' in Customers > Customers and I understand that the more a table has column the more it will be difficult to read through it. 

But in my opinion, there is still space for this EAN13 column in this table and it can be optimized by reducing the size of some columns and some components. Adding this column can work on this 'Stocks table' but can be complicated for others such as 'Products table' in Catalog > Products because it's already full and columns' sizes can hardly be reduced.

Wdyt?

**Comment by equipposbarcelona** [comment]
Custom display would be the best option

**Comment by tswfi** [comment]
ean should also be in the exported csv file

**Comment by equipposbarcelona** [comment]
I think that the point is to improve ean management since thousand of merchants work with it and it is a must to perform inventories. Also I think that it must be configurable to be unique or not. Many merchants are working with the reference since the do not have other option.

The column in stock can be easily added and best option I think would be optional display. Export in csv can be also easily done and you can manage inventories based in ean in a Google Sheet.
![image](https://user-images.githubusercontent.com/73116704/145569368-af432e6d-9394-4bb3-ac72-9c523e50778d.png)

**Comment by pollat** [comment]
So, has EAN research on inventory management been implemented?
