### ISSUE TITLE
Set shop URL form not working

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#21560]
#### Describe the bug

The form allowing to change the domains & Base URI of the shop doesn't save new values without any error message when certain characters are present in Base URI

#### Expected behavior

It should save the new values or display an error message.

#### Steps to Reproduce

1. Go to Configure > Shop Parameters > Traffic & SEO
2. In *Set shop URL*, change the *Base URI* for `/prestashop+dev/` and click *Save*
3. See that the new value is not saved and no error message is displayed

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @atomiix ,

I managed to reproduce your issue, using PrestaShop develop, PHP 7.2 and 7.3.
Here's the screen record :
https://drive.google.com/file/d/1JdDvrvji1fteH6C7dcGQEbZSoLIkGJp4/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
