### ISSUE TITLE
Quantity Product Problem 

### ISSUE THREAD

**Issue by Stephlql** [PrestaShop/PrestaShop#21561]
#### When I add a product, several messages appear. As soon as I remove the product, everything goes back to normal and I have no more bugs. I don't understand why and I'm not sure where to look to fix the problem. Can you help me?

**Screenshots**

<img width="850" alt="Capture d’écran 2020-10-21 à 21 20 52" src="https://user-images.githubusercontent.com/73280831/96850174-cdf41300-1456-11eb-9226-2c018a8b2ddb.png">
<img width="783" alt="Capture d’écran 2020-10-21 à 20 27 38" src="https://user-images.githubusercontent.com/73280831/96850189-d2b8c700-1456-11eb-9eb1-1a7b09144401.png">

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: N/A

**Comment by florine2623** [comment]
Hi @Stephlql ,

I can't reproduce your issue in PS 1.7.6.7.
If this happens after you have done a migration, I suggest you to check to error log. Or to restore a back-up of your store.

It seems like your issue is a configuration or server issue, not a core issue.
To get more help you can contact the [support team](https://addons.prestashop.com/en/388-support) or a [partner agency](https://www.prestashop.com/en/experts).
Thanks!
