### ISSUE TITLE
error when displaying accents and rare characters

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#21577]
#### Describe the bug

when a word has an accent or there is a strange symbol (/, -, º, etc ...) the word becomes a kind of code.
attached image

#### Expected behavior

accents and words must display well

**Screenshots**

https://prnt.sc/v4vs1f

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.34

**Comment by florine2623** [comment]
Hi @alfonsolr09 ,
I can't reproduce your issue in PS 1.7.6.4.
![Capture d’écran 2020-10-23 à 09 18 45](https://user-images.githubusercontent.com/16019289/96968159-dc066a00-1510-11eb-96fe-83f3d5fb84d9.png)
It seems like your issue is an encoding issue, you can change it in your database.
If you need more help, you can contact the [support-team](https://addons.prestashop.com/en/388-support) or an [agency partner](https://www.prestashop.com/en/experts).
Thanks!

**Comment by SimonGrn** [comment]
@florine2623 
It's only visible in Spanish when you have accentued characters (in your capture there is not).
It's however a duplicate of #21298 !
We are aware of this issue, it will be fixed when our team prioritizes it.

**Comment by SimonGrn** [comment]
Duplicate of #21298

**Comment by SimonGrn** [comment]
@florine2623 
It's only visible in Spanish when you have accentued characters (in your capture there is not).
It's however a duplicate of #21298 and was fixed by PrestaShopCorp/ps_mbo/pull/101

You'll be able to download the new version of mbo when a new release will be issued.

Thank you

**Comment by alfonsolr09** [comment]
What is mbo? 
I have the same problem with the order messages....

**Comment by alfonsolr09** [comment]
@SimonGrn

**Comment by SimonGrn** [comment]
MBO is the module showing you a list of module from Addons. All is visible in the links above. You can't do anything right now regarding this issue, you just need to wait until a new version is available and you update the module in your backoffice.

You however shouldn't have the problem with Orders messages. Please provide mode information.

**Comment by alfonsolr09** [comment]
@SimonGrn https://github.com/PrestaShop/PrestaShop/issues/23369
