### ISSUE TITLE
Not able to purchase PrestaShop Kickstart Template via the Azure Marketplace 

### ISSUE THREAD

**Issue by Olosinsk-commits** [PrestaShop/PrestaShop#21597]
#### Describe the bug
When I try to buy the image via the Azure Marketplace, validation run forever or deployment fails with the error message saying extension timed out. 

"status": "Failed",
"error": {
"code": "ResourceDeploymentFailure",
"message": "The resource operation completed with terminal provisioning state 'Failed'.",
"details": \[
{
"code": "VMExtensionHandlerNonTransientError",
"message": "The handler for VM extension type 'Microsoft.OSTCExtensions.CustomScriptForLinux' has reported terminal failure for VM extension 'installAnsible' with error message: '\(000003\)Invalid status/status: failed'.\r\n \r\n'Unknown failure occurred for the extension. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot'"
}
\]

![image](https://user-images.githubusercontent.com/11326592/97066222-878ed900-1568-11eb-8ff7-37ef3e937c8b.png)

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @ssinskolga,

your problem is not related to PrestaShop, you will not be able to get help here. You must contact the Azure team directly as they are responsible for their product.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

Is this the product you were trying to use ? https://azuremarketplace.microsoft.com/en/marketplace/apps/prestashop.prestashop-performance-starter?tab=Overview

Their "Support" link is misleading, they are responsible for this implementation, we have litteraly no control on how this was designed and developed.

Thank you!

**Comment by SimonGrn** [comment]
Hello,

this package was managed by an old team at PrestaShop. Since we cannot update or maintain them, we are currently disabling them on Azure.
Do not use them, we may add some updated packages in the future.

Thank you for your understanding.
