### ISSUE TITLE
https not working in front shop

### ISSUE THREAD

**Issue by harisrnd** [PrestaShop/PrestaShop#21662]
version 1.7.7 beta
php 7.3.23
apache 2.4

The installation was working fine without ssl. After I enabled it, the front shop is not working while the backofice works.

The SSL domain and the shop domain are set to www.mydomain where mydomain ofcourse is the name of the real domain.
I tried recreating .htaccess, i tried switching to classic theme, nothing works.
I get 404 - not found

UPDATE:
After disabling "Friendly Urls" SSL works!
So, it seems that there is a bug here? Note that without SSL friendly urls work.

**Comment by florine2623** [comment]
Hi @harisrnd ,
I can't reproduce your issue.
After installing PS 1.7.7.0 beta 2, enabling SSL, with or without friendly URL, I have both front and back available.
It must be a server config issue.
Thanks !

**Comment by harisrnd** [comment]
Well, I 'd appreciate some guidance. I spent many hours on this issue and I cannot find sth wrong with my configuration on a brand new VPS (debian 10) with a brand new certificate(letsencrypt) and .htaccess with no manual interference.
Where should I look? The site is ready for production and it's a pity if we can't use friendly urls.
And if you are right and it is a server configuration issue, this means that friendly urls need special handling and maybe it's better to reopen the issue. Other people might also et help here if we manage to track it.
I can give you any configuration you need in order to advise.

**Comment by florine2623** [comment]
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

If you need more info on the configuration that you need, please check this link : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Comment by harisrnd** [comment]
Bugs exist because they only "appear" under certain circumstances - conditions. Just because you couldn't reproduce it on your installation it doesn't mean it's not a bug.
And no, I don't have any misconfiguration if you're implying it. Everything is "by the book".
And you never asked me one question about my configuration.
I 'm sorry, I know that your support plans are valuable for you but this is not a way to sell one.

**Comment by SimonGrn** [comment]
Hello @harisrnd 
we are not able to reproduce with all the infos you gave us, when we do the things "by the books" like you said, so this means you may have something specific in your configuration. Since we cannot give support for specific configurations and are only able to register bugs in the core, we cannot help you any further. You will need specific help for your specific problem.

Also @florine2623 gave you the links to the forums and the public Slack server which are totally free.

Thank you for your understanding.

**Comment by harisrnd** [comment]
Well, actually I cannot understand what's happening here. I am a beta tester, you people need us and we need you.
We lost a considerable amount of time writing these comments but you didn't ask me a single extra question about my configuration.It seems that you are sure that this is not a bug. Specific configurations(which I do not believe I have) show BUGS, right?
Anyway. Have a nice day.

**Comment by matks** [comment]
Hi, please allow me to jump in the conversation. :)

> Well, actually I cannot understand what's happening here. I am a beta tester, you people need us and we need you.

That is a very true statement, so
- thank you for testing the beta ! your feedback is very valuable to us
- as you mentioned we both need each other : you need us to maintain and deliver this OSS project that you can use for free while we need you to report bugs and contribute

> We lost a considerable amount of time writing these comments but you didn't ask me a single extra question about my configuration.It seems that you are sure that this is not a bug. Specific configurations(which I do not believe I have) show BUGS, right?

When you reported a bug, @florine2623 set up a standard environment for PrestaShop and attempted to reproduce the issue. She saw the issue could not be observed on a regular environment that we know PrestaShop is built for. This is good news! 😄 it means the software works as expected for the configuration we usually see and use.

However if you observe a bug that we do not observe, it can mean 4 things:

1. Maybe there is a bug in the software that is only observable in your configuration/setup/environment.
2. Maybe your configuration/setup/environment is not compatible with PrestaShop, either because it cannot work (like a missing php extension, some server settings that prevent PS from running correctly or even incompatible software*) or because it is a limitation we know.
3. Maybe the way you installed your shop (for example did you install some modules ? maybe a 3rd party theme ?) has introduced the buggy behavior (and the bug is real but it's not in the Core, rather in the 3rd party software that you installed/use)
4. Maybe also you thought you observed an issue but mistook it for a bug because you are not familiar with PrestaShop. It happens sometimes 😊 a simple human mistake creates a buggy behavior and user believes it's a PrestaShop bug.

*For example some configurations of opcache or memcache can create issues for some of PS operations

In order to find out if we are in usecase 1, 2, 3 or 4 a deep exploration is needed. However this exploration can only be done by you because
- only you have access to the shop where the faulty behavior is observable
- unfortunately our resources are limited so as we receive multiple bug reports we focus on the ones we can reproduce (because these ones, we can act on it, and deliver a bugfix)

There is no harm in the situation, just numbers 😢 . We dont have enough time and manpower to perform the long exploration that would tell us whether this is usecase 1, 2, 3 or 4. And this deep exploration has quite a bad ROI because if usecase is not 1 ; but 2, 3 or 4 in the end there is nothing we can do that benefit the software. Only if we are in usecase 1 can we confirm the existence of a bug and then act on it (= deliver a patch).

If you are motivated 😉 you can perform the exploration and, hopefully, you'll be able to find out this is usecase 1 by identifying the specific setup/settings/environment needed to reproduce the bug. On our side however we cannot invest the necessary resources to do it provided the informations that we know. We have a lot of work on our hands already (see number of reported issues 😅 ) so we have to spend our time wisely on bugs that have been confirmed and reproduced rather than chase bugs we are not sure of.

This is not done in order not to help you or to ignore your valuable feedback. It's rather a strategy aiming at being efficient in bug fixing and providing as much as possible valuable bug fixes for community.

Finally,

> I 'm sorry, I know that your support plans are valuable for you but this is not a way to sell one.

We did not try to push our support plans here 😉 (although indeed we need customers because else we wont be able to invest more money and resources in this project 😆 ) this was rather an offer we made if you needed this bug to be explored. As I said, in our current understanding of the situation and of the bug, we cannot invest resources of the Open Source Project for the exploration of this bug. If however you need this exploration to be done, you can pay a Support plan so the money goes in and we can dedicate (paid) resources for it.

The cool thing about you buying a Support plan is that you would get a bugfix AND thanks to the exploration the bugfix would also be submitted for the project so both you and the OSS project benefit from it!

Have a nice day too
