### ISSUE TITLE
/themes/classic/_dev/js/cart.js - ajax arg method: 'POST' instead type: 'POST'

### ISSUE THREAD

**Issue by industria01** [PrestaShop/PrestaShop#21667]
Hi there is a wrong ajax argument on /themes/classic/_dev/js/cart.js lines: 145 and 182.
method: 'POST' instead type: 'POST'

**Comment by florine2623** [comment]
Hi @industria01 ,
Thanks for the report, but in order to proceed with this issue we need more info.
Please follow the bur report template and add any additional info that might be relevant :
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...
I'll close your issue for now, feel free to open a new one when all info is gathered.
Thanks!

**Comment by SimonGrn** [comment]
Hello @industria01

The argument `method` is an alias of `type` as you can see for yourself in the [jQuery documentation](https://api.jquery.com/jquery.ajax/).

![image](https://user-images.githubusercontent.com/49909275/97562803-82a3ac80-19e2-11eb-865b-7025eeb8b220.png)
