### ISSUE TITLE
Classic Theme - Unable to resolve path to module 'prestashop'

### ISSUE THREAD

**Issue by 0dp** [PrestaShop/PrestaShop#21664]
#### Describe the bug

In `./_dev/assests/js/theme.js`
I get a report from eslint that `Unable to resolve path to module 'prestashop'` as used here:
```
...

import prestashop from 'prestashop';
import EventEmitter from 'events';

...

for (const i in EventEmitter.prototype) {
  prestashop[i] = EventEmitter.prototype[i];
}
```

#### Expected behavior

I would expect this import path to be valid

#### Steps to Reproduce

1. Open classic/_dev/assets/js/theme.js
2. Try and resolve path to 'pretashop'

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by NeOMakinG** [comment]
Hello, tested with https://github.com/PrestaShop/PrestaShop/pull/20080

using https://github.com/PrestaShop/eslint-config/blob/master/rules/imports.js

As we disable `import/no-unresolved`, it doesn't create any warning.

What's the reason behind this disabled feature ? `prestashop` is a global window object, resolved by webpack, this means that we need to declare every global variables to eslint too.

I think this is not hard to do, I'll try it, if it breaks on too much global vars I'll keep this rule off.

For the moment if you want to kick this error, add a global `prestashop` var to your own eslint configuration, otherwise you'll need to wait that #20080 is merged.

Hope I helped you.

**Comment by SimonGrn** [comment]
Thank you @NeOMakinG !

Hope it answers your problem @0dp.

I close this issue

**Comment by 0dp** [comment]
Thanks @NeOMakinG 
I have no stress in suppressing this warning. I was just curious.
As an aside, Where would I be able to look at where the prestashop object is created?
