### ISSUE TITLE
Override class SpecificPriceRuleCore Prestashop 1.7 to add new field (PHP)

### ISSUE THREAD

**Issue by ad3r** [PrestaShop/PrestaShop#21727]
Hi, 

I would add field into class SpecificPriceRuleCore i create the file SpecificPriceRule.php in the path /override/classes/ 
how can we add a field in the static $definition

I see the new field on the backoffice but I cannot save the value entered

here is my code:

```

> 
> class SpecificPriceRule extends SpecificPriceRuleCore
> {
> 
>     public $my_custom_field;
> 	
> 	SpecificPriceRuleCore::$definition['my_custom_field'] = array('type' => self::TYPE_FLOAT, 'shop' => true, 'validate' => 'isPrice');
> 
> 
> }

```

Thank you.

**Comment by PululuK** [comment]
Hi @ad3r 

Have you added this new field to your database table?

**Comment by hibatallahAouadni** [comment]
Hello @ad3r ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: You can continue your discussion with @PululuK even the issue is closed.

Thank you

**Comment by ad3r** [comment]
yes i already added the field 
i have this error:
![error_specificprice](https://user-images.githubusercontent.com/3882680/97973904-18ff1600-1dc7-11eb-8033-93bb1504246e.png)
