### ISSUE TITLE
What should I do if the prestashop upgrade failed more than ten times? Ask for help

### ISSUE THREAD

**Issue by golden1688** [PrestaShop/PrestaShop#21762]
Hello there!
Strong technical support:
I am a user of prestashop, I upgraded from prestashop 1.7.6.1 to 1.7.6 stable version (1.7.6.8), I tried to upgrade several times, and it appeared: [Ajax/Server operation backup file error] textStatus: "Error" errorThrown: "" JqXHR: "", what should I do? Please help me, thanks!
PHP version is 7.2
For request I provide
Server log:
Apache: /var/log/apache/apache_error.log
Nginx: /var/log/nginx/nginx_error.log
IIS: %SystemDrive%\inetpub\logs\LogFiles
PHP error log:
Apache: /var/log/apache/php_error.log
Nginx: /var/log/php-fpm/default/error.log
IIS: %SystemDrive%\inetpub\logs\LogFiles
The following is the response from the server provider:
Thank you for your assistance. We apologize for the trouble you encountered during the installation of Prestashop. Since you are on a shared hosting plan, direct access to server logs is not allowed because they contain information about all accounts hosted on the server. To view the Apache error log, you can use "errors" under the "metrics" section of cPanel. This will resolve all errors related to cPanel users in the Apache error log.
The only error logs I can find are these, and there are also website logs. What should I do?
There are a lot of server logs, which are security information. Can I send you a private message?
The picture is a screenshot of the upgrade error:
![WechatIMG166](https://user-images.githubusercontent.com/58970401/98200741-3a980300-1f69-11eb-8869-373d10f4e186.jpeg)
![WechatIMG12](https://user-images.githubusercontent.com/58970401/98200763-44ba0180-1f69-11eb-9c43-6e989c31ba74.jpeg)

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by SimonGrn** [comment]
I'm really sorry @golden1688 I don't understand why you still post the same issue without reading our answers. If you keep posting this _as is_, we will keep closing it.
When we ask you to follow our template it's because it helps us work efficiently by organizing the informations and making sure we don't miss any details.
Moreover, you problem seems to not be linked with the Core itself: we don't have any trouble upgrading from 1.7.6.1 to 1.7.6.8 when we test this.
Upgrade problems are usually caused by two things:
* the upgrade process is very heavy and your server is undersized which cause a timeout: check with your provider
* you have a faulty external module: you will need specific help.

As mentionned before, we only handle issues related to the Core and the natives modules on Github. If you want specific help to try to find the real culprit, you have a few choices:
* the [community forums](https://www.prestashop.com/forums/) 
* the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack)
* the [official PrestaShop support](https://www.prestashop.com/support)

Thank you for your understanding.

**Comment by golden1688** [comment]
Hello there!
Sorry, I saw that the question was closed at the end, and you can submit the question. I did it. Now I understand, sorry!
Now the backup to the screenshot stops, what should I do? thank!

**Comment by SimonGrn** [comment]
* [community forums](https://www.prestashop.com/forums/) 
* [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack)
* [official PrestaShop support](https://www.prestashop.com/support)
