### ISSUE TITLE
ps_googleanalytics doesn't work with the new google analytics G4

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#21790]
Hi
today I've created a new google account to set google analytics for a new website, google analytics G4 now is only the selection. So it is necessary to set a data stream and it is completely different from before. I set the code inside the 
ps_googleanalytics but from analytics I can see no interaction on the site, but I'm browsing it

![1](https://user-images.githubusercontent.com/653230/98355482-78a52d80-2022-11eb-8da9-9475e7a44772.png)

is it possible to update it?
thanks

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2
* Module version: 4.0.0

**Comment by florine2623** [comment]
Hi @maofree ,
Please keep in mind that it can take up to 24 hours for data to show up in your regular reports.
You might need to wait a little bit before new data display in your google analytics account.
Thanks!

**Comment by matks** [comment]
Hi @florine2623 I think there is a little more we need to explore 😉 

@maofree provided additionnal informations such as https://www.simoahava.com/analytics/google-analytics-4-ecommerce-guide-google-tag-manager/

If this blog post is correct, then indeed Google Analytics 4 requires new implementation details 😞  so that would need a rework of our module.

**Comment by Quetzacoalt91** [comment]
We can find more details about the migration in https://support.google.com/analytics/answer/9744165

**Comment by Maofree** [comment]
Hi @florine2623  the real time page, normally shows the current visitors just implemented, the problem is the compatibility between the module and the new system
I have activated data collection right now, I'll see in the next hours

**Comment by Maofree** [comment]
I've found this page
it can be useful
https://developers.google.com/analytics/devguides/collection/ga4/ecommerce

**Comment by Maofree** [comment]
with this guide it is possible to create an Universal Analytics UA- code with the new system

https://support.google.com/analytics/answer/9304153

**Comment by Hlavtox** [comment]
@matks @Quetzacoalt91 It uses the newer gtag implementation, otherwise, nothing much changes.

https://github.com/PrestaShop/ps_googleanalytics/issues/78

**Comment by maofree** [comment]
@Hlavtox are you using ps_googleanalytics with G4?

**Comment by Hlavtox** [comment]
@maofree It is still possible to create a classic Analytics account.
1. Click new account.
2. When "Create service" page appears, click blue "Show extra settings" in the bottom.
3. Switch "Create Universal Analytics service" appears
4. Select "Create only Universal Analytics"

Done!

**Comment by Maofree** [comment]
I've already done it 15 minutes ago, yes that property is like the past version, and with the UA code the module can works

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

As discussed with @matks, it is indeed an improvement. Cause the module works fine for Google Analytics v1, v2 and v3.
Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , wdyt?

**Comment by amanv8060** [comment]
Any updates on when we will be able to use the new code , or else how can we manually add code in the codebase?

**Comment by zorrobiwan** [comment]
FYI, module works well with Universal Analytics property and (basic) data are pushed to GA4 property if the two properties are linked (see https://support.google.com/analytics/answer/9744165?hl=en)
Yes basic events only. eCommerce data are not compatible
See https://support.google.com/analytics/answer/10119380?hl=en : 

> Avoid sharing ecommerce implementations across UA and GA4
> If you use your existing UA ecommerce implementation (i.e. dataLayer events and gtag.js code) with a GA4 property, your GA4 ecommerce reports will not be complete. The gtag.js library automatically translates some, but not all of the UA event and parameters to what is needed for GA4. 

Should be cool that PS module compatible with UA and GA4 with eCommerce support

**Comment by ComonSoft** [comment]
Agree with @zorrobiwan this is very important, specialy when you use Adwords. And many merchants use it ;-) And also to manage user consent!

**Comment by Hlavtox** [comment]
Universal analytics will stop working 01.07.2023 and our marketing agency is pushing a long time for the switch to GA4.
Is there any hope that core dev power will be assigned for this or we should start looking for 3rd party module?

**Comment by rzuf666** [comment]
I join the question, does anyone consider this problem at all? Soon, Google will turn off universal ID support... I design stores for multiple customers and am struggling with this problem, we recently launched several stores on PrestaShop 1.7 and our customers need Google Analytics, but everyone is already using Google Analytics v4 which has a Gtag ID that starts with "G". It is not compatible with the ps_googleanalytics module. Such a problem should be solved as soon as possible, the lack of compatibility lowers the value of PrestaShop in the eyes of customers.

**Comment by matks** [comment]
I will provide an answer here: although GA4 is definitely an important topic, the maintainer team has topics _even more important_ to handle.

If support of GA4 is really important for you, then you can *invest* into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that work with everyone by submitting a Pull Request -- that's what the open source spirit is all about. This will help everybody here and encourage to do the same thing, sharing their work with everybody else, so at the end of the day everyone benefits from the group effort.

This reminds me of what Adam Wathan said on Twitter: [https://twitter.com/adamwathan/status/1381275398646927362](https://twitter.com/adamwathan/status/1381275398646927362)

*"One of the most stressful parts of product development (especially open source) is when people are frustrated you haven’t made the improvement they want and automatically attribute it to complacency or ignoring the community instead of just being completely buried in work to do.*

*If something important takes two years to get worked on, it’s usually because there are two years worth of other fires to put out and work that’s necessary for pure survival. Things taking a long time is more stressful for me than it is for you, I promise. We’re on the same side."*

Unfortunately the maintainer team is buried in work to do so we'd like to handle this topic but can't. We'll be happy to welcome your help, we're on the same side.

At some point GA4 support will become the top item on our list and we'll do it. But I dont know when. If you need this soon, try doing it on your own.

**Comment by lmeyer1** [comment]
When will you start working on this? Is un update to GA4 already planned?

**Comment by lmeyer1** [comment]
ping @matks @MatShir 
When will you start working on this? Is an update to GA4 already planned?

**Comment by lmeyer1** [comment]
It seems that https://addons.prestashop.com/en/analytics-statistics/51261-ga4-google-analytics-and-universal-analytics.html and https://addons.prestashop.com/en/analytics-statistics/23806-google-tag-manager-enhanced-ecommerce-ga4-ua-pro.html are alternatives.

It is up to the PS Team to choose if they want to continue this module. If yes, once PS 8.0.0 is out, it is the time to upgrade this module to GA4.

**Comment by webdev69420** [comment]
@lmeyer1 [this module](https://www.lineagrafica.es/en/modulos-prestashop/prestashop-module-google-analytics-4/) also seems to be a viable alternative and it's the cheapest one I could find out there:

- [https://www.lineagrafica.es/en/modulos-prestashop/prestashop-module-google-analytics-4/](https://www.lineagrafica.es/en/modulos-prestashop/prestashop-module-google-analytics-4/)

I'll soon have the opportunity to install and test it for a client on a production website. We'll see how it goes...

**Comment by ComonSoft** [comment]
It's really a shame that we have to pay for such an important feature! Maybe we should ask Google directly ;-)

**Comment by Oksydan** [comment]
Guys, you can work together and create open source module with GA4 implementation. 
Instead of complaining, use this time and energy for something useful.

**Comment by ComonSoft** [comment]
> Guys, you can work together and create open source module with GA4 implementation.
> Instead of complaining, use this time and energy for something useful.

This is exactly what we are doing Oksydan ;-) We spend time to debug, open issues, propose fixes, propose evolutions... And we have also to pay to be a Prestashop developper or partner :-( Don't you think we do enough?
If many merchants don't find the minmum they expect in a product, and have to pay for every "vital" feature, don't be surprise to loose a lot of them to alternatives that offers theses. We don't complain for complain, we just tell the community echo of merchants ;-)

**Comment by Oksydan** [comment]
@ComonSoft yea but it is still open source project.
Maybe you should propose it to Prestashop Corp not to Prestashop project. 
This kind of module could be part of essential modules. 
IMO Prestashop project should focus on developing prestashop core, not modules with third party marketing integrations.

**Comment by anjohnb** [comment]
> If many merchants don't find the minmum they expect in a product, and have to pay for every "vital" feature, don't be surprise to loose a lot of them to alternatives that offers theses. We don't complain for complain, we just tell the community echo of merchants ;-)

I use prestashop for 4 years now and I am cool with it because it is free. If I need something more, I can write a module for that or if there is a paying module, I think if the price is a good bargain for me. if too high I write it me. if low I buy it saves my time and money.

prestashop has really nice feature and the admin is good too. if you want something done, do it or pay for it

it is business friend

**Comment by matks** [comment]
Release 4.2.0 of module ps_googleanalytics should provide GA4 support

https://github.com/PrestaShop/ps_googleanalytics/pull/131
