### ISSUE TITLE
Not possible to download pdf invoice

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#21799]
## Describe the bug
If you place an order as a guest and then you want to download it from FO order confirmation page the system generates ContextErrorException

#### Expected behavior
The invoice download shouldn't generate an exception.

#### Steps to Reproduce
1. Select any item to the cart  in FO
2. Go to checkout
3. Use guest user and fill data for address and shipment
4. Choose payment method PayPal
5. Confirm and place the order
6. On the confirmation page you can see the link for download pdf invoice
7. Click this link and you'll get the ContextErrorException: Notice: Undefined index: bgcolor_class

![image](https://user-images.githubusercontent.com/33311857/98416889-42969680-2080-11eb-9d78-3eb823bfd4e2.png)

#### Additional information
* PrestaShop version: 1.7.6.8
* PHP version: 7.2.32

**Comment by hibatallahAouadni** [comment]
Hello @juraj1000 

I didn't manage to reproduce your issue with PS1.7.6.8 and PS1.7.7.0-rc.1+build.4 using the native payment modules.
It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on [Addons](https://addons.prestashop.com/en/contact-us?id_product=1748)

We will close this issue.

Thanks!
