### ISSUE TITLE
Adding a new product to an order generates a new cart, that remains abandoned

### ISSUE THREAD

**Issue by rdy4ever** [PrestaShop/PrestaShop#21808]
#### Describe the bug

When the shop admin manually adds a product(s) to  an existing order, a new cart containing that product is created. However, this cart remains abandoned. The issue occurs when the shop has an abandoned cart recovery module installed that will wrongly send the customer a confusing email, saying his order is not completed. To make things even worse, if you add more than one product, a cart is created for each one of them, instead of a single consolidated cart containing all added products, so instead of getting one confusing email, the customer receives multiple emails, for each product.
#### Expected behavior

The generated cart should be validated when the product is added to the order, insead of being treated like an abandoned cart. Furthermore, only one consolidated cart should be generated for all the added products.
#### Steps to Reproduce

1. Go to an order
2. Add a new product
3. Go to carts
4. See non-validated cart

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.3.4

**Comment by hibatallahAouadni** [comment]
Hello @rdy4ever 

I managed to reproduce your issue with PS1.7.6.8 but I didn't manage to reproduce your issue with PS1.7.7.0-rc.1+build.4
See the attached screen record below:

https://drive.google.com/file/d/1OVOKX-PUrH6NoBp0M9YIfPC6NSgd-ew0/view

It seems this bug has been fixed in the new release 1.7.7.0.
So, I close this ticket.

Thanks!
