### ISSUE TITLE
 Error: Syntax error, unrecognized expression expression: input[id^='condition_to_approve'] core.js:39

### ISSUE THREAD

**Issue by kjbtech** [PrestaShop/PrestaShop#21879]
#### Describe the bug
When a user wants to command his cart qnd he gets in the process to login ou register, a javascript error is thrown :

`Error: Syntax error, unrecognized expression expression: input[id^='condition_to_approve'] core.js:39`

We suspect that the behaviour prevent a module to operate correctly (click and collect from Prestatill).

This in Safari 10.1.2 (not earlier version).

#### Expected behavior

The error not to be thrown..

#### Steps to Reproduce

1. Go to https://drive.latetedanslebocal.fr/
2. Click on a product and add it to the cart
3. Command the cart (there is 2 buttons)
4. See the JS error who prevent available hours to display

**Screenshots**

/

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @KevinBTech 

Your issue is only displayed on your shop and not on PrestaShop 1.7.6.8 it means that your issue is not related to PrestaShop Core, it's related to your theme. See the attached screen record below:

https://drive.google.com/file/d/1QWtvLG2e25gA4xM0_S9UsBHYVnEruCYX/view

As it's not a PrestaShop Core issue, you should contact your Theme Author.
So, I close this issue.

Thanks!
