### ISSUE TITLE
Shop Parameters > Search - Alias is duplicated instead of updated

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#21884]
#### Describe the bug

When we edit an alias in the page 'Shop parameters > Search', a new alias is created.

#### Expected behavior

When we edit an alias, the alias should be updated and not duplicated.

#### Steps to Reproduce

1. Go to 'Shop Parameters>Search' page
2. Click on 'Edit' the first alias
3. Edit for example 'blue' by 'red'
4. See error -> a new alias is created instead to update

**Screenshots**
https://www.awesomescreenshot.com/video/3646993?key=b9e0d8d3fca3fa78128e604d8d14573a

Edit Blue by red
![image](https://user-images.githubusercontent.com/24647495/98929003-d3370180-24da-11eb-8f76-733dd09d2827.png)

Result after update
![image](https://user-images.githubusercontent.com/24647495/98928922-af73bb80-24da-11eb-86bf-a718d6aeb94e.png)

#### Additional information

* PrestaShop version: 1.7.6.x & 1.7.7.x & 1.7.8.x
* PHP version: 7.2

---
_Originaly posted in this issue #24374 created by @Robin-Fischer-PS_

> As seen with @MatShir , issue created from a return of this PR #24352

**Comment by BElluu** [comment]
Hi! I will check that today :)

**Comment by kpodemski** [comment]
Hello

I've tested it and this is not a bug but expected behavior, comma separated alias is splitted into single row and this is what we want

alias for `adids, addidas, adids` => `adidas`

needs to create three aliases to work properly with `Search` class

maybe it's a bit confusing but idea was to always get all aliases for selected item, just to split them later

**Comment by kpodemski** [comment]
cc @hibatallahAouadni IMO to close :)

**Comment by hibatallahAouadni** [comment]
Ping @MatShir @marionf wdyt?

**Comment by matks** [comment]
ping again @MatShir or @eshraw

**Comment by matks** [comment]
ping again @MatShir or @eshraw

According to @kpodemski this is the expected behavior

**Comment by eshraw** [comment]
Hello @matks , @kpodemski ,

To me this is indeed a bug. I understand the case described by @kpodemski but in the following case we still encounter an unexpected behaviour : 
- I have an alias "teeest" for the word "test"
- I edit the alias "teeest" and change it to "tst" because "teeest" was a mistake
- In the list we have 2 aliases "teeest" and "tst" and when trying to edit either aliases, both appear "teeest, tst" despite the fact that I wanted only 1 alias "tst"

In that sense, this is an unexpected behaviour with the duplication of an alias and indeed a bug.
