### ISSUE TITLE
BO - Order page - the Canceled status is repeated twice

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#21902]
#### Describe the bug

In the BO > Orders > Order detail page, when we cancel products => the Canceled status is repeated twice.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Create order from the FO with only one product
2. Go to BO > Customer Service > Marchandise return > Enable returns
3. Go to BO > Order page > Last order created
4. In the Documents tab > generate an invoice / you can try the same issue without generating an invoice
5. Click on the cancel products button
6. Select the product
7. Click on cancel products
8. See the error, the Status Canceled is displayed twice => it shouldn't

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/99064004-a1d73800-25a5-11eb-80c4-a9a299bafb52.png)

PS: 1768 => ok 
#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by matthieu-rolland** [comment]
I didn't manage to reproduce the issue, following exactly your steps:

<img width="1007" alt="Capture d’écran 2020-11-20 à 15 31 07" src="https://user-images.githubusercontent.com/1784781/99811517-935cc380-2b45-11eb-9694-6505201d12ed.png">

I tried in multishop as well just in case, no difference...

As seen with @khouloudbelguith it seems like it could have been fixed by this PR:  #21994

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

thank you!

Yes, it is fixed :smile: 
https://drive.google.com/file/d/1ApdSVK-zV-XMXnMhHRpElChkn9yaBOEU/view?usp=sharing

Thanks!
