### ISSUE TITLE
Impossible to change shop name without multi store

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#21917]
#### Describe the bug

It is impossible to change the name of the store.

#### Expected behavior

I made a mistake when installing PrestaShop in the name of my store.

When I realized this, I went directly to change this information in the store's contact information.

Afterwards I added a logo to my store and strangely enough, the name of this logo still contained the error I made during the installation.

While searching I discovered that when I update the information of the name of my store it is absolutely not transmitted to the Shop table and it is there that the name of the store is retrieved for the creation of the logo name.

And of course, apart from going through the database, it's impossible to correct it.

#### Additional information

* PrestaShop version: 1.7.6.8 and i suppose all before
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @jeckyl 

Of course you can change your store name at any time you want, please follow the steps below:

1. BO > **Configure** > **Shop Parameters** > **Contact**
2. Go to **Stores** tab
3. You can edit you shop name in **Contact Details** form (see screenshot below)
4. **Save**

![image](https://user-images.githubusercontent.com/23308427/99240748-37b8d000-27fd-11eb-8caa-d169055592c2.png)

5. **Design** > **Theme & Logo** > **Theme & Logo** tab
6. Upload your new logo
7. **Save**
8. FO > click right > inspect > See the screenshot below

![image](https://user-images.githubusercontent.com/23308427/99242468-85ced300-27ff-11eb-98af-bd47d3b37825.png)

I attached a screen record too:

https://drive.google.com/file/d/1RPGyhs28-As2wkXwXcQ_EIV5xmxeHtCh/view

Please check and feedback.
>  the name of this logo still contained the error I made during the installation.

What do you mean by **the name of this logo**, did you mean by **alt** attribute or something else?

PS: Could you please check if this issue is related to your problem #16499

Thanks!

**Comment by jeckyl** [comment]
I'm talking about the name of the logo file.
When you put a logo, strangely a choice was made to name it with the name of the store, except that this name is not good and if you change it of course nothing is changed on the file name and even worse even if you load a new logo it's always the old name that is used.
I'm going to try to take the time to make a complete video to explain something that of course shouldn't exist because the very idea of naming the logo precisely the name of the store is so constraining to properly manage the thing that we shouldn't do it, wrong good idea.

**Comment by jeckyl** [comment]
I hope you will come to understand the concern here 👍 https://www.loom.com/share/f176166966054a8390653e9b415ccdff

**Comment by hibatallahAouadni** [comment]
Hello @jeckyl 

Thanks for the clarification, I did manage to reproduce the issue with PS1.7.6.8 and PS1.7.7.0-rc.1+build.4.

Steps to reproduce the issue:
1. BO > **Configure** > **Shop Parameters** > **Contact**
2. Go to **Stores** tab
3. Edit you shop name in **Contact Details** form
4. **Save**
5. **Design** > **Theme & Logo** > **Theme & Logo** tab
6. Upload your new logo
7. **Save**
8. Under your **PrestaSHop project** > **img** > refresh you will see the new uploaded logo with the old shop name.

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by jeckyl** [comment]
I can't make the choice to fix this bug as I would like since it requires making strategic choices on the whole PrestaShop code and I don't think it's the responsibility of a community member to make this kind of choice.
I'm surprised that you classify this bug as minor knowing that it calls into question the use of an important PrestaShop variable PS_SHOP_NAME or shop->name because it impacts a very large part of the PrestaShop code, namely all the places where PS_SHOP_NAME is used, that is to say 26 files in the original PrestaShop 1.7.6.8 archive.

**Comment by hibatallahAouadni** [comment]
Please check this document to understand how we handle the [issue severity](https://build.prestashop.com/news/severity-classification/)

**Comment by jeckyl** [comment]
Don't worry, if the name of a site is not important it's not me that will be bothered.

**Comment by ttoine** [comment]
@jeckyl please calm down and respect the code of conduct, use a correct and polite tone.
nobody wants to fix an issue reported with this tone of voice, no matter the severity.

That said, it remembers me this issue: https://github.com/PrestaShop/PrestaShop/issues/14917

**Comment by jeckyl** [comment]
> @jeckyl please calm down and respect the code of conduct, use a correct and polite tone.
> nobody wants to fix an issue reported with this tone of voice, no matter the severity.
> 
> That said, it remembers me this issue: #14917

is this a joke?
I take the time to report a bug that affects all the 1.7 versions of PrestaShop and you just tell me to calm down just because I don't agree with the qualification of a problem.
Honestly if you don't want us to come up with problems, avoid producing them in spades.

**Comment by matks** [comment]
@jeckyl and here we go again...

> Honestly if you don't want us to come up with problems, avoid producing them in spades.

If you cannot write a bug report in a correct and polite manner, yes we dont want your bug reports. This is an open source project, collaboration is the heart of it. Collaboration can only happen if everybody is involved to make it a nice place for others.

Quoting [The Contributor Covenant](https://www.contributor-covenant.org/): "One way to begin addressing this problem is to be overt in our openness, welcoming all people to contribute, and pledging in return to value them as whole human beings and to foster an atmosphere of **kindness, cooperation, and understanding**."

Saying "is this a joke", "it's not me that will be bothered", "avoid producing them in spades" is not kindness, cooperation or understanding.

It's not too much to ask for some kindness and politeness. We are all humans. If tomorrow you tell you something, and I answer "you say X ? is this a joke ?" it's not kindness.

Collaboration cannot happen in an area where we dont consider how others will react to our writings.

**Comment by matks** [comment]
Great news: this issue is fixed 😊 by @jeckyl PR https://github.com/PrestaShop/PrestaShop/pull/21996

Thank you for your contribution 👍 even if some harsh words were used, in the end the project was improved by your efforts

**Comment by PululuK** [comment]
‎
