### ISSUE TITLE
CartRow applyDiscount percent not number format based on PS_PRICE_DISPLAY_PRECISION

### ISSUE THREAD

**Issue by Mch0** [PrestaShop/PrestaShop#21962]
#### Describe the bug

In CartRow classe, in method applyPercentageDiscount the division who calcul the amount of discount not limit the format of result at number of digit defined in Configuration value PS_PRICE_DISPLAY_PRECISION. So when the result of the division return more digits it can be make a false total amount with round price

#### Expected behavior

The result of division for percent discount must be limited at the number of digit who is defined in configuration value PS_PRICE_DISPLAY_PRECISION
#### Steps to Reproduce

1. Make a cart with total amount at 301,9€
2. Apply discount percent to 5%
3. The result should be 286.80 while the result is 286.81
4. This error can introduce an error for payment.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by jolelievre** [comment]
Hi @Mch0 

I think you confuse `PS_PRICE_DISPLAY_PRECISION` with `_PS_PRICE_COMPUTE_PRECISION_` For computing we use a bigger precision to avoid losing values because of rouding (on purpose) The result is generally rounded at the latest moment for display.

Besides in your example I don't think it's an error, `301,9 - 5% = 301,9 - 15,095 = 286,805` So the result is correct the rounding then differ from the rounding mode, you can round up, round down, truncate, ... PrestaShop actually has different available rounding mode, it is configured by the `PS_PRICE_ROUND_MODE` configuration value, by default it is configured as `PS_ROUND_HALF_UP` which is why the result is 286.81

You can change this config in `Shop Parameters > General > Round mode`

Finally, you should be aware that starting from the next version (1.7.7) these two const `PS_PRICE_DISPLAY_PRECISION` and `_PS_PRICE_COMPUTE_PRECISION_` are not used any more, the precision is now related to the Currency, because some currencies have a precision of 0, others 2, ... So using a general precision for all currencies was not correct, thus the precision will be configured for each currency in `International > Localization > Currencies`

I hope all this information will be of use to you, I think we can close this issue if it's ok with you?

**Comment by hibatallahAouadni** [comment]
Hello @Mch0 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
