### ISSUE TITLE
Wrong display in customer order 

### ISSUE THREAD

**Issue by Roomsmaniia** [PrestaShop/PrestaShop#21983]
#### Describe the bug

In the order page of a customer the Messages / status / payment are displayed one below the other

#### Expected behavior

The blocks should be grouped not one below the other

#### Steps to Reproduce

1. Go to BO
2. Click on Orders> orders 
3. Click on a customer order

**Screenshots**

![image](https://user-images.githubusercontent.com/73104293/99548219-af7f2a00-29b8-11eb-8d0a-43f0e0ca7c40.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers easy fix, just remove this line [#L272](https://github.com/PrestaShop/PrestaShop/blob/2b0f98244576c1809dc82a07cb587bb29cfde0f1/src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig#L272) 
It caused by rebase while merging the branch 1.7.7.x  ;-)
