### ISSUE TITLE
[Multistore] Very slow query maybe due to ps_stock_available

### ISSUE THREAD

**Issue by Nesta78** [PrestaShop/PrestaShop#21998]
Hi,
I'm on multistore and when i change of shop, it is very very slow ...
I enabled profiling and I see a huge amount of queries.
In table stress part, i see 14365 stock_available.
Is it normal ? I think maybe this is what causing the issue ?

And in "Double" I see 

14331 | SELECT SUM(quantity) FROM `ps_stock_available` WHERE (id_product = XX) AND (id_product_attribute = XX) AND (id_shop = XX) AND (id_shop_group = XX) LIMIT XX

Thank you guys :)

* PrestaShop version: 1.7.6.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Nesta78 

You need to **downgrade your PHP version to 7.2**, because PS1.7.6.7 is not compatible with PHP 7.3 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/))

Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report** (we need clear steps to reproduce the issue).

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
