### ISSUE TITLE
Envois d'un email de notification au vendeur et au client

### ISSUE THREAD

**Issue by thierry-laval** [PrestaShop/PrestaShop#22039]
#### Describe the solution you'd like

Lorsque un avis est emis sur la boutique ce serait bien qu'un email soit envoyé aux client pour le remercier.

Lorsque un avis est emis sur la boutique ce serait bien que l'administrateur recoive un email pour l'avertir.

Lorsque un client poste un avis avec 5 etoiles, seulement 3 etoiles sont mises sur le front de la boutique.

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. Your issue **MUST BE** written in English.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by thierry-laval** [comment]
Hello, so yes I write in English if you want but points out that we are in France and that prestashop is French ... But either :-)
There is no problem !
A suggestion ... That of being able to receive an email notifying the administrator that a notice has been posted by a customer ...
And that of ensuring that an email is also sent to the customer to thank him for his opinion ...

The rest is good I corrected directly in the module. Thank you ;-)

**Comment by SimonGrn** [comment]
> Hello, so yes I write in English if you want but points out that we are in France 

What makes you think "we are in France" ? Maybe you are physically, but Github is hosted in the USA. Everything in this repository is written in English, the [PrestaShop documentation](https://devdocs.prestashop.com/) is written in English, our own [communication](https://build.prestashop.com/) is written in English, because the product is used by people all around the world.

> and that prestashop is French ... But either :-)

You're mixing up the company and the product. The company is based in Paris but we're all talking in English when interacting with users. We cannot limit our communication to French.

When you open an issue, you're not just asking for help or requesting a feature. You're also bringing value to the product, and everyone should be able to understand what you want to interact with you, not only PrestaShop employees or maintainers. That means using English. That also means respecting our process, for example when you open an issue and you delete all the template: that's not helpful, it forces us to close your issue because we don't have all the details and informations we need.

**Comment by thierry-laval** [comment]
Well, you're in Lyon, it's not in France.
And sorry but ... https://fr.wikipedia.org/wiki/PrestaShop
Whatever :-) let's be nice ...

You are upset.
This was not my point and I just wanted to ask for a missing function ... Useful to everyone :-)

I have no problem but where should I write to point out an important missing function?
Sorry you don't like it but I assure you that this function would be very nice ...
Good development

Et désolé mais de mon coté le site est en Français... Et désolé mais je ne parle pas anglais... Et :-) .. Allez passez une bonne soirée

You can close I won't bother you anymore ... :-) :-) :-)

![Capture d’écran 2020-11-21 à 19 25 01](https://user-images.githubusercontent.com/46448224/99884567-874d3080-2c2f-11eb-9186-0e26fa6da1e6.png)

**Comment by SimonGrn** [comment]
> Well, you're in Lyon, it's not in France.

Again, what does that have to do with anything ? We're on Github, not in my house.

> And sorry but ... https://fr.wikipedia.org/wiki/PrestaShop

Yes, this is the french version of the article on Wikipedia. So what ? [This is the english version](https://en.wikipedia.org/wiki/PrestaShop), what does that have to do with anything ?

> I have no problem but where should I write to point out an important missing function?

You use the correct template and fill it, like you did with #22041.

> Sorry you don't like it but I assure you that this function would be very nice ...

I don't have to "like it" or not, this is not how Open Source works. I highly suggest you educate yourself on the subject, as a student you could really benefit from it.

> Et désolé mais de mon coté le site est en Français... Et désolé mais je ne parle pas anglais... Et :-) .. Allez passez une bonne soirée

Your screenshot is a Google translated version 🤦 there is no official french Github version. You really think Github would translate issue with "numéro" ?

> You can close I won't bother you anymore ... :-) :-) :-)

It's already closed, but I will lock it down.
