### ISSUE TITLE
Saving virtual product attachment is modifying product price if a specific price is set on the product

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#22069]
#### Describe the bug

When using virtual products, retail price is getting modified during attachment save 
if there is a specific price set on the product.

#### Expected behavior

We expect the price remain the same , this is quite major issue as it messed up a lot of product prices in one of 
our customer shop.

#### Steps to Reproduce

1. Create a "virtual product" with Retail Price Tax Inc  € 10.00
2. Add a specific price on the product (10% discount for ALL customers)
3. Go in "Virtual product" and add a file attachment, then click SAVE to confirm the attachment
4. Refresh the page and check the retail price again - It had been set to €9.00 (!)  - SAVING the attachment again will cause the price to get lowered again and again..

#### Additional information

Issue was debugged thanks to the help of M4 module creator.

The wrong line of the code is:

**$productAdapter->getProduct()** in **saveAction** method on **VirtualProductController** 
This method sets the product price using any specific price and later saves this wrong price.

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @gennaris 

I didn't manage to reproduce your issue with PS1.7.6.9, see the attached screen record below:

https://drive.google.com/file/d/1tFkj7ZqIIQ_AbYezKaSqNM10mCeqtkQO/view

Please check and feedback.

Thanks!

**Comment by gennaris** [comment]
@hibatallahAouadni 
Since the save attachment is performed with an AJAX request, you need to refresh the page to see the updated (wrong) price.

**Comment by hibatallahAouadni** [comment]
Hello @gennaris 

I managed to reproduce your issue with PS1.7.6.9, PS1.7.7.0-rc.1 and develop, see the attached screen record below:

https://drive.google.com/file/d/1P2LCeSldQUWF7qzcWETPUcQtDrZhuyJP/view

**PS: to avoid this problem, all you need is to click on Save button as shown in the screen record [1:10]**

Thanks for the report, I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!
