### ISSUE TITLE
Display of the customization product when there is a reduced product in the invoice

### ISSUE THREAD

**Issue by Roomsmaniia** [PrestaShop/PrestaShop#22089]
#### Describe the bug

The display of the customization part is not very readable when another product is in reduction

#### Expected behavior

The customization part should be on one line to be more readable

#### Steps to Reproduce

1. Go to FO
2. Buy a customizable product and a discounted product
3. Go to BO > Make payment accepted for the order
4. Go to FO > Order history and details > Open the pdf 

**Screenshots**
For 177 : 
![image (1)](https://user-images.githubusercontent.com/73104293/100207348-c9b08f00-2f07-11eb-8e43-e8c5d8d01a03.png)

For develop : 
![image](https://user-images.githubusercontent.com/73104293/100207466-e77df400-2f07-11eb-8d23-8201f03de1a2.png)

#### Additional information

* PrestaShop version: develop,177
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @RomainBocheux 

I managed to reproduce your issue with PS1.7.6.9, PS1.7.7.0-rc.1 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/100210406-3e38fd00-2f0b-11eb-87a2-9d54e8ee5a26.png)

I’ll add this to the debug backlog so that it’s fixed.

Thanks!
