### ISSUE TITLE
Log of Contact Form / Contact Form IP Saving

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#22111]
Hello,

#### Is your feature request related to a problem?

I receive Spam by the Contact Form in the Webshop. Sadly, all Captcha Addons do charge money and this feature is not integrated.
If you like to add some Captcha System that would be great.
In the meantime, I just wanted to check the logs of the PS for the IP for the Spamer. PS does not save this level of log, and you can not set it to do so.
The contact form itself does not log the IP of an inquery too, so that was no help either.

#### Describe the solution you'd like

- 1. Integrate some Open Source Captcha System
- 2. Extend the Log Feature for logging contact form events
- 3. Rework the Contact Form to save more Meta Data, maybe user selectable to comply with GDPR laws.

Used PS 1.7.6.9

Thanks

**Comment by SimonGrn** [comment]
Hello,

thanks for your issue. AFAIK we already had this kind of discussion, you can find it [here](https://github.com/PrestaShop/PrestaShop/issues/21650). The conclusion was to **not** implement a specific system inside the Core itself.

I let it open if anyone has something to add to the conversation, maybe ?

Regarding the IP logging and protection, you can also get it at the server level, through some well-known solution like `fail2ban` for example.

**Comment by pitkz** [comment]
Hello,

the other topic is missing solutions like OpenCaptcha https://pypi.org/project/open-captcha/#history


Anyway - the Captcha was just one part of the Q:
The server level does not help within features of PS - to log 100% every Server Action and read it out of this mess of data would be a) not too less work and b) users do not have access to that kind of log lever on their web servers! This definitly is a feature that has to get into the PS Log System - like other User Actions are logged too!

**Comment by hibatallahAouadni** [comment]
Hello @6xthFNGR 

Thanks for your improvement idea but I'm afraid we will decline it. Even if CAPTCHA systems are very efficient to fully protect stores from spamming, it has been decided a few years ago not to offer this feature natively because it could complicate the installing and setting process.

However, if we decided not to integrate it to 300,000 stores in order to keep them performant, many modules exist on our marketplace that could be installed on individual shops when merchants are looking for this kind of solution. I invite you to read more about it on Build: https://build.prestashop.com/news/fighting-against-spamming

> by @LouiseBonnard [comment](https://github.com/PrestaShop/PrestaShop/issues/21650#issuecomment-718028174)

Thanks!

**Comment by pitkz** [comment]
It is quite frustrating to me that you close the whole Topic because you only read what you like: "Captcha"!
The proposal to use a Captcha System was a totally second storyline in here and you proof yourself to not have read my text but the reply by SimonGrn who focus just on the Captcha too.

Reopen the ticket please and focus on whats the Titel and the other 2 missing Features!

**Comment by SimonGrn** [comment]
Hello,

please remember the Code Of Conduct. You're talking to real humans here.

The topic was closed because we already talked about this. If you want to talk about 2 different things, open 2 differents feature requests.

Please remember that we don't **have to** accept everything, and our time is limited.
If a feature is really important for you, you can contribute to this open-source project, because that's how open-source works.

Thank you for your consideration, this thread will not be reopened.

**Comment by matks** [comment]
Hi @SimonGrn  @6xthFNGR 

In order to make the atmosphere a little bit more friendly I helped a bit 😉  I submitted the idea of @6xthFNGR (which is quite relevant) in https://github.com/PrestaShop/PrestaShop/issues/22128 and removed the parts that could be harsh

Let's now discuss calmly on https://github.com/PrestaShop/PrestaShop/issues/22128 😄
