### ISSUE TITLE
 No unit of value for the txt files attached to a product

### ISSUE THREAD

**Issue by Roomsmaniia** [PrestaShop/PrestaShop#22123]
#### Describe the bug

The file attached to a product has no unit of value

#### Expected behavior

The file attached to a product has a unit of value

#### Steps to Reproduce

1. Go to BO > catalog > Products 
2. Click on a product > go to option > Attached files
3. Attach a **txt** file `(*.txt)` to the product
4. Preview product
5. Click on attachments
6. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/73104293/100336655-bd473780-2fd6-11eb-8787-79324f55161c.png)

#### Additional information

* PrestaShop version: 1.7.7, develop
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
hello @RomainBocheux 

I didn't manage to reproduce your issue with PS1.7.7.0-rc.1 and develop, see the attched screen record and screenshot below:

**- 1.7.7.0-rc.1:**

https://drive.google.com/file/d/1BUQLuOxtbJu4sgdEhJsvzeFP1moxU3Wm/view

**- develop:**

![image](https://user-images.githubusercontent.com/23308427/100343571-d1436700-2fdf-11eb-90ad-a38f7035aa40.png)

Please check and feeedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Thanks to @RomainBocheux 

I was able to reproduce the issue with PS1.7.7.0-rc.1 and PS1.7.6.9, see the attached screen record below:

https://drive.google.com/file/d/1Ax2Xmi3A-uPqGfkPcu1ujPqfvj5IIY45/view

I created 5 files (png, jpg, pdf, csv, txt) and I attached them to the product, as you can see in the attached screenshot below, the units of the attached files are all well displayed except the **txt** file:

![image](https://user-images.githubusercontent.com/23308427/100358549-9bf64380-2ff6-11eb-825c-30cd8f2377c1.png)

I’ll add this to the debug backlog so that it’s fixed.

Thanks!
