### ISSUE TITLE
Text for shipping methods overlaps shipping icon in confirmation step

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#22137]
#### Describe the bug
The text for shipping method overlaps shipping icon in confirmation step. 

#### Expected behavior
The text never should overlaps any icon.

#### Steps to Reproduce
1. Create an order in FO
2. During confirmation step change the width of window browser
3. Use width between 580-768 pixels and you'll see overlapped shipping icon

![image](https://user-images.githubusercontent.com/33311857/100393584-80ad2780-303a-11eb-907f-e4c057c1f609.png)

#### Additional information
* PrestaShop version: 1.7.6.9
* PHP version: 7.2.32

**Comment by florine2623** [comment]
Ping @prestascott @PrestaShop/product-team 
I managed to reproduce it, what do you think about it ?

Thanks!

**Comment by MatShir** [comment]
@NeOMakinG, what do you think? Could we find an improvement?

**Comment by NeOMakinG** [comment]
Is it fixed on develop/1.7.7 ? It remember me something

**Comment by prestascott** [comment]
Hello everyone,

Thank you @juraj1000 for your report. :) 

What we can do is to remove the icon from a specific breaking point. Do you think it's possible? @NeOMakinG

**Comment by hibatallahAouadni** [comment]
Hello everyone,

The breakpoint is: @media (min-width: 576px) and (max-width: 767.98px)
See the attached screen record below:
https://drive.google.com/file/d/1UpqcGKgPpIqJ0_uvdSt22eO5dF948LD0/view

Like @NeOMakinG mentioned above, it's already fixed with PS1.7.7.0-rc.1, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/100463158-b0f0d680-30cb-11eb-8586-0dd2b47026ee.png)

So, I close the issue.

Thanks!
