### ISSUE TITLE
Product price in the order is updated when the cart is updated

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#22192]
**Bug**:
When the cart on the order page is updated, it updates the product price if the product has changed between the cart creation and the updates.
New price can come from :
- the new group reduction
- Specific price from the product page
- Cart rule 
- Catalog price rule

**Wanted behavior**: 

Ping @PrestaShop/product-team what do you think?
Render the product price static when an invoice is generated.
 
**Steps**:

1. Go to BO > International > Localization page
2. Import the United States pack
3. Go to the currencies page
4. Edit the $ currency with exchange = 10 (only to visualize the issue)
5. Go shop Parameters > Customer Settings > Groups Tab
6. Edit the customer Group, Add a discount 50% for the Art category
7. Go to FO > Art category > Select $ currency > Add the product `demo_18` to the cart
8. Continue checkout
9. On the Personnel information page "order as a **guest**"
10. At this step: try to navigate to "Guest Order Tracking" using this URL: shop.com/en/guest-tracking
11. Set the Order Reference: of the last order
12. Set the Email: of the last guest added
13. Click Send
14. Scroll down
15. Transform your guest account into a customer account: Set a password and send 
![image](https://user-images.githubusercontent.com/16067358/100853075-a053ae00-3487-11eb-8843-377889beb0bf.png)
16. Go to BO > Orders > Open last Order created
17. Add `demo_19` to the order
18. See error => the product's total is changed

 
I attached a screen record
https://drive.google.com/file/d/1WKztTVBm93SVulwG1SVdbsATbPmceQAr/view?usp=sharing

PS: there is a difference between updating the same product and adding a product.
If we update the quantity of the product => the price is not changed.

I think, after transforming the gust account to customer => prices should be changed when reloading the page / or do not accept to change the price at first.

_Originally posted by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/issues/22161#issuecomment-737109932_

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

I managed to reproduce your issue with PS1.7.7.0-rc.1, the problem here like you mentioned above is that we have two behavior:

**1. if we add anoher product, the discount well be applied on the first product**

![image](https://user-images.githubusercontent.com/23308427/100898625-41128f80-34c1-11eb-89d7-8c78f684fcf4.png)

**2. if we just increment the first product quantity, the discount will be applied too but is not mentioned on product table**

![image](https://user-images.githubusercontent.com/23308427/100898505-1e807680-34c1-11eb-82a8-21bfef5ed7ab.png)

---
When I tested with PS1.7.6.9, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/100900057-bc287580-34c2-11eb-8f51-2677f84875cc.png)

THAT'S THE MOST ODD!!! :sweat_smile: 

1. If I increment the product quantity, the discount won't be applied
2. If add a another product, the discount won't be applied and it will be applied twice on the added product. OMG 

Thanks!
