### ISSUE TITLE
[IMPROVEMENT] Replace info alerts by a more discreet alternative

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#22193]
#### Is your feature request related to a problem?

These info alerts seem to be too important for this page and need to be discreet because users don't want to read them every time they're on this translation page.

![Frame 194](https://user-images.githubusercontent.com/54888056/100890105-2a1b6f80-34b8-11eb-8e9d-b2535b382319.png)

#### Describe the solution you'd like

- Solution 1: Change these info alerts' behaviours so they can be closed. 
- Solution 2: Remove these info alerts and replace them by tooltips placed next to the card title. This solution can be applied when the info alerts is about the full card.   

![Frame 197](https://user-images.githubusercontent.com/54888056/100890118-2ee02380-34b8-11eb-80fe-94cb17342884.png)

ping @NeOMakinG

**Comment by NeOMakinG** [comment]
Same behavior on:
- Monitoring page
- /improve/shipping/preferences
- /improve/international/geolocation/
- /improve/international/translations/
- configure/shop/seo-urls
- configure/advanced/performance
- /configure/advanced/administration

**Comment by NeOMakinG** [comment]
I didn't change some alerts as they contains links

**Comment by LouiseBonnard** [comment]
Hi, thanks @Progi1984 for the reminder! Actually, I'm looking at the International > Translations page and I'm wondering if this content is even relevant. In my opinion, this kind of information should better be displayed in the user documentation.

Since a pull request has already been made, what I suggest is to split the work into two parts:

1. make those alerts more discreet - thanks @prestascott and @NeOMakinG!
2. ask @Julievrz to browse the back office and, if need be, to list all the pages that display irrelevant notifications in a new issue so that it can be handled and harmonized later.
