### ISSUE TITLE
Can't edit shipping or invoice address on order page

### ISSUE THREAD

**Issue by toutantic** [PrestaShop/PrestaShop#22201]
#### Describe the bug
I get the error below when I try to edit an address on the order page.

Oops... looks like an unexpected error occurred.
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Link could not be converted to string").
[Twig\Error\RuntimeError 0]

If debug mode is enable, it works...

#### Expected behavior
The page to edit the address is displayed

#### Steps to Reproduce
1 Go to an order page in the backoffice
2 Click on the ... next to shipping address
3 Click Edit existing address

#### Additional information
* PrestaShop version: 1.7.7.0
* PHP version: php 7.2.24

Can be reproduced on http://demo.prestashop.com/

Sorry I am keeping the old habit of finding a bug right after a release ;)
Anyway that new order page rocks. Keep up the good work

**Comment by SimonGrn** [comment]
Hello @toutantic !
Thank you for this report, it took us a lot of time and effort to pinpoint the real culprit: it's actually the welcome module 😠 ! It only happens when you let the module "enabled", ie you don't click on "Stop the tutorial" on the bottom left after clicking on "Later" on the main page.

@atomiix created a PR to fix this weird behavior.

PS : it reminds me of #21938 not sure if this is related ?

**Comment by matks** [comment]
@SimonGrn https://github.com/PrestaShop/PrestaShop/issues/21938 is related but not directly.

The buggy behavior in welcome module that messes with the Order page and results in this bug report is also observable in ps_legalcompliance according to https://github.com/PrestaShop/PrestaShop/issues/21938 . So similar consequences to this issue could be observed because of ps_legalcompliance, in pages where ps_legalcompliance is hooked.

**Comment by toutantic** [comment]
That was quick !
Thank you
