### ISSUE TITLE
Docker folder should not be inside release zip

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22233]
#### Describe the bug

.docker folder is present in release zip

#### Steps to Reproduce

1. Install a new shop from zip
2. Display hidden files
3. See .docker folder

#### Additional information

* Info : This can give informations to exploit
* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @okom3pom ,
Thanks for the report, I was able to reproduce the issue with PrestaShop version 1.7.7.0. I’ll add this to the debug backlog so that it’s fixed.
![Capture d’écran 2020-12-04 à 10 08 36](https://user-images.githubusercontent.com/16019289/101144659-f0ae4580-3618-11eb-8843-72ceb4a3fe07.png)

And thank you for for the PR.
Please stay tuned !
