### ISSUE TITLE
Prestashop 1.7.6.8 Combinations & Save Error The CSRF token is invalid. Please try to resubmit the form.

### ISSUE THREAD

**Issue by dz49** [PrestaShop/PrestaShop#22254]
Every time i try to save a product with combinations on 1.7 i get this error 
"The CSRF token is invalid. Please try to resubmit the form."

The product never saves. 

My PHP settings are attached I believe my PHP settings are correct. So this is a bug??
<img width="739" alt="PHP" src="https://user-images.githubusercontent.com/17770385/101198979-1e938a00-3619-11eb-8c55-3451b5db192b.png">

**Comment by matks** [comment]
Hi @dz49 how many combinations do you have on this page?

If you have a big number of combinations (like thousand) it can create issues. In this situation you need to increase the max_input_vars from 1000 to a high number (like 15000) in your PHP configuration.

**Comment by dz49** [comment]
Thanks for the reply @matks , i have maybe 40 combinations nothing crazy. I have already increased max_imout_vars in the core to 22000. 
I also noticed that all my addon prestashop stores are not saving. Not sure if i deleted a core file i need :(

**Comment by hibatallahAouadni** [comment]
Hello @dz49 

I manage to reproduce your issue with PS1.7.7.0 with 54 combinations but with 53 combinations the product is well saved, please see the attached screen record below:

https://drive.google.com/file/d/114FuKOeEvePX63NvA-SWN2O5WSJlwhyH/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

PS: Please, next time, respect the provided **template to submit a complete bug report**.

Thanks!

**Comment by marionf** [comment]
@hibatallahAouadni isn't it a duplicate of #9809 ?

**Comment by hibatallahAouadni** [comment]
@marionf yes it's similar

@dz49 It seems that your issue is already in our debug roadmap, so I close this issue.

Please follow the issue mentioned above to get notification when it's fixed.

Thanks for understanding!

**Comment by hibatallahAouadni** [comment]
Duplicate of #9809
