### ISSUE TITLE
Email sending error (response code 220) after upgrade to 1.7.7

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#22262]
After i upgraded to 1.7.7 i started havng customers call me and say that they got no email or response that their account or message was created/sent..

i went into email settings and tried to send an email and i got the following message..
###############################
Error: Please check your configuration

Expected response code 220 but got an empty response
#########################################
The email is set to "Use /usr/sbin/sendmail"
Moreover i tried to setup my own SMTP par according to my server to no success..

#### Additional informations
Prestashop version: 1.7.7.0
PHP version: 7.3.23

**Comment by matks** [comment]
Hi, in PS 1.7.7.0 we had to disable the use of `mail()` for security reasons (details https://github.com/PrestaShop/PrestaShop/pull/20124).

But `/usr/sbin/sendmail` or SMTP should work fine 🤔 .

**Comment by DPStudioGR** [comment]
Still... i have 4 Prestashop installations that now give this error..

**Comment by SimonGrn** [comment]
Hello @Stampa-Stampa 
we need more information. When you create an issue, there is a template with some sections you're supposed to fill with the correct information, not delete everything...
Could you please do that ?

Thank you in advance.

**Comment by DPStudioGR** [comment]
Hi there...  
The section you mention has nothing to fill or delete when you use the default option (/usr/sbin/sendmail)..
Moreover it was working fine before the update. 
Cant understand why Prestashop decided to move with such a change without being sure there is functionality or at least a workaround.
Nevertheless on other server the email test goes on for ever and it ends up with timeout after 4-5 min..
Setting up smtp option ends up with :
################################
Error: Please check your configuration

Failed to authenticate on SMTP server with username "Info@stampa-stampa.com" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535 Incorrect authentication data ". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535 Incorrect authentication data ".
###########################
The same smtp setting work just fine on other email clients.

**Comment by matks** [comment]
> Cant understand why Prestashop decided to move with such a change without being sure there is functionality or at least a workaround.

`mail()` has been disabled because it's not secure https://github.com/swiftmailer/swiftmailer/issues/866#issuecomment-289291228

Replacement is `/usr/sbin/sendmail` and SMTP and they work well. In your usecase something seems wrong but it works for standard prestashop environment.

**Comment by Hlavtox** [comment]
@matks I told you this is going to be a problem... We asked all major hosting providers in Czech republic and all of them refused to enable sendmail. 😞

**Comment by matks** [comment]
> @matks I told you this is going to be a problem... We asked all major hosting providers in Czech republic and all of them refused to enable sendmail. 😞

I'm sorry but if I don't remember that 😅 but github notifications are like a never-ending rain so I might have missed something.

But once `mail()` has been declared unsafe we cannot keep it. Security comes first. There are hundred email providers available 😊 I dont think we have limited options.

**Comment by hibatallahAouadni** [comment]
hello @Stampa-Stampa 

Could you please provide your previous PS version and your PHP version.

Thanks!

**Comment by Hlavtox** [comment]
@matks Wasn't you, sorry 😄 https://github.com/PrestaShop/PrestaShop/issues/19957#issuecomment-652165599

It's quite a situaliton we can never win. `mail()` is considered unsafe, but `proc_open()` is disabled everywhere, because it poses even bigger threats.

**Comment by SimonGrn** [comment]
Reading the [answer ](https://github.com/PrestaShop/PrestaShop/issues/19957#issuecomment-656216190)from @atomiix it seems the other alternative is to use your own SMTP parameters. Is it a viable option for you ?

@Stampa-Stampa I was not talking about the configuration in PrestaShop, I was talking about the issue template, when you create an issue on Github. We have a template with some sections to fill (environment, steps to reproduce, other important details) and you deleted everything.

**Comment by DPStudioGR** [comment]
I finally managed to setup smtp but still more problems apear ...
I have added a new issue...

**Comment by DPStudioGR** [comment]
My Prestashop version is 1.7.7.0 and my php version is 7.3.23

**Comment by hibatallahAouadni** [comment]
Hello @Stampa-Stampa 

> Could you please provide your previous PS version and your PHP version.

I said your previous version :sweat_smile: So what was your shop version before upgrade.

Thanks!

**Comment by kierweb** [comment]
It appears sendmail via swiftmail needs "proc_open" - which most php installations, has disabled via disable_functions, for security reasons!

**Comment by zelduxs** [comment]
Same problem after upgrading to 1.7.6.9 ->1.7.7

**Comment by GSafar30** [comment]
Same problem since update to 1.7.7, "Error sending e-mail (response code 220)". 
 cannot configure the mails in SMTP because hosting on ionos on a shared server. How to do?

**Comment by fire2** [comment]
Same problem here... pretty messed up that this breaks without notice. 
Where is the "send from" email configured now with sendmail?

**Comment by JeffreyDracoon** [comment]
i also have this problem

Error: Please check your configuration Expected response code 220 but got an empty response

close
An error occurred while sending the e-mail to the customer.

**Comment by DPStudioGR** [comment]
I am not sure it will help but i couldn't even setup my own smtp. The browser i was using was firefox and what i realised was that the browser somehow was changing the pass according to an autoregistry without me noticing it, and i got a break when i tried the same with a chrome.

**Comment by Ouro17** [comment]
Same here, tried different browsers amd accounts without any luck.

**Comment by fire2** [comment]
This should have been handled way better during the upgrade process. There should have been an automatic email test and if it doesn't work it should clearly inform the user after the upgrade process that the email sending is not working anymore and it should be reconfigured. There was no notice at all. Without looking deep into the changelog one wouldn't have even noticed the change in the email settings wording until seeing the emails aren't arriving anymore (e.g, "new order" notifications, which is what happened to my client).

**Comment by SimonGrn** [comment]
Hello everyone,

this change was made for security purposes. I understand some of you may feel frustrated, but remember that security is one of our top priorities and as such we removed this feature to keep PrestaShop as secure as possible.
I want to also remind you that we published 3 preversions ([beta 1](https://build.prestashop.com/news/prestashop-1-7-7-0-beta-release/), [beta 2](https://build.prestashop.com/news/prestashop-1-7-7-0-beta2-release/), [RC 1](https://build.prestashop.com/news/prestashop-1-7-7-0-rc-release/)) before releasing the final product. **We ask for people to test these preversions with a copy of their production shops to catch any problem before the final build is released**. We need people to test them. Sadly we didn't receive a lot of feedbacks, feedbacks that could have helped us catching this in advance.

Thank you for your understanding.

**Comment by fire2** [comment]
I totally agree that security comes first, and I therefore fully agree with removing the usage of php mail. What I don't agree with is not implementing something like an automated test during the upgrade to see if the new default option still works, or at least telling the user "hey, your email configuration changed, please make sure it still works". I think it's quite a breaking change. The standard message after upgrade doesn't help end users that upgrade with the auto upgrade module. Breaking changes should be tested and informed better, IMHO. In my client's case, sendmail doesn't work even with it enabled on the hosting and the correct path. Had to configure it as SMTP.

**Comment by SimonGrn** [comment]
>Breaking changes should be tested and informed better, IMHO

Totally. Once again, this is an Open Source project, if you feel something is not done right, you are more than welcome to contribute to improve it, so the fix can be released for free for everyone.

Please remember that we are a small team compared to other big ecommerce projects, and therefore cannot test every possible configuration to make sure we don't miss anything.

And once again, we provided 3 preversions. Did you test them ?

**Comment by Hlavtox** [comment]
@SimonGrn I reported it 7.7.2020 on Slack and 26.7.2020 here (https://github.com/PrestaShop/PrestaShop/issues/19957). We found the cause, so don't say the PS team did not know about it... 😉

I warned you that this will piss people off. I run on a private server, so I don't care, but if I was on public hosting, I would be in big trouble. We specifically emailed all the biggest hosting providers in Czech republic, with a question, if they could allow `proc_open`. Reply from **all of them** - "No, only on VPS".

_EDITED by @matks_ : no need for passive-aggressive statements.

**Comment by kierweb** [comment]
The issue is actually the 3rd party mailer you use, which is swift mailer -  is there any other mailer you could use instead, to stop the proc_open issue?

**Comment by ttoine** [comment]
@Hlavtox 
You also make money with PrestaShop software, like a lot of merchants, agencies and freelancers. PrestaShop Company is the biggest contributor, but it's an open source project, and any one can contribute. 

Developing, promoting and sustaining an open source software project cost a lot, that's why PrestaShop company has a business model.

That said, this discussion is not really respectful and friendly, and usually this does not help to find a solution. As I would prefer not to close it as "too heated", please try to work together.

The reason of the change is security, and that should not be a compromise. There are ideas in the discussion already, like test and display information.  It's time to provide a solution, your pull requests are welcome

**Comment by Hlavtox** [comment]
@ttoine There is no attack in my post, but I think it's not right that Simon practically blames us for not testing it properly...

Regarding the security risk - I reallly don't understand SwiftMailer's move. I have read about the mail() issue and it's dangerous, because you can add extra email headers and other data when calling this function. I think if somebody gets into your Prestashop installation, you have much bigger trouble than that he can use mail().

The solution we have available is sendmail, which needs proc_open. Proc_open, if enabled can run any external command, that is not dangerous? 😄

**Comment by ttoine** [comment]
The problem is your tone. You are agressive and unfriendly, sometimes insulting.  And not a surprise, people don't like to work this way.

If you want to find people enthusiastic to work with you here, start with being friendly and positive. PrestaShop is not a proprietary software, so you can improve it.

**Comment by matks** [comment]
> The issue is actually the 3rd party mailer you use, which is swift mailer - is there any other mailer you could use instead, to stop the proc_open issue?

You will find the details about the security issue in this thread https://github.com/swiftmailer/swiftmailer/issues/866#issuecomment-289291228

Many people in the thread disagree about it being a security issue. Many people agree.

As for us we have chosen to follow Symfony's side: the use of `mail()` was disabled because of security reasons. We don't want to keep something that will has security issues.

Remember that this is an open source software: you have control on the files of your shop (contrarily to SaaS products). If you disagree with us disabling something for security you can enable it again on your shop 😉  .

**Comment by Hlavtox** [comment]
@ttoine Sorry, but I don't feel it that way. I am discussing pure facts, there is nothing unfriendly and insulting about it. I have nothing against anyone and you can see I am trying to help wherever I can. I don't say this is the case, but this is business and you won't be always handled in white gloves.

Somebody says that the issue was known, I say it was.
Somebody says the community should have tested it, I say it's not (purely) community's task.
What's wrong with that?

@matks The problem is that people cannot revert it easily, other than downgrading SwiftMailer... :(

**Comment by ttoine** [comment]
@Hlavtox Actually, if you would have been friendly in your communication, your advice would have been taken in account with a higher impact. As I said already, people appreciate to work with friendly people, but they don't want to work with unfriendly and agressive people. Being borderline with the Code of Conduct is not really respecting it fully.

Being factual is very good. But that's not enough in an open source project. Even Linus Torvalds, himself, had to change his behavior, recognizing in 2018 that he was a problem to foster a nice Linux community. Now, he gives example. That's also a fact.

Coming here means wanting to build something together. If you come just to blame others, at what point, you will not be welcome anymore. So next time you create an issue, a pull request, or even write a comment, please re-read yourself before you push the button, and ask yourself: "will people like what they will read, and will they want to work with me?"

**Comment by Ouro17** [comment]
Any insight on why configuring the SMTP options also doesn't work?

**Comment by matks** [comment]
> Any insight on why configuring the SMTP options also doesn't work?

Some people said their password manager put their password inside the "password" field, erasing the SMTP password.

**Comment by Hlavtox** [comment]
@ttoine I think it's difficult to guess the tone from written communication, in a different language. And what could sound harsh can be only because of the language barrier. I assure you there is no anger in anything I write. 👍

> Coming here means wanting to build something together. If you come just to blame others, at what point, you will not be welcome anymore. So next time you create an issue, a pull request, or even write a comment, please re-read yourself before you push the button, and ask yourself: "will people like what they will read, and will they want to work with me?"

What is the other reason people would come here? If I encounter a bug and I can fix it, I always make PR straight away. If I wouldn't want to help the community, I would fix it for my clients and go on...

And regarding the thing @matks edited out - it was not meant in hate, but maybe we should take the the pink glasses off and feel the reality. Insane amount of work was done on Prestashop, but I think it's still not time to hug each other and say how insanely successful it is. There are maybe PS team + 20 people from the public reporting bugs and testing betas...

**Comment by ttoine** [comment]
Fortunately, there are more contributors that than. Big agencies and big merchants tests with their scenario, even if it is not always with an iso stack (core+module+theme+configuration+data). That's also why 1.7.7 is late: there has been a loooot of issues identified. But this is still not enough.

The pain is that it's difficult to test for the small independent merchants, because it takes time and often, they don't have the skills. And, they are the most important group of users.

**Comment by JeffreyDracoon** [comment]
Hi everyone,

Can anyone help me with the sollution? It still dont work for me :(

**Comment by matks** [comment]
Hi, we tested multiple times the SMTP settings and it seems they are working as expected. SMTP would by my recommandation as it does not depend on your PHP server settings.

**Comment by JeffreyDracoon** [comment]
![Naamloos](https://user-images.githubusercontent.com/75450376/102336146-1597a680-3f91-11eb-972b-5fd35b9872b8.png)

**Comment by JeffreyDracoon** [comment]
![Naamloos](https://user-images.githubusercontent.com/75450376/102336318-4e378000-3f91-11eb-9db1-ed53c2efeea5.png)

**Comment by JeffreyDracoon** [comment]
I get this error

**Comment by DPStudioGR** [comment]
> Any insight on why configuring the SMTP options also doesn't work?

I am not sure it will help but on one of my customer's email smtp setup i also had difficulty setting up and in the end the problem was the port. Despite the fast that my customer's host provider has a card with all the info, the port was not working and in the end he (the customer) was given an alternate one that finally worked..

**Comment by Ouro17** [comment]
> 
> 
> > Any insight on why configuring the SMTP options also doesn't work?
> 
> Some people said their password manager put their password inside the "password" field, erasing the SMTP password.

I don't understand what do you mean. I also tried to override the settings in the parameters.php file as the file containted this:
`    'mailer_host' => '127.0.0.1',
    'mailer_user' => NULL,
    'mailer_password' => NULL,`

But is not working.
As @Stampa-Stampa did,  I contacted my host provider but they still don't know why is not working.

**Comment by web-plus** [comment]
I installed 1.7.7 on two websites so far and I have to agree with @Hlavtox  - I already have issues too. I'm also in Czech Republic and it's true that proc_open is disabled everywhere. On one hosting I could setup SMTP without problems, but I wasn't able to make it work on the second one, I tried all options / different ports and ways of connection according to hosting manual.
Order cannot be finished because after saving the user details, it can't send email. I can debug it as a developer, but common users will not know why it doesn't work...

**Comment by Ouro17** [comment]
Hello, I was able to solve my problem thanks to this thread: https://github.com/PrestaShop/PrestaShop/issues/22298

I went to the database I saw that in ps_configuration, the entry PS_MAIL_PASSWD was invalid.

My password has a `<` on it and it made my password to be cut from that point.

For example, `my_pass<word` became `my_pass` only and that was the whole problem.

I tested with > and it's saved and working.

Is this the expected behavior?? 
If so, maybe we can output some error message related to it.

**Comment by matks** [comment]
@Ouro17 You are right! indeed some "cleaning" happens when you submit the password.

Could you please open another github issue so we can treat this? Or I can open it if you prefer

**Comment by matks** [comment]
@Ouro17 I reported it https://github.com/PrestaShop/PrestaShop/issues/22540 so we can start dealing with it ASAP 😊

**Comment by Lukascisar** [comment]
Hello,
I have a similar problem. I newly founded an eshop with prestashop version 1.7.7.0 and I can't send any emails. According to the information here, it is possible to send using smtp, which unfortunately has my hosting disabled (cesky-hosting.cz).
My question is, what should I do to send emails using sendmail?
Thank you very much in advance for your help.

**Comment by web-plus** [comment]
> Hello,
> I have a similar problem. I newly founded an eshop with prestashop version 1.7.7.0 and I can't send any emails. According to the information here, it is possible to send using smtp, which unfortunately has my hosting disabled (cesky-hosting.cz).
> My question is, what should I do to send emails using sendmail?
> Thank you very much in advance for your help.

Hello, 
I'm afraid that cesky-hosting.cz will also have disabled proc_open library (security reasons) which is required for sendmail. But you should test it to verify it.

**Comment by hibatallahAouadni** [comment]
Hello @Stampa-Stampa and everyone

As you can see in the screen record below, I had a shop 1.7.5.2 upgraded to 1.7.7.0, I configured my email (STMP) and I tested my email configuration by sending email to myself, I recieve my test email:

https://drive.google.com/file/d/1HXFQqTpfm3o-shFbjq4I-xcOCsaccLTT/view

So, please provide extra infos to understand how we can reproduce your issue.

Thanks!

**Comment by matks** [comment]
Hi @web-plus @Lukascisar if I understand correctly how `proc_open` works, it prevents the use of SMTP if you use your hosting provider as a SMTP provider.

If you use another SMTP provider like Sendgrid or Mailgun it should work 🤔  (not 100% sure, I'm not experienced in this area).

**Comment by Hlavtox** [comment]
@web-plus @Lukascisar @Stampa-Stampa @JeffreyDracoon

https://danielhlavacek.cz/files/177mailfix.zip
1. Download it, extract it. 
2. Drop these files into your PS installation.
3. Profit
(optional) Let me know if it works 😄

______
PS: @Lukascisar Ahoj, zprávu na fóru jsem viděl, necháme konverzaci tady. :-D

**Comment by DPStudioGR** [comment]
Hi there...
Maybe upgrading your host plan or changing your host provider is the best
thing to do.
Setting up your own email service (smtp) is the proper way...
Since i setup my own i had no issue and all emails are received and sent
problem free (i had some speed issues prior to that maybe was relevant
maybe not)

>

**Comment by web-plus** [comment]
> Hi @web-plus @Lukascisar if I understand correctly how `proc_open` works, it prevents the use of SMTP if you use your hosting provider as a SMTP provider.
> 
> If you use another SMTP provider like Sendgrid or Mailgun it should work 🤔 (not 100% sure, I'm not experienced in this area).

When I was testing on my hosting, choosing sendmail option didn't work. I got error about proc_open library which is disabled on shared hosting. With SMTP option, it worked (on that hosting, not on another but that's probably configuration issue). This is the error:
https://www.dropbox.com/s/37n3fceacfsgqus/Screenshot%202020-12-04%2000.53.43.png?dl=0
it was visible only in debug mode I think, so it may be problem for common users who install Prestashop on hosting without proc_open (order will not be made successfully).

**Comment by Lukascisar** [comment]
> @ web-plus @Lukascisar @ Stampa-Stampa @JeffreyDracoon
> 
> http://danielhlavacek.cz/files/177mailfix.zip
> 
> 1. Stáhněte si jej, extrahujte.
> 2. Umístěte tyto soubory do instalace PS.
> 3. Zisk 
>    (volitelný) Dejte mi vědět, jestli to fungujeúsměv
> 
> PS: @Lukascisar Ahoj, zpráva na další jsem viděl, necháme konverzaci tady. :-D

Great!!! this solution works I tested and my problem is solved!
I think people who are not proficient in php programming like me will really appreciate it.

PS: @Hlavtox super moc děkuji už jsem propadal panice, že budu muset vše z eshopu přesouvat do jiného. Moc děkuji.

**Comment by carlitossuper1** [comment]
> Hi there... Maybe upgrading your host plan or changing your host provider is the best thing to do. Setting up your own email service (smtp) is the proper way... Since i setup my own i had no issue and all emails are received and sent problem free (i had some speed issues prior to that maybe was relevant maybe not)
> […](#)

I have the same issue and setting correctly the SMTP values DOES NOT work. The test email is not sent and the order email aren't sent either.

Applying the patch above works using sendmail but is not desirable.

**Comment by webeshop** [comment]
@Hlavtox Thanks (děkujeme převelice)

**Comment by Stephane1874** [comment]
Hello, 

I am having the same problem after updating from version 1.7.6.9 to 1.7.7.0. "Error sending e-mail (response code 220)"

@Hlavtox  solution works very well, thank you so much.

**Comment by GSafar30** [comment]
Hello,
I got mine working on a **ionos hosted** doing the following.

**Mail domain name:**     

**SMTP server:         auth.smtp.1and1.fr**

**SMTP Username:      ____@yourdomain.com  "You have to have an email address created through ionos hosting"**

**SMTP password:         "your ionos hosted email password"**

**Encryption:         SSL**

**Port:             465**

If it can help someone....

**Comment by hibatallahAouadni** [comment]
Hello everyone,

As I mentioned above I couldn't manage to reproduce the issue (see my [comment](https://github.com/PrestaShop/PrestaShop/issues/22262#issuecomment-754539103)).
For people who are still stuck with this issue, you have three solutions provided by our beloved contributors:

### 1st solution by @Stampa-Stampa 

> I am not sure it will help but on one of my customer's email smtp setup i also had difficulty setting up and in the end the problem was the port. Despite the fast that my customer's host provider has a card with all the info, the port was not working and in the end he (the customer) was given an alternate one that finally worked..

Check your port, if it's not working => change it :wink: 

### 2nd solution by @Hlavtox 

> http://danielhlavacek.cz/files/177mailfix.zip
> 1. Download it, extract it. 
> 2. Drop these files into your PS installation.
> 3. Profit
> (optional) Let me know if it works 😄

Extract the provided solution and enjoy it :wink: 

### 3rd solution by @GSafar30 

> I got mine working on a **ionos hosted** doing the following.
**Mail domain name:**     
**SMTP server:         auth.smtp.1and1.fr**
**SMTP Username:      ____@yourdomain.com  "You have to have an email address created through ionos hosting"**
**SMTP password:         "your ionos hosted email password"**
**Encryption:         SSL**
**Port:             465**
If it can help someone....

If you encounter this issue with **ionos hosted**, enjoy his solution :wink: 

---
Well, I think I tried my best to summarize the issue,if any contributor could provide more information that helps us reproduce the issue, please help :pray: 

Sorry but I have to close this issue and as I said before, when **an issue is closed it doesn't mean that we won't fix it**, but we just don't have enough information to reproduce it.
if anyone has more informations to reproduce the issue, we will respond ASAP and try to reproduce it :relaxed: 

Thanks for understanding :pray:

**Comment by Ronald72a** [comment]
> Hello @Stampa-Stampa and everyone
> 
> As you can see in the screen record below, I had a shop 1.7.5.2 upgraded to 1.7.7.0, I configured my email (STMP) and I tested my email configuration by sending email to myself, I recieve my test email:
> 
> https://drive.google.com/file/d/1HXFQqTpfm3o-shFbjq4I-xcOCsaccLTT/view
> 
> So, please provide extra infos to understand how we can reproduce your issue.
> 
> Thanks!

Hello Everyone.

I had this problem sins long time and finally I think that I found a solution "very simple" ...
How did I found this ? I read a lot of experience of people who have to create a new email to configure the Email in PS
and I sow the video that you posted @hibatallahAouadni , than I sow the difference, because in your example and what is happening when you create a new email the password space stays "empty", but not when you have the password in the navigators memory like Chrome, in my case, and I use the same email address to login to my back-office but it's not the same as my email account, so even when I change and enter my email password it doesn't works !?
So I erased the password registration from my email adress in Chrome and now the password stays empty when I actualize the page !!!
and now it works, I tested this on 2 websites and it works fine now, so if this can help anyone ;) 

https://www.dropbox.com/s/tx25eq2zhxke436/capture_email_config_ps1.7.8.3.jpg?dl=0

So now just try to find out why with automatic password indicate this doesn't works ???

Sorry for my English, but I live in France ...
Ronald 

PS, so the bug Prestashop is that in the block "password", when you enter a new password is replaced by the password that is memorized  in the browser !

had this in my apache error.log  (about 10 times)
[Fri Mar 04 21:23:52.319674 2022] [authz_core:error] [pid 5146:tid 139859955930880] [client 2a01:e0a:1e5:e640:75fa:25be:9718:95d3:38274] AH01630: client denied by server configuration: /srv/data/web/vhosts/www.xxxxxxxx.fr/htdocs/img/p/1/9/7/5/4/9, referer: https://www.xxxxxx.fr/fr/

**Comment by levimauricio** [comment]
> @web-plus @Lukascisar @Stampa-Stampa @JeffreyDracoon
> 
> https://danielhlavacek.cz/files/177mailfix.zip
> 
>     1. Download it, extract it.
> 
>     2. Drop these files into your PS installation.
> 
>     3. Profit
>        (optional) Let me know if it works 😄
> 
> 
> PS: @Lukascisar Ahoj, zprávu na fóru jsem viděl, necháme konverzaci tady. :-D

Excelente, esta solución resolvió mi problema

**Comment by Varindien** [comment]
Hello, just install a fresh install of Prestashop 1.7.8.7 and emails are not working if we send it to same domain as the shop.
Above solution fixed it, thanks @Hlavtox  !

tested on PS 1.7.8.7 .. did not see any change about it on : changelog_1.7.8.8.txt

**Comment by justbennett** [comment]
I attempted the @Hlavtox fix, but it appeared to break my configuration. Sending a test email now reports
`Error: Please check your configuration`

Sorry if this is very obvious, but does "Drop these files into your PS installation" just mean moving them into the prestashop folder and overwriting the original folders ?

**Comment by pinch-pass** [comment]
@Hlavtox the same problem as @justbennett mentioned, Error: Please check your configuration , Prestashop 1.7.8.6. mail doesn't work. Any ideas except smtp?

**Comment by levimauricio** [comment]
> I attempted the @Hlavtox fix, but it appeared to break my configuration. Sending a test email now reports `Error: Please check your configuration`
> 
> Sorry if this is very obvious, but does "Drop these files into your PS installation" just mean moving them into the prestashop folder and overwriting the original folders ?

Yo hice un respaldo de las carpetas y archivos, luego lo eliminé. Por último extraje el contenido del archivo zip en la ubicación original y probé nuevamente. Con eso me funcionó.

**Comment by Hlavtox** [comment]
### Mailfix updated for 8.1.1

➡️ https://danielhlavacek.cz/files/811mailfix.zip
➡️ Keeps the latest version of SwiftMailer that comes with 8.1.1 and only adds the removed transport, with some fixes and improvements that have been done to other transports.

**Comment by presta-modulShopmkCZ** [comment]
> ### Mailfix updated for 8.1.1
> ➡️ https://danielhlavacek.cz/files/811mailfix.zip ➡️ Keeps the latest version of SwiftMailer that comes with 8.1.1 and only adds the removed transport, with some fixes and improvements that have been done to other transports.


The fix is ​​not complete, I copied the entire swiftmailer function from the original archive for PS 177 and it works

![image](https://i.imgur.com/Cd4nDi5.png)
