### ISSUE TITLE
ps_mainmenu, the "edit" button redirects me to "insert link" dialog

### ISSUE THREAD

**Issue by dmoibm** [PrestaShop/PrestaShop#22282]
#### Describe the bug

If I press the edit button of a link in the link list I get the insert link dialog. 

#### Expected behavior

I expect to get the link edit dialog.

#### Steps to Reproduce

1. Go to Module 'Main menu'
2. Click 'Edit' on a link in the link list
3. See 'ADD A NEW LINK' instead of 'UPDATE LINK'

After click to 'Edit' the URL is like this:
`http://.../admin.../index.php?controller=AdminModules&configure=ps_mainmenu&updatelinksmenutop=&id_linksmenutop=1&token=...`
If I change the URL to this (add 1 to updatelinksmenutop=):
`http://.../admin.../index.php?controller=AdminModules&configure=ps_mainmenu&updatelinksmenutop=1&id_linksmenutop=1&token=...`
the correct dialog is shown and all things are ok.

**Screenshots**
![image](https://user-images.githubusercontent.com/11785485/101441976-a2e85480-391a-11eb-874a-cee4d2f5cc03.png)

#### Additional information

* PrestaShop version: 1.7.7.0-rc.1
* PHP version: 7.3.24

**Comment by hibatallahAouadni** [comment]
Hello @dmoibm 

I managed to reproduce your issue only with PS1.7.7.0 and Mainmenu v2.2.0, so it's a regresion!

- **PS1.7.7.0** - Mainmenu v2.2.0

![image](https://user-images.githubusercontent.com/23308427/101508273-bd045000-3977-11eb-9132-b614a256ccf4.png)

- **PS1.7.6.9** - Mainmenu v2.1.1

![image](https://user-images.githubusercontent.com/23308427/101508167-a0681800-3977-11eb-96aa-ddb02818bbf1.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by dmoibm** [comment]
Sorry! I'm to stupid to send you a pull request;-) But the solution is:

change Line 1092 from:
`'title' => (Tools::getIsset('updatelinksmenutop') && Tools::getValue('updatelinksmenutop')) ?`
to:
`'title' => (Tools::getIsset('updatelinksmenutop') && !Tools::isSubmit('updatelink') ) ?`

and Line 1146 from:
`if (Tools::getIsset('updatelinksmenutop') && Tools::getValue('updatelinksmenutop')) {`
to:
`if (Tools::getIsset('updatelinksmenutop') && !Tools::isSubmit('updatelink')) {`

In File ps_mainmenu.php on Dev branch of PrestaShop/ps_mainmenu

I will learn to made a pull request for the next time;-)
Have fun!

**Comment by LouiseBonnard** [comment]
Hi @dmoibm, I'm sure your first PR will be a success! If you ever feel like trying to submit your fix, you can read the [CONTRIBUTING.md](https://github.com/PrestaShop/PrestaShop/blob/develop/CONTRIBUTING.md) file and the [contribution guidelines](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/) before, everything is explained. ;-)
