### ISSUE TITLE
1.7.7.0 Orders page - filtering orders not working on drop-down change

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#22301]
#### Describe the bug

Orders page - In previous versions changing drop-down order status filtered orders by selected order status. It doesn't work anymore and to filter orders, you have to confirm the action by "Search" button. It is therefore one extra click of mouse, why?
Same goes for "Delivery country" or "New client".

Please don't tell me it is a "feature"!

#### Expected behavior

Same as before, orders should be filtered immediately after selecting requested value from the drop-down menu.

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by SimonGrn** [comment]
Hello,

thank you for your issue. This new behavior is the result of the migration of the Orders page, and it's working that way because all searchable grids work the same way in migrated page. The goal is to have an homogeneous system.

So yes, it is indeed a feature.

Thank you for your understanding.
