### ISSUE TITLE
CMS Pages can be modified but does not work in front office ( 404 Not found) 

### ISSUE THREAD

**Issue by Haitamc** [PrestaShop/PrestaShop#22312]
**CMS Pages** can be modified in BO but **does not work in front office** (404 Not found) 

I'm facing a problem with CMS pages they are not working all page return 404 error here is a CMS pages link 
[https://pomme-cannelle.fr/content/3-termes-et-conditions-utilisation](https://pomme-cannelle.fr/content/3-termes-et-conditions-utilisation)

I have enabled and disabled URL rewriting to regenerate htaccess but the problem still the same 
the links are not working even when I disable URL rewriting

![CMS-pages-error](https://user-images.githubusercontent.com/32599737/101647431-04064a00-3a39-11eb-919b-77f34f62e3a6.png)

I really need your help 
Thanks in advance 

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @Haitamc 

I didn't manage to reproduce your issue with PS1.7.6.8 and PS1.7.7.0. It seems that your issue is not a PrestaShop core bug.

I'm really sorry but I have to close this issue. Cause, we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one
of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by Haitamc** [comment]
I will recontact the theme author and try to find a solution

Thank you for taking time to answer
