### ISSUE TITLE
Product Import - Main category deleted after the import

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22336]
#### Describe the bug

Hello,

We have an issue on our prestashop (1.7.6.1) : when we import a product with only columns ID & Name, the main category of the product is deleted.

#### Expected behavior

The import should only change the data that are in the csv imported, no other information on the product.

#### Steps to Reproduce

1. Prepare a CSV to import a product : 
![image](https://user-images.githubusercontent.com/60292126/101781462-214e1d80-3af8-11eb-8358-43f3d1e7155c.png)

2. Check in the back office the main category of the product you want to import before doing the import (here it is "jumelles" : 
![image](https://user-images.githubusercontent.com/60292126/101781032-9a00aa00-3af7-11eb-8b02-6d4adebe49f9.png)

3. Go in the import part & import your CSV : 

![image](https://user-images.githubusercontent.com/60292126/101781433-17c4b580-3af8-11eb-945d-017595159ea2.png)

![image](https://user-images.githubusercontent.com/60292126/101781419-13000180-3af8-11eb-81d1-7f3ba2ec2d85.png)

![image](https://user-images.githubusercontent.com/60292126/101781402-0f6c7a80-3af8-11eb-8031-b0f22d55d935.png)

![image](https://user-images.githubusercontent.com/60292126/101781488-2a3eef00-3af8-11eb-8ca3-4021bf7607c7.png)

4. Go back to the product page to see the change in the title (which is normal) and to see that the main category was deleted and moved to 'all products':
![image](https://user-images.githubusercontent.com/60292126/101781564-46429080-3af8-11eb-8d9c-c588ab72a555.png)

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @LauSoup 

If you import CSV only contains two columns (id_product and name), so it's normal to find that the parent Category is the default category, see the attached screen record below:

https://drive.google.com/file/d/1jz_AMP4J_904uh8Fd_Du9Q2hg5aJqx_2/view

But, in your last screenshot, I've seen that "Jumelles" category is checked!! Did you check it manually?
Please check and feedback.

Thanks!

**Comment by ghost** [comment]
Hello @hibatallahAouadni,

Thanks for your answer :) 

My issue is not on the "left part" of the categories, but on the main category part : 
![image](https://user-images.githubusercontent.com/60292126/101895867-6467c980-3ba8-11eb-88f8-9876d401a6b8.png)

The categories themselves are still checked (which is good), but the main category always go back to "all products" instead of staying on the one checked before the import ("Jumelles" in this case). 
As we don't import the categories it should not move the main category I think, as it does not move anything else on the product that is not imported.

Also additional question : is there a way to import the main category ? I tried imported all categories again on a product but the main category is always "all products" after import. As we imported all our catalogue to change the titles I would like to correct the main category with an import too, and not by hand.

Many thanks

**Comment by hibatallahAouadni** [comment]
Hello @LauSoup 

After importing CSV containing only id_product and the name:

![image](https://user-images.githubusercontent.com/60292126/101781462-214e1d80-3af8-11eb-8358-43f3d1e7155c.png)

> The categories themselves are still checked (which is good)

How it could be the categories are checked (even in the left part) !!!???? It's not possible! 
That's why I asked "did you checked manually" :wink: 

> I tried imported all categories again on a product but the main category is always "all products" after import.

Could you please list the steps that you did to import the categories.

Thanks!

**Comment by ghost** [comment]
Hi @hibatallahAouadni ,

I confirm that the categories that were checked BEFORE the import are still checked AFTER the import on the left part even with just id and name in the import file.
I made a video to show it to you:
https://drive.google.com/file/d/19dipkLQKvGm2p92jv4Ckf9Q1zTvStK5i/view?usp=sharing

To reproduce follow the steps on my first message, on a product that already has categories checked (I don't see how was your product before your import in the video you sent).

Also please can you explain how to import main categories in addition to checking the initial bug?

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @LauSoup 

Thanks to your screen record I managed to reproduce the issue. This issue is related to #12092
Let's list more simple steps to reproduce the issue:

1. **BO**>**SELL**>**Category**> cretae a new product
2. Check some categories as **associated categories** and check one as the **main category**
3. **Save**
4. In the product list, copy the newly created product **id**
5. Download the attached [test.txt](https://github.com/PrestaShop/PrestaShop/files/5742172/test.txt) file, paste the **product_id** and save, then change the file extension to **.csv**
6. **BO**>**Advanced Parameters**>**Import**
7. Choose Products in the **What do you want to import?** select
8. Choose the the CSV file
9. Uncheck the **Delete all products before import** option
10. Check the **Use product reference as key** option
11. Uncheck the **Skip thumbnails regeneration** option
12. Check the **Force all ID numbers** option
13. Click on **Next step** button => import success
14. **BO**>**SELL**>**Category**>**Products**, edit the imported product
15. See error in Category tree (see the attached screen record below to understand better the issue)

https://drive.google.com/file/d/1jKqLuPaK7-BltPclKPEE9TG9gx2r3z2E/view

To be honest, I don't if it's a bug or not.
This issue has to be specified. Ping @PrestaShop/product-team is it a bug? 

Thanks!

**Comment by Manuel905** [comment]
Hello, @hibatallahAouadni ,
I have seen the following change in the file AdminImportController.
Controllers/admin/AdminImportController.php
In 1.7.5
From line 1948 to 1957  the code is;

![cambios de categoria archivo AdminImportController 1 7 5](https://user-images.githubusercontent.com/83748387/117530256-6493b600-afdc-11eb-8b11-20b321cb39d5.JPG)

In 1.7.7
From line 1940 to 1950 the code is:

![cambios de categoria archivo AdminImportController 1 7 7](https://user-images.githubusercontent.com/83748387/117530327-d3710f00-afdc-11eb-93b2-c81fc893a373.JPG)

If we change these lines in 1.7.7 for the code lines of version 1.7.5 the problem is solved.
Can you check if this is what is causing the bug?

Thanks!

**Comment by MatShir** [comment]
This is indeed a bug :) and a major problem, an import should never result in data loss.
