### ISSUE TITLE
BO Persistent cache

### ISSUE THREAD

**Issue by radioeventos** [PrestaShop/PrestaShop#22334]
#### Describe the bug

On PS1.7.7. every time I chace of page on BO I have to refres with Ctrl+F5 to update the data. Always show previous version of the page, not the last. Same when chace the sop on multishop or on order list when push reset doesn´t do it. I have to reload with Ctrl+F5 to really reset.

#### Expected behavior

I expect when I pus o menu or other link togo to other page, it show the last version, not previous version showed.

#### Steps to Reproduce

1. Go to 'menu'
2. Click on 'Orders, o customers, for example'
4. See error: show the sanme information like the last time although new orders or customers have entered

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.3.25

**Comment by hibatallahAouadni** [comment]
Hello @radioeventos 

I didn't manage to reproduce your issue with PS1.7.7.0 and develop, see the attached screen record below:

https://drive.google.com/file/d/1A7NvXHxifcOn3K9ZTnWlX_CirPqKOPng/view

Please check and feedback.

Thanks!

**Comment by radioeventos** [comment]
Example:
I try to change the shop:
![image](https://user-images.githubusercontent.com/5453650/101809442-da702000-3b17-11eb-9b61-4a639d2f5466.png)
But does nothing:
![image](https://user-images.githubusercontent.com/5453650/101809537-f96eb200-3b17-11eb-9b49-2190c9d6ef12.png)
I have to refresh with trl+F5 to make a change:
![image](https://user-images.githubusercontent.com/5453650/101809717-2e7b0480-3b18-11eb-888f-d9131bc04299.png)

If I go in to one oreder an make a change, for example status:
![image](https://user-images.githubusercontent.com/5453650/101810121-b06b2d80-3b18-11eb-891d-5044bdfbfa31.png)
![image](https://user-images.githubusercontent.com/5453650/101810264-e14b6280-3b18-11eb-8519-2a335b2b4e3a.png)
After click in ORDERS in menu:
![image](https://user-images.githubusercontent.com/5453650/101810452-16f04b80-3b19-11eb-961a-a7f531a168eb.png)

Order still  at the same status. I have to refresh with Ctrl+F5:
![image](https://user-images.githubusercontent.com/5453650/101810668-5a4aba00-3b19-11eb-9b32-2222a93ab738.png)
It´s the same when edit procucts, translations, categorires, modules... You see the changes when click in Save, but if go out, when you came in again, you see the page like before you make the last changes. You have to refres to see the last version. It´s horrible.

**Comment by hibatallahAouadni** [comment]
Hello @radioeventos 

It seems that your issue is not a PrestaShop core bug. Please check your server.

I'm really sorry but I have to close the issue, cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one
of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
