### ISSUE TITLE
Three digits after the comma

### ISSUE THREAD

**Issue by mahdimedia** [PrestaShop/PrestaShop#22375]
hello

Comic problem in all previous releases
In the currencies of Arab countries, three digits are used after the comma
But the problem has not been solved yet

**Screenshots**

https://snipboard.io/xVcrEQ.jpg

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @mahdimedia 

This issue is already solved with PS1.7.7.0, follow these steps to use three digits after the comma with your currency:

1. BO > IMPROVE > International > Localization
2. Go to Currencies tab
3. Click on edit button of your currency
4. Change the value of Decimals to 3
5. Save
6. Check FO > you will see all prices are displayed with three digits after the comma with your currency.

See attached screen record below:

https://drive.google.com/file/d/1GNej10v703es_H2_W188zVYjaFBwG5Yz/view

Thanks!
