### ISSUE TITLE
BO - Import page - There is no option "Delete all stores before import" but the alert about accepting the delete is required

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#22372]
#### Describe the bug

In the BO > Import page > when we select "Stores contact", there is no option "Delete all stores before import", but when we click on the "Next step" button, the alert  Are you sure you want to delete this entity: store contacts?" is displayed

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Import page
2. The Category option is selected by default
3. Enable the option "Delete all categories before import"
4. Select the Stores Contact Option
5. There is no option "Delete all stores before import" 
6. Choose a file csv
7. Click on the "Next step" button
8. See the error "Are you sure you want to delete this entity: store contacts?" 

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/101923928-4e6dff00-3bd0-11eb-9e0f-1654c2e2d559.png)

#### Additional information

* PrestaShop version: 1765, 1770, develop (1780)
* PHP version: 7.1, 7.2

**Comment by zuk3975** [comment]
I see there is a PR already, but I cannot understand the expected behavior. Can it be described?
I mean, should the option "Are you sure you want to delete this entity: store contacts?" be added to form, or is it ok that its not there and we just should not allow deleting all contacts before import (so the warning should not be shown as well in that case)?
