### ISSUE TITLE
Autoupgrade module update v4.8 to v4.9 fails

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22399]
Issue reported by @nenes25 for PR https://github.com/PrestaShop/autoupgrade/pull/374

#### Describe the bug

When upgrading the module from version 4.8.0 through command line you should not have an error in upgrade file [install-4.9.0.php](https://github.com/PrestaShop/autoupgrade/blob/master/upgrade/install-4.9.0.php) line 32: `Call to private method Autoupgrade::registerHookAndSetToTop() from context`

The function is private and is called in upgrade file, this is an error.

This can be seen from the command line:

<img src="https://user-images.githubusercontent.com/7163132/102023224-34791b80-3d8c-11eb-96fa-f1ec74e5133d.png">

On back office, it's a red error message (see below)

#### Expected behavior

Autoupgrade module update v4.8 to v4.9 is successfull.

#### Steps to Reproduce

1. Install autoupgrade module v4.8
2. Upgrade module to more recent version
3. See error

**Screenshots**

<img src="https://user-images.githubusercontent.com/7163132/102023224-34791b80-3d8c-11eb-96fa-f1ec74e5133d.png">.

**Comment by matks** [comment]
@nenes25 Can you give us the exact Command Line you have run? It's to help QA test this 😉

**Comment by nenes25** [comment]
@matks you never stop working :D 
Sure in my case it's a bit special as i'm using a custom command to manage modules.
But it is just a wrapper for php bin/console prestashop:module  upgrade autoupgrade ( when the source files are already updated but the upgrade not installed in db )

In fact you could also reproduce the issue in the back office.
Download the release https://github.com/PrestaShop/autoupgrade/releases/tag/v4.8.0 and install it.
Then try to update the module with the "update" button
![image](https://user-images.githubusercontent.com/7163132/102026503-78751c00-3d9e-11eb-8c36-24c276358826.png)

I guess that more users shoud have this error in back office then.

Regards,

**Comment by hibatallahAouadni** [comment]
Hello @matks & @nenes25 

I managed to reproduce the issue with PS1.7.7.0, following these steps:

1. `git clone https://github.com/PrestaShop/autoupgrade.git`
2. `cd autoupgrade`
3. `git checkout tags/v4.8.0`
4. `composer install`
5. Compress the folder autoupgrade
6. **BO** > **IMPROVE** > **Modules** > **Module Manager**
7. Click on **Upload a module** button
8. Drag and drop the compressed autoupgrade folder
9. The autoupgrade module is well displayed in the installed modules list
10. Click on **Upgrade** button
11. See error

I got two different error messages, see the attached screen records below:

- on the first click:
https://drive.google.com/file/d/1ZrhyPXXCipYwOI-dTMcb8rKSW6X7wbB-/view
- on the second click:
https://drive.google.com/file/d/1Wib0R-mUDKaVu7zf9rYGVa7Dn7LIFzAR/view

I’ll add this to the debug backlog so that it’s fixed. Thanks for your PR.

Thanks!

**Comment by vegancorr** [comment]
The same issue seems to be with PS v. 1.6.1.3 and "1-Click Upgrade" module v. 4.11.0

The following error occurs at this address
/administrator/index.php?controller=AdminModules

```
[PrestaShop] Fatal error in module file : [...]/public_html/modules/autoupgrade/upgrade/install-4.9.0.php:
Call to private method Autoupgrade::registerHookAndSetToTop() from context ''
```
In case you were wondering about the old versions, the website was not maintained for years and I was asked if I could fix just the above error.

**Comment by matks** [comment]
@PrestaShop/product-team As mentioned in https://github.com/PrestaShop/PrestaShop/issues/22819 now that people are upgrading to PS 1.7.7 it might be urgent to process this issue because (to be confirmed by QA) I believe "everybody that has installed module autoupgrade before and now tries to update it will see the upgrade process fail" (see details in https://github.com/PrestaShop/PrestaShop/issues/22819)

**Comment by Robin-Fischer-PS** [comment]
Hi,

I tried with a 1.7.2.4 fresh install, with 4.8.0 autoupgrade module (downloaded here https://github.com/PrestaShop/autoupgrade/releases/tag/v4.8.0).
The upgrade of the module from 4.8.0 to 4.11.0 went fine, BUT the displayed version in the BO is not modified, and the upgrade buttons is still displayed after upgrade to 4.11.0.
The upgrade process via autoupgrade from 1.7.2.4 to 1.7.7.1 is OK (not OK when using 4.8.0 autoupgrade version).

When clicking again on the upgrade button of the module, I have the error mentioned : "Could not perform action update for module undefined" (probablu because, in fact, the module is already updated).

It's confusing for the user (with the wrong module version displayed), but it works fine when upgrading PS.

See screenrecord : 

https://drive.google.com/file/d/1IOQOaqvCqxtihz_aL_i00WpgFOBt6yjM/view?usp=sharing

**Comment by musicpanda** [comment]
@Robin-Fischer-PS 

When you upgrade the way you do - by choosing the "install module" option, then it indeed overwrites the module - except for the version number.  You do get the error message but it looks like the files are overwritten and so the problem goes away.

However, this doesn't apply when for example you go the Module Manager page in the backoffice and you click on "Upgrade" at the end of the line for this module. In that case there is no change and are stuck with the old version.
