### ISSUE TITLE
If "Set the order as paid" is necesary to activate RMA, payments appears dupliclated on BO order detail

### ISSUE THREAD

**Issue by radioeventos** [PrestaShop/PrestaShop#22414]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

I want activate RMA and is necessary switch on "Set the order as paid." on order status to activete it, but payments appears duplicated every status set ont tat option. If i have set on in "Payment Acepted" and like if set on Prestashop dosc: "...it cannot be set back to the previous status." Why is it necessary to have this option activated to allow RMA?

#### Steps to Reproduce

1. Allow Retuns on Merchandise returns.
2. In FO go to an order "Delivered"
3. If "Set the order as paid" is not allowed on this status, RMA does not appear. If is alowed, RMA appears but duplicate the original payment on BO when change the status.

**Screenshots**

Appears new payment when order change:
![image](https://user-images.githubusercontent.com/5453650/102119698-d60e7480-3e41-11eb-9e6f-dabfe1ea6d21.png)

If Set the order as paid, RMA is alowed:

![image](https://user-images.githubusercontent.com/5453650/102120189-75cc0280-3e42-11eb-8a65-a03aa91df6ae.png)

If Unst order as paid, RMA disalowed:

![image](https://user-images.githubusercontent.com/5453650/102120374-bcb9f800-3e42-11eb-901f-3e952e2dc747.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @radioeventos 

I believe that's the expected behavior, even with PS1.7.6.9, I get the same behavior :wink:
So, let's list your steps clearly here:

1. **BO** > **SELL** > **Customer Service** > **Merchandise Return**
2. **MERCHANDISE RETURN (RMA) OPTIONS** block, activate the **Enable** returns option, then **Save**
3. **BO** > **CONFIGURE** > **Shop Parameters**  > **Order Settings**
4. **Statuses** tab, edit **Delivered** status
5. Uncheck **Set the order as paid** option, then **Save**
6. **FO** > make an order
7. **BO** > **SELL** > **Orders** > **Orders**
8. Change the last created order's status to **Delivered**
9. **FO** > **My account** >  **Order History and Details**
10. You can see that the checkbox or **RMA** doesn't exist

Screen record with PS1.7.7.0:
https://drive.google.com/file/d/1woHAxcLFF8MEY4kG2dcvTigr11_popk2/view

Ping @PrestaShop/product-team is this the expected behavior? if I'm wrong please correct me :wink: 

Thanks!

**Comment by radioeventos** [comment]
> Hello @radioeventos
> 
> I believe that's the expected behavior, even with PS1.7.6.9, I get the same behavior 😉
> So, let's list your steps clearly here:
> 
> 1. **BO** > **SELL** > **Customer Service** > **Merchandise Return**
> 2. **MERCHANDISE RETURN (RMA) OPTIONS** block, activate the **Enable** returns option, then **Save**
> 3. **BO** > **CONFIGURE** > **Shop Parameters**  > **Order Settings**
> 4. **Statuses** tab, edit **Delivered** status
> 5. Uncheck **Set the order as paid** option, then **Save**
> 6. **FO** > make an order
> 7. **BO** > **SELL** > **Orders** > **Orders**
> 8. Change the last created order's status to **Delivered**
> 9. **FO** > **My account** >  **Order History and Details**
> 10. You can see that the checkbox or **RMA** doesn't exist
> 
> Screen record with PS1.7.7.0:
> https://drive.google.com/file/d/1woHAxcLFF8MEY4kG2dcvTigr11_popk2/view
> 
> Ping @PrestaShop/product-team is this the expected behavior? if I'm wrong please correct me 😉
> 
> Thanks!

I suppose it's the behavior that has to be expected, but I don't understand several things: 
First, why if it's a state that doesn't have to go back, as specified in Prestashop docs, it's necessary for returns to work if the service is already activated elsewhere and there's already the circumstance that the status has to be delivered for them to workand for as long as it is determined. By the way, that time should start counting from delivery, which is when they start legally counting deadlines, not from purchase.

And second, if the option to set the order as paid beyond Accepted Payment really needs to be enabled, why are payments duplicated? That's the main problem, that payments appear duplicated.

**Comment by LouiseBonnard** [comment]
Hi @radioeventos, @hibatallahAouadni, it's the expected behavior. Merchandise can be returned if the following conditions are met: 

1. Merchandise returns are enabled.
2. It is still time to return a product.
3. Both 'Set the order as paid' and 'Set the order as shipped' settings must be enabled, either by one status (the two parameters are checked) or two statuses (each one having one of the two parameters checked).

**Comment by hibatallahAouadni** [comment]
Hello @radioeventos 

Thanks @LouiseBonnard for the confirmation and the explication!

As @LouiseBonnard mentionned above, this is the expected behvior. 
So, I close the issue.

Thanks!

**Comment by radioeventos** [comment]
Hello again,
As I am checking in real cases, do not test, if the Set order as paid parameter is not enabled in all cases after the Accepted Payment status, it doubles the payment, so it is something that should be noticed in Prestashop Docs, since it is only said that after setting this paramertro there is no going back:  "once an order is set as "paid", it cannot be set back to the previous status."(http://doc.prestashop.com/display/PS17/Statuses)
So why should it be kept pointing out after the first time if there is no reverse?
And now, in a real case, I repeat, not test, due to the failure of a thirteen module, the order has entered the Payment Error state and the payment has been noted without being marked in the state "Set the order as paid" and after passing the order to Payment Accepted, the payment note has doubled, since in the latter state IF it is marked to set the order as paid.
I don't know where the inconsistencies or lack of information, such as the one in prestashop's Documentation, come from. So either inconsistencies are corrected or the behavior of states and their consequences are correctly documented in order to perform actions such as returns.
Anyway, with the subject of payments, I insist as it was done in another thread that is not normal that you cannot make a negative payment note or delete a payment to delete the payment error message, among other things. It is one thing that the total payment cannot be negative and another that no refunds of partial amounts can be entered.
I am sorry I could not answer before, but I am a trader and I have to take care of my stores, which with all the errors of the latest version and un-updated modules by third parties, gives more work than normal.
Regards.

**Comment by radioeventos** [comment]
And now not knowing why, all payments are doubled:
![image](https://user-images.githubusercontent.com/5453650/102354778-53092d80-3fab-11eb-9b57-0ebde7c227d5.png)

![image](https://user-images.githubusercontent.com/5453650/102354822-5e5c5900-3fab-11eb-9276-e467dd79a2ac.png)
Seriously, this is starting to bore me.

**Comment by hibatallahAouadni** [comment]
Hello @radioeventos 

Take it easy :sweat_smile: just list the steps to repoduce, so I can check the problem.
If I found it as a new bug, so you need to open a new issue :wink: 

Thanks!

**Comment by radioeventos** [comment]
Unique step its to make an order. The only difference is that in the Accepted Payment step it is marked that the delivery note is generated so that the invoice dates and the number are consequential, since it takes that date from that of the generation of the packing slip, not that of the time of invoice creation, which I consider an error, and I am sick of the accountant telling me that the numbers and dates are not increasing both.

**Comment by hibatallahAouadni** [comment]
Hello @radioeventos ,

I believe that your problem is a third-party modules and you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
