### ISSUE TITLE
Pagination in backoffice products after filtering by category PS1.7.6.1

### ISSUE THREAD

**Issue by zell9999** [PrestaShop/PrestaShop#22441]
### Describe the bug
When you remove the filter category in Catalog>Products, the number of products showed are 300 (instead 20). 

Maybe the problem was solved in lastest versions of Prestashop. I can not update my Prestashop version, we need to know how to fix that in PS1.7.6.1.

### Steps to reproduce
1. Go to Catalog>Products
2. Set "Show 20 products per page"
3. Filter by any category
4. Change positions of products inside that category
4. Remove filter
5. You can see now there are 300 products per page (instead 20). (This overloads the page)

**Screenshots:**
Step3:
![1](https://user-images.githubusercontent.com/36448511/102320114-2984dd80-3f7c-11eb-911c-a9957a34655d.jpg)
Step4:
![2](https://user-images.githubusercontent.com/36448511/102320115-2a1d7400-3f7c-11eb-93d2-aac6fb2b56e8.jpg)
Step5:
![3](https://user-images.githubusercontent.com/36448511/102320117-2ab60a80-3f7c-11eb-829b-e4b847f0c9e3.jpg)
Step6:
![4](https://user-images.githubusercontent.com/36448511/102320118-2ab60a80-3f7c-11eb-832d-dd5e624474da.jpg)

### Addtional infos
* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @zell9999 

I manage to reproduce the issue with PS1.7.5.2, PS1.7.6.1, PS1.7.6.9, PS1.7.7.0. But, I didn't reproduce it with PS1.7.4.1, so it's a regression. It's kind of related to this issue #11152.

@marionf do you have any idea about this issue? Cause it seems familiar to me :sweat_smile: 

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by zell9999** [comment]
Hello @hibatallahAouadni 

When category filter is enabled, the change in the order of the products is correctly saved in 1.7.6.1, so ticket #11152 would be unrelated. 
The problem is the pagination when you remove the filter.

Thanks!

**Comment by MatShir** [comment]
It seems to be fixed on 8.1 :)
