### ISSUE TITLE
Improve the given nginx .conf on the Prestashop documentation

### ISSUE THREAD

**Issue by Corazun** [PrestaShop/PrestaShop#22443]
#### Is your feature request related to a problem?

Hello since I've been trying to make Prestashop working on a Nginx configuration on my Ubuntu server I finally found that the given nginx .conf file in documentation missed an important part about rewriting the front office part. The current configuration works well on back office at the point I've tested but the front office isn't properly displaying so here's the solution I've found and I think should be added in the Prestashop documentation

```php
location / {
    if (!-e $request_filename) {
        rewrite ^/.*$ /index.php last;
    }
}
```

Add this part of code on your .conf to get the front displaying the products, and the others pages !

#### Describe the solution you'd like

Improve the https://devdocs.prestashop.com/1.7/basics/installation/nginx/ to have the whole front office properly working

#### Additional context

Prestashop 1.7.7
Nginx 1.18
PHP 7.3.24

**Comment by SimonGrn** [comment]
Hello,

the devdocs is actually a repository, and you can directly submit your modification as a Pull Request to the correct page so that it can be merged and displayed 😄 
You just need to click on the "Improve this page" link at the top right, that leads you to [this page](https://github.com/PrestaShop/docs/edit/master/src/content/1.7/basics/installation/nginx.md) where you can submit your modification.

Thank you, improving the documenation is a huge help.

**Comment by hibatallahAouadni** [comment]
Hello @Corazun 

Thanks for the suggestion, the Developers Team will take a look.
Please stay tuned !

Ping @PrestaShop/prestashop-core-developers , do you approve the solution proposed by @Corazun ?

**Comment by SimonGrn** [comment]
I'm closing this issue.
