### ISSUE TITLE
Bug main menu

### ISSUE THREAD

**Issue by Amulliez** [PrestaShop/PrestaShop#22487]
Hi,

I have had a problem for some time with the creation of CMS pages and the ps-main-menu module. Indeed, I manage to create CMS pages with my first store but when I try to do it with my second store, I cannot access the page (ERR_TOO_MANY_REDIRECTS).

When I work around the error by creating my page through the first store and equating it to the second, the CMS page category and CMS page do not appear in the main menu module as if they did not exist.

Here are screenshots of the situation.
![Site n2](https://user-images.githubusercontent.com/47451841/102593119-b82c6280-4114-11eb-8979-e74cc60c432a.jpg)
![Site n1](https://user-images.githubusercontent.com/47451841/102593127-b9f62600-4114-11eb-82cf-786adb0b4df3.jpg)
![Exemple page CMS](https://user-images.githubusercontent.com/47451841/102593130-bb275300-4114-11eb-8d55-71a321103013.jpg)

Thanks for your help.

Prestashop 1.7.6.8

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by Amulliez** [comment]
Hello @SimonGrn ,

You cannot reproduce the bug so you close the ticket? You don't go further?
I understand better why some Pretashop bugs have been going on for years now!

Despite my explanations and my screenshots, it seems that you do not understand all the steps:
1- Create a CMS page on the store 1
2- Create another CMS page on store 2 (I cannot access this tab on my side)
3- Install the ps_mainmenu module on the two stores
4- Integrate the CMS page into the main menu on each store

Prestashop 1.7.6.8
Template store 1 : classic-child
Template store 2 : classic-child

Thanks for your help.

**Comment by SimonGrn** [comment]
> Hello @SimonGrn ,
> 
> You cannot reproduce the bug so you close the ticket? You don't go further?

We didn't try to reproduce it because you didn't bother following the template. We are not robots, we are humans, we don't have a lot of time to work FOR FREE to fix this Open Source project, so we ask one thing: that people who come here to get their problems diagnosed follow the template. That's it. That's the only thing we ask.
If you don't have any respect for us, how do you expect we solve your issue exactly ?

> I understand better why some Pretashop bugs have been going on for years now!

This is an Open Source project, meaning people work here so you can get a FREE PrestaShop product. It means you are a part of the community because you use this project, meaning you can help too. Which you apparently think is not your responsibility.

> Despite my explanations and my screenshots, it seems that you do not understand all the steps:

We have a Cod of Conduct, that you are not following. Once again, we are humans, we don't have a lot of time, we can't spend our time trying to understand what's happening in an issue when somebody didn't give all the info we need.

Please open a new issue, and please follow the template.

As this one won't go any further, I lock it.

Thank you for your understanding.
