### ISSUE TITLE
Problem with product_mini_ images

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#22496]
Hi,
After successfull upgrade from 1.7.5.2 to 1.7.6.9 and right after to 1.7.7.0 (direct 1.7.5.2 to 1.7.7.0 has failed) customer notticed missing BO product images from the list view.

It's funny because products have images on place but product_mini_ images are missing randomly and showing randomly...
Heck?

1) Product (ID 120) have image on place
![1](https://user-images.githubusercontent.com/8243273/102609275-7d81f480-412b-11eb-8211-ed2e120222e7.png)
2) Product have image
![2](https://user-images.githubusercontent.com/8243273/102609286-807ce500-412b-11eb-8fe5-dcd0193e2573.png)
3) Product have only dot and image is missing
![3](https://user-images.githubusercontent.com/8243273/102609289-82df3f00-412b-11eb-86e6-fba1e0d7ec6c.png)
4) Product have image again...
![4](https://user-images.githubusercontent.com/8243273/102609295-85da2f80-412b-11eb-9238-68a736f5ee42.png)

/img/tmp folder was flushed and images regenerated successfully
![6](https://user-images.githubusercontent.com/8243273/102610176-09485080-412d-11eb-863c-71f4e8130cae.png)

but... randomly not seen by the shop...
![5](https://user-images.githubusercontent.com/8243273/102610217-18c79980-412d-11eb-91c4-3a7a860813c0.png)

**Comment by florine2623** [comment]
Hi @PrestaShark ,

After regenerating the images, did you encounter errors ?

In the folder /img/tmp, are the images present ?

Can you also regenerate .htaccess by oing to SEO&URL and save configuration without making any change ?

Thanks

**Comment by HartLarsson** [comment]
product_mini_xxx.jpg are under /img/tmp
You can try to delete one from the folder and see if is recreated right.

**Comment by ghost** [comment]
> 
> 
> product_mini_xxx.jpg are under /img/tmp
> You can try to delete one from the folder and see if is recreated right.

Yes they are recreated but unfotrunately unseen by the script on BO. File is on place but not shown on the BO. Take a look at two last attached images... :/

**Comment by HartLarsson** [comment]
> > product_mini_xxx.jpg are under /img/tmp
> > You can try to delete one from the folder and see if is recreated right.
> 
> Yes they are recreated but unfotrunately unseen by the script on BO. File is on place but not shown on the BO. Take a look at two last attached images... :/

if you take the image url and paste in another browser tab, you see the pic? if yes probably is a browser cache problem

**Comment by hibatallahAouadni** [comment]
Hello @PrestaShark 

> Yes they are recreated but unfotrunately unseen by the script on BO.

That's weird!!! even your console doesn't show any error about broken URL.

> if you take the image url and paste in another browser tab, you see the pic? if yes probably is a browser cache problem

Could you please try to clear cache like @HartLarsson mentionned above and check.

Thanks!

**Comment by ghost** [comment]
Nothing changed even in other browser.

Any dependencies could broke that images and function?

**Comment by hibatallahAouadni** [comment]
Hello @PrestaShark 

When I tried to upgrade a shop PS1.7.5.2 to PS1.7.7.0, I get no error but everytime I try to open Order page or Products page, I got this exception (error 500):

![image](https://user-images.githubusercontent.com/23308427/103131608-b5e08000-46a1-11eb-8389-28ac1cf062c0.png)

Then I execute this command line like @jolelievre suggest in this issue #14617

`ALTER TABLE PREFIX_admin_filter ADD filter_id VARCHAR (255) DEFAULT '' NOT NULL AFTER shop;`

The problem is fixed :tada: thx @jolelievre :rocket: 

1. BO>SELL>Products, I can see all the products with their attached images
2. BO>IMPROVE>Design>Image Settings, I regenerate all products images and the Erase previous images" is checked.
3. The thumbnails were successfully regenerated. And I didn't encounter your problem.

I'm really sorry but I didn't manage to reproduce your issue :confused: 
Is there a detail you missed? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @PrestaShark ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
