### ISSUE TITLE
screen remains white with warning message

### ISSUE THREAD

**Issue by BENZINEBK** [PrestaShop/PrestaShop#22509]
Hello,  I have been having the a problem for a week now, my front and back office page page displays 
messages :

 

Warning: rename (/tmp/class_index.phplJtY1y,/var/www/html/var/cache/dev/class_index.php): No file or directory of this type in /var/www/html/classes/PrestaShopAutoload.php in route 264

Warning: rename (/tmp/class_stub.phpziTlg3,/var/www/html/var/cache/dev/class_stub.php): No file or directory of this type in /var/www/html/classes/PrestaShopAutoload.php in route 264

Warning: rename (/tmp/namespaced_class_stub.php6ilLux,/var/www/html/var/cache/dev/namespaced_class_stub.php): No file or directory of this type in /var/www/html/classes/PrestaShopAutoload.php in route 264

Warning: require_once (/var/www/html/var/cache/dev/appParameters.php): failed to open stream: no such file or directory in /var/www/html/config/bootstrap.php online 87

Fatal error: require_once (): Failed to open required '/var/www/html/var/cache/dev/appParameters.php' (include_path = '/ var / www / html / vendor / pear / pear_exception: / var / www / html / vendor / pear / console_getopt: / var / www / html / vendor / pear / pear-core-minimal / src: / var / www / html / vendor / pear / archive_tar:.: / usr / local / lib / php ') in /var/www/html/config/bootstrap.php on line 87

Following an update from 1.7.4.2 to 1.7.07, I performed this update because the site no longer accepts any module for some time, at the time of the update error file install. TxT, after I wanted to make a back up to the old version impossible, I left the application wanting to see a little later but unfortunately I can not find anything, I also reinstall an old image that I saved for a few days from my old server, but unfortunately no solution, screen remains white with warning message.

I ask for your help because I am at a dead end.

Thank you.

**Comment by SimonGrn** [comment]
Hello,

You probably need to empty your cache manually: try emptying the folder /var/www/html/var/cache/.

However your problem seems to be linked to your environment, so I close this issue: we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
