### ISSUE TITLE
[RESPONSIVE - BO] Notification window modal can't be closed on migrated pages

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22514]
#### Describe the bug

When you open notification modal, you see this :

![image](https://user-images.githubusercontent.com/14963751/102768648-c9c67200-4381-11eb-9f1c-b4f6df070f6a.png)

#### Expected behavior

I would suggest as a quickwin to just add a small margin like this :

![image](https://user-images.githubusercontent.com/14963751/102768791-fda19780-4381-11eb-8590-9a5fde3e0208.png)

#### Steps to Reproduce

1. Go to Orders page
2. Click on Notification icon on the left on mobile

#### Additional information

* PrestaShop version: develop

**Comment by prestascott** [comment]
Hey @NeOMakinG,

Nice improvement, i will add a 16px margin left and right on mobile to keep it consistent with the BO. 
Also, the notification icon needs to be put on focus state to show that it's selected. It's confusing to see that the view my shop's icon is blue, it needs to be grey otherwise it's confusing for users to identify if it's selected or not.

Here is my design proposition:
![notification](https://user-images.githubusercontent.com/54888056/102771812-d39ea400-4386-11eb-8b98-6afab3208180.png)

**Comment by prestascott** [comment]
@NeOMakinG I changed the design of the notification window modal to give the best UX. 
It will now be in full width of the screen, and when the notification icon is clicked/selected there is an indicator in primary color to emphasize the fact that it's selected. 
Also, everything behind is darker because I want our merchants to be focused on the modal so they won't be disturbed by what's behind.

Here is my latest design proposition:
![notifications](https://user-images.githubusercontent.com/54888056/105055763-b3d8c980-5a73-11eb-8340-6b4e956df1fd.png)

You can also find the Figma prototype [here](https://www.figma.com/proto/b2sVogt6tyvB5EIkVmTAdP/PrestaShop-Responsive?node-id=412%3A1969&scaling=min-zoom).
