### ISSUE TITLE
Posts products in front page - ordonate

### ISSUE THREAD

**Issue by itsoftgroup01** [PrestaShop/PrestaShop#22604]
Greetings, 

I have prestashop 1.7.6.9. and I have the next problem or we can call it a bug. I imported over 3000 products in the store, some are active and others are not. The problem is that when I want to activate 2 products, one with the number 20 and 30, they do not appear in the order in which they are published, they appear in the order that they are in the list of products.

Site: ​https://macoshop.ro/​​​

 I want to appear in the new products section, but in the order in which I publish them. I know I can filter and move them manually, but I can't move so many products to infinity by hand.

 I also searched for preferences - products and selected to appear in the order when they change but do not work.

 What can I do ? 

Thanks.

**Comment by hibatallahAouadni** [comment]
Hello @itsoftgroup01 

**Please follow the template to submit a complete bug report**.

> I also searched for preferences - products and selected to appear in the order when they change but do not work.

Could you please watch the screen record below, cause in my case it works :wink: 

https://drive.google.com/file/d/1vj0l6uSWrADEjQie4xdp81aPeFmDlPwN/view

Please check and feedback.
Thanks!

**Comment by itsoftgroup01** [comment]
Not work at me..

**Comment by hibatallahAouadni** [comment]
Hello @itsoftgroup01 

Sir, please **FOLLOW THE TEMPLATE TO SUBMIT A COMPLETE BUG REPORT**.
We need these informations to reproduce your issue and to help you solving your problem.
If you don't provide these infos how we could help you :slightly_smiling_face: 

Thanks!

**Comment by itsoftgroup01** [comment]
what template if this is my entire problem. 

my products are displayed by product id, and I don't want that, I need a code or to edit product.tpl to display my new products when I modify a product to appear first in my list on the first page of new products, I repeat not to take after the product id but when I modify a product it should be put first on the first page at new products

**Comment by hibatallahAouadni** [comment]
Hello @itsoftgroup01 

If you follow the steps that I presented in the screen record above, it will display your new products / recently updated products in the top of the list.
Otherwise, if this doesn't work for you like you mentioned above, it means that there's a module or your theme affect the PS behavior. You should check it out.

> what template if this is my entire problem.

**Your tone is not acceptable!** And it's not the first time that **you don't respect the provided template** when you create a new issue.

It seems that you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
