### ISSUE TITLE
Test your database connection error

### ISSUE THREAD

**Issue by yeojun08** [PrestaShop/PrestaShop#22618]
![Capture](https://user-images.githubusercontent.com/30577018/103287826-e8211300-49fc-11eb-861a-4995b3432cbe.JPG)

i need some expert advise to fix this error

**Comment by hibatallahAouadni** [comment]
Hello @yeojun08 ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by yeojun08** [comment]
Why would i buy a support if this issue is a bug itself in the installation. I already used 3 computers and still have the same issue.

**Comment by yeojun08** [comment]
Or maybe this is coincidence to sell your support plans.

**Comment by matks** [comment]
Hi @yeojun08 as you said:

> i need some expert advise to fix this error

Expert advise is developer advise. Developer time costs money. That is why if you need expert advise you need to pay for it.

This github repository is not a free support channel, it's a place to work together.

We are sure this part of the code is not wrong. We install PrestaShop dozen times a day. So we know the issue comes from your setup. If you need someone to check exactly what is wrong on your setup, you must pay this someone to spend his time looking at your issue.

It does not have to be PrestaShop support plan, you can hire any PrestaShop expert 😉 .
