### ISSUE TITLE
Errors when viewing a order in BackOffice when the language of the order no long exists

### ISSUE THREAD

**Issue by amaurigabriel** [PrestaShop/PrestaShop#22611]
#### Describe the bug

Hi,
If a order has id_lang with a value that do not correspond to an existent language in a shop, I have the same error reported in https://github.com/PrestaShop/PrestaShop/issues/22215. This is an issue if I remove a language, e.g. Even if I do a brand new installation and remove the English language, I can no longer open any of the pre-installed orders in the BackOffice.

#### Expected behavior

The order should assume the default language of the shop if it's language no longer exists.

#### Steps to Reproduce

1. Make a brand new installation
2. Remove English Language
3. Open any of the pre-installed orders

OR

1. Install a new language
2. Create a order with this language
3. Remove the language
4. Open the order in the BackOffice.

**Screenshots**

The same error happen if I click in this new icon of 1.7.7.
![image](https://user-images.githubusercontent.com/1836086/103246301-c3b43080-4941-11eb-946c-c153b4287330.png)

#### Additional information

* PrestaShop version: 1.7.7

**Comment by amaurigabriel** [comment]
The fix I suggested in https://github.com/PrestaShop/PrestaShop/issues/22215#issuecomment-751368329 worked well for 1.7.7 version, but I could not find these files in the repository. Probably this part of the code is already migrated and the issue may already have been fixed?

**Comment by hibatallahAouadni** [comment]
Hello @amaurigabriel 

Thanks for your issue! I managed to reproduce it only with PS1.7.7.0, see the attached screen record below:

https://drive.google.com/file/d/1lpFaymGXXVmsugRFea3yhHsvVr0fcfZU/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

PS: it's a regression! I didn't manage to reproduce it with PS1.7.6.9

Thank you

**Comment by Progi1984** [comment]
Fixed by #22677
