### ISSUE TITLE
Faceted search bad SQL queries

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#22622]
#### Describe the bug

SQL inserts for price index is not type cast correctly. This can cause issues where the inserts break and the module stop working.
This is an example of SQL when trying to index prices
INSERT INTO `ps_layered_price_index` (id_product, id_currency, id_shop, price_min, price_max, id_country)
                     VALUES 
(26,
                        1,
                        1,
                        ,
                        ,
                        21);

#### Expected behavior

the empty values should be 0 or the product should be excluded from the index.

#### Steps to Reproduce

1. Go to faceted search module. 
2. Click on reindex prices
3. See error of failed index build

#### Additional information

* PrestaShop version: 1.7.6.8
* Module version: 3.7.0 
* PHP version: 7.2.x

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

Thanks for your issue :slightly_smiling_face: I encounter this issue with PS1.7.6.9 when I upgrade my FacetedSearch module to version 3.7, and then I added a specific price to a product (which means that the system launchs the reindex prices) :wink: 
See the attached screen record below:

https://drive.google.com/file/d/15qI4fXLZ8C-9Oh87aXB0UYJmhGPCONIR/view

I didn't manage to reproduce it with FacetedSearch v3.5 ( and 3.6).
I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

**PS: I didn't manage to reproduce the issue with PS1.7.7.0 and FacetedSearch v3.7**

Thank you

**Comment by PierreRambaud** [comment]
Could you tell me if https://github.com/PrestaShop/ps_facetedsearch/pull/299 fixes the issue? I don't manage to reproduce the problem but it should work.

**Comment by hibatallahAouadni** [comment]
Hello @PierreRambaud 

Thanks for your PR :1st_place_medal: I tested your PR, I didn't encounter the issue with your fix :raised_hands:
