### ISSUE TITLE
can't find cronjobs module on ps 1.7.7.0

### ISSUE THREAD

**Issue by momo1240** [PrestaShop/PrestaShop#22630]
Hello guys,
I don't know if it is the right place to post my issue. I have with a fresh ps 1.7.7.0 install
I wanted to update my currencies rates automatically. Usually on older prestashop version (I was using ps 1.5.6 )
we used to have an url for that.

On prestashop 1.7.7.0 it says that I have to download cronjobs module.
the issue is that I can't find this module nowhere (defaults modules, addon etc..)

thank you for your help

**Comment by hibatallahAouadni** [comment]
Hello @momo1240 

Please read this [comment](https://www.prestashop.com/forums/topic/1012820-solved-create-a-cronjob-to-auto-update-exchange-rate/?tab=comments#comment-3263631) 
It will helps how to get a cron job setup and make it work with your shop :wink: 

Otherwise, ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers could anyone please help him :pray: thanks in advance :slightly_smiling_face: 


Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by matks** [comment]
Hi, is this the module you search ?

https://github.com/prestashopcorp/cronjobs

**Comment by momo1240** [comment]
thanks for your reply @matks 
yes, but seems not working properly  with the last version of ps 1.7.7.0
to update currencies for example, we used to have the direct url with the key (ps 1.5-1.6). and we just have to add it in our cron jobs and that's it. I don't really understand why we should install this module

**Comment by matks** [comment]
@momo1240 You dont need the module. The URL is still possible to use (but the URL may be different between 1.5 and 1.7). The module only implements the "cron" ability which is to automatically trigger at given time. If you have your own crontab you do not need the module AFAIK
