### ISSUE TITLE
BO ORDER CREATE - Confusing buttons when finishing order

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22644]
### Is your feature request related to a problem?

The wording of buttons when finishing BO order is REALLY confusing and it does other thing as you would think.

### Describe the solution you'd like

Move the buttons and make the wording clearer.

**BEFORE**
![Výstřižek](https://user-images.githubusercontent.com/6097524/103491675-0ab09300-4e26-11eb-92c6-f7c78de94bdb.JPG)

**AFTER**
![proper](https://user-images.githubusercontent.com/6097524/103491677-0c7a5680-4e26-11eb-9385-ba254c327461.JPG)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , do you agree to change the wording, cause it confuses me too :sweat_smile: (specially "Go on payment page to process the payment" ?

**Comment by LouiseBonnard** [comment]
Hi @Hlavtox and @hibatallahAouadni, thanks for the contribution and best wishes for 2021! @Julievrz & @PrestaShop/ux-team, what do you think? Should those buttons be reworded and/or placed elsewhere? 

FYI, here are the current actions triggered by those buttons:

'Send an email to the customer with the link to process the payment' = clicking this button triggers the *backoffice_order* email, sent to the customer so that he/she can complete the payment of the BO-created order > the order still needs to be created in the BO.

'Go on payment page to process the payment' = clicking this button redirects to the FO checkout funnel so that the user can complete the payment of the BO-created order > if the payment is processed right away, it automatically creates the order, if not the order still needs to be created in the BO.

'Create the order' = clicking this button automatically creates this order and adds it to the orders listing in the BO.

You can find the specifications here: https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/orders/orders/Order%20Add/Add%20new%20Order.md#send-an-email-to-the-customer-with-the-link-to-process-the-payment

**Comment by Hlavtox** [comment]
Hi @LouiseBonnard! You too 🎉

> 'Send an email to the customer with the link to process the payment' = clicking this button triggers the backoffice_order email, sent to the customer so that he/she can complete the payment of the BO-created order > the order still needs to be created in the BO.

If I'm not wrong, it behaves differently. When you click it, he receives backoffice_order email, that's correct. 
In that email, there is a link that will throw you to checkout page. You will be logged in, addresses and cart prepared. And you need to finish the order from front office. No need to create in back office.

**Comment by LouiseBonnard** [comment]
Exactly but it might happen at two different moments, that's why I wrote down the order still needs to be created in the BO. 

Indeed, when the merchant is creating the order in the BO and clicks to send an email to the customer, we can assume the customer may complete the payment a few hours/days later. Meanwhile, the merchant should finish creating the BO order.

**Comment by Julievrz** [comment]
Hi @Hlavtox @LouiseBonnard 
I agree that the second wording ("Go on payment page to process the payment") should be reworded. It is not very clear, and kind of repetitive. 
However, I feel like the first wording is quite clear (a bit long though, so I'll try to shorten it) 

What do you think of my suggestion? 

"Send a payment link to the customer" in Admin.OrdersCustomers.Feature 
"Proceed to check out in the front office" in Admin.OrdersCustomers.Feature

**Comment by Hlavtox** [comment]
@Julievrz @LouiseBonnard I think the first one is very confusing too. :-/

“Send an email to the customer with the link to process the payment.”

What do you think this button will do? What I would think - “Create the order and send a link to the customer that will get him to a payment gate, and he will only enter his payment details.

But no, it logs him in, shows him the prepared cart and he needs to finish the order manually....

Anyway! The wordings you suggested are perfect, but I would change “Send a payment link” to “Send prepared order”, wdyt?

**Comment by Julievrz** [comment]
Hi @Hlavtox, thanks for your feedback! I'm not sure "prepared order" is a very common expression. Also, but it might be just me, I feel like it is too close to "prepaid", which I think could lead to some confusion. But I see what you mean. 
I thought of 2 expressions: 
a draft order or a pre-filled order. 
@matks has worked a lot on the Orders page, so I think his opinion will be helpful.☺️

**Comment by Hlavtox** [comment]
@Julievrz Pre-filled sounds good!

**Comment by NeOMakinG** [comment]
https://github.com/PrestaShop/PrestaShop/pull/22888

Here is the PR, feel free to ping me when you validate the wording (used the wording of hlavtox for the momet)

**Comment by Julievrz** [comment]
Hi @NeOMakinG, here is the wording that I validated with @MatShir:

"Send pre-filled order to the customer by email" in Admin.OrdersCustomers.Feature
"Proceed to checkout in the front office" in Admin.OrdersCustomers.Feature
"Create the order" in Admin.OrdersCustomers.Feature

@Hlavtox Thank you for your suggestion and your help on this one! ☺️

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/105044636-3f982900-5a67-11eb-9fb5-82c807dd6cd5.png)
Now the text is way too big

@PrestaShop/ux-team what should I do ?

**Comment by prestascott** [comment]
Hey everyone, 

Thanks @Hlavtox for your request!

By changing the wording it's easier to understand the possible actions. 👍 

@NeOMakinG Text is too big and it might be too big for other languages when we translate the wording. 
I suggest to use a dropdown button instead. It will fix the long text issue but there will be an additional click for our merchants. 

Here is my design proposition:

**Default**
![#22644 default](https://user-images.githubusercontent.com/54888056/105049535-095da800-5a6d-11eb-88d1-36b7258e19c7.png)
**Clicked**
![#22644 clicked](https://user-images.githubusercontent.com/54888056/105049678-35792900-5a6d-11eb-85dd-52c3a807c5ab.png)

Wdyt?

**Comment by hibatallahAouadni** [comment]
@prestascott :clap: brilliant idea :star2:

**Comment by Hlavtox** [comment]
@prestascott Perfect. You're the man!!!
