### ISSUE TITLE
BO ORDER CREATE - Customer search field shows results for all words

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#22652]
#### Describe the bug

When you go to create a new order from BO and you search for customer, it shows results for all words you enter.
You search for John Doe and instead of one or few John Does, it finds all Johns and all Doe. There are billion of results... 

#### Expected behavior

It should search only for the phrase as a whole.

#### Steps to reproduce

1. **BO**>**SELL**>**Customer**
2. Create two customers: "John Smith" and "Sam Doe"
3. **BO**>**SELL**>**Orders**
4. Create Order
5. make a search with "John Doe"
6. See error > there's 3 customers diplayed

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Yes I managed to reproduce it along with these issues #10122 & #15954 with PS1.7.7.0, see the attached screenshot below:

- Guest: **Hiba**tallah Aou**adni**
- Customer: Bipa **Adni**

![image](https://user-images.githubusercontent.com/23308427/103525303-44fa4e80-4e7f-11eb-8a9b-6268a7252c9b.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by sabansen** [comment]
Hi @Hlavtox 

I have also another issue somehow related with this bug, I guess. Won't able to search customers when we're on the new order page.

Not sure but the issue: about routing you may able to see in the screenshot, URL not placing properly and "token" parameter won't set correctly.

![ss](https://user-images.githubusercontent.com/8502105/104458491-c18ddb00-55ab-11eb-9c7a-bdde16500a17.jpg)

System information 
Nginx, Ubuntu
PS: 1.7.7.0

**Comment by orthofoods** [comment]
Hello,

About the first bug, I've solved it by modifying the CustomerController (in src/PrestShopBundle/Controller/Admin/Sell/Customer)

line 413 change  $phrases = explode(' ', $query); in $phrases =[$query];

The problem is that I've to do it for each update. So I'm trying to do a module to decorate the controller, but I'm stuck in a routing problem.

**Comment by matks** [comment]
I add the "Waiting for PM" label so that PM team can tell us if the suggested solution https://github.com/PrestaShop/PrestaShop/pull/26109 is good and well built in their opinion
