### ISSUE TITLE
Error message after successful payment with PrestaShop Checkout

### ISSUE THREAD

**Issue by ludoplt** [PrestaShop/PrestaShop#22680]
Hello, 

After successful payment with CB I got this message : 
"Votre commande n'a pas encore été validée, elle a seulement été créée. Il y a peut-être un problème avec votre paiement ou votre commande sera peut-être enregistrée plus tard. Veuillez contacter notre service client pour plus d'informations. "

Translation : 
"Your order has not yet been validated, it has only been created. There might be a problem with your payment, or your order might be registered later. Please contact our customer service for more information."

At the end, the payment is well done... Why did this message appeared ? Perhaps because of payment secure checks ?

**Comment by ludoplt** [comment]
<img width="1131" alt="Capture d’écran 2021-01-05 à 22 06 58" src="https://user-images.githubusercontent.com/7975284/103698940-6e5fcb00-4fa2-11eb-83ab-4ccfec595fc6.png">

**Comment by SimonGrn** [comment]
Hello,

PrestaShop Checkout is not a part of the Core and issues are not handled here. Please use the contact form you can find in module configuration page > Subtab Help > there is an email address.

Please also think about **following the template** if you need to create a new issue, because this one would have been closed.

Thank you.
