### ISSUE TITLE
Product page - tech/product task - Move classes into the right subdomain namespace

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22700]
As discussed in Slack, we want to move some classes into right subdomains

- [x] AttributeGroup - ✅  https://github.com/PrestaShop/PrestaShop/pull/22722
- [x] Combination - ✅  https://github.com/PrestaShop/PrestaShop/pull/22718
- [x] Customization - ✅  https://github.com/PrestaShop/PrestaShop/pull/22849
- [x] Image - ✅  https://github.com/PrestaShop/PrestaShop/pull/22725
- [x] SpecificPrice - ✅  https://github.com/PrestaShop/PrestaShop/pull/22614
- [x] Pack -  ✅  https://github.com/PrestaShop/PrestaShop/pull/22555
- [x] Stock ✅  https://github.com/PrestaShop/PrestaShop/pull/22745
- [x] Supplier - don't start until @zuk3975 is done
- [x] VirtualProductFile - ✅  https://github.com/PrestaShop/PrestaShop/pull/22726

**Comment by zuk3975** [comment]
> * Customization - don't start until @zuk3975 is done
> *  Supplier - don't start until @zuk3975 is done

related PR https://github.com/PrestaShop/PrestaShop/pull/22703

**Comment by jolelievre** [comment]
@matks about Stock I wonder if it needs a subdomain, it's not exactly like other relations (Combination, Image, ...) which are independent entities

Here we have StockAvailable indeed but I don't know if we should move all the related services into a StockAvailable sub domain, especially since we also have a command `UpdateCombinationStockCommand` so which sub domains would it be related to? StockAvailable or Combination?

For now I moved it into Combination sub domain in this PR https://github.com/PrestaShop/PrestaShop/pull/22718 which makes sense since it's the stock of a Combination. For the same reason I think the stock of a Product should be managed in the Product namespace

There are some elements like `StockAvailableRepository` which are shared by the two domains.. So maybe we should only move services titghtly related to the `StockAvailable` object (like `StockAvailableRepository` and `StockAvailableValidator`) but leave the commands (and handlers) into Product and Combination namespace

Anyway this one needs to wait for the Combination PR to be merged to avoid complicated conflicts

**Comment by jolelievre** [comment]
This is an old technical issue, all the code has been moved a while ago
