### ISSUE TITLE
condition product

### ISSUE THREAD

**Issue by papich06** [PrestaShop/PrestaShop#22719]
I sell reconditioned products

no matter what condition I put on my product with or without variation it is always written "new" on the image even though I have used it

how to do ?

thank you

prestashop version 1.7.7.0
php 7.3

**Comment by florine2623** [comment]
Hello @papich06 ,

The "new" tag on the image is displayed because the product is considered "new" on the shop. But the condition is written on the product detail part :
![Capture d’écran 2021-01-08 à 09 16 18](https://user-images.githubusercontent.com/16019289/103990888-34551b80-5192-11eb-8319-579fc972c8c0.png)

If you don't want the new tag you can change it in Shop Parameters > Product Settings :
![Capture d’écran 2021-01-08 à 09 17 18](https://user-images.githubusercontent.com/16019289/103990999-5fd80600-5192-11eb-8dc3-3aabd0780642.png)

Thanks!

**Comment by papich06** [comment]
Hello @florine2623 
Thanks but if i want change display "new" to another condition like "refurbished" ?
specially for declinaison

can i change for backoffice or bdd ?
Shop Parameters > Product Settings  ??

**Comment by papich06** [comment]
Hello @florine2623 
thank you but the condition of the "new" product is different from its "reconditioned" condition

how to change the label and / or assign and display the good status?
