### ISSUE TITLE
Allow to translate carriers

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#22720]
#### Is your feature request related to a problem?

We have a setup with more than one language and more than one shop. For now, it is not possible to translate the carrier name, only the carrier delay. This is a problem for carrier names that must be translated, like:
*Pickup in the store*, *Priority shipping*

#### Describe the solution you'd like

It should be possible to translate the carrier name.

**Comment by matks** [comment]
Hi, this idea has already been reported and we think it's a great idea 😄  see https://github.com/PrestaShop/PrestaShop/issues/12901

However it will be done only on next major version because it introduces a massive database structure breaking change that will impact all modules using SQL queries related to carrier entity.

**Comment by florine2623** [comment]
Hi @lmeyer1 ,

As your improvement request is a duplicate, I'll close your issue, you can follow the progress here : #12901

Thanks!

**Comment by florine2623** [comment]
Duplicate of #12901
