### ISSUE TITLE
Error in product image thumbnails

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#22729]
#### Describe the bug

product image thumbnails are changed

#### Expected behavior

each item should have the correct thumbnail

#### Steps to Reproduce

**Screenshots**

https://youtu.be/LQ8suielnaI

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2.34
.

**Comment by kpodemski** [comment]
I suggest to clear /img/tmp folder, this should help. Remember about backup first.

**Comment by florine2623** [comment]
Hello @alfonsolr09 ,

Please do as @kpodemski said.
You can also delete cache or login to your BO in incognito mode.

Thanks!

**Comment by alfonsolr09** [comment]
https://youtu.be/B63eo7Oapy4

**Comment by alfonsolr09** [comment]
@florine2623 
@kpodemski 

the same problem in the statistics of the main page, the image is displayed well but the name of the article is displayed wrong, in the green scissors

**Comment by alfonsolr09** [comment]
@ florine2623
@kpodemski 
ping

**Comment by kpodemski** [comment]
It seems like there are some cache issues on your server, have you tried to delete img/tmp folder?

**Comment by alfonsolr09** [comment]
Yes, i tried... The other error disappeared. But this not

**Comment by alfonsolr09** [comment]
Now its with the product tittle... I dont know

**Comment by kpodemski** [comment]
When you open this wrong image in new tab, and add at the end of URL for example ?v=777, do you still see wrong image?

**Comment by alfonsolr09** [comment]
Look the last video. Now its not with pictures. Now its with product tittle.

**Comment by SimonGrn** [comment]
Hello,

looks like your problem is specific to your own environment and is not tied to PrestaShop itself.
You may have some problems with your cache folders, maybe permissions problem blocking the process from emptying them.

Anyway, we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by alfonsolr09** [comment]
I still have not managed to fix this problem. I think it arises when I modify a product that had already been used before
