### ISSUE TITLE
i cant update products

### ISSUE THREAD

**Issue by SisCompufax** [PrestaShop/PrestaShop#22779]
I add products by means of a script which adds the products without any problem.
Then I run a module that I bought (Icecat) which after adding their characteristics and information to the products and not let me update them I get this error in the logs of prestashop and this error in the panel of products of the backend I leave the images
I am using prestashop 1.7.7.0 which is a clean installation that has nothing else installed but the icecat module

products error:
https://drive.google.com/file/d/1KyMbRt3fDDdCQttpFTmj5utj-i3nZ104/view?usp=sharing

prestashop logs:
https://drive.google.com/file/d/1AiT1Igtjsp1u-4AsNxER1gbMs469rRuV/view?usp=sharing

**Comment by kpodemski** [comment]
Hello

Please follow the template to submit a complete bug report and fill the blocks that we provided in the template (describe the bug, expected behavior, steps to reproduce, ..).

Thank you 👍

**Comment by matks** [comment]
@SisCompufax Also if the issue comes while using a module `Icecat` then the issue must be solved in the module, not on PrestaShop. Unless there is indeed a bug, highlighted by this usecase ; but this has yet to be proven.

The best solution is to contact the Icecat module developer, ask him. He will be able to check whether issue comes from his module or the PrestaShop software.
