### ISSUE TITLE
Payment mode needs some adjusts on mobile view

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#22801]
Epic: https://github.com/PrestaShop/PrestaShop/issues/22358 

[Link to Figma prototype](https://www.figma.com/proto/b2sVogt6tyvB5EIkVmTAdP/PrestaShop-Responsive?node-id=608%3A0&scaling=scale-down)

#### Describe the bug

The page a bit broken on mobile 

![image](https://user-images.githubusercontent.com/14963751/104458240-60660780-55ab-11eb-8fd6-a93d5fe075a2.png)

#### Steps to Reproduce

1. Go to Payment Methods
2. See on mobile view (375px)

#### Additional information

* PrestaShop version: develop

**Comment by prestascott** [comment]
Hello,

I reopened this issue because I forgot to add my mockups. Also because there is some adjustments to do on @NeOMakinG's PR.

As you can see on this screenshot below, alerts don't have the same padding left and right than the container above. Alerts must be aligned.
![Capture d’écran 2021-03-01 à 14 06 49](https://user-images.githubusercontent.com/54888056/109501240-a0b81100-7a97-11eb-9de2-bd0f154e1cc3.png)

As you can see on this second screenshot below, text is difficult to read. Split button need to be identifiable at first sight but this isn't the best solution.
![Capture d’écran 2021-03-01 à 14 06 37](https://user-images.githubusercontent.com/54888056/109501373-c9400b00-7a97-11eb-835e-c584deca2c0d.png)

Here is what I suggest to do for "Installed" tab:
![payment methods - installed](https://user-images.githubusercontent.com/54888056/109501519-fbea0380-7a97-11eb-889a-28587718ec12.png)

We can use the same layouts for "Not installed" tab:
![payment methods - not installed](https://user-images.githubusercontent.com/54888056/109501641-2d62cf00-7a98-11eb-98f2-ede1bd35b0c3.png)
