### ISSUE TITLE
1.7.7.1 Back office Shopping Cart browsing causes "Type error: Return value of CartCore::getCartPriceFromCatalog()"

### ISSUE THREAD

**Issue by devonto** [PrestaShop/PrestaShop#22812]
#### Describe the bug

Searching and viewing shopping carts in the back office produces an "unexpected error" screen.
As previously reported yesterday on the closed report #22784

> Oops... looks like an unexpected error occurred.
> 
> Type error: Return value of CartCore::getCartPriceFromCatalog() must be of the type float, null returned
> 
> [Symfony\Component\Debug\Exception\FatalThrowableError 0]

#### Expected behavior

Should be able to search and open shopping carts

#### Steps to Reproduce

1. Within back office, click on Orders -> Shopping Carts
2. Search by name for some customers
3. Error will not always appear (may be historical order-content specific?)

**Screenshots**

![image](https://user-images.githubusercontent.com/6807236/104474188-aaec8180-55b5-11eb-970c-30411260c7a6.png)
![image](https://user-images.githubusercontent.com/6807236/104475197-b7250e80-55b6-11eb-9844-930a859a3e9a.png)

#### Additional information

* PrestaShop version: 1.7.7.1 (just upgraded)
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @devonto 

I reproduced your issue with PS1.7.4.1 upgraded to 1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/12yb3NNec-sTPrRr4fxSID-9FOYpo_ldT/view

And it's a regression cause I didn't managed to reproduce with PS1.7.4.1 upgraded to 1.7.7.1, see the attached screen record:

https://drive.google.com/file/d/1JLebQKa9Qqq2H7eIKK6ci2I2MMr2ht8h/view

While with fresh install PS1.7.7.1, I didn't manage to reproduce it too, see the attached screen record below:

https://drive.google.com/file/d/1n4Ip5D9fWo8065mLC9RZmepGBlysk11A/view

Thanks for your issue. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by alfred2016decanet** [comment]
Hi I have exactly same error, on multishop product, to view order details, customer etc... this is very ambarassing :(

**Comment by 4ngeluxpunk** [comment]
Hello I have the same error in several stores with version **1.7.7.0** and **PHP 7.3**, this error is generated when in the prefix_cart table the **id_currency column is 0**; Rather, the cart orders should be entered the id_currency by data 1 which is the ID of the currency but enter it with 0

**Comment by Progi1984** [comment]
Fixed by #22947
