### ISSUE TITLE
Autoupgrade not available or gives error

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#22819]
In Addons 1-click upgrade is not available. The page is there nut you cannot download anything.

Using PS 1.7.6.1 I have version 3.0.3 of 1-click upgrade. When I click on the Upgrade button I get an error message and nothing is upgraded. 

So I went to Github and downloaded the latest version (4.11.0) there. But when I try to install it I get an error. See the attached image.
![upgrade](https://user-images.githubusercontent.com/13930107/104482036-be541880-55c6-11eb-88d4-f63c704553a7.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

> So I went to Github and downloaded the latest version (4.11.0) 

All right, first of all you need to execute these commands:

```
git clone https://github.com/PrestaShop/autoupgrade.git
cd autoupgrade
composer install
```

When the composer finish its work, compress the autoupgrade file and then you can install it :wink: 
Hope it helps and please next time **follow the template to submit a complete bug report**.

I'm closing this issue cause it's not related to PrestaShop Core.
Keep in mind that I'm always available to answer all questions even the issue is closed :wink: 

Thanks!

**Comment by musicpanda** [comment]
This is ridiculous:
 - there is no Issues tab with the autoupgrade module
 - If you miss anything tell it. This reference to the template looks childish.
 - I refuse to use Composer. Things should work on my Windows pc. 
 - The forum is full of people having problems upgrading to 1.7.7. This isn't a problem that can be isolated from the Core.

**Comment by hibatallahAouadni** [comment]
> This is ridiculous

This tone is not acceptable.
> This reference to the template looks childish.

You should respect the provided template, we made it to help you resolving your issue ASAP.

> The forum is full of people having problems upgrading to 1.7.7.

We already aware of this issues and we are working on it.

About your issue, the problem is when I open my shop 1.7.6.1 and go to Module Catalog, I found the 1-Click Upgrade v4.11.0
So, I can not reproduce your issue, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/104496318-1a279d00-55d9-11eb-87b4-d98317fa71a4.png)

Thanks!

**Comment by musicpanda** [comment]
If I click that button in your image while version 3.0.3 is installed I get an error - just like when I upgrade the module in Modules.
![upg3](https://user-images.githubusercontent.com/13930107/104509062-6da1e700-55e9-11eb-8988-1036031714c0.jpg)

Mostly I use another path - the button on the side. It brings me to the 1-click upgrade page in Addons
![upg2](https://user-images.githubusercontent.com/13930107/104509197-9c1fc200-55e9-11eb-956b-25b78e9d8af7.jpg)

Until recently that page didn't contain a link. Now it does contain a link. But it also contains the price of 899 euro. 
![upg1](https://user-images.githubusercontent.com/13930107/104509385-e30db780-55e9-11eb-9a8e-9e2822932c21.jpg)

"You should respect the provided template, we made it to help you resolving your issue ASAP."
Obviously you didn't miss any information. Otherwise you would have mentioned it. I am puzzled why someone with such a bureaucratic attitude works at a software company.

**Comment by matks** [comment]
Hi @musicpanda, we do have a [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/63ab23f170875f63e2fa8b3149db4fb00c81ae0d/CODE_OF_CONDUCT.md) in this area.

Your current tone is not compliant with the Code of Conduct, see:
> Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members

The statements "This is ridiculous" or "I am puzzled why someone with such a bureaucratic attitude works at a software company." are not "welcoming and inclusive language respectful of differing viewpoints and experiences".

Please stop using this tone and adopt a better attitude 😊 so that we can focus on the issue content and work on what is best for the community or the project. An opensource project is a a place for collaboration. Collaboration cannot happen between people when sentences like "It's ridiculous", "It's bureaucratic", "It's childish" or "I refuse to use Composer". Disagreeing is possible but without harsh adjectives.

**Comment by musicpanda** [comment]
Hello Matks,

I admit. I am guilty. I only make an exception for the Composer issue. I think you are wrong there. When working with Composer becomes a requirement for using Prestashop 95-99% of the users will stop using it.

But I hope you will also look at the other side of the picture:
 - I submit a serious issue that concerns many people. It is closed unsolved.
 - I get feedback about the Upgrade module that is plainly wrong. 
 - I like to "focus on the issue content". My issue is that the reactions that I get don't focus on the issue content. I am treated with vague words that only serve as an excuse to close the issue without changing anything. To call that kind of reaction "respectful" stretches the meaning of that word. 
 
In the meantime you still get this empty screen when you look for the upgrade module on Addons:
![upg3a](https://user-images.githubusercontent.com/13930107/104511776-86140080-55ed-11eb-9d7e-98a18c51ddd5.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

Did you try to uninstall the 1-click upgrade from the Module Manager page and then install it again from the Module Catalog page?

Please check and feedback.
Thanks!

**Comment by matks** [comment]
> I admit. I am guilty. 

No worries, it happens 😄  we know sometimes the frustration is too high and we are all humans here.

> I only make an exception for the Composer issue. I think you are wrong there. When working with Composer becomes a requirement for using Prestashop 95-99% of the users will stop using it.

We are making it more and more mandatory to use Composer because in 2021 it becomes hard to be able to stay relevant with PHP ecosystem without using it. If you want to contribute to the Core or to some modules like ps_facetedsearch it is really mandatory. But I don't think it's so complex? 😊  For me git is a lot more complex than Composer. Composer is mostly `composer install` and `composer update` ? It's not something to be afraid of I think. If you check it a bit you will see it can look scary but actually it's very simple under the hood.

> * I submit a serious issue that concerns many people. It is closed unsolved.

Issues can be closed and reopened 😄  it's just a way to manage our backlogs. When an issue status is "not eligible" it's closed, else it's kept open. But we attempt to avoid staying in-between. It might be frustrating for the issue author but remember people are using issues to work 😉  they look for bug reports, feature requests, tracking the history. Closing the issues we think are not relevant is a way to make sure when people search inside "open issues" they find a result as relevant as possible. Closing an issue is not a "no we don't want to hear about it" statement it's just a status we toggle 😄 . 

Imagine tomorrow you browse github issues because you want to find some infos in it, and you get some results but they are actually bad bug reports: you have wasted your time! So we keep open only the reports we can guarantee (and reproduce).

> * I like to "focus on the issue content". My issue is that the reactions that I get don't focus on the issue content. I am treated with vague words that only serve as an excuse to close the issue without changing anything. To call that kind of reaction "respectful" stretches the meaning of that word.

We are not in your head 😅  this is why we do not know whether yes, the issue you report is good, or no, there is actually no issue but rather a little mistake on your side. Sometimes (often actually) we have people telling us "X is broken" and when we explore with them what they have done, we find out they did not know how to use X properly so they thought it was broken. This is why we have some "basic" checks and hints, because this is what quite a big portion of GitHub messages actually need.  You would be surprised 😄  try having a look at the other closed github issues, we have some... raw requests / bug reports.

**Comment by matks** [comment]
Now I think I remember something similar. https://github.com/PrestaShop/PrestaShop/issues/22399 mentions the same error message I believe `Call to private method Autoupgrade::registerHookAndSetToTop() from context`

OK so I check https://github.com/PrestaShop/PrestaShop/issues/22399 deeper and it might mean that the **autoupgrade module is unable to upgrade itself because of this issue**. So what you can do is
- uninstall current autoupgrade module 3.0.3 on your shop
- install directly autoupgrade module 4.11.0

This should work.

**Comment by musicpanda** [comment]
Thank you for reactivating #22399

I understand that you get a lot of error reports where the reporter made some mistake. However, my feeling is that you have gone a bit too far in rejecting everything that doesn't immediately click.

Take the fact that both people who investigated my report did it by compiling a module with composer and then installing it as a new module. It shows them far out of touch with the common user that will never work this way. It also shows that Prestashop doesn't have permanently a couple of workstations ready with standard installations where this kind of things can be tested from the user perspective. 

When I look at case #22399 I see another disturbing pattern. There is an error message and there is a problem with the visible version not matching the supposedly real version but the conclusion is that it works and that thus it is ok. Debug mode isn't activated to see what the error message says and it looks like the check on the quality of the upgrade is very superficial too. That is not the way I am used to making software. For me both these things would be signals that something is wrong and I would like to know what is going on that produces these effects. It might be harmless but it could also be symptoms of serious problems. 

So my impression is that the way error reports on Github are handled at Prestashop is rather seriously broken.

**Comment by PierreRambaud** [comment]
> Thank you for reactivating #22399
> 
> I understand that you get a lot of error reports where the reporter made some mistake. However, my feeling is that you have gone a bit too far in rejecting everything that doesn't immediately click.
> 
> Take the fact that both people who investigated my report did it by compiling a module with composer and then installing it as a new module. It shows them far out of touch with the common user that will never work this way. It also shows that Prestashop doesn't have permanently a couple of workstations ready with standard installations where this kind of things can be tested from the user perspective.
> 
> When I look at case #22399 I see another disturbing pattern. There is an error message and there is a problem with the visible version not matching the supposedly real version but the conclusion is that it works and that thus it is ok. Debug mode isn't activated to see what the error message says and it looks like the check on the quality of the upgrade is very superficial too. That is not the way I am used to making software. For me both these things would be signals that something is wrong and I would like to know what is going on that produces these effects. It might be harmless but it could also be symptoms of serious problems.
> 
> So my impression is that the way error reports on Github are handled at Prestashop is rather seriously broken.

Hey, if you think something is broken, please take time to investigate issues (https://github.com/PrestaShop/PrestaShop/issues we have a lot of them that are waiting for investigation) and help us to make it better by giving us everything we need to fix it faster :muscle: 
Don't forget this is an open source project and we are open for help :heart:

**Comment by musicpanda** [comment]
> Hey, if you think something is broken, please take time to investigate issues (https://github.com/PrestaShop/PrestaShop/issues we have a lot of them that are waiting for investigation) and help us to make it better by giving us everything we need to fix it faster 💪
> Don't forget this is an open source project and we are open for help ❤️

I have tried several times to do that and my experience is that it is a hopeless endeavor. Maybe one in ten proposals will be approved and the quality of the rejections is depressing. So I have decided that I can contribute more to the Prestashop community by maintaining and expanding the tools I support ([Prestools](https://www.prestashop.com/forums/topic/1011667-free-script-prestools-suite-mass-edit-order-edit-and-much-more/) and [Copy_shopdata](https://www.prestashop.com/forums/topic/445453-copy-shopdata-script-for-copying-shop-content-for-upgrade/)) and giving some support on the forum. 

So now I restrict myself to reporting issues that run into while working with Prestashop.

**Comment by matks** [comment]
> So my impression is that the way error reports on Github are handled at Prestashop is rather seriously broken.

> the quality of the rejections is depressing.

@musicpanda Telling people on the internet "eyh, the quality of your work is depressing" or "eyh, your process is rather seriously broken" is not going to boost their motivation to look at the topic you bring on the table. Actually it will rather do the opposite : people will start to ignore you or block you.

It seems you are trying to tell us about real issues, but if you keep wrapping the topic in passive-aggressive statements like "the quality of rejections is depressing" nobody will listen to you.

So let's please resume to actionable and workable topics without the harsh words. It's not hard. You can say "the process can be improved" instead of "the process is broken" => same concept, very different words, very different impression on the other side of the table. 😉 

Remember that this is an open source project: a lot of people are working on this github repository _for free, on their own time_. Avoiding unnecessary harsh words is a little thing to do to thank them for what they do. Feedback is welcome but it can be written in a not-aggressive way 😉 .

**Comment by musicpanda** [comment]
@matks Look at the (lack of) arguments with which my error report above was closed. Can you imagine this was quite depressing - given that I had invested quite a bit of time in it. 

Consider also what would have happened if I had not just reported the bug but also added code how things could be fixed (this would be as far as I go - I don't do Github submissions). My report would still have been rejected - given that it was claimed that there was no problem. And I would have wasted even more time.

Or consider another case. I recently posted in the comment section of PS post about quality control that it might help to improve error messages too and I offered one concrete example where an error message "missing locale nl-NL" could have been replaced with something like "missing nl-NL translation for currency with id=2". You answered that I should have submitted a concrete suggestion for improvement. But this is a much wider problem and in that context one has to wonder whether there is a Prestashop policy that favors short error messages. In that case me proposing a change would be pointless. Neither did you address the problem of the mysterious word "locale" - what quite likely is a mistranslation of the word "translation" by someone for whom English isn't the mother language. How could this pass any form of quality control and how many similar cases are there? But there seems to be a big taboo on discussing any kind of meta-issues.

I found this treatment condescending. My major issue - quality control - was ignored and I was lectured on something that I had only used as an example.

I am good in the kind of quality control that focuses on finding bugs and getting stable software. And from that point of view I am rather horrified to see how signs of instability are ignored at Prestashop. I have given several examples above. 

You several times encouraged me to look at the list of Github issues and investigate some of them. I am not interested. My focus is on the issues that I encounter. And I think that that is in the interest of everyone as I know them already.

I get the impression that the people at the Prestashop organization see user contributions as a kind of honey pot. They will use what comes handy at the moment. And they will be happy to haughtily reject the rest.

**Comment by matteolavaggi** [comment]
LOL. 

From the prestashop "official" documentation:

Database upgrade
Once the files have been copied, your shop database is ready to be upgraded.

Some web hosting providers gives you two user accounts to access your database. One with full privileges the other for using in scripts with limited rights. To be able to use this Database upgrade script you have to use the account with full privileges.
All the changes to apply have been defined in the install folder, running them can be done with a specific PHP script.

When you’re ready, run the file upgrade/upgrade.php from the autoupgrade module.

This can be done with a browser, by reaching the address http://<shop_domain>/modules/autoupgrade/upgrade/upgrade.php, or from your server’s command line:

php modules/autoupgrade/upgrade/upgrade.php
In both cases, an XML log will be displayed. The result can be found in the attribute result of the first tag <action>:

ok if updates have been found and executed
error if something went wrong
info for next actions, displaying the details on the process


____________________________________

autoupgrade modules is not distribuited in the "official" git repository ^^ it's missed from the module folder ^^ LOL

**Comment by kpodemski** [comment]
@matteolavaggi 

> autoupgrade modules is not distribuited in the "official" git repository ^^ it's missed from the module folder ^^ LOL

What do you mean exactly? https://github.com/PrestaShop/autoupgrade/releases/tag/v4.15.0

**Comment by matteolavaggi** [comment]
Very simple, read the official guide, after copy new file to old folder you
need to run the autoupgrade script... That is missed from the repository ^^
!

Il Gio 5 Gen 2023, 10:46 Krystian Podemski ***@***.***> ha
scritto:

**Comment by kpodemski** [comment]
The documentation .needs to be updated. I'm going to update it as soon as possible. I didn't get that you meant the file. I thought you couldn't find a module :)

**Comment by matteolavaggi** [comment]
Not bad, in perfect prestashop style, one of the most sensible and
important feature ... not work and has a wrong documentation ^^ it's only
the way to update the store , not so important ... Btw ... Or not? LOL.

Il Gio 5 Gen 2023, 11:06 Krystian Podemski ***@***.***> ha
scritto:

**Comment by kpodemski** [comment]
There are other ways to upgrade your store. 

https://build.prestashop-project.org/news/2023/core-monthly-2022-12-01-2022-12-31/#autoupgrade-module

I just wanted to let you know there's no need to be sarcastic there. It's an open-source project. If you notice some errors in the documentation, you have all the tools available to suggest improvements. Project members are not your employees.

**Comment by matteolavaggi** [comment]
For sure, my employee take a complete different level of care of business
they own ;)!

And we all need to be sarcastic, there is no other way to approach this
project, is the most impressive collection of bad management, bad
programming and far-fetched bugs I've ever seen. For thus reason we are
left with sarcasm ^^. In the past 10 years I've have never seen a single
one prestashop release with the ability to be updated without problem. No
one ^^! Thanks btw for your time.

Il Gio 5 Gen 2023, 13:41 Krystian Podemski ***@***.***> ha
scritto:
