### ISSUE TITLE
After upgrade to 1.7.7 clicking on some orders in BO result in a symfony error - OrderMessageForViewing construct must be of the type string, null given

### ISSUE THREAD

**Issue by LeLeCS** [PrestaShop/PrestaShop#22862]
#### Describe the bug

**All old** orders (details) can be opened without problem from BO, while **some** new orders opened with this error, while their invoices opened fine. Some new orders can be opened normally, no error.
Have a net installation of PS 1.7.7.0 firstly, then manually one by one import webfiles and sql data from PS 1.6.1.24, all work fine but this error appeared. Clicking some orders made under PS 1.7.7, error received: Argument 2 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderMessageForViewing::__construct() must be of the type string, null given, called in /home/***/***/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 646

1 click update from 1.7.7.0 to 1.7.7.1 does not fix this error.

#### Expected behavior

All orders (detailed page) can be opened without error.

#### Steps to Reproduce

1. Go to 'BO'
2. 'Select orders from the left pane'
3. Click on some orders to see their details

**Screenshots**
![error](https://user-images.githubusercontent.com/77522120/104797685-06f41780-57fb-11eb-99c0-269e0d4455eb.jpg)
![error2](https://user-images.githubusercontent.com/77522120/104797690-107d7f80-57fb-11eb-9e80-7950f1bc1cdb.jpg)

#### Additional information

* PrestaShop version: 1.7.7.0 & 1.7.7.1
* PHP version: 7.3.25

**Comment by hibatallahAouadni** [comment]
Hello @LeLeCS 

Could you please check these issues, it seems similar to your #22386 & #22611
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @LeLeCS ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by bastienuh** [comment]
Hi @hibatallahAouadni,
Unfortunately, this is not the same issue : here, we talk about **OrderMessageForViewing**.

#22386 is about `OrderShippingAddressForViewing`
#22611 is about address and language, but I only have one language is my shop, with id_lang = 1 everywhere, and we talk here about message, not address.

Moreover, everything was working very fine since yesterday on 1.7.7.2. I made an upgrade on 1.7.7.4 and this bug appears on some orders...

I can see the preview without any problem :
![Capture d’écran 2021-05-26 à 10 48 13](https://user-images.githubusercontent.com/1685778/119631289-081ffb80-be10-11eb-84ef-4249adabda93.png)

But when I want to open the order detail page I have :
```
Type error: Argument 2 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderMessageForViewing::__construct() must be of the type string, null given, called in /home/paniersakk/psj-v17/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 684

[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```

**Comment by LauraMingues** [comment]
Hi @bastienu, 

I have exactly the same error. Did you find any solution ? 

Thank you

**Comment by PubliAlex** [comment]
Same problem here, any fixes to this issue ?
