### ISSUE TITLE
Different domain for different languages

### ISSUE THREAD

**Issue by ruchus** [PrestaShop/PrestaShop#22866]
#### Is your feature request related to a problem?

We're planning to migrate to Prestashop from Magento because magento is so complicate and a lot of features we don't need. In addition, in spain is easyer find PS experts than no for magento and we think it can be useful and good because we need to customize a lot.

But, is mandatory for us to use different URLs for different languajes. It's good for SEO and to increase confidence to customers.
Examples: 
  - www.mydomain.es/es SPANISH
  - www.mydomain.fr/fr FRENCH
  - www.mydomain.de/de DEUTCH
  - www.myitaliandomain.it/it ITALIAN
  - www.myotherdomain.pl/pl Polish

We think it's a MUST BE feature for large and serious ecommerce platforms and it would have to be in the PS core.

#### Describe the solution you'd like

Until this feature won't be on PS we can't migrate.

#### Additional context

The best place to put the new URL input would be:
![imagen](https://user-images.githubusercontent.com/6729380/104827879-258df900-5863-11eb-9103-b5fa71b1eea6.png)

**Comment by hibatallahAouadni** [comment]
Hello @ruchus 

Thanks for the suggestion, the Product Team will take a look.
Please stay tuned !

Ping @PrestaShop/product-team , do you think it's a doable to add the domain management in PS? I think you can manage all your domains only server side :confused:

**Comment by marionf** [comment]
Hello @ruchus 

You can use the multistore to do that and create a shop by language :)

Furthermore, there are some modules allowing to do that: https://addons.prestashop.com/fr/recherche?search_query=language%20par%20domaine

Regards

**Comment by ruchus** [comment]
Hello @marionf 

A feature like that would be have in PS core. Not as extension.
Pay for everything..... too much. On Magento is in the core.

Regards,

**Comment by ttoine** [comment]
Hello, well, I wish you success for your migration to PrestaShop. Welcome in the ecosystem.

PrestaShop is open source, so, your contribution of this feature to the core is very welcome and will be a nice addition for many merchants.

That said, PrestaShop and Magento are both open source ecommerce solutions. But they also are very different software, so of course, features are different. If PrestaShop had all the features of Magento, it would have the same complexity, so maybe you would not considerate a move from Magento to PrestaShop. That's also because PrestaShop is more easy to use that it is faster to get ready, faster to make custom developments, and cheaper to make a project with it (buying modules and development from expert included).

Paying a module something like 100€ to get the required feature will actually save you a lot of time. So, don't forget to compare the time you spend on development of your shop project, and the cost of a cheap module ready to use. That's, btw, how the ecosystem of all open source CMS is sustained.

**Comment by ruchus** [comment]
Hello @ttoine ,

A module that performs the complete rewriting of the URL in all the requests of all the store urls can generate security and performance doubts when acquiring it. I repeat, I think it is a very core functionality, not a module.

I think including this in the PS core can make it more attractive and attract more users who need multi-domain per language.

**Comment by marionf** [comment]
@ruchus 

It's already possible without module by using the multistore feature

**Comment by ttoine** [comment]
@ruchus note that if the default feature to do that is not enough for you, then, please, your contribution is welcome. We are waiting for your pull request.

the roadmap of the project is created after interviews with merchants and their techs. and this need you have is a custom need for you, or other companies migrating from Magento. That's why this is available in third party module.

Now, as @marionf told you, please check how PrestaShop is working on this very topic. It does the job already with multistore.
