### ISSUE TITLE
[UI-KIT] - bad display on switch button

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#22873]
#### Describe the bug

There is a " * " before label of every switch button and sometimes there is a bad alignment 

#### Steps to Reproduce

1. Go to BO
2. Click on preferences (or another page with switch)
3. See error

**Screenshots**

<img width="1440" alt="Capture d’écran 2021-01-15 à 10 36 51" src="https://user-images.githubusercontent.com/3034677/104900431-5a41a380-597c-11eb-9fd6-d81b152b1e32.png">
<img width="1440" alt="Capture d’écran 2021-01-15 à 10 38 37" src="https://user-images.githubusercontent.com/3034677/104900459-5f065780-597c-11eb-9506-79ae5a176116.png">
<img width="1440" alt="Capture d’écran 2021-01-15 à 10 39 01" src="https://user-images.githubusercontent.com/3034677/104900465-60d01b00-597c-11eb-8e71-9c05700d469a.png">

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by NeOMakinG** [comment]
Can't reproduce on develop after `rm -rf node_module && npm i && npm run build` inside new-theme folder of the BO

![image](https://user-images.githubusercontent.com/14963751/105011358-27131900-5a3d-11eb-99ca-20b4f76afd12.png)

**Comment by hibatallahAouadni** [comment]
Hello @sarahdib 

I didn't manage to repdouce your issue with develop, see the attached screenshots below:

- **BO**>**CONFIGURE**>**Shop Parameters**>**General**

![image](https://user-images.githubusercontent.com/23308427/105481460-5dec6780-5ca7-11eb-859d-10669c3ae415.png)

- **BO**>**CONFIGURE**>**Shop Parameters**>**Customer Settings**

![image](https://user-images.githubusercontent.com/23308427/105481515-752b5500-5ca7-11eb-9536-65d5c9808dbf.png)

- **BO**>**CONFIGURE**>**Shop Parameters**>**Traffic & SEO**

![image](https://user-images.githubusercontent.com/23308427/105481578-8bd1ac00-5ca7-11eb-9276-6aeadc2230bc.png)

I think you just had a problem with cache (I didn't even need to clear cache neither execute @NeOMakinG cmd).
Please check and feedback.

Thanks!

**Comment by NeOMakinG** [comment]
I think the star needs to be after the label isn't it?

**Comment by hibatallahAouadni** [comment]
@NeOMakinG well I think so :sweat_smile:
Ping @PrestaShop/ux-team where should the star be? after the label or before the label?

**Comment by NeOMakinG** [comment]
And @PrestaShop/ux-team should we align labels on the right instead of left ? It was right on 1.7.7

**Comment by prestascott** [comment]
Hello everyone,

Red asterisk position choice doesn't really make a big difference. Putting it before the label makes it more identifiable and will be more useful for longer label because it will always appear on the first line.
Putting the red asterisk at the end of the label is still easy to identify because it's red, as long as it's not too small.

I will keep the red asterisk at the beginning of the label but I recommend to put a space in between. Also, it will be easier when we need to add a tooltips at the end of the label name, it won't be "packed" on the right side. 

To keep consistency, I will align labels on the right instead of left. :)

**Comment by NeOMakinG** [comment]
I did the PR
