### ISSUE TITLE
Rolling back upgrade not possible

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#22961]
#### Describe the bug
A few days ago I upgraded a fresh 1.7.7.0 shop to 1.7.7.1. I got all kinds of problems and decided to roll the upgrade back. This resulted in errors:
 - [INTERNAL] /var/www/vhosts/kohbaba.com/httpdocs/classes/shop/Shop.php line 346 - Invalid argument supplied for foreach()
 - [INTERNAL] /var/www/vhosts/kohbaba.com/httpdocs/config/config.inc.php line 122 - Error: Call to a member function getName() on null #0 /var/www/vhosts/kohbaba.com/httpdocs/modules/autoupgrade/classes/UpgradeContainer.php(550): require_once() #1 /var/www/vhosts/kohbaba.com/httpdocs/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #2 /var/www/vhosts/kohbaba.com/httpdocs/adminpiet/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() #3 {main}

A look at the database learned that it didn't go further then ps_product_lang. This looks like a timeout problem.

#### Expected behavior

a rollback 

#### Steps to Reproduce

![error](https://user-images.githubusercontent.com/13930107/105606108-aaaf6b80-5d97-11eb-9ce7-e23f8eae0a07.jpg)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0/1.7.7.1
* PHP version: 7.2.31

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

As you can see in my screen record below, I upgraded my shop from 1.7.7.0 (fresh install) to 1.7.7.1.
The upgrade process was successful: 

https://drive.google.com/file/d/1H7A2zThw5ezAiol9u2M90SIarL67jv7k/view

Then, I tried to roll back and I encountered another issue (not like yours), even though that I already check these rollback options:

![image](https://user-images.githubusercontent.com/23308427/105713627-a90eb080-5f1b-11eb-9bc8-19ca3328fae3.png)

ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

---
**Edit:** I refresh the page again and I saw that the shop already is rollback to 1.7.7.0 :open_mouth: 
I don't know why the system display this error.

Ping @PrestaShop/prestashop-core-developers any idea why I get this error?

Thanks!

**Comment by musicpanda** [comment]
Thank you for your reaction.

There were two signs of instability that made me choose to roll back:
 - when I got the "invalid sign. This may be a security risk" page nothing happened when I clicked the "yes, I understand the risks" button. The only way to go further was changing the url by removing the token part of it. After a day or so this problem disappeared.
 - the second issue was that I couldn't search in the Module Manager.

In both cases I checked for javascript errors but didn't find any.

I solved the issue by copying the missing tables from a backup installation.

**Comment by musicpanda** [comment]
One possibility is that the issue concerned the browser cache and that refreshing  (ctrl-F5) might have helped. It is just speculation and I can't test it. But it matches the symptoms.

**Comment by kpodemski** [comment]
I'll close this ticket since the rollback feature is now automatically tested in the module. Also, I hope that one day we will remove it since the backup and rollback should be a job done outside of the upgrade tool for performance reasons.
