### ISSUE TITLE
Dashboard stats error 1.7.7.0

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#22973]
Hi,

When we try to compare a date period in the dashboard stats, it's not possible to open the dropdown list to choose what we want to compare it with.

We then get the error message "The selected period is not valid".

Thanks

![Screen Shot 2021-01-18 at 16 37 26](https://user-images.githubusercontent.com/71735/105688390-73ed6880-5ef1-11eb-8e53-a48908d4a562.png)
![Screen Shot 2021-01-18 at 16 37 34](https://user-images.githubusercontent.com/71735/105688395-751e9580-5ef1-11eb-9232-04ff8b629af8.png)

**Comment by hibatallahAouadni** [comment]
Hello @ced--ced 

I was able to reproduce the issue with PrestaShop version 1.7.7.0, 1.7.7.1 and develop, see the attached screen record below:

https://drive.google.com/file/d/1xk4Kq2WNpxOXjaNKVkBr0dNcixGc6DSY/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

**PS:** it's a **regression**! I didn't reproduce it with **1.7.6.9**, usually when we check the "Compare to" checkbox, the select becomes enabled and the "From - To" selects appear :confused: 

Thank you

**Comment by Progi1984** [comment]
Fixed by #22997
