### ISSUE TITLE
Notice: Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46'

### ISSUE THREAD

**Issue by krausik002** [PrestaShop/PrestaShop#22989]
Hello! 
When i do a new order in my e-shop, i will have this problem... 
Can you help me with this? 

![objednávka](https://user-images.githubusercontent.com/77977890/105734298-c56a1780-5f32-11eb-870f-2f4a1afbdbd7.png)

**Comment by matks** [comment]
Hi @krausik002 this is probably because your ICU version on your environment is too old (see for example https://github.com/PrestaShop/PrestaShop/issues/22300 same root cause, different behavior). You need to update your ICU version

**Comment by krausik002** [comment]
Where I will update ICU? Webhosting or where?

**Comment by hibatallahAouadni** [comment]
Hello @krausik002 ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the
[public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: please next time respect and follow the provided template to submit a complete bug report! and fill all the provided blocks (describe the bug, expected behavior, steps to reproduce, PrestaShop version, PHP version, ...) we need these infos to help you :wink: 

Thanks!

**Comment by simbus82** [comment]
> Hi @krausik002 this is probably because your ICU version on your environment is too old (see for example #22300 same root cause, different behavior). You need to update your ICU version

I have a PHP 7.3 with old ICU and php 7.4 with supported ICU.

It's a standard CPanel/Cloudlinux server with the famous PHP Selector and EasyApache 4.
PHP 7.3 is compiled with an ICU <4.6, why Prestashop did this thing?
90% of PHP 7.x early adopter have ICU <4.6.

And this in not mentioned in requirements, and we don't see any warning during installation.

Now i have a shop with 1.7.7.1 that i can't login to Backend if i have PHP 7.3 (old ICU) and out customer can't register when, to let me access to BO, i switch to PHP 7.4 (new ICU).

Any workaround that not is the recompile of a production stable PHP 7.3?
