### ISSUE TITLE
Product Location is stored in 2 places (and only pulled from one in the BO)

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#23008]
#### Describe the bug

The product location is stored in both: `ps_product_attribute` and `ps_stock_available`
but in the BO only pulled from ps_stock_available

This should not be the case, it should be stored in a single table.

#### Expected behavior

This should not be the case, it should be stored in a single table.

#### Steps to Reproduce

1. Save a location for a product (with a combination)
2. Search for that location in the database and you will find 2 entries

Which will remain?

**Screenshots**

![image](https://user-images.githubusercontent.com/3520123/105985169-6a076900-609b-11eb-8f54-c65f0cea9fe0.png)

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @sickboards 

Could you please provide screenshot or screen record?

Thanks!

**Comment by sickboards** [comment]
![image](https://user-images.githubusercontent.com/3520123/105985169-6a076900-609b-11eb-8f54-c65f0cea9fe0.png)

**Comment by hibatallahAouadni** [comment]
Hello @sickboards 

OK I can see that this attribute `location` exist in both tables `ps_product_attribute` and `ps_stock_available`:

![image](https://user-images.githubusercontent.com/23308427/106020108-b1095480-60c3-11eb-9329-1aff3a5c5af7.png)

But, where is the bug?? being saved in both tables does it throw any error?
Please check and feedback.

Thanks!

**Comment by sickboards** [comment]
A variable should only exist in one table (unless it is a key)
The location variable in ps_product(_attribute) is not being used
so why is it there?
Why store the same data on 2 locations?

**Comment by hibatallahAouadni** [comment]
Hello @sickboards 

Well you're right, let's ask the Developer Team :wink: 
Please stay tuned!

Ping @PrestaShop/prestashop-core-developers any idea why this attribute `location` saved in both tables?

Thanks!

**Comment by jolelievre** [comment]
Hi @sickboards,

these two fields are quite old so the current didn't introduce them but we encountered the same questions as you recently while we are working on the migration of the Product page. The location field had disappeared for a time in the 1.7 version, it was reintroduced in 1.7.5 but was stored in the `StockAvailable` object because it is related to the location where the product is stored in the warehouse.

Though we couldn't remove the existing location fields in Product and Combination, so although they exist in database they are not used any more and are filled with the value from StockAvailable. In the coming 1.7.8 version we are officially going to deprecate them as they shouldn't be used any more, we only keep them for backward compatibility.

In the next major version of PrestaShop though, since they are deprecated fields they will be completely removed. Besides thanks to your reminder we noticed that we forgot to mark these fields as deprecated in the `develop` branch, we are creating a PR to fix this.

**Comment by jolelievre** [comment]
Once https://github.com/PrestaShop/PrestaShop/pull/23076 is approved and merged I think we can close this issue

@sickboards is it ok for you? Did we answer all your concern?

**Comment by sickboards** [comment]
Yes, go ahead.

**Comment by hibatallahAouadni** [comment]
Hello guys,

It seems the PR is already merged :tada: 
So, I close this issue.

Thanks!
