### ISSUE TITLE
Issue in cookie with the SameSite parameter

### ISSUE THREAD

**Issue by maxenceboissieux** [PrestaShop/PrestaShop#23036]
#### Describe the bug

On the demo page in addons.prestashop.com when I launch the front demo or the back demo of my modules there is a problem with the paramater SameSite. So in front office I can't add product to the basket and in the back office I can't login. But all this bugs don't appear when I use the site without your iframe.

#### Expected behavior

Normally it would add product to the basket and login without that problem.

#### Steps to Reproduce

Front Office:
  1. Go to [https://addons.prestashop.com/demo/FO21159.html](https://addons.prestashop.com/demo/FO21159.html)
  2. Try to add any product to your basket.
  3. See error.

Back Office:
  1. Go to [https://addons.prestashop.com/demo/BO21159.html](https://addons.prestashop.com/demo/BO21159.html)
  2. Try to connect with the demo credentials.
  3. See error.

**Screenshots**

<img width="672" alt="Capture d’écran 2021-01-28 à 14 35 09" src="https://user-images.githubusercontent.com/71264635/106145759-35b4ab00-6176-11eb-9f81-d536a679a482.png">

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.0

**Comment by SimonGrn** [comment]
Hello,

this repository is aimed at the Core of PrestaShop. Addons is a separate entity which belongs to the PrestaShop company, not the PrestaShop open source project.
I highly suggest you contact them throught [their official page](https://www.prestashop.com/contact).

Thank you for your understanding.

**Comment by maxenceboissieux** [comment]
Hi ! @SimonGrn 

I misspoke, this bug is not only on Addons it is global. I see that you have one similar issue but in another version : #20528.

**Comment by matks** [comment]
Hi @maxenceboissieux I am not sure to fully understand.

What you report is "when I launch the demo of my module, there is an issue because of missing SameSite attribute". This is probably something related to how addons.prestashop.com "see a demo of my module" feature is setup?

If this is the case there is nothing we can do, we have no control of addons.prestashop.com . If you need this to be fixed, you need to contact a sales representative of Addons (I believe as a seller on Addons you have access to one?).
