### ISSUE TITLE
error showing description listed in product quick view

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23065]
#### Describe the bug

When I put a bullet list in the description of an article, it is not shown if I open the quick view of the product
See the video

#### Expected behavior

if I open the quick view of the product, I can see the bullet list in the description of an article

#### Steps to Reproduce

1. **BO**>**SELL**>**Catalog**>**Products**
2. Edit your product
3. Add a bullet list to your product's summary
4. **Save**
5. Click on **Preview**
6. FO, you can see the bullet list in product page
7. Go to **Category** page and click on **quick view** link
8. See error => the bullit list is not displayed

**Screenshots**

https://youtu.be/nY7uM-RmAwQ

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.29

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Thanks for your issue!
I reproduced your issue with PS1.7.7.0 and PS1.7.7.1. I tried to reproduce with older version and it seems that even in the product page, the bullet list was not displayed :confused: 
Apparently this issue has been fixed partially :wink: 

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by alfonsolr09** [comment]
in my store I fixed it, I was going to make a pull request, but someone already did :)
