### ISSUE TITLE
[BO - RESPONSIVE] Profile block needs some improvements to be more UX on mobile

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#23102]
#### Is your feature request related to a problem?

Profile block is so unresponsive, scott provided a mockup for this.

#### Describe the solution you'd like

It should look like this :

![image](https://user-images.githubusercontent.com/14963751/106621359-c8888780-6572-11eb-85c6-6117fad4f13a.png)

**Comment by prestascott** [comment]
Hello @NeOMakinG, 

There is just 2 small changes to do in this PR. It's not about the responsive itself but about providing better UX on mobile. Change the background-color when an option is clicked/tapped on mobile. Because the light background represents the hover, and there's no hover on mobile.

![my account (1)](https://user-images.githubusercontent.com/54888056/109283027-9212f500-781e-11eb-8bf3-154ae8fc8e5e.png)
![my account (2)](https://user-images.githubusercontent.com/54888056/109283028-92ab8b80-781e-11eb-8c32-5d1ab6191833.png)

Thanks!
