### ISSUE TITLE
New error with breadcrumbs

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23133]
![image](https://user-images.githubusercontent.com/62474824/106824811-e2fe5600-6683-11eb-8f65-fa49364b132a.png)
 new error with using the code of new PR (#22417)
 Error on [www](http://www). your website /shops

#22417
#23024

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by alfonsolr09** [comment]
to reproduce you just have to change the code of the path themes/classic/templates/_partials/breadcrumb.tpl and try with google search console. You have to change this code
https://github.com/PrestaShop/PrestaShop/pull/22417

**Comment by alfonsolr09** [comment]
@hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
@alfonsolr09 I will try to reproduce it and feedback 😉

**Comment by alfonsolr09** [comment]
@tswfi

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I didn't manage to reproduce your issue with develop, the only issue that I encountred is this one #22962

and this new regression: 

![image](https://user-images.githubusercontent.com/23308427/106909100-3d3cfc80-6700-11eb-8b2a-6db60aa01b61.png)

Please check and feedback.
Thanks!

**Comment by tswfi** [comment]
@hibatallahAouadni I'm pretty sure the "url non valide" is because you are using "prestashop" as domain name without any tld so it is not a fqdn..

**Comment by hibatallahAouadni** [comment]
@tswfi yep I just test it with my local shop and I need to test it with hosted one :sweat_smile:

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I didn't reproduce your issue with develop on hosted shop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/106914993-d6badd00-6705-11eb-9d97-b635c231f601.png)

And as I mentioned above, the only issue that I encounter is this one #22962

Ps: Thanks @tswfi  :wink: 

Thanks!

**Comment by alfonsolr09** [comment]
You have to test your web /shops
@hibatallahAouadni

**Comment by alfonsolr09** [comment]
the only mistake is with the "stores" page.
Like in the screen

**Comment by hibatallahAouadni** [comment]
@alfonsolr09 you mean to test it with multistore, is that so?

**Comment by alfonsolr09** [comment]
No, section shops

**Comment by alfonsolr09** [comment]
Like this lamagrande.com/tiendas

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

you mean `/stores ` 

![image](https://user-images.githubusercontent.com/23308427/106916806-e63b2580-6707-11eb-8e6b-ff08c432b152.png)

It seems your issue related to your theme.

Thanks!

**Comment by alfonsolr09** [comment]
Can you show me the code of the web that you have inspected?
@hibatallahAouadni

**Comment by alfonsolr09** [comment]
the breadcrumb code i mean

**Comment by matks** [comment]
Hi @alfonsolr09 , it I am not wrong, what @hibatallahAouadni has done is:

1. Checkout `develop` branch which is the next version of PrestaShop being built (it will become 1.7.8.0) - and this branch contains the result of https://github.com/PrestaShop/PrestaShop/pull/22417
2. Install it, test it
3. See result.

You can do the same.

However when you copy the code changes from https://github.com/PrestaShop/PrestaShop/pull/22417 be aware that you are not using the same codebase as we do. It is likely you are on PrestaShop 1.7.6 or 1.7.7, and these changes were meant to be applied to PrestaShop 1.7.8. To apply correctly the patch of https://github.com/PrestaShop/PrestaShop/pull/22417 you need to fully understand what these changes bring, for your very situation. But it's not the same codebase we have.

Also @hibatallahAouadni is not here to debug your store or your theme 😉  . When you encounter an issue with your shop, you must first identify whether the issue comes from the modifications you have applied on this shop (installing a theme, some modules, maybe some overrides...) and/or your setup ; or does the issue come from the code.

@hibatallahAouadni has verified, and so far it seems that issue cannot be traced back to the code of this repository. It's on your side now.

This repository is not a free support channel 😄  we don't have unlimited resources, so we cannot go further than verifying if your bug report can be traced to the code in this repository. This repository a place where people can collaborate on the project. If however you need help, If you need help with your shop or third-party modules, please have a look at the PrestaShop Company’s [support plans](https://www.prestashop.com/support).

**Comment by alfonsolr09** [comment]
Ok, thanks @matks 
Where can i download develop built?

**Comment by matks** [comment]
There 😉  https://nightly.prestashop.com/

**Comment by alfonsolr09** [comment]
thanks
