### ISSUE TITLE
PS 1.7.7.1 : Merchandise return (in order detail page > customer account) no input

### ISSUE THREAD

**Issue by elvisesteban** [PrestaShop/PrestaShop#23152]
#### Describe the bug

In prestashop 1.7.7.1, i activated the Mercandise return option.

I created some fake orders and changed their status to "Shipped".

I wanted to make a merchandise return test so i went to my customer account and selected a "shipped" order.

In the detail order page, i can't select any product for return. There are no input on the left of the product line. 
Actually, if you refresh the 

page, you'll see the input appearing for 0.5 second and it disappears.

The only input visible is the one that select all the products.

![bug-merchandise-return-1771](https://user-images.githubusercontent.com/61242427/107019949-92314f00-67a2-11eb-8154-4a5274550f40.png)

Maybe i forgot something, but it looks like a bug ! ;)

Any clue ?

Thanks for your help !

**Comment by florine2623** [comment]
Hello @elvisesteban ,
It seems like the issue comes from your template.
When using Classic theme, the merchandise return work correctly :
![Capture d’écran 2021-02-05 à 11 50 33](https://user-images.githubusercontent.com/16019289/107024550-7a5cc980-67a8-11eb-8888-c0237ca01539.png)
![Capture d’écran 2021-02-05 à 11 50 39](https://user-images.githubusercontent.com/16019289/107024561-7cbf2380-67a8-11eb-8763-ea19b15b3572.png)

I suggest you contact the developer of your template !
Thanks!
