### ISSUE TITLE
Prestashop doesn't update currency after changing shipping country

### ISSUE THREAD

**Issue by marcobeniamin-calicantus** [PrestaShop/PrestaShop#23160]
#### Describe the bug
I have configured prestashop to sell in two different countries (Italy and United Kingdom) and specified in each one its currency (IT: € and UK: ₤).
I have enabled "Geolocation by IP address" in "international > Geolocation" and uploaded the Geolite2 file.
I have Created a simple product and the Pricing Tab and set 2 specific price (see screenshot below).
When I visit the shop from an Italian IP i see the right price (€47,58)
When I visit the shop from an English IP i see the right price. (£82,79)
From an Italian IP i add the product to the cart and proceed to checkout.
In the Address fields i choose an Address of the other country (UK) and click on "continue" to advance to shipping method
Prestashop then refreshes the page and correctly changes the price value of the product but not change the currency (it shows €95.16 instead of £82,79).

#### Expected behavior

When Prestashop Refreshes the page it has to changes the price (which it does) and use the right currency: IT € and UK £

#### Steps to Reproduce

1. Enable two different countries (Italy and United Kingdom) and specify in each one his currency (IT: € and UK: ₤).
2. Go to 'International > Geolocation' and enable 'Geolocation by IP address'
3. Download Geolite2 file and upload on the right folder
3. Create a simple product and in the Pricing Tab set 2 specific price as in this screenshot ![specific_prices](https://user-images.githubusercontent.com/74672433/107057953-48f9f300-67d4-11eb-87a8-f7f8c184f800.png)
4. Visit the shop with the IP from one of this country and add the product to the cart
5. Proceed at checkout
6. Create a user
7. In the Adress insert the other nation that is enabled in the shop and click continue
8. Page will refresh and the price value will change with the one of the other country however the currency will not be changed to the correct one ![wrong_currency](https://user-images.githubusercontent.com/74672433/107060117-e22a0900-67d6-11eb-94da-ee20d5c49429.png)

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @marcobeniamin-calicantus 

I managed to reproduce your issue with PS1.7.7.1, see the attached screen record below:

https://drive.google.com/file/d/1BxchOPVpBHBtpqpaoRtSuUj9hb34jZi_/view

But, I'm a little bit confused :confused: I think that's the normal behavior (change the price but not the currency).
Well, if you suggest that we need to add this behavior in this case, so it's not a bug :wink: it's an improvement.

Ping @PrestaShop/product-team I don't think changing the currency along with the address is a good idea, wdyt?

**Comment by marionf** [comment]
Hello @marcobeniamin-calicantus 

Changing the delivery address doesn't change the currency because you can live in Italy and want to deliver your order to a friend in UK for example. In this case you want to pay the order in euro.

If you want to change the currency you can do it through the currency selector and if you want to change the language, you can do it through the language selector as you can see below:

![capture d'écran_2949](https://user-images.githubusercontent.com/13449658/107257546-13a30e80-6a3b-11eb-98ca-cabaf3313b92.png)


The geolocation by IP address is to choose in which countries you want to display the website or not.

If you want the country selected by default on the store to be the one of the visitor, you have to put the option "Set language from browser" to Yes and "Set default country from browser language" to yes.

**Comment by marcobeniamin-calicantus** [comment]
Hello @marionf
Thanks for your answer.
I understand the logic behind the functionality as you have explained it when we take into consideration the delivery address.
However, if I set the billing address to a different county from the one we are located, I think that Prestashop should change the corrency accordingly but, at the moment, it does not.

Can you give me feedback about this?

**Comment by marionf** [comment]
The behavior is the same for the delivery & billing address, you can for example live in Italy without speaking italian and not necessarily wanting to pay in euros. That's why the change of the language/currency should not depend on the delivery or billing address. The visitor / customer can change it through the language / currency selectors if the default language or currency selected doesn't suit his/her needs.
