### ISSUE TITLE
Problem with how tax is displayed when using discount.

### ISSUE THREAD

**Issue by marketingmedia** [PrestaShop/PrestaShop#23178]
#### Describe the bug

If you set a discount amount in the backend and set it to "Tax included" the amount displayed on the cart for the customer will have the tax deducted. Causing confusing between our customers.

#### Expected behavior

We expect to show "total products with tax" then a "discount with tax" at the end, 
instead what is show is  the products(with no taxes) -  discount(with no taxes) - taxes 

#### Steps to Reproduce

  1. Create a discount set amount, tax included
  2. try using coupon

**Screenshots**
![image](https://user-images.githubusercontent.com/16925824/107238362-5fc76200-69ed-11eb-8656-4c7f076b33dc.png)
![image](https://user-images.githubusercontent.com/16925824/107238443-75d52280-69ed-11eb-8fc3-06a0453b7f37.png)

Clients will expect the $20 to be subtracted at the end. 

#### Additional information

* PrestaShop version: 1.7.6.4

**Comment by hibatallahAouadni** [comment]
Hello @marketingmedia 

Could you please check in your **BO**>**CONFIGURE**>**Shop Parameters**>**Customer Settings**, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/107258606-4a2d5900-6a3c-11eb-886f-f75547ec9c48.png)

Could you please check if you choose **Tax included** as **Price display method** and feedback.

Thanks!

**Comment by marketingmedia** [comment]
is set to Excluded. 
![image](https://user-images.githubusercontent.com/16925824/107276789-29074100-6a19-11eb-9bbe-03661cdfd95e.png)

the math seems better but where it says "tax included" math is still wrong
![image](https://user-images.githubusercontent.com/16925824/107277395-ee51d880-6a19-11eb-8e40-d77f5cba5771.png)


This solution will not work for us either because it forces to show the prices with taxes around the whole site with taxes and we don't want that as different places in country has different taxes making it confusing for our clients when they see the price change after setting up their address.

What we would expect for the summary is something like this:
Products pre-taxes                  20.0
Product taxes                            3.0
total before discount              **23.0**
discount                               -  20.0 
                                            _________
TOTAL TO PAY                           3.00

This way is clear the whole coupon is being used.

**Comment by hibatallahAouadni** [comment]
Hello @marketingmedia 

Yes, that issue is fixed with PS1.7.7.1, see the attached screenshots below:

- Cart Rule:

![image](https://user-images.githubusercontent.com/23308427/107439601-9ce93c80-6b32-11eb-9fbe-8c2a19165b06.png)

- 1st case: when the **Price display method** set to **Tax included**

![image](https://user-images.githubusercontent.com/23308427/107439736-d28e2580-6b32-11eb-9955-886103e5fa93.png)

![image](https://user-images.githubusercontent.com/23308427/107439745-d7eb7000-6b32-11eb-9548-450a9daccfbb.png)

- 2nd case: when the **Price display method** set to **Tax excluded**

![image](https://user-images.githubusercontent.com/23308427/107439802-edf93080-6b32-11eb-85d5-8dad04f4c1ab.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @marketingmedia ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
