### ISSUE TITLE
Hook BO address change

### ISSUE THREAD

**Issue by olecorre** [PrestaShop/PrestaShop#23209]
#### Describe the bug

These hooks seem to not work on 1.7.7.1
- actionAddressesGridDefinitionModifier
- actionAddressesGridQueryBuilderModifier
- actionAdminAddressesFormModifier

#### Expected behavior

I have a module that uses its hooks, after update 1.7.6.3 to 1.7.7.1 
In 1.7.7.1 don't work, not called

#### Additional information

I changed my hooks to :
- hookActionAddressGridDefinitionModifier
- hookActionAddressGridQueryBuilderModifier
- hookActionCustomerAddressFormBuilderModifier

Now it works => did the hook names change?

My site is under development, I have made the modifications but if a trader has installed a module, the update will be a problem.

**Comment by hibatallahAouadni** [comment]
Hello @olecorre 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22981. 
And it's already fixed with our futur next minor release 1.7.7.2, please subscribe to the issue mentioned above.

About these two hooks: **actionAddressesGridDefinitionModifier** & **actionAddressesGridQueryBuilderModifier** 

![image](https://user-images.githubusercontent.com/23308427/107520738-06f4f680-6bb2-11eb-9a0b-0260883086ee.png)

About this hook **actionAdminAddressesFormModifier**, I couldn't find it with PS1.7.7.2, and I don't know if its name has been changed.
Let's ask the Developer Team. Stay tuned.

Ping @PrestaShop/prestashop-core-developers Has this hook name **actionAdminAddressesFormModifier** been replaced by **actionCustomerAddressFormBuilderModifier**

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @olecorre 

After discuss this issue with @Progi1984 and reproduce it again wihth @khouloudbelguith 
It seems this hook is missing after the migration.

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by Progi1984** [comment]
@olecorre I don't know where you find : 
* `actionAddressesGridDefinitionModifier`
    * you must use `actionAddressGridDefinitionModifier`
    * Specified in `src/Core/Grid/Definition/Factory/AbstractGridDefinitionFactory.php` l.93
    * And `src/Core/Grid/Definition/Factory/AddressGridDefinitionFactory.php` l.57
*  `actionAddressesGridQueryBuilderModifier`
    * you must use `actionAddressGridQueryBuilderModifier`
    * Specified in `src/Core/Grid/Data/Factory/DoctrineGridDataFactory.php` l.90
    * And `src/Core/Grid/Definition/Factory/AddressGridDefinitionFactory.php` l.57
*  `actionAdminAddressesFormModifier`
    * It was relative to the controller legacy
    * Like the CustomerAddress has been migrated in 1770, the hook should be migrated  
    * In this case, we can't alias it as it not the same hook
    * Legacy : `classes/controller/AdminController.php` l.2499 :scream: 
    * ![image](https://user-images.githubusercontent.com/1533248/108373223-f0791b80-71ff-11eb-863c-8a0fc29352dd.png)
    * Migrated : `src/Core/Form/IdentifiableObject/Builder/FormBuilder.php` l.122
    * ![image](https://user-images.githubusercontent.com/1533248/108373315-0f77ad80-7200-11eb-8a6c-02acc7172e97.png)

I hope I have answered to your questions.

**Comment by olecorre** [comment]
C’est bon pour moi, c’est un module spécifique pour un projet, j’ai fait les modifications adequates. 
Mais pour des modules vendus, le changement risque de poser des soucis. Je tenais juste à le signaler.

**Comment by hibatallahAouadni** [comment]
@olecorre so shall we close the issue?

**Comment by olecorre** [comment]
Okay, I'll close it.
