### ISSUE TITLE
BO / product page : attribute that can't be generated and I don't save my product

### ISSUE THREAD

**Issue by LaurentPrei** [PrestaShop/PrestaShop#23241]
Hello,

I'm working on Prestashop 1.7.7.1

The site is under construction and will be launched with only 10 products. So I enter them manually.

It's a liquid product available in 5L, 60L, and 200L. -> Packaging attribute and the values 5, 60 and 200 (see screenshots)

When I made my first product sheet (two days ago), it was working on the back office and the front end.

Since then, I have created a second similar product with the same choice of packaging and I cannot generate my 3 attributes, nor save my modifications.

This also does in my first product sheet. In addition, they no longer appear in the back office but I find them in the front end.

I emptied my nav cache and tried in another. Nothing

I have emptied the Prestashop cache. Nothing

I deleted my existing attribute to make a new one. 
As a result, I cannot grant it to either of my two products and I can no longer register.

Do you have any idea where this might come from?

Thank you all in advance.

A clear and concise description of what went wrong.

**Screenshots**

![Fiche-produit](https://user-images.githubusercontent.com/48889865/107789007-5887b780-6d51-11eb-9e4f-2cbb1b5cf918.jpg)

![dedbug-mode](https://user-images.githubusercontent.com/48889865/107789033-63424c80-6d51-11eb-99ab-5b73db84ad82.jpg)

![Attribut](https://user-images.githubusercontent.com/48889865/107789038-65a4a680-6d51-11eb-9bde-48c424bab274.jpg)

![Attributs2](https://user-images.githubusercontent.com/48889865/107789050-676e6a00-6d51-11eb-9bbc-c1cc3dc62731.jpg)

Thank you

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @LaurentPrei ,

This issue is not reproducible in fresh install of PrestaShop 1.7.7.1. It seems like your issue is coming from your site.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
