### ISSUE TITLE
css bug when trying to write dimensions in an image or video (product description)

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23255]
#### Describe the bug

error when trying to write dimensions in an image or video (product description)

#### Steps to Reproduce

https://youtu.be/19n-umrDU8E

**Screenshots**

https://youtu.be/19n-umrDU8E

#### Additional information

* PrestaShop version: **1.7.6.4, 1.7.7.0, 1.7.7.1, 1.7.8.0 (develop)**
* PHP version: 7.2, 7.3

**Comment by florine2623** [comment]
Hello @alfonsolr09 ,

I have reproduced your issue in PS 1.7.6.9 and PS 1.7.7.1.
You can use tab key to write your image dimensions.

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by alfonsolr09** [comment]
Thanks :)
