### ISSUE TITLE
gtin or ean-13 must be specified to show product details in google shopping

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#23259]
![image](https://user-images.githubusercontent.com/62474824/107892576-53c82c80-6f26-11eb-9d39-22de4293fead.png)
![image](https://user-images.githubusercontent.com/62474824/107892697-2e87ee00-6f27-11eb-97a2-b64872fe0463.png)
https://support.google.com/merchants/answer/6324461
https://support.google.com/merchants/answer/6219078
https://support.google.com/merchants/answer/7052112?visit_id=637489419380464244-394408072&rd=1#gtin   (look at the table)
https://schema.org/gtin13

In the Rich Results Test it only appears as a warning, but if you want to include the products of your store in google shopping, it does show an error and is rejected

#### Steps to reproduce:

1- Create a new product with all information.
2- Log in to your google merchant center account
3- Open PrestaShop Ads module and follow the steps to upload your products via API.
4- Once you send the products, after a few hours or maybe a day several errors will appear.

#### Additional information

* PrestaShop version: 1.7.6.4, 1.7.7.0, 1.7.7.1, 1.7.8.0
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @alfonsolr09 ,
The MPN and EAN13 code are present in the produce sheet in the BO.
Simple product :
![Capture d’écran 2021-02-15 à 09 43 58](https://user-images.githubusercontent.com/16019289/107923924-741dd880-6f72-11eb-89f2-1c94587b2d2f.png)

Product with combinations :
![Capture d’écran 2021-02-15 à 09 43 32](https://user-images.githubusercontent.com/16019289/107923918-71bb7e80-6f72-11eb-92e0-2981a4848dcb.png)

Thanks

**Comment by alfonsolr09** [comment]
but it has no schema.org tags @florine2623

**Comment by alfonsolr09** [comment]
@florine2623 reopen this please
The itemprop ean13 or gtin It is not defined

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Could you please edit your issue **following the provided template to submit a complete bug report** and please provide clear **steps to reproduce**, then I will open the issue :wink: 

Thanks!

**Comment by alfonsolr09** [comment]
@hibatallahAouadni now you can reopen this.
I already wrote the steps to reproduce the problem

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Thanks for the details!
I think your issue is similar to this one #22962 could you please check it and feedback.

Thanks!

**Comment by alfonsolr09** [comment]
Not the same. I mean google merchant center

**Comment by alfonsolr09** [comment]
Not the same. I mean google merchant center
@hibatallahAouadni

**Comment by Maofree** [comment]
Hi @alfonsolr09
don't pass to google merchant center a csv or a xml with combinations, the same for facebook shop (in this mode you reduce the click cost)

go into product-details.tpl and check if you have this code:

`    {if isset($product.reference_to_display)}
      <div class="product-reference">
        <label class="label">{l s='Reference' d='Shop.Theme.Catalog'} </label>
        <span itemprop="mpn">{$product.reference_to_display}</span>
      </div>
    {/if}`

   ` {if isset($product.ean13)}
      <div class="product-ean13">
        <label class="label">{l s='Ean code' d='Shop.Theme.Catalog'} </label>
        <span itemprop="gtin">{$product.ean13}</span>
      </div>
    {/if}
  {/block}`

`<meta itemprop="productID" content="{$product.id}" />
<meta itemprop="sku" content="{$product.id}" />`

![1](https://user-images.githubusercontent.com/653230/110180459-17dc0500-7e0a-11eb-92dd-a513d0b87c6b.png)

now open the product-prices.tpl and add this code

`        <link itemprop="availability" href="{$product.seo_availability}"/>
        <link itemprop="itemCondition" href="https://schema.org/NewCondition"/>
        <meta itemprop="priceCurrency" content="{$currency.iso_code}">
        <meta itemprop="url" content="{$urls.current_url}">
        <meta itemprop="priceValidUntil" content="{"+1 year"|date_format:"%Y-%m-%d"}">`

![2](https://user-images.githubusercontent.com/653230/110180825-c84a0900-7e0a-11eb-957a-eea6483449c0.png)

at the end you will get a perfect microcode for a product check this page with https://search.google.com/
https://www.solariabio.it/integratori-alimentari-naturali-liquidi/474-vonderweid-aloe-arborescens-ricetta-del-frate-classica-830g-biologica-8051490700040.html

I suggest you to use
`<link itemprop="itemCondition" href="https://schema.org/NewCondition"/>`
instead of
`<link itemprop="itemCondition" href="{$product.condition.schema_url}"/>`
because in many cases appears refunded instead of new. this is another problem of prestashop's microdata
I developed a module to export file for many comparators so I have experience about it

for google merchant center it is necessary to set into the csv or xml file:
id
reference
brand
google category
ean13 if present

byeeee

**Comment by alfonsolr09** [comment]
i do with official module

**Comment by alfonsolr09** [comment]
where is the place where i have to write te ean13 ??

**Comment by Maofree** [comment]
hi
go into
templates/catalog/_partials/product_details.tpl
and add this code inside the {block name='product_reference'} like in the image

`    {if isset($product.ean13)}
      <div class="product-ean13">
        <label class="label">{l s='Ean code' d='Shop.Theme.Catalog'} </label>
        <span itemprop="gtin">{$product.ean13}</span>
      </div>
    {/if}`

**Comment by alfonsolr09** [comment]
Ok, i say on BO where is the place ??

**Comment by Maofree** [comment]
the microdata are in the front-office, so you need to donwnload this file of your theme and the upload it again on your server
nothing to do in the BO

**Comment by alfonsolr09** [comment]
I know, i mean where i have to write the ean13 of the products?

**Comment by alfonsolr09** [comment]
in which box?

**Comment by Maofree** [comment]
![1](https://user-images.githubusercontent.com/653230/110211372-9a120b00-7e96-11eb-90d4-e1e61ab8a2b9.png)

in you have combinations also in the single combination, the default combination should have the ean13 of the option step

**Comment by alfonsolr09** [comment]
Ok, and one more question.
I don't have the ean13 in any product, why did google accept most of the products but rejected some of them??
89% accept and 11% reject

**Comment by alfonsolr09** [comment]
The reason that google gives me is that an ean13 must be specified

**Comment by Maofree** [comment]
usually because they are not correct, the ean13 are provided by the manufacturers of the products

**Comment by alfonsolr09** [comment]
I do not have ean13 in any product and many products accepted them

**Comment by Maofree** [comment]
I can't help you from here because I cannot see the errors of google merchat center
normally it is written the motive of this refuse.
if the product has a ean13 you must set it, if not it is necessary only
id
reference
brand
google category

**Comment by alfonsolr09** [comment]
I checked that none of my products have ean13. but i don't know why i reject some products. Can you help me?

**Comment by Maofree** [comment]
send me an email look at my github profile

**Comment by alfonsolr09** [comment]
> hola,
> vaya a
> templates / catalog / _partials / product_details.tpl
> y agregue este código dentro del {block name = 'product_reference'} como en la imagen
> 
> ` {if isset($product.ean13)} <div class="product-ean13"> <label class="label">{l s='Ean code' d='Shop.Theme.Catalog'} </label> <span itemprop="gtin">{$product.ean13}</span> </div> {/if}`

why is all this not already included in prestashop?
