### ISSUE TITLE
Error 500 1-click upgrade

### ISSUE THREAD

**Issue by JeromeBijourium** [PrestaShop/PrestaShop#23271]
#### Describe the bug

I tryed to use the 1-clic update to get the last version of prestashop

#### Expected behavior

ended to 500 error, it seems that the system was not able to unpack it but i m not sure

#### Steps to Reproduce

1. Go to module
2. Click on 1 clic update
4. See error -> 500

->www.bijourium.com is my website

* PrestaShop version: 1.7.5 (?)
* PHP version: 7.2

**Comment by matks** [comment]
Hi @JeromeBijourium you need to provide us a screenshot or something more tangible, "a 500 error" is a bit vague 😅

**Comment by JeromeBijourium** [comment]
I know it s a bit short but I unfortunatly didnt think about taking a screenshot.
But I have more informations now :
My hosting was full and it seems that the plugin was unable to unpack. (seems theres nothing to check if the plugin has enough place to unpack)
SO... something went wrong because of that and i have no idea how to get the site back.

**Comment by matks** [comment]
> My hosting was full and it seems that the plugin was unable to unpack. (seems theres nothing to check if the plugin has enough place to unpack)

Indeed if you have run out of space, it is possible the ZIP archive could not be unpacked.

> SO... something went wrong because of that and i have no idea how to get the site back.

If you need help with your shop or third-party modules, please have a look at the PrestaShop Company’s [support plans](https://www.prestashop.com/support).

**Comment by hibatallahAouadni** [comment]
Hello @JeromeBijourium 

As @matks mentioned above, it seems you need some help with your store and your issue is not related to PS Core.

So, I close this issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
