### ISSUE TITLE
Details link in customer management module config is not valid

### ISSUE THREAD

**Issue by ijzershop** [PrestaShop/PrestaShop#23323]
The url generated in psgdrp at 415:            ` 'customer_link' => $this->context->link->getAdminLink('AdminCustomers', true) . '&viewcustomer&id_customer=',`
Does not redirect to the customer information page but the customers overview page because the url is not valid.
The generated url is for example: `index.php/sell/customers/?_token=439mm6A-AWILQB2sSXczCo6REgDlbrHfAGdq0XpBpO4&viewcustomer&id_customer=6` 
but should be: `index.php/sell/customers/6/view?_token=439mm6A-AWILQB2sSXczCo6REgDlbrHfAGdq0XpBpO4`

**Comment by hibatallahAouadni** [comment]
Hello @ijzershop 

Sorry for the late response and thanks for your issue!
I reproduce your issue with PS1.7.7.2 and GDPR v1.2.1, see the attached screenrecord below:

https://drive.google.com/file/d/1mG0SdUi-azEGmyRNMK2mBbSjmD89YlqJ/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

PS: it's not a regression cause I reproduce the issue with PS1.7.6.8 and GDPR v1.2.0

Thank you

**Comment by Progi1984** [comment]
Fixed by @moncef-essid in PrestaShop/psgdpr#122
