### ISSUE TITLE
[Firefox] Checkbox, text and link about data protection not shown in contactform

### ISSUE THREAD

**Issue by tbores** [PrestaShop/PrestaShop#23321]
Prestshop version: 1.7.6.1
Module version: 1.1.3

### Chrome - OK
![image](https://user-images.githubusercontent.com/4364483/69799849-5ed55680-11d4-11ea-9cda-a85b4fd01477.png)

### Internet Explorer - OK
![image](https://user-images.githubusercontent.com/4364483/69799954-8fb58b80-11d4-11ea-8d51-d9b2258b5810.png)

### Firefox 70.0.1 - NOK
![image](https://user-images.githubusercontent.com/4364483/69800033-b7a4ef00-11d4-11ea-92f0-7dabd3259036.png)

Module configuration
![image](https://user-images.githubusercontent.com/4364483/69799696-16b63400-11d4-11ea-8654-8c391c049279.png)

**Comment by hibatallahAouadni** [comment]
Hello @tbores 

Since we had no news from you for more than 2 years, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

PS: I didn't manage to reproduce the issue with PS1.7.7.2 and GDPR v1.2.1 on Firefox v86.0 (see the attached screenshot below)

![image](https://user-images.githubusercontent.com/23308427/109350484-d9799f80-7877-11eb-8756-091a4755f3b1.png)

Thanks!
