### ISSUE TITLE
BO - Orders page - missing DNI number in some countries when the DNI is not required

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#23357]
#### Describe the bug

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/23040#issuecomment-783326399
When the DNI is not required for some countries, the dni number is missing in the BO > Orders > Order preview page & Order details page

#### Steps to Reproduce

1. Install PS with English language & France country
2. Go to BO > International > Locations > Countries Tab
3. Edit France country
4. In the Address format, Add dni 
![image](https://user-images.githubusercontent.com/16067358/108817645-845c3600-75b8-11eb-8d52-e1b28cdcf1d0.png)
5. Save
6. Go to FO > Sign in with John Doe
7. Update Mon adresse (France country)
8. Add an `Identification number`
 ![image](https://user-images.githubusercontent.com/16067358/108817701-96d66f80-75b8-11eb-857b-621e98a6a592.png)
9. Save
9. Add a product to the cart
10. Continue checkout
11. In the ADDRESSES Shipping Address step > Select Mon adresse
12. Place Order
13. G to BO > Orders > Last order created
14. See the error => the dni is not displayed

In the PS1769 => ok 
![image](https://user-images.githubusercontent.com/16067358/108819040-98a13280-75ba-11eb-8df0-42d603abafc3.png)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1

**Comment by Progi1984** [comment]
As discussed yesterday with @PrestaShop/prestashop-core-developers, the missing feature is the support of Address Format in Order Page.

**Comment by matks** [comment]
> As discussed yesterday with @PrestaShop/prestashop-core-developers, the missing feature is the support of Address Format in Order Page.

Oh, this one is completely intentional.

When we were working on Order page, we tried to setup this concept of Address Format in order page. And what we found is that it is a complete mess 😄  . Basically, when you are on a page where address format must be validated, the address format to apply can come from multiple places.

To be sure: we are talking about "what field in the address is mandatory, what field in the address is optional", right?

So about that
- it's possible to modify the address format from BO addresses page
- but it's also possible to configure address format for countries 😄  you can say "country A needs VAT, country B does not need it"
- but modules can also modify this address format ! they can also add custom fields into the address
- and I think there was a 4th configuration setting that was able to modify this stuff

So @zuk3975 and @MatShir spent a few hours/days trying to find "when you configure all these different settings, what should be the final format address to validate ?" only to conclude that this was a complete mess, merchants will never understand what's going on so it was better to disable any validation on this and let merchant do whatever they want. Basically the final behavior decision "Merchant can do whatever he wants in his Back Office, so even if he wants to input invalid adresses he should be able to."

What we wanted to avoid at all costs was the following scenario:
- merchant configures his address format
- merchants makes a mistake (well, since even us dont understand how this address format stuff how could the merchant figure it out?)
- then merchant wants to enter an address to place an order, and he's blocked by the address format validation

**Comment by zuk3975** [comment]
related https://github.com/PrestaShop/PrestaShop/issues/17647

**Comment by Progi1984** [comment]
@matks FYI In this case, the bug is about displaying of the adress based on the address format.

**Comment by Progi1984** [comment]
Fixed by #24273
