### ISSUE TITLE
Bug. The "Add to cart" button does not work

### ISSUE THREAD

**Issue by Kssindri** [PrestaShop/PrestaShop#23360]
#### Describe the bug

On the product sheet when click on the button "Add to cart" nothing happens and the product is not added to the cart then does not update automatically you must refresh the page to be able to see your order add to basket.

#### Expected behavior

Normally with previous versions, when you click on the "Add to cart" button, a window appears which summarizes and summarizes the order which can allow us to continue Purchasing or Order. But this window does not appear when click on the button "Add to cart".

#### Steps to Reproduce

1. Go to 'https://afriqpharmacopee.com/'
2. Click on 'one of the products'
3. Click on the 'add to cart' button

**Screenshots**

![1](https://user-images.githubusercontent.com/79507416/108833665-0ce0d380-75c5-11eb-9a1b-a0a5963e02a1.png)

![2](https://user-images.githubusercontent.com/79507416/108833731-284bde80-75c5-11eb-9f3d-1bf0b1e1b1c7.png)

![3](https://user-images.githubusercontent.com/79507416/108833752-2e41bf80-75c5-11eb-8751-2bf4af7c0adf.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Kssindri 

It seems you upgrade your shop. So what was your previous version? and did you encounter any issue (errors or warnings) during the upgrade process?
Please check and feedback.

Thanks!

**Comment by Kssindri** [comment]
No error noticed and I specify that my previous site under prestashop 1.7.7.1 had the same bug or malfunction

**Comment by Kssindri** [comment]
No error noticed and I specify that my previous site under prestashop 1.7.7.1 had the same bug or malfunction.
Website : https://afriqpharmacopee.com/

**Comment by hibatallahAouadni** [comment]
Hello @Kssindri ,

Sorry but I didn't manage to reproduce your issue with PS1.7.7.1 and PS1.7.7.2 and it seems your issue is not related to PS Core. So, I close this issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Kssindri** [comment]
Can you give me the name of the cart module please for prestashop 1.7.7.2

**Comment by hibatallahAouadni** [comment]
Hello @Kssindri 

I didn't use any cart module. I use the default PS shop (cart, ...).

Thanks!

**Comment by Kssindri** [comment]
There is no native prestashop module to uninstall and reinstall it to see if the problem can be solved

**Comment by matks** [comment]
> Can you give me the name of the cart module please for prestashop 1.7.7.2

It's simply name "Shopping Cart"

https://github.com/prestashop/ps_shoppingcart

**Comment by Kssindri** [comment]
thank you
