### ISSUE TITLE
Cart rule exception in multistore when product not available for default store

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#23376]
#### Describe the bug

When you open a cart rule with a free gift, and this product is not enabled in the store context, it throws an exception

#### Steps to Reproduce

1. Create a multistore with 2 stores
2. Set context for store 2
3. Create a product
![image](https://user-images.githubusercontent.com/15104724/108978836-55ae9000-768a-11eb-8ce1-0406c4f2de70.png)

4. Create a cart rule with a free gift. Select the product created. Save.
![image](https://user-images.githubusercontent.com/15104724/108978593-0b2d1380-768a-11eb-8921-6d7caa653add.png)

5. Set context for "All shops":
![image](https://user-images.githubusercontent.com/15104724/108978987-7f67b700-768a-11eb-922e-9c9c9dc11177.png)

6. Try to open the created cart rule:
![image](https://user-images.githubusercontent.com/15104724/108978667-21d36a80-768a-11eb-8022-9478ba7b5972.png)

Exception is thrown here https://github.com/PrestaShop/PrestaShop/blob/6cc8f20c2a5675d754c5566adf76ec6ac25ef901/controllers/admin/AdminCartRulesController.php#L573, because `$product['price_tax_incl']` is null.

#### Additional information

* PrestaShop version: 1.7.7.2

**Comment by hibatallahAouadni** [comment]
Hello @idnovate 

Thanks for your issue!
I reproduce the issue with PS1.7.7.0, PS1.7.7.1 and PS1.7.7.2, I didn't reproduce it with PS1.7.6.7.

![image](https://user-images.githubusercontent.com/23308427/108985096-f011d200-7690-11eb-8c39-6fc16f841d41.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

**_PS: when I switch to the Store 1 and try to edit the cart rule, I didn't encounter any problem (even when the product is created only in Store2)._**

Thank you

**Comment by atomiix** [comment]
Fixed by #23584
