### ISSUE TITLE
Remove live exchange rate toggle in International > Localization > Currencies

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#23412]
#### Is your feature request related to a problem?

The [cronjob module](https://github.com/PrestaShopCorp/cronjobs) isn't compatible with 1.7 versions and since it is a service provided by PrestaShop Corp, the core should not have any dependency with it.

#### Describe the solution you'd like

- [ ]  Remove all dependencies in the core with the cronjob module.
- [ ] Remove the live exchange rate toggle in International > Localization > Currencies
- [ ]  Add explanations in the documentation to indicate how to automatically update the exchange rates ->  "Check the [developer documentation](https://devdocs.prestashop.com/1.7/faq/pricing/#refresh-exchange-rates) for setup instructions." in Admin.International.Help

**Comment by matks** [comment]
Hi @marionf after diving into the code, I found that when merchant tries to turn on the live exchange rate toggle in "International > Localization > Currencies" BO page,
- if cronjob module is not installed, an error is displayed
- if cronjob module is installed, it creates a cron record for cronjob which will call an URL to trigger the exchange rate update

So what this little toggle does is 'configure cronjob module to call script `cron_currency_rates.php` with the right parameter'. When this script is called with the right parameter, the exchange rates are updated.

Related code https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Currency/CommandHandler/ToggleExchangeRateAutomatizationHandler.php#L162

There are some forum posts explaining how to do this manually
- https://www.prestashop.com/forums/topic/177598-updating-currencies-automatically/
- https://www.prestashop.com/forums/topic/1012820-solved-create-a-cronjob-to-auto-update-exchange-rate/

As well as services that offer to do it like easycron.com https://www.easycron.com/cron-job-tutorials/how-to-set-up-cron-job-for-prestashop-currencies

It would be nice to provide this information to merchant, in the user documentation maybe? And we could put a link in the BO page where to find this information?

**Comment by marionf** [comment]
It's a good idea @matks we could add an information message in the BO with a link to the documentation
And could explain in what are the alternatives:
- easycron
- setting a cron task through the hosting provider ? But maybe this needs some dev in the shop ?

Let me know if you see other solutions that we could add in the doc ?

**Comment by matks** [comment]
> * easycron

easycron or other CRON services, I think we can find a few. Maybe we can ask @kpodemski if he has any recommendation?

> * setting a cron task through the hosting provider ? But maybe this needs some dev in the shop ?

[cron](https://en.wikipedia.org/wiki/Cron) "is a time-based job scheduler in Unix-like computer operating systems". Almost every Unix-like server has this capacity, although not every hosting provider allow its customer to access and configure it. We could quite simply provide an example for a popular distribution like Ubuntu 📘 . It's just 1 line of configuration and 5 lines of explanation.

For people using lowcost hosting providers, they might not be able to control their server cron but then there's the services like easycron. Any business that invests into a proper hosting platform will be able to use a cron.

And also I think the logic inside https://github.com/PrestaShopCorp/cronjobs is not very complex. An experienced developer should be easily able to take https://github.com/PrestaShopCorp/cronjobs module and allow it to work with PrestaShop 1.7, at least for the basic need. And updating exchange rates regularly using a cron job is a basic need.

**Comment by jeckyl** [comment]
Hi,

1. I don't think it's Prestashop's backoffice's job to promote third party companies since they could disappear and the links would become obsolete or turn into a dubious site.
2. Putting the links back as they have always been presented on this page would be enough to separate the core from the module, which [I offer as a free module](https://link.prestatoolbox.fr/medlivexchangeurl) for all uncorrected 1.7 versions.
3. The idea of recalling what a cron task is and how to use it finds its perfect place in the documentation, but no link should be made between the backoffice and the documentation because any change of url or other would cause a 404 error or force the teams to maintain the redirection of all the pages properly, which is tedious and, I think, useless.
4. The choice was made to remove the cronjob module from version 1.7, so there is no point in continuing its development knowing that there have always been free or paid community alternatives.

Currency documentation 1.6 : http://doc.prestashop.com/display/PS16/Devises
Currency documentation 1.5 : http://doc.prestashop.com/pages/viewpage.action?pageId=11272508#Comprendrelesr%C3%A9glageslocaux-Devises

Updating the currency exchange rate was not proposed before, but alternatives exist in the form of a module proposed by the community.

**Comment by kpodemski** [comment]
I believe we could create some kind of Cron Handler like WordPress has, where you can schedule tasks and run them not in background but when someone is visiting - for example back-office.

I agree partially with @jeckyl that maybe it's not best to promote third party services in back-office **but** link to documentation should be available, and then in docs we could create detailed instruction (if Cron Handler is too crazy idea)

**Comment by jeckyl** [comment]
> **but** link to documentation should be available, and then in docs we could create detailed instruction

The choice was made to modify with version 1. 7 the management of the exchange rate update by forcing the use of the cronjob module. Years later, a new team took the decision to remove the cronjob module for good reasons, but did not remember the link with the exchange rate management, It is therefore necessary to imagine that the implementation of a link to a documentation that would be likely to evolve or disappear may cause problems in the use of the back office over time. It seems coherent to me to favor stable elements because an installed version of Prestashop can be used for a very long time by some people.
The experience here, proves us that nobody is infallible and that it is thus always necessary to privilege the least risk by putting perhaps a link towards the root of the documentations which should be rather stable except if PrestaShop disappears, and to take again the documentation already written for the previous versions while waiting to improve them, that would be a simple and fast starting point to implement.
I didn't do PR to simply correct the display because this part of PrestaShop has switched to symfony and I haven't yet taken the time to train myself to this framework and when I simply tried to find the place where this insert is displayed I understood absolutely nothing by opening the ten or so files related to the currency administration.

**Comment by matks** [comment]
> Hi,
> 
> 1. I don't think it's Prestashop's backoffice's job to promote third party companies since they could disappear and the links would become obsolete or turn into a dubious site.

I was indeed thinking of a link to the documentation, not writing a message into the Back Office directly. The Back Office code is immutable, so people with old versions will have it forever. But a link to https://doc.prestashop.com/ or https://devdocs.prestashop.com/ can always be updated.

> It is therefore necessary to imagine that the implementation of a link to a documentation that would be likely to evolve or disappear may cause problems in the use of the back office over time. It seems coherent to me to favor stable elements because an installed version of Prestashop can be used for a very long time by some people.

The documentation that is available inside the 1.7 Back Office (it can be expanded on the right) can be updated at runtime because it is fetched from help.prestashop.com, so we can have a content that depends on time there.

As for whether it's OK to talk about easycron I dont know 🤔  . I guess there's a difference between quoting a service "some web services offer cron capabilities, like easycron or ..." and _endorsing_ a service "you can use easycron" ?

Better ping @ttoine to validate this

**Comment by jeckyl** [comment]
> As for whether it's OK to talk about easycron I dont know 🤔 . I guess there's a difference between quoting a service "some web services offer cron capabilities, like easycron or ..." and _endorsing_ a service "you can use easycron" ?

Maybe just quote several of them in the doc but not in the backoffice directly, it's just on this point that I was reacting.

**Comment by marionf** [comment]
Thank you everyone for your feedbacks :)

It seems a good idea to mention in the documentation different alternatives and quote third services (not only easycron) as an example, we could even explain in a sentence that these services are completely independent of PrestaShop.

Maybe rather in the [devdoc](https://devdocs.prestashop.com/) than in the [user doc](https://doc.prestashop.com/) as it seems a bit technical, wdyt @Julievrz ?

**Comment by Julievrz** [comment]
Hi @marionf, I agree with you, I think it should be in the devdocs and not in the user doc. We can still add a link to the devdoc in the userdoc for tech-savvy merchants if necessary.

**Comment by brunopacory** [comment]
HI, I am new and not sure to be at the right place here but I have 2 first questions :
- Is there any mean to contact directly Prestashop for any problem we can have ?
- I have got problem with mutli store automatic currency update using native PS cron module, with a trouble on 2 of my items which have different prices according to the size : working good on all shops in 2 currencies each, except one where for one specific currency, prices do not change..
Waiting from reading from you (in french if Marion is from Paris as indicated).

**Comment by matks** [comment]
Hi @brunopacory I think you'll find answers on https://devdocs.prestashop.com/1.7/faq/i-need-help/

**Comment by brunopacory** [comment]
Hi, My version is 1.6. Nothing in the documentation about my specific problem. Anyone to assist regarding both of my questions ?

**Comment by lmeyer1** [comment]
@marionf @MatShir 
Meanwhile, we have a page on devdocs (https://devdocs.prestashop.com/1.7/faq/pricing/#refresh-exchange-rates) that explain this very well, but the BO still display the old message:
![Capture du 2022-04-07 14-14-45](https://user-images.githubusercontent.com/7520695/162197882-68368f31-a050-493c-bb9e-00d268d1e494.png)

Shouldn't the suggestions in this tread be turned into a PR that replaces `Please install the cronjobs module before using this feature.` with something like `Please consult the [documentation](https://devdocs.prestashop.com/1.7/faq/pricing/#refresh-exchange-rates) for setup instructions`

**Comment by MatShir** [comment]
@lmeyer1 you are right, we should be more explicit ! nice catch :)

**Comment by MatShir** [comment]
@Julievrz What do you think ?

**Comment by Julievrz** [comment]
I agree, thanks @lmeyer1. Here's my suggestion: "Check the [developer documentation](https://devdocs.prestashop.com/1.7/faq/pricing/#refresh-exchange-rates) for setup instructions." in Admin.International.Help

**Comment by Progi1984** [comment]
@lmeyer1 Do you see any thing to do before closing this issue ?

**Comment by lmeyer1** [comment]
@Progi1984 No, for me it is OK to close.

**Comment by Progi1984** [comment]
@lmeyer1 I check it. I agree too. Good job for this contribution.

**Comment by jeckyl** [comment]
I made a free contribution to get the url to use a cron task https://link.prestatoolbox.fr/medlivexchangeurl

**Comment by lmeyer1** [comment]
Thanks @jeckyl
