### ISSUE TITLE
[FO - checkout page] Error on payment step 

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#23429]
#### Describe the bug

An error is displayed in checkout payment step when final Summary is enabled

#### Expected behavior

Final summary looks fine

#### Steps to Reproduce

1. Go to BO shop parameters order setting
2. Enable final summary
3. Go FO and add product to cart 
4. Go to checkout step
5. Set customer information and addresses information too
6. Chosse shipping method and click on next
7. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/48441421/109296042-086c2300-7830-11eb-8baf-9dcbae4a1e1a.png)

#### Additional information

* PrestaShop version: develop branch 
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Ping @marionf where I should put this issue? in Project 1.7.8.0 or Project 1.7.9.0?

**Comment by marionf** [comment]
It depends if it's a regression of the 1.7.8 or develop ;)

**Comment by hibatallahAouadni** [comment]
Hello @marionf 

I manage to reproduce with both develop and 1.7.8.x (this issue is related to PHP 7.4, cause I didn't manage to reproduce with PHP 7.2).

![image](https://user-images.githubusercontent.com/23308427/117098332-6f491380-ad6e-11eb-8e30-9b3e6563c498.png)

So, shall I add it to 1.7.8.0 project?

Thanks!

**Comment by marionf** [comment]
> So, shall I add it to 1.7.8.0 project?

If it worked on 1.7.7.x and not on 1.7.8.x, yes it's a regression of the 1.7.8 to fix

**Comment by Progi1984** [comment]
Fixed by @atomiix in #24457
