### ISSUE TITLE
Call to a member function compile() on null

### ISSUE THREAD

**Issue by md2158** [PrestaShop/PrestaShop#23436]
#### Describe the bug

Upgraded from 1.7.3.4 to 1.7.7.2 and now can't access to advanced setting, showing this error:
Call to a member function compile() on null. What's wrong?

**Screenshots**

![image](https://user-images.githubusercontent.com/13145310/109311301-b4286980-7856-11eb-9bcd-66c832508fcd.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @merick2158 ,

I updated my shop from 1.7.3.4 to 1.7.7.2, the upgrade was successful and I have access to all pages of Advanced Parameters tab.
![Capture d’écran 2021-02-26 à 16 02 52](https://user-images.githubusercontent.com/16019289/109317174-bbe31080-784c-11eb-8c8c-e12e38c3372e.png)
![Capture d’écran 2021-02-26 à 16 03 46](https://user-images.githubusercontent.com/16019289/109317192-bf769780-784c-11eb-984f-4802a65242c8.png)

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
