### ISSUE TITLE
Trouble to translate multiple occurence of the same string in the same domain

### ISSUE THREAD

**Issue by e-gaulue** [PrestaShop/PrestaShop#23437]
#### Describe the bug

Translation is said to be validated. You've got the green popup right up the screen. But if you leave and come back or if you try to see the result you see translation has not changed.

#### Expected behavior

I don't know. Translation to be dealt or one unique field if ever the same string is twice in the domain.

#### Steps to Reproduce

1. Go to Translation and select backoffice
2. Search for "first name"
3. Select Admin > Global domain
4. You'll see the exact same string twice.
5. Try to change one and save
6. Leave translation
7. Redo 1-6 but change the other one
8. Redo 1-4 : you should notice just one of the two get changed

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

**Comment by florine2623** [comment]
Hi @e-gaulue ,

I managed to reproduce the bug in PS 1.7.7.2, 1.7.6.7 and 1.7.5.2.
When editing multiple fiels, every fiels of translation isn't saved after refreshing the page.
Before :
![Capture d’écran 2021-02-26 à 15 42 13](https://user-images.githubusercontent.com/16019289/109315747-2430f280-784b-11eb-9c27-99918f7233ef.png)

After :
![Capture d’écran 2021-02-26 à 15 45 23](https://user-images.githubusercontent.com/16019289/109315769-2c892d80-784b-11eb-8ac9-eb1d16f307ef.png)
![Capture d’écran 2021-02-26 à 15 49 54](https://user-images.githubusercontent.com/16019289/109315775-2e52f100-784b-11eb-9e88-6001f692ca81.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you
