### ISSUE TITLE
Invalid Security Token

### ISSUE THREAD

**Issue by MAramex** [PrestaShop/PrestaShop#23455]
Hello everyone,

Here is Mohammad from Aramex support team, we are facing an issue and we need your assist. 
In our shipping module “Aramex Shipping Module” we are facing an invalid security token problem,
this issue occurs in Prestashop 1.7.7.0 & 1.7.7.1.
We tried couple of solutions from our side but the problem still exist, we also checked whether
there is a change in the token but there is not.

If anyone could assist me with this one and thank you all.

![InvalidToken](https://user-images.githubusercontent.com/79833135/109502547-cc3ff900-7aa1-11eb-961e-1e639116c14f.png)

**Comment by hibatallahAouadni** [comment]
Hello @MAramex 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: it seems your issue is related to your module, so you may need help with it, please consider one of our [support plans](https://www.prestashop.com/support).

Thanks!
