### ISSUE TITLE
when I use the search engine, with some words I get error 500

### ISSUE THREAD

**Issue by Marcelozippo** [PrestaShop/PrestaShop#23469]
Hello when I use the search engine, with some words I get error 500.
I share video, also in the video is the debug screen.
https://drive.google.com/file/d/1GZCCqvZ7-WWt84zpIWVhr8hMn5l4zYTI/view
PHP 7.3
1.7.7.2
Maria 10.3
VPS
cpanel with engintron
warehouse
https://www.cotillonunpocoloco.com/

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @Marcelozippo 

I tried make a search on your web site and it works, see the attached screen record below:

https://www.awesomescreenshot.com/video/2918158?key=ba7cff4f2c25d97672fe6316cee23c49

And please next time **follow the provided template to submit a complete bug report**.
It seems your issue is random and not related to PS Core. 

So, I close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
