### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by chithraongithub** [PrestaShop/PrestaShop#23516]
When i click any category or brands form megamenu or from anywhere else it leads to  500 error.

when i check it on debug mode, it showing so many errors on 4-5 modules i'm using. There is so many warning in all module , i updated modules which i'm using in our store .But still the problem exist there. Debug error changes for each run.

I checked on the log file. There showing only one error :Invalid product vars at line 161 in file classes/Link.php
When this issue started from that day onwards it showing this error.

![Capture-3](https://user-images.githubusercontent.com/61942537/109926226-c7628b80-7cd3-11eb-90b8-1b75923b6dfb.JPG)
![Capture-2](https://user-images.githubusercontent.com/61942537/109926230-c893b880-7cd3-11eb-830b-6f394e7f440f.JPG)
![Capture-1](https://user-images.githubusercontent.com/61942537/109926233-c893b880-7cd3-11eb-8e55-66d2d0ef0aa8.JPG)

* PrestaShop version: N/A
* PHP version: N/A

**Comment by chithraongithub** [comment]
please help in this

**Comment by florine2623** [comment]
Hi @chithraongithub ,
Your issue comes from your module kbrelatedproducts.
Please deactivate it or contact the developer of the module.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by chithraongithub** [comment]
But for the next run after deactivating this module, it will shows error of different module. deactivating all modules which showing errors , then the debug mode will show errors of smarty template and cache files error.
 But on log file the error is the same (Invalid product vars at line 161 in file classes/Link.php)
