### ISSUE TITLE
Cannot create attributes

### ISSUE THREAD

**Issue by ced--ced** [PrestaShop/PrestaShop#23511]
#### Describe the bug

I cannot create attributes to products in 1.7.7.0.

#### Expected behavior

For attributes to be created.

#### Steps to Reproduce

1. Go to a product in the admin.
2. Go to the attributes tab.
3. Select the chosen attributes and click on Generate button.
4. Green message is given: the attributes are created.
5. Click on the general Save button to save the changes in the product.
6. Get red message saying it cannot save.
7. Refresh page or go back to product list, then back to the product: the attributes have not been created and saved.

**Screenshots**

https://prnt.sc/10ce3fk

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.34

**Comment by florine2623** [comment]
Hello @ced--ced ,

I can't reproduce your issue. Please see my screen record :
https://drive.google.com/file/d/1P62urPGA-TKQg56AacAKJHrfYW9L8zmm/view

If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by ced--ced** [comment]
@florine2623,

The problem is there on 2 websites I have on 2 different hosting!!!!

Googling in the Prestashop forums, others have had the problem as well but with no solution.

It's a bit hesty from you to close this post so quickly without digging any further!!!

If you can't, can someone else in the Prestashop tech team help?

**Comment by matks** [comment]
Hi @ced--ced this is not @florine2623 role to find out what exact setting or environment configuration is needed to find out why it does not work for you.

The problem can be observed on your server, then something on your server / shop setup is responsible for showing it. We are not going to try random server configurations to maybe find the issue.

**We are not here to help**. When you report a bug, you dont do this because you need help. You do this in order to raise awareness about this issue for all the project community, so that it can be fixed for the best of the project. If you need help, please follow https://devdocs.prestashop.com/1.7/faq/i-need-help/
