### ISSUE TITLE
Desactivated category still display in breadcrumbs

### ISSUE THREAD

**Issue by mkdgs** [PrestaShop/PrestaShop#23530]
#### Describe the bug

On a page of product with a categories path, deactivate one category.
The category still display in breadcrumbs

#### Expected behavior

The category must not appear in breadcrumb

#### Steps to Reproduce

1. Create a path of categories, add thoses to a product.
2. Show the product, with the path of breadcrumbs
3. Deactivate one category in this path
4. Clear all cache
5. The category still display in breadcrumbs of the product page

#### Additional information

* PrestaShop version: 1.7.X
* PHP version: N/A
Fix in pull request
#23528

**Comment by florine2623** [comment]
Hello @mkdgs ,

I was able to reproduce the issue with PrestaShop version 1.7.7.2. I’ll add this to the debug backlog so that it’s fixed.
![Capture d’écran 2021-03-04 à 18 12 15](https://user-images.githubusercontent.com/16019289/110002154-62c82080-7d15-11eb-9ce0-9ab5578adce0.png)
![Capture d’écran 2021-03-04 à 18 12 22](https://user-images.githubusercontent.com/16019289/110002165-6491e400-7d15-11eb-895a-1cab658615c7.png)


Thanks for the PR.

Thank you
