### ISSUE TITLE
Manual order creation - search for proudcts not working

### ISSUE THREAD

**Issue by Kaktusodlarn** [PrestaShop/PrestaShop#23548]
#### Describe the bug

When creating a manual order in BO the search of products fails with a 500 error, same result both with both product name and product reference. 

#### Expected behavior

Search using product namne or reference should return a result

#### Steps to Reproduce

1. Go to orders -> new order
2. Choose customer
3. Search a product 
4. Searching for products....... - no result returned - 500 error ini troublshooting mode

**Screenshots**

![image](https://user-images.githubusercontent.com/80204246/110241175-b58d1c80-7f4f-11eb-8853-38e47627b108.png)
![image](https://user-images.githubusercontent.com/80204246/110241471-40224b80-7f51-11eb-8ecb-6ee921ace8da.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.1 and 7.3 same result

**Comment by hibatallahAouadni** [comment]
Hello @Kaktusodlarn 

I didn't manage to reproduce your issue with PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1YhH-lP7qiWnXzkoYOaVztrxAXolx466m/view

Please check and feedback.
Thanks!

**Comment by Kaktusodlarn** [comment]
Did you also try with pack Products and Products with one or more attributes or combinations? 
Does the error message give you any indication of the origin of the problem?

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @Kaktusodlarn 

At first I encountred some cache issue while searching for product (pack) and after enabling the **Debug Mode**, the issue is gone. And just to be sure, I disabled the **Debug Mode** and I didn't encounter the cache issue again:

https://drive.google.com/file/d/1VjGrwwhJa-FWn95yx8ZoiTuSvl1IxPfl/view

So, I tried searching a pack product and a product with combinations and it works :wink: 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Kaktusodlarn ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
