### ISSUE TITLE
How to manually upgrade of the DB from 1.7.6.9 to 1.7.7.2.

### ISSUE THREAD

**Issue by Art3c** [PrestaShop/PrestaShop#23545]
Hi,

i still have the same problems that i cant upgrade ma PS. Still the same error. We it comes to the point that the upgrade of the DB should start it throws a error.

Upgrade problem to Prestashop 1.7.7.1 Cannot declare class PrestaShopBundle\Entity\Tab #22775

Is there any option to upgrade the DB manually? Both other options are crap. Lose all the store and seat up a new one with clean install or not to upgrade.

I would appreciate any help.

Gratings, Tilen

**Comment by matks** [comment]
Hi @Art3c there is no clear explanation of how to do the upgrade manually, the process is too complex.

I can however show you where to look to find it.

You will find the complete explanation of what is performed by the autoupgrade module in the documentation https://devdocs.prestashop.com/1.7/development/upgrade-module/ .

See the list of steps https://devdocs.prestashop.com/1.7/development/upgrade-module/upgrade-process-steps/ . You can find and apply the ones relevant for you. I think it will probably be step `UpgradeDb`. You will probably need to look at the code being run https://github.com/PrestaShop/autoupgrade/blob/dev/classes/TaskRunner/Upgrade/UpgradeDb.php because, as mentioned

```
UpgradeDb: This step does much more than you can think.

Its initial purpose is to run all the upgrade SQL files available in the install folder.
Then, it will run some additional steps, such as theme enabling, cache deletion, language update…
```

So it's not only the SQL scripts, it's also some setup and cleaning steps that you need to apply.

Note that there is also a CLI option https://devdocs.prestashop.com/1.7/development/upgrade-module/upgrade-cli/ . It allows you to run steps one at a time so you can "check" how the shop behaves between each step.

If however you have trouble upgrading, you might need an expert to look at your shop. PrestaShop provides [support plans](https://www.prestashop.com/support) for that.
