### ISSUE TITLE
Prestashop core shouldn't depends on vatnumber archived module

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#23544]
#### Describe the bug

There is code in the core that relay on vatnumver module to exclude vat on B2B.
https://github.com/PrestaShop/PrestaShop/blob/f6caa1cacfbfb326dce35ad643deedb354d65cf2/classes/helper/HelperForm.php#L305
it's required to replace this test by a hook or something more generic to be answered by other modules.

The Configuration::get('VATNUMBER_MANAGEMENT') or VATNUMBER_COUNTRY are only set by the archived vatnumber module and is used in many parts of the core.

A core feature that depends on an archived module is not clean.

#### Expected behavior

Keep vat calculation in the core but with a more generic way

* PrestaShop version: all

**Comment by wilva** [comment]
VAT calculation is an essential component, so I would welcome it if it was moved to core.

As it stands, it now only shows up as archived, without any indicators of why it was archived and what is the future plan on this IMO core feature.

**Comment by jeckyl** [comment]
Hi,
As the management of European VAT does not concern the rest of the world, it seems to me preferable to keep this in the form of a module.

**Comment by matks** [comment]
> VAT calculation is an essential component, so I would welcome it if it was moved to core.
> 
> As it stands, it now only shows up as archived, without any indicators of why it was archived and what is the future plan on this IMO core feature.

@wilva You will find the answer here https://build.prestashop.com/news/focusing-on-essential-modules/

**Comment by wilva** [comment]
Thank you @matks that's useful. 
Of course I'm not happy with the decision, but the decision has been made. 
Somehow I doubt that I can convince you guys at Prestashop that it is essential, at least for European shops.
I do understand the need for being able to focus on core functionality.

Those notes mention that there are compatibility issues with 1.7, do you also happen to know what those issues are?
I have used the module since long - including 1.7 - and apart from it disappearing on each update (which might be due to installatron and not Prestashop), don't have any compatibility issues that I am aware about.

Already forked the repository a while back and willing to spent time on fixing issues (within certain limits).

Thanks for working on Prestashop!

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

> A core feature that depends on an archived module is not clean.

Yes that's totally true.

Ping @PrestaShop/prestashop-core-developers is it safe to use an archived module in PS Core?

**Comment by matks** [comment]
Hi @hibatallahAouadni ; not it's not safe to use an archived module in the Core 😊  . I guess it's not an issue, but it definitely is not clean.

We need to perform a little cleaning of the code to remove all code related to vatnumber module now that it has been removed.

**Comment by wilva** [comment]
Hi,

@matks you said:
"We need to perform a little cleaning of the code to remove all code related to vatnumber module now that it has been removed."

But that means that the plugin will no longer function ??
Am I misunderstanding that? Is core another product perhaps?

So it would not matter if I would spent time on keeping the plugin up-to-date, the VAT functionality is dead.

**Comment by hibatallahAouadni** [comment]
Thanks @matks for the clarification :wink: changed to an improvement

**Comment by matks** [comment]
> Hi,
> 
> @matks you said:
> "We need to perform a little cleaning of the code to remove all code related to vatnumber module now that it has been removed."
> 
> But that means that the plugin will no longer function ??
> Am I misunderstanding that? Is core another product perhaps?
> 
> So it would not matter if I would spent time on keeping the plugin up-to-date, the VAT functionality is dead.

What will be removed from the Core can be moved into a module 😉  . If some hooks are missing, they can be added.

If someone is willing to maintain a VatNumber module, we will be happy to discuss with him and provide the needed extension points for this module (and any other VAT module) to function.

But keeping hardcoded statements in the core related to an archived module is not good.

**Comment by hibatallahAouadni** [comment]
> We need to perform a little cleaning of the code to remove all code related to vatnumber module now that it has been removed.

> But keeping hardcoded statements in the core related to an archived module is not good.

@matks So, shall we change the label to **`To Do`**?

**Comment by wilva** [comment]
Mathieu, thanks for you swift reply.

Understood.

As mentioned earlier, I am willing to spent time to maintain the VAT plugin.
But admittedly I know more about C++ and a number of other programming languages than I do about php and the Prestashop framework. I do not expect that to be a real problem though.

**Comment by jf-viguier** [comment]
@matks it's not clear : I hope that you will not remove the code that remove vat.
Imo you could keep VATNUMBER_* configuration variables (it's not module dependent) and calculation or add a new hook/override to manage this.

**Comment by matks** [comment]
> @matks it's not clear : I hope that you will not remove the code that remove vat.

Without doing an extensive summary of all the code we are talking about, I cant answer accurately. But the target for this issue will be:

**After we have done the cleaning, there must be no logic in PrestaShop that depends on VatNumber module being installed**.

However _every feature currently provided by a combination of the Core and the VatNumber module installed should be achievable by installing another Vat module_.

In other words: if we say that today "when I install VatNumber module in PrestaShop 1.7.7.2, it enables the following features:
- validate VAT numbers
- exclude VAT when B2B mode is enabled
- feature A
- feature B"

Then after we have done the cleaning, any module developer should be able to build a module that provides these 4 features, just like before.

I would love that we can achieve that by adding the right hooks. If we can make sure that a module can handle VAT with no need of logic into the Core, it's better. Because such hooks will give a lot of flexibility to any module.

If however we find some logic can go nowhere else than the Core, well... we'll have to find a workaround 😅 .

**Comment by jf-viguier** [comment]
OK, sounds good to me

**Comment by wilva** [comment]
Turns out that there are actually issues with the VAT module and 1.7.7.2.
It still adds vat even after adding a valid VAT number, I was sure I had tested it, but seems I somehow missed that. 
I then looked at what changed in core between my last correct working version 1.7.6.9 and 1.7.7.2 and that brought back memories of me working on accounting software for a client over a decade ago.

Made me realize that I don't want those memories.. and hereby am retracting my offer to work on the vat module. 
This is not my core business. 
I will find another solution, sorry for any hope I might have given and wish you all the best.

**Comment by jf-viguier** [comment]
@wicaksono can you explain what issues are you talking with 1.7.7 ?

**Comment by wilva** [comment]
Not sure what @wicaksono has to do with this thread, so I am assuming you mean me instead as my github name also starts with "wi".

It is what I said "It still adds vat even after adding a valid VAT number". Let me elaborate a bit.

IOW, a customer puts an item in the cart, goes to sign up, adds their company address -including a valid VAT number- and the price that is charged still includes VAT. What would be expected is that the VAT is no longer added to the price.
Tested on 2 separate shops.

**Comment by wilva** [comment]
FWIW, ran more tests and can now say that the problem was introduced in 1.7.7.0
Which tracks it down a little more.
Then I looked at what changed between 1.7.6.9 and 1.7.7.0, but there's soo many changes.. 
Tried a few ways on isolating where to look, but no success and I have no idea on where to look for patching this.

~~Starting to feel like that jumping ship and building a new shop is easier :*(~~ 
edit: Scratch that, was frustrated, I like PrestaShop and don't want to change to something else.

**Comment by wilva** [comment]
The problem appears to be that function getTaxCalculator in class VATNumberTaxManager in VATNumberTaxManager.php of the VatNumber module no longer gets called.
I have no idea why that is the case.

**Comment by matks** [comment]
Hi, I removed `Waiting for dev` label because there is no need for developer answer.

What needs to be done now is a careful developer exploration to find out all logic statements in PrestaShop that depends on VatNumber module being installed, and decide what to do about them.

**Comment by hibatallahAouadni** [comment]
Thanks @matks 
So, in order not to lose the issue, I added it in **[EPIC] B2B** :wink:

**Comment by jf-viguier** [comment]
Thanks @matks, you are certainly a careful developer

**Comment by matks** [comment]
Thanks @jf-viguier 😄  but I'm afraid I am already under a huge workload. The Product Team will give this topic a priority number and it will be done according to this number. Unless a community contributor wishes to invest his own time in this :)

**Comment by Bugfunder** [comment]
> The problem appears to be that function getTaxCalculator in class VATNumberTaxManager in VATNumberTaxManager.php of the VatNumber module no longer gets called.
> I have no idea why that is the case.

In my case it was caused by not finding the module `vatnumber `transplanted to `taxManager `hook in `classes/tax/TaxManagerFactory.php`

In 1.7.7.4 I do have the hook `taxManager `and the module `vatnumber `is transplanted to it. But I also have the hook `actionTaxManager `with no module transplanted to it. There is also hook alias `taxManager `to `actionTaxManager`. 

When `Hook::getIdByName('taxManager')` is called in `classes/tax/TaxManagerFactory.php`, it returns the `id` of the `actionTaxManager` hook, which has no modules transplanted to it.

Transplanting the module `vatnumber` also to the `actionTaxManager` hook resolved the issue.
