### ISSUE TITLE
"Expand all" button not working in the back office

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#23558]
#### Java-script error when trying to close categories tree
When trying to close a category folder, the folder does not close. An error will be displayed.
This issue can be seen in module ps_facetedsearch 

#### Steps to reproduce the behavior:

1. Go to module ps_facetedsearch
2. Click on button **Add a new template**
3. In the Categories option click the button "Expand All"
4. Try to close an category folder

**Error**
Uncaught TypeError: elem is undefined

**File causing error**
 /backoffice/themes/default/js/tree.js Line 255

#### Additional information

* PrestaShop version: 1.7.7.2
* ps_facetedsearch 
Version 3.5.0 > not working
Version 3.7.0 > not working
* Browsers
Chrome > not working
Firefox > not working

**Comment by hibatallahAouadni** [comment]
Hello @crezzur 

Thanks for reporting this issue.
I reproduce this issue only with FacetedSearch v3.7.0 and I didn't manage to reproduce it with v3.5.0, see the attached screen record below:

https://drive.google.com/file/d/15bHqbwdmkQ6m07Nrx6m8X2ebQILzrNy9/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by PierreRambaud** [comment]
I see you're not using the same PrestaShop version for Faceted Search v3.5.0, could you please retry with the same PrestaShop version you test for the v3.7.0?

**Comment by ghost** [comment]
**Prestashop version 1.7.7.2**
ps_facetedsearch 3.5.0 option not working
ps_facetedsearch 3.7.0 option not working

**Comment by hibatallahAouadni** [comment]
Hello @crezzur 

PS1.7.7.2 & `ps_facetedsearch` 3.5.0 => NOK
PS1.7.7.2 & `ps_facetedsearch` 3.7.0 => NOK

PS1.7.6.7 & `ps_facetedsearch` 3.5.0 => OK
PS1.7.6.7 & `ps_facetedsearch` 3.7.0 => OK

So the issue is not related to the module `ps_facetedsearch` but to PS Core.
Thanks @PierreRambaud for the clarification :rocket: 

Thanks!

**Comment by ghost** [comment]
Pull request made to resolve issue https://github.com/PrestaShop/PrestaShop/pull/23625

**Comment by hibatallahAouadni** [comment]
Thanks @crezzur for your PR :tada:

**Comment by Progi1984** [comment]
Fixed by #23625
