### ISSUE TITLE
Redesign of backoffice header and backoffice menu

### ISSUE THREAD

**Issue by bullmade** [PrestaShop/PrestaShop#23586]
## Redesign suggestion

I've really waited a long time for PrestaShop to redesign the not-so-pretty header and the even uglier navigation (sorry). But no progress so far, so i made a decent mockup myself.

### Design
![image](https://user-images.githubusercontent.com/16975198/110540262-8c72b480-8126-11eb-80b5-56c41983bff3.png)

Design can be seen in a browser here (not interactive, just an image):
https://xd.adobe.com/view/bae6a807-8f0c-41ee-8366-03e9e92f64e1-efb5/?fullscreen&hints=off

The design follows the PS 1.7 UI kit. The design also suggests some UX improvements. The main design improvements/changes are:

- Prestashop logo replaced with Preston icon.
- Simplified menu in consistency with the grey background.
- Placing the store name in the header - Was removed in 1.7 for some reason.
- Given the menu a bit more width
- Placing the notification bell in the left side, as it should! Was placed in the right corner after 1.7 - this aint facebook.
- Making the "Maintenance" mode clearer with a yellow background. Needs to be clear cut that the store is in maintenance.
- Putting much more focus on the search, giving it the rest of space in the top header. Could even get some more improvements.
- Material icons have been maintaned, for good reasons - althought there are prettier font libraries like Feather Icons - which would however create inconsistency with other menus added by external modules.
- Added padding and spacing in the left and right side - let the elements breath

Other improvements to consider:
- Putting the name of the employee in the top (as it was in 1.6)
- Putting the profile picture of the employee in the top (as it was in 1.6) - creating a more personal dashboard

In reality, its not alot of change.

### Implementation

I would also like to make the actual css implementations and make a pull request - but i'll only do so if the design gets a green light from the community or from PrestaShop. Otherwise it's just going to be another pullrequest leftover.

This is not a bug, but an improvement, so it needs consensus from PrestaShop.

### Single elements

Header (without tabs)
![image](https://user-images.githubusercontent.com/16975198/110540474-d5c30400-8126-11eb-8f63-ca7305a13456.png)

Navigation
![image](https://user-images.githubusercontent.com/16975198/110540543-e96e6a80-8126-11eb-956c-fd5417a8b6b9.png)

###  Alternative design
![image](https://user-images.githubusercontent.com/16975198/110541389-f770bb00-8127-11eb-869f-e80d88861318.png)

Alternative design with focus on Quick Access menu. Would require additional development to let the use add an icon to each menu. Menu name would appear on hover. Only visible on desktop/tablet.

![image](https://user-images.githubusercontent.com/16975198/110604634-95946d80-8188-11eb-8c0f-a46e191d469d.png)

#### Single element navigation with Quick Access focus
![image](https://user-images.githubusercontent.com/16975198/110605580-8e219400-8189-11eb-909a-3e0b7a6e9cca.png)

**Comment by hibatallahAouadni** [comment]
Hello @bulldesign 

Thanks for the design and the specifications :clap: :rocket: 
Let's ping the Product Team :wink: Stay tuned!

Ping @PrestaShop/product-team @PrestaShop/ux-team we have a new design proposal, enjoy it :wink:

**Comment by bullmade** [comment]
Nice 👍 
I updated the post with some other alternative versions, one which is focused on the Quick Access menu.

**Comment by dialt0n3** [comment]
I dig it

**Comment by prestascott** [comment]
Hello @bulldesign,

Thank you for your work, it’s really nice to get design contributions like this in the back office. 🙌
What you propose is really interesting, enlarging the menu, placing the store in the header, creating a more personalized back office by putting name and profile picture in it, etc.

Each of your improvements needs to be studied in detail because we can’t decide quickly to give the menu a bit more width like you said. It will impact all of the back office pages because if we do so, then some contents will be tightened. For example, enlarging menu size by 64px means reducing cards size by 64px. I guess this might be a nice thing to do, but we first have to test the menu on other pages to see if there are any issues we don’t see at the moment.

Also, there’s some of your explanations that I don’t understand and I think discussing with you about it would be better and more productive. For example: “Placing the notification bell on the left side, as it should! Was placed in the right corner after 1.7 - this ain’t facebook.” I don’t really understand why the notification bell should be placed on the left? All actions are grouped on the right side of the menu (debug mode, view my shop, notifications, merchant expertise), what would you separate them and put some actions on the opposite side? Yes PrestaShop isn’t Facebook obviously, but does it mean we can’t put notifications on the right side? 
This is why you either give more explanations on the issue or discuss with us in detail so we can understand better.

Thanks for your suggestion, it's not everyday we have designs suggestions. PrestaShop Product team should work on “How to contribute in design”. So every designer could provide design on any issue according to the PreastaShop expectations and best practices. But for this step to happen, we need first a strong Design System. We will keep all of your ideas and study them in detail for a potential back office redesign. But for now, we can’t do any redesign because we don’t have a solid Design System, so it will be hard to consider revamping design project.

Thank you again! ✌️

**Comment by bullmade** [comment]
Hi @prestascott 
Thanks for reverting back, and nice that you like it. I will try to explain some of the points you have mentioned.

Increasing menu width:
Yes, true that a width increase will impact the size of the other elements. I tried to analyze the card content quickly, and for smaller and larger screens, most of the time there seems to be a good gap, that would protect the card from "deforming" in a bad manner.
![image](https://user-images.githubusercontent.com/16975198/114991779-44b81900-9e9a-11eb-8105-19cf0024cc72.png)

Regarding the notification bell:
The main actionarea for the merchant belongs to the left side of the screen, where the menu is placed.
Placing it on the left or right is not a big deal, but the fact that the mouse area of the merchant would mostly be on the left side of the screen, given the placement of the navigation/menu, then it would make it easier for the merchant to have the notification bell in the left side aswell.

If you did a heatmap on the backoffice, it would give more insight.

Is there a roadmap on making a design system for the backoffice?
Can we expect something in 1.7.8.x, or will we have to wait longer?

**Comment by NeOMakinG** [comment]
@prestascott What means the UX ✅  on this issue? Because I think it's not validated yet

**Comment by prestascott** [comment]
@NeOMakinG It means that i replied, but I can remove it

**Comment by NeOMakinG** [comment]
@PrestaShop/ux-team @PrestaShop/product-team What should we do about this issue? We can't just let it open without any active discussion :/

**Comment by bullmade** [comment]
Its a shame this request was not considered for PrestaShop 8.0 @prestascott @hibatallahAouadni 

Is there any UI improvement of the backoffice navigation in 8.0?

**Comment by matks** [comment]
Hey @bullmade 

I will answer with that quote of Adam Wathan: [https://twitter.com/adamwathan/status/1381275398646927362](https://twitter.com/adamwathan/status/1381275398646927362)

*"One of the most stressful parts of product development (especially open source) is when people are frustrated you haven’t made the improvement they want and automatically attribute it to complacency or ignoring the community instead of just being completely buried in work to do.*

*If something important takes two years to get worked on, it’s usually because there are two years worth of other fires to put out and work that’s necessary for pure survival. Things taking a long time is more stressful for me than it is for you, I promise. We’re on the same side."*

Unfortunately it's exactly the same for us. We're buried in work to do. So please dont say "it's a shame" or press us :( . Just like Adam Wathan said: things taking a long time is more stressful for us than it is for you.

**Comment by bullmade** [comment]
Hey @matks 

All you guys really had to do was to tell me to start on the project, or maybe engage in the design process. I was and am still ready to implement it.

I clearly stated this in the first post:
_I would also like to make the actual css implementations and make a pull request - but i'll only do so if the design gets a green light from the community or from PrestaShop. Otherwise it's just going to be another pullrequest leftover._

I wouldn't want to start on it if it weren't going to be considered by PrestaShop since it is not a bug, but _just_ a design improvement.
I realize you are busy, but i don't think taking a few discussion hours from the UI team would have hurt anyone. @prestascott gave alot of good feedback, but that was all. PrestaShop has a UI kit, that should be more than enough. No one asked for a complete backoffice design, it was simply the existing structure and design of the navigation. That can't justify waiting for a whole new design system.

I have to state again that it is indeed a shame, not for PrestaShop, but for the merchant. It would have been great to show the merchant you are reorganizing their navigation on their backoffice.

IMO, offering the merchant a better backoffice navigation and structure is probably the **only thing** that will give real and direct impact for 99% of the merchants. Tell me a single PrestaShop merchant who is not using the backoffice navigation?

Yes, PrestaShop is open source, but help us so that our PR's dosent go in vain.

**Comment by matks** [comment]
@bullmade Thank you. This 2nd answer is a lot more constructive than the previous one 👍 

> All you guys really had to do was to tell me to start on the project, or maybe engage in the design process. I was and am still ready to implement it.

I am not UX designer but my guess is that they are so buried with work to do that even this they can't do it. You used the right word: "engage". Starting this project means starting to design, means starting discussions, means questions will arise, means decisions will need to be explored and taken.

If I am not wrong @prestascott is no more working on this project, @TristanLDD is in charge now. Let's see if we can make this move on.

ping @TristanLDD

**Comment by ElodieOS** [comment]
Hi @bullmade! 

I'm replacing prescott and working with @TristanLDD to improve the design of open source. 

I've read all the discussions and I agree with prescott, it's a good proposal and we're really happy that people get involved in the design and contribute to it. 
Unfortunately, we can't make a decision easily. Here, we have a good proposal for sure, but it’s not user tested. All important issues like this need to be verified by testing and interviews with users. This work is really long.

I understand that it can be frustrating. For us too. But we can't make a decision without a thorough study. Every change has an impact on a large number of users. 
So, we thank you for your contribution and we hope it didn't demoralize you to contribute, but now we have to go step by step to build a solid tool. 

The next steps for us are to test the navigation and header, see what can be done and prioritize all issues to fix bugs and improve the platform in the long term.

**Comment by bullmade** [comment]
@ElodieOS thanks for the update.
The changes are quite insignificant, it's a bit vague to say it needs thorough study. It's simply a design improvement, and not a refactoring of anything other than simple visual improvement.

I hope you aren't implying that the current navigation has been usertested.

Im not saying you should implement the design we proposed, but it is indeed a big demoralization to see that absolutely nothing has happen to the design of PS 1.7 since its initial launch in 2016.
If this is a question of priority on bugs vs design, i must assume that the design will keep the way it is forever, because nothing happend to the PS1.7 backend design for 6 years so far, and i should rightly assume that nothing will happen with it anytime soon from 8.0?

It's sad to see this is the way PrestaShop prioritizes backend UX, the place that the merchant spends 95% of their time on the store..... but i guess i've already said too much.

**Comment by ElodieOS** [comment]
For sure @bullmade, UX it’s a priority. In our studies, retailers don't talk about an actual navigation problem. That doesn't mean we can't improve it. Just we can prioritize an another issue for the moment. 
You said it would have been great to show the merchant you are reorganizing their navigation on their backoffice. But why is that important now? Do you have any data or use cases that show the importance of this issue now? That's a real question, maybe we missed something and we didn’t see the difficulties of our users on this topic.

**Comment by bullmade** [comment]
@ElodieOS ive previously offered our full help to make the design + make a PR for it, so that PrestaShop does not have to put development resources into it. But there is no reason to start it if PrestaShop does not show any signs of willingness to look into the issue, or to cooporate on it.

I agree with you that the backoffice design in general is not a "crucial" issue/bug/feature or for that sake, improvement, but if PrestaShop only keeps focusing on crucial and high alert issues, and only has done so for the backoffice for the last 6 years, will there ever be resources to start with the "nice to have" features (or so called less important low-priority features)? I doubt it. If the core team is just in "alert" mode all the time, and only focuses on all high priority for the backoffice, then i doubt anything will happen to the backoffice. Design standards evolve all the time, and i think everyone would have a hard time arguing that the backoffice layout and design is today as good as it was 6 years ago.

I understand that the backoffice is not the most important thing, but the same way that PrestaShop focuses on a new frontend theme with PS 8.0 (Hummingbird), the same arguments can be put into the backoffice design.

Apart from that, till this day it is still not possible to customize the navigation in 1.7. This feature was removed in 1.7. In v.1.6,  the merchant was able to remove any unwanted menu that some modules forced into the backoffice. Being able to edit, add and reorganize the menu saves time and clicks for the merchant - as obviously, the importance of menus differs from merchant to merchant.

PrestaShop decided to remove the menu for this reason: "This page was deleted in 1.7.0 because merchants were removing menus and then didn't know how to re-add them because don't know how to find th the controller name."
https://github.com/PrestaShop/PrestaShop/issues/21107

That is just one of many examples where the core team decided to remove functionality instead of being solution-oriented. A good example of how "unwanted deleting" is handled is in the core statusses (payment accepted, etc), where there are specific ID's that cannot be deleted. I can't tell for sure why such thing was not done instead, but nevertheless, removing the ability to change menus has not made the backoffice better, if anything, just less bad - and thus, no real improvement.

**Comment by marianhlavac** [comment]
To the Prestashop team: **this really was a missed opportunity**.

I really like the proposed design by @bullmade, because it was "reasonable" and it didn't propose a complete overhaul of the backoffice UI (which would be unreal & very expensive to do). It's just a little touch and CSS tweaking to keep the project's design contemporary. Currently, the backoffice UI looks like 10-20 years old. Seriously. I'd love to have this design in 2010. Not today.

Prestashop is 16 years old, and it really starts to "feel old". It's not keeping up with modern admin UIs and I can expect only more and more people will be thinking in the same way as I do.

**Comment by ElodieOS** [comment]
Hello @marianhlavac 
Yes, as we said, we also like bullmade's proposal. It's a fact: the Prestashop interface has become obsolete and we know it. With the rebranding, we have worked and are still working on design changes to the interface. You can see the first results on the PrestaShop Edition Basic. The open-source project will follow this style in the future. However, some technical elements must be reviewed to be able to apply the design to the OS project. 

<img width="1418" alt="Capture d’écran 2023-09-21 à 14 58 48" src="https://github.com/PrestaShop/PrestaShop/assets/113457393/924db904-c222-4454-a021-f7d342791a1c">

**Comment by marianhlavac** [comment]
Didn't know about the basic edition, we've been always working with the open-source version. Thanks for the update. The UI on the screen looks promising, I'm looking forward having this UI in the OSS!

**Comment by matks** [comment]
> Didn't know about the basic edition, we've been always working with the open-source version. Thanks for the update. The UI on the screen looks promising, I'm looking forward having this UI in the OSS!

PrestaShop Basic Edition is the ZIP you can download on https://prestashop.com/ and it's open source too 😉 same license as the Core. It's simply a different of flavor of PrestaShop, you can start using it tomorrow

**Comment by marianhlavac** [comment]
@matks This updated UI is already available in the Prestashop Basic Edition, or it's something coming up later?

**Comment by matks** [comment]
It's already available

**Comment by matks** [comment]
> I'm looking forward having this UI in the OSS!

@bullmade Hello, it's done on `develop` branch now. I close the issue then 😉
