### ISSUE TITLE
Keep the category tree expanded

### ISSUE THREAD

**Issue by Braian70** [PrestaShop/PrestaShop#23580]
#### Is your feature request related to a problem?

After applying a filter by category in the BO product list, if you wan to change the filter for another category you have to click on each category to open the tree.

#### Expected behavior
Keep the category tree expanded to the selected category

#### Steps to Reproduce

1. Go to Catalog > products
2. Click on 'filter by categories'
3. Choose category, it works fine
4. If I want to select another category, I have to open category one by one

#### Screenshots

![52656565](https://user-images.githubusercontent.com/80336133/110494133-93340400-80f3-11eb-9195-d125994dc678.PNG)
![64456+56](https://user-images.githubusercontent.com/80336133/110494134-93cc9a80-80f3-11eb-90fd-baa77db1480f.PNG)

#### Additional information

- PrestaShop version: 1.7.6.1
- PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @Braian70 

> 4. See error ： Before category is expand into third category, so save a lot of time.

Could you please explain more this point :pray: 
Please check this screen record below and tell me where the issue exactly:

https://drive.google.com/file/d/1-isPYV2KCQtdr9CvzkaS5QDJ0KTmDzhV/view

PS: I know it shows 1.7.7.2 in my screen record, but it's ok, I just need to figure out the issue :wink: 

Thanks!

**Comment by Braian70** [comment]
Thank you for answering.
I always work with a lot of category, if I choose the category that I want, then I want to choose another category, I have to select from the beginning, so I waste a lot of time, before with 1.6, chosen category continues to maintain panel.


Example: enter category iphone 11 case, I need 4 click, okay, now I want to enter iphone x case, again 4 click, before in 1.6 category it is always open, only change 1 click, I always have to spend more time than before.
![error 1](https://user-images.githubusercontent.com/80336133/110527740-a1941700-8117-11eb-9d93-8c533172417f.PNG)
![error 2](https://user-images.githubusercontent.com/80336133/110527743-a22cad80-8117-11eb-8cf3-bdb4acfe32d3.PNG)
![error 3](https://user-images.githubusercontent.com/80336133/110527746-a22cad80-8117-11eb-91eb-0cbb1f4700d3.PNG)
![error 4](https://user-images.githubusercontent.com/80336133/110527749-a2c54400-8117-11eb-83db-b3272bca18b1.PNG)
![error 5](https://user-images.githubusercontent.com/80336133/110527750-a2c54400-8117-11eb-8f63-4e41b0837c83.PNG)
![error 6](https://user-images.githubusercontent.com/80336133/110527752-a35dda80-8117-11eb-9196-c493cac11a5c.PNG)
![error 7](https://user-images.githubusercontent.com/80336133/110527753-a35dda80-8117-11eb-9eca-2e57a51f9b31.PNG)
![error 8](https://user-images.githubusercontent.com/80336133/110527755-a35dda80-8117-11eb-8b23-15fb61bff028.PNG)

**Comment by hibatallahAouadni** [comment]
Hello @Braian70 

What you suggest is an improvement and not a bug :wink: 
You suggest to adopt the same structure of Categories tree that we use to have with PS1.6:

![search_cat_1 6](https://user-images.githubusercontent.com/23308427/110697248-5f88d500-81ec-11eb-949e-aac97308bc72.png)

But, I notice that with PS1.7.7.0 and PS1.7.7.2, when we select a category to search and then we reopen the categories tree, the chosen category is not selected, see the attached screenshot below:

![search_cat_1 7](https://user-images.githubusercontent.com/23308427/110697436-a5459d80-81ec-11eb-9fd4-7a521b9a4bf6.png)
 
While, with PS1.7.6.7 I didn't reproduce the issue, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/110698226-aa571c80-81ed-11eb-8636-e42dc42c7008.png)

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by marionf** [comment]
Hello @hibatallahAouadni This issue isn't very clear, is it an improvement or a bug ?
Could you please udpate the title of the issue and the steps to reproduce the issue in the first comment and attach a screenrecord ?

**Comment by hibatallahAouadni** [comment]
Hello @marionf 

@Braian70 ask to change the **Filter by category** behavior as PS1.6:

1. BO>SELL>Catalog>Products
2. Click on **Filter by category**
3. Select a category
4. The list of products whose belong to the selected category is well displayed =>OK
5. Click on **Filter by category**
6. The tree is not expanded displaying the selected category => it's regression of PS1.7
7. The selected category is not selected in the tree => NOK => it's a regression of PS1.7.7.0

https://www.awesomescreenshot.com/video/3221596?key=8ead019929db71ff76bb1c9268b1f4d7

So, what do you think? shall we treat the two issues in this ticket or shall I open a new issue for the second issue (regression of 1.7.7.0) and leave this one as an improvement?

**Comment by marionf** [comment]
Hello @Braian70 

If I understand well your request, you want to have the category tree expanded to the category that is currently selected when you click on "filter by category" ?
I tried to rewrite your request improvement because it wasn't very clear :)

Did you see the "expand" button allowing to open the whole category tree in one click ?
This saves you from having to click on each category

**Comment by hibatallahAouadni** [comment]
Hello @Braian70 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
