### ISSUE TITLE
Ecotax BO + Invoice

### ISSUE THREAD

**Issue by Ideoclic** [PrestaShop/PrestaShop#23618]
#### Describe the bug

Problem calcul ecotax Invoice + ecotax BO !

#### Expected behavior

When calculating the price on the invoice, this is wrong! I take this product as an example (Screenshot),  normally the price should be tax excluded and not VAT in BO for product..

**Screenshots**

![produit](https://user-images.githubusercontent.com/80488574/110856384-dd65e280-82b7-11eb-88cf-d882834aa084.png)

**Normally the product therefore costs 17.73 + 0.12 (ecotax) so 17.85 Tax Excl**

**BUT in my invoice is :** 

![ApplicationFrameHost_Kqph3qNfq3](https://user-images.githubusercontent.com/80488574/110856698-45b4c400-82b8-11eb-9296-30e3708eacff.png)

And 17.85 x 3 = 53.55 and not 53.56

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @Ideoclic ,
If you want the product to show without tax, you should choose "No tax" :
![Capture d’écran 2021-03-12 à 09 26 09](https://user-images.githubusercontent.com/16019289/110913125-06689080-8315-11eb-8e31-26919fafe19c.png)
![Capture d’écran 2021-03-12 à 09 26 00](https://user-images.githubusercontent.com/16019289/110913140-09638100-8315-11eb-9d14-f04111f8d17f.png)

Please check and feedback

**Comment by Ideoclic** [comment]
My invoice : I want taxe

![ApplicationFrameHost_V99XXnINuI](https://user-images.githubusercontent.com/80488574/110913742-cb1a9180-8315-11eb-947f-6378a76948cd.png)

**Comment by florine2623** [comment]
I can't reproduce your issue :
![Capture d’écran 2021-03-12 à 09 52 59](https://user-images.githubusercontent.com/16019289/110916130-c3a8b780-8318-11eb-831a-eaa806fd8b95.png)

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**Comment by Ideoclic** [comment]
For you is it normal that 17.85x3 = 53.56?

**Comment by matks** [comment]
Hi @Ideoclic actually, yes, it can happen that 17.85x3 = 53.56 .

It might sound crazy 😄  but it's because what is actually stored in your shop is not 17.85 .

17.85 is likely what is displayed to you because only 2 decimals are shown. But in the database, we store a lot more decimals are they are needed for accurate computations.

Here is an example.

If your product price is actually 17.854€ because it was computed from some way (like a tax applied, which explains the 4 at the end)
It might be displayed as 17.85 in your shop, but when you multiply it by 3 it becomes 53.562 which will be displayed... 53.56 in your shop 😄  .

So you might have 2 different shops, and in one 17.85x3=53.55 and in the second shop 17.85x3=53.56 **and both shops are working as expected**. Because you are not seeing the true numbers, only the truncated numbers, formatted for rendering.

I believe you can configure how the rounding is done. See http://doc.prestashop.com/display/PS16/General+Preferences

**Comment by Ideoclic** [comment]
Hey !

I understand your point of view, and how can we only have 2 decimal when adding a product? Because for this product is 17.33333
