### ISSUE TITLE
Customer Data Privacy module

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#23708]
#### Describe the bug

The module Customer data privacy are default installed in the version 1.7.7.2
But that module aren't need with the module GDPR installed.
When you uninstall the module Customer Data Privacy this give you one error and don't uninstall

#### Expected behavior

Delete the module without problem

#### Steps to Reproduce

1. Go to 'modules in prestashop 1.7.7.2 clean install'
2. Click on 'data privacy costomer'
3. select delete

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @TecnoHands 

Thanks for your issue!
I manage to reproduce your issue with PS1.7.7.0 and PS1.7.7.2, see the attached screen record below:

https://drive.google.com/file/d/1cCSXZKUiwJReeAYui1txbV_9u2S9uwBJ/view

I didn't reproduce with PS1.7.6.7, so it's a regression.
With PS1.7.7.2, I can't disable and uninstall the module. With PS1.7.7.0, I can disable the module but I can't uninstall it.

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by TecnoHands** [comment]
If anyone like to uninstall it in prestashop 1.7.7.2
1. Delete the directory ps_dataprivacy from /modules/
2. Search in the database %dataprivacy and delete from all tables where this appears

I deleting it with this metodology and don't found problems after delete it

**Comment by atomiix** [comment]
This should be fixed when https://github.com/PrestaShop/ps_dataprivacy/pull/21 will be merged (and released)
