### ISSUE TITLE
Custom Upload Product Fields

### ISSUE THREAD

**Issue by Dreimus** [PrestaShop/PrestaShop#23701]
Hello there, 

The main backoffice product form does not currently allows FileType  because the ajax process serialize data which does not handle uploaded files.

https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js#L637

I suggest to switch from serialization to formData handling to allow FileType to be added as custom fields.

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

What's your opinion on that ?

Thanks!

**Comment by PululuK** [comment]
Hi @florine2623 @Dreimus 

I will just add some details to help @PrestaShop/prestashop-core-developers  and QA team !

## Context

Some modules use the follows hooks to add custom fields in product catalog form.

- displayAdminProductsExtra
- displayAdminProductsMainStepLeftColumnMiddle
- displayAdminProductsMainStepLeftColumnBottom
- displayAdminProductsMainStepRightColumnBottom
- displayAdminProductsQuantitiesStepBottom
- displayAdminProductsPriceStepBottom
- displayAdminProductsOptionsStepTop
- displayAdminProductsOptionsStepBottom
- displayAdminProductsSeoStepBottom
-  etc etc

And use follows hooks to process their custom datas after product form submit 

- hookActionAdminProductsControllerSaveBefore
- hookActionAdminProductsControllerSaveAfter
- hookActionProductUpdate
- etc etc

## Limitations (or issue ?)

When submitting the product form, the modules received all their data, except for 'file' type fields,
this is because you can serialize input files datas, see https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js#L637

Modules therefore obliged to process file type fields in a separate request.

## How to reproduce quickly ?

You can reproduce it without module, follow the steps below :  


#### 1 - Add custom fields in template 

Edit this file [src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/essentials.html.twig]( https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/essentials.html.twig#L104) just before :
```twig
{{ renderhook('displayAdminProductsMainStepLeftColumnMiddle', { 'id_product': productId }) }}
```
And add this html code : 
```html
<div id="mymoduleproductcustomfields" class="row mb-3">
   <div class="col-md-12">
      <h2>Champs complémentaires</h2>
   </div>
   <div class="col-lg-12">
      <fieldset class="form-group">
         <label class="form-control-label">My custom field TextType</label>
         <div class="translations tabbable" id="mymoduleproductcustomfields_project_desc-title">
            <div class="translationsFields tab-content">
               <div data-locale="pt" class="translationsFields-mymoduleproductcustomfields_project_desc-title_1 tab-pane translation-field show active translation-label-pt">
                  <input type="text" id="mymoduleproductcustomfields_project_desc-title_1" name="mymoduleproductcustomfields[project_desc-title][1]" class="form-control">
               </div>
               <div data-locale="us" class="translationsFields-mymoduleproductcustomfields_project_desc-title_2 tab-pane translation-field translation-label-us">
                  <input type="text" id="mymoduleproductcustomfields_project_desc-title_2" name="mymoduleproductcustomfields[project_desc-title][2]" class="form-control">
               </div>
            </div>
         </div>
      </fieldset>
   </div>
   <div class="col-lg-12">
      <fieldset class="form-group">
         <label class="form-control-label">My custom field FileType</label>
         <style>
            .custom-file-label:after {
            content: "Browse";
            }
         </style>
         <div class="custom-file">
            <input type="file" id="mymoduleproductcustomfields_project_desc-img" name="mymoduleproductcustomfields[project_desc-img]" required="required" class="custom-file-input" data-multiple-files-text="%count% file(s)" data-locale="pt">
            <label class="custom-file-label" for="mymoduleproductcustomfields_project_desc-img">
            Choose file(s)
            </label>
         </div>
      </fieldset>
   </div>
</div>

```

Make sure you have something look  (don't forgot to clear cache)

![custom_fields](https://user-images.githubusercontent.com/16455155/111812764-b2434a80-88d8-11eb-86ae-2569c5aebd22.jpg)

#### 2 - Check product controller data process 

Edit this file [src/PrestaShopBundle/Controller/Admin/ProductController.php](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/ProductController.php#L442)

And add this code in `formAction` method

```php
   var_dump($_REQUEST);
```

- Go to backoffice product catalog form
- Open you browser network tools
- Save your product et inspect the request response (see the screen below )
-  See you have `project_desc-title` data, but is missing `project_desc-img`

![debug](https://user-images.githubusercontent.com/16455155/111815965-8f1a9a00-88dc-11eb-94c9-e03a599d5e27.jpg)


## Additional infos 

in my case I managed to get around in the following way : 
In this file  https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js#L637

replace 

```js
var data = $('input, textarea, select', elem).not(':input[type=button], :input[type=submit], :input[type=reset]').serialize();
```
by

```js
var  data = new FormData(elem[0]);
elem.find('input[type=file]').each(function(index, field){
        data.append(field.name, field.files[0]); 
});
```

and add these options in ajax request 

```js
processData: false,
contentType: false,
enctype:"multipart/form-data",
```

**Comment by kpodemski** [comment]
@PululuK @Dreimus since the old product page is no longer supported, could you try to check this on the new product page?
