### ISSUE TITLE
[ps_emailalerts] Cannot translate the mail subject

### ISSUE THREAD

**Issue by ibeppo993** [PrestaShop/PrestaShop#23748]
in prestashop 1.7.3 the translations do not work, and I still have the default English language.
it can be fixed?
thanks

**Comment by hibatallahAouadni** [comment]
Hello @ibeppo993 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17810. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #17810

**Comment by matks** [comment]
@hibatallahAouadni ps_emailalerts and mailalerts are 2 different modules 😉 

https://github.com/prestashop/mailalerts
https://github.com/prestashop/ps_emailalerts

mailalerts is now archived. I think it was a module for PS 1.6 only. Can I suggest we close https://github.com/PrestaShop/PrestaShop/issues/17810 because the module mailalerts has been archived but we keep this bug report open?

**Comment by hibatallahAouadni** [comment]
Thanks @matks for pointing to this labels conflict.
So, for the issue #17810 is about **`ps_emailalerts`** with PS1.7 and not **`mailalerts`**, I changed the label in that issue :wink: 

And as I discussed with you, @eternoendless and @marionf I'll replace all the labels **`Mailalerts`** with **`ps_emailalerts`** and then delete the label **`Mailalerts`**.

Thanks again @matks :rocket:

**Comment by kmorgen** [comment]
Has this been reopen and/or still in debug backlog?

Seems in Mail Alerts V2.3.0 (ps_emailalerts) and PS 1.7.7.4 it is still not possible to translate e-mail **SUBJECT**.

**Comment by matks** [comment]
> Has this been reopen and/or still in debug backlog?
> 
> Seems in Mail Alerts V2.3.0 (ps_emailalerts) and PS 1.7.7.4 it is still not possible to translate e-mail **SUBJECT**.

Still open => https://github.com/PrestaShop/PrestaShop/issues/17810
