### ISSUE TITLE
Enable to back to shop in admin login page

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#23775]
## Is your feature request related to a problem?

when you arrive on the admin page by mistake, it will be interesting to have the possibility of coming back to the site (this often happens for administrators.)

## Describe the solution you'd like

Enable to back to shop in admin login page.
Only the “back to my shop” will be changed and placed on the top left corner of the page:

![image](https://user-images.githubusercontent.com/23308427/140721277-3291aedd-17e9-4a83-9337-7a8983c03453.png)

**Comment by MatShir** [comment]
Good idea 👍 
@prestascott What do you think of the @PululuK design ?

**Comment by prestascott** [comment]
Hey everyone,

Thanks @PululuK, can you develop why administrators are often brought to this login page please?

In fact, this is a great feature and it would avoid them to re-type their logs to reconnect. Thanks!

I suggest to place the "Back to My Shop Name" link on the top left corner of the page since it's more identifiable. 
Also because users will tend to look there when they want to go back to a previous page. 

See my design proposition:
![23775 - mockup](https://user-images.githubusercontent.com/54888056/112615902-5e2dee00-8e23-11eb-81fb-91fa7aaa4e61.png)

Wdyt?

**Comment by Progi1984** [comment]
@PululuK I reopen the issue as the design needs to be fixed.
