### ISSUE TITLE
CartController smarty context 'cart' is override by FrontController

### ISSUE THREAD

**Issue by valentinchevalier** [PrestaShop/PrestaShop#23816]
## How I discover the issue

When I add a gifted product to cart, it is not considered as a gift in cart template. 

## Why it's not working
I investigate and I found the following explanation : 

`CartController::initContent()` is assigning to smarty a cart value that use the cart presenter with the flag `shouldSeparateGifts` to true ([here](https://github.com/PrestaShop/PrestaShop/blob/bae0db4dee1858ae0a505d2a0fc612e2c427bf6c/controllers/front/CartController.php#L109))

Then `CartController::initContent()` calls `FrontController::initContent()` that re assign a 'cart' value to smarty ([here](https://github.com/PrestaShop/PrestaShop/blob/046246c460e4467e73e5833cebf23b99bab10868/classes/controller/FrontController.php#L501)) without the `shouldSeparateGifts` flag.

So the smarty `cart` variable is not set as expected.

#### Additional information

* PrestaShop version: 1.7.7

**Comment by hibatallahAouadni** [comment]
Hello @valentinchevalier 

Could you please provide clear and consice steps to reproduce the issue. 
Please **respect and follow the provided template to submit a complete bug report**. We provide this template because we need all the information mentioned.

Please edit your issue and notify me.

Thanks!
