### ISSUE TITLE
X number of decimals are only displayed if the product price has X decimals

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#23868]
#### Decimals for currencies not working on PresstaShop 1.7.7.3

I've set the Decimals for Omani Rial to **3**:

![Screen Shot 2021-04-01 at 4 01 29 PM](https://user-images.githubusercontent.com/20775532/113353787-cc7f1e80-9303-11eb-9e68-1ba4833c4612.png)

But it's not working:

![Screen Shot 2021-04-01 at 4 04 32 PM](https://user-images.githubusercontent.com/20775532/113353915-fc2e2680-9303-11eb-96f9-5c7d5d92b900.png)

I've also cleared the cache (removing **_var/cache/prod - dev_**), but the problem persists.

**Comment by samberrry** [comment]
this is the same for dollar and any other currency.

**Comment by efranklin94** [comment]
I have the exact same issue with the decimal points in prices of my products. It will not change if you for instance change the decimals from 2 to 3, it will show two decimal points, like (2.45) instead of (2.450).

**Comment by florine2623** [comment]
Hello @sam-beri @eeffathi 

X number of decimals are only displayed if the product price has X decimals.
If produce price is **10.325€**, it will show **3 decimals**
If product price is **15.66€**, it will show **2 decimals**
The extra 0 won't be added to match the number of decimals chosen in configuration
Tested with multiple currencies, the result is the same.

![Capture d’écran 2021-04-02 à 10 15 00](https://user-images.githubusercontent.com/16019289/113396892-8033ed00-939c-11eb-85b6-4e0c449ad488.png)
![Capture d’écran 2021-04-02 à 10 15 47](https://user-images.githubusercontent.com/16019289/113396807-698d9600-939c-11eb-8283-a82b5944773b.png)


I was able to reproduce the issue with PrestaShop version 1.7.7.0 up to 1.7.7.3. I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello everyone,

As it's a new feature, I didn't manage to reproduce the issue with PS1.7.6.7.
So, it's a regression :wink: 

Thanks!

**Comment by sam-beri** [comment]
@hibatallahAouadni 
thanks for your consideration. Do you have any plan to fix this issue in the future releases? 
thanks in advance

**Comment by matks** [comment]
Hi everyone, I am not 100% sure it is an issue 🤔  . It might be working as expected.

X number of decimals are only displayed if the product price has X decimals.
If produce price is 10.325€, it will show 3 decimals
If product price is 15.66€, it will show 2 decimals

I understand you consider it a problem, so let's see with @PrestaShop/product-team .

Hi @PrestaShop/product-team today, we have the following scenario

1. I have product A which has price 23.4 € in BO.
2. I have product B which has price 26.34 € in BO.
3. I have product C which has price 28.921 € in BO.
4. I open International > Localisation > Currencies BO page and open Euro currency BO page
5. I set Euro currency decimals number to 2 (default behavior)
6. I go to Front Office, I can see that
- product A price is displayed 23.40€
- product B price is displayed 26.34€
- product C price is displayed 28.92€
7. In Back Office, I set Euro currency decimals number to 3
8. I go to Front Office, I can see that
- product A price is displayed 23.40€
- product B price is displayed 26.34€
- product C price is displayed 28.921€

We could expect that product A and product B prices are displayed 23.400 and 26.340 but since the "last decimal" is zero, the code does not add it.

Is this expected or is this a bug?

**Comment by marionf** [comment]
Personally I would say this is the desired behavior but @MatShir know better this topic than me :)

**Comment by samberrry** [comment]
@marionf @matks 
Hi,
there are two different bugs. One is the inherent functionality for this feature, which when we set Decimals to 3 it does not show 3 digits. This is really a bug which is as a result of running this line as I've mentioned it in the pull request:
`(self::$_taxCalculationMethod == PS_TAX_EXC ? 2 : 6),`
as you see digit is fixed to '2' which is used as the floating digits.

Another bug is what you've not considered as a bug. When we set decimals to 3, we expect to see this price 26.34, with three digits like 26.340. In some currencies and countries this is very important to have three floating digits like Oman even when we have 26.000. This comes from may be a culture in finance in that region for that people.

**Comment by matks** [comment]
> Another bug is what you've not considered as a bug. When we set decimals to 3, we expect to see this price 26.34, with three digits like 26.340. In some currencies and countries this is very important to have three floating digits like Oman even when we have 26.000. This comes from may be a culture in finance in that region for that people.

Hi we just confirmed this is a bug 😉  after discussing further. I just wanted to check 😄  .

**Comment by samberrry** [comment]
> > Another bug is what you've not considered as a bug. When we set decimals to 3, we expect to see this price 26.34, with three digits like 26.340. In some currencies and countries this is very important to have three floating digits like Oman even when we have 26.000. This comes from may be a culture in finance in that region for that people.
> 
> Hi we just confirmed this is a bug 😉 after discussing further. I just wanted to check 😄 .

hi again,
great, thanks guys ;)

**Comment by Progi1984** [comment]
Fixed by @samberrry in #24320
