### ISSUE TITLE
Footer text formating differs between PS Core, Link Widget and Legal Compliance Blocks & differs at Home and Order Checkout Page

### ISSUE THREAD

**Issue by 6xthFNGR** [PrestaShop/PrestaShop#23904]
To not alter the chronologic understanding, the original text stays unaltered, but to understand the issue please see my reply
https://github.com/PrestaShop/PrestaShop/issues/23904#issuecomment-814998100

Original Title:
Footer text formating differs on Order Checkout

#### Describe the bug

On the Order Checkout Page, but only the last page where you confirm the payment options,
the footer text is formated different.
In my case, the Information Box Header is a css #h3 but appears grey in font,
but all the other Boxes are p wraps with class=h3 and appear black.

I use the Legal Compliance and GDPR PS Addons, and guess that the overwrite by the Addon causes this issue.

#### Expected behavior

As obvious, I expect there arent some hard coded text styles for different areas, but rather a clean modul that repeats itself and therefor can not differ from one to another.

#### Steps to Reproduce

1. Set up a PS 1.7.7.3 Shop
2. put some item into the cart and checkout
3. Last Checkout Page should look like the screenshots
4. if not: Try the steps above but with Legal Compliance and/or GDPR Addon

**Screenshots**
![h3](https://user-images.githubusercontent.com/64662500/113721829-26ab2580-96f0-11eb-9727-d75483fbd9f4.png)
![h3_2](https://user-images.githubusercontent.com/64662500/113721837-27dc5280-96f0-11eb-8d0f-6f0abe5f841f.png)

#### Additional information

* PrestaShop version: 1.7.7.3
* Official GDPR compliance v1.2
* Legal Compliance v3.0.2

**Comment by hibatallahAouadni** [comment]
Hello @6xthFNGR 

On my side, with fresh install PS1.7.7.3 (even on [demo.prestashop.com](https://demo.prestashop.com/#/en/front)) the footer is not displayed with/without the GDPR module. See the attached screen record below:

https://drive.google.com/file/d/1yjMQhV4B_vP7YkEASTFx-jDw_FoAt5Ux/view

Please check and feedback.
Thanks!

**Comment by pitkz** [comment]
Hey,

try Legal Compliance, I guess its the Module that alters it.

Greets
EDIT After watching your video its clear that you did not understood the issue as you do not have ANY Footer Boxes activated... You may want to check the provided Screenshots before you do another video...

**Comment by 6xthFNGR** [comment]
Lol. After watching your video its clear that you did not understood the issue as you do not have ANY Footer Boxes....

**Comment by florine2623** [comment]
Hello @6xthFNGR ,

I see the exact same thing as @hibatallahAouadni on fresh install 1.7.7.3.
On checkout page, there's no footer displayed, so i can't see the text formatted differently.

Also, I use GDPR module, v1.2.1 :
![Capture d’écran 2021-04-07 à 16 39 47](https://user-images.githubusercontent.com/16019289/113885826-72c59b00-97c0-11eb-98c4-c686e044aec4.png)

Here you can see my Position in DisplayFooter :
![Capture d’écran 2021-04-07 à 16 42 49](https://user-images.githubusercontent.com/16019289/113885966-938df080-97c0-11eb-9306-68f50ece8936.png)
The link widget module :
![Capture d’écran 2021-04-07 à 16 42 55](https://user-images.githubusercontent.com/16019289/113885989-9ab4fe80-97c0-11eb-8855-0649eacaad36.png)


Here's my last step at checkout, no footer :
![Capture d’écran 2021-04-07 à 16 40 00](https://user-images.githubusercontent.com/16019289/113885889-807b2080-97c0-11eb-8829-c9f405842208.png)

Am I missing something ?

**Comment by pitkz** [comment]
Hello.

to get this into some order:
I am thinking I remember some option in the Backend that allows to decide if the Footer is displayed on Checkout - but I was not able to make it out right now,
this could be because I am maybe confusing it with the Reassurance Block and its Configure - Display Options that allow to set display options.

To bring a quick solution:
I use the Link Widget and have 2 custom Blocks with it, maybe they enforce the display while checkout?

Also I attached you my Positions/hooks as screenshot here:

![1](https://user-images.githubusercontent.com/64662500/113890288-4e6bbd80-97c4-11eb-86c5-84c2130f04a1.png)
![2](https://user-images.githubusercontent.com/64662500/113890291-4f9cea80-97c4-11eb-8c35-5e60a287ec99.png)
![3](https://user-images.githubusercontent.com/64662500/113890293-50358100-97c4-11eb-854c-fdf25c11ade8.png)


Never the less, I just checked the footer in general and can say that regardless of the Checkout:

Additionaly to the 2 different Footer Blocks mentioned in the first post, I noticed that the Link Widget Blocks are formated different again as p class h3,
while, to repeat the previous post, the "Your Account" Block by PS is formated in p class h3 tags as wrap with an a class h3 tag,
and the Legal Compliance "Information" block is formated directly in h3 tags,
rendering every font to look different by the parenting features of the a and the p wrap which you actually can see in my screenshots if you compare them close enaugh.

![4](https://user-images.githubusercontent.com/64662500/113890297-50ce1780-97c4-11eb-99e9-c4e8c11ee70d.png)

The difference in the Checkout Page, what ever forces the Footer to be displayed while checkout at the moment (which I actually prefer), was just the initial report that shows to be a second, related problem after the initial issue is that there are different formatings between PS and its own PS Features/PS made Addons on the regular "Homepage" already.

If I will find the feature where to activate the Footer in the Checkout again, I will let you know.

Thanks

**Comment by florine2623** [comment]
Hello @6xthFNGR ,

The option to display footer in the checkout process doesn't exist on PS natively.
You must be using a external module that allows that or you changed `/themes/your theme/templates/checkout/_partials/footer.tpl` file.

At installation, here's the file you should have : 
[footer.tpl.zip](https://github.com/PrestaShop/PrestaShop/files/6277444/footer.tpl.zip)

**Comment by pitkz** [comment]
Hello florine2623,

for sure you are right and its not a standard option,
but this behaviour is not triggered by any external module, because I do not use any external module except the 1-Click Upgrade, Legal Compliance, GDPR, PayPal and Stripe by 202 (PS official),
and its not caused by the theme because I use the unaltered standard theme.

Like I mentioned, I guess the webhooks may be the cause of the footer beeing displayed while checkout.

Nether the less:
The Bugs I reported about a Standard PS1.7.7.3 (and previous) within the footer between the different blocks by PS Core, PS Legal Compliance and PS Link Widget, do still consinst and should get focus now first.
Everything else by causality is depending on this first issue, so the focus should change to it.

Best regards

**Comment by florine2623** [comment]
Hello @6xthFNGR ,

Stripe is an external module, not developed by PrestaShop.

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Comment by pitkz** [comment]
Hello,

you havent replied on the Hooks that may caused the footer to be displayed later on in the order page.

Anyways,
before of your reply I already stated what is the core problem that exist on the main page - yet you do not reply to that report in any way!

It is consisting with every fresh PS installation.

Your claims that its has to be caused by another addon are wrong, are not helping in any way when I already stated that I use a clean PS installation for testing! You show this kind of reply on multiple of my bug reports and I got to say you are the only one acting like this - its kind of annoying.

Also, 202 his Stripe Addon is the offical PrestaShop module - so either way that behaviour mustnt be expected from "your" own advertised features.

Merci
