### ISSUE TITLE
Don't display warning if module is disabled (ps_checkpayment)

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#23942]
#### Describe the bug

When the module is disabled a waring is display

#### Expected behavior

Dont show warning is module is disabled

#### Steps to Reproduce

1 ) Disable the module 
2 ) Go to module catalogue
3)  Check Warning
**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @okom3pom ,
I reproduced your issue in PS 1.7.7.3 : 
![Capture d’écran 2021-04-08 à 16 49 06](https://user-images.githubusercontent.com/16019289/114048168-99e89f00-988a-11eb-8986-fde58e72f8de.png)
![Capture d’écran 2021-04-08 à 16 49 48](https://user-images.githubusercontent.com/16019289/114048184-9c4af900-988a-11eb-97cd-0befdfecf7f2.png)

It is added to the debug roadmap.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](url_here) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a Pull Request. Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you !

**Comment by ghost** [comment]
Hi @florine2623 

I don't understand is not display but a PR is linked for this issue : 

https://github.com/PrestaShop/ps_checkpayment/pull/48

**Comment by hibatallahAouadni** [comment]
The PR is merged :tada: So I close the issue :wink: 
Thanks @okom3pom
