### ISSUE TITLE
Backorder status set to (Paid) using COD module

### ISSUE THREAD

**Issue by soft-dot** [PrestaShop/PrestaShop#23953]
#### Describe the bug

When ordering products with 0 stock and the option to allow orders is set to true in BO,  using the official COD module, the order status is set to Backorder (paid).

#### Expected behavior

When ordering out of stock products with COD as payment method, the correct status should be Backorder (Unpaid)

#### Steps to Reproduce

1. Place order with 0 stock product
2. Use official COD payment module
3. Let the order go through
4. Check order status

#### Additional information

* PrestaShop version: 1.7.6.8
* Php version: 7.0.33

How can we change this?

**Comment by florine2623** [comment]
Hello @soft-dot ,

I was able to reproduce the issue with PrestaShop version 1.7.7.3, COD module v1.0.6, so I can confirm that this behavior is indeed a bug.
![Capture d’écran 2021-04-09 à 11 21 54](https://user-images.githubusercontent.com/16019289/114159218-d74e3a80-9925-11eb-9210-44e8a8affc2f.png)


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](url_here) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a Pull Request. Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by fredoche1810** [comment]
Hello @soft-dot  #@florine2623,
I've exactly the same issue in Prestashop 1.7.7.3 using Mollie as payment module.
Is there a correction that we can apply manually ?
Thanks in advance,

**Comment by matks** [comment]
Should be fixed by v2.0.0 of COD module https://github.com/PrestaShop/ps_cashondelivery/pull/44

**Comment by florine2623** [comment]
It is fixed :


https://github.com/PrestaShop/PrestaShop/assets/16019289/0d4bf6fc-d2a9-48e7-af3b-d743d066316f
