### ISSUE TITLE
Wrong characters encoding on Order view and Address view grid

### ISSUE THREAD

**Issue by nikos83** [PrestaShop/PrestaShop#23988]
#### Wrong characters encoding on Orders View and Addresses View

After upgrade from 1.7.5 to 1.7.7.2 I have wrong characters encoding on Orders page ana also on Addresses page. The problem is only with grid view on for example Orders or Addresses pages - when I go to the selected Address - or try to edit the characters are correct there. 

#### It should correctly encode UTF8 characters

Grid view should show correct characters

#### Steps to Reproduce

This happened when upgrade from 
1.7.5 to 1.7.7.2 
Before it was upgrade from 1.6.x to 1.7.5

**Screenshots**
This is addresses view grid in admin panel

![image](https://user-images.githubusercontent.com/4093704/114283873-79684280-9a4c-11eb-8124-d11e78346556.png)
Then when I click on it to edit 

![image](https://user-images.githubusercontent.com/4093704/114283902-a0bf0f80-9a4c-11eb-8f77-3610624ad249.png)
 
Is correct.

The problem is in admin panel  - is there anything ( function or something) what changes or may change this character encoding - don't know where to look 
There are also other places in admin panel where encoding is wrong. 

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2.22

**Comment by sarahdib** [comment]
Hello @nikos83 

I try to reproduce but I wasn't able to.

Could you provide us more information ?

Thank you

**Comment by nikos83** [comment]
Hi @sarahdib ,
Thanks for your response - We have had manual update from 1.6 to 1.7.5 and then automatic update to 1.7.7.2 
At the moment I've tried upgrade 1.6.21 -> 1.7.7.3 after this upgrade issue is not present.
It looks like this issue maybe related only to our example. So assuming it maybe related to our module or modification.

**Comment by florine2623** [comment]
Hello @nikos83 ,

After upgrading from PS 1.7.5.2 to PS 1.7.7.3, I have the correct encoding in my shop.
Address section :
![Capture d’écran 2021-04-16 à 15 49 06](https://user-images.githubusercontent.com/16019289/115033989-4fd76d00-9ecb-11eb-9d9e-9e61b6e653b0.png)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
