### ISSUE TITLE
Product discounted price after using voucher on Order list in BO. PS 1.7.7.1

### ISSUE THREAD

**Issue by paulps-stack** [PrestaShop/PrestaShop#24054]
#### Problem

On order list in BO we don't see the final price of one single product after using any voucher-discount. There is just total amount of discount value in summary.

#### Describe the solution you'd like

I would like to show next to the normal price on order product list, the price of product after applying voucher. I mean I have a product witch normal price 10$, I used a voucher with 10% discount, so I would like to see next to the normal price, a price with discount set 9$.

#### Alternatives you've considered

I know that I need to put this variable in src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\Blocks\View\product.html.twig, but I still don't know how to get it.

**Comment by florine2623** [comment]
Hello @paulps-stack ,

You would like to have the details of the discount amount directly on the product list of the order details, is that right ?
On my example, 43.08 - 34.46 = 8.62, 8.62 should be displayed ?
![Capture d’écran 2021-04-16 à 10 54 43](https://user-images.githubusercontent.com/16019289/115000255-e2174b00-9ea2-11eb-8fd8-9fd03175b92a.png)
![Capture d’écran 2021-04-16 à 10 58 03](https://user-images.githubusercontent.com/16019289/115000576-2c98c780-9ea3-11eb-9df0-813e8214e395.png)

What would the result be if there are multiple product with discount ? Could you add a screenshot of what you would like to see ?
What about other page ? Order confirmation page ? Invoice ?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @paulps-stack ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by ButcherFromHell** [comment]
> Hello @paulps-stack ,
> 
> You would like to have the details of the discount amount directly on the product list of the order details, is that right ? On my example, 43.08 - 34.46 = 8.62, 8.62 should be displayed ? ![Capture d’écran 2021-04-16 à 10 54 43](https://user-images.githubusercontent.com/16019289/115000255-e2174b00-9ea2-11eb-8fd8-9fd03175b92a.png) ![Capture d’écran 2021-04-16 à 10 58 03](https://user-images.githubusercontent.com/16019289/115000576-2c98c780-9ea3-11eb-9df0-813e8214e395.png)
> 
> What would the result be if there are multiple product with discount ? Could you add a screenshot of what you would like to see ? What about other page ? Order confirmation page ? Invoice ?
> 
> Thanks!

I think that what @paulps-stack wanted is to show price in basket after using discount code (or voucher),
Default behavior is that discount amount is calculated and show as total amount (not showing a discount value for each product).
So take it like this:

product X - price 10,00$ 
product Y - price 20,00$
product Z - price 2,00$

and we use the code let;s say: gimme20 - that gives 20% discount
So in basket summary it looks like:

product X - price 10,00$ 
product Y - price 20,00$
product Z - price 2,00$
code: gimme20
total: 32,00$
discount: 6,40$
to pay: 25,60$

and we need to show in summary:

product X - price 10,00$ after discount-> **8,00$**
product Y - price 20,00$ after discount-> **16,00$**
product Z - price 2,00$ after discount-> **1,60$**
code: gimme20
total: 32,00$
discount: 6,40$
to pay: 25,60$

So it is strange that is not working like that by default - because when giving receipt to customer in most cases we need to show what was discounted exactly. 

Thanks.
