### ISSUE TITLE
Prestahop account module update problem

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#24099]
#### Describe the bug

I updated prestashop account module and now i cant login to my backoffice

#### Expected behavior

login to my backoffice as usual 

#### Steps to Reproduce

1. Go to modules , update prestahop account module to the latest.
2. Click on dashboard

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.4

**Comment by sarahdib** [comment]
Hello @Stampa-Stampa,

Thanks for your report.

Your php version is not compatible with 1.7.7.3 like indicate in documentation : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Please contact your hosting provider in order to downgrade your php version

Have a nice day !
