### ISSUE TITLE
The placeholder 'Search our catalog' does not appear in ps_searchbar 

### ISSUE THREAD

**Issue by Julievrz** [PrestaShop/PrestaShop#24105]
#### Describe the bug

The placeholder does not appear in the search bar (ps_searchbar) in the front office.

#### Expected behavior

The wording 'Search our catalog' located in Shop.Theme.Catalog should appear in the search bar.

**Screenshots**

![image](https://user-images.githubusercontent.com/70583503/115204885-47647980-a0f9-11eb-801f-41c0e81ee60b.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/70583503/115204941-56e3c280-a0f9-11eb-8df8-0a3b976d72ed.png)

**Comment by NeOMakinG** [comment]
@atomiix I remember this, maybe you know why

**Comment by hibatallahAouadni** [comment]
Hello @Julievrz 

Thanks for reporting! I reproduce the issue only with develop. So, it's a **regression**!
I’ll add this to the debug backlog so that it’s fixed.

Thanks @NeOMakinG :rocket:

**Comment by atomiix** [comment]
@Julievrz @NeOMakinG @hibatallahAouadni that's because we deleted the ps_searchbar override in the develop branch but we're not using the last version of the module ps_searchbar yet. Once the composer.lock will be updated with the last version of the module, it will have the placeholder as well as the right style for the input and the button

**Comment by MatShir** [comment]
First, we need to test it in a fresh installation with version 2.1.0 of the module to see if we can reproduce the issue.

**Comment by hibatallahAouadni** [comment]
@MatShir I see you've been struggling with prestabot :sweat_smile: So al last what's the status of this issue?
Shall I reopen it with TBR label?
