### ISSUE TITLE
Still cannot delete product combinations in newest ps version.

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#24141]
#### Describe the bug

Tried the .htacces solution on fresh install of ps 1.7.7 and - even after all these updates - this still does not work.
Force compilation is on, cache is off and emptied.
Just same old problem : click on delete combination, screen / save button will freeze on loading and that's it.

When using ctrl+f5 to get things working again, combination is still there.

#### Expected behavior

The combinations are removed without any problem

#### Steps to Reproduce

1. Go to **BO** > **SELL** > **Catalog** > **Products**
2. Click on Edit Product with combinations
3. Delete the combinations and **Save**
4. See error > the **Save** button will freeze on loading

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

---
Since the issue is closed while it isnt solved and lack of any reply from the developers , i reopend the issue.

Good old thirtybees and ps 1.6 for me it is  :) 
Its a shame they refuse to fix this.

_Originally posted by @loetje88 in https://github.com/PrestaShop/PrestaShop/issues/10198#issuecomment-751288386_

**Comment by matks** [comment]
Hi @loetje88 reopening an issue is useless if you just repeat the same thing 🤔 

If you wish to report a bug, you must do it by following the GitHub template for that (see https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md). We need a series of clear steps like

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

However from the previous issue it seems after multiple attempts, QA was not able to reproduce the issue locally using the steps given.

It looks like you are not trying to submit a bug report but you are rather trying to get some help. You will probably be interested in https://devdocs.prestashop.com/1.7/faq/i-need-help/ then.

**Comment by hibatallahAouadni** [comment]
Hello @loetje88 

I just edit your issue, could you please check it and add the missing infos.
And please provide a screen record, cause I didn't manage to reproduce the issue with PS1.7.7.3 with these provided infos :wink: 

Thanks!

**Comment by loetje88** [comment]
Hi hibatallah,

Thank you for the help! 

I have included a video recording to reproduce the issue and show my steps.

Just to be sure 👍
Clean install PrestaShop 1.7.7
Php 7.3

**Comment by florine2623** [comment]
Hello @loetje88 ,
I can't reproduce your issue in PS 1.7.7.3. Please check my screen record : 
https://drive.google.com/file/d/1mUaIJma4jsYUBBUbfZ_6A16t14Uri9nv/view

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by loetje88** [comment]
@florine well that's too bad because as seen in my record, the bug does exists.

Just as many, many other reports here.

Closing reports withing this short time just because ' you can't reproduce' does not solves the problem.

So, onze again, please re open this issuem

**Comment by matks** [comment]
@loetje88 we do not open and validate a bug report because someone has an issue on its shop. There is 300,000 shops powered by PrestaShop, and all of them are installed in different servers with thousand of different configurations, setups, environment settings. You can add to this that all of these shops have installed third party modules, custom themes and sometimes some more changes like overrides.

If you observe an issue on your shop, there is a bug on your shop. But until it has been explored and proven, we cannot say the issue comes from the code on this project.

When we can confirm the issue comes from the code on this project, we validate the bug report, because we are 100% sure this is something we need to fix.

Unless we are 100% sure the issue comes from the code in this project, we dont validate the bug report.

If you want this bug issue to stay open you need to explore the bug and find out the accurate steps / settings / requirements that would allow us to reproduce the issue and explore it. Without the accurate steps / settings / requirements  we cannot reproduce the bug. Without the accurate steps / settings / requirements we cannot fix it.

Why would we keep open a bug report that we cannot reproduce? If we cannot reproduce, we cannot fix. We dont keep bug reports open if we know we cannot fix them.

**Comment by loetje88** [comment]
hi matks,

unfortunately, there is not much more i can tell since it is a fresh install with no third party modules and so on.
Just install, delete install folder, log in, look at demo product, try to delete - nothing.
No error, no nothing, it just freezes until i refresh and see the same combination again.

Just as shown in my previous video recording.

I have several live running webshops on ps 1.6 and thirtybees on the same server with absolutely no problem, the problem only enters whenever i try to run ps 1.7 , in different versions.

I have been watching github from the start of ps 1.7 and know that this problem is a looooooong one which never seems to be solved in new updates.

**Comment by hombean** [comment]
I have the same problem on Prestashop 1.7.7.8.

**Comment by luisway2net** [comment]
I have the same problem in version 1.8.7.2 and when delete combination display this error:
![Captura de pantalla 2021-12-27 a la(s) 16 28 15](https://user-images.githubusercontent.com/2183028/147501578-d698ca93-e143-4587-a11b-18162b65466b.png)
