### ISSUE TITLE
Failed to authenticate on SMTP server PS 1.7.7.3

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#24207]
Hello 

I'm using PS version 1.7.7.3, I have my mail configured on thunderbird and outlook , everything works fine on this mail program 
but on Prestashop i'm getting this error with same credentials 

Erreur : veuillez vérifier votre configuration
Failed to authenticate on SMTP server with username "support@mydomain.com" using 3 possible authenticators. Authenticator CRAM-MD5 returned Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: authentication failure ". Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: authentication failure ". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: authentication failure ".

I want to add that my domain is on cloudflare dns and when I use amazon service mail it works fine.

I changed the password many times but same error

I'm using the same access on newsletter module and I can send email 

Regards,

**Comment by lmeyer1** [comment]
Prestashop uses swiftmailer v.6.2.3. Maybe you find an answer in their doc and community ressources.
Also you are not specific on the settings your mail host recommends and those you configured in Prestashop.

**Comment by hibatallahAouadni** [comment]
Hello @go-sudo 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: Thanks @lmeyer1 for your quick reply :rocket: 

Thanks!

**Comment by alvesjc** [comment]
Helo,

I'm having the same issue.

I'm sure that the user and pass is correct, but it always results in authentication failure.

What info you need to try to reproduce it ?

Thanks

**Comment by bodek63** [comment]
From my trial and error it appears that:
The prestashop 1.7 form has the property that the "Email setup test" script sends the data that is entered at that point in the form, and not what has been stored in the database.
Therefore, the "send" e-mail test will not work properly after clicking "save".
The test will work after entering the password, but only if you do not click "save".
Clicking save removes the password from the form and saves it in the database. I think this is some script error, but I don't know if and where to change it, so that the script sends the password saved earlier in the database, and not what is currently masked in the form.
So it works for me like this: enter the password into the form, click "send" and if I have a message that "e-mail has been sent" and then I click "save". Consequence: Sending a test message from the form will no longer work, but the mail functions of the order, status changes, seem to work correctly.

**Comment by Betafer** [comment]
same problem with prestashop 1.7.8.5
password is not saved correctly

there is also a security problem, that password is stored in the db not encrypted
you can solve by changing the password manually in the DB

I have write to security prestashop to report the problem

**Comment by tone87** [comment]
Yes, for me the same problem WITH 1.7.8.5... not work with sendmail method .. and after i tried with SMTP method but not work too .. i checked in the _configuration table and prestashop have double name of PS_MAIL_ configuration .. this problem create a conflict .. so i removed all names duplicated with id_shop_group and id_shop with a propriety value and i keep all name with NULL value in id_shop_group and id_shop ... now it works and it save the configuration from the settings form .. maybe it's a Bug ?
For me with this solution I SOLVED
