### ISSUE TITLE
1.7.8 Product form display hooks reminder

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#24249]
Reminder issue for display hooks that worked in old page, but are not dispatched anymore in new one (providing alternative in a new page if there is one). Overall, we are almost able to achieve everything by using hookActionProductFormBuilderModifier and adding fields to related form types (though some things are still missing - like the form_rest at the end of each subtype and some parts of product page). Also as discussed with @jolelievre , it would be great to introduce some helper methods in FormBuilderInterface like addAfter, addBefore to ease the job of switching form fields order for module developers)

Hooks list (can see the same hooks with description in https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/):

* displayAdminProductsExtra - Currently not possible to achieve same behavior. This hook is not dispatched in new page - IMO we could try to dispatch it and render in same manner)
![Screenshot from 2021-04-28 16-10-01](https://user-images.githubusercontent.com/31609858/116417543-06c8d680-a844-11eb-9ae2-d70ec71e1ce9.png)

* displayAdminProductsCombinationBottom - Possible by using hookActionCombinationFormBuilderModifierand adding field in Combinationtype
![Screenshot from 2021-04-28 16-11-54](https://user-images.githubusercontent.com/31609858/116417664-2a8c1c80-a844-11eb-99d4-7920fac9a519.png)

* displayAdminProductsMainStepLeftColumnBottom - Possible to achieve same by adding field in BrandType (because related product is not yet there. But same concept - add field in last form type rendered)
![Screenshot from 2021-04-28 16-15-43](https://user-images.githubusercontent.com/31609858/116418313-b2722680-a844-11eb-82ff-d598fe8809db.png)

* displayAdminProductsMainStepLeftColumnMiddle - Possible by adding field in BasicInformationType.
![Screenshot from 2021-04-28 16-15-35](https://user-images.githubusercontent.com/31609858/116418513-e3eaf200-a844-11eb-89a2-9946b7fa6a46.png)

* displayAdminProductsMainStepRightColumnBottom - Currently not possible (should be possible when categoryType is introduced)
![Screenshot from 2021-04-28 16-19-34](https://user-images.githubusercontent.com/31609858/116418560-efd6b400-a844-11eb-81ed-2aea405bcf3f.png)

* displayAdminProductsOptionsStepBottom - Possible by adding field in SuppliersType (because suppliers type is the last one rendered in Options tab)
![Screenshot from 2021-04-28 16-26-37](https://user-images.githubusercontent.com/31609858/116418921-3d532100-a845-11eb-922c-6092283bb5b7.png)

* displayAdminProductsOptionsStepTop - Possible by adding field into OptionsType and modifying fields order (loop through $formBuilder->all() and after adding your field first add the original ones - might be improved later with above-mentioned helpers)
![Screenshot from 2021-04-28 16-26-22](https://user-images.githubusercontent.com/31609858/116419230-86a37080-a845-11eb-8f67-27624d9b9077.png)

* displayAdminProductsPriceStepBottom - Possible by adding field in PriceType (though we haven't added priority management block yet)
![Screenshot from 2021-04-28 16-27-56](https://user-images.githubusercontent.com/31609858/116419328-9cb13100-a845-11eb-8c52-0ff9aaafb1e1.png)

* displayAdminProductsQuantitiesStepBottom - Possible by adding field to StockType.
![Screenshot from 2021-04-28 16-30-06](https://user-images.githubusercontent.com/31609858/116419652-f0237f00-a845-11eb-94c3-7462560486e3.png)

* displayAdminProductsSeoStepBottom - Possible by adding field to SEOType
![Screenshot from 2021-04-28 16-28-34](https://user-images.githubusercontent.com/31609858/116419861-1fd28700-a846-11eb-8868-bb16c7a29c82.png)

* displayAdminProductsShippingStepBottom - Possible by adding field to ShippingType
![Screenshot from 2021-04-28 17-22-35](https://user-images.githubusercontent.com/31609858/116420090-57d9ca00-a846-11eb-9c94-a3f5fae2fb8b.png)

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @zuk3975 

> Reminder issue for display hooks that worked in old page, but are not dispatched anymore in new one (providing alternative in a new page if there is one)

I think you're talking about this issue #22981, so we still have other hooks to add.
@matks should I label it as **`To Do`** along with **`regression`**? or this is an **`improvement`**?

Thanks!

**Comment by jolelievre** [comment]
Thank you @zuk3975 really interesting resume, so I would suggest this:

- **displayAdminProductsExtra** add this hook and respect the legacy behaviour where all modules are in this extra tab
- additionally we should think of a new more proper way to add tabs in the page, so that each module could add its own tab, either via a display hook or via an actionHook that force a structure a bit like we did for order page
- **displayAdminProductsCombinationBottom** removed as it can be done by adding fields in `CombinationFormType` as you said 
- **displayAdminProductsMainStepLeftColumnBottom** We remove this one but I think we should review the structure of the product form so that we have a BasicType that contains all the fields from basic tab, this way we can display it by only doing `form_row(productForm.basic)` and it's much simpler to add content at the end
- **displayAdminProductsMainStepLeftColumnMiddle** removed, use form fields
- **displayAdminProductsMainStepRightColumnBottom** removed, it should be possible by adding fields into `ShortcutsType`
- **displayAdminProductsOptionsStepBottom** removed, here too we might need an OptionType to add some content at the end
- **displayAdminProductsOptionsStepTop** removed, but then we should provide some helper service or tools to easily add some fields into an existing form `addAtBeginning`, `addAtTheEnd`, `addBefore`, `addAfter`, ...
- **displayAdminProductsPriceStepBottom** removed
- **displayAdminProductsQuantitiesStepBottom** removed
- **displayAdminProductsSeoStepBottom** removed
- **displayAdminProductsShippingStepBottom** removed

So I guess besides this tab thing everything is doable by adding form fields at the proper place, but what we need to do is:
- split form type into several sub forms, each one will have to represent a tab in the page, I guess that will be the simpler and more understandable way to organize the form structure
- if we do this maybe we could even have an automatic loop that adds a tab for each product form children, this would allow module developers to add new tab more easily Maybe we should restrict this to a specific type though, like `ProductTabType`, that needs to be used as a parent class I also though about an idea to make this generic in the form theme, this would allow to add tabs in other pages for modules but maybe it's too early for that
- we need to provide form helper functions to help integrating fields wherever the module needs to

I think the structural modification can be done in the current PR we are working on with @NeOMakinG https://github.com/PrestaShop/PrestaShop/pull/24076/

**Comment by Progi1984** [comment]
Fixed by @jolelievre in #24661
