### ISSUE TITLE
Defined() without quotes

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#24251]
#### Describe the bug

In the file /src/Adapter/environment.php in the function __construct() the function defined is twice used without quotes around the constant name. This produces a error: Use of undefined constant _PS_ENV_ - assumed '_PS_ENV_'

line 56:      $this->isDebug = defined(_PS_MODE_DEV_) ? _PS_MODE_DEV_ : true;
line 64:             if (defined(_PS_ENV_)) {

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

Thanks for respecting the provided template :clap: 
Could you please provide steps to reproduce the issue :pray: 

Thanks!

**Comment by musicpanda** [comment]
Sure:
 - rising up
 - putting on my glasses
 - starting the computer
 - looking at the code

**Comment by matks** [comment]
Hi @musicpanda, is this [sarcasm](https://en.wikipedia.org/wiki/Sarcasm) ?

**Comment by sarahdib** [comment]
Hi @musicpanda ,

Unfortunately, there is not enough information provided to reproduce this issue and work on it. You must follow the template to submit a complete bug report.
Read more about how we expect the issues to be handled [[here].](https://build.prestashop.com/news/how-bug-reports-are-handled/) 
Feel free to create a new issue if you can provide further information and respect the [code of conduct](https://devdocs.prestashop.com/1.7/project/code-of-conduct/).

**Comment by musicpanda** [comment]
Look in the manual: defined is used with quotes. (https://www.php.net/manual/en/function.defined.php)

Try it yourself: 
define("MYCONSTANT", "Hello world.");
if(defined('MYCONSTANT')) echo "quoted found<br>"; /* echoes "quoted found" */
if(defined(MYCONSTANT)) echo "unquoted found<br>"; else echo "unquoted NOT found<br>"; /* echoes "unquoted NOT found" */
if(defined(OTHERCONSTANT)) echo "other found<br>"; else echo "other NOT found<br>"; /* produces warning */

**Comment by matks** [comment]
Hi @musicpanda I think I will clear the misunderstanding here 😄 

We can see you are reporting a _defect_ in class https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Environment.php, which is the use of define without quotes.

But a defect is not a bug report. We do not have the resources to transform a known defect into a bugfix. We are already aware of dozen of defects into the software, but it takes time to explore them, see how they can be fixed, test the fix is valid. This is why we do not validate a bug report that just mentions "I saw defect X in file Y".

In order to dedicate resources to fix an issue, the team in charge of sorting issues need multiple informations: the nature of the defect, the impact of the defect, how to observe the issue. This is why there is a template. This is why @hibatallahAouadni asked you to fill in the template.

If you do not fill the template, what will happen?

When all issues are being analyzed to see what needs to be fixed soon and first, and what can be fixed later and in a long time ; since the necessary items will not be provided, this issue will be discarded and not fixed. This is why we close the issue if the template is not filled.

<hr>

To sum it up: thank you for reporting this defect in the software but unfortunately we are way too busy to be able to receive bug defects without context and fix them all. If you want this to be fixed, you need to go through the full process and provide the necessary items for this issue to enter the backlog and given a priority. If you do not have the time to do this* then it's better not to report this defect**.

Even better is to submit a PR to fix it ; but this also takes time, and there is also a template to fill.

Basically, PrestaShop is a project too big and too complex ; there is no quick way to report/fix something in it. There is a process, we understand it can be considered heavy and boring, but it helps the maintainer team handle the hundred of items going through GitHub. You cannot simply tell us "Hello I found a defect in file Y", it's a single piece of a puzzle. We only accept complete puzzles, not pieces.

*It's OK: we understand it's a lot of time!
**Unless it's a critical defect but here this is not what we are talking about, right?

**Comment by musicpanda** [comment]
If that is your choice, so be it. But be aware that those defined() warnings often appear as a side effect when there are other problems. And then they can be quite confusing.

**Comment by musicpanda** [comment]
I wonder how many Prestashop programmers know that 
if( defined(PS_MODE_DEV))
will never return true. It is counterintuitive.

Try it in a quiz during your next company meeting.

**Comment by matks** [comment]
Follow up https://github.com/PrestaShop/PrestaShop/issues/25002 😊
