### ISSUE TITLE
ERROR 500 / PrestaShopBundle\Entity\Tab error

### ISSUE THREAD

**Issue by enoelai** [PrestaShop/PrestaShop#24298]
Please help me
`The association PrestaShopBundle\Entity\Tab#tabLangs refers to the owning side field PrestaShopBundle\Entity\TabLang#tab which does not exist.`

**Comment by matks** [comment]
Hello @enoelai 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**. https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

But rather than a bug report you might be looking for help. If you are looking for help, please do not open a GitHub issue as we use GitHub issues only to discuss about bugs and new features for the PrestaShop project.

You will find better places for help in https://devdocs.prestashop.com/1.7/faq/i-need-help/
