### ISSUE TITLE
Performance ps_facetedsearch

### ISSUE THREAD

**Issue by luigimassa** [PrestaShop/PrestaShop#24294]
#### Describe the bug

Prestashop performance is very slow when the module ps_facetedsearch is activated

#### Expected behavior
Low sql time when the module  ps_facetedsearch is activated

#### Steps to Reproduce

1. Go to 'manage module'
2. Click on 'activate the ps_facetedsearch"
3. Go to the shell
4. exec curl -s -w '\nLookup time:\t\t%{time_namelookup}\nConnect time:\t\t%{time_connect}\nSSL handshake time:\t%{time_appconnect}\nPre-Transfer time:\t%{time_pretransfer}\nRedirect time:\t\t%{time_redirect}\nStart transfer time:\t%{time_starttransfer}\n\nTotal time:\t\t%{time_total}\n'    <link of product or category>
5. check total time
6. Go to 'manage module'
7. Click on 'deactivate the ps_facetedsearch"
8. Go to the shell
9. exec curl -s -w '\nLookup time:\t\t%{time_namelookup}\nConnect time:\t\t%{time_connect}\nSSL handshake time:\t%{time_appconnect}\nPre-Transfer time:\t%{time_pretransfer}\nRedirect time:\t\t%{time_redirect}\nStart transfer time:\t%{time_starttransfer}\n\nTotal time:\t\t%{time_total}\n'    <link of product or category>

**Screenshots**

![ricerca_per_aspetti](https://user-images.githubusercontent.com/186556/116782007-f2285080-aa86-11eb-955f-31d5580b27ba.png)
![ricerca_per_aspetti_senza](https://user-images.githubusercontent.com/186556/116782012-f5234100-aa86-11eb-9909-0e65ebaa5570.png)

**Comment by matks** [comment]
Hello @luigimassa performance is a very subjective topic.

I suggest reading https://build.prestashop.com/news/performance-and-prestashop/ as it provides some background for this statement 😄 .

Faceted search module is indeed a complex module and using it adds an overhead on requests. But is it too big ? Is it worth it ? Is it relevant ? it also depends on your server, on your SQL content, on other modules installed... so this topic is too vague to be explored.

**Comment by hibatallahAouadni** [comment]
Hello @luigimassa 

As @matks mentioned, this module performance depends on your server, on your SQL content, on other modules installed... While with fresh install, I can't see any difference :confused: (ps_factedsearch enabled or disabled).

I'm really sorry but I have to close the issue unless, you create a PR to improve this module performance otherwise `this topic is too vague to be explored.`

PS: i know you're frustrated with the performance but we have other blocking issues to resolve :pray: 
PS: by the way, thanks for detailed bug report :wink: :rocket: 

Thank you for your understanding!
