### ISSUE TITLE
Select partial part of product link in backoffice order page

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#24300]
#### Describe the bug

In 1.7.6 it was possible to select a part of the product link and copy this ( order page ). This is handy, for when you want to select only the product reference and find it in the search ( front office )

In 1.7.7 it is impossible to select a part of the product link or reference. You need to select the whole link and edit this or click on the link that brings you to the product page and from here copy the reference.

I would say this is not in line with the goal to make 1.7.7 more efficient. 

#### Expected behavior

Option to select a part of link ( purchase products from the order )

#### Steps to Reproduce

1. Place an order
2. Try to copy for example the reference in the order page
3. See error

**Screenshots**

#### Additional information
* PrestaShop version: 1.7.7.x
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @01park 

I managed to reproduce the issue with PS1.7.7.3 and as you mentioned it has been working with PS1.7.6.x.
If you notice the structure of the link has been changed, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/116952073-07210180-ac8a-11eb-909d-aff709c43c26.png)

With PS1.7.6.x, the link structure is composed from **`span`** tags.
In the other hand with PS1.7.7.x, it's composed from **`p`** tags: 

![image](https://user-images.githubusercontent.com/23308427/116952223-6b43c580-ac8a-11eb-941b-3e1b56c75779.png)

Changing the link structure may affect this behavior, but I don't know if it's the wanted behavior or it's a regression :confused: 
Ping @PrestaShop/prestashop-core-developers any idea about this behavior changement?

**Comment by matks** [comment]
Hello everyone,

1. If I understand correctly this matter, this is not a bug.

A bug is a situation where the software does A _on purpose_ and later A cannot be done anymore because it's faulty, it's broken. A was built to work, then was correct, then was broken.

I dont think it was done on purpose to use a span to allow to select a part of the product link. I think it is an unwanted side-effect that can be useful for some users. It was never supposed to be built, so it cannot be broken.

_So it's not a Bug it's an Improvement._

2. When you say

> In 1.7.6 it was possible to select a part of the product link and copy this ( order page ). This is handy, for when you want to select only the product reference and find it in the search ( front office )

You are saying "When I display my Order in Back Office, I want to look at one of the products that has been bought, so I want to go to the Product page on Front Office as easily as I can", right ?

Then I dont think `This is handy, for when you want to select only the product reference and find it in the search ( front office )` is efficient. Rather than copy some part of a sentence then search it in FO, we could rather suggest something a lot more direct: **add a link or a button that allows merchant to navigate to product FO page from the view**.

A link is even quicker than copy-and-search, don't you think? 😉 

@hibatallahAouadni Next step is to get @PrestaShop/product-team opinion on this topic

**Comment by 01park** [comment]
Hi,

" A link is even quicker than copy-and-search, don't you think? 😉"

In our case the way it used to be was better, we use these reference numbers also to search on external pages. 

Would it be possible to have both, a link and a the 1.7.6 way of selecting the info.?

**Comment by florine2623** [comment]
Hello,

You can actually select the reference number by going on the left sign of the price.

https://github.com/user-attachments/assets/77921016-7aa3-495a-a0ee-536c6f40fcae

Thanks!
