### ISSUE TITLE
Blockwishlist upgrade v1.3.2 -> 2.0.0 fails

### ISSUE THREAD

**Issue by jacob-v-dam** [PrestaShop/PrestaShop#24321]
#### Describe the bug

I'm unable to upgrade blockwishlist version v1.3.2 to v2.0.0 in a multishop context

#### Expected behavior

Upgraded module to v2.0.0

#### Steps to Reproduce

1. Go to Modules
2. Go to tab "Updates"
3. Upgrade blockwishlist

**Screenshots**

![image](https://user-images.githubusercontent.com/310526/116887667-d8c00980-ac2a-11eb-8507-94226d670eab.png)

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @jacob-v-dam 

How did you install blockwishlist version v1.3.2 on 1.7.7.3 in the first place? :sweat_smile: 
Did you install PS1.6.1.24 and blockwishlist version v1.3.2, then you upgrade your shop to 1.7.7.3?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Ping @masiorama

**Comment by masiorama** [comment]
Hello @hibatallahAouadni , I don't remember when, but I guess I installed the module manually, definitely  on PS 1.7, since my project started in 2018 on 1.7.4. At the moment I am on PS 1.7.6.7 and the module seems to work, but since I plan to upgrade to 1.7.7 I want to upgrade all my modules beforehand.

**Comment by masiorama** [comment]
Ping @hibatallahAouadni

**Comment by florine2623** [comment]
Hello @masiorama ,

I can't reproduce your issue.
The blockwishlist module is not available in version 1.3.2 :
https://github.com/PrestaShop/blockwishlist/tags

**Comment by masiorama** [comment]
Hello @florine2623 ,
 actually I guess that since there was no blockwishlist for PS 1.7 till a few weeks ago, I (and some other people like the opener of the issue, @jacob-v-dam ) tried to install the module version for PS 1.6. Guess what, it worked till now (I installed version 1.3.2 on my ps in 2019). Now I do not know why there is no trace of the 1.3.2 release, I guess some clean up has been made, but there was something, otherwise I wouldn't have come up with this solution. Beyond that, it is the very same module manager inside PS 1.7 admin panel that asks me to upgrade to 2.0.0, so they are connected.

What do you suggest to do?

**Comment by matks** [comment]
> Hello @masiorama ,
> 
> I can't reproduce your issue.
> The blockwishlist module is not available in version 1.3.2 :
> https://github.com/PrestaShop/blockwishlist/tags

Unfortunately past releases were not done rigorously so there is no GitHub release, but there has been a v1.3.2 version of the module (distributed by Addons) https://github.com/PrestaShop/blockwishlist/commit/0eafb91aea556e4ae06c2ffd962aad54eeabb36d#diff-3986bd5e03f6be158323df2285d3a4725dc466df0b5d55128b258c59fa2ff044

**Comment by masiorama** [comment]
Thanks @matks !
What do you suggest to do, drop (disable and uninstall) the 1.3.2 module and install the new 2.0.0 version? I guess all records created by the clients would be deleted, so I should somehow port those records somehow, right? 
Thanks!

**Comment by fire2** [comment]
I know this question is off-topic, but I do not know if it is worth creating a new issue: why was this module not renamed to ps_wishlist if it is still maintained in Prestashop 1.7?

**Comment by matks** [comment]
> I know this question is off-topic, but I do not know if it is worth creating a new issue: why was this module not renamed to ps_wishlist if it is still maintained in Prestashop 1.7?

I guess only @Quetzacoalt91 can answer

**Comment by Quetzacoalt91** [comment]
> I know this question is off-topic, but I do not know if it is worth creating a new issue: why was this module not renamed to ps_wishlist if it is still maintained in Prestashop 1.7?

We figured out that renaming the modules for PS 1.7 was a mistake. Having similar modules but with different name make the upgrade process complex when you switch from 1.6.x.x to 1.7.x.x. We could have made a simple upgrade to keep the module compliant with the new version of PrestaShop, but with the new name we have to ask the merchant to manually remove the module with the previous one and install the module with the new name (and configure everything again).
That was tedious for you until we started to create a migration script for each module, like in https://github.com/PrestaShop/PrestaShop/issues/13350.

Hope this helps.

**Comment by fire2** [comment]
Thank you for the answer. Makes sense, although it still feels a bit strange that some are migrated and others are not.

**Comment by lmeyer1** [comment]
@hibatallahAouadni, @florine2623 
I can confirm this issue.

    foreach ($products as $k => $field) {
        $newStat = new Statistics();
        $newStat->id_product = $field['id_product'];
        $newStat->id_product_attribute = $field['id_product_attribute'];
        $newStat->id_shop = $this->context->shop->id;  <= exception here
        $newStat->save();
    }

There are two problems with this line:
- `$this` is used inside a function and not in an object context.
- `id_shop` in the stat table should come form `PREFIX_wishlist.id_shop`, otherwise, statistics are invalid in multishop context.

There is also a problem naming the tables: We now have `PREFIX_wishlist`, `PREFIX_wishlist_product`,  `PREFIX_wishlist_product_cart` and now `PREFIX_blockwishlist_statistics` ?!
