### ISSUE TITLE
Translation problem in blockwhishlist

### ISSUE THREAD

**Issue by henri9813** [PrestaShop/PrestaShop#24399]
#### Describe the bug

Add a product is in the correct language

Remove the product is not present in french

The sort select in the wishlist product view is not translated

#### Expected behavior

Respect the locale ( french in my case ),

#### Steps to Reproduce

For the first problem
1. Go to category view
2. Click on add to wishlist button ( little heart <3 ) 
3. Once you seen the green popup to tell you that's added
4. Remove the product from the wishlist
5. You will see the message in english

For the second
6. Go to your wishlist product view, the sort option is not translated

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/4645967/117483145-a1709600-af65-11eb-91e8-52162080660b.png)

![image](https://user-images.githubusercontent.com/4645967/117487037-cfa4a480-af6a-11eb-90ab-cebe9b3e6b71.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* Wishlist version: 2.0.0

**Comment by hibatallahAouadni** [comment]
Hello @henri9813 

I was able to reproduce the issue with PS1.7.7.4 and PS1.7.6.7 (with this version both sentence are not translated). I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

PS: FYI @kpodemski this sentence is missing in the `ModuleBlockwishlidtShop.xlf` file

Thank you

**Comment by lmeyer1** [comment]
I have the same problem and can give more information:

1. Go to International - Translations
2. Select `Translate installed modules` and `Block wishlist`
=> You will see in the summary that there are missing translations, but they do not show to the right.
3. Search for `Remove`, since this is a word in a missing translation.
=> This is what you will see : `4 missing`in red, but they do not display to translate. See screenshot.
![2021-08-27_172105](https://user-images.githubusercontent.com/7520695/131150877-0199c4dc-fd0f-4013-ab97-5d6415fc83d9.png)

Additional information
- PrestaShop version: 1.7.7.5
- Wishlist version: 2.0.1 (dev#9e15242)

**Comment by NeOMakinG** [comment]
@lmeyer1 

![image](https://user-images.githubusercontent.com/14963751/148243067-7d598907-ddb4-40dc-a4c4-e71d4bb9c2b5.png)


Sort by is hardcoded inside ProductsListContainer.vue :trollface:
