### ISSUE TITLE
Error during database upgrade with decimal columns

### ISSUE THREAD

**Issue by RomsC** [PrestaShop/PrestaShop#24423]
#### Describe the bug

An error occured during database upgrade from Prestashop 1.7.7.3 to 1.7.7.4.
The error is located in `src/PrestaShopBundle/Command/UpdateSchemaCommand.php`
I attach my [log.txt](https://github.com/PrestaShop/PrestaShop/files/6450987/log.txt) file to the issue.

#### Steps to Reproduce

1. Create a module that use Doctrine and a table that have a DECIMAL field
2. Install the module
3. Go to 1-Click Upgrade
4. Click on "Upgrade Prestashop Now!'

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3.27
* 1-Click upgrade version: 4.12.0

**Comment by hibatallahAouadni** [comment]
Hello @RomsC 

> Create a module that use Doctrine and a table that have a DECIMAL field

Could you please provide a module to help me reproduce the issue :pray: 

Thanks!

**Comment by RomsC** [comment]
Hi @hibatallahAouadni,

You can find a testing module in my repositories.
https://github.com/RomsC/upgradewithdecimalfield

**Comment by RomsC** [comment]
@hibatallahAouadni, do you need more information ?

**Comment by hibatallahAouadni** [comment]
Hello @RomsC 

Thanks for your patience and the details.
I was able to reproduce the issue with PrestaShop version 1.7.7.3. See the attached screen record and screenshot below:

https://drive.google.com/file/d/1kiRacuXdmMkq8sdMnZ5e6GRItiLW4kcD/view

Before displaying the error during database upgrade, a pop-up has been displayed asking if I want to rollback and I click on **Cancel** button: 

![image](https://user-images.githubusercontent.com/23308427/118505479-bc44c680-b72c-11eb-9a05-502fa5372a92.png)

After refreshing the page, I notice that the shop is already upgraded to 1.7.7.4. So, the issue is not blocking but it's confusing.
Well, I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment]
Ping @RomsC I couldn't install this module in PS1.7.6.8, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/118525559-9d9bfb00-b73f-11eb-96bd-bca2c695e009.png)

I need to check if this issue is it a regression or no?
