### ISSUE TITLE
Bug with multistore and backend grid view of products ?

### ISSUE THREAD

**Issue by angelflo** [PrestaShop/PrestaShop#24436]
#### Describe the bug

I have enable multistore feature on PS 1.7.7.4 last release
I have created my differents websites and in the table ps_shop I see them and each shop have it own id_shop => this part seems OK and logic.

But when i go in my Prestashop Backend >> Catalog >> Products and when I choose to display "**All Shops**" in the dropdown list at the top => **the products grid still display ONLY the products relative to Shop ID : 1**

When I choose to display the Prestashop query for this i saw in the query some clause who use the shop_id like for exemple :
**LEFT JOIN `ps_shop` shop ON (shop.id_shop = 1)**

How is it possible that in "All Shops" views i found restriction on shop_id = 1 ???

#### Expected behavior

"All shops" must display all products in ALL SHOPS => so the SQL query who return the grid of products should not include shop_id to restrict the products set on a specific shop !

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @angelflo 

Could you please provide a clear and concise steps to reproduce (we provide that block to fill it) :wink: 
And if you could provide a screen record, it will be super helpful :pray: 

Thanks!

**Comment by angelflo** [comment]
![screenshot2021 05 11-06_02_56](https://user-images.githubusercontent.com/9958770/117759678-7071b900-b224-11eb-8685-2cdb1acf646a.png)

Like you can see, in the backoffice catalog >> products : your query who return the list of products use some SPECIFIC shop_id whereas i ask to display "All Shops" products
It seems not Logic and with this SQL it display ONLY products of shop 1 => this is not what i want because i want to display ALL SHOPS products (like selected in the dropdown list in the header)

From what i see, but i'm not prestashop expert (I just try from few day to use your solution in replacement of magento) but i have good understanding of SQL

The good logic seems to replace in this  SQL query:

 JOIN `ps_product_shop` sa ON (p.`id_product` = sa.`id_product` AND sa.id_shop = 1)
should be :
JOIN `ps_product_shop` sa ON (p.`id_product` = sa.`id_product`)
=> do not restrict the product's list on a specific shop ID, like this is currently the case with this INNER JOIN who restrict on shop id 1

and also

LEFT JOIN `ps_shop` shop ON (shop.id_shop = 1)
should be:
 LEFT JOIN `ps_shop` shop ON (shop.id_shop = p.id_shop_default) 
=> use the product id_shop_default to display the corresponding shop name

**Comment by angelflo** [comment]
quelle déception de vouloir migrer sur une solution française et de constater que 5 ans après le lancement de pretashop 1.7, les fonctionnalités de base du multi boutique sont buguées à ce point :-(

https://www.prestashop.com/forums/topic/1048519-bug-multisites/

**Comment by matks** [comment]
Bonjour @angelflo 
PrestaShop est un projet open source: il devient meilleur grâce à la contribution de tous, l'équipe en charge ainsi que les utilisateurs. Si le multiboutique est un sujet important pour vous nous serons ravis d'accueillir vos contributions (en Anglais toutefois) pour le rendre meilleur.

**Comment by angelflo** [comment]
Bonjour @matks,

Le multiboutique est effectivement primordial pour nous comme pour probablement de nombreuses autres personnes.

Open source ou pas, lorsque nous prenons le temps d'investir du temps et de l'argent (déjà investit 500 euros pour la migration et j'avais un panier d'achat de près de 9000 € d'extensions que je m’apprêtai à valider avant de découvrir ces nombreux bugs concernant la gestion buguée du multistore) sur **une solution qui affiche dans ses spécifications** qu'elle supporte le multistore comme cela est le cas pour magento MAIS AUSSI pour Prestashop 1.7 il me semble que cela est un minimum d'avoir quelques chose qui fonctionne dans l'ensemble correctement, je ne parle pas ici de bug minime mais bien d'un bug général de la logique et du code concernant cet aspect.

**Comment by hibatallahAouadni** [comment]
@matks @angelflo in English please :wink: English is the norm on GitHub.

**Comment by angelflo** [comment]
@hibatallahAouadni  ... sorry please find the translation ;-)

The multistore is indeed essential for us as for probably many other customers.

Open source or not, when we invest time and money (already invested 500 euros for the migration and I had a shopping cart of nearly 9000 € of extensions that I was about to validate before discovering these many bugs concerning the buggy management of the multistore) on **a solution that displays in its specifications that it supports the multistore** like this is the case for magento BUT ALSO for Prestashop 1. 7 it seems to be a minimum to have something that works overall correctly, I'm not talking here about a minor bug but a general bug in the logic and code concerning this aspect.

I'm sorry to tell you this , but we don't speak about a new feature still in beta, but to something develop since PS 1.6 more than 6 years .. so when the basic of this feature is now totally buggy this is really not a good things for the image of your company ... except if your name is apple and in this case you can of course say : this is not a bug, this is a feature ;-)

**Comment by matks** [comment]
PrestaShop 1.7 supports multistore, and there is known bugs about multistore (it's such a complex topic). Some of these bugs have been fixed, some are yet to be fixed. If they are not fixed yet, it does not mean that it won't be fixed, or that we don't care. It doesn't mean that the issue is NOT important either. It just means that other issues have been considered, for whatever reason, _more_ important, so they were (or are being) tackled first. There's an immense amount of work to be done (897 bugs right now, and growing!), and tasks take time.

Developer time is limited, so if the amount of issues opened in a certain timeframe exceeds the amount of issues that can be processed using the available developer time, tasks will simply pile up. This is common to ALL projects. Now that you mention Apple, it might be worth it to read https://m.signalvnoise.com/software-has-bugs-this-is-normal/ that mentions Apple too. It explains very well the situation.

But PrestaShop is an open source, community project. If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about. This way the software becomes better for you and for any other user.

**Comment by angelflo** [comment]
@matks 
Thanks a lot for your point of view and for your answer but this is not mine.
When I plan to invest more than 9000 € in extensions (and many of them are from your company) I think that the opensource core (in that case prestashop 1.7.7.4) must offer the minimum stability requirement for the advertised features and in that case this is clearly not the case.

just find another list of multistore bug open since 2018 here https://github.com/PrestaShop/PrestaShop/issues/9723
and who seems still in pending 3 years after.

When you say to customer to also invest in a developper to fix bug in the core, i'm sorry to tell you that we can't win money on selling extension and in the same time ask to your customer to invest money to solve core bug (another time we speak here about major and critical bug who don't permit to use multistore feature AT ALL => for exemple i also discover that the stock management reserved qty also doesn't work in my dev server and i found explanation here https://github.com/PrestaShop/PrestaShop/issues/13210 )

You're developer and me too, so I think we know together that if we start a project with such critical bugs and wrond SQL query in core it's not good for the future.

Of course, i also have bug with magento and on my test to migrate on magento2 but honestly out if the box i have something really more stable with magento2 so i'll not try to invest a lot of money to buy all the prestashop extensions needed if i can't start with a PS core stable.

And when i read French Prestashop expert company who say me to downgrade on very old deprecated PS 1.6 due to major bugs on PS 1.7 released now since more than 5 years : 
https://www.prestashop.com/forums/topic/1048519-bug-multisite
I think you can understand why i'm affraid to invest in your solution ... :-(

**Comment by matks** [comment]
@angelflo sorry to hear that you are afraid to invest in PrestaShop project.

As I said before, this is an open source project. PrestaShop company invests in it to make the software go forward. Same for all contributors, and many PrestaShop developers. They invest time to make the software grow and they work on the topics that are important for them. If nobody invested time to fix the bugs you mention, it means nobody, of all the project contributors, consider this bug is a priority. It does not mean it's not important, it means there are other topics to be done/handled/fixed/completed before.

If you want the software to become better, you need to invest in it. If you find that any issue is critical for you, and it's important to have it fixed, then you can invest into having it done. Because it is a priority for you, not others.

There is 300,000 shops powered by PrestaShop so I think the software is definitely not flawless but not useless either.

**Comment by hibatallahAouadni** [comment]
Hello @angelflo 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9613. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #9613

**Comment by angelflo** [comment]
Yes, I discover that this bug #9613 is open since 2018 !!!
So i think that if 4 year later you still didn't fix it, it's really not a good idea to use your Prestashop software for people who have multi store.
