### ISSUE TITLE
Bad display on FO when maintenance mode & restricted-country mode is activated

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#24477]
#### Describe the bug
Bad display on FO when maintenance mode is activated

#### Steps to Reproduce

1. Go to admin and activate maintenance mode (do not add an ip) and save
2. Click on 'view my shop'
3. See error

**Screenshots**

In 1.7.8.x and develop
<img width="1440" alt="Capture d’écran 2021-05-12 à 12 09 50" src="https://user-images.githubusercontent.com/3034677/117958569-6f6f8300-b31b-11eb-9b3d-b69fabd88fdd.png">

In 1.7.7.x
<img width="1440" alt="Capture d’écran 2021-05-12 à 12 14 33" src="https://user-images.githubusercontent.com/3034677/117958815-af366a80-b31b-11eb-9676-ce8b0ccff5f3.png">

#### Additional information

* PrestaShop version: 1.7.8.x, develop
* PHP version: 7.1

**Comment by ghost** [comment]
Hello,

I think we it's related to : https://github.com/PrestaShop/PrestaShop/issues/13505

But not exactly the same

**Comment by khouloudbelguith** [comment]
Hi!

This issue is reproduced in the `restricted-country mode` following these steps:
1. Go to BO > International > Localization > Geolocation page 
2. Enable Geolocation by IP address
3. In the `Geolocation behavior for other countries` set, visitors cannot see your catalog
4. Try to access to the FO with another country
5. See error
![image](https://user-images.githubusercontent.com/16067358/119340764-3e843c00-bc93-11eb-8869-06800ca1dd1c.png)

Thank you!

**Comment by Progi1984** [comment]
Fixed in #24539
