### ISSUE TITLE
Product quantity changes to zero after modifying a product which has combination 

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#24505]
#### We expect 

Regular product modification, product quantity is saved without error after modifying a product which has combination

#### Steps to Reproduce

1. Through localization try to add Arabic package
2. Change your BO language to Arabic
3. Go to product list section
4. Select a product which has combination
5. try to save the product - or modify something and then save. 
6. See that the quantity will be 0

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: any version

**Comment by matks** [comment]
@samberrry We need you to fill the 4 bug report sections

```

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A
```

The 4 sections are needed to explore this issue.

**Comment by samberrry** [comment]
@matks for sure.

**Comment by matks** [comment]
@samberrry thank you 😊

**Comment by samberrry** [comment]
@matks welcome ;)

**Comment by florine2623** [comment]
Hello @samberrry ,

I was able to reproduce the issue with PrestaShop version 1.7.7.4, so I can confirm that this behavior is indeed a bug.
https://drive.google.com/file/d/1dWyORZfGrc3fHfCu9OxNuj9-gjyzkbIl/view
![Capture d’écran 2021-05-14 à 15 44 18](https://user-images.githubusercontent.com/16019289/118281721-d46ada80-b4cd-11eb-864f-d56e0cc47edf.png)


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.
Thank you
