### ISSUE TITLE
Bad URL for module catalog after disabling PrestaShop Marketplace module

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#24544]
#### Describe the bug

Disable PrestaShop Marketplace made an error

#### Expected behavior

No error 

#### Steps to Reproduce

1. **BO** > **IMPROVE** > **Modules** > **Module Manager**
2. Disable Marketplace
3. Reload the page
4. **BO** > **IMPROVE** > **Modules** > **Module Catalog**
5. See error

**Screenshots**

http://www.okom3pom.com/Pr!vaTe/errorModule.webm

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

I didn't manage to reproduce your issue with PS1.7.7.4, see the attached screen record below:

https://www.awesomescreenshot.com/video/3781716?key=8e99ee613ed0b925e473bf07bb83bb6c

Please check and feedback.
Thanks!

**Comment by ghost** [comment]
hello @hibatallahAouadni 
 
You dont reload the page it's only the link who is broken we need to reload for regenrate a new link see :

http://www.okom3pom.com/Pr!vaTe/errorModule.webm

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for th details!
I reproduce the issue with PS1.7.7.4, 1.7.8.x and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/118676644-dd281d00-b7fb-11eb-9c92-82e95c87270a.png)

But I didn't reproduce it with PS1.7.6.9, so it's a regression! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

**_PS: you need to reload the page after disabling the module Marketplace (to reproduce the issue) and then access to Module Catalog to see the error._**

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for details on Slack :wink: 
Well, we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #21588. 
And it's already fixed https://github.com/PrestaShopCorp/ps_mbo/pull/102 but not yet released https://github.com/PrestaShopCorp/ps_mbo/pull/108

Ping @eternoendless when will the new version be released?

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #21588

**Comment by ghost** [comment]
Thank you for feedback
