### ISSUE TITLE
From version 1.7.7.2 cost price is not update in product table only product_shop

### ISSUE THREAD

**Issue by smartsoftbox** [PrestaShop/PrestaShop#24630]
#### Describe the bug

From version 1.7.7.2 cost price is not update in product table only product_shop. (wholesale_price)

#### Expected behavior

In previous version both tables were updated.

#### Steps to Reproduce

1. Go to any Product
2. Click on edit
3. Enter value for cost price field and save
4. See table product wholesale_price and product_shop wholesale_price

**Screen record**

https://drive.google.com/file/d/1WKfRny30wBT-9IRMYcQUKO8OBcLsGvGm/view

#### Additional information

* PrestaShop version: From 1.7.7.2

**Comment by hibatallahAouadni** [comment]
Hello @smartsoftbox 

Could you please check this issue #24529 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by smartsoftbox** [comment]
Issue #24529 it is about update products order so it is not similar. It is stored in order_details table.

**Comment by hibatallahAouadni** [comment]
Hello @smartsoftbox 

Thanks for your patience :pray: 
I reproduce your issue only with PS1.7.7.4, see the attached screen record below:

https://drive.google.com/file/d/1WKfRny30wBT-9IRMYcQUKO8OBcLsGvGm/view

The `wholesale_price` in `ps_product` is not updated (it always = 0) but in `ps_product_shop` is correct.
I didn't manage to reproduce the issue with PS1.7.6.7, so it's indeed a regression:

https://drive.google.com/file/d/1vM4qwrT8vQ5_8khoNMOydzB-1it30_M4/view

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment]
Weird, @PrestaShop/prestashop-core-developers ! I don't see why the part has been impacted, if you guys have more insights 🤔

**Comment by atomiix** [comment]
Hi everyone, I think behavior has changed in 1.7.7.0 since this PR #20198. From what I understand, this is the expected behavior

**Comment by hibatallahAouadni** [comment]
Hello everyone,

> Mark `wholesale_price` and `supplier_reference` as deprecated. These values are already register with `ProductSupplier` ObjectModel, it's useless to duplicate values. I also restore the registration of these fields when there is no combination even if values can be fetched by a request into `ProductSupplier` table.

Thanks @atomiix for pointing to this PR, as you mentioned this is the expected behavior.
@smartsoftbox I think you can use the `wholesale_price` saved in product_shop :sweat_smile: 
So, I close this issue.

Thanks guys for your hard working :clap:
