### ISSUE TITLE
PrestashopLogger should save object type, even if object id is not set.

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#24706]
#### Describe the bug

Swiftmailer has thrown an exception, but `Prestashoplogger` did not save the `object_type` 'Swift_Message'.

#### Expected behavior

I expected that the exception waould be logged to `ps_log` with all it's attributes.

#### Steps to Reproduce

1. Go to *Configure - Advanced Parameters - E-mail*
2. Select *Set my own SMTP parameters (for advanced users ONLY)*, and define email parameters for SMTP
3. Enter an invalid *SMTP password*
4. Send a email from the FO (e.g. a reset password request)
5. The e-mail will fail to send (obviously)
6. Open phpmyadmin and look at the latest entry in the table `ps_log`. You will notice that it does not have an `object_type`, event though in `Mail::send()` `PrestaShopLogger::addLog()` was called with a parameter of `$object_type = 'Swift_Message'`

#### Additional information

* PrestaShop version: 1.7.7.4, develop
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

In my ps_log, the whole line doesn't exist like I didn't send the test mail and didn't receive the error.
But when I try to change an Order status, then I reproduce the issue, see the attached screen record below:

https://drive.google.com/file/d/1iKb36pR0AOT6nSlA2JbYPyt-r5kSIbln/view

I was able to reproduce the issue with PS1.7.6.7, PS1.7.7.4 and develop. I’ll add this to the debug backlog so that it’s fixed.
Thanks for your issue and your PR :rocket: 

Thank you

**Comment by lmeyer1** [comment]
@hibatallahAouadni 
> In my ps_log, the whole line doesn't exist like I didn't send the test mail and didn't receive the error.

That's right. Test emails don't log neither in `ps_log` nor in `ps_mail`. Only real emails get logged.
Sorry, I didn't test my steps to reproduce. I updated the issue.

**Comment by lmeyer1** [comment]
@hibatallahAouadni

There was another bug hidden, that caused failing mail not to be logged. Even real emails that failed. (see https://github.com/PrestaShop/PrestaShop/pull/24707#issuecomment-857672010)

**Comment by marwachelly** [comment]
Hello,
The issue is fixed. The  the object_type 'Swift_Message' is added.
https://www.awesomescreenshot.com/video/5813614?key=7bf7bb5cf1c47bb632ed58f5e39423da
Thanks,
