### ISSUE TITLE
Replace `pear/archive_tar` with Phardata

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#24715]
#### Is your feature request related to a problem?

As of PHP 5.3 not needed, see https://stackoverflow.com/questions/9416508/php-untar-gz-without-exec

#### Describe the solution you'd like
...

**Comment by hibatallahAouadni** [comment]
Hello @mvorisek 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: could you please descibe the solution you would like in your post :pray: 

Thank you

**Comment by matks** [comment]
Sounds good. If we can rely on PHP built-in class rather than an external dependency, we should do it.

**Comment by Progi1984** [comment]
@eternoendless Are we ok to add the `phar` extension to requirements and replace a dependency ?

**Comment by eternoendless** [comment]
I think we might be able to just remove the dependency. It is currently used only by:

- AdminModulesController, where the unused code has been removed in #27912
- AdminTranslationsController, the old translation interface, which is perhaps not needed anymore

**Comment by Progi1984** [comment]
@eternoendless AdminTranslationsController is not fully migrated. Check @matks issues : #10613 & #10614 (which seems duplicated)

**Comment by matks** [comment]
@Progi1984 It's not a duplicate because it seems there is a page 1/2 and a page 2/2 . But these pages are indeed migrated.

I'm afraid we've lost track of the situation but if I remember correctly, the Translations page has been fully migrated for "BO translations" but it's still being used for "Mail theme translations", something like that :/ .

I think we can close #10613 and #10614 as the main migration was done and we need to explore how the old controller might still be used in order to find out: a) is there some work left b) is that migration work or is it not related to migration

**Comment by eternoendless** [comment]
> AdminTranslationsController, the old translation interface, which is perhaps not needed anymore

> AdminTranslationsController is not fully migrated

You're right, AdminTranslationsController is still needed, in particular to be able to translate legacy modules.

When I said "not needed anymore" I meant just the part of the code that uses the `pear/archive_tar`.
