### ISSUE TITLE
Decimal separator non standard

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#24860]
#### Describe the bug

Hello,

decimal separator not standardized.

as you can see from this image the decimal separator in the price tab is not the same in all fields, commas and periods alternate.

In the price of the product there is the point while in the special prices the comma.

In product price tab, i have price without tax with comma separator and price with tax with dot instead of comma, if i set backoffice lang in english is ok but in italian is wrong

Kind regards

#### Expected behavior

both price should be with comma separator for decimal
<img width="1255" alt="Schermata 2021-06-08 alle 10 18 23" src="https://user-images.githubusercontent.com/5024055/121149850-4de2b800-c843-11eb-9e2f-bd7d82dce538.png">

1. Go to price tab in product section

#### Additional information

* PrestaShop version:  1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Betafer 

I didn't manage to reproduce your issue with PS1.7.6.8 & PS1.7.7.4, see the attached screenshot below:

### PS1.7.6.8
![image](https://user-images.githubusercontent.com/23308427/121153675-8df76a00-c846-11eb-8445-04ac12e27030.png)

### PS1.7.7.4
![image](https://user-images.githubusercontent.com/23308427/121153698-92238780-c846-11eb-80db-e1563b95bf7f.png)

It seems that your issue is not a PrestaShop core bug but most likely a module or an override problem.
We will close this issue.

Thanks!

**Comment by Betafer** [comment]
> Hello @Betafer
> 
> I didn't manage to reproduce your issue with PS1.7.6.8 & PS1.7.7.4, see the attached screenshot below:
> 
> ### PS1.7.6.8
> ![image](https://user-images.githubusercontent.com/23308427/121153675-8df76a00-c846-11eb-8445-04ac12e27030.png)
> 
> ### PS1.7.7.4
> ![image](https://user-images.githubusercontent.com/23308427/121153698-92238780-c846-11eb-80db-e1563b95bf7f.png)
> 
> It seems that your issue is not a PrestaShop core bug but most likely a module or an override problem.
> We will close this issue.
> 
> Thanks!

Please try in Italian

**Comment by matks** [comment]
@Betafer @hibatallahAouadni I think the scenario requires specific settings
- language (italian as said @Betafer )
- currency
- locale

**Comment by hibatallahAouadni** [comment]
Hello everyone,

@matks Thanks for the tip :wink: 
@Betafer Yes, you're right the issue occurs only with italian language :confused: 
But I think this problem may be fixed with this PR #24339 @PierreRambaud could you please confirm it :pray: 

Thanks!

**Comment by PierreRambaud** [comment]
> Hello everyone,
> 
> @matks Thanks for the tip 
> @Betafer Yes, you're right the issue occurs only with italian language 
> But I think this problem may be fixed with this PR #24339 @PierreRambaud could you please confirm it 
> 
> Thanks!

Not entirely, in fact my PR only aims to make numbers more standard in front, but if the back still allowed it, it's another problem. But it should be related to the old Product page, and it will be fix in the next version with the new migrated page :)

**Comment by hibatallahAouadni** [comment]
Hello everyone,

@PierreRambaud Thanks :pray: 
Well then, I reproduce the issue with PS1.7.6.7, PS1.7.7.4 and PS1.7.8.x. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by zorrobiwan** [comment]
This bug leads to more deeper problems like this one #26419 which is a duplicate of this one #25797.

IMHO PR https://github.com/PrestaShop/PrestaShop/pull/25807/commits/794af8aef007e72b2e69098b3fedcb81f99fc16f is just a workaround and not a valid solution.

Solving this issue will solve referenced issues as well in a better way

Thx

**Comment by florine2623** [comment]
I can't reproduce this issue on 9.0.0 with italian package installed and applied to my BO :

![Image](https://github.com/user-attachments/assets/739a84c5-00a1-48ef-8acd-7c9c026bf98d)
