### ISSUE TITLE
[BO] - New Product Page - an error thrown while updating the price with a comma

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24889]
#### Describe the bug

When you use italian language as your BO language, and try to update the product price in the new Product page, an error occurs

#### Expected behavior

the price update successfully 

#### Steps to Reproduce

1. install your shop with Italian language
2. **BO** > **CONFIGURE** > **Advanced Parameters** > **Experimental Features**
3. Enable **Experimental product page** and save
4. **BO** > **SELL** > **Catalog** > **Products** 
5. Edit a product
6. Try to edit the price
7. See error 

**Screenshots**

https://user-images.githubusercontent.com/43613217/187480258-03058259-5ad8-4e3d-aa7f-20d3c8ada901.mp4

https://www.awesomescreenshot.com/video/4050320?key=3b48730df51513e9bfe3d50fec052661

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

#### Blocked by 
Should be merged after https://github.com/PrestaShop/PrestaShop/issues/24103

**Comment by zuk3975** [comment]
according to https://github.com/PrestaShop/PrestaShop/pull/25574#issuecomment-975775632 - which branch should the fix PR target? (because the labels again points to 178)

**Comment by MatShir** [comment]
Might be fixed, I will try to reproduce it again !

**Comment by MatShir** [comment]
Seems to fixed !

**Comment by florine2623** [comment]
On PS `1.7.8.8` and branch `1.7.8.x`, the issue is still present :
<img width="296" alt="Screenshot 2023-03-09 at 14 43 38" src="https://user-images.githubusercontent.com/16019289/224042920-ff27d76b-7412-4a9e-84ab-bf86904f89d4.png">

With branch `8.0.x`, `8.1.x` and `develop`, it is fixed :
<img width="806" alt="Screenshot 2023-03-09 at 14 56 58" src="https://user-images.githubusercontent.com/16019289/224047359-99dc4c9d-77c3-4d45-ab46-e4f9033113d0.png">

@MatShir , what should we do about this issue ?

**Comment by MatShir** [comment]
It is fixed then :)
