### ISSUE TITLE
BO - Orders - invoice note with invalid data

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#24893]
**Describe the bug**
In the BO > Orders > Order details page > when we add an  invoice note with invalid data, an Update successful alert is displayed by the note is empty.

**Expected behavior**
The user should be able to save any value.

**Steps to Reproduce**

1. Go to BO > Orders > Orders list page
2. View any order
3. In the invoice Tab, add a note with < hello > and save
4. See error: the invoice  note is still empty

#### Additional information

- PrestaShop version: 178x
- PHP version: 7.3

**Comment by matthieu-rolland** [comment]
I reproduced this issue

**Comment by matks** [comment]
Might be related to https://github.com/PrestaShop/PrestaShop/issues/22540 and https://github.com/PrestaShop/PrestaShop/issues/9574

**Comment by matthieu-rolland** [comment]
> Might be related to #22540 and #9574

It's exactly the same bug as this one: https://github.com/PrestaShop/PrestaShop/issues/24534

that was fixed here: https://github.com/PrestaShop/PrestaShop/pull/24867

but on the order invoice's note (instead of order's  note)

Using `TYPE_STRING` field type in object model with `isCleanHtml` validation method triggers an escape method that does a striptag.   (we have this weird `psql` method that overrides the native `psql` function and do all kind of stuff depending on your field type 😓 )

**Comment by ghost** [comment]
There is the same for the customer message, I am trying to do this week i need to check because an email is sent

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

I was able to reproduce the issue with PS1.7.6.7, PS1.7.7.4 and PS1.7.8.x. I’ll add this to the debug backlog so that it’s fixed.
Thanks for your PR :rocket: 

Thank you
