### ISSUE TITLE
Bad request : header is too big

### ISSUE THREAD

**Issue by bastienuh** [PrestaShop/PrestaShop#24903]
#### Describe the bug

Sometimes, for some customers, without any logic, we have this on the homepage of our website :

![Capture d’écran 2021-06-08 à 19 30 08](https://user-images.githubusercontent.com/1685778/121489842-c462ef80-c9d4-11eb-88eb-bb050fe96972.png)

I have contacted the hosting service of our server to know if we can have a bigger header field size... but with this, we will treat the symptoms... not the main causes. So are you going to reduce the header size ? Because it seems to be **very** big if it make a bad request error...

#### Expected behavior

Smaller header field.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

**Comment by bastienuh** [comment]
It seems to be the cookie field in the header.

One of the cookie is named PrestaShop-bc20d32305bff7bca7f94559091d638e and has a size of 1,297 bytes.
Another one named PrestaShop-d128dcc0b239a91cabb9edf397675c4e is 951 bytes.
etc. (I have at least 5 cookies of this type).

What are this cookies for ? Why are they so big !?

Thanks.

**Comment by matks** [comment]
There is no persistent server-side sessions in PrestaShop, only cookies are used. Unfortunately in some situations too much data is stored inside session which lead to very large cookies. That could be your situation.

Similar to https://github.com/PrestaShop/PrestaShop/issues/12185

**Comment by bastienuh** [comment]
Ok I understand... but this is not an relevant behavior.

Because the customers are totally blocked with a bad request outside the website. The only solution seems to be to delete cookies, but :
- if you do that you loose you cart
- you are disconnected
- most of customers does not how to delete cookies

So : what solutions can you propose?

**Comment by bastienuh** [comment]
Moreover, we did not have this bugs on Prestashop 1.7.6.x.

So why do we have it on 1.7.7.4 ?

**Comment by hibatallahAouadni** [comment]
Hello @bastienu 

Your issue is a duplicate of #12185. Despite our efforts, we were not able to reproduce your issue with the provided information. 
You ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

We will close this issue.

Thanks!

**Comment by bastienuh** [comment]
_Despite our efforts, we were not able to reproduce your issue with the provided information._

You perfectly know the issue because it's a know issue, and one of your dev explained it. There is obviously an architecture problem here... and obviously, changes are required.

**Comment by hibatallahAouadni** [comment]
@bastienu thanks for your feedback!
Well, I'm not able to reproduce the issue with basic install :wink: 
@matks wdyt?

**Comment by matks** [comment]
> So : what solutions can you propose?

What solution do _you_ propose? 😄 

If you find that this issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

This is open source software: we are not working for you.
We are working on a common project that everybody can contribute to. We work on the topics we consider important (such as critical bugs and must-have features), and you can help by working on the topics that you consider important. We all work on topics we think are important for PrestaShop and submit our work to be merged inside the software. All this work, of many different people, is merged together and released so that everybody can benefit from it. It's the spirit of open source: everybody invests in it, and gets 100x its investment at the end of the day.

> There is obviously an architecture problem here... and obviously, changes are required.

This is not for sure.

Not having persistent server-side sessions in PrestaShop is a choice that was made a long time ago by people who are gone. It has benefits and it has drawbacks. For example, it's a lot easier to have PrestaShop run on multiple servers with a load balancer because there is no persistent server-side sessions. This is one benefit, there is others (the people who made this architectural choice had probably other choices in mind). There is also drawbacks, one of them is that cookies can grow very huge.

So maybe the solution is to modify PrestaShop to use persistent sessions server-side, but this is not a choice to be done quickly because it brings huge impacts and has also benefits and drawbacks.

**Comment by bastienuh** [comment]
Let me be clarify my point.

My point is not to say that _you_ have to fix this. My point is to say that you have the knowledge of the solution and the code, and that the solution proposed above is not a real solution, because it's unusable on final user side, or creating other big problems.

I'm not saying that not having persistent server-side sessions in PrestaShop is stupid. I'm saying that there is an architecture problem (or something not thought, for example by limiting those fields) because it's creating huge header with huge cookies fields, and, finally, the customer can not come on the website, because you seems to need a server with no header limit.

Lastly, about load balancers : having Prestashop running on load balancer server is, anyway, a nightmare (for a lot of things you know : modules updates not possible easily, same for images or images of some modules stored in module directory, etc.). Server-side sessions is really not the first thing to think about if you want to make Prestashop run of load balancer server 🤣 

I will think try to find a solution for my customer website.

**Comment by mehdi-ghezal** [comment]
Same issue here, I will find a solution by myself as Prestashop Core team doesn't seems to care. 

But it's again a bad signal sent to the community. If you want contribution to your project you should be more open minded about external feedback and opinion. It's not the first issue where I see this kind of communication.

**Comment by lakano** [comment]
> Not having persistent server-side sessions in PrestaShop is a choice that was made a long time ago by people who are gone. It has benefits and it has drawbacks. For example, it's a lot easier to have PrestaShop run on multiple servers with a load balancer because there is no persistent server-side sessions. This is one benefit, there is others (the people who made this architectural choice had probably other choices in mind). There is also drawbacks, one of them is that cookies can grow very huge.
> 
> So maybe the solution is to modify PrestaShop to use persistent sessions server-side, but this is not a choice to be done quickly because it brings huge impacts and has also benefits and drawbacks.

To try to fix this critical bug, could you please give me some details of what do you put in this cookie please? May be there is some documentation somewhere?

From my point of view, the old architectural choice to not have session in the DB to simplify horizontal scaling is good, but the architectural choice to put more than the strict required information is the cookie is bad. In theory, you should only keep informations about the user details, roles, permissions, and a proof that this cookie have been signed from the server side. All the others informations should not be inside the cookie but in the server-side DB or client-side storage (localStorage, indexedDB, ...) so my question is what do you put inside this huge cookie ?
