### ISSUE TITLE
FO | BO - customer message  with invalid data

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#24901]
#### Describe the bug

In the BO > Orders > Order details page > when we add a customer  message with invalid data, an Update successful alert is displayed but the message is empty.

In the FO Order History > when a customer add `{` `<` an error is display

#### Expected behavior

The user should be able to save any value. (expect html tags)

#### Steps to Reproduce

1. BO ->Go to an order add a message with `<`
2. FO -> Go to an order history add a message with `<`

#### Additional information

* PrestaShop version: 178
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

> In the BO > Orders > Order details page > when we add a customer message with invalid data, an Update successful alert is displayed but the message is empty.

About the first issue: I reproduce the issue: 

![image](https://user-images.githubusercontent.com/23308427/121552091-77047380-ca10-11eb-8856-ab9ec86cdf21.png)

IMHO, I think it must display an error alert and the message should be saved.

> In the FO Order History > when a customer add `{` `<` an error is display

About the second isssue, I think it's the expected behavior :sweat_smile: 

![image](https://user-images.githubusercontent.com/23308427/121553951-09f1dd80-ca12-11eb-808b-b0066404938f.png)

Cause why the customer send to the merchant a message with html tags?!

Ping @PrestaShop/product-team wdyt?

**Comment by ghost** [comment]
Hello @hibatallahAouadni 

For me it's the same https://github.com/PrestaShop/PrestaShop/issues/9574 

Customer don't enter html only < or {

**Comment by ghost** [comment]
I add a PR to see the way

**Comment by MatShir** [comment]
The order message is sent by mail and the message is displayed on the FO. So to avoid breaking the FO or the email, we blocked the possibility to send html tags.
But the merchants should be able to send any value (except tags) :)

**Comment by ghost** [comment]
A small minor label plz 

https://twitter.com/Progi1984/status/1401803612829982726

:rofl:

**Comment by hibatallahAouadni** [comment]
@okom3pom done :smile:

**Comment by ghost** [comment]
@hibatallahAouadni thank you :)
