### ISSUE TITLE
Adding products in an order already created, to a customer of a group without taxes, applies taxes anyway.

### ISSUE THREAD

**Issue by z72diego** [PrestaShop/PrestaShop#24962]
#### Describe the bug

A clear and concise description of what went wrong.

#### Steps to Reproduce
Steps to reproduce the error:

1. Create a customer group.
2. Assign this group as the default for a customer.
3. In the tax rules settings. Add a new rule for the tax that is active, for example Standard rate (21%), and set "Taxes = No taxes", for the customer group created.
4. Add a new order to the user from the back-office. The products of the order will be added without taxes.
5. Once the order is created, check its details and add a new product.
6. You will see the error. The product is charged to the order WITH taxes.

#### Additional information

- PrestaShop 1.7.7.2
- PHP 7.3.28

**Comment by hibatallahAouadni** [comment]
Hello @z72diego 

Could you please check this issue #23957 it seems related to yours.
Please check and feedback.

Thanks!

**Comment by z72diego** [comment]
Hi @hibatallahAouadni i don't think it's the same bug, but similar.

The user reports an error in the totals. The error that I report happens in the price of the specifically added product.

Please try to reproduce.

Thanks.

**Comment by florine2623** [comment]
Hello @z72diego ,

Please check my screenshots below :

**_My tax rule :_**
<img width="537" alt="Screenshot 2021-06-23 at 16 30 29" src="https://user-images.githubusercontent.com/16019289/123115452-686e8100-d440-11eb-9c8a-2a0430b1daa6.png">
**_Customer details :_**
<img width="862" alt="Screenshot 2021-06-23 at 16 37 47" src="https://user-images.githubusercontent.com/16019289/123116625-59d49980-d441-11eb-9a99-5d4ece21fbf6.png">
**_My initial order :_**
<img width="790" alt="Screenshot 2021-06-23 at 16 29 23" src="https://user-images.githubusercontent.com/16019289/123115562-7cb27e00-d440-11eb-8b06-310f0be8bb3e.png">
**_After I've added a product to the initial order :_**
<img width="790" alt="Screenshot 2021-06-23 at 16 29 38" src="https://user-images.githubusercontent.com/16019289/123116163-f64a6c00-d440-11eb-9069-aa90dc55677b.png">

To me your issue is the same as mentioned by @hibatallahAouadni : #23957

**Comment by hibatallahAouadni** [comment]
Hello @z72diego 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
