### ISSUE TITLE
Error when adding products with combinations to the cart Prestashop 1.7

### ISSUE THREAD

**Issue by Jonatan949** [PrestaShop/PrestaShop#24998]
When the customer adds a product with combinations to the cart, the combination of products that the customer chooses is not chosen, only appear the default combination. This problem only occurs in the mobile version, in the computer version it works fine.

Regards,

URL of a product: https://bitbitinformatica.com/fundas-movil-shingeki-no-kyojin/funda-shingeki-no-kyojin-escudos.html

URL example in video:https://user-images.githubusercontent.com/41923515/122376441-731ea700-cf64-11eb-86ad-7d88c60b362b.mp4

**Comment by hibatallahAouadni** [comment]
Hello @Jonatan949 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: I think the problem is from your theme :wink: 

Thanks!
