### ISSUE TITLE
Bad request on header and huge cookie size

### ISSUE THREAD

**Issue by bastienuh** [PrestaShop/PrestaShop#25001]
Hi,

(I open this discussions after a first issue (#24903) and a lot of investigations)

## Recap:
Sometimes, for some customers, we have a blank page on the homepage, with a Bad request. This is due to very very big cookie size. So I'm trying to find how we can have so big cookies on the browser and then sent in the header of each requests... causing bad request errors...

## Investigations: 
On my account, I have multiple cookies prefixed by "Prestashop-" : 
- PrestaShop-67fb7f2c09cf97bf9b9747900c7092b8
- PrestaShop-b667ef084cc25f6a675d2bfc2f33ecda
- **PrestaShop-bc20d32305bff7bca7f94559091d638e**
- PrestaShop-d128dcc0b239a91cabb9edf397675c4e
- PrestaShop-ef797002620351cc301e7998512559d3

The `Context::getContext()->cookie` uses the Prestashop-bc20d32305bff7bca7f94559091d638e (bolded above).

## Questions and help to go on further investigation:

1. Why do I have 5 Prestashop cookies? Is it a normal behavior or is it because the previous one are not deleted? Or maybe a module is created them?
2. How my Prestashop is knowing which one of the cookie it needs to use?
3. How to see what is the (decrypted) value of each of these cookies, to see which behavior (or module) is creating so much and so big cookies?

**Comment by hibatallahAouadni** [comment]
Hello @bastienu 

Thanks for the detailed report :clap: 
Ping @PrestaShop/prestashop-core-developers could someone please answer @bastienu questions :pray: 

Thanks in advance.

**Comment by PierreRambaud** [comment]
Hi,
The size limit for Cookies is 4096bytes (4097 for firefox), this is why there is a Bad Request.
Cookies can be created because of:
- ps_install => During the installation process
- username_addons and password_addons, just to save this information (should have been done in the admin cookie instead don't ask me why it's like that
- ps-s when switching Shop context
- ps-sg when switching Shop Group context
- psAdmin when using the admin backend

Afaik, they decided to use Cookie for scalability, but they forget to use the session system.
If you want to decrypt cookie, you can see it in Cookie.php file, everything is here.

**Comment by davidcylke** [comment]
@bastienu did you find a solution for this?

**Comment by hibatallahAouadni** [comment]
Hello @bastienu 

I think @PierreRambaud answered all your questions. Thanks @PierreRambaud :clap: 

As you know, since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

PS: @bastienu & @davidcylke you can always ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack) :wink: 

Thanks!
