### ISSUE TITLE
No Return Statement found in function -- Back Office

### ISSUE THREAD

**Issue by diksha-cedcoss** [PrestaShop/PrestaShop#25134]
#### Describe the bug

In the function description, it shows that 'true' should be returned if the CSS is successfully added but nothing is returned.

#### Expected behavior

The function should return something if it is given in description

#### Steps to Reproduce

1. Go to 'Prestashop Backoffice Files'
2. Open up 'classes > controller > controller.php'
3. Scroll down to 'line no. 422' where it is written it returns true but if you will see the function nothing is returned

**Screenshots**

[
![classes_controller_return_statement](https://user-images.githubusercontent.com/40261082/123510381-bb427580-d698-11eb-862b-b28d18211e35.png)
](url)

[
![class_controller_no_return_statement](https://user-images.githubusercontent.com/40261082/123510390-cb5a5500-d698-11eb-959f-0c4f5ca09146.png)
](url)

#### Additional information

* PrestaShop version: 1.7.8.0 beta version
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @diksha-cedcoss 

That's true, there's no return sentence in the end of this method:

![image](https://user-images.githubusercontent.com/23308427/123650591-02607000-d82b-11eb-93dd-5a2722abff6b.png)

Ping @PrestaShop/prestashop-core-developers could someone please confirm if this is a bug or not?
Thanks in advance :pray:

**Comment by matks** [comment]
Confirmed, the phpDoc is wrong.
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/Controller.php

It should be `@return void` or there should be no phpDoc `@return` line

**Comment by hibatallahAouadni** [comment]
Hello,

Thanks @matks for your confirmation!
I was able to reproduce the issue with PrestaShop version 1.7.6.7, 1.7.7.x, 1.7.8.x and develop. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by diksha-cedcoss** [comment]
Hello @hibatallahAouadni & @matks 

Thanks for considering my point

**Comment by Progi1984** [comment]
Fixed in #25391
