### ISSUE TITLE
Product deleteFeatures doesn't delete custom features

### ISSUE THREAD

**Issue by jonasburneika** [PrestaShop/PrestaShop#25163]
#### Describe the bug

ProductCore method deleteFeatures ignores custom made features in single store mode.

#### Expected behavior

After product deletion related feature_values removed.

#### Steps to Reproduce

1. Go to the product
2. Add custom feature value
3. Check database tables: **ps_feature_product, ps_feature_value, ps_feature_value_lang**, for newly added custom feature
4. Delete product
5. Check again for custom features in the database.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.1.33
* MySQL version: 5.7.34

**Comment by hibatallahAouadni** [comment]
Hello @jonasburneika 

I manage to reproduce the issue only with PS1.7.7.3, PS1.7.7.4 and PS1.7.7.5.
Even when I delete the product with id=20, the DB query still display the results, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/123938300-4a040a80-d997-11eb-846f-ac1a25b73da6.png)

![image](https://user-images.githubusercontent.com/23308427/123938318-4cfefb00-d997-11eb-9dff-5deb7b15fdb8.png)

![image](https://user-images.githubusercontent.com/23308427/123938337-50928200-d997-11eb-8bda-6f931c68ed95.png)


While with PS1.7.7.0 and PS1.7.7.2, I have no issue after deleting the product, the DB query display nothing:

![image](https://user-images.githubusercontent.com/23308427/123938230-36f13a80-d997-11eb-8bbd-36c528f3fbf2.png)

And it seems the issue has been fixed with the next patch release 1.7.7.6 and PS1.7.8.0.
So, I close the issue.

Thanks!
