### ISSUE TITLE
id_tax_rules_group in carrier table is not used anymore

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#25208]
#### Is your feature request related to a problem?

id_tax_rules_group in carrier table is not used anymore

#### Describe the solution you'd like

Remove the id_tax_rules_group  column from the carrier table

#### Additional context

* PrestaShop version: develop
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- steps to reproduce
- describe the bug
- expected behavior
- screenshots
- ...
You don't know how to get this information? Please read the following article: [How to create a bug report]
(http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could you please confirm that this column is not used any more in this table 🙏

**Comment by jolelievre** [comment]
The `Carrier:: id_tax_rules_group` field no longer exists in the entity, so the issue is legitimate indeed

**Comment by hibatallahAouadni** [comment]
@jolelievre thanks for your confirmation 
Changing the issue status to **`To Do`**
