### ISSUE TITLE
How to get category id in hookdisplayBackOfficeCategory($params) in prestashop 1.7.8.0

### ISSUE THREAD

**Issue by web23421** [PrestaShop/PrestaShop#25248]
#### Describe the bug

Hello, can not get id of the category, because $params['request']->get('categoryId') is not working anymore in prestashop 1.7.8.0 in this admin hook for module - displayBackOfficeCategory.

#### Expected behavior

$params['request']->get('categoryId') returns id in prestashop 1.7.7

#### Steps to Reproduce

1. Create module
2. Create public function hookdisplayBackOfficeCategory($params)
    {..}

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2.7

**Comment by florine2623** [comment]
Hello @web23421 ,
Can you provide the module so we can test it on our side ?
Thanks!

**Comment by kpodemski** [comment]
@florine2623 I think we can test it using ps_qualityassurance? 🤔 

hook into: `displayBackOfficeCategory`

and use:

`dump($params['request']->get('categoryId'));`

**Comment by web23421** [comment]
@florine2623 I can send you screenshot. The module is on sale for addons.

![333](https://user-images.githubusercontent.com/72523258/124600724-b1c2c580-de6f-11eb-852a-9b7f5eaf8276.png)

**Comment by florine2623** [comment]
@kpodemski & @web23421 ,

Indeed I was able to reproduce the issue using ps_qualityassurance module in PS 1.7.8.X.

In PS 1.7.8. I get the following error :
<img width="874" alt="Screenshot 2021-07-06 at 18 46 44" src="https://user-images.githubusercontent.com/16019289/124637872-91eccb00-de8a-11eb-8889-9ee53e20ae0d.png">

In PS 1.7.7 I get the data :
<img width="939" alt="Screenshot 2021-07-06 at 18 46 35" src="https://user-images.githubusercontent.com/16019289/124637879-95805200-de8a-11eb-823d-476ffc5a5908.png">


So I can confirm this is a regression.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by matks** [comment]
The root cause of https://github.com/PrestaShop/PrestaShop/issues/26471 and this issue is probably the same.

**Comment by l4nj1n9** [comment]
I have the same problem with 1.7.7.6....

**Comment by MatShir** [comment]
@web23421 Have you check the fix share by @matks on the 1.7.8.x branch, it might have fixed your issue. Could test it again on the 1.7.8.x branch?

**Comment by web23421** [comment]
> @web23421 Have you check the fix share by @matks on the 1.7.8.x branch, it might have fixed your issue. Could test it again on the 1.7.8.x branch?

Hello, I checked in the 1.7.8.0 Minor version - everything was fine - thank you. The topic can be closed.

**Comment by MatShir** [comment]
Thanks @web23421
