### ISSUE TITLE
Make a final 1.7.7.x version

### ISSUE THREAD

**Issue by mihaiSeoCup** [PrestaShop/PrestaShop#25262]
#### Is your feature request related to a problem?

Sincronize your site download arhive with the last version of github code: now you guys have a 1.7.7.5 version on the official website and a 1.7.7.6 version on the 1.7.7.x branch. 
ITS ambiguous !!

WHICH ONE OF THEM IS THE STABLE ONE?

#### Describe the solution you'd like

make a new copy after a change ahs been tested and finalized

#### Alternatives you've considered

none

#### Additional context

If you don;t do this people won;t know what version is the correct one

**Comment by matks** [comment]
Hello @mihaiSeoCup there is no 1.7.7.6 release on GitHub. There is work in progress, nothing stable.

1.7.7.5 is the latest stable release for 1.7.7.x ; 1.7.7.6 is not usable in production

I don't understand why you say it's ambiguous: on GitHub people can find the work in progress. Every software project works like this: there is a latest stable version, tested, approved, released, and next version is being built on a git repository.

**Comment by mihaiSeoCup** [comment]
Hi @matks  , 

soo, ok.  I'll use the arhive from the oficial website. Maybe the error is that i dind;t give it a composer install. MAYBE.

ALSO, what if i want to the stable version from github? 
You guys made a subbranch on  the 177x branch? 
because you lost me here. i mean no offence but it should've been 177x-stable branch, 177x-development branch ,  thats my opinion.

**Comment by matks** [comment]
> Hi @matks ,
> 
> soo, ok. I'll use the arhive from the oficial website. Maybe the error is that i dind;t give it a composer install. MAYBE.
> 
> ALSO, what if i want to the stable version from github?

On prestashop.com you can download the 1.7.7.5 ZIP, and this is exactly the same ZIP as you can download from GitHub on https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.5

Both ZIP are the same 😉  and you do not need to run `composer install`, the `vendor/` folder is already bundled inside the ZIP. This is a production-ready ZIP, you can upload it on a server and run the install wizard.

> because you lost me here. i mean no offence but it should've been 177x-stable branch, 177x-development branch , thats my opinion.

No worries, this means we might need to improve the documentation 😄 

I think you're thinking about something similar to gitflow, where there is a `main` branch that contains stable work, a `develop` branch that contains the work-in-progress not stable yet, and releases happen by merging the work of `develop` into `main`. So you expect a `177x-stable` branch for stable work and `177x-development` branch for work-in-progress not stable.

We have the `develop` for 1.7.7: it's `1.7.7.x`. But we have no `main` because we don't deploy code, we're a software editor. We don't run `main` in production, we provide ZIP archives. That is the difference. So our release process is to stabilize work on `1.7.7.x` and then build a ZIP ready-for-prod archive from it using git tags.

So the 1.7.7.5 tag is what is closest to a `main` branch for you https://github.com/PrestaShop/PrestaShop/tree/1.7.7.5 if you want to use "stable version from github" I think you should use git to checkout the tag.

**Comment by matks** [comment]
Actually in OSS where we don't have a `main` that is deployed in production this is the standard usage. See https://github.com/symfony/symfony and https://github.com/drupal/drupal for example
