### ISSUE TITLE
ps_facetedsearch v3.7.1 not displaying prices filter on 1.7.7.5

### ISSUE THREAD

**Issue by Dupflo** [PrestaShop/PrestaShop#25282]
#### Describe the bug

The price filter is not working when activated.

I am using the Warehouse theme an comment theme override to make sure it does not come from the theme 

I reset the module and occurred the same issue

I enable weight filter slider and it works

#### Expected behavior

When enable the price filter should be displayed on the left column

#### Steps to Reproduce

Go to ps_facetedsearch and enable price filter in your schema

**Screenshots**

<img width="1146" alt="Capture d’écran 2021-07-07 à 23 21 58" src="https://user-images.githubusercontent.com/39828779/124857336-22ee9f80-df7a-11eb-9d05-1c80da972db8.png">

<img width="167" alt="Capture d’écran 2021-07-07 à 23 22 33" src="https://user-images.githubusercontent.com/39828779/124857396-3863c980-df7a-11eb-9960-c47ca9eb8d48.png">

#### Additional information

* PrestaShop version: 1.7.7.5
* Plugin version: 3.7.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Dupflo 

I didn't manage to reproduce your issue with PS1775, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/124886574-aa68fc80-dfd4-11eb-8fae-9d0af71daf73.png)

Try to rebuild your entire price index by clicking on this button:

![image](https://user-images.githubusercontent.com/23308427/124886788-e00de580-dfd4-11eb-8d83-1f4237a0a035.png)

Please check and feedback.
Thanks!

**Comment by Dupflo** [comment]
@hibatallahAouadni I did and still getting the issue. The thing is it was working couple days ago. Products come from a webservice. Is an issue on the price data could be an issue ?

**Comment by hibatallahAouadni** [comment]
Hello @Dupflo 

> Is an issue on the price data could be an issue ?

May be :confused: Well, what I know for sure this issue is not related to PS Core.
So, I have to close the issue as we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by HanamiDangos** [comment]
Hello @Dupflo ,

I have exactly the same version of Prestashop, the same version of the module and the same template and exactly the same thing you mention happens to me. 

Have you found a solution to this bug?

Thanks,

**Comment by alisamie97** [comment]
I have prestashop 1.7.7.8 and ps_facetedsearch 3.8.0.
I have rebuilt the entire index and enabled the price facet
But It does not show up in front office side bar
