### ISSUE TITLE
Drop Guzzle in favor of Symfony HTTP client

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#25402]
#### Is your feature request related to a problem?

Yup, since the introduction of Guzzle to manage the PrestaShop Addons API the core team is annoyed but this package.
Since the migration to Symfony 4 have been done, why not rely on the Symfony HTTP Client and remove Guzzle ?

#### Describe the solution you'd like

1. Add the dependency symfony/http-client (afaik the API don't change in v4/v5, need to be checked in v6) 
2. Rewrite the implementation of MarketPlace API Client using Guzzle, so does the related tests if any
3. Remove Guzzle, add the notice to the changelog so the module contributors can already add the dependency to their own composer.json file

#### Alternatives you've considered

A upgrade of Guzzle have been planned and done, but imho this won't save us from any other breaking change in the next major version of Guzzle. The Symfony Core Team Policy (and [contracts](https://github.com/symfony/contracts/blob/main/HttpClient/HttpClientInterface.php)) are more secure.

#### Additional context

Nope. Except, I may contribute this feature if I get an explicit agreement.

**Comment by florine2623** [comment]
Hello @mickaelandrieu ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by eternoendless** [comment]
I just saw a very interesting [intro by Nicolas Grekas from 2019](https://symfonycasts.com/screencast/london2019/http-client-what-else).

I understand the advantages of switching libraries, and I see that there's some interoperability built-in, meaning that you can transform an HttpClient into other clients' interface, which is nice... as long as the other libraries are are coded to depend on interfaces and not implementations.

On the downside, it looks like there's no middleware support, processing is done through decorators, which is less flexible but not impossible to work with.

What worries me most is how we can provide a way so that existing modules that depend on Guzzle will work both in PrestaShop 1.7 (Guzzle 5) and 8.0 (Guzzle 7 or HttpClient). Implementations relying on circuit breaker will, according to @PierreRambaud. We _could_ include an HttpClient implementation into circuit breaker and use that by default...

> Rewrite the implementation of MarketPlace API Client using Guzzle, so does the related tests if any

Luckily there's no need to worry about that because the Marketplace is being completely removed from the Core (will be handled in a separate module). But the module itself will probably need to rely on Guzzle or circuit breaker if it wants to be compatible with 1.7 as well.

**Comment by matks** [comment]
@eternoendless I dont see a strong reason to prefer the Symfony Http Client, and we'll soon be able to release major versions more often so the BC promise should not be an issue anymore.

As you mentioned I expect module developers to rely more on Guzzle than Symfony Http Client (it's just more popular and it has been around for a longer time) so IMO we should keep Guzzle for now. It could change in the future but today, given it does not bring strong benefits, I think we should not add this piece of work to our roadmap.

**Comment by kpodemski** [comment]
Done 🎉
