### ISSUE TITLE
BO responsivity - button text should not overflow

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25422]
#### Describe the bug
Longer buttons overflow their container on lower resolutions.

#### Expected behavior
They should wrap

#### Steps to reproduce

1. **BO** > **Edit your Profile**
2. Change your admin language to **Čeština (Czech)**
3. Save
4. Go to **Orders** > **Invoices**
5. On your browser, enable the **Toggle device toolbar**
6. Choose iPhone 5s view
7. See error

#### How to fix it
Remove white-space: nowrap; from buttons.

#### Screenshots
![buttons](https://user-images.githubusercontent.com/6097524/126959787-fa44c4c5-05eb-425f-bc98-ab8e8673fd2f.jpg)

#### Additional information
* PrestaShop version: develop & 1.7.8.x

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for your issue! I reproduce the issue with develop and 178x. It's a regression! cause I didn't manage to reproduce it with PS1775, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/126963141-03bd3451-e551-4b3d-9a89-9f95a10983ac.png)

I think it's caused when we add the padding-right and padding-left to the content-div.
I’ll add this to the debug backlog so that it’s fixed.

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Hlavtox** [comment]
@hibatallahAouadni No it's caused by what I said :-) The button should be allowed to wrap. It should always fit no matter the outside container.

**Comment by Hlavtox** [comment]
@hibatallahAouadni This is standard behavior in Boostrap 4, so we need to override it. It's removed in Boostrap 5, I think they found out the same as we did. 👍

**Comment by hibatallahAouadni** [comment]
@Hlavtox yep I know :wink: I meant that the issue appears now cause we changed the paddings 
Thanks for your PR :rocket:
