### ISSUE TITLE
Blockwishlist module adds modals into <head>

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#25434]
#### Describe the bug

The html markup generated by blockwishlist is invalid. It adds the html code of the models using `hookDisplayHeader`, thus they are ending up inside the `<head>` tag instead of the `<body>`. 

#### Expected behavior

The generated HTML code should be valid.

#### Steps to Reproduce

1. With blockwishlist installed look at the source code. You will see:

```
<head>
(...) // alot of stuff
<!-- begin module:blockwishlist/views/templates/hook/displayHeader.tpl -->
<!-- begin /modules/blockwishlist/views/templates/hook/displayHeader.tpl -->
<!-- begin /home/www-data/ps/test1/releases/20210727080251/modules/blockwishlist/views/templates/components/modals/add-to-wishlist.tpl -->
<div
  class="wishlist-add-to"
  data-url="https://ch.test1.ps.sbgmb.net/module/blockwishlist/action?action=getAllWishlist"
> //                              <=  <div> is invalid here in <head>
(...) 
<!-- end /modules/blockwishlist/views/templates/hook/displayHeader.tpl -->
(...) // maybe other modules
</head>
<body id="index" class="lang-fr country-ch currency-chf layout-full-width page-index tax-display-enabled">
```

#### Additional information

* PrestaShop version: 1.7.7, blockwishlist 2.0.1
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @lmeyer1 ,

In the FO, my block wishlist is in the <body> :
<img width="1103" alt="Screenshot 2021-07-27 at 15 24 36" src="https://user-images.githubusercontent.com/16019289/127161278-52dad151-7072-4cad-878d-cf3ddf49823b.png">

Am I missing something ?
Thanks!

**Comment by lmeyer1** [comment]
@florine2623 
In Chrome Dev Tools, when you look at `Inspect element (Ctrl-Shift-I)`, you will not see the same thing as when you look at `Show source code of page (Ctrl-U)`. 
The issue shows using `Ctrl-U`, this is the real source code. When you look at `Ctrl-Shift-I`, you don't see the source code that was sent to the browser, but the code of the page in memory, as it was modified during page load. 
Chrome fixes automatically the problem and shifts the `<body>` tag up in the code, such that it comes before the first content tag, here `<div data-v-cab62222`.

I don't know if this issue of disrespect of code order will give rise to real problems in certain circumstances or not. I could imagine two things that could trigger problems:
- If  another module is loaded after `blockwishlist` in `hookDisplayHeader`, that module's code is inside the body tag instead of the head tag, thus that code could behave differently.
- If another browser does not fix the problem automatically itself, something bad could happen.

Anyway, I expect Prestashop to generate valid HTML code.

**Comment by florine2623** [comment]
Thanks for the details @lmeyer1 ,

Indeed I have the same result as you in PS 1.7.7.5 and PS 1.7.8.x with blockwishlist module v2.0.1.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by matks** [comment]
Nice bug report @lmeyer1 thanks 😉
