### ISSUE TITLE
Unable to enable modules in BO

### ISSUE THREAD

**Issue by onlinedigitaltrade** [PrestaShop/PrestaShop#25454]
Describe the bug

I am unable to re-enable a module after disabling it. Prestashop throws the error "Could not perform action enable for module undefined"

Expected behavior

Explain what you Prestashop should enable the module successfully.

Steps to Reproduce

1. Go to 'Modules' > 'Module Manager' in the BO.
2. Install a bunch of modules such as 'pscheckout', 'paypal', 'litespeedcache', 'gsitemap', and 'pscartbanner'
3. Disable a module (it can be any module).
4. Re-enable that module that was disabled on the previous step.
5. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/86529518/127373084-51152349-513c-49aa-a1c6-5b158d2d4915.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @onlinedigitaltrade 

I didn't manage to reproduce the issue with PS1775, see the attached screen record below:

https://drive.google.com/file/d/1pjZkyfJ_7xEedX4SkKx-kIytORFM-SuQ/view

I only encountred this issue on develop (see the original issue: #25340).
Please check and feedback.

Thanks!

**Comment by onlinedigitaltrade** [comment]
Maybe it's just a strange bug on my install... I'll wait to see what happens when ps 1.7.7.6 comes out. Hopefully it will be solved.

**Comment by khouloudbelguith** [comment]
Hi @onlinedigitaltrade,

Thanks for your feedback.
Me also, I did not manage to reproduce the issue with PS1775.
I attached a screen record
https://drive.google.com/file/d/1fMidYMrCKd1SeB9aYJ-A6zGDhL4Sh0Ke/view?usp=sharing
Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
I invite you to contact our support team: http://addons.prestashop.com/en/388-support to help you solve your issue.

Thanks!
