### ISSUE TITLE
1.7.8 - Content with left column is not aligned properly

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25467]
#### Describe the bug

Go to any category, see that content is not aligned with the container on both sides by 15px due to missing .row element that should be wrapping left-column and content-wrapper.

On pages without left column it's properly aligned.

PR to fix: https://github.com/PrestaShop/PrestaShop/pull/25460
ping @matthieu-rolland 

#### Expected behavior

Boostrap column should by wrapped by a row.
Page should not have extra 15px padding on the sides, limiting space. There is already a padding produced by container class.

#### How it looks
![before](https://user-images.githubusercontent.com/6097524/127622520-0e7aacad-fa9b-4add-9f6c-26505cce02ba.JPG)

#### How it looks after fix
![row](https://user-images.githubusercontent.com/6097524/127622575-78b27610-643f-4eb4-a289-736cf47a36ed.JPG)

#### Additional information
* PrestaShop version: 1.7.8

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I manage to reproduce the issue with PS1769, PS1775, and the branch 178x (1780)
**178x branch**
![image](https://user-images.githubusercontent.com/16067358/127628679-093bf328-8bea-4772-b6fb-0eacb6ffb352.png)
**PS1769**
![image](https://user-images.githubusercontent.com/16067358/127628982-bbd748ac-ea4a-403e-af19-45913b05e240.png)

I'll add this to the debug backlog so that it's fixed.
Ping @prestascott 

Thanks for the PR :slightly_smiling_face:

**Comment by Progi1984** [comment]
@PrestaShop/product-team Hi, should this issue be fixed in `1.7.8.x` or `develop` ?

**Comment by marionf** [comment]
@Progi1984 As it's not a regression, on `develop` branch ;)
