### ISSUE TITLE
Smarty Modifier Classname - compatibility with CSS BEM method

### ISSUE THREAD

**Issue by tups** [PrestaShop/PrestaShop#25502]
#### Describe the bug

I am facing an issue with using the CSS BEM method with the Smarty Classnames Modifier.

The function removes the double dashes, except it is the method to make "modify" classes in CSS BEM

#### Expected behavior

The original CSS classes

#### Steps to Reproduce

1. Create a template with the following smarty tag: `{['block__elem' => true, 'block__elem--mod' => true]|classnames}`

**Screenshots**

This gives the following result: `block__elem block__elem-mod`

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: 7.3

**Comment by Progi1984** [comment]
@eternoendless @PierreRambaud @NeOMakinG Are you ok that it's a bug and not a wanted behavior ?

**Comment by kpodemski** [comment]
My 2 cents, BEM classes are correct ones, so it's a bug

**Comment by hibatallahAouadni** [comment]
Hello @tups 

Thanks for reporting this issue!
After discussing with @kpodemski on Slack, it's indeed a bug! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

PS: thanks guys for your quick replies :rocket: 

Thanks!

**Comment by tups** [comment]
Hello,

I have already done the PR: https://github.com/PrestaShop/PrestaShop/pull/25501

For my part no worries, I have already made the correction on my projects, if it may be present on the next update it's good for me. It was to share with you the correction of this bug.

**Comment by hibatallahAouadni** [comment]
@tups thanks for your PR :rocket: (my last answer was just automatic answer :sweat_smile: sorry about that)

**Comment by NeOMakinG** [comment]
> @eternoendless @PierreRambaud @NeOMakinG Are you ok that it's a bug and not a wanted behavior ?

I think it's definitely a bug
