### ISSUE TITLE
Hook actionAttributeCombinationSave is not triggered after editing a Product combination

### ISSUE THREAD

**Issue by nshdigital** [PrestaShop/PrestaShop#25522]
#### Describe the bug

I'm creating a module to add custom fields on combination and I'd like to avoid overriding AdminProductWrapper and Product by using a hook "actionAttributeCombinationSave".
I tried to register this hook but it's not called. In fact the only method that should trigger it (Combination::setAttributes) is not called.

#### Expected behavior
Trigger hook actionAttributeCombinationSave when we save product information on backoffice.

#### Steps to Reproduce

1. Create a module that register actionAttributeCombinationSave
2. Go to backoffice and edit a product and its combination, then click on Save button
3. Hook is not triggered

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.27

I hope this is clear, otherwise do no hesitate to ask me for more detailed info that I didn't think about.

All the best guys, you're doing great things 😄

**Comment by hibatallahAouadni** [comment]
Hello @nshdigital 

Thanks for respecting the template and for reporting the issue!

I reproduce the issue with PS1775, PS1767 and develop, see the attached screen record below:

https://www.awesomescreenshot.com/video/4749476?key=63018bd0a5a56feefb97bb3ff2f6d63c

’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by ghost** [comment]
Hello @hibatallahAouadni && @nshdigital  

This hook is called when you add a combination not for update. 

For the update you can use : `actionObjectCombinationUpdateAfter 
`
Combination can be remplaced by all object.

**Comment by hibatallahAouadni** [comment]
Ping @okom3pom even with this hook, when I try to save the combination change, the hook is not triggered.
See the attached screen record below:
https://watch.screencastify.com/v/jbqBUOHaKqjWt1TthphE

**Comment by ghost** [comment]
Hello,

@hibatallahAouadni this hook is called when you **add** a combination not for update, on the video you update a combination.

And the return is in XHR 

You can see this video https://www.okom3pom.com/video/actionAttributeCombinationSave.webm

I can add this hook for update on a PR but we need ask dev and PM teams before.

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

The issue is about edit a combination not creating :wink: 
> #### Steps to Reproduce
>
> 1. Create a module that register actionAttributeCombinationSave
> 2. Go to backoffice and edit a product and its combination, then click on Save button
> 3. Hook is not triggered

As you said we may need a PM approval, if we don't have a hook that can save the edit of combination.
Let's check with Dev Team :wink: 
Ping @PrestaShop/prestashop-core-developers do we have a hook that can save the combination edit?

**Comment by okom3pom** [comment]
This one : `actionObjectCombinationUpdateAfter`

**Comment by atomiix** [comment]
@hibatallahAouadni I think the hook `actionObjectCombinationUpdateAfter` is called actually:

https://user-images.githubusercontent.com/2168836/136940644-8ca97aaa-b07b-4451-b056-0e5858823ea1.mov

**Comment by hibatallahAouadni** [comment]
Thanks @atomiix :rocket: 
Closing the issue!
