### ISSUE TITLE
The discount mode does not apply to all currencies (despite being set to do so)

### ISSUE THREAD

**Issue by MattTreeman** [PrestaShop/PrestaShop#25532]
#### Describe the bug

I am trying to set a discount mode (-15%) for all the products and all the currencies (I have two - PLN and EUR). However, it only applies to PLN and not for EUR. I have also tried to set the discount to EUR currency specifically (omitting the PLN), but the result is the same - the discount for EUR simply does not apply. 

#### Expected behavior

I would like to have the discount applied to all currencies (both PLN and EUR) once I choose this option. 

#### Steps to Reproduce

I am setting the discounts through: Catalog -> Cart Rules -> Specific Price Rule.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @MattTreeman 

I didn't manage to reproduce the issue with PS1775, see the attached screen record below:

https://drive.google.com/file/d/1xSxTcHStabAkIjezdG-6q4N8mjGOWE_b/view

Please check and feedback.
Thanks!

**Comment by MattTreeman** [comment]
Hi @hibatallahAouadni ,

Thanks for your time and effort. Actually it happened to me also on the older version of Prestashop, so I don't think it's the upgrade issue. I have also tried to set the amount, not percentage discount (like you did), but the effect was the same - no discounts for EUR.

Any idea what can be wrong here? Or where should I report it to be sure it will be dealt with?

Thanks,
MattTreeman

**Comment by hibatallahAouadni** [comment]
Hello @MattTreeman 

I'm really sorry, but the issue seems not related to PS Core. If you want disable your custom/no-native modules and switch to the default theme, check if you still encounter the issue. Don't forget to disbale your overrides.

If you still encounter the issue, you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Closing the issue as we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Thank you
