### ISSUE TITLE
Set minimum quantity for sale doesn't work, decreaseable quantity in the checkout.

### ISSUE THREAD

**Issue by Spiros333** [PrestaShop/PrestaShop#25566]
On cart page, the minimum purchase order quantity for a product is 5 (wholesales) but you can decrease product quantity in the checkout.

Can you assist on this please?

![afbeelding](https://user-images.githubusercontent.com/85503636/128936318-76fefba5-0fef-4a14-b1d4-52b4fbd36424.png)
![afbeelding](https://user-images.githubusercontent.com/85503636/128936385-602c3d96-bd23-4f0e-a9cc-1d270500c4dc.png)

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Spiros333 

I didn't manage to reproduce the issue with PS1762 and PS1776, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/128985704-94858421-191f-4cca-8f7e-4498773c24bc.png)

I think your issue is related to some installed modules or your theme.
I close this issue as it's not a PrestaShop Core bug.

Thanks!
