### ISSUE TITLE
1.7.7.6 - ps_order_recalculate_shipping set to NO - Not working correctely

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#25565]
#### Describe the bug

ps_order_recalculate_shipping set to NO - Not working correctely

#### Expected behavior

When the configuration "Recalculate shipping costs after editing the order" is defined to "No" and the user edits the carrier of an order, the shipping cost of the order remains the same. The order total and invoice are not impacted.
Specs: https://github.com/PrestaShop/prestashop-specs/pull/258

#### Steps to Reproduce

0 - Set "Recalculate shipping costs after editing the order" to "NO".
1 - Make an order with a free shipping carrier and pay with bankwire for instance;
2 - Go to the backoffice set the order as "Processing in progress";
3 - Change the carrier to a paid one and introduce a tracking number;
4 - Set the order as "Shipped";

After you change the order status to "Shipped" it will show an additional payment that will match the shipping price of the carrier selected at step 3.

#### Additional information

* PrestaShop version: 1.7.7.6
* PHP version: 7.2

**Server info:**

- Server information Linux 160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64
- Server software version: Apache
- Memory limit: 1024M
- Max execution time: 600
- Upload Max File size: 128M
- PHP version: 7.2.24-0ubuntu0.18.04.8

**Database information**

- MySQL version: 5.7.35-0ubuntu0.18.04.1
- MySQL server: 127.0.0.1
- Tables prefix: ps_
- MySQL engine: InnoDB
- MySQL driver: DbPDO

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

I didn't manage to reproduce the issue with PS1776, see the attached screen record below:

https://drive.google.com/file/d/1lFd-Ip_g3REJREDhh80U3mCFVFY6HyqW/view

Please check and feedback.
Thanks!

**Comment by seederp2p** [comment]
Hello,

I was able to reproduce it on the official demo yesterday. please check this:

https://we.tl/t-R8HzBjaCRs

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

I can't access to your screen record, could you please record your screen with this free tool **Screencastify** :pray: 
Please check and feedback.

Thanks!

**Comment by seederp2p** [comment]
https://drive.google.com/file/d/1jTdQG56K4I9k-z0e1Jfzp8HiZ1dEs7D_/view

**Comment by seederp2p** [comment]
Are you able to open the video now?

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

Yess! thanks for your feedback.
I reproduce the issue with PS1.7.7.5, PS1.7.7.6, PS178x and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/129266528-56d5cea9-0d64-4bdc-ac7b-5d429ca0d8e8.png)

---
I didn't reproduce the issue with **PS1.7.7.4**
### so it's a regression!

![image](https://user-images.githubusercontent.com/23308427/129267792-a51f349f-3f10-4a44-ac90-7b9e2b780fea.png)

I’ll add this to the debug backlog so that it’s fixed.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment]
@PrestaShop/product-team 
**Context :**
- When the configuration "Recalculate shipping costs after editing the order" is defined to "No"

**Question :**
- Actually the amount of shipping amount of an order change when we change a carrier (from a free to a paid one, for example, or the reverse too) in an order, is that correct ?

**Comment by MatShir** [comment]
When the configuration "Recalculate shipping costs after editing the order" is defined to "No" and the user edits the carrier of an order, the shipping cost of the order remains the same. The order total and invoice are not impacted.
Specs: https://github.com/PrestaShop/prestashop-specs/pull/258

**Comment by hdkcreative** [comment]
Prestashop 1.7.6.8. We modify a order in the backoffice and now we have have  the sum is incorrect. 

The correct sum would be 171€ but the total in the order is 266 €.

we don't know where is the error. 

It happens only in certain orders, not all.

![image](https://user-images.githubusercontent.com/18191896/140444118-ff8afa01-6ca9-4f95-b208-73997d297aea.png)

**Comment by Progi1984** [comment]
Fixed in #26481 by @Progi1984
