### ISSUE TITLE
Error uploading product images.

### ISSUE THREAD

**Issue by nahrin** [PrestaShop/PrestaShop#25598]
I upgraded my prestashop store from 1.7.7.4 to 1.7.7.6, yesterday. Today I created a new product I can save all the written information but when I upload the product images an html text is displayed.
![image](https://user-images.githubusercontent.com/12375876/129390751-264a4b06-96ba-4995-99cd-760d6b53469f.png)

**Comment by arouiadib** [comment]
Are you sure you just upgraded? no other tasks after (like server config)?

This is the error: `Unable to guess the mime type as no guessers are available`, and it might be caused by php version and/or phpinfo extension status.

[Further reading.](https://www.prestashop.com/forums/topic/625041-server-responded-with-500-code-when-upload-an-product-image/)

**Comment by hibatallahAouadni** [comment]
Hello @nahrin 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
