### ISSUE TITLE
Register / Login with social channel

### ISSUE THREAD

**Issue by DracoBluee** [PrestaShop/PrestaShop#25601]
Register and login with social account facebook, google etc. I think it's a good feature for prestashop.

**Comment by eveneme** [comment]
Good idea

**Comment by Oksydan** [comment]
I think it shouldn't go into core. API might change and prestashop will  have to keep it up to date. There is a lot cheap module out there and even free ones https://github.com/oneall/social-login-prestashop

**Comment by matks** [comment]
Agreed with @Oksydan : such features will never go into the Core because they rely on third party.

AFAIK there is already good capabilities to plug in any SSO on Front Office and there is an issue to do the same for Back Office https://github.com/PrestaShop/PrestaShop/issues/23243

The Core will welcome the right mechanisms to allow adding SSO modules (probably hooks) but will not implement any of the connections itself.
