### ISSUE TITLE
Update to bootstrap 4.6 & 5 framework

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#25608]
update to the current version bootstrap new major version

**Comment by kpodemski** [comment]
You're adding the same issue as one from the few weeks ago. What's the point? :)

**Comment by eveneme** [comment]
The point is that it should be included in the next major version

**Comment by kpodemski** [comment]
Creating duplicated issues won't help 🙂 

We know about this issue and there are other topics where we've already discussed this.

**Comment by matks** [comment]
@kpodemski is right.

I already said in https://github.com/PrestaShop/PrestaShop/issues/25550 that this is already included in https://github.com/PrestaShop/PrestaShop/issues/14533 item. "Classic theme should promote code quality and best practices - upgrade and rework" implies to use, as much as possible, up-to-date dependencies.

In next major version we'll do our best to upgrade bootstrap versions to a stable, standard, up-to-date version, but we'll maybe not pick the latest if it's too much changes for child themes. We must consider the upgrade process and make sure **it is as easy as possible for people to upgrade**. Dependencies update can be a big issue.

Please dont create duplicate issues, this will not change what is inside the roadmap 😄 . We dont put things in roadmap because lot of issues are opened about it. Also it could start to look like spam.
