### ISSUE TITLE
New fields in smarty template urls when using child theme

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25667]
#### Is your feature request related to a problem?

Here is my case. 
Client want to create easy to maintain theme for their franchise stores.
Franchise stores are not multistores but separate installation for different countries and they are not operated by client employees but by different company.
Our goal is to provide theme and configured store that will be looking the same as main store but with modification for country needs.
Child theme are perfect use case here but we are facing an issue with parent theme urls.

Inside parent theme we are using `{$urls.img_url}` to use img files inside template.
When child theme is used - `{$urls.img_url}` is pointing to child theme not to the parent theme, so images are not available. 
We are forced to copy files from parent theme to child theme.

#### Describe the solution you'd like

When we are using child theme and in theme.yml file config `assets.use_parent_assets` field is true.
We could change that `{$urls.img_url}`, `{$urls. theme_assets}`, `{$urls. css_url}`, `{$urls. js_url}` will be pointing to parent theme instead of child and provide new fields with `child_` prefix like `{$urls.child_img_url}` pointing to child theme (current).

**Comment by hibatallahAouadni** [comment]
Hello @Oksydan 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
And thanks for your PR :rocket: 

Thank you

**Comment by matks** [comment]
> When we are using child theme and in theme.yml file config assets.use_parent_assets field is true.
We could change that {$urls.img_url}, {$urls. theme_assets}, {$urls. css_url}, {$urls. js_url} will be pointing to parent theme instead of child and provide new fields with child_ prefix like {$urls.child_img_url} pointing to child theme (current).

It could also be the other way around, provide new fields with parent_ prefix like {$urls.parent_img_url}

@PululuK and @kpodemski : you might have some experience using child theme.

Is it more needed to access parent theme assets / variables or child theme assets, or fifty/fifty? What should be the "default": parent or child?

**Comment by kpodemski** [comment]
@matks 

I completely trust @Oksydan on this one, more often you want to get assets from the parent because the child theme is suppose to change only parts of the parent theme :-)

**Comment by matks** [comment]
Thank you @kpodemski for the insight 😉
