### ISSUE TITLE
Faceted search - back/forward buttons in browser do nothing

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25669]
#### Steps to Reproduce

1. Enable faceted search, setup some filters.
2. Go to category, select one filter, select another filter.
3. Use your browser's back button and see that it changes the URL, but the page itself does not change.

#### Expected behavior

Back button should work, page data should be updated and URL should stay consistent with the data shown.

#### Video

https://drive.google.com/file/d/11Ptf6EbfSsdC-HiD_91zQVj46e-6of2T/view?usp=sharing

#### Additional information

* Browser: Chrome 92.0.4515.131
* PrestaShop version: 1.7.6.2
* Faceted version: 3.5.0
* PHP version: 7.2

Ping @PierreRambaud

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for your detailed bug report :clap: 
I reproduce the issue with PS1767, PS1777, but it seems the issue has been fixed with PS1780_build2, see the attached screen record below:

https://drive.google.com/file/d/1aDdZP2Ze6w9p-G3-nBe-X0p4WrXzbKdm/view

With Faceted Search 3.7.1.
Browser Chrome: 91.0.4472.114
Please check and feedback.

Thanks!

**Comment by NeOMakinG** [comment]
@Hlavtox It reminded me of something, I think we fixed it on 1.7.7 or something like it

**Comment by hibatallahAouadni** [comment]
@NeOMakinG Indeed, it has been fixed with PS1780 :wink:
