### ISSUE TITLE
BO - Unable to save "meta_keywords" field on suppliers

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#25705]
#### Describe the bug

When saving a supplier, the "meta_keywords" field is not saved in database.

#### Expected behavior

The data should be saved

#### Steps to Reproduce

~~ ~~1. Go to Catalog > Brands and Suppliers and create a new **Supplier**,
make sure to enter some tags in the "meta_keywords" field.~~ ~~

1. Open an existing supplier with some already saved "meta_keywords" 

2. Add some meta keywords to the supplier and save

3. You'll see data is not saved.

4. Try to edit again the supplier and remove the meta_keyword

5. The meta_keyword is not removed

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @gennaris 

I didn't manage to reproduce the issue with PS1777, see the attached screen record below:

https://www.awesomescreenshot.com/video/4977446?key=b9c76b6bcaed0ab2e55660433413027b

Please check and feedback.
Thanks!

**Comment by gennaris** [comment]
Hi @hibatallahAouadni !
Yes it looks like this is happening only on already existing suppliers (I have edited original comment)

Try opening the supplier you already created in your recording, add a new "meta keyword" and click save again. 

You will lose your modification.

**Comment by khouloudbelguith** [comment]
Hi @gennaris,

Thanks for these clarifications.
I manage to reproduce the issue with the PS1770 & PS1777 and PS178x branch.
It is ok with PS1769.
I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by gennaris** [comment]
Hi @khouloudbelguith , 
being in a hurry to fix it for a customer , 
I checked the code and figured out the issue myself - Just sent a PR.

**Comment by Progi1984** [comment]
Fixed by @gennaris in #25725
