### ISSUE TITLE
BO combination price editor problem - Number comma formatter

### ISSUE THREAD

**Issue by skeccy** [PrestaShop/PrestaShop#25718]
#### Describe the bug

https://user-images.githubusercontent.com/70293774/131098475-aa0a9a48-f8f8-4d3c-ab09-e007d2807b9e.MP4

Hello everyone, I am writing this post to report a problem I had recently following an update of prestashop from version 1.7.7.6 to 1.7.7.7.
In the back office, if I try to edit a product that contains combinations, as soon as I enter the single combination editor, the price entry seems to go crazy. It is useless to try to cancel the price. I can only enter the price through massive actions in the combination summary. The problem seems to arise especially with already existing combinations. I am attaching a video showing the problem.

#### Steps to Reproduce

1. Go to BO > Catalog > Products > Edit a product with combinations
2. In the Combinations Tab > Edit a combination
3. In the field `Impact on the price (tax incl.)` > try to add a decimal with a comma or point for example `1.2`, `1,2`, `1N000`
4. See error => the price is converted

Seems related to this PR: https://github.com/PrestaShop/PrestaShop/pull/24339
Has anyone had the same problem as me? Is there a solution?
Prestashop 1.7.7.7
PHP 7.3

Thanks

**Comment by khouloudbelguith** [comment]
Hi @skeccy,

Thanks for your report.
Please next time you need to follow the exact template to create a new issue.
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

- Did you use the 1-click upgrade module? if yes, what is the exact version did you use?
- Have you any errors during the upgrade?
- This issue occurs only with products created before the upgrade or the same issue when you try to edit new products created after the upgrade?

Thanks!

**Comment by skeccy** [comment]
@khouloudbelguith Scuse me, this is my first bug report. sorry.

One click upgrade module version is 4.12 no error reported during upgrade
The error occurs both on an existing combination created previously and with the creation of a new product with combinations. The error also occurs if I write the price with decimals, as soon as I put the comma or the point using the numeric keypad of the keyboard

**Comment by khouloudbelguith** [comment]
@skeccy, thanks for these clarifications.

I manage to reproduce the issue with PS1776 and PS1777.
It is ok with PS1775.
I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by skeccy** [comment]
Thanks a lot @khouloudbelguith 
I'm not a programming expert, but I want to help the community develop the project so I find it very important to report any bugs.
if I find a solution I will be happy to communicate the solution. Thanks

**Comment by skeccy** [comment]
@khouloudbelguith Scuse me, How can I contact you to report another problem of mine other than the one reported?

**Comment by MatShir** [comment]
@skeccy If you find a bug, you just have to create a new one issue as you did for this one. On your issue, you have to share the steps of how did you reproduce the bug, your PrestaShop's version and PHP's version.

**Comment by khouloudbelguith** [comment]
Hi,

Fixed by https://github.com/PrestaShop/PrestaShop/pull/25749

Thanks!

**Comment by skeccy** [comment]
@khouloudbelguith 
I'm sorry but I didn't understand in prestashop 1.7.7.7 which file to modify, assuming that I use the classic theme. What is the correct path where I can make the change?

**Comment by khouloudbelguith** [comment]
Hi @skeccy,

The PrestaShop 1.7.7.8. is released.
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks!
