### ISSUE TITLE
PrestaShopDatabaseException after update

### ISSUE THREAD

**Issue by Jojo-Kaly** [PrestaShop/PrestaShop#25730]
#### Describe the bug

Hi ! After Preestashop update from 1.7.7.1 to 1.7.7.7, I have a PrestaShopDatabaseException messag on front office in debug mode.
Thank you for your help!

<img width="1440" alt="Capture d’écran 2021-08-27 à 22 35 06" src="https://user-images.githubusercontent.com/59056657/131187460-28c2308c-f44c-4d56-b688-5dd8982c6390.png">

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Jojo-Kaly 

With the standard install & upgrade, I didn't encounter any issue while upgrading from 1.7.7.1 to 1.7.7.7. And it seems your issue related to a third-module cause in PS, there's no table with this name `_template`:

![image](https://user-images.githubusercontent.com/23308427/131318499-c1498292-aa95-4344-97c7-792e453288f0.png)

So, your issue is not a PrestaShop core bug. We will close this issue.
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
