### ISSUE TITLE
B2B option is disabled but company field still apparead in Order (commande) Page

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#25752]
Hello

I'm using on PS 1.7.7.7 and i disabled the B2B option but the company and vat fields still there **IN THE ORDER PAGE** NOT create_account page

so I need your help please to know if this is normal or it's a bug , so if it's normal the how can I remove those fields from the theme instead removing theme from Zones géographiques because i have 40 countries to edit

i![image](https://user-images.githubusercontent.com/11594433/131491190-2720b85f-f56c-4882-bc99-9738df180bf2.png)
Regards
![image](https://user-images.githubusercontent.com/11594433/131491272-f7112783-f2db-49a9-8ba1-6b18ad23e79c.png)
![image](https://user-images.githubusercontent.com/11594433/131491290-3ebfadff-57b7-4301-8fc4-1427132a2798.png)

Additional information
Version de PrestaShop : 1.7.7.7
Version de PHP : 7.2.34
Limite de mémoire : 80128M
Temps maximal d'exécution : 72000
Taille max. pour envoi de fichiers : 5G

**Comment by florine2623** [comment]
Hello @go-sudo ,

I was able to reproduce the issue with PrestaShop version 1.7.6.7 and PS 1.7.7.7.

I will ping product team to check if this is the wanted behavior or a bug.

Thank you

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

I have the B2B option disabled and the fields Company and VAT number displayed in the step 2 of order form
<img width="728" alt="Screenshot 2021-08-31 at 17 26 05" src="https://user-images.githubusercontent.com/16019289/131531332-a9db57a7-6307-4b4b-a545-2fee6354c7fd.png">

In order to hide those fields, we need to go to International > Locations > Countries > Delete those 2 elements 
<img width="420" alt="Screenshot 2021-08-31 at 17 27 41" src="https://user-images.githubusercontent.com/16019289/131531235-14c2426e-7830-4a4c-be9e-28dae8ba5bdf.png">

Is this the wanted behavior, or disabling B2B should hide those fields ?

Thanks!

**Comment by go-sudo** [comment]
Hello
Yes but I'm managing 10 websites so to gain time is there any action more faster and easier then removing those fields manually 

Regards

**Comment by Hlavtox** [comment]
@go-sudo @florine2623 That's perfectly normal behavior. :-) Even without B2B mode, in 99 % of cases you need the company and VAT fields. If ordering stuff for a company, you need these fields to be on a invoice.

So if you really want to remove it... in order to update it quickly, run this SQL:
```
UPDATE ps_address_format SET 
format = 'firstname lastname\r\naddress1\r\naddress2\r\npostcode city\r\nCountry:name\r\nphone';
```

**Comment by MatShir** [comment]
@Hlavtox I couldn't have answered better, thanks :)
I will close the issue, @go-sudo do not hesitate to reopen it if the context of your problem changes.

**Comment by go-sudo** [comment]
Hello @Hlavtox  

 Thank you for the solution , but I'm not agree with you , if I choose to disable B2B it means that I do not Sell products to Companies Otherwise this B2B option worth nothing

Regards
