### ISSUE TITLE
Image slider module lang switch is NOK

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25840]
#### Describe the bug

Language switch in image slider module is not on a right position, due to bad extending of form.tpl.

#### Expected behavior

It should be the same as in other outputs.

**Screenshots**

![before](https://user-images.githubusercontent.com/6097524/132841512-f90a39b7-6c9e-4129-9491-04dd4e149fa2.JPG)

**PR to fix**
https://github.com/PrestaShop/ps_imageslider/pull/64

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by Hlavtox** [comment]
**After fixing**
![after](https://user-images.githubusercontent.com/6097524/132841747-7eb7f5d5-24ff-442a-a245-06a44101d587.JPG)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I reproduce the issue only with develop & 178x (ps_imageslider v3.1.0), see the attached screenshot below:

### 1.7.8.x:

![image](https://user-images.githubusercontent.com/23308427/133065761-5d3c42e1-a61b-4af2-b468-6acf46af64a3.png)

### develop:

![image](https://user-images.githubusercontent.com/23308427/133066603-6ec21983-c447-4c78-b144-1f299d7f785b.png)

And it's a regression! Thanks for your PR :rocket: 
I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by Progi1984** [comment]
Needs a module release

**Comment by Progi1984** [comment]
Release in progress :)

**Comment by Progi1984** [comment]
Fixed in #28347
