### ISSUE TITLE
Ps_banner module fixed width and height value

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25852]
#### Describe the bug

In prestashop 1.7.8 with recent changes to fix CLS, fixed values for width and heigh has been added to template. That causing problem when someone is adding images with different ratio than has been assumed.

#### Expected behavior

Product listing - [this lines](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0-build/themes/classic/modules/ps_banner/ps_banner.tpl), width/height the values should be retrieved from getimagesize function.

#### Steps to Reproduce

1. In BO go to Modules->Module Manager and find module `ps_banner`.
2. Replace banner images with this [image](https://via.placeholder.com/1510x500)
3. Go to FO and homepage, inspect banner image with dev tools. Img tag values will be `width="1110" height="213"` even if image width and height are different. 

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by Oksydan** [comment]
https://github.com/PrestaShop/ps_banner/pull/37 it is first part to solve this issue.
Another PR will require to fetch that data in theme template that overrides module template.

**Comment by hibatallahAouadni** [comment]
Hello @Oksydan 

Thanks for reporting the issue!
I reproduce the issue with PS178x and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/133082914-f7942d36-249a-404b-bc6e-98babc66f982.png)

And it's a regression! Thanks for your PR :rocket: 
I’ll add this to the debug backlog so that it’s fixed.

Thank you
