### ISSUE TITLE
Hook actionCategoryUpdate is fired twice when toggling category display status

### ISSUE THREAD

**Issue by yo7hli** [PrestaShop/PrestaShop#25870]
#### Describe the bug

When you toggle a category display status in BO, the hook actionCategoryUpdate is invoked twice

#### Expected behavior

the hook should only be invoked once.

#### Steps to Reproduce

1. Register the actionCategoryUpdate hook in a module (optional)
2. Go to Catalog/Categories
3. Click on any category's display status (e.g. enabling or disabling its display state)
4. hookActionCategoryUpdate is invoked twice

#### Additional information
the hook is invoked once in Category->update() method and again in Category->toggleStatus(), this last one is redundant IMO.

* PrestaShop version: 1.7.8-beta1
* PHP version: 7.4.21

**Comment by florine2623** [comment]
Hello @yo7hli ,

Could you send a test module so that we can reproduce the issue ?

Thanks!

**Comment by yo7hli** [comment]
sure, i drafted a quick proof of concept module which dumps a stack trace into a file for each call
just clone the repo here https://github.com/yo7hli/test25780.git into the modules folder, make sure it's writable by the web server, install the module and follow the steps in the issue.
there should be a 'hook_debug.txt' file in the module folder with the stack trace dump

**Comment by khouloudbelguith** [comment]
Hi @yo7hli,

I used this module https://github.com/PrestaShop/ps_qualityassurance/ with PS1778 and 178x branch (version 1780).
I added the `actionCategoryUpdate` hook
![image](https://user-images.githubusercontent.com/16067358/133819564-ed26950a-2586-40e0-bd74-730f9f1dde9c.png)

I tried to change the status of a category => only one line was added.
I attached a screen record
https://www.awesomescreenshot.com/video/5272978?key=3b5076c29e94ee902d62db325e1a1f0a

Thanks to check and feedback.

**Comment by yo7hli** [comment]
thanks for looking into it, i'll have a look at that module too, figure out what's happening

**Comment by yo7hli** [comment]
@khouloudbelguith 
you need to append to the file otherwise it just rewrites it.
so using `file_put_contents('/tmp/test', 'works', FILE_APPEND);` , `works` is added twice.
also, it logs the hook call twice in db table `ps_quality_assurance_hook_logs`

**Comment by yo7hli** [comment]
> Hi @yo7hli,
> 
> I used this module https://github.com/PrestaShop/ps_qualityassurance/ with PS1778 and 178x branch (version 1780).
> I added the `actionCategoryUpdate` hook
> ![image](https://user-images.githubusercontent.com/16067358/133819564-ed26950a-2586-40e0-bd74-730f9f1dde9c.png)
> 
> I tried to change the status of a category => only one line was added.
> I attached a screen record
> https://www.awesomescreenshot.com/video/5272978?key=3b5076c29e94ee902d62db325e1a1f0a
> 
> Thanks to check and feedback.

**Comment by khouloudbelguith** [comment]
Hi @yo7hli,

Thanks for these clarifications.
I manage to reproduce the issue with PS1763 and PS1780rc.
![image](https://user-images.githubusercontent.com/16067358/134667052-d14f76e4-6b6c-4c97-b608-de3da56061c1.png)

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by PierreRambaud** [comment]
For me, it's not a bug, regarding the code, when you call the toggleStatus function from the object model, it triggers an update, so the hook is logical. :thinking: 
![image](https://user-images.githubusercontent.com/1462701/134857659-08ab994a-79c8-437f-ad3f-918abf8deec3.png)
