### ISSUE TITLE
Mail alerts availability notification subscription not working in a quick view window

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#25886]
#### Describe the bug

Mail alerts availability notification subscription not working in a quick view window

#### Expected behavior

Subscription should work correctly

#### Steps to Reproduce

1. Have a shop with one product or one of it's combinations out of stock
2. Open a quick view for this product from home page or category listing
3. Try to subscribe to availability notification in the form
4. Notice that the subscription request is not sent

#### Additional information

* PrestaShop version: 1.7.7.7
* ps_emailalerts v 2.3.0
* PHP version: N/A

This bug happens because the ps_emailalerts module only adds it's JS nad CSS files for product and account controllers, while they are also needed in other areas, if the store uses quick view.

**Comment by florine2623** [comment]
Hello @daresh ,

I was able to reproduce the issue with PrestaShop version 1.7.7.7, so I can confirm that this behavior is indeed a bug.

This email should be sent from the Quick View popin, but is only sent from the product page :
<img width="675" alt="Screenshot 2021-09-15 at 14 41 58" src="https://user-images.githubusercontent.com/16019289/133435176-2cbd25a0-1ef9-46a3-ab8d-89feed97cec1.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment]
Fixed in PrestaShop/ps_emailalerts#93 by @daresh
