### ISSUE TITLE
BACK OFFICE / Advanced Parameters / Import /Products   the Image alt and Title texts of the picture will be replaced by the language imported later. 

### ISSUE THREAD

**Issue by sampuchina** [PrestaShop/PrestaShop#25881]
After building a multilingual website, when importing products in batches.
via BACK OFFICE / Advanced Parameters / Import /Products

When importing Chinese language products first, and then importing English products, the Image alt and Title texts of the picture will be replaced by the language imported later. This is a small bug. It needs to be fixed.

**Comment by florine2623** [comment]
Hello @sampuchina ,

Please edit your issue and follow the report template so that we can reproduce your issue and fix this bug.
<img width="574" alt="Screenshot 2021-09-15 at 10 18 15" src="https://user-images.githubusercontent.com/16019289/133396944-aac6694a-c8aa-4d30-9cca-babee1631d72.png">
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @sampuchina 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
