### ISSUE TITLE
BO - Product V2 - An exception is displayed when creating a product with invalid name or too long name

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25905]
#### Describe the bug
In the BO > Catalog > Products > when we try to add a product V2 with an invalid name or too long name => an exception displayed
![image](https://user-images.githubusercontent.com/16067358/133591700-0694b987-f530-4f2a-810a-b3ac1db0a458.png)

#### Solution
![Capture d’écran 2022-01-27 à 12 29 24](https://user-images.githubusercontent.com/43613217/151350421-5436adce-f85b-499d-a348-9fa6a324c072.png)

Wording alert: 'This field contains invalid characters (<>;=#{})'

#### Steps to Reproduce

1. Go to BO > International > Taxes page > enable ecotax
2. Go to BO > Advanced Parameters > Experimental Features page
3. Enable Experimental product page
4. Go to BO > Catalog > Products page and add a product V2
5. Set the name with an invalid expression for example `<<<` or an expression too long and save
6. See error

#### Additional information

* PrestaShop version: 1.7.8.0rc1build4, develop
* PHP version: 7.2

**Comment by jolelievre** [comment]
I don't think raisin an error is really a bug however we should improve two things:
- provide an appropriate translated message to replace this technical message
- add a constraint in the form so that such values are not accepted on submit and thus we will have an inline error in the header

**Comment by MatShir** [comment]
@PierreRambaud @jolelievre I think, we should allow all characters !  WDYT?

**Comment by jolelievre** [comment]
As discussed with @PierreRambaud allowing more characters would be an interesting feature but it's a new feature that requires more work and more thought Not sure we should add it to the already big scope of v8

So the purpose of this issue is actually just to improve the error message display, we need to add a constraint on the name field so that a Symfony form inline error is displayed Not a validation exception thrown during command execution

**Comment by MatShir** [comment]
The forbidden characters are `<>;=#{}`. @Julievrz we can find a more accurate error message ? WDYT?

**Comment by jolelievre** [comment]
I don't think we need to, we already have dedicated constraints for this kind of use cases which have their own wording already existing

**Comment by Julievrz** [comment]
"This value is not valid" is not really helping the user here. 👀 We should clearly inform the user about invalid characters. Otherwise, the user could try multiple characters before he/she finally manages to save.

For example: 'This field contains invalid characters (<>;=#{})'

An even better solution would be to anticipate the error by displaying invalid characters in a help text under the field.
