### ISSUE TITLE
[BO] Dashboard time-val selection doesn't change the calendar

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#25966]
Hi there,

Selecting a time-val (day, month, year,...) from the calendar form, doesn't change the date-picker and causes a jquery error.

1. Go to BO > Dashboard
2. Select a time-val from calendar form 

![image](https://user-images.githubusercontent.com/16067358/134660440-d56525a3-046c-4482-b0fe-bf1136db61a2.png)

3. See error in browser console

**Screenshots**

![Screenshot 2021-09-22 at 12-11-40 پیشخوان • ONE](https://user-images.githubusercontent.com/85633460/134363529-135caafa-1c80-4e75-8f4b-691c1d418335.png)

![Screenshot 2021-09-22 121231](https://user-images.githubusercontent.com/85633460/134363968-a3ff450f-f4cc-43c0-b493-141866607ce4.png)

#### Additional information

* PrestaShop version: 1.7.8.0 (RTL)
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

I didn't manage to reproduce your issue with PS1780_rc1 (with Persian), see the attached screen record below:

https://watch.screencastify.com/v/qsWc13jHy0dxGpfugRCg

Please check and feedback.
Thanks!

**Comment by mparvazi** [comment]
Hello @hibatallahAouadni 

I meant selecting the time-val buttons at the right side, causes a jquery error and doesn't make any changes to the calendar at the left side.

**Screenshots**

![Screenshot 2021-09-22 at 12-11-40 پیشخوان • ONE](https://user-images.githubusercontent.com/85633460/134391567-0e4cc2d1-8bfe-4afb-8465-fda2eba449e3.png)

Please check again.
Ty!

**Comment by mparvazi** [comment]
admin/themes/default/js/calendar.js

![Screenshot 2021-09-24 115607](https://user-images.githubusercontent.com/85633460/134643472-fcf67d40-d5ce-4bed-a488-37081398207a.png)

Deleting the **const** keyword will fix the problem.

**Comment by khouloudbelguith** [comment]
Hi @mparvazi,

I manage to reproduce the issue with PS1780rc1. 
![image](https://user-images.githubusercontent.com/16067358/134659906-c88c023f-671f-4f19-aa7b-89401f77ed71.png)

It was ok with PS1778 & PS1777.
If we click on any button => the calendar will be changed 
![image](https://user-images.githubusercontent.com/16067358/134659662-70ef5309-d9bf-4d3c-9f85-ac6da7c7eb78.png)

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by Fred64640** [comment]
Hello, I have the modified calendar.js file which works because I had the same bug as you. If you are interested I can send it to you.
Fred

**Comment by mparvazi** [comment]
Hi @Fred64640 
Please join us on #26145

**Comment by deadlyengineer** [comment]
> Hello, I have the modified calendar.js file which works because I had the same bug as you. If you are interested I can send it to you. Fred

Hi @Fred64640
can you send it to me?

**Comment by Progi1984** [comment]
Fixed by @mparvazi in #26145
