### ISSUE TITLE
Configuration::updateValue truncates the value after '<=' in the value

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#25967]
#### Describe the bug

Configuration::updateValue truncates values if it finds `<=` in the value.

```php
Configuration::updateValue('TESTCONFIG', 'asdf <= qwer');
```

Saves into db as
```mysql
mysql> select name, value from ps_configuration where name="TESTCONFIG";
+------------+-------+
| name       | value |
+------------+-------+
| TESTCONFIG | asdf  |
+------------+-------+
1 row in set (0.00 sec)
```

```php
Configuration::updateValue('TESTCONFIG', 'asdf < = qwer');
```

saves correctly

#### Expected behavior

`Configuration::updateValue` should save the value as is

#### Steps to Reproduce

```php
Configuration::updateValue('TESTCONFIG', 'asdf <= qwer');
```

check the db for the value

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.30

**Comment by tswfi** [comment]
And no, using html=true (the third parameter) is not the solution

```php
Configuration::updateValue('TESTCONFIG', 'asdf <= qwer', true);
```

That will save as 
```mysql
mysql> select name, value from ps_configuration where name="TESTCONFIG";
+------------+-----------------+
| name       | value           |
+------------+-----------------+
| TESTCONFIG | asdf &lt;= qwer |
+------------+-----------------+
1 row in set (0.00 sec)

```

This will make it really hard to use the value as a configuration for external services (In my use case the external service allows giving select rules for a query)

**Comment by tswfi** [comment]
its pSQL that does this

```php
pSQL('asdf<=qwer');
```
returns `asdf`

**Comment by tswfi** [comment]
so pSQL has htmlOK which works correctly https://github.com/PrestaShop/PrestaShop/blob/8f75bff32899fb89e707d78886fa0072a4264022/config/alias.php#L45

```php
pSQL('asdf<=qwer', true)
```
returns `asdf<=qwer` correctly

but updateValue is more of a "ishtml" 
https://github.com/PrestaShop/PrestaShop/blob/8f75bff32899fb89e707d78886fa0072a4264022/classes/Configuration.php#L433

and thus does purification and other unwanted things to the value.

```php
Tools::purifyHTML('asdf<=qwer', true)
```

returns `asdf&lt;=qwer`

and as updateValues calls the purify when html is true it will mess up the string.

Suggestion: updateValue should always set html parameter true for pSQL even if it didn't do any extra html processing.

**Comment by hibatallahAouadni** [comment]
Hello @tswfi 

I think even when you try to save 'asdf<qwer' without =, you will get the same issue :confused: 
But when you try with 'asdf>qwer', it will be saved succefully. And that's remind me of this issue #22540
Wdyt, is it related?
Please check and feedback.

Thanks!

**Comment by tswfi** [comment]
tested and `<` and `>` work correctly.

but yes, that issue is probably something similar.

**Comment by khouloudbelguith** [comment]
Hi @tswfi,

I manage to reproduce the issue with PS1763 and PS1780rc
We can reproduce the issue with some fields
for example 

- Go to BO > Orders > Invoices page > In the invoices option
- Set `Invoice prefix ` & `Legal free text` & `Footer text ` with this expression `asdf <= qwer` and save
- See error => only the expression `asdf ` is saved


https://drive.google.com/file/d/1x1VFEPpr3qaJ1JTXgS1PUVLRkXJlfudV/view?usp=sharing
I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by tswfi** [comment]
As commented in the PR changing the existing configuration class is not worth the risk of breaking stuff.

The new configuration service (https://devdocs.prestashop.com/1.7/development/components/configuration/) hopefully does not have this issue (didn't test yet).

I'm self closing this issue.
