### ISSUE TITLE
Allow ean14 for ean13 field

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#25974]
#### Describe the bug

Currently, ean13 is restricted to 13 characters. Europe uses ean14 quite a lot https://www.gtin.info/ which cannot be saved into 13 characters. 

#### Expected behavior

- Allow to save 14 characters 
- rename label: '`EAN-13 or JAN barcode`'  ->` GTIN (EAN, JA, ITF or UCC code)`

It is 13 or 14 next to EAN are purposely removed to be more generic. EAN 13 is a legacy code that could be still use.

Replace the tool tips text by:
`The GTIN describes a family of GS1 (EAN.UCC) global data structures that employ to 14 digits and can be encoded into various types of data carriers. This type of product code is specific to Europe and Japan, but is widely used internationally. It is a superset of the UPC code: all products marked with an EAN will be accepted in North America.`

#### Acceptance test

1. Go to on a product page in bo'
2. Click on 'options'
3. Try to insert ean14 code into ean or jan field '12345678901234'
4. Save
5. Success

#### Suggestion:

Validation here:   
https://github.com/PrestaShop/PrestaShop/blob/2c059b93062ce25bbde22355982e651215544e81/src/Core/Domain/Product/ValueObject/Ean13.php#L41

Change 13 to 14

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @tswfi 

It seems an improvement cause in PS there's only ean13 :wink: so that's normal to throw an error while saving ean with 14 char.
So, thanks for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you
