### ISSUE TITLE
skip folders when importing translation

### ISSUE THREAD

**Issue by kiang** [PrestaShop/PrestaShop#260]
When trying to make a language pack manually, the import feature would report errors as there are folders inside it. Could you please add the line after 'skip folders inside the archive' ?

prestashop/controllers/admin/AdminTranslationsController.php

``` php
                    foreach ($files_list as $file2check)
                    {
                        // skip folders inside the archive
                        if(is_dir($sandbox.$file2check['filename'])) continue;
                        //don't validate index.php, will be overwrite when extract in translation directory
                        if (pathinfo($file2check['filename'], PATHINFO_BASENAME) == 'index.php')
                            continue;

                        if (preg_match('@^[0-9a-z-_/\\\\]+\.php$@i', $file2check['filename']))
                        {
                            if (!AdminTranslationsController::checkTranslationFile(file_get_contents($sandbox.$file2check['filename'])))
                                $this->errors[] = sprintf(Tools::displayError('Validation failed for: %s'), $file2check['filename']);
                        }
                        elseif (!preg_match('@^[0-9a-z-_/\\\\]+\.(html|tpl|txt)$@i', $file2check['filename']))
                            $this->errors[] = sprintf(Tools::displayError('Unidentified file found: %s'), $file2check['filename']);
                    }
```

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards

**Comment by prakhar-ap** [comment]
Hi,
I am currently working on some logic where i need to fetch the data from javascript to Prestashop code.
I used `$_COOKIE['search']` to extract a cookie from the browser because `Context::getContext()->cookie` is not able to fetch the required cookie.

While validating, 
It shows me an error of 

`The use of $_COOKIE is forbidden; use Context::getContext()->cookie instead
`
Can you please suggest me how i can skip this check?

Prestashop version `1.7.6.7`
PHP version `7.4`
