### ISSUE TITLE
Hide expert mode by default when minor chanel selected

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26003]
#### Describe the bug

By default the exepert mode is only hide when the major chanel is seletected. The metchant don't see / undestand the bloc is for expert .

#### Expected behavior

Hide also when the minor chandel is slected .

#### Steps to Reproduce

1. Go to 'Auto upgrade module'
2. Select  'Minor Chanel'
3. Refresh the page
4. See the expert mode is open
5. Do the the with major the block is hidden.

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

I was able to reproduce the issue with PrestaShop version 1.7.8.0_rc1, PS1778, PS1767 and with **1-Click Upgrade** v4.12.0, v4.11.0 and v4.10.0:

![image](https://user-images.githubusercontent.com/23308427/134893174-0afdb17c-a716-487b-b778-5f883681f1f5.png)

IMHO, it will be better if when we select the Major option, the bloc Expert Mode doesn't hide. 
Let's see with the Product Team :wink:  I’ll add this to the debug backlog so that it’s fixed.
Ping @PrestaShop/product-team wdyt?

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by ghost** [comment]
Thank you @hibatallahAouadni i wait the answer from PM before my PR

**Comment by marionf** [comment]
Hello @okom3pom 

On my side the behavior is different:
The channel "minor release" is selected by default and the "expert mode" is open and I can close it by clicking on "less options".
If I select the channel "major release", the "expert mode" stays open and I can close it by clicking on "less options".

As we plan to display [the table of compatibility between PS version and PHP versions](https://github.com/PrestaShop/PrestaShop/issues/25659) in the "Expert mode" block, I suggest not change this part and keep it as it is currently.

Furthermore, the module will be redesigned for the next version so let's not waste time with this ;)

**Comment by ghost** [comment]
Thank you @marionf i see you Thursday, For me the expert mod is not open when using the chanel major.

I close this issue.
