### ISSUE TITLE
ps_facetedsearch module bug: Search with "Not available" options, but there are still available products in the results.

### ISSUE THREAD

**Issue by tiedh** [PrestaShop/PrestaShop#26016]
Refer: #26013 
The bug report closed. Because my steps to reproduce not clear.

Describe the bug
I found this problem after I try to search to find out of stock products using ps_facetedsearch module.
The product found that the problem is a Product with combinations. I think the module only searches only with quantity of Simple product.

Expected behavior
I think the module should able to find "Simple products" and "Product with combinations" whose sum of combinations is really zero. not mixed with combinations is available.

1. Create product by Standard product and select Product with combinations.
2. Go to Categories page on the frontend
3. Click on the search filter as "Not available"
4. See the result.

Screenshots
Create product by Standard product and select Product with combinations.
![Screen Shot 2564-09-28 at 15 47 58](https://user-images.githubusercontent.com/91517381/135058100-ca0afcc4-2dbb-4ad5-ad10-e00c890c4f18.png)

![Screen Shot 2564-09-28 at 16 09 33](https://user-images.githubusercontent.com/91517381/135058750-ced968e5-9df6-4880-acfd-da5daae5ead9.png)

The product in red border has 2 combination items, Some of them is out of stock and other one is available.
![Screen Shot 2564-09-28 at 13 58 55](https://user-images.githubusercontent.com/91517381/135063633-8f0f68b5-cc16-4776-8479-9e8ef510cfcc.png)

Additional information
PrestaShop version: 1.7.7.8
PHP version: 7.3.3
ps_facetedsearch version: v3.7.1

**Comment by florine2623** [comment]
Hello @tiedh ,

Thanks for the details.
The product is displayed because one combination is out-of stock, but there is stock for other combination.
It shows the red combination because it is the Default Combination.

That's how it is supposed to work.

**Comment by DATA-HORIZON** [comment]
Hello @florine2623 ,

the problem here is, that also our own clients see this "feature" buggy. We have several shop owners, that constantly complain about this behavior.

To give you a good example, what is meant:

-> create a product that has combinations, e.g. a Jeans with sizes S, SM, M, L, XL, XXL, XXXL [...]
-> give all combinations a stock value > 0 except one, that is out of stock (e.g. size M = 0)

Now the following will haben:

-> the new jeans is displayed for both filters: 
"In stock" (1)
"Not available" (1)
-> when you activate both filters, only 1 product is shown, so also the calculation is not really understandable for the people

But the even more worse thing is: if people activate the "Not available" filter or they come from external traffic sources to that page including the filter "Not available" they will think: "oh, this jeans is not available at all, so sad". They will not click on the product. So even all sizes except one are available to buy for that jeans, people will think: not available at all. We even get customer calls asking, when it is available again. This is quite annoying to explain to them: please ignore the filter, just go to the final product page and check your size.

So a patch could have the following behavior:
-> a product should only be listed for "Not available", if all stock values of all combinations as sum are 0, if at least one combination can still be bought, show the product as "In stock" only.

Thanks in advance for a quick fix! Our shop owners will love it because it will reduce the support requests in their online shops and some will activate the filter/feature again as this is a blocker for them.

**Comment by khouloudbelguith** [comment]
Hi @schattenfell,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #16952
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #16952
