### ISSUE TITLE
Bad display when multishop enable Blockreassurance

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26025]
#### Describe the bug

Bad display when multishop enable on Blockreassurance module

#### Expected behavior

Good display

#### Steps to Reproduce

1. Enabble Multishop
2. Go to Blockreassurance module

**Screenshots**

![Capture d’écran de 2021-09-29 10-30-56](https://user-images.githubusercontent.com/5064590/135232845-bcf1ec6f-cc63-4dff-869b-61f725971d77.png)

![Capture d’écran de 2021-09-29 10-31-11](https://user-images.githubusercontent.com/5064590/135232830-162e17e0-2f2a-4e05-8b76-c83e71c02dcf.png)

#### Additional information

* PrestaShop version: 177 178 dev
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Could you please provide the blockreassurance version 🙏 

Thanks in advance!

**Comment by ghost** [comment]
v5.0.0  or Dev ( 5.1.0 )

**Comment by ghost** [comment]
Hello @hibatallahAouadni 

https://okom3pom.com/videos/PrestaShop-blockreassurance.webm

Regards

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

I manage to reproduce the issue with 
PS1778 + blockreassurance v5.0.0
PS1780rc1 + blockreassurance v5.0.0
PS1769 + blockreassurance v 4.1.1
![image](https://user-images.githubusercontent.com/16067358/135589202-676c3c94-c1c4-4130-a224-76a086f34cd2.png)

It is ok with PS1769 + blockreassurancev3.0.1
![image](https://user-images.githubusercontent.com/16067358/135589271-3014013e-9b52-4219-8f55-6dc8e4107402.png)

I'll add this to the debug backlog so that it's fixed.

Thanks!

**Comment by Progi1984** [comment]
Fixed by @okom3pom in PrestaShop/blockreassurance#277
