### ISSUE TITLE
Cannot change the settings in the Performance section for the context of single-store

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#26058]
#### Describe the bug

We are not able to change settings in Adv. Preferences -> Performance for the single store. That means that we cannot set, for example, different media servers. Page was working completely fine on the 1.7.7 version.

For people using CDN servers or additional cache, it's a no-go for 1.7.8.0.

IMO there's no reason to block it, ok, we don't have checkboxes, but the page should be fully functional anyway.

#### Expected behavior

We should be able to change these settings in the context of a single store.

#### Steps to Reproduce

1. Set up multi-store
2. Go to Performance settings
3. See that you can only set the settings for the "All shops" context

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

I was able to reproduce the issue with PrestaShop version 1.7.8.0. I’ll add this to the debug backlog so that it’s fixed.
And it's a regression cause with 1.7.7.8, the list of shops are all displayed:

![image](https://user-images.githubusercontent.com/23308427/135838909-c3fbeebc-f443-4b0b-a0a2-00936630a4e0.png)

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment]
Fixed by @kpodemski in #26089
