### ISSUE TITLE
v4.0.0 not compatible with PS 1.7.7.0 : "cancel product" fails with error message

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#26098]
As found by @SD1982,
- when ps_googleanalytics v4.0.0 is used with PS 1.7.7.0 with new migrated Order page
- if merchandise return is enabled, which allows to cancel products
- if you perform "cancel product" action on an order you get this error message

<img src="https://user-images.githubusercontent.com/40635814/99063464-d991b000-25a4-11eb-8612-eb023a263b49.png">

When this message is being explored, what happens is that this code is not working: https://github.com/PrestaShop/ps_googleanalytics/blob/dev/classes/Hook/HookActionProductCancel.php#L45
```
    public function run()
    {
        $quantityRefunded = Tools::getValue('cancelQuantity');
        $gaScripts = '';

        foreach ($quantityRefunded as $orderDetailId => $quantity) {
            // Display GA refund product
            $orderDetail = new OrderDetail($orderDetailId);
            $gaScripts .= 'MBG.add(' . json_encode(
                [
                    'id' => empty($orderDetail->product_attribute_id) ? $orderDetail->product_id : $orderDetail->product_id . '-' . $orderDetail->product_attribute_id,
                    'quantity' => $quantity,
                ])
                . ');';
        }
```
This is because parameter `cancelQuantity` has changed between 1.7.6 Order page and 1.7.7 order page. So we get a `Warning: Invalid argument supplied for foreach()` error.

**Comment by hibatallahAouadni** [comment]
Hello @matks & @Hlavtox 

Thanks for reporting the issue!
I still manage to reproduce the issue with PS1778 and GoogleAnalytics v4.1.0, see the attached screen record below:

https://watch.screencastify.com/v/30pt9bFIEoaTwwuiVr4J

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by khouloudbelguith** [comment]
Hi @matks,

I have the same exception following these steps:

1. Go to BO > Customer Service > Merchandise Returns page and enable returns
2. Go to BO > Orders > View an order with payment accepted status
3. Click on Standard refund or Partial refund
4. Select the quantity & complete the action
5. See error => an exception: we cannot do a refund
6. Go to BO > Orders > View an order with shipped status
7. Click on Return a product
8. See exception: we cannot return a product 

![image](https://user-images.githubusercontent.com/16067358/159526186-d9bf3032-17a7-431a-bd07-5942198d9946.png)

I think we need to change the severity of the issue from minor to major.

What do you think?

Thanks!

**Comment by matks** [comment]
@khouloudbelguith Agreed !
