### ISSUE TITLE
Developer documentation not complete enough

### ISSUE THREAD

**Issue by chattago2002** [PrestaShop/PrestaShop#26142]
Hi everyone.

I'm reading the devdocs for 1.7 at https://devdocs.prestashop.com/1.7/ but I can't find the entire documentation to develop a module. I'd like to know all methods (and relatives parameters) for PS objects as Product, Tag, Order, etc...

Example
`Product::getProducts(Context::getContext()->language->id, 0, 200, 'position', 'ASC', $id_category, true);`

How can I know all parameters for getProducts method?
And how can I know all Product methods?

Thanks

**Comment by matks** [comment]
Hello all the documentation we have is https://devdocs.prestashop.com/1.7/

You can find all methods and relative parameters for PS objects by opening the code I guess.

If you think the PS documentation can be improved, dont hesitate to help us -> see https://devdocs.prestashop.com/1.7/contribute/documentation/

I close this issue because we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop, you can get help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
