### ISSUE TITLE
Social media follow links

### ISSUE THREAD

**Issue by antonchik777** [PrestaShop/PrestaShop#26152]
#### Describe the bug

Social media follow links went down as in the screenshot after updating from 1.7.7.7 to 1.7.8.0(Classic theme)
Excuse me if this is a new feature.

#### Expected behavior

Previously, they were on par with the email subscription block(Classic theme)

#### Steps to Reproduce

1. Update prestashop to version 1.7.8.0
2. Scroll down to 'Footer'
3. See error

**Screenshots**

![888](https://user-images.githubusercontent.com/35896021/136514737-dc790930-69df-4e48-a998-8e9114fe0e96.jpg)

#### Additional information

The location of the module in the "Design-Positions" tab has not changed and is located in displayFooterBefore

* PrestaShop version: 1.7.8.0
* PHP version: 7.2/7.4

**Comment by khouloudbelguith** [comment]
Hi @antonchik777,

I manage to reproduce the issue with PS1780after an upgrade from PS1777.
`Before upgrade`
**FO**
![image](https://user-images.githubusercontent.com/16067358/136548604-fd22e12f-ba0c-4ae6-83dd-14ed17fdf30f.png)
**BO**
![image](https://user-images.githubusercontent.com/16067358/136548688-b078c920-1376-465b-8960-701ef463ea7e.png)
`After the upgrade`
**FO**
![image](https://user-images.githubusercontent.com/16067358/136549369-fdf83abf-5fc1-48eb-9227-76053b888cad.png)

**BO**
![image](https://user-images.githubusercontent.com/16067358/136549180-5ae9c827-40e5-40b1-86b9-38aafd15645c.png)

I tried these steps:

- Install PS1769
- Configure the module social follow in different language > check-in FO
- Upgrade to PS1778
- Disable maintenance mode 
- In the FO > OK

 https://www.awesomescreenshot.com/video/5556733?key=59b77216b7630906d6b085190558209e


I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by khouloudbelguith** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/20748

**Comment by antonchik777** [comment]
Hello, could you please clarify whether there is news on this problem, is there already some kind of fix?
Thank you
Regards

**Comment by AlexTechDev** [comment]
Hi,
I can't reproduce the issue in PrestaShop 8
![image](https://user-images.githubusercontent.com/100702024/187081985-39e9db12-f3da-4d52-bae2-33f5358c4245.png)

**Comment by gericfo** [comment]
@AureRita Can you try to reproduce it with a 1.7.8.11? Thanks

**Comment by antonchik777** [comment]
Hello, yes, this problem is still in the version [1.7.8.11](https://www.parfumla.com/)

**Comment by BenTen** [comment]
And in PS 8.1.7 with Classic theme 2.1.3 is still too.

**Comment by gericfo** [comment]
After a few checks, it's not a bug but an evolution of the theme. So I'm closing the ticket. Thanks a lot!
