### ISSUE TITLE
PS 1.7.8.1 Search Bar

### ISSUE THREAD

**Issue by TGD001** [PrestaShop/PrestaShop#26179]
Installed new release, we upgraded  search  module to 2.1.1 but strangely bar appares as per picture enclosed. 
We dont know if is a bug or we have to set it. We have been forced to delete new release and reload old one from backup.
Thank you for attention
Piero Terracina
![barra](https://user-images.githubusercontent.com/41903971/136686017-3ca09793-8738-43fa-a061-983bb52cb65c.JPG)

**Comment by hibatallahAouadni** [comment]
Hello @TGD001 

> Installed new release (PS 1.7.8.1)

Well, our latest release is 1.7.8.0 :wink: 
If you upgraded your shop to 1.7.8.0 and you encounter this issue with SearchBar module, so your issue is a duplicate of #25594. 
And the PR to fix the issue is https://github.com/PrestaShop/ps_searchbar/pull/38 but SearchBar 2.1.2 is not released yet.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #25594
