### ISSUE TITLE
Bug in edit carrier after add an invalid character

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26187]
#### Describe the bug

You can't continue the process to edit a carrier after add an invalid character

#### Expected behavior

Same as 1.7.7 you can continue to edit the carrier.

#### Steps to Reproduce

1. Go to 'Edit a Carrier'
2. On the name put `#` or `;`
3. Click to continue
4. Show the behavior:

**Screenshots**

![ScreenShot Tool -20211011083412](https://user-images.githubusercontent.com/5064590/136743371-68375760-2c08-44bb-83cf-9016be10b5d2.png)

#### Additional information

* PrestaShop 1.7.8.1 or dev
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

> Same as 1.7.7 you can continue to edit the carrier.

Well, it seems that even with PS1778, we have the same behavior:

![image](https://user-images.githubusercontent.com/23308427/136779541-b077950e-7e01-49d7-b74a-c66970e00910.png)

![image](https://user-images.githubusercontent.com/23308427/136779557-d89d2442-57df-4b70-8c4a-a87cdd0bf210.png)

Please check and feedback.
Thanks!

**Comment by ghost** [comment]
ho my bad the bug is only for the 1.7.8.1 ( dev ) 

I  update my issue

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for reporting the issue!
I reproduce the issue only with develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/136807620-146c6a61-de2f-4a02-94a8-dd05d25df6a6.png)

It's a **Regression**! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
