### ISSUE TITLE
Webservice Symfony Container not loaded

### ISSUE THREAD

**Issue by sfroment** [PrestaShop/PrestaShop#26199]
#### Describe the bug

Call a webservice, try to save any Entity that as some lang involved and you'll get ```You have requested a non-existent service "prestashop.translation.translator_language_loader".```

#### Expected behavior

Having all the Symfony deps loaded

#### Steps to Reproduce

1. Create a webservice
2. Create an entity involving translation
3. ->add() it
4. this will throws an error 

#### Additional information

* PrestaShop version: 1.7.X.X (all ps version involving symfony basically) 
* PHP version: 7

#### How to fix this
Load the AppKernel even when a webservice is called
```php
global $kernel;
if (null === $kernel) {
	$kernel = new AppKernel(_PS_ENV_, _PS_MODE_DEV_);
	$kernel->boot();
}
```

**Comment by matks** [comment]
> 1. Create a webservice
> 2. Create an entity involving translation
> 3. ->add() it
> 4. this will throws an error

What do you mean by "create a webservice" ?

**Comment by sfroment** [comment]
Create your own webservice like 
```php
class WebserviceSpecificManagementXXXX implements WebserviceSpecificManagementInterface
```
Then in your module 
```php
public function hookAddWebserviceResources()
{
	return [
		'XXXX' => [
			'description' => 'XXX',
			'specific_management' => true
		],
	];
}
```

**Comment by matks** [comment]
Does the error happen with regular entities that already exist in PrestaShop, like customer, product, country?

**Comment by sfroment** [comment]
Never tried but I believe it could be the case as this will go through the same dispatcher if you update an entity such as cart_rule, product
In my WS I use PS entity btw (so if you mean using a new Product() and then saving it you'll have the error)
I just extend the base WS api in order to get relations etc... through an API and not retrieving them by calling PS again and again

**Comment by sfroment** [comment]
You can just have the error by adding a $this->l at the construct of your module and then calling your WS
Since PS will try to resolve the "prestashop.translation.translator_language_loader" which won't be loaded

**Comment by matks** [comment]
I'll be honest 😆  : we have only little pieces of information about `specific_management` usage. The [documentation](https://devdocs.prestashop.com/1.7/webservice/) does not mention it and it does not mention either how one can create a webservice endpoint from a module (although that's definitely possible).

So we'll have a hard time reproducting your issue as we have never done this. And I'm not even sure we support this - as we have no idea how this is supposed to behave, how could we maintain it?

Note: if you are skilled in the topic of PS webservice, don't hesitate to [contribute to it](https://devdocs.prestashop.com/1.7/contribute/documentation/) 😊

**Comment by sfroment** [comment]
Why should this be supported ?
1. This was supported before (at least since 2013).
2. The knowledge on how to support it should be at prestashop since it's used inside some part of prestashop actually.
3. Since the hook is in the hooks list I suppose that it should be supported.
<img width="1144" alt="Screenshot 2021-10-11 at 18 44 53" src="https://user-images.githubusercontent.com/7238385/136825997-b5c4dd83-6214-4e27-a3ce-beee82e9ecc8.png">

Sadly I do not know Symfony well so I might do something bad, what I can do is give you some snippet on how to do one.
Nonetheless here's what I'll do if I should fix it on my own https://github.com/PrestaShop/PrestaShop/pull/26205/files it's not tested at the moment I'll give you some update tmrw

**Comment by matks** [comment]
In understand your point of view but unfortunately things are not as simple 😞  .

> Why should this be supported ?
> 
> 1. This was supported before (at least since 2013).

I currently have no documentation neither trace about it. If you have some, I'll be happy to read them. If not, then I'm afraid nothing has been left behind to help us take care of this `specific_management`and maintain it over time.

If I have no idea how something is supposed to work in PrestaShop, I cannot take care of it, keep it working, keep it secure, keep it performing and review pull requests that modify it if I don't even know how it works.

It sounds a little crazy 😆  but since I have nothing to rely on, I cannot even know if your bug report is valid or not. I cannot even know if what you are doing is supposed to be possible or not.

> 2. The knowledge on how to support it should be at prestashop since it's used inside some part of prestashop actually.

Unfortunately the [Webservice](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceRequest.php) part is a gigantic piece of code that is very hard to read or reverse-engineer. So even if the `specific_management` usage is inside the code, it does not mean we can extract from the code how it's supposed to work. Also there is no tests on the Webservice that would allow us to modify it without the fear of breaking it (there's a little beginning on https://github.com/PrestaShop/PrestaShop/pull/24162 but it's a first step only).

Once again, if you have this knowledge that I dont I'd be happy to review PRs from you that would add documentation and/or tests on the webservice to make it easier to maintain 😉  . Webservice is like a 'unknown area' for now because we lack documentation and tests so any work on it, bugfix, refactoring or new feature is a risky operation. I would be happy to welcome contribution that change this situation.

> 3. Since the hook is in the hooks list I suppose that it should be supported.

The hook is one thing, usage of `specific_management` is another.

**Comment by sfroment** [comment]
About the 1st point I was a Core Dev @prestashop at this time that's why I know we were supporting it, you can ask Thomas Nabord or Yousri or anybody that was there at this time.
About the hook I'm using it as a module dev is supposed to use it, this hook is there to allow the user to extend the basic WS api, so if you can't call anything that you hook cause of this bug what is the purpose of the hook ? 
So I'm not speaking only about specific_management but the hook part also which allow the user to make his own API. The whole translation part of the WS are bugged at the moment
If you want you can hit me up on the ps slack and I can show you some of my code so you can understand

**Comment by sfroment** [comment]
BTW the PR i've made #26205 fix the problem
I've send you a small demo module on slack so you can see what I'm talking about like that it should be easier for you to test

**Comment by Hellogark** [comment]
I'm having the same issue when trying to update a product, the documentation says that i need to do a get for the product, then modify the xml and then send the whole xml as i got it, but when i send it i get two errors, the first one is  `<![CDATA[parameter "manufacturer_name" not writable. Please remove this attribute of this XML]]>` and the second one is  `<![CDATA[parameter "quantity" not writable. Please remove this attribute of this XML]]>`, if i delete those parameters i get the same error 
`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "prestashop.translation.translator_language_loader". in ...\xampp\htdocs\prestsashop\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php:348 Stack trace: #0 ...\xampp\htdocs\prestsashop\classes\Context.php(448):`

**Comment by matkpc** [comment]
Hi,
I'm having the same issue on 1.7.8.  Everything was working fine.  The only thing that I can remember of is that I did change a value in a module.
`$this->displayName = $this->l('pc_creditcardpayment');`
to 
`$this->displayName = $this->l('Credit card payment'); `
I also deleted a line in en.php because the translation was the same value as the one coded and that was bugging me.
Then later I tried to run my webservice script and got the error 500.
_This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error._

Php error looks like the following
> PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "prestashop.translation.translator_language_loader". in C:\wamp64\www\testabo2021\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php:348
Stack trace:
#0 C:\wamp64\www\testabo2021\classes\Context.php(448): Symfony\Component\DependencyInjection\Container->get('prestashop.tran...')
#1 C:\wamp64\www\testabo2021\classes\Context.php(398): ContextCore->getTranslatorFromLocale('fr-FR')
#2 C:\wamp64\www\testabo2021\classes\module\Module.php(3437): ContextCore->getTranslator()
#3 C:\wamp64\www\testabo2021\classes\module\Module.php(3444): ModuleCore->getTranslator()
#4 C:\wamp64\www\testabo2021\modules\ps_mainmenu\ps_mainmenu.php(76): ModuleCore->trans('Main menu', Array, 'Modules.Mainmen...')
#5 [internal function]: Ps_MainMenu->__construct()
#6 C:\wamp64\www\testabo2021\src\Core\Foundation\IoC\Container.php(123): ReflectionClass->newInstance()
#7 C:\wamp64\www\testabo in C:\wamp64\www\testabo2021\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php on line 348

I deleted the module but that did not fixed the issue.

This is a dev project but I would like not to have to start a fresh one.

Anyone found a solution?

**Comment by sfroment** [comment]
@matkpc I've given a solution here https://github.com/PrestaShop/PrestaShop/pull/26205

**Comment by sfroment** [comment]
@matks  @matthieu-rolland could we get an update on this issue and the related PR thanks

**Comment by matkpc** [comment]
> 
> 
> @matkpc I've given a solution here #26205

@sfroment : Thanks!  I tried the solution directly in my php webservice script but it didn't work.  Putting it in webservice/dispatcher.php did it!
Thanks a million!

**Comment by sfroment** [comment]
@matks @matthieu-rolland bump for update on this issue plz

**Comment by gitbjorn** [comment]
Same issue here. PHP Version 7.3.32, Prestashop 1.7.8

Sending the following XML to the Webservice to create a new Supplier.

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<supplier>
	<id></id>
	<link_rewrite></link_rewrite>
	<name>SUPPLIER NAME (English)</name>
	<active>1</active>
	<date_add></date_add>
	<date_upd></date_upd>
	<description><language id="1">SUPPLIER NAME (English)</language></description>
	<meta_title><language id="1"></language></meta_title>
	<meta_description><language id="1"></language></meta_description>
	<meta_keywords><language id="1"></language></meta_keywords>
</supplier>
</prestashop>

```

This gives the following PHP error message:

```
[Sat Nov 13 17:24:44.560025 2021] [proxy_fcgi:error] [pid 2758892:tid 140487350040320] [client XX.XXX.XX.XXX:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException: You have requested a non-existent service "prestashop.translation.translator_language_loader". in /var/www/vhosts/my.domain.net/httpdocs/prestashop-1.7.7.8-staging/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:348\nStack trace:\n#0 /var/www/vhosts/my.domain.net/httpdocs/prestashop-1.7.7.8-staging/classes/Context.php(448): Symfony\\Component\\DependencyInjection\\Container->get('prestashop.tran...')\n#1 /var/www/vhosts/my.domain.net/httpdocs/prestashop-1.7.7.8-staging/classes/Context.php(398): ContextCore->getTranslatorFromLocale('nl-NL')\n#2 /var/www/vhosts/my.domain.net/httpdocs/prestashop-1.7.7.8-staging/classes/module/Module.php(3437): ContextCore->getTranslator()\n#3 /var/www/vhosts/my.domain.net/httpdocs/prestashop-1.7.7.8-staging/classes/module/Module.php(3444): ModuleCore->getTranslator()\n#4 /...'
```

The same XML works fine on a Prestashop 1.7.7.5 installation on the same server.

**Comment by jf-viguier** [comment]
@sfroment "Create a webservice" in the description should be "Call the web service".
Every change in a multilang entity (add, update) will raise the error, it's a main issue.
@matks can you check the pr ?

**Comment by sfroment** [comment]
good catch 👌 edited

**Comment by jf-viguier** [comment]
@khouloudbelguith has this same bug here in my pr :
https://github.com/PrestaShop/PrestaShop/pull/24403#issuecomment-950785940

**Comment by jf-viguier** [comment]
@sfroment I've included your pr here and it's merged, thanks https://github.com/PrestaShop/PrestaShop/pull/24403

**Comment by sfroment** [comment]
haha nice getting this merged !

**Comment by deibono** [comment]
Hello, 
Thanks for your patch, it works perfectly with debug mode enabled.
Can you explain me how to make it work in production mode? 
(i tried to modify this line : $kernel = new AppKernel(_PS_ENV_, false);
But it didn't work 

Thanks

**Comment by rsoulard-prolaser** [comment]
Hello,

This problem is quite critical and should be fixed on versions 1.7.8.x
What do you think @jf-viguier @matks ?

**Comment by jf-viguier** [comment]
@rsoulard-prolaser I agree but it's an old bug and not a regression to 1.7.8.x version, so it's up to Prestashop maintainers to decide.

**Comment by rsoulard-prolaser** [comment]
On this issue #27411, it was tested as a regression.

**Comment by jf-viguier** [comment]
A regression from1.7.6, not from 1.7.8.
This issue is a major one and should be fixed before this summer, but I'm not a maintainer, just a contributor.

**Comment by rsoulard-prolaser** [comment]
On this comment https://github.com/PrestaShop/PrestaShop/issues/27411#issuecomment-1018014025, it works on 1.7.7.8 but not in 1.7.8.0

**Comment by jf-viguier** [comment]
Thanks, @hibatallahAouadni it's a regression and should be fixed in next 1.7.8.x ?

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Thanks for your patience :pray: 
Closing this issue as a duplicate of this one #27411
To be informed when it's fixed, please subscribe to the issue mentioned above.

@jf-viguier waiting for your PR :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #27411

**Comment by matks** [comment]
Fixed by @jolelievre https://github.com/PrestaShop/PrestaShop/pull/27766
