### ISSUE TITLE
Enable/Disable maintenance with CLI

### ISSUE THREAD

**Issue by ytilotti** [PrestaShop/PrestaShop#26211]
#### Is your feature request related to a problem?

Need to active maintenance in CLI for automation

#### Describe the solution you'd like

Add a method to active maintenance with command for CLI

#### Alternatives you've considered

- Update manually in SQL query
- Update manually in BO

#### Additional context
n/a

**Comment by ytilotti** [comment]
I will create a PR for this feature, regards.

**Comment by florine2623** [comment]
Hello @ytilotti ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments.

Thank you

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

What do you think about this feature request ?

Thanks!

**Comment by tswfi** [comment]
I think this issue can be closed with #26183 as it will implement changing `PS_SHOP_ENABLE` `PS_MAINTENANCE_TEXT` and `PS_MAINTENANCE_IP` and all the other configuration values also

**Comment by ytilotti** [comment]
If #26183 is valid and merge, I agree.

**Comment by SebSept** [comment]
So a single clear command will be replaced by a complex command ?
Switching the shop to maintenance could be easy with a dedicated command.
It could be a complex command, error prone and confusing because of the parameters that need to be remembered and convey no meaning (has the lang paramater a meaning while switching to maintenance ?).

What about the developer experience ? 
This command can offers a great DX, using configuration command not at all.
Imho this task deserve a dedicated command.

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/26183 was merged
