### ISSUE TITLE
Respect "Display tax label" setting in ps_shoppingcart

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#26236]
#### Describe the bug

Original issue: https://github.com/PrestaShop/PrestaShop/issues/21484

This is for `ps_shoppingcart` part.

BO>Locations>Countries>Edit countries
Display tax label (e.g. "Tax incl.") > No
FO>product page>Add to the cart
The label tax incl is still shown in the attached screenshot:

![](https://user-images.githubusercontent.com/89604350/135472670-40da3f9a-2127-4e2f-b449-0f65be9d9c3a.png)

#### Expected behavior

"Tax incl" lavel is not shown

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2
* Module version: 2.0.4

pr that fixed this in core: https://github.com/PrestaShop/PrestaShop/pull/25882

**Comment by hibatallahAouadni** [comment]
Hello @tswfi 

I was able to reproduce the issue with PrestaShop version 1.7.8.0. I’ll add this to the debug backlog so that it’s fixed.

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by tswfi** [comment]
oh, actually the classic theme overrides the ps_shoppingcart templates that show the data: https://github.com/PrestaShop/PrestaShop/tree/develop/themes/classic/modules/ps_shoppingcart

so maybe this is actually a theme bug :D

**Comment by hibatallahAouadni** [comment]
@tswfi Thanks for your PR :rocket:

**Comment by marwachelly** [comment]
Hello, 
PR #26242 is tested on develop and the label (tax incl) is not present when "Display tax label" is disabled in the shopping cart as shown bellow
![image](https://user-images.githubusercontent.com/89604350/139034190-547586b1-bad4-4d13-8877-9573422206a0.png)
Many thanks,
