### ISSUE TITLE
Respect "Display tax label" setting in ps_checkpayment

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#26237]
#### Describe the bug

Original issue: https://github.com/PrestaShop/PrestaShop/issues/21484

This is for `ps_checkpayment` part.

BO>Locations>Countries>Edit countries
Display tax label (e.g. "Tax incl.") > No
FO>product page>Add to the cart
The label tax incl is still shown in the attached screenshot:

![](https://user-images.githubusercontent.com/89604350/135473112-baf92122-e19a-4a7b-b639-15b47b561255.png)

#### Expected behavior

"Tax incl" label is not shown

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2
* Module version: 2.0.5

pr that fixed this in core: https://github.com/PrestaShop/PrestaShop/pull/25882

**Comment by hibatallahAouadni** [comment]
Hello @tswfi 

I was able to reproduce the issue with PrestaShop version 1.7.8.0. I’ll add this to the debug backlog so that it’s fixed.

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by tegbessou** [comment]
I can't approve this PR. But I think this PR is ok!

**Comment by matks** [comment]
PR for module ps_checkpayment https://github.com/PrestaShop/ps_checkpayment/pull/51
