### ISSUE TITLE
Add `Breadcrumb Links` in `psgdpr` and `ps_emailalerts`

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#26261]
## Is your feature request related to a problem?

The names of the sections are missing in breadcrumb links. It would be interesting to have the names of the sections of these two modules in the  breadcrumb links.

![image](https://user-images.githubusercontent.com/16455155/137405490-5fa06c6b-afd5-411c-9338-02c2ae25d98b.png)

## Describe the solution you'd like

- psgdpr 
![image](https://user-images.githubusercontent.com/16455155/137405574-482eaf2d-8c38-4b26-ba2f-022fd31974e9.png)

- ps_emailalerts
![image](https://user-images.githubusercontent.com/16455155/137405627-f53d7c7d-4b3f-4aed-ba64-6a107341b314.png)

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

Thank you for your suggestion.
About the ps_emailalert module, is it similar to this issue https://github.com/PrestaShop/PrestaShop/issues/17480? which fixed with this PR: https://github.com/PrestaShop/ps_emailalerts/pull/43
> Edited after discussion with @PululuK 

Those issues are not similar.
The Product Team will take it into consideration for future developments, ping @PrestaShop/product-team 

Thank you!

**Comment by florine2623** [comment]
Hello @PrestaShop/product-team ,

Before testing the related PR https://github.com/PrestaShop/psgdpr/pull/145 for psgdpr, could I get a confirmation from you with label "PM ✔️"  and removal of "TBS" and "Waiting for PM" ?

Thanks!

**Comment by marionf** [comment]
@florine2623 done ✔️
