### ISSUE TITLE
Somes bad displays after update to 1.7.8

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26273]
#### Describe the bug

Some bad displays after upgrading to 1.7.8.0, witout update classic theme.

I test from 1.7.7.1 / 1.7.7.2 / 1.7.73 /  **1.7.7.8**

#### Expected behavior

Good displaying

#### Steps to Reproduce

Upgrade with this options and go to the FO

![Capture d’écran de 2021-10-16 09-54-37](https://user-images.githubusercontent.com/5064590/137580289-49e07dfe-f564-4bba-9ad1-de6ed571af22.png)

**Screenshots**

![Capture d’écran de 2021-10-16 09-58-04](https://user-images.githubusercontent.com/5064590/137580321-edb7d61a-5ace-4c48-a8c1-c69ddcb8bfad.png)
![Capture d’écran de 2021-10-16 10-03-20](https://user-images.githubusercontent.com/5064590/137580323-9168ddd3-cf2e-4da9-bfa2-92e2c417a2c0.png)

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @okom3pom ,

I updated from PS 1.7.7.8 to PS 1.7.8.0, I can't reproduce your issue.
Please check my screenshots :
<img width="1142" alt="Screenshot 2021-10-18 at 11 32 42" src="https://user-images.githubusercontent.com/16019289/137706280-c87c432a-fbdd-4b24-83b2-8debea299199.png">
<img width="1152" alt="Screenshot 2021-10-18 at 11 33 13" src="https://user-images.githubusercontent.com/16019289/137706291-cb89bf6c-b6e6-40ac-974a-dc84ca669f6c.png">

I used PHP 7.3.

What happens if you clear cache ? from BO and from browser ?
Please check and feedback
Thanks!

**Comment by Hlavtox** [comment]
@okom3pom Check your browser console, the material icon font is not loading. Is your HTTPS settings correct?

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
