### ISSUE TITLE
[Product Comments] Ratings change to 1-star on changing product combination

### ISSUE THREAD

**Issue by templatin** [PrestaShop/PrestaShop#26277]
#### Describe the bug

Ratings change to 1-star on changing the product combination. Tested on fresh PS installation without any third-party modules.

#### Steps to Reproduce

1. Go to any product page with combinations and having a rating other than 1-star.
2. Change its combination.
3. Scroll down to see that ratings have changed to 1-star.

**Screenshots**
Page loaded with default combination and ratings. Everything OK.
![Untitled-1](https://user-images.githubusercontent.com/3615808/137585265-97f2c2bc-068f-44ce-b068-ced48bafe24e.jpg)

On changing the combination, the ratings change to 1-star 
![Untitled-2](https://user-images.githubusercontent.com/3615808/137585207-c748bad6-217a-439d-97b7-a6bd240dbbcc.jpg)

#### Additional information

* PrestaShop version: 1.7.8.0
* Product Comments module version: 4.2.2

**Comment by eopws** [comment]
Out of topic, but can you please explain how to enable rating and comments?

**Comment by templatin** [comment]
"Product Comments" is a native module which is pre-installed on fresh installation of PS 1.7.8.0.

**Comment by florine2623** [comment]
Hello @templatin ,

I was able to reproduce the issue with PrestaShop version 1.7.8.0 and productcomments v4.2.1 and v4.2.2, so I can confirm that this behavior is indeed a bug.

https://watch.screencastify.com/v/6I1Fn7xcldeYLuRCM4Vm

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment]
As I didn't reproduce the issue with PS1778, so it's indeed a **regression**!
Check the attached screen record below:
https://watch.screencastify.com/v/lWUkqCgPigxveoZal4Gu

**Comment by marionf** [comment]
We should release the productcomments module once this issue will be fixed

**Comment by Progi1984** [comment]
PR : PrestaShop/productcomments#116

**Comment by templatin** [comment]
> PR : [PrestaShop/productcomments#116](https://github.com/PrestaShop/productcomments/pull/116)

Working fine now :+1:
