### ISSUE TITLE
Cannot build JavaScript for ps_linklist

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/PrestaShop#26291]
Inside the module `ps_linklist`, we import some JavaScript modules from core (the modules in `admin-dev/new-theme` like grid and tinyMCE for text editor input field...).

These modules are today rewritten to Typescript, which make them impossible to import. 

There should be a change in Webpack config to take typescript loader into account. Unfortunately, this is not the only change to be brought :(. We should also add the loader in package.json and perhaps, other dependencies.  We also need to resolve other errors. This issue need a JavaScript advanced person. 

PrestaShop devs  already started writing their CRUD modules with `ps_linklist` philosophy in mind ( that is with the use of NPM and not directly including JavaScript in view). Consequently, we can't bring changes to JavaScript code without passing by NPM today. 

Is someone there willing to help me fix this issue for ps_linklist?

#### Expected behavior

If I run `npm run build`, I should encounter no errors.

#### Steps to Reproduce

1. Go to /modules/ps_linklist/views
2. Run `npm install`
3. Run `npm run build`
4. See list of errors like: 

ERROR in ./js/form/index.js
Module not found: Error: Can't resolve '@components/translatable-input' in '/var/www/html/prestatute/modules/ps_linklist/views/js/form'
 @ ./js/form/index.js 20:0-63
 @ multi ./js/form

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @arouiadib ,

I was able to reproduce the issue with PrestaShop version develop and 1.7.8.0, so I can confirm that this behavior is indeed a bug.
<img width="779" alt="Screenshot 2021-10-18 at 16 16 32" src="https://user-images.githubusercontent.com/16019289/137752498-56d70a78-de75-4c39-89d0-3e42986c4908.png">

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by arouiadib** [comment]
Thank you @florine2623 for reproducing the issue.
I have found a solution to the problem,  could you please take a look at the linked PR?

**Comment by NeOMakinG** [comment]
Nice catch!
