### ISSUE TITLE
ps_categorytree - Do not display unnecessary li tag if there is no subcategory

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#26325]
#### Describe the bug

Currently, if there is no subcategory, the ps_categorytree module still adds an empty `<li>` tag (see screenshot)

#### Expected behavior

Do not add an empty li tag.

Add a condition like this: 
`{if isset($categories.children)}<li>{categories nodes=$categories.children}</li>{/if}`

It could also be interesting to propose an option to display or not the block if there is no sub-category. Indeed, I don't find it useful, personally, to display the empty block which only repeats the name of the category

#### Steps to Reproduce

![ps_categorytree](https://user-images.githubusercontent.com/76649472/137890975-f531ec70-cabe-4400-a98a-8bf16c388463.png)

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @d33x 

I was able to reproduce the issue with PrestaShop version 1.7.8.0. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment]
I reopen this issue as there's two other PRs need to be merged.

**Comment by hibatallahAouadni** [comment]
Ping @okom3pom  Could you please re-create this PR https://github.com/okom3pom/theme-refacto/pull/2 on this [PrestaShop/theme-refacto](https://github.com/PrestaShop/theme-refacto/) project :pray: 

Thanks in advance.

**Comment by ghost** [comment]
Hahaoups:) sorry i do this

**Comment by hibatallahAouadni** [comment]
@okom3pom after creating the PR, please reopen the issue :wink: 
Thanks in advance :pray:

**Comment by ghost** [comment]
I don't have the right to do this I'll warn you

**Comment by ghost** [comment]
It's good @hibatallahAouadni
