### ISSUE TITLE
Wishlist button disappears while using Faceted Search

### ISSUE THREAD

**Issue by templatin** [PrestaShop/PrestaShop#26327]
#### Describe the bug

Wishlist button disappears on category page while using any filter in faceted search.

#### Expected behavior

Wishlist button should not disappear.

#### Steps to Reproduce

1. Go to category page having faceted search module.
2. Click on any filter in faceted search module.
3. See that Wishlist button has disappeared.

**Screenshots**

![Untitled-3](https://user-images.githubusercontent.com/3615808/137918909-104c0681-d992-4f4c-963b-5eca54300e1c.jpg)

#### Additional information

* PrestaShop version: 1.7.8.0
* Wishlist module: v2.0.1
* Faceted Search module: v3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @templatin 

Thanks for reporting the issue!
I reproduce the issue wonly with PS1780, it's a **regression**! Cause I didn't manage to reproduce with PS1778.
I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment]
PR by @alexandrebrubeyonds

**Comment by Progi1984** [comment]
Fixed by @alexandrebrubeyonds in #26526
