### ISSUE TITLE
BO new slide button look be more coherent with the theme.

### ISSUE THREAD

**Issue by SNor42** [PrestaShop/PrestaShop#26387]
#### Is your feature request related to a problem?
NO
#### Describe the solution you'd like
See image.
#### Alternatives you've considered
See image.

![kép](https://user-images.githubusercontent.com/1334351/138552709-3c832e10-0847-4cc1-85eb-d0b25d1642ad.png)

**Comment by hibatallahAouadni** [comment]
Hello @SNor42 

So, you're asking to change the color of the actuals Yes/No to the proposed ones, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/138688461-1133a211-5ead-4083-9f90-ed039d2bfadd.png)

![image](https://user-images.githubusercontent.com/23308427/138688473-fc97c21a-80af-404e-bef2-a231c903d36c.png)

- Actual **Yes** (Green) => Proposed **Yes** (Blue)
- Actual **No** (Gray) => Proposed **No** (Red)

Is that so? please confirm :pray: 

Thanks!

**Comment by SNor42** [comment]
I'm not 100% sure, that we need to drop the green color. But to be true, there is only few place where it was used (banners for example). So if it count, I found the blue one is a better choice. :) 
Proposed:
**Disabled**: background: #b3c7cd (as it is now), opacity: 0.5 (not 0.2 as now).
**YES**: background: --blue (#25b9d7)
**NO**: background: --red (#f54c3e), but about lighter (I used 0.5 opacity for the preview-> #faa59e).

**Comment by hibatallahAouadni** [comment]
Hello @SNor42 

> **Disabled**: background: #b3c7cd (as it is now), opacity: 0.5 (not 0.2 as now).
**YES**: background: --blue (#25b9d7)
**NO**: background: --red (#f54c3e), but about lighter (I used 0.5 opacity for the preview-> #faa59e).

Well then, thank you for your suggestion!
The Product Team will take it into consideration for future developments. Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by NeOMakinG** [comment]
@prestascott Looks like a question for you! cc @PrestaShop/ux-team

**Comment by prestascott** [comment]
Hello everyone!

Thank you @SNor42 for your suggestion, and @NeOMakinG for the ping :)

The blue color is used for neutral actions, it doesn't suppose to represent a positive component. 
For example, the "Add new product" button is blue because it's not positive or negative.

About switches/toggles, the same rules apply. When on, it must be green so users can identify them as enabled by simply looking at the color. If you decide to change the green into blue, then users won't have this reflex.

Users have this natural perception of what's wrong (red) and what's good (green), most frequently blue color represents calmness. That's why most of the interfaces use blue because it's soft for users' eyes. In this case, the grey color is used instead of the red color when switches/toggles are off because it's simply less aggressive.

Now about the switch/toggle's appearance, it has been changed into a rounded because of its higher level of affordance. Rounded shapes are identified as harmless and users tend to interact easier with them than sharp-corner shapes.

What we should keep: 
- Green when toggle/switch is on
- Grey when toggle/switch is off
- Light Grey when toggle/switch is disabled
- Rounded shape

**Comment by hibatallahAouadni** [comment]
Hello @SNor42 

> What we should keep:
>
> - Green when toggle/switch is on
> - Grey when toggle/switch is off
> - Light Grey when toggle/switch is disabled
> - Rounded shape

Well then, I close this issue. 
Thanks @prestascott for your reply :relaxed: 

Thanks!

**Comment by SNor42** [comment]
Hi!
@prestascott: Thank you for your answer. I understand your thoughts, and I would say in most case it's alright.
But this is a switch, with two options, what you could use widly on the BO. 
If the two option is on and off, or similar, than green is a good solution*. But you could set up very different ways too: left/right, dark/white. In these scenarios both option is neutral. The other thing is that we use green only with the switch, and with success dialogs. None of the buttons have green options. For exampe "Save" is not a neutral choise, it could be also green than. But to use it wildly would made more probem, so I understand why is it blue quite everyhere.

*One thought about red: we use these swith on products page too, where shows if a product is active or disabled. Here I suggest a red option (what it was previusly) is a better color choise for disabled product.

After all, thanks again for and for others your to take time to thought about it.

**Comment by prestascott** [comment]
I'm interested to see which product pages are you referring to. Can you provide us some screenshots so we can visualize what you are explaining, please?

**Comment by SNor42** [comment]
My bad, sorry :) It is the catalog/products page:
![kép](https://user-images.githubusercontent.com/1334351/139291227-cedb7c0a-0971-4363-83f8-68582600de33.png)

**Comment by prestascott** [comment]
Okay i see. The state of the switch/toggle is "off" (grey color), which is different than "disabled" (lighter grey color).
