### ISSUE TITLE
BO - Migrated page - Multistore - annoying content-div transition

### ISSUE THREAD

**Issue by SNor42** [PrestaShop/PrestaShop#26383]
#### Describe the bug

On every page load the div with class name "content-div" have a padding transition.
![2021-11-05 123449](https://user-images.githubusercontent.com/1334351/140504742-c423fea4-04ec-4577-b78f-93903cf5387c.png)
**Todo**

- [ ]  investigate

#### Expected behavior

No transition

#### Steps to Reproduce

https://www.awesomescreenshot.com/video/5739026?key=55111ffd394f5717648b9a7ebc84a214

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

#### Solution:
Under PrestaShop/admin-dev/themes/new-theme/scss/components/layout/_content_div.scss 
Delete these lines:
```
  @include transition(
    padding 0.5s ease
  ); // transition when collapsing the nav menu
```

**Comment by Hlavtox** [comment]
@SNor42 Yes this definitely needs to be removed, it's against all content shifting rules. Do you want to make a PR for this?
We can also convert the header to `position: sticky;` and ditch the JS.

cc @NeOMakinG

**Comment by eopws** [comment]
Not able to reproduce with PS1781. Also the
`@include transition(
    padding 0.5s ease
  ); // transition when collapsing the nav menu`
lines are present

**Comment by SNor42** [comment]
I Could not test it on PS1781 only on PS1780, and it only appears when the multistore is enabled (with the new multistore header). WO multistore, everything is fine.

**Comment by hibatallahAouadni** [comment]
Hello @SNor42 

It seems to me an improvement more than a bug :wink: 
So, thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: thanks @Hlavtox for your quick reply

Thank you

**Comment by Progi1984** [comment]
@PrestaShop/product-team Does it need specifications ? :wink:

**Comment by MatShir** [comment]
It looks like more a reggression introduce by the multistore feature. I don't see what specification I can deliver here since it is a performance issue. But my question now before approving any changes is to understand why it has been implemented in first place in the multistore header? and how this transition can be improved if it was necessary in the first place?
Maybe @matthieu-rolland could you help us on this?

**Comment by MatShir** [comment]
> Not able to reproduce with PS1781. Also the `@include transition( padding 0.5s ease ); // transition when collapsing the nav menu` lines are present

@hibatallahAouadni it seems that the issue is not present on `1.7.8.x`, could you double check ? It might have been alreday fixed 🤷‍♂️

**Comment by Hlavtox** [comment]
@MatShir Google “content layout shift” and why is it bad, then you will just accept immediately 😁

**Comment by matthieu-rolland** [comment]
I'm not sure it's safe to remove this line, it was added long before multistore, in this commit from @eternoendless 

https://github.com/PrestaShop/PrestaShop/commit/1388076f31708163412b7fad90007a311782798f

I don't know if it's still necessary or not, if it's still necessary we need to find another fix

**Comment by eternoendless** [comment]
The problem is not the transition (which is needed to get the animation you collapse the left menu), but the layout shift introduced by something else (probably the multistore header?) whose height is updated after the page has been initially rendered.

@Hlavtox CLS is irrelevant in a Back Office IMO.

Perhaps @NeOMakinG can have a look to find out what it is

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

> > Not able to reproduce with PS1781. Also the `@include transition( padding 0.5s ease ); // transition when collapsing the nav menu` lines are present
>
> @hibatallahAouadni it seems that the issue is not present on `1.7.8.x`, could you double check ? It might have been alreday fixed 🤷‍♂️ 

You can only reproduce it when Multistore is enabled, see the attached screen record below:

https://watch.screencastify.com/v/ZPghiHSiTvNeYrasDio8

Thanks!

**Comment by Hlavtox** [comment]
@eternoendless It's annoying the same as everywhere else. On a slow server, I am already aiming my mouse on a product or order I want to click and it moves under it.

Basically the problem is everywhere, where the header is longer than normal. (Longer page name, multistore line added, buttons don't fit)

**Proper solution:**
- Remove this JS fixed height calculating
- Use `position: sticky;` and automatic or min-height
- Remove transitions and make it instant
- Profit

I can have a look into it with Valentin :-)

**Comment by SNor42** [comment]
There is also some minor issue, when you change the window width.

Daniel Hlavacek ***@***.***> ezt írta (időpont: 2021. nov.
5., P, 12:12):

**Comment by SNor42** [comment]
![2021-11-05 123449](https://user-images.githubusercontent.com/1334351/140504742-c423fea4-04ec-4577-b78f-93903cf5387c.png)
![2021-11-05 123515](https://user-images.githubusercontent.com/1334351/140504744-804bc977-cd10-4d77-80c4-e1f1ac4ccde3.png)

**Comment by SNor42** [comment]
And what, if we just animate padding-left?
transition:padding 0.5s ease -> transition:padding-left 0.5s ease


Silló, Norbert ***@***.***> ezt írta (időpont: 2021. nov. 5., P, 12:35):

**Comment by eternoendless** [comment]
I think the padding transition also impacts Vuejs-based pages (stock management & translation interface).

**Comment by MatShir** [comment]
Hey @NeOMakinG, could you investigate the issue please? I look like, it is a front end issue. Maybe @matthieu-rolland, can help you 🤗

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/26613
