### ISSUE TITLE
Theme selector preview image fitting problem BO/multistore

### ISSUE THREAD

**Issue by SNor42** [PrestaShop/PrestaShop#26385]
#### Describe the bug

BO multistore settings, when add new shop, under the theme selector, the preview image won't fit. Missing max-width:100%, and there is set a margin-bottom for some reason.

#### Expected behavior
![kép](https://user-images.githubusercontent.com/1334351/138551495-bbf1bafa-b402-4440-a8e5-b8557c7462ce.png)
![kép](https://user-images.githubusercontent.com/1334351/138551548-4d95594d-5ea7-4660-bff2-64f5f7816be2.png)

#### Steps to Reproduce

1. Enable multistore
2. Add new shop

![kép](https://user-images.githubusercontent.com/1334351/138551531-374d9501-bd11-4e70-b718-7eadf417f4d9.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @SNor42 

I reproduce the issue with PS1767, PS1778 and PS1780. I’ll add this to the debug backlog so that it’s fixed.
And many thanks for reproting this issue :clap: :rocket: 

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

A PR is available for this issue and waiting for QA.
Could you check if it is PM ✅ ?

Thanks!

EDIT : a bug not an improvement, no need for PM
