### ISSUE TITLE
Multistore: payment options disapear after adding voucher in checkout

### ISSUE THREAD

**Issue by SimonasB88** [PrestaShop/PrestaShop#26413]
#### Payment options disappear after adding voucher in checkout

Once the user inputs the voucher in the last step of checkout, Prestashop payment disappear instantly

#### Expected behavior

The voucher should discount the price correctly, and the user should proceed finishing the order by clicking PLACE ORDER

#### Steps to Reproduce

1. Create 2 Default Shop groups, with 2 Mulstishops for each:
![image](https://user-images.githubusercontent.com/29095235/138721018-2cc95062-e967-4197-b495-0a8a782528a5.png)

2. Create the Cart Rule just like in screenshots:
![image](https://user-images.githubusercontent.com/29095235/138720387-85e74e06-51df-4b3c-a76c-4228a6ef0e39.png)
![image](https://user-images.githubusercontent.com/29095235/138720429-827f7c38-d3f2-40fa-b362-f6bfdccc6cab.png)
![image](https://user-images.githubusercontent.com/29095235/138720707-3dddc00d-9d64-4673-918a-9ed3d014c242.png)
3. Switch on to the Shop-4 and then proceed to the Checkout.
4. Navigate to the last step of Payment.
5. Use the Voucher.

Payment options then somehow vanishes away.
Can not detect anything in frontend or backend logs. 

Additional reproduction video added also.

https://user-images.githubusercontent.com/29095235/138722799-b2746b0f-39d7-4b3a-8888-60726b616e7c.mp4

#### Additional information

* PrestaShop version: 1.7.8.0 
* PHP version: 7.1.33

**Comment by nandugachristine** [comment]
Thanks for the video

**Comment by florine2623** [comment]
Hello @SimonasB88 ,

Thanks for the report, I managed to reproduce the issue in PS **1.7.8.0** and **develop** branch. This is a regression as it was working fine in PS 1.7.7.7.

In PS 1.7.7.7 - **OK** :
https://watch.screencastify.com/v/Ub4cbZ91MNiz0y7dWqCh

In PS 1.7.8.0 and develop branch, here's my multishop config :
<img width="1226" alt="Screenshot 2021-10-26 at 12 38 25" src="https://user-images.githubusercontent.com/16019289/138861850-931b0c65-7b9c-4177-a814-3ee1dc99af72.png">

My payment config :
<img width="1166" alt="Screenshot 2021-10-26 at 12 38 34" src="https://user-images.githubusercontent.com/16019289/138861886-828b8bc5-d725-4410-b941-85fe3e201927.png">

My cart rule config tab :
<img width="884" alt="Screenshot 2021-10-26 at 12 38 53" src="https://user-images.githubusercontent.com/16019289/138862858-01beaa2a-7e52-4735-b7dc-ddd617ea686a.png">

In PS 1.7.8.0 and develop - **NOK** no payment displayed:
<img width="1154" alt="Screenshot 2021-10-26 at 12 47 02" src="https://user-images.githubusercontent.com/16019289/138862984-0c320f95-6c10-46d8-81e7-823183722b56.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment]
It might be strongly related to https://github.com/PrestaShop/PrestaShop/issues/17621

**Comment by atomiix** [comment]
@florine2623 I don't think this is a regression, can you try again with PrestaShop 1.7.7.7? Because when I try I have the same issue.

**Comment by matks** [comment]
@atomiix did you start this topic?

**Comment by atomiix** [comment]
@matks I only investigated and see that it didn't seem to be a regression

**Comment by matks** [comment]
@atomiix I take it then 👍  thank you

**Comment by matks** [comment]
@florine2623 Sorry for disturb, could you please retest this bug with 1.7.7.7 ? 😄  we need to know if it's a regression and @atomiix thinks maybe it's not a regression

**Comment by hibatallahAouadni** [comment]
Hello @SimonasB88 & @florine2623 & @atomiix 

I didn't reproduce the issue with PS1778 and PS1785 :sweat_smile: 

![image](https://user-images.githubusercontent.com/23308427/162443832-c3d63ffc-b3e2-4449-9c57-2118f93640fc.png)

You need to enable the cuurrency in BO for the Payemnt method:

![image](https://user-images.githubusercontent.com/23308427/162443933-2533250b-7b5e-4c18-b6d3-d56ca5656626.png)

Closing the issue as there's no issue :sweat_smile: 
Thanks!

**Comment by SimonasB88** [comment]
yea seems like no more in the latest versions :)
