### ISSUE TITLE
Specific prices are not properly duplicated when duplicating a product

### ISSUE THREAD

**Issue by samaij** [PrestaShop/PrestaShop#26424]
#### Describe the bug

When duplicating a product, any specific prices related to the product that are specific to a single combination are not duplicated.

#### Expected behavior

All specific prices should be duplicated.

#### Steps to Reproduce

1. Create a specific price for a combination
2. Duplicate the base product
3. See that the specific price is not found in the duplicated product

**Screenshots**

Original product with 2 specific prices:
![image](https://user-images.githubusercontent.com/47714302/138826908-b1d6ba2d-6789-4a78-b2d8-3766328640b6.png)

Duplicated product with only 1 specific price (combination-specific one is missing):
![image](https://user-images.githubusercontent.com/47714302/138827288-3dc3f153-b5f0-4a87-8b20-c093695ede06.png)

#### Additional information

Tested on:
* PrestaShop version: 1.7.8.1 (develop), 1.7.7.2
* PHP version: 7.4.24, 7.2.24

**Comment by florine2623** [comment]
Hello @samaij ,

I was able to reproduce the issue with PrestaShop version 1.7.7.7, 1.7.8.0 and develop, so I can confirm that this behavior is indeed a bug.

Specific price related to a combination does not duplicate.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
