### ISSUE TITLE
Attributes with comma not displayed in Stock management

### ISSUE THREAD

**Issue by Sekar33000** [PrestaShop/PrestaShop#26429]
#### Describe the bug

If a product attribute contain a comma (,) the product is not displayed in stock management.
For example a shoe size 37,5 is not displayed, a 37 1/2 shoe size work perfectly.

#### Expected behavior

I want to see all my product attributes...

#### Steps to Reproduce

1. Go to 'Stock management'
2. Search a product which contain product attribute with comma, it will be not displayed...

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by florine2623** [comment]
Hello @Sekar33000 ,

I was able to reproduce the issue with PrestaShop version 1.7.8.0 and 1.7.7.7 with a difference between the 2 versions, so I can confirm that this behavior is indeed a bug.

In PS 1.7.7.7 (displayed the attribute with "undefined") :
<img width="1180" alt="Screenshot 2021-10-26 at 16 00 18" src="https://user-images.githubusercontent.com/16019289/138894726-f3639a5d-afba-47c2-b9ab-85f4a5c13cac.png">

In PS 1.7.8.0 (attribute 37,5 is not displayed at all) :
<img width="1185" alt="Screenshot 2021-10-26 at 15 58 23" src="https://user-images.githubusercontent.com/16019289/138895009-1b8ad417-0caf-445d-ba7f-df764671f4d7.png">


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Progi1984** [comment]
Fixed by @alexandrebrubeyonds in #26447
