### ISSUE TITLE
ps_facetedsearch - Alphabetical order of brands is not correct

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#26444]
#### Describe the bug

The alphabetical order seems to be case sensitive as it takes into account possible capital letters when it should not.

![ps_facetedsearch](https://user-images.githubusercontent.com/76649472/139065842-34654ac6-13da-41a0-8fb4-e768ca65211c.png)

#### Expected behavior

"abc" brand should be before "Studio Design"

#### Steps to Reproduce

1. Create several brand with capital letters or not
2. Activate faceted search
3. See error

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3
* ps_facetedsearch version: 3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @d33x 

I manage to reproduce the issue with PS1767, PS1778, PS1780, see the attached screenshots below:

### BO :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/23308427/139106519-0d6aeb59-c573-4513-8519-a1c3000f041a.png)

### FO: :x: 
![image](https://user-images.githubusercontent.com/23308427/139106483-2560edfe-42aa-445b-a33b-a91fdee7433a.png)

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
