### ISSUE TITLE
SEO & URLs problem after upgrading to 1.7.8

### ISSUE THREAD

**Issue by Dar-us-Salam** [PrestaShop/PrestaShop#26536]
#### Describe the bug

I upgraded fine from 1.7.7 to 1.7.8 but recently noticed that when I turned on Debug it gave an error in override/classes/Dispatcher.php for all the front office pages: https://prnt.sc/1y8g8tk . After clearing the cache, it changed to override/classes/Link.php - screenshot: https://prnt.sc/1xqbz42 . Both of the files are from the Advanced Friendly URL module so I thought that was the cause and so I uninstalled the module and when I tried to add {id} back on the SEO & URLs page, it keeps giving this error:  **Keyword "{id}" required for route "layered_rule" (rule: "{categories:/}{rewrite}/{/:selected_filters}/")** . This 3rd Route line is [missing in Prestashop 1.7.8](https://prnt.sc/1yiaw9v) while it is being required - https://prnt.sc/1yib7g1 . I found this out in the [user guide for v.1.7](https://doc.prestashop.com/download/attachments/51185023/Capture%20d%E2%80%99e%CC%81cran%202019-08-20%20a%CC%80%2016.35.39.png?version=1&modificationDate=1566312616000&api=v2).

I will appreciate any help to resolve this issue and fix the problem.
Thank you!

**Comment by Dar-us-Salam** [comment]
I purchased the PS IT Advanced Clean Urls module which had the same issue. I contacted their tech support who said I needed to purchase the $50 check service for them to research & fix the issue. I purchased that and they updated their module which is working great now. 

Prestashop developers should fix the root cause which is caused when friendly URL module/s is uninstalled.

**Comment by hibatallahAouadni** [comment]
Hello @Dar-us-Salam 

Without steps to reproduce, how we can find and fix the root problem :wink: 
Glad that your problem is fixed, but please next time **respect and follow the provided template to submit a complete bug report**.

Unfortunately, there is not enough information provided to reproduce it and work on it. So, I close the issue.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
