### ISSUE TITLE
[FO] Mobile add-to-cart modal is messed up on 1.7.8.x - regression

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26642]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![obraz](https://user-images.githubusercontent.com/5007456/142082860-f7877efd-3673-4b66-bd0a-7fb15268a33d.png)

### Expected behavior

It was good enough on 1.7.7.x

### Steps to reproduce

1. Open product page on mobile or dev tools responsive mode
2. Add product to cart and wait for the modal to pop up

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by hibatallahAouadni** [comment]
Hello @SharakPL 

I reproduce the issue with PS1780, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/142297870-2f5a6c4f-f14c-490d-bfb5-baad2335ad8c.jpeg)

While with PS1778, the modal displays well:

![image](https://user-images.githubusercontent.com/23308427/142297811-2e5942f9-883a-4581-a644-5648a09fb0eb.jpeg)

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by SharakPL** [comment]
Thanks. I'm trying to fix all these issues I reported recently, but it's hard when docker setup isn't working properly, especially on branches other than develop :(

**Comment by hibatallahAouadni** [comment]
@SharakPL You can ask for help in the [public Slack channel](https://prestashop.slack.com) :wink: the developers and the maintainers will be glad to help you up.

**Comment by NeOMakinG** [comment]
@SharakPL do you want to fix these issues or should I take some?

**Comment by SharakPL** [comment]
Go ahead @NeOMakinG :)

**Comment by SharakPL** [comment]
I'd recommend moving buttons into seperate lines on mobile

**Comment by NeOMakinG** [comment]
@prestascott wdyt of the last comment of @SharakPL ?

**Comment by prestascott** [comment]
Hello everyone,

Thanks @SharakPL,

I agree with you by putting both buttons into separate lines on mobile. But to keep consistency, we can also provide the same behavior on the desktop version.

Behaviors:
- Proceed to checkout (at the top) because this is where merchants want their clients to focus and click so they can place the order.
- Continue shopping (at the bottom) because it's is not the focus.

Great work!

Wdyt?

**Comment by SharakPL** [comment]
I'd also put **Proceed to checkout** on top on mobile. Though I'm not sure it's an improvement also on desktop version:

![image](https://user-images.githubusercontent.com/5007456/143479700-e10d7446-1f6e-4c4c-b756-f2da80bfce1d.png)

Whole modal is too big for the information it contains. Content sizes also could be better. Maybe something like this (open images to compare actual size):

![image](https://user-images.githubusercontent.com/5007456/143482079-dcea250e-2809-43d3-8a03-4e46dcf2cbf1.png)

**Comment by Progi1984** [comment]
@NeOMakinG Could you check this issue ?

**Comment by saulaski** [comment]
@hibatallahAouadni Transparency on top is not an issue anymore, looks ok in current 1.7.8.x patch version.
I still notice 3 differences in the responsive design of the modal:
1. There is no margin between picture name and picture
2. Left margin of the lowest block should be removed on mobile display (comes from desktop display)
3. Lower buttons lost their shadow effect, just like all other buttons in FO

Points (1) and (2) are easy fixes.
Point (3) isn't an issue I suppose.

![issues](https://user-images.githubusercontent.com/97030953/151408474-4ea61e4a-a32b-4198-bf9c-f6ba17421b7a.jpeg)

**Comment by NeOMakinG** [comment]
> @NeOMakinG Could you check this issue ?

This is an UI decision honestly, ping @prestascott

**Comment by Progi1984** [comment]
Fixed by @saulaski in #27502 and tested by @HanaRebaiQA.

**Comment by saulaski** [comment]
@Progi1984 before closing the issue, should we include this other PR dedicated to layout refactoring in develop ?
https://github.com/PrestaShop/PrestaShop/pull/27548

**Comment by prestascott** [comment]
@SharakPL "Proceed to checkout" button is placed on top of the "Continue shopping" button which is nice because it's the priority. But because of the wide size of the modal, both buttons are very large... Can you reduce the width of the modal please?

Same on mobile, "Proceed to checkout" button needs to be on top of the "Continue shopping" button and not next to each other because of the priority and also because some users have small mobile devices.

**Comment by SharakPL** [comment]
@prestascott you're referring to [my design](https://github.com/PrestaShop/PrestaShop/issues/26642#issuecomment-979366709) or @saulaski 's PR?

**Comment by saulaski** [comment]
@prestascott please take a look at the new design ready to merge in this PR : https://github.com/PrestaShop/PrestaShop/pull/27548#issuecomment-1026575671

**Comment by prestascott** [comment]
I was referring to your design @SharakPL 

Ok, I'll take a look @saulaski

**Comment by SharakPL** [comment]
> I was referring to your design @SharakPL

Then my suggestion was this:
![image](https://user-images.githubusercontent.com/5007456/143482079-dcea250e-2809-43d3-8a03-4e46dcf2cbf1.png)

- compact size
- better layout
- clear view of modal actions

**Comment by prestascott** [comment]
@SharakPL The layout is good. I would remove the grey background on modal actions, and remove the check icon on the "Proceed to checkout" button.

**Comment by MeKeyCool** [comment]
@MatShir , as you didn't allow #27548, what should we do with this issue ?
Should it be suppressed ? Redefined ? Target another version ?

**Comment by MatShir** [comment]
Close the issue in favor https://github.com/PrestaShop/hummingbird/issues/55

**Comment by Progi1984** [comment]
@MatShir Should we close the PR #27548 ?

**Comment by SharakPL** [comment]
@MatShir what **quick view** modal has to do with **add to cart** modal?

**Comment by NeOMakinG** [comment]
I guess this bug has been "fixed" but not "improved" as we don't push improvement on classic now, to make it fully compatible without any changes in the next PS version

And @MatShir just took a wrong issue, but he wanted to say "Closing in favor of hummingbird add-to-cart implementation"
