### ISSUE TITLE
Refactor KPI bar

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26667]
### Is your feature request related to a problem?

KPI code is full of errors, unneeded code and difficult to debug.

![KPI](https://user-images.githubusercontent.com/6097524/142404774-10ed493f-686c-4aa4-b725-68effd5f0779.JPG)

### Describe the solution you'd like

It needs to be refactored.

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thanks!

**Comment by matks** [comment]
Hello @Hlavtox 

- KPI code is full of errors

Well, obviously we'll be happy to review contributions which fix errors ✅ 

- unneeded code

KPI HTML markup is automatically generated by some php logic, so maybe this explains the over-engineered structure. So depending on the items, some might have to be kept ;)

- difficult to debug

This item needs to be explained a little bit more, what's hard to debug?

For example structures generated by "magic" components like the Grid or HelperForm are always hard to debug because in order to understand why the 4th div has the wrong class you need to understand why it generated it this way. This is why [I usually try to avoid magic](https://dev.to/matks/what-is-magic-in-code-and-why-avoid-it-1m4p) but as PrestaShop is a CMS, we _need_ to implement some generic magic in order to make things configurable. Hardcoded HTML is always the easiest to debug 😄 

So can you tell us more about what is hard to debug ? Depending on the answer, there might be things we can do ... or maybe we wont be able to fix it because it comes from its inner nature of generated code.


---------

I see the PR https://github.com/PrestaShop/PrestaShop/pull/9242 is the one who introduced the KPI system, I believe it was built by @rokaszygmantas and @mickaelandrieu . As you can see it says `We needed a common and re-usable system to display KPIs block everywhere in Symfony pages` so I'm quite sure some of the behaviors you consider mistakes are unfortunately _consequences_ of using a common, generic, re-usable system (instead of hardcoding each KPI).

**Comment by Hlavtox** [comment]
@matks No hard feelings for anything, just wanted to specify the problems. I went right away and refactored it in my PR. It has both clean code and common, generic, re-usable system. 😉

It's difficult to debug CSS, because there were a lot of unneeded divs and mistakes. You expect some things to behave some standardized way, but there is a lot of hacks everywere.

Imagine you are searching for an element that is producing some unwanted margin.
- There is row with negative margin, cancelled by a col-md-12's padding. OK, rookie mistake.
- Then there is a boostrap row producing negative margin again, cancelled by boostrap container's padding. This container should not be there at all, it should be used only for limiting page width.
- Then there is a row which produces negative padding, but has no columns. Confusion again.

![divs](https://user-images.githubusercontent.com/6097524/142851639-bd1da3b7-0a12-4b2b-8f1a-61dab3a60005.JPG)
