### ISSUE TITLE
Notifications should not be responsible for showing informational messages about empty data

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26749]
### Is your feature request related to a problem?

In my account, information about empty orders, empty credit slips is passed as a notification to the controller.
If we don't want to move all notifications on my account pages, which **A) can be totally unrelated to the content**, **B) is a hackjob** and **C) we want to style them**, we need to change it.

![notification](https://user-images.githubusercontent.com/6097524/143426365-3f51d9de-d407-4d12-ac97-a33ca0358886.JPG)

### Describe the solution you'd like

It should be the responsibility of the template to display relevant informational messages, if nothing is found.
Notification should be removed and strings moved to this logic in the template. Theme will have a full control of the display and if it wants, it could display in whatever way possible.

![lost-john-travolta](https://user-images.githubusercontent.com/6097524/143427414-4718663e-948f-4379-a4d5-82de2e3a11c3.gif)

```
{if $orders}
   Your orders:
    --List them--
{else}
    You have not placed any orders.
{/if}
```

### Concerned pages
https://github.com/PrestaShop/PrestaShop/blob/901a073a6466642d20bc6440e83fc472bfa7ceb5/controllers/front/DiscountController.php#L47
https://github.com/PrestaShop/PrestaShop/blob/901a073a6466642d20bc6440e83fc472bfa7ceb5/controllers/front/HistoryController.php#L58
https://github.com/PrestaShop/PrestaShop/blob/901a073a6466642d20bc6440e83fc472bfa7ceb5/controllers/front/OrderSlipController.php#L47
https://github.com/PrestaShop/PrestaShop/blob/901a073a6466642d20bc6440e83fc472bfa7ceb5/controllers/front/OrderFollowController.php#L108

Ping @matks @PierreRambaud

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Developer Team and UX-team will take it into consideration for future developments. 
Ping @PrestaShop/ux-team wdyt?

Thank you

**Comment by Hlavtox** [comment]
@hibatallahAouadni It's more of a dev thing, UX is already approved on Figma. Can you ping dev team please?

![Výstřižek](https://user-images.githubusercontent.com/6097524/143427731-cae5c5f1-9ea4-4a8e-8e06-e2ea47af5097.JPG)

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers

**Comment by matks** [comment]
> In my account, information about empty orders, empty credit slips is passed as a notification to the controller.

Usually, information messages that are passed as notifications are described as 'flash messages'. They are stored in sessions and their behavior is "store them until next page (whatever page) is displayed, and display them there". The goal of this system is to make sure that, no matter what page the visitor will visit, he will see the message.

One of the benefits of this approach: if I visit page A, and on page A something bad happens, so I need to be notified, and because of this bad thing the application redirects me to page B, I will see the notifications on page B. If we dont use flash messages, and instead display only the warning on page A, then if I cannot visit page A (it's broken or when I visit it I am redirected to page B) I cannot see my informations.

@Hlavtox so we could say your suggestion is "Stop using flash messages to transfer the warnings about empty orders or empty credit slips and inform the user, rather display these informations in the dedicated place" am I right ?

**Comment by Hlavtox** [comment]
Exactly Mathieu!

Notification is a one time success or error message. Your address have been added, order return has been submitted, your customer account has been transformed.

Permanent data, like having no orders should be done by just simply doing an else - like in product list where there are no products.

**Comment by matks** [comment]
It makes sense for me 👍
