### ISSUE TITLE
Unefficient retreival of $this->id_lang in class Cart

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#26787]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I discovered this bug in Profiling mode, see screenshot :
![2021-11-29_100258](https://user-images.githubusercontent.com/7520695/143838392-e45b986d-508a-46a7-8a28-b1c82a3dfd68.jpg)
The class *Cart* instantiates 40x an object model *Language*, always the current language. Not only one time would suffice, but looking at the code, each time it is the code `$this->getAssociatedLanguage()->getId()` that is implicated.
`ObjectModel::getAssociatedLanguage` loads the Language object model referenced in `$this->id_lang` (see https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ObjectModel.php#L379), but we only use the id of that model.

The bug consist of using `$this->getAssociatedLanguage()->getId()` instead of the straight forward `$this->id_lang`.

### Expected behavior

I expect that when an object property is directly accessible, like `$this->id_lang`, we use it, instead of going for a convoluted, ressource intensive solution.

### Steps to reproduce

1. Enable Profiling mode
2. Display a FO page while having an article in the cart
3. Scroll down to Profiling section *ObjectModel instances*
4. Notice the number of times a language object model is instantiated (43x in my case, of which 40x in `classes/Cart.php`)

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for reporting this issue :rocket: 
This behavior has been introduced since PS1.7.7.3:

### PS1.7.6.7 & PS1.7.7.0 & PS1.7.7.2:

- Empty Cart: 3
![image](https://user-images.githubusercontent.com/23308427/144023315-579e927e-ca08-4d6c-8c08-850aee3e3d84.png)
- Cart not empty: 3 
![image](https://user-images.githubusercontent.com/23308427/144028823-0430322b-9609-4aef-9809-894233755384.png)

We have the same number of times a language object model is instantiated: 3 times

### PS1.7.7.3:

- Empty cart: 3
- Cart not empty: 17

https://watch.screencastify.com/v/NOPnyXzhJr3gUvxznVaJ

### PS1.7.7.4: 
It gets worse:

- Empty Cart: 3
- Cart not empty: 48

https://watch.screencastify.com/v/zlcmFfeCnLWxoQU1e9lO

### PS1.7.7.8:

- Empty cart: 28
![image](https://user-images.githubusercontent.com/23308427/144028896-f5b42469-6d77-4143-9784-200e3f68e40e.png)
- Cart not empty: 48
![image](https://user-images.githubusercontent.com/23308427/144028934-c089d162-9bab-4b63-8631-946525a54604.png)

Here's a screen record showns the difference between PS1770 and PS1778:

https://watch.screencastify.com/v/CPNyca7QvBskXvwJjQUK

So, indeed it's a **regression** since **`1.7.7.3`**. I’ll add this to the debug backlog so that it’s fixed.

Thanks for your PR :rocket: 

Thank you
