### ISSUE TITLE
[BO] Bad display of the notifications dropdown in medium screen

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#26792]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When screen size is between 768px and 1023px, the notifications dropdown has an oversized height.

![Screenshot from 2021-11-29 14-42-55](https://user-images.githubusercontent.com/85633460/143860172-118e4cfe-974c-4e91-ad86-0697880caf89.png)

### Expected behavior

![Screenshot from 2021-11-29 14-45-43](https://user-images.githubusercontent.com/85633460/143860228-0cc608d4-30b4-41c2-9c68-8c82dbd179ae.png)

### Steps to reproduce

Go to BO > Orders

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

I reproduce the issue with PS1767, PS1781 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/143889419-33bc9c67-248d-4024-8b53-1fa3f00fedef.png)

This issue occurs only on migrated pages. I’ll add this to the debug backlog so that it’s fixed.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
