### ISSUE TITLE
Upgrade from 1.7.7.8 to 1.7.8.2 – strange behavior in the admin

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#26984]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

1)	Eshop works but new Experimental features is installed with completely different name.
Correct is BO menu Advanced parameters - **Experimental features**
But I have BO menu Advanced parameters – **Customer settings** (Nastavení zákazníků in Czech language)
![image](https://user-images.githubusercontent.com/38213520/146028251-b9d11473-ae22-473c-b9a6-2a5adc1b97fe.png)
 
2)	Second problem is after installation modules Marketing  Facebook (ps_facebook) and Google (psxmarketingwithgoogle). 

Menu is wrong same like point 1) and after click on the Facebook (Zaměstnanci/Team) or Google (Importovat/Import) access denied.
![image](https://user-images.githubusercontent.com/38213520/146028378-4cebf674-8292-4614-aae0-3f6839560bc1.png) 

After uninstall and delete modules menu Marketing/E-maily still remains.
Page not found
The Marketing driver is missing or invalid.
 
![image](https://user-images.githubusercontent.com/38213520/146028462-ebba2c79-e974-4c09-a891-c553c9393ad2.png)

Reinstall Facebook module:
Is not possible install module ps_facebook. Failed to install Marketing tab
Second attempt – Installation module ps_facebook was sucefull.

Reinstall Google module:
Is not possible module psxmarketingwithgoogle. Failed to install AdminPsxMktgWithGoogleModule tab
Installation module psxmarketingwithgoogle was sucefull.

Same behavior but menu have different names:
 
![image](https://user-images.githubusercontent.com/38213520/146028517-0e91fd61-0ce5-4258-a496-35550ea2bf16.png)
![image](https://user-images.githubusercontent.com/38213520/146028532-ffc673ba-1a73-4b58-8427-ef19a8ee83f8.png)

MySQL: 10.1.48-MariaDB-0+deb9u2

Thank you
Best regards
PN

### Steps to reproduce

upgrade PS from 1.7.7.8 to 1.7.8.2
install modules: Marketing Facebook (ps_facebook) and Google (psxmarketingwithgoogle)
click on configure

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3.31-1~deb10u1

**Comment by florine2623** [comment]
Hello @PeNov ,

I upgraded PS 1.7.7.8 to PS 1.7.8.2 (I have 2 languages : Czech default & English), it went well :
<img width="1194" alt="Screenshot 2021-12-14 at 17 06 08" src="https://user-images.githubusercontent.com/16019289/146035150-5e353f0b-7f81-4cce-9243-9f09b5bfa5a6.png">

1. After the upgrade my menu is correct regarding Experimental Features : ✅ 
<img width="838" alt="Screenshot 2021-12-14 at 17 14 28" src="https://user-images.githubusercontent.com/16019289/146036535-aff825d8-dc57-4b98-889c-826da1709312.png">

2. Modules Marketing Facebook (ps_facebook) and Google (psxmarketingwithgoogle) are correct : ✅ 
<img width="636" alt="Screenshot 2021-12-14 at 17 15 39" src="https://user-images.githubusercontent.com/16019289/146036776-49727139-1aa6-4c71-941f-f88643086882.png">
<img width="792" alt="Screenshot 2021-12-14 at 17 17 19" src="https://user-images.githubusercontent.com/16019289/146037083-8de8807d-7a04-4df2-ae40-3fa96a2e4948.png">

I uninstalled module Facebook and Marketing : ✅ 
<img width="461" alt="Screenshot 2021-12-14 at 17 20 51" src="https://user-images.githubusercontent.com/16019289/146037580-e9190899-5db0-46a3-b267-d9ed4bb2870c.png">
<img width="551" alt="Screenshot 2021-12-14 at 17 21 30" src="https://user-images.githubusercontent.com/16019289/146037721-1ed9ab3e-7e68-482e-9e46-38a5e3355359.png">

Menu Marketing displays an error after uninstallation of ps_facebook and psxmarketingwithgoogle : 🙅 
<img width="895" alt="Screenshot 2021-12-14 at 17 25 11" src="https://user-images.githubusercontent.com/16019289/146038413-633bb9f5-5e7a-451c-a71f-63e0cfd9f1ab.png">

After reinstallation of Facebook and Google Marketing, it works the same way as before : ✅ 

So the issue is just about the Marketing menu after uninstalling Facebook and Google modules, can you confirm ?

Thanks!

**Comment by PeNov** [comment]
Hello Florine2623,

I have these issues:
1)	Newly installed things and modules **use wrong translations in the BO menu**. Each installation of the same module we have **different translation**. It looks like randomly generate translation from old existing translations.
example 1:
![image](https://user-images.githubusercontent.com/38213520/146061841-0b5ae8ae-812b-470e-a474-6d707449ce74.png)
_Emails instead of Maketing, Acces rights (oprávnění přístupu) instead of Facebook, SQL manager (SQL manažer) instead of Google_

example 2:
![image](https://user-images.githubusercontent.com/38213520/146062294-e8d5ac40-92d3-4502-93d3-1567e8fc3dc5.png)
_Emails instead of Maketing, Logs instead of Facebook, Multishops stores instead of Google_

example 3:
![image](https://user-images.githubusercontent.com/38213520/146062584-b8ea991a-d934-452e-8728-4099947ab2db.png)
_Emails instead of Maketing, Teams instead of Facebook, Import instead of Google_

2)	**Is not possible configure Facebook and Google module**. After click on the configuration, we have error: **access denied**.
![image](https://user-images.githubusercontent.com/38213520/146062907-4c185c3b-8387-40d9-a3af-2c9dc6caa0a1.png)

3)	Next issue is **Marketing menu is not removed** after uninstallation marketing modules.

Something must be wrong, what should i check? Where to start?

Thank you
Best regards
PN

**Comment by PeNov** [comment]
Hello Florine2623,

I don’t know if this solution is 100% correct, but this solution works.

Access denied was solved by these SQL query’s:

```
INSERT INTO ps_access(
    SELECT
        1,
        id_authorization_role
    FROM
        ps_authorization_role
    WHERE
        id_authorization_role NOT IN(
        SELECT
            id_authorization_role
        FROM
            ps_access
        WHERE
            id_profile = 1
    )
ORDER BY
    id_authorization_role
)
```

For modules access denied:

```
INSERT INTO ps_module_access(
    SELECT
        1,
        id_authorization_role
    FROM
        ps_authorization_role
    WHERE
        id_authorization_role NOT IN(
        SELECT
            id_authorization_role
        FROM
            ps_module_access
        WHERE
            id_profile = 1
    )
ORDER BY
    id_authorization_role
)
```

I uninstalled and Installed modules Facebook and Google again. Now BO menu contain correct names (Facebook and Google) and I am able access to module configuration.

Problem with wrong translation and Marketing menu after uninstalling modules remains.

Translations for labels marketing and experimental features can be repair manually in the DB table: ps_tab_lang.

Thank you
Best regards
PN

**Comment by hibatallahAouadni** [comment]
Hello @PeNov 

- **First issue:** it's a cache problem, you need to clear your cache:

https://www.awesomescreenshot.com/video/6607071?key=d83cf87abdc6132d9a8d747aa56fc4b0

- **Second issue:** you need to check the issue with Addons team (Facebook's developers & GoogleMarketing's developers)
- **Third issue:** when you uninstall the module, you need to check this option:

![image](https://user-images.githubusercontent.com/23308427/147471271-dcc74d47-9843-4086-b1b6-475ea5e28631.png)

Then, the GoogleMarketing will be removed from the menu:

![image](https://user-images.githubusercontent.com/23308427/147471224-04c2e2e5-9a83-4b2d-923c-ebe43ceecce5.png)

I see no issue here, so I close this issue.

Thanks for your understanding :pray:
