### ISSUE TITLE
delete gamification module on v 8.0

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#27025]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

will the gamification module be removed from prestashop? 
Since everything related to prestashop links is being eliminated, will this module also be eliminated from open source?
@matks

### Steps to reproduce

...

### PrestaShop version(s) where the bug happened

1.8

### If your bug is related to a module, specify its name and its version

gamification

**Comment by matks** [comment]
@alfonsolr09 Gamification module is being pushed inside new shops at install process.

The "push modules on install" process also install modules like ps_checkout or ps_facebook. The "push modules on install" process will be removed from PrestaShop 8 so gamification, ps_checkout, ps_facebook, all of them will be gone :)

I close this issue because it's already fixed 😝 . If you want to see try installing a shop using `develop` branch: no gamification!

**Comment by alfonsolr09** [comment]
Okay, so what are the modules that will come installed by default?

Also, is there any tutorial to install the develop branch, I tried to do it once but the styles were not loaded

**Comment by matks** [comment]
> Okay, so what are the modules that will come installed by default?

The modules that are part of this list https://github.com/PrestaShop/PrestaShop/blob/develop/composer.json because they are part of the project and do not belong to the company.

> Also, is there any tutorial to install the develop branch, I tried to do it once but the styles were not loaded

https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/contribute_using_localhost/

You probably did not apply the step "Compile assets"

**Comment by alfonsolr09** [comment]
Okay, I'll try. thank you very much matks

**Comment by alfonsolr09** [comment]
For existing stores, will there be any option when updating to eliminate the modules that would not be in a new installation?

**Comment by matks** [comment]
> For existing stores, will there be any option when updating to eliminate the modules that would not be in a new installation?

I'm not sure but I dont feel safe building a feature that remove modules on shops... sounds like a dangerous move. I dont want the code to delete a module that the merchant needed by mistake 😅  isn't it easier for merchants to clean their shops by themselves? At least they 100% control what they remove

**Comment by alfonsolr09** [comment]
they can be removed by the merchant, but we need a list of the modules that will be native
