### ISSUE TITLE
Wrong calculation in cart page?

### ISSUE THREAD

**Issue by saulbarros** [PrestaShop/PrestaShop#27024]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi guys I have been testing with 1.7.7.2 and also with the live version shown at https://demo.prestashop.com/#/en/front  and I don't understand why If I add to cart for example 36 x Hummingbird printed sweater (€43.08 -20%  -> €34.46) In the cart is giving a total of €1,240.70 instead of  €34.46 x 36 units  = €1,240.56 this will give me errors with invoicing software. 

Any clue? Could this be a bug? 

![image](https://user-images.githubusercontent.com/38511029/146680872-9114b022-40f5-4d58-8f3e-5cf65ffae210.png)

### Expected behavior

€34.46 x 36 units  = €1,240.56 

### Steps to reproduce

1. Go to 
2. Add to cart 36 units of product  HUMMINGBIRD PRINTED SWEATER
3. Go to cart 

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @Pandazul 

Let me explain it:

1. So the original price of the product is: **`43.08`**
2. With discount **`(-20%): 34.464`** and it will be dispalyed: **`34.46`** but it will be calculated as **`34.464`**
3. While in **General** Prefrences, the **Round type** is setted on **Round on each line**:

![image](https://user-images.githubusercontent.com/23308427/146746279-1182c49a-6600-4c74-a9ed-3087a3bce99d.png)

**`34.464 * 36 = 1240.704`** and it will be displayed as **`1240.70`** => **Correct**

---
Now, if we change the **Round type** to **Round on each item**:

![image](https://user-images.githubusercontent.com/23308427/146752134-4853b87f-f1aa-4548-8bd2-08471cc1f586.png)

Then, we get the result that you want:

![image](https://user-images.githubusercontent.com/23308427/146752218-cb5bbdb9-da00-46df-962d-4205af846161.png)

Because, the product price with discount is **`34.464`** and it will be calculated as **`34.46`**
So, **`34.46 * 36 = 1240.56`**

Closing the issue as it's not a bug :wink: 
Thanks!
