### ISSUE TITLE
Display issue for the polish language and the search bar

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#27077]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The search bar cannot show an entire phrase translated in Polish because of the unnecessary padding

![image](https://user-images.githubusercontent.com/2137763/147276441-18300a26-87df-425a-a690-ff6b1a0b1f17.png)

### Expected behavior

Search bar displayed properly :-)

### Steps to reproduce

1. Install polish language
2. See front office and the display issue

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

ps_searchbar

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

I did not manage to reproduce this issue while testing on develop & 178x branch using the steps to reproduce.
develop
https://watch.screencastify.com/v/9EEsvS0B6iiSNoFpKRIC

178x
https://watch.screencastify.com/v/NPJSbbZjPpal86KqeTqp

Can you please provide us more information about screen size, padding?
Maybe it's related to this issue #26569 ?

Please check and feedback!

Thanks!

**Comment by kpodemski** [comment]
Hello @HanaRebaiQA 

I've just checked, and the issue is on the Chrome browser, on Firefox, everything is all right.

Chrome 96.0.4664.110, MacOS, 16" Macbook Pro, but I think it is coming from the Chrome 🤔

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

I reproduce the issue with PS1782, develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/147583056-a808e24f-99bc-43c6-8bd6-979c117ded10.png)

It's not related to Polish language, you just need to put a long placeholder and you will reproduce the issue.
With PS1778, the placeholder overlaps the loop icon:

![image](https://user-images.githubusercontent.com/23308427/147583242-69dafa05-69e0-479e-98e5-d334045da9f2.png)

I’ll add this to the debug backlog so that it’s fixed. Thanks for your PR :tada: 

Thank you

**Comment by Progi1984** [comment]
@kpodemski Needs a module release and a bump in core.

**Comment by Progi1984** [comment]
Release in progress

**Comment by Progi1984** [comment]
Fixed by @matks in #28259.

**Comment by adamus007p** [comment]
@kpodemski  The names of languages are always written with a capital letter. Polish not polish or you are writing about polish something. :)
