### ISSUE TITLE
Last visit column is queried different than in a customer view

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#27121]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the Customer view, the last visit is based on the `connections` table. The Customers list `last_visit` is based on the `guest` table. This is confusing because `connection` properly tracks the latest visit, not a `guest` table.

### Expected behavior

In the customer view and customer list page, the last visit value should be identical (based on the `connections` table).

### Steps to reproduce

1. Create an account
2. Visit your store
3. Log off
4. Visit again from a different browser, etc.

Check that the `last visit` on the customer list differs from the customer view page.

### PrestaShop version(s) where the bug happened

1.7.6+

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

n/a

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

> The Customers list last_visit is based on the guest table.

You mean this table?

![image](https://user-images.githubusercontent.com/23308427/147647041-6a20a06c-6eaa-49d6-8c43-9172088901d4.png)

Well, in this table it's only mentioned the date and one connection :thinking: 
I didn't seem to understand the bug :sweat: could you please provide a screen record :pray: 
Because, I didn't manage to reproduce the issue following your steps:

![image](https://user-images.githubusercontent.com/23308427/147647219-c486945d-a96a-494b-a168-a05b8e0e95c1.png)

---
![image](https://user-images.githubusercontent.com/23308427/147647247-cff3b2aa-bf0e-4c10-a141-e1fe4cfa0ad1.png)

Please check and feedback.
Thanks!

**Comment by kpodemski** [comment]
@hibatallahAouadni it's about the customer lists, and "Last visit" column, try to visit the store a few times. Eventually, you should see a different value in the "Last visit" in the customer view and the customer list

**Comment by kpodemski** [comment]
@hibatallahAouadni weird, I cannot reproduce it now on the clean installation 🤷 even tho the query to get the last visit is different in these two places, maybe it's related to some DB cleaning I did on the installation when I had this error

**Comment by hibatallahAouadni** [comment]
Well :sweat_smile: Glad to hear :grin:
