### ISSUE TITLE
getimagesize(): SSL operation failed with code 1

### ISSUE THREAD

**Issue by harman-jack** [PrestaShop/PrestaShop#27124]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A Warning is displayed when try to download pdf invoice
![ps_git_error_1_1](https://user-images.githubusercontent.com/55911839/147640959-01b14b04-76bb-4a0a-9af7-3b2d06f136d3.PNG)

### Expected behavior

invoice pdf should be downloaded without any warning

### Steps to reproduce

 1. Go To Home >> Your account >> Order history
 2. Click on the invoice PDF

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @harman-jack 

You need to downgrade your PHP version to 7.4 cause PrestaShop 1.7.8.2 is not compatible with PHP 8.0 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).

Besides, I didn't manage to reproduce the issue with PS1.7.8.2, see the attached screen record below:

https://www.awesomescreenshot.com/video/6630514?key=2ce6f218050d8091d7ea25db736c58f2

Please check and feedback.
Thanks!

**Comment by harman-jack** [comment]
hello @hibatallahAouadni 

I have degraded my PHP version but the issue still persists.
Please see the attached screen record below:

https://user-images.githubusercontent.com/55911839/147721299-96d71437-e4ee-4e40-bcc0-95377aa9ff35.mp4

**Comment by Alexandro2000** [comment]
Hi, I had this problem with a my customer. he reason is that php were not able to verify the ssl certificate is related to file certificate authorities file.
For resolve this problem, I had re-recreate ssl certificate and this problem was is resolved.

If the prestashop is installed on a machine linux, advice of install the ssl certificate with certbot.
This is a link for install certbot and create correttly the certificate:
https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-centos-7

Let me know how it goes, bye bye

**Comment by hibatallahAouadni** [comment]
Hello, 

Thanks @Alexandro2000 for your tip :rocket: 
@harman-jack please verify your ssl certificate and apply the solution proposed by @Alexandro2000 above.
I close this issue as it's not related to PS Core.

Thanks!

**Comment by harman-jack** [comment]
Hello, 

Thanks @Alexandro2000 and @hibatallahAouadni for the reply
