### ISSUE TITLE
Prestashop Backoffice problem "ERR_TOO_MANY_REDIRECTS"

### ISSUE THREAD

**Issue by Rosario98sr** [PrestaShop/PrestaShop#27177]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi everyone, I migrated my site from hosting to a server (I did this on 3 other sites without any problem), but when I enter the back office, I can't work on the various functions, for example if I click on products, I get the page with this error. (I attach screenshoot). Can anyone help me
<img width="1728" alt="Schermata 2022-01-03 alle 18 35 42" src="https://user-images.githubusercontent.com/97048444/147961451-3dbd151b-1b67-4124-b8ad-0fda6b47572e.png">
?

### Steps to reproduce

Go to catalogue - Product

### PrestaShop version(s) where the bug happened

1.7.6.5

**Comment by florine2623** [comment]
Hello @Rosario98sr ,

First, for security reasons, please modify your admin folder name.

Second, regarding your issue after migrating your site; have you changed these info in the database ?
- ps_shop_url
- ps_configuration -> PS_SHOP_DOMAIN_SSL & PS_SHOP_DOMAIN

Also, you need to modify the file `config/parameters.php` to match with your own database configuration.

Please check and let me know!

**Comment by mparvazi** [comment]
It's maybe related to SSL certification.
Try to change options in `Shop Parameters > General` for SSL and then clear the browser cache.

**Comment by Rosario98sr** [comment]
> Hello @Rosario98sr ,
> 
> First, for security reasons, please modify your admin folder name.
> 
> Second, regarding your issue after migrating your site; have you changed these info in the database ?
> 
> * ps_shop_url
> * ps_configuration -> PS_SHOP_DOMAIN_SSL & PS_SHOP_DOMAIN
> 
> Also, you need to modify the file `config/parameters.php` to match with your own database configuration.
> 
> Please check and let me know!

Hi, yes of course I have configured as you say

**Comment by Rosario98sr** [comment]
> It's maybe related to SSL certification.
> Try to change options in `Shop Parameters > General` for SSL and then clear the browser cache.

I would like to do so but unfortunately I do not have the opportunity to enter because if I click on shop parameters, the error appears as a photo

**Comment by mparvazi** [comment]
Go to `phpMyAdmin` on server
Try to find `ps_configuration` table
Change the `PS_SSL_ENABLED` and `PS_SSL_ENABLED_EVERYWHERE` values to "0"
Clear browser cache

![Screenshot 2022-01-04 at 11-17-14 localhost localhost develop ps_configuration phpMyAdmin 5 1 1](https://user-images.githubusercontent.com/85633460/148051814-b0db897f-01a0-483a-b858-70a78822ec80.png)

**Comment by Rosario98sr** [comment]
> 

Nothing, in this case, by doing so, the front office does not work either

**Comment by mparvazi** [comment]
![Screenshot from 2022-01-04 12-03-42](https://user-images.githubusercontent.com/85633460/148056435-8254ef71-a967-4c4c-9e20-aa0eca9eda20.png)

**Comment by Rosario98sr** [comment]
yes because I put the configuration back on the database

**Comment by Rosario98sr** [comment]
> ![Screenshot from 2022-01-04 12-03-42](https://user-images.githubusercontent.com/85633460/148056435-8254ef71-a967-4c4c-9e20-aa0eca9eda20.png)

yes because I put the configuration back on the database

**Comment by mparvazi** [comment]
So problem is for Back Office?

**Comment by Rosario98sr** [comment]
> Quindi il problema è per il Back Office?

yes, I manage to enter the backoffice, but trying to interact on the various functions, it leads me to that error

**Comment by mparvazi** [comment]
Something is wrong for `token` in URL.
There is a redirection by `admin_security_compromised`

Normally you should see a page like this:

![Screenshot 2022-01-04 at 12-23-18 Invalid token](https://user-images.githubusercontent.com/85633460/148058742-9fbd80a4-f202-47df-acff-8aa66d80c0de.png)

What is the problem:
Your shop sets to `https://`, but this controller try to redirect in `http://`
Then a loop will be occurred, because there is a rule that convert all your site links from `http://` to `https://`

I think that's why you get this error by browser: `ERR_TOO_MANY_REDIRECTS`

**Comment by Rosario98sr** [comment]
> Qualcosa non va `token`nell'URL. C'è un reindirizzamento da`admin_security_compromised`
> 
> Normalmente dovresti vedere una pagina come questa:
> 
> ![Schermata 2022-01-04 at 12-23-18 Token non valido](https://user-images.githubusercontent.com/85633460/148058742-9fbd80a4-f202-47df-acff-8aa66d80c0de.png)
> 
> Qual è il problema: il tuo negozio è impostato su `https://`, ma questo controller tenta di reindirizzare in `http://` Quindi si verificherà un ciclo, perché esiste una regola che converte tutti i collegamenti del tuo sito da `http://`a`https://`
> 
> Penso che sia per questo che ricevi questo errore dal browser: `ERR_TOO_MANY_REDIRECTS`

yes, as far as I can see there is a problem right there, but I don't get that page. Do you know how I can solve?

**Comment by mparvazi** [comment]
Disable any automatic redirect on the hosting, if set.

Please login with this URL (without token parameter):

`https://magriecostore.com/{your_admin_folder}/`

**Comment by Rosario98sr** [comment]
This is what happens.

https://user-images.githubusercontent.com/97048444/148063016-33f6a798-abc3-4a34-a02c-40b4f263ce08.mp4

**Comment by mparvazi** [comment]
As I see in this video there is different `token` parameters for Product page and Theme page, but it's wrong!

So try to sign-out and clear browser cache completely (Cookies) or even better to use another browser and sign-in again.

**Comment by Rosario98sr** [comment]
> Come vedo in questo video ci sono diversi `token`parametri per la pagina del prodotto e la pagina del tema, ma è sbagliato!
> 
> Quindi prova a disconnetterti ea svuotare completamente la cache del browser (cookie) o ancora meglio a utilizzare un altro browser e ad accedere di nuovo.

nothing not work...

**Comment by ytilotti** [comment]
Same problem today without modification.
Cleared var/cache/prod and problem solved, weird.

Edit : I know why. No more space disk.

**Comment by matteolavaggi** [comment]
I'm reconnecting to this discussion because I have a sudden and destructive problem on my 1.7.8.10 store.

Today, after 2 months from the migration of my store from 1.7.6.9 to 1.7.8.10, I realized that I had left 2 admin folders, the one from the original 1.7.8.10 installation and the one from 1.7.6.9.

Until today, I have always continued to use the 1.7.6.9 admin folder without problems, today I tried to connect by going through the 1.7.8.10 url and everything seemed to work, so I did these 2 things:

1) renamed the 8.10 folder with the name of 6.9
2) deleted the 6.9

from that moment I can no longer access the configuration of the modules and/or the prestashop performance page!

If I try to search for a module, for example amazzingfilter from the module list and press configure I get the error too may redirect.

If I use an old link saved in quick access for the same module instead everything works.

Same goes for almost all the back office functions, I no longer have access to orders!

EVERYTHING COMPLETELY BLOCKED.

I then restored the two folders exactly as they were before, deleted the caches, restarted the php services, restarted the web server --> NOTHING TO DO. My prestashop site is completely unusable. I wonder how it is possible to run into a problem like this just for some urls? How could I solve it?

I deleted the browser's navigation data, tried with another browser, did everything possible and I am with the store blocked for an absurd problem that is not even diagnosable O_O



/security/compromised?uri=https%253A%252F%252Fwww.sixrace.it%252FADMINFOLDER%252Findex.php%252Fsecurity%252Fcompromised%253F&_token=TOKEN

<img width="494" alt="Image" src="https://github.com/user-attachments/assets/845ec24c-40dd-40c8-88dc-72e18ce498b7" />


This is a nightmare. 


i've noticed that link was changed from old to new but i cant really remember if the new 1.7.8.10 work just with the new link structure... btw i cant figure out how is possible this url problem start from scratch and does no go away...


https://old.sixrace.it/ADMIN/index.php?controller=AdminOrders&token=46b87e17d88b6f65ac56df9ed5bedc19

https://www.sixrace.it/ADMIN/index.php/sell/orders/?_token=KJO7VW7ANuji99D64J0_T-gkDS6CEodEpt_BSwcMCng
