### ISSUE TITLE
Profiling cosmetic problems on develop - escaping and unknown spans in queries.

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27209]
### Describe the bug and add screenshots
If you enable profiling in config/defines.inc.php.

**Queries contain escaped < > characters. They cannot be simply copied to SQL client to test.**
![Výstřižek](https://user-images.githubusercontent.com/6097524/148103869-8f0fbc28-4dcf-4048-a58a-f872081a7206.JPG)

**Queries contain some weird spans**
![image](https://user-images.githubusercontent.com/23308427/148252149-fcdae04b-c648-4919-90c7-571bb88bf4b6.png)

### Steps to reproduce
1. Open config/defines.inc.php.
2. Set _PS_DEBUG_PROFILING_ to true.
3. Open any page in FO and go down.

### PrestaShop version(s) where the bug happened
1.7.8.0 & develop

### PHP version(s) where the bug happened
7.4

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I didn't manage to reproduce the issue on develop, see the attatched screen record below:

https://watch.screencastify.com/v/LfP2nWITQQrHGF6dXbSw

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello again,

Thanks for the provided details on Slack, I reproduce the issue on develop, see the attached screenhsot below:

![image](https://user-images.githubusercontent.com/23308427/148250647-f758055a-24bd-4c04-bb6d-3d703b6403eb.png)

Well on **`develop`**, we only see the `&gt` and `&lt`! 
But on **`1.7.8`**, we have the `<span>`, `&gt` and `&lt` in the queries :confounded: 

![image](https://user-images.githubusercontent.com/23308427/148252420-191467d7-912c-4303-a42e-9ad9876b17ef.png)

It's a **regression** on PS1.7.8.0! I’ll add this to the debug backlog so that it’s fixed.
Waiting for your PR :rocket: 

Thank you

**Comment by Hlavtox** [comment]
@hibatallahAouadni Why was this added and removed from regression backlog? It should have been fixed for 1.7.8.x branch no?

**Comment by MatShir** [comment]
My fault, I don't record why it was removed from the patch kanban, mishandling from me

**Comment by kpodemski** [comment]
Fixed on the develop
