### ISSUE TITLE
BO - Customer view page - error when using `actionCustomerGridQueryBuilderModifier` hook

### ISSUE THREAD

**Issue by rsoulard-prolaser** [PrestaShop/PrestaShop#27235]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error occurson Customer view page when using the `actionCustomerGridQueryBuilderModifier` hook to add a field from another table.

### Expected behavior

No error

### Steps to reproduce

1. Install module https://github.com/PrestaShop/demo-cqrs-hooks-usage-module
2. Go to Customer page
3. Click on a customer to go to the Customer view page

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by hibatallahAouadni** [comment]
Hello @rsoulard-prolaser 

Thanks for reporting the issue and creating the PR :rocket: 
I reproduce the issue with PS1782, see the attached screen record below:

https://watch.screencastify.com/v/QaABbgbs3YzJ4tDrEua4

As you can see I didn't reproduce the issue with PS1778, so it's a regression!
I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by Progi1984** [comment]
Fixed by @rsoulard-prolaser in #27236 & Tested by @florine2623
