### ISSUE TITLE
Bad display of scrollbar for sidebar menu in RTL

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27325]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Scrollbar for sidebar menu in RTL is hidden on new-theme pages.

**RTL:**

<img src="https://user-images.githubusercontent.com/85633460/149123733-a1d4449b-41b1-45f5-8b7f-3c2a1a5ea9a8.png" width="500">

**LTR:**

<img src="https://user-images.githubusercontent.com/85633460/149124581-158fcf57-355e-44cf-9114-28f1f756a2a8.png" width="500">

### Expected behavior

It must be displayed at the left side of sidebar-menu.

### Steps to reproduce

1. Go to BO > Orders (Open submenu)
2. Try to wheel inside menu
3. Scrollbar will be displayed at right side with an incorrect width. 

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

Thanks for the issue!
I reproduce the issue with PS1780, PS1783 and develop, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/149174467-c77e59f0-ea64-48b3-9bf7-6d08587348e5.mp4

This issue is a **regression**! as I didn't reproduce it with PS1778.
I’ll add this to the debug backlog so that it’s fixed. Waiting for your PR :rocket: 

Thank you!

**Comment by mparvazi** [comment]
@hibatallahAouadni 

Very good idea to upload screen-record with GitHub :ok_hand:

**Comment by Progi1984** [comment]
Fixed by @mparvazi in #27333 and tested by @marwachelly
