### ISSUE TITLE
Module Description gives "missing" Translation issue

### ISSUE THREAD

**Issue by Juiliard** [PrestaShop/PrestaShop#27351]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Module description text: "Get notified directly on your browser tab each time you get a new order, customer or message." , see screenshot, is not appearing anywhere for translation to other languages, but is probably referred as "missing" translation in International>Translation>installed modules translation section, even in English, see screenshot.
This also gives error in Symphony, see another screenshot
<img width="1341" alt="Снимок экрана 2022-01-13 в 23 26 40" src="https://user-images.githubusercontent.com/58143423/149418823-f43438b3-7dd5-496f-aebc-dd03ad15995d.png">
<img width="1347" alt="Снимок экрана 2022-01-13 в 23 29 36" src="https://user-images.githubusercontent.com/58143423/149419146-7ae908aa-0e30-43fb-92cf-6a9197ee3ed0.png">
<img width="1359" alt="Снимок экрана 2022-01-13 в 23 32 31" src="https://user-images.githubusercontent.com/58143423/149419487-c89a7539-ff95-46bd-93bc-7013437c0c8b.png">

### Expected behavior

text is translatable and no translation error in Symphony

### Steps to reproduce
>Edited by Khouloud

1. Enable Debug mode
1. Go to BO > International > Translations page 
2. Choose a module 'Order Notifications on the Favicon' to translate
3. Search for this expression: `Get notified directly on your browser tab each time you get a new order, customer or message.` => No expression
4. In the Path `/PrestaShop/Modules/Ps_faviconnotificationbo.php` => it is well displayed

That's why we have a warning
https://user-images.githubusercontent.com/16067358/149479984-3329c17a-e66c-4e0d-8840-3576535d1e59.mp4

---------------------------------------------

1. Debug mode
2. Translation errors in Symphony
3. International>Translation>installed modules translation of English: cannot find any missing string, while it is shown that there is one
(see screenshots above)

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Order Notifications on the Favicon v2.1.1 / ModulesFaviconnotificationboAdmin

**Comment by khouloudbelguith** [comment]
Hi @Juiliard,

Thanks for your report.
In fact, I found another problem.

1. Go to BO > International > Translations page 
2. Choose a module 'Order Notifications on the Favicon' to translate
3. Search for this expression: `Get notified directly on your browser tab each time you get a new order, customer or message.` => No expression
4. In the Path `/PrestaShop/Modules/Ps_faviconnotificationbo.php` => it is well displayed


That's why we have a warning.
Could be you please check and feedback.

https://user-images.githubusercontent.com/16067358/149479984-3329c17a-e66c-4e0d-8840-3576535d1e59.mp4

Thanks!

**Comment by Juiliard** [comment]
1. Hi. Yes, this is exactly what I meant - the text from module "Description" filed `   $this->description = $this->l('Description of my module.');`  is missing from the translation strings.
2. I have checked file  /PrestaShop/Modules/Ps_faviconnotificationbo.php - in line 49 I have also this expression available:
`$this->description = $this->trans('Get notified directly on your browser tab each time you get a new order, customer or message.', [], 'Modules.Faviconnotificationbo.Admin');`
3. And I have also checked  other modules - the missing translation error has each module which has "description" field populated.  It might be a Prestashop issue though, see Welcome module for example which was recently updated.
<img width="1363" alt="Снимок экрана 2022-01-14 в 12 09 18" src="https://user-images.githubusercontent.com/58143423/149506045-0005b847-1fc5-415e-93e7-4fa4422c2328.png">
<img width="1385" alt="Снимок экрана 2022-01-14 в 12 11 05" src="https://user-images.githubusercontent.com/58143423/149506321-1fe01cdd-5ed1-4972-9590-5782609e1fb2.png">
<img width="1668" alt="Снимок экрана 2022-01-14 в 12 14 04" src="https://user-images.githubusercontent.com/58143423/149506669-c0fcba71-3291-4b01-8121-c30a84059454.png">

**Comment by khouloudbelguith** [comment]
@Juiliard, thanks for your feedback.
About the `Order Notifications on the Favicon`, it is a regression module.

- I checked with PS1778 + `Order Notifications on the Favicon` v 2.1.0 => no missing translations
- I checked PS1778 + `Order Notifications on the Favicon` v2.1.1 => there is missing translations

So I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.


https://user-images.githubusercontent.com/16067358/149520732-39f16bf2-39ef-4d0a-9889-580106686265.mp4


For the welcome module could you please create a new issue?
Related to https://github.com/PrestaShop/PrestaShop/issues/17810
https://github.com/PrestaShop/PrestaShop/issues/9697

Thanks!

**Comment by florine2623** [comment]
This issue is present for any native module.

https://github.com/PrestaShop/PrestaShop/issues/30085
