### ISSUE TITLE
Addresses are not saved after update

### ISSUE THREAD

**Issue by fritaasd** [PrestaShop/PrestaShop#27369]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

i am looking for help with a problem. Adresses are not storing in frontoffice. I cant add new address in checkout. After fully filling form in checkout and clicking next the site is refreshing and not going to the next step. Also i cant add or change address in MyAccount > Addresses. After confirming i dont see any changes in DB. I can change addresses only in backoffice Customer > Addresses. Problem is the same on classic theme. 

### Steps to reproduce

After update from 1.6 to 1.7.8.2

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment]
Hello @fritaasd 

I didn't manage to reproduce the issue with PS1.6.1.20 upgraded to 1.7.8.2, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/149748673-f7664605-4332-4b18-8046-913fe6d8a9a3.mp4

Please check and feedback.
Thanks!

**Comment by fritaasd** [comment]
Have you got idea where can i find the problem?

**Comment by hibatallahAouadni** [comment]
Hello @fritaasd 

I think it will be better if you disbale every module (or overrides) may impact on Addresses, then check if you still encounter the issue. By the way these options `Disable all overrides` & `Disable non PrestaShop modules` in BO are not working (check the issue #9965).

I have to close the issue cause it's not PS Core bug.
Otherwise, you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
