### ISSUE TITLE
Anchor links for image slider are incorrectly formatted

### ISSUE THREAD

**Issue by JoryHogeveen** [PrestaShop/PrestaShop#27399]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The `ps_imageslider` plugin adds `http://` as a prefix for anchor links (starting with `#`). This is incorrect and results in blank pages.

### Expected behavior

Do not prefix anchor links.
Might be best to make links optional but that is a different issue.

### Steps to reproduce

1. Create an image slider with anchor links as URL's
2. Click image
3. Witness the blank abomination

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_imageslider

**Comment by hibatallahAouadni** [comment]
Related to #18536

**Comment by hibatallahAouadni** [comment]
Hello @JoryHogeveen 

Thanks for reproting the issue and for your PR :rocket: 
I reproduce the issue with PS1782 and develop, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/150325385-f5cc0b99-6422-4585-a3f8-e21af3ddbaee.mp4

I’ll add this to the debug backlog so that it’s fixed.

Thank you
