### ISSUE TITLE
As a user, I should be able to download/access my uninstalled/deleted modules from the module manager list.

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#27427]
All the native module and non-native module can upgrade from the Modules and Updates lists on the Module Manager.

The Modules list on the Module Manager can be expanded with module to be installed. 

Even if a module is completely removed and uninstalled, the module will be present on the module list with module info and the installation button.

### Feature status

- [x] Module manager PR https://github.com/PrestaShop/PrestaShop/pull/27632
- [x] Module that uses Distribution API https://github.com/atomiix/ps_distributionapiclient
  - [x] Latest changes to finish 
  - [x] need https://github.com/PrestaShop/.github/pull/2
  - [x] then transfer to PS org
- [x] Distribution API v0
- [x] Distribution API v1 : need @atomiix and @djodjo3
  - [x] need https://github.com/PrestaShop/psssst/pull/8

**Comment by Hlavtox** [comment]
Sooo, just restore the functionality from 1.6 😁🤪

**Comment by MatShir** [comment]
@Hlavtox kinda ;) The feature is available from the Marketplace Module. But now, we want to make it native, so everyone can beneficiate from it

**Comment by prestascott** [comment]
Hello everyone,

Thank you @MatShir for your request!

We currently have 2 module status:
- Downloaded module
- Downloaded + installed module

A new module status will definitely be created:
- Visible module, but not downloaded or installed

The users will be able to access the module and download + install it all at the same time. They can't just download the uninstalled/deleted module from the module manager list.

----
### Design

Here is my design mockup:
<img width="1014" alt="Frame 133" src="https://user-images.githubusercontent.com/54888056/152166866-90c8bf70-9cd3-4acc-a3b1-304a7e1e5f09.png">

Explanations:
- To keep consistency in the back office, checkboxes are moved to the left side of the table.
- To avoid misunderstanding with the primary button and the enabled/disabled status of the module, I added a new column where users can easily enable or disable the module they want. It's better for users because they can immediately see if the module is activated or not. If a module isn't downloaded or installed yet, the toggle is on by default but in the disabled state.
- The button group is now separated into 2 different buttons: for the primary action, and for more actions. The icon has also changed.
- The content of the new button for the visible module is "Download and install" with an icon already used in the back office in order to be transparent and consistent as much as we can. 
- The "Uninstall" button becomes red because it means a dangerous action.

Wdyt?

**Comment by Julievrz** [comment]
The wording on Scott's design is the right one. ☺️ The translation domain to use is Admin.Modules.Feature

**Comment by matks** [comment]
Status update

- [x] Module manager PR https://github.com/PrestaShop/PrestaShop/pull/27632
- [ ] Module that uses Distribution API https://github.com/atomiix/ps_distributionapiclient
  - [ ] Latest changes to finish 
  - [x] need https://github.com/PrestaShop/.github/pull/2
  - [ ] then transfer to PS org
- [x] Distribution API v0
- [ ] Distribution API v1 : need @atomiix and @djodjo3
  - [x] need https://github.com/PrestaShop/psssst/pull/8
