### ISSUE TITLE
JSON output of WebService does not return datas of ressource

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27465]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you use the WebService and get the schema or describe a ressource, the XML is populated with the needed datas.

As exemple, the /api/customers/1 will let you see this part:

```
<lastname>
    <![CDATA[DOE]]>
</lastname>
<firstname>
    <![CDATA[John]]>
</firstname>
<email>
    <![CDATA[pub@prestashop.com]]>
</email>
```

Once you ask to deliver the output as JSON format, the return content is missing every datas.

The previous call give you this:

```
{
    "customer": []
}
```

### Expected behavior

Expected that JSON output will give you same datas, in JSON format.

### Steps to reproduce

1. Enable the webservice
2. Describe the ressource /api/customers/1
3. Do the same with the Output-Format set to JSON as HTTP Header.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0.14

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

YEP, it's a regression on develop!
I only reproduce the issue with develop, see the attached screenshots below:

- `develop` with `&output_format=JSON` :x: 
![image](https://user-images.githubusercontent.com/23308427/151137532-246ae629-2071-40a3-b936-faf3b09540b6.png)
- `develop` without `&output_format=JSON` :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/23308427/151137675-eb425057-f45f-4b49-bb17-1ca9cf792289.png)

While with PS1782, it works with `&output_format=JSON`:

![image](https://user-images.githubusercontent.com/23308427/151137942-285ff1b2-1e77-4f22-8222-02abbe4d3be8.png)

I’ll add this to the debug backlog so that it’s fixed.
Thanks for reporting the issue and waiting for your PR :rocket: 

Thank you
