### ISSUE TITLE
Multistore  checkbox & drop-down is not compatible with MaterialChoiceTableType::class 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#27540]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The new multistore  checkbox & drop-down  is not compatible with MaterialChoiceTableType::class

### Expected behavior

Make it compatible with : MaterialChoiceTableType::class and all other multiple choices 

### Steps to reproduce

Fork [this branch](https://github.com/okom3pom/PrestaShop/tree/geolocalization-multi-store)
Install a shop
Enable multistore and add an url 
Go to Localization -> Geolocation

![Capture d’écran de 2022-01-31 08-36-11](https://user-images.githubusercontent.com/5064590/151755212-57c87a18-c763-461d-8b1f-08ffab5358a7.png)

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

I didn't manage to reproduce the issue with develop, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/151895703-e0163540-4201-4d40-aecc-8d388dcab702.mp4

Did you update your develop? or is there a missing step?
Please check and feedback.

Thanks!

**Comment by ghost** [comment]
Oups i forgot a step : 

- Fork [this branch](https://github.com/okom3pom/PrestaShop/tree/geolocalization-multi-store)  or use [this PR](https://github.com/PrestaShop/PrestaShop/pull/27538)
- Install a shop
- Enable multistore and add an url
- Go to Localization -> Geolocation

**Comment by HanaRebaiQA** [comment]
Hello @okom3pom 

Thanks for your report!
I was able to reproduce the issue using the steps that mentioned above : 

1. Install this [PR](https://github.com/PrestaShop/PrestaShop/pull/27538) 
2. Install a Shop
3. Enable multistore 
4. Add a new shop with an url
5. Go to BO > IMPROVE > International > Localization > Geolocalization 
6. See error ==> An exception is thrown
![image](https://user-images.githubusercontent.com/92912932/152520114-cc78b704-0f09-4520-b4fb-679c124aa73c.png)

https://user-images.githubusercontent.com/92912932/152520284-08167cd6-cd0e-4bc6-af2c-d8eb5498012f.mp4


So the issue is related to this [PR](https://github.com/PrestaShop/PrestaShop/pull/27538) since it's not present on develop fresh install!

I’ll add this to the debug backlog so that it’s fixed.
The Developer Team will take it into consideration for future developments.


Thank You!

**Comment by HanaRebaiQA** [comment]
Hello @matthieu-rolland About this issue: I want to validate with you if it's related to his PR or if it's a bug that his PR makes appear but which is not related. 
It will be corrected in the PR If it is directly linked to his PR
Else, it's a regression ! 

What do you think ?

Thank you!

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers friendly reminder :wink: Could someone answer @HanaRebaiQA question.
Thanks in advance :pray:

**Comment by matthieu-rolland** [comment]
hello ! 

Other multistore configuration forms don't behave like this, it looks like it is related to this form precisely, and should be fixed in this PR 👍

**Comment by HanaRebaiQA** [comment]
Thank you @matthieu-rolland for your feedback !

Hello @okom3pom, according to @matthieu-rolland  response, this issue should be fixed on your PR.
So, i close this issue.

Thanks!

**Comment by matthieu-rolland** [comment]
I talked with @okom3pom and it seems like it's not related to his PR, but it still keeps his PR from getting merged...

So I re-open it and assign it to myself 👍

**Comment by matthieu-rolland** [comment]
fixed in this PR #27700
