### ISSUE TITLE
modules are deleted when 1-click upgrade is done

### ISSUE THREAD

**Issue by nexustotalsolutions** [PrestaShop/PrestaShop#27561]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I'm a contributor on the Prestashop addons store with few modules. And there are 2 very popular payment modules on mine which are considered as not compatible from Prestashop 1.7+ version. There is only one issue that the module gets auto deleted from the FTP while 1-click upgrade done on Prestashop with statement of non-compatibility.

Before I came to post this issue here, I got the answer from the Prestashop addons validating team that these bugs are due to the core.
My payment modules are:
https://addons.prestashop.com/en/product.php?id_product=17856
https://addons.prestashop.com/en/product.php?id_product=19407

Other then this, there is no issue present in the modules related with any PS 1.7+ non-compatibility.
There are lots clients who reported these issues but I can no more ignore this issue now.

Best Regards,
Dev

### Steps to reproduce

1. Do install my module.
2. Do 1-click upgrade and see the error.

### PrestaShop version(s) where the bug happened

1.7+

### If your bug is related to a module, specify its name and its version

stripejs v4.3.9, stripepro v6.2.4

**Comment by hibatallahAouadni** [comment]
Hello @nexustotalsolutions 

Thanks for reporting the issue!
Ping @PrestaShop/product-team & @eternoendless is deleting the no-native module whom are not compatible with PS1.7 while upgrading from PS1.6 to PS1.7 the expected behavior? or is it a bug?
Waiting for your confirmation :pray: 

Thanks in advance!

**Comment by eternoendless** [comment]
To the best of my understanding, non-compatible modules are meant to be _disabled_, not deleted.

**Comment by nexustotalsolutions** [comment]
Hello @hibatallahAouadni,

You mentioned that the issue is "when upgrading from PS 1.6 to 1.7" which is not what I meant.
The issue is when 1-click upgrade is done on any version of PS 1.7. 

PS: It's not related with PS 1.6.
Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @nexustotalsolutions 

>  And there are 2 very popular payment modules on mine which are considered as not compatible from Prestashop 1.7+ version.

When you mentioned that your modules are considered as not compatible from Prestashop 1.7+, so I understand that you encounter this problem when you upgrade from 1.6 to 1.7.

So, could you please specify from which version did you upgrade and if your modules are not compatible to PS 1.7, then how/why do you think there will be no issues with with your modules?

Please provide as much as you can details to understand better the issue.
Waiting for your feedback.

Thanks!

**Comment by nexustotalsolutions** [comment]
Hello @hibatallahAouadni,

It does happens in case when we do upgrades within PS 1.7.
I got many messages from my clients and Yesterday also one client reported that he gets this error after upgraded from 1.7.8.2 to 1.7.8.3.

Thank you.

**Comment by stephR** [comment]
I have this module. Each time I upgrade through 1-ClickUpgrade with last prestashop versions, I have this bug. 
"Stripejs has been removed from your ftp". And all positions in the hooks are deleted too. So when I re-upload the module, I need to add positions on hooks again, manually...

**Comment by AlexAlexE** [comment]
/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php line 94

```
$modules_to_delete = array(
                'backwardcompatibility' => 'Backward Compatibility',
                'dibs' => 'Dibs',
                'cloudcache' => 'Cloudcache',
                'mobile_theme' => 'The 1.4 mobile_theme',
                'trustedshops' => 'Trustedshops',
                'dejala' => 'Dejala',
                'stripejs' => 'Stripejs',
                'blockvariouslinks' => 'Block Various Links',
            );

```
Why? It's a full compatible module: https://addons.prestashop.com/ru/payment-card-wallet/17856-stripe-payment-pro-sca-ready.html

Look at this: https://github.com/PrestaShop/autoupgrade/pull/44#issuecomment-290011291
You repeated error from 2016 :)

**Comment by MatShir** [comment]
@AlexAlexE @nexustotalsolutions It seems you have identified the issue. I don't know why the upgrade module remove this module in particular. 
If the issue affects your client and your business and if you have the technical knowledge, don't hesitate to propose a pull request ([find more information here](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/)). PrestaShop is an open-source project, we will be happy to review your contribution to the PrestaShop core.

**Comment by nexustotalsolutions** [comment]
@MatShir @hibatallahAouadni Yes Prestashop is an open source for merchants but they are taking 40% commission from each module sales.
At this commission rate if they can't provide a good support and still expecting from developers to fix their own issues then it's a very bad approach. 
Individual developers do contribute in Prestashop at various levels. But their business model is suppressing us and giving room for big contractors. We as developers are already disappointed from their commissions.

**Comment by MatShir** [comment]
Hello @nexustotalsolutions, 
I totally understand your frustration. My point was not so much to say that the problem is your problem. If a bug harms PS and its community, of course we will fix it at some point. But the difference is that if you are users who are facing the issue, you know how to fix it, test it and check that everything works fine. You will go much faster and the bug will be solved faster than done by us. 
We will see where we can put your issue on the backlog. You can see the current plan for the next autoupgrade release https://github.com/PrestaShop/PrestaShop/issues/25647

**Comment by nexustotalsolutions** [comment]
@hibatallahAouadni @MatShir, After 4.5 months of time, still you're not able to delete some lines of code.

**Comment by matks** [comment]
> @hibatallahAouadni @MatShir, After 4.5 months of time, still you're not able to delete some lines of code.

As said by @MatShir : we will not take care of this issue unless it's considered a high priority on our side.

Does the issue affects your client and your business? If yes, you must go forward and explore then submit a bugfix Pull Request for the project. Instead of waiting for PrestaShop company to fix issues, you can invest into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

If this issue is important for you, you must take action to get it fixed. This is how an open source project works.

**Comment by darkf3d3** [comment]
So there's no chance that this will be fixed?
I think an issue like this should be considered an high priority?

**Comment by nexustotalsolutions** [comment]
Issue has been resolved. Thank you everyone.

**Comment by MatShir** [comment]
Thanks @nexustotalsolutions 🥳
