### ISSUE TITLE
Products of a sub-category to which I do not have access are visible

### ISSUE THREAD

**Issue by bibips** [PrestaShop/PrestaShop#27601]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On a category page, I can see products for which I don't have access

![image](https://user-images.githubusercontent.com/6272184/152646275-2ca43066-a86e-4136-a6b0-d1a6f5ab5d2c.png)

What I see when I go to the product page
![image](https://user-images.githubusercontent.com/6272184/152646231-070fbef3-976f-45eb-8c3e-a3263be199ca.png)

### Expected behavior

If I do not have access to a product, it should not be visible on the listing

![image](https://user-images.githubusercontent.com/6272184/152646011-3d9c8447-bcac-448d-92d5-db10b1a1148a.png)

### On Administration
1. On category " Vêtements", go to sub-category "Hommes" and set access only to groups "Client" (Customer)
2. Create a product "test" with **only** the category "Hommes"
### On store
1. Go to the category "Vêtements"
2. Sub-category "Hommes" isn't display but you can see the produt "test"

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.26

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @bibips 

> On category " Vêtements", go to sub-category "Hommes" and remove access to all groups

You're not allowed to leave this field empty, check the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/152890350-67beff8f-ebf6-4765-a323-de07d67b5d24.png)

But if you disable the category Men while you associated the product only with this category, then the product will be not displayed. See the attached screen record below:

https://user-images.githubusercontent.com/23308427/152895665-2a5f5b31-a959-4224-a6ed-c359e5a84dbb.mp4

For the **Hummingbird printed t-shirt** product, it's well displayed cause it's associated to other activated categories like **Home** and **Clothes**, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/152895618-0c6d433e-8102-435f-bcab-fd35e92f4f33.png)

Closing the issue as it's not a bug.
BTW, we will respond to your questions (if you have) even when the issue is closed :wink: 

Thanks!

**Comment by bibips** [comment]
Hello @hibatallahAouadni,

Thanks for your response, I've updated the description of the issue like this :

> 1. On category "Vêtements", go to sub-category "Hommes" and set access only to groups "Client" (Customer)

I agree with you when you said 
> For the Hummingbird printed t-shirt product, it's well displayed cause it's associated to other activated categories like Home and Clothes, see the attached screenshot below:

That's why I had precised :

> 2. Create a product "test" with only the category "Hommes"

I don't want to disable a category : I want to authorize to product "test" only to user from specific group.

As you can see in the bellow recording, the product **T-shirt imprimé colibri** belongs only to category **Hommes** and category **Hommes** can only be visible by group **Client** (Customer). So it's not normal to see this product when you are on the category **Vêtements** and you are not logged.


https://user-images.githubusercontent.com/6272184/152949873-f5d3d177-cc94-4d43-8b65-b0f1bc53c5a4.mp4

**Comment by florine2623** [comment]
Hello @bibips ,

Indeed I have reproduce your issue.
The product "test" should be visible in the listing and a product page only when a customer is logged in.
Can you confirm ?
Thanks!

**Comment by bibips** [comment]
Hello @florine2623,

thanks for the re opening and yes I confirm

**Comment by hibatallahAouadni** [comment]
Hello @bibips 

Could you please confirm that you encounter this issue even with older PS version :pray: 
Waiting for your feedback.

Thanks!

**Comment by florine2623** [comment]
@hibatallahAouadni ,

PS 1.7.7.8 + ps_facetedsearch v3.7.0 => nok
PS 1.7.8.4 + ps_facetedsearch v3.7.0 => nok

PS 1.7.7.8 + ps_facetedsearch v3.7.1 => nok
PS 1.7.8.4 + ps_facetedsearch v3.7.1 => nok

It is not a regression ^^
