### ISSUE TITLE
[BO]Cannot edit or insert a category product in 1.7.8.3

### ISSUE THREAD

**Issue by tone87** [PrestaShop/PrestaShop#27603]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

error 👍 
Unexpected character "'" in __string_template__4995ee5449ec4239b268b37f57db3c9558311a0cf788e029d52d2ee5c334b1e6 at line 1.

### Expected behavior

Controller->render()
in [src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php] line 320

`''contextLangId' => $this->getContextLangId(),
'editCategoryForm' => $categoryForm->createView(),
'editableCategory' => $editableCategory,
'defaultGroups' => $defaultGroups,
'categoryUrl' => $this->get('prestashop.adapter.shop.url.category_provider')
->getUrl($categoryId, '{friendly-url}'),            ]        );    }    /**`

### Steps to reproduce

This error is happend when you tray to create or edit a product category

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.2

![bug_category](https://user-images.githubusercontent.com/8173557/152652905-f89a3ad2-999e-46f7-bb63-ad3c54abfc9e.png)

**Comment by hibatallahAouadni** [comment]
Hello @tone87 

I didn't manage to reproduce your issue with PS1783, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/152883401-66fd3741-0201-4543-8bbe-9f1daaead932.mp4

It seems that your issue is not a PrestaShop core bug.
We will close this issue.

Thanks!

**Comment by PrestaEdit** [comment]
Hi,

To inform you, I can reproduce this issue but is with a third party module.
It could occurs with others, when you try to use Smarty template (legacy hooks) into a modern controller (Twig template) due to recent escaping made on the 1.7.8.3.

I was not yet able to resolve my own issues, I will let you know how it's need to be handled, if possible.

**Comment by mrports** [comment]
hi 
im also suffering from this bug, i first noticed it after i updated to 1.7.8.3 when i wanted to edit a cms page, then happened again when i wanted to edit a brand title and today the product's editing page fall apart ...seems its getting worst every passing day

any quick solution? please

**Comment by roncarino** [comment]
Yep,
we are having this problem too and I have the feeling that a few modules can be affected by this. It seems quite serious honestly.

**Comment by a-suez** [comment]
Same problem here with critical module for us, plsease help

**Comment by tone87** [comment]
if someone know the name of the related module can publish the name here ? thanks

**Comment by PrestaEdit** [comment]
> if someone know the name of the related module can publish the name here ? thanks

It's not only a module, it could be one or another, depending your your modules catalog and the page where you try to edit something.

**Comment by tone87** [comment]
for me the problem it's related to core and not to a module, anyway for now it's not solved

**Comment by tone87** [comment]
Founded the module !!!! Jscomposer create a bug, when it's disables not reproduce the error

**Comment by roncarino** [comment]
> Founded the module !!!! Jscomposer create a bug, when it's disables not reproduce the error

Yes, sorry. I didn't mention the module involved. JScomposer it is but ...good luck with that.... It always been rubbish.

**Comment by mrports** [comment]
i dont have JScomposer installed but im still getting the same error when i try to edit a cms page, the error from the product editing page is gone despite that i did nothing

**Comment by a-suez** [comment]
In my case is this one: https://addons.prestashop.com/es/transportistas/26558-chilexpress.html desactivated the error disappears.

Regards

**Comment by cmsmartj** [comment]
HOLA BUENAS TENGO MISMO ERROR DESDE QUE SE ACTUALIZO PRESTASHOP 1.7.8.3
MI ERROR PASA CUANDO INTENTO CREAR O EDITAR CATEGORIAS 
![Sin título-1-RecuperadoFF](https://user-images.githubusercontent.com/66569106/153103927-fe86c1b5-2657-4195-9105-911abee40ae6.jpg)
![Sin título-1-Recuperado](https://user-images.githubusercontent.com/66569106/153103929-39432b0f-b901-450b-a90f-1a58bd54751a.jpg)

**Comment by mcasamayor** [comment]
I am also having the same problem after upgrading to 1.7.8.3.

The message appears when I update some products, it does not happen in all cases. I can't find the reason for this error

![image](https://user-images.githubusercontent.com/35779730/153200476-0b105de8-f8f9-4d0c-9b8c-9074ef7c633a.png)

![image](https://user-images.githubusercontent.com/35779730/153201003-25f47e37-ee70-4d38-83e5-96aa6a21423b.png)

**Comment by PrestaEdit** [comment]
There is a solution for all modules having this behavior: using `{strip}{/strip}` to encapsuled their template causing an issue with that.

**Comment by mrports** [comment]
> There is a solution for all modules having this behavior: using `{strip}{/strip}` to encapsuled their template causing an issue with that.

seems like you are the promised savior 🥇 :D

can you please explain to me how i can implement this solution?

**Comment by smartdatasoft** [comment]
> Founded the module !!!! Jscomposer create a bug, when it's disables not reproduce the error

we just release jscomposer new update with this fix. Please check if you found any issue related to composer open ticket our support https://support.classydevs.com
Thank you

**Comment by roncarino** [comment]
> > Founded the module !!!! Jscomposer create a bug, when it's disables not reproduce the error
> 
> we just release jscomposer new update with this fix. Please check if you found any issue related to composer open ticket our support https://support.classydevs.com Thank you

Hi, we tried with version 4.4.27 and we still get the same identical error.

**Comment by matks** [comment]
Hello everyone thank you for all the informations provided here.

As mentioned by @prestamodule it's possible that the security fix https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a introduces a backward incompatible change and consequences would be that some module, that do work as expected with 1.7.8.2, would not work with 1.7.8.3 because we added some more safety.

Unfortunately backward incompatible changes are sometimes needed in order to ensure the project safety 🔓 there was a confirmed vulnerability (reported as https://github.com/PrestaShop/PrestaShop/security/advisories/GHSA-mrq4-7ch7-2465) that was present and 1.7.8.2 and these changes are needed to fix it.

Thank you @PrestaEdit for providing a possible workaround.

If there is a usecase where it is impossible to adapt a module behavior so that it works with both 1.7.8.2 and 1.7.8.3 please report it so that we can analyze it. However unless there is a major drawback, I think we will not revert https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a because security is more important that backward compatibility. The loss of money and reputation caused by a hack is much more expensive and damaging that a module update.

**Comment by matks** [comment]
@tone87 @roncarino @smartdatasoft please have a look at https://github.com/PrestaShop/PrestaShop/pull/27806 ;)

**Comment by PrestaEdit** [comment]
> @tone87 @roncarino @smartdatasoft please have a look at #27806 ;)

Hi @matks ! I just test this change onto an existing 1.7.8.3 with the module that throw the error and... it's still exists, it's seems.

**Comment by mkdgs** [comment]
I facing the same issue on many page of BO after upgrade from 1.7.8 to 17.8.3 
I've a crap fix, sampled, here:
https://gist.github.com/mkdgs/302cb2b56205cbb4b013a79610ea1aa1#file-layoutextension-php-L85
It's around escapeSmarty(...)

I've not noticed this issue after upgrade 1.7.8 to 17.8.2, and after reading the change in the code i think it's related to the security fix. 
It's seem not directly caused by a module (or an override), I've disabled everything and the problem was still present. 
I didn't research further to find the origin of this problem of escapement (the output seems to be correct but generate an error).

I will digging more in few day, if nobody found the source of that problems.

Edit, after looking at #27806 which matches this issue, I switch to it

**Comment by cmsmartj** [comment]
hola buenas tengo mismo problema este problema no se si pueden tener una solución se los voy agradecer, no puedo editar categorias ni modificar ni agregar nuevo 
¡Uy!... parece que ocurrió un error inesperado

Unexpected character "'" in "__string_template__d7cbc8ccf651226dc9bcec2e7e01cc4da86322d95a5b5ae47df5b332bcfe4588" at line 1.

[Twig\Error\SyntaxError 0]

 
![error](https://user-images.githubusercontent.com/66569106/158915733-bda8862f-5375-48f9-aeee-d06693b2a026.jpg)
