### ISSUE TITLE
[BO] Improve UX design for date-picker form

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27621]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is some minor UX bugs in date-picker form.

### Expected behavior

| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/85633460/152975182-c56d306e-f209-405d-9426-6d9ceef70253.png">  | <img src="https://user-images.githubusercontent.com/85633460/152975644-e14f638f-fb95-4605-8f25-520351dbf8c4.png"> |

### Steps to reproduce

1. Go to BO > Dashboard
2. Select drop-down menu in date-picker toolbar.

**Comment by marwachelly** [comment]
Hello @mparvazi ,

Thank you for your report. I think that the behavior described is a bug not a new feature. So could you please add steps to reproduce.

Many thanks,

**Comment by florine2623** [comment]
Hello @mparvazi ,

It is indeed a bug as @marwachelly said.

I reproduced it on PS 1.7.8.x and develop, as well as on PS 1.7.7.x (it was bugged, but looked slightly different). So it is not a regression.

| PS 1.7.8.x & develop  | PS 1.7.7.x |
| ------------- | ------------- |
|<img width="424" alt="Screenshot 2022-02-09 at 18 02 18" src="https://user-images.githubusercontent.com/16019289/153251578-78b58557-2714-458b-94b9-5bdeb4b4dc13.png">|<img width="416" alt="Screenshot 2022-02-09 at 18 02 12" src="https://user-images.githubusercontent.com/16019289/153251605-073b631a-324a-4567-90aa-1d162b0c03f4.png">|


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by mparvazi** [comment]
Hello everyone!

I'm waiting for UX approval to create PR.
IMO it's not a bug, because there is no problem for accessibility.
I think this component needs a redesign.

Ping @prestascott
