### ISSUE TITLE
When Carrier has taxes, Order taxes disappear

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#27654]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If we go to the admin and choose a carrier that has shipping fees and we apply taxes to the shipping fees, then all orders that uses that carrier won't have any taxes but the taxes of the shipping fee

### Expected behavior

If a customer places an order in the website for a product worth 20$ + 5$ shipping, if you have 10% taxes then the total taxes in the order must be 2$ + 0,5$ = 2,5$
This is not the case, what I get instead is a 20$ + 5$ total order value with only 0,5$ taxes.

### Steps to reproduce

1.- Go to Admin -> Carriers choose any carrier that has shipping fees, configure the carrier to apply taxes to those fees and save it.
2.- Then go to the FO place an order for whatever product (of course you need to have taxes enables on the website and applied to all your products ), choose the carrier you've configured previously and validate the order
3.- Go to Admin -> Orders and chez if the order you've just placed has all taxes (product taxes + shipping taxes)

### PrestaShop version(s) where the bug happened

1.7.6

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @omar2886 

I didn't manage to reproduce the issue with PS1767, PS1778 and PS1783, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/153926262-4f253d57-9cdc-4800-a4ef-2486bf9aed12.mp4

It seems your issue is related to some overrides or some third-party modules.
Closing the issue as we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by omar2886** [comment]
Can you PLEASE @hibatallahAouadni tell me where the total taxes of the order is store? because it's not in ps_orders
Thank!

**Comment by hibatallahAouadni** [comment]
@omar2886 you can ask your question here in the [public Slack channel](https://prestashop.slack.com/).
Thanks for your patience!
