### ISSUE TITLE
Webservice image management doesn't handle WebP

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27706]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Inside PrestaShop 8, webP format is enabled but the webservice doesn't manage it as you can see here: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceSpecificManagementImages.php#L140

### Steps to reproduce

1. Add webP image
2. Get it with webservice

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

I think it will be better if we treat this issue as a feature request rather than a bug report.
As you know we have recently integrated WebP :wink: 

So thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.
Can't wait for your PR :muscle: :rocket: 

Thank you

**Comment by Progi1984** [comment]
@PrestaEdit I reopen it. My PR is on QA ;)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/28711
