### ISSUE TITLE
Installation allows an admin email without toplevel-domain but login does not 

### ISSUE THREAD

**Issue by marc-fischer** [PrestaShop/PrestaShop#27740]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The installer allows to create an admin account without a toplevel domain in the email (i.e. admin@localhost), but the admin login does not allow to log in without a top-level domain. 

### Expected behavior

The installation should also require a valid email with extension, if the login requires it. 

### Steps to reproduce

1. Set up docker containers like mentioned here: https://hub.docker.com/r/prestashop/prestashop/
2. Start installation, set up an account admin@localhost
3. Finish installation
4. remove install folder
5. rename admin folder
6. try to log in - the panel throws a use a valid email address error

>Edited by Khouloud

I tried to installed the shops via cli using this command
`php install-dev/index_cli.php --language=en --country=fr --base_uri=1783 --domain=0.0.0.0:8081 --db_server=10.1.55.2 --db_user=root --db_name=ps1783 --db_password=xxx --prefix=sk_ --firstname=demo --lastname=demo --email=admin@localhost --password=123456789 --db_create=1`
![image](https://user-images.githubusercontent.com/16067358/155686660-7db1b307-3608-4790-8e83-80d781e0665b.png)
![image](https://user-images.githubusercontent.com/16067358/155686780-d0f01145-4199-4146-b816-43b468d72a41.png)
**BO**
![image](https://user-images.githubusercontent.com/16067358/155686894-7d587e67-7451-4fdc-a7dc-38a19f527153.png)
![image](https://user-images.githubusercontent.com/16067358/155686980-87391d8f-c8bb-4e1e-8183-aedd68154acf.png)

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by hibatallahAouadni** [comment]
Hello @kartoffelfighter 

Thanks for reporting the issue!
Did you mean that on Docker, you can install with no-valid mail like **`admin@localhost`** and when you try to connect to BO it shows an error. While on local, you can't create/install your shop with invalid mail like **`admin@localhost`**, is that so?
Please check and feedback.

Thanks!

**Comment by marc-fischer** [comment]
Hi @hibatallahAouadni 

I installed on a local testserver the Dockercontainer for prestashop with `admin@localhost` as email. When i wanted to log in to exactly this instance as `admin@localhost` i got an error below the email field, that my email is not valid (missing the top-level, i.e. `.com`). 
I fixed the issue in my mysql-db by changing the email to `admin@localhost.com`, but nevertheless, i think it shouldn't be possible to install but not log in with an email.

**Comment by khouloudbelguith** [comment]
Hi @kartoffelfighter,

I manage to reproduce the issue with PS1783 & PS1778.
I tried to installed the shops via cli using this command
`php install-dev/index_cli.php --language=en --country=fr --base_uri=1783 --domain=0.0.0.0:8081 --db_server=10.1.55.2 --db_user=root --db_name=ps1783 --db_password=xxx --prefix=sk_ --firstname=demo --lastname=demo --email=admin@localhost --password=123456789 --db_create=1`
![image](https://user-images.githubusercontent.com/16067358/155686660-7db1b307-3608-4790-8e83-80d781e0665b.png)
![image](https://user-images.githubusercontent.com/16067358/155686780-d0f01145-4199-4146-b816-43b468d72a41.png)
**BO**
![image](https://user-images.githubusercontent.com/16067358/155686894-7d587e67-7451-4fdc-a7dc-38a19f527153.png)
![image](https://user-images.githubusercontent.com/16067358/155686980-87391d8f-c8bb-4e1e-8183-aedd68154acf.png)

so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by PierreRambaud** [comment]
Unfortunately, `admin@localhost` is not a valid email address.
You misunderstand what `admin@localhost` is. It's `"USER"@"DOMAIN"`, it could be `admin@127.0.0.1` which is not related to the email address (the email address RFC will tell you it's not valid.)
It's the same as the MySQL domain.

We will not fix that as it's not an email address.

**Comment by marc-fischer** [comment]
Hi @PierreRambaud 

I think you didn't understand the problem. 
Of course its valid the admin panel is returning the error, but it's unfortunate that the installer allows installing with parameters, which are invalid for usage. The Installer is missing a validation for the email address RFC.
 
One can install the software without valid credentials and has a bricked installation. Imo, this should be fixed..

**Comment by PierreRambaud** [comment]
Yes, that's why I removed my message :sweat_smile: 
If find the reason why it works and then failed :eyes: 
https://github.com/egulias/EmailValidator/issues/188 

Following the RFC, and after checking the `Validate::isEmail` method, we have a warning which is `RFC5321, TLD` the TLD part is missing and shouldn't be.

**Comment by Jesse-21** [comment]
this is not fixed.  I just tried to install presta from the customer area on ionos.  
It doesnt ask for an email it asks for a username during install and never asks for an email.
if this is why im unable to login to the admin area, then its not fixed.  
I am not sure if this is an ionos change to the install steps or if its part of your fix or an update.

how: on new install

where:  ionos shared hosting using their autoinstall in their customer area

what: only asks for username on install steps and a password,  no email is asked for in the setup steps.
           inputing a username and moving along with install, you cant login to the admin area. on login it asks for an email not username. 

Troubleshooting done: i deleted and reinstalled and follow the exact same steps but paying closer attention to see what possibly caused it.  finding that there is no mention of email in setup and theres no username on login just email.  
figured id let yall know.  its what ionos is instlalling when any customer aut installs your shop
