### ISSUE TITLE
"Out of memory" error while editing the product

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#27928]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

One of my customers uses PrestaShop 1.7.8.3 with PHP 7.4.28 on the IONOS server.
The shop has 50 000 categories and 60 products.
Shop uses currently the default "classic" theme.

When I try to edit products I see the error "Out of memory" when the debug mode is enabled:
https://prnt.sc/1HPEbEMttUnw

and a little diffrent error when the debug mode is disabled:
https://prnt.sc/DkTIapjDMXLW

Screenshot with server configuration:
https://prnt.sc/WorOtHUdtJ9a

I thought that this error is related to the PHP memory limit, so I told my customer to ask the server administrator to change the memory limit, but he got this reply:
"This is a change that IONOS cannot make, it is up to the client to make this client via, for example, your SFTP software.

If Prestashop support cannot tell you in which folder the file concerning PHP information is located, IONOS being an expert in hosting only, I strongly advise you to seek the help of a Webmaster specialized in Prestashop."

I tried to change memory_limit in php.ini, but I still see the same error.

So I have 3 questions:
1.This error is related to the server or it is a PrestaShop bug?
2.Does PrestaShop have any category limit?
3.How much memory is recommended for a PrestaShop with 50 000 categories?

Thank you in advance for the information.

Regards

### Steps to reproduce

.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @Angar90 

I only can share with you my Server information:

![image](https://user-images.githubusercontent.com/23308427/158560992-4cae5407-1074-43fb-92b1-654e1b5a6d44.png)

Sorry but I can't help you because it seems the problem is related to your server configuration :disappointed: 
If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
