### ISSUE TITLE
bug SSL in BO Order

### ISSUE THREAD

**Issue by duongductuan** [PrestaShop/PrestaShop#27929]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

My website has fully installed ssl but for some reason, the following message appear
![Untitled](https://user-images.githubusercontent.com/87248592/158523168-6f5d2dd5-d624-427d-aebf-8a4774da43ca.png)
s

### Steps to reproduce

1. Go to Order BO
2. Check Order

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @duongductuan 

It seems your issue is not related to PrestaShop Core, cause I didn't manage to reproduce the issue with PS1784 + PHP7.4:

![image](https://user-images.githubusercontent.com/23308427/158577253-782946df-33e1-4136-a2ec-af954836d052.png)

Check your SSL certificat still valid or no :wink: 
Sorry but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
