### ISSUE TITLE
Product price currency is false at seller back office order page and invoice pdf 

### ISSUE THREAD

**Issue by rytaf** [PrestaShop/PrestaShop#27950]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Screenshot_20220317-191711_Chrome~2](https://user-images.githubusercontent.com/63957824/158846603-a5b2c6e3-d55c-40b6-8df8-a18dbb63f531.png)
The customer currency appears on the order page instead of the product price in dollars.  The problem is seen in pdf files and order page. 
Normally it should appear as 370 dollars, but it looks 370 lira
The main language of my site is english and the currency is usd
Shopping language and currency variable 

### Steps to reproduce

Customer creates order and the error occurs

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @LordIndustry 

Could you please list clear and concise steps to reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by starqus** [comment]
> Hello @LordIndustry
> 
> Could you please list clear and concise steps to reproduce the issue. Waiting for your feedback.
> 
> Thanks!

The native language of my website is english and the default currency is usd.
Customers pay in different currencies. (Turkish lira)
I enter the product prices in usd default.
There is no problem with the customer during the ordering phase.
After the order is created, currency confusion occurs on the Order page and pdf files, as in the photo.
On the order page, the product price should appear in the currency that the customer pays.
Or the currency should still appear as the base currency instead of the customer's currency and the icon should be fixed.
The price of the product should be 370 dollars, not 370 Turkish Lira.
Or it should appear as 5200 Turkish lira, i think this is better.

**Comment by HanaRebaiQA** [comment]
Hello @LordIndustry 

I tried to reproduce your issue with PS1784 using the same data that you used : 
-English as a native language in my Shop 
-USD as a default currency 
I added many languages as Turkish in my shop, but i can't reproduce your issue.

https://user-images.githubusercontent.com/92912932/158986318-3c011b72-f416-44f1-bb65-4dc1cad97a0d.mp4


![image](https://user-images.githubusercontent.com/92912932/158986199-eec4a72c-cec3-4fb8-8b73-b72c858fdb9f.png)
![image](https://user-images.githubusercontent.com/92912932/158986293-5b918b0c-8f6e-46b0-90be-e53956f67cc3.png)


Could you please check and feedback?

Thank you!

**Comment by starqus** [comment]
Hi @HanaRebaiQA Could you add a different currency and create the order with that currency? For example, euro or lira.

**Comment by starqus** [comment]
I will add detailed information, it does not always occur and is not a critical issue.
