### ISSUE TITLE
Prestashop PHP Requirement

### ISSUE THREAD

**Issue by jameswill** [PrestaShop/PrestaShop#27985]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While creating category in Prestashop 1.7.8.5 gives the following error on PHP 7.1 (refer screenshot attached)

Unexpected character "'" in [__string_template__18493dc0e63d2a4642b126187bbe4bd3fb097a9eff19f534720fbfca1d172637 at line 104](http://[[domain]]/prestashop1785/admin663bk1ulo/index.php/_profiler/open?_token=3BAUVI4iUiUDnroJWK9dJimYnjRWU0p6h1Ry0uiMnZw?file=__string_template__18493dc0e63d2a4642b126187bbe4bd3fb097a9eff19f534720fbfca1d172637&line=104#line104).
![presta1](https://user-images.githubusercontent.com/6368036/159215352-7f3407a3-d31a-4fe0-8d78-29dcc25c5049.png)

Works well on PHP 7.2. Has the MInimum PHP requirement changed ? If yes, Please change here. [https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/](url)

### Expected behavior

Should work all well on PHP 7.1 or requirement should be increased in docs.
[https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/](url)

### Steps to reproduce

1. Install and visit category on PHP 7.1

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by matks** [comment]
> Works well on PHP 7.2. Has the MInimum PHP requirement changed ?

It works on PHP 7.2 and it does not work on PHP 7.1 -> you're going to fast in the conclusion. This does not mean it's a PHP compatibility issue. Different behaviors on PHP versions can hide or show an error 😉 

> While creating category in Prestashop 1.7.8.5 gives the following error on PHP 7.1 (refer screenshot attached)

You need to explain how you created it. What is the title? What is the parent category? What other options?

**Comment by HanaRebaiQA** [comment]
Hello @jameswill 

Thanks for your report.
Your issue is already exists, see this [comment1](https://github.com/PrestaShop/PrestaShop/issues/27684#issuecomment-1069249590) and c[omment2](https://github.com/PrestaShop/PrestaShop/issues/27684#issuecomment-1056767579) and will be fixed in this [PR](https://github.com/PrestaShop/PrestaShop/pull/27806)

So, it's a duplicate of this [issue](https://github.com/PrestaShop/PrestaShop/issues/27684) 

You can subscribe to the PR to be notified when the issue is fixed. 
I'll close this issue. Don't hesitate to open new tickets when needed.

Thank you!

**Comment by HanaRebaiQA** [comment]
Duplicate of [#27684](https://github.com/PrestaShop/PrestaShop/issues/27684)
