### ISSUE TITLE
Prestashop 1.7 productlist.tpl add date of availability

### ISSUE THREAD

**Issue by stech10** [PrestaShop/PrestaShop#28013]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Hello,

I need to add the date of availability in the productlist.tpl and if possible if the product is in stock ready for shipping or not

![date](https://user-images.githubusercontent.com/102210948/159643458-a4026ac4-2b1d-4c51-8189-258a73bf987b.png)

### Describe the solution you'd like

What tpl file should edit?

Can you help me with source code?

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
Hi, edit `/themes/classic/templates/catalog/_partials/miniatures/product.tpl`. If you put `{dump($product)}` in there, you will see all the data you have available in the product object.

You will be interested in `$product->quantity`, `$product->available_now`, `$product->available_later`.

However, try to ask on Prestashop Slack instead - somebody will help you there. Github is only for issues and this will be closed. 👍

**Comment by HanaRebaiQA** [comment]
Hello 

Thanks @stech10  for your report and @Hlavtox for your response.

I just saw how can i help you. 
**Case 1** : I putted  ` {product->name}` in `product-flags.tpl` file to can display the name of product under the flag. Here is my example : 
![image](https://user-images.githubusercontent.com/92912932/159671710-8b34a5c6-0dbd-4cac-8b38-f1eda0560f59.png)

https://user-images.githubusercontent.com/92912932/159671778-de3988ac-4c5e-460b-bff5-ae152a84babb.mp4


**Case 2** : I added a `{dump($product)}` under `product.tpl `file to can see all needed information. Like this : 
![image](https://user-images.githubusercontent.com/92912932/159672265-31e10990-67f6-4eb3-9700-29b557539367.png)
![image](https://user-images.githubusercontent.com/92912932/159672321-23471b6e-2539-4b8c-8d9c-758fc85f760d.png)


So, i'll close this issue as it's not a Core issue/feature.
Otherwise, ifyou have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you!
