### ISSUE TITLE
Automate local CI checks

### ISSUE THREAD

**Issue by tom-combet** [PrestaShop/PrestaShop#28024]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As a developer, I want to run code checks (php syntax, js syntax, unit tests, behat, and every other workflows) automatically with one command so that I don't have to run each dedicated command separately with executables from `vendor/bin`.

No really, I'm tired of running the commands one by one manually, specifying each time which files I want to check as argument.
Moreover, it would avoid additional "Fix PHP-CS-Fixer", "Fix PHP Stan" commits, things like that.

### Describe the solution you'd like

We need a tool which checks our code changes for us.
It could be run automatically (with git hooks) and manually (running one single command).

I suggest to use [GrumPHP](https://github.com/phpro/grumphp).
It's imo the perfect solution for this issue as we would have everything out of the box. No need to dive into writing scripts and reinvent the wheel: many tasks are available, we can extend them, add custom ones and it's super easy to configure!

### Alternatives you've considered

N/A

### Additional context

You can check an example of GrumPHP configuration in my [kjmodulebedrock](https://github.com/Kaudaj/kjmodulebedrock/tree/main/tests) project.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by matks** [comment]
> We need a tool which checks our code changes for us.

I do not fully understand what do you mean.

Notice that you cannot achieve the same output as the CI because we have some CI steps that run the code in multiple environments (for example we run tests with PHP 7.2, 7.3, 7.4 and 8.0). So unless you build a docker environment for each possible environment you won't be able to do this on localhost.

Our CI runs in GitHub because it's not just tools it's also environments. You won't be able to have the same complete code checks on localhost I think.

So even if you could create a single script that call all other scripts, you won't be sure PHPUnit tests will not fail on PHP7.2 (because you checked with PHP7.3).

I am not sure to understand... what does your tool bring that the CI on GitHub cannot do? You want to know if your code is valid, push it on your fork, run GitHub Actions (you can also do it on your fork).

**Comment by tom-combet** [comment]
> Notice that you cannot achieve the same output as the CI because we have some CI steps that run the code in multiple environments (for example we run tests with PHP 7.2, 7.3, 7.4 and 8.0). So unless you build a docker environment for each possible environment you won't be able to do this on localhost.

Ah yea, didn't see that workflows run with each supported PHP version. But by the way, is it really useful?
I see for example that [PHP-CS-Fixer runs only against PHP 8](https://github.com/PrestaShop/PrestaShop/blob/a280f3bae8455e0b5c8fa41670a188913fcd6b34/.github/workflows/php.yml#L16).
Moreover, [it looks useless to run PHPStan with multiple PHP minor versions](https://github.com/phpstan/phpstan/issues/623#issuecomment-347765945).

I may be wrong, so if we still have to use different php versions for tests, I have the solution for you: [tada](https://github.com/phpro/grumphp/blob/master/doc/parameters.md#parameters)!
See `git_hook_variables` > `EXEC_GRUMPHP_COMMAND` parameter. You can run GrumPHP with multiple PHP versions like this:

`EXEC_GRUMPHP_COMMAND: ['usr/bin/php71', 'usr/bin/php72', 'usr/bin/php73', 'usr/bin/php74', 'usr/bin/php80']`

I just discovered it while writing this! 😁 

> I am not sure to understand... what does your tool bring that the CI on GitHub cannot do? You want to know if your code is valid, push it on your fork, run GitHub Actions (you can also do it on your fork).

Speed. Tests will run only on code changes, not on the whole project.
And still, beside that, the whole contributing process becomes faster and more pleasant. Imagine, you don't have to:

- Push your changes.
- Wait the GitHub Actions feedback.
- Fix your changes accordingly with a dirty "Fix PHP-CS-Fixer" commit that could have never been there.
- Wait the GitHub Actions feedback.
- (Re-fix it if you forgot to run some tests locally, it happens when things are manual. Sometimes even several times.)
- (Wait the GitHub Actions feedback.)
- If GitHub Actions feedback is green and you want to do things right, squash the commits to avoid meaningless "Fix syntax" commits.

Oh and don't get me wrong: I don't want to replace GitHub Actions with GrumPHP! It's not the idea at all.
If we compare it to forms validation, GitHub would be the server-side one and GrumPHP the client-side one.

I hope I made it clear enough this time...

**Comment by tom-combet** [comment]
@matks Don't you agree?

That makes me more and more crazy to be honest... I spend quarter of the time (if not the half) on fixing the code style and syntax. On small pull requests, you spend sometimes more time to fix them than developing the feature.

It doesn't encourage to do PR, this is even discouraging in my case. Not blaming at all, but I think this issue should be considered.

**Comment by matks** [comment]
If you want to use GrumPHP to be able to run the CI locally, and make sure that your changes will not make the CI crash, please do 👍 it's a nice idea.

You could maybe check with the group Friends of Presta (https://github.com/friends-of-presta) to add this to the organization, they built a nice Console tool https://github.com/friends-of-presta/fop_console

But unfortunately I dont this is something suitable that should be included/merged in the PrestaShop project, because:

- I'm sorry but you're the only person who reported this issue although I have been maintainer for 4 years so I think this issue is annoying mostly only for you, most people, me included, do not encounter this issue or find it annoying 😅 although I push code to this repository almost every day
- I dont want add another tool to the project that has no big ROI. As maintainers we're responsible for configuring, fixing, improving, updating all the tools we chose to embed into the project so adding a tool makes our maintenance burden bigger. So we don't do it lightly.
- "When you adopt a tool you adopt the management philosophy embedded in that tool."

> Fix your changes accordingly with a dirty "Fix PHP-CS-Fixer" commit that could have never been there.

You can [amend your commits](https://www.atlassian.com/git/tutorials/rewriting-history) to avoid useless commits

> I spend quarter of the time (if not the half) on fixing the code style and syntax. On small pull requests, you spend sometimes more time to fix them than developing the feature.

I'm sorry but if you really spend this much tome fixing code style and syntax you might need to improve your setup. Do you use an IDE like VSCode or PHPStorm? Most IDE can be configured to automatically enforce the codestyle for you and can even parse npm config to detect lint issues while you are writing the code. This should make the issue a lot less annoying.

I'm closing this as I dont think this will lead to something to be merged into the project but thank you for submitting the idea 👍  sorry it did not blossom into a nice addition
