### ISSUE TITLE
The sum in the cart is not updated after changing quantity

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#28034]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After changing quantity of product in the cart more or less the sum is not changing.
![image](https://user-images.githubusercontent.com/50954519/159979971-7fed7bd7-621f-435d-955d-89c8670c10b7.png)
The sum is changed only after reload the page

### Expected behavior

I expect that the sum in the cart will be changed after changing product quantity automaticaly without page reloading.

### Steps to reproduce

Go to https://old.te.com.ua/
put the any product in the cart. 
Change the product quantity in the cart, see the issue.

### PrestaShop version(s) where the bug happened

1.7.8.1-1.7.8.5

### PHP version(s) where the bug happened

7.1.33-44

**Comment by hibatallahAouadni** [comment]
Hello @photinia73 

I didn't manage to reproduce the issue with classic theme, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/160094506-ec5845e8-d67b-473c-8bf2-a84007d65ba5.mp4

It seems your issue is related to your theme or your overrides :wink: 
Closing the issue as it's not a Core bug.

Thanks!

**Comment by photinia73** [comment]
Ок, thank you
