### ISSUE TITLE
POC Implement new multiple format thumbnail generation

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#28048]
This is a part of https://github.com/PrestaShop/PrestaShop/issues/27318.

### 1. Generation of new formats
- When generating multiple image per format availble.
- The basic JPG/PNG format plus any additional formats checked. Test for now with Currently only WebP is supported, png and jpg
- Be sure that thumbnails are automatically regenerated in **all formats**, if missing.

### 2. Provide these new formats to FO $product objects.
**Option 1** 
Just add url_webp, url_jpg & url png next to the original URL

![webp1](https://user-images.githubusercontent.com/6097524/160348990-37b7e851-c262-42e6-a31f-f793db3f97ee.png)

**Option 2** 
Add it to sources array, so it looks like this

```
- small => array 
  - url => https://dev.trendo.cz/2-small_default/osklivy-produkt.jpg
  - width => 98,
  - height => 98
  - sources => array
    - jpg => https://dev.trendo.cz/2-small_default/osklivy-produkt.jpg
    - webp => https://dev.trendo.cz/2-small_default/osklivy-produkt.webp
    - avif => https://dev.trendo.cz/2-small_default/osklivy-produkt.avif
```
**Acceptance test**

FO object match the BO configuration and expected format

**Comment by eternoendless** [comment]
IMO additional formats should be handled through modules. So I think we just need to add the extension points.

**Comment by NeOMakinG** [comment]
> IMO additional formats should be handled through modules. So I think we just need to add the extension points.

WebP and next modern formats should be included with prod build, this is a must-have for front-end themes and developers, we shouldn't need to add a module in order to have these formats to the product lists of the FO, or it should be shipped as a native module in the build prod, so you don't have to add it yourself everytime you develop something

**Comment by Hlavtox** [comment]
@eternoendless 

I very strongly disagree. WebP is already integrated, in a not so good way. Images are a crucial part of front end and absolutely **ALL MERCHANTS** will benefit from it.

Plus, it has been already validated by both core devs and pm.

**Comment by eternoendless** [comment]
> WebP is already integrated, in a not so good way.

Let's improve it then.

If anytime a new format appears we need to modify the core, we're not doing things right. Adding extension points has the advantage of being future proof (you don't need to upgrade your core to add support once the extensions are in place), implementation agnostic (you can do it with GD or Imagick) and flexible (you only want Webp and don't care about AVIF? -- just disable the module, then you have a lot less thumbnails to generate!).

We briefly discussed implementations this afternoon with @NeOMakinG. For example, instead of:

```json
{
  "small": {
    "url": "url/to/file.jpg",
    "url_webp": "url/to/file.webp",
    "url_xyz": "url/to/file.xyz",
    "width": 98,
    "height": 98
  }
}
```

I'd suggest this:

```json
{
  "small": {
    "url": "url/to/file.jpg", // backward compatibility
    "uris": {
	  "jpeg": "url/to/file.jpg",
	  "webp": "url/to/file.webp",
      "xyz": "url/to/file.xyz",
    }
    "width": 98,
    "height": 98
  }
}
```

This way, you can have any number of urls for any number of formats. On the template side, you'd end up with this:

```html
<picture>
    <source srcset="url/to/file.xyz" type="image/xyz">
	<source srcset="url/to/file.webp" type="image/webp">
	<source srcset="url/to/file.jpeg" type="image/jpeg">
    <img src="url/to/file.jpg" alt="" />
</picture>
```

The above code is trivial to generate with a simple loop, supporting any arbitrary number of formats included in the data structure, with no change required in the templates.

**Comment by Hlavtox** [comment]
@eternoendless Any format is good. :-) However, the looping of any format won't work anyway, because the primary "key" in srcset is the format, then we select the resolutions we wan't, but maybe you could find a way...

We want to make it a component that you just call, with parameters `image` and `required_sizes`. The smarty component then will generate the srcset with all supported formats contained in the image, we can then put some conditions there, it's not a problem.

> If anytime a new format appears we need to modify the core, we're not doing things right.

Pablo, new format appears every 10 years, I don't think it's that much of a problem, is it. 😁 When we will have the the system improved and it will generate multiple formats at once, adding a new one is one checkbox settings, a template mod and few lines in the thumbnail generator. And who knows if we won't be using something else to view products. (VR?)👍 While I understand your point, I don't think it's worth it to overcomplicate things and build extension points for this, there is sooooo much more important work to do.

Yes, I think that a module should be everything that is not needed by all users. But, especially this topic is beneficiary for absolutely everybody, everybody wants to have a faster website, more modern website, better SEO.

**Comment by eternoendless** [comment]
> Pablo, new format appears every 10 years, I don't think it's that much of a problem, is it.

But it took us 10 years to add support Webp because it wasn't a priority. 

> Yes, I think that a module should be everything that is not needed by all users. 

Do all users need AVIF? Extracting what's not needed by most is not the only objective, the point is modularizing as much as possible to provide more flexibility. Having everything done by the core not only adds to the maintenance burden but it also prevents other people from adding support when they want it.

If we implement this in the core, we'll do it with GD. In addition to allow people to adopt new (or special?) formats more quickly, extracting the feature from the Core would allow people to develop alternative implementations using, for example, [Imagemagick](https://github.com/PrestaShop/PrestaShop/issues/21101). If we hardcode the feature, the core must be modified to support alternative implementations. See what I mean?

> the looping of any format won't work anyway, because the primary "key" in srcset is the format

Because of the preference order? It can be improved this way:

```js
{
  "uris": [
    {type: "image/xyz", url: "url/to/file.xyz"},
	{type: "image/webp", url: "url/to/file.webp"},
	{type: "image/jpeg", url: "url/to/file.jpg"}
  ]
}
```

**Comment by Hlavtox** [comment]
> But it took us 10 years to add support Webp because it wasn't a priority.

That's sad, it should be number 1 priority. You make the software for merchants to have the best stores and sell the most. Not to make developers happy by doing some internal changes. Migrating another controller to symfony is nice, but no merchant gives a 💩, because the original page worked better. Every migrated controller just ruined the responsivity and brought more bugs to the controller. Long live the exceptions. 😞

> Do all users need AVIF?

Yes they do, show me one single merchant on the planet who doesn't want to have a faster and more modern website.

> If we implement this in the core, we'll do it with GD.

That's fine. 👍

> Extracting the feature from the Core would allow people to develop alternative implementations using, for example, https://github.com/PrestaShop/PrestaShop/issues/21101.

They can override it by their own service if they want to implement custom generator with more options.

> Because of the preference order?

No, because currently the structure is **$images->image->sizes->large->url**. So I guess now it will be **$images->image->sizes->large->uris->webp**.

If you wanted to loop through the formats in the srcset compoment it would need to be **$images->image->sources->webp->sizes->large**.

I would keep it like this for now and just add the `uris `array as you specified to the `imagesize`. It will be the easiest thing to do. We will play with it in the template.

**Comment by MeKeyCool** [comment]
> [...] You make the software for merchants to have the best stores and sell the most. Not to make developers happy by doing some internal changes. [...]

I really don't like this argue ... I don't accept it when I am working with a "classical pyramidal" system but with open source I really don't understand it.

If I work for a boss that pay me for, I can argue that studies show that considering work as pain destroy productivity and I like to share some elements about importance of enthusiasm and playing in human self-construction, social construction and all those things that are required for human to work together instead of behave like animals.

In open source, I really don't understand how you can say this ... How do you expect somebody that you don't have any power on will help you to build a tool you need if he doesn't enjoy doing it ? Why should I learn a dated technology ? Why should I use my time, brain, energy ? Maybe you consider developers are just a free resource you can use but ... I think they should legitimately feel insulted with this argue ^^' ...

I agree that we have to work together and I won't accept neither a developer saying that he doesn't care about merchants. But if we are a team please consider developers interests as well.

**Comment by Hlavtox** [comment]
If I am paid for it, it doesn't matter if it's easy or hard. They have been doing it for 10 or more years with a software like this, so I guess they can do for few months more, before important front-end stuff is implemented?

Yeah, so cool to have better API, to migrate something to symfony, to have cleaner code, but it doesn't put bread to our mouths unfortunately.

**Comment by MeKeyCool** [comment]
> If I am paid for it, it doesn't matter if it's easy or hard. They have been doing it for 10 or more years with a software like this, so I guess they can do for few months more, before important front-end stuff is implemented?

Hard isn't opposed to happiness ;) 

> Yeah, so cool to have better API, to migrate something to symfony, to have cleaner code, but it doesn't put bread to our mouths unfortunately.

And you can't cook bread without oven, that's why we need to work together, helping each other to make work more efficient and more enjoyable ^^

**Comment by matks** [comment]
Interesting point brought by @MeKeyCool 👍 

@Hlavtox PrestaShop technical stack needs to evolve because if it becomes too obsolete nobody will be willing to work on it. As you know, today PrestaShop SA is the only company that is hiring people to work on the software full-time. I hope more companies will do this in the future.

But it's very hard to find skilled people willing to work on the software. Most of the people I meet prefer to work on something else, full Symfony, full Laravel. They simply say "no, thanks!" when PS SA offers them the role 😄  . The developer market is actually against us: there are more companies willing to hire than available candidates (for senior developers). So candidates choose what they prefer, and PrestaShop is not the most interesting project.

PrestaShop SA is currently looking to hire _5_ new senior developers that would work on the project and apply to become maintainers when their level is high enough. Five. Finding these 5 people is going to be a massive challenge. And the problem is not the money, it's the scope of the project. A lot of people don't want to do our job. They prefer to work on a SaaS project, with Symfony/Laravel applications deployed by k8s and using Elasticsearch and PostgreSQL 😄  . PrestaShop stack is old-style.

So if we focus on building new features and improving the software without upgrading the stack, in the future PrestaShop SA will find _nobody_ to hire to work on the project. Nobody. So on maintainer side there will only be volunteer people to do the review. Do you think the hundred of contributions we have on the project will be handled by those "not paid by PrestaShop SA" maintainers 🤔 ?

In order to keep the project alive, we need to make sure it attracts developers. So we need better API, migration to Symfony and cleaner code.

> If I am paid for it, it doesn't matter if it's easy or hard.

A lot of people don't think like you do. They look at the job behind the money, and if they can choose between multiple jobs they choose the ones they think they'll enjoy the most. PrestaShop is not in the top 3 I'm afraid.
