### ISSUE TITLE
[Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:" " jqXHR: " undefined"

### ISSUE THREAD

**Issue by estenolotienenadie** [PrestaShop/PrestaShop#28077]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, i gotot this error if i try the 1-click update module in version 1.7.8.2 to 1.7.8.5

I´m using 1-Click upgrade  v4.14.0 version
PHP version: 7.3.33
Current PrestaShop version: 1.7.8.2
![Screenshot_2](https://user-images.githubusercontent.com/64229330/160796888-0631fc96-2fcb-40e9-afce-450af28dade1.png)

Please if you can help.
Thanks.

### Steps to reproduce

Trying to update from 1.7.8.2 to 1.7.8.5

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by hibatallahAouadni** [comment]
Hello @estenolotienenadie 

There could be many things that prevent the upgrade from occurring successfully, but this issue is not PS Core issue. 
So, these are the most common causes to crash the upgrade:

1. Custom theme or modules are installed.  So remove them completely
2. The server is too restrictive, and does not allow for long running processes.  You need to increase the max execution time (if the host allows you to)
3. Using nginx in full or as a proxy to apache adds complexity, and now you have to consider many other factors.  I would suggest running the upgrade in fast cgi/fcgi mode and remove nginx from the equation completely.  (You can re-enable nginx after the upgrade is complete if necessary).

Closing the issue as it's not a Core bug. If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
