### ISSUE TITLE
"out of stock" label displayed with stock management disabled

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#28097]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I have the stock management, nothing of the stock should be taken into account, right?
Well, the out of stock flag is displayed if a product is out of stock and stock management is disabled

### Expected behavior

the out of stock flag should not be shown when you don't want to use the stock

### Steps to reproduce

>Edited by Khouloud

This issue is very related: https://github.com/PrestaShop/PrestaShop/issues/27604
It could be fixed by https://github.com/PrestaShop/PrestaShop/pull/27841

1. Go to product configuration and disable stock management
2. Go to Catalogue, Stocks
3. Put the stock of some product in 0 or a negative value for example
4. Go to FO and see the bug (the out of stock flag is displayed in the product page & category list page)

https://user-images.githubusercontent.com/62474824/161162147-813feec3-9c4c-4259-8c11-cf1d0ea81d61.mp4

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3.33

**Comment by khouloudbelguith** [comment]
Hi @alfonsolr09,

Thanks for your report.
I manage to reproduce the issue with PS1785.
**Product page** 
![image](https://user-images.githubusercontent.com/16067358/161230739-b1749636-54c7-468c-9041-cb95792820bf.png)
**Category list page**
![image](https://user-images.githubusercontent.com/16067358/161230966-5189f2fa-c02f-4533-940f-189027c966cd.png)

It is ok with PS1778.
It is related to https://github.com/PrestaShop/PrestaShop/issues/27604 and could be fixed by https://github.com/PrestaShop/PrestaShop/pull/27841

So I can confirm that this behavior is indeed a bug.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by alfonsolr09** [comment]
do you think it's a minor bug? I think that putting the label "out of stock" on a product when in fact it is in stock is a very big mistake

**Comment by alfonsolr09** [comment]
do you think it's a minor bug? I think that putting the label "out of stock" on a product when in fact it is in stock is a very big mistake

**Comment by Hlavtox** [comment]
This flag will be removed in the next version, we are completely redoing the availability with @NeOMakinG

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/28112
