### ISSUE TITLE
Faceted search not working with feature value containing hyphens

### ISSUE THREAD

**Issue by tom-combet** [PrestaShop/PrestaShop#28224]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Filtering with feature values containing hyphen is not working.
This must be caused by the fact that feature name and feature value is already separated by a hyphen.

### Expected behavior

We should be able to choose a different separator in the settings, or at least warn the user that he can't use hyphens in indexable features' values.

### Steps to reproduce

1. Create a feature value with an hyphen
2. Enable feature filter in the faceted search model
3. Try to filter with this value in FO

### PrestaShop version(s) where the bug happened

1.7.5.0

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @tom-combet 

We are aware of this issue. This issue is a duplicate of #23815. 
As you can see in the issue mentioned above, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #23815

**Comment by tom-combet** [comment]
In fact, I'm not able to reproduce it in last version, special characters are correctly escaped.

Sorry for the inconvenience... 😅

**Comment by KoenBrouwer** [comment]
I can confirm that this is still an issue. We have the exact same versions of PrestaShop and the Faceted Search module running. We solved this issue by replacing all hypens `-` with minus `−` characters in our product names and features, but seriously, this shouldn't be a big issue. Why not change the module to use a pipe `|` instead of hyphens and slashes as a break character in URLs?

**Comment by tom-combet** [comment]
On 1.7.5 or 1.7.8? I can confirm the issue has been solved in latest version.

**Comment by KoenBrouwer** [comment]
We're on 1.7.5. Bit of a pain in the a** to upgrade, but this might be worth it.
