### ISSUE TITLE
Blockreassurance - an exception is displayed in the product page after upgrading the module to v5.1.1

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28264]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

(modified by @matks / the initial bug report is down)

When PrestaShop is installed in a subfolder, custom icons cannot be used else an exception is displayed.

![image](https://user-images.githubusercontent.com/16067358/163388308-9148a391-8fc0-47b9-ad45-a56b5b1ac110.png)

### Expected behavior

When PrestaShop is installed in a subfolder, custom icons can be used and are displayed correctly in FO and in the module BO page.

### Steps to reproduce

_WARNING: bug happens only if store is installed in a subfolder, see https://github.com/PrestaShop/PrestaShop/issues/28264#issuecomment-1104814142_

1. Install PrestaShop 1.7.8.x in a subfolder
2. Go to BO > Module manager > search the blockreassurance module and click on configure
3. Add one block with custom PNG image
4. Activate the block
5. Go to FO > View product
6. See error

https://user-images.githubusercontent.com/16067358/163389408-d76994f7-90ab-4815-b2ad-3ed4fc464240.mp4

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.5, develop

### PHP version(s) where the bug happened

7.2, 7.4

### If your bug is related to a module, specify its name and its version

blockreassurance v5.1.1

#### Initial bug report

After an upgrade of the module `blockreassurance` from an old version to v5.1.1.
An exception is displayed

PS1778 + PHP 7.2 + blockreassurance v5.1.1 => NOK
PS1785 + PHP 7.2 + blockreassurance v5.1.1 => NOK
PS1785 + PHP 7.4 + blockreassurance v5.1.1 => NOK

It is ok with v5.1.0

1. Install PS1785
2. Enable debug mode
3. Go to BO > Module manager > search the blockreassurance module and click on configure
4. Add two blocks with png image & jpg image
5. Upgrade the blockreassurance to v5.1.1
6. Go to FO > View product
7. See error

**Comment by matks** [comment]
Hello @khouloudbelguith I failed to reproduce the issue.

This is what I did
1. Install PS1785. Install blockreassurance 5.1.0
2. Go to BO > Module manager > search the blockreassurance module and click on configure
3. Add two new blocks using custom images: one png image and one jpg image
4. Enable the new blocks.
5. Go to FO > View product, page displays correctly
6. Upgrade the blockreassurance to v5.1.1 using the button from "BO > Module manager" page
7. Go to FO > View product

My reassurance block displays correctly:
![Capture d’écran 2022-04-15 à 17 20 12](https://user-images.githubusercontent.com/3830050/163588920-ca613d43-cce8-45e7-9f38-394538811cae.png)

Maybe there is a little something to clarify to reproduce the issue. I have some questions:
- after step 3 (adding the two blocks), did you "enable" the 2 blocks?
- how did you have module 5.1.0 ? just after installing 1.7.8.5 ?
- how did you update module? did you use "update" button? did you drag-and-drop a ZIP of 5.1.1 into the BO page?
- after step 3 can you check if your directory modules/blockreassurance/views/img/img_perso contains the images you uploaded at step 3 ? when you reach step 6 can you check the directory content again?
- can you check the FO > View product page after step 4 (and if you enable _and_ disable the new blocks)

**Comment by khouloudbelguith** [comment]
@matks, thanks for your feedback.

We should enable debug mode to have the exact exception as described in the step2
Also, I manage to reproduce the issue with develop branch fresh install + blockreassurance v5.1.1 (no need to upgrade the module)
[develop+blockreassurancev5.1.1.pdf](https://github.com/PrestaShop/PrestaShop/files/8496887/develop%2Bblockreassurancev5.1.1.pdf)

>Maybe there is a little something to clarify to reproduce the issue. I have some questions:

>after step 3 (adding the two blocks), did you "enable" the 2 blocks?

yes, I enabled them
>how did you have module 5.1.0 ? just after installing 1.7.8.5 ?

yes, after a fresh install 1785, I have the `blockreassurance` module 5.1.0

>how did you update module? did you use "update" button? did you drag-and-drop a ZIP of 5.1.1 into the BO page?

I just clicked on the upgrade button from the BO > Modules > Module manager page 

>after step 3 can you check if your directory modules/blockreassurance/views/img/img_perso contains the images you uploaded at step 3 ? when you reach step 6 can you check the directory content again?

Yes, I have the images 
![image](https://user-images.githubusercontent.com/16067358/163594173-b5df8c46-64da-450d-9a91-fe5012681e0e.png)

>can you check the FO > View product page after step 4 (and if you enable and disable the new blocks)

- If I disable the new blocks => no exception is displayed
- If I enable the new blocks => the exception is displayed

Thank you!

**Comment by matks** [comment]
I still cant reproduce the issue
![Capture d’écran 2022-04-20 à 15 57 55](https://user-images.githubusercontent.com/3830050/164247266-15821942-581d-4531-94fb-d392c6e79b4e.png)

**Comment by matks** [comment]
@khouloudbelguith If I do

1. Install PS1785
2. Enable debug mode
3. Go to BO > Module manager > search the blockreassurance module and click on configure
4. Add two blocks with png image & jpg image
5. Open FO -> View product page

I see the error you have. It is a bug fixed in v5.1.1 in PR https://github.com/PrestaShop/blockreassurance/pull/388 . @florine2623 was able to observe the bug ref https://github.com/PrestaShop/blockreassurance/pull/384#pullrequestreview-935033968

**Comment by matks** [comment]
I can reproduce the issue with one specific detail: the application must be installed in a subfolder. PrestaShop files must not be at the root document of the web server but in a directory.

1. Install PrestaShop 1.7.8.x in a subfolder
2.Go to BO > Module manager > search the blockreassurance module and click on configure
3. Add one block with custom PNG image
4. Activate the block
5. Go to FO > View product
6. See error

**Comment by matks** [comment]
@khouloudbelguith Is this bug still `Major` is it only happens if shop is installed in subfolder?

**Comment by khouloudbelguith** [comment]
Hello @matks,

After a discussion with the qa_team @PrestaShop/qa-functional, we think it is a major issue.
Because:
- There are real shops are installed in the subfolder, ping @sarahdib @florine2623 
-  If we change the configuration of the blockreassurance module 
![image](https://user-images.githubusercontent.com/16067358/164475236-75afbba9-f68f-4ab5-8b90-898b8fc57842.png)
=> all the FO, will have an exception 
![image](https://user-images.githubusercontent.com/16067358/164475298-a4ecd6b1-92ef-4672-934d-5f52feaa3171.png)


Thanks!

**Comment by matks** [comment]
@AureRita and I spent some time exploring the bug that is making us go crazy 🤯  


So I think I know the root of our problems: I believe that when you upgrade module blockreassurance from version A to version B, blocks created with custom images are corrupted because the custom images are deleted.

This is, I guess, because custom images are stored in blockreassurance/views/img/img_perso and I think when an upgrade of the module happens, this directory is deleted and replaced by the new blockreassurance/views/img/img_perso folder, of the new version.

This makes it very hard for @AureRita  to test my PR : everytime he prepares a shop using blockreassurance 5.1.1 then ‘upgrades’ to my branch, his images are deleted.

Unfortunately the fix for this “blockreassurance custom images are deleted on upgrade” issue would be to persist custom images into another folder, outside of the module. I don’t think this is suitable for a bugfix, more a minor version or a major version, moving “where I store my images” is a high-impact change.

In order not to delay 1.7.8.6 further, I can suggest one path now: I don’t embed blockreassurance 5.1.1 into 1.7.8.6, I set 1.7.8.6 to use 5.1.0 only. So 1.7.8.5 -> 1.7.8.6 upgrade is not impacted by blockreassurance issues -> PR https://github.com/PrestaShop/PrestaShop/pull/28362

And parallel to that I register the bug “blockreassurance custom images are deleted on upgrade” must be sorted by priority to solve this problem for good.

**Comment by matks** [comment]
I was not able to fix the problem and I cannot find time to finish my PR https://github.com/PrestaShop/blockreassurance/pull/393 :( so I'll let someone else continue

**Comment by HanaRebaiQA** [comment]
Hello everyone, 

This issue is already fixed by this PR [#blockreassurance/473](https://github.com/PrestaShop/blockreassurance/pull/473) (see this [comment](https://github.com/PrestaShop/blockreassurance/pull/473#pullrequestreview-1251923112))
So, I'll close it.

Thank You!

**Comment by leemyongpakvn** [comment]
@HanaRebaiQA I don't think so. This issue is **only** gone after I **Merged branch 'PrestaShop:dev'** into my own branch in PR blockreassurance/473. PR 473's changes are not related to this issue at all :) @matks wdyt?
