### ISSUE TITLE
Same product with different customization content can be put into cart once only

### ISSUE THREAD

**Issue by molsondry** [PrestaShop/PrestaShop#28323]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

You are not able to order/ put into the cart the same product twice or more times with different customization content. Then you get the message that the maximum amount of articles of this kind is reached and no more may be put into the cart

https://user-images.githubusercontent.com/5124936/165110318-098d1647-6359-4091-a876-6937ff7a1121.mp4

### Expected behavior

Adding the same product with different customization content twice or more should be added to the cart as two or more cart entries.

### Steps to reproduce

Go to my example https://shop.gymcollection.de/soeckchen/3130-121958-sck001.html#/4351-groessen_socken-gr_27_30/4384-farben_folien-blau_glitter
Leave size and color as it is or change it.
Put in a name for customization
Put the customized product into the cart
Put in a different name for a second customized product (leave size and color the same)
Put this product into the cart
The error will appear

Choosing different attributes in size or color will not reproduce this error, but the first product will be put into the cart with customization, the second misses the customization text.
![2022-04-25 16_36_53-Warenkorb](https://user-images.githubusercontent.com/5124936/165112270-6dff6eb1-b688-4ae0-8658-ea72cf183506.png)

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment]
Hello @molsondry,

I didn't manage to reproduce your issue nor with PS1.7.7.8 neither PS1.7.8.3

https://user-images.githubusercontent.com/89604350/165275870-2f0be40f-4cc9-456e-b49c-6fab853f3480.mp4

Did I miss some thing?

Thanks,

**Comment by molsondry** [comment]
Hi [marwachelly](https://github.com/marwachelly),
Thank you very much for helping. I have got an update and solved the problem. It is related to an installation of Attribute Wizard Pro made by Prestochangeo. For all who want to get rid of Attribute Wizard Pro: AWP installation changes your database structure of table xx_cart_product. It adds three additional fields and id_customization is no longer part of the PRIMARY KEY. After deinstalling AWP you have to add id_customization back to the PRIMARY KEY group
![changesAfterDeinstallationOfAWP](https://user-images.githubusercontent.com/5124936/166121320-4bee0bb5-f674-4780-add2-87c5ed9d5c31.png)
.

**Comment by Anthony-Tran** [comment]
I allow myself to open the ticket again because I have exactly the same problem as you describe on your screenshot. I tested on a clean install.
I posted on the prestashop forum (https://www.prestashop.com/forums/topic/1069155-duplicate-display-of-the-personalization-and-does-not-save-the-personalizations-when- several-combinations-cart-order/) but I have no answer so I try my luck on github.

This video shows the customization fields that are doubled on the cart
https://user-images.githubusercontent.com/745311/195545651-03cf2fd2-82ee-460b-a472-bdcb5b40b78e.mp4

This video shows that the second customization is not saved
https://user-images.githubusercontent.com/745311/195545851-67e41e1b-d865-4076-94d2-bd13c5b15a28.mp4


The full video with backend
https://www.prestashop.com/forums/uploads/monthly_2022_10/full.mp4.b6a0b851862d231373e232723cfc6a9a.mp4
