### ISSUE TITLE
Invalid characters are being saved as titles

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#28320]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When creating or editing an existing social title, the tool tip shows the invalid characters as: "0-9!<>,;?=+()@#"{}_$%:".
However when entering any of these characters, they are still getting saved, only the max length limit works in this field. 

https://user-images.githubusercontent.com/23308427/165263440-c6f1ef76-d635-4387-9c33-d5f729f7f3d0.mp4

### Expected behavior

Invalid characters should not be allowed to save.

### Steps to reproduce

1. Go to Shop parameters -> Customer settings -> Titles.
2. Press "Add new social title".
3. Check the "Social title" tool tip.
4. Enter the invalid characters in to the same field.
5. Press "Save".

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.1

**Comment by marwachelly** [comment]
Hello @Saimis777 

I was able to reproduce the issue with PrestaShop version 1.7.7.8. I'll add this to the debug backlog so that it's fixed.

https://user-images.githubusercontent.com/89604350/165262911-504b5001-dbc8-4ab6-8d9e-22970e737aec.mp4


Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks,

**Comment by fabienvallon** [comment]
If there is no technical / security flaws, I think we can remove this invalid characters ( and remove the tooltip) 
If there is a technical / security flaw, we should filter and fix it

**Comment by AlexTechDev** [comment]
I'm working on it :)
