### ISSUE TITLE
Display products from disabled Subcategories in Parent Category

### ISSUE THREAD

**Issue by Alan3k** [PrestaShop/PrestaShop#28349]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

I'm trying to show products from disabled subcategories in parent category. 

For example:
![categories](https://user-images.githubusercontent.com/29299511/165504669-c18ed474-3539-4602-a4d0-3725b223ee5d.jpg)

I want this item to display in category "**Surazo euro 5**", "**BENYCO**" and "**BENYCO SURAZO - CZĘŚCI**".
If I enable subcategory "**elektronika surazo 2**" then item is displayed in parent categories. But this subcategory is only for my informations so I would like to keep then disabled.

Item is enabled and showing only in makred parent category "**Części do skuterów chińskich**".

I'm using **ps_facetedsearch** module with option enabled "**Show products from subcategories**".

Prestashop 1.7.8.5

This issue started after update from 1.7.5.X or previously version.

### Expected behavior

Parent category should display active products from disabled subcategories.

### Steps to reproduce

1. Add parent category
2. Add subcategory
3. Add product only to subcategory
4. Disable subcategory
5. Check parent category page

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.8.0

**Comment by hibatallahAouadni** [comment]
Hello @Alan3k 

Your issue is quite similar to this one #24370
Could you please check it and feedback.

Thanks!

**Comment by Alan3k** [comment]
Hello @hibatallahAouadni,

I'm afraid this issue is not similar.

I will try to make explanation simpler. Let's say we have category tree:

- Category (level 1)
-- SubCategoryA (level 2)
--- SubCategoryB (level 3)

Product is enabled and added only to SubCategoryB. But it's displaying in all Categories (Category, SubCategoryA, SubCategoryB) because of "Show products from subcategories" option enabled from ps_facetedsearch.

But if I disable SubCategoryB then product (active) is not visible in parent categories.

I have made some more screenshots:

- When subcategory are disabled
![screen-1](https://user-images.githubusercontent.com/29299511/165682750-77a2c8d4-e45b-442e-99ce-19c62d412e93.jpg)

- We don't see products in parent category
![screen-2](https://user-images.githubusercontent.com/29299511/165682886-64ed6d59-4679-41ae-8c59-c40567d55651.jpg)

- When subcategory is enabled
![screen-3](https://user-images.githubusercontent.com/29299511/165682931-4c43402b-c367-456b-8614-36a510edf554.jpg)

- Then products are visible in parent category
![screen-4](https://user-images.githubusercontent.com/29299511/165682991-e94ff092-0084-44e5-8780-12e18fab8d30.jpg)

**Comment by AureRita** [comment]
Hi @Alan3k, 

I see the problem here, 

Currently, the option "Show products from subcategories" show us products we can see, 

What this option show :

https://user-images.githubusercontent.com/100699445/166256866-6a802039-e146-4917-aaf2-373bf9f47a6f.mp4

We'll take an example : Now, Only your customers and guest can see your products and your visitors can't, how can you did it ? like this : 

https://user-images.githubusercontent.com/100699445/166257627-55b7d7cb-f9ab-4693-8dc3-646e3d5b422a.mp4

Now, you know all your product of this category are obsolete, how did you disable all of them in one click ? 
Like you do it, so it's an expected feature. 

Now, In your issue, you want to see all the products even if you disabled the category, you can do like this 
(first time I will present the problem and after the answer) 

https://user-images.githubusercontent.com/100699445/166259904-6abfa44b-7a87-4a16-ac10-e3579f52eb79.mp4

As you can see, we can now see the product on the main category even if the child category of the product is disabled. 
Moreover, the category show on the product page on BO is the same than before. 

So you can continue to see your category "elektronika surazo 2" even if it is disabled 

Do all these explanations help you for your problem ? 
Are you agree to say that's not an issue but an expected feature ? 

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @Alan3k 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
