### ISSUE TITLE
Problem with`filterProductContent` hook in productcomments module

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#28342]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hook inside `hookFilterProductContent` should return `$params`. 
Since it not returning it there is no arguments for another module registered to that hook and error occurs. 

> Type error: Argument 3 passed to HookCore::callHookOn() must be of the type array, null given, called in /Users/admin/code/nutropharma/classes/Hook.php on line 944

### Expected behavior

When more modules than product comments are registered to `filterProductContent` no error should occur.

### Steps to reproduce
1. Install module [productcomments_filter_test.zip](https://github.com/PrestaShop/PrestaShop/files/8566301/productcomments_filter_test.zip)
2. Trun on debug mode.
3. Go to product page.
4. Error should be displayed.

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

productcomments v5.0.1

**Comment by hibatallahAouadni** [comment]
Hello @Oksydan 

I reproduce the issue with PS1778 and PS1785, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/165536874-22229924-b576-4169-b876-ce1a0ab36329.mp4

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Oksydan** [comment]
@hibatallahAouadni [PR available ](https://github.com/PrestaShop/productcomments/pull/137)
