### ISSUE TITLE
Although it was merged, PR #21732 seems to have never been merged into the branch

### ISSUE THREAD

**Issue by JordanSuarez** [PrestaShop/PrestaShop#28345]
_Note from @matks: please see [this analysis](https://github.com/PrestaShop/PrestaShop/issues/28345#issuecomment-1222489800) for a complete explanation of this ticket_

### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Related to this [issue ](https://github.com/PrestaShop/PrestaShop/issues/21034), fixed by this [pull request](https://github.com/PrestaShop/PrestaShop/pull/21732).

This bug was fixed, merged, but it seems the PR was not really applied.

### Expected behavior

Expected this change 
`$this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < Pack::noPackPrice((int) $this->product->id)));`

 but got this, in develop branch and 1.7.8.5 version
 `$this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < $this->product->getNoPackPrice()) ? true : false);`

### Steps to reproduce

See:

-  [1.7.8.x file](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/controllers/front/ProductController.php#L354)

-  [develop file](https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/ProductController.php#L360)

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by hibatallahAouadni** [comment]
Hello @JordanSuarez 

That's totally weird :scream: 
Ping @PrestaShop/prestashop-core-developers can someone please explain to us why this PR is displayed as merged while its modification isn't taken into account, check the files changes [here](https://github.com/PrestaShop/PrestaShop/pull/21732/files) and the attached screenshot below of develop branch:

![image](https://user-images.githubusercontent.com/23308427/165557927-2eddb234-50d4-4d82-a4a6-e84ab8c14979.png)

As you can see the line hasn't change since 2015.
Please check and feedback.

Thanks!

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-maintainers 

something went wrong here:
https://github.com/PrestaShop/PrestaShop/commit/2dc61fba9db8b531b071877f799a3f95c7978264 😱

It's sometimes tricky to know during the `version-branch` to `develop-branch` merge which fix is good 🤔

**Comment by matks** [comment]
> It's sometimes tricky to know during the version-branch to develop-branch merge which fix is good 🤔

Always with git merges 😭

**Comment by MatShir** [comment]
@hibatallahAouadni Have you reproduced this issue https://github.com/PrestaShop/PrestaShop/issues/21034 if the fix have been revert?

**Comment by matks** [comment]
### Analysis

Hello everyone, so let's check a little closer what happened here.

In September 2020 bug https://github.com/PrestaShop/PrestaShop/issues/21034 was reported.
It was fixed by a PR submitted in November 2020 https://github.com/PrestaShop/PrestaShop/pull/21732, tested and merged into 1.7.8.0 .

But if we check the [code](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/ProductController.php#L354) in 1.7.8.0, the code is not identical to the code submitted to the PR. The code is identical to what it was before. It looks like _if the PR was never merged_.

It is probably a git merge issue. It will be hard to know so I suggest we don't spend too much time trying to understand what happened and rather focus on
- can we reproduce this bug on 8.0.0 ?
- if yes, is it a regression or not, and then where does it go

I will also update OP with this information.

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

Yes, I reproduce the issue with PS1778, PS1786 and PS800, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/185976274-ad43fc44-bc96-458c-9552-1fb250aabb1d.png)

So, it's not a regression!

Thanks!

**Comment by jolelievre** [comment]
Hi @matks 

the initial fix was destined to 178 and approved for it so I reproduced the fix targeting 178x branch which seems only fair, since we don't know why nor when the commit/fix disappeared.

https://github.com/PrestaShop/PrestaShop/pull/29413

**Comment by HanaRebaiQA** [comment]
This issue is fixed in this [PR](https://github.com/PrestaShop/PrestaShop/pull/29413).
