### ISSUE TITLE
Bank address mandatory field does not work. [Bank transfer module]

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#28351]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Editing the account details in the bank transfer module, the "Bank address" field is marked as mandatory, but when leaving it empty it still saves without any issues.
![image](https://user-images.githubusercontent.com/75423142/165523849-46fcf9a2-fdd6-4d74-a5df-40ca98fd9d2d.png)

### Expected behavior

Should not allow to save without any bank address.

### Steps to reproduce

1. Go to Modules -> Module manager
2. Enter the default Prestashop module "Bank transfer".
3. Enter all the details, leave the "Bank address" field empty.
4. Press "Save".

### PrestaShop version(s) where the bug happened

1.7.8.2

### If your bug is related to a module, specify its name and its version

Bank transfer v2.1.1

**Comment by hibatallahAouadni** [comment]
Hello @Saimis777 

I reproduce the issue with PS1767, PS1778, PS1785 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/165545306-40342c03-bb2f-45ee-bde2-0f3bcaccb6f9.png)

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
