### ISSUE TITLE
BO - Orders details - Block Status - dropdown has bad styling

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#28405]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The styling is bad on this part of the BO :

https://user-images.githubusercontent.com/16019289/166484489-b3db462a-95b1-472e-8833-bcce427c3859.mov

Bad display of status in the order page.
Develop:

https://user-images.githubusercontent.com/89604350/168549851-d3752216-6681-4b45-bab5-e9b7ebad5af6.mp4

### Expected behavior

It should be displayed better.

### Steps to reproduce

Go to BO > Orders > Order details 
Check block Status

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by MeKeyCool** [comment]
Hi @florine2623 ! I think this issue is related to https://github.com/PrestaShop/PrestaShop/issues/28494
I proposed a fixed : https://github.com/PrestaShop/PrestaShop/pull/28524 but I had some troubles to understand what does mean "displayed better." or "Bad display".

My fix is about the arrow, it looks like @AureRita suggests changing the dropdown size.
Does a "min size" would be enough ? should the size fit to the longest text element ? Maybe something simpler like alternating background colors to see different lines could do the job ?

**Comment by AureRita** [comment]
In my opinion, I think the size should fit to the longest text element, with that element, the arrow should have a good display and the problem of visibility should be corrected ( Indeed, you can have a scroll bar but when you're set on canceled, one status can take all the field of view for statuses ). 
For this point, we maybe want the point of view of an @PrestaShop/product-team

**Comment by MeKeyCool** [comment]
In fact the arrow and the size are two different problems ^^
If you set the size to the longest element, the arrow won't be good for the longest element ;)
The point is this behavior looks the best but as it should adapt to any language, it implies some custom javascript treatment.
(:thinking: maybe it is already implemented somewhere)

**Comment by MeKeyCool** [comment]
After further explanations with @MatShir , I'll fix this issue with a min-size attributes that should match `Awaiting Cash On Delivery validation` content size.
