### ISSUE TITLE
Modules list cache is not correctly cleared in a multishop context

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#28446]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In a multishop context, When I have a module which is activated or disabled for all shops

If I disable the module, I want to have the possibility to clear the cache for every existing store

### Steps to reproduce

1. Be in multishop mode with 2 shops : Shop 1 and Shop 2
2. Install the module [prestashopexamplemodule.zip](https://github.com/PrestaShop/PrestaShop/files/8806627/prestashopexamplemodule.zip)
3. The module is active for shop1 and shop2
4. disable the module for shop2
5. Check that the module is still active for shop1
6. Go to advanced parameters> Performance> Clear cache
7. Check that the module status is changed to inactive for shop 1 after clearing the cache

### PrestaShop version(s) where the bug happened

develop

**Comment by hibatallahAouadni** [comment]
Related to #24354

**Comment by hibatallahAouadni** [comment]
Hello @sowbiba 

Thanks for reporting the issue!
I only managed to reproduce on PS178x and develop. So, it's a regression!
Thanks for your PR :rocket: 

Thanks!

**Comment by marwachelly** [comment]
Hello @sowbiba,

As discussed on slack, the issue is reproduced only following the steps on develop bellow branch :

1. Be in multishop mode with 2 shops : Shop 1 and Shop 2
2. Install the module [prestashopexamplemodule.zip](https://github.com/PrestaShop/PrestaShop/files/8806627/prestashopexamplemodule.zip)
3. The module is active for shop1 and shop2
4. disable the module for shop2
5. Check that the module is still active for shop1
6. Go to advanced parameters> Performance> Clear cache
7. Check that the module status is changed to inactive for shop 1 after clearing the cache

https://user-images.githubusercontent.com/89604350/171216211-57b959d0-35bf-450a-a236-698470e5f2d2.mp4



The bug is not reproducible with PS1.7.8.x. So it is regression on the branch develop. 
Steps to reproduce are updated.

Thanks,
