### ISSUE TITLE
Shop::getBaseURL should return the good url sheme: http or https

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#28468]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

By default $shop->getBaseURL() without the first argument return shop url in http only.

### Expected behavior

https is the standard now, getBaseURL() should return the good scheme by default and not http by default.

There are https calls of getBaseURL() without argument in Prestashop core and native modules (QuickAccess.php, HelperForm, ps_mainmenu, ps_imageslider, ...)

### Steps to reproduce

1. Call Context::getContext()->shop->getBaseURL(); in a shop in https in front
2. Display the URL

### PrestaShop version(s) where the bug happened

1.7, 8

### PHP version(s) where the bug happened

all

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thanks for reporting the issue and creating the PR :rocket: 
I reproduce the issue with PS1778 and PS1785 with SSL mode enabled, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/168115351-6264c094-e67e-4366-8127-38bd2308b6ff.png)

I’ll add this to the debug backlog so that it’s fixed.

Thank you
