### ISSUE TITLE
After upgrading to 1.7.8.5 the Product page with Combinations doesn't load

### ISSUE THREAD

**Issue by Upartech** [PrestaShop/PrestaShop#28495]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Once I upgraded from ps1.7.6.0 to ps1.7.8.5, I started getting error 524 when trying to enter most products with combinations or attributes. The update to ps1.7.8.5 was done on a clone of the ps1.7.6.0 site version so the main site works fine. Every time I try to open the product page of a product with combinations, the process is on hold until the 524 error appears.

I appreciate your help.

### Expected behavior

Normally, when clicking on a product with combinations, the product page with its attributes is displayed in the shortest time.

### Steps to reproduce

1. Update prestashop ps1.7.6.0 to ps1.7.8.5
2. Find a product with combinations on the home page and click. The product can be from the old version or a new one created in the new version.
3. The page will be loading and will not open, error 524.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @ovallepa 

Could you please enable the debug mode and share the exception details 🙏 
Don't forget to provide a screenshot of the displayed exception 😉 
Waiting for your feedback.

Thanks!

**Comment by Upartech** [comment]
Hello. Thanks for answering. I have activated debug mode. When entering a product with combinations and the 524 error is generated, I do not see any report in the error_log file. However, an error has occurred with products that do not have combinations and it did not occur before. Apparently there are missing tables in my database. Attached capture them. What will be the most efficient way to complete the database update?
![image2](https://user-images.githubusercontent.com/24786644/168621260-34135495-4087-4c84-8a92-96c776be6aed.jpg)
![image1](https://user-images.githubusercontent.com/24786644/168621358-223060a1-1654-4144-9212-a0c304de307f.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @ovallepa 

I see that exception is related to the module productcomment, could you please disable it and check if you still encounter the issue.
Otherwise, when you upgrade your shop, did you encounter any issue? and what was the version of the autoupgrade module?
Waiting for your feedback.

Thanks!

**Comment by Upartech** [comment]
I already uninstalled the module and products without combinations work fine. But the 524 error is persistent with products with combinations. I used the 1-Click Upgrade module version 1.14.0.

**Comment by florine2623** [comment]
Hello @ovallepa ,

I've upgraded my shop 1.7.6.0 to 1.7.8.6 without any error on product with combinations page.

It seems like your issue comes from your hosting provider.
"_The 524 A Timeout Occurred error is a Cloudflare-specific HTTP status code that indicates that the connection to the server has been closed due to a timeout. Depending on the context, an Error 524 message might prevent you from loading a web page, signing in to an online gaming platform, or using a piece of software._"

You might have a lot of combinations and your host is not able to support that much queries in order to open the page.
Please contact your hosting provider and make sure your system requirements are met : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I will close your issue as i can't reproduce it on my end.
Thanks!
