### ISSUE TITLE
When accessing admin during install, we cannot know if install is well finished

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#28499]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

During the conception of the edition, we find a problem.

* You make the install. 
* During the install (progress bar), you can access to admin directory but you cannot know (from hook modules) if the install is well finished.

### Describe the solution you'd like

A configuration value where we define if the installation is well finished.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Thanks for your PR :rocket: 

Thank you

**Comment by MatShir** [comment]
Good idea ! Maybe we should add this new parameter in the devdoc? WDYT?

**Comment by Progi1984** [comment]
@MatShir It's not a parameter. It's a configuration value in database. It defined to 0 by default. And at the end, if always it's well processed, it defined to 1.

**Comment by matks** [comment]
I dont think a configuration value is the right solution.

A configuration value is useful to store something that we can and must change over time, like an option, a parameter, a setting.

Here you want this value to start at 0 and then become 1 then never change again. It's a waste to use a MySQL boolean to keep a value that will never again be changed.

I suggest to use something that will not take unnecessary space in database over time:
- we create a single file `.install-in-progress` at the beginning of the install process
- install process performs
- at the end of the install process the file is deleted

This allows us to know whether or not the installation has finished, it will not waste database space or disk space because we _remove_ something, and is even easier to check than a database value (check a file versus perform a SQL query).

**Comment by kpodemski** [comment]
Usually, you cannot access the Back office because the directory name is `admin`, and PrestaShop forces you to change it.

**Comment by Progi1984** [comment]
@kpodemski You can access to the directory `admin` during the install and it will be renamed as it's not done by the installer : https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminLoginController.php#L105-L118

**Comment by MeKeyCool** [comment]
Don't we have the same issue during upgrade process ? :thinking: 
Shouldn't we have a "maintenance mode" / "recovery mode" for admin interface as well ?
During any install / update process you can't access admin interface and have a minimalist view about current install/update process. Then if the process is stuck, shouldn't we allow admin to be able force admin access ?

**Comment by Progi1984** [comment]
@MeKeyCool The upgrade process is managed by the module `autoupgrade`. A maintenance mode already exists. This issue is relative to install not upgrade. During the install, you can access to admin path which renames the directory during the install, so this PR avoids this renaming. For a minimalist view, you should create a specific issue.

**Comment by MeKeyCool** [comment]
Thanks for details :blush:
