### ISSUE TITLE
Google analytic - Prestashop multi boutique

### ISSUE THREAD

**Issue by 1JS-Bordeaux** [PrestaShop/PrestaShop#28573]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bonjour,

Je suis en alternance sans webmaster dans une entreprise et j'aimerai voir le trafic de mon site internet sur Google Analytic. 
Le problème est que, je suis sur Prestashop en multi boutique et quand je rentre la ligne de code après avoir paramétrer le compte sur G.A ca fait planter le site.

Je n'ai pas trouvé de solution. J'ai contacté Google analytic et ils m'ont dit d'appeler Prestashop. J'ai ensuite eu Prestashop par mail qui m'ont dit d'aller sur GitHub...

Avez vous une réponse a ce problème ?

### Expected behavior

Une aide technique

### Steps to reproduce

Une solution ?

### PrestaShop version(s) where the bug happened

1.6.1.24

**Comment by HanaRebaiQA** [comment]
Hello @1JS-Bordeaux 

Thanks for your report.

Could you please use English as the default communication language of PrestaShop ? And, please provide us the steps how to reproduce your issue with a screen-shot OR a screen-record ? 

Is one of theses tickets are similar to yours [#13252](https://github.com/PrestaShop/PrestaShop/issues/13252), [#21790](https://github.com/PrestaShop/PrestaShop/issues/21790), [#13911](https://github.com/PrestaShop/PrestaShop/issues/13911) ?

Please check and feedback

Thank you!

**Comment by HanaRebaiQA** [comment]
Hello @1JS-Bordeaux,

Please send your request in English. English is the norm on GitHub.
PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Otherwise, if you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
