### ISSUE TITLE
Google analytic - Prestashop multi boutique

### ISSUE THREAD

**Issue by 1JS-Bordeaux** [PrestaShop/PrestaShop#28579]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I am on a work-study program without a webmaster in a company and I would like to see my website traffic on Google Analytics.
The problem is that I'm on Prestashop in multi store and when I enter the line of code after setting up the account on GA it crashes the site.

I haven't found a solution. I contacted Google analytics and they told me to call Prestashop. I then had Prestashop by email who told me to go to GitHub...

Do you have an answer to this problem?

### Expected behavior

Technical help

### Steps to reproduce

A solution ?

### PrestaShop version(s) where the bug happened

1.6.1.24

**Comment by florine2623** [comment]
Hello @1JS-Bordeaux ,

I think your issue is related to : https://github.com/PrestaShop/PrestaShop/issues/21790#issuecomment-724016924
As it is an improvement, so you can follow that issue directly there.

Also, PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Otherwise, if you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com/).

I will close your issue.
Thanks!
