### ISSUE TITLE
Problem with loading category page and paginator in category page

### ISSUE THREAD

**Issue by alesspetio01** [PrestaShop/PrestaShop#28602]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

https://calipio.com/app/play/wYOxV7ej#cRfG3egu
This is the problem.

The load of the page and the paginator is very slow.

### Expected behavior

The page will be loaded fast

### Steps to reproduce

1. Go to https://mcgroup.store/it/2-home
2. The loading of the page is slow
3. Change paginator to 2, 3 or n number
4. the loading of the page is slow

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by alesspetio01** [comment]
Please, help!

**Comment by hibatallahAouadni** [comment]
Hello @alesspetio01 

I know you're frustrated with this massive loading problem :disappointed:  
I'm really sorry that I can't help you because this is not a PS Core bug, this problem is related to your server configuration.
Try with the Classic theme and only native modules, you won't encounter the problem :wink: 

So the only way I could help you is to suggest support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
