### ISSUE TITLE
Products added via webservice not appear in suppliers

### ISSUE THREAD

**Issue by tdzierza** [PrestaShop/PrestaShop#28610]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1, Added product via webservice with set id_supplier
![suppliers_1](https://user-images.githubusercontent.com/8463620/170667868-93f3a445-603f-43ec-8d1c-5a456c6f7181.png)
2, Product changed manually - brings effect
![suppliers_2](https://user-images.githubusercontent.com/8463620/170667874-62caf00f-3383-4ed8-8661-d9a4ad023f1a.png)
3. Where it should appear
![suppliers_3](https://user-images.githubusercontent.com/8463620/170667879-43ce5134-4c6b-48bf-9b24-21066a1bd284.png)

### Expected behavior

Products added using webservice should appear ins Suppliers listing

### Steps to reproduce

Send request:

`<prestashop xmlns:ns0="http://www.w3.org/1999/xlink">
     <product>
         <id />
         <id_manufacturer>1</id_manufacturer>
         <id_supplier>55</id_supplier>
         <id_category_default `

### PrestaShop version(s) where the bug happened

1.7.8.4

**Comment by HanaRebaiQA** [comment]
Hello @tdzierza 

Thanks for your report.
Please send your screenshots in English. English is the norm on GitHub.
Could you please provide us the body request that you used and please specify more the steps to reproduce ?

Otherwise, we have issue about products creation with API [#28382 ](https://github.com/PrestaShop/PrestaShop/issues/28382) (Second issue), it can be related ?

Thank you!

**Comment by tdzierza** [comment]
Images are not important, amount of suppliers products not appear  in BO Catalog -> Brands & Suppliers -> Suppliers
You can check any other body request. This is one of example:

`<prestashop xmlns:ns0="http://www.w3.org/1999/xlink">
     <product>
         <id />
        <id_manufacturer>1</id_manufacturer>
        <id_supplier>55</id_supplier>
        <id_category_default 
'ns0:href="http://localhost/api/categories/2">2</id_category_default>
        <new />
        <cache_default_attribute>0</cache_default_attribute>
        <id_default_image notFilterable="true" />
        <id_default_combination 
notFilterable="true">0</id_default_combination>
        <id_tax_rules_group 
ns0:href="http://localhost/api/tax_rule_groups/1">1</id_tax_rules_group>
        <type notFilterable="true">simple</type>
        <id_shop_default>1</id_shop_default>
        <reference>RM-</reference>
        <supplier_reference />
        <location />
        <width>0.000000</width>
        <height>0.000000</height>
        <depth>0.000000</depth>
        <weight>0.000000</weight>
        <quantity_discount>0</quantity_discount>
        <ean13>00000145</ean13>
        <isbn />
        <upc />
        <mpn>S 100 ABT</mpn>
        <cache_is_pack>0</cache_is_pack>
        <cache_has_attachments>0</cache_has_attachments>
        <is_virtual>0</is_virtual>
        <state>1</state>
        <additional_delivery_times>1</additional_delivery_times>
        <delivery_in_stock><language id="1"
ns0:href="http://localhost/api/languages/1" /></delivery_in_stock>
        <delivery_out_stock><language id="1"
ns0:href="http://localhost/api/languages/1" /></delivery_out_stock>
        <product_type />
        <on_sale>0</on_sale>
        <online_only>0</online_only>
        <ecotax>0.000000</ecotax>
        <minimal_quantity>1</minimal_quantity>
        <low_stock_threshold>0</low_stock_threshold>
        <low_stock_alert>0</low_stock_alert>
        <price>15014.23</price>
        <wholesale_price>0.000000</wholesale_price>
        <unity />
        <unit_price_ratio>0.000000</unit_price_ratio>
        <additional_shipping_cost>0.000000</additional_shipping_cost>
        <customizable>0</customizable>
        <text_fields>0</text_fields>
        <uploadable_files>0</uploadable_files>
        <active>1</active>
        <redirect_type>404</redirect_type>
        <id_type_redirected>0</id_type_redirected>
        <available_for_order>1</available_for_order>
        <available_date>0000-00-00</available_date>
        <show_condition>0</show_condition>
        <condition>new</condition>
        <show_price>1</show_price>
        <indexed>0</indexed>
        <visibility>both</visibility>
        <advanced_stock_management>0</advanced_stock_management>
        <date_add />
        <date_upd />
        <pack_stock_type>3</pack_stock_type>
        <meta_description><language id="1"
ns0:href="http://localhost/api/languages/1" /></meta_description>
        <meta_keywords><language id="1"
ns0:href="http://localhost/api/languages/1" /></meta_keywords>
        <meta_title><language id="1"
ns0:href="http://localhost/api/languages/1" /></meta_title>
        <link_rewrite><language id="1"
ns0:href="http://localhost/api/languages/1" /></link_rewrite>
        <name><language id="1" ns0:href="http://localhost/api/languages/1">S
100 ABT Zmywarka do naczyń i garnków</language></name>
        <description><language id="1"
ns0:href="http://localhost/api/languages/1">Zmywarka do garnków, koszy,
rondli, itp.&lt;br/&gt; sterowany czasowo dozownik środka myjącego i 
płuczącego&lt;br/&gt; system stałej temperatury płukania abt z pompą 
wspomagającą płukanie&lt;br/&gt; dwie pompy myjące&lt;br/&gt; 4 programy 
standardowe (cykle: 60”, 120”, 180”, 240”)&lt;br/&gt; termometr bojlera i 
wanny&lt;br/&gt; wysokość drzwi: 50 cm&lt;br/&gt; w zestawie: 1x nierdzewny 
ruszt na naczynia 55 x 70 cm&lt;br/&gt; 1x kosz uniwersalny, na szkło 55 x 
55 cm&lt;br/&gt; 1x kosz na tace 55 x 55 cm</language></description>
        <description_short><language id="1"
ns0:href="http://localhost/api/languages/1" /></description_short>
        <available_now><language id="1"
ns0:href="http://localhost/api/languages/1" /></available_now>
        <available_later><language id="1" 
ns0:href="http://localhost/api/languages/1" /></available_later>
        <associations>
            <categories nodeType="category" api="categories" />
            <images nodeType="image" api="images" />
            <combinations nodeType="combination" api="combinations" />
            <product_option_values nodeType="product_option_value"
api="product_option_values" />
            <product_features nodeType="product_feature" 
api="product_features" />
            <tags nodeType="tag" api="tags" />
            <stock_availables nodeType="stock_available"
api="stock_availables" />
            <attachments nodeType="attachment" api="attachments" />
            <accessories nodeType="product" api="products" />
            <product_bundle nodeType="product" api="products" />
        </associations>
    </product>
 </prestashop>`

**Comment by HanaRebaiQA** [comment]
Hello @tdzierza 

Thanks for your feedback.
I tried to reproduce your issue with 1784 using the same body request, but i have some errors.
So, i used another body request with the desired `id_supplier` like the following : 

```
<prestashop>
<product>
  <id/>
  <state>1</state>
  <id_supplier href="http://0.0.0.0:8081/prestashop_1.7.8.4/api/suppliers/2">2</id_supplier>
  <id_category_default>2</id_category_default>
  <active>1</active>
  <advanced_stock_management>1</advanced_stock_management>
  <associations>
    <categories>
      <category><id>2</id></category>
    </categories>
  </associations>
  <reference>REF_1</reference>
  <name>
  <language id="1">TEST</language></name>
  <link_rewrite><language id="1">Hello</language></link_rewrite>
  <price>100</price>
  <id_shop_default>1</id_shop_default>
  <low_stock_alert>0</low_stock_alert>
</product>
</prestashop>
```
I noticed that when edit the product to check the supplier in : 

1. BO> Catalog > Products 
2. In Options section > Check that Only the Default supplier is checked (in my example : Accessories supplier)
And the supplier associated with this product is not checked 
![image](https://user-images.githubusercontent.com/92912932/170728058-c3d3060d-ebbd-413d-8318-5585b0ab5178.png)

So, that's why the product is not displayed in `Suppliers` page 
But, when check it manually, the product is well displayed in `Suppliers` page
I think so, maybe the request should be updated to can select the associated supplier to the product.
To do that manually, it's impossible only to check the Default supplier without checking the associated supplier.
@tdzierza Could you use the associated supplier attribute in your body request to see if it's possible to added it ?

https://user-images.githubusercontent.com/92912932/170730705-a10b32cf-5ef5-4f08-84b4-e49af31a955d.mp4


https://user-images.githubusercontent.com/92912932/170730347-45b646a8-e126-430e-96ab-e03bd96525f7.mp4


Also, i have checked on develop. It seems that the behavior is changed with Product V2. When want to check the supplier by clicking on the supplier in the associated section which is displayed and so the Default one will be checked automatically.
![image](https://user-images.githubusercontent.com/92912932/170729364-bc2ed71a-155a-45b5-b7e5-8d3e5e63cf8a.png)

And i couldn't check with Product V2 using API because of this issue [#28382](https://github.com/PrestaShop/PrestaShop/issues/28382) 

@MatShir & @jolelievre : What do you think ?

Thank you!

**Comment by tdzierza** [comment]
I found reason. In version 1.7.7.2 it was enough to put id_supplier to products request. Already is required also request product_suppliers.

**Comment by AureRita** [comment]
Hi @tdzierza 
Thanks for your feedback
