### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by dananghel89** [PrestaShop/PrestaShop#28657]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This is an error that I received for the inline JS code on "../{admin}/themes/default/template/helpers/form/form.tpl" line 908 and all it must to be changed is to add double quotes for the values of JS variables instead single. This will be applied for all block of the script. I mean that it will be great if it will be as an oficial update instead of overriding for each module.

Yes, I understand that it depends on how module it calls the template and maybe this error is triggered, after all PAYCOMET module is not the perfect example. The translations are not so important on admin side but it will be great to avoid these kind of errors.

### Expected behavior

Double quotes instead single for all block of the script, from line 907 until 986.

### Steps to reproduce

In my case just to access the PAYCOMET module configuration.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

PAYCOMET 7.7.15

**Comment by hibatallahAouadni** [comment]
Hello @danutel 

> Yes, I understand that it depends on how module it calls the template and maybe this error is triggered, after all PAYCOMET module is not the perfect example. 

Indeed it's not the perfect exemple and we need to reproduce the issue with PrestaShop without overrides or with native modules.

> In my case just to access the PAYCOMET module configuration.

PAYCOMET is not native module. It seems that your issue is not a PrestaShop core bug.
If your module is PAYCOMET Official, please contact support team on Addons

We will close this issue.

PS: if you can reproduce the issue with any native module, please edit the steps to reproduce and ping me, to reopen the issue :wink: 

Thanks!
