### ISSUE TITLE
Getting Error in installation

### ISSUE THREAD

**Issue by devphoenix2404** [PrestaShop/PrestaShop#28693]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi team,

Whenever I try to install the PS 1.7.8.6 it leads to the 

`An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by [clicking here].

1: HTTP 200 - parsererror -`

I've tried many time still its same.

- enabled debug logs but nothing in logs
- requirements fullfil 
- php7.4

![Uploading Screenshot 2022-06-07 at 2.37.36 PM.png…]()

### Expected behavior

Should install easily

### Steps to reproduce

Installation steps failed

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @devphoenix2404 

Could you please provide a screenshot cause the attached photo is broken :disappointed: 
And in which step the installation has been stopped?
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @devphoenix2404 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by devphoenix2404** [comment]
Thanks, no problem :)

**Comment by nguyenhy** [comment]
I also face error making fresh install. I dig it up little bit and find the problem
- version: pretashop 8.0.4 on php 8.1:fpm
- Issue:  `install/index.php?installTheme=true&_=16850805189` return `500` error during fresh install
- problem: 
```php
class ImageManagerCore {
    public static function create($type, $filename)
    {
        switch ($type) {
            case IMAGETYPE_GIF:
                return imagecreatefromgif($filename);
            case IMAGETYPE_PNG:
                return imagecreatefrompng($filename);
            case IMAGETYPE_WEBP:
                return imagecreatefromwebp($filename);
            case IMAGETYPE_JPEG:
            default:
                return imagecreatefromjpeg($filename);
        }
    }
```
`ImageManagerCore::create` being called by  `copyLanguageImages` during `installTheme`.
If we do the `try-catch` the will be exception 
> Call to undefined function imagecreatefromjpeg()

`imagecreatefromjpeg` is belong to `GD` extension. According to [System requirements for PrestaShop 8](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/). We need to install the complete version it in order to Prestashop working properly, not just `GD`

- Read this [comment](https://stackoverflow.com/a/29669394/8332986) to fix the issue.
> When you compile the gd extension, use the flag --with-jpeg-dir=DIR and --with-freetype-dir=DIR

If you using docker like me
```Dockerfile
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd
```

**Comment by vadim-popa** [comment]
@nguyenhy you've saved my life, thanks bro!!!
