### ISSUE TITLE
Multishop Bugs > Product duplicate, product images and Stock 1.7.8.5

### ISSUE THREAD

**Issue by pdkey** [PrestaShop/PrestaShop#28695]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The following problem occurs:
- Situation: 2 shops, 2 different shop groups. Customers, products and orders are not shared. Completely as separate stores.

Products are edited in shop 2.

1. when copying existing products in shop 2 - there are following problems with editing.
- Deletion of images must be done in global mode, otherwise uploading new images shop 2 is unsuccessful.
- Changing the name of the product in shop 2.
- In stock shop 2 the product name of global Mode is taken from database "ps_product_lang" > "name" shop 1.

2. shop 1 - works without problems

3. question:
- why is "ps_product_lang" for product store 2 also created for store 1?
- Why is the name for store 1 shown in the stock?

### Expected behavior

The creation and editing of shop 2 products (name, photos, description and stock) must work smoothly in the store 2 mode.

Stock in shop 2 must show the names of shop 2.

Products from separate shops should not create duplicate entries for shop 1 and shop 2.

### Steps to reproduce

see description

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.1

**Comment by hibatallahAouadni** [comment]
Hello @pdkey 

It seems you report more than a bug in this report :sweat_smile: 
But all of them are related to a duplication of product with multistore context selected, is that so? if so, your issue is related/duplicate to this one #27148.

> why is "ps_product_lang" for product store 2 also created for store 1?

Could you please check #16753 if it's related to your question :pray: 
Waiting for your feedback.

Thanks!

**Comment by pdkey** [comment]
Hi @hibatallahAouadni 

Thank you for your quick response. 

To #27148 - I think not.
In my case the categories, store groups and products of store 1 and store 2 are completely separated.
No product is used in both shops.

To #16753 - also a different situation.

In both shops, if products are duplicated, the images must be deleted in global mode.
If images are deleted directly in one shop. No new images can be uploaded.
If we switch to global mode the old images are still there.

Another problem, because in the shop 2 duplicated products have the described error and the system requires mandatory information such as name and price for both stores. 

Is there a bug in the global mode product list (sell/catalog/products):
"
Oops... looks like an unexpected error occurred

Invalid $number parameter: "" cannot be interpreted as a number
[PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]
"

Because the multishop is the first priority for us to continue using Prestashop, these problems should be solved slowly. I'm afraid the priority for the multishop feature is a bit low when both bugs you described are still open in 2019 and 2021.

**Comment by hibatallahAouadni** [comment]
Hello @pdkey 

> Is there a bug in the global mode product list (sell/catalog/products):
"
Oops... looks like an unexpected error occurred
Invalid $number parameter: "" cannot be interpreted as a number
[PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0]
"

Could you please enable the debug mode and provide a screenshot of this issue :pray: 
And it will be perfect if you could provide a screen record about your issue while duplicating a product :pray: 

Waiting for your feedback.

Thanks!

**Comment by JoeyJanson** [comment]
> Hi @hibatallahAouadni
> 
> Thank you for your quick response.
> 
> To #27148 - I think not. In my case the categories, store groups and products of store 1 and store 2 are completely separated. No product is used in both shops.
> 
> To #16753 - also a different situation.
> 
> In both shops, if products are duplicated, the images must be deleted in global mode. If images are deleted directly in one shop. No new images can be uploaded. If we switch to global mode the old images are still there.
> 
> Another problem, because in the shop 2 duplicated products have the described error and the system requires mandatory information such as name and price for both stores.
> 
> Is there a bug in the global mode product list (sell/catalog/products): " Oops... looks like an unexpected error occurred
> 
> Invalid $number parameter: "" cannot be interpreted as a number [PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException 0] "
> 
> Because the multishop is the first priority for us to continue using Prestashop, these problems should be solved slowly. I'm afraid the priority for the multishop feature is a bit low when both bugs you described are still open in 2019 and 2021.

I've got the same issue for the sell/catalog/products with the error 'Invalid $number parameter: "" cannot be interpreted as a number' and found out that the `format` function in [src/Core/Localization/Number/Formatter.php:106 ](https://github.com/PrestaShop/PrestaShop/blob/2b0a73f9ea15eb883c2d020df08bc3c7c60c5c77/src/Core/Localization/Number/Formatter.php#L106)is trying to do `prepareNumber` on a `NULL` value which ultimately gives the error for the final price in the overview. I've solved this for now by changing the line to `$decimalNumber = isset($number) ? $this->prepareNumber($number) : $this->prepareNumber("0.00");` which is not ideal but skips the error for now. 

I'm also experiencing a lot of issue with the overall multistore feature and can't tell you precisely what goes wrong now. I'm having random duplicate categories, duplicated products, not able to save products because of certain attribute features which are not available in one of the shop contexts, category tree seems invalid on saving etc. etc.

**Comment by hibatallahAouadni** [comment]
Hello @JoeyJanson 

> Could you please enable the debug mode and provide a screenshot of this issue :pray:
And it will be perfect if you could provide a screen record about your issue while duplicating a product :pray:

Could you please provide what I asked for above :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @pdkey 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
