### ISSUE TITLE
Cash on delivery order status issue

### ISSUE THREAD

**Issue by ejfarsta** [PrestaShop/PrestaShop#28707]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After upgrading ps_cashondelivery there is a problem with status when customer choose COD as a delivery method. 

After the upgrade to the v.2.0 the order status is directly set to: OUT OF STOCK /
Untill the upgrade it was status something like: "preparation in progress" the standard PS status with ID no. 3

I cannot change it manualy ... 

### Expected behavior

Instead of order status: OUT OF STOCK should be status set to "Preparation in progress" (ID.3)

### Steps to reproduce

Place an order with COD payment. 

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_cashondelivery

**Comment by Matt75** [comment]
It's the attended behavior because `Preparation in progress` is considered as paid.
<img width="1052" alt="Capture d’écran 2022-06-09 à 10 19 41" src="https://user-images.githubusercontent.com/5262628/172799943-16201cf1-79e9-4174-974e-c8872a66d673.png">

Order state should be `Awaiting Cash On Delivery` that's not considered as paid.
<img width="1052" alt="Capture d’écran 2022-06-09 à 10 19 23" src="https://user-images.githubusercontent.com/5262628/172799985-89ce3158-b7d5-46d1-acde-cec35501e6fd.png">


Order state `Out of stock` is not set by `ps_cashondelivery` but by the core itself.
<img width="1102" alt="Capture d’écran 2022-06-09 à 10 21 05" src="https://user-images.githubusercontent.com/5262628/172800218-38e58661-b867-48f8-9668-83912515b7ec.png">
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.6/classes/PaymentModule.php#L575

For more information, please read https://github.com/PrestaShop/ps_cashondelivery/pull/32

As a new feature we can add a module configuration page to let merchant choose order state should be set for an order paid with `ps_cashondelivery` but please note `Out of stock` state is not set by module but [by the core itself](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.6/classes/PaymentModule.php#L575) so `ps_cashondelivery` cannot change this without side effect.

**Comment by sLorenzini** [comment]
hi @ejfarsta,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- screenshots or screen record
- clear and concise steps to reproduce
- version ps_cashondelivery module before the upgrade

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you

**Comment by ejfarsta** [comment]
It doesn't make sense. Okay, I understand that the order is not paid but how can you "await for cod payment" before processing the order and sending it out? 
First you have to "accept" the order in store, then process it, send it out, deliver and then it can be "awaiting for COD payment". As this is the moment your are actually awaiting for your payment to came from carriers company ... 

Our employee won't start even checking the order if it has status "awaiting" for something ... if it's awaiting then it meanst that they shouldn't be collecting/processing order. 

Plus. The OUT OF STOCK statur is set to all orders with COD payment after upgrade. The product are on stock, avaliable to order - so how core set's the orders to OUT OF STOCK ???

**Comment by Matt75** [comment]
In fact, there a misunderstood because order state `Awaiting Cash On Delivery validation` is set on order at creation because merchant want check order before change order state to another and also order should not be considered as paid to avoid to sent false data to analytics tools and accounting stuffs.

So if you need to add another order state `await for cod payment` after you sent the package for delivery, you can create a custom order state and manage it on your order state workflow.

`ps_cashondelivery` has only in charge to create the order, it initiate the workflow but it's up to merchant to define his desired workflow based on his custom order states and his own order processing workflow

That why I purpose to add a module configuration page to allow merchant to define witch order state should be set by `ps_cashondelivery` on order creation to initiate the order processing workflow.

> Plus. The OUT OF STOCK statur is set to all orders with COD payment after upgrade. The product are on stock, avaliable to order - so how core set's the orders to OUT OF STOCK ???

I attached screenshot for this part of the core
<img width="1102" alt="Capture d’écran 2022-06-09 à 10 21 05" src="https://user-images.githubusercontent.com/5262628/172807303-2f49cab3-50ec-4bfe-b6d1-22041f706389.png">
You can see conditional statement that initiate order state change to `out of stock`

**Comment by hibatallahAouadni** [comment]
Hello @ejfarsta 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by ejfarsta** [comment]
Yes, adding a module should solve the issue.

Untill then - how can I configure to have a different status than "Out of stock" when order is created?
________________________________
Od: Matthias RAIGNE ***@***.***>
Wysłane: czwartek, 9 czerwca 2022 10:50
Do: PrestaShop/PrestaShop ***@***.***>
DW: ejfarsta ***@***.***>; Mention ***@***.***>
Temat: Re: [PrestaShop/PrestaShop] Cash on delivery order status issue (Issue #28707)


In fact, there a misunderstood because order state Awaiting Cash On Delivery validation is set on order at creation because merchant want check order before change order state to another and also order should not be considered as paid to avoid to sent false data to analytics tools and accounting stuffs.

So if you need to add another order state await for cod payment after you sent the package for delivery, you can create a custom order state and manage it on your order state workflow.

ps_cashondelivery has only in charge to create the order, it initiate the workflow but it's up to merchant to define his desired workflow based on his custom order states and his own order processing workflow

That why I purpose to add a module configuration page to allow merchant to define witch order state should be set by ps_cashondelivery on order creation to initiate the order processing workflow.
