### ISSUE TITLE
"Type error" message when trying to edit category

### ISSUE THREAD

**Issue by felinuxsas** [PrestaShop/PrestaShop#28727]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![0125](https://user-images.githubusercontent.com/9337043/173101023-ec6f85be-5535-4572-869c-1dc2be8c3a43.png)
![0124](https://user-images.githubusercontent.com/9337043/173101025-4aca6287-bbe3-4e45-b7be-e909efce257b.png)

### Steps to reproduce

1. Go to Catalog -> Categories
2. Click on Edit for any category

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @felinuxltda ,

Please make sure your version of PHP match with your PrestaShop version.
See our system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by felinuxltda** [comment]
https://comfandi-test.felinux.co/marketplace/php/phppsinfo.php

User/password: prestashop

**Comment by felinuxsas** [comment]
![imagen](https://user-images.githubusercontent.com/9337043/173123346-d31eae77-40c9-4c96-9c87-9984b11be27f.png)

**Comment by kathep** [comment]
I am having the same/similar issue. 

When I click on the categories, I get the same error as screenshot shows above. 

When I installed, I was running Prestashop 8 on PHP 8.2. I recently downgraded to PHP 8.1, but the errors persist. 

Here are the logs: 

INFO08:16:15 | php | User Deprecated: Since api-platform/core 2.7: The service "ApiPlatform\Core\Bridge\Symfony\Routing\IriConverter" is deprecated, use ApiPlatform\Symfony\Routing\IriConverter instead. {     "exception": {} }
-- | -- | --
INFO08:16:15 | request | Matched route "admin_categories_index". {     "route": "admin_categories_index",     "route_parameters": {         "_route": "admin_categories_index",         "_controller": "PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\CategoryController::indexAction",         "_legacy_controller": "AdminCategories",         "_legacy_link": "AdminCategories",         "_legacy_parameters": {             "id_category": "categoryId"         },         "categoryId": null     },     "request_uri": "https://shop.nqo.link/admin624tllio5njwhgkwbtw/index.php/sell/catalog/categories?_token=uTMUDpOFR-QSWr1BE6z2NjySSaRd7QmCtMMBzndwKLk",     "method": "GET" }
DEBUG08:16:15 | doctrine | SELECT t0.id_lang AS id_lang_1, t0.name AS name_2, t0.active AS active_3, t0.iso_code AS iso_code_4, t0.language_code AS language_code_5, t0.locale AS locale_6, t0.date_format_lite AS date_format_lite_7, t0.date_format_full AS date_format_full_8, t0.is_rtl AS is_rtl_9 FROM ps_lang t0 WHERE t0.id_lang = ? [     1 ]
DEBUG08:16:15 | security | Read existing security token from the session. {     "key": "_security_main",     "token_class": "Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken" }
DEBUG08:16:15 | security | User was reloaded from a user provider. {     "provider": "PrestaShopBundle\\Security\\Admin\\EmployeeProvider",     "username": "hello@neuroqueero.com" }
INFO08:16:15 | php | User Deprecated: __construct is deprecated since version 8.1 and will be removed in the next major version. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {     "exception": {} }
DEBUG08:16:15 | doctrine | SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1 [     1,     1,     "category" ]
DEBUG08:16:15 | doctrine | SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1 [     1,     1,     "category" ]
INFO08:16:15 | php | User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {     "exception": {} }
INFO08:16:15 | php | User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {     "exception": {} }
DEBUG08:16:15 | doctrine | SELECT COUNT(cp.`id_product`) AS `products_count`, c.id_category, c.id_parent, c.active, cl.name, cl.description, cs.position FROM ps_category c LEFT JOIN ps_category_lang cl ON c.id_category = cl.id_category AND cl.id_lang = :context_lang_id AND cl.id_shop = c.id_shop_default LEFT JOIN ps_category_shop cs ON c.id_category = cs.id_category AND cs.id_shop = :context_shop_id LEFT JOIN ps_category_product cp ON c.`id_category` = cp.`id_category` WHERE (c.id_category != :root_category_id) AND (c.id_parent = :id_category_parent) AND (c.id_category != :root_category_id) AND (c.id_category != :root_category_id) GROUP BY c.`id_category` ORDER BY position asc LIMIT 50 {     "context_lang_id": 1,     "context_shop_id": 1,     "root_category_id": "1",     "id_category_parent": 2 }
DEBUG08:16:15 | doctrine | SELECT COUNT(c.id_category) FROM ps_category c LEFT JOIN ps_category_lang cl ON c.id_category = cl.id_category AND cl.id_lang = :context_lang_id AND cl.id_shop = c.id_shop_default LEFT JOIN ps_category_shop cs ON c.id_category = cs.id_category AND cs.id_shop = :context_shop_id WHERE (c.id_category != :root_category_id) AND (c.id_parent = :id_category_parent) AND (c.id_category != :root_category_id) AND (c.id_category != :root_category_id) {     "context_lang_id": 1,     "context_shop_id": 1,     "root_category_id": "1",     "id_category_parent": 2 }
INFO08:16:15 | php | User Deprecated: The "$name" argument in method "Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector::__construct()" is deprecated since Symfony 4.2. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: The "$version" argument in method "Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector::__construct()" is deprecated since Symfony 4.2. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: __construct is deprecated since version 8.1 and will be removed in the next major version. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: The "Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent::getException()" method is deprecated since Symfony 4.4, use "getThrowable()" instead. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: The "Symfony\Component\Debug\Exception\FatalThrowableError" class is deprecated since Symfony 4.4. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: The "Symfony\Component\Debug\Exception\FatalErrorException" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\Error\FatalError" instead. {     "exception": {} }
CRITICAL08:16:15 | request | Uncaught PHP Exception TypeError: "stripslashes(): Argument #1 ($string) must be of type string, null given" at /var/www/prestashop/src/Core/Grid/Data/Factory/AbstractCategoryDataFactory.php line 77 {     "exception": {} }
CRITICAL08:16:15 | php | Uncaught Error: stripslashes(): Argument #1 ($string) must be of type string, null given {     "exception": {} }
