### ISSUE TITLE
Remove "Powered by PrestaShop" from emails

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#28723]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In [the latest news about PrestaShop 8](https://build.prestashop.com/news/prestashop-feature-freeze-v8/) I can see that one of the most important new feature is to "remove all dependencies to the company to make the project as neutral as possible".

I am not sure if this is directly related, but the first thing I thought when I read this news was about removing the `Powered by PrestaShop` from PrestaShop emails.

But this text is still present in PrestaShop 8:

https://github.com/PrestaShop/PrestaShop/blob/cfeda5a14feb360235d01729bdda755378b66f7d/mails/themes/classic/components/footer.html.twig#L6

https://github.com/PrestaShop/PrestaShop/blob/cfeda5a14feb360235d01729bdda755378b66f7d/mails/themes/modern/components/footer.html.twig#L20

Is it something you forget or is it intentional?

### Expected behavior

Emails should not display `Powered by PrestaShop` anymore in the footer.

### Steps to reproduce

1. Do any action that result into sending an email (eg: complete an order)
2. See the `Powered by PrestaShop` text in the footer of the email

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by matks** [comment]
> Is it something you forget or is it intentional?

It is not something we forget
it is not something intentional

It's just that there is hundred of links like this everywhere in the project and it takes weeks to modify them all. I'm quite sure if you look around you will be able to find more.

If you want to help I think we can replace link to prestashop.com by link to https://www.prestashop-project.org/ . But I don't think the text "Powered by prestashop" should be removed: prestashop will be neutral. PrestaShop SA is not neutral

**Comment by florine2623** [comment]
Hello @Seb33300 ,

Thank you for your suggestion. 

Do not hesitate to create a Pull Request if possible ^^

Thank you

**Comment by Hlavtox** [comment]
@matks Another point of view to consider that is related to this - a good safety measure is to remove traces of signs that reveal the platform used, so malicious servers of users have harder time detecting your software and abusing it.

**Comment by matks** [comment]
> @matks Another point of view to consider that is related to this - a good safety measure is to remove traces of signs that reveal the platform used, so malicious servers of users have harder time detecting your software and abusing it.

Security by obsfucation 😉 😛 

I think removing the "powered by prestashop" wording is something easy to do for users wanting to do it ^^ and I'm afraid hacking tools have systems able to detect what is your CMS far more performant that looking for the name of the CMS

(also here we're talking about email templates, so bots scrapping websites are out of topic)

I would be sad to see this little "Powered by PrestaShop" go because I'm proud of that work ^^ but if you guys really want it to be gone we can ask Product team about that

**Comment by MatShir** [comment]
Nice catch @Seb33300 here, if you see more links don't hesitate to share them. 
Here we have 2 options:
1. Remove definitely the wording and links 
OR
2. Put the project link. 
We will decide between @PrestaShop/prestashop-maintainers the best solution, we will keep you in touch :)

**Comment by eternoendless** [comment]
PrestaShop is the project's name (not to be confused with PrestaShop SA), which is why I think it's perfectly legitimate to leave it there. The link should be updated though, as pointed out by @matks.

**Comment by NeOMakinG** [comment]
I guess it can be closed by https://github.com/PrestaShop/PrestaShop/pull/28949

If you find any other mail that we forgot, don't hesitate to open the issue again!
