### ISSUE TITLE
Duplicated Invoice Number

### ISSUE THREAD

**Issue by la-lisa** [PrestaShop/PrestaShop#28757]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If several orders are placed at exactly the same time, the invoice number (in ps_order_invoive) will be duplicated. As a result, the customer will see an invoice from another customer. This is a big problem from a privacy point of view. Please urgently for a solution! 

The problem occurs in the Order.php at the function setLastInvoiceNumber, because there the last number is queried and then +1 is added. With two simultaneous queries it happens that the same number is assigned twice. 

`if ($number) {
            $sql .= (int) $number;
       } else {
            $getNumberSql = '(SELECT new_number FROM (SELECT (MAX(`number`) + 1) AS new_number
                FROM `' . _DB_PREFIX_ . 'order_invoice`' . (Configuration::get('PS_INVOICE_RESET') ?
                    ' WHERE DATE_FORMAT(`date_add`, "%Y") = ' . (int) date('Y') : '') . ') AS result)';
           $getNumberSqlRow = Db::getInstance()->getRow($getNumberSql);
           $newInvoiceNumber = $getNumberSqlRow['new_number'];
           $sql .= $newInvoiceNumber;
        }`

### Expected behavior

The Order Invoice Number must be Unique!

### Steps to reproduce

Place two Orders in the exact same time.

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by hibatallahAouadni** [comment]
Hello @la-lisa 

Your issue is duplicate of this one #23025
And as you can see in this comment https://github.com/PrestaShop/PrestaShop/issues/23025#issuecomment-768980463 I didn't manage to reproduce the issue.
Please check and feedback.

Thanks!

**Comment by la-lisa** [comment]
As described above, it happens under certain circumstances when in the database the query` SELECT (MAX(number) + 1) AS new_number`, returns the same value. E.g. if the operations for the two different orders are executed almost at the same time, or one takes a little longer. 
It's hard to recreate this problem under artificial circumstances, but we have this problem every month with a customer with a lot of orders - this is a privacy issue and needs to be fixed somehow. The issue exists and is not due to another module - we crosschecked it on a clean PS1.7.8.6 instance and the issue is there too.

I can attach you a screenshot with the duplicated order numbers - but that will not help to reproduce the issue!

**Comment by hibatallahAouadni** [comment]
Hello @la-lisa 

> The issue exists and is not due to another module - we crosschecked it on a clean PS1.7.8.6 instance and the issue is there too.

So, could you please provide a clear and concise steps to reproduce the issue and a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by la-lisa** [comment]
Steps:
1. Customer 1 hits the "Place Order" Button in the Checkout - Order is placed in the backend (page is loading - payment actions are taken)
2. Customer 2 hits the button during the loading Page of Customer 1 and his Order is placed and payment loads
3. Customer 1 can view his Invoice - he sees the right one
4. Customer 2 can view his Invoice - he sees the invoice of customer 1 because the invoice number ("number" colum in ps_order_invoice) is the same for both orders

Or:
1. Customer 1 hits the "Place Order" Button in the Checkout - Order is placed in the backend (page is loading - payment actions are taken)
2. Employee of shop owner changes the status of a wirepayment order of Customer 2 during the page loading of customer 1, to "Payment Accepted" and an Invoice is generated.
3. Customer 1 can view his Invoice - he sees the right one
4. Customer 2 can view his Invoice - he sees the invoice of customer 1 because the invoice number ("number" colum in ps_order_invoice) is the same for both orders

I will try to capture it in a screen recording the next week.

But as more people were reporting this same issue already, I think this is not only a problem of our system.

**Comment by florine2623** [comment]
Hello @la-lisa ,

In my case, I can't really reproduce your issue. It was tested on PS 1.7.8.6.

My 2 orders have been placed without issue. I can see the 2 emails to my 2 different customers. In my BO, the 2 orders have different reference and IDs.

Order 1 :
<img width="524" alt="Screenshot 2022-06-24 at 16 45 25" src="https://user-images.githubusercontent.com/16019289/175559910-3274c1e2-e54b-455d-8886-b2cd6f16e5d9.png">


Order 2 :
<img width="530" alt="Screenshot 2022-06-24 at 16 45 30" src="https://user-images.githubusercontent.com/16019289/175559957-a6e7f0be-6537-4811-ad00-136bb780c91d.png">

In the BO :
<img width="1029" alt="Screenshot 2022-06-24 at 16 46 38" src="https://user-images.githubusercontent.com/16019289/175560068-a5d925c1-291b-4607-8ec3-170c13bbd153.png">

There is just 1 sec of difference between the 2 orders. How is it in your case ? both have the exact same hour ?

Waiting for your feedback.
Thanks

**Comment by zubco** [comment]
@la-lisa, @florine2623 I can confirm occurrences of that issue too. In our shop's DB I discovered 94 cases of duplications and even a case of triple repetition. In a span of 3 years. 
And this issue is old one, not specific to 1.7.8.x. 
In our case is 1.7.7.6, before middle 2021 it was 1.7.2.4.

@florine2623 please don't ignore or close this issue like in case of [#23025](https://github.com/PrestaShop/PrestaShop/issues/23025)
From ONE human physic perspective is not possible manually reproduce this, because orders should be performed in the same second. For this should be used some automation tests or request some assistance of a PS developer.

In my opinion this is CRITICAL issue, that in some cases may imply legal consequences for shop owners.

**Comment by HanaRebaiQA** [comment]
Hello @zubco 

Thanks for your feedback.
Could your please provide us a screen-record to help us to reproduce the issue.

Waiting for your feedback.

Thank You!

**Comment by zubco** [comment]
This issue is described also in #11115, 3 years old. With a lot of details.

Don't want to be rude, but kind of issue is not one you can just reproduce by willing to "record".
But I am sure consequences of this issue is present in every DB of sites that runs on PrestaShop.

Quotation from mentioned issue: 
> the logic of invoice number generation that is prone to race conditions issues

**Comment by la-lisa** [comment]
@zubco thanks for helping me out here! The issue is really hard to reproduce.

Unfortunatelly i can't provide a screenrecording because it is not that easy to reproduce alone. In #11115 there is a also a very precise description of the problem and one of you contributors already states that there is a problem with the MAX() call.

**Comment by sLorenzini** [comment]
hello @la-lisa,

Thank you for your feedback.
I couldn't reproduce the issue. Invoice Number is not duplicate

Fresh install of 1.7.8.6, PHP 7.3.
Here's my screenshots:

![01-orders](https://user-images.githubusercontent.com/2854834/178265758-c9baf003-46c3-4788-9c8b-d9b33bcb0e67.png)

Order 1:

![02-orders](https://user-images.githubusercontent.com/2854834/178265815-9677cc35-4adb-4c25-b6c1-4865113f62b0.png)

![04-orders](https://user-images.githubusercontent.com/2854834/178265909-60b28808-2385-42b8-85bc-50fc09186f44.png)

Order 2:

![03-orders](https://user-images.githubusercontent.com/2854834/178265835-a5fea130-b59b-467a-b497-c87392b07dea.png)
![05-orders](https://user-images.githubusercontent.com/2854834/178265925-24d7cc44-63ef-4357-bfc3-d42221d5bf95.png)

Sorry again for this question but could you provide us a screenrecord please 🙏?

Waiting for your feedback

Thank you

**Comment by la-lisa** [comment]
@sLorenzini as I wrote above screenrecording is not possible. I cannot share customer data in a screenrecording. And the problem is not that easy to reproduce.

**Comment by hibatallahAouadni** [comment]
Hello @la-lisa 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

We will close this issue.

Thanks!

**Comment by josecarlosphp** [comment]
I've seen this occurs, two invoices (different orders) having same number. Both invoices are generated at the same moment (same date_add), so I guess the query to obtain the current max number returned same value... Yeah, it's a great coincidence, but in a shop with a lot of orders maybe it occurs.

In the shop I'm talking about there are 7 duplicated invoice number in the last 7 months, so an average of 1 per month. Invoices with same number were generated at the same time. This is not a joke.

I take this opportunity to comment that the billing management in PrestaShop is painful, it drags things wrong from very old versions.

**Comment by la-lisa** [comment]
@josecarlosphp unfortunatelly the issue was again closed by prestashop. Because the issue is not that easy to reproduce - but i also have more than 10 duplicated invoice numbers in our shop. Which is a very big issue, especially for data security.

**Comment by josecarlosphp** [comment]
> @josecarlosphp unfortunatelly the issue was again closed by prestashop. Because the issue is not that easy to reproduce - but i also have more than 10 duplicated invoice numbers in our shop. Which is a very big issue, especially for data security.

Sure, not easy to reproduce, but easy to imagine... Sometimes it isn't needed to reproduce an issue to understand it, and then solve it. "Most likely a module problem", it makes me laugh. And here comes PrestaShop 8.0 from 1.7 XDDD, the word you're looking for is: commercial.

**Comment by Kinematix** [comment]
One of my clients notified me of this problem on his website in a fresh PS 1.7.7.8. In this case there are 3 invoices with the same ID and delivery note (client data is OK, issue is just regarding the invoice ID and the delivery note) but each order was placed in different days (13, 14 and 15 January 2023) and they are not correlative (first order is 2373, second is 2374 but the third one is 2376).

![PRESTASHOP_DUPLICATED_INVOICE](https://user-images.githubusercontent.com/7861764/212727393-d133c2e3-408b-43f6-a537-81f990a3ac89.png)

This is not a a module problem. I'm checking other websites from my clients with versions from 1.7.6.5 to 1.7.7.8 and all of them are suffering this critical (due to finance regulations) problem. There are sites without common modules and with different themes affected by this bug.

Please, priorize this. This is not a joke and can have a high negative impact in bussiness accounting.

**Comment by josecarlosphp** [comment]
PrestaShop looks for commercial light instead of improve too old bad done things.
Ironically, if those things were improved, it would do better commercially, and preventing people from moving to WooCommerce or whatelse.

**Comment by SylvainSimonGPA** [comment]
Hello i come with a way to reproduce easily !

From ANY version of Prestashop from 1.7.7.2 (mine) and 8.0.*

In method `setLastInvoiceNumber` in
`classes\order\Order.php`

The request is following :
`SELECT new_number FROM (SELECT (MAX(number) + 1) AS new_number`

Its atrocious way to find the last available number because this method don't lock any other process concurrent executing an order integration at the same time to get the SAME maximum number.

For reproduce, you just can put here, before executing the insert request, a `sleep()` juste before the `Db::getInstance()->execute($sql)`. When you validate the first order the sleep start, and then, validate another order in same time. The two order validation get the same maximum number....

This case is occured in production for my company !

We patched our prestashop by overriding `setLastInvoiceNumber` with a request who select in a created separate sequence
`CREATE SEQUENCE ps_sequence_invoice_number START WITH 100000;`

AND get next number by
`SELECT NEXT VALUE FOR ps_sequence_invoice_number;`

Any hope to see a fix of this kind in Prestashop base code ?
A good system for locking invoice number...

**Comment by Ybeske** [comment]
Same problem here. 19 double invoice numbers in one year. All cases were created on orders at the exact same time. I hope this security and privacy issue will be solved by building an extra condition. Any news about this bug?

**Comment by Dreimus** [comment]
> Hello i come with a way to reproduce easily !
> 
> From ANY version of Prestashop from 1.7.7.2 (mine) and 8.0.*
> 
> In method `setLastInvoiceNumber` in `classes\order\Order.php`
> 
> The request is following : `SELECT new_number FROM (SELECT (MAX(number) + 1) AS new_number`
> 
> Its atrocious way to find the last available number because this method don't lock any other process concurrent executing an order integration at the same time to get the SAME maximum number.
> 
> For reproduce, you just can put here, before executing the insert request, a `sleep()` juste before the `Db::getInstance()->execute($sql)`. When you validate the first order the sleep start, and then, validate another order in same time. The two order validation get the same maximum number....
> 
> This case is occured in production for my company !
> 
> We patched our prestashop by overriding `setLastInvoiceNumber` with a request who select in a created separate sequence `CREATE SEQUENCE ps_sequence_invoice_number START WITH 100000;`
> 
> AND get next number by `SELECT NEXT VALUE FOR ps_sequence_invoice_number;`
> 
> Any hope to see a fix of this kind in Prestashop base code ? A good system for locking invoice number...

Thanks for your reply, we will try your option.

To anyone who will try to use this method, please be aware that SEQUENCES instruction is not natively supported on MySQL 5.6. You need at least MySQL 8.0.3, or MariaDB 10.3 to use this instruction.

**Comment by vbled** [comment]
When I batch generate invoices for my system's backend order list, I find that many invoices with the same number are generated. My invoice number setting is reset the invoice number every year.  So the ps_orders.invoice_number will have two duplicates numbers, I can not set the invoice_number to auto increament.
