### ISSUE TITLE
Debugging bar covers some elements 

### ISSUE THREAD

**Issue by Sasni** [PrestaShop/PrestaShop#28783]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

debugging bar partially covers some elements, for example when editing a product it partially covers the bottom bar (product-footer class) 

![image](https://user-images.githubusercontent.com/3370929/174397849-ad70ebb1-d553-4f0d-98b5-1968b3e62a5b.png)

### Describe the solution you'd like

I meant to replace "bottom: 0" with "bottom: 37px" in case debug mode is enabled.
Move product-footer in debug mode 37px higher
```
.product-page .product-footer {
    bottom: 37px;
}
```

![image](https://user-images.githubusercontent.com/3370929/174398123-fc459bd4-7ad8-48e7-a2dc-1396b73bb68a.png)

**Comment by AureRita** [comment]
Hi @Sasni , 

Thank you for your reporting, currently we can't put the footer with 37px on the bottom because, as you can see, this is not a real good position : 
![image](https://user-images.githubusercontent.com/100699445/174583764-45b1e27b-5f86-48f2-8f4a-5239ea97aea7.png)

If it's only the debugging bar that you want hide, you can click on the cross, like this 

https://user-images.githubusercontent.com/100699445/174584494-e0314939-ef66-4b7e-87a3-2bcf3dd2bede.mp4

Otherwise, if you really want to have a slide of the footer when you've the debugging bar displayed, we can see with the dev team to do it, and it will be treated like a feature, 

Can you tell me if this answer help you or you're waiting for this new feature ? 

Waiting for your feedback

**Comment by Sasni** [comment]
Hi @AureRita I think in your example you removed the "bottom" entry from the CSS  
your example: 
![image](https://user-images.githubusercontent.com/3370929/174590016-0a03205a-e7db-47e7-a597-835fb3bd4b95.png)
I meant to replace "bottom: 0" with "bottom: 37px" in case debug mode is enabled. 
![image](https://user-images.githubusercontent.com/3370929/174590258-f47635eb-9935-4481-84bc-e2a6326c5215.png)
I reported this because I was hoping it might have a positive effect on the look of the admin panel. 
It is not essential to my life :) Your proposal is satisfactory and sufficient. 
If obscuring elements was the original design intent, then mark my submission as invalid.

**Comment by hibatallahAouadni** [comment]
Hello @Sasni 

> I meant to replace "bottom: 0" with "bottom: 37px" in case debug mode is enabled.

It seems to me as a feature more than a bug.
Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: waiting for your PR :rocket: 

Thank you
