### ISSUE TITLE
Products disappear when user disconnects

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#28793]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

I recently upgraded my prestashop version from 1.7.8.5 to 1.7.8.6 where I encountered the following problems:

1. Products disappear when the user disconnects
2. Difference in price (4€) for users who connects and disconnects
For ex: for visitors, the price is 20€ but for the clients the price is 24€

I have verified the Client parameters where everything seems to be normal.

Any solution ?

Regards,
Gaja

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by AureRita** [comment]
Hi @Gaja-A 

Thank you for your reporting, I tried to understand your problem, but currently, in your video, you've many prices that didn't follow the same rules, can you fake a purchase to see if it's the same price at the end ( the difference it's maybe because some person see the prices with taxes and the other not ). 

About the first point : " Products disappear when the user disconnects " it's maybe because it's the "suggestion" page and it will always change in relation to the person ( what they bought before ) and the suggestion always change, it's not the popular product 

If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

Can you tell me if this answer help you or not ?

Waiting for your feedback
Thanks

**Comment by Gaja-A** [comment]
Hi @AureRita ,

The difference it's maybe because some person see the prices with taxes and the other not - but I display TTC for all (Visitors, Invites and Client)

How should I display same price for all ? Is there any configuration to do ?



About the first point : " Products disappear when the user disconnects " it's maybe because it's the "suggestion" page and it will always change in relation to the person ( what they bought before ) and the suggestion always change, it's not the popular product

No, even the product disappeared in category page too.

Regards,
Gaja

**Comment by florine2623** [comment]
Hello @Gaja-A ,

Please change your admin folder name for security reasons, this is a public space !
I deleted your video where your admin is displayed.
Do not hesitate to supply written Steps to reproduce ^^

Thanks!

**Comment by Gaja-A** [comment]
Hi @florine2623 ,

Sorry for that.

Here is the configuration of my group: Visitor and Client where they both have the same parameters but in site there is a price difference for clients and visitors.

![visitor](https://user-images.githubusercontent.com/51961329/174751627-353e06b2-75db-4e01-adcb-7184434d01ef.PNG)
![client](https://user-images.githubusercontent.com/51961329/174751635-c982c3e9-899a-4233-972f-9d4060fbe084.PNG)

And even the catalog disappears when they disconnect.

**Comment by Gaja-A** [comment]
Hi @florine2623 ,

I solved the pricing problem by reworking the tax rules.

For the catalog, I found something strange that works.

Normally, the products are not visible for visitors in the front, but when I click on the SAVE button in BO, then they show up for visitors.

Is there any configuration that needs to be done?
I cleared the browser & PrestaShop cache.

Regards,
Gaja

**Comment by hibatallahAouadni** [comment]
Hello @Gaja-A 

Thanks for your all feedbacks!
> Is there any configuration that needs to be done?

No idea, cause I didn't reproduce the issue :disappointed: but if you import your products by webservice, then may be it's related to #28586

Thanks!
