### ISSUE TITLE
BO - Products V1- The alert is duplicated when we create a product is a too long/too short name 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28877]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we create a product with a too-long/too short name, the alert is duplicated
![image](https://user-images.githubusercontent.com/16067358/175986731-2d9b1a78-9425-41cb-8ddf-364645e9c7c5.png)
![image](https://user-images.githubusercontent.com/16067358/176129705-c6443870-5a94-4859-a78b-f616f421162b.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/175986808-2b056375-1c3c-4040-bfab-c32399ae7b5e.png)

### Steps to reproduce

1. Go to BO > Catalog > Products V1
2. Add a product with a long name (more than 128 characters)
3. Save
4. See error: the alert is duplicated

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
@yanmakouf started it

**Comment by yanmakouf** [comment]
I just have a question for the error message in case of blank field. The expected behavior is "This value should not be blank.
This value is too short. It should have 3 character or more." or just  "This value should not be blank." or maybe something else ?
[https://user-images.githubusercontent.com/16067358/176129705-c6443870-5a94-4859-a78b-f616f421162b.png](url)

**Comment by MeKeyCool** [comment]
I can't test those commits so I don't know which one introduced the bug but I am quite sure the problem comes from one of them :
- [Update dependencies to make it work with Symfony 4.4](https://github.com/PrestaShop/PrestaShop/commit/7eb3edd57db41c99ef53c3195067a49ec357fa97)
- [Rename ObjectModel Attribute to ProductAttribute](https://github.com/PrestaShop/PrestaShop/commit/f0bbc632cd048dbc3efdbdf3e83b4b282cd5fe80)
- [Fix symfony 4.4 issues](https://github.com/PrestaShop/PrestaShop/commit/4ce82803e7a3708afa7faa7524f2e18e2f6b6c13)

Only the last one looks to have changed something about translations (`Inflector` and some changes with `$form` validation.

I think it should be a good starting point for further investigations ^^

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29584
