### ISSUE TITLE
COD v2 module displays it's order confirmation template everywhere

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#28882]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The COD module v.2.0.0 (also 2.0.1) attaches itself to the displayOrderConfirmation hook. That causes it's tpl file to be displayed for every other payment method (bankwire etc.).
![COD-bug](https://user-images.githubusercontent.com/5658940/176132270-31841ebe-fa61-4818-b698-56d6c49b22a6.png)

### Expected behavior

COD module's order confirmation message should appear only if the chosen payment is COD.

### Steps to reproduce

1. Place a bankwire order on a shop with the COD module installed.

2. Observe the order confirmation page to see the wrong message at the top, and correct message at the bottom.

### PrestaShop version(s) where the bug happened

1.7.x.x

### If your bug is related to a module, specify its name and its version

ps_cashondelivery v.2.0.0 & v.2.0.1

**Comment by Hlavtox** [comment]
It's because this module uses `hookDisplayOrderConfirmation`, which shows all hooked modules. https://github.com/PrestaShop/ps_cashondelivery/blob/eae8d15f1a16c8dc2cafd3bfba904e0372524992/ps_cashondelivery.php#L101

For example `ps_wirepayment` uses `hookDisplayPaymentReturn`, which returns only the payment module for the order and no further checks are needed.
https://github.com/PrestaShop/ps_wirepayment/blob/72d5e83ab67d5abfc16341e9b46ad3bceef7bff9/ps_wirepayment.php#L208

**Comment by daresh** [comment]
Exactly, I wonder why this module got changed from paymentReturn to displayOrderConfirmation hook...

**Comment by Matt75** [comment]
> Exactly, I wonder why this module got changed from paymentReturn to displayOrderConfirmation hook...

Because many customer doesn't see information in `displayPaymentReturn` because they have to scroll down, especially when Order summary is displayed before `displayPaymentReturn`

![image](https://user-images.githubusercontent.com/5262628/176152736-c8dcda26-888d-4ee2-9dac-63f5a6d80544.png)
Customer should scroll down to see `displayPaymentReturn` in this case

**Comment by daresh** [comment]
So maybe a general solution would be to put the paymentReturn higher above the items? Other modules may still be using it.

**Comment by Hlavtox** [comment]
I changed this in hummingbird. Payment info is now shown directly under the confirmation message.

**Comment by Hlavtox** [comment]
![localhost_prestashop_order-confirmation_id_cart=56 id_module=42 id_order=20 key=739725a4772960b65cfc198993a25b7b](https://user-images.githubusercontent.com/6097524/176154395-c4f0e2eb-7abb-4000-9893-45d55a585a79.png)

**Comment by daresh** [comment]
Great you did that, but the COD module needs to be fixed either way.

**Comment by Matt75** [comment]
In fact `displayOrderConfirmation` hook is more accurate to display information of `ps_cashondelivery` module because it's only **few** additional information.

`displayPaymentReturn` hook has to be use when module needs to display **detailed** additional information to customer or when customer has to performs action to finalise payment process.

In this case it should be currently used in pair with `displayOrderConfirmation` to notify customer to scroll down to see additional information about his payment.

Changes of @Hlavtox on `hummingbird` theme are interesting because it avoid to do like above and we could use `displayPaymentReturn` every times 👍.

What I explained above is more for PS 1.6 & 1.7 due to order summary that takes too much space above `displayPaymentReturn`...

**Comment by daresh** [comment]
Great, but on the displayOrderConfirmation hook the COD module needs to check if the payment for order is COD. Currently it gets displayed everywhere, which is clearly a big bug.

**Comment by Matt75** [comment]
> Great, but on the displayOrderConfirmation hook the COD module needs to check if the payment for order is COD. Currently it gets displayed everywhere, which is clearly a big bug.

You can found the PR here : https://github.com/PrestaShop/ps_cashondelivery/pull/48

**Comment by hibatallahAouadni** [comment]
Hello @daresh 

Thanks for reporting the issue!
And thanks guys for yoru quick replies @Matt75 & @Hlavtox :muscle: 
Thanks again @Matt75 for your PR :rocket: 

I was able to reproduce the issue with PrestaShop version 1.7.6.7, PS1778, PS1786 and develop. I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by Hlavtox** [comment]
@Matt75 BTW, do you think we can simplify the hooks on that page?

**Current situation on order confirmation page in hummingbird:**
- Your order is confirmed
- `displayPaymentReturn`
- `displayOrderConfirmation`
- Order details
- Guest conversion
- `displayOrderConfirmation1`
- `displayOrderConfirmation2`

I think we can simplify the bottom hooks to `displayOrderConfirmationBottom` and make the old ones aliases.

ping @PrestaShop/prestashop-maintainers

**Comment by Matt75** [comment]
I never used `displayOrderConfirmation1` and `displayOrderConfirmation2` 👀
Probably introduced on 1.7 ? 

Btw I think order confirmation page is bad and should be reworked 😄

**Comment by Hlavtox** [comment]
@Matt75 Yeah, I think its a 1.7 thing, it's not even in the install xml 🤔.

Go try hummingbird dude, I think you will be happy.

**Comment by NeOMakinG** [comment]
Fixed already

**Comment by jolelievre** [comment]
Indeed, bug from github the PR has been merged in the history but not closed:
<img width="1249" alt="Capture d’écran 2022-07-01 à 15 42 40" src="https://user-images.githubusercontent.com/13801017/176906610-467ac26a-4213-4248-9f4e-707d4729b94b.png">
