### ISSUE TITLE
Redundant function in ps_googleanalytics module - class Hook

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#28905]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

In https://github.com/PrestaShop/ps_googleanalytics/blob/dev/classes/Hook/HookDisplayHeader.php#L153-L167, we have 2 functions just to do a simple assignment. 
Looking back to the releases history, I found it came from the last commit of @matks before release v4.1.0  https://github.com/PrestaShop/ps_googleanalytics/commit/a4d4c9fc9d4a82cab2fdd1027c10b178ac4f3549#diff-3730c736a8503cccf13f7c3de6297fc96cde9872c50fc90988df1abafa5e8930R107

### Describe the solution you'd like

 Assign directly in function setBackOffice 
```
    public function setBackOffice($backOffice)
    {
        $this->backOffice = $backOffice;
    }
```
Remove function acknowledgeBackOfficeContext

back to what version 4.0.0 used to be.

function acknowledgeBackOfficeContext is not used elsewhere so it is safe to remove it.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Otherwise, we're waiting for your PR :rocket: 

Thank you

**Comment by leemyongpakvn** [comment]
Close due to Backward Compatibility concern as discussed in the PR.

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback!
