### ISSUE TITLE
BO - A bad display of buttons in combinations tab with product page V2 when multistore enabled

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28934]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A bad display of buttons in combinations tab with product page V2 when multistore enabled
![image](https://user-images.githubusercontent.com/92912932/176925853-0d6f85e0-6bff-4a86-afe4-5fc3e3ffafc8.png)

![image](https://user-images.githubusercontent.com/92912932/176925874-ec5c9800-103b-4c13-83b0-9ce13520c995.png)

### Expected behavior

The buttons are well displayed

### Steps to reproduce

1. Enable multistore and create a new shop
2. BO > Advanced Parameters > New & Experimental Features > Enable new product page 
3. Create a product with combinations
4. Click to generate a new combinations
5. See error >> the buttons (edit, delete, radio) are bad displayed

### PrestaShop version(s) where the bug happened

8.0.x, 8.0.0

### PHP version(s) where the bug happened

7.2

**Comment by thomasDelaporte** [comment]
@HanaRebaiQA 

The problem comes from the text underneath "Apply changes to all stores" which takes a definite 
space of minimum 200px. 

However, if we remove this specificity we end up with quite high lines.
![image](https://user-images.githubusercontent.com/55890466/181736735-4e5ba2c6-1153-4660-ab8d-17a02349e04d.png)

I also tested something like this:
![image](https://user-images.githubusercontent.com/55890466/181736711-727fabdd-f991-483c-983f-383b4adf51dd.png)

Would we have mock-ups (figma) to see what was planned?

**Comment by TristanLDD** [comment]
hi @thomasDelaporte 

If we could display the "Apply changes to all stores" checkbox only when the user starts to edit one of the fields, it would save us a lot of space. The check box will then appear only in edition mode:

<img width="959" alt="Capture d’écran 2022-12-15 à 16 45 29" src="https://user-images.githubusercontent.com/27484094/207905208-72fe3ec5-7d38-42ea-8c96-cdee6b1e77fc.png">

Also, we can't align that checkbox with the quantity field because it gives the message that it only applies to this field, while it apply to all the fields of the line

**Comment by MatShir** [comment]
blocked by https://github.com/PrestaShop/PrestaShop/pull/30590

**Comment by jolelievre** [comment]
The edition in the combination list doesn't handle the multishop checkbox, so this one should simply be removed in this case

**Comment by jolelievre** [comment]
This appears to have been fixed already
