### ISSUE TITLE
Unable to save a single supplier for a product with combination  

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29006]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you try to save a single supplier associated for the product with combinations, an error will be displayed.

https://user-images.githubusercontent.com/90208051/177954182-699fbb59-7e92-414a-b6ef-f79da63563bb.mp4

### Expected behavior

It should be saved without errors 

### Steps to reproduce

1. Select product with combinations in BO
2. Open "Options" tab
3. Select all the suppliers and save
4. Unselect all suppliers except the default one
5. Save
6. See error: Enable to update settings.  

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by thomasDelaporte** [comment]
Hi, I wanted to experiment a bit with this problem and I’m not confident enough with the project code to do PR yet but if I can give my opinion:

The problem could comes from the `Assert\NotBlank` constraint on the `product_price` field of the Suppliers list which is defined in `ProductSupplierCombination::buildForm`.

Since the form to validate the data is created from the initial data, it tries to rely on it to validate future data. In our case if we had 3 suppliers checked at default then we remove 2, it will look for 3 * (number of combination) product prices while there is only (1 * number of declination0) in POST data.

This can be easily solved by allowing the null value in the constraint like this, but I doubt it’s robust enough.
`new Assert\NotBlank(['allowNull' => true]),`.


If you are looking for the creation of the form for suppliers selection, it's done in `ProductOptions::buildForm` line 231.

**Comment by MeKeyCool** [comment]
I take this issue.
@thomasDelaporte , do you want we try to work together on it ? ^^ I am sure your analysis may help :)

**Comment by thomasDelaporte** [comment]
> I take this issue. @thomasDelaporte , do you want we try to work together on it ? ^^ I am sure your analysis may help :)

I let you try and I will check your solution :) good luck.

**Comment by MeKeyCool** [comment]
It looks that the regression is linked to https://github.com/PrestaShop/PrestaShop/pull/26609

**Comment by NeOMakinG** [comment]
Related to `ps_mbo`, I'll keep the issue opened until we get a response from the MBO team on what we should do in order to fix this!

For reference: https://github.com/PrestaShopCorp/ps_mbo/issues/217
