### ISSUE TITLE
FO - An exception is displayed when creating an address with italian country

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29012]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Could be related to https://github.com/PrestaShop/PrestaShop/issues/28781
In the FO > When we try to create an address with an Italian country, an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/177974456-b161e9cd-b3be-4e53-b3d2-c28f94800b47.png)

### Steps to reproduce

1. Go to BO > International > Localization page & Import the italian pack
2. Go to BO > International > Locations > Countries tab & edit the Italian country
3. Enable `Do you need a tax identification number?` and save
4. Go to BO > Addresses page
5. Select dni as a required field
6. Go to FO > Create an address with the Italian country
7. See error 
8. Go to FO > Add a product to the cart and proceed to checkout
9. In the Addresses tab, create an address with the Italian country
10. See error

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.2, 7.3

**Comment by matks** [comment]
@yanmakouf takes it

**Comment by yanmakouf** [comment]
Hello @PrestaShop/qa-team, I am not sure about the expected behavior here. As i understand it, once I set the DNI required and VAT required in the parameters, then the expected form when selecting country italia, should display a DNI required text field, and a required VAT text field. Am I getting it right ?

**Comment by ghost** [comment]
Hello @yanmakouf i am not sure but i think it's also related. https://github.com/PrestaShop/PrestaShop/issues/28781

The required fields in BO are no longer displayed in FO?

**Comment by yanmakouf** [comment]
Hello @okom3pom, they are displayed in the FO as far as I can see. https://github.com/PrestaShop/PrestaShop/issues/28781https://github.com/PrestaShop/PrestaShop/issues/28781 is not related in my opinion. But I will check. 

@khouloudbelguith I think the problem comes from an inconsistency between BO/FO. I go to BO > Enable French and UK and Italy adresses in International > Localization page & Import. Then I go to BO > Addresses page and add DNI as a required field. As i Understand the DNI is now required for all adresses regardless of the country. 

Then when I go back to BO > International > Locations > Countries click edit on
 any country and save with no modifications i get this error -> ![Capture d’écran 2022-07-20 à 15 25 32](https://user-images.githubusercontent.com/55691343/179993822-bb48f2b2-ff33-45c7-bd99-c27fe492f37c.png)

If I go to FO and follow the "Steps to reproduce" step 6 to 10. I get the error drecribed in the issue.

Then when I go back again to BO > International > Locations > Countries click edit on
 any country add  "dni" in the "adresse format" field. Then I can save succesfully. And back to FO everything seems ok. =>
![Capture d’écran 2022-07-20 à 15 31 30](https://user-images.githubusercontent.com/55691343/179994946-62add05d-1d1f-4a84-b619-ce0a10080a04.png)

**Comment by yanmakouf** [comment]
Ok I got it, it is the JS that doen't reload correctly the form fields. If you arrive first time on the adresse page (FO) and the default selected country has vat et dni in the BO, you will have the corresponding field in the form, and everything is ok. but if you arrive first time and switch country (to one with different settings) then the form is not updated. So @okom3pom was right and it is totally related to https://github.com/PrestaShop/PrestaShop/issues/28781https://github.com/PrestaShop/PrestaShop/issues/28781

So i am now tryin to find a fix ;)

**Comment by ghost** [comment]
Glad we could help you. I did not succeed on my side.

Ready to review your PR

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29122
