### ISSUE TITLE
Order page in BO > partial refund block, bad displaying of products “Quantity” field 

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29050]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Screenshot from 2022-07-12 12-03-20](https://user-images.githubusercontent.com/90208051/178486709-5e7c48ba-9de0-4191-ae65-4c4b5fc5a102.png)

### Expected behavior

As in previous versions
![Screenshot from 2022-07-12 14-10-49](https://user-images.githubusercontent.com/90208051/178486745-c6d114d2-5d56-4578-9e0e-508469e80116.png)

### Steps to reproduce

1. Open some order page in BO
2. Click on "Partial refund" button
3. Check “Quantity” field 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @szavadskiy 

Thanks for reporting the issue :rocket: 
I only reproduce the issue with PS8.0.x, so indeed it's a regression on 8.0.x!
I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by FabienPapet** [comment]
Looks like it's related to https://github.com/PrestaShop/PrestaShop/issues/28892 i'll have a look

**Comment by ghost** [comment]
@FabienPapet I just did a PR

**Comment by zuk3975** [comment]
It requires some styling changes, because if the number is bigger, the refundable quantity div jumps down anyway.
![Screenshot from 2022-07-25 15-44-54](https://user-images.githubusercontent.com/31609858/180780353-e680862c-eb93-4921-b40d-d096fb71cfea.png)
![Screenshot from 2022-07-25 15-42-24](https://user-images.githubusercontent.com/31609858/180780199-3d1fa555-2c0b-4d04-9a1e-c146523fe7ed.png)

**Comment by ghost** [comment]
@zuk3975 It's the same in 1.7.8.6. But it's possible @NeOMakinG can help me for that and we don't need to open a new issue

**Comment by hibatallahAouadni** [comment]
Hello guys,

Thanks @zuk3975 for your tip, indeed the bug exist since 1786 but only with bigger numbers (like you said):

PS 1.7.8.6:

![image](https://user-images.githubusercontent.com/23308427/181462998-48b067c7-a724-45cf-a6d1-971f49469307.png)

While with PS 8.0.0, nothing works :disappointed: 

![image](https://user-images.githubusercontent.com/23308427/181463107-4d533e41-8eca-432a-a948-be5b638f53c4.png)

So, @MatShir we should fix the issue on which branch? 1.7.8.x or 8.0.x or develop?

Thanks!

**Comment by MatShir** [comment]
in 8.0.x should be enough since it only for big number in 1.7.8.x

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29060
