### ISSUE TITLE
Allow merchant to set a BCC recipient for emails

### ISSUE THREAD

**Issue by abramofranchetti** [PrestaShop/PrestaShop#29130]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

It often happens that merchants ask me to receive a copy of all the emails sent from the prestashop shop in their email box. This for many reasons: to keep copies of all messages over time, to verify that the messages sent are error-free and compliant with the graphics of the site, for customer assistance in order to have exactly what was sent to the customer at hand and therefore be able to respond to any disputes or questions.

### Describe the solution you'd like

The Mail::send method of the standard core class already provide the possibility to set an array of recipients. But that parameter can not be set anywhere. The ideal would be that the bcc parameter can be set somewhere in BO, probably in the standard email alert module.

### Alternatives you've considered

The required behavior can probably be achieved through certain settings of the email server, but often the merchant is unable, unable or unwilling to make these settings but simply prefers to have copies of the emails in a mailbox that he can set up.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by marwachelly** [comment]
Hello @abramofranchetti 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments.
Thanks for your PR!

Thank you :blush:

**Comment by matks** [comment]
Hello @abramofranchetti 

> The required behavior can probably be achieved through certain settings of the email server, but often the merchant is unable, unable or unwilling to make these settings but simply prefers to have copies of the emails in a mailbox that he can set up.

I'm sorry but ... as you said it yourself: this is something that can be done easily with server config, but some people don't want to use the server config. So the solution would be to implement in PHP a behavior that is already available in most mail server systems 😞 . Is it a good thing for the software? Is it a good thing to put inside prestashop a feature that will be less powerful, more expensive, and less configurable because some people don't use the right tool?

Imagine if tomorrow I tell you: "I want to create a 'dual screen' mode in PrestaShop back-offices because people sometimes want to see 2 pages of the BO next to each other. They could use 2 screens and each screen opens a tab, but some merchants are unable or unwilling to use 2 screens so I wish to implement dual screen inside PrestaShop".

Maybe I'm too opiniated, need more opinions @PrestaShop/prestashop-maintainers

**Comment by matks** [comment]
As explained here https://github.com/PrestaShop/ps_emailalerts/pull/117#issuecomment-1234512988 I close this topic
