### ISSUE TITLE
Delete the feature cache smarty MySQL

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29160]
**Description of the pb**
We need to remove the feature 'Caching type' - MySQL because it is unsafe and provides lower performance compared to file system cache.

**Solution**
 Delete the feature 'Caching type' -> MySQL in Advanced parameter > Performance.
 
 **Acceptance test**
 The feature is not displayed anymore in the selector and the code related is removed

**Comment by Hlavtox** [comment]
@ShaiMagal Bro can you provide your experience regarding mysql caching? Is it still needed for some clients? What were the reasons to use it on some installs?

**Comment by ShaiMagal** [comment]
@Hlavtox I already wrote you reasons to chat, so, why you don't paste it here...?

Yes, approximatelly 10% customers are using mysql cache, because with filesystem cache, they had problem most of times on home page, where changes don't appear automatically (like new products, etc) - only clear smarty cache works.

if they have mysql cache now, it is working good. with filesystem no.

There is more reasons, I don't remember, it is historical. But HP I remember very well.

Didn't have time to depth investigating this issue with filecache, so in years ago we switch to mysql and no problems with it anymore... Don't know if its related to prestashop theme, or core, or module...

EDIT 2023-01-21:
Mysql cache is really not needed at newer PS version, my original post was related to **PS 1.6 only**! I apologize, I forgot add this info.
**So, yea, removing mysql cache for newer PS version is correct way.**

**Comment by matks** [comment]
> Yes, approximatelly 10% customers are using mysql cache, because with filesystem cache, they had problem most of times on home page, where changes don't appear automatically (like new products, etc) - only clear smarty cache works.

We're sorry but we want to put this feature of the scope of PrestaShop 8.0.0 as we believe majority of users don't use it.

But for people who do rely on it 😉 they can simply revert our changes, it's not a lot of code to modify.
