### ISSUE TITLE
Update symfony to version 5.4

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29166]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Now that PrestaShop 8 is PHP 7.2.5 minimum compliant, we could update to the 5.4 version of Symfony regarding this, maybe.

### Describe the solution you'd like

Update Symfony version.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by PrestaEdit** [comment]
I link this to this comment, it could be usefull : https://github.com/PrestaShop/PrestaShop/issues/24111#issuecomment-1098951474

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it. 

If you or anyone else is willing to [contribute this feature](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) to the PrestaShop Project, the teams will be happy to help by ensuring that it fits well within the project. Please let us know if that is the case!

Here's a comment from @eternoendless : 
https://github.com/PrestaShop/PrestaShop/issues/20739#issuecomment-961777868

> We will likely do that in 9.0

Thank you

**Comment by matks** [comment]
We have in mind to do the upgrade to Symfony 5 for prestashop 9, as indicated 
https://github.com/PrestaShop/PrestaShop/issues/20739#issuecomment-961777868

But as we have no roadmap for prestashop 8.1 or 9.0 now I cannot guarantee it's going to happen. It's very likely 😄 .

**Comment by tom-combet** [comment]
I could try to make a PR for this, do you know how to display all deprecations of the Symfony project?
`bin/console debug:container --deprecations` is only available in 5.1+...

**Comment by matks** [comment]
@tom-combet please don't go into this big piece of work because we have no idea if we would approve it or not 😄 . You could always submit the PR but I would be sad if your work was wasted because we can't merge it soon :(

Changing symfony version will have a big impact to every kind of users, so we can't decide to change it before being sure this is something good for the project and in which version it's the right moment. Such a big impact must be discussed and approved before.

**Comment by jolelievre** [comment]
And especially we should only do this for the next major v9 since it will probably introduce some breaking changes. The develop branch targets version 8.1.
So it's for later ^^

**Comment by excitedbox** [comment]
If you install phpunit bridge once the symfony 4.4 based version of prestashop is released you can see exactly what needs to be done to upgrade to 5. So far I haven't had many breaking changes going from my Symfony 5 -> 6 projects.

At this point I am even considering if it may be easier to build a shopping cart based on Symfony 6 from scratch than waiting on any of the other Open Source projects. Because of the Easy Admin and maker bundle systems, the majority of the work is DB design, integrations and the custom logic needed.
