### ISSUE TITLE
Release autoupgrade 4.15 version (allows upgrades to 8.0.x)

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#29215]
A new release of the autoupgrade module is needed [to enable upgrades from 1.7.x to 8.0.x](https://github.com/PrestaShop/PrestaShop/issues/29217)

## Bugs to fix before the release

- [x] https://github.com/PrestaShop/PrestaShop/issues/25649
- [x] https://github.com/PrestaShop/PrestaShop/issues/29248
- [x] https://github.com/PrestaShop/PrestaShop/issues/28748
- [x] https://github.com/PrestaShop/PrestaShop/issues/29395
- [x] https://github.com/PrestaShop/PrestaShop/issues/29394

## Release process

- [x] Submit release PR https://github.com/PrestaShop/autoupgrade/pull/535
- [x] QA test campaign
- [x] Make release available on GitHub

**Comment by matks** [comment]
Awaiting @matthieu-rolland analyzis to know whether or not this is possible 8.0.0 beta

**Comment by matthieu-rolland** [comment]
## State of the 5.0 milestone and the 5.x branch

1/ About the 5.0 milestone, after investigating the PRs on the 5.O milestone, I didn't find any relevant BC break, I asked some people why they put this milestone at the time, and it seems like people would only put it because it was the most advanced milestone. There was no actual decision taken about this milestone, at least not in the last 2 years or so.

2/ About the 5.x branch...  this branch didn't move since 2019, I guess at some point it was decided that a 5.0 version would be released but it never happened and we forgot about it ?

Right now we have only one PR merged on the 5.X branch that should be backported to the dev branch, it's a PR that splits the upgrade and the backup process:

https://github.com/PrestaShop/autoupgrade/pull/331

This is not necessary for the Beta

3/ About the 4.15 release, @matks tried making a PR but he faced a few issues that were problematic, several discussions happened, that didn't really reach any conclusion:

 - Should the next release be 4.15 (minor) or 5.0 (major), knowing that:
     - The recommended PHP version goes from PS 7.1 to 7.2, (that's for the warning displays in `classes/UpgradeSelfCheck.php` ), which is a kind of BC break, an upgrade that would work on 4.14 would be considered not safe on 4.15
     - should we allow people upgrading directly from < 1.7.7 to 8 ? (if not then we must keep the recommended version at 7.1)

- Could we decide that auto-upgrade V4 deals with PS1.6 => PS8, and auto-upgrade V5 deals with PS1.7 => PS8 (and above, for now), it seems like the best solution.

### is the dev branch ready for beta ?

It could be, the modifications we have to make are not huge, we just have to take a decision. That being said, major bugs are being found by the QA when doing upgrades like from 1.7.8.6 to 8.0

**Comment by matks** [comment]
@matthieu-rolland thank you for investigation

I think in the time we gave ourselves for beta we won't be able to build a stable `dev` release of the module so I move this item to be done for 8.0.0 RC, not 8.0.0 beta

**Comment by MatShir** [comment]
@HanaRebaiQA will perform the test on https://github.com/PrestaShop/autoupgrade/pull/535 💪 🤞

**Comment by matks** [comment]
4.15.0 was delivered https://github.com/PrestaShop/autoupgrade/releases/tag/v4.15.0
