### ISSUE TITLE
[WS][1.7.8.7] Cannot receive blank schemas for resources

### ISSUE THREAD

**Issue by preoteasa** [PrestaShop/PrestaShop#29251]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This is the same as issue #26559.

I have provided already a fix for this problem, and it was probably applied to the development version.

I have spent quite a lot of time to submit the patch, and to make it production ready. I am disappointed to see that current release 1.7.8.7 still has this problem. After updating to 1.7.8.7 I had to manually apply the fix.

### Steps to reproduce

The same as in issue #26559 for release 1.7.8.7

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.3

**Comment by AureRita** [comment]
Hi @preoteasa ,

As you can see on your PR ( thank you for this PR ) this it for the milestone of the new version of prestashop 8.0.0. This version could be tested by you and other contributors in a few days. Your correction should be in this version. 

Thank you for allowing us to improve unfortunately I will have to close this issue because it has already been created and corrected by yourself for the next versions
