### ISSUE TITLE
Add Custom File Css To change Style of Back Office Prestashop 

### ISSUE THREAD

**Issue by Said-code777** [PrestaShop/PrestaShop#29250]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 I want to create module Prestashop to custumize Style of back Office

Step 1 : I Create The module and validate it

Step 2 : I want to Add Fille Css in the Module to change Style of Back-Office

Step 3 : I will edit this file Via Php in the module 

my problem is in Step 2 : 

     how can I link files Css with back-Office

**Comment by AureRita** [comment]
Hi @Said-code777, 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Moreover, this seems to be more a feature than a bug so if you really want to submit something to Prestashop, take time to read the documentation above and create a new feature 

Thank you

**Comment by Said-code777** [comment]
Hi @AureRita  . 

thank you for your Comment . 

I write issues for the first time , My Problem is :

I want to Créate Module to Customise style of Back Office ... to do that I need to have already custom css file in my Module 

I need know to know just how to requere this file with style of back Office  , 

I hope that you can understand my problem know

Thank you

**Comment by AureRita** [comment]
Hi @Said-code777, 

I understand that is your first issue, but we create some template to help you to writte a correct issue, if there is different boxes to complete, it's because you've to writte different things on it and currently, you didn't take the template. 

All that I can do for you is suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 
or 
If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thanks
