### ISSUE TITLE
BO - Products V2 - New product can be saving without name

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29283]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![ksnip_20220809-131406](https://user-images.githubusercontent.com/90208051/183635190-ce39e46f-971a-417e-85be-238ce6efd2cc.png)

https://user-images.githubusercontent.com/90208051/183635217-313a942e-c7f2-4898-a7e4-2a62926ae5b2.mp4

### Expected behavior

Can't be saved without name, less than 3 characters and more than 128

![scrnli_8_9_2022_1-24-59 PM](https://user-images.githubusercontent.com/90208051/183636246-4686dd41-8852-4cd9-99cb-7943e9373203.png)
![scrnli_8_9_2022_1-24-54 PM](https://user-images.githubusercontent.com/90208051/183636248-8527b3d2-59d1-4b37-821f-16f4a5adbd09.png)
![scrnli_8_9_2022_1-24-04 PM](https://user-images.githubusercontent.com/90208051/183636249-928704bd-bd50-41f2-a356-8ae2b932dd80.png)

### Steps to reproduce

1. open multistore environment
2. enable "New product page - Multi store" in BO
3. create new product
4. try to save without name, use space
5. try more than  128 characters

### PrestaShop version(s) where the bug happened

8.0.0 beta 1

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @szavadskiy 

I reproduce the issue with PS800, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/183717142-30685d0d-29d7-4551-a68d-419bcfacbedc.png)

But, we can't save the product without name if we try to enable it, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/183717752-0abd079b-06ba-43d6-a135-68d557ee282a.png)

Ping @PrestaShop/product-team is this the expected behavior or it's a regression?
Waiting for your feedback.

Thanks!

**Comment by alfonsolr09** [comment]
I don't think it's an error, there is no problem with save without a name as long as it appears in the list of products and the hidden product or some similar bug is not created

**Comment by alfonsolr09** [comment]
I mean errors on the old product page like:
https://github.com/PrestaShop/PrestaShop/issues/9945
https://github.com/PrestaShop/PrestaShop/issues/19913
https://github.com/PrestaShop/PrestaShop/issues/18822
https://github.com/PrestaShop/PrestaShop/issues/18822#issuecomment-619960816

**Comment by szavadskiy** [comment]
![ksnip_20220810-091427](https://user-images.githubusercontent.com/90208051/183838631-9482ae05-fae9-4f1e-9769-b1409c781b00.png)
If the product is online the name can be saved with less than three characters, in the first and second cases (product online/offline) the behavior is different from Product V1

**Comment by eshraw** [comment]
Hello @szavadskiy thank you for the issue.

As long as the online product cannot have an empty name we are fine.
While it's a different behavior from ProductV1 regarding the lower character limit for the product name, it's not a bug but rather a change as a product could very well have one or two characters as a name. We will update the specs accordingly.

@hibatallahAouadni it's the expected behaviour. Thank you for looking into this issue.
