### ISSUE TITLE
Error when I update my shop

### ISSUE THREAD

**Issue by Gtulian** [PrestaShop/PrestaShop#29300]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,
An error appear after upgrade Prestashop, this is coming from module ganalytics. (see file attached)

(1/1) ContextErrorException
Notice: Undefined index: name
ganalytics.php line 530

![reporte](https://user-images.githubusercontent.com/78052890/183907924-f5e37241-38e8-4c28-9567-b00f8053f69e.png)

### Expected behavior

What is the reason and what we should do to repair?

### Steps to reproduce

1- activate debug 
2- error appear

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ganalytics

**Comment by AureRita** [comment]
Hi @Gtulian 

I don't really understand your issue, from wich version to wich version did you do the autoupgrade, if you do it from 1.7.8.7 to 8.0.0, as we can see on this document : https://build.prestashop.com/news/prestashop-8-0-beta-release/ you should disable ganalytics. 
By the way, can you tell me which page are you on? in the FO, in the BO? 

I should normally close your issue because I haven't enought information, but here I ask you what I need to have the same result as you and leave us the opportunity to improve prestashop together 

Waiting for your feedback

**Comment by florine2623** [comment]
Hello @Gtulian ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
