### ISSUE TITLE
The checkout is broken when only one payement without CGV validation

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#29371]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The checkout is broken when only one payement without CGV validation

![Screenshot - 2022-08-17T100835 771](https://user-images.githubusercontent.com/5064590/185068103-52aa936d-51c8-4a17-aeb9-b72c2b18dd40.png)

### Expected behavior

Checkout working

### Steps to reproduce

1 ) Go to module active only one payment module
2 ) Go to order options disable CGV
3) Try to make an order on FO

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.3

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/issues/26274#issuecomment-1217646799

**Comment by AureRita** [comment]
Hi @okom3pom  ,

I reproduce the issue with PrestaShop version 1.7.8.6 and not with the version 1.7.7.8. Nice catch ! It's a regression ! I'll add it to the patch backlog.

We can see this issue with this video : 

https://user-images.githubusercontent.com/100699445/185085108-51008256-e3e6-44ec-87b6-8de027fd6034.mp4

As we can see we also can validate the order even if we have a cross on the button 

Thank for your PR :rocket: 

Thank you

**Comment by Steppenw** [comment]
Hi @okom3pom, I looked at https://github.com/PrestaShop/PrestaShop/pull/29373 and thought I'd test the changes (3 files changed) but my installation doesn't have this path: /themes/_core/js/checkout-payment.js .
The '_core' folder is completely missing: something is wrong with my installation?

**Comment by ghost** [comment]
@Steppenw 

No problem with your installation, this is because it is a source file.

You can replace your : 

themes/core.js 
by the attached file

**Comment by ghost** [comment]
@AureRita i am not sure it's minor.

https://devdocs.prestashop.com/1.7/contribute/contribution-process/how-issues-are-sorted/

**Comment by ghost** [comment]
@Steppenw there is a simpler solution juste replace the core.js 

[core.zip](https://github.com/PrestaShop/PrestaShop/files/9363183/core.zip)

**Comment by Steppenw** [comment]
Thanks @okom3pom, but should the changes still be applied to the other two files?

**Comment by ghost** [comment]
No just the core.js  I await your return.

**Comment by Steppenw** [comment]
I try and let you know.

**Comment by Steppenw** [comment]
![Screenshot](https://user-images.githubusercontent.com/76645799/185175616-9dd77a77-c52a-49bf-a0f7-a2097ae1e3e4.png)

Hi @okom3pom, I would say that everything is fine.
The radio button is already checked, the form is already expanded.
At the bottom of the page there is no reference to select a payment method or to accept 'Terms and conditions'.
The 'Submit' button is active: clicking on it without having filled in the form fields correctly highlights the error.
By correctly filling in all the fields and signing the order, the purchase is regularly made.
I repeat, I would say that everything is fine...
I hope you have experienced the same behavior described.
**EDIT**: Hi @okom3pom, don't hate me ...
For my case the problem is solved.
Keeping the 'Terms and conditions' deactivated, I still wanted to add a second payment method (it may take a day), to verify the effect: at the bottom appears the invitation to select a payment method and to accept 'Terms and conditions' .
I would say that this is correct and that it refers to the failure to select the payment method; so much so that once selected the invitation disappears.
Maybe I am the one who interprets the mechanism incorrectly but what I expect is that if 'Terms and conditions' is deactivated the wording that invites you to accept 'Terms and conditions' does not appear ...

**Comment by ghost** [comment]
@Steppenw 

It is possible that modules add their own checkboxes.
It is also possible that some modules do not respect the standard. 
With two native modules no problem. 


https://user-images.githubusercontent.com/5064590/185365059-1538dd2a-25df-45df-82fa-f5be21ac9ef0.mp4

**Comment by Steppenw** [comment]
![Screenshot1](https://user-images.githubusercontent.com/76645799/185380295-072fc60f-b427-43e7-b386-76204cff4685.png)

@okom3pom, I assure you that this is the last time I stress you: I repeat that for my case the problem is solved.
What I meant earlier is what appears in the screenshot (two payment methods, 'Terms and conditions' deactivated), which is the notification circled at the bottom. Which in this case depends only on the selection of the payment method as yet (so it is correct that there is): once the payment method has been selected, it disappears (correctly).
What I noticed in your video is that this is missing ...
All in all, at the moment I am not interested in understanding the reason for this difference: my scenario is a single payment module and 'Terms and conditions' deactivated.
Thank you very much for your availability.
