### ISSUE TITLE
Error Invalid $number parameter: "NAN" cannot be interpreted as a number

### ISSUE THREAD

**Issue by PalomaDiPierro** [PrestaShop/PrestaShop#29451]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When downloading PDF invoices I get an error and I can't download them.
![error facturas PDf buckerbook](https://user-images.githubusercontent.com/112171310/186888340-2fd938ef-836e-431a-9734-368aeccc2747.png)

### Expected behavior

download PDF invoices

### Steps to reproduce

Invoices, date and download pdf invoices

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by hibatallahAouadni** [comment]
Hello @PalomaDiPierro 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely an override or a module problem.

We will close this issue.

Thanks!

**Comment by EvilDragon** [comment]
As I had the same problem, I investigated the issue a bit more and I think I know why you can't reproduce the problem.

It seems to be a bug of M4pdf in combination with 0 EUR total product value.

For me, this happens if there is an invoice which has a product value of ONLY EUR 0.
As an example:
I offer a printed product catalog in my shop which can be ordered for free (except for shipping costs).

Whenever someone orders ONLY the catalog, the product price is 0 EUR which triggers the same message.
If someone orders the catalog together with some other products, it works well.

So it seems the M4PDF invoice download system has a problem if the total products price is 0.
I hope that helps!

**Comment by EvilDragon** [comment]
And a small update, as I found the exact part that's causing it in the M4PDF template:
 
```
{foreach from=$order[orders].price_breakdown.taxes key=k item=v}
 <td class="align-right">{displayPrice price=$order[orders].price_breakdown.totalsProductsWithTax[$k] currency=$order[orders].id_currency}</td>
{/foreach}

```
The problem occurs whenever the .price_breakdown is being called. No idea if that's an issue of M4PDF or PrestaShop (as the displayPrice function should be part of PrestaShop).

As a temporary solution, I changed the template like this:

```
 {if $order[orders].total_products != '0.00'}
                <td class="align-right" style="padding-left: 7mm; ">{displayPrice price=$order[orders].price_breakdown.totalWithTax currency=$order[orders].id_currency}</td>
                {else}
                <td class="align-right">{displayPrice price=$order[orders].total_shipping currency=$order[orders].id_currency}</td>
                {/if}
```

So basically: If all products have a total value of 0 EUR, it shows the shipping costs as total instead of the total costs (which would be the same in this case).

That's all I can do - now it's up to you developers to determine if the bug lies within PrestaShops code or M4PDFs code :)
