### ISSUE TITLE
BO - Product Page - Quantity in combination on Small Screen Phones is partially visible

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#29459]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Admin Back Office -> Catalog -> Product (with combination) -> quantity looks like empty but there is not enough space to show number (css min-width is needed and paddings are to big)

i suggest to add this BUT ONLY ON SMALL SCREEN

```
.form-control {
padding: 0.5rem;
text-align: center;
min-width: 3rem;
}
```

#27589 is front office
this issues is about ADMIN BACK OFFICE

### Expected behavior

3 digits are fully visible for the quantity field and hide edit and delete button behind one button (dropdown).

### Steps to reproduce

1. Admin Back Office Catalog
2. Product with combination

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

![empty-box](https://user-images.githubusercontent.com/9866119/187039951-afef8c80-5720-480c-96bd-2540f7713608.jpg)

**Comment by sLorenzini** [comment]
Hello @slupostrupek,

Thank you for your report.

I couldn't reproduce exactly your issue on 1.7.8.0 and more. The field is broken but not empty:

![Capture d’écran 2022-08-29 à 14 39 28](https://user-images.githubusercontent.com/2854834/187204306-2cf0605f-e1da-449c-9158-916d963c4eab.png)

Could you please provide us with more info to reproduct the empty field? 

- If it's on a computer, which size of small screen did you use? which browser?
- If it's on a mobile phone, which phone it is? which browser again?

Waiting for your feedback.

Thank you

**Comment by slupostrupek** [comment]
On my Phone it's not empty either, box of quantity is to small to see numbers

**Comment by florine2623** [comment]
Hello @slupostrupek ,

In the devices that I tested, I always see the quantity, even if it's not entirely, it is never blank.
Can you confirm which device you are using ?
That way we can decide what to do with your issue.

Thanks!

**Comment by slupostrupek** [comment]
iphone 12 pro

**Comment by kpodemski** [comment]
Hi @florine2623 

Just a suggestion, I think it's worth improving, even if the field is partially visible. The question is whether this issue exists on the new product page or not.

**Comment by hibatallahAouadni** [comment]
Hello @slupostrupek 

I reproduce the issue with PS1786 and PS800_beta, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/187647686-43407e79-d15c-4a17-a00d-2460aa58d830.png)

And as you can see I didn't manage to reproduce the issue with PS1770, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/187648560-6f24375e-6a2a-4f31-898e-3ab1a58f9fee.png)

So, it's a regression! I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment]
@slupostrupek I see you find a way to fix the issue. I would be nice if you can make a contribution, here some [doc](https://devdocs.prestashop.com/1.7/contribute/) if you need help. We would be happy to review your work ;)

**Comment by MatShir** [comment]
Fixed by the new product page for the combination, it has a horizontal scrolling
