### ISSUE TITLE
PHP notice (`theme_name of non-object`) when installing Prestashop 8

### ISSUE THREAD

**Issue by danielkauffman** [PrestaShop/PrestaShop#29557]
### Prerequisites

- [ ] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The method of installation seems irrelevant. Either with command or through the browser installation throws a notice about accessing `theme_name` on null object.
On PHP 7.4:
> PHP Notice:  Trying to get property 'theme_name' of non-object in /opt/prestashop/var/cache/prod/ContainerILJ4mH5/appAppKernelProdContainer.php on line 2714

On PHP 8.1:
![obraz](https://user-images.githubusercontent.com/5007456/213665076-62b4f383-b318-49f7-bd4b-36551042c4a5.png)

Installation process creates several **Container[hash]** directories. Installation completes succesfully if warnings are ignored, but the Container(...) mentioned in the warning is deleted and few other similar containers appear in the cache:

![obraz](https://user-images.githubusercontent.com/5007456/213666135-e1a8a627-8bb7-4daf-abac-115cfc001504.png)

These containers seem to be connected with [distributionapi](https://github.dev/PrestaShop/distribution-api)

### Expected behavior

Installing PrestaShop should succeed without any errors, warning or notices.

### Steps to reproduce

1. Install PrestaShop using the command line or from prestashop.zip. Note that in PrestaShop 1.7.8.x the following command succeeds without any notices.<br>`php install/index_cli.php --step=database --domain=example.com --db_user=prestashop --db_password=XXX --country=us --firstname=XXX --lastname=XXX --password=XXX --email=user@example.com`
2. Check the php error log
3. Or check the attached screen record below at 1:43

https://user-images.githubusercontent.com/23308427/189728379-39b1f503-4567-48ef-b47e-01879e1ed864.mp4

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.4, 8.0, 8.1

**Comment by danielkauffman** [comment]
The installer (run in step 2 above) deletes `appAppKernelProdContainer.php` at some point after throwing the notice and before exiting.

**Comment by florine2623** [comment]
Hello @danielkauffman ,

I can't reproduce your issue.
<img width="974" alt="Screenshot 2022-09-07 at 14 21 45" src="https://user-images.githubusercontent.com/16019289/188877081-445e266f-221c-4214-adcc-c65960bd5a92.png">
I just changed the info to match my server. My result was "Installation successful"

Can you give me more info about :
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

Thank you

**Comment by danielkauffman** [comment]
* host - not applicable
* server setup and configuration - PHP version was already provided, nothing else is applicable because the installer is running from the command line
* PrestaShop version (source) - git tag was already provided, here is the link to the download: https://github.com/PrestaShop/PrestaShop/releases/download/8.0.0-beta.1/prestashop_8.0.0-beta.1.zip
* debug mode report - there is no debug/verbose option for install/index_cli.php
* PHP error logs - the only line was already provided, the installer is running from the command line
* apache error log - not applicable, the installer is running from the command line
* Javascript console log - not applicable, the installer is running from the command line
* screenshots - not applicable, the installer is running from the command line

Did you start with the zip and install to an empty directory? Is your local PHP configured to suppress notices?

**Comment by hibatallahAouadni** [comment]
Hello @danielkauffman 

I didn't manage to reproduce the issue with the provided infos, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/189728379-39b1f503-4567-48ef-b47e-01879e1ed864.mp4

Waiting for your feedback.

Thanks!

**Comment by paulnoelcholot** [comment]
Hello @danielkauffman,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by bm-services** [comment]
I'm sorry but error IS in the video.
In 8.0.1, I have the same error but it's a warning and it blocks install completely !

**Comment by danielkauffman** [comment]
@hibatallahAouadni The unexpected PHP Notice appears in your video at 1:43.

@bm-services It may be helpful to know what version of PHP you are using.

**Comment by bm-services** [comment]
I tried with PHP 8.0 and PHP 8.1

```
php8.1 index_cli.php --language=fr --timezone=Europe/Paris --base_uri=/ --domain=ps801.d81.test --db_server=localhost --db_name=dev_ps801 --db_user=dev_ps801 --db_password=dev_ps801 --prefix=ps801_ --firstname=Support '--lastname=BM Services' '--password=xxxxxxx' --email=xxxx --newsletter=0 --ssl=1
PHP Warning:  Attempt to read property "theme_name" on null in .../www/var/cache/prod/ContainerNa7Xhhv/appAppKernelProdContainer.php on line 2740
PHP Stack trace:
PHP   1. {main}() .../www/install/index_cli.php:0
```

**Comment by SharakPL** [comment]
This notice still appears, even with stable versions of 8.0.x branch

**Comment by SharakPL** [comment]
> I can't reproduce your issue.
> <img alt="Screenshot 2022-09-07 at 14 21 45" width="974" src="https://user-images.githubusercontent.com/16019289/188877081-445e266f-221c-4214-adcc-c65960bd5a92.png">
> I just changed the info to match my server. My result was "Installation successful"

@florine2623 result depends on the php configuration. If warnings are ignored then installation is successful, but either way you should have `theme_name` mentioned in a warning in your php_error.log

**Comment by pastoryohan** [comment]
@SharakPL 
I've ignored warnings in php.ini, my logs are now empty, but error 500 still block installation.

![image](https://user-images.githubusercontent.com/56559466/213678245-6ce69d6f-bba5-434b-ab3b-aaa57e1b9883.png)

**Comment by hibatallahAouadni** [comment]
Hello @danielkauffman 

Thanks for your feedback.
> @hibatallahAouadni The unexpected PHP Notice appears in your video at 1:43.

Indeed, there's a unexpected PHP notice about the theme_name  in my screen record at 1:43 🙏 
I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

PS: thanks @SharakPL for reopening this issue 🙏 your rock 🚀 

Thank you

**Comment by bm-services** [comment]
Looking for a fix, I found a new error:
```
PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /.../classes/db/DbPDO.php:149
Stack trace:
#0 /.../classes/db/DbPDO.php(149): PDO->query()
#1 /.../classes/db/Db.php(377): DbPDOCore->_query()
#2 /.../classes/db/Db.php(567): DbCore->query()
#3 /.../src/PrestaShopBundle/Install/SqlLoader.php(118): DbCore->execute()
#4 /.../src/PrestaShopBundle/Install/SqlLoader.php(97): PrestaShopBundle\Install\SqlLoader->parse()
#5 /.../src/PrestaShopBundle/Install/SqlLoader.php(82): PrestaShopBundle\Install\SqlLoader->parseFile()
#6 /.../src/PrestaShopBundle/Install/Install.php(308): PrestaShopBundle\Install\SqlLoader->parse_file()
#7 /.../install/controllers/console/process.php(214): PrestaShopBundle\Install\Install->installDatabase()
#8 /.../install/controllers/console/process.php(143): InstallControllerConsoleProcess->processInstallDatabase()
#9 /.../install/classes/controllerConsole.php(134): InstallControllerConsoleProcess->process()
#10 /.../install/index_cli.php(75): InstallControllerConsole::execute()
#11 {main}
```
Maybe it's related to first warning.
This error occurs in file : `/.../src/PrestaShopBundle/Install/Install.php` in function "clearDatabase".

**Comment by bm-services** [comment]
After a lot of debugs... It seems the problem is linked with 'kernel'. I succeed to avoid this warning modifing 2 files: 
`install/index.cli.php` adding after `require_once __DIR__ . DIRECTORY_SEPARATOR . 'classes/datas.php';`
these lines:
```
require_once __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '/config/config.inc.php';
require_once __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '/config/bootstrap.php';

global $kernel;
$kernel = new AppKernel('prod', 1);
$kernel->boot();
```

And in file `install/controllers/console/process.php` adding after `$this->rebootWithoutTranslationsCache();`
these lines:
```
// Deferred Kernel Init
$this->initKernel();
```

@PrestaShopTeam,
What do you think about this fix?

**Comment by hibatallahAouadni** [comment]
Hello @bm-services 

I see that you manage to get the problem fixed :rocket: , so please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) :pray: 
Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by bm-services** [comment]
Please, I asked a question, will there be someone to answer it?

> @PrestaShopteam, What do you think about this fix?

**Comment by bm-services** [comment]
Kernel errors are common when using CLI, proof is in PrestaShop install CLI.
We all need an answer global for this that only PrestaShop team can give.

**Comment by pastoryohan** [comment]
> Kernel errors are common when using CLI, proof is in PrestaShop install CLI. We all need an answer global for this that only PrestaShop team can give.

if i have time, i'll test it today.

**Comment by matks** [comment]
> What do you think about this fix?

I am sorry but it seems you solved the problem by tinkering with the system, it looks more like a hotfix than a real solution 😅 . You asked what I think so I answer, sorry if this is not the answer you hoped for 😅

**Comment by bm-services** [comment]
I am aware of it, that is why I asked for PrestaShop team opinion on this subject and that I didn't find the hibatallahAouadni's answer appropriate.
But these hot fixes highlight a kernel / context problem on this bug.
I often have kernel problems when I use CLIs, especially when I set up command synchronization crons that update command statuses.
I think there is a problem to have a functional context in this case because even when defining an employee, a shop, a currency, etc... I have context / kernel errors.

**Comment by matks** [comment]
Is there a problem? Yes, certainly. I mean there is [745](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3AVerified) verified registered bugs in the bug tracker so this is not a surprise.

[Software has bugs, it's normal](https://m.signalvnoise.com/software-has-bugs-this-is-normal/) said a famous developer.

**Comment by SharakPL** [comment]
The same issue with PS 8.0.2. The notice is triggered by this code:

![obraz](https://user-images.githubusercontent.com/5007456/225175403-d043a6d7-38c6-4bce-bafa-e97ff7c5590a.png)

https://github.com/PrestaShop/PrestaShop/blob/4f78450af5154012334046862530889bb6311a77/src/PrestaShopBundle/Resources/config/services/adapter/data_provider.yml#L102-L106

**Comment by Darkov3** [comment]
I have the same problem, using 8.01
And the fix from @bm-services did not help me.
I am on a windows machine, might be important.

edit: turning off notice errors fixed it, had to manually kill the IIS process as well, it didnt restart properly the PHP service, maybe that was my bigger issue fixing this error.

**Comment by juchems** [comment]
I am having this same issue with 8.0.3.

**Comment by audebms** [comment]
I confirm : problem persists on PrestaShop version 8.0.3

**Comment by M0rgan01** [comment]
Some precisions 😃 

The problem occurs during the "database" step, more precisely when executing the command "prestashop:schema:update-without-foreign".

![Image](https://user-images.githubusercontent.com/36233446/237038938-695bddf2-4525-43b3-acd2-f3b081da7af8.png)


Warnings are hidden in the output of the command

![Image](https://user-images.githubusercontent.com/36233446/237039184-a39a3a05-4e24-4eae-a959-ba19f6745af6.png)

**Comment by M0rgan01** [comment]
@ChillCode Hi ! 

We initialize the context after creating the database.

![image](https://github.com/PrestaShop/PrestaShop/assets/36233446/6f320d3f-619b-43f0-bc97-50cf43b280cf)

Here the processInstallDefaultData method initializes the shop of the context :scream: 

Dependency injection is performed when creating the database, so there is a problem with the availability of the context.

    /*
     * Gets the public 'prestashop.categories_provider' shared service.
     *
     * @return \PrestaShopBundle\Service\DataProvider\Admin\CategoriesProvider
     */
    protected function getPrestashop_CategoriesProviderService()
    {
        return $this->services['prestashop.categories_provider'] = new \PrestaShopBundle\Service\DataProvider\Admin\CategoriesProvider($this->parameters['prestashop.addons.categories'], ((($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->shop->theme_name) ? (($this->services['prestashop.core.addon.theme.repository'] ?? $this->load('getPrestashop_Core_Addon_Theme_RepositoryService.php'))->getInstanceByName(($this->services['prestashop.adapter.legacy.context'] ?? $this->getPrestashop_Adapter_Legacy_ContextService())->getContext()->shop->theme_name)->getModulesToEnable()) : ([])));
    }
  
The above code is generated code against the categories provider service definition :

```
prestashop.categories_provider:
    class: PrestaShopBundle\Service\DataProvider\Admin\CategoriesProvider
    arguments:
      - "%prestashop.addons.categories%"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.theme_name?service('prestashop.core.addon.theme.repository').getInstanceByName(service('prestashop.adapter.legacy.context').getContext().shop.theme_name).getModulesToEnable():[]"
```

By modifying the constructor we can fix the problem. I'm on it :smile:

**Comment by ChillCode** [comment]
Thanks @M0rgan01, spent two hours just to install a test site to reproduce other issues that are not related to this and appreciate your hard work.

**Comment by audebms** [comment]
Good news, thank you M0rgan01 !

**Comment by lea-BMS** [comment]
> Good news, thank you M0rgan01 !

Same issue persist when installing 8.1.6 from cli. @mflasquin problem is still not fixed. Please re-open

```none
PHP Warning:  Attempt to read property "theme_name" on null in ..../var/cache/prod/ContainerBPB7tXb/appAppKernelProdContainer.php on line 2870
```

**Comment by francisbrosnan** [comment]
> > Good news, thank you M0rgan01 !
> 
> Same issue persist when installing 8.1.6 from cli. @mflasquin problem is still not fixed. Please re-open
> 
> ```
> PHP Warning:  Attempt to read property "theme_name" on null in ..../var/cache/prod/ContainerBPB7tXb/appAppKernelProdContainer.php on line 2870
> ```

FIX: We have found same issue with Prestashop 8.1.4, .8.1.5 and 8.1.6. Disabling error reporting before running installation fix all issues:

    // E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT & ~E_DEPRECATED
    error_reporting (22517);

The issue is caused during database deployment which expects to receive JSON. Because part of the code is in transition (context, database and configuration is not ready yet) it generate warnings that are mixed with JSON code, causing an error that cannot be handled by the installer.

We tried different solutions before reaching this (changing appAppKernelProdContainer.php, reviewing OpenSSL settings, ensuring GD library is available and up to date, checking session parameters, but now knowing the fix, none of them could have solved the problem: database installer expects JSON and error reporting during installer breaks that.

**Comment by SymeR17** [comment]
Hi @francisbrosnan,
I encounter this problem, can you tell me in which file the line is

E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT & ~E_DEPRECATED

What should I comment on please?

**Comment by francisbrosnan** [comment]
Hi @SymeR17,

If you are running a php-fpm env, find .conf associated to hosting and add:

      php_admin_value[error_reporting] = 22517

Alternatively, you can also using .htaccess (if you use apache2) at top hosting folder, adding:

     php_flag  error_reporting  22517

Also, Prestashop will load any php code you place under config/defines_custom.inc.php (see https://github.com/PrestaShop/PrestaShop/blob/develop/config/config.inc.php). In such case, you could add there:

     <?php
     
      error_reporting (22517);

**Comment by SymeR17** [comment]
It doesn't work for me. For information, I am testing a local installation with Wamp.
So I started the installation with connecting to the url. He unzipped the zip. There, I added the config/defines_custom.inc.php file with the content: (before continuing the installation)

 <?php
 error_reporting(22517);

But the problem is still the same.
On the other hand, I don't really understand what the number 22517 is for?
I shouldn't put error_reporting(0); if I want it to report any errors to me?

**Comment by SymeR17** [comment]
It doesn't work for me. For information, I am testing a local installation with Wamp.
So I started the installation with connecting to the url. He unzipped the zip. There, I added the config/defines_custom.inc.php file with the content: (before continuing the installation)

 <?php
 error_reporting(22517);

But the problem is still the same.
On the other hand, I don't really understand what the number 22517 is for?
I shouldn't put error_reporting(0); if I want it to report any errors to me?

**Comment by SymeR17** [comment]
@francisbrosnan,
It doesn't work for me. For information, I am testing a local installation with Wamp.
So I started the installation with connecting to the url. He unzipped the zip. There, I added the config/defines_custom.inc.php file with the content: (before continuing the installation)

`<?php
 error_reporting(22517);`

But the problem is still the same.
On the other hand, I don't really understand what the number 22517 is for?
I shouldn't put error_reporting(0); if I want it to report any errors to me?

**Comment by SharakPL** [comment]
@francisbrosnan disabling error reporting is **not a fix**.

**Comment by francisbrosnan** [comment]
> @francisbrosnan disabling error reporting is **not a fix**.

Certainly it does not fix the real issue behind this bug, which is: the installer seems to be mixing json with error/warning reporting, something that shouldn't be.

Given many users have no chances to fix the real inside beneath, the solution is to disable **error reporting/warnings** during installation, so you can complete it and reenable it back again once finished.

So it is workaround that allows to complete the installation, but also a manifestation that the installation process, during database deployment is prone to fail in case you have error reporting enabled in your php environment, which is the default in many cases.

**Comment by SymeR17** [comment]
What is strange is that on certain configurations the installation works without problems, and on others impossible.

For my part, on the online Debian hosting server, the installation went smoothly.
And on a local Windows installation with Wamp. Impossible.

**Comment by SharakPL** [comment]
@SymeR17 this is just a notice about `theme_name` missing. It doesn't stop the installation.

Windows installation not working is whole another issue #35044
