### ISSUE TITLE
Hook actionObjectUpdateAfter - Infinite loop that leads to memory limit in FO

### ISSUE THREAD

**Issue by Kandax86** [PrestaShop/PrestaShop#29560]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,
i don't understand why the core is doing this but i'm facing an infinite loop when customer is loggedin but its totally logical if I read the code. First it was working but since I hooked a module on actionObjectUpdateAfter i get this syndrom.

I searched in code and this is what i found

When we are logged in as customer on front, 
It calls 
1. Hook::exec 
which check user logged in groups in Hook class with the method 
2. getHookModuleExecList who calls
3. getAllHookRegistrations.
This function calls 
4. $customer->isLogged() 
and this function calls 
5. Context::getContext()->cookie->isSessionAlive()
this function calls (on cookie class)
6. $this->getSession($this->session_id)
and the getSession method calls 
7. $session->save() 
who calls in object model the 
8. update() method who calls the 
9. hook actionObjectUpdateAfter who tried to Hook::exec 
then restart this infinite loop (back to 1.) .

I succed to stop this look by adding in objectModel line 864 

```
if(get_class($this) != 'EmployeeSession' && get_class($this) != 'CustomerSession'){
	Hook::exec('actionObjectUpdateAfter', ['object' => $this]);
	Hook::exec('actionObject' . $this->getFullyQualifiedName() . 'UpdateAfter', ['object' => $this]);
}
```
But with this it breaks the hook actionObjectUpdateAfter on EmployeeSession class and CustomerSession which extends ObjectModel too...

Edit : I figured out that natively (I mean when fresh install prestashop) this hook is not in database and is added only once a module is attached to this hook ( actionObjectUpdateAfter ) si until the hook doesn't appear in ps_hook table there is not this issue but when the row exists in ps_hook we got an infinite loop....

### Expected behavior

We can't have an infinite loop...

### Steps to reproduce

1. I attached a module on actionObjectUpdateAfter but the module is uninstalled since (i don't know if it is linked to this i checked on DB there is no more entries of attached module on this hook) ...
2. I logged in in front and i get a max execution time with a random location of killing process.. (it's never the same end position)

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

**Comment by jsc-web** [comment]
Hi,

I can reproduce the same behavior.

If there is one of these hooks :
- actionObjectUpdateBefore
- actionObjectEmployeeSessionUpdateBefore
- actionObjectCustomerSessionUpdateBefore
- actionObjectUpdateAfter
- actionObjectEmployeeSessionUpdateAfter
- actionObjectCustomerSessionUpdateAfter

In the ps_hook table, then there is an infinite loop for logged in users.

Thats due to the fact that the isLogged() method of Customer class is called in the Hook execution behavior, in order to determine the customer group (probably to determine the modules to display/hide).

The isLogged() method call the isSessionAlive() method of the Cookie class which update() or add() on the CustomerSession or the EmployeeSession Object. Theses actions execute the pre-cited hooks, which call again the same code. And so on.

I think it's a critical bug.

Best,

**Comment by florine2623** [comment]
Hello @Kandax86 ,

Can you send the module test you are using to generate the infinite loop please ?

Thanks!

**Comment by Kandax86** [comment]
Hello @florine2623 
You doesn't need any module, you just need to add the actionObjectUpdateAfter hook entry in ps_hook manually from sql db or to hook any module on this point it will create the hook in the ps_hook table. If the entry in ps_hook exists, the loop is present. Even if there is nothing hooked on this hook.

Btw, i think this issue is also on 1.7 branch...

Cédric

**Comment by florine2623** [comment]
Hello again @Kandax86 ,

Not all modules can be hooked to `actionObjectUpdateAfter` that's why I asked if you had a specific module ^^

I added the hook manually and I reproduced your issue.
<img width="910" alt="Screenshot 2022-09-07 at 15 16 41" src="https://user-images.githubusercontent.com/16019289/188887829-1e88faf3-5fc3-493f-a91b-378993a27c9f.png">

In FO, I have a memory limit:
<img width="1109" alt="Screenshot 2022-09-07 at 15 17 20" src="https://user-images.githubusercontent.com/16019289/188887987-ac77aa1c-0962-4c0b-b122-787fd1ae8a37.png">
`Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /classes/Hook.php on line 1055`

Reproduced on 8.0.x. NOT on 1.7.8.x. So this is a regression.
I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by jsc-web** [comment]
@florine2623 @Kandax86,

For your information, the regression was inserted by this commit : https://github.com/PrestaShop/PrestaShop/commit/7779817d31463fc1e04be5f8d6431693ddaf7272

The error is due to the addition of the line with the $session->save(); on the Cookie object.

But this commit is a part of a more global commit. No idea of the reason of the purpose.

The fix will be easy, the PR will just remove this line, but maybee it will introduce other regressions, maybee you need to check with @PierreRambaud why this line was introduced.

Thanks,

**Comment by matks** [comment]
What a funny bug 😄 

Here's what I understand from the situation:

Hook `actionObjectUpdateAfter` is fired when any eligible Object is updated. Object can be an order, a customer or... a session.

When hook `actionObjectUpdateAfter` is fired, the hook system at some point checks whether user is logged. "Is user logged" is implemented in a way that it checks if session is alive and this requires to call function `getSession()`

When `getSession()` is called, this is going to modify the 'last updated date' (a timestamp) of the session and save it. This is the modification introduced by Pierre in commit https://github.com/PrestaShop/PrestaShop/commit/7779817d31463fc1e04be5f8d6431693ddaf7272 : every time we check the session data we update the date_upd field to mark it. The timestamp is used to track the last time session was "alive".

But session is an object, so performing this update is going to trigger hook `actionObjectUpdateAfter` which is going to cause the hook system to check if user is logged which is going to check if session is alive and so on.

That's an infinite loop caused by a sorry series of functions calling each other.

I can imagine some possible solutions, to be explored:
1) Why does the hook system needs to know if user is logged in this usecase? It could be needed to check if this is really useful
2) Why does "is user logged" checks if session is alive? It could be needed to check if this is really useful
3) Possibly _exclude the Session from_ the list of objects that do trigger the hook `actionObjectUpdateAfter`
4) When hook `actionObjectUpdateAfter` is called twice in a row on the very same object, the second time skip it an return, to avoid infinite loop

**Comment by Kandax86** [comment]
Thank you for the answer that is the effect.
another solution consists by add a touch() function on ObjectModel which is not dependant of save and does not call the hook which only update date_upd as touch() function is supposed to do... and not calling the full save() function.

**Comment by jsc-web** [comment]
Hi @matks 

The same behavior can be reproduced with all theses hooks  ; 

actionObjectUpdateBefore
actionObjectEmployeeSessionUpdateBefore
actionObjectCustomerSessionUpdateBefore
actionObjectUpdateAfter
actionObjectEmployeeSessionUpdateAfter
actionObjectCustomerSessionUpdateAfter
actionObjectAddBefore
actionObjectEmployeeSessionAddBefore
actionObjectCustomerSessionAddBefore
actionObjectAddAfter
actionObjectEmployeeSessionAddAfter
actionObjectCustomerSessionAddAfter

It's due to the fact that the save() ObjectModel method call the update() or add() method depending on the case. And all the hook calls in theses methods are concerned.

For your suggested solutions : 
1. i think it's usefull to determine the client group in order to display ou hide some modules
2. i think it's not usefull
3. that's the @Kandax86 suggestion in the initial message, maybee a little bit verbose
4. this could be a great security optimisation for all the hooks

Best,

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29619

**Comment by PrestaEdit** [comment]
Hi @matks ,

Why 8.0.1 ? Isn't it an error ?

**Comment by matks** [comment]
8.0.0 content is already frozen
8.0.x branch content is now PS 8.0.1

**Comment by PrestaEdit** [comment]
But which version will be available on the final release, so ?
