### ISSUE TITLE
While the URL call a module front controller without the name, it's throw an uncaught PrestaShopException

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29610]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While you have an URL calling a front controller module without mentionning the related module, it will be an empty string.

Exemple : index.php?fc=module

Instead of 404 URL or handled error, an uncaugth exception is throw.

### Expected behavior

Show at least a 404 error.

### Steps to reproduce

1. Call the given URL (index.php?fc=module)

### PrestaShop version(s) where the bug happened

8.0.0-beta.1

**Comment by PululuK** [comment]
NOTE : In debug mode only

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

I reproduce the issue with PS1778, PS1783, PS800_beta, only with debug mode enabled.
Ping @PrestaShop/prestashop-maintainers do you think it is a valid bug? cause with debug mode disabled I will be redirected to 404 page, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/189633275-8c59cbb4-26e0-4035-905b-595da7cb7fed.png)

Waiting for your feedback.

Thanks!

**Comment by matks** [comment]
Hello all, I think it actually is quite interesting like this.

With debug mode off, we have the expected behavior: a 404 response.

With debug mode on, we are in a situation where developers are working on the shop/module and need plenty informations.

So I think "throwing an exception" (current behavior) is not great but it is quite good to have an Error, it would help a module developer working on his module to detect issues in its code.

Wdyt?
