### ISSUE TITLE
Error "VAT number validation service unavailable"

### ISSUE THREAD

**Issue by FactoryBike** [PrestaShop/PrestaShop#29656]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Error "VAT number validation service unavailable"

### Expected behavior

Error "VAT number validation service unavailable"

### Steps to reproduce

1 try register www.factory-bike.es
2 Write VAT NUMBER
3 Gives error VAT number validation service unavailable
![vat number](https://user-images.githubusercontent.com/99812042/190594548-c842991f-09db-41ec-b7fe-f9d5097e675a.JPG)

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.30

**Comment by Hlavtox** [comment]
Hi, the issue is related to vatnumber module (https://github.com/PrestaShop/vatnumber), that archived for a long time and not supported anymore.

Unfortunately, the API that the module uses has been disabled some time ago and the module stopped working completely. 😞 I suggest to disable the online check in module settings for now, and start looking for a working 3rd party alternative.

**Comment by FactoryBike** [comment]
Ok, thanks. We found another module.
