### ISSUE TITLE
Behavior while logout on wishlist is not consistent

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/PrestaShop#29654]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I was on a wishlist details, I clicked on logout link and I was still on wishlist details, with a forbidden message and with wishlist title. 

![Capture d’écran 2022-09-16 à 09 21 08](https://user-images.githubusercontent.com/121870/190586623-2aaaf3fb-c5d4-457a-8fc2-d4549b7864af.png)

### Expected behavior

Two possible behavior: 
* redirect to login form or the homepage 
* stay on the same URL (`module/blockwishlist/view?id_wishlist=ID`) but without private information. 

### Steps to reproduce

1. Go to your wishlist detail (`module/blockwishlist/view?id_wishlist=ID`)
2. Click on logout link

### PrestaShop version(s) where the bug happened

8.0.x, develop 

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

blockwishlist

**Comment by sallemiines** [comment]
Hello @nicosomb 

I reproduce the issue with PrestaShop version 1778,1787,8.0.x , develop  I'll add this to the backlog so it can be fixed.
you can see the issue here:

https://user-images.githubusercontent.com/31663369/190617588-9d3e0ab8-703b-448e-acb5-5cb8cb5d5e8d.mp4

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by nicosomb** [comment]
In fact, no need be logged and to click on logout link. 

With anonymous user, just go on `module/blockwishlist/view?id_wishlist=ID` and you have this behavior.

**Comment by matks** [comment]
I think the good solution is `redirect to login form or the homepage`: user should not stay in this area

**Comment by matks** [comment]
Started by @0x346e3730
