### ISSUE TITLE
Autoupgrade - BO - A 500 errors in console when upgrade from 1.7 to 8.0 (Method Not Allowed  (Allow: POST) )

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29705]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A 500 errors in console when upgrade from 1.7.7.8 to 8.0 and 1.7.7.8 to 1.7.8.7 (Method Not Allowed  (Allow: POST) )

**Upgrade with 1-click upgrade v4.14 From 1.7.7.8 to 8.0.0 : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/191243035-70f644b5-9860-40c4-8b77-b2dd744f9a4d.png)

https://user-images.githubusercontent.com/92912932/191243332-a8cb8d0b-3fe3-4285-a9b1-520871006ff2.mp4

**Upgrade with 1-click upgrade v4.15 From 1.7.7.8 to 8.0.0 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/191243519-12671975-14c4-4c5e-a5d6-428a6a41936b.png)

![image](https://user-images.githubusercontent.com/92912932/191243787-3689183a-9727-4221-814d-c77a2ac23dd0.png)

https://user-images.githubusercontent.com/92912932/191243460-1f8159e9-c231-43c4-948c-ef307a403652.mp4

When enabling debug mode, this is the generated exception : 

![image](https://user-images.githubusercontent.com/92912932/191243687-14487c1e-558e-4053-9d83-4fca6f6b0766.png)

**Upgrade with 1-click upgrade v4.15 From 1.7.7.8 to 1.7.8.7 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/191245311-18a681fe-de06-477f-90b2-ca4b9ff361e3.mp4

So, it's a regression on 8.0.0 !

### Expected behavior

No 500 errors is displayed!

### Steps to reproduce

1. Install PS1778 OR PS1787
2. Uninstall problematic modules (welcome, ps_mbo, pd_metrics, facebook, psxmarketingwithgoogle)
3. Install the autoupgrade v4.15 module from dev branch OR use the autoupgrade v4.14.2
4. Install a new 8.0.x branch
5. Create a release from 8.0.0
6. Configure the autoupgrade module
7. Upgrade to 8.0.0 branch
9. See error > During upgrade check the console : A 500 erros are displayed
10. Enable debug mode > An exception is thrown related to Method Not Allowed  (Allow: POST) 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0 from dev branch and v4.14.2

**Comment by atomiix** [comment]
@HanaRebaiQA I was unable to reproduce the issue with the dev branch of autoupgrade: 

<img width="849" alt="Capture d’écran 2022-09-22 à 16 56 31" src="https://user-images.githubusercontent.com/2168836/191781367-e8f67dcb-9d30-40d2-8219-6595074df111.png">

**Comment by matthieu-rolland** [comment]
I reproduced the bug, but with autoupgrade on master branch, not dev :+1: 

![image](https://user-images.githubusercontent.com/1784781/191792123-7692851a-66b7-44ee-8546-282392947b11.png)

**Comment by HanaRebaiQA** [comment]
Hello @atomiix 

The issue is in the console

**Comment by HanaRebaiQA** [comment]
Hello @atomiix 

The issue is an error in the console: 500 Error 

![image](https://user-images.githubusercontent.com/92912932/191921746-e16dbc2f-cc71-463b-a225-61cd10cf1f8d.png)

**Comment by atomiix** [comment]
@HanaRebaiQA I don't have the error 500 in the console, I only have 403:
<img width="1426" alt="Capture d’écran 2022-09-23 à 11 12 52" src="https://user-images.githubusercontent.com/2168836/191929172-d29eb526-9f5b-4dfd-a8e3-098c72acc661.png">

Which make sense because once we upgraded, we need to log in again.

But then, if I try to go on the url like you did, I have the error 500:
<img width="1192" alt="Capture d’écran 2022-09-23 à 11 13 08" src="https://user-images.githubusercontent.com/2168836/191929681-3058a724-965d-44bb-8159-f38811149ee0.png">

But that's the expected behavior because we're not suppose to access this url with the `GET` method but with `POST`:
<img width="1193" alt="Capture d’écran 2022-09-23 à 11 13 35" src="https://user-images.githubusercontent.com/2168836/191929565-a9c5390b-7666-46a6-94a0-ed52a91d068a.png">

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

As @atomiix I didn't manage to reproduce the issue and it seems your issue related to not valid version number, see the attached screenshot (that I took from your screen record, after enabling the debug mode):

https://user-images.githubusercontent.com/23308427/192360832-510246a5-7ea3-410a-91be-80515afa7947.mp4

@matthieu-rolland your issue is not related to this one, it's related to the method installEmailsLanguagePack and it may related to this issue #28470
Closing the issue as it's not a bug :wink: 

Thanks!
