### ISSUE TITLE
Bad layout in Advanced Parameters > Security > Password policy

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#29790]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The form takes all the horizontal space instead of having a margin:

<img width="1571" alt="Screenshot 2022-09-28 at 12 25 31" src="https://user-images.githubusercontent.com/1009343/192756182-8d2a3c86-7155-45e1-b6d6-1935d1be15b7.png">

### Expected behavior

It should have a horizontal margin like the other forms:

<img width="1570" alt="Screenshot 2022-09-28 at 12 22 34" src="https://user-images.githubusercontent.com/1009343/192756239-06fc49aa-2a7b-42ee-9487-2f4bf67f0191.png">

### Steps to reproduce

1. Go to the page
2. Observe the bad layout

### PrestaShop version(s) where the bug happened

8.0.x branch

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @eternoendless 

Thanks for your report.
I was able to reproduce your issue with **PS8.0.x** with php7.3

![image](https://user-images.githubusercontent.com/92912932/192831112-bd4f0cde-950a-4b04-ba55-1a593192cdec.png)

The security page is not present in the **1.7.7** and **1.7.8** branches

So, indeed it's a regression

I'll add this to the debug backlog so that it's fixed.

Thanks for your PR!
