### ISSUE TITLE
BO > Profiles - If I bulk delete Profiles including mine, only the ones above mine will be deleted

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29838]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

https://user-images.githubusercontent.com/16019289/193547794-ad3f63fa-349b-46f5-bc1a-6f661fcb3ae3.mov

In my case, only "manager" profile is deleted, when 3 are selected.

It is not a regression.

### Expected behavior

I want to be able to delete everything except my own profile (or delete nothing, depending on PM decision)

### Steps to reproduce

As a employee with SuperAdmin Profile:
1. Go to BO > Team > Employee
2. Check All > Bulk Action > Delete selected
3. See message : "You cannot delete your own profile"

Result:
Every Profile _above_ SuperAdmin Profile are deleted
Every Profile _below_ SuperAdmin Profile are not deleted

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.6, 8.0.0

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by AureRita** [comment]
Hi @florine2623 ,

Thank for this reprot,I reproduce the issue with PrestaShop version1.7.7.8, as you can see on this video 

https://user-images.githubusercontent.com/100699445/193593561-2d32cbb8-e82d-4e4d-b82c-0ae62f16abe4.mp4

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. 

Thanks

**Comment by eshraw** [comment]
Hello, thanks @florine2623 , @AureRita 

Best case scenario should be "I cannot select my own profile for a bulk action" as bulk actions (enable/disable/delete) are affecting profile integrity.

Expected behaviour is as follow in case best case scenario cannot be achieved : 
- Given that I have admin rights
- When 
   - I select multiple profiles including mine using check boxes
   - And I try to perform a bulk delete
- Then 
   - I get the error "You cannot delete your own profile"
   - And no profile is deleted
