### ISSUE TITLE
Delivery in stock return empty string

### ISSUE THREAD

**Issue by compsoul** [PrestaShop/PrestaShop#29856]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Similarly issues: 
#28457
#18559

Product template not shows information from delivery_in_stock product variable value. I had checked on default template.

### Expected behavior

Showing information from BO

### Steps to reproduce

1. Set to default template to active
2. Edit `catalog/product.tpl`
3. Add variable `{$product.delivery_in_stock}`
4. Open FO product page
5. `{$product.delivery_in_stock}` is empty

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.9

**Comment by paulnoelcholot** [comment]
Hello @compsoul,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:

- screenshots
- clear and concise steps to reproduce


Thank you

**Comment by compsoul** [comment]
Steps:
1. Set to default template to active
2. Edit catalog/product.tpl
3. Add variable {$product.delivery_in_stock}
4. Open FO product page
5. {$product.delivery_in_stock} is empty

You have similar situations in my first report.

**Comment by sallemiines** [comment]
Hello @compsoul 

I test your issue following those steps with PS1778 ans PS1787 : 

- Access to **themes/classic/templates/product.tpl** 
- Add `{$product.delivery_in_stock|print_r}` in the file 
- Access to the FO 
- Click on a product 

==> In my test case I couldn't reproduce your issue, the displayed value in the FO is not emtty, you can see the attached screenShot 

![Capture d’écran du 2022-10-06 17-07-40 png (1561×1023)](https://user-images.githubusercontent.com/31663369/194365089-7b7e2a10-33e6-4f52-b3ef-ebce6d801abb.png)


![Capture d’écran du 2022-10-06 17-09-59 png (1421×831)](https://user-images.githubusercontent.com/31663369/194365085-ff6c86e5-ea10-470a-9e05-829f5a503435.png)

Thank you !

**Comment by frettka** [comment]
Hello, I happen to have the same issue with prestashop 1.7.8.5.
Variables $product.delivery_in_stock and $product.delivery_out_stock show empty on product page under related product minature. I have added following code to my template \mytheme\templates\catalog\_partials\minatures\product.tpl:
                {$product.delivery_in_stock|print_r}
		{$product.delivery_out_stock|print_r}
		{$product.delivery_information|print_r}
$product.delivery_information shows the correct value (it is default value from the shop settings) but other 2 variables (which are the values from the product settings show Array ( ) 1 -> as a result the delivery time doesnt show under the minature of related product.
Minatures under category page show correct values for all of those 3 variables. The problem is only with the minature under related products tab on product page.

Screenshots below. I would really appreciate any help with this problem. Thank you.

![category](https://user-images.githubusercontent.com/132687539/236502209-03facdbe-37dc-4b1d-b8ea-89543403976f.jpg)
![related-products](https://user-images.githubusercontent.com/132687539/236502213-a6e65860-73bf-447f-bb36-e14515ebba6f.jpg)
