### ISSUE TITLE
Incorrect number of columns when filtering in Shopping Carts page

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#29894]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In Shopping Carts page, if I filter on Numeric in Order ID, there are 8 columns rather than 9.

### Expected behavior

If I filter on Numeric in Order ID, there are 9 columns.

### Steps to reproduce

1. In BO, go to Shopping Carts page
2. There are 9 columns : 
![image](https://user-images.githubusercontent.com/1533248/194094866-6b34f8bc-f23a-46a1-bbe2-5dc2fd6c2b45.png)
3. If I filter on Abandoned carts, there are 9 columns
![image](https://user-images.githubusercontent.com/1533248/194095073-d3619544-1189-4580-8ee8-51046dbfc39d.png)
4. If I filter on Numeric in Order ID, there are 8 columns
![image](https://user-images.githubusercontent.com/1533248/194095222-13fdff4e-8711-4a2d-b950-aced90172a7a.png)

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

This is the expected behavior, because when looking for a valid cart (which you can't delete), then you won't have a column for delete checkboxes.
Closing the issue as it's not a bug.

Thanks!

**Comment by Progi1984** [comment]
@hibatallahAouadni We discuss with @PrestaShop/qa-automation and we think we should have an empty column. Isn't it ?

**Comment by eshraw** [comment]
Hey 👋 
Thanks for the issue @Progi1984 .

As this page has yet to be migrated ([#10584](https://github.com/PrestaShop/PrestaShop/issues/10584)) this falls in the improvement category (unless we have a clear regression from a past version).

Regarding the expected behaviour, according to UX principles we should value consistency over a cleaner look. As a result, we indeed need to stick with 9 columns in every table display in this page, even if that means we'll end up with an empty column in some cases.

I think that an UX review of this table might be a good thing to couple to the page migration @TristanLDD .

**Comment by ElodieOS** [comment]
Hello everyone!

For a quick action, I agree with @eshraw, we need to keep consistency regardless of the state to not lose the user. 

In the long term, I think we need to rework the ux of the data tables in general (several issues on it), but if you want a quick action, eshane's proposal is good :)
