### ISSUE TITLE
Notice: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by dobra947** [PrestaShop/PrestaShop#29901]
in file modules/ps_buybuttonlite/controllers/admin/AdminAjaxPs_buybuttonliteController.php (line 129)

```
        $image_data = Image::getBestImageAttribute($id_shop, $id_lang, $id_product, $id_product_attribute);
        $id_image = $image_data['id_image'];
```
Module version 1.0.1

**Comment by PrestaEdit** [comment]
Thanks @dobra947 for the report.

Ping @PrestaShop-maintainers : this repo allow issue on it.

**Comment by PrestaEdit** [comment]
Ping @PrestaShop/prestashop-maintainers

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-maintainers

**Comment by matks** [comment]
I suppose this is because this repository was once on https://github.com/prestashopcorp organization and was transferred to this organization

**Comment by matks** [comment]
Transferred 😄 

Dear @PrestaShop/qa-team I transferred this issue from https://github.com/PrestaShop/ps_buybuttonlite/ it was in the wrong place.

@dobra947 in order to make it easier to work on this issue do you think you could follow the format like in https://github.com/PrestaShop/PrestaShop/issues/29897 for example ? Provide steps to reproduce and expected behavior?

**Comment by sallemiines** [comment]
Hello @dobra947 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by PrestaEdit** [comment]
Next time, be carefull about closing issues, please. It's a valid one.

The lack of details is due to the fact that Issue template was not on the repository where the issue was created.
Also, it's less than a day that it was transferred and asked to get more details.

Thanks in advance for contributors.
