### ISSUE TITLE
All mails sent to one costumer

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#29919]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello

When I resend mail from history Tab Content, all mails are sent with name of one customer and his mail instead of the real buyer

Since I apply this solution 
https://github.com/PrestaShop/PrestaShop/issues/22215#issuecomment-748894921

![image](https://user-images.githubusercontent.com/11594433/194369327-0aa0635d-ed35-45a3-94a7-fada839d3696.png)

Regards

### Expected behavior

customer should receive mail with his correct name and address

### Steps to reproduce

Change order status or resend mail

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

**Comment by Hlavtox** [comment]
@go-sudo Hi, that is very weird. Nothing like this is happening on any Prestashop version I have ever used.

Check if you have any overrides or modules intervening with mailing/order processing.

Also, why there are missing lines in your screenshot? The IDs are not sequential.

**Comment by go-sudo** [comment]
Hi @Hlavtox 
I agree but it happens , you can check here i do not know why the mail is sent with other client name 
regards

**Comment by hibatallahAouadni** [comment]
Hello @go-sudo 

It seems that your issue is not a PrestaShop core bug.
Please disbale your overrides and disbale all non-native modules :pray: 

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

We will close this issue.

Thanks!
