### ISSUE TITLE
The 410 redirection is not saved on product page V1

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29945]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The 410 Gone was made onto the product page v2.

But the product page v1 show the help text and the option to choose the 410 as redirection.
It's seems not handled/saved.

### Steps to reproduce

1. Go to product settings
2. Change the redirection to 410

See that it's not handled in Front Office and that on refresh is 301.

### PrestaShop version(s) where the bug happened

8.0.0-beta.1

**Comment by sallemiines** [comment]
Hello @PrestaEdit 

Thanks for reporting the issue .
I tried to reproduce your issue with  Ps1787 & PS800 

Following your steps , i didn't reproduce the issue : 
`Go to product settings => Change the redirection to 410` => I cannot find this option in the page product settings , see the  attached screen-record


https://user-images.githubusercontent.com/31663369/195035985-2ab7f91e-500f-4a1e-8fd7-2410f94089a0.mp4


Could you please provides us a screen record shows all the steps 

Thank you !

**Comment by PrestaEdit** [comment]
Sorry, my steps was not clear enough.

I mean the product edition, not the settings of produts.

**Comment by AureRita** [comment]
Hi @PrestaEdit 

Thank for your details, I reproduce your Issue in 8.0.0 ( it can be reproduce on 1.7.8.7 because it's a new feature ) 
we can see a video of this issue here : 

[Untitled_ Oct 13, 2022 12_13 PM.webm](https://user-images.githubusercontent.com/100699445/195570662-053a01c5-7b97-4298-8177-adee4afc2f64.webm)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Waiting for your PR :rocket:

Thanks

**Comment by PrestaEdit** [comment]
It's merged, but never closed.
