### ISSUE TITLE
No more default tax rule when creating new product

### ISSUE THREAD

**Issue by VanigliaPro** [PrestaShop/PrestaShop#29982]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Creating a new product (manually or via API) there's no default tax rule selected, but it's set to "NO TAX" instead.

![Schermata 2022-10-12 alle 13 48 13](https://user-images.githubusercontent.com/115633430/195334999-70448307-4819-4ec6-9860-7627e14f8e4d.png)

### Expected behavior

In older Prestashop versions, when creating a new product, the field dedicated to the tax rule was automatically filled in with the ID1 default tax.

![Schermata 2022-10-12 alle 13 50 11](https://user-images.githubusercontent.com/115633430/195335339-0080b8ff-9c86-4f01-b1eb-7cbd337cd921.png)

### Steps to reproduce

1. Go to Catalogue
2. Create a new product
3. There will be no default tax rule selected

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by paulnoelcholot** [comment]
Hello @VanigliaPro ,

Despite our best efforts, we were unable to reproduce your issue with the information provided. Would you be able to provide us with more information so that we can reproduce it?

Thank you

https://watch.screencastify.com/v/Ev8VUDvT7v3BGLZF4tmg

**Comment by VanigliaPro** [comment]
Hi @paulnoelcholot 

There's nothing to do... I can't get the default Tax Rule... It's a fresh installation of Prestashop 1.7.8.7, no 3rd party modules installed. 

Maybe some language-related bug? I'm using Prestashop in italian.

Here's a video:
https://watch.screencastify.com/v/h2FPjHkOQ8p7MKKBBxv7

**Comment by paulnoelcholot** [comment]
I just created a new shop and I still can't reproduce this bug as you can see.

https://watch.screencastify.com/v/vwHfdWCy0TaHGCAjOpL1

Can you give me more informations to let me reproduce this issue. 

Thank you

**Comment by VanigliaPro** [comment]
Hi, 

what version of php and mysql are you using?
There's some way, for me, to force this feature to work as expected? A file to modify o something?

thank you.

**Comment by paulnoelcholot** [comment]
PHP 7.4 and MySQL 5.7

Can you go to : Internazionale --> Tasse -->  Did you have the same settings as this screen?
![image](https://user-images.githubusercontent.com/112863083/195373439-92862db6-4b8f-43fa-99db-fb9c4b206e53.png)

**Comment by VanigliaPro** [comment]
Same settings here:
![Schermata 2022-10-12 alle 16 44 20](https://user-images.githubusercontent.com/115633430/195374227-10cc2695-828a-43de-8751-ea7fc580260e.png)

I tried setting up php 7.4 on my VM but nothing has changed... I can't really understand why this happens.

**Comment by AureRita** [comment]
Hi @VanigliaPro 

I think I reproduce you issue, as we can see on this video : 

[Untitled_ Oct 13, 2022 12_03 PM.webm](https://user-images.githubusercontent.com/100699445/195567908-94bffd04-7925-464c-b717-d60a10465ac2.webm)

Just to have more information, could you say us if you have a taxe rules with id = 1 ? 

waiting for your feedback

**Comment by VanigliaPro** [comment]
Hi @AureRita 

unfortunately, seems there's a problem with the video you posted...

Anyway, i have tax rules active and with ID 1:

![Schermata 2022-10-13 alle 17 29 20](https://user-images.githubusercontent.com/115633430/195640196-aa8e5ea1-1b6d-42dd-a7e5-ff5e01cdeee5.png)

![Schermata 2022-10-13 alle 17 29 11](https://user-images.githubusercontent.com/115633430/195640241-fff0e78a-c55f-4b19-8c50-a408b885d266.png)

**Comment by hibatallahAouadni** [comment]
Hello @VanigliaPro 

Thanks for your feedback!
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a configuration problem.

PS: @AureRita that's the expected behavior cause you choose France as a Country when you install the shop. So when you delete the default tax, **`No Tax`** will be applied by default :wink: 

We will close this issue.

Thanks!

**Comment by CarolinePublipresse** [comment]
Hi, I'm having the same issue. 
How can we redefine the default tax ? I'm about 100% sure my clients will forget to add a tax if it is not defined by default. And it's gonna be always the same tax amount. So how can I set my defaut 20% FR TVA as default value ?

**Comment by HartLarsson** [comment]
> Hi, I'm having the same issue. How can we redefine the default tax ? I'm about 100% sure my clients will forget to add a tax if it is not defined by default. And it's gonna be always the same tax amount. So how can I set my defaut 20% FR TVA as default value ?

this is an interesting question because i was not able to setup a DEFAULT one too (if there is a way)

**Comment by Danilo8024** [comment]
Hi, I'm having the same problem on a prestashop where the taxes have been changed, @hibatallahAouadni answer doesn't give a solution, prestashop can't have a constraint (id_tax = 1) which we can't even modify by code to solve the problem. therefore, marking it as closed is not a solution. It would be nice to understand when creating a product which class assigns this (id_tax = 1 fixed), so that those who have this problem can solve it, without having to reinstall a new prestashop.

Personally, I have been trying to resolve this problem for days by restoring all the tax tables but the problem persists.

I hope someone can give comprehensive information on how to solve the problem.

Thanks for the support
