### ISSUE TITLE
When you have no image settings, there is an error on Front Office

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#30000]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you delete (even its not recommend) all the image settings, you have an error on the shop.

<img width="1700" alt="Capture d’écran 2022-10-13 à 17 08 27" src="https://user-images.githubusercontent.com/2631425/195635424-c2372049-1c71-46c7-bcec-f109a5fecf08.png">
<img width="1700" alt="Capture d’écran 2022-10-13 à 17 08 39" src="https://user-images.githubusercontent.com/2631425/195635432-688e36b0-3e26-490b-a006-d95933e4fcb4.png">

### Expected behavior

Have no error.

### Steps to reproduce

1. Delete all images settings
2. Go to your shop.

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.0

**Comment by AureRita** [comment]
Hi @PrestaEdit ,

I reproduce the issue with PrestaShop version 1.7.8.6 and not with the version 1.7.7.8,as we can see in this video : 

[Untitled_ Oct 13, 2022 5_13 PM.webm](https://user-images.githubusercontent.com/100699445/195636260-9ea84dde-84c0-4e9e-ad0f-c5ba9baa5457.webm)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved.

Waiting for your PR :rocket: 

Thanks

**Comment by matks** [comment]
Hello @AureRita I'm a bit curious as @PrestaEdit said: "If you delete (even its not recommend) all the image settings" 😅 

I have never heard of anybody that tried to delete all image settings and it seems really weird to me that one day a shop admin will decide to do it on purpose. Do you think even if this looks weird, this is still a major?

If you want to keep it `Major` it's OK for me it's just it really looks like something nobody will try ^^

**Comment by ghost** [comment]
@matks  if you knew what the merchants do  :o 

It's the 30 000 :100:

**Comment by PululuK** [comment]
# 30000 💯

**Comment by kpodemski** [comment]
We have PR coming to the core where there is information that if you delete image types used by the theme it may cause error. I think that'd be enough.

**Comment by Robin-Fischer-PS** [comment]
@matks Today we follow this matrix for the severity of the issues (sorry, it's in French), so even if it's highly unlikely, if the impact is really bad, it stays major.

However Miss Rita will check if there are workarounds, to be sure the impact is "really bad" and not just "bad" :stuck_out_tongue: 

![image](https://user-images.githubusercontent.com/55688534/195812698-2674645e-8274-4677-b4c4-7a029ff8427f.png)

**Comment by PrestaEdit** [comment]
Hi @Robin-Fischer-PS ,

Is this documentation is available in public, maybe ?

**Comment by matks** [comment]
@Robin-Fischer-PS I understand 😄  thank you for your answer

**Comment by Robin-Fischer-PS** [comment]
Hi @PrestaEdit ! Well, this specific matrix is not public, unfortunately it was done by the previous QA Manager, and since we had a lot of work and we left this subject aside...

For the moment, the only public documentation we have on issue management is this one : https://devdocs.prestashop-project.org/1.7/contribute/contribution-process/how-issues-are-sorted/

We are working on a new test strategy with more details (and maybe some changes on issue mangement), I hope we will be able to publish that soon.

In the meantime, I suggested to the QA team to give more details on the "Why" of the chosen severity, so that it is clearer for the contributor and for the people consulting the outcome.

**Comment by AureRita** [comment]
Hi @matks, 

After some research, I will let this issue at `major`, I will explain why : 
- for the main page, you just have to keep an image wich is selected for "products" whatever the name so this issue can be considered as "bad" instead of "really bad" 
- But, for the product page (so the second main page of a shop) if you just modify the name of "home_default" resolution, this page will be broken, so if you delete it and you don't remember the name, the product page will be broken and you "can't" repair this. So it can be considered as "really bad"

Moreover, I see two different possible scenario   : 
- If you've been hacked by person that want to break your shop (it's easy to know that will break things, you have a red notification at the top of the page ) 
- If you fired a person and he want to break your shop with his last modification on it for revenge

That's why I put the major label on it

**Comment by MatShir** [comment]
Seems the issue is not new https://github.com/PrestaShop/PrestaShop/issues/18867

**Comment by MatShir** [comment]
PrestaShop has never work with no image setting, (it kind works since some of the image are already generated, but your shop is definitely broken). So it is an expected behavior, ok the shop crash, we probably need to rework the UX. So like proposing to import the theme default image, if there are none or displaying an warning

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/18867

**Comment by PrestaEdit** [comment]
#30000 is a duplicate of... #30000 ?! :trollface:

**Comment by Hlavtox** [comment]
@PrestaEdit Nope, bad issue, I will link the correct one 😂 Fixed. :-)
