### ISSUE TITLE
Access back office Prestashop

### ISSUE THREAD

**Issue by beautifullook** [PrestaShop/PrestaShop#30010]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have a problem in the Prestashop back office. When I try to log in with my credentials, the page reloads every time, but it doesn't log in and the login screen appears. In the console I get GET 404 and "Failed to load source map in DevTools: Failed to load content for chrome-extension: //gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net :: ERR_FILE_NOT_FOUND."

### Steps to reproduce

I log in with my credentials and it won't let me in.

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @beautifullook 


It seems your issue is related to your server configuration.

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by beautifullook** [comment]
What should I do?
Thank you.
