### ISSUE TITLE
Override Class ImageManager is impossible

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#30041]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Impossible to override ImageManagerCore
When overrided in orders there is an error like this:
![imagemanager missing funtion](https://user-images.githubusercontent.com/9866119/196221532-45481b7c-b0aa-46ba-bb39-a398d5ad5323.jpg)
Sample module which overrides ImageManager
[overridexample.zip](https://github.com/PrestaShop/PrestaShop/files/9802266/overridexample.zip)

### Steps to reproduce

1 install module
2. go to orders -> orders

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @slupostrupek 

I reproduce the issue with PS1770, PS1787 and PS800! I’ll add this to the debug backlog so that it’s fixed.
Ping @PrestaShop/prestashop-core-developers could someone check if the problem persist with another module other the provided one :pray: 

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by rsoulard-prolaser** [comment]
Hello @slupostrupek
Your override of the ImageManager class is incorrect, it should extend the ImageManagerCore class

**Comment by slupostrupek** [comment]
Module should extends ImageManagerCore.  What is incorrect? Precise or upload working module

**Comment by matks** [comment]
Hello @hibatallahAouadni I think @rsoulard-prolaser is right : the given example module does not follow the official documentation about how override work. 

@slupostrupek Inside the module is a PHP class ImageManager.php and it should extend ImageManagerCore, like this:
```
class ImageManager extends ImageManagerCore
```

See documentation https://devdocs.prestashop-project.org/1.7/modules/concepts/overrides/

> In order to override the Product class, your file needs to be called Product.php and must feature a Product class that then extends ProductCore class.

@hibatallahAouadni As the example module provided to demonstrate the bug is not correct I am not sure this is indeed a bug 🤔 I think it requires more exploration.

**Comment by slupostrupek** [comment]
sorry, you have right extended was missing. Issue can be closed
