### ISSUE TITLE
All exports are not working

### ISSUE THREAD

**Issue by caromatias** [PrestaShop/PrestaShop#30083]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have several installations of Prestashop 1.7.8.6 and when using the export option in all the tables the site throws a timeout error and the PHP log reaches 60GB!
Please help, I haven't been able to solve this.

this appears in the PHP log
`Got error 'PHP message: PHP Warning:  feof() expects parameter 1 to be resource, null given in /home/website/webapps/app-website/src/PrestaShopBundle/Component/CsvResponse.php on line 289\nPHP message: PHP Warning:  fread() expects parameter 1 to be resource, null given in /home/website/webapps/app-website/src/PrestaShopBundle/Component/CsvResponse.php on line 290\n', referer: https://website/admin/index.php/sell/catalog/products?_token=`

this is the while that goes into a loop and collapses the log
```
private function dumpFile($handle)
    {
        fseek($handle, 0);

        while (!feof($handle)) {
            $buffer = fread($handle, 1024);
            echo $buffer;
            flush();
        }

        fclose($handle);
    }
```
Please help

### Steps to reproduce

Login BO > Open catalog > Products > Click export

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.1.33

**Comment by hibatallahAouadni** [comment]
Hello @caromatias 


I didn't reproduce the issue with the provided info, it seems your issue is not related to your server configuration.

So closing the issue as we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
