### ISSUE TITLE
An uninstalled module with deleted folder remains displayed with an Install button available

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#30095]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

On version 8.0.0 rc1
If you decide to uninstall a module by checking the option to delete the folder, at the end of the operation, the module is still displayed in the list of modules with an Install button which, of course, causes an error when clicked.

### Expected behavior

Logically, the module should disappear from the list or at least no longer offer a button to perform any action on it.

### Steps to reproduce

1. Go to the list of modules
2. Uninstall a module by checking the box to delete its folder

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @jeckyl 

Indeed Sir, after uninstalling and deleting a module, you still find the module well displayed in the modules list with install button.
Cause in the new release 8.0.0, as you notice, we remove the *Module Catalog* page and we create a new native module that update all installed modules (if there's a new released version, an upgrade button will be displayed) and list all uninstalled native modules (to make it easy for merchant to install them without problems).
So, this is the expected behavior! 
If you want, I can ping the product team to explain more why we change this behavior. 

Please ping me for any other questions ☺️ 

Sorry Sir, but I have to close the issue as this is the expected behavior.

Thanks for your understanding 🙏
