### ISSUE TITLE
Calculated tax error on product 1.7.8.x test

### ISSUE THREAD

**Issue by Esh-network** [PrestaShop/PrestaShop#30137]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, I have a problem with the calculation of taxes in the product sheet with a simple calculation.

Price including VAT - PRICE excluding VAT which normally gives the difference between the two.
Exemple : 
 27,90€ -  26.45€ = 1.45
 The bug occurs if I set a rounding to 1 or 2... If I set the rounding to 0 the bug is not present (however I need the rounding to 2)
 
 Except that prestashop shows me something else :
 
 ![taxe1](https://user-images.githubusercontent.com/54634416/198290360-d747f3cb-aa31-4fa2-98b2-da637303d91f.png)
 
 Mon code : 
 
 VAT and costs included: approx. {$product.price - $product.price_tax_exc}€ <- ( {$product.price}ttc - {$product.price_tax_exc}ht )

### Steps to reproduce

1. Go to currency and round to 2 (precision)

2. In a product sheet add your price excluding or including tax with VAT at 5.5% (do not test on 20% because I am not interested).
You can also test by putting combinations

3. Add this variable in product-price.tpl
(Themes->yourtheme->templates->catalog->_partial)

Then go to your product page and test

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @Esh-network ,

It's normal that the calculation is incorrect.
Because you are using 2 different types of variables.
<img width="104" alt="Screenshot 2022-10-31 at 10 01 36" src="https://user-images.githubusercontent.com/16019289/198971467-ab06910d-ae18-41b5-8e49-e3e204cc9ab2.png">

You need to be using this: `{$product.rounded_display_price-$product.price_tax_exc}` to get you tax value.
Or create your own variable.

<img width="562" alt="Screenshot 2022-10-31 at 10 07 22" src="https://user-images.githubusercontent.com/16019289/198971968-1f77190c-1a1f-466b-acd2-64760c5bf032.png">

I'll close you issue as I the issue doesn't come from PrestaShop itself.
Thanks!
