### ISSUE TITLE
Incorrect discount voucher value at Cart backoffice page, when cart has more than one products

### ISSUE THREAD

**Issue by nsakiotis** [PrestaShop/PrestaShop#30264]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The bug is reproducable on Shopping Cart backoffice page, for carts having more than on products and a discount voucher.

While the "Total value of vouchers:" is correct, the value for the individual vouchers (even if there is only one voucher used) below is not correct. It seems to me, that for the individual voucher not the total product price is used for the calculation, but only one product (see screenshot)
![Capture](https://user-images.githubusercontent.com/4609108/201138048-6eba2629-2af2-4bc7-bb6b-13dd9590d5eb.JPG)

### Expected behavior

 since the customer uses only one voucher, the individual discount voucher value should match the total one

### Steps to reproduce

Open Shopping Cart backoffice page, for a carts that has more than on products and a discount voucher.

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hello @nsakiotis ,

Your issue is similar to https://github.com/PrestaShop/PrestaShop/issues/22948 and has been fixed in https://github.com/PrestaShop/PrestaShop/pull/24088.

You can upgrade your issue to get the fix or apply the fix direct on your shop.

Also, your PHP version is to high for your PS version, you need to downgrade it : https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/

I'll close your issue has it is fixed.
Thanks!
