### ISSUE TITLE
Problem When you try to edit a Product that have combinations

### ISSUE THREAD

**Issue by Yan-Studio-WEB** [PrestaShop/PrestaShop#30305]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I try to edit a product with combination and save the all site is freezing and cannot access it any more.
to access it again a trick that i found it was to toggle back and forward the php version from server cPanel

### Expected behavior

to edit a product with no issues

### Steps to reproduce

1. Go to edit a product that have combinations
2. try to erase the combinations and save
3. the site is getting frozen

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.3 , 8.0

**Comment by sallemiines** [comment]
Hello @Yan-Studio-WEB 

Thanks for reporting the issue

Following your steps I tried to reproduce your issue with` PS 800 + PHP 8.0 `, `PS 800 + PHP 7.4` , `PS 1787` , but i didn't manage to reproduce it

You can see the attached screen records : ( i tried to edit /delete combinations) 

[Untitled_ Nov 16, 2022 4_05 PM.webm](https://user-images.githubusercontent.com/31663369/202218395-176efee8-176c-43da-8a33-c45f365e6cc3.webm)

[Untitled_ Nov 16, 2022 4_05 PM.webm](https://user-images.githubusercontent.com/31663369/202218496-576d769f-381f-4ca0-b910-1e0d5798406b.webm)

Could you please check if your issue is similar to this one ? [issue-30179](https://github.com/PrestaShop/PrestaShop/issues/30179)

Waiting for your feedback ! 
THank you

**Comment by Yan-Studio-WEB** [comment]
Hi
Sorry for the late reply
I had to install 2nd time and check again from the beginning
So i confirm that the problem is there and is serious!!!
I have install 3rd time a new presta because to my second attempt it was not possible to make the site work
The 3d installation is for you, please tell me where to send you the login details to see for your self don't worry is a test site do what ever you like

**Comment by AureRita** [comment]
Hi @Yan-Studio-WEB 

Unfortunately, we didn't reproduce issues on other setup than our setup ( to see if the issue is due to an intern problems or not, 

I try to reproduce your issue and I didn't success to do it, as you can see ( I test it with a new product ) 

[Untitled_ Nov 18, 2022 2_43 PM.webm](https://user-images.githubusercontent.com/100699445/202718830-851588c9-67fb-41b9-99e5-aae78efdd7f0.webm)

can you give us a video of your issue ? 

Waiting for your feedback

**Comment by Yan-Studio-WEB** [comment]
Hi
Ok.
Here is the video: https://www.dropbox.com/s/fe6hgm7kt7ifwz5/Issue-when-i-delete-combination.mp4?dl=0
Here is the link of the page i fix it https://www.arion-patmos.gr/en/
the way i describe in my previous message
Thanks in advance

**Comment by Yan-Studio-WEB** [comment]
in continuation of the previous message
If I go and try to edit this product again the problem occurs again if i wait for 5 minutes then the page start to work again

**Comment by AureRita** [comment]
I tried again with the same product that you selected, as you can see, I can't reproduce the problem 

[Untitled_ Nov 18, 2022 4_54 PM.webm](https://user-images.githubusercontent.com/100699445/202746735-1fa7c621-7ebb-485e-b975-2145a1744233.webm)

@PrestaShop/qa-team someone can reproduce the problem ? 

Thanks

**Comment by Yan-Studio-WEB** [comment]
Ok I see that this is on local server maybe this is something we have to consider???
Did you tried on live server?

**Comment by paulnoelcholot** [comment]
Hello @Yan-Studio-WEB,

I have tested this issus and I can't reproduce the problem as you can see : 

https://watch.screencastify.com/v/Q6h1mAUSIGwmFzEQpt3k

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

You can also search on this doc : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

Thank you
