### ISSUE TITLE
FO: Sign in link is not functional when all carriers are disabled in BO

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#30325]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Bo, when a user tries to disable all existing carriers, and  in FO , he tries to add a product to cart, then he clicks checkout button and tries to login, the login link  is not functional

https://user-images.githubusercontent.com/31663369/202472088-c99a13a6-112b-4b2d-835b-e3c4a269de3a.mp4

### Expected behavior

In FO, the sign in link should be clickable

### Steps to reproduce

1. Connect to Bo > Shipping > Carriers page  >  disable all the existing carriers
2. Go to FO 
3. Add to cart some product
4. Proceed to checkout 
5. Click on sign in 

**=>** The sign in link is not clickable 

1. Go back to Bo > Shipping > Carriers page  > Enable one or more carriers 
2. In FO, the sign in link is clickable

**PS: Scenario tested with :**

-  PS 1.7.8.7 +PHP 7.4 OK
-  PS 8.0.0 + PHP 7.4 OK 
-  PS 8.0.x + PHP 7.4 OK 
-  PS 8.0.0 + PHP 8.0 OK
-  PS 8.0.x + PHP 8.0 OK 
-  PS 8.0.0 + PHP 8.1 NOK
-  PS 8.0.x + PHP 8.1 NOK

### PrestaShop version(s) where the bug happened

8.0.x , 800

### PHP version(s) where the bug happened

8.1

**Comment by HanaRebaiQA** [comment]
Hello @sallemiines 

Thanks for your report :tada: 
I was able to reproduce your issue with **PS8.0.0** only with **php 8.1**
But, i was unable to reproduce it with **php 7.4**

**php7.4 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/202478690-3600d98a-13ef-4f74-95f1-258cbeeb7205.png)

**php8.1 : NOK** :x: 

https://user-images.githubusercontent.com/92912932/202478660-f188e052-508d-413c-96a2-75c01405cd0a.mp4


So, it's a regression! 

I'll add this to the debug backlog so that it's fixed.

Thank You!

**Comment by HanaRebaiQA** [comment]
It's related to [#30078](https://github.com/PrestaShop/PrestaShop/issues/30078)

**Comment by florine2623** [comment]
I'm closing the issue as it is fixed.


https://github.com/PrestaShop/PrestaShop/assets/16019289/df43f478-29df-4282-91cf-ea808b214f25
