### ISSUE TITLE
FO - Guest tracking link in email is not redirecting to the correct URL

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30447]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In any email containing the `Guest tracking` link, there's a wrong redirection to Order History.

https://user-images.githubusercontent.com/16019289/204581260-22912bb1-f017-4ba8-a8de-0b9c5df002e2.mov

Tested on :
`1.7.8.7` and `8.0.0` OK ✅ 
`1.7.8.8` and `develop` NOK :x:

### Expected behavior

The link for Guest tracking in the email should redirect to :

<img width="1146" alt="Screenshot 2022-11-29 at 17 51 17" src="https://user-images.githubusercontent.com/16019289/204591925-2399368e-dfd9-4d57-8f04-eb67c3b901f6.png">

https://user-images.githubusercontent.com/16019289/204581433-0fff31db-829c-4e51-acf3-0a016124095f.mov

### Steps to reproduce

1. Go to BO > Orders > Change status to `Awaiting bank wire payment`
2. Check your emails
3. Scroll to the Guest Tracking link
4. Click on it, see wrong redirection

### PrestaShop version(s) where the bug happened

1.7.8.8, develop

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @florine2623 

Thanks for your report.
I tried to reproduce your issue on 1788 build1, but it seems that's the expected behavior.
When you are **logged IN** : it's redirected to `Guest Order Tracking`
When you are **logged OUT** : it's redirected to `Order history`

As you can see in this screen record: 

https://user-images.githubusercontent.com/92912932/204755660-107872fa-35b2-4d30-a642-829e274bffb0.mp4

So, i'll close the issue.

Thank You
