### ISSUE TITLE
Error when sort by Price

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30440]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

From the FO, if I choose to sort products according to their price, the products are no longer visible.

https://watch.screencastify.com/v/Xb6QnVxYlnZgMUAj42oO

### Expected behavior

Products should remain visible and sorted by price

### Steps to reproduce

1. Go on FO
2. All products
3. Sort by "Price, high to low"
5. Sort by "Price, low to high"
6. See error

Only present on 1.7.8.8. 

Tested and OK on 1.7.8.7 and 8.0.0

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @paulnoelcholot 
Thanks for reporting the issue.

As we discussed on Slack, you need to configure the `facetedsearch`  module  in BO > Module Manager
Click on all 4 buttons : I**ndex all missing prices** / **Rebuild entire price index** / **Build attributes and features indexes** / **Clear cache** and then you will find that the bug will dispeared, you can see the attached screenshot 

![image](https://user-images.githubusercontent.com/31663369/204554363-7e226283-1135-4b53-bc5a-96446ddfa944.png)

You can see the attached screen record : the issue is not exist 

[Untitled_ Nov 29 2022 3_23 PM.webm](https://user-images.githubusercontent.com/31663369/204554727-1a0ba3b5-7b24-4fef-8f47-a14b5a735dbf.webm)


Thank you !
