### ISSUE TITLE
Registration Form validation errors in email field

### ISSUE THREAD

**Issue by PrestaVision** [PrestaShop/PrestaShop#30475]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Clean installation of PS 8.0.0.0 on PHP 8 or any PHP. When a new customer wants to register in frontend, normal email adresses work, like: name@domain.com. However: when emailadress is complicated like: part1-part2-part3part1-part2-part3part1-part2-part3@subdomain.domain.com , the form responds with 'invalid format'.  PS 1.7.8.7 (on PHP 7.x) did not have that problem.
<img width="1109" alt="Screenshot 2022-12-15 at 12 23 39" src="https://user-images.githubusercontent.com/16019289/207847172-ec02e9b4-de4b-4313-8bd8-25ff8e25c1dc.png">

In backoffice, when creating a new customer the same way, i get error 'Unexpoected Error. [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerException code 0]: Customer contains invalid field values'
<img width="1213" alt="Screenshot 2022-12-15 at 12 22 51" src="https://user-images.githubusercontent.com/16019289/207847226-e6648d08-37db-4690-9327-8673f9d2a446.png">

### Expected behavior

I expect that customer can register with dashes - before the @ sign and multiple dots . after the @ sign in the emailfield of the registry form, i.e. part1-part2-part3part1-part2-part3part1-part2-part3@subdomain.domain.com

### Steps to reproduce

On frontend of PS 8.0.0.0 on PHP 8:
1. go to Login/Register
2. fill in the fields accordingly, but use an email adress like: part1-part2-part3part1-part2-part3part1-part2-part3@subdomain.domain.com
3. click on Submit/Register

The frontend error will appear.

On backoffice:
1. go to Customers
2. click on 'Add New Customer'
3. fill in the fields accordingly, but use an email adress like: part1-part2-part3part1-part2-part3part1-part2-part3@subdomain.domain.com
4. click on Submit/Register

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

the PS registry form

**Comment by hibatallahAouadni** [comment]
Hello @PrestaVision 

Thanks for the detailed issue report :pray: 
I believe this is the wanted behavior as you can see in these issues discussions: #20351 & #22131
Please check and feedback.

Thanks!

**Comment by PrestaVision** [comment]
Hello @hibatallahAouadni 

Yes, that is the correct error i am talking about. 

Many thanks!

**Comment by hibatallahAouadni** [comment]
Hello @PrestaVision 

I didn't manage to reproduce your issue with PS800, see the attached screen record below:

[issue_30475.webm](https://user-images.githubusercontent.com/23308427/205862925-84cc83e1-c54c-4046-a65c-10151548d9dc.webm)

Could you please provide a screen record or screenshot of the displayed error :pray: 
Waiting for your feedback.

Thanks!

**Comment by PrestaVision** [comment]
Screenshots of live site, both frontend and backoffice of registration of new customer with emailadress sample.
![0002](https://user-images.githubusercontent.com/119726053/205867194-45f17d70-a38d-41af-be30-1076f3db993e.jpg)
![0003](https://user-images.githubusercontent.com/119726053/205867204-e728f369-36f4-4f90-82f8-c27f6f4211d1.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @PrestaVision 

Could you please disable your overrides and all third-party modules, then check if you still encounter the same issue.
Waiting for your feedback.

Thanks!

**Comment by PrestaVision** [comment]
Hi @hibatallahAouadni 

i disabled the setting at >Advanced>Performance>setting above Debug Error. Then i flushed the cache.

Frontend: the error remains the same.
Backoffice: the error remains the same.

**Comment by sallemiines** [comment]
Hello @PrestaVision

Unfortunately following your steps , I didn't manage to reproduce your issue with `PS800`,  you can see the attached screen record :

[Untitled_ Dec 7 2022 10_59 AM.webm](https://user-images.githubusercontent.com/31663369/206148231-06523b64-ba76-42a4-8635-6d8498ba3542.webm)

Could you please provide more infos ? 

Thank you !

**Comment by florine2623** [comment]
Hello @PrestaVision ,

I reproduced the issue with PrestaShop version 8.0.0, I'll add this to the backlog so it can be fixed.

The issue does not come from the format, but the length of the field.
I tested with `part1-part2-part3@subdomain.domain.com`. the form could be saved in BO and FO.
But with `part1-part2-part3part1-part2-part3part1-part2-part3@subdomain.domain.com`, I had an error.

In both cases (BO and FO), the error message should be clearer.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by HanaRebaiQA** [comment]
Hello everybody, 

Me too I tried to reproduce this issue **on PS8.0.0 with both php7.3 and php8.0 and on PS1788 with php7.3.**

The problem comes when using this address email `part1-part2-part3part1-part2-part3part1-part2-part3@subdomain.domain.com` only on PS8.0.0 as mentioned above by @florine2623 

So, with P**S8.0.0 php 7.3 and php 8.0** with this address part1-part2-part3@subdomain.domain.com (provied by @PrestaVision) when creating a new customer on BO and FO : **OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/208073974-f60efa62-2735-4759-b3ae-b335b7c30054.mp4


https://user-images.githubusercontent.com/92912932/208074078-8597d320-744f-4591-992d-a9c70da1b511.mp4


**PS8.0.0 php 7.3 and php 8.0** with this address format `part1-part2-part3part1-part2-part3part1-part2-part3@subdomain.domain.com` when creating a new customer on BO and FO : **NOK** :x: 


https://user-images.githubusercontent.com/92912932/208074426-281f3524-2561-47a5-a387-a57e85c8beb7.mp4



https://user-images.githubusercontent.com/92912932/208074287-4b39dfcb-1029-49b4-8319-7f25ee6f2fa0.mp4


**PS1788 with php7.3** with this address format `part1-part2-part3part1-part2-part3part1-part2-part3@subdomain.domain.com` when creating a new customer on BO and FO : **OK** :heavy_check_mark: 


https://user-images.githubusercontent.com/92912932/208074528-0658b60f-0ae3-4441-908c-5639c61c4a7b.mp4



Indeed, it's a regression on 8.0.0! 

Thank You!
