### ISSUE TITLE
Fix htmlentities by Tools::htmlentitiesUTF8 to keep behaviour in php 8.0

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#30573]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

To be sure to escape simple quote in PHP 8.1 it's better to use Tools::htmlentitiesUTF8() that use ENT_QUOTES flag (ENT_COMPAT since php 8.1+)

### Expected behavior

Escape simple quote with php 8.1

### Steps to reproduce

Add an author name with a simple quote.
It should be replace by the corresponding html entity.

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

productcomments 5.0.1

**Comment by hibatallahAouadni** [comment]
Hello @clotairer 

Thanks for reporting the issue and for your PR :rocket: 
Could you please provide clear and concise steps to reproduce the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by clotairer** [comment]
This is the same issue fixed by @atomiix here https://github.com/PrestaShop/productcomments/security/advisories/GHSA-prrh-qvhf-x788 but due to php 8.1 specification changes, the XSS is not prevent by htmlentities.

**Comment by atomiix** [comment]
@clotairer it seems that this is the other way around, before php 8.1, `ENT_COMPAT` was the default flag and was ignoring single quotes, but since php 8.1 the default flags are `ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401` thus escaping single quotes.

While I see that single quotes wouldn't be escaped with php version < 8.1, in this context I can't see any possibility of XSS. Am I missing something?

**Comment by clotairer** [comment]
@atomiix 
In php 8.1 :
```php
htmlentities("<script src='test.js'></script>");
// &lt;script src='test.js'&gt;&lt;/script&gt;
```
You are right, we can consider, htmlentities escape the main caracters and in the case of this module, no XSS is exploitable.

I close this issue.

**Comment by touchweb-vincent** [comment]
Hello, 

There is two distincts subjects there : 

1. Is this harmful to use htmlentities without configuration for this module : after reflexion we do not have any POC to give - for the moment - so no, it's harmless in state until proven otherwise

2. Lead by example on the ecosystem : htmlentities without configuration on PHP 8.0- must be considered risky and should never be writen like this (injection SQL and probably some XSS we do not have in mind for the moment) - https://onlinephp.io/c/0226f3

It would be wise to keep in mind point 2.

Kind regards,

Vincent
