### ISSUE TITLE
[Sentry] Reports almost no error

### ISSUE THREAD

**Issue by d0niek** [PrestaShop/PrestaShop#30635]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've created new module which add integrations with Sentry. In file **$root_dir/config/defines_custom.inc.php** I've added code like:

```php
require_once "/var/www/html/config/defines.inc.php";
require_once _PS_CONFIG_DIR_ . 'autoload.php';
require_once "/var/www/html/modules/mymodule/vendor/autoload.php";

\MyModule\Sentry\Helper\SentryRunner::run();
```

and in `\MyModule\Sentry\Helper\SentryRunner::run();` is simply `\Sentry\init(['dsn' => '...']);`.

But almost no "hard" errors/exceptions (front/back office) aren't reported to the sentry only few silence (deprecated) are. It looks like Prestashop/Symfony cutoff sentry handlers?

I've also tired with hook `actionDispatcherBefore` in which run same code:

```
\MyModule\Sentry\Helper\SentryRunner::run();
```

### Expected behavior

Report all "hard" errors/exceptions (front/back office) to sentry.

### Steps to reproduce

1. Create new module and add sentry `composer req sentry/sdk`.
2. Init sentry in **$root_dir/config/defines_custom.inc.php** or `actionDispatcherBefore`.
3. Make error in other place/module, e.g. ask container for non existing service `$this->get('non-existing-service');`.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.30

### If your bug is related to a module, specify its name and its version

mymodule v0.1.0

**Comment by HanaRebaiQA** [comment]
Hello @d0niek 

Thanks for your report.

Could you please provide the module that you used?

ping @PrestaShop/prestashop-core-developers Could you please check this issue? It seems to be too technical

Thank You!

**Comment by d0niek** [comment]
Hi @HanaRebaiQA!

Thanks for your response! Here is my module I've created https://github.com/eXtalionLab/prestashop-sentry

**Comment by kpodemski** [comment]
Hi @d0niek 

Could you check on PrestaShop 8.0?

**Comment by d0niek** [comment]
Hi @kpodemski!

I'm not ready on PrestaShop 8.0 :-/ I'm using latest (old) docker image `prestashop/prestashop:1.7-fpm` for my prod/dev. Waiting for updates other merchants modules and `autoupgrade` to allow make upgrade from `1.7 -> 8.0`

I'll try to run it on local PrestaShop 8.0.

**EDIT**

Just saw release `autoupgrade:4.15.0` which allow to upgrade PrestaShop `1.7 -> 8.0`.

**Comment by kpodemski** [comment]
Please do try on the clean PrestaShop 8.0 installation, as there were some changes to how errors behave in the front office.

**Comment by atomiix** [comment]
I think that @lmeyer1 can have some clues on this topic!

**Comment by lmeyer1** [comment]
Hello, indeed, I also found that Sentry logs very few issues unless we tweek Prestashop for it. I didn't find a way to handle all this in a module, because it needed quite a lot of changes in core files. Have a look at https://medium.com/@lmeyer./get-an-error-free-e-commerce-web-site-using-sentry-b6061264efc8 in the section `Full PHP integration with PrestaShop`.

In short: Sentry logs only uncatched exceptions, but in Prestashop most of the exceptions are catched by default. We must override at lest these classes: `PrestaShopException`, `PrestaShopLogger` and `DbPDO`

**Comment by d0niek** [comment]
@kpodemski! I've just installed `PS8.0` ([docker](https://hub.docker.com/layers/prestashop/prestashop/8.0/images/sha256-c500df464ac4409f8e5d221d5efce0d9a6b90f4c95cfb8850176c4dfc86ac4cc?context=explore)) and added my module. The same "error", none errors are logged to Sentry.

![obraz](https://user-images.githubusercontent.com/9316891/210400218-83d7ec0e-b576-46b6-92ed-cf0b5a4cab16.png)

Maybe @lmeyer1 has good clue?

**Comment by lmeyer1** [comment]
@d0niek 
Hello, indeed, I also found that Sentry logs very few issues unless we tweek Prestashop for it. I didn't find a way to handle all this in a module, because it needed quite a lot of changes in core files. Have a look at https://medium.com/@lmeyer./get-an-error-free-e-commerce-web-site-using-sentry-b6061264efc8 in the section `Full PHP integration with PrestaShop`.

In short: Sentry logs only uncatched exceptions, but in Prestashop most of the exceptions are catched by default. We must override at least these classes: `PrestaShopException`, `PrestaShopLogger` and `DbPDO`

**Comment by d0niek** [comment]
@lmeyer1 I've read this article :-)

**Comment by kpodemski** [comment]
@d0niek, as there's no way that it would be improved in 1.7.8, and there's no clear way how to implement it inside future version, I suggest I close this ticket, and we can discuss it in some other place

I'll ping you after creating a discussion for this feature request.
