### ISSUE TITLE
Incorrect product name displayed on front office #30647

### ISSUE THREAD

**Issue by arcofins** [PrestaShop/PrestaShop#30655]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I  created a product with a test name (azertyu) in order to make some tests.
I changed the name of my product in my back office. The product name is well displayed on my home, but on the product page I still have the old name (azertyu).

**I already checked the product name in different languages. 
I already cleared my cache (browser, server and Prestashop BO) and I still got this problem.**

What can I do to update the name of the product on the product page.

(cf screenshots)

The product displayed on the homepage

![](https://user-images.githubusercontent.com/65950828/209107292-b8c6d559-af14-46a3-9878-c614723c2a1e.png)

The product page with the bug

![](https://user-images.githubusercontent.com/65950828/209107389-dd3564a3-c530-4179-a49b-0e80afc6cae6.png)

The back office product page (same page for FR/GB)

![](https://user-images.githubusercontent.com/65950828/209107432-1aad8c29-1c95-4400-aa53-ec61dee6878f.png)

### Expected behavior

Just display the good name on the product page.

### Steps to reproduce

Go to backoffice / catalog
try to edit the product (ID784)
Go to the product page (no change)

### PrestaShop version(s) where the bug happened

1.7.1.2

### PHP version(s) where the bug happened

7.1

**Comment by kpodemski** [comment]
Hello @arcofins 

It's been years since the release of PrestaShop 1.7.1. I would highly suggest you check this behavior using the newest PrestaShop version. This is not a support center but a place where you can report bugs that may be found in the latest version of the software. As this is a common feature to have the store in a few languages, there's no chance for a bug like this to go unnoticed.

Other options are to visit the project's [Slack](https://www.prestashop-project.org/slack/) or create a topic on [PrestaShop Stack Overflow](https://stackoverflow.com/questions/tagged/prestashop), [forum](https://www.prestashop.com/forums), some Facebook support group in your country, etc.

My gut tells me that your store has some modifications that allow you to manage `<h1>` on the product page separately.
