### ISSUE TITLE
npm run build fails in both node 14 & 16 with ps_buybuttonlite module 

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#30691]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are incompatible issues between node-sass, sass-loader and Node in current [dev package.json](https://github.com/PrestaShop/ps_buybuttonlite/blob/dev/app/package.json) that make `npm run build` fail.
With Node 14:
![ps_buybuttonlite_node14_node-sass-v7_incompatible_with_loader-4 0 0](https://user-images.githubusercontent.com/3759923/209916225-cf07dbd6-cde7-485e-a626-c1c6eec13ff0.png)
With Node 16:
![ps_buybuttonlite_node16_node-sass-v7_incompatible](https://user-images.githubusercontent.com/3759923/209916240-d80a801c-b1e5-4d19-8fff-42734ca89681.png)

### Expected behavior

`npm run build` succeed in Node 14 and/or Node 16

### Steps to reproduce

1. git clone ps_buybuttonlite
2. `cd modules/ps_buybuttonlite/app`
3. switch to Node 14 or Node 16 with `nvm`, then
`npm install`, `npm run build`
to see the errors.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_buybuttonlite 1.0.1

**Comment by HanaRebaiQA** [comment]
Hello @leemyongpakvn 

Thanks for your report.
I tried to reproduce your issue with PS1787, PS8.0 and PS1778 using the latest version of module `ps_buybuttonlite 1.0.1` and `ps_buybuttonlite 1.0.0` and i reproduced these errors : 

**Node version: v14.20.1**

**Check with PS1787 with ps_buybuttonlite 1.0.1 : NOK** 

- When running the npm install: OK
- When running the npm run build: NOK

![image](https://user-images.githubusercontent.com/92912932/209967260-e9bcb383-6645-40c2-8dda-156714c699f5.png)

https://user-images.githubusercontent.com/92912932/209967810-91858a4e-a9da-4f87-98d2-ab061a708f0a.mp4


**Check with PS1787 with ps_buybuttonlite 1.0.0 : NOK** 

- When running the npm install: NOK
- When running the npm run build: NOK

![image](https://user-images.githubusercontent.com/92912932/209967310-9f71ff85-75d6-4ee3-86ae-12b8a76d93fc.png)

https://user-images.githubusercontent.com/92912932/209968213-f762c545-1c40-4688-a62b-f750cc5b478d.mp4


**Check with PS800 with ps_buybuttonlite 1.0.1 : NOK** 

- When running the npm install: OK
- When running the npm run build: NOK

![image](https://user-images.githubusercontent.com/92912932/209968592-0ee371a8-ba19-4544-a174-eb5ba7cfe253.png)

https://user-images.githubusercontent.com/92912932/209968365-44b528ac-ed2e-463a-b0a5-cfd30a70ca66.mp4


**Check with PS1778 with ps_buybuttonlite 1.0.1 : NOK** 

- When running the npm install: OK
- When running the npm run build: NOK

![image](https://user-images.githubusercontent.com/92912932/209968465-2704406d-62f5-4215-b01b-71fec53748cf.png)

https://user-images.githubusercontent.com/92912932/209968812-edfde65d-dc7c-4ba1-9781-c7e33fdf2623.mp4


So, it's not a regression of the PrestaShop version nether of the module version.

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

Thanks for the Pull request!

**Comment by davidglezz** [comment]
The [repo](https://github.com/PrestaShop/ps_buybuttonlite) is archived. Should we close this issue?

**Comment by leemyongpakvn** [comment]
Close as the repo is archived.
