### ISSUE TITLE
Handle low_stock_alert field by low_stock_threshold value in product and combination handlers

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#30750]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Currently in new product page combination form data handler the low_stock_alert is depending on dedicated disabling_switch_low_stock_threshold input (and there is a dedicated $lowStockAlert property in the UpdateCombinationCommand which handles dedicated low_stock_alert field in database). 

### Describe the solution you'd like

We discussed with @jolelievre that it will probably be better/cleaner to handle the field based on the low_stock_threshold value, so basically if the value is = 0 then we assume the low_stock_alert = false.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by jolelievre** [comment]
The purpose here is mostly refacto it would imply:
- simplifying commands and queries so that we don't have two getters/setters (one for boolean the other one for value), but a single one
- it would still update both fields in the DB appropriately (0 == false)
- the provider and handlers/builders should be improved to avoid relying on the disabling switch parameter in the request (if possible) as the disabling extension is supposed to correctly adapt the data (this will need to be tested though, I may not realize some difficulties here)
- this should be cleaned in all forms/handlers/providers (product, combination, bulk combination)
