### ISSUE TITLE
Error 500 when Group Default is selected

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30771]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When Product V2 and multishop are enabled, Group Default make a 500 error

https://watch.screencastify.com/v/3vqoLfTvbTkoyDfUCVBP

### Expected behavior

This shouldn't be the case, it should display all products belong to the Group Default without any error.

### Steps to reproduce

1. Enabled Multishop
2. Enabled Product V2
3. Create a shop
4. Select Group Default
5. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @paulnoelcholot 

Thanks for reporting the issue! 
Indeed it's a regression on develop as I couldn't reproduce it with PS8.0.0.
I will put it in the Project backlog to be fixed.

Thanks

**Comment by jolelievre** [comment]
Hi @hibatallahAouadni 

It can't be considered a regression since the multishop was not handled in 8.0 there is nothing to compare here, so not a regression.

However @paulnoelcholot, I tried to reproduce the bug by doing the same steps but I didn't have the bug. I'm on MariaDB but I doubt it could be the cause since this page is tested with integration tests, so the tests would be failing if the display by shop group didn't work 🤔

There is currently a pending partial PR for this page https://github.com/PrestaShop/PrestaShop/pull/30781 but anyway even with the develop branch I don't have the bug, that's weird. We still have some things to finish for the page to handle multishop fully anyway. So I'll retest this bug once the page is fully finished.
