### ISSUE TITLE
Infinite load when opening autoupgrade module

### ISSUE THREAD

**Issue by soduno** [PrestaShop/PrestaShop#30913]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to load autoupgrade via Prestashop 1.7.5.2, the page just infinite loads and will not load.
I dont receive any error message, because site never gets loaded.

We are upgrading to prestashop 8.0 from 1.7.5.2 and using php version 7.3 (which is deprecated).

### Steps to reproduce

Go to modules.
Open 1 click autoupgrade
It will just load forever 

### PrestaShop version(s) where the bug happened

1.7.5.2

### PHP version(s) where the bug happened

7.3

**Comment by sallemiines** [comment]
Hello @soduno 

Thanx for reporting the issue.

Following your steps , unfortunately I didn't manage to reproduce your isssue
Could you please provide us the version of the module `click autoupgrade` ? 

Thank you !

**Comment by kpodemski** [comment]
It happens if you have a lot of files. Autoupgrade scans everything, and it slows down the module drastically.

@soduno it's not a general bug of the autoupgrade, it happens when some conditions are met. This is why your "Steps to reproduce" are not reproducible for the QA team. If you install this module on a clear 1.7.5.2 version, there's no issue.

Could you tell us more about your store? How many products do you have? How many images?

**Comment by gennaris** [comment]
I use autoupgrade a lot and this problem always happen in shops with many images, 
due to whole filesystem being scanned in configuration page as @kpodemski just said.

@soduno as a workaround, you can move the **/img/p** folder outside the document root, 
run the autoupgrade again and move it back afterwards.

**Comment by florine2623** [comment]
@soduno , let me know how your upgrade goes with @gennaris 's tips ^^

Please use PHP 7.2 as this version is compatible with PrestaShop 1.7.5.2 and PrestaShop 8.0.0.

https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/
https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

**Comment by hibatallahAouadni** [comment]
Hello @soduno 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
