### ISSUE TITLE
Translations not working anymore.

### ISSUE THREAD

**Issue by venditdevs** [PrestaShop/PrestaShop#30921]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After one of the last to updates we noticed that the translations in a (child) theme are not loading anymore in some cases. As example:

We translated "Sign up to newsletter" to "Meld je aan voor onze nieuwsbrief", but Prestashop keeps showing the English language.

![image](https://user-images.githubusercontent.com/14218917/213114535-9aa570df-82af-422a-aed8-4f2ca11eb421.png)

![image](https://user-images.githubusercontent.com/14218917/213114879-bb061ac1-296c-40bb-8921-4d5f6ab7e2c2.png)

Alle entries in the backoffice and database seems correct.

### Expected behavior

The translations should be loaded

### Steps to reproduce

Backoffice, translate the, in this case, iqitcommerce Warehouse theme. Save the changes and clear the cache. refresh the frontoffice and no translations are vissible.

### PrestaShop version(s) where the bug happened

1.7.8.7, 1.7.8.8

### PHP version(s) where the bug happened

7.3, 7.4

**Comment by florine2623** [comment]
Hello @venditdevs ,

I installed a shop in 1.7.8.7, in Dutch.
I translated the string "Ontvang ons laatste nieuws en aanbiedingen" in classic theme
<img width="814" alt="Screenshot 2023-01-18 at 10 43 35" src="https://user-images.githubusercontent.com/16019289/213137614-ea286e50-32ed-4b8d-a5d4-320a2d0e6ed4.png">

I upgraded to 1.7.8.8.
<img width="1220" alt="Screenshot 2023-01-18 at 10 54 25" src="https://user-images.githubusercontent.com/16019289/213140395-74dcd1fe-cccb-4cc2-9641-58865da8e23c.png">


The translated string is still well displayed. ✅ 

Your issue comes from your theme, please check directly with the developer of the theme.

I'll close your issue as it is not an Core issue.
Thanks!
