### ISSUE TITLE
Module does not disappear from module list after uninstalling and deleting it

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#30952]
### Describe the bug and add attachments

Discovered when working on https://github.com/PrestaShop/PrestaShop/pull/30863.

When you uninstall a module and check the "delete" checkbox in the modal, the module does not disappear from the list.

### Expected behavior

It should disappear, like in previous versions. 

➡️ Watch out for compatibility with ps_distribution api, when this module is available from a distribution module, it should not disappear from the list.

### Steps to reproduce

1. Get some develop branch ready, uninstall ps_distributionapi to be sure, clear cache.
2. Go to module manager.
3. Uninstall any module and check "delete module after uninstalling".
4. Module stays in the list.
5. (optional) Attempts to install it end up with red toast `Cannot Install module xxx. The module is invalid and cannot be loaded.` But that's normal, the module is not on the disk anymore.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Ping @atomiix

**Comment by HanaRebaiQA** [comment]
Hello @Hlavtox 

Thanks for your report.
Is it similar to this one #29712  ?

**Comment by Hlavtox** [comment]
Nope, different. The module just stays in the list, offering to install it.

![Multimédia1 (1)](https://user-images.githubusercontent.com/6097524/213482584-c5b975ce-8324-4bc5-a1bf-33bba4e7c526.gif)

**Comment by HanaRebaiQA** [comment]
Hello, 

Yes! It's the same that I have mentioned [here](https://github.com/PrestaShop/PrestaShop/issues/29712#issuecomment-1275773425) 
But, you are right in the case we check the delete option, it shouldn't be displayed anymore and the page should be refreshed again.

I have checked on **PS1788** and **PS1778**, and the behaviors are different from **develop**. Also, I could reproduce this [issue](https://github.com/PrestaShop/PrestaShop/issues/29712) on PS1788 and PS1778 when searching for the module without refreshing the page

So, Indeed it's a regression! 
I'll add this to the debug backlog so that it's fixed.

https://user-images.githubusercontent.com/92912932/213487573-cbe7427d-526c-4a20-92cd-1a2081b81585.mp4


Thank You!

**Comment by MatShir** [comment]
> ➡️ Watch out for compatibility with ps_distribution api, when this module is available from a distribution module, it should not disappear from the list.

Exactly, it's for now the expected behavior :)

**Comment by HanaRebaiQA** [comment]
Hello @MatShir 

Thanks for your feedback. So, I'll close the issue.

**Comment by MatShir** [comment]
The problem is still there, I just wanted to point out that for the native modules of api_distrib is normal as @Hlavtox explained well but not for the rest.

**Comment by RosaBenouamer** [comment]
When this issue will be corrected, we have to verify that resinstall an uninstall  natif module (from API distrib) works (no error message)

**Comment by Hlavtox** [comment]
@M0rgan01 This is fixed right? Should I close it? :-)
