### ISSUE TITLE
Favicon notification BO : the message "no new order for now" is bad displayed

### ISSUE THREAD

**Issue by Sasni** [PrestaShop/PrestaShop#31268]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Fresh install 
![image](https://user-images.githubusercontent.com/3370929/217464063-d888f5b7-eb6c-4eb4-a89b-699aca15ef00.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/3370929/217463585-43793050-3ea5-41ca-8422-4e3b53d5b278.png)

### Steps to reproduce

Fresh install. I tried adding/updating the language but it didn't change anything.

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

 7.3.33

**Comment by HanaRebaiQA** [comment]
Hello @Sasni 

Thanks for your report.
Which language did you use, is it `Czech republic` ? Did you install the shop with this language or you added after installing the shop? Could you please specify more about the steps to reproduce?

Thanks!

**Comment by Sasni** [comment]
I installed the store in Polish (language selected in the installer). Then after installation as I noticed the problem. So I tried updating the language but it didn't help.

**Comment by Sasni** [comment]
I reproduced the problem also on a local installation (Laragon)
PHP: 7.4.19
PS: 8.0.1
Polish language
![image](https://user-images.githubusercontent.com/3370929/218268557-65f1db6c-4307-46a3-bf3a-e2cbbe5e756d.png)

**Comment by hibatallahAouadni** [comment]
Hello @Sasni 

Thanks for your feedback and your patience 🙏 
I reproduce the issue with PS801, PS810 with all languages and it's a regression, see the attached screenshot below:

<img width="455" alt="Screenshot 2023-02-16 at 00 08 48" src="https://user-images.githubusercontent.com/23308427/219219846-5c5e9b90-4e10-4491-8111-1835a0ee6b1b.png">

<img width="443" alt="Screenshot 2023-02-16 at 00 44 21" src="https://user-images.githubusercontent.com/23308427/219220350-0d20d757-5f85-4471-bc7e-3c6e0ade5f4b.png">

I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Sasni** [comment]
Hello, i think this is a fix -> https://github.com/PrestaShop/PrestaShop/commit/7c9200c123185f7e17c2606fa70ad9f08af87acf
i test this and looks OK. 
I guess I don't need to add my own pull request in this situation?
![image](https://user-images.githubusercontent.com/3370929/219790939-e742f2b5-df84-4509-8712-98c25e9d7e55.png)

**Comment by MatShir** [comment]
to be reproduced with the 8.0.x branch

**Comment by hibatallahAouadni** [comment]
Hello @MatShir & @Sasni 

Unfortunately I reproduce the issue with the latest updated branch 8.0.x, see the attached screenshot below:

<img width="1186" alt="Screenshot 2023-02-21 at 07 39 57" src="https://user-images.githubusercontent.com/23308427/220267413-9a3319c2-a342-42b4-b6d6-fd286dc65fc6.png">

@Sasni are you sure that you test it with 8.0.x branch?
Please check and feedback.

Thanks!

**Comment by Sasni** [comment]
Hi @hibatallahAouadni 
This problem occurs on version 8.0.x and, as far as I can see, is supposed to be fixed in 8.**1**.x (I think that's what the link I found says) 
Manually applying the changes in version 8.0 also has a positive effect. 
Have you tried manually applying the changes I suggested? ---> https://github.com/PrestaShop/PrestaShop/commit/7c9200c123185f7e17c2606fa70ad9f08af87acf

![image](https://user-images.githubusercontent.com/3370929/220273568-98c4f75f-3fbe-49fc-82ce-3b27da4b76cf.png)

**Comment by florine2623** [comment]
This is fixed on 8`.0.x`, `8.1.x` and `develop` branches.
