### ISSUE TITLE
Error when importing Combinations of product that's linked to supplier.

### ISSUE THREAD

**Issue by Ken-vdE** [PrestaShop/PrestaShop#31314]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When importing combinations of products that are linked to supplier the 'Importing your data' popup shows "Errors occurred: Technical error: Unexpected response returned by server. Import stopped."

The underlying call to 
http://some-store.blabla/admin-dev/index.php?ajax=1&action=import&tab=AdminImport&offset=0&limit=5&token=sometoken&validateOnly=1 
shows this SQL error:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '10082-1-1' for key 'ps_product_supplier.id_product'

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/15888558/218248393-a6f759f9-f742-4a80-8d89-9896f5a5b333.png">

### Steps to reproduce

see description

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @Ken-vdE 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

It seems you're forcing the ID and importing some duplicate id, so check your file first 😉 
Otherwise, you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by Ken-vdE** [comment]
I am forcing an ID when importing products and the Combinations use that ID. When I clear the Supplier field when importing products and run the exact same file to import the Combinations, the error is gone.

'Can not reproduce' seems strange, have you actually tried?

**Comment by hibatallahAouadni** [comment]
Hello @Ken-vdE 

> 'Can not reproduce' seems strange, have you actually tried?

I didn't say that I can not reproduce 🤔 I close this issue cause you didn't respect the template, cause you didn't provide clear and concise steps to reproduce, you didn't even provide a file csv to help me reproduce the issue neither a screen record.
So you can edit your issue respecting the template and providing all infos and ping me to reopen it, or open a new one but don't forget to fill all blocs of the template 😉 

Thanks!

**Comment by ZZizy** [comment]
I am here just to comment I am experiencing the same bug. I removed the supplier and now I can import the combinations.
Prestashop 8.20
