### ISSUE TITLE
Prestashop 1.7.7.4 product page not opening 

### ISSUE THREAD

**Issue by Elviplanets** [PrestaShop/PrestaShop#31331]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/102857589/218456916-48218f36-47f8-4ced-9810-98849ec33e2e.png)

Catalog-product page not opening on Prestashop 17.7.4
Everything else works, but the products page, since a few hours ago.

### Expected behavior

Usually, all the products should appear on that page and I'll be able to modify, add or delete them.

### Steps to reproduce

1. Go to : catalogue
2. Droppdown menu: products
3. 
![image](https://user-images.githubusercontent.com/102857589/218457656-9b568852-6dcc-45db-94fd-b232dc8fa5bd.png)

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

not sure

### If your bug is related to a module, specify its name and its version

not sure

**Comment by hibatallahAouadni** [comment]
Hello @Elviplanets 

It seems your issue is not related to the Core, but to your PHP version or your server configuration.
Please check your PHP version, it should be between 7.1 and 7.3 (see our [system requirements](https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/#php-compatibility-chart)).

If you need any further help, you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by Elviplanets** [comment]
Hello Hibatallah,

thank you, will do.
