### ISSUE TITLE
Voucher amount is wrong in the cart when products have different tax amounts

### ISSUE THREAD

**Issue by dudu0911** [PrestaShop/PrestaShop#31358]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

HI

I have a problem with a voucher created with these features:

Upon reaching the 7 products in the cart, the least expensive is 100% discounted

The problem arises with products in the 4% VAT cart.

I also tried on a fresh install of PS 1.7.8.7 and the error is still there.

![Immagine 2023-02-11 012420](https://user-images.githubusercontent.com/40777107/218780880-27577398-8928-4307-ade0-60af9cf9a1b6.jpg)

### Steps to reproduce

Create three product with vat 4%,10% and 22%
Create un voucher with " 7 products in the cart, the least expensive is 100% discounted"

Voucher amount wrong on the cart

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

1.7.8.7

**Comment by hibatallahAouadni** [comment]
Hello @dudu0911 

Your issue is similar to this one #20199
Could you please check it and feedback.

Thanks!

**Comment by dudu0911** [comment]
You are very kind but unfortunately I tried version 8 but it does not solve

How can I do?

![Error1](https://user-images.githubusercontent.com/40777107/219941958-48bd6fd5-416e-4474-ae5a-4aa54ac43a0a.jpg)
![Error2](https://user-images.githubusercontent.com/40777107/219941959-350c9519-7db1-4a39-9b74-2bcbca67a322.jpg)
![Error3](https://user-images.githubusercontent.com/40777107/219941960-141ad847-b8c6-452d-bd34-b699930693c9.jpg)

**Comment by florine2623** [comment]
Hello @dudu0911 ,

I have reproduced your issue on PS 8.0.0. I'll add this to the backlog so it can be fixed.

As far as i know, it happens when there's a different tax for each product in the cart :

https://user-images.githubusercontent.com/16019289/220414587-5204514e-d557-4e9a-a97a-860e0ef95f4a.mov

When all the products have the same tax, there's no issue.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by dudu0911** [comment]
Hi
RESOLVE HERE: 
https://github.com/PrestaShop/PrestaShop/pull/31487/files

works! thank you so much

**Comment by hibatallahAouadni** [comment]
@dudu0911 You shouldn't close the issue as the PR hasn't been merged :wink:

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback @dudu0911 :pray:

**Comment by hibatallahAouadni** [comment]
Duplicate of #31486
