### ISSUE TITLE
BO - Translations - 2 Exceptions displayed when trying to add/update language Breton

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31384]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

2 Exceptions are displayed when I add/update the language Breton.

**Add/update language Breton:**
`Invalid or uninitialized Zip object`
<img width="1102" alt="Screenshot 2023-02-15 at 15 04 49" src="https://user-images.githubusercontent.com/16019289/219049077-7d1733cc-173b-43d1-81de-2aca26c0f5de.png">

**Refresh your URL:**
`An exception has been thrown during the rendering of a template ("Parameter "type" for route "api_translation_domains_tree" must match "[^/]++" ("" given) to generate a corresponding URL.").`
<img width="1058" alt="Screenshot 2023-02-15 at 11 30 51" src="https://user-images.githubusercontent.com/16019289/219048836-ae2cc5da-795a-4085-a773-a31e07e75bf6.png">

https://user-images.githubusercontent.com/16019289/219048868-d764da40-3d03-42ef-b2be-734509b907eb.mov

It's a regression. In 1.7.8.8, we could add/update Breton language without error.

### Expected behavior

Display an error message when the language translation is not available

### Steps to reproduce

1. Go to BO > International > Translations
2. Add language Breton
3. See error :x: `Invalid or uninitialized Zip object`
4. Update your URL
5. See Error :x: `An exception has been thrown during the rendering of a template ("Parameter "type" for route "api_translation_domains_tree" must match "[^/]++" ("" given) to generate a corresponding URL.").`
6. Refresh and do that multiple times
7. Internal Server Error :x:

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by HanaRebaiQA** [comment]
Hello @florine2623 

I was able to reproduce your issue on PS8.1.0_beta and PS8.0.1.

**PS8.1.0_beta : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219419805-52b026dd-84a2-46dd-8de2-14f0c2212f97.png)


![image](https://user-images.githubusercontent.com/92912932/219419910-506c8710-ef25-48b7-8d46-304e50d2f7bf.png)

**PS8.0.1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219420149-a0abe95b-9219-4e48-a46c-963a09c20b0d.png)

**PS1.7.8.8 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/219421773-a0b8d6a2-1104-4afe-9d22-bc0aa6823f74.png)

Indeed, it's a regression on PS8.0.1!

I'll add this to the debug backlog so that it's fixed.

Thank You!
