### ISSUE TITLE
The term "upgrade" is being used incorrectly and interchangeably with "update"

### ISSUE THREAD

**Issue by alohapili** [PrestaShop/PrestaShop#31397]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When viewing the update all page, some buttons reference update while others incorrectly reference upgrade. Normally, upgrade involves a transaction, or a higher tier (normally paid) of a certain product. Update means the version has been improved and an update needs applied to the base product. I noticed this when I went to the Update All page, and then hesitated when I saw the "Upgrade All" button, thinking, it can't be possible for me to upgrade all these modules to a higher (often paid) tier service, the person must have meant Update All. When I clicked the Upgrade All button, it did indeed "Update" all the modules.

![Screenshot 2023-02-16 045320](https://user-images.githubusercontent.com/4334363/219370572-41b23969-4459-474d-b8ce-9d883fc25ae0.png)

I thought at first that this was a typo in the button itself, so I went exploring the code documentation and discovered that Upgrade is used incorrectly in multiple other locations, including the containing folder for the code itself! This is far more than a typo, so I'm here writing a bug instead.

![image](https://user-images.githubusercontent.com/4334363/219370918-eb717c61-112d-4b49-98fa-eb9130ee2d86.png)
![image](https://user-images.githubusercontent.com/4334363/219371236-be61d0b8-c1f3-4fef-af3d-5aadd4487809.png)

This is a larger refactoring project that I'm not skilled enough to undertake.

### Expected behavior

Update means updating the base version.
Upgrade means applying something more than the "base" version provides (often paid).

### Steps to reproduce

1. Module Manager
2. Updates
3. Look for "Update All"
4. Look for documentation on how to Update
5. Find interchanging references to Update and Upgrade
6. End up trying the button Upgrade All
7. The Upgrade All prompts notifications that the modules have been _Updated_

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Module Manager

**Comment by florine2623** [comment]
Ping @l-delin ,

What do you think about that ? :)

Thanks!

**Comment by alohapili** [comment]
I'd be happy to help!

**Comment by eternoendless** [comment]
I don't know the original reasoning behind choosing "upgrade" instead of "update", but the way I see it it isn't necessarily wrong as per the dictionary's definition of _upgrade_:

<img width="572" alt="Screenshot 2023-02-17 at 10 39 24" src="https://user-images.githubusercontent.com/1009343/219608770-1af638d4-1704-4bc0-984c-b2b84cbc0726.png">

According to that definition, _upgrade_ may be understood as just "getting a **better**, more modern version", instead of just "getting a more recent version". Both are fine from my point of view.

**Comment by l-delin** [comment]
Hello @alohapili 

First of all, thank you for your feedback! :-) 
I completely agree with you on the use of `upgrade` and `update`. The proper wording is **"to update a module"**. There is a difference between the two terms that we've clarified in the Content Style Guide, which will soon be available to the community. See: 

<img width="629" alt="image" src="https://user-images.githubusercontent.com/113511191/219674045-1f408af4-be2f-4591-ab73-c6b3a3c5118d.png">

While update and upgrade roughly mean the same thing, they're **not** synonyms in this context. So, the string needs to be changed to unify the module page as well as the dev/user doc. Think of the '1-Click upgrade' module which requires you to **update** your module in order to **upgrade** your store. This difference in wording helps us differentiate the two verbs :-)

![image](https://user-images.githubusercontent.com/113511191/219690333-1345882c-ab57-4f84-8377-3f8ac56b7635.png)


I can edit the docs **but regarding the software strings, a PR needs to be open to change the following strings:**

- `'Upgrade All'` to `'Update all'` in`'Admin.Modules.Feature'`
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/113511191/219680270-f4b1739e-7a7f-403e-9161-184c935ce061.png">

- `'Upgrade anyway'` to `'Update anyway'` in `'Admin.Actions'`
![image](https://user-images.githubusercontent.com/113511191/219686124-5f018eb1-dcfa-4775-9e2a-4a7f98686734.png)

- `'You are not allowed to upgrade this module.'` to`'You are not allowed to update this module.'`  in '`Admin.Modules.Notification'`

- `'%d file upgrade applied' `to `'%d file update applied'` in '`Admin.Modules.Notification'`

- `'No upgrade has been applied'`to `'No update has been applied'` in `'Admin.Modules.Notification'`

- `'%d upgrade left'` to `'%d update left'` in `'Admin.Modules.Notification'`

- `'Module %s cannot be upgraded this time: please refresh this page to update it.'` to `'Module %s cannot be updated this time: please refresh this page to update it.'` in `'Admin.Modules.Notification'`

- `'You are not allowed to upgrade the module %module%.'` to `'You are not allowed to update the module %module%.'` in `'Admin.Modules.Notification'`

- `'Are you sure you want to upgrade this module?'` to `'Are you sure you want to update this module?'` in `'Admin.Modules.Notification'`

- `'Are you sure you want to upgrade these modules?'` to`'Are you sure you want to update these modules?'` in `'Admin.Modules.Notification'`

- `'We strongly advise you to upgrade the modules on maintenance mode to avoid any cache issues.'` to `'We strongly advise you to update the modules on maintenance mode to avoid any cache issues."` in `'Admin.Modules.Notification'`

I noticed these strings are not available for translation and therefore cannot be edited or translated:
-`'Upgrade action on module %ds succeeded.'`
-`'Could not perform action upgrade for module undefined'` 

![image](https://user-images.githubusercontent.com/113511191/219689821-0077f73d-d6f6-468b-ace1-b0607659595e.png)

So, they need to be changed into translation strings and edited:
- From `'Upgrade action on module %ds succeeded.'` to `'Update action on module %ds succeeded.'`
- From `'Could not perform action upgrade for module undefined'` to `'Could not perform action update for module undefined'`

Thanks! :-)

**Comment by eternoendless** [comment]
> I noticed these strings are not available for translation and therefore cannot be edited or translated:
> -`'Upgrade action on module %ds succeeded.'`
> -`'Could not perform action upgrade for module undefined'`

@l-delin these are actually a composition of `%action% action on module %module% succeeded.` from `Admin.Modules.Notification` and a collection of independent action wordings (see https://github.com/PrestaShop/PrestaShop/blob/8.0.0/src/Adapter/Module/AdminModuleDataProvider.php#L51-L76)
