### ISSUE TITLE
Epoch doesn't fit in a PHP integer In php 32 bits

### ISSUE THREAD

**Issue by pelechano** [PrestaShop/PrestaShop#31436]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In my local installation with WAMP 32 bits (php 32 bits ) there's a critical bug 

I installed in php 7.4 the prestashop 8.1.0 beta version, without problems. Afterwards I changed to php 8.1, once cleared the cache there's a Fatal error: 

Uncaught ValueError: Epoch doesn't fit in a PHP integer

 PHP Fatal error:  Uncaught ValueError: Epoch doesn't fit in a PHP integer in C:\Repositorio1\prestashop810\src\Core\Localization\CLDR\Reader.php:640
Stack trace:
#0 C:\Repositorio1\prestashop810\src\Core\Localization\CLDR\Reader.php(640): DateTime->getTimestamp()

When processing "old dates" like 1898-12-10 presents in the supplementalData.xml file. If the localization is cached no problem.

In my test installation (Linux 64 bits) no problem.

Now testing the installation in 32 bits and it's not possible to begin the create tables step:
PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in C:\Repositorio1\prestashop810\src\PrestaShopBundle\Install\Install.php:198
Stack trace:
#0 C:\Repositorio1\prestashop810\src\PrestaShopBundle\Install\Install.php(198): openssl_pkey_get_details(false)

### Expected behavior

Run prestashop in a php 32 bits version 

### Steps to reproduce

1 In a php 7.2-7.4 32 bit environment you can install without problems. 
2 Afterwards change to php 8.0-8.1
3 Clear cache

The installation with php 8.0-8.1 in a php 32 bits in the last step it crashes

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.0, 8.1

**Comment by hibatallahAouadni** [comment]
Hello @pelechano 

Thanks for reporting the issue!
Ping @PrestaShop/prestashop-core-developers someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by matks** [comment]
Hello,

> In my local installation with WAMP 32 bits (php 32 bits ) there's a critical bug

Actually I am not sure at all PrestaShop can work in a 32 bits environment 😅 

@pelechano you might be the first person I meet that tried to run PrestaShop in a 32 bits environment 😄

**Comment by pelechano** [comment]
@matks 
Is strange..  in the previous versions (1.7.X and 1.6.X) no problem.. I usually use wamp64 but for accident I downloaded the 32 bits version  when I changed my Computer (my OS is 64 bits obviously, but many software is 32 bits) so I didn't give it any importance. 

Anyway I suppose this "problem" might not be of any "real" impact since all the production servers should run with php 64 bits, but I really don't know if it's true (that's why I created the issue) and I also didn't see this requirement in the system requirements doc page.

**Comment by matks** [comment]
So, to be transparent, I've been working on PrestaShop for 5 years now and as far as I know, nobody tried
- to run PrestaShop extensively with Wamp
- to run PrestaShop extensively on a 32bits system

Some people might have done it here and there, however I don't think they tried to do it to map the software and make sure it works as expected.

>  I also didn't see this requirement in the system requirements doc page.

You're right, I think we simply did not thought it had to be written, but here you are so I guess we were wrong.

As I mentioned

> So, to be transparent, I've been working on PrestaShop for 5 years now and as far as I know, nobody tried
> - to run PrestaShop extensively with Wamp
> - to run PrestaShop extensively on a 32bits system

So you could say that PrestaShop does not support officially Wamp neither 32bits systems. Luckily to you, PS 1.6 and 1.7 seem to have been compatible by chance but this was not done on purpose (at least on 1.7) :/ .

I'm sorry but I don't think we should support officially Wamp neither 32bits systems because, as you say, "all the production servers should run with php 64 bits".

If we wanted to support this environment, and do it seriously, it would mean
- make sure the CI runs on this env too, both for the GitHub-based CI and [nightly tests](https://nightly.prestashop.com/)
- make sure every release testing campaign (like [the one for 8.1.0](https://build.prestashop-project.org/news/2023/prestashop-8-1-beta-release/) happening right now) includes testing on this environment

Only then could we really write "We do support env {...}": after spending the energy and time on making sure this is true.

**Comment by pelechano** [comment]
Ok, I was worried about the 32 bits issue, obviously my open issue is for that. I really don't know if it's normal a 32 bit production php server. Sincerely I've never thought about that until this issue.. probably it's used somewhere because there's the option to download/install from php for windows servers.


Wamp is only a test development server, is not the problem, it's also in the documentation https://devdocs.prestashop-project.org/8/basics/installation/localhost/ among other AMP installers.

I'm glad to see that is not a problem!
Great work with this Prestashop 8.1 Version!
