### ISSUE TITLE
displayAdminProductsSeoStepBottom hook is not launched in 8.1

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#31534]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

displayAdminProductsSeoStepBottom hook is not launched in 8.1 beta1 bo product page

### Expected behavior

Hook launched

### Steps to reproduce

1. Install a module hooked on displayAdminProductsSeoStepBottom
1. Nothing displayed in bo product page

### PrestaShop version(s) where the bug happened

8.1 beta 1

### PHP version(s) where the bug happened

all

**Comment by jf-viguier** [comment]
If it's a BC break, it should be documented and deprecated in 8.1, removed in 9.0 ?

**Comment by jolelievre** [comment]
Hi @jf-viguier 

Indeed this hook is no longer present in product page v2, it was already not present in the 8.0 actually.

Most of the display hooks have been removed from the new product page because they are not needed anymore, instead you should rely on `actionProductFormBuilderModifier` to get the symfony form and add you own form inputs

It actually offers much more customization as you can add anything anywhere in the form in a generic way instead of a fe hooks here and there that only handled specific and limited use cases The only hook that was kept compared to V1 was `displayAdminProductsExtra` for modules that added extra content in the `Modules` tab Although I wouldn't recommend using it now since the form customization offers much better UI possibilities

It is indeed a breaking change, I plan on writing a documentation similar to what was done [for the Order page](https://devdocs.prestashop-project.org/1.7/modules/core-updates/1.7.7/#modified-hooks) explaining the removed hooks and the alternatives

In the meantime you can also have a look at our example module to see how you can integrate modules in the new product page:
https://github.com/PrestaShop/example-modules/tree/master/demoproductform

There's a pending PR for this example module for combination form as well:
https://github.com/PrestaShop/example-modules/pull/138

However, you're also right that we need to document and identify these hooks as deprecated in 8.1, since the V1 will be removed in 9.0 and only the v2 will remain

**Comment by jf-viguier** [comment]
Thanks for your clear explanation.

**Comment by hibatallahAouadni** [comment]
https://github.com/PrestaShop/PrestaShop/issues/24249#issuecomment-828532689

**Comment by jonasburneika** [comment]
Thank you @jolelievre for your reply. I searched for what was wrong with my stage for at least three hours. Is there any way to update the documentation? it is misleading A LOT!!! 

https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/
