### ISSUE TITLE
smarty js=1 modifier don't escape string anymore in smarty backoffice tpl in PrestaShop 8

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#31593]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In prestashop 8.1 beta 1, the js=1 flag in smarty translation doesn't escace the string.
This could cause a lots's of XSS security issues.

It's a regression from PrestaShop 8.0

### Expected behavior

escape the string

### Steps to reproduce

1. Install Prestashop 8.1 beta in french
2. Try to add a new carrier : the page is broken du to an non escaped js string.

![image](https://user-images.githubusercontent.com/16720275/222217070-12ebde42-d45d-4170-89cd-a99ec09900bc.png)

Javascript error occurs in nearly every bo page, in information page, module page.

the smarty code is correct here :
`var need_to_validate = '{l s='Please validate the last range before creating a new one.' js=1 d='Admin.Shipping.Notification'}';`

The js=1 parameter doesn't do his job.

### PrestaShop version(s) where the bug happened

8.1 beta 1

### PHP version(s) where the bug happened

all

**Comment by jf-viguier** [comment]
Certainly cause by this PR https://github.com/PrestaShop/PrestaShop/pull/30415

**Comment by jf-viguier** [comment]
Same behavious with slashes=1

**Comment by HanaRebaiQA** [comment]
Hello @jf-viguier 

Thanks for your report.
I was able to reproduce your issue on ***PS8.1.0_beta only with French** language.

**PS8.1.0_beta : FR : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/222449744-e14f2ef0-e39b-451a-8958-7229de7b7496.png)

**PS8.1.0_beta : ENG : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/222449775-36160be5-7e03-4cee-ba3d-19d8b11c9156.png)

**PS8.1.0_beta : AR : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/222449860-df2f572d-d83c-409a-a575-ee81cb4dd1b2.png)

**Develop : FR : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/222462241-a5e680cc-a39a-4aef-84db-ebdba440f695.png)

**Develop : ENG : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/222462317-8970c350-0572-43a5-9ee8-58bf2a113191.png)


**PS8.0.1 : FR : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/222449820-9a87ca10-3c06-4d58-ba73-f9f74c6ee56e.png)

Indeed, it's a regression on PS8.1.0_beta!

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank You!

**Comment by jf-viguier** [comment]
I don't understand why you've changed the issue "smarty js=1 modifier don't escape string anymore in smarty backoffice tpl"
To "Carriers page is broken only with french language"
The bug occurs in many languages, and in many backoffice pages.

**Comment by jf-viguier** [comment]
Sorry, you minimize the issue, I can't accept it, i go back to the old name

**Comment by jf-viguier** [comment]
Javascript error occurs in nearly every bo page, here in information page
![image](https://user-images.githubusercontent.com/16720275/222462504-47c0a3da-eb65-491b-b871-72487d38d41e.png)

**Comment by HanaRebaiQA** [comment]
Hello @jf-viguier 

I've changed the title to be more clear.
I was able to reproduce the issue only with the French language as I've mentioned here in my [comment](https://github.com/PrestaShop/PrestaShop/issues/31593#issuecomment-1451913062).
I already checked the issue on develop. The issue occurs only with the French language also. I'll add this to my comment

Could you please send us the other languages/pages where the bug occurs to can change the title if needed?

Thank You!

**Comment by jf-viguier** [comment]
here in module page
![image](https://user-images.githubusercontent.com/16720275/222463159-f507ec3e-8557-4187-91ea-aa7a7a5ccc9e.png)

**Comment by micka-fdz** [comment]
Hi @HanaRebaiQA

I think you don't have issue with EN and AR languages because there are no (or very few) « ' » (apostrophe) characters in these languages.

**Comment by jf-viguier** [comment]
For other languages, you have to choose language with a lot's of ' in javascript translations.

**Comment by jf-viguier** [comment]
This is the way to XSS vulnerabilities https://cwe.mitre.org/data/definitions/79.html

**Comment by HanaRebaiQA** [comment]
Hello again, 

I think there are two issues in this case if I'm not wrong.

- The first issue of the carrier page which is broken with the French language as I communicated above.
- The second of javascript error on every BO page also only with the French language.

**FR : NOK**
![image](https://user-images.githubusercontent.com/92912932/222465891-5e9825a5-647a-4864-9d03-20dc7d8747be.png)

![image](https://user-images.githubusercontent.com/92912932/222465863-e25964fd-59ec-4a4e-ba27-21821d7e7d62.png)

**ENG : OK**
![image](https://user-images.githubusercontent.com/92912932/222466188-f734bebf-e814-48be-80ec-21544f905c9e.png)

![image](https://user-images.githubusercontent.com/92912932/222466282-400a1085-9993-474a-aec4-052184cca560.png)

What do you think ?

**Comment by BarbUk** [comment]
> * The second of javascript error on every BO page also only with the French language.

This is an escape issue, all language are impacted.
cf: https://github.com/PrestaShop/PrestaShop/issues/31593#issuecomment-1452000049

**Comment by jf-viguier** [comment]
japanese & breton uses a lot's of ' 
https://fr.wikipedia.org/wiki/Apostrophe_(typographie)

**Comment by micka-fdz** [comment]
@HanaRebaiQA try with italian:
- English trans: "Order number:"
- Italian trans: "Numero dell'ordine:"

This JS translation is used in every legacy BO pages.

**Comment by HanaRebaiQA** [comment]
Hello, 

In my opinion, there are two issues then as I've mentioned here in my [comment](https://github.com/PrestaShop/PrestaShop/issues/31593#issuecomment-1452021219).

And, this current issue is about the error of js in every BO page with languages that contain `' '`

ping @MatShir What do you think ?

**Comment by jf-viguier** [comment]
no, the issue is that  js=1 modifier don't escape string anymore: what do you talk is about consequences of this issue.

**Comment by micka-fdz** [comment]
I think this issue is also in v8.0.2 because of this PR: https://github.com/PrestaShop/PrestaShop/pull/30415

**Comment by Hlavtox** [comment]
Critical issue:
Difficulty accessing the front office or back office (significant slowdown, error during installation or update, fatal error)
Difficulty to globally manage categories, products or customers
Difficulty to globally place and manage orders

Page javascript completely broken definitely fits the criteria.

**Comment by MatShir** [comment]
Thanks for the issue ! We will try to solve it for the next patch !

**Comment by AureRita** [comment]
Hello, 

as @micka-fdz said, Indeed this issue is also on 8.0.2 as we can see here : 

[Untitled_ Mar 6, 2023 10_47 AM.webm](https://user-images.githubusercontent.com/100699445/223076352-86777344-0105-4a1d-a4ab-9b3e63d28751.webm)

**Comment by HanaRebaiQA** [comment]
Hello everybody,

I found also that the Discounts page is broken (with Carriers) following my tests on PS8.0.2 !

![image](https://user-images.githubusercontent.com/92912932/223169617-c947cbae-89ed-4c09-a7c6-4d53c2ca8d7f.png)

Thank You!
