### ISSUE TITLE
BO - International - Translations - Add or update languages shows a warning

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#31636]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Bo > International when we try to add or update a langauage a warning appears 

### Expected behavior

The translations should  been successfully added.

### Steps to reproduce

1. Go to Bo > International > Translation
2. Select on Add a language : Brezhoneg (Breton) 
3. Click on the button  Add or update languages
4. A warning appears 

https://user-images.githubusercontent.com/31663369/222732417-f5d42237-aa4b-4b17-9e53-39758425d783.mp4

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @sallemiines ,

Your issue is similar to : https://github.com/PrestaShop/PrestaShop/issues/31384

I think we can keep this one open, as it is reported for PS 8.0.2.
In my case, I can only reproduce the issue with PHP 8, with PHP 7 it is OK.

@PrestaShop/product-team , wdty should we merge the 2 issues together ?
Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #31384

**Comment by ingridusta** [comment]
This issue is reproduced with PrestaShop 8.2.0 and PHP 8.1.13.
