### ISSUE TITLE
Problem with ps_imageslider module

### ISSUE THREAD

**Issue by Majk3l01** [PrestaShop/PrestaShop#31633]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

My problem with ps_imageslider module is that it is over 100% of the width and my carousell arrow buttons are not changing the slides - also - the timer which is set to 5000ms is also not changing the slides, could you help me ?

### Expected behavior

I expect it to be max width 100% and my arrow buttons and timer to work

### Steps to reproduce

1. Go to website https://woodandhome.pl/
2. There will be the homepage slider - this is the slider i'm talking about

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

Dont know how to check it

### If your bug is related to a module, specify its name and its version

ps_imageslider v3.1.0

**Comment by florine2623** [comment]
Hello @Majk3l01 ,

Your issue seems to be a theme related problem. You can contact the develop of your theme directly.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
