### ISSUE TITLE
ps_emailsubscription and ps_dataprivacy show HTML in frontend<br><em>

### ISSUE THREAD

**Issue by ArteInfoRM** [PrestaShop/PrestaShop#31794]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments
![no-rendering-html](https://user-images.githubusercontent.com/41371761/225307713-afd6c216-a76c-4372-a713-139c71d8b542.jpg)

The modules mentioned in PS 8.0.1 do not redering HTML showing it in font-end, example:
"Sign up for our newsletter &lt;br&gt; &lt;em&gt; You may unsubscribe at any moment. For that purpose, please find our contact info in the legal [notice. &lt;/em&gt;

ps_emailsubscription v2.7.1 
ps_dataprivacy v2.1.1

### Steps to reproduce

1 Go to Create an account or Proceed to Checkout in front-end

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_emailsubscription v2.7.1

**Comment by djoelleuch** [comment]
Hello @ArteInfoRM ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #29940 .
The issue has been fixed on develop , these are the PR [ #91 ](https://github.com/PrestaShop/ps_emailsubscription/pull/91) , [#40](https://github.com/PrestaShop/ps_dataprivacy/pull/40) .
You can check it if you want .

Closing the issue.

Thank you .
