### ISSUE TITLE
500 error after updating 8.0.2 to 8.0.3

### ISSUE THREAD

**Issue by milor-nl** [PrestaShop/PrestaShop#32030]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

After updating with the current 1-click update( v4.15.0  ) I have an 500 error.
My knowledge is about zero so I hope you can help me.

Fatale fout: Uncaught --> Smarty: Kan sjabloon 'file:.' niet laden. /_partials/.tpl' in 'file:_partials/desktop-header.tpl' <-- thrown in /home/pellets/domains/houtpellets.shop/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195

I have replaced 8.0.3 with an backup back to 8.0.2 now 

### Steps to reproduce

1- click update v4.15.0 
after updating  ctrl-F5 - empty cache etc.
result:  500 error    FATAL FAULT: Uncaught --> Smarty: Kan sjabloon 'file:.' niet laden. /_partials/.tpl' in 'file:_partials/desktop-header.tpl' <-- thrown in /home/pellets/domains/houtpellets.shop/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195

### PrestaShop version(s) where the bug happened

after update from 8.0.2 to 8.0.3

### PHP version(s) where the bug happened

PHP 7.4.33

### Your company or customer's name goes here (if applicable).

De Houtpellet Shop

**Comment by florine2623** [comment]
Hello @milor-nl ,

I can't reproduce your issue. I'm upgrading from 8.0.2 to 8.0.3 :
<img width="1440" alt="Screenshot 2023-04-05 at 12 02 12" src="https://user-images.githubusercontent.com/16019289/230049219-16c0f986-7c6a-4467-88ea-ba76414e2573.png">

The upgrade is successful :
<img width="1423" alt="Screenshot 2023-04-05 at 12 06 16" src="https://user-images.githubusercontent.com/16019289/230049962-1fe53645-e3b3-49de-99b7-cc6577cea9f9.png">


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by amazingballzs** [comment]
Hello

I tried to upgrade from prestashop 8.0.2 to 8.0.3, toward the end of the process when the database had to be upgraded I got this error:

CRITICAL [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "There is no active transaction" ["exception" => PDOException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => "There is no active transaction"]
In Connection.php line 1854:
There is no active transaction
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] 

Error during database upgrade. You may need to restore your database.
Error upgrading Doctrine schema

Expected behavior

A succesful upgrade, I got the error posted above instead

Steps to reproduce

Just use 1- click update v4.15.0

PrestaShop version(s) where the bug happened
during automatic process to upgrade form PS V 8.0.2 to V 8.0.3

PHP version(s) where the bug happened

PHP 8.1
If your bug is related to a module, specify its name and its version

not module related

============

Post update
I rolled back to a backup I did before updating the "Official GDPR compliance" module.
I launched again the upgrade from PS8.0.2 to 8.0.3, this time worked.

However checking the modules I saw that with the upgrade also the gdpr module ws update to version 2, this caused the database table myprefix_ps_gdpr_log to be renamed into ps_ps_gdpr_log, all works fine apparently, but I suspect that this table's prefix being renamed to ps_ will maybe cause other problems in future when upgrading PS.

============

Further Post update

After the upgrade from 8.0.2 to 8.0.3 regenerating the miniatures caused the theme to fall off with an amount of errors of this kind:

Warning: Trying to access array offset on value of type null in /home/youruser/public_html/var/cache/dev/smarty/compile/transformerlayouts_layout_full_width_tpl/ab/54/14/ab5414f0e8dc1eaecab89319433546d630a49f30_2.file.layout-both-columns.tpl.php on line 51 desktop_device

I can't guess a way to fix this

Also I noticed that after  the upgrade from 8.0.2 to 8.0.3 and the automatic update to version 2 of the module "Official GDPR compliance" in the database there are both the tables myprefix_ps_gdpr_log and ps_ps_gdpr_log now, of which the latter is empty, so previous records are on the old log table and I guess new records will go on the new one,,,,,,, I have no idea of what happens with the keys between tables in this situation....., however it is a mess.....

**Comment by milor-nl** [comment]
I will follow, perhaps my problems are related.

**Comment by matks** [comment]
Found another bug report "There is no active transaction" https://github.com/PrestaShop/PrestaShop/issues/32350#issuecomment-1530998189

This will maybe help you https://github.com/PrestaShop/PrestaShop/discussions/32348#discussioncomment-5782671
