### ISSUE TITLE
Backoffice loop and ERR_TOO_MANY_REDIRECTS in the frontend

### ISSUE THREAD

**Issue by danyeah** [PrestaShop/PrestaShop#32045]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello guys

I downloaded version 1.7.8.8, install went file and db is created correctly.
But when i go to login in the backoffice, it reloads the same page
Frontend returns an error page: ERR_TOO_MANY_REDIRECTS
I have tried different browsers (Brave & Chrome version 111, Safari 16, Firefox 111) all lead to same behaviour, always deleting /var/cache to be sure to start from fresh cache(also browser cache has been deleted in all tests)

I have googled long and far to try to find a solutions and tried all the suggestions found but still can't make it work.

I am running apache with MAMP and i've tried it with different php version
7.4.21
7.3.29
7.2.34

Since i dont have SSL locally i disabled it in PS_CONFIGURATION table
PS_SSL_ENABLED : 0
PS_SSL_ENABLED_EVERYWHERE : 0

I have also changed the url from 127.0.0.1 to localhost via the PS_SHOP_URL table

Enabled _PS_MODE_DEV in defines.inc.php but its not showing any errors anywhere.

/var/logs/dev.log is showing
`[2023-04-04 18:22:55] php.INFO: User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {"exception":"[object] (ErrorException(code: 0): User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 at /Users/daniel/ps2/src/Adapter/Configuration.php:418)"} []
`
Happy to provide more info, i have no idea how to solve.

### Steps to reproduce

1. Install v 1.7.8.8

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.1

**Comment by florine2623** [comment]
Hello @danyeah ,

If you want to change your URL in localhost, I suggest changing it in your hostname directly in MAMAP and not in your database.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Comment by danyeah** [comment]
Hello @florine2623  
How can you tell it is a server configuration issue? I've tried so many different configurations.
localhost or not problem is still there, in fact the issue is not "how do i change website to localhost"

Can't install a fresh installation, I've been using MAMP pro for years for all kinds of php/cms development.
I've seen issues with the same problem but none of them is resolved.

**Comment by sudo-do** [comment]
@florine2623 I can validate this is valid on PHP 7.1 too many modules raise 500 error. Upgrading to 7.3 fixes but in readme it says 7.1+

**Comment by sudo-do** [comment]
My environment is open until 9/04

Php info: http://ps1788.dev.crossduck.gq/PHP%20info.php
FO: http://ps1788.dev.crossduck.gq/
BO: http://ps1788.dev.crossduck.gq/C/

**Comment by danyeah** [comment]
yeah prestashop community is dead @sudo-do, don't even bother.
