### ISSUE TITLE
International -> Localization Pack -> specs to cleanup CLDR xml files

### ISSUE THREAD

**Issue by dominiqueblanc** [PrestaShop/PrestaShop#32076]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,

I'm aware this subject is an old one.
Thanks to @eternoendless for the details exposed https://github.com/PrestaShop/PrestaShop/issues/16029#issuecomment-551079194.

Before suggesting anything, eventually useful, I feel the need to understand how all this works.

I know now that the LocalizationPacks are using the ISO-639-1 code as an ID to the main language (e.g . en, fr, de, es), then the IETF to split it in regions (en-US, en-GB, fr-BE, fr-CH, fr-FR, de-AT, de-DE...).

CLDR are more than 700 xml files, such a huge work to update them.
However it seems necessary.

For example we have fr-CH xml...

https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/fr_CH.xml

```
<ldml>
	<identity>
		<version number="$Revision$"/>
		<language type="fr"/>
		<territory type="CH"/>
	</identity>
	<localeDisplayNames>
		<languages>
			<language type="gu" draft="contributed">goudjrati</language>
			<language type="pdc" draft="contributed">allemand de Pennsylvanie</language>
			<language type="sdh" draft="contributed">kurde méridional</language>
		</languages>
```

```
<numbers>
		<symbols numberSystem="latn">
			<currencyDecimal>.</currencyDecimal>
		</symbols>
		<percentFormats numberSystem="latn">
			<percentFormatLength>
				<percentFormat>
					<pattern draft="contributed">#,##0%</pattern>
				</percentFormat>
			</percentFormatLength>
		</percentFormats>
	</numbers>
</ldml>
```

Questions : 
1. What is the expected role of the `languages `tags ? (is it 1) all languages in the world or 2) the languages used in the country) ?
In both cases, there is a mistake on this file : if it's 1) many languages are missing, if it's 2) these 3 are not the official languages in this territory.

Correct languages would be,  code-iso : "fr, de, it" and language type : "fr_CH, de_CH, it_CH"
In that case do we have to include as `languages ` iso-code (fr, de, it) AND `language type` (fr-CH, de_CH, it_CH) to make the LocalizazionPack works correctly ?

2. In the `numbers` we have a `currencyDecimal` but not the `group`, nor the `pattern`.

In the main language file, reffering to ISO-639-1, "fr"
https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/fr.xml

		<symbols numberSystem="latn">
			<decimal>,</decimal>
			<group> </group>
			<list>;</list>
			<percentSign>%</percentSign>
			<plusSign draft="contributed">+</plusSign>
			<minusSign draft="contributed">-</minusSign>
			<approximatelySign>≃</approximatelySign>
			<exponential>E</exponential>
			<superscriptingExponent>×</superscriptingExponent>
			<perMille>‰</perMille>
			<infinity>∞</infinity>
			<nan>NaN</nan>
			<timeSeparator draft="contributed">:</timeSeparator>
		</symbols>

The decimal separator is called `decimal` and not `currencyDecimal`, and the thousands separator is called `group`.
A change on these on the main language file, help to change the pricing display FO (while nothing occured when changed on the regional language file). 

Importing the Pack for the country Switzerland, leads me to load fr-fr, de-de and it-it, which means wrong formats numbers and dates.

However, I can't solve this by modifying it manually, because having both language "French FR" and "French CH" make it confuse in FO where 2 lines "French" will stand.

But to satisfy both customers french and swiss, each deserve to get their specific country formats.

![image](https://user-images.githubusercontent.com/129511652/230401765-a4494c01-417c-4107-b1a7-c343c14161f0.png)

Thank you in advance to help me to understand how the regional languages (IETF) are related to the main languages files (ISO-639-1)

### Expected behavior

When uploading the Switzerland Pack of languages, I expected to get the specific languages and formats.

### Steps to reproduce

1. Goto : BO -> International -> Localization -> Localization sheet -> Localization pack you want to import : Switzerland
2. Goto : BO -> International -> Localization -> Languages sheet  = (as described on the print screen)

### PrestaShop version(s) where the bug happened

8.0.2, 8.0.3

### PHP version(s) where the bug happened

8.0

**Comment by dominiqueblanc** [comment]
Sorry, it has been sent but I wasn't finished... On 8.0.3, the problem occured too and I'm on 8.0 PHP.

Thank you in advance for your replies and help.
Best regards

**Comment by florine2623** [comment]
Hello @DomShop ,

@PrestaShop/committers might have the answer to your question. I'll let them answer ^^

**Comment by eternoendless** [comment]
Hi @DomShop 

The CLDR files are direct copies of the original CLDR from Unicode (see [details](https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/readme.md)). If you have questions regarding the specifics of these files, have a look at the documentation [here](https://cldr.unicode.org/). Note that these files contain more data than what we actually use at the moment, we only use them to format prices and currencies.

PrestaShop currently includes CLDR v36 whereas the current stable version is v42. Maybe it would be a good idea to update it sometime soon, to benefit from any currencies added since 2019. Updating them should be a simple matter of copy-paste (consider making a PR for that!).

Now, regarding the specific problem you describe, I think at the root is basically the same problem as the one you linked at the beginning of your message: the historical choice of using 2-letter country codes for languages doesn't play well with language varieties. You have already figured out that in order to use the swiss number format you need to change the language code to "fr-ch", but in order to get FR-FR and FR-CH working at the same time, you will have to "invent" a new ISO code for the Swiss French, (like was done with "QC" for Canadian French, or "AG" for Argentinian Spanish). However doing that will probably expose you to other issues, like missing TinyMCE translations for example.

**Comment by dominiqueblanc** [comment]
Hi @florine2623 and @eternoendless,

Thank you so much for your quick replies and explanations.

It seems that we have an issue here with the source. I checked the CLDR v42 and the files are not ok (I'm not criticizing, just saying that it's obvious that files had to be cleaned up).
So an update from v36 to v42 won't be enough I think.

To give the CLDR a hand, if each of us, living in our specific countries, opens a ticket to add/update these files, it won't take long to improve it.

But first of all, I need to understand the CLDR specs https://unicode.org/reports/tr35/tr35.html#Introduction to figure out how it works, what expected data had to be fulfill between tags, and so on... but some of you may know it already.

Shortly, are the expected `languages` -> `language type` in IETF file, such as "fr_CH", the languages spoken in the territory "CH" only ? (and not the fr_CH translation of all the languages (as it seems to be in the ISO-639-1 file "fr.xml" ) ?

By the way, how to make the Switzerland LocalizationPack becoming fr-ch, de-ch and it-ch instead of fr-fr, de-de and it-it) ?
(the same phenomenon occured with Belgium, fr-fr, de-de, nl-nl).

Any change on the IETF file (eg. as format number) is not considered in FO. Do you know why ?
Is it because of the tags ? Supposing the main file "fr" is unable to reach the regional "fr_CH" elements (or to be linked to) - even when the IETF is mentioned in BO - because the tags are not correctly written or mismatch ? as in fr.xml vs fr_CH.xml, used tags are `decimal` vs `currencyDecimal` and the so called `group` as the thousands separator is missing, as it follows : 

fr.xml :
```
<symbols numberSystem="latn">
			<decimal>,</decimal>
			<group> </group>
			<list>;</list>
```

fr_CH.xml : 	
```
<numbers>
		<symbols numberSystem="latn">
			<currencyDecimal>.</currencyDecimal>
		</symbols>
```


As you will see below, the three IETF files of the same country "CH" are not showing the same tags.
It looks like a bit erratic.
For example, the it_CH should have the same languages than the other ones ("fr_CH and de_CH"), but no `languages` tag is mentioned.

I'm discovering it, so sorry if many of you already mentioned that x times, but I'm worrying on possibly mistakes due to missing tags on a file, especially when these might be expected in some requests.

https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/de_CH.xml
https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/fr_CH.xml
https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/it_CH.xml

Focusing on the `languages` tags, starting from `ldml` until `dates` in CLDR v42 (Oct. 18th, 2022) there are : 

fr_CH : 
```
<ldml>
	<identity>
		<version number="$Revision$"/>
		<language type="fr"/>
		<territory type="CH"/>
	</identity>
	<localeDisplayNames>
		<languages>
			<language type="gu" draft="contributed">goudjrati</language>
			<language type="pdc" draft="contributed">allemand de Pennsylvanie</language>
			<language type="sdh" draft="contributed">kurde méridional</language>
		</languages>
	</localeDisplayNames>
	<delimiters>
		<alternateQuotationStart>‹</alternateQuotationStart>
		<alternateQuotationEnd>›</alternateQuotationEnd>
	</delimiters>
	<dates>
```

de_CH : 
```
<ldml>
	<identity>
		<version number="$Revision$"/>
		<language type="de"/>
		<territory type="CH"/>
	</identity>
	<localeDisplayNames>
		<languages>
			<language type="ach">Acholi-Sprache</language>
			<language type="bik">Bikol-Sprache</language>
			<language type="chb">Chibcha-Sprache</language>
			<language type="din">Dinka-Sprache</language>
			<language type="fan">Pangwe-Sprache</language>
			<language type="gba">Gbaya-Sprache</language>
			<language type="prg">Altpreussisch</language>
			<language type="rhg">Rohingya</language>
			<language type="tgx">Tagisch</language>
			<language type="zh_Hans" alt="long">Hochchinesisch (vereinfacht)</language>
			<language type="zh_Hant" alt="long">Hochchinesisch (traditionell)</language>
		</languages>
		<territories>
			<territory type="BN">Brunei</territory>
			<territory type="BW">Botswana</territory>
			<territory type="CV">Kapverden</territory>
			<territory type="QO">Äusseres Ozeanien</territory>
			<territory type="SB">Salomon-Inseln</territory>
			<territory type="TL">Osttimor</territory>
			<territory type="TR" alt="variant">Türkiye</territory>
			<territory type="ZW">Zimbabwe</territory>
		</territories>
		<keys>
			<key type="colCaseFirst">Sortierung nach Gross- bzw. Kleinbuchstaben</key>
			<key type="colCaseLevel">Sortierung nach Gross- oder Kleinschreibung</key>
			<key type="ms">Mass-System</key>
		</keys>
		<types>
			<type key="colCaseFirst" type="upper" draft="contributed">Grossbuchstaben zuerst aufführen</type>
			<type key="colCaseLevel" type="no" draft="contributed">Ohne Gross-/Kleinschreibung sortieren</type>
			<type key="colCaseLevel" type="yes" draft="contributed">Nach Gross-/Kleinschreibung sortieren</type>
			<type key="ms" type="uksystem">britisches Mass-System</type>
			<type key="ms" type="ussystem">US Mass-System</type>
		</types>
	</localeDisplayNames>
	<characters>
		<exemplarCharacters>[a ä b c d e f g h i j k l m n o ö p q r s t u ü v w x y z]</exemplarCharacters>
		<exemplarCharacters type="numbers">[\- ‑ . ’ % ‰ + 0 1 2 3 4 5 6 7 8 9]</exemplarCharacters>
		<parseLenients scope="general" level="lenient">
			<parseLenient sample="’">['ʼ՚᾽᾿’＇]</parseLenient>
		</parseLenients>
	</characters>
	<dates>
```

it_CH :
```
<ldml>
	<identity>
		<version number="$Revision$"/>
		<language type="it"/>
		<territory type="CH"/>
	</identity>
	<characters>
		<exemplarCharacters type="numbers">[\- ‑ . ’ % ‰ + 0 1 2 3 4 5 6 7 8 9]</exemplarCharacters>
	</characters>
	<delimiters>
		<alternateQuotationStart draft="unconfirmed">‹</alternateQuotationStart>
		<alternateQuotationEnd draft="unconfirmed">›</alternateQuotationEnd>
	</delimiters>
	<dates>
```

There is also the country file ch.xml (the localizationPack content actually)
https://github.com/PrestaShop/PrestaShop/blob/develop/localization/ch.xml

Wouldn't be possible (and easier) to use this one as format numbers and dates instead of the CLDR files ? (as it seems to be used to define the units and currency already).
Wouldn't be possible to include the IETF as `language type` next to the `language iso-code` ? (as IETF are related to the country)

```
<?xml version="1.0" encoding="UTF-8" ?>
<localizationPack name="Switzerland" version="1.0">
	<currencies>
		<currency name="Franc" iso_code="CHF" iso_code_num="756" sign="CHF" blank="1" format="5" decimals="1" />
	</currencies>
	<languages>
		<language iso_code="de" />
		<language iso_code="fr" />
		<language iso_code="it" />
	</languages>
```

It would also be nice to have an IETF to be shown in the url instead of the ISO-639-1.

Thank you in advance for your help and replies.
Best regards

**Comment by eternoendless** [comment]
> Shortly, are the expected `languages` -> `language type` in IETF file, such as "fr_CH", the languages spoken in the territory "CH" only ? (and not the fr_CH translation of all the languages (as it seems to be in the ISO-639-1 file "fr.xml" ) ?

No I don't think so. From the looks of it, it's just how those languages are spelled in Swiss french, which is probably just different than in "general" french. The CLDR spec uses the general language "fr" file as basis, then extends or overrides the initial configuration as described by the specific sub variant "fr_CH" file. That said, please be aware that that specific tag isn't used by PrestaShop. As I said, PrestaShop chooses which languages are spoken in what country using the _locale pack_ (see [here](https://github.com/PrestaShop/LocalizationFiles/blob/master/ch.xml#L6-L10)), not CLDR files. CLDR files are used exclusively for number and price (currency) formatting.

> how to make the Switzerland LocalizationPack becoming fr-ch, de-ch and it-ch instead of fr-fr, de-de and it-it) ?
(the same phenomenon occured with Belgium, fr-fr, de-de, nl-nl).

As I said before, this is not trivial to achieve. PrestaShop's language system was not designed for multilingual countries using their own language variants, because it uses country codes (ISO-639-1) to identify languages. The only way to get language variants in PrestaShop currently is through hacks involving the creation of arbitrary nonstandard "iso codes", like it was done with "QC" for Canadian French, or "AG" for Argentinian Spanish, which are then associated to the proper IETF tag ("fr-CA" and "es-AR" respectively) using [this file](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/all_languages.json#L498-L506).

> Any change on the IETF file (eg. as format number) is not considered in FO. Do you know why ?

From what I remember, the information read from CLDR files is stored in physical cache (`/var/cache/<env>`). You may need to flush the cache for the CLDR files to be read again. Also this might be overridden by the pattern set through the currency format customization in back office. In that case, you need to delete the "pattern" value for that currency/language in the table `ps_currency_lang`.

> There is also the country file ch.xml (the localizationPack content actually)
> Wouldn't be possible (and easier) to use this one as format numbers and dates instead of the CLDR files ? (as it seems to be used to define the units and currency already).

No, this was abandoned in favor of the CLDR standard for very good reasons, most notably that formatting depends on the language and not on the country. It's not a good idea to go around the standard. The standard is complex because reality is more complex than what it seems. We invested heavily in adopting CLDR, and we are not planning to go back. 

Old data has been kept there for backward compatibility reasons.

> Wouldn't be possible to include the IETF as language type next to the language iso-code ? (as IETF are related to the country)

It could be possible, but you still need a dedicated 2-letter iso code for Swiss variants for french, german and Italian. Otherwise you'd end up squashing the general variants with the swiss variants.
