### ISSUE TITLE
1-Click Upgrade 4.15.0 error OutOfMemoryExeption in ConfigurationTest.php

### ISSUE THREAD

**Issue by Kerami82** [PrestaShop/PrestaShop#32337]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Before 1-Clickupgrade version 4.15.0, never had this kind of problem. Now when try to access to 1 Click upgrade without debug mode I get 500 error. When turn on additional debug mode, I get OutOfMemoryException in ConfigurationTest.php line 259

I have php_value memory_limit 2048M

![blad2](https://user-images.githubusercontent.com/37613614/234484419-2b892b5c-43ad-45aa-b3f6-ecd317bf99a4.jpg)

If I dont add my IP in maintenance, I can access to 1 Click Upgrade, but checklist of maintenance is on red X and can't upgrade.

More users had the same problem and found this theme on forum: https://www.prestashop.com/forums/topic/1073724-1-click-upgrade-module-enable-maintenance-mode-error/

https://www.prestashop.com/forums/topic/1071917-1click-update-to-1788-ver-4150/

Additionally, I had session problem in 1 Click Upgrade, but this was helpful: https://github.com/PrestaShop/autoupgrade/pull/561/files

### Expected behavior

Access to 1 Click Upgrade module site and upgrade without problems.

### Steps to reproduce

1. Turn on maintenance mode with IP
2. Turn on debug mode
3. Go to 1-Click upgrade

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-Click upgrade v4.15.0

**Comment by Kerami82** [comment]
When I clean cache it starts to work.

**Comment by agroundworld** [comment]
I'm aware this issue is closed, but I wanted to chime in case others get this error.  I got the error for the first time when upgrading from 8.0.3 to 8.0.4 using PHP 8.1.18. I tried to clear the cache but the error still persisted. I changed the memory allocation for PHP on my web host to 512M, but this didn't resolve the issue either.  I disabled all non-native modules but nothing resolved the issue. I finally had to hard code ini_set("memory_limit","512M"); into config/defines.in.php. Once I upgraded, this file was overwritten and things seemed work without the hard coded memory limit.

For me, the error occurred after disabling the shop and attempting to go back into the 1-Click Module Upgrade in order to update. I was unable to reenter the module. Hope this additional information helps someone else if they encounter this issue.
