### ISSUE TITLE
1-Click Upgrade returned several errors after upgrade from PS V8.0.3 to V8.0.4

### ISSUE THREAD

**Issue by amazingballzs** [PrestaShop/PrestaShop#32350]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
While upgrading prestashop from V8.0.3 to V8.0.4 everything seemed fine except that I got these errors:

[INTERNAL] /public_html/vendor/smarty/smarty/libs/sysplugins/smarty_cacheresource.php line 208 - Symfony\Component\ErrorHandler\Error\UndefinedFunctionError: Attempted to call function "smarty_ucfirst_ascii" from the global namespace. #0 /public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_clearallcache.php(38): Smarty_CacheResource::load() #1 /public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php(133): Smarty_Internal_Method_ClearAllCache->clearAllCache() #2 /public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_data.php(270): Smarty_Internal_Extension_Handler->_callExternalMethod() #3 /public_html/classes/Tools.php(3280): Smarty_Internal_Data->__call() #4 /public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(672): ToolsCore::clearCache() #5 /public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(121): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runCoreCacheClean() #6 /public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #7 /public_html/admin561m14uxnqdxp1aah4c/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #8 {main}

The website seems to work fine after the upgrade, however, do these errors indicate that something is wrong in the resulting upgraded website?

Should I roll back the previous version or can I trust this upgraded version despite these eeors?

Should I fix anything to make sure everything will work fine?

Thank you

### Expected behavior

I expected to not get the errors listed above

### Steps to reproduce

1. Have Prestashop 8.0.3 upgraded from prestashop 8.0.2 on PHP 8.1
2. Go to modules and open 1Click upgrade module
3. Set the module to backup files and database, NOT backup images, server performance low, NOT disable non native modules, NOT disable overrides, yes to Upgrade the default theme, NOT to Switch to the default theme, yes to Regenerate RTL stylesheet, yes to Keep the customized email templates
4. Hit upgrade button

### PrestaShop version(s) where the bug happened

8.0.3 to 8.0.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

1-Click Upgrade

**Comment by PrestaEdit** [comment]
Hi,

Having the same issue (or a simular, not having time to copy the errors) upgrading 1.7.8.7 to 8.0.4.
Was able to upgrade the same shop on 8.0.3 (restoring due to a theme issue) without issues as this evening.

**Comment by jolelievre** [comment]
Not sure if it's related but with the latest version Smarty removed some modifiers, we had to add a bunch of them here https://github.com/PrestaShop/PrestaShop/blob/8.0.x/config/smarty.config.inc.php#L97 

The list is not exhaustive though since it's hard to know all the methods that were, so far, automatically bound with native PHP functions. There is no `smarty_ucfirst_ascii` only `ucfirst` so I'm not even sure if it's the reason but it's a lead

**Comment by florine2623** [comment]
Hello @amazingballzs ,

I'm upgrading from [8.0.3](https://build.prestashop-project.org/news/2023/prestashop-8-0-3-maintenance-release/) to [8.0.4](https://build.prestashop-project.org/news/2023/prestashop-8-0-4-maintenance-release/).

Using 1-Click Upgrade v4.15.0.

The upgrade is successful :

<img width="1435" alt="Screenshot 2023-04-28 at 15 45 27" src="https://user-images.githubusercontent.com/16019289/235164880-342ddae3-9a83-47ca-af91-64e82f361323.png">


https://user-images.githubusercontent.com/16019289/235164845-aba25739-35d9-4fc8-bd25-cb2c1211fb20.mov

**Comment by arcanewater** [comment]
I am having the same problem also with upgrading to 8.0.4 from 8.0.3 the error i receive during upgrade is

`08:33:24 CRITICAL [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "There is no active transaction" ["exception" =] PDOException { …},"command" =] "prestashop:schema:update-without-foreign --env=prod","message" =] "There is no active transaction"]In Connection.php line 1854:There is no active transactionprestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--]`

After this error site is somewhat 8.0.4 but non of theme is working (probably because upgrade failed midway) with errors like:

`[29-Apr-2023 15:46:48 Europe/Ljubljana] PHP Warning:  Undefined array key "ArabicFontStatus" in /public_html/nova/var/cache/dev/smarty/compile/v1_layouts_layout_left_column_tpl/03/88/41/`

**Comment by hibatallahAouadni** [comment]
Hello @amazingballzs 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by matks** [comment]
@amazingballzs @arcanewater this will maybe help you https://github.com/PrestaShop/PrestaShop/discussions/32348#discussioncomment-5782671

**Comment by jonasburneika** [comment]
Had same error on 8.1.5  fresh install. Main issue was MySQL user lack of Privileges (on my case INDEX privilege was missing) after `GRANT INDEX ON *.* TO 'username'@'host'; FLUSH PRIVILEGES;` problem was solved. My server was VPS and had created mysql user myself.
