### ISSUE TITLE
e-mail issue

### ISSUE THREAD

**Issue by radpol1440** [PrestaShop/PrestaShop#32378]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The presta shop doesn’t send  any notfications e.g the customer places an order and doesn’t receive any notification about the shippment, update. 

### Steps to reproduce

The presta shop doesn’t send  any notfications e.g the customer places an order and doesn’t receive any notification about the shippment, update. 

### PrestaShop version(s) where the bug happened

1.7.5.2

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

2.2.1

### Your company or customer's name goes here (if applicable).

Rad-Pol Sp. Z.o.o.

**Comment by florine2623** [comment]
Hello @radpol1440 ,

I can't reproduce your issue, the emails are well sent :
<img width="554" alt="Screenshot 2023-04-28 at 15 04 05" src="https://user-images.githubusercontent.com/16019289/235155378-dd8ea874-b87e-47a4-a78d-7ae45355fbc3.png">

It seems like your issue comes from your configuration.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
