### ISSUE TITLE
No adequate language  to the chosen in the menu  

### ISSUE THREAD

**Issue by AchrafKchaou1991** [PrestaShop/PrestaShop#32453]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using the Deutsh language many elements in the  `Advanced Parameters` still in English as :
*`Webservice `,`New &Experimental Features`,`Security` 

[Deutsh.webm](https://user-images.githubusercontent.com/131356155/236255146-f7bef48a-e024-43d6-80f4-2aebfea880c2.webm)

### Expected behavior

The menu shall be appear in adequate language. 

### Steps to reproduce

1.Choose the Deutsh
2.Go to `Advanced Parameters` > see the  error  : `Webservice `,`New &Experimental Features`,`Security` still in English

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Thanks for the report @AchrafKchaou1991 

@l-delin , Could you check if that's already translated in Crowdin ?

Thanks!

**Comment by l-delin** [comment]
Hello @florine2623 

Webservice translates to "Webservice", so no problem here.
![image](https://github.com/PrestaShop/PrestaShop/assets/113511191/d7912cde-83d8-42a1-881f-93fa9bed708e)

Both the "New & Experimental Features" and "Security" strings aren't validated, so that's why they still appear in English on a German installation of PrestaShop. See:

![image](https://github.com/PrestaShop/PrestaShop/assets/113511191/c208f2ee-dcab-4338-b770-b988831198c4)

![image](https://github.com/PrestaShop/PrestaShop/assets/113511191/f76ba600-4f6f-443c-a277-59800c384785)

FYI, I've approved both strings so they'll be available in German tomorrow. 
@AchrafKchaou1991 Could you update your German translations **tomorrow** and let me know if this issue is fixed? Thanks

**Comment by l-delin** [comment]
👋 
![image](https://github.com/PrestaShop/PrestaShop/assets/113511191/e9d8a322-4e43-4cb7-8e1a-510aed9a5754)
