### ISSUE TITLE
Not suitable language to the chosen in the help message 

### ISSUE THREAD

**Issue by AchrafKchaou1991** [PrestaShop/PrestaShop#32452]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The help text stills in English when changing  to an other language.

[helptext.webm](https://user-images.githubusercontent.com/131356155/236148355-94d5092d-06ee-4220-881e-e6fa698076d3.webm)

### Expected behavior

The help text shall be appear in adequate language. 

### Steps to reproduce

1.Choose any language expect English
2.Go to `Advanced Parameters`> `Data Base`> see the wrong help text in the section `Settings`
3.Go to `Advanced Parameters`> `Security`> see the wrong help text in the section `Password policy`

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.0.3

**Comment by l-delin** [comment]
Hello, same issue as [this PR](https://github.com/PrestaShop/PrestaShop/issues/32428#issuecomment-1541476698)

The catalog hasn't been pushed to Crowdin yet so its strings aren't available for translation yet. 
That's why it stays in English no matter what language you select for your BO

The only way to fix it is to wait for the [catalog](https://github.com/PrestaShop/PrestaShop/pull/32147) to be pushed and translated.

**Comment by florine2623** [comment]
I'm closing the issue as it is fixed.


https://github.com/PrestaShop/PrestaShop/assets/16019289/97d33c3a-888d-4835-9770-942821e56305
