### ISSUE TITLE
Upgrade from 1.7.8.7 to 8.0.4 Causes many errors

### ISSUE THREAD

**Issue by alkorotkovas** [PrestaShop/PrestaShop#32507]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading the website via the 1-Click Upgrade module from 1.7.8.7 to 8.0.4 it causes an error when trying to login into the admin dashboard.
![344310672_221031880636252_8394863096887608648_n](https://github.com/PrestaShop/PrestaShop/assets/103935370/8777aa23-fcfc-4472-93b7-34f754ca1b19)

### Expected behavior

Successful upgrade to 8.0.4

### Steps to reproduce

1. Go to 1-Click Upgrade
2. Perform an update from 1.7.8.7 to 8.0.4
3. Go to admin dashboard.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

1-Click Upgrade

**Comment by paulnoelcholot** [comment]
Hello @alkorotkovas,

I tried to reproduce this issue as you can see : https://watch.screencastify.com/v/BpOILIKxMS9aySXKdQX2

But I can't... Did I miss something?

Thanks for your feedback

**Comment by alkorotkovas** [comment]
Hello @paulnoelcholot,

I did the same, but instead of the local archive I used the live channel so it downloaded the file and then I clicked on the upgrade file.

**Comment by AureRita** [comment]
Hi @alkorotkovas 

I tried also to reproduce your issue from the major release and I can't reproduce it as you can see : 

[Untitled_ May 11, 2023 4_27 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/f673bc4e-7b6c-4864-97d8-eb50e7d0f37a)

Did you have more details to give us ? 

Waiting for your feedback

**Comment by ChillCode** [comment]
Hi,

It appears that your installation may not have updated or upgraded the configuration file for the product adapter services in PrestaShop. I would suggest checking to see if the file `src/PrestaShopBundle/Resources/config/services/adapter/product.yml` has the same content as the latest release of PrestaShop, which can be downloaded from the official Github repository at https://github.com/PrestaShop/PrestaShop/releases/download/8.0.4/prestashop_8.0.4.zip.

If there are any differences between the two files, you may need to update your configuration file accordingly. It is important to keep your software up-to-date and ensure that any configuration files are updated along with it in order to prevent issues and ensure that your software is running smoothly.

If you're not sure how to update the configuration file or run into any issues, you may want to consider reaching out to a PrestaShop agency for assistance. They can provide expert advice and support to help you resolve any problems you're experiencing.

I hope this helps. Let me know if you have any further questions or concerns.

**Comment by alkorotkovas** [comment]
Hi @ChillCode, @AureRita, @paulnoelcholot,

I will try to perform an update once again with the instructions mentioned above and let you know, I will record the whole process to show you.

Thank you.

**Comment by paulnoelcholot** [comment]
Hello @alkorotkovas,

Do you have some news about this issue?

Thank you so much for your attention and participation.

**Comment by hibatallahAouadni** [comment]
Hello @alkorotkovas 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
