### ISSUE TITLE
After upgrade cart don't update

### ISSUE THREAD

**Issue by Armi-Force-One** [PrestaShop/PrestaShop#32579]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, good afternoon:

After recent update to Prestashop 1.7.8.9, there is a problem.

The cart is not updated when quantities vary or after deleting, so it seems to do nothing. When updating with F5, the cart appears with the changes

 in quantities or without the products that have been correctly removed.

Putting the system in debug mode, a certain error appears, the detail in the attached file.

Could you help me?

My domain [www.articulosdepoker.com](https://articulosdepoker.com/en/)

Thanks...

[error cart debug.pdf](https://github.com/PrestaShop/PrestaShop/files/11480944/error.cart.debug.pdf)

### Steps to reproduce

1. Go to Articulosdepoker.com 
2. Add products 
3. Change quantyties
4. Delete products
5. F5

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

Articulosdepoker.com

**Comment by hibatallahAouadni** [comment]
Hello @Armi-Force-One 

It seems your issue is related your custom theme.
Closing the issue as we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
