### ISSUE TITLE
Error 500 when upgrading to (8.0.4

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#32603]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading from 1.7.8.9 to 8.0.4 with 1-Click Upgrade
It shows error 500 after BO login. _Property  Employee-&gt;email is empty._

![error](https://github.com/PrestaShop/PrestaShop/assets/19774996/fbea8043-c588-4a26-95a6-b8fff8bd3fe6)

### Steps to reproduce

upgrade from 1.7.8.9 to 8.0.4 with 1-Click Upgrade

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

**Comment by tesshsu** [comment]
Hi @thbl 
Since you had an update from version 1.7.8 to 8.0, 
The private static function callHookOn on classes/Hook.php had been enhanced with a try catch error, try to check the code on your local and compare this version: https://github.com/PrestaShop/PrestaShop/blob/8.0.x/classes/Hook.php

If you have recently made any changes to the code or modules, try reverting those changes and check if the error still occurs. Sometimes, code modifications or conflicts with other modules can cause unexpected issues.

Check the PrestaShop error logs for more detailed information about the error. The error logs can usually be found in the "logs" directory of your PrestaShop installation. Look for any error messages related to the Employee->email property

Make sure you are logged in as an employee with a valid email address. Check if the email address is set correctly in your employee profile

Hope this could help, tks

**Comment by thbl** [comment]
Hi @tesshsu thanks for your reply, i checked Hook.php and its same as from repo, also I disabled modules and overrides but the issue is still there when upgrading from 1.7.8.9 to 8.0.4.
I have to rollback before I can access BO, so I cant see any errors in log related to email.
And yes email is correct and valid.

**Comment by djoelleuch** [comment]
Hello @01Kuzma ,

 I try to reproduce you issue as you can see :

[Untitled_ May 18 2023 5_14 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/98c1955d-ac23-40f4-9d43-445330e37fb2)


But currently I can't, did I miss something ?

Waiting for your feedback


Thank you

**Comment by thbl** [comment]
@djoelleuch the issues / errors shows after you click log in button 3:22 in your video, as I see you don't click login

**Comment by thbl** [comment]
and @djoelleuch also login with a email not "root"

**Comment by AureRita** [comment]
Hi @thbl 

Thank you for your report and your details, I try to reproduce your issue as you can see : 

[Untitled_ May 19, 2023 4_32 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/a39e3f32-d6e0-4457-a77b-fd85ad0e3b0e)

But currently I can't reproduce it, Did I miss something ?

**Comment by thbl** [comment]
@AureRita nope, that should be it

**Comment by thbl** [comment]
it seems others are having the same problem 
https://www.prestashop.com/forums/topic/1073917-installation-of-module-failed-property-employee-email-is-empty/

**Comment by tesshsu** [comment]
Hi @thbl 
Great, do you set debug mode false : `define('_PS_MODE_DEV_', false);`
Then issue still persists?

**Comment by AchrafKchaou1991** [comment]
Hello @thbl 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

[issue32603bis .webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/0d56c5a8-7e93-49af-9cc4-fd21abba5eab)

We will close this issue.

Thank you

**Comment by thbl** [comment]
@AchrafKchaou1991 as you can see here its an bug in the ps_mbo module, did you have this installed doing your test ?
https://github.com/PrestaShop/PrestaShop/issues/32603#issuecomment-1555973900

**Comment by Tomi1444** [comment]
After updating to 8.1 from 1.7.8.7 i have this screen when I try to log into BO

![image](https://github.com/PrestaShop/PrestaShop/assets/118079647/5f90b243-7e8c-45e3-9e1f-36f9615e74bb)

**Comment by Tomi1444** [comment]
When I change name of ps_mbo to "ps_mbo2" I can log in.

But when I try to enter modules i have this:

![image](https://github.com/PrestaShop/PrestaShop/assets/118079647/acbda754-40f6-40a3-83aa-802400e79d5f)

**Comment by matks** [comment]
ping @sowbiba @intraordinaire if ps_mbo is involved you might be able to help

**Comment by intraordinaire** [comment]
@Tomi1444 Hi
Indeed, your first error is related to our module. There is already an issue [here](https://github.com/PrestaShopCorp/ps_mbo/issues/620).
We are working on a fix.
In the meantime, if you try to remove it, and install the last available version ([here](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.5.2)), it should work normally.

Your second error, is a problem with another module "hnews". It uses an old PHP syntax which is not supported anymore, try to check if you can have an update of this one too.
