### ISSUE TITLE
Invalid token when changing email address in profile page

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#32734]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Invalid token when changing email address in profile page

![Capture d’écran de 2023-05-29 10-07-17](https://github.com/PrestaShop/PrestaShop/assets/24647495/a6f8c6b4-bc73-42ae-91d6-aa82d8dc2b07)

### Expected behavior

A validation message should be displayed

![Capture d’écran de 2023-05-29 10-08-53](https://github.com/PrestaShop/PrestaShop/assets/24647495/d969c25e-dc0d-45a7-be4f-0c13820b6f01)

### Steps to reproduce

1- Go to Advanced parameters > Team page
2- Go to the first employee page
3- Update email and save
4- See the error => Invalid token: direct access to this link may lead to a potential security breach.

### PrestaShop version(s) where the bug happened

9.0

### PHP version(s) where the bug happened

8.1

**Comment by tleon** [comment]
The problem is caused when you change the email address of the account you're connected with. At some point in a redirection, the token of the BO access is regenerated. But it is regenerated using the old email address. The new address should be already saved into db but when the regeneration process fetches the user it gives an old version of the user.
To fix the problem,  ensure the user retrieved is with the right email address, then force the token regeneration.
