### ISSUE TITLE
1: HTTP 200 - parsererror -

### ISSUE THREAD

**Issue by Artlfmj** [PrestaShop/PrestaShop#32830]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://github.com/PrestaShop/PrestaShop/assets/73163159/383e5938-9876-4735-a574-3ce24cb693ca)
Getting this error, whilst it has correct information put in.

### Expected behavior

Should install correctly.

### Steps to reproduce

Make all usual steps, and it showed up at the end

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

8.2.6

**Comment by Artlfmj** [comment]
![image](https://github.com/PrestaShop/PrestaShop/assets/73163159/491d691a-216e-48c8-adb9-df9f3a1e1a29)
In english

**Comment by dnkhack** [comment]
Hello @Artlfmj please read first the System requirements for PrestaShop 1.7

You will see that version of PHP recommended for your version of PS.

By the way, your version has two critical vulnerabilities with SQL injection. The safety version from family 1.7 is 1.7.8.9 for PS8 is 8.0.4 

https://github.com/PrestaShop/PrestaShop/security/advisories/GHSA-6xxj-gcjq-wgf4
fixed in 1.7.8.2

https://github.com/advisories/GHSA-p379-cxqh-q822
fixed in 1.7.8.9 and 8.0.4

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/86b37e09-8711-447d-af40-abdbb77f57f3)

Have a good one 😉

**Comment by paulnoelcholot** [comment]
Hello @Artlfmj,

As @dnkhack said (thanks for your answer), Prestashop 1.7.7.4 is not compatible with a version of PHP higher than 7.3.
You need to change your version of PHP or your version of prestashop.

I will close this issue.
