### ISSUE TITLE
shopping cart problem

### ISSUE THREAD

**Issue by Murat-06** [PrestaShop/PrestaShop#32910]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When logging out, the products added to the shopping cart are deleted, and the products added to the previous cart are deleted when the same customer logs in.

### Expected behavior

When the customer creates an account and adds a product to the shopping cart and leaves the order without completing the order, they can see the products in the shopping cart, not search for products again, and place an order easily.

### Steps to reproduce

I don't know

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

 I don't know

**Comment by venditdevs** [comment]
@Murat-06  Probably related to this cases?

https://github.com/PrestaShop/PrestaShop/issues/12198
https://github.com/PrestaShop/PrestaShop/issues/28336

**Comment by dnkhack** [comment]
@Murat-06  hello. 
If you sign out then the cart be cleaned - and it is normal behavior.
If you want to keep the cart when login then **Shop Parameters > Customer Settings > Re-Display cart at login** set to **Yes**

**Comment by venditdevs** [comment]
> @venditdevs hello. If you sign out then the cart be cleaned - and it is normal behavior. If you want to keep the cart when login then **Shop Parameters > Customer Settings > Re-Display cart at login** set to **Yes**

Hello @dnkhack, we know this setting but that setting does not work anymore. There is something with an ID in the cookie (see other issues). Don't know the details but what OP posted is probably related to the other issues.

**Comment by dnkhack** [comment]
@venditdevs I'm sorry. I try to ask the @Murat-06 

@Murat-06  ok. If you use Chrome browser or another try to use the Cookies plugin to delete all cookies for the current website.

For Chrome this plugin is https://chrome.google.com/webstore/detail/awesome-cookie-manager/hcpidejphgpcgfnpiehkcckkkemgneif 

Also, you can try to use the Guest session in your browser. 

Please, can you provide the video or detailed step-by-step instructions to reproduce your issue? Better will be to capture the video. 
Thank you.

**Comment by AureRita** [comment]
Hello @Murat-06 

If your issue can be corrected by " Shop Parameters > Customer Settings > Re-Display cart at login set to Yes" setup 
I can close this issue 
If you need to put this option by default as this feature ask it (https://github.com/PrestaShop/PrestaShop/issues/12198) 
I can close this issue 
If it's an other issue, can you give us more information ? 

Waiting for your feedback

**Comment by florine2623** [comment]
Hello @Murat-06 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by topfuel75** [comment]
The nature behavior of PrestaShop is to replace the previous saved cart with the newly created cart.

The module **Merge Carts** will fix this issue and merge the carts instead of deleting the old/previous saved cart.

<img width="300" height="300" alt="Image" src="https://github.com/user-attachments/assets/7969262c-c196-488f-933c-2b83ed7949d3" />

**Get the module — The module “Merge Carts” is available at:**
https://addons.prestashop.com/en/social-login-connect/96287-merge-carts-prevent-lost-shopping-carts-on-login.html

**Demo — You can try the demo at:**
https://www.bulletproof.se/_demos/mergecarts/
(btw, the demo is darn easy to use. It's got some cool features, and it's super easy to create an account and log in).

**Video** — I explain the logic of how PrestaShop handles carts and how the module “Merge Carts” will fix it in this video:
https://youtu.be/mXKQUnPAjw8
