### ISSUE TITLE
Shipping Calc

### ISSUE THREAD

**Issue by cunha-fabricio** [PrestaShop/PrestaShop#32917]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop cart is calculating the shipping cost at every product added to cart, its causing a delay of 12 seconds depending of how many carriers integrations do you have.

### Expected behavior

I believe it should do the calculation only at the checkout page

### Steps to reproduce

go to product
add to cart

### PrestaShop version(s) where the bug happened

1.7.6

### PHP version(s) where the bug happened

7.2

**Comment by AureRita** [comment]
Hi @cunha-fabricio 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue about the performance  ? 

Thanks

**Comment by MatShir** [comment]
Hi @cunha-fabricio,
I think your issue is strongly related to this issue as well → https://github.com/PrestaShop/PrestaShop/issues/14979
I will close this one, it will be easier to track the bug in one issue on GitHub. 
Don't hesitate to comment the other issue to bring more feedback on the topic 

Thanks for your understanding.

This issue is a duplicate of #14979.

**Comment by hibatallahAouadni** [comment]
Duplicate of #14979
