### ISSUE TITLE
Auto upgrade module is not loading (stuck)

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/PrestaShop#32952]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a shop at 1.7.8.8 and want to upgrade to 1.7.8.9 with the autoupgrade module, but the configuration page of the module does not show up at all.

I am aware that we have a relatively huge shop, but I should be able to see something at least. It stays in loading when I click on the module link in side panel and then it goes for a long time. after that it shows timeout errors.

What should I do?

### Steps to reproduce

1. install autoupgrade module
2. open config page

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by florine2623** [comment]
Hello @stifler97 ,

I have installed PS 1.7.8.8, installed 1-Click Upgrade v4.15.0 and proceed with upgrade to 1.7.8.9 without issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/cef50b43-2341-4dc8-87a6-83f3b8739050

Upgrade successful:
<img width="1431" alt="Screenshot 2023-06-20 at 15 05 38" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/3ace8cac-4c56-48d8-b5be-49b2c4337b59">


It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
