### ISSUE TITLE
Hummingbird theme integration

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#33119]
The goal is to integrate the new Humming bird theme in PrestaShop 8.1

- [ ] Integrate bootstrap compatibility layer, two files JS/CSS from a CDN (waiting for URL) must be integrated in the FO depending on a configuration value to enable/disable its integration (disabled by default, possibility to use local version or CDN version: so three options)
- [ ] Once the configuration is available the classic theme should force it to false in its configuration, and hummingbird should force it to true
- [ ] Hummingbird should be integrated in 8.1.x but NOT as the default theme
- [ ] Ideally, we should launch the UI tests for hummingbird, we need to define if this should be handled on 8.1 (which implies activating it and maybe run at least the sanity tests)
- [ ] On develop the theme should be integrated by default, and this time I guess all UI tests should be based on this theme instead of classic

**Comment by kpodemski** [comment]
I'm surprised with this task. I missed the last Hummingbird Weekly, but we could've discussed it with the product and tech council and let the lead council decide, as it sounds like a strategic decision.

The bootstrap compatibility layer was supposed to be spread only in the PrestaShop Edition. The idea was for the Edition team to use it to launch the theme faster. They could put it in the module. Why would we need to integrate it into the core?

Also, I'm not a fan of rushing Hummingbird to 8.1 because it impacts the entire ecosystem.
Not a single layer will automatically make every single module compatible with the theme. The design aspects still would need to be adapted, so by doing this, you're causing mayhem in the ecosystem. As a module developer, your #1 job is to make your solution compatible with themes provided by PrestaShop in the core. I don't believe merchants would understand that Hummingbird is just a test theme, and module developers shouldn't worry about making their solutions compatible. Hummingbird wasn't battle-tested, and we don't have an update mechanism for the themes, so we can't provide fixes quicker.

Another reason why it isn't a good idea is that it forces us to maintain backward compatibility for the theme. Imagine that we add a theme to 8.1, a few months pass, and module developers need to re-work some of their solutions because we introduced bc breaks. Not to say that it's absolutely impossible for us to prepare documentation, a migration guide, and all other stuff required for the theme authors and module developers to know what's going on.

I understand that we wanted to be flexible in patch versions, but adding a new theme in the patch version sounds crazy.

That's my point of view 👍🏻

**Comment by Hlavtox** [comment]
I don't agree with this being in the core or into the opensource project.

Hummingbird is supposed to be a new clean start of clean code, integrating a "compatibility layer" will only allow the module developers to say "OK I don't have to do anything and I can keep my code". Not even talking about the mess it's gonna cause, like Krystian said.

The theme should not be rushed and we should do it cleanly for once. With a proper theme identification flag and the things we talked about.

**Comment by MatShir** [comment]
It was also the opportunity for theme dev to use the layer. But I understand your concerns the team is able to work around it. 

We are planning at some point including the HB theme in the core when we consider it stable enough. So new contribution can be tested directly with HB.

Thanks for the constructive feedbacks.
