### ISSUE TITLE
Categories blank schema is invalid

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#33166]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you use webservice, you should be able to ask for a schema, with an url like this: api/method?schema=blank.
This query must return a valid XML.
For categories method, XML is invalid:

![image](https://github.com/PrestaShop/PrestaShop/assets/6622400/2f58f8f9-4154-4a29-b057-d6ce6023b6fd)

It is a 8.1.0 regression.

### Expected behavior

XML must be valid.

### Steps to reproduce

1. Go on BO, enable webservice, allow GET onto categories.
2. Open in your browser yoururl/api/categories?schema=blank
3. Check XML validity, it is invalid.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1.2

**Comment by florine2623** [comment]
Hello @Max84 ,

I'm having a different issue from yours. Tested on PS 8.0.4 and 8.1.0. (have been fixed with https://github.com/PrestaShop/PrestaShop/pull/31023)
<img width="697" alt="Screenshot 2023-07-12 at 15 48 22" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/83c6a8fd-9eae-4c05-a122-054944747c96">

On develop, I do not have the issue.
<img width="324" alt="Screenshot 2023-07-12 at 15 50 42" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9fd7d6d3-cfbd-4f54-94cd-00c3029035b7">

It has been fixed on develop by https://github.com/PrestaShop/PrestaShop/pull/32884

I'm closing your issue as both issues are fixed on later versions of PS !

Thanks!
