### ISSUE TITLE
Order History not updated

### ISSUE THREAD

**Issue by MichielStr** [PrestaShop/PrestaShop#33238]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to update the status of an order, either programatically or through the backend, I get an error message: Er is een onverwachte fout opgetreden. [PrestaShopException code 42]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_employee' in 'field list'

No row has been added to ps_order_history since 28/06/2023, which I believe to be the date I upgraded to PS 8.1.0. 

### Expected behavior

I expect the order state to be updated and rows to be written to ps_order_history

### Steps to reproduce

1. Go to an order
2. Select any status
3. Click on 'Update status'

The same occurs when I run 

          $order = new Order($orders['id_order']);
          $history  = new OrderHistory();
          $history->id_order = (int)$order->id;
          $history->changeIdOrderState((int) $new_order_state, $order->id);
          $history->save();

from a php-script

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.0.29

**Comment by aitorjp** [comment]
Same here with PHP 8.1.21. Just happens with Orders created after upgrading to 8.1 from 8.0.4. Old Orders don't show errors and work correctly.
The Order is created without status, when you change the status, PS shows the error 42 but is changed. The status history doesn't show any status.
Adding manually the payment data shows the same error and doesn't work.
The Orders tab shows the amount of every order, but the clients tab show 0.00 spent by the user.

**Comment by OnLineDucha** [comment]
In #33118, near the end, there is a solution, inserting the "id_employee" column in the ps_order_payment table.

It fixed the error code 42 and allows me to add payments from the BO, but now I get an error [PrestaShopException code 23000] when changing the order status to "Payment accepted", because when I receive payment for an order, via the ps_checkout module, by PayPal or card, the default status is "Authorized. Seller will capture it" instead of "Payment accepted". Payments are correctly received in PayPal account. 
In my case the error code 42 started after upgrading from 8.0.1 to 8.1.0.

**Comment by aitorjp** [comment]
> In #33118, near the end, there is a solution, inserting the "id_employee" column in the ps_order_payment table.
> 
> It fixed the error code 42 and allows me to add payments from the BO, but now I get an error [PrestaShopException code 23000] when changing the order status to "Payment accepted", because when I receive payment for an order, via the ps_checkout module, by PayPal or card, the default status is "Authorized. Seller will capture it" instead of "Payment accepted". Payments are correctly received in PayPal account. In my case the error code 42 started after upgrading from 8.0.1 to 8.1.0.

Thank you so much. I add the column in order_payment table and that works.
I receive the 23000 error code, but if i add manually the payment info (Date, method, transaction id, etc.) all works perfectly with the change of status.
Now waiting for a new Order and see if PS adds the info automatically and all works fine.

EDIT: 
<strike> Not working for new orders.
The orders are created without any status and the payment info is not completed automatically</strike>

Sorry, doesn't work because I created the id_employee column with bad format. After deleting and created again with the following SQL command, all works fine again:
```SQL
ALTER TABLE `ps_order_payment` ADD `id_employee` INT NULL AFTER `date_add`;
```

**Comment by aniszr** [comment]
Hello @MichielStr 

I didn't manage to reproduce this issue with PS version :8.1.0 & PHP : 8.0 .

See attached screenvideo :

https://github.com/PrestaShop/PrestaShop/assets/92626242/6f047524-2842-4ade-adc7-6cb9da42c434

Please let me know if I missed something.

Thanks!

**Comment by MichielStr** [comment]
The column id_employee was missing in my ps_order_payment table. Adding that solved the issues for me. Both new and existing orders of which the state was changed, now have an order state again. Perhaps this only happens if users upgrade from an older version to version 8.1?

**Comment by Hlavtox** [comment]
@MichielStr Yes, author of that change forgot to update the autoupgrade script. We fixed it and will release a new version of the autoupgrade module. 👍

For existing upgrades, you can fix the issue permanently by running this SQL.

```sql
ALTER TABLE `ps_order_payment` ADD `id_employee` INT NULL AFTER `date_add`;
```
