### ISSUE TITLE
Upgrade egulias/email-validator

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#33445]
Check if JS lib should be updated.

**Comment by matks** [comment]
The work will be a lot more complex than expected, see https://github.com/PrestaShop/PrestaShop/discussions/33511

**Comment by WahbiPS** [comment]
~~Blocked, waiting for discussion above~~

**Comment by M0rgan01** [comment]
Requires modules upgrades:

- ps_linklist https://github.com/PrestaShop/ps_linklist/pull/179
- productcomments https://github.com/PrestaShop/productcomments/pull/178

Main PR: https://github.com/PrestaShop/PrestaShop/pull/33459

**Comment by M0rgan01** [comment]
The upgrade of the email-validator library required an update of several Doctrine libraries, which complicated the task. The majority of the changes come from Doctrine DBAL (https://github.com/doctrine/dbal/blob/3.6.x/UPGRADE.md). All native modules also need to be checked.

- [x] autoupgrade
- [x] blockreassurance
- [x] blockwishlist
- [x] contactform
- [x] dashactivity
- [x] dashgoals
- [x] dashproducts
- [x] dashtrends
- [x] followup
- [x] graphnvd3
- [x] gridhtml
- [x] gsitemap
- [x] pagesnotfound
- [x] productcomments
- [x] ps_banner
- [x] ps_bestsellers
- [x] ps_brandlist
- [x] ps_cashondelivery
- [x] ps_categoryproducts
- [x] ps_categorytree
- [x] ps_checkpayment
- [x] ps_contactinfo
- [x] ps_crossselling
- [x] ps_currencyselector
- [x] ps_customeraccountlinks
- [x] ps_customersignin
- [x] ps_customtext
- [x] ps_dataprivacy
- [x] ps_distributionapiclient
- [x] ps_emailalerts
- [x] ps_emailsubscription
- [x] ps_facetedsearch
- [x] ps_faviconnotificationbo
- [x] ps_featuredproducts
- [x] psgdpr
- [x] ps_googleanalytics
- [x] ps_imageslider
- [x] ps_languageselector
- [x] ps_linklist
- [x] ps_mainmenu
- [x] ps_newproducts
- [x] ps_reminder
- [x] ps_searchbar
- [x] ps_sharebuttons
- [x] ps_shoppingcart
- [x] ps_socialfollow
- [x] ps_specials
- [x] ps_supplierlist
- [x] ps_themecusto
- [x] ps_viewedproduct
- [x] ps_wirepayment
- [x] referralprogram
- [x] statsbestcategories
- [x] statsbestcustomers
- [x] statsbestmanufacturers
- [x] statsbestproducts
- [x] statsbestsuppliers
- [x] statsbestvouchers
- [x] statscarrier
- [x] statscatalog
- [x] statscheckup
- [x] statsdata
- [x] statsforecast
- [x] statsnewsletter
- [x] statspersonalinfos
- [x] statsproduct
- [x] statsregistrations
- [x] statssales
- [x] statssearch
- [x] statsstock

**Comment by WahbiPS** [comment]
Blocked by this https://github.com/PrestaShop/productcomments/pull/180

**Comment by matks** [comment]
Now awaiting for ps_linklist 6.0.4 release https://github.com/PrestaShop/ps_linklist/pull/183

**Comment by matks** [comment]
This topic is blocked because PR https://github.com/PrestaShop/PrestaShop/pull/33459 is blocked

We have Sanity tests failing and it seems this is not due to a real problem*, but rather something to improve in Sanity tests.

*We attempted to follow the test steps on a real shop and could not observe the bug symptoms.

@jolelievre first attempted to do PR https://github.com/PrestaShop/ga.tests.ui.pr/pull/47 but it did not work

Another attempt https://github.com/PrestaShop/ga.tests.ui.pr/pull/44 that might help solving the problem

If PR https://github.com/PrestaShop/ga.tests.ui.pr/pull/44 does not solve the problem, we need to decide on what we do to unblock this topic with. People that need to be included in the discussion
- @jolelievre 
- @matthieu-rolland 
- @Progi1984 
- (optional) @M0rgan01

**Comment by matks** [comment]
🎉
