### ISSUE TITLE
Backoffice translations broken when updating from 1.7 to 8.1

### ISSUE THREAD

**Issue by venditdevs** [PrestaShop/PrestaShop#33647]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

First of all, my apologies if we missed something.

When you update from 1.7.8.7 or 1.7.8.8 in this case, directly to 8.1.1, the backoffice translation is broken, the translations are present but not visible.

When you update from 8.0.4 to 8.1.1 everything works fine.

Example from 1.7.8.8 to 8.1.1

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/295b41cd-7435-45fa-9959-6cb3bcca23db)

Translations:

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/4a7cc7e2-f122-433b-8b05-e9662c594dad)

Example from 8.0.4 to 8.1.1

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/98e1fce3-da4c-41e0-9444-0789c2b93f61)

Translations:

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/d852b651-6ff3-47d2-b322-fa7fa197952a)

As you can see, the translations are present but not active in the first situation.

### Expected behavior

Translations should be working

### Steps to reproduce

One click upgrade from 1.7.8.8. and update directly to 8.1.1 (switch to PHP8.1) and the translations are broken.

One click upgrade from 8.0.4. and update directly to 8.1.1 PHP8.1 allready active and the translations are working.

### PrestaShop version(s) where the bug happened

1.7.8.7, 1.7.8.8, 8.1.0, 8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @venditdevs 

Sometimes we encounter these translation issues because of cache, so just try to update your language under BO>International>Translation as shown in the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/c10e635e-c79a-4495-a372-f28e73a082cc)

Then, disable the cache, clear it and check if you still encounter the issue.
Waiting for your feedback.

Thanks!

**Comment by venditdevs** [comment]
@hibatallahAouadni  It is not a cache problem, we allready tried that. 

I'm willing to try the update of the language but what happends to the existing translations then? because a lot of standard translations are just one on one Google Translate translations, like "Place order", its litteraly "Place Order" in Dutch while the button should be called "Pay and Place order" or "Order and Pay" (in Dutch) cause of some lawsuit someone won in the Netherlands the "Pay" should be clearly present so the customer knows they need to pay when they place the order (i know... it's lame..). That translation is allready gone after updating to a newer version from 1.7 => 8, we don't want to lose more of our custom translations.

**Comment by MatShir** [comment]
It should not erase custom translation but only update the missing default one. I see your concern, maybe we should check it to be sure. 
@eternoendless do you more insight on the subject ?
@venditdevs maybe worth the try on new test shop env

**Comment by eternoendless** [comment]
AFAIK downloading the new translation pack shouldn't overwrite custom translations because those are stored in the database, unlike translation packs which are xlf files.

Incidentally, this can be done more than once because sometimes packs are updated with fixes (but to the best of my knowledge only the last major branch receives translation updates).

That aside, it's interesting to see that only the menu translations seem to be broken. These wordings aren't translated in real time but stored translated in `ps_tab_lang`; I can't see why they would have been modified by the upgrade process. Can you have a look in your database and see if they are there?

**Comment by venditdevs** [comment]
@hibatallahAouadni  @MatShir and @eternoendless, thanks for the support, this seems to solve the problem and custom translations are not overwritten.

The weird thing was that it looks like a temporary problem, because if we update other shops now, we don't encounter this problem anymore while it was with every shop till yesterday.

Case closed

**Comment by MatShir** [comment]
Sometime we have issue on menu translation, it's not the first time we have this issue. Temp fix is to update the translation. But I don't know why this part is unstable
