### ISSUE TITLE
Preview panel always loading

### ISSUE THREAD

**Issue by Dano7762** [PrestaShop/PrestaShop#33645]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
In the activity preview panel we don't see any statistics, just the loading animation.
This is quite disturbing.
Can you help us solve this problem?
Thank you in advance.

![Capture d'écran 2023-08-17 155435](https://github.com/PrestaShop/PrestaShop/assets/75814070/d36bb8fd-7bbd-4e73-b9fa-49a68a41cd34)

### Steps to reproduce

Go to BO
Activity overview is on the left

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

81.18

### If your bug is related to a module, specify its name and its version

dashactivity v2.1.0

**Comment by paulnoelcholot** [comment]
Hello @Dano7762 ,

I have tried to reproduce your bug, but I can't as you can see :

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/43a002ba-3f13-456b-9075-fec339ab6d1b)

Can you give more information to reproduce it?

Thank you for your feedback.

**Comment by Dano7762** [comment]
Unfortunately, I can't give any more information, as this panel is displayed automatically when I connect to the back-office.
It has never worked

What can I check ?

**Comment by paulnoelcholot** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Please check your server configuration or disable your third-party modules

[Get help with PrestaShop](https://www.prestashop-project.org/support/).

We will close this issue.

Thank you
