### ISSUE TITLE
Handle file upload

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/PrestaShop#33652]
Some are event related to file uploading (maybe this use case deserves a dedicated issue, since it needs to handle file upload as well): https://github.com/PrestaShop/PrestaShop/blob/824691139ee1ee220fc1a2f3b9d7b4fed5cd33f0/src/Core/Domain/Attachment/Command/EditAttachmentCommand.php#L103

**Comment by jolelievre** [comment]
That's the goal 😅

```php
class Hook
{
    #[ApiProperty(identifier: true)]
    #[Groups(['hook-status:read'])]
    public int $id;

    #[Groups(['hook-status:read'])]
    public bool $active;

    public string $name;

    public string $title;

    public string $description;

    /** @var UploadedFile */
    #[UploadableField(fileNameProperty: 'pathName', mimeTypeProperty: 'mimeType')]
    public $uploadedFile;
}
```

**Comment by matks** [comment]
Hey everyone, this ticket has been "blocked" because I believe this might not be the most important thing to focus on right now

1. Handling file uploads in REST APIs is always, whatever the API, overly complex (cf. https://github.com/json-api/json-api/issues/246#issuecomment-163569165 nice insights)
2. We don't even have an API yet, and how many endpoints of the API are going to need file upload? Endpoints being mapped on Commands and Queries I believe it's like ... 2% ? 5% ?
3. So IMO this is an unnecessary complex, that might be useful to solve for 5% usecases, for me it's not relevant to do this as we're aiming to build a MVP API. MVP as Minimum Valuable Product :grin:
