### ISSUE TITLE
Cannot create new product after upgradcing from 8.1.0 to 8.1.1

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33793]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It seems basic functionality is suffering in the 8.x releases of Prestashop which has unfortunately hindered the progress of several projects.

The latest issue is, after upgrading from Prestashop 8.1.0 to Prestashop 8.1.1 using the 1 click upgrade module, when attempting to create a new product the following error is thrown:

Attempted to load class "RatesHelper" from namespace "PrestaShop\Module\Mbeshipping\Helper".
Did you forget a "use" statement for another namespace?

Preventing the user from creating a new product.

### Steps to reproduce

Install Prestashop 8.1.0 (Basic addition as downloaded from the Prestashop.com site)
Upgrade to 8.1.1 via 1 click upgrade module
Attempt to create a new product

### PrestaShop version(s) where the bug happened

8.1.1

**Comment by Hlavtox** [comment]
@musaffarpatel Basic functionality is suffering because of `Mbeshipping` you have installed. 👍

**Comment by musaffarpatel** [comment]
@Hlavtox Strange as I did not install anything.  Here are the steps I performed which I hope helps clarify the issue:

Installed fresh version of Prestashop 8.1.0 (Basic edition from prestashop.com)
Immediately upgraded to 8.1.1 from the 1 click upgrade module

At this point the issue appears.

**Comment by paulnoelcholot** [comment]
Hello @musaffarpatel,

I tried to reproduce your bug but as you can see, I can't. Did I miss something?

Thanks for your feedback !

[1-Click Upgrade _ 1-Click Upgrade • the future.webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/b93b2d71-348f-4ecb-bddf-d6e90baa1b9a)

**Comment by Hlavtox** [comment]
@paulnoelcholot I think @musaffarpatel is using company edition with some faulty bundled module Mbeshipping.

**Comment by musaffarpatel** [comment]
@paulnoelcholot As @Hlavtox correctly points out, I upgraded to 8.1.1 from the branded version of 8.1.0 downloaded from prestashop.com

**Comment by GASNII** [comment]
Same issue, can not add product after upgrade to 8.1.1

**Comment by ChillCode** [comment]
Hi

I've had the same issue, since there is no Shipping tab the query to get carriers returns null on Virtual products.

The temp workaround is to modify `admin/themes/new-theme/public/product_edit.bundle.js`

Replaced at line 1922 the following:

`function(t,e){const n=document.querySelector(t),`

with:

`function(t,e){const n=document.querySelector(t); if (n === null) {return false;};const `

**Comment by ChillCode** [comment]
Hi @paulnoelcholot

You're adding a Standard Product that have Shipping Tab, try with Virtual.

**Comment by Hlavtox** [comment]
Maybe a duplicate of https://github.com/PrestaShop/PrestaShop/issues/32632

**Comment by sallemiines** [comment]
Hello @musaffarpatel 

Please donwload PrestaShop from github, we only support the Open Source Project here, see the attached screen record below:

[issue_33793.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/b046d95c-71b8-4da8-a68f-bfeaaa6f2ffe)

Otherwise the version that you download it from prestashop site is MBE version and it's not supported by us, so you may contact the Team on addons.prestashop (please read this [comment](https://github.com/PrestaShop/PrestaShop/issues/32632#issuecomment-1560510783) to understand better)
Closing the issue as it's not related to OS project, thanks for your understanding :pray: 

Thanks!

**Comment by SireEphraim** [comment]
@sallemiines 
I am currently facing the same challenge following the same steps upgrading from 8.1.0 to 8.1.1. using the 1-click upgrade.
I had to confirm that my upgrade was from github link 

I really need a breakthrough.


Thank you.

**Comment by musaffarpatel** [comment]
@sallemiines While I can download the Github version no issues, large number of clients are downloading from Prestashop.com and will run into the same issue after they upgrade to 8.1.1 - therefore I do feel this is an issue both teams should have a conversation about.

**Comment by lordchukz** [comment]
Hello, I came across same problem and yes, after I read this tread, uninstalling the MBE shipping module resolved the error.

Question, can I please know what is the difference between prestashop "MBE" version and "OS" project?

Thanks in advance.

Regards.

**Comment by matks** [comment]
@lordchukz I will quote [PrestaShop Edition](https://help-center.prestashop.com/en/articles/8742641310098-prestashop-edition) FAQ 👍 

> ### What is the difference with the open source project?
> PrestaShop Edition is a turnkey solution, based on the open source project PrestaShop. Unlike the Open Source solution, the Edition offer contains hosting and support services, as well as additional functionalities thanks to the modules directly installed at the creation of the store.

To clear the confusion with MBE 😄 :
- PrestaShop Edition is a product from PrestaShop company
- PrestaShop company has joined the MBE group since 2022

This is why you'll find the MBE Shipping module inside PrestaShop's company product 😉

**Comment by lordchukz** [comment]
Oh well, thank you so much for the clarification.

Then it remains open source except one decides to use the services.

Regards.

**Comment by lordchukz** [comment]
> Hello @musaffarpatel
> 
> Please donwload PrestaShop from github, we only support the Open Source Project here, see the attached screen record below:
> 
>  issue_33793.webm 
> 
> Otherwise the version that you download it from prestashop site is MBE version and it's not supported by us, so you may contact the Team on addons.prestashop (please read this [comment](https://github.com/PrestaShop/PrestaShop/issues/32632#issuecomment-1560510783) to understand better) Closing the issue as it's not related to OS project, thanks for your understanding 🙏
> 
> Thanks!

Hi, please where can I download the OS version on GitHub?

I noticed today on my test environment that I cannot export product data which I believe is another MBE limitation.

I'm afraid there will be more so I would prefer to avoid these surprises by getting the OS version.

Thanks.
