### ISSUE TITLE
Missing AdminWarehouses controller

### ISSUE THREAD

**Issue by ihulsbus** [PrestaShop/PrestaShop#33859]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After migrating to Prestashop8, the warehouse management seems to be missing. This also happens in a clean installation of Prestashop. 

When searching for "Warehouses" in the search bar, I do get the option "Warehouses" but when I click it I get the error
"The controller AdminWarehouses is missing or invalid."

<img width="950" alt="Screenshot 2023-09-06 at 12 56 53 PM" src="https://github.com/PrestaShop/PrestaShop/assets/11390889/5c3dfe11-643a-4264-a699-427717cb4f79">

### Expected behavior

I expect the warehouse functionality to be working

### Steps to reproduce

1. Go to the backoffice
2. search for "Warehouse"
3. click the feature "Warehouses"
4. observe error 

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.22

### If your bug is related to a module, specify its name and its version

AdminWarehouses

**Comment by ChillCode** [comment]
Hi @ihulsbus 

I think that controller is deprecated (Advanced Stock Management) since 1.7.8 and was removed sometime time ago.

**Comment by matks** [comment]
Hi @ihulsbus I agree that this is a bug:

1. Go to the backoffice
2. Search for "Warehouse"
3. See option "Warehouses"

Warehouse management has been removed in PrestaShop 1.7.0 . It was available in PrestaShop 1.6 but it was so full of bugs it was removed from the scope of the open source project, in 2017. The removal was not done properly which is why many files and links remained in the backoffice and need to be cleaned, but the feature has been removed so when you say

> I expect the warehouse functionality to be working

I'm afraid this will not happen

**Comment by Hlavtox** [comment]
@matks Done ;-) https://github.com/PrestaShop/PrestaShop/pull/33158

**Comment by sallemiines** [comment]
Hello @ihulsbus 

Thanks guys for your quick replies :pray: 
Closing the issue as it's fixed by @Hlavtox in this PR #33158 on 9.0.0 (next major release) :tada: 

Thanks!

**Comment by ihulsbus** [comment]
Great work thank you!
