### ISSUE TITLE
Autoupgrade module runs old sql commands

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#33856]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

During an upgrade from Prestashop 1.7.8.8 to 8.1.1 the autoupgrade module reruns all 1.7.0.0 + SQL upgrade commands.

### Expected behavior

Only run the SQL commands for version higher than current version.

### Steps to reproduce

Perform an upgrade using the autoupgrade module from PS 1.7.8.8 to 8.1.1 major channel.
Let the process complete, in the result field of the upgrade you will se lots of green rows with info like
OK] SQL 1.7.0.0 SET NAMES 'utf8'
[OK] PHP 1.7.0.0 : /* PHP:ps_1700_short_description_config(); */
and so on, these should not have been executed.

### PrestaShop version(s) where the bug happened

FROM 1.7.8.8 TO 8.1.1

### PHP version(s) where the bug happened

7.4.9

### If your bug is related to a module, specify its name and its version

autoupgrade 4.16.2

### Your company or customer's name goes here (if applicable).

Prestaworks AB

**Comment by sallemiines** [comment]
Hello @Prestaworks 

I didn't manage to reproduce the issue with the provided infos, the autoupgrade was done without any error :thinking: 
Could you please provide more infos or some srcreenshots :pray: 
Waiting for your feedback.

Thanks!

**Comment by kpodemski** [comment]
@Prestaworks I'm not sure if that's true, if that were the case, you'd have failed upgrade because of some `ALTER TABLE` 🤔 maybe it just informs that this file has been run, but skip it? ;) so maybe the log is wrong

**Comment by Prestaworks** [comment]
> @Prestaworks I'm not sure if that's true, if that were the case, you'd have failed upgrade because of some `ALTER TABLE` 🤔 maybe it just informs that this file has been run, but skip it? ;) so maybe the log is wrong

that could be the case, but it's odd that it starts with 1.7.0.0 and moves up, why not the 1.6 files?

**Comment by Prestaworks** [comment]
![upgradeIssue](https://github.com/PrestaShop/PrestaShop/assets/2902272/e3da873d-48ee-4cbc-b567-6488bbeb8f85)
here is a screenshot of the issue

**Comment by Prestaworks** [comment]
and just to be clear, the screenshot is from upgrade from 1.7.8.8 to 8.1.2

**Comment by ChillCode** [comment]
Hi @Prestaworks and @kpodemski 

Have you investigated this issue?  So I not lose my time.

It also happened to me few times, but now I can confirm it while upgrading via cli from 8.1.2 to 8.1.4 it loaded 8.1.0.sql again and the upgrade failed because was trying to add a unique value multiple_image_format to PREFIX_feature_flag and add id_employee to PREFIX_order_payment when already present.

The next files (8.1.1, 8.1.2) doesn't break the upgrade because there is only command and have ON DUPLICATE KEY UPDATE so we prevent those errors.

By now just solved it by removing those two lines from 8.1.0.sql and upgrade finished.

Maybe has something to do with this:

https://github.com/PrestaShop/PrestaShop/issues/33886

**Comment by kpodemski** [comment]
@ChillCode @Prestaworks 

It seems it might be fixed on 5.0.1 of autoupgrade:
https://github.com/PrestaShop/autoupgrade/pull/661

Have you tried the latest version?

**Comment by ChillCode** [comment]
Hi @kpodemski 

Just opened VS to go directly to that function haha and saw a notification with your link, nice.

Did it yesterday, and I usually upgrade the modules before I start the cli process, but since I have a snapshot will try again when I've few minutes to make sure I was using latest autoupgrade.

**Comment by ChillCode** [comment]
Hi @kpodemski 

Now I see is not related, but it's a weird issue.

At the end I just checked PS_VERSION_DB on this installation and before the upgrade was 8.0.4, and the real installed version was 8.1.2, so the module loaded all the files correctly. Strange did not update to latest version on the few upgrades I did from 8.0.4, and the latest one to 8.1.2 ended correctly and dev site worked.

Now PS_VERSION_DB is 8.1.4, so will stop facing this issue.

Before starting the upgrade a consistency check could be added, if PS_VERSION_DB dose not compare to _PS_VERSION_ block the upgrade process.

**Comment by kpodemski** [comment]
@ChillCode

Thank you very much for taking the time to investigate this issue and for the solution, as a consistency check should be a good option. On top of that, maybe some text/instruction should probably explain what to do in such a situation.

cc @MatShir

**Comment by Quetzacoalt91** [comment]
Thanks for the analysis @ChillCode.

Blocking the upgrade (with the module) is a first solution, but it is not enough in my opinion.
I'm wondering how can we help merchants to fix this, as it would be better for him to not finish on a dead end.

Shall we try to run missed SQL files without stopping on errors ? Redirect to a documentation page ? Assuming we know what to do in this situation.

**Comment by ChillCode** [comment]
Hi @Quetzacoalt91 

> Blocking the upgrade (with the module) is a first solution, but it is not enough in my opinion.

Is not enough, but it's like the other blocking requirements we get.

> I'm wondering how can we help merchants to fix this, as it would be better for him to not finish on a dead end.

This issue can occur in two situations:

While upgrading via BO and the upgrade fails before calling ["UpgradeComplete"](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade-module/upgrade-process-steps/) or if the UpgradeComplete fires but there were previous errors, then is when PS_VERSION_DB is not updated.

While upgrading via CLI and error occurs before "Running generic queries" step completes.

Sometimes, in both situations, database is upgraded, files are upgraded and PS works, but PS_VERSION_DB is not updated, and since the rest of steps/actions are not really blocking or critical, merchants usually ignore this unfinished installation, and merchants do not update PrestaShop every month, so they will forget completely and face this error on next upgrade.

My solution was removing the blocking SQL commands.

Another solution is to upgrade PS_VERSION_DB just after the upgradeDb finishes, so the rest of process don't block this, but this may cause other issues.

It also can be prevented using ON DUPLIACTE KEY UPDATE or IGNORE, CREATE IF NOT EXISTS, but ALTER TABLE ADD COLUMN IF NOT EXISTS is not available on older MySQL dist. so is not a solution for PS.

An I did broke one upgrade to 8.1.5 from 1.7.8.11  in purpose after database was upgraded, so PS_VERSION_DB was not updated, then I just run via upgrade-cli an upgradeDb command again and it finishes without errors and PS_VERSION_DB was updated, an site works.

**Comment by Prestaworks** [comment]
I think that blocking the upgrade and then having a clear instruction informing the user that
PS_VERSION_DB dose not compare to PS_VERSION and that PS_VERSION_DB needs to be adjusted in the db, maybe an sql command that can be copy pasted? But also some information that this could be due to an earlier failed upgrade and that the user shoud take caution?
