### ISSUE TITLE
Add / Update a language section doesn't override the current files of mail folders

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34128]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I recently noticed that on Prestashop 8.1 if I update a language, the email files in the main mails/ folder are not overwritten
to update those files I have to remove the folders and then update the language

I wanted to know if it was intentional or a mistake

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/52dea242-053d-416e-bc9f-07dd65df6d4c)

bye

### Steps to reproduce

1. go in the Translations page
2. update a language
3. check if its files are updated into the mails folder (try to set a past version of order_conf.html like of 1.7.x to see if after the update you get the new version of this file)

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by jolelievre** [comment]
Hello @maofree 

thanks for the feedback, actually the behaviour you are describing is on purpose this is because the email feature is still, today, a mix between two features:
- the legacy feature based on static HTML files that can be manually edited in the Back Office or exported by legacy Email themes that contain hard coded HTML templates
- the more recent feature of Email themes, based on twig templates that include translatable wordings, but this feature is not fully dynamic yet For backward compatibility it only allows to generate static HTML files, so that then it works the same as the legacy feature

For this reason we can't force overwriting the static files when a language is updated, because some users probably still rely on the legacy system and they don't want their custom modifications to be erased every time a language is updated.

That's for the content, but for your current problem you can actually force the re-generation of the emails but manually, to do this you need to go to the `Design > Email theme` section in the back office, you will find a form that allows generating the static files. It lets you select the language, which email theme you want to use (by default it's the recent Modern theme, at least in recent versions). Be careful to select the appropriate theme as well, because the FO themes also allow to override the core email HTML files, so if you are using a theme you'll need the select it so that the files are overwritten in the appropriate folder. And of course don't forget to check the toggle `Overwrite templates`, because it is not selected by default (again out of safety to avoid erasing some files by mistake).

![Capture d’écran 2023-10-10 à 12 44 32](https://github.com/PrestaShop/PrestaShop/assets/13801017/f5401681-4577-4739-be23-4daa6f19826f)

**Comment by Maofree** [comment]
ok thanks for your infos
