### ISSUE TITLE
ColorBrightnessCalculator.php

### ISSUE THREAD

**Issue by Teidata** [PrestaShop/PrestaShop#34141]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Unknown error en línea 66 en archivo /var/www/vhosts/xxxxxxx.com/httpdocs/presta_811/src/Core/Util/ColorBrightnessCalculator.php
[8192] Invalid characters passed for attempted conversion, these have been ignored

Unknown error en línea 67 en archivo /var/www/vhosts/xxxxxxx.com/httpdocs/presta_811/src/Core/Util/ColorBrightnessCalculator.php
[8192] Invalid characters passed for attempted conversion, these have been ignored

Unknown error en línea 68 en archivo /var/www/vhosts/xxxxxxx.com/httpdocs/presta_811/src/Core/Util/ColorBrightnessCalculator.php
[8192] Invalid characters passed for attempted conversion, these have been ignored

### Expected behavior

Change the color of the label of the order statuses

### Steps to reproduce

When you want to change the color of the label of the order statuses, the following error is displayed

### PrestaShop version(s) where the bug happened

Prestashop 8.1

### PHP version(s) where the bug happened

PHP 8.1

### Your company or customer's name goes here (if applicable).

Teidata

**Comment by florine2623** [comment]
Hello @Teidata ,

I can't reproduce your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/7bfff37d-a310-434c-9706-dd874f08bca4

Am I missing something ?

**Comment by AOD28** [comment]
Hello, just to let you know that I have the same error, but in a different environment. I checked the affected file, but I don't see any invalid characters on the 3 affected lines.

Unknown error on line 66 of file /home/sdxw6342/public_html/src/Core/Util/ColorBrightnessCalculator.php
[8192] Invalid characters passed for conversion attempt, they were ignored

Unknown error on line 67 of file /home/sdxw6342/public_html/src/Core/Util/ColorBrightnessCalculator.php
[8192] Invalid characters passed for conversion attempt, they were ignored

Unknown error on line 68 of file /home/sdxw6342/public_html/src/Core/Util/ColorBrightnessCalculator.php
[8192] Invalid characters passed for conversion attempt, they were ignored

Expected behaviour
Appears when accessing the Order Status page from Store Settings / Orders

Steps to reproduce
Just go to the page

PrestaShop version(s) where the bug happened
Prestashop 1.7.8.8

PHP version(s) where the bug happened
PHP 7.4

If your bug is related to a module, specify its name and its version
No response

Your company or customer's name goes here (if applicable).
Art de Lys


![PS7-4-erreur-parametres-commandes-etatsdecommandes](https://github.com/PrestaShop/PrestaShop/assets/87701789/c0cada6b-09d7-4ca0-8f22-3c830e24bb7a)
![screencapture-artdelys-admin039ginhrp-index-php-2023-10-11-14_39_59](https://github.com/PrestaShop/PrestaShop/assets/87701789/21e7f7a6-a0b3-4710-8553-383ae0b6c4fe)

**Comment by florine2623** [comment]
Hello @Teidata 

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/30997 ?

**Comment by kmorgen** [comment]
> Hello @Teidata
> 
> Is your issue similar to #30997 ?

Yes, seem to be same issue so can be merged.

**Comment by florine2623** [comment]
I'm closing your issue in favor of https://github.com/PrestaShop/PrestaShop/issues/30997
Thanks !
