### ISSUE TITLE
ps_searchbar no drop-down menus or clicks possible

### ISSUE THREAD

**Issue by ValentiniVini** [PrestaShop/PrestaShop#34331]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,
often in a prestashop that I manage it happens that the ps_searchbar plugin does not work correctly the usual drop-down menu with product thumbnails (see attachment 1).
The drop-down menu does not appear on the Firefox or Edge browser.
On the Chrome browser the drop-down menu appears but it does not give the possibility to click on the products (clicking on the products displayed in the drop-down menu takes you nowhere).
By cleaning the browser cash, the drop-down menu starts working again for 2 or 3 searches, then the problem returns.
In a local copy of the same prestashop the problem does not arise. The most visible difference is that the local copy is updated to version 1.7.8.9, while the online version has recently been updated to version 1.7.8.10.
In another prestashop that I manage the problem does not arise, this site il updated to version 1.7.8.8. 
Maybe there are other differences that but I can't see it at the moment.
Has anyone already encountered this type of problem and could tell me a possible solution?

### Expected behavior

I expected the drop-down menu to work correctly as per the attached screenshot, but instead it seems to stop working after a few searches following cleaning the browser cash.

### Steps to reproduce

1 GO to https://catalogo.valentinivini.com
2 Log in with ut: allarme@valentinivini.com pass: allarme
3 Perform some searches in the search bar at the top right.
   For example, you can search for words: "soldati", "vaglie", "more", "nocino", "limin
![drop-down exemple](https://github.com/PrestaShop/PrestaShop/assets/141723106/27e758e7-df12-4736-bfd2-30cebdc1e217)

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.3.4

### If your bug is related to a module, specify its name and its version

ps_searchbar 2.1.3

### Your company or customer's name goes here (if applicable).

Valentini Vini & Liquori S.r.l.

**Comment by florine2623** [comment]
Hello @ValentiniVini ,

I have reproduced your issue on your shop. And on your shop only.
On the classic theme, I have no issue displaying the dropdown in different browsers and clicking on the search results.

Unfortunately, as this issue is not common to classic theme, I won't be able to help you.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
