### ISSUE TITLE
Add to cart modal translations

### ISSUE THREAD

**Issue by DavidFortuneFactory** [PrestaShop/PrestaShop#34404]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

2 add to cart strings do not translate: "products" & "shipping".

![image](https://github.com/PrestaShop/PrestaShop/assets/149175905/9b54c6e0-9a4c-4993-b818-e3b5a2c5e4de)

I tried to looking for this strings into:
BO > international > translations > front > Current theme > modules > ps_shoppingcart
BO > international > translations > front > Child theme > modules > ps_shoppingcart
BO > international > translations > front > Classic theme > modules > ps_shoppingcart
BO > international > translations > modules > ps_shoppingcart
Nothing to find there...

Also, I modified .tpl this following .tpl files, with the target to remove "total shipping" text line, is not necessary to show it in modal:
Current theme > modules > ps_shoppingcart > modal.tpl
Child theme > modules > ps_shoppingcart > modal.tpl
Classic theme > modules > ps_shoppingcart > modal.tpl

Removing lines 75 to 81
{if $cart.subtotals.shipping.value} <p><span>{l s='Shipping:' d='Shop.Theme.Checkout'}</span>&nbsp;<span class="shipping value">{$cart.subtotals.shipping.value} {hook h='displayCheckoutSubtotalDetails' subtotal=$cart.subtotals.shipping}</span></p>{/if}

![image](https://github.com/PrestaShop/PrestaShop/assets/149175905/44058c30-e24d-4316-b636-c7b5bc6b4790)

Clear cache.

Untranslated strings is still showing...

Any idea?

### Expected behavior

Find strings in BO > international > translations
or
Remove or translate it directly from .tpl

### Steps to reproduce

1. go to development site: https://prestashop.doosom.com/
2. add any product to cart.
3. modal popup add to cart appears showing the untranslated and unlocated strings.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_shoppingcart

**Comment by AureRita** [comment]
Hi @DavidFortuneFactory ,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

It seems that your issue is not a PrestaShop core bug but most likely a customization problem(with your theme or anything else).

As you can see : 

In spanish 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/37937fbb-33ba-4a1c-978d-7e8d314bde49)

in english (where I don't have the same wording than you)
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/a630504b-86c3-41f0-9f47-029d3ebfed16)


We will close this issue.

Thank you
