### ISSUE TITLE
ps_wirepayment

### ISSUE THREAD

**Issue by massimo222** [PrestaShop/PrestaShop#34555]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

we are using prestashop 8.1.2 but bank transfer payment doesn't work
I tried to activate debug but we have no errors
ps_wirepayment/validation

we deleted and added the plugin but it doesn't change the problem

![payment](https://github.com/PrestaShop/PrestaShop/assets/19530244/1fe9bf82-0109-491c-9f59-fc76816044c2)

### Steps to reproduce

the problem happens when payment by bank transfer is selected and the order is confirmed
but on the backoffice the order is not created

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.25

### If your bug is related to a module, specify its name and its version

ps_wirepayment

**Comment by massimo222** [comment]
I want to add that I also tried cash on delivery and we have the same error

**Comment by AureRita** [comment]
Hi @massimo222 

Thank you for your report, Dispite my effort, I can't reproduce your issue as you can see : 

[Untitled_ Nov 14, 2023 3_38 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/288284eb-6c7e-4faf-8c44-906252a73908)

Can you try it with the classic theme ? 

It's maybe because you don't setup the wirepayment as good as you need, you can [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Waiting for your feedback

**Comment by ShaiMagal** [comment]
This problem is not related to ps_wirepayment. Author have same troubles with other payment modules. I tested it now.
It's not PS bug. It is something specific for this instalation (any error there), clean PrestaShop without problems.
