### ISSUE TITLE
Product not added into 2nd store if using multistore

### ISSUE THREAD

**Issue by huyhoang8398** [PrestaShop/PrestaShop#34582]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm using multistore feature, and then go to add a new product, it shows in the 1st store but not the 2nd store

### Expected behavior

product show on both store 

### Steps to reproduce

1. Go to backoffice
2. Check if you are in All Shops mode
3. Go to Catalog -> Products
4. Add a new products

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @huyhoang8398 ,

Everytime you add a new product to your store, you need to choose which store you add your product to.

Here's the example in PS 8.1.0 :


https://github.com/PrestaShop/PrestaShop/assets/16019289/36fa75b8-6043-4a80-a5c6-8ad2ad3b8d06


You can upgrade your store in order to get the latest product page v2 feature.

I'm closing your issue to avoid clogging the backlog.
Thanks!
