### ISSUE TITLE
PScleaner not compatible with PS 8

### ISSUE THREAD

**Issue by borjagarciab** [PrestaShop/PrestaShop#34630]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Is not possible to execute PScleaner on > PS 8

### Expected behavior

Works.

### Steps to reproduce

1. Install module
2. Try to use any function.

### PrestaShop version(s) where the bug happened

> 8.0

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

pscleaner

**Comment by borjagarciab** [comment]
I have this commit on my own fork.
Is not possible to create new PR...
https://github.com/PrestaShop/pscleaner/commit/7f4750121a43750850db37f9463c3e633a4edec6 

Please check!

**Comment by matks** [comment]
The pscleaner repository has been archived by on Feb 1, 2021. It is now read-only and is not maintained anymore. We have decided to put it outside of the project perimeter of maintainance.

If you want to help making it better, continue working on your work 😉 and advertise it so that people can use it. This is how open source thrives!
