### ISSUE TITLE
Prices displayed without taxes when Set default country from browser language is enabled

### ISSUE THREAD

**Issue by ChillCode** [PrestaShop/PrestaShop#34636]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a user visits a site that have a group to display prices without taxes and have no cookies already set, PS will display prices without taxes even to visitors, but if the same page is reloaded (we have cookies) prices are shown as configured in the group.

### Expected behavior

Show prices as configured.

### Steps to reproduce

1. Install PS 1.7.8.10 in French
2. Add EN-US as a second language.
3. Add a new customer Group called B2B and set to show prices without taxes.
4. Go to International->Localization->Configuration and enable `Set default country from browser language`.
5. Open a Browser configured with EN-US as the default language.
6. Clean cookies or open a private session. [IMPORTANT]
7. Visit a product and note that prices are shown without taxes to a visitor.
 
![image](https://github.com/PrestaShop/PrestaShop/assets/9787055/0ce40ba5-6b69-466d-9fe8-9544165e752d)

8. Reload the page and prices are shown with taxes to the same visitor now PS is using cookies.

![image](https://github.com/PrestaShop/PrestaShop/assets/9787055/95a97df7-53ca-4e76-8549-8a7538c5eae5)

11. Do the same with a Browser with FR and both times prices are shown with taxes.

### PrestaShop version(s) where the bug happened

1.7.8.10

**Comment by florine2623** [comment]
Hello @ChillCode ,

I've tested with 8.1.x, I can't reproduce your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/9d9e1a75-3e78-4b46-a77e-43b2a616a96b

Am I missing something ?

**Comment by ChillCode** [comment]
Hi @florine2623 

Some time I'm bad at communication.

Just created a demo on prestashop.com, explore BO, added a B2B group without taxes and the rest is on the following video:

https://github.com/PrestaShop/PrestaShop/assets/9787055/d2b81602-2e1a-42c3-ac6c-569cc33c38ca

Thanks for testing.

**Comment by ChillCode** [comment]
After some digging, the issue resides on `FrontController` and affects all versions.

https://github.com/PrestaShop/PrestaShop/blob/95475a2d72238d2bf8586b452f1f6391157369ad/classes/controller/FrontController.php#L312-L316

`!$has_currency ` is blocking to set the context country from the browser when we already have a cookie, since it's always set, if we remove that check the prices always display without taxes on a browser with US and with taxes on a browser with FR.

Not sure which is the expected behavior but don't think should be this, since customers coming from search engines are getting a different price when reload.

Just disabled `Set default country from browser language` as a temp solution.

**Comment by ChillCode** [comment]
Now I thought to search for term has_currency  and found this:

https://github.com/PrestaShop/PrestaShop/pull/27903

**Comment by florine2623** [comment]
ping @PrestaShop/qa-functional can someone test this ? On my end, I can't reproduce it.

**Comment by ChillCode** [comment]
As we can see I did not login at any time, just removed cookies to show how a customer sees a product price when first visits a PrestaShop site with `Set default country from browser` enabled , and this issue is the culprit of many other issues related to addresses, taxes etc...

It's worth a watch.

**Comment by AureRita** [comment]
Hi @ChillCode 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(38).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/cbe4c59f-7009-4785-89d3-ad6350a0caa1)

[recording(39).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4e4c00e5-7eaa-49b9-9e5a-e649b8475b92)

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Maybe your issue is more related to the FR taxes and not for the taxes of the other country.

Because this one 'll appear only with the cookie, as you said it. And we can't reproduce it. We will close this issue. 

Thank you

**Comment by ChillCode** [comment]
Hi @AureRita 

Don't worry, at the end i care as much as you care, but in any of your videos you're following my steps, don't know why, but it is ok.

It is a core bug, a Frontcontroller issue,i even explained where the issue resides, so you don't have to tell what it is, really.

**Comment by ChillCode** [comment]
Hi  @AureRita 

If you came to visit the product from an external link and you never visited the site before you will never have a cookie so you will see the prices without taxes until you refresh.

I just followed and even quoted the code where the issue resides... and the check @Progi1984 added while ago that is preventing to get the correct country, so I can  tell you with all my short experience that there is an issue when `Set default country from browser` is enabled and if I follow all the steps to reproduce it I can, but the cookie must be deleted.

**Comment by metacreo** [comment]
@ChillCode hi
This is how it was intended, the function of determining the country by the browser header only works in the absence of context, once until the country appears. for example, you enter address1 and then cookies.

~~your bug is that when you exit, the group does not change? but after cookies clean all ok?~~
I reproduced this bug.

no B2B group is needed.
1. Set all default groups to display tax incl, set PS default country FR, browser locale en-US.
2. clean cookies and go directly to product page with configured price with FR taxes.
3. You will see price without taxes.
4. Refresh page and you will see other price with taxes.

the first time visitor always receives the price he receives based on the country in the context... who set by browser detection....
so... if detected en-US.. those taxes must be configured... or at all removed...
it all depends on the pricing policy in your country in relation to en-US 🙂

Do you think it’s worth removing the price dependence on browser locale determination?

**Comment by metacreo** [comment]
[Screencast from 11.01.2024 21:53:05.webm](https://github.com/PrestaShop/PrestaShop/assets/543458/22742bca-6db6-43ed-9a9d-640220eff039)

**Comment by metacreo** [comment]
@ChillCode tryed you #27903 ?

**Comment by ChillCode** [comment]
Hi @metacreo 

I spend few hours with this and already got paid for it, so i understood how all this works, and my customer, a senior dev understood also why some people complain for viewing prices without taxes.

I know we don't need the group, found it later, but also wanted to include the same settings as the site I was working on so it was sure to reproduce.

I just wanted to show you where to look, and you found the changes between 1.7.8 and 8, I knew before my post you would find it, and for me that is ok, that site just set geolocation and that disabled the browser thingy.

Nice you found has_address_type thingy.

**Comment by ChillCode** [comment]
> @ChillCode hi This is how it was intended, the function of determining the country by the browser header only works in the absence of context, once until the country appears. for example, you enter address1 and then cookies.
> 
> ~your bug is that when you exit, the group does not change? but after cookies clean all ok?~ I reproduced this bug.
> 
> no B2B group is needed.
> 
> 1. Set all default groups to display tax incl, set PS default country FR, browser locale en-US.
> 2. clean cookies and go directly to product page with configured price with FR taxes.
> 3. You will see price without taxes.
> 4. Refresh page and you will see other price with taxes.
> 
> the first time visitor always receives the price he receives based on the country in the context... who set by browser detection.... so... if detected en-US.. those taxes must be configured... or at all removed... it all depends on the pricing policy in your country in relation to en-US 🙂
> 
> Do you think it’s worth removing the price dependence on browser locale determination?

Also forgot to mention (was working with this a month ago) on your address issue that you will have different result if the cart is initialized or not, so if you don't have cookies, and go directly to your profile without initializing the cart  you'll not have a different country...

As stated, it's worth a watch.

**Comment by metacreo** [comment]
@ChillCode hello, I think this issue #34636 and PR #27903 must be re-opened.
The code construction of PR #27903 is better and more adapted for browser detection function.

In #27903 only this part code confuses me ` : (int) Configuration::get('PS_CURRENCY_DEFAULT'))->id`
Better to leave original ` : Currency::getDefaultCurrencyId())->id;`
I don't think it's need mixing $has_address_type ($cart) with this issue. 

Indeed, I agree that now it does not work logically and all because of the closure of normal PRs and the inability to repeat bugs. At the same moment, they accept the unfinished PR. All this violates the logic... This is nice work of the 🙄...

Bugs #34636 #34080 #33991 come from accepted unfinished #27187 which violated part of controllers logic. Now we are trying to finish it.

I tested #27903 This is a great addition to #27187

**Comment by metacreo** [comment]
Dears @florine2623 and @AureRita can you please re-open issue #34636 and PR #27903 ? Or we must create new?
Because mentioned #27187 not solve this problem.
