### ISSUE TITLE
personalization fields do not stay in the correct order or disappear

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#34718]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I created 7 personalization fields in a product. And after saving one field disappeared and the others are not in the right order.

![personnalisation bo -after register](https://github.com/PrestaShop/PrestaShop/assets/61431435/84337243-170e-42eb-9164-c4c635430c01)
![personnalisation FO -after register](https://github.com/PrestaShop/PrestaShop/assets/61431435/57d0d8bd-b070-4dfe-b33f-57601accf2df)
![personnalisation bo -before register](https://github.com/PrestaShop/PrestaShop/assets/61431435/74ea41ad-e902-4b95-9ab3-e2293762eb52)

### Expected behavior

when we create several personalization fields we expect that all the fields are present in the front office and in the same order

### Steps to reproduce

in product page (BO)
go to Option
Go to personalization
add some personalizations (7/8)
register
display in front office

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @ECC64 ,

I can't reproduce your issue with theme classic and hummingbird in PS 8.1.x and develop.

<img width="1169" alt="Screenshot 2023-11-29 at 10 26 36" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/63960490-8f9a-4393-aae7-317409b4d6d8">

<img width="558" alt="Screenshot 2023-11-29 at 10 26 29" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/97e8e8d5-19ed-48c1-8f3a-b3fb7de3508f">

<img width="534" alt="Screenshot 2023-11-29 at 10 27 24" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/577d0c4d-ac8a-4fd7-b751-3f06f58fa691">


You should contact the developer of your template directly in order to get it fixed.
