### ISSUE TITLE
PPV2 - In specific price, cannot delete a customer

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34748]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If a create a specific price in PPV2, I cannot deleted a specific customer that I'm applying the specific price to.

First reported here :
https://github.com/PrestaShop/PrestaShop/pull/34699#pullrequestreview-1759363859

### Expected behavior

I should be able to deleted my customer like I was able to do in Old Product Page.

### Steps to reproduce

1. Install PR https://github.com/PrestaShop/PrestaShop/pull/34699 or branch 8.1.x if PR is merged
2. Go to BO > Product > Edit a product
3. Pricing tab > Add a specific Price
4. Disable Apply to all customer
5. Choose customer John Doe
6. Try to delete the customer to choose another one, you can't :x:

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @florine2623 ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.x, as you can see 

[Untitled_ Dec 5 2023 3_20 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/de1b8022-fd8b-4e60-b948-435c3275db9c)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by jolelievre** [comment]
Hi regarding this issue,
I don't think it is a bug, or at least it was done this way on purpose

You don't have the cross button to remove the customer but you can still search for another customer to replace the existing one, the fact that the selected customer cannot be removed is on purpose When you uncheck `Apply to all customers` you MUST select exactly one customer instead, that's why the remove button is not there because it shouldn't be removed only replaced

Now maybe the UX is not intuitive enough and needs to be improved, maybe some feedback from @PrestaShop/ux-team  could be interesting in this case, like should we indeed add the remove button, if we click on it does it only remove the selected customer or does it also forces `Apply to all customers` to true?

Here's a video showing how the customer can be replaced already:
[Products • Prestashop 81.webm](https://github.com/user-attachments/assets/9564e0af-ace6-4e31-947d-7cd4386599ad)

**Comment by florine2623** [comment]
Closing this issue as it is not a bug !
