### ISSUE TITLE
order of personalization fields product sheet

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#34837]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I created products on a PS 8.1.2 with 7 personalization fields with a precise order.
and when I go to the front office the fields are not in the same order
![perso](https://github.com/PrestaShop/PrestaShop/assets/61431435/1a0a2243-ae79-4528-a88e-bd8dd13f28e5)

### Expected behavior

when we create personalization fields in the back office, we expect them to appear in the same order in the front office

### Steps to reproduce

Create product
insert personalization fields (7 for my website)
If we don't like the final result, we remove or modify some of them.
back office fields are not in the same order as front office

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @ECC64 ,

I can't reproduce your issue :

<img width="558" alt="Screenshot 2023-12-18 at 11 23 53" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/52cce6e4-cfd8-4249-bfe3-ee755ad7c83d">
<img width="1182" alt="Screenshot 2023-12-18 at 11 23 58" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/52ba50c7-d75d-4bac-ab09-226a6d7d087b">

The issue comes from your template.
You can contact the developer of the theme directly.
