### ISSUE TITLE
Adapt the command Order status for the API access 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34830]
id_employee | order_history |

#### Specs

- create the endpoint:
/orders/{orderId}/update-status
/orders/bulk-update-status

- Adapt the command to be able to save API access and associated to the API ID
  - BulkChangeOrderStatusCommand
  - UpdateOrderStatusCommand

- Add the new column in table order_history to store the ID API access 

- Adapt the page to display the API access name if the status is updated by the API.

#### Acceptance 

When an API access updates the order status 
Then the API access name is displayed on the order page in the order status history next to the new order status

**Comment by Hlavtox** [comment]
@kpodemski @ShaiMagal Is this really needed to add new column to order_history table? (https://github.com/PrestaShop/PrestaShop/pull/35292)
 This way there could be another column in all other tables, tracking who changed what.

I think a log system should be a place for such information, not data tables.

**Comment by kpodemski** [comment]
I asked @jolelievre about logs some time ago, I never would have thought about polluting core tables with such an extra columns only for the sake of logging employee/API operations. I don't like this idea. I would prefer having central logs mechanism allowing to filter the logs and have a better overview.

**Comment by kpodemski** [comment]
My other doubts:
- it may not be consistent for third party solutions, we don't set any framework really - we could log based on the input and do our best to process the data for logs
- it will complicates upgrade (will have to approach upgrades differently because adding new field on bigger tables could be slow)
- we can see in the PR how much work was needed to introduce this, now imagine having a standarized code for CQRS layer handling logging based on the input, especially since we use SF Messenger which makes things easier

**Comment by Hlavtox** [comment]
We could just create some abstract command handler or trait that every command handler will inherit from. In that, there would be logging mechanism.

Some switch in the command or handler, if we want to log it and in what format and we are golden.
