### ISSUE TITLE
[autoupgrade] Action `upgradeModules` is not upgrading modules on command line

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#34860]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

We built a custom CI/CD pipeline to deploy our PrestaShop projects and for this we use the [`autoupgrade`](https://github.com/PrestaShop/autoupgrade) module to upgrade our project during deployment.

### Expected behavior

Our project may contains some custom modules shipped at the same time, and we execute the following command:
```
php modules/autoupgrade/cli-upgrade.php --dir=admin-path --channel=private --action=upgradeModules
```

We expect that command to upgrade all modules requiring an upgrade (= when the version of the module save in the database is different from the actual version of the module).
But it looks like no module update happens and we still need to manually update our modules from the admin panel.

### Steps to reproduce

1. install prestashop
2. install a module version 1.0.0
3. change the module version to 1.0.1 by modifying th module code
4. run command line `php modules/autoupgrade/cli-upgrade.php --dir=admin-path --channel=private --action=upgradeModules`
5. See that the module has not been updated

### PrestaShop version(s) where the bug happened

8.1.2

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.0

**Comment by AureRita** [comment]
Hi @Seb33300 

Thank for your report, Depsite my effort, I can't reproduce your issue as you can see : 

[recording(13).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/1673b29b-3102-42bf-8144-f2e7cc2e6a22)

This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by Seb33300** [comment]
@AureRita the command line has to be executed from the project root directory.
And you need to replace `admin-path` by the name of your admin folder ("admin-dev" in your case)

(In your video the command fails because you did not replace "admin-path" by the name of your admin folder)

So, here is the comment you need to run:
```
php modules/autoupgrade/cli-upgrade.php --dir=admin-dev --channel=private --action=upgradeModules
```

**Comment by Quetzacoalt91** [comment]
Hi @Seb33300,

Indeed, the list of modules to upgrade is generated before the core upgrade process is started because it relies on files that are removed in the middle of the upgrade process.

We will rework the management of module upgrades in the context of a core upgrade. As a workaround in the meantime, you may loop on your modules folder, and for each folder run the following command to upgrade them one module at a time:

```
php bin/console prestashop:module install [module_name]
```

One advantage of this command is the ability to use more sources to get your upgrades. While the autoupgrade module is only able to get from `addons.prestashop.com`, the command above will also get upgrade for the OS API if the [ps_distributionapiclient module](https://github.com/PrestaShop/ps_distributionapiclient) is installed.

https://devdocs.prestashop-project.org/8/modules/testing/resources/#basic-actions
