### ISSUE TITLE
ps_facetedsearch - When an attribute value is deleted, it is still displayed even after rebuilding the index

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35331]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After deleting an attribute and rebuilding the index from the faceted search module, I still see the deleted item on the FO. I tried clearing the cache from  ps_facetedsearch module, from PS and from the browser. The item is still displayed and I can select it. I will see the page loading without result.

https://github.com/PrestaShop/PrestaShop/assets/16019289/08ad7b54-ef44-4aa6-b84e-2a32733b533f

Related to https://github.com/PrestaShop/ps_facetedsearch/pull/979/

### Expected behavior

The deleted attribute should not be displayed in the FO

### Steps to reproduce

1. Create an attribute group + some attribute values
2. Create a combination product with these attributes
3. Go to faceted_search module > Enable attribute group > Build attributes and features indexed
4. Go to FO > Filter by the attribute
5. Go to BO > Delete one attribute value > Configure faceted_search > Rebuild the index
6. Go to FO > See that the attribute value is still displayed and the page loads with no filter :x:

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_facetedsearch

**Comment by jolelievre** [comment]
Hi @florine2623 

I tested the bug and I think it's actually a "feature" even if it's poorly made Actually you also need to click on `Clear the cache` and then everything is ok I only tested on develop branch but I’m almost sure it’s the same thing with older versions because it's the principle of the module that stores some data in DB to optimize the FO display I guess

That's why even if the attribute is removed it can still display its name, even though it's not in the core tables anymore, but in the module cache in DB there are some generated JSON content that still contains the old attribute data, you need to clear the cache to update them

**Comment by florine2623** [comment]
(info for @PrestaShop/qa-functional )

Tested with `8.0.x`, `8.1.x`, works OK ✅ 

On `develop`, the following bug is fixed by https://github.com/PrestaShop/ps_facetedsearch/pull/983 :

https://github.com/PrestaShop/PrestaShop/assets/16019289/5e59eb81-50ee-45e4-a175-5da4f710c21a
