### ISSUE TITLE
AdminSearch external index cron URL is no longer reachable when unlogged

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#35359]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the back office go to Shop Parameters > Search
Here you'll see information explaining how to setup an cron based on a callable URL:
![Capture d’écran 2024-02-14 à 16 17 41](https://github.com/PrestaShop/PrestaShop/assets/13801017/0ef1d735-a9e0-4e70-87bc-33fe5726e65d)

This URL should therefore be callable even when you are not logged in to your back office, it can be tested by using a browser with private navigation as well.

With the Symfony layout enabled this URL is no longer callable and is redirected to the login page.

https://github.com/PrestaShop/PrestaShop/assets/16019289/1188f503-56f5-4056-8ed4-6fe266d8447b

### Expected behavior

I should be able to call the search indexation URL even if I'm not logged in (it works with legacy layout but not with Symfony layout). We need to find either a solution to make it work as is with Symfony layout or at least to find how the controller could be adapted to skip the global token validation and handle its own internal validation separately.

- [ ] Investigate to find a clean fix and without impacting the modules ecosystem

### Steps to reproduce

1. Make sure the Symfony layout is enabled in feature flags
2. Go to Shop Parameters > Search
3. Copy the search indexation URL and call it in a browser with private navigation (or any other way to call it without being logged in to the back office)
4. The URL should be callable, no redirection to the login page, a white content should appear since the controller returns no content but the call should be a success 200

### PrestaShop version(s) where the bug happened

9.0

**Comment by boherm** [comment]
After some research on this issue, I've find why we have this bug.

To summary, when we have the Symfony Layout enabled all requests are processed by Symfony.

This kind of url (http://ps-develop.test/admin-dev/index.php?controller=AdminSearch&action=searchCron&ajax=1&full=1&token=yjNTcaUs&id_shop=1) can't work properly first of all because of the `TokenizedUrlsListener.php` and the token in the url that can't be a valid one. But, if we find a solution for this token, we pass the request to the `LegacyController.php` but this one await a legacy admin controller with a `displayAjax` function in it, but we process indexation on the `postProcess`. Because of this, the indexation canno't be done.

So we have two solutions to resolve this issue:
- 1) Find a solution for the token and for the LegacyController, but this could be a pain to keep a good security!
- 2) Migrate into Symfony this feature.

**Comment by MatShir** [comment]
Migrating everything to a SF feature doesn't solve the problem for modules 
How to configure and detect that certain controllers should not be validated by the token? 
Post-process is called on the init but doesn't seem to be well executed. 
Linked to https://github.com/PrestaShop/ps_facetedsearch/pull/983/files
