### ISSUE TITLE
Problem with product cost prices

### ISSUE THREAD

**Issue by angeldavo** [PrestaShop/PrestaShop#35405]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I have a problem with a prestashop.

The customer insert the cost price with decimals, but when some time passes (we do not know days or weeks) the price is automatically rounded by itself.

What can be happening?

### Expected behavior

The price should be kept to decimal places, otherwise the profit statistics are not real.

### Steps to reproduce

Insert price with decimals and wait (days or weeks). We do not know the estimated time.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4.33

**Comment by AureRita** [comment]
Hi @angeldavo 

Thank you for your report, Currenlty your issue seems to be a rounded issue,to see this modification quickly, I recommand you to disable you cache 
(1. Go to BO > Advanced Parameters > Performance 
2. Disable cache, 
3. Save
4. Clic on cleat cache ) 

Moreover, you can see your rounded mode on BO > Shop Parameters > General 

Let me know if this information help you and if you keep this "new issue" 

Waiting for your feedback

**Comment by florine2623** [comment]
Hello,

Since we had no news from you for, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
