### ISSUE TITLE
Symfony Layout with the nightly docker image doesn't work

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#35487]
**Issue encounter**
I have not yet discovered the reason behind the loop redirect issue when accessing the BO. This problem seems to be present in the Docker version of PrestaShop from a Nightly image when the Symphony Layout is enabled.

**Expected behavior**
Nightly docker image should work with the Symphony Layout enabled.

**Acceptance test**
Docker nightly should work

**Comment by M0rgan01** [comment]
Infinite redirection is here https://github.com/PrestaShop/PrestaShop/blob/380afb5114ae7c77e992aba8d41f1183d8190a98/src/PrestaShopBundle/Security/SslMiddleware.php#L97

**Comment by M0rgan01** [comment]
Ticket paused, the source of the problem must be determined.

In summary, currently an infinite redirection is present on v9 of Prestashop. This is due to SslMiddleware, which was ~~added~~ **updated** in the PR https://github.com/PrestaShop/PrestaShop/pull/30565.

The error scenario: if Symfony determines that the request is insecure, and the `PS_SSL_ENABLED` environment variable is `true`, then we redirect to https.

An element to take into account is that in general the application is behind a secure reverse proxy, which uses port 80 of Prestashop, and therefore uses an unsecured request internally.

**Comment by MatShir** [comment]
Todo:

- [x] Investigate if we still need SSL enabled, and if not, consider deprecating it and base the configuration on SSL everywhere. 
- [x] Compare the old functions with isSecure from SF to be sure of the diff.
- [x] Detect in the header the loop redirections to through 404 errors (check if it is a config issue, it seems SF have the feature)
- [ ] Then Split the configuration: SSL everywhere with redirects SSL in the config (true by default)


help: if reverse proxy blabla recommned to disble it.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35761
