### ISSUE TITLE
Missing root hook in hook.xml

### ISSUE THREAD

**Issue by manudas** [PrestaShop/PrestaShop#35545]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is a hook that is getting run before a Swift message is sent in Mail.php send static class method. The name of the hook is actionMailAlterMessageBeforeSend. After inspecting ps_hook table and then hook.xml installation file, I realised this hook is not there even though it is in the Mail class.
For this I have created the following PR:

https://github.com/PrestaShop/PrestaShop/pull/35544
Please have a look and let me know if you need anything else from me
Best

### Expected behavior

When you create and install a module with the method hookActionMailAlterMessageBeforeSend, you expect the body of this function to be run  when you are sending an email with prestashop, for instance, in the Order page while sending an email with the updates to the customer

### Steps to reproduce

1,Create a simple module with a method hookActionMailAlterMessageBeforeSend
2.In the body method write something like:
die('mehod reached');
3.Install the module
4.Go to a customer order, or create a new testing order
5.Change the order status or send an email to the customer throughout this form
The body of the method (die), is not executed and therefore it works without dying as it should have done

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @manudas 

Thank you for your report.

Can you give us a module to test your exemple because currently we can't create the module. (in our module Qualityassurance, we can't have the hook "actionMailAlterMessageBeforeSend", I think it's related to your issue). Moreover, I check it in the hook.php and didn't see it. 

@PrestaShop/product-council is it a hook that we want to have ? 

Waiting for feedback

**Comment by kpodemski** [comment]
Hello @manudas 

While your report seems legit because the hook should exist in the hook.xml, it doesn't mean it doesn't work because it is not there.

Please find attached module, I tested it and it correctly dumps content of `$params['message']` when I'm updating order state.

[kptestemailhook.zip](https://github.com/PrestaShop/PrestaShop/files/14493432/kptestemailhook.zip)

![image](https://github.com/PrestaShop/PrestaShop/assets/2137763/7842d7d1-93ef-41a9-90e6-b25a4ee01bf5)
