### ISSUE TITLE
Check all product are still active to set orderable cart

### ISSUE THREAD

**Issue by csoon1992** [PrestaShop/PrestaShop#35634]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

a user adds product X to the cart on February 10th but leaves the store before completing the order. Two days later, they return to the store and still find their product in the cart. Upon accessing the cart page, they encounter an error message stating "Product X is no longer available." However, if the user directly accesses the checkout URL without visiting the cart page first, they can proceed to finalize the order without any validation of product availability in the cart.

### Expected behavior

Upon clicking the "Finalize Order" button, it should be verified that all products are still active to prevent a user from purchasing deactivated products.

### Steps to reproduce

1. Add a product to the cart.
2. Go to the checkout page.
3. Disable the product from the backoffice.
4. Come back to the checkout page. Click the "Finish order" button. The order will be finished instead of show a message notifying "Product is not available".
5. After my pull request changes, this problem has been fixed.

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.0

### Your company or customer's name goes here (if applicable).

csoon1992

**Comment by AureRita** [comment]
Hi @csoon1992, 

Thank you for your issues, Despite my effort, I can't reproduce your issue as you can see : 

[recording(138).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/67c0b8a0-60f7-4a50-b1d1-b9a65e530ff6)

Did I miss something ? 

Currently, I have to reproduce your issue on 8.1.x because it's the version that'll be up to date ( the version 8.0.x 'll be up to date if there is some security issue ) 

Moreover, you issue seems to be the same that this one https://github.com/PrestaShop/PrestaShop/issues/10762, What did you think ? 

You can see that this PR should be correct the issue : https://github.com/PrestaShop/PrestaShop/pull/26048

Waiting for feedback

**Comment by Hlavtox** [comment]
@AureRita This is already fixed on 8.1. :-)

**Comment by AureRita** [comment]
@Hlavtox That what I think, but I leave it to the contributors to inform me if this is indeed another issue. 

but thank you for the answer and the PR
