### ISSUE TITLE
Cumulative coupons use the base price but not the discounted price.

### ISSUE THREAD

**Issue by Touxten** [PrestaShop/PrestaShop#35696]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Cumulative coupons use the base price but not the discounted price.  

### Expected behavior

I have two 10% discount coupons and the PrestaShop calculation is :

First coupon = 100-10%  = 10€
Second Coupon = 100-10% = 10€

The total of the cart is 80€  

Expected behavior

First coupon = 100-10%  = 10€
Second Coupon = 90-10% = 9€

The total of the cart is 81€  

### Steps to reproduce

Description above

### PrestaShop version(s) where the bug happened

1.7.8 8.1

### Your company or customer's name goes here (if applicable).

Friend Of Presta

**Comment by AureRita** [comment]
Hi @Touxten 

Thank you for your report, currently I think this one is not an issue but an expected behavior. Indeed, if you have two separate coupon, one with 20% and one with 10%, with your request, we have to put the 20% in first place to have more discount. so the coupon is all on the base total. 

@PrestaShop/product-council What did you think about this issue ? 

Waiting for feedback

**Comment by Touxten** [comment]
Hi @AureRita 

I have two 10% discount coupons

Not one for 10 and one for 20

**Comment by florine2623** [comment]
Hello,

On PS 8.2.0, the behavior is as expected.

<img width="1121" alt="Screenshot 2024-10-10 at 14 21 41" src="https://github.com/user-attachments/assets/59737c1a-dc99-48d9-8569-a4596cb0b593">

Thanks!
