### ISSUE TITLE
Upgrade PS from 8.1.3 to 8.1.5 does not work - MD5 sum does not match

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#35720]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

Upgrade Prestashop from 8.1.3 to 8.1.5 does not work - MD5 sum does not match.

I tried check autoupgrade folder permissions (755) and reset module - result: does not works too. After reset module I only lose previous backups (ROLLBACK) and setting. 

Thank you

BR
Petr

**Here is log:**
Analyzing the situation...Shop deactivated. Now downloading... (this can take a while)
Download complete but MD5 sum does not match (d41d8cd98f00b204e9800998ecf8427e). Operation aborted.

Starting upgrade...
Downloaded archive will come from https://github.com/PrestaShop/PrestaShop/releases/download/8.1.5/prestashop_8.1.5.zip
MD5 hash will be checked against f0c1fe954d9dceb205bf172cbc00a195
Downloading from https://github.com/PrestaShop/PrestaShop/releases/download/8.1.5/prestashop_8.1.5.zip
File will be saved in /home/www/domain.cz/www/test.domain.cz/Admin/autoupgrade/download/prestashop.zip
Download directory has been emptied
[INTERNAL] /home/www/domain.cz/www/test.domain.cz/modules/autoupgrade/classes/Tools14.php line 305 - fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[INTERNAL] /home/www/domain.cz/www/test.domain.cz/modules/autoupgrade/classes/Tools14.php line 305 - fopen(): Failed to enable crypto
[INTERNAL] /home/www/domain.cz/www/test.domain.cz/modules/autoupgrade/classes/Tools14.php line 305 - fopen(https://github.com/PrestaShop/PrestaShop/releases/download/8.1.5/prestashop_8.1.5.zip): failed to open stream: operation failed
[INTERNAL] /home/www/domain.cz/www/test.domain.cz/modules/autoupgrade/classes/Tools14.php line 308 - fclose() expects parameter 1 to be resource, bool given

----
PHP: 7.4.33
MySQL: 10.1.48-MariaDB-0+deb9u2
1-Click Upgrade - v5.0.1

### Expected behavior

Working without a problem as before.

### Steps to reproduce

Standard 1-Click Upgrade process.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

PHP: 7.4.33

### If your bug is related to a module, specify its name and its version

1-Click Upgrade - v5.0.1

**Comment by matks** [comment]
Hello @PeNov I just verified the md5 of https://github.com/PrestaShop/PrestaShop/releases/download/8.1.5/prestashop_8.1.5.zip and it is f0c1fe954d9dceb205bf172cbc00a195 as indicated in https://api.prestashop.com/xml/channel.xml

I think maybe the problem is your SSL configuration because I can see some SSL related errors. Maybe because of a SSL issue, your prestashop cannot download correctly file https://github.com/PrestaShop/PrestaShop/releases/download/8.1.5/prestashop_8.1.5.zip so as the ZIP is not correctly downloaded, then its MD5 cannot be computed without errors?

The other possibility is that a temporary SSL issue happened on https://github.com causing the same behavior I mentioned. Maybe you can try again?

**Comment by AureRita** [comment]
Hi @PeNov 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(151).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/edda4730-ab74-46a9-88be-ed64dece8f21)

Did I miss something ? 

What type of upgrade did you use ? (minor release, major release, etc ...) 

As @matks mentioned it, can you check if it's not because of your environment ? 

Waiting for feedback

**Comment by PeNov** [comment]
Hello,

I tested upgrade again.

With Minor release – I have same MD5 error.
With Major release – I have same MD5 error.

I have not any problem in the lasted upgrades and 1-click upgrade module version 5.0.0. I will ask hosting provider if something was changed.

Thank you.
Best regards
Petr

**Comment by PeNov** [comment]
Hello,

Sorry for the unnecessary bug report.

The cause of the problem was the missing root certificate of the certificate authority that issued the github.com domain certificate.

Please close the bug report.

Thank you.
Best regards
Petr

**Comment by SimplyButter1** [comment]
> Hello,
> 
> Sorry for the unnecessary bug report.
> 
> The cause of the problem was the missing root certificate of the certificate authority that issued the github.com domain certificate.
> 
> Please close the bug report.
> 
> Thank you. Best regards Petr

Hi,

Do you mind sharing exactly what you did to solve this problem? Was it something specific you asked your hosting provider and that they had to fix?

Thank you

**Comment by AureRita** [comment]
Hi @PeNov 

We are greeting that you find the solution of your issue, because you don't have it, I'll close the issue 

Thank you

**Comment by Giorgiomezzo** [comment]
hello,
how did you solved it .
I have the same problem.
prestashop 8.1.3

**Comment by Giorgiomezzo** [comment]
> Hello,
> 
> Sorry for the unnecessary bug report.
> 
> The cause of the problem was the missing root certificate of the certificate authority that issued the github.com domain certificate.
> 
> Please close the bug report.
> 
> Thank you. Best regards Petr

hello ,
how did you solved it ? 
please guide me .
i have the same problem.
prestashop 8.1.3

**Comment by LIJE** [comment]
Same here

**Comment by kellian84** [comment]
Hello, could you detail your solution? Because the issue is still present.
Thanks
