### ISSUE TITLE
Problem with meta information on CMS pages. No meta title, meta description.

### ISSUE THREAD

**Issue by Rus-Design** [PrestaShop/PrestaShop#35763]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Скриншот 28-03-2024 032525](https://github.com/PrestaShop/PrestaShop/assets/63929772/d3a64e43-40ac-4da4-94c8-c063491a7fbb)
![Скриншот 28-03-2024 032551](https://github.com/PrestaShop/PrestaShop/assets/63929772/c2ffd661-9e98-4258-aa79-70eeddd37c40)

### Steps to reproduce

1. create cms page with meta title and meta description.
2. go to the new cms page.

### PrestaShop version(s) where the bug happened

8.1.5

**Comment by fenner2689** [comment]
I can confirm that it is an issue with brand pages also, both meta title and meta description

**Comment by gianluca77** [comment]
Pay attention to the fact that if you have a long text on description field it does NOT save anything at all due to the format text warning-->public const LIMIT_TEXT_UTF8 = 21844; it means that the text is too long in the description field. The bug is that it is not a TEXT but a LONG TEXT the description field in mysql and so it must be corrected in the cms page editor!
Temporary solution is to change the LIMIT_TEXT_UTF8 = 218448; in FormattedTextareaType file increasing it.

**Comment by max06200** [comment]
Could you tell me where the file to modify is located? 
because it is no longer possible from the Prestashop backoffice with version 8. 
There is only the short_description

Tank's
