### ISSUE TITLE
Email template access is forbidden in bo

### ISSUE THREAD

**Issue by KodeToad** [PrestaShop/PrestaShop#35781]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This bug has been reported before #17759 and is not fixed in 8.1.5.
The .htaccess file [in this directory 'mails/.htaccess'](https://github.com/PrestaShop/PrestaShop/blob/develop/mails/.htaccess) restricts access so email templates cannot be previewed

### Expected behavior

Ability to preview email templates for order status changes

### Steps to reproduce

Sign in to bo. Go to "Shop Parameters" -> "Order Settings" -> "Statuses" tab.
Edit a status with "Send email to customer" set and try to preview that status' email template.
Result 403 Forbidden

Work around: remove the .htaccess file from https://github.com/PrestaShop/PrestaShop/blob/develop/mails/.htaccess
Suggested permanent fix would be to move that directory to the administration directory and remove the .htaccess file

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

7.4.33

**Comment by Prestaworks** [comment]
I think the proper fix would be to add a controller that reads and display the content of the selected html file.

**Comment by AureRita** [comment]
Hi @KodeToad 

Thank you for your report, I reproduce your issue on 8.1.x as we can see here : 

[recording(167).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/eb5a75a8-2c14-4b69-ab7f-0d0294c1fcbc)

But, if we enabled the experimental feature on the order state like it : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/260b7e68-4934-4ef4-9c1b-afbcb8cadfb5)

We can check the email as you can see : 

[recording(168).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/1c9522eb-e94f-4177-958c-b7f2325b57a5)

So, I considere that your issue is already corrected but it's for the new feature that'll be implemented on prestashop 

Thank you

**Comment by Prestaworks** [comment]
I can confirm that this works in the experimental page.
