### ISSUE TITLE
Autoupgrade - When you do an upgrade to 9.0.0, you can't go on stock page 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#35879]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you do an upgrade from 8.1.5 or 8.0.5 to 9.0.0, if you go on stock page, you'll have an error 500 as you can see : 

[recording(181).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/d162a255-c965-48c4-8d59-c874e5b7d23a)

### Expected behavior

I expect to go on the stock page 

### Steps to reproduce

1. Install a fresh install of 8.1.5 (or 8.0.5)
2. Install autoupgrade from dev branch 
3. Go on autoupgrade 
4. Do an upgrade to 9.0.0 
5. Go on the new BO 
6. Go on Stock :negative_squared_cross_mark: 

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1 from dev branch 

### Your company or customer's name goes here (if applicable).

PS

**Comment by paulnoelcholot** [comment]
FYI @AureRita :trollface:

**Comment by florine2623** [comment]
Hello @AureRita ,

I couldn't install autoupgrade from dev branch, I had to use branch 680.

With branch `develop` I have this error : 
<img width="1440" alt="Screenshot 2024-04-12 at 10 59 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5346b6b5-cb4f-4414-9107-54b2b5610a78">

I have reproduced your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/ae8043a0-3dbd-42f5-b38b-23c1881ec79b

<img width="1077" alt="Screenshot 2024-04-12 at 11 08 40" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/29868733-e25f-44f2-8816-77a4a28c67d1">

**Comment by Quetzacoalt91** [comment]
This is caused by a duplicated of the class name 'AdminStockManagement' in the tab table.

```sql
SELECT class_name, count(class_name) FROM ps_tab group by class_name HAVING count(class_name) > 1;

# class_name, count(class_name)
'AdminStockManagement', '2'

```

This controller was referenced two times in the tab.xml file in 8.1.x:
* https://github.com/PrestaShop/PrestaShop/blob/607b567270b931e3492f8036e4d2e1817b5bfcbc/install-dev/data/xml/tab.xml#L137-L141
* https://github.com/PrestaShop/PrestaShop/blob/607b567270b931e3492f8036e4d2e1817b5bfcbc/install-dev/data/xml/tab.xml#L214-L218

**Comment by Quetzacoalt91** [comment]
This specific error can be fixed with https://github.com/PrestaShop/autoupgrade/pull/698, but I'm pretty sure similar errors will happen on production shops if a controller has been registered at several places as the Stock page used to be.

@jolelievre I saw you created the method `getIdByClassName` in https://github.com/PrestaShop/PrestaShop/pull/33158. If you expect a Controller to be listed only one time, don't you think a key with UNIQUE contraint should be added?
