### ISSUE TITLE
Issue with Wishlist block plugin for prestashop

### ISSUE THREAD

**Issue by Devorosrl** [PrestaShop/PrestaShop#35894]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning, the following plugin is not working properly. When a user who is not logged in on our ecommerce tries to enter the product within the wishlist , the system shows the alert asking to log in. However, the page crashes and the user can no longer perform actions.

![issue wishlist](https://github.com/PrestaShop/PrestaShop/assets/166703632/14f8dd2a-7bda-4812-85e6-4ce8a076cf85)

### Expected behavior

We expect that the moment the user receives the error message, they can close the pop-up window and operate normally on the platform.

### Steps to reproduce

- go to devoro.shop
- go in the product section: https://devoro.shop/it/83-prodotti
-  add a product in the wishlist
- the error pop up will appear and no more action can be performed

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.25

### If your bug is related to a module, specify its name and its version

Wishlist block

### Your company or customer's name goes here (if applicable).

Devoro srl

**Comment by florine2623** [comment]
Hello @Devorosrl ,

I can't reproduce your issue on PS 8.1.x and blockwishlist v3.0.1 as you can see from my screen record :

https://github.com/PrestaShop/PrestaShop/assets/16019289/674774f7-d0c0-4ccd-8ebb-6761eb0ace77

It seems like your issue comes from your theme.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
