### ISSUE TITLE
throw new InvalidArgumentException('Invalid category parameter');  I get an error message when I use a sitemap generator.

### ISSUE THREAD

**Issue by thomveen** [PrestaShop/PrestaShop#36120]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

throw new InvalidArgumentException('Invalid category parameter');

I get an error message when I use a sitemap generator.

PrestaShop 8 

<img width="1261" alt="Scherm­afbeelding 2024-05-09 om 10 59 47" src="https://github.com/PrestaShop/PrestaShop/assets/70706635/48c8dfcf-cb44-470b-990d-ec9cb28a0f18">

### Expected behavior

throw new InvalidArgumentException('Invalid category parameter');

### Steps to reproduce

Got to SITEMAP google

Generate Sitemap

throw new InvalidArgumentException('Invalid category parameter');

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.27

### Your company or customer's name goes here (if applicable).

SmarThuis

**Comment by Hlavtox** [comment]
@thomveen Something is wrong with your install. 👍

**Comment by florine2623** [comment]
Hello @thomveen ,

I can't reproduce your issue. I'm using module gsitemap v4.4.0.

https://github.com/PrestaShop/PrestaShop/assets/16019289/56e4ecf1-c9d2-4676-b92a-d603c2afc3cf

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by compsoul** [comment]
It seems the issue appears when a category has no language record in ps_category_lang for the language currently being processed.  As a result, the module’s getCategoryLink() (from gsitemap) tries to work with an unloaded Category objec but still accesses its properties instead of validating it first.

This leads to an InvalidArgumentException thrown by the core Link::getCategoryLink() method.

To identify the problematic entry, you can add a quick dump inside the module’s sitemap method:

```php
// inside modules/gsitemap/... getCategoryLink()
dump($category_id);

$category = new Category((int) $category_id['id_category'], (int) $lang['id_lang']);

if (empty($category->id_category)) {
    dump($category);
    die;
}
```

When you try to generate the sitemap, the loop will stop on the problmatic category i.e. the one missing its language entry (or not properly loaded from the database).
