### ISSUE TITLE
PDF generation of OrderSlip generates an error if no product inside (orderslip concerns only delivrey fees)

### ISSUE THREAD

**Issue by pibrom** [PrestaShop/PrestaShop#36209]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a credit slip is generated, but concerns only delivery fees, the PDF generation of this credit slip generates an issue :

> PrestaShop\PrestaShop\Core\Util\Sorter::natural(): Argument #1 ($array) must be of type array, null given, called in classes/pdf/HTMLTemplateOrderSlip.php on line 169
[TypeError 0]

I modified the HTMLTemplateOrderSlip.php on line 169 like this  : 

```
        $order_details = [];
        $order_details = $this->order->products;
        if (!empty($order_details)) {
            // Sort products by Reference ID (and if equals (like combination) by Supplier Reference)
            $sorter = new Sorter();
            $order_details = $sorter->natural($order_details, Sorter::ORDER_DESC, 'product_reference', 'product_supplier_reference');
        }
```

### Steps to reproduce

1. Generate an credit slip with only delivery fees
2. generate associated PDF

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.0

### Your company or customer's name goes here (if applicable).

Romaric PIBOLLEAU - RP2I

**Comment by paulnoelcholot** [comment]
Hello @pibrom,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by ytilotti** [comment]
@paulnoelcholot i's a bug. When create a slip, PS 8.1.6

**Comment by pibrom** [comment]
Hello.
I perfectly understand That.
There's nothing in my message to suggest that I need help with the error I've encountered. How did you come to the conclusion that I was looking for help?
I detected a bug in the generation of credit slips, and I fixed it. I also used Github to post the bug, and I took advantage of the opportunity to propose the correction.
On my version of Prestashop, the bug is fixed. I'm going to switch my fix to the override to avoid it being overwritten in a future update of the Prestashop core. You're free to do what you like with it.
I haven't made a pull request, because I don't know how to do it.

Best regards 😉.

**Comment by quasiperfect** [comment]
hi @paulnoelcholot 

Can you tell us what part of this report is considered invalid? I think it is a valid bug report, which happens to me also. 

It's a bug in the prestashop code, in `classes/pdf/HTMLTemplateOrderSlip.php`, in the call to `Sorter::natural` method, which happens only for refunds that don't contain products (which only contain shipping fees).

You can easily replicate:
1. create an order with products and shipping fees.
2. create a refund for the shipping fees only.
3. try to download the order slip pdf and you will get this error:
![image](https://github.com/user-attachments/assets/41fd2702-2caa-435f-8cce-3c4cd5e05252)

Please reopen this ticket.

Thank you.

Later edit: this bug is solved by this commit: https://github.com/Prestashop/PrestaShop/commit/e4fea7479422e3b167b7f037e83d1eb2b554f590.

@paulnoelcholot please ignore my request to reopen the bug request. i didn't know about the commit at that time
