### ISSUE TITLE
[UI] Price management from the range and zone Part 2

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#36260]
**US**

I want to set the price depending on the range and the zone.

**Specs**

![Image](https://github.com/PrestaShop/PrestaShop/assets/43613217/a964961b-6774-4e5e-975b-e884e7001d99)

Once the ranges are saved, a list of zones is displayed containing all the ranges with an empty input. Depending on the configuration, either price or weight metrics are displayed, along with the currency or weight metrics. 

If the ranges or zones are updated, then the list of range/zone is also updated. The value is kept if the range min and max stay the same even if the range position changed.

Max 4 ranges per row displayed.

Once the form saved the value are persisted.

**Responsive**

![Image](https://github.com/PrestaShop/PrestaShop/assets/43613217/b93f6925-319f-47d2-af5f-bba734f42d4f)

**Design**

https://www.figma.com/design/QlgjdPJHkpTZ8NSgLa4qzr/Carrier-page?node-id=1-1913&t=dxi5Fx4de7sqiuT1-0

**Comment by MatShir** [comment]
Blocked by https://github.com/PrestaShop/PrestaShop/issues/36259

**Comment by Hlavtox** [comment]
@amine-O @jolelievre Hi, I think we can simplify this page a bit.

1) There is no need to have separate zone input on the top, it can just be a button "Add zone" under the prices.
2) Shipping locations can be just one input name and then the zones next to it. It would save some space and make it look like any other form type.

![refacto](https://github.com/user-attachments/assets/33f1c403-0de5-4308-a9f5-96f8829ca692)

3) `Add range` button should be called `Change ranges`, because where do you remove a range?
4) I think we could siplify the price input just making it a table. It would fit on all screens, you don't have to repeat the input labels etc. Isn't it much cleaner? And takes up less space then the boxes. :-)

![ranges](https://github.com/user-attachments/assets/5b3f9215-f82c-40a1-8c85-ff0c48f06ba6)

WDYT @kpodemski

**Comment by ShaiMagal** [comment]
I prefer simplicity. So @Hlavtox proposal looks better for me.

**Comment by jf-viguier** [comment]
nice suggestions @Hlavtox 👍

**Comment by Hlavtox** [comment]
@jolelievre Do you think it can be implemented like this? :-)

**Comment by jolelievre** [comment]
We've shared the feedback and we are waiting for an answer from the designers, to be continued 😉

**Comment by kpodemski** [comment]
> We've shared the feedback and we are waiting for an answer from the designers, to be continued 😉

Could they maybe come here on GitHub to discuss this?

**Comment by Progi1984** [comment]
@PrestaShop/ux-team ?

**Comment by jolelievre** [comment]
Hi, we performed and UX review with @prestascott that mixes some of his suggestions and some of @Hlavtox suggestions.

Here's a video that presents the current state of the page, which is much simpler and the places of elements feels more intuitive:
[Carrier • Prestashop carrier.webm](https://github.com/user-attachments/assets/3eb6bb65-a3da-4551-aabb-5eb5c2999406)


@prestascott can you tell me if it's ok for you?

**Comment by Hlavtox** [comment]
@jolelievre @prestascott Looks awesome guys! :-) Few last suggestions!

In that section, we have zones, ranges and prices. And it's named "Zones". Do we add "Shipping prices" label next to the price boxes?

![Snímek obrazovky 2024-08-14 101232](https://github.com/user-attachments/assets/16e18b32-0e2b-42b6-8dcc-7cfedc96b604)

Not sure about the location of this button, doesn't it feel a bit weird that it's next to the Zones input? No idea where to put it though, maybe @prestascott would have some idea?

![Snímek obrazovky 2024-08-14 101340](https://github.com/user-attachments/assets/0f94e039-2ea2-45fd-b06e-ae1c4582dc3d)

**Comment by prestascott** [comment]
Hi everyone,

- No need to keep "Shipping prices" label since it’s right under the input, it’s quite understandable already. Also, when the user adds a zone, it immediately appears as a card
- The best solution is to be able to edit the ranges directly in each card zone so user can create ranges for a specific zone without implying the other zones. I agree that it feels weird but it’s weirder when the button is between both rows because it feels that it’s not related to any components... For now, my only suggestion is to keep the button as it is on the screenshot, maybe change the wording to “Edit price ranges” so at least we keep the “price” wording because we removed the label “Shipping prices”. 

Wdyt?

**Comment by Hlavtox** [comment]
@prestascott 

> No need to keep "Shipping prices" label since it’s right under the input, it’s quite understandable already. Also, when the user adds a zone, it immediately appears as a card

Yeah, but the whole section is about setting a _shipping prices_, not about _zones_ only. So I think that `Shipping prices` would be more appropriate, if you want to keep only one label.

> The best solution is to be able to edit the ranges directly in each card zone so user can create ranges for a specific zone without implying the other zones. 

Yep, but due to legacy reasons, it must be kept the same for each zone. It would be a BC break and no idea what else it would break.

> I agree that it feels weird but it’s weirder when the button is between both rows because it feels that it’s not related to any components... For now, my only suggestion is to keep the button as it is on the screenshot, maybe change the wording to “Edit price ranges” so at least we keep the “price” wording because we removed the label “Shipping prices”.

I think that `Edit ranges` is good. 👍

As I wrote above, you could save some space by not displaying the tags. You already see the zones you selected in the boxes, no need to have it again. Then you could have just two buttons - `Add or remove ranges`, `Add or remove zones`.

![tags](https://github.com/user-attachments/assets/32945f44-acd4-4b8a-964c-5208d094857d)
