### ISSUE TITLE
Rounding error in Prestashop invoice 8.1.5. Mismatch by cents

### ISSUE THREAD

**Issue by portimafia** [PrestaShop/PrestaShop#36308]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I updated approximately a month ago to Prestashop 8.1.5 and I see that there are errors in the invoice. It seems that the taxes are not added correctly, possibly due to a rounding error in PrestaShop. I have tried changing the types of rounding but the one that works best is the rounding on each line although there is always a deviation of some cents. I would please appreciate it if you could help me solve it since I have updated precisely to avoid the errors of previous versions of Prestashop. I attach a screenshot of the invoice in which the imbalance can be seen.
I take this opportunity to comment that the base price field appears but only for some items. It should appear for all or none although the base price that appears is not correct.
Nothing related to invoices or taxes has been changed to cause this error.
I work with 2 decimals and have tried other types of rounding but nothing works correctly.
![Capturadepantalla2024-05-29183127 jpg 8f97509f285d963742287cea2bdd60e8](https://github.com/PrestaShop/PrestaShop/assets/14858624/e5a25bd1-4f85-4b45-b947-e19c01664b1b)

### Expected behavior

Prestashop should correctly calculate taxes on invoice

### Steps to reproduce

When placing the order on the website the problem occurs, you get a miscalculated invoice

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.2

### Your company or customer's name goes here (if applicable).

Juanma

**Comment by SharakPL** [comment]
The issue is much bigger when you use multiple currencies on your shop and the order is not in the default one. The differences there can rise to very big numbers. Order totals should be a simple sum of values of each product line in the cart. Instead it's being counted separately from each product's tax excluded price and only rounded up in the end. It makes total price very precise but at the same time makes it differ from the sum of products in the order.

> I take this opportunity to comment that the base price field appears but only for some items. It should appear for all or none although the base price that appears is not correct.

And do you have base prices set in each of these products? Some users tend to leave the base price at 0 and only set a price impact in the product's combinations or a unit price only.

**Comment by portimafia** [comment]
Hello, thanks for answering.
I only use one currency, it is the only one active in my store, the euro.
I have base price for all products. Attached screenshot of Prestashop Store Manager.
I don't understand why this base price is shown only for some products and also not the actual base price. Would it be possible to eliminate the base price field from the invoices? Since it appears bad unless it is not seen.
I have created 2 groups of clients in addition to the ones that Prestashop brings by default. These two groups of customers have category discounts applied. I don't know if these discounts can create some kind of error in the Prestashop configuration.
Regarding taxes, they are correctly configured. Where could the error come from?
Thanks again.
![Captura de pantalla 2024-06-05 171643](https://github.com/PrestaShop/PrestaShop/assets/14858624/2f966c87-eeda-4d6c-8005-0f58005404c6)

**Comment by cruftex** [comment]
There are fundamental errors in the way taxes are calculated ever since. Most likely, this was just not noticed by you before, or, the previous orders just did not trigger it. It depends on several factors, but roughly, the more cheap products are on the invoice, the more likely the calculation will become off by a cent. I was analysing the problem a while ago. Here is the wrap up:

https://github.com/PrestaShop/PrestaShop/discussions/32969

**Comment by florine2623** [comment]
Hello @portimafia ,

We are aware of this issue, it is already in our debug backlog. You can find the EPIC with all related issues here : https://github.com/PrestaShop/PrestaShop/issues/19445

I will close your issue to avoid clogging the backlog.

Thank you

**Comment by portimafia** [comment]
Thanks, I will wait for an update that can correct this problem.
