### ISSUE TITLE
error out of memory when doing sales and order statistics in prestashop (re-again)

### ISSUE THREAD

**Issue by quimSTM** [PrestaShop/PrestaShop#36517]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi!

First of all, please @florine2623, do not close the topic without reading the entire text and taking it into account. The tests you have done are without data and the solution you gave of "it will be a hosting error" cannot be because it happens on various websites installed on various hostings, with different versions of Prestashop and various PHP. 
If you test what I say with the parameters that I say, with data on the web, you will have the error that I detail.

When I want to see sales and order statistics for 1 year ( you must have 700 or more orders in the last year to take the test), an Out of memory error appears. It is an error that the web browser shows, I know, but it happens with Chrome, Edge, Firefox... and it happens with different versions of PrestaShop like ps 1.7.8 or ps 8.1.1, and it happens with various versions of php from 7.1 to 8.1. It also happens on websites installed on different hostings, I know this because I work in a company with various clients who use PrestaShop and who have **different versions of PrestaShop, PHP and different hostings**.

To reproduce the problem go to the Statistics menu > Sales and orders > 1 year
It also happens with 6 months...
![hot_to_get_stats_error](https://github.com/PrestaShop/PrestaShop/assets/174600204/0c8f67a5-cd03-4c9e-a306-09b61baeff1f)

### Expected behavior

See the statistics for the period of 1 year, or the period you want without errors

### Steps to reproduce

1 - Go to Stats > Stats
2.- Go to Sales and Orders,
3.- you must have 700 or more orders in the last year to take the test 
4.- Click button "Year-1" and wait ...
5.- the browser shows an Out of memory error

### PrestaShop version(s) where the bug happened

from ps 1.7.8 to ps 8.1.1

### PHP version(s) where the bug happened

php 7.4.33 & php 8

### Your company or customer's name goes here (if applicable).

Software Textil Maresme

**Comment by quimSTM** [comment]
@florine2623 If you don't want to help, you can pass the case on to one of your colleagues, **but don't close it without reading.**

**Comment by matks** [comment]
@quimSTM I'm going to answer to avoid you opening a 4th issue 😄 

PrestaShop is php-based ecommerce CMS. It runs on your server, using CPU, memory, server resources. Like any other software, if you start accumulating a lot of data you will start to experience slowness. This is logical : if there is more data to load, search, filter, group, it takes more CPU and memory to handle it.

Some people handle the problem by upgrading the server hardware go have more memory, CPU and file storage.
Some people handle the problem by working on their data, chunking it, archiving old data now useless.

(And there are other possibilities like porting data into an ERP...)

Although the code of PrestaShop could be optimized to push further the limit where a solution is needed, it will be limited at some point.

I want to clarify something: even if we don't close the bug, it does not give any guarantee it will be fixed. The only person who can guarantee this problem of yours will be fixed is you, whether or not this bug report is opened or closed.

If you find that issue is critical for you, and it's important to have it fixed ASAP, then you can *invest* into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. And you could share the fix (be it code or infrastructure or tips) with everyone -- that's what the open source spirit is all about.

The people who work on the PrestaShop project decide what issues they want to fix depending on their own priority: some people are interested in bugfixes, others in features, others (like you) in performance optimization, others in developer tools... but everyone works on what is important to them.

So what I am saying is: whether or not this bug report is closed or opened will not condition if someone fixes it. Only you can. So insisting on keeping that bug report open will not resolve anything.

**Comment by kabeer95** [comment]
@quimSTm hey i checked you are stuck with your problem from days , as it's a open source project you will have to hire yourself someone to solve your issue . 

I understand the problem i can fix it for you and get the things rollig as you wants . 

let's get into contact to discuss further . 

Email: roonie.wood01@gmail.com 
whatsapp : +447456309448
linkedin : https://pk.linkedin.com/in/kabeer-a-19167788
