### ISSUE TITLE
Autoupgrade : ps_linklist an exception in FO when upgrade from 1.7.4.0 ~ 1.7.4.4 to 1.7.8.11 with php 7.1

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#36572]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After an upgrade (1.7.4.0 -> 1.7.4.4), the ps_linklist trigger an error after an upgrade

![Capture d’écran de 2024-07-18 14-29-28](https://github.com/user-attachments/assets/a33c3670-00ce-4bbb-bce1-6b6e450dd550)

### Expected behavior

No error

### Steps to reproduce

1- Install 1.7.4.0 on php 7.1 (For example)
2- Upgrade to 1.7.8.11
3- Go to FO
See the error

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by nesrineabdmouleh** [comment]
The exception is displayed also with 
PS 1.7.5.0 ~ 1.7.5.2 after upgrade to 1.7.8.11 on php 7.2
PS 1.7.6.0 ~ 1.7.6.9 after upgrade to 1.7.8.11 on php 7.2

**Comment by AureRita** [comment]
Hi @nesrineabdmouleh ,

Thank you for your report, I reproduce the issue with PrestaShop version 1.7.5.1

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

FYI : I know that this issue seems the same than this [one](https://github.com/PrestaShop/PrestaShop/issues/29700) 
but currently, the other issue is about a no possibility to upgrade the module after the update of the shop. 
Here the issue is about the non upgrade of the module during the update of the shop @PrestaShop/squad-seamless-upgrade 

Thanks

**Comment by Quetzacoalt91** [comment]
With the incoming PR https://github.com/PrestaShop/autoupgrade/pull/850, the migration is now applied properly and the FO is working as expected.

```
Checking updates of module ps_linklist...
Module ps_linklist update files (2.1.5 => 5.0.5) have been fetched from https://api.addons.prestashop.com/?id_module=24360&method=module&version=1.7.8.11.
Content of archive /var/www/html/**admin_folder**/autoupgrade/tmp/ps_linklist.zip is extracted
(1/4) Applying migration file upgrade-3.0.php.
(2/4) Applying migration file upgrade-4.0.php.
(3/4) Applying migration file upgrade-5.0.php.
(4/4) Applying migration file upgrade-5.0.5.php.
31 modules left to update.
```
