### ISSUE TITLE
Be able to disable a combination of a product

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#36589]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

You cannot disable a combination of a product, you can only delete it.
This function does not exist?

### Expected behavior

Be able to disable a combination of a product
This function does not exist?

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @alfonsolr09 ,

You can use a module for that. 
Example : https://addons.prestashop.com/en/combinaisons-customization/17711-enable-disable-a-combination-import-csv.html

I'll close your issue as it is not a bug.
Thanks!

**Comment by alfonsolr09** [comment]
It should be in the core of PrestaShop, it is a function that a product without combinations has so a product with combinations should have it too.

**Comment by kpodemski** [comment]
@alfonsolr09 

if you want to see it in the core, you will have to implement it yourself

**Comment by alfonsolr09** [comment]
In other words, it is an open source project, but do you not accept my implementation proposal for the public project?

**Comment by alfonsolr09** [comment]
In other words, it is an open source project, but do you not accept my implementation proposal for the public project?

**Comment by kpodemski** [comment]
@alfonsolr09 

that's not how it works

you are free to suggest whatever improvements you want to see in the software, but that doesn't mean that everything you suggest will be implemented, either by the core team or by the community

regarding your suggestion, in my opinion, it's been like that for over 15 years, introducing the switch for enabling/disabling combinations impacts entire ecosystem of modules, integrations, etc., you are one of the few people who ever suggested that + there are workarounds like the mentioned module

why should the project invest time in your suggestion instead of, for example, improving the performance, cart rules or something else that is regularly mentioned by users?
