### ISSUE TITLE
Loading orders page takes 30 seconds (37400 oders in the dataabse)

### ISSUE THREAD

**Issue by zenplayx** [PrestaShop/PrestaShop#36704]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have Prestashop 8.1.7 installed and working on VPS server.
I performed manual data migration from Prestashop 1.6.1.24 to Prestashop 8.1.7
I carefully followed the steps from this documentation :
https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/migration/
Database contains more than 37,400 orders.

It takes a lot of time to display the orders page (more than 30 seconds).
After that, when I want to display the "quick preview" for an order, it takes another 30 seconds.

See debug informations :
<img width="1464" alt="Capture d’écran 2024-08-13 à 17 29 29" src="https://github.com/user-attachments/assets/1e4d4467-f6e1-4a8f-8882-5d6fb78d8a3c">

I try to find this issue on the Internet. I found that someone got the same problem as me, and I perfomed what I told me to do :

Open the file **\src\Core\Grid\Query\OrderQueryBuilder.php**

Find : 
`$qb->addSelect('(' . $this->getNewCustomerSubSelect() . ') AS new');`

And change to :
`$qb->addSelect('IF((SELECT so.id_order FROM ps_orders so WHERE (so.id_customer = o.id_customer) AND (so.id_order < o.id_order) LIMIT 1) IS NOT NULL, 0, 1) AS new');`

And curiously, it works perfectly well.
Of course this is a workaround, and I would like to maintain the Prestashop with the latest release, and do not want to modify this code for every new release.

Thank you for your support.

### Steps to reproduce

Click on "Orders" to display orders (pagination : 50)

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

**Comment by paulnoelcholot** [comment]
Hello @zenplayx,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by Hlavtox** [comment]
@zenplayx The query you provided is the old one from 1.6.1.24. If it's faster, we can change it. 👍 

But I would like some other people to try it also.

**Comment by Hlavtox** [comment]
Oh, we actually have the same issue here - https://github.com/PrestaShop/PrestaShop/issues/30206

Caused by https://github.com/PrestaShop/PrestaShop/pull/26221

**Comment by ShaiMagal** [comment]
We have customer with more than 100 000 orders and no problem with loading... (our hosting openservis.cz) - PS 8.1.x

**Not sure, maybe it will be have impact on performance only on slow hosting servers @Hlavtox ?**

**Comment by zenplayx** [comment]
For your information.
I did a complete new installation of my hosting environment, with identical settings. The problem seems to have completely disappeared. It's been 10 days now that I no longer have the problem. Maybe it was due to a database failure or corruption.

**Comment by kpodemski** [comment]
Thanks for the confirmation @zenplayx

**Comment by dens-svg** [comment]
I have Prestashop 8.1.3 installed.
I performed data migration from Prestashop 1.6.1.5 to Prestashop 8.1.3

Database contains more than 400,000 orders.

It taked a lot of time to display the orders page (more than 10 seconds). The request took 9s.
It doesn't work for me.

I found a dirty solution and it's not compatible with multistore but the problem was so embarrassing...
I modified on the file \src\Core\Grid\Query\OrderQueryBuilder.php that :
Line 152 :
//  ->leftJoin('o', $this->dbPrefix . 'shop', 's', 'o.id_shop = s.id_shop')
Line 96 : 
->addSelect('os.color, o.payment, \'Your_store_name\' AS shop_name')

Curiously, after that, the request takes 0,01s.

It's ugly, but it works, if you have a greater solution...

**Comment by bpodwinski** [comment]
Same problem! With 18,000 orders, it took 43 seconds to load the page on the latest version of Prestashop 8.2.

I modified the getNewCustomerSubSelect function:


**Before: use SQL COUNT method, COUNT iterates through all rows, result 43s env**

    /**
     * Returns the subquery defining if a customer is new or not
     */
    private function getNewCustomerSubSelect(): string
    {
        return $this->connection
            ->createQueryBuilder()
            ->select('IF(count(so.id_order) > 0, 0, 1)')
            ->from($this->dbPrefix . 'orders', 'so')
            ->where('so.id_customer = o.id_customer')
            ->andWhere('so.id_order < o.id_order')
            ->setMaxResults(1)
            ->getSQL()
        ;
    } 

Fix by @Hlavtox [https://github.com/PrestaShop/PrestaShop/issues/27232#issuecomment-1006692117](https://github.com/PrestaShop/PrestaShop/issues/27232#issuecomment-1006692117)
**After: with if condition and limit 1, result 4.4s env**

    /**
     * Returns the subquery defining if a customer is new or not
     */
     private function getNewCustomerSubSelect(): string
    {
        return $this->connection
            ->createQueryBuilder()
            ->select('IF((' . 
                $this->connection->createQueryBuilder()
                    ->select('so.id_order')
                    ->from($this->dbPrefix . 'orders', 'so')
                    ->where('so.id_customer = o.id_customer')
                    ->andWhere('so.id_order < o.id_order')
                    ->setMaxResults(1)
                    ->getSQL() . 
                ') IS NOT NULL, 0, 1)')
            ->getSQL();
    } 

**Another solution with EXISTS, result 4.7s**

    /**
     * Returns the subquery defining if a customer is new or not
     */
    private function getNewCustomerSubSelect(): string
    {
        return $this->connection
            ->createQueryBuilder()
            ->select('IF(EXISTS(' . 
                $this->connection->createQueryBuilder()
                    ->select('1')
                    ->from($this->dbPrefix . 'orders', 'so')
                    ->where('so.id_customer = o.id_customer')
                    ->andWhere('so.id_order < o.id_order')
                    ->setMaxResults(1)
                    ->getSQL() . 
                '), 0, 1) AS new')
            ->getSQL();
    }

My Prestashop, which is causing issues, is the result of a migration from PS 1.7.7 to 8.2. I’m not sure if the problem is due to the migration itself or because the migration script may have missed adding some SQL indexes.

Anyway, COUNT is not suitable for checking if a customer has already placed an order because it scans all matching rows without stopping, even if it finds one. This creates unnecessary load, especially when only the existence of an order is needed, not the total count.

**Comment by Hlavtox** [comment]
@kpodemski @ShaiMagal It seems to be a really common problem, maybe it's related to database engine and version?

I have this column deleted for years, so I don't really know the "wild" regarding this issue. :-)))

**Comment by zenplayx** [comment]
@kpodemski @Hlavtox @ShaiMagal @bpodwinski Unfortunately, after 3 months of good operation, the problem has just reappeared, without having made any configuration changes on the website or on the server. It takes more than 40 seconds to display the orders.

![Image](https://github.com/user-attachments/assets/2d5df390-d79c-4204-901e-6b1a667b0bff)

Again, I have to change the query in `\src\Core\Grid\Query\OrderQueryBuilder.php` as I did in my first message, and it works well.
Very mysterious ...

By the way, I do not know if it is normal that I have duplicate "config" and "__construct" in the debug mode informations.

**Comment by githubjonny** [comment]
I've just run into this same issue on my site after migrating from 1.7 to 8 using a migration module. 

Editing:

Open the file \src\Core\Grid\Query\OrderQueryBuilder.php

Find :
$qb->addSelect('(' . $this->getNewCustomerSubSelect() . ') AS new');

And change to :
$qb->addSelect('IF((SELECT so.id_order FROM ps_orders so WHERE (so.id_customer = o.id_customer) AND (so.id_order < o.id_order) LIMIT 1) IS NOT NULL, 0, 1) AS new');

instantly solved the problem (27 seconds down to 1).

My question is does anyone know if :
1) There is an official way to solve this issue as the GitHub states "Not Planned".
2) The change listed above has any side effects etc 

@zenplayx I'm assuming you haven't seen any issues / side effects from the change?
