### ISSUE TITLE
Modules not update

### ISSUE THREAD

**Issue by C55-IT** [PrestaShop/PrestaShop#36701]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In our prestashop store we have installed modules made by prestashop and other suppliers, I see that many modules installed have more recent versions available in the addons but in the backoffice of the shop there are no updates for these modules, given that we have not activated the "Prestashop marketplace in the backoffice" module because it slows down the backoffice considerably, i would like to know if it is normal not to see these updates and if there is something we can do to install the updates without necessarily installing the "Prestashop marketplace in the backoffice" module, which every time it is uninstalled generates an error on the server... Thanks

### Expected behavior

Updating the modules visible in the backoffice

### Steps to reproduce

Check the backoffice to see the installed modules but without seeing any available updates that however are available in the prestashop addons, updates visible only by installing Prestashop marketplace in your backoffice.

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1.29

**Comment by kpodemski** [comment]
Hello @C55-IT 

Without the `ps_mbo` module, you'll only see updates for native modules like `ps_wirepayment` or others that are bundled inside the default PrestaShop distribution.

Regarding errors with `ps_mbo` and uninstallation, if you use PrestaShop 8.0.2, since this version, a lot of things have been optimized to work better that are related to modules installation and uninstallation, consider upgrading core to PrestaShop 8.1.7.
