### ISSUE TITLE
Popup to explain Hummingbird for new shops

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#36727]
Integrate a warning popup when the theme is enabled to warn about bootstrap with a link to devdoc for more details

**Comment by Hlavtox** [comment]
Why specifically for hummingbird? Any theme could be using any framework. Changing a theme will completely mess up your front office, it should not be done by an inexperienced user.

Problem that doesn't exist IMHO.

**Comment by matks** [comment]
@Hlavtox The pop-up aims to explain to a merchant, that has been using Classic Theme and themes built similarly to Classic for years, what is this new theme "Hummingbird" he might have never heard about, and to also put the link to the documentation there.

> Why specifically for hummingbird? Any theme could be using any framework.
Because Hummingbird, just like Classic, is going to become a "Default theme for PrestaShop" one day. It will be "the theme installed by default" in PrestaShop and this is a very special place.

The need for this pop-up cames from @kpodemski , he's very experienced with how merchants approach themes, I think we can trust him on this 😉

**Comment by kpodemski** [comment]
@Hlavtox 

> Any theme could be using any framework.

We don't write about the 0.01% chance of somebody deciding to do that, but about a real scenario in which we decided to release a new theme with changes that will lead to problems with third-party solutions if they are not adapted.

Also, my idea was to base it on a special flag available in the theme.yml, the subject that we've already discussed @Hlavtox @matks - so, it is not theme-specific, but this change is driven by Hummingbird.

> Changing a theme will completely mess up your front office, it should not be done by an inexperienced user.

That is also **false**. You probably haven't worked with paid themes too often, but believe me, a lot of them work quite well straight after enabling the theme in the back office. Since they are based on Classic, third-party solutions display fine on them most of the time.

**Comment by Hlavtox** [comment]
@kpodemski On one hand, you agree with me that Prestashop is not a tool to be installed by a non experienced merchant, on the other hand, you want to implement a message "This theme is using different framework, your shop can be ugly or not work". I don't understand.

Shop developer doesn't need these messages, changing a theme is not a thing that a shop manager does. And if he does, he does it on a test repository, fixing everything that doesn't work.

**Comment by matks** [comment]
> @kpodemski On one hand, you agree with me that Prestashop is not a tool to be installed by a non experienced merchant, on the other hand, you want to implement a message "This theme is using different framework, your shop can be ugly or not work". I don't understand.

The message is not "This theme is using different framework, your shop can be ugly or not work"

The message is "Hola! This new default theme is using a different framework than the one used for at least 5 years, **we are changing a standard**, please read the documentation we have written to fully understand what's going on" 😉

**Comment by kpodemski** [comment]
@Hlavtox 

If I'm not wrong, you weren't there when PrestaShop changed a theme between PrestaShop 1.6 and 1.7, maybe if you were, you'd understand this suggestion better :D

**Comment by Hlavtox** [comment]
Well, I was. :-) Most modules are using something_16.tpl and something 17.tpl, but still ugly as hell :D

Anyway, if you really want to do a message like this, do it universal, so there is nothing hardcoded in the core. 👍

**Comment by kpodemski** [comment]
@Hlavtox 

I think it could be integrated into the theme's code, but I'm not sure if we can afford to spend too much time on this one.

The most important thing is to communicate to the user that Hummingbird is new, and the ecosystem may not be ready for it right away.

**Comment by Hlavtox** [comment]
> I think it could be integrated into the theme's code

You check the theme YML for some message, but that message would need to be translated somehow etc.

> but I'm not sure if we can afford to spend too much time on this one

Well, I am surprised that you came with it, I think that there are more important things to resolve for Hummingbird, like hardcoded classic on many places.

> The most important thing is to communicate to the user that Hummingbird is new, and the ecosystem may not be ready for it right away.

There are two kinds of shops/people:
A) Those that buy million modules on Addons, install them and have no problem with their JS being X megabytes and loading million sliders, libraries, jquery libraries. Most shops using Prestashop.
B) Those with a proper agency, that make their own clean customized TPL and have no problem Hummingbird being different framework. And they are probably not even using some public slow modules.

For A), I think we are naive if we think that Leo, ETS and simmilar high quality developers would do it properly.  :-D Few lines of CSS and it will be done. Unless Addons teams manually check code quality of each module?

**Comment by kpodemski** [comment]
@Hlavtox 

> Well, I am surprised that you came with it, I think that there are more important things to resolve for Hummingbird, like hardcoded classic on many places.

My POV is that we shouldn't spend too much time on this popup, so it fits what you mentioned ;)

Regarding hardcoded "classic", the question is if that's really a problem if classic is still a default theme so that Hummingbird is treated as any other "third-party" theme. Translations should be all good in that case.

> For A), I think we are naive if we think that Leo, ETS and simmilar high quality developers would do it properly. :-D Few lines of CSS and it will be done. Unless Addons teams manually check code quality of each module?

We can't save the world, but let's try to do our best. ;) I think we should learn from the past and minimize the effect of a new theme on the ecosystem. I'm 100% sure that there are people who make a living by working with PrestaShop, that will download PrestaShop, try to enable Hummingbird, and don't care. The thing is that such communication is also a help for module developers who will need some time to adjust their solutions. In an ideal world, devs should adjust their solutions ASAP, but we don't live in the ideal world, and having a chance to reply, "Yes, I know about Hummingbird, but as you probably have seen in PrestaShop back office, it's a new theme, and we need to adjust our solutions" sounds like a good move to have a better rapport with them.

> You check the theme YML for some message, but that message would need to be translated somehow etc.

Yes, that's why it sounds more like something that should be rendered on the view level with a translatable phrase, but only based on the flag from the .yml whether to display it or not.

**Comment by BenTen** [comment]
If this theme has so much warning and seems not ready for the actual ecosystem, why to include it so fast?

**Comment by Hlavtox** [comment]
@BenTen Well, I don't know either. Hummingbird should have been a new start for a clean future. Now, it just reskinned all the nonsense the current `classic-to-core` relation has.

Examples:
- Terrible cart action implementation, error messages.
- Core weirldy updating parts of the templates in a way, where some modifications are just impossible. For example, I can't remove quantity input and add to cart button for out of stock products, because of how the core.js expects the input to be there.
- CSS and JS for all pages and native modules merged into one bundle.

**Comment by kpodemski** [comment]
@BenTen 

How do we prepare the ecosystem for a theme if it's not released? We have to release it so that the ecosystem can adapt.

**Comment by BenTen** [comment]
> @BenTen 
> 
> 
> 
> How do we prepare the ecosystem for a theme if it's not released? We have to release it so that the ecosystem can adapt.

To be honest, I don't know. I feel rlz the theme to everyone too fast, it's just a chance to get a bad image of Prestashop.
Shop manager will try to install (even if there is a red message in the middle of the screen) and just see (or not) a theme not compatible with module.

And then a lot complain, increase of customer service for dev of module to explain the problem is not directly the module, etc.

Seems the same scenario of ps 1.7 rlzed too early without compatible payment method.

There is an experimental part for experimental feature in PS 8, seems a better place for this theme.

**Comment by kpodemski** [comment]
@BenTen 

Hummingbird has been used for a base for paid themes already, so it's been _battle-tested_ for some time already, that's one thing. Another thing is that changes are less impactful than they were for 1.6 -> 1.7 when introducing a new theme. 

Also, it's not that we rush things with Hummingbird. It was announced two years ago, and if we want to see it as a default theme in PrestaShop 10, in my opinion, we have to move forward and release it.

> And then a lot complain, increase of customer service for dev of module to explain the problem is not directly the module, etc.

And that's a good thing because module developers have to adapt :D

**Comment by BenTen** [comment]
Understood.

> And that's a good thing because module developers have to adapt :D

In the real life, module developers will say "I don't care, my module works but you use non standard theme, I will do something when I won't have choice to do something" that's the real life of addon.

But I understand it's a problem of dev not a problem of theme.

**Comment by matks** [comment]
> In the real life, module developers will say "I don't care, my module works but you use non standard theme, I will do something when I won't have choice to do something" that's the real life of addon.

You are right, but our actions are limited here.

In PrestaShop 10 the Classic theme will be gone. Only Hummingbird will be in the shop. I guess most module developers will wait for PrestaShop 10 to be released before doing the work.

But we have to do it right on our side
- with a deprecation policy
- with a clear information about what's happening
- with a documentation easily accessible for users

And then ... how users (module developers and merchants) behave is out of control but we gave them all the cards to do things right.

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/36731
