### ISSUE TITLE
Webservices not reflecting changes

### ISSUE THREAD

**Issue by AftabZ20** [PrestaShop/PrestaShop#36744]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I followed the documentation of the prestashop web services for creating a product. Im currently making a custom API in node js to create a product along with Product Images, quantity and associated data. According to the documentation, there were separate API for updating the quantity of the product just created. But it doesn't seem to reflect on the prestashop's admin panel yet it is still giving success response. moreover, the condition attribute of the product is told to be writable but gives error when I try to assign it a value

### Expected behavior

I want that the product quantity and condition update as well, multiple images are also uploaded from my side but I can only see 1 image.

### Steps to reproduce

1. Call the Create Product API
2. Some writable attributes give error when try to assign it a value
3. To update the quantity, use stock availability API
4. Gives success response but quantity not reflected

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

Node 20.15.0

**Comment by ingridusta** [comment]
Hello @AftabZ20, 

According to this documentation https://www.prestashop.com/forums/topic/451883-how-do-you-use-the-webservice-api-to-increase-physical-stock/#comment-3133427, it is not a bug. You have to modify the quantity by using <stock_available instead of <products>.

In case you need the dev doc, here is were to get it https://devdocs.prestashop-project.org/8/webservice/tutorials/create-product-az/#create-the-product.

Thanks
