### ISSUE TITLE
Generate automatically a public documentation for the new admin API

### ISSUE THREAD

**Issue by ibahloul-ps** [PrestaShop/PrestaShop#36928]
# Context
- The documentation of the back office API should be publicy available on [the developer documentation](https://devdocs.prestashop-project.org/). (Note: in the Admin API section once this PR is merged https://github.com/PrestaShop/docs/pull/1860)
- Only the "native" endpoints, not those added by the merchants, whose documentation should be accessible only by authenticated users (#36929).
- This documentation must be manually updated when a new version is released (core and/or the module)
- Spike for the automation in order to evaluate the complexity (half day max)

## Technical details
- We need to integrate the [Swagger UI](https://github.com/swagger-api/swagger-ui) in the devdoc site, this UI is generated based on a JSON Open API file that can be generated by the core, the JSON should be persisted statically in the dedcos site
- To update the devdoc Swagger content we just need to update the json file, this should be done via a Github action that runs everyday, once a day, it can checkout the 9.x branch from the core and generates the JSON file (there is an endpoint accessible in the BO, maybe a CLI command would be easier to use to generate this JSON), it can then updates the docs content and commit/push it when it was modified

**Comment by matks** [comment]
I feel like this is over-thinking

<img src="https://imgs.xkcd.com/comics/the_general_problem.png">

Instead of having a github action that runs every day, checkout the code, installs prestashop, then extracts the Swagger file, copy it into the devdocs, and commit all of this... maybe we can simply do the copy-paste manually everytime we release a minor/major version, which is once per year?

A GitHub Action must be maintained. It must evolve together with the codebase, the environment where it is run, the technology it uses. I think the automation of this task is not cost-effective

**Comment by matks** [comment]
Morever if you "plug" the CI on a branch then when a developer modifies the branch, it'll update the devdocs automatically.

But there is only 1 doc for PS 8, one doc for PS 9. If we modify a endpoint in PrestaShop 8.2.3 because of a bug, then people using PrestaShop 8 will see the Swagger documentation as it is `on the 8.2.x branch` not as it is inside their software

Suggestion to keep it half-automated ;)

- make sure the JSON Swagger file can be generated by a CLI command
- however do perform the copy-paste manually when we release a new version (like we do when we write devdoc pages like https://devdocs.prestashop-project.org/8/modules/core-updates/8.0/#notable-changes) this way we fully control how the doc is being published

**Comment by jolelievre** [comment]
@matks most of the modification of this doc won't come from the core but from the module, so it should be much more recurrent than once a year At least once we really start to invest in the missing endpoints...

This could be a CI that is launched in both the core and the modules but since there are two potential sources of modification I thought a unique cron on the doc repo would do the job

Generating this manually is doable, but it means we need to remember it, assigned someone to it and so on We are recently trying to automatize as much as possible of our release process so this operation should not be an exception, this way we don't forget about it and we don't have to worry about it in a corner of our heads either

**Comment by jolelievre** [comment]
About the versions, there won't be an API doc for 8.2 because it doesn't include this feature, so it will only be for PrestaShop 9 for now The CI should update the doc for the branch 9 only, when we'll have a branch 10 then we can add a matrix so that two different JSONS are generated for each branch (even though they should be quite similar for a while)

Most of the changes will not come from the core but from the module anyway, so if a shop is missing some endpoints it means it should mostly update the module Regarding this we should check If it's possible to add some extra data in this doc so that we can see which version of PrestaShop + the module was used to generate it

**Comment by matks** [comment]
OK after discussing with @jolelievre we found out we did not want the same thing

- I wanted simply to be able to see, in the devdocs, for each new minor/major version, what endpoints are available so people can see the progress and the diff
- Jonathan wanted developers to be able to use the devdocs page as a replacement because [it won't be available publicly on shops](https://github.com/PrestaShop/PrestaShop/issues/36929)

As we did not wanted the same thing we disagreed on the level of effort to put into this topic, we disagreed on whether or not the suggested solution was relevant or overkill.

I now agree with the suggestion of @jolelievre because I consider `developers should be able to use the devdocs page as a replacement because it won't be available publicly on shops` is a good thing
