### ISSUE TITLE
One click upgrade never works

### ISSUE THREAD

**Issue by Youkapi22** [PrestaShop/PrestaShop#36949]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since 9 years that we use Prestashop, One click upgrade has never worked properly.
This time again we get this incomprehensible error message :
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 922851503

Varnish cache server

This is really boring.
What do you suggest ?

### Expected behavior

Launch the upgrade to get the last Prestashop version and avoid this repetitive error message : Jeton (token) invalide

### Steps to reproduce

Click on 1 Click upgrade button

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

1

### If your bug is related to a module, specify its name and its version

1

### Your company or customer's name goes here (if applicable).

YOUKAPI

**Comment by kpodemski** [comment]
Hello @Youkapi22 

I suggest looking at what lies under the 503 error because it means something went wrong. You mentioned that you use Varnish. Did you deactivate it before the upgrade? 

In 15 years of working with PrestaShop, I've used this module hundreds of times. Most of the time, if there were issues, they were related to the environment and third-party solutions, not the module itself.

I must admit it's pretty shocking that you didn't solve this problem for 9 years and now you report it here, saying that you are bored :)

**Comment by M0rgan01** [comment]
Hello @Youkapi22 

We would need more information to understand the error and the context of it.

What was the destination version? What was the PHP version? Do you have the application logs? 

Were third-party modules activated and/or modified the application's token management?

**Comment by ga-devfront** [comment]
I am sincerely sorry to hear that you are having a problem with the module. Remember that this project is open source and open to any contribution. However, we have been actively working for several months so that the module improves significantly, we take into account ALL user feedback.

I will add to what @M0rgan01 said that it would be good to also give us the version of the module used as well as the logs if there are any (at what stage does the error occur?)

**Comment by Hlavtox** [comment]
@Youkapi22 Interesting that I upgraded all of my about 20 stores with no issues using this module. :-)

**Comment by Youkapi22** [comment]
@kpodemski kpodemski 
I don't now where to deactivate varnish

**Comment by Youkapi22** [comment]
@M0rgan01 M0rgan01
From 1.7.8.5 to the last one

**Comment by Youkapi22** [comment]
@ga-devfront 
@Hlavtox 
What is pretty shocking for me is that it must be "one click" 
I'm not a IT developer
"Error 503 Backend fetch failed - Backend fetch failed - Guru Meditation: - XID: 922851503 - Varnish cache server"
is chineese for me... 
This is not acceptable that the error message is non understandable.
Each time since 9 years, we get an error message with this stupid module...
I'm really angry about it.
This is the only one in my back office that makes problem but the most important.
If it was an apple product, you would never have an "Error 503" This is microsoft method.
I left Microsoft products to Apple fo this reason a lot of years ago.
On my Apple products, upgrades are automatics during the night. That's great.
This is what I wait from Prestashop since 9 years.

**Comment by Hlavtox** [comment]
@Youkapi22 

> What is pretty shocking for me is that it must be "one click"
> I'm not a IT developer

I agree, the thing is that Prestashop is so diverse, so expendable in so many ways, that there is an infinite amount of possibilities, and even bringing it to 99% success rate is a huge achievement.

> I'm really angry about it.
> This is the only one in my back office that makes problem but the most important.

I understand, but this is some specific issue to your environment. Not saying the environment is wrong, but we have to find WHY it happens. Can you try to contact your server admin or hosting company and tell them to deactivate Varnish?

> If it was an apple product, you would never have an "Error 503" This is microsoft method.
> I left Microsoft products to Apple fo this reason a lot of years ago.
> On my Apple products, upgrades are automatics during the night. That's great.

Yes. The exact reason why I use an iPhone, it just works. :-)

**Comment by Youkapi22** [comment]
@Hlavtox Thanks fo the advice. I just opened a ticket to OVH. 
Yesterday, I opened also a ticket at Prestashop support but they closed it and send me to this forum.
Strange.

**Comment by Quetzacoalt91** [comment]
As said previously, the error is returned by Varnish running between you and your shop. He is responsible of displaying these "Microsoft-styled" errors. OVH should be able to help but the error is likely displayed because the autoupgrade module took too much time to answer.

You didn't tell us where the error occurred exactly so I'll cover several things:

* The loading of the configuration page can take some time, because the module always checks the permissions recursively in several folders among other checks. This will be improved on the version 7 with the new UI.
* Some steps of the backup, update and restore can timeout as well. This is a topic we've started having a look at, and one of the steps got its first improvement with https://github.com/PrestaShop/autoupgrade/pull/894.
* The module will be renamed as "Update assistant", this is planned for version 7 with https://github.com/PrestaShop/autoupgrade/pull/777.


Eventually, OVH will disable Varnish and the module may finally work for you. Otherwise, waiting for the v7 should help.
I'm closing this issue, feel free to reopen it when you get more details to share to reproduce your issue.

**Comment by Youkapi22** [comment]
@Quetzacoalt91 
We cannot wait the version 7
It is urgent to make this upgrade because we get everytime an other error message "Jeton Token invalid". (see attachement)
The upgrade should solve this error.
![Capture d’écran 2024-09-20 à 09 05 11](https://github.com/user-attachments/assets/1729247f-dceb-4d47-a337-19fa0b3a60c4)

**Comment by kpodemski** [comment]
@Youkapi22 if it's urgent, then I suggest you hire a technical person who can do an upgrade for you

also, I'm pretty sure that this problem with a token error won't disappear :) Problems with token may also be related to environment configuration, especially since all the time errors messages do mention about Varnish...

**Comment by Youkapi22** [comment]
@kpodemski 
Hire a technical person is precisely what I want to avoid. Each time we have to make an upgrade of a Prestashop back office version, we have to pay for it to Prestashop. THIS IS NOT NORMAL. One click upgrade has to work properly without any outside intervention. On a free Apple upgrade, I never have a Varnish error. All is foreseen in the upgrade.
It is not normal that I have to contact you and then OVH. This is really boring...
I perfectly agree to pay for a module that I buy but not for a technical BUG in Prestashop. They make pay the customers for their errors ???

**Comment by Quetzacoalt91** [comment]
We heard you and gave you several solutions.
If you cannot wait for the incoming version 7 of the module, then you hire someone to have it immediately and hassle-free (https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/).

**Comment by kpodemski** [comment]
@Youkapi22 

remind me: how much did you pay for PrestaShop, and how much did you pay for Apple products? :)

What is not normal is that you still don't understand that the problem you encounter is something specific to your environment, it's an open source software that you can freely download, so coming here and demand fixing situation for your unique scenario is not a way to go
