### ISSUE TITLE
Autoupgrade : Some modules are disabled after upgrade to major or minor version

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#36958]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Some modules are disabled after upgrade of PS [1.7.0.6 ~ 1.7.8.2] with CLI

![Capture d’écran de 2024-09-18 18-04-44](https://github.com/user-attachments/assets/530bc91e-511e-4119-af81-4e49604f01d6)

### Expected behavior

The upgrade is :heavy_check_mark: 

### Steps to reproduce

1- Install PS 1.7.5.0
2-Upgrade to minor or major version with CLI
3- See the error

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.1 - 7.2 - 7.3 - 7.4

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by Hlavtox** [comment]
@Quetzacoalt91 @M0rgan01 Is it possible that two module upgrade methods are colliding?

**Comment by Quetzacoalt91** [comment]
That's precisely what's happening. In the process running with the CLI, we run all modules upgrade in the same context. If two of them have the same function name to run, the module cannot proceed with the second one in the list because the method name is already defined in memory.

The fail safe has been existing for a long time and prevents a Fatal error, this "new issue" is reported because new modules get their migration files executed since https://github.com/PrestaShop/autoupgrade/pull/850 has been merged.


The only improvement we think about is applying namespaces on-the-fly, but this would require the use of `eval()` and I've never been fond of it.

**Comment by Hlavtox** [comment]
@Quetzacoalt91 Quick fix would be to just upgrade one module per one ajax call. Or the eval, as you suggested. 🤔

**Comment by Quetzacoalt91** [comment]
There is one module by ajax call already, but the issue applies on CLI where all modules are run in the same command.
