### ISSUE TITLE
Imposible to preview product on multilanguage shop

### ISSUE THREAD

**Issue by bogdanpricop** [PrestaShop/PrestaShop#36959]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have installed a clean Prestashop, in English - ID=1. 
I have added the Romanian language in the International -> Localization -> Languages - ID=2.
I have added a product.
Then disabled the English Language (ID=1) and open the Catalog -> Products.
Add a new "Test product" -> Save the product -> Press Preview

You will get a 403 error.

### Expected behavior

Expected to be able to add the product and preview it.

### Steps to reproduce

I have installed a clean Prestashop, in English - ID=1. 
I have added the Romanian language in the International -> Localization -> Languages - ID=2.
I have added a product.
Then disabled the English Language (ID=1) and open the Catalog -> Products.
Add a new "Test product" -> Save the product -> Press Preview

You will get a 403 error.

### PrestaShop version(s) where the bug happened

8.0 - 8.1

### PHP version(s) where the bug happened

8.1.29

### Your company or customer's name goes here (if applicable).

Amondia.ro

**Comment by florine2623** [comment]
Hello @bogdanpricop ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
