### ISSUE TITLE
Autoupgrade : A notice is displayed in dashboard page related to psaddonsconnect module after upgrade with CLI

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#36969]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A notice is displayed in dashboard page related to psaddonsconnect module after upgrade with cli
upgrade : 
- 1.7.3.0 ~ 1.7.3.4 to minor
- 1.7.2.0 ~ 1.7.2.5 to minor
- 1.7.1.0 ~ 1.7.1.2 to minor
![Capture d’écran de 2024-09-19 12-04-25](https://github.com/user-attachments/assets/3f1c084f-95f5-4de3-9ff1-8b36847a93ed)

### Expected behavior

No error

### Steps to reproduce

1- Install 1.7.3.0 on php 7.1
2- Upgrade to 1.7.8.11 with CLI
3- Login and see the error

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by Quetzacoalt91** [comment]
These errors are only related to the module `psaddonsconnect` because they can be found after a fresh install as well. 

You can see the history in https://github.com/PrestaShop/PrestaShop/issues/13675, with the release of 2.0.0 fixing this issue.
In the case of the UI tests, I have changed the compatibility range of the buggy versions to make sure there are not distributed anymore.
