### ISSUE TITLE
Cannot have because of faulty code [Exception code 0].

### ISSUE THREAD

**Issue by GusA44** [PrestaShop/PrestaShop#37031]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Standard refund not possible with default code [Exception code 0].
![Sans titre](https://github.com/user-attachments/assets/1565a2dc-3a52-42b5-a90d-0347cdfab363)

### Expected behavior

Resolved the error to generate the credit note and refund my customer.

### Steps to reproduce

Steps to follow to reproduce
1.go to order
2.click on “standard refund
3.select all items to be refunded and check price
4.check “Refund buyer via Web Services SystemPay” box
5.click on “Standard refund”.

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by ibahloul-ps** [comment]
Hello @GusA44,

This issue seems to be related to a module, please reach out the developper of this module in order to fix it.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
