### ISSUE TITLE
No datas in visits data in BO

### ISSUE THREAD

**Issue by Mel-meel** [PrestaShop/PrestaShop#37137]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I have a problem with the Backoffice dashboard, i have no monthly visits :

![Capture d’écran 2024-10-14 110238](https://github.com/user-attachments/assets/53a9a5bb-9e35-47f3-bfad-89603acb99cf)

When I switch to yearly statistics, we have some visits but only in spring and summer. The shop in still online and we have commands so we should have visits :

![Capture d’écran 2024-10-14 110308](https://github.com/user-attachments/assets/d6904fd8-07d1-4fd4-b757-ee56bd8ad751)

As fund in my research, i tried to reinit the statsdata module but nothing, visits still 0.

### Steps to reproduce

1. Visit the shop
2. Go in BO
3. Check the monthly visits data

### PrestaShop version(s) where the bug happened

1.8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

statsdata

**Comment by florine2623** [comment]
Hello,

I was not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Mel-meel** [comment]
Hi, thank you for trying.

Best regards,

Mel
