### ISSUE TITLE
CCC should be enabled by default after PS installation

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#37145]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After clean PS installation we enabled by default filesystem cache, but not CCC for JS/CSS/Apache. I don't see any reason for that, I think, this should be enabled everytime.
![Untitled](https://github.com/user-attachments/assets/648785b2-0e14-45b5-88e7-da1d9c006808)

### Expected behavior

CCC should be enabled by default. (CSS, JS, Apache)

### Steps to reproduce

1. Install PS9
2. Go to "Advanced Parameters" -> "Performance"
3. scroll down to "CCC (Combine, Compress and Cache)"

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

**Comment by florine2623** [comment]
ping @PrestaShop/product-council ,

What do you think about this ?

Thanks!

**Comment by ibahloul-ps** [comment]
Hello @ShaiMagal,
Thanks for your feedback!

> I don't see any reason for that, I think, this should be enabled everytime.

Maybe @jolelievre or @matks do? 🤷

**Comment by Hlavtox** [comment]
I agree, I have never seen a case where it doesn't work. And @ShaiMagal hosting hundreds of prestashop installs would know if it made issues. :-)

**Comment by matks** [comment]
I don't have the answer because this was done a long time ago, but I can make a guess.

As some themes and some modules, are not compatible with CCC, it's probably safer to keep it turned off. A merchant who does now know what it does and tries to install a theme/module that is not compatible with CCC might be confused as to why a caching system, default ON, does not work out-of-the-box.

**Comment by kpodemski** [comment]
@matks since CCC is about having multiple CSS or JS files compiled into one, I'm not sure how the module could not be compatible with this mechanism - there might be some corner cases, of course, but I don't think I've ever heard of any 🤔 Maybe I remember one where 0 was changed to 0px or something like that, and that produced some issues, but that was a very specific case.

**Comment by matks** [comment]
I just made a guess about why it's like this, I did not say I agree about this choice 😉

**Comment by ShaiMagal** [comment]
I think we should enable all 3 CCC by default :)

**Comment by Hlavtox** [comment]
@ibahloul-ps This can't produce any issues, other than bad module css being badly processed, which I also never see.

**Comment by florine2623** [comment]
Fixed in https://github.com/PrestaShop/PrestaShop/pull/37260
