### ISSUE TITLE
MAX_EXECUTION_TIME

### ISSUE THREAD

**Issue by lomba55** [PrestaShop/PrestaShop#37347]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello community, I am trying to upgrade my current prestashop 1.6.14 to 8. Right now I have PHP 5.6. Before the upgrade I have to follow a checklist. I still have the same problem for max_execution_time (I provide a screenshot). I tried changing the value to 60sec (but the site was giving me problems and wouldn't go) and I tried changing the value to 90/300sec but it still gave me problems. How can I solve this?

### Steps to reproduce

1. Going to "1-click update" module
2. view the checklist

### PrestaShop version(s) where the bug happened

1.6.14 to 8

### PHP version(s) where the bug happened

5.6

**Comment by ShaiMagal** [comment]
I think you should contact any expert. 1.6 isn't supported anymore... longer time...

**Comment by Quetzacoalt91** [comment]
Hi @lomba55,

I think this issue is related to this one: https://github.com/PrestaShop/PrestaShop/issues/36106
Each folder on your shop is checked to make sure the module has sufficient permissions to make changes during an update or a restoration. Depending on the number of sub-folders in your filesystem, this can take a long time and even trigger on some environments the timeout error.

The workaround is to move your `img/` folder to another place while the update is done, then move it back to its original place.
Is it planned to improve this check with the incoming v7 of the module by running it at a specific time of the update configuration process instead of each page load. But you would need to update to PrestaShop 1.7 first in order to enjoy it.
