### ISSUE TITLE
SEO product Optimization : delete categorie name

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#37428]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
PrestaShop has always had the bad practice of embedding category names in product URLs.
`{category:/}{id}{-:id_product_attribute}-{rewrite}.html`

### Expected behavior

It would be preferable, when installing PrestaShop, for the rewrite to be without the categories :
`{id}{-:id_product_attribute}-{rewrite}.html`

Provide a redirection line from URL anchors to new ones to avoid problems when updating.

### Steps to reproduce

SEO&URLs Tab

### PrestaShop version(s) where the bug happened

1.0.0 - 9.0.0

### Your company or customer's name goes here (if applicable).

Mediacom87

**Comment by venditdevs** [comment]
Why would you want that? companies like Google want a clean, readable URL. A  product URL with categories in it is not per definition bad. It is only bad when you make a trash of the URL so Google "does not understand" what's behind the URL.

We have webshops with a complete parent/child category URL structure and they are diong very, very well on SEO base. We also have webshops with no categories in the URL, so, for example domainname.com/product-name which are also doing great.

The structure of the URL is negligible, leave the structure of the URL a decision of the end user. 

Considering it as an option would be fine, but not standard.

**Comment by jeckyl** [comment]
Simply in cases where a product is moved from one category to another by default, or when the simplified URL of a category changes, as this crashes the product URLs miserably.

**Comment by venditdevs** [comment]
That's not true, as long as there's a product ID in the product section of the URL itself, it will not crash. It wil only result in a 404 if the category changes and the URL does not contain the necessary ID's.

**Comment by Multipage** [comment]
@jeckyl  what @venditdevs says is true. There is absolute no way this causes any problems when something changes. As long as there is a product ID in the URL Prestashop will find it and redirect the 'wrong' page to the 'correct' page.

The categoryname is needed. The product can be in multiple categories. Prestashop needs to know where  the user came from (breadcrumbs)  otherwise we get really unpredicted and unrealiable behaviour of Prestashop and thus bad user experience!

This change would bring 0 to SEO optimization.

**Comment by Hlavtox** [comment]
I agree, the category in the name is useless.

### Arguments
- Shorter URL, better URL - for readability, for QR codes, for storage.
- When you change default category of a product, URL changes. Yes, there is 301, but still, it harms SEO. It's enough that I have search console full of redirects because of EAN changes, that are in the URL.
- Prestashop doesn't need it to know where the user came from, it detects it from `$_SERVER['HTTP_REFERER']`.

So, for me, for **NEW INSTALLS**, it's a yes.

Ping @kpodemski @ShaiMagal

**Comment by kpodemski** [comment]
Typical SEO issue. One is in favor of it, one is against it.

I don't see any value in this change, and please don't treat it as a "bug" or call it "bad practice" without showing sources and evidence that it actually is.
