### ISSUE TITLE
Autoupgrade attempts to update non-installed modules, causing the upgrade process to fail

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#37445]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When updating Prestashop using the "autoupgrade" module, the system attempts to update modules located in the "modules" folder even if they are not actually installed.

I encountered this issue while updating a website that had the "ps_mbo" module in the "modules" folder, but the module was not installed.

The upgrade procedure fails to complete and stops at the step:

```
=== Step upgradeModules
Updating module ps_mbo...
Module ps_mbo has been successfully downloaded from Addons.
The content of the archive \prestashop_prova_aggiornamento\**admin_folder**\autoupgrade\tmp\ps_mbo.zip has been extracted 
(1/11) Applying migration file upgrade-2.0.0.php.
```
To complete the upgrade, I had to delete the module's folder, after which the procedure was successfully finalized.

In this case, the issue arises because the module update process cannot be completed as the module is not installed.
I believe the upgrade should only process modules that are actually installed.

The list of modules to be "upgraded" is retrieved here without verifying whether these modules are really installed:

https://github.com/PrestaShop/autoupgrade/blob/4ea36f0b3f668b54dddf775ed58dd54aec2542f9/classes/Task/Upgrade/UpgradeModules.php#L62-L75

![Image](https://github.com/user-attachments/assets/f21ea420-bbb5-45f1-8e8b-9c55d2f327ae)

I believe that here we should check if the module is actually installed.

https://github.com/PrestaShop/autoupgrade/blob/4ea36f0b3f668b54dddf775ed58dd54aec2542f9/classes/Task/Upgrade/UpgradeModules.php#L96-L103

### Steps to reproduce

1. Install autoupgrade module
2. Copy the ps_mbo module into the modules folder without installing it.
3. Perform the upgrade to the latest version of Prestashop.

### PrestaShop version(s) where the bug happened

8.x

### If your bug is related to a module, specify its name and its version

autoupgrade

### Your company or customer's name goes here (if applicable).

@codencode

**Comment by Hlavtox** [comment]
Ping @Quetzacoalt91

**Comment by Codencode** [comment]
In my opinion, it would be enough to check if the `$dbVersion` variable is set. If it isn’t, it means the module is not installed and therefore should not be updated.

```php

                if ($dbVersion !== '') {
                    $module = \Module::getInstanceByName($moduleInfos['name']);

                    if (!($module instanceof \Module)) {
                        throw (new UpgradeException($this->translator->trans('[WARNING] Error when trying to retrieve module %s instance.', [$moduleInfos['name']])))->setSeverity(UpgradeException::SEVERITY_WARNING);
                    }

                    $moduleMigrationContext = new ModuleMigrationContext($module, $dbVersion);

                    if (!$moduleMigration->needMigration($moduleMigrationContext)) {
                        $this->logger->info($this->translator->trans('Module %s does not need to be migrated. Module is up to date.', [$moduleInfos['name']]));
                    } else {
                        $moduleMigration->runMigration($moduleMigrationContext);
                    }
                    $moduleMigration->saveVersionInDb($moduleMigrationContext);
                } else {
                    $this->logger->info($this->translator->trans('Module %s is not installed, so it has not been updated.', [$moduleInfos['name']]));
                }
```


I have created the following PR.: https://github.com/PrestaShop/autoupgrade/pull/1036

**Comment by Quetzacoalt91** [comment]
This step has slightly changed since the last release, we should check the issue is still happening on the `dev` branch.

The list of modules you get in the Backlog only contains installed modules. This check is done earlier in the step, especially in the warm up.
-> https://github.com/PrestaShop/autoupgrade/blob/4be38a10d54b7073180778d7f6afd2bc0fd83023/classes/Task/Update/UpdateModules.php#L147

It calls this method `listModulesPresentInFolderAndInstalled()`: https://github.com/PrestaShop/autoupgrade/blob/4be38a10d54b7073180778d7f6afd2bc0fd83023/classes/UpgradeTools/Module/ModuleAdapter.php#L136-L170

It starts by getting all modules Supposed to be installed, meaning found in the table database. Modules are added in this table while installed:
https://github.com/PrestaShop/PrestaShop/blob/e50e10d052c7556ada1ce5d74db351aadc33231c/classes/module/Module.php#L432-L436
Then removed at uninstallation: https://github.com/PrestaShop/PrestaShop/blob/e50e10d052c7556ada1ce5d74db351aadc33231c/classes/module/Module.php#L843

So if ps_mbo ends in this list anyway, I would look for the reason instead hiding the issue with an additional filter in the middle of the process. Furthermore, the current behavior is actually to apply all the migration files if the version is not properly set.

Could you please check if there is a reference to `ps_mbo` in your `PREFIX_module` table before the update? If yes, that's the reason it is being updated.

**Comment by Codencode** [comment]
Hi @Quetzacoalt91 ,

I tried running the update with the "dev" version of the module, and indeed the issue does not occur.

I noticed there are some changes, so I believe the problem has already been resolved.

Anyway, I can confirm that the issue does not occur.

What should I do? Should I close this issue and the related PR?

Thanks!

**Comment by Quetzacoalt91** [comment]
We can close this issue knowing the issue will be solved on the next release.
On our side we plan testing the different processes on several environment prior the release of the v7 of the module, so we can expect finding this error is it still happen. And we will reopen it if that's the case.

**Comment by Codencode** [comment]
Ok,
I have conducted further tests and confirm that the issue occurring with version 6.2.0 of the module does not happen with the "dev" version.

One thing I noticed is that the system performs file backups even if the corresponding setting is set to NO, but this might be because the module is still under development.

@Quetzacoalt91 thank you!

**Comment by Quetzacoalt91** [comment]
Yeah as the interface is going to change, it is a known issue that will stay until the release.
Thanks for the feedback
