### ISSUE TITLE
Errors sentry 8.2.1

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#37490]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

in 1click Upgrade i can't change the channel to local folder
in Console i have 3 errors with Sentry 8.2.1, the screen not refresh

### Expected behavior

change the channel![Image](https://github.com/user-attachments/assets/61412991-2fb0-40d4-9fe0-2f889b1be443)
 from minor version to local folder with refresh screen

### Steps to reproduce

go to 1click upgrade V 6.2.0
change the channel from minor version to local folder
the screen don't refresh

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

1click upgrade V 6.2.0

**Comment by Quetzacoalt91** [comment]
Thanks, I've been able to reproduce the issue. A few comments about your issue:

* `versionNumberRegex` is the curlprit, one PR has been opened to fix this but was unfortunately never completed: https://github.com/PrestaShop/autoupgrade/pull/906
* Sentry is catching all the unhandled exceptions, that's why it appears as the script responsible of the error. While the error `versionNumberRegex` is from the update module, the two other ones are unrelated to it (We don't have any Vue application).
* The channel you're trying to use will disappear on the next major version, where only two options will remain: `online` and `local archives`. The `folder directory` seams easier to use, but because of the non-required XML file the module is unable to complete a proper update.

**Comment by Quetzacoalt91** [comment]
The fix to this issue has been included in the freshly release v6.3 of the module, update it and it should be good.
