### ISSUE TITLE
regenerate images

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/PrestaShop#37685]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Probably are you aware when you want to regenerate images, and you have a lot of products it takes so long, and freeze the server.

An idea or solution it would be add a queuing for this and for time consuming operations/actions.

I was testing it with 500 products store. I can not imagine what would happen when there were thousands of products.

### Steps to reproduce

NA

### PrestaShop version(s) where the bug happened

8.2

**Comment by florine2623** [comment]
Hello @adamus007p ,

I can suggest you to check the system requirements for V8 to make sure they match the configuration of your shop : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

Your issue is similar to : https://github.com/PrestaShop/PrestaShop/issues/21915

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by adamus007p** [comment]
@florine2623  it is not similar, it is finishing the thing is there is no queuing for this jobs which take a lot of time
