### ISSUE TITLE
[BO] Error when changing order statut

### ISSUE THREAD

**Issue by GuillaumeFaidherbe** [PrestaShop/PrestaShop#37724]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have an error when I want to change the status of an order.

[PrestaShopException code 23000] : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '64-29906-0-0' for key 'product_sqlstock'.

![Image](https://github.com/user-attachments/assets/af344c3a-e24f-4050-99da-02f74857b98a)

### Expected behavior

Hi,

I have an error when I want to change the status of an order.

[PrestaShopException code 23000] : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '64-29906-0-0' for key 'product_sqlstock'.

### Steps to reproduce

1. Go to BO
2. Change statut of order

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @GuillaumeFaidherbe ,

I cannot reproduce the issue as you can see :

https://github.com/user-attachments/assets/04f5e39a-45a3-467b-aa54-98aaf571f644


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Daaaaad** [comment]
Same error here on **PrestaShop 8.2.1**:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '14-183-0-0' for key 'ps_stock_available.product_sqlstock'
```

In our case the cause is clear: the order whose status we're changing contains a **product combination that was later deleted**. The order still references the old `id_product_attribute` (183) in `order_detail`, but that combination no longer exists in `product_attribute`. When we set the order to a status that updates stock (here "Delivered"), PrestaShop tries to write a `stock_available` row for that dead combination with `id_shop = 0, id_shop_group = 0` and collides with the unique key `product_sqlstock`.

Reproducible steps: order a product with a combination → delete that combination → change the order's status. The first such order goes through, the next one referencing the same deleted combination fails.
